[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 40 0 0][uf 3 1 1 0 0 1 0 0]Aww, it's so pretty! This is wonderful...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's beautiful.[e]
[uf 0 5 65278][uf 2 1]What next?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 40 0 0][uf 3 1 1 0 0 2 0 0]Yeah... I could look at this all night long.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 40 0 0][uf 3 1 1 0 0 3 0 0]Come on... You're ruining the mood.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 40 0 0][uf 3 1 1 0 0 4 0 0]Did you know they brought in a famous designer for these decorations?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 5 0 0]Here, I have a present for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 40 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 2 1 25 25]It's been a while since I've made something like this.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]（アイテム名）を受け取った。[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 7 0 0]I hope it tastes all right.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 8 0 0]Honestly, when I first met you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 9 0 0]I never thought we'd end up spending Christmas together like this.[n][uf 1 1][e]

[msg MSG_008_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 10 0 0]I was just so used to being all on my own.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 11 0 0]I'm only gonna tell you this because it's a special day, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 0 0][uf 3 1 1 0 0 12 0 0]I actually always dreamed of doing something like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 40 0 0][uf 3 1 0 0 0 13 0 0][uf 4 23 0 2 3 25 25]......[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 40 0 0][uf 3 1 1 0 0 14 0 0]I know that with everything going on, it's not exactly the time to be getting all warm and fuzzy...[n][uf 1 1][e]

[msg MSG_011_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 40 0 0][uf 3 1 1 0 0 15 0 0]But... one night couldn't hurt, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 40 1 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 0 0 0 0]Just for today... I want to be by your side.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I shared a tender moment with Yukari.[n][uf 1 1][e]

