[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 1 0 0]I'm using different beans today. I went to a coffee shop and bought some real ones this time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0]I made sure to store them in the fridge, and I only ground them right before brewing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 3 0 0]I also learned you need to be mindful of how hot the water is as well as how you pour it.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]You did a great job.[e]
[uf 0 5 65278][uf 2 1]How sure are you?[e]
[uf 0 5 65278][uf 2 1]It's gonna get cold.[e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Yes, I practiced with the cheaper beans from before since I can't afford too many of the expensive ones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 5 0 0]...Although it was hard to drink all that coffee, so I added a lot of milk and sugar.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]Well, I practiced with the cheaper beans from before since I can't afford too many of the expensive ones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]Although, this is the first time I'm brewing with these fancier beans. I wonder how it'll turn out...[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 159 65535 0 0][uf 3 1 1 0 0 8 0 0]Oh, sorry! You're right, coffee is best when it's hot and fresh![n][uf 1 1][e]

[msg MSG_013_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 9 0 0]Well then, let's drink, shall we? Cheers, [uf 4 1]-san![n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 10 0 0]Phew...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 8 3 25 25]It's still really bitter... So bitter...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 8 1 25 25]But it's not only that. I could actually taste some of the sweetness and richness this time.[n][uf 1 1][e]

[msg MSG_014_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]The beans and brewing technique can make a huge difference, huh? Oh, and the smell was great, too![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 14 0 0]I'm feeling a little nostalgic, actually...[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0]Thanks for joining me, [uf 4 1]-san. You can go on ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 16 0 0]I'm gonna practice a little more to try and get the hang of this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 17 0 0]Let's make some more if we ever get the chance.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 159 65535 0 0][uf 3 1 1 0 0 18 0 0]Oh...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 159 65535 0 1][uf 3 1 1 0 0 19 0 0]Uh, first I gotta use the bathroom...! I drank a lot while I was practicing today...[n][uf 1 1][e]

