[msg MSG_NOSCHEDULE]
[uf 0 5 65278][uf 2 1]Nothing in particular[n][uf 1 1][e]

[msg MSG_JOIN_0421]
[uf 0 5 65278][uf 2 1]Junpei joins SEES[n][uf 1 1][e]

[msg MSG_JOIN_0611]
[uf 0 5 65278][uf 2 1]Fuuka joins SEES[n][uf 1 1][e]

[msg MSG_JOIN_0721]
[uf 0 5 65278][uf 2 1]Aigis joins SEES[n][uf 1 1][e]

[msg MSG_JOIN_0808]
[uf 0 5 65278][uf 2 1]Koromaru joins SEES[n][uf 1 1][e]

[msg MSG_JOIN_0828]
[uf 0 5 65278][uf 2 1]Amada joins SEES[n][uf 1 1][e]

[msg MSG_JOIN_0902]
[uf 0 5 65278][uf 2 1]Aragaki rejoins SEES[n][uf 1 1][e]

[msg MSG_DIALY_0429]
[uf 0 5 65278][uf 2 1]Showa Day[n][uf 1 1][e]

[msg MSG_DIALY_0503]
[uf 0 5 65278][uf 2 1]Constitution Day[n][uf 1 1][e]

[msg MSG_DIALY_0504]
[uf 0 5 65278][uf 2 1]Greenery Day[n][uf 1 1][e]

[msg MSG_DIALY_0505]
[uf 0 5 65278][uf 2 1]Children's Day[n][uf 1 1][e]

[msg MSG_DIALY_0518_0523]
[uf 0 5 65278][uf 2 1]Midterms[n][uf 1 1][e]

[msg MSG_DIALY_0525]
[uf 0 5 65278][uf 2 1]Exam Results[n][uf 1 1][e]

[msg MSG_FULLMOON_0707]
[uf 0 5 65278][uf 2 1]Operation Day[n][uf 1 1][e]

[msg MSG_DIALY_0714_0718]
[uf 0 5 65278][uf 2 1]Finals[n][uf 1 1][e]

[msg MSG_DIALY_0720]
[uf 0 5 65278][uf 2 1]Marine Day[n][uf 1 1][e]

[msg MSG_DIALY_0720_0723]
[uf 0 5 65278][uf 2 1]Yakushima Vacation[n][uf 1 1][e]

[msg MSG_DIALY_0724]
[uf 0 5 65278][uf 2 1]Exam Results[n][uf 1 1][e]

[msg MSG_DIALY_0725]
[uf 0 5 65278][uf 2 1]Ending Ceremony[n][uf 1 1][e]

[msg MSG_DIALY_0727_0801]
[uf 0 5 65278][uf 2 1]Track Team Practice[n][uf 1 1][e]

[msg MSG_DIALY_0802]
[uf 0 5 65278][uf 2 1]Myouou Cup[n][uf 1 1][e]

[msg MSG_FULLMOON_0806]
[uf 0 5 65278][uf 2 1]Operation Day[n][uf 1 1][e]

[msg MSG_DIALY_0814]
[uf 0 5 65278][uf 2 1]Physical Examination[n][uf 1 1][e]

[msg MSG_DIALY_0810_0815]
[uf 0 5 65278][uf 2 1]Summer School[n][uf 1 1][e]

[msg MSG_DIALY_0816]
[uf 0 5 65278][uf 2 1]Summer Festival[n][uf 1 1][e]

[msg MSG_DIALY_0901]
[uf 0 5 65278][uf 2 1]Welcoming Ceremony[n][uf 1 1][e]

[msg MSG_FULLMOON_0905]
[uf 0 5 65278][uf 2 1]Operation Day[n][uf 1 1][e]

[msg MSG_DIALY_0919_0921]
[uf 0 5 65278][uf 2 1]Culture Festival[n][uf 1 1][e]

[msg MSG_DIALY_0921]
[uf 0 5 65278][uf 2 1]Respect for the Aged Day[n][uf 1 1][e]

[msg MSG_DIALY_0922]
[uf 0 5 65278][uf 2 1]National Holiday[n][uf 1 1][e]

[msg MSG_DIALY_0923]
[uf 0 5 65278][uf 2 1]Autumnal Equinox[n][uf 1 1][e]

[msg MSG_FULLMOON_1004]
[uf 0 5 65278][uf 2 1]Operation Day[n][uf 1 1][e]

[msg MSG_DIALY_1012]
[uf 0 5 65278][uf 2 1]Health and Sports Day[n][uf 1 1][e]

[msg MSG_DIALY_1013_1017]
[uf 0 5 65278][uf 2 1]Midterms[n][uf 1 1][e]

[msg MSG_DIALY_1019]
[uf 0 5 65278][uf 2 1]Exam Results[n][uf 1 1][e]

[msg MSG_FULLMOON_1103]
[uf 0 5 65278][uf 2 1]Operation Day[n][uf 1 1][e]

[msg MSG_DIALY_1103]
[uf 0 5 65278][uf 2 1]Culture Day[n][uf 1 1][e]

[msg MSG_DIALY_1117_1120]
[uf 0 5 65278][uf 2 1]School Trip[n][uf 1 1][e]

[msg MSG_DIALY_1123]
[uf 0 5 65278][uf 2 1]Labor Thanksgiving Day[n][uf 1 1][e]

[msg MSG_DIALY_1124_1127]
[uf 0 5 65278][uf 2 1]Career Experience[n][uf 1 1][e]

[msg MSG_DIALY_1214_1219]
[uf 0 5 65278][uf 2 1]Finals[n][uf 1 1][e]

[msg MSG_DIALY_1221]
[uf 0 5 65278][uf 2 1]Exam Results[n][uf 1 1][e]

[msg MSG_DIALY_1223]
[uf 0 5 65278][uf 2 1]Emperor's Birthday[n][uf 1 1][e]

[msg MSG_DIALY_1226]
[uf 0 5 65278][uf 2 1]Ending Ceremony[n][uf 1 1][e]

[msg MSG_DIALY_1231]
[uf 0 5 65278][uf 2 1]New Year's Eve[n][uf 1 1][e]

[msg MSG_DIALY_0101]
[uf 0 5 65278][uf 2 1]New Year's Day[n][uf 1 1][e]

[msg MSG_DIALY_0108]
[uf 0 5 65278][uf 2 1]Welcoming Ceremony[n][uf 1 1][e]

[msg MSG_DIALY_0111]
[uf 0 5 65278][uf 2 1]Coming of Age Day[n][uf 1 1][e]

[msg MSG_DIALY_0125]
[uf 0 5 65278][uf 2 1]Career Consultation[n][uf 1 1][e]

[msg MSG_DIALY_0131]
[uf 0 5 65278][uf 2 1]The Promised Day[n][uf 1 1][e]

[msg MSG_DIALY_0211]
[uf 0 5 65278][uf 2 1]National Foundation Day[n][uf 1 1][e]

[msg MSG_DIALY_0305]
[uf 0 5 65278][uf 2 1]Graduation Day[n][uf 1 1][e]

[msg MSG_DIALY_0308_0313]
[uf 0 5 65278][uf 2 1]Finals[n][uf 1 1][e]

[msg MSG_DIALY_0320]
[uf 0 5 65278][uf 2 1]Ending Ceremony[n][uf 1 1][e]

[msg MSG_DIALY_0321]
[uf 0 5 65278][uf 2 1]Spring Equinox[n][uf 1 1][e]

