[msg MND_000_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]Fuuka is working silently...[n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I tended the rooftop planters with Fuuka...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 3 1 6]I bet these taste really good when they're freshly harvested.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 3 1 6]Wow, they've gotten so big since we last saw them.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 3 1 6]The smell of the soil really makes it feel like we're growing something, doesn't it?[n][uf 1 1][e]

[msg MND_005_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I think that about does it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Shall we head back downstairs?[n][uf 1 1][e]

