[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30076 0 0]Let's see here... My name is Metis... And my nickname...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 4 23 0 1 4 25 25]My nickname?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Sister, do I have a nickname?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]"Li'l Sis."[e]
[uf 0 5 65278][uf 2 1]You're simply "Metis."[e]
[uf 0 5 65278][uf 2 1]I don't know...[e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30067 0 0]Oh, some of your friends call me that. I see, so it counts as a nickname...[n][uf 1 1][e]

[msg MSG_004_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30128 0 0]That's true! And there's nothing more special than your own name.[n][uf 1 1][e]

[msg MSG_005_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30059 0 0]Well, if you don't know, then I doubt anyone else would, either...[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30003 0 0]Hm, this next section is about... my role model.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Obviously, my sister.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]My favorite thing? Also my sister. And so is this one... And this one, and...[n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 11 52 65535 0 0]...Okay, all done![n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Good job.[e]
[uf 0 5 65278][uf 2 1]Was I the answer to everything?[e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30127 0 0]Oh, it was nothing, hehe.[n][uf 1 1][e]

[msg MSG_010_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30093 0 0]Huh? I don't... think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Well, I guess things just happen to turn out that way.[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]So... How far did you get? Are you already done?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]I'm still writing.[e]
[uf 0 5 65278][uf 2 1]Please give me a moment.[e]
[uf 0 5 65278][uf 2 1]Must I fill one out, too?[e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30103 0 0]Well, you're doing great, Sister![n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30111 0 0]Okay! I'll be patient and wait right here for you to finish.[n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30027 0 0]Of course you do! That's the whole point of this [uf 4 4 0 37 1 16789].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Also... I was hoping we could exchange them.[n][uf 1 1][e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]And that does it for the [uf 4 4 0 37 1 16789] exchange. Mission success![n][uf 1 1][e]

[msg MSG_017_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]I'm so happy we were able to carry out our own exchange...[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30110 0 0]I get this strange feeling whenever I receive something from you, Sister...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Like a sense of fulfillment whenever you gift me things or trust me with something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]It's hard to articulate it effectively, but I feel as if... As if my chest is swelling up—to the point it might just burst.[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]I think I understand.[e]
[uf 0 5 65278][uf 2 1]I'm afraid I don't follow.[e]
[uf 0 5 65278][uf 2 1]But from what...?[e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30046 0 0]You do?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Then you must have someone in your life who's just as important to you as you are to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]And that thought makes my chest feel even more full... It's overwhelming.[n][uf 1 1][e]

[msg MSG_021_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30050 0 0]That's okay. I'm actually not too sure what it all means, either.[n][uf 1 1][e]

[msg MSG_022_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30056 0 0]Hm... I don't really know, but whatever it is, I doubt it's something bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 0 1 1 25 25]After all, it feels so pleasant and warm... So it has to be good, right?[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Metis seems to be deeply[n]reflecting on her feelings...[n][uf 1 1][e]

[msg MSG_024_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30106 0 0]This is my new treasure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 11 52 65535 0 0][uf 4 23 0 1 11 25 25]I'll always cherish it and keep it safe. I hope you feel the same way with mine.[n][uf 1 1][e]

