[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]According to the records, the accumulated mass of Shadows split into several large ones that later dispersed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 3 0 0]These are the Shadows we've been encountering on nights when the moon is full.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 4 0 0]Maybe... that's why it's difficult to predict where they'll appear?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Wait a minute...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 6 0 0]If what you said is true, then why did our school turn into Tartarus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 7 0 0]Don't tell me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 8 0 0]Is it because that's where they conducted the experiment!?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Yes.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 10 0 0]Then those students who were hospitalized...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 11 0 0]It's just as you fear.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 12 0 0]It was a highly populated area, and the Kirijo Group had influence there. They could essentially do as they pleased.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]Port Island must have been the perfect location for them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 14 0 0]So yes, as you guessed, the experiment ten years ago was conducted at Gekkoukan High School.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 15 0 0]Just what are you trying to say here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 16 0 0]So that's the whole purpose behind SEES?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 17 0 0]We were dragged into all this just to clean up their mess!?[n][uf 1 1][e]

[msg MSG_008_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 17 2 2 0][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 18 0 0]You lied to us?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 0 0 0 19 0 0]......[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 20 0 0]And you knew too, didn't you, Sanada-senpai?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 21 0 0]You've both just been using us![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 22 0 0]Or do you not care, as long as you're the one who gets to do the fighting?[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 1 65535 0 0][uf 3 1 1 0 0 23 0 0]I never said anything like that![n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 1 65535 0 0][uf 3 1 1 0 0 24 0 0]I... have my reasons.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 25 0 0]Think what you'd like, but it was my decision not to share the information.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 26 0 0]I'm sorry.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 27 0 0]It was never my intent to deceive you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 28 0 0]Convincing you to join SEES was my highest priority.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 29 0 0]I know it may not be fair, but Shadows can only be defeated by Persona-users. We are the only ones who can fight.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 30 0 0]That's hardly the point![n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 31 0 0]I never had a choice either... It didn't matter if I wanted this power or not.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 32 0 0]I...[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 33 0 0]Mitsuru, that's enough.[n][uf 1 1][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Takeba-kun, it's only those in the past who are to blame.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]And they lost their lives as a result of what they did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]We're all in the same boat, here. None of us deserve the burden that's been thrust upon us.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 37 0 0]But that's...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 0 0 0 38 0 0]......[n][uf 1 1][e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]It's been ten years since the incident in question. No one knows why those Shadows suddenly returned.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]But now that they're here, we have the chance to find and destroy them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Do you realize what that means?[n][uf 1 1][e]

[msg MSG_022_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]What if I told you that the twelve Shadows are the cause of everything?[n][uf 1 1][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 1 65535 0 0][uf 3 1 1 0 0 43 0 0]You're saying if we defeat them all, Tartarus and the Dark Hour will disappear?[n][uf 1 1][e]

[msg MSG_024_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Exactly![n][uf 1 1][e]

[msg MSG_025_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]That's what I was going to tell you earlier. See, it's good news, isn't it?[n][uf 1 1][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 46 0 0]Can that really be true!?[n][uf 1 1][e]

[msg MSG_027_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]There's evidence to support it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]And this is where our true battle begins.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 49 0 0]Our true battle...[n][uf 1 1][e]

[msg MSG_029_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Regardless of what's happened in the past, we must fight to protect the people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]The Shadows are gaining strength. We can't afford to wait for them to strike first.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 52 0 0]Right.[n][uf 1 1][e]

[msg MSG_031_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]And there are still many mysteries surrounding Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]For instance, why did such a gigantic structure appear in the first place? The answers must be out there somewhere.[n][uf 1 1][e]

[msg MSG_032_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 55 0 0]Hm...[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]We must defeat the twelve[n]Shadows that started all of this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...In order to eradicate both[n]the Dark Hour and Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I must fight to protect everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Six of them remain...[n][uf 1 1][e]

