[msg MSG_000_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]From what I understand, Mitsuru has already given you the short version.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 2 0 0]Oh, yes...[n][uf 1 1][e]

[msg MSG_002_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, it's true. We adults are to blame.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]If I could've atoned for it with my life, I would have done so.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Now, I have no choice but to rely on you.[n][uf 1 1][e]

[msg MSG_002_5_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]What my father wanted to create with those monsters' power...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]It was a [uf 0 1 33]time manipulation device[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 8 0 0]That's what he was trying to do?[n][uf 1 1][e]

[msg MSG_004_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Imagine if you could control the flow of time, eliminate unwanted events before they occur.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]With such a device, you could shape the future to your liking.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 65535 0 0][uf 3 1 1 0 0 11 0 0]Damn, that's insane.[n][uf 1 1][e]

[msg MSG_006_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Unfortunately, under my father's direction, the research began to stray from its original goal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]In his later years, my father seemed to have only nihilism in his heart.[n][uf 1 1][e]

[msg MSG_006_5_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]In fact, his madness may have resulted from his struggle to break free from that.[n][uf 1 1][e]

[msg MSG_007_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]It's only natural that you want to know the truth. And it's my duty to tell you.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 5 65535 0 0][uf 3 1 1 0 0 16 0 0]What's this?[n][uf 1 1][e]

[msg MSG_009_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]This is the only existing footage of the accident, recorded by a scientist who was at the scene.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 18 0 0]...A video recording?[n][uf 1 1][e]

