[msg TRL_000_0_0 [Growing Vegetables]]
[uf 0 5 65278][uf 2 1][uf 4 8 421]You can leave vegetable seeds with Rafflesia's Paulownia Mall branch to have them grown for you.[n][uf 1 1][e]

[msg TRL_001_0_0 [Growing Vegetables]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Vegetables will grow while you explore the Abyss of Time. Once you return, check to see if they're ready for harvest.[n][uf 1 1][e]

[msg TRL_002_0_0 [Growing Vegetables]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Grown vegetables will provide energy for Aigis and the rest of the team. Try growing a variety of crops to aid in your exploration of the Abyss of Time.[n][uf 1 1][e]

