[msg TRL_000_0_0 [Combat Characteristics]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 4 8 0]You've unlocked [uf 0 1 2]Combat Characteristics[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Combat Characteristics]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 4 8 0]Combat Characteristics are passive effects that will automatically activate during battle. Your party members each have their own unique Combat Characteristics.[n][uf 1 1][e]

[msg TRL_002_0_0 [Combat Characteristics]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 4 8 0]Select STATS from the [uf 1 3 112] menu for further details on a party member's Combat Characteristics under Theurgy.[n][uf 1 1][e]

