[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maya's not logged in.[n][uf 1 1][e]

[msg MSG_001_0_0 [Instant Message]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]im running a lil late! ill brt, k? ^^;;[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Maya entered the area.[n][uf 1 1][e]

[msg MSG_003_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]i was on teh phone w/my mom =/ whenever we talk, its always the same[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]its like all she cares about is marrying me off to some dude ＞=/ whys it her problem?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Don't wanna get married?[e]
[uf 0 5 65278][uf 2 1]You'll need a boyfriend first.[e]
[uf 0 5 65278][uf 2 1]Let's plan our wedding, then.[e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]i jus dun wanna rush ok!? ＞_＜ maybe by 40 or sumthin[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Maya seems upset.[n][uf 1 1][e]

[msg MSG_007_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]i mean, WTF! everyone acts like a girl has to get married to be happy -_-;[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]im takin my time!!1 =/ there's no rush, yo.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Maya seems troubled.[n][uf 1 1][e]

[msg MSG_009_5_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]Half teh population is male, rite? i'll be fine.[n]＞=)   ＜---(playa)[n][uf 1 1][e]

[msg MSG_010_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0][uf 5 13 10 15 1]even w/o meeting me irl? :O take me, Tatsuya! \(^x^)/[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Maya seems happy.[n][uf 1 1][e]

[msg MSG_012_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]dun worry... ＞:D i still got it even at my age, lol *^_^*[n][uf 1 1][e]

[msg MSG_013_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]its sexist to think women can only be happy when theyre tied down. ~_~;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]the other nite, i got a lil drunky, and kinda passd out @ paulownia...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]then this old dude wuz like, "youll never get a man lookin like that!" ugh!![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i told him to stfu, dammit!! ＞=([n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]OTL ...sry, kinda got off topic. i guess im a lil tired =_=[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]but i do feel better now! xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]here tatsuya, this is for u ^^[n][uf 1 1][e]

[msg MSG_014_0_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]Maya used a Heal Potion on Tatsuya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But there was no effect...[n][uf 1 1][e]

[msg MSG_015_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]oh... guess your hp was already full... lmaonade[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]im trying to say thx for listening to all my bitching ;P[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I think Maya is opening up to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_017_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]yknow that old lamer I told u bout? he wuz hangin around paulownia so =_=[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]if you see him, don't be nice! ＞=/ i saw him on this weird tv show too, super creepy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]alrite, i better go pratice being a good housewife for tatsuya! ＜3[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned about a man from TV(?)[n]who visits Paulownia Mall at night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

