[msg MND_000_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]It's the first day of exams...[n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]It's the last day of exams...[n][uf 1 1][e]

[msg MND_002_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]The questions are just too easy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]My pen won't stop moving![n][uf 1 1][e]

[msg MND_003_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]All these questions look familiar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I did well![n][uf 1 1][e]

[msg MND_004_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]The last question was a little difficult...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I still feel like I did pretty good.[n][uf 1 1][e]

[msg MND_005_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I recognize these questions from class...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I can't seem to remember the answers...[n][uf 1 1][e]

[msg MND_006_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I don't understand the questions...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But there's nothing I can do about it now...[n][uf 1 1][e]

