[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 2 1 1 2]You better be ready... 'Cause I'll do whatever it takes to win![n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 2 2 1 5]Let both sides give it their all. No holds barred![n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0][uf 3 1 1 0 2 3 0 6]This is it... You can do it, Aigis![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 2 4 1 2]It's gonna take a lot more than that![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 5 52 65535 0 0][uf 3 1 1 0 2 5 1 2]Don't think it'll be so easy![n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 2 6 1 2]I'm not down yet... I won't go down![n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 2 7 1 5]You're strong... Just as expected.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 5 52 65535 0 0][uf 3 1 1 0 2 8 1 5]Impressive... But I'll fight to the bitter end![n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 3 1 1 0 2 9 1 5]Ha... There's a fire in your eyes. Let's see whose resolve burns brighter![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 2 10 1 2]Mitsuru-senpai![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 2 11 1 2]Gotta push past the pain... I'm still not done![n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 5 52 65535 0 0][uf 3 1 1 0 2 12 1 5]Yukari... Don't worry, I'll carry on your will![n][uf 1 1][e]

