[msg MSG_802_1_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 2 1 0 5]The enemy's attacks are growing stronger...[n][uf 1 1][e]

[msg MSG_802_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 0 0 0][uf 3 1 1 0 2 2 0 5]If you're being overwhelmed by the enemy's assault, protect yourselves by guarding.[n][uf 1 1][e]

[msg MSG_802_1_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 0 0 0][uf 3 1 1 0 2 3 0 5]When you guard, even if your weakness is struck, you can avoid being knocked down.[n][uf 1 1][e]

[msg MSG_802_1_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 0 0 0][uf 3 1 1 0 2 4 0 4]Try and make use of that in battle.[n][uf 1 1][e]

[msg MSG_802_2_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 5 0 5]The enemy's attacks are growing stronger...[n][uf 1 1][e]

[msg MSG_802_2_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 6 0 5]If you're being overwhelmed by the enemy's assault, protect yourselves by guarding.[n][uf 1 1][e]

[msg MSG_802_2_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 7 0 5]If you're guarding, then even if your weakness is struck, you can avoid being knocked down.[n][uf 1 1][e]

[msg MSG_802_2_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 8 0 5]Try and make use of that in battle.[n][uf 1 1][e]

[msg TRL_802_1_1]
[uf 0 5 65278][uf 2 1]By guarding against an enemy attack, you can halve damage received.[n][uf 1 1][e]

[msg TRL_802_1_2]
[uf 0 5 65278][uf 2 1]Furthermore, you will avoid being knocked down, even if your weakness is struck.[n][uf 1 1][e]

[msg TRL_802_1_3]
[uf 0 5 65278][uf 2 1]If an enemy is winding up for a powerful attack, or if you think your weakness will be targeted, try guarding to play it safe.[n][uf 1 1][e]

