[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Майко переживает за Камики...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Пойти в храм?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Пойти[e]
[uf 0 5 65278][uf 2 1]Не делать этого[e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Отправлюсь в храм.[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

