[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]It's Takeba. Are you awake?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Good morning.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Hello? Please answer the door, or I'm going to get in trouble![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Good morning. Did you sleep okay?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]I've been asked to show you the way to school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Are you ready to go?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, I'm ready.[e]
[uf 0 5 65278][uf 2 1]I can find it myself.[e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Great! Let's head out.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Uh... Didn't expect you to turn me down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]You don't want to risk being late on the first day, do you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]C'mon, hurry and get ready![n][uf 1 1][e]

