[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...I've been waiting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I finished my story and wanted to show it to you...[n][uf 1 1][e]

[msg MSG_001_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I was having a lot of trouble with the ending... but I finally figured it out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]After the alligator ate his friend, the bird, he cried and cried for a long time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]In fact, he was so sad... that he drowned in his own tears.[n][uf 1 1][e]

[msg MSG_001_3_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]His tears became a sparkling lake, around which grew beautiful flowers, and a tree that bore delicious fruit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]The other animals in the forest came there often to relax...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]But none of them knew the alligator had created it, or that he was gone.[n][uf 1 1][e]

[msg MSG_001_7_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]...The end.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]That's the ending I decided on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Even though the alligator didn't find meaning in his life, the residents of the forest did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]...They just didn't realize it.[n][uf 1 1][e]

[msg MSG_002_3_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]The meaning of my life isn't something I should spend my time on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]It's more about how I was able to affect others.[n][uf 1 1][e]

[msg MSG_002_7_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]So... for me, or you, or anyone... just simply existing gives our lives meaning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]People can't survive without help from others... We all depend on one another.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I don't know how to explain it, but... does that make sense?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]I still don't get it.[e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I'm glad...[n][uf 1 1][e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...That's what I've found to be the meaning of life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Perhaps you and others have different concepts of what it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 117 1 25 25]But, I hope someday you can understand.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]This is the notebook I wrote my story in. I've poured my heart and soul into it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I wanted to give you this... since you shared my final moments.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]DEV: Unused[n][uf 1 1][e]

[msg MSG_009_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Ah... My body feels lighter...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I'm so grateful to have met you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]It seems so insignificant, but maybe there was some meaning in it, for both of us...[n][uf 1 1][e]

[msg MSG_009_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Thank you... In the end... I'm glad that I was born...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I can sense Kamiki's tender feelings...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg SYS_011_0_0]
[uf 0 5 65278][uf 2 1]The Sun Social Link reached its maximum level! You can now fuse [uf 0 1 35]Asura[uf 0 1 27], the grand being![n][uf 1 1][e]

[msg MSG_012_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]I have to go now...[n][uf 1 1][e]

[msg MSG_013_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Maybe, someday, [uf 4 2]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]We'll meet again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I'd like that...[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]...With the notebook tightly in hand,[n]I decided to head back to the dorm.[n][uf 1 1][e]

