[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I see Maya.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]whoa, did u just get here? we signed on @ the same tiem![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]the weathers nice today huh? let's go outside! (＞' ')＞ ingame, duh[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]Traesto! ＆= ( ^o^)/[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Shinagawa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A gray-colored sky stretches[n]as far as the eye can see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A barren wasteland lies[n]before Tatsuya and Maya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maya is stretching.[n][uf 1 1][e]

[msg MSG_003_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]for an apocalypse, the air sure iz nice out here ;P[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]pshyeah right... it's just a game... we should go lvl or sumthing[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i'm so lazy irl tatsu... i havnt even gotten dressed or put on makeup T_T[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Maya stands at attention![n][uf 1 1][e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]AAARGH!!11;alksjf;alskdjfa;slkf im so pissed off rite now![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]Mr. E is such a stupid eh so bee!! t(-_-t)[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Who's Mr. E?[e]
[uf 0 5 65278][uf 2 1]Are you drunk again?[e]
[uf 0 5 65278][uf 2 1]Do you mean S.O.B.?[e]

[msg MSG_007_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0][uf 5 13 10 5 1]...tatsuya, u know too much now[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i shouldnt have mentioned his name, huh? ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]HAhahHhahHA! roflmao!!1 dun get me busted, k?  O=)[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Maya seems happy.[n][uf 1 1][e]

[msg MSG_009_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]wat do u take me for... you think im drunk 24/7 or sumthin?  -_-;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]im stressed, not drunk... o_O      O_o[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Maya seems upset.[n][uf 1 1][e]

[msg MSG_011_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 5 1]yesss, u get it!! wooooo! tatsuya and maya ftw! xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]we must be soulmates ya? hi five! (^ ^) /\ (^ ^)[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Maya seems very happy.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Maya is looking around.[n][uf 1 1][e]

[msg MSG_014_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]erm, there arnt that many players ne more. most of em left for that new mmo, CoW...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]there were alot of dupers an goldfarmers, but still... =/[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]its good tho cuz it lets us talk about personal things rite? ＞=P[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...maya IS a shy girl, u know... ::blush:: lol[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...see, Mr. E is a teacher whos kinda above me[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...oh noes! u cant figure out what my job is can u? O_o[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]A drunken master?[e]
[uf 0 5 65278][uf 2 1]Maya's a reporter, right?[e]
[uf 0 5 65278][uf 2 1]Are you a teacher?[e]

[msg MSG_016_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0][uf 5 13 10 5 1]well bein drunk does make me stronger =P[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...hah! i wish.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Maya is enjoying herself.[n][uf 1 1][e]

[msg MSG_018_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]...ok, im a teacher. surprised? xD[n][uf 1 1][e]

[msg MSG_019_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]thats in the GAME im talking about real life ._.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Maya seems disappointed.[n][uf 1 1][e]

[msg MSG_021_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]...ok, im a teacher. surprised? xD[n][uf 1 1][e]

[msg MSG_022_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0][uf 5 13 10 5 1]ya, ur smart O_O i knew u'd figure it out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]u get an A+ for reading comprehension today! lol  d-^_^[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Maya seems happy.[n][uf 1 1][e]

[msg MSG_024_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]welp... now u kno im a teacher xD[n][uf 1 1][e]

[msg MSG_025_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]hey! i just figured sumthing out o_O[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]when i complain to u, i feel better afterwards! xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]from now on we HAVE to party up together, k? promise!! ＞=I[n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]It seems Maya feels comfortable[n]talking to me about real life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_027_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]im so pumped, i think i'll clean teh bathroom xD ...its been 2 months o_O[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off.[n][uf 1 1][e]

[msg MND_028_5_0]
[uf 0 5 65278][uf 2 1]Maya signed back on.[n][uf 1 1][e]

[msg MSG_029_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]dont tell anyone abt that "SOB" stuff, k? its our little secret! ＞_＞[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

