[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I apologize for asking you to come at such short notice.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Truth be told... I'd like to ask you a favor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 202 1 25 25]I've been searching for someone of exceptional ability.[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]So if you have the time, do you mind taking on several of my requests?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]On special occasions, I may require you to escort me on certain excursions.[n][uf 1 1][e]

[msg MSG_003_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Of course, you will be aptly rewarded for completing the request.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 202 0 25 25]I look forward to your cooperation and hope to see you demonstrate your capability.[n][uf 1 1][e]

[msg MND_004_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I can accept Elizabeth's requests now.[n][uf 1 1][e]

