[msg MSG_000_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_DUNGE_BRDG_FUKA_STAR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5008 0 0]The last Shadow is floating in front of us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]I'm not sensing any movement from it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Let's prepare here... then head for battle.[n][uf 1 1][e]

