[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]This room feels so nostalgic, even though the entrance exams have only kept me away for a short while...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]The results haven't been posted yet... but I'm fairly confident that I passed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]If that's the case, then this spring, I'll formally become a college student.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]...And that means I'll no longer be seeing this view.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Unfortunately, I don't have much time to spare today. The company heads are conducting a briefing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]The Kirijo Group may appear strong, but it's actually rather frail... It could collapse at any time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I have to keep it together...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Don't push yourself.[e]
[uf 0 5 65278][uf 2 1]Any way I can help?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Heh... You're right. Resting is of equal importance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 5 0 25 25]Still, this is a crucial moment for me. I'll accept that I may need to go a bit overboard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]But if I do end up needing a change of pace, I hope you'll help me clear my head.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Heh, of course. In fact, there's something that only you can do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Who else is going to help me clear my head when I need a change of pace?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]It's thanks to you that I learned to feel comfortable in my own skin, beyond my identity as a Kirijo.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Before long, I'll be taking my leave from the dorm as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 3 25 25]I've begun packing up my things, but... I haven't made significant progress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]My books, my clothes, my photos... Every one of them brings back memories.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 5 1 25 25]It's been a short, but eventful three years. It all went by so fast.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Especially the year that you came.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 20 0 0]Whenever we spoke, or passed each other in the dorm... I felt like my heart would burst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 21 0 0]I never knew I had these emotions just waiting to be given permission to be felt.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]I wonder what would have become of me if you hadn't transferred to this school...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]If I hadn't met you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Would I have gone through with the arranged marriage?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Or would I have gotten on my motorcycle and left it all behind?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Fate is... a mysterious thing.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Well, there's no point in dwelling on the past.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]There are things that need to be done—for the future of the Kirijo Group, as well as my own.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 29 0 0]And... for your future as well, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 0 0 0 30 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]You know what I mean, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Come introduce yourself to the heads of the family sometime. Don't worry, you'd only be saying hello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 5 1 25 25]I'd just like them to know who you are.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Well, it's almost time. I'd best be on my way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]I'd love to see you back at the dorm, but I'll be out late tonight. Perhaps this weekend?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 36 0 0]Just the two of us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 37 0 0][uf 4 23 0 5 1 25 25]Heh, who else will lend me their shoulder when I need a little support?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 5 0 25 25]You're the only one who can do this for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 39 0 0]Go on, try and name someone who could do the same.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Heh, was that a bit much? Well, now you know how serious I am, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]I... need you in my life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 0 0 0 42 0 0]......[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]It's hard to believe I've begun to feel like an ordinary high school student...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]I never knew I had these emotions just waiting to be given permission to be felt.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]I wonder what would have become of me if you hadn't transferred to this school...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]If I hadn't met you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]I might never have realized what was truly important to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]Or would I have gotten on my motorcycle and left it all behind?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]Fate is... a mysterious thing.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Well, there's no point in dwelling on the past.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]There are things that need to be done—for the future of the Kirijo Group, as well as my own.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]Even if I lose my way again someday... it doesn't matter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]I know things will work out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]I won't have to face it alone. You're the one who taught me that.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]All right, it's almost time. I must be on my way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 56 0 0][uf 4 23 0 5 1 25 25]Perhaps we could find some time to relax together on a weekend. I found a nice crêpe shop that I'd like to try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 5 0 25 25]It's a bit far, though... You'd better get your motorcycle license soon.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]Just imagine hitting the road on our motorcycles together... I look forward to it.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]...Well, we'll see. Now then, if you'll excuse me.[n][uf 1 1][e]

