[msg AST_DNG_LIMITED_102_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1 0 0]Gotta say, I wasn't expectin' to go on another adventure with Sanada-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 2 0 0]I bet I'll come outta this in even better shape than last year! Right, Amada?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 3 0 0]Yeah, same here. I'd say he's been a good influence on us.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 4 0 0]Oh really? Well, I'd say you've both been slacking off.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5 0 0]What!? C'mon, man, I've been gettin' some exercise in![n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10_4 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 6 0 0]And that's between all our schoolwork! We don't have that much time to train...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10_5 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 7 0 0]Do you hear how you both sound, making all these excuses?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 8 0 0]Deep down inside, you know how disappointed you are in yourselves.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_102_0_10_6 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 9 0 0]Uh, wow, that's a bit harsh. I'm not that disappointing...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 10 0 0]Staying true to yourself no matter who you have to fight... That takes guts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 11 0 0]I gotta say, Junpei... I'm impressed.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 12 0 0]Huh...? Wait, what? Oh, uh... Nah, I was just doin' what anyone'd do, right?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 13 0 0]You don't have to be so embarrassed, Junpei-san. You're even blushing.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 14 0 0]Wh— I ain't blushin'![n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 15 0 0]You too, Amada. It felt good knowing I had a reliable partner watching my back.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_5 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 16 0 0]R-Really? But I didn't, uh... I was just...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_6 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 17 0 0]You don't have to be so embarrassed, Amada. You're even blushing.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_7 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 18 0 0]Seriously? That's extremely childish, you know.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_103_0_10_8 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 19 0 0]Uh, how did this turn into an argument?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 20 0 0]I realize this may be a bit of an awkward time and place to say this, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 21 0 0]I'm glad you're here, Yukari. It's been too long since we've last seen each other.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 22 0 0]Ruff![n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_10_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 23 0 0]You're right, Koro-chan. I guess I haven't seen Yukari-chan in a while either.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_10_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 24 0 0]Oh, um... I wasn't trying to avoid you guys or anything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 25 0 0]I just, uh... Sorry.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_10_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 26 0 0]There's no need to apologize. What's important is that we're together now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 27 0 0]So, let's resolve this predicament we find ourselves in, shall we?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_104_0_10_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 28 0 0]Heh... Right.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 29 0 0]Hey, uh... I... I'm really sorry.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 30 0 0]Hm? What for?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 31 0 0]For... basically making you take my side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 32 0 0]I was just being selfish, and... took my own feelings out on everyone else...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 33 0 0]Hm... I'm afraid I haven't the faintest idea what you mean. Do you, Koromaru?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_4 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 34 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 35 0 0]Come on, Koromaru. Don't answer like you know what's going on.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_6 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 36 0 0]But he does know. Don't you, Koro-chan?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_7 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 37 0 0]Yes, I'm certain that he does, Yukari.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_8 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 38 0 0]Arf, arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_105_0_10_9 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 39 0 0]Why're you all ganging up on me?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 40 0 0]Heh, been a while since the team looked like this, huh?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 41 0 0]I suppose... From your perspective, this was the original lineup. But with Aigis.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_10_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 42 0 0]Yeah, we got the OG squad here![n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_10_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 43 0 0]There's no point getting all sentimental. Let's just focus on the mission.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_10_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 44 0 0]Damn, Yuka-tan. What's got you all grumpy?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_106_0_10_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 45 0 0]I'm not grumpy.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_107_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 46 0 0]It just feels right, the team lookin' like this, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 47 0 0]All us old-time Tartarusers, hittin' the road together... Right, Yuka-tan?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_107_0_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 48 0 0]Why would I "feel right" with you around? You're always so loud.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_107_0_10_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 49 0 0]You say that, but I can tell from how you fight that you're more relaxed as well.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_107_0_10_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 50 0 0]Wh— Mitsuru-senpai! Don't give Junpei the satisfaction or it'll go to his head![n][uf 1 1][e]

[msg AST_DNG_LIMITED_107_0_10_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 51 0 0]Haha...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 52 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 53 0 0]Koromaru, wait! Don't just go running ahead of everyone else![n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_10_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 54 0 0]Fearless as always... He doesn't seem worried at all about our situation.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_10_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 55 0 0]Well, I get that he's excited. It has been a while since we teamed up like this.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_10_4 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 56 0 0]Arf, arf, arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_108_0_10_5 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 57 0 0]Hey! I told you to stop running ahead![n][uf 1 1][e]

[msg AST_DNG_LIMITED_109_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 58 0 0]*pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_LIMITED_109_0_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 59 0 0]Huh... I'm just thinking, we won't have many more chances to go on walks anymore.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_109_0_10_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 60 0 0]Oh, um... It'll be okay. I'll take Koromaru out on jogs after you leave, Sanada-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 61 0 0]We're gonna keep training together, so don't worry about us![n][uf 1 1][e]

[msg AST_DNG_LIMITED_109_0_10_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 62 0 0]Heh... Glad to hear it.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_110_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 63 0 0]It's been some time since we've actually seen each other in person, huh?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_110_0_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 64 0 0]It's a little late to be bringing that up now, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 65 0 0]Besides, I'd say that's largely due to you not reciprocating my requests to talk.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_110_0_10_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 66 0 0]I've got my own business to take care of too, you know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 67 0 0]And I won't offer anyone special treatment—not even a Kirijo.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_110_0_10_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 68 0 0]Well... No one can say you don't stay true to your convictions.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 69 0 0]Haha...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 70 0 0]What're you laughing at? You're creeping me out.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 71 0 0]Sorry... I was just thinking back on your choice. It couldn't have been more you.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 72 0 0]Of course it was me, I'm the one who made it. Your choice, meanwhile...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 73 0 0]What about my choice?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10_5 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 74 0 0]I was about to say your choice wasn't like you at all, but actually... It was.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_111_0_10_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 75 0 0]Yes, I think so as well.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_201_0_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 76 0 0]We'd probably be able to get further more easily with a bigger group, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 77 0 0]At least the two of us will get stronger like this, so I guess it's fine.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_202_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 78 0 0]Man, it's kinda scary goin' in with just two people. That's a lotta responsibility![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 79 0 0]But don't worry, Ai-chan, I'm here for ya! Just follow my lead![n][uf 1 1][e]

[msg AST_DNG_LIMITED_203_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 80 0 0]Though there may be only two of us, I feel assured with you at my side, Aigis.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_204_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 81 0 0]Just the two of us, huh? Sounds like a challenge... Heh, fine by me.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_205_0_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 82 0 0]It feels more dangerous with such a small group, but I can handle it.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_206_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 83 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_206_0_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 84 0 0]Koro-chan seems like he wants to give even more since it's just you and him.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_207_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 85 0 0]It's just you and me, Sister! I'll do everything I can to keep you safe![n][uf 1 1][e]

[msg AST_DNG_LIMITED_208_0_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 86 0 0]Hey, Aigis... I just... wanted to say, uh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 87 0 0]Um...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_209_0_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 88 0 0]What is it, Yukari-chan?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_210_0_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 89 0 0]Um... Don't worry about it. C'mon, let's do this![n][uf 1 1][e]

[msg AST_DNG_LIMITED_211_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 90 0 0]We testin' our strength? Well, bring it on! I'll knock 'em all outta the park![n][uf 1 1][e]

[msg AST_DNG_LIMITED_212_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 91 0 0]I see you've opted for a lineup consisting of just the two of us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 92 0 0]In that case, I'll do everything I can to ensure that I'm doing my part.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_213_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 93 0 0]Pretty gutsy, going with a team this small. But don't worry, I won't disappoint.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_214_0_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 94 0 0]Since you're only bringing me along, you must really trust my abilities, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 95 0 0]Well, I'll make sure you don't regret it. Let's do it, Aigis-san![n][uf 1 1][e]

[msg AST_DNG_LIMITED_215_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 96 0 0]*pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_LIMITED_215_0_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 97 0 0]It's easy to tell when Koro-chan is happy. He must like being paired with you.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_216_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 98 0 0]I get to be with my sister! Hehe...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 99 0 0][uf 7 3 11 0 65535]......[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 100 0 0]Hey. I know we're not exactly best friends, but do you really have to glare?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 101 0 0]Like it or not, we gotta work together to get out of this. You, me, Aigis—everyone.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_10_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 102 0 0]I'm not glaring...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 103 0 0][uf 7 3 11 2 65535]......[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_10_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 104 0 0]What?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_10_4 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 105 0 0]You're right. I was glaring.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_301_0_10_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 106 0 0]Uh... Okay, thanks for being honest, I guess.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_302_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 107 0 0]Oh, I got one! Hey, Metis, stop me if you've heard this one...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_302_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 108 0 0]Even if I hadn't, I wouldn't care to.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_302_0_10_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 109 0 0]Aw, come on! You're no fun...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_303_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 110 0 0]Hm... A successor unit to Aigis...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_303_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 111 0 0]Why are you staring at me?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_303_0_10_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 112 0 0]Oh, my apologies. I didn't mean to be so rude.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_303_0_10_3 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 113 0 0]Uh, you don't really need to apologize...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_304_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 114 0 0]Hm... You seem capable. But I guess that's to be expected from Aigis's sister.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_304_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 115 0 0]Of course! Never underestimate us sisters![n][uf 1 1][e]

[msg AST_DNG_LIMITED_305_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 116 0 0]You appear to be much shorter in stature compared to the others.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_305_0_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 117 0 0]Well, that's just because they're older than me. I'm not short for my age.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_305_0_10_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 118 0 0]Your age...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 119 0 0]I comprehend.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_306_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 120 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_306_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 121 0 0]You don't have to show me how it's done. I already know how to fight.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_306_0_10_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 122 0 0]Grrr... Woof![n][uf 1 1][e]

[msg AST_DNG_LIMITED_306_0_10_3 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 123 0 0]What!? Well, yes, but still![n][uf 1 1][e]

[msg AST_DNG_LIMITED_306_0_10_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 124 0 0]Huh. I wonder what they're arguing about...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_307_0_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 125 0 0]So, Metis, uh... What kinda things do you like?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_307_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 126 0 0]I like my sister, obviously.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_307_0_10_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 127 0 0]Um... Maybe I could've phrased that better.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_308_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 128 0 0]I want you to take back what you said.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_308_0_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 129 0 0]Huh? What'd I say?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_308_0_10_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 130 0 0]You said I'm "just a kid." I want you to take it back.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_308_0_10_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 131 0 0]Wow, you, uh... You're really not lettin' that go, huh?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_309_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 132 0 0]I've been wondering... Why did you decide my sister should be the leader?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_309_0_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 133 0 0]Hm? Well, her abilities, for one. But mostly because of her intelligence.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 134 0 0]A leader must have observational and decision-making qualities such as hers.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_309_0_10_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 135 0 0]Huh... Yeah...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_310_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 136 0 0]I guess it makes sense for a little sister to cling so tightly to her older sibling...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_310_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 137 0 0]What do you mean?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_310_0_10_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 138 0 0]It's nothing. Just thinking out loud...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_311_0_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 139 0 0]We've been teamed up for a while now, but we don't really know each other.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 140 0 0]Once we get out of here and time goes back to normal, let's sit down and talk.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_311_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 141 0 0]"Once we get out of here"...? Ha... Yes, I'm sure you'll find your way out.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_312_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 142 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_312_0_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 143 0 0]Yeah, I know.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_312_0_10_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 144 0 0]Woof![n][uf 1 1][e]

[msg AST_DNG_LIMITED_312_0_10_3 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 145 0 0]Hehe, of course you would say that.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_312_0_10_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 146 0 0]It looks like Metis and Koro-chan are getting along.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 147 0 0]How nice...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_401_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1148 0 0]I know this whole matter is... complicated. But I'm still with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1149 0 0]I'll do whatever I can for you.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_402_0_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 737 0 0]Even if we get the key, if those fires go out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 738 0 0]It's scary to think about...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_403_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1150 0 0]Sister, I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1151 0 0]Uh, never mind. Sorry...[n][uf 1 1][e]

[msg AST_DNG_LIMITED_410_0_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 273 0 0]This whole time, I just felt so alone... Even though I had everyone right by me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 274 0 0]I doubt I'll ever live up to Mitsuru-senpai... She's just incredible. Well, nothing I didn't already know.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_411_0_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 436 0 0]We'll be busy once we're out, but we're still throwin' a welcome party for Metis, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 437 0 0]Let's find out what places she'd like to go to and hit up the town![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 438 0 0]But first, we gear up, press on, and make that future a reality![n][uf 1 1][e]

[msg AST_DNG_LIMITED_412_0_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 567 0 0]So our regrets gathered together to form the very entity that created this place... Interesting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 568 0 0]Sounds like we'll have to defeat this thing if we want to put those thoughts to rest. You ready, Aigis?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_413_0_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 672 0 0]I thought I had grown accustomed to facing the things I'd rather not see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 673 0 0]But I still have much growing to do. And with everyone's support, I know I will.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 674 0 0]All right, Aigis... Let's continue onward, together![n][uf 1 1][e]

[msg AST_DNG_LIMITED_414_0_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 739 0 0]We were so impatient with it all, even before we got stuck here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 740 0 0]But now, we've all acknowledged it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 741 0 0]I'm sure everything will turn out all right.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_415_0_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 874 0 0]I thought I was looking at things calmly and rationally...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 875 0 0]But I wasn't. I was just lying to myself the whole time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 876 0 0]And now that I see that... I have to confront it.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_416_0_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1008 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_416_0_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1009 0 0]Koro-chan, you seem really happy to be back with everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1010 0 0]It feels like we've been apart for a long time, doesn't it?[n][uf 1 1][e]

[msg AST_DNG_LIMITED_416_0_10_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1011 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_LIMITED_416_0_10_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1012 0 0]Hehe... I think we can all agree on that.[n][uf 1 1][e]

[msg AST_DNG_LIMITED_417_0_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1152 0 0]I feel like I finally understand the meaning of the word "friend."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1153 0 0]They spoke about the future as if I would obviously be part of it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1154 0 0]It feels... nice.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_002_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 148 0 0]This place doesn't look like Tartarus at all, but it's just as creepy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 149 0 0]We better stay on our toes.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_002_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 675 0 0]We don't know anything about this place, so please be cautious...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_002_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 742 0 0]I'm a bit nervous, since we haven't done this in a while... Not scared, just nervous.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_003_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 150 0 0]Kinda feels like we're back in Tartarus... Which just sucks.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_003_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 439 0 0]So... We're stuck.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 440 0 0]We could take on a physical wall, but... What good are fists when we're up against time?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_003_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1013 0 0]I'm so, so happy to be here with you, Sister. And I love this armband![n][uf 1 1][e]

[msg AST_DNG_REGULAR_004_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 441 0 0]Not too long ago, we were climbing up, but now we're heading down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 442 0 0]'Least we might work out different muscles this way.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_004_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 676 0 0]No big issues so far... But there's still a lot more we don't know than we do.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_004_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 743 0 0]I might be a little rusty, but don't worry, I'll still give it everything I've got![n][uf 1 1][e]

[msg AST_DNG_REGULAR_005_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 151 0 0]I thought I'd at least perform better than this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 152 0 0]I guess enough time's passed for us to get bent out of shape...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_005_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 677 0 0]Nothing seems terribly off... But that in itself is a little eerie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 678 0 0]Maybe I'm just overthinking it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_005_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1014 0 0]Can they really help my sister...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1015 0 0]I guess it's fine...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_006_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 153 0 0]We used to have time for other things, but now all we do is explore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 154 0 0]Isn't it weird for us to go so hard when time's basically stopped?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_006_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 443 0 0]Did she actually think that we would've let her kill us in the first place? Hah![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 444 0 0]Can you believe her? As if we'd go down that easily![n][uf 1 1][e]

[msg AST_DNG_REGULAR_006_04_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 445 0 0]Uh... Is that really the problem here?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_006_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 679 0 0]My Persona feels a little different now... Maybe it's just because it's been a while.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_007_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 680 0 0]It's been some time since we've done this... But I'm getting less nervous about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 681 0 0]I can't let myself get too relaxed either, though. I'll stay vigilant.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_007_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 744 0 0]I'm actually not really that suspicious of Metis-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 745 0 0]I saw her face when we said we might leave her by herself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 746 0 0]It's hard going through life all alone...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_007_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1016 0 0]The path ahead is unpredictable, and I don't want to lose you on our way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1017 0 0]So we need to stay close to each other, all right, Sister?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_008_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 155 0 0]I've been thinking about that thing we saw... It's not a Shadow, is it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 156 0 0]Now that we finally have a lead, let's find out where it takes us.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_008_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 446 0 0]Is that mysterious figure the one behind all this? Heh, things are getting interesting.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_008_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 682 0 0]This whole place is mysterious, but that shadowy figure was especially so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 683 0 0]I wonder what's really going on here...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_009_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 157 0 0]What even was that figure anyway? Hard to believe it has nothing to do with us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 158 0 0]Let's hurry and catch it. We'll get out of here, for sure.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_009_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 447 0 0]We need more discipline if an opponent of that caliber is considered a threat.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_010_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 684 0 0]I didn't know Aigis had a sister unit. It's strange...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 685 0 0]And how did Metis end up here...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_010_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 747 0 0]I wonder where that shadowy figure went... Further in, I guess.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_010_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1018 0 0]I have no idea what that dark figure is. Where did it come from...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1019 0 0]It better not try to harm my sister...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_011_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 448 0 0]This place looks completely different... Yet we still haven't found any leads.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_011_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 748 0 0]Wow, it suddenly looks so different around here. How much is there to go?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 749 0 0]Tartarus was really long... I wonder if the Abyss of Time will be the same.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_011_08_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 750 0 0]Oh god, don't even say that. I don't want to be here for a year![n][uf 1 1][e]

[msg AST_DNG_REGULAR_011_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1021 0 0]Hey, Sister! You're my sister![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1022 0 0]Oh, um... I was just calling you my sister. Because you said I could, right...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_012_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 159 0 0]I wonder how everyone else is doing... Junpei won't get sidetracked, will he?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_012_02_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 160 0 0]I'm sure Koromaru will keep him in line and away from anything strange.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_012_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 686 0 0]It reminds me of Tartarus here... Though I'd rather not think of that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 687 0 0]Is this place as big as Tartarus was too...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_012_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 751 0 0]We probably still have a long way to go, so let's make sure to take breaks.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_013_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 449 0 0]We must be over ten floors in by now. Feels like we're nowhere close to the end, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 450 0 0]Is there even an "end" to the Abyss...? Eh, we'll find out if we keep moving along.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_013_04_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 451 0 0]Sanada-senpai's all over the place, as per usual.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_013_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 752 0 0]Think we'll end up fighting that dark figure? Whatever it is, it's pretty creepy.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_013_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1023 0 0]My sister: the leader...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1024 0 0]That has a nice ring to it! I'm so proud of my sister![n][uf 1 1][e]

[msg AST_DNG_REGULAR_014_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 161 0 0]Metis and Aigis might be sisters, but... They're not much alike, are they?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_014_02_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 162 0 0]W-We definitely are! Why would you say such a thing!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_014_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 163 0 0]N-No need to get huffy! You just give off a different vibe, is all.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_014_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 452 0 0]If there's anything I know I can do, I'll get it done and then some.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 453 0 0]The worrying can wait till after all's said and done.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_014_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 753 0 0]Koromaru's really been giving it his all. I've gotta do the same![n][uf 1 1][e]

[msg AST_DNG_REGULAR_015_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 164 0 0]Not much to speak of on our end... I wonder if Mitsuru-senpai found anything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_015_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 688 0 0]I'm sure being the new leader is tough, but I'll do all I can to help you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 689 0 0]Let me know whenever you need anything, okay?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_015_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1025 0 0]It's nice getting to walk with someone like this.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_016_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 454 0 0]So this is it, huh. Nowhere else to go, and no telling what'll come out of this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 455 0 0]Brace yourself, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_016_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 754 0 0]I feel like the mood is different now from when we were in Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 755 0 0]What could be waiting for us in here...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 165 0 0]What's the deal with this place? Didn't think we'd be sent back to the past...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 166 0 0]Right when I was struggling to muster the courage to look forward, at that.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 167 0 0]Yukari-chan...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 168 0 0]Haha, don't mind me. I'm just griping. Sorry about that...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 275 0 0]Junpei's back—and better than before! This expedition's gonna be nice n' smooth![n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_03_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 276 0 0]Hehe, how very reliable.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 277 0 0]Well, I ain't exactly in top form or anything, so uh, yeah, y'know, fine print and all that...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 877 0 0]Koro-chan seems so happy. Maybe he's glad to be with everyone again.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_017_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 878 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_018_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 278 0 0]So not only are we stuck in time, we're also, like, going back...? What's that all about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 279 0 0]Gotta be something weird behind all this... I mean, what other explanation is there?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_018_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 456 0 0]So that was Paulownia Mall last July... Maybe if we kept looking, we'd find—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 457 0 0]No, forget it. What's the point?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_018_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 756 0 0]It really felt like we were back in the past. I can't say I liked it...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_019_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 280 0 0]Hm, can't put my finger on it, but... Isn't there somethin' weird about li'l sis here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 281 0 0]Better keep your guard up, Junpei. Stay alert, protect Aigis. Ten-hut![n][uf 1 1][e]

[msg AST_DNG_REGULAR_019_03_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 282 0 0]Actually, it'd make me happy if you were so vigilant for my sister's sake.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_019_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 283 0 0]Uh, I-I wasn't talkin' about you or anything! Like, in a bad way! All good things, I swear![n][uf 1 1][e]

[msg AST_DNG_REGULAR_019_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 458 0 0]I honestly hadn't realized it before, but I think I've been pushing myself too hard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 459 0 0]We'll have an easier time once we're able to resupply.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_019_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1027 0 0]Seems like everyone's been kinda down lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1028 0 0]I thought finding a supply route would be something to be happy about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1029 0 0]I... don't comprehend...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_020_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 690 0 0]That Paulownia Mall was strange, but I'm more worried about that dark figure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 691 0 0]Something like that in a place where time doesn't flow normally... What's it mean?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_020_06_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 692 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_020_06_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 693 0 0]Oh, I'm sorry, Koro-chan. I didn't mean to worry you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_020_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 758 0 0]We may not know how this place works, but I'm sure we're making progress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 759 0 0]We even have a way to restock supplies now! That's a pretty good step forward.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_020_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1030 0 0]The more people we have on our team, the more combat options we have.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1031 0 0]I guess that would be helpful to my sister...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 284 0 0]So how do ya like bein' leader, Ai-chan? Probably not a total cakewalk, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 285 0 0]But, hey, I got your back—100%! Now put on your game face and let's get to marchin'![n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_03_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 286 0 0]Heh, well, someone's confident. Since when did you talk big like that to the leader?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 287 0 0]Uh, I've always been this confident, though?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 879 0 0]Time keeps starting over, but our energy is still always running out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 880 0 0]The Dark Hour was one thing, but what'll happen if we're here for too long...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 881 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 882 0 0]Oh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 883 0 0]You're right, Koro-chan. I shouldn't let myself worry so much.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1032 0 0]My sister's friends are actually pretty capable in battle.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_11_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1033 0 0]Excuse me? We may be out of practice, but we're more than "pretty" capable.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1034 0 0]You wish to be excused? I don't understand...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_021_11_1_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1035 0 0][uf 7 3 4 6 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_022_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 169 0 0]Now that we found a supply route, that's one less thing to worry about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 170 0 0]This really is Tartarus all over again, just with no sleep and no breaks.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_022_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 694 0 0]I feel a little better now that Junpei-kun and Koro-chan are with us again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 695 0 0]I hope Kirijo-senpai will return soon too...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_022_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 760 0 0]Things have gotten a lot livelier since Junpei-san came back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 761 0 0]Which has its pros and cons.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_022_08_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 762 0 0]C'mon, you couldn't just leave it at "livelier"?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_023_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 171 0 0]This is just so frustrating. Combat never felt this hard before, but now...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_023_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 288 0 0]All of us explorin' together kinda reminds me of befo— Er, forget that I said anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 289 0 0]Don't wanna kill the mood or nothin'.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_023_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 884 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_023_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 885 0 0]Koro-chan's staring at Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 886 0 0]Maybe he's feeling lonely because she can't understand him as well anymore...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_024_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 290 0 0]That thing was hangin' around when we were fighting those strong Shadows, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 291 0 0]Probably oughta watch our backs when exploring, yeah?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_024_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 460 0 0]That was the same figure we saw before, wasn't it? What's it up to...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 461 0 0]I say we corner it and demand answers. It better not think of giving us the slip.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_024_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 717 0 0]I hope we don't end up running into anything too dangerous...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_025_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 172 0 0]Finally seems like we're making progress...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 173 0 0]But if this ends up getting us nowhere, I'm gonna lose it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_025_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 292 0 0]Another victory SEES'd! Heh, like my new catchphrase? Juuust kidding! Or am I?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_026_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 174 0 0]I wonder how Mitsuru-senpai's doing... I'm a bit worried about her.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_026_02_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 175 0 0]Don't be. I'm sure she's doing just fine.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_026_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 293 0 0]Oh man, I thought we were gettin' somewhere, but we're probably just halfway, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 294 0 0]Still got a looong ways to go...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_026_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 462 0 0]Looks different here. Wonder if the enemies have changed any, too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 295 0 0]The vibes here are kinda off... Thought so when it was just me and Koromaru, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 296 0 0]Throw some Shadows into the mix, and... Euuugh.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_03_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 297 0 0]Ruff! Arf, arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 298 0 0]Haha, thanks for the push, pal. Knew I could always count on ya![n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 763 0 0]Suddenly becoming the leader must've been tough, but you're doing a great job.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 764 0 0]I feel very confident every time we go into battle with you in charge.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1036 0 0]What was it behind that door...? A Paulownia mole?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1037 0 0]But it didn't seem to resemble any kind of subterranean mammal at all...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_11_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1038 0 0]Um, Metis, it's not "mole," it's "mall"...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_027_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1039 0 0]It's what!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 176 0 0]Time's not advancing at all, huh... If only it'd stop when I'm studying.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 177 0 0]That'd definitely come in handy for our entrance exams.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 178 0 0]And for licenses and certifications, too! Wait... What am I saying?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 179 0 0]We should focus on getting out of here, but I just totally went off track.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_02_1_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 180 0 0]That makes two of us...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 463 0 0]Huh, I'm the oldest one here right now... Well, you can count on me for anything, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 892 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_028_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 893 0 0]Koro-chan's so peppy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 894 0 0]I bet he feels like he can do anything right now. You can do it, Koro-chan![n][uf 1 1][e]

[msg AST_DNG_REGULAR_029_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 765 0 0]It feels kind of suffocating, going down this much, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 766 0 0]The airflow hasn't changed, though... Maybe it's just all in my head.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_029_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 895 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_029_09_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 896 0 0]What're you rushing us for? There isn't gonna be food down there or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 897 0 0]Wouldn't mind if there was, though...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_029_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 898 0 0]Oh, I guess Sanada-senpai's hungry...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_029_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1040 0 0]It's been some time since we saw that unknown figure... But nothing's happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1041 0 0]At least my sister's safe, but I want her to accomplish her goals too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1042 0 0]Ugh...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_030_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 181 0 0]We've gone quite a ways by now... Here's hoping we find some kinda clue soon.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_030_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 299 0 0]Oh, man, guys, this is bad... What do we do?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 300 0 0]We've gotten pretty far, but if we step out for a breather, we're technically still trapped![n][uf 1 1][e]

[msg AST_DNG_REGULAR_030_03_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 301 0 0]Junpei... Please, just stop.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_030_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 464 0 0]I need to make some adjustments to my current training regimen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 465 0 0]Looks like it's just my stamina that didn't take a hit. Gotta keep up the running.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_031_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 182 0 0]The vibe here is kinda similar to where we found the door to Paulownia Mall, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 183 0 0]Wonder where this one will take us...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_031_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1043 0 0]Was that figure just trying to get in our way?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1044 0 0]Or... was it guiding us here...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 184 0 0]The doors reflect the minds of those who enter... Is that actually true?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 185 0 0]Well, I guess anything goes in a place like this.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 302 0 0]We all knew what you went through, Amada, but seein' it play out like that, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 303 0 0]It's totally different hearin' it from someone else... Blindsided us all, I think.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 304 0 0]It's okay, I don't mind. I trust all of you, so...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 305 0 0]Wow, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 306 0 0]Sorry, I'm... just getting a little choked up.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_03_1_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 307 0 0]You are? But why?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_032_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 569 0 0]Apologies for the extended absence. I'll be sure to focus on exploring now.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_033_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 696 0 0]I keep thinking about what Amada-kun said...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 697 0 0]About "that feeling we all shared"...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_033_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 767 0 0]Reliving that memory was tough... But I actually feel better about it this time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 768 0 0]Sanada-san got mad on my behalf, and everyone else was there for me too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 769 0 0]I wish I could tell my past self what it'll be like seeing that memory again now.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_033_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1045 0 0]I don't understand my sister's friends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1046 0 0]They say they want to leave this place, but...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_033_11_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1047 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_033_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1048 0 0]Oh, because that makes sense.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_034_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 186 0 0]Honestly, I'm a bit relieved to have you back with us, Mitsuru-senpai.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_034_02_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 187 0 0]I'm happy to be back. We'll stick together from here on out.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_034_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 466 0 0]Reliving those feelings, huh... And here I thought I had myself all figured out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 467 0 0]But I didn't—not until I had to face the truth all over again.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_034_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 570 0 0]So... The door has shown us a clue on how to destroy the Abyss of Time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 571 0 0]But what, exactly? Is it something in our past? Just what is this place...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_035_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 308 0 0]Awright, next clue, where you at, hm?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_035_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 698 0 0]It feels so long since I've navigated for Kirijo-senpai... I'm a little nervous.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_035_06_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 699 0 0]Is that so? Regardless, I'm sure you'll be giving us the best support you can.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_035_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1049 0 0]Everyone talks about the past so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1050 0 0]They probably need it to get out of here... And that would help my sister![n][uf 1 1][e]

[msg AST_DNG_REGULAR_036_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 309 0 0]Hey, Aigis... You sure Metis is your little sister?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 310 0 0]Honestly, I dunno if I can trust her.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_036_03_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 311 0 0]I couldn't care less about your trust, but know this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 312 0 0]We ARE sisters. Make no mistake.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_036_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 313 0 0]THAT'S your takeaway!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_036_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 468 0 0]If he were here... I wonder what he'd say about that door—and what it showed us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 469 0 0]Though I guess thinking about that is just a waste of time.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_036_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 572 0 0]Taking on the leader's mantle must be difficult at this time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 573 0 0]But I believe you're capable of seeing it through, Aigis. Give it the best you've got.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_037_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 700 0 0]Things like going to school and studying feel natural to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 701 0 0]But navigating for everyone also feels natural.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 702 0 0]It's odd, isn't it? Especially since we explore such dangerous places.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_037_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 770 0 0]I'm getting thirsty...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 771 0 0]Wait... Are our bodies still metabolizing even with time looping...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 772 0 0]Eh, probably better not to think about it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_037_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1051 0 0]Sister, let me know right away if you need anything. I'm always here for you![n][uf 1 1][e]

[msg AST_DNG_REGULAR_038_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 188 0 0]Aigis as the leader, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 189 0 0][uf 7 3 2 0 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_038_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 190 0 0]Yukari-chan...? Are you not feeling well?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_038_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 191 0 0]Mm... No, I'm fine. It's nothing.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_038_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 905 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_038_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 906 0 0]Koro-chan's always so full of energy after beating a strong enemy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 907 0 0]Maybe he wants to keep up his momentum?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_039_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 703 0 0]Our surroundings may look different, but my readings seem the same.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 704 0 0]I have to wonder if we're actually making any progress...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_039_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 773 0 0]Maybe I should start running more after we get out of here...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_039_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1052 0 0]My sister's protector... You know that's me! Metiiiis! ♪[n][uf 1 1][e]

[msg AST_DNG_REGULAR_039_11_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1053 0 0]Hell of a good mood she's in...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_040_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 336 0 0]Phew. Gonna take me a little breather...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 337 0 0]Well, 'least our feet aren't covered in nasty, squishy gunk. Silver lining and all that, yeah?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_040_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 477 0 0]If only we could go toe-to-toe with a stronger foe for a change.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 478 0 0]Nothing beats taking on a real challenge to gauge your own strength.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_040_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 581 0 0]Even after coming this far, I haven't seen Metis behaving suspiciously.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 582 0 0]But there's still much we don't know about her, so let's not lower our guard just yet.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 194 0 0]Everything looks the same in here. It's sooo boring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 195 0 0]For a place so outrageous, you'd think it'd look the part. I oughta spruce it up myself.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_02_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 196 0 0]"Spruce it up"...? How would pine trees make the Abyss more "outrageous"?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 316 0 0]Oh man... My head's spinning, looking at the same old scenery for too long.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 774 0 0]It must be weird having someone you don't know say they're your little sister.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 775 0 0]If I got a big brother out of nowhere, I wouldn't even know how to feel.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_08_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 776 0 0]Mm, and unexpected siblings could complicate family inheritance matters.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_041_08_1_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 777 0 0]Uh, yeah, I... I guess I didn't think of that...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 473 0 0]Being a leader, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 474 0 0]If someone told me to take command, I'd do it, but I doubt I'd be the best fit for the job.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 475 0 0]Sanada-san as the leader...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 476 0 0]Yeeeahhh, not too sure about that.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 579 0 0]An abyss of time, indeed... All that we've seen are perfect reconstructions of our memories.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 580 0 0]Aigis, let's hurry and progress the expedition. We need to get to the bottom of this, quickly.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 901 0 0]*pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 902 0 0]I wonder what Koro-chan thinks about not being able to leave this place.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_09_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 903 0 0]He doesn't seem particularly bothered by it. He's got enough food, after all.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_042_09_1_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 904 0 0]Well, he certainly knows his priorities.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_043_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 197 0 0]We better keep moving. Seems like we still have a long road ahead of us.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_043_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 778 0 0]I'm worried we'll lose track of what floor we're on. I thought this last year too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 779 0 0]Right now, we're on the... 12th floor. Not the 13th. I'm pretty sure.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_043_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1054 0 0]You know what, Sister's friends? You're doing all right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1055 0 0]But I'm the one who protects my sister. And don't forget it![n][uf 1 1][e]

[msg AST_DNG_REGULAR_044_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 314 0 0]That was the same figure, right? The one we saw before?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 315 0 0]It'd be nice if it just told us what it wants, but nooo, it's too shyyy...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_044_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 576 0 0]That strange figure is worrying...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 577 0 0]It may be connected to whatever trapped us here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 578 0 0]Let's keep our guard up as we proceed, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_044_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 781 0 0]Just what is it...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_045_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1056 0 0]Is that unidentified figure trying to stop us from progressing...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1057 0 0]Unacceptable. How dare you try to get in my sister's way![n][uf 1 1][e]

[msg AST_DNG_REGULAR_045_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 867 0 0]That's the second time we've beaten that one. I hope there won't be a third...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 198 0 0]I'm not exactly patient, but I know you gotta take some things one step at a time.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_02_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 199 0 0]That's very mature of you, Yukari-san. There's a lot I can learn from you...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 200 0 0]Uuugh, seriously, how much further do we have to gooo!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_02_1_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 201 0 0]Didn't take very long for her to crack...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 319 0 0]Hm, might look different down here, but I'm guessin' we still have a lotta ground to cover.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 320 0 0]Time to buckle up. We've got a long road ahead of us...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_046_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 705 0 0]I guess all we can do is keep exploring little by little, just like last year.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_047_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 479 0 0]It's frustrating we're trapped in here, but at least there aren't any distractions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 480 0 0]Nobody nagging at you, telling you what to do... Honestly, it's not that bad here.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_047_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 583 0 0]The time loop... The Shadows...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 584 0 0]I can't help but be reminded of Tartarus and the Dark Hour... Much as I'd rather not.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_047_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 908 0 0]*sniff* *sniff*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_047_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 909 0 0]Koro-chan? Um, I don't think there's anything there...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_047_09_1_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 910 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_048_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 321 0 0]We got so far, but nothing's really changed. Wish something excitin' would happen...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_048_03_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 322 0 0]I don't know, Junpei-kun...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_048_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 323 0 0]I meant, good exciting! Not "dangerous" exciting![n][uf 1 1][e]

[msg AST_DNG_REGULAR_048_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 911 0 0]There are actually some things about time not moving that I find reassuring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 912 0 0]Like our families won't be worried about us, since it's all just one day to them.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_048_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 782 0 0]A hole this deep sitting just under the dorm... It defies physics.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 783 0 0]Tartarus did too. So many impossible things keep happening...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_049_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 324 0 0]Here's an idea: why not knock out our homework while we're stuck here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 325 0 0]Ha, but just 'cause I'm full of good ideas don't mean I always make good decisions![n][uf 1 1][e]

[msg AST_DNG_REGULAR_049_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 481 0 0]I think I warmed up plenty. I don't know about you, but I'm ready for a real fight.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_049_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1058 0 0]Working with others is difficult. I never thought about that before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1059 0 0]But I've been doing all right so far... Right? Yes! I've been doing great![n][uf 1 1][e]

[msg AST_DNG_REGULAR_050_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 470 0 0]Tartarus had us going up, but now that we're going down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 471 0 0]Couldn't we just dig a hole in the ground and make ourselves a shortcut?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_050_04_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 472 0 0]Akihiko, some plans ought to stay on paper.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_050_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 574 0 0]It's plausible she may be a prototype for the next-gen Anti-Shadow Suppression Weapon, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 575 0 0]I suppose it doesn't matter what she is. Better to focus on finding a way out.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_050_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1076 0 0]My sister's companions are wearing uniforms... School uniforms...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1077 0 0]I wonder if I would look good in one...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_051_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 585 0 0]Sometimes, things start to become clearer with experience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 586 0 0]I wonder what this next door will show us... Let's move, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_051_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 913 0 0]*pant* *pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_051_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 914 0 0]Koro-chan's got a glimmer in his eye. Maybe he senses something...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 587 0 0]Seeing my middle school self was certainly a strange experience...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 588 0 0]I tried so hard to look in control. Normally, I wouldn't say this about myself, but... It was rather cute.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 784 0 0]It was interesting seeing what Sanada-san was like in middle school...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 785 0 0]Maybe... I'll be that tall in a few years too...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_08_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 786 0 0]Don't worry, kiddo. I'm sure ya got plenty of puberty ahead of ya.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_08_1_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 787 0 0]Pu— What!? Why would you put it like that!? Ugh, just forget I said anything...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 915 0 0]Ruff! Ruff, ruff![n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_09_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 916 0 0]What is it? You've been barking an awful lot lately.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 917 0 0]And he won't take his eyes off you, Sanada-senpai...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 918 0 0]Maybe he was inspired by what we saw in your past![n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_09_1_3 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 919 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_052_09_1_4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 920 0 0]Heh, whatever you say, buddy. If you're fired up, then so am I![n][uf 1 1][e]

[msg AST_DNG_REGULAR_053_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 203 0 0]There's no avoiding the past here... But I guess that's what this place is all about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 204 0 0]Let's just assume these memories are clues and move on. What else can we do?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_053_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 482 0 0]As Yamagishi and the others have been saying, I doubt Metis has bad intentions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 483 0 0]But that doesn't necessarily mean she's not our enemy. I'll be keeping my guard up.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_053_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 706 0 0]After we escape the Abyss of Time, it'd be nice to take Metis around the school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 707 0 0]Hehe... That thought reminds me of when Aigis started attending.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_053_06_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 708 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_053_06_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 709 0 0]Great idea, Koro-chan! We can go on your usual walk route to get there.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 326 0 0]I've been watching Metis since we all talked, and, well... She really is just a kid, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 327 0 0]Kinda reminds me of... Well, me? Past me, I mean.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_03_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 328 0 0]Huh... Yeah, I kinda see it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 329 0 0]You do!? Hrngh, that's sweet you agree, but man... It's a huge blow to my pride.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 589 0 0]If we were to return to the dorm or Paulownia Mall, we'd find them unchanged.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 590 0 0]This is a different sort of confinement from the Dark Hour...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1060 0 0]The school was fascinating, but so is seeing how the human body changes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1061 0 0]You can tell it's the same individual even though they look different...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_11_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1062 0 0]Huh... I don't think any of us would have thought that you have such interests.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1063 0 0]Well, it's actually not so different from us![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1064 0 0]I think I would recognize my sister no matter what parts she had![n][uf 1 1][e]

[msg AST_DNG_REGULAR_054_11_1_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1065 0 0]I see... I'm sure you would.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 205 0 0]I'm starting to feel it in my legs...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 206 0 0]Going up was exhausting, but going down... isn't much better, either.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 484 0 0]Still can't net that decisive win... Maybe I should change up my footwork next time?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 485 0 0]His head's always in the ring, isn't it...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 710 0 0]What Junpei-kun said is pretty interesting, about how she's like a kid.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_06_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 711 0 0]I don't like that. I'm not a kid.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_055_06_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 712 0 0]Oh, okay, sorry. Hehe...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_056_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 788 0 0]Metis-san is "like a kid," huh...? She sure doesn't look like one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 789 0 0]So... Do I address her like someone my age or like someone older than me...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_056_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 921 0 0]You've covered a lot of ground. Are you sure none of you are tired?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_056_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 922 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_056_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 923 0 0]Hehe... Koro-chan, as ready as ever![n][uf 1 1][e]

[msg AST_DNG_REGULAR_056_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1066 0 0]Sister... Is it just me, or are your friends acting differently towards me now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1067 0 0]I don't think it was like this before...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_057_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 330 0 0]"This random rich girl lost it," bahaha! That's a good one! Gets me every time![n][uf 1 1][e]

[msg AST_DNG_REGULAR_057_03_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 331 0 0]At least have the decency not to laugh in my presence, Iori.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_057_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 486 0 0]Hmm, what if we didn't teleport and just ran from the top down instead?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 487 0 0]Surely that'd be easier than going bottom up like we would in Tartarus.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_057_04_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 488 0 0]W-Would it really...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_057_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 591 0 0]Not to downplay our situation, but to be honest, I'm a bit thankful time's stopped.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 592 0 0]...Since it means I won't be inconveniencing anyone with my prolonged absence.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 713 0 0]I feel like we've been exploring with Metis for a while now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 714 0 0]But it's hard to tell with time acting so strangely...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 790 0 0]It doesn't really look like Tartarus here, but it gives me the same uneasy feeling...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 924 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_09_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 925 0 0]Yeah, I know. You don't have to bark at me like that.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_09_1_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 926 0 0]Woof![n][uf 1 1][e]

[msg AST_DNG_REGULAR_058_09_1_3 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 927 0 0]Tch, you just have all the answers, don't you?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_059_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 207 0 0]Maybe Metis keeps calling for her sister all the time 'cause she's like a baby chick.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 208 0 0]With how they imprint on the first thing they see. I could be wrong, though.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_059_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 332 0 0]Man, it's just explore, explore, explore, aaall freakin' day. Talk about boooring![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 333 0 0]Eh, not like I was doin' much. Just feel like I oughta be out there, doin' something, y'know?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_059_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 334 0 0]Yeah, I think I do know what you mean.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_059_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 593 0 0]I started a training regimen last year since improving my stamina was a necessity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 594 0 0]I didn't expect to fall back on it so soon, but it's the reason I'm still able to keep walking.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_060_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 791 0 0]I bet there's still a lot left to go in this place, so let's try to pace ourselves.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_060_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 928 0 0]*pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_060_09_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 929 0 0]Ha... Koromaru appears quite spirited, as per usual.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 930 0 0]No matter what happens, you always manage to stay levelheaded. Good boy.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_060_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1068 0 0]I could follow my sister forever![n][uf 1 1][e]

[msg AST_DNG_REGULAR_060_11_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1069 0 0]Well, you've got quite a fan here, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_061_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 595 0 0]I think I've regained my battle prowess, but I admit I'm still far from my best...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_061_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 342 0 0]That midboss ain't so tough now! C'mon, let's keep this train movin'.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_062_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 209 0 0]Our surroundings changed... But that's like the only thing that seems different.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 210 0 0]Guess that means we gotta keep moving, huh?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_062_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 792 0 0]When our surroundings change, the Shadows might change too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_062_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1070 0 0]I don't know how large this place really is either...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1071 0 0]But it doesn't go on forever.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1072 0 0]I think.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_062_11_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1073 0 0]You "think"...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_063_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 317 0 0]So you're tellin' me we've been walking for ages, but time's just standin' still?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 318 0 0]Now that don't add up, nope. What happened to all that time I spent walking?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_063_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 490 0 0]We're wiping our enemies out left and right, but still can't unravel this mystery...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 491 0 0]Just means we need to be careful not to run out of steam.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_063_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 596 0 0]The fight against the Shadows just doesn't end. Where are they even coming from?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_064_03_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 492 0 0]Using Personas is all well and good, but I'm one for hand-to-hand combat.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_064_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 793 0 0]I hope I'm not holding anyone back...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 794 0 0]It's hard to tell. Everything's so different from before...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_064_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1074 0 0]Destroy my sister's enemies, show them no meeercy! ♪[n][uf 1 1][e]

[msg AST_DNG_REGULAR_064_11_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1075 0 0]Uh, I guess Metis is... in a good mood...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_065_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 360 0 0]Wish we could just plow through the enemy and go on our merry way in peace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 361 0 0]But nooope, 'course things can't be that easy.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_065_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 597 0 0]Metis knows a great deal about the Abyss, but not much about anything else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 598 0 0]I wonder why that is...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_065_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 931 0 0]You've traveled so far down... Please keep being careful.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_065_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 932 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_066_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 211 0 0]Ugh, I'm not even as good in archery anymore? This is the absolute worst.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_066_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 795 0 0]It feels like it's been so long since I've spent this much time with you all![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 796 0 0]I wish I was older so we could at least take classes closer to each other...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_066_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1020 0 0]Sister, do you want to go scout up ahead? I'll come with you![n][uf 1 1][e]

[msg AST_DNG_REGULAR_067_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 340 0 0]Been a while since we last saw that figure... Wonder if it'll be a no-show from now on.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_067_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 493 0 0]Time may have stopped, but we're only getting stronger and stronger.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 494 0 0]We're in a rough situation right now, sure, but it might actually be ideal for training.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_067_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 599 0 0]I know we need to keep going in search of answers, but it's equally important we pace ourselves.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_068_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 715 0 0]It's as if there's an infinite number of Shadows here, like with Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 716 0 0]I wonder how they all got here...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_068_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 933 0 0]*pant* *pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_068_09_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 934 0 0]You've got impressive stamina, Koromaru. Especially for being so small.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_068_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1078 0 0]We haven't seen that figure in a while... And we're pretty far down now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1079 0 0]Maybe it's gonna come back for us at the end like, "Bam!" Be careful, Sister![n][uf 1 1][e]

[msg AST_DNG_REGULAR_069_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 212 0 0]I thought I got used to seeing the same scenery, but my morale's still taking a hit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 213 0 0]Feels like we're hardly making any progress...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_069_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 341 0 0]For a place overrun with Shadows, it sure is awfully quiet here.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_069_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 600 0 0]You'd think we'd be used to exploring on foot after last year, but it's really no easier.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_070_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 192 0 0]Fuuka said that figure we saw wasn't a Shadow... So what is it, then?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 193 0 0]If they're the one who trapped us here, we'll make 'em answer for it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_070_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 797 0 0]That strange figure again... Let's get it![n][uf 1 1][e]

[msg AST_DNG_REGULAR_070_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1080 0 0]Whatever that weird figure is, it got my sister's attention...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1081 0 0]It's not fair.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_071_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 601 0 0]Now that we've overcome the hurdle, the path forward is clear. Allons-y, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_071_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 798 0 0]Taking down tough enemies really helps build confidence, huh?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_072_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 214 0 0]We've beaten some really tough Shadows, but it just never ends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 215 0 0]Seriously, how far do we have to go?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_072_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 497 0 0]Wish that, after taking out a strong foe, there'd be another one lined up for us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 498 0 0]Guess I'll just keep holding out hope.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_072_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 499 0 0]You actually WANT that?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_072_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1082 0 0]It looks different here... Let's keep our guards up, Sister.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_073_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 343 0 0]In one fell swoop, Junpei-kun emerges victorious—and the crowd goes wild...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 344 0 0]Hrm... They say you can visualize things into reality, but I dunno...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_073_03_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 345 0 0]That's because you're just daydreaming.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_073_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 799 0 0]This part of the Abyss is longer than the others. It's similar to Tartarus like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 800 0 0]I wish it wasn't, though...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_073_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 935 0 0]Koro-chan's tail is really going... Maybe he's happy to be with everyone.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_073_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 936 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_074_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 216 0 0]Oh, come on... Still nothing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 217 0 0]Well, we've gotten this far, so we better see this through![n][uf 1 1][e]

[msg AST_DNG_REGULAR_074_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 602 0 0]Though I'm not sure if my combat skills are up to par, I will say that I'm still fit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 603 0 0]I'll be able to keep going all the way to the very end. You can count on me, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_074_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1083 0 0]"Just a kid"...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1084 0 0]Hmph, not that it's bothering me at all. Why would it, right?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_074_11_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1085 0 0]That's, uh... still buggin' you, huh...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 248 0 0]Well, one good thing about this place is that the floors are nice and level.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 249 0 0]If we had to move up and down an incline all the time, I think I'd be a goner...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 381 0 0]If you add 'em all up, we've done explored a hell of a lot of floors, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 382 0 0]There was too many in the first area... Even more in the next, and then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 383 0 0]Yep, just one hell of a lot of floors! Moving on![n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 384 0 0]It's good you know when to give up...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 887 0 0]Arf! Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_09_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 888 0 0]Really...? You sure know a lot, Koromaru-san.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_075_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 889 0 0]Metis can't be so bad if Koro-chan gets along with her like this.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_076_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 346 0 0]Are we gonna see someone's past again? It might be a clue, sure, but... Eugh.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 347 0 0]Please don't let it be me... Please, oh please...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_076_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 500 0 0]Looks like we made it to the bottom. What's waiting for us this time...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 604 0 0]Iori understood that he wanted a friend who would see him for who he really is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 605 0 0]It's quite impressive, given how long it took me to realize that about myself.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 801 0 0]Junpei-san gets carried away easily, and he can be frivolous and absentminded...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 802 0 0]But he can be impressive when he puts his mind to something.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_08_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 803 0 0]Hehe... I've noticed that too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_08_1_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 804 0 0]Yeah, I think we all know it, even if we don't always see it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 937 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_09_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 938 0 0]Ah, the dog of destiny—my fated friend! What's up, buddy?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_09_1_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 939 0 0]Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_077_09_1_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 940 0 0]Alright, alright, I'm comin'! Don't strain your voice barkin'.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_078_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 218 0 0]Gossiping is seen as a girl thing, but I think guys do it better, don't you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 219 0 0]Going on and on about striking out, nursing broken hearts... What idiots.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 220 0 0]I remember thinking the same thing back then, but now it's clear you're all hopeless.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_078_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 501 0 0]So the doors do mean something... Wonder what, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 502 0 0]We saw when Mitsuru and I met, when Junpei and Koromaru met... Is that it? First encounters?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 503 0 0]Wait, no, Amada's was different. Guess that's back to the drawing board.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_078_04_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 504 0 0]Akihiko, you'll tire yourself out thinking so hard. Why don't you take a break?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_078_04_1_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 505 0 0]True, I'm more for raw power over brain power. In which case, let's move out![n][uf 1 1][e]

[msg AST_DNG_REGULAR_078_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 718 0 0]So Junpei-kun and Koro-chan knew each other even before they awakened...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 719 0 0]I think I'm a little jealous. I wish I knew someone in the group beforehand too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_079_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 606 0 0]These Shadows appear stronger than the earlier ones. Let's exercise caution.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_079_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 805 0 0]Growing up is tough. There's way more to it than just getting older.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 806 0 0]Those guys in Junpei-san's memory got me thinking about that again...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_079_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1086 0 0]Every time we go through one of those doors, they always...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1087 0 0]Whatever. I don't want to think about them. I want to think about my sister.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_080_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 221 0 0]I thought we were finally getting somewhere, but I still don't understand anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 222 0 0]Are those doors actually clues?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_080_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 348 0 0]Honestly, I thought I was gonna die of embarrassment seein' past me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 349 0 0]But now... Hm, how do I put it... Well, I was just doing the best I could back then.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_080_03_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 350 0 0]Junpei-kun...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_080_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 351 0 0]Haha, man, the hell am I sayin'! Guess I'm more embarrassin' now than ever.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_080_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 607 0 0]Metis sees something that even the owners of these memories don't...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 608 0 0]Just what is the commonality that they all share...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_081_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 807 0 0]You don't normally get to see memories of others from before you met them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 808 0 0]In that way... Maybe being here isn't all bad.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_081_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 941 0 0]I guess if I'd found Junpei a little earlier, I could've met up with Koromaru, too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_081_04_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 942 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_081_04_1_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 943 0 0]Yeah... We were this close, huh?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_081_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1088 0 0]Junpei-san seems reinvigorated somehow...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1089 0 0]Even though we still don't have any leads... Strange.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_082_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 223 0 0]We take out the queen, we wipe out the hive... If only bug spray worked on Shadows.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_082_02_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 224 0 0]Guess we'll need to invest in some Anti-Shadow Spray, then.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_082_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 335 0 0]What if we opened that window...? Not that I'd actually do it or anything. Too scary.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_082_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 506 0 0]That Shadow just then was...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 507 0 0]Actually, never mind. Junpei's face was more horrifying during his first time with the Dark Hour.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_082_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 508 0 0]Could you PLEASE stop bringing that up!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_083_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 609 0 0]The doors disappear once they've served their purpose...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 610 0 0]It may be best to keep that in mind. There's meaning to everything here.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_083_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 809 0 0]You all have a lot more stamina than me... I noticed it last year, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 810 0 0]I need to try harder so I can keep up.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_083_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 944 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_083_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 945 0 0]Koro-chan, are you hungry? Just hold on for a little longer, okay?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_084_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 515 0 0]Glad we get to face a tough enemy. Now we're one step closer to our goal.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_084_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1111 0 0]I wish I could walk with my sister like this even when we're not exploring...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 611 0 0]The scenery is different here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 612 0 0]The Shadows may have changed as well. Be ready for anything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 811 0 0]I wonder what else is outside of here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 812 0 0]If it's an "abyss," there are probably multiple directions you can fall in from.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 946 0 0]Koro-chan's been going around in circles for a while now. I wonder why...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 947 0 0]*pant* *pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_09_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 948 0 0]Hm... It seems he would like someone to scratch his rear.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_085_09_1_3 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 949 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_086_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 228 0 0]We haven't seen the sky in a while... Which is kind of a strange thought to have.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_086_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 495 0 0]Even though we're underground, there's light coming through the windows...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 496 0 0]It caught my attention just now. Where the hell is that light coming from?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_086_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 720 0 0]Aigis, I know it must be tough with your new responsibilities as leader.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 721 0 0]Let me know if you ever need help with anything. I'll do whatever I can.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_086_06_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 722 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_086_06_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 723 0 0]Hehe... I think Koro-chan wants to help out too.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 613 0 0]Every now and again, this place reminds me of Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 614 0 0]I couldn't explain why specifically. It's just a feeling I have...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_05_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 615 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_05_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 616 0 0]You too? Well, that is certainly validating.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 813 0 0]Maybe extra milk...? No, I need something with more protein...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_08_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 814 0 0]Hm? What was that, Amada?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_08_1_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 815 0 0]Oh, uh, i-it was nothing![n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1090 0 0]Sister's enemiiies, go splat and die pleeease! ♪[n][uf 1 1][e]

[msg AST_DNG_REGULAR_087_11_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1091 0 0]Uh... I'm not the only one creeped out by that, right?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_088_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 229 0 0]I think I'm getting stronger... Maybe not as strong as I used to be, but it's something![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 230 0 0]We just have to keep pressing forward and put an end to this...![n][uf 1 1][e]

[msg AST_DNG_REGULAR_088_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 357 0 0]And here I thought we were finally done with stairs...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 358 0 0]Man, at this rate, I'm gonna lose so much weight and wind up the sexiest man alive![n][uf 1 1][e]

[msg AST_DNG_REGULAR_088_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 359 0 0]If you keep wasting your breath, you'll just tire yourself out faster, you know.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_088_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 816 0 0]They don't really calm me down, but taking breaks is still important.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 817 0 0]Even Sanada-san respects the need for a rest between rounds.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_088_08_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 818 0 0]That's right. Sounds like you know what you're talking about.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_089_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 617 0 0]I'm not sure if she feels the same, but I've grown quite accustomed to Metis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 618 0 0]She's rather... unique, but we've met many unique people over the past year.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_089_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 950 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_089_09_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 951 0 0]Koromaru's got so much energy. I guess going on all those walks has paid off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 952 0 0]Well, I do a fair bit of walking too, but...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_089_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1092 0 0]Leave it to me, Sister! I'll beat all those Shadows![n][uf 1 1][e]

[msg AST_DNG_REGULAR_090_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 338 0 0]The floors here are real nice n' clean, huh? Think the Shadows are polishin' 'em?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_090_03_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 339 0 0]You know they're not.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_090_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 512 0 0]Aigis has really grown as a leader. I'm not really sure how I feel about it since, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 513 0 0]Never mind, sorry. Didn't mean to make things awkward.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_090_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 819 0 0]That strange figure could show up again at any moment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 820 0 0]In fact, I hope it does. Let's keep going, and maybe it will.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_091_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 231 0 0]My legs are gonna be so muscly after all this exercise...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 232 0 0]Even though I've been trying so hard to stay slender.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_091_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 821 0 0]It's pretty and all, but I wish we didn't have to be here this long...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_091_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1093 0 0]I love walking with my sister. Hehe![n][uf 1 1][e]

[msg AST_DNG_REGULAR_091_11_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1094 0 0]Hey, looks like the kid's havin' a ball.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_091_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1095 0 0]I'm not a kid...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_092_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 362 0 0]Man, these guys are stubborn as hell![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 363 0 0]They just keep coming one after another. Sure do love us, don't they?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_092_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 514 0 0]There it is again! We'll catch it this time, mark my words.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_092_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 619 0 0]It simply shows itself and flees... Surely, it intends to set something else on us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 620 0 0]Stay vigilant, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_093_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 621 0 0]Let's hurry onward.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 622 0 0]That strange figure may have the lead, but we can catch up to it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_093_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1096 0 0]That figure keeps just sending Shadows after us and then running away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1097 0 0]I don't comprehend...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_093_11_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1098 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_093_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1099 0 0]Right!? You get me.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_094_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 233 0 0]If only the door could pop up after we defeat a tough enemy... Guess that'd be too easy.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_094_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 364 0 0]Now that we've gotten past THAT hurdle, it'll be smooth sailin' from here on out![n][uf 1 1][e]

[msg AST_DNG_REGULAR_094_03_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 365 0 0]Heh, how reassuring. Sounds like you'd be a good fit for the vanguard, Iori.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_094_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 366 0 0]Wha— The, uh... The vanguard? Like... the meat shield?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 367 0 0]Please, oh please, let it be smooth sailin' on the front lines...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_094_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 724 0 0]The scenery has changed again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 725 0 0]And we just defeated a strong enemy. I wonder if that's somehow related...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_095_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 623 0 0]Hmhm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 624 0 0]Oh, I apologize. I was simply thinking about how fitting leadership is for you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_095_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 822 0 0]The Shadows keep getting even tougher.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 823 0 0]But it's not like we're outmatched, of course. Right, Aigis-san?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_095_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 953 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_095_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 954 0 0]Koro-chan's always so happy when he's with Aigis. He must like her a lot.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_096_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 368 0 0]Aw yeah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 369 0 0]Getting weaker is always a bummer, but I'd say I'm just about back to 100% now![n][uf 1 1][e]

[msg AST_DNG_REGULAR_096_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 516 0 0]If only the supply route we found took us to the front of the station...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 517 0 0]Paulownia Mall is fine, though... Yeah, just... Just fine.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_096_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1100 0 0]I hope I'll never have to stop walking with you, Sister.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1101 0 0]But it'd be nice if there weren't any Shadows...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_097_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 225 0 0]How many floors have we explored by now? I haven't exactly been counting.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_097_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 226 0 0]I've been keeping track this whole time. Do you want to hear it?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_09702_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 227 0 0]Oh, um, I think I'm good! Knowing the answer for sure would just get me down...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_097_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 355 0 0]Wonder what's happening out there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 356 0 0]I just don't want to make other people worry, you know? Worst feeling ever.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_097_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1026 0 0]Don't worry, Sister. I'm right behind you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_098_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 518 0 0]Keep the battles coming, I'm game. Just make sure we don't burn ourselves out.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_098_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 625 0 0]It seems fair to assume that we'll see someone's past behind the next door as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 626 0 0]So far, these memories are nothing to be ashamed of, but let's brace ourselves.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_098_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 824 0 0]It's kind of nice getting to move around this much again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 825 0 0]I've basically been doing nothing but studying lately. It made me feel so stiff.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 234 0 0]Seems like we're making a lot of progress... "Seems" being the keyword.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 235 0 0]It sucks we can't see the finish line. I mean, sure, Tartarus was the same, but still.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 370 0 0]Breaks are important, y'know? With all this explorin', maybe we're due for one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 371 0 0]Liiike, right about... Now![n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_03_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 372 0 0]You seem to have plenty of energy to spare, though.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 373 0 0]G-Guh...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1102 0 0]A little bit ago, I heard Sanada-san muttering something to himself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1103 0 0]I thought I heard him say something like, "Ooh me, ooh she"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1104 0 0]"Me" would be Sanada-san in this context, but who's "she"?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_099_11_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1105 0 0]Oh, you heard that, huh...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_100_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 519 0 0]We've gotten pretty far. Be nice if one of those doors showed up sometime soon, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 520 0 0]Doesn't seem like there's one on this floor, so I guess we gotta keep exploring.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_100_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 826 0 0]What exactly are those things we find items in?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 827 0 0]I gotta say, it's not my favorite way to get stuff...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_100_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 955 0 0]*sniff* *sniff*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_100_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 956 0 0]It seems like something's bothering Koro-chan. Is he looking for the door?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 957 0 0]It doesn't look like it's on this floor, though...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_100_09_1_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 958 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_101_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 236 0 0]Well, this'll be the fourth memory now. Wish they'd start making sense sometime soon...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_101_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 374 0 0]Maaan, these doors never fail to blow me away. C'mon, open sesame![n][uf 1 1][e]

[msg AST_DNG_REGULAR_101_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 375 0 0]You sure seem eager. What's gotten into you?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_101_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 376 0 0]Ha, I already had a turn! Who's next?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_101_03_1_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 377 0 0]Junpei-san...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 828 0 0]The way Mitsuru-san's father spoke reminded me of my mom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 829 0 0]He sounded angry, but... also sad. Nothing like my mom. So why...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 959 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_09_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 960 0 0]I don't have anything in my hand, so there's no need to nudge it, Koromaru.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 961 0 0]Um, I think he's saying that you can pet him if you want.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_09_1_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 962 0 0]Oh, are you trying to comfort me? Haha... I'm sorry if I worried you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_09_1_4 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 963 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_102_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1106 0 0]I'll do whatever I can to help my sister... so I don't get left behind.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_103_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 237 0 0]I feel awful for Mitsuru-senpai... I wish she could've told us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 238 0 0]Everything happens so fast, you only realize later you can always confide in a friend...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_103_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 239 0 0]You're right...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_103_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 240 0 0]Aw, Fuuka, don't you start getting sad on me, too. It'll be okay![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 241 0 0]Let's just focus on exploring, okay? There's no reason to dwell on these things anyway.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_103_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 521 0 0]Our priority is figuring out what this place is, but I really want to know what's up with that figure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 522 0 0]Something about it makes me uneasy, and I don't know why...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_103_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1107 0 0]Are you tired, Sister? Please let me know if you are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1108 0 0]I can't heal you, but... I'll carry you on my back![n][uf 1 1][e]

[msg AST_DNG_REGULAR_104_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 629 0 0]Reliving that memory has reinforced my desire to protect others with my powers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 630 0 0]That conviction remains. All that has changed is I now have more to protect.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_104_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 830 0 0]So Mitsuru-san was twelve years old in that memory...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 832 0 0][uf 7 3 8 10 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_104_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 385 0 0]Heheheh... I just realized something that no one else has.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 386 0 0]Ladies and gentlemen! We have now reached our 100th floor![n][uf 1 1][e]

[msg AST_DNG_REGULAR_104_03_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 387 0 0]Er, Junpei-kun? I hate to break it to you, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 388 0 0]We're actually on our 103rd floor.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_104_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 389 0 0]Our what?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_105_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 378 0 0]We were all kids once, huh. Even scary people like Kirijo-senpai.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_105_03_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 379 0 0]Iori.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_105_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 380 0 0]Wh-What? I didn't say anything![n][uf 1 1][e]

[msg AST_DNG_REGULAR_105_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 242 0 0]Metis said that all the things we've seen have something in common... Maybe—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 243 0 0]Er, never mind. I'm getting ahead of myself. Let's hurry and check out the next door.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_105_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 523 0 0]Mitsuru must have taken that pretty hard... But you can barely tell. She looks fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 524 0 0]It can't be easy, dealing with all that. She's more impressive than I thought.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_106_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 834 0 0]Running efficiency is determined by how your feet land and your posture...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 835 0 0]I've known that since last year, but I always forget once the fighting starts...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_106_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 964 0 0]It's important to stay hydrated when you're using so much energy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 965 0 0]Especially for you, Koro-chan. Let Aigis know whenever you need water, okay?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_106_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 966 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_106_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1109 0 0]From what we've seen, I predict the next door will be much further ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1110 0 0]But I'll get you there, Sister! Just make sure you're prepared for battle.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 244 0 0]I need to pull myself together, but I just can't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 245 0 0]I know my nerves aren't making things any easier, either...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_02_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 246 0 0]Woof.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_02_1_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 247 0 0]...He just told me to chill out, didn't he?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 352 0 0]Weee've been walkin' in this daaamn maze, aaall the livelong daaay! ♪[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 353 0 0]Wasn't very uplifting, huh...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_03_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 354 0 0]Well, if nothing else, it's nice you're cheery enough to sing.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_107_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 631 0 0]We've all become adept at exploring, but we still must rest when necessary.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 632 0 0]I'd consider returning while we still have some leeway.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_108_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 525 0 0]Exploring's not so bad, is it? We can fight all we like on our way down.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_108_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 836 0 0]I'm starting to remember that using a spear takes more than just arm strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 837 0 0]But just knowing something doesn't necessarily make it easy to act on...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_108_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 967 0 0]Koro-chan's tail is as straight as an arrow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 968 0 0]Maybe that means something, like... He's confident in his own strength![n][uf 1 1][e]

[msg AST_DNG_REGULAR_108_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 969 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_109_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 510 0 0]It's unnerving, being trapped here, but if we view this as a chance to focus on training, it'll all be worthwhile.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_109_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 511 0 0]Uh, 'scuse me, sorry, just one thing—we're not training here, we're exploring...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_109_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 890 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_109_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 891 0 0]Koro-chan's in high spirits. Maybe he's adrenalized after the last battle.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 390 0 0]Our surroundings may have changed, but I can feel the truth deep in my bones...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 391 0 0]The road forward will be quite long![n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_03_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 392 0 0]Yes, it probably will be very long indeed, Junpei-san...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 393 0 0]Quite![n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 635 0 0]It is truly a precious opportunity, being able to spend time with you all like this.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 970 0 0]Koro-chan doesn't seem to like it when the scenery is suddenly different.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_110_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 971 0 0]Woof...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_111_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 394 0 0]Stay sharp out there, guys! One mistake can cost you everything![n][uf 1 1][e]

[msg AST_DNG_REGULAR_111_03_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 395 0 0]Very convincing coming from you, Junpei.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_111_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 396 0 0]Whoa! When I said "stay sharp," I didn't mean with your words! They cut, y'know?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_111_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 526 0 0]If it's one thing I learned after getting this far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 527 0 0]...It's that I'm not where I used to be back in my heyday. I need to train even harder.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_111_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 838 0 0]Phew, my legs are starting to get tired. How pathetic...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 839 0 0]I got used to it in Tartarus, but the floor layouts always changing is unsettling.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 840 0 0]I didn't mind it much before, but it's not something I really want to get used to...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_08_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 841 0 0]Agreed. Desensitization to something so abnormal would be quite disconcerting.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_08_1_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 842 0 0]Yeah... I-It would...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 972 0 0]Arf?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 973 0 0]Hehe... Koro-chan keeps looking back to check on everyone. What a kind soul.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1112 0 0]Humans are supposed to become fatigued from prolonged exercise...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1113 0 0]So the humans with us must be physically exceptional.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_112_11_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1114 0 0]Heh... Our training's not just for show, you know.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_113_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 397 0 0]You know, exploring with everyone again got me thinking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 398 0 0]Mostly about how dumb I was last year... And how much more I could've done.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_113_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 528 0 0]To think... We're all being held prisoner by time. Strange, huh? It's not even tangible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 529 0 0]It'd be nice if we could simplify things, like move time by breaking walls or something.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_113_04_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 530 0 0]Where is the logic in that?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_113_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 726 0 0]I'm having trouble with some of those notes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 727 0 0]They're quite detailed, but not very orderly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 728 0 0]I think I'm going to need more time to figure them out. Please sit tight, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_114_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 636 0 0]There are no limits to how much we can improve ourselves.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 637 0 0]Any level of skill lost can eventually be regained.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_114_05_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 638 0 0]That's right—training never ends. Glad to see you get it now.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_114_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 843 0 0]You can trust me to watch our backs. I've gotten pretty good at it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_114_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1115 0 0]Sister, you look so dignified walking out in front, leading us![n][uf 1 1][e]

[msg AST_DNG_REGULAR_115_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 531 0 0]Before all this, I'd never have imagined repeating the same day over and over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 532 0 0]...What does this mean for my training schedule, then?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_115_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 533 0 0]Oh yeah, that thing. That thing that's totally booked for the next six months?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_115_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 639 0 0]The sheer number of Shadows here seemed odd to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 640 0 0]Though it appears more logical if this place truly is related to Tartarus.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_115_05_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 641 0 0]Yes, I agree. I'll try to find anything that can confirm that connection for sure.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_115_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1116 0 0]The most important thing to me is my sister. And that's not going to change.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_116_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 250 0 0]I'm feeling better now after all this moving around... Well, a little bit better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 251 0 0]There's just a lot on my mind... Honestly, I feel as if I'm drowning in my thoughts.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_116_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 399 0 0]Man, all this walkin' is really puttin' some wear and tear on my poor kicks...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 400 0 0]Thought I wouldn't have to change 'em out for a while after last year.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_116_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 844 0 0]It feels like Metis-san is kind of wary of us again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 845 0 0]It's better than it was at first, but it'd be nice if she started trusting us more.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_116_08_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 846 0 0]I don't think I'm wary...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 847 0 0]I just don't understand...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_117_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 534 0 0]That figure showed up to set the stage for our fight on the next floor, didn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 535 0 0]Heh, doesn't matter what Shadows are lying in wait for us. They're all going down.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_117_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 642 0 0]If Metis is right, that figure may have something to do with our situation...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 643 0 0]Either way, we'll have to catch it to find out. Let's go, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_117_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 974 0 0]Grrr...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_117_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 975 0 0]Koro-chan's been on edge ever since he saw that shadowy figure...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 976 0 0]I wonder what he senses about it...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_118_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 848 0 0]I'm worried about that figure and what its ultimate goal might be...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_118_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1117 0 0]That unrecognized figure ran away again. It probably wants us to go after it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1118 0 0]How annoying...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_119_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 401 0 0]Huh, the scenery's changed again. Guess that means we still got a ways to go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 402 0 0]We've seen that so many times now that even I caught on![n][uf 1 1][e]

[msg AST_DNG_REGULAR_119_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 644 0 0]The seemingly never-ending floor count does remind me of Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 645 0 0]We can only hope that number won't be as high as last time...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_119_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 977 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_119_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 978 0 0]Koro-chan seems enthusiastic, but I hope he's not just forcing it for our sakes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 979 0 0]This expedition has been going on for some time. I'm worried about him...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_120_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 536 0 0]Train as though you're in a real battle... Battle as though you're training.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 537 0 0]Gotta be in top form at all times.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_120_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 849 0 0]Spears are great in battle, but they can be kinda heavy to carry...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_120_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1119 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1120 0 0]I'm fine. Nothing's wrong...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_121_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 254 0 0]What the doors all had in common... The things Mitsuru-senpai knew...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 255 0 0]I need to think this all over some more...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_121_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 538 0 0]Hm... I can't seem to organize my thoughts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 539 0 0]Sorting my head is starting to be just as difficult as physical training.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_121_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 646 0 0]Aigis, remember to give adequate support to each member of the team.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 647 0 0]I'd like to myself, but I'm not sure I'll be able to manage on my own...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_122_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 403 0 0]The li'l sis seems kinda huffy, don'tcha think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 404 0 0]Sure, she's always had an attitude with us, but... I dunno. It's different this time.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_122_03_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 405 0 0]I am not huffy.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_122_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 406 0 0]Crap, she heard me.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_122_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 729 0 0]I wonder why this place exists, and how it came to be...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_122_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 850 0 0]It seems like there are as many Shadows here as there were in Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 851 0 0]I hope Fuuka-san will figure out why. There's too much we don't know...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 256 0 0]I feel like I'm starting to get back into the groove, but really I'm just scraping by.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 257 0 0]Heck, I used to— Ugh, never mind, why bother comparing?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 540 0 0]We'd be able to exploit the Shadows' weak points more easily if we knew more about their anatomy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 541 0 0]It's frustrating how differently they're built from humans.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_04_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 542 0 0]Wow, Sanada-san knows the human body's weak points... Incredible.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1121 0 0]Maybe I don't fit in because... I really am just a kid?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1122 0 0]No, that can't be it... Definitely not... Right...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_11_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1123 0 0]Metis, are you all right? Do you need a break?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_123_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1124 0 0]No, I'm fine! I'm fine...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_124_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 407 0 0]Whoa! I nearly tripped and tumbled over just now. Watch your step, Ai-chan![n][uf 1 1][e]

[msg AST_DNG_REGULAR_124_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 648 0 0]Despite its inconvenience, this situation has provided a valuable experience.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_124_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 980 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_124_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 981 0 0]Koro-chan's right behind you all, just like he was last year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 982 0 0]I get the sense he won't back down for anything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_125_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 252 0 0][uf 7 3 2 10 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_125_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 253 0 0]Yukari-chan's been really quiet, hasn't she...? I'm a bit worried about her.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_125_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 509 0 0]I can take out the weaker enemies here no sweat. I'm ready for a challenge.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_125_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 633 0 0]Perhaps I ought to help Yamagishi analyze those documents, rather than leave it all to her...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_125_05_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 634 0 0]Oh, not at all! You're needed on the battlefield. Leave the paperwork to me![n][uf 1 1][e]

[msg AST_DNG_REGULAR_126_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 852 0 0]There's no room for hesitation now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 853 0 0]Whatever caused this whole thing is waiting for us, so let's go.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_126_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1125 0 0]Sister, it's the door! Go ahead, open it yourself.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 649 0 0]Yukari has remained consistent in her ability to fight with undaunted resolve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 650 0 0]That side of her saved me once, and for that, she will always have my gratitude.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_05_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 651 0 0]Uh, I can hear you, you know.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_05_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 652 0 0]Yes, I would assume you could. And?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_05_1_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 653 0 0]Mitsuru-senpai... You're sure not afraid to be direct, huh?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 730 0 0]Metis might be right about the past being all we talk and laugh about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 731 0 0]I feel like the future hasn't been a very pleasant topic lately...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 732 0 0]Not just since we got trapped in here, but since... that day...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_127_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1126 0 0]I'm not sulking or anything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1127 0 0]I just... don't get to talk to my sister as much as all of you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 408 0 0]I think Yuka-tan's been feelin' off lately. Kinda like how she was when I first joined.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 409 0 0]We should do something for her, remind her that we're there for her, y'know?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_03_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 410 0 0]I can hear you.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 411 0 0]Whuh!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_03_1_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 412 0 0]Honestly... There's no need to go out of your way and do anything weird, all right?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 544 0 0]Aigis's sister has a point. These memories are all important—and painful, at that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 545 0 0]The fact she won't tell us where she came from still rubs me the wrong way, though.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_04_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 546 0 0]I'm not trying to rub you in any which way. I don't even care what you think.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_04_1_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 547 0 0]Hmph.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_128_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 854 0 0]This place was always weird, but now it's getting scary too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 855 0 0]I wonder what we'll see in the next door. We've got to be ready for anything...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 413 0 0]So... I was the only one who didn't get what the doors all have in common, huh?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_03_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 414 0 0]Don't sweat it. Wouldn't be the first time.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 415 0 0]Hey, what're you tryin' to say!?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 983 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_09_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 984 0 0]What is it, Koromaru? Did you find some Shadows?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_09_1_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 985 0 0]Actually, I think he just wants you to pet him.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_09_1_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 986 0 0]Oh, is that what it is? Well... Maybe later. We should stay focused for now.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_09_1_4 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 987 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1128 0 0]What to say, what to say...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1129 0 0][uf 7 3 11 3 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_129_11_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1130 0 0]Uh... Approaching others is tough, huh? Maybe just try to relax a little.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_130_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 258 0 0]Now that we know what the doors have in common... how do we get rid of the Abyss?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 259 0 0]Well, no point wasting time thinking in circles. We just have to keep moving.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_130_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 548 0 0]Amada basically suggested we reflect on our reasons, but... I'm drawing a blank.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 549 0 0]Feels like I'm off my game. Like I'm doing mittwork and nothing's landing.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_130_04_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 550 0 0]Oh, a classic Sanada-san-ism! Totally flies over your head if you're not into boxing![n][uf 1 1][e]

[msg AST_DNG_REGULAR_130_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 988 0 0]*whine*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_130_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 989 0 0]Koro-chan seems down... Maybe he has something on his mind.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_131_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 654 0 0]The past has been far from exclusively blissful, and yet...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 655 0 0]What your sister said is undoubtedly true, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_131_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 733 0 0]There's a lot to think about. I should've already been thinking about it all...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_131_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 856 0 0]I'm thinking about what'll come up next and what we might have to do...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 857 0 0]Whatever it is, I'm sure it'll be tough.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_132_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 260 0 0]Are we making any progress? Everything looks the same as ever, so it's a bit worrying.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_132_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 416 0 0]Once li’l sis' mask thing comes down, there's just no getting through to her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 417 0 0]Guess there's not much we can do if she just shuts us out like that.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_132_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 551 0 0]The experience gleaned from battling is invaluable. Last year really drove that home for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 552 0 0]But it's hard to find a place where combat is a daily occurrence... At least in Japan.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_133_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 656 0 0]I've been thinking about engaging in more "small talk" lately...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 657 0 0]But I find it exceedingly difficult. Perhaps it's just not one of my strengths.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_133_05_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 658 0 0]Well, uh, it ain't really somethin' you can just decide to be good at.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_133_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 858 0 0]This is much simpler than last year. All we have to do is keep exploring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 859 0 0]But unlike last year, we can't leave whenever we want...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_133_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1131 0 0]This is difficult. Though I'm not sure what about it is difficult...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1132 0 0]Maybe that's why it's difficult...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_134_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 418 0 0]Wasn't Fuuka's reaction kinda weird? What's she tryin' to say about that figure...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_134_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 990 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_134_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 991 0 0]Huh... The way Koro-chan reacted just now... Could it mean...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_134_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1133 0 0]Let's go after it quickly. We need it to get out of here.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_135_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 261 0 0]That figure, it's...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 262 0 0]Actually, never mind. We'll learn what it is once we catch it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_135_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 553 0 0]That was supposed to stop us? Seems they're underestimating us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 554 0 0]Let's hurry. We'll definitely catch that figure.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_136_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 419 0 0]Dunno 'bout you guys, but I'm pooped. All the more reason to get pumped![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 420 0 0]Lookin' like crap just makes you feel even worse, y'know?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_136_03_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 422 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_136_03_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 423 0 0]Yeah? You get me, bud? 'Preciate you, I really do, Koromaru![n][uf 1 1][e]

[msg AST_DNG_REGULAR_136_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 860 0 0]Looks like we've made some more progress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 861 0 0]It's not ideal that our surroundings changing is our only indication of that, though...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_136_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1134 0 0]It feels different here... We need to be prepared for anything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_137_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 555 0 0]Only easy pickings around here, huh... Perfect. Just what I needed to lift my mood.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_137_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 661 0 0]For most of last year, our goal and how to achieve it seemed relatively clear. But now...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_137_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 734 0 0]I've been making some progress going through those notes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 735 0 0]I'll be able to share what I find soon. I should probably organize it all first...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_138_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 424 0 0]The Shadows ain't gonna go any easier on us just 'cause we're off our game.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 425 0 0]They didn't last year, and they sure won't start now. Wish they'd chill, though.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_138_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 556 0 0]Our priority right now is to press forward and keep exploring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 557 0 0]We can't afford to waste any more time getting lost.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_138_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 992 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_138_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 993 0 0]Koro-chan's back in high spirits. Did seeing that figure do something...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 994 0 0]Hm... I'm probably just overthinking it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_139_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 662 0 0]It feels as if doing all we can is never enough. It's frustrating...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_139_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 862 0 0]She can't tell us anything about herself because she has no memories...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 863 0 0]I wonder if that's true or if Metis-san just doesn't want us to know.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_139_08_1 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 864 0 0]I have nothing to say to that.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_139_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 995 0 0]Koro-chan never leaves Aigis's side... Maybe he's protecting her.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_139_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 996 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 263 0 0]Hurry, we have to catch up...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 264 0 0]I know saying it out loud won't make a difference, but still, I just have to...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_02_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 265 0 0]Yukari-chan...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 426 0 0]Runnin' around, seein' the same sights over again... Now that's what I call good exercise![n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1135 0 0]I just have to protect my sister. That's what I'm here to do...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_11_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1136 0 0]What're you sulking about? Something wrong?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_140_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1137 0 0]I'm not sulking.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 427 0 0]Exploring's dangerous and tiring, yeah, but sittin' on our asses is just not an option.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 663 0 0]Everyone seems to be weighed down by something. It's similar to last...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 664 0 0]No, we should focus on our current predicament. In fact, we need to.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1138 0 0]Um... Sister...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1139 0 0]Uh, never mind, it's nothing.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_11_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1140 0 0]*whine* Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_11_1_2 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1141 0 0]No. Bad. Don't be so nice to me...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_141_11_1_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1142 0 0]Huh... What's that supposed to mean...?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_142_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 266 0 0][uf 7 3 2 2 65535]......[n][uf 1 1][e]

[msg AST_DNG_REGULAR_142_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 558 0 0]Last year, we fought so that we could live to see tomorrow...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 559 0 0]Who'd have thought we'd be stuck in time and may never see tomorrow again...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_142_06_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 736 0 0]At least we know a lot more than we did at first, but I'm still feeling uneasy...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_143_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 428 0 0]You know, we've been so busy lately that I haven't had much time to stop and think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 429 0 0]But now that we're stuck exploring, I've been looking back on all kinds of stuff...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_143_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 665 0 0]Manipulation of time... It reminds me of my grandfather's original goal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 666 0 0]I can't say I've ever shared his desires.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_143_09_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 997 0 0]Koro-chan keeps checking on you all like he's looking out for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 998 0 0]He really seems like a leader...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_143_09_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 999 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_144_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 560 0 0]It's finally showed itself to us. Now we just chase it down—all there is to it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_144_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 865 0 0]If whatever it is we need to see is at the end, we just have to push through to it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 866 0 0]That's all we have to do. In fact, it's all we can do.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_144_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1143 0 0]We have to keep moving. Um, not that I think you don't know that, Sister...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_145_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 667 0 0]I believe it'd be wise to put stock in Yamagishi's earlier report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 668 0 0]All that's left is to confirm it with our own eyes. Let's go, Aigis.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_145_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1000 0 0]Grrrrr...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_145_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1001 0 0]Koro-chan seems restless, even with that strong enemy defeated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1002 0 0]Maybe he senses what's waiting up ahead...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_146_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 268 0 0]Huh? Our surroundings changed again. That's a sign of progress... Right?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_146_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 430 0 0]Alright, back in the game! Let's wrap this up, so we can get the hell outta here![n][uf 1 1][e]

[msg AST_DNG_REGULAR_146_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 561 0 0]The Shadows here might be different since we're in a new area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 562 0 0]Let's change up our battle strategy if needed. Gotta stay light on our feet.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_147_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 868 0 0]It's weird to think this is technically all one day, even though it feels so long.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_147_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1003 0 0]Arf![n][uf 1 1][e]

[msg AST_DNG_REGULAR_147_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1004 0 0]Koro-chan's always so bold and confident... He's amazing.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_147_02_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1144 0 0]I have to be helpful to my sister. That's my only purpose...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_148_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 431 0 0]I know it's kinda late to ask, but... What the heck is behind this whole time loop thing?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_148_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 563 0 0]Even the weaker Shadows can still pack a punch. Best we can do is return the favor.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_148_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 669 0 0]As tempting as it may be to proceed hastily, let's remain cautious.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_149_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 869 0 0]I feel... strange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 870 0 0]I want to get to the end, but I also kind of don't...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_149_09_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1005 0 0]*pant* *pant*[n][uf 1 1][e]

[msg AST_DNG_REGULAR_149_09_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1006 0 0]Koro-chan's staring at Aigis. What's he trying to say to her...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1007 0 0]I can't tell, but even so, just the look in his eyes makes me feel relieved.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_149_11_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1145 0 0]I've said it before, but one more time... Actually, I'll probably keep saying it many more times...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1146 0 0]I'm here for you, Sister. And I always will be.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_150_02_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 269 0 0]I think... We're nearly there. Just a little longer now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 270 0 0]Well, I hope so at least. I don't really know if we are or anything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_150_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 432 0 0]Kinda hard to breathe down here, huh? I mean, we've gotten pretty far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 433 0 0]No? Just me?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_150_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 489 0 0]No need to push yourself, Aigis. Breaks are also essential to a proper regimen.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_151_03_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 434 0 0]Think we'll be able to bust outta here soon? And finally be done with the 31st...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 435 0 0]Wonder if folks'll think it's weird we all got super buff in a day...[n][uf 1 1][e]

[msg AST_DNG_REGULAR_151_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 670 0 0]What I must do— No... What I myself want to do hasn't changed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 671 0 0]Nor will it, no matter what awaits us. Surely, you feel the same, Aigis?[n][uf 1 1][e]

[msg AST_DNG_REGULAR_151_08_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 871 0 0]I keep wondering about what could be ahead of us, causing all this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 872 0 0]Maybe there's no way to know, and it's pointless trying to figure it out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 873 0 0]But... I want to keep thinking about it anyway.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_152_05_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 659 0 0]I seem to be regaining my combat abilities at a reasonable rate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 660 0 0]Whatever gets in my way, I'm ready to face it.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_152_04_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 564 0 0]There's no telling what we're up against... till we come face-to-face with it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 565 0 0]Which means we just need to focus on preparing for anything and everything.[n][uf 1 1][e]

[msg AST_DNG_REGULAR_152_00_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 1147 0 0]I really respect your determination, Sister. I always have.[n][uf 1 1][e]

