[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]When I close my eyes...[n]I remember the last moment[n]I spent with him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]The day he fell asleep...[n]We brought him back to our dorm,[n]fear beginning to well up within us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]And the next morning,[n]our fears became reality.[n]He was lost to us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]For some time after that, I fell into[n]depression, and began having the[n]same dream night after night...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]A dream where I run after him, calling[n]his name... but can never catch up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]When he was alive, I promised to protect[n]him, and I made that my reason for living.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]But now... that promise can never be fulfilled.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Then one day, my sadness suddenly[n]left me, as if a mysterious fog had lifted.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]I stopped dreaming... and I[n]now no longer require sleep.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 11 0 0]It's no use. I can't sleep...[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 12 0 0]Can I really continue living like this...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 0 0 0 13 0 0]...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 14 0 0]A butterfly...?[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 17 7 2 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 15 0 0]Huh? What's going on!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Aigis, are you awake!?[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 17 0 0]Ah, yes...! The door is open.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 6 65535 0 0][uf 3 1 1 0 0 18 0 0]Aigis, come quick! We need you![n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 19 0 0]Has something happened?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 20 0 0]Are we... under attack!?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 6 65535 0 0][uf 3 1 1 0 0 21 0 0]It's hard to describe. The lobby floor suddenly opened up, and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Anyway, we need to hurry to the lounge![n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 23 0 0]Understood![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]Come to think of it, that[n]day I stopped dreaming...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]That must have been[n]when all this actually began.[n][uf 1 1][e]

