[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I enjoy reading novels with Fuuka.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Fuuka seems to be having fun too...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 3 1 6]I don't know why, but I feel so calm when I have someone reading next to me.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 0 1 1 0][n]have improved thanks to the[n]skillful expression in the writing...[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]It's getting pretty late. Should we wrap up for the night?[n][uf 1 1][e]

