[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Listen up, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Now that we're good and stuffed, how 'bout we take a picture together?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]A picture?[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Actually, I did try to take one last night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 5 0 0]'Cept I forgot it doesn't work during the Dark Hour.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 2 65535 0 0][uf 3 1 1 0 0 6 0 0]You mean you brought a camera with you to the battle?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Well, yeah. I mean, it was our last battle and all.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 8 0 0]'Scuse me, mister! You mind takin' our picture?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Ugh, I feel like such a tourist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 2 1 25 25]But y'know, I do kinda want a picture, too.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, wait. Ikutsuki-san and Aigis aren't here. I guess we'll have to take another one later.[n][uf 1 1][e]

[msg MSG_007_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Alright, everyone get together.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 13 0 0]C'mon, squeeze in tight! Everyone get real close to me![n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]You want me close, too?[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 15 0 0]Uh, no, not you.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Ah, geez, don't make the poor camera guy wait all day![n][uf 1 1][e]

[msg MSG_011_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Hey, we're good to go. You can take the picture whenever![n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 18 0 0]How's this for a pose!?[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 19 0 0]Hey, get your hand outta my face![n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Is it just me, or did this not get my good side?[n][uf 1 1][e]

[msg MSG_014_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 21 0 0]We'll just take another one when Aigis and Ikutsuki-san get back, alright!?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Yes, yes, we hear you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 23 0 0]I could really get used to this worry-free lifestyle.[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Woof![n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 25 0 0]How about you, Koro-chan? Are you excited for all this meat?[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Woof![n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]The celebration party continues...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I spent a moment of relaxation[n]with my battle-weary friends...[n][uf 1 1][e]

