[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]I'm getting a reading of a small organism... Is this a person? Look around on this floor, just in case.[n][uf 1 1][e]

[msg MSG_000_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5101 0 0]I'm getting a faint reading of a living thing...! It could be a person, so please try looking for them.[n][uf 1 1][e]

