[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Yes, correct. The answer is "May blues." Next, for the following sentence...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]What's the matter, Iori? Feeling the May blues?[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Wha!? Oh, uh, it's nothing![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Um, Kirijo-senpai! About this question here...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Hey, [uf 4 2]... You smell that? It's insane...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Smell what?[e]
[uf 0 5 65278][uf 2 1]Focus.[e]
[uf 0 5 65278][uf 2 1]I'm getting hungry...[e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]You know what I'm talking about! There's this floral scent coming from Kirijo-senpai's direction...[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]How do you expect me to do that!? C'mon, that fragrance across the table is just...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Come on, man, get your priorities straight! Don't you notice when a sensual fragrance comes your way!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Yeah, I know what you mean. To be honest, I can't get enough of it.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Aha! Now that's what I'm talkin' about, Sanada-san![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Man, this is heaven... Such grace, such elegance! Truly the fragrance of the upper class![n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I'd personally describe it as... stimulating. I can almost taste the juicy tenderness.[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Uh, what?[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Oh, I was heating up a beef bowl for a late-night snack. Smells pretty good, right?[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]...A beef bowl? That's what you were talking about!?[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]My mouth is watering.[e]
[uf 0 5 65278][uf 2 1]I've been waiting for this![e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Not you too! C'mon, guys like us should be thinking with our... Well, not our stomachs![n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Ahaha... Sanada-san, you don't happen to have any extra, do you?[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]No eating until you've gotten some work done. Stay focused, [uf 4 1]—keep your hand moving.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]The enticing smell of the beef bowl[n]motivated me more than usual...[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Beef, beef, beeeeeef![n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]For goodness sake... All right, if you answer five more questions correctly, you can have your food.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 8 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Hraaaaaah! Beef. Beef! BEEEEEEF![n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You're like a horse with a carrot dangled in its face...[n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]One mention of food, and you finally give a crap. That's all it takes, huh?[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]All right, that should be enough for tonight. Make sure not to eat too much before bed.[n][uf 1 1][e]

