[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]There's a crowd forming in[n]front of the bulletin board...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I'll take a peek before[n]going to the faculty office...[n][uf 1 1][e]

[msg MND_001_0_0 [Junpei Iori]]

[msg MSG_002_0_0 [Junpei Iori]]

[msg MND_003_0_0 [Junpei Iori]]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I'll head to the entrance[n]of the Velvet Room...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]We should try gathering information[n]at the outskirts of the station...[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]

[msg MSG_019_0_0 [Junpei Iori]]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I should head to the faculty office...[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]Class has ended for today.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...My whole body feels sluggish. I'm[n]too exhausted to fight the fatigue.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The third-years' graduation[n]ceremony is tomorrow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to bed early tonight.[n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2002 0 0]Should we also take a look around the school, while we're at it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I'll just follow you around. If you want to leave, head for the front entrance.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Today's lessons have ended...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There are plans for a celebration[n]to be held tonight...[n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2025 0 0]Well, I was just headed there myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You know the place, right? Let's go.[n][uf 1 1][e]

