[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 202 65535 0 0][uf 3 1 3 0 65535 2094 0 0]Huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 202 65535 0 0]People make cooking look so easy. I thought I could just whip something up, lickety-split.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 202 65535 0 0]Hey, Ai-chan, is cooking actually... really hard?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]It appears so.[e]
[uf 0 5 65278][uf 2 1]I'm not sure myself.[e]
[uf 0 5 65278][uf 2 1]Only because you lack skill.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 202 65535 0 0][uf 3 1 3 0 65535 2062 0 0]...Yep, sure does.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 202 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Yeah, I don't got a clue, either...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 202 65535 0 0][uf 3 1 3 0 65535 2062 0 0]W-Well, that's just a matter of perspective! Pretty sure.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 202 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Whatever! 'Sides, it's way too early to throw in the towel![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 202 65535 0 0]If I give up now, then the only thing I managed to do was fail![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 202 65535 0 0]C'mon, Ai-chan! Let's put our heads together and turn the dang tables, yeah?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, let's![e]
[uf 0 5 65278][uf 2 1]I fear it is too far gone...[e]
[uf 0 5 65278][uf 2 1]But this table cannot be turned.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 202 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Hell yeah! We've got this in the bag. Now's my chance for a heroic comeback![n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 202 65535 0 0][uf 3 1 3 0 65535 2034 0 0]No way! Stop with that quitter talk. The time for action is now![n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 202 65535 0 0][uf 3 1 3 0 65535 2034 0 0]Oh, c'mon, don't pull a Sanada-san on me! You'll see, I won't lose here! I'll come out on top for sure![n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 8 202 65535 0 0]Alright, time to unleash my ultimate attack! Eat thiiis![n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 202 65535 0 0][uf 3 1 3 0 65535 2108 0 0]Damn, can't believe I actually turned that disaster of a dish into a tasty, chunky curry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 202 65535 0 0]That roux sure is one hell of a miracle worker.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 202 65535 0 0]I know Sanada-san told me to be more realistic, but you really can turn the tables in an instant.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]It's certainly possible.[e]
[uf 0 5 65278][uf 2 1]That may not happen every time.[e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 202 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Exactly! That's why you just gotta go for it, y'know?[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 202 65535 0 0][uf 3 1 3 0 65535 2063 0 0]Well, yeah, sure. But you know...[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 202 65535 0 0]Maybe some folks prefer to pull back and try again later because... Because they're confident they'll succeed next time.[n][uf 1 1][e]

[msg MSG_016_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 202 65535 0 0][uf 3 1 3 0 65535 2077 0 0]But me? Not so much. I just kinda panic—like, I gotta do something NOW 'cause there might not be a next time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 202 65535 0 0][uf 4 23 0 1 0 25 25]Guess that's why I like those ultimate attacks so much—they can turn things around in just one move.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 202 65535 0 0][uf 4 23 0 1 15 25 25]Maybe I'll be strong enough to pull one off whenever, wherever I want someday.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]It seems Junpei-san[n]experienced an epiphany...[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 202 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Welp, I'm stuffed! How 'bout we put all this away and get goin'?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 202 65535 0 0]Thanks for hangin' with me, Aigis![n][uf 1 1][e]

