[msg MSG_000_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 1 0 0]Hello, this is Elizabeth speaking.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 2 0 0]I'm calling in regard to a recent change in Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 3 0 0]It seems that a path that had been blocked off is now open.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 4 0 0]I thought it prudent to inform you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 5 0 0]Well then... I wish you a safe journey.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Elizabeth said that a previously[n]blocked path is now open.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should check it out next[n]time I go to Tartarus.[n][uf 1 1][e]

