[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5074 0 0]Oh, by the way, Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]You've encountered a human-like figure a couple of times in the Abyss, right? Did you sense anything peculiar about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]All I could tell through Juno was that it seemed to be another person...[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30032 0 0]"Another person"? No way, that's impossible. We were the only ones down there.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]We can talk till we're blue in the face about it. Won't make a difference.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]As long as it keeps showing itself, we'll catch it. You can bet on that—and that's really all there is to it.[n][uf 1 1][e]

