[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30070 0 0]By the way, I've been wondering...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]What's in the room all the way down the hall on the second floor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]I get the strangest feeling when I stand in front of it. Could it be...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Down the hall on the second floor... Do you mean his room?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 3 0 65535 1090 0 0]...The upper floors are none of your business. Quit being so nosy.[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]You don't have to get so mad...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Well, our job right now is to explore this place... So come on, let's go.[n][uf 1 1][e]

