[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Despite the summer heat, I manage[n]to pay attention to the lecture.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]It's the first day of summer school...[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]It's the third day of summer school...[n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]It's the fourth day of summer school...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]It's the last day of summer school...[n][uf 1 1][e]

