[msg MSG_801_1_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 1 0 5]You're up against a difficult opponent. But if the intel is available, I can help you.[n][uf 1 1][e]

[msg MSG_801_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 2 0 5]I can suggest the most effective attack, based on the enemy's weakness.[n][uf 1 1][e]

[msg MSG_801_1_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 3 0 5]But, I can only assist like this when we know the enemy's weakness.[n][uf 1 1][e]

[msg MSG_801_1_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 4 0 5]I'm sorry, but until you can get more information, you'll be on your own.[n][uf 1 1][e]

[msg MSG_801_2_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 2 5 0 6]The enemy here looks tough. But if we have any intel on them, I can help you.[n][uf 1 1][e]

[msg MSG_801_2_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 2 6 0 6]I can tell you what attack will work best based on the enemy's weakness.[n][uf 1 1][e]

[msg MSG_801_2_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 2 7 0 6]But, I can only assist you like that when we already know what an enemy's weak to...[n][uf 1 1][e]

[msg MSG_801_2_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 2 8 0 6]You'll need to analyze them first before I can help.[n][uf 1 1][e]

[msg TRL_801_1_1]
[uf 0 5 65278][uf 2 1]Press the R1 button during battle to use the Assist function.[n][uf 1 1][e]

[msg TRL_801_1_2]
[uf 0 5 65278][uf 2 1]If there is a skill available that can strike the enemy's weakness, then the cursor will automatically highlight it.[n][uf 1 1][e]

[msg TRL_801_1_3]
[uf 0 5 65278][uf 2 1]This will help speed up menu navigation during battle, so give it a try.[n][uf 1 1][e]

