[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 1 0 0]What a sight...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 2 0 0]I thought I was accustomed to Christmas decorations by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 3 0 0]But for some reason, they look especially beautiful today.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Not as beautiful as you.[e]
[uf 0 5 65278][uf 2 1]So, what's next?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 40 0 0][uf 3 1 1 0 0 4 0 0]Er— Hey, don't tease me.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 40 0 0][uf 3 1 1 0 0 5 0 0]Er— You mean after this? Well...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 6 0 0]What would you like to do?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 7 0 0]I would honestly be fine with anything...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 8 0 0]Well, shall we stroll around for a bit?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 9 0 0]Even a simple walk with you is quite pleasant.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 10 0 0]No manner of extravagant party could offer an experience like this.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 11 0 0]Here. I'd like you to have something.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Received (Item name)[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 12 0 0]I put in a special order for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 5 1 25 25]My hope is we take some time to enjoy it together, once things have settled down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 14 0 0]I'm glad I was able to give this to you today. Thank you, [uf 4 1].[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 15 0 0]For once, I feel... calm. Like I'm finally at peace.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 16 0 0]I should probably let you know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 40 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 5 3 25 25]When I see you enjoying yourself with Yukari or the others, I get... restless.[n][uf 1 1][e]

[msg MSG_011_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 40 0 0][uf 3 1 1 0 0 18 0 0]But at the same time, it's a pleasure to be reminded of these feelings I have.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 1 0 0 19 0 0]In all honesty... I never thought I'd be allowed to be this happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 40 0 0][uf 3 1 0 0 0 20 0 0]......[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I shared a tender moment with Mitsuru...[n][uf 1 1][e]

