[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Eek![n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 2 0 0]There it is![n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Hey, get back here![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 4 0 0]Wait![n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 50 0 0][uf 3 1 1 0 0 5 0 0]The enemy is acting strangely. I have a bad feeling about this.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 6 0 0]But if we don't go after it, we're gonna lose it![n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 7 0 0][uf 4 1], you're in command right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 8 0 0]What do you think of the situation?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]We should be careful.[e]
[uf 0 5 65278][uf 2 1]We should go after it.[e]
[uf 0 5 65278][uf 2 1]I don't know.[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 9 0 0]I agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 10 0 0]It would be dangerous to chase after it blindly.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 11 0 0]So what if it's dangerous!? We can't just stand here and let it get away![n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 12 0 0]But why did it flee after revealing itself? I can't make sense of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 13 0 0]Just be careful.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 14 0 0]I don't have any more information, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 15 0 0]Just be careful.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 16 0 0]We can beat that thing no problem![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 17 0 0]Hell, I'll do it myself![n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Junpei! Wait![n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 50 0 0][uf 3 1 1 0 0 19 0 0]Watch out! Behind you![n][uf 1 1][e]

