[msg MSG_000_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]You there...[n][uf 1 1][e]

[msg MSG_001_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]You live in a world where emptiness roams and chaos reigns...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]You struggle so fervently, twinkling like stars in the night, but such delusion will not lead to deliverance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Why not join us and the Messiah, and await the moment of salvation?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]We still have time.[e]
[uf 0 5 65278][uf 2 1]I'm busy right now.[e]

[msg MSG_003_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]You say that only because you don't know the truth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]Heed the voice of the Messiah, and follow the path to true salvation.[n][uf 1 1][e]

[msg MSG_004_0_0 [Suspicious-Looking Man]]

[msg MSG_005_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]Time will not wait.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]If you wish to hear the voice of the Messiah, you must make haste...[n][uf 1 1][e]

[msg MND_006_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]That suspicious man that preached to me[n]is staring at me from over by the wall...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Once he starts, it's probably going[n]to take a while for him to finish...[n][uf 1 1][e]

