[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 3 0 65535 10869 0 0]I swear I usually don't go jumpin' into fights or anything...[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0]Man, can you believe they were startin' shit? Talk about being a sore loser.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0]Did they seriously think they could stand a chance against me in a real fight?[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]If you didn't stop me back there, I probably would've beaten the crap outta them...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10845 0 0]Anyway... Sorry about all of that.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]You'd be in trouble.[e]
[uf 0 5 65278][uf 2 1]I was worried about you.[e]
[uf 0 5 65278][uf 2 1]Gotta pick your battles.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 3 0 65535 10882 0 0][uf 5 13 8 15 105]Guess you're right. Not like I'd lose to a bunch of tantrum-throwing nobodies anyways.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 4 23 0 105 3 25 25]But yeah... It's pretty stupid to risk injury when we've got a competition soon.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Looks like Miyamoto's cooled his head off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 3 0 65535 10829 0 0]What, you think I'd lose to those guys? They're just a bunch of tantrum-throwing nobodies![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0]Or is it because of my knee? Ha, they would've needed that handicap![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto looks angry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10822 0 0][uf 5 13 8 30 105]Y-Yeah, you're right... It doesn't mean shit if I win against those guys.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]It's just my knee, man. I've been on edge lately 'cause of it...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems impressed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10867 0 0]Guess I owe you one. C'mon, I'll treat you. Let's get some food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]I'm pretty fast at paying people back. Almost as fast as I can run![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After enjoying a meal together,[n]I headed back to the dorm.[n][uf 1 1][e]

