[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Um, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I am going to upgrade my outer appearance.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]First, I will triple the current surface area of my armor plating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]After that, I will repaint my body gold, and add a large dragon to my back...[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]What are you talking about?[e]
[uf 0 5 65278][uf 2 1]Not bad, I guess...?[e]
[uf 0 5 65278][uf 2 1]That sounds tacky.[e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]After reading this book, I came to a conclusion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]This is what I have to do to appear strong and encourage people to depend on me.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 7 1 25 25]Don't you think? I'm pleased to hear that you agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 7 0 25 25]Are you thinking of getting upgraded yourself, [uf 4 2]-san?[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 7 2 25 25]That is not true.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Once you actually see my upgraded form, I suspect "your socks will explode," as they say.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Outer appearances carry an influence that is beyond my ability to calculate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]The main character of this story also carefully cultivated his image so everyone would take him seriously.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]That is why I'm looking into upgrading myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]In order for me to become more dependable, it's necessary I change my appearance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Don't you agree, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Looks aren't everything.[e]
[uf 0 5 65278][uf 2 1]What's important is attitude.[e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Are you saying there's something else which takes greater priority?[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 22 1 7]Oh, could it be...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]I apologize. Please forget what I said about upgrading my appearance.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Attitude...? So that's what takes priority?[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 5 13 22 1 7]Oh, could it be...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]I apologize. Please forget what I said about upgrading my appearance.[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 7 0 25 25]It seems I had the completely wrong idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]At one point, the main character of the book says, "Can't have people think I ain't cool..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Until then, he'd put so much effort into his attire, yet he goes to raid his rivals' territory wearing nothing but a shimekomi.[n][uf 1 1][e]

[msg MSG_015_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Thanks to you, [uf 4 2]-san, I finally understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]What's most important in life is having a strong heart to stay true to your beliefs.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Therefore, I will also follow what I believe in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]I may not appear dependable, but don't worry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 7 0 25 25]I will adjust my attitude to reach maximum energy output, and to increase my ammo stocks by 50%...[n][uf 1 1][e]

[msg MND_016_5_0]
[uf 0 5 65278][uf 2 1]By understanding the essence of the story,[n]Aigis is fueling her fighting spirit...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]For some reason, I feel like going to Tartarus and raising some hell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Shall we conduct a raid?[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Oh, it's gotten so late. It doesn't seem like we'll be able to go tonight.[n][uf 1 1][e]

[msg MSG_018_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]How unfortunate. I'll just return to my room, then.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 0 0 0 35 0 0]......[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]...[uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]I want to give myself a makeover. I need a new image.[n][uf 1 1][e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Maybe I should triple my current height, so I can look down on my enemies...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Or maybe I can add spikes to my shoulders, or carve a giant dragon onto my back...[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]What are you talking about?[e]
[uf 0 5 65278][uf 2 1]Not bad, I guess...?[e]
[uf 0 5 65278][uf 2 1]That sounds tacky.[e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Reading this book has convinced me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]This is what I need to do if I want people to think I'm strong and reliable.[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Is there a problem?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 7 1 25 25]Are you considering changing your image as well, [uf 4 2]-san?[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 1 0 0 44 0 0][uf 4 23 0 7 2 25 25]Th-That's not true![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Once you actually see the new me, I'm certain your socks will explode.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Outer appearances carry an unimaginable amount of influence.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]The main character of this story also put a lot of effort into looks so people would take him seriously.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]That's why I wanted to change my image, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]If I want people to think I'm strong, I need to look the part.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]What do you think, [uf 4 2]-san? I'd like to hear your opinion, as our leader.[n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]Looks aren't everything.[e]
[uf 0 5 65278][uf 2 1]What's important is attitude.[e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]What...? You mean there's something else that's more important...?[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 4 23 0 7 1 25 25][uf 5 13 22 1 7]Oh, could it be...?[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]Attitude...? So it's not about appearances, then?[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0][uf 4 23 0 7 1 25 25][uf 5 13 22 1 7]Oh, could it be...?[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 55 0 0][uf 4 23 0 7 3 25 25]I'm sorry. It looks like I've had the wrong idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0][uf 4 23 0 7 0 25 25]At one point, the main character of the book says, "Can't have people think I ain't cool..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Up until then, he'd cared so much about his image, yet he goes to raid his rivals' territory wearing nothing but a shimekomi.[n][uf 1 1][e]

[msg MSG_034_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0][uf 4 23 0 7 1 25 25]I finally understood what he really meant after hearing what you said, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]The most important thing... is to hold true to your beliefs, no matter what.[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]I'm going to hold true to my beliefs as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]I may not look reliable, but I will make up for that with attitude.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]I'm going to operate at maximum output so that I can be useful to everyone![n][uf 1 1][e]

[msg MND_035_5_0]
[uf 0 5 65278][uf 2 1]By understanding the essence of the story,[n]Aigis is fueling her fighting spirit...[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]For some reason, I feel like going to Tartarus and raising some hell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]Maybe we can organize a raid...[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]Oh, I didn't realize it was so late.[n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]That's unfortunate. I suppose I'll just go back to my room for tonight...[n][uf 1 1][e]

