[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 1 0 0]Huh...? Is this—!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Oh wow, I didn't think we'd emerge here instead of the Desert of Doors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 3 0 0]But I guess it's not completely improbable since this place seems to be fully connected to the Abyss of Time now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]Maybe it was influenced by everyone thinking of making frequent supply trips.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]In any case, this will certainly make it easier to go back and forth.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Helloooooo! Yo, li'l sis, what's with the holdup?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 7 0 0]No way... Seriously?[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Hey, keep it moving! The rest of us need to get through, too.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Though we secured a means[n]to acquire supplies, we remain[n]trapped in the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]What awaits us further[n]inside the labyrinth?[n][uf 1 1][e]

