[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Huh? This is... Paulownia Mall?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 2 0 0]But we were just in...[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 1 0 0 3 0 0]What's going on? Did we make it out somehow?[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]I dunno... Something seems off.[n][uf 1 1][e]

[msg MSG_002_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Also... Isn't it kinda hot?[n][uf 1 1][e]

[msg MSG_003_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]You kids...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh, Kurosawa-san.[n][uf 1 1][e]

[msg MSG_005_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]What're you doing out here on a weekday? Shouldn't you be in school?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Oh, but it's spring break...[n][uf 1 1][e]

[msg MSG_007_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]Spring break? That was a couple months ago. It's July now.[n][uf 1 1][e]

[msg MSG_008_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]And what's with the getup? You all headed somewhere, or...?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Oh, um, no! We're just, uh...[n][uf 1 1][e]

[msg MSG_010_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]...Well, I'll let it slide since you kids are a little different.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Don't think I'll always turn a blind eye, though. If you're up to something, you won't get off scot-free. Are we clear?[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Geez...[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]All the dates displayed here say 2009... That calendar, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]So when he said it's July, did he mean... July of last year?[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]That's impossible... Are you saying this is the past?[n][uf 1 1][e]

[msg MSG_013_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Hey, Aigis's sister![n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Hey! Are you listening!?[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 21 0 0]Are the things here that interesting to you...?[n][uf 1 1][e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 22 0 0]N-No, not at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]It's all normal, everyday stuff, right? This is a "fountain," and that over there is a "store"...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 24 0 0]Well, I come here to gaze at the fountain myself from time to time...[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 25 0 0]R-Really? You do the same—[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 26 0 0]But there is something mysterious about this place—for all of us, not just you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 2 0 25 25]Tell me, what is this place?[n][uf 1 1][e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 28 0 0]...We got here by passing through a door, remember?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Doors like that are located throughout the Abyss of Time, each of them connected to the past.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Then... This really is last year!?[n][uf 1 1][e]

[msg MSG_022_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 31 0 0]How else can you explain the different time and season?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 32 0 0]But it seems you can't just go anywhere in the past... Only somewhere from your memories.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 33 0 0]I don't think this place connects to anywhere else, either.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Seriously? The past? Aw, man...[n][uf 1 1][e]

[msg MSG_024_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 35 0 0]We're lucky to have ended up here. Let's use this time to gather supplies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 36 0 0]Whatever we get here should be usable until the Abyss of Time disappears.[n][uf 1 1][e]

[msg MSG_024_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 37 0 0]Perhaps that's why the door led us here in the first place...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 38 0 0]It may have reflected your inner thoughts.[n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 1 0 0 39 0 0]She seems to be taking this pretty well... It's all so mind-boggling to me, though.[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 0 0 0 40 0 0]......[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 1 0 0 41 0 0]Well, on the bright side... At least we won't starve now.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0]...And that was how we learned why[n]the Abyss of Time was called as such.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0]It was a place where one[n]could revisit bygone days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0]But looking back on it now, that wasn't[n]the only thing that astounded us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 45 0 0]Maybe we all subconsciously[n]sensed some sort of salvation...[n][uf 1 1][e]

