[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I ordered the Prodigy Platter.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Maybe it's something in the ingredients,[n]but I feel a little smarter...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I wonder what's in this food... I feel[n]like my mind is clearer than usual...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I feel smarter now that[n]I've had some brain food...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I ordered the Seafood Full Course.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the omega-3s in the fish, I feel[n]like my mind is sharper than before...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I can sense omega-3s rushing to my brain.[n]I feel like I can solve any problem now...![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Every bite fills my mouth with flavor[n]and my brain with omega-3s...![n][uf 1 1][e]

