[msg SYS_021_0_0]
[uf 0 5 65278][uf 2 1]Ambush has been enhanced![n][uf 1 1][e]

[msg SYS_022_0_0]
[uf 0 5 65278][uf 2 1]When attacking an enemy from behind, you will now inflict Distress without fail.[n][uf 1 1][e]

[msg SYS_023_0_0]
[uf 0 5 65278][uf 2 1]After successfully attacking an enemy from behind, your Theurgy gauge will rise.[n][uf 1 1][e]

[msg SYS_024_0_0]
[uf 0 5 65278][uf 2 1]While dashing, you will automatically destroy breakable objects upon collision.[n][uf 1 1][e]

[msg SYS_025_0_0]
[uf 0 5 65278][uf 2 1]The amount of time needed to dash before being able to Ambush has been decreased.[n][uf 1 1][e]

