[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I've gotten a lot of my edge back since I've been able to focus on my training.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 4 1 25 25]I've been meaning to thank you for that. You've really stepped up as our leader.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]So tonight's on me. You've got enough responsibility as it is.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I can handle it.[e]
[uf 0 5 65278][uf 2 1]I'm barely getting by.[e]
[uf 0 5 65278][uf 2 1]Good, I'm starving.[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Hahaha, you really are something else. I knew I had a good feeling about you.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Really? I'd say you're doing great. As long as you make sure to get plenty of food and rest, too.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Heh, so you've got talent and an appetite. I think you'd make a pretty good athlete.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Just don't push yourself too hard. Things'll get easier with experience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]And if you need anything, let me know. I'll do whatever I can to help.[n][uf 1 1][e]

[msg MSG_007_0_0 [Young Woman's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1001]Excuse me...![n][uf 1 1][e]

[msg MSG_008_0_0 [Excited Fan]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1001]Ah, I knew it! You're Sanada-san, from Gekkoukan High![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1001]I heard you lived in Iwatodai, but wow, I never thought I'd run into you here![n][uf 1 1][e]

[msg MSG_009_0_0 [Noisy Fan]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1002]We're big fans of yours! Please, can we get a picture with you!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]...I'm busy. A-And I don't like having my picture taken.[n][uf 1 1][e]

[msg MSG_011_0_0 [Excited Fan]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1001]I kept hearing rumors that you were injured. Are you okay now?[n][uf 1 1][e]

[msg MSG_012_0_0 [Noisy Fan]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1002]Do you need any help? Is there anything I can bring you?[n][uf 1 1][e]

[msg MSG_012_3_0 [Passing Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1003]Ooh, who do you think that is?[n][uf 1 1][e]

[msg MSG_012_5_0 [Intrigued Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 1004]Not sure. A celebrity maybe? Wanna go see?[n][uf 1 1][e]

[msg MSG_012_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Let's go, [uf 4 1].[n][uf 1 1][e]

[msg MSG_014_0_0 [Excited Fan (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 1001]Wait, Sanada-saaan![n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]...I've had this problem at school, but I didn't think it'd happen out here, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]It's probably because of those interviews, or the rumors online. I've gotten all kinds of attention as I've kept up my winning streak.[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds rough.[e]
[uf 0 5 65278][uf 2 1]I'm jealous.[e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]You can say that again. I'm not some panda in a zoo for everyone to gawk at.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I've heard Junpei say that, but I wasn't expecting it from you, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 4 0 25 25]Well, I appreciate their support, but I don't have time for them right now.[n][uf 1 1][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]All I want is to be as strong as I can. I wanna train hard and feel real pride in my strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 4 3 25 25]...But all I ever seem to get is more trouble.[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]All right, looks like they've given up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Let's head out to eat, for real this time. We only have so many hours left in the day.[n][uf 1 1][e]

