[msg MSG_000_0_0 [Mitsuru Superfan]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 315]Remember that incident about a month ago? Where everyone was standing outside in the middle of the night?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 315]I also went outside, but I don't remember what I was doing at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 315]Maybe it was because I was just worried about Kirijo-senpai moving to another country...[n][uf 1 1][e]

