[msg MSG_000_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]My third year is just around the corner.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Time flies, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]I spent the whole year stalking and being stalked.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]*sigh* I have to spend my time more wisely next year.[n][uf 1 1][e]

