[msg MSG_000_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0][uf 5 21 1 101]Welcome. Oh, it's you! Thanks for always coming by![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]It's almost the season for cherry blossoms. Do you know the meaning of cherry blossom flowers?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]They say it's, "Don't forget about me."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Spring is supposed to represent new beginnings, so I wonder why its flower meaning is so sad.[n][uf 1 1][e]

[msg MSG_001_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0][uf 5 21 1 101]Welcome! What kind of flowers are you looking for?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Spring is a time when all kinds of flowers bloom, so it's fun to have a variety to choose from.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]The cherry blossoms may bloom soon... Do you know the flower meaning of cherry blossoms?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]They say it's, "Don't forget about me."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Spring is supposed to represent new beginnings, so I wonder why its flower meaning is so sad.[n][uf 1 1][e]

[msg MSG_002_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20204 0 0][uf 5 21 1 101]We'll have new flowers coming in next week. Do come around again to see them.[n][uf 1 1][e]

