[msg MSG_000_0_0 [Stylish Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 312]I've decided to go to a four-year college. I think it's true that you need a good education in life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 312]But that doesn't mean I've given up![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 312]I'll get into the fashion industry, even if I have to take a part-time job or something like that![n][uf 1 1][e]

