[msg MSG_000_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Did you eat the special Hagakure ramen? I heard that if you eat it with a friend...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You'll be friends forever! It might just be another rumor, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]When I'm as old as you, I'm gonna go have some with my friends.[n][uf 1 1][e]

