[msg MSG_000_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I'll be a third-year soon, which means I'll be studying for exams every single day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]But that doesn't mean I'm giving up the hunt for mysterious stuff like that observatory.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Having an inquisitive mind is important for people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]And it's what makes me so interesting to talk to.[n][uf 1 1][e]

