[msg MSG_000_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]Oh, hey. I didn't expect to see you somewhere other than the club.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]There's been a lot of discussion on the Internet lately about cults and mysterious incidents...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]But I'm sure whoever knows what's really going on isn't on the Internet...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]Besides, even if there were an explanation, I'm not sure I could trust it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]What's true and what's false... Those who cannot discern the difference will not survive.[n][uf 1 1][e]

[msg MSG_001_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]Only those who have the ability to discern truth from falsehood can survive in this digital age.[n][uf 1 1][e]

