[msg MSG_000_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh, hey... What happened to those Apathy Syndrome people?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Just a while ago, it was like everyone in town had it. Kinda felt like the world was gonna end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh wait, I'm busy messaging my friends, so tell me all about it later.[n][uf 1 1][e]

