[msg MSG_709_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 1 0 6]C'mon, everyone. Let's band together and win this... I know we can do it![n][uf 1 1][e]

[msg MSG_709_100 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 2 0 0]The moment man devoured the fruit of knowledge, he sealed his fate...[n][uf 1 1][e]

[msg MSG_709_110 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 3 0 0]Entrusting his future to the cards, he clings to a dim hope.[n][uf 1 1][e]

[msg MSG_709_120 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 4 0 0]Yes, the Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_130 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 5 0 0]Attaining one's dream requires a stern will and unfailing determination.[n][uf 1 1][e]

[msg MSG_709_140 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 6 0 6]Nyx's Arcana just changed to the Magician![n][uf 1 1][e]

[msg MSG_709_150 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 7 0 6]His properties changed along with the Arcana! Be careful![n][uf 1 1][e]

[msg MSG_709_002 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]It doesn't matter how many times he changes Arcana... I'll scan him no matter what![n][uf 1 1][e]

[msg MSG_709_003 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]I don't care what you are. I'm not backing down![n][uf 1 1][e]

[msg MSG_709_200 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 8 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_210 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 9 0 0]The silent voice within one's heart whispers the most profound wisdom.[n][uf 1 1][e]

[msg MSG_709_220 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]DEV: Cut[n][uf 1 1][e]

[msg MSG_709_230 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 11 0 6]I'm picking up a massive energy spike from those wings![n][uf 1 1][e]

[msg MSG_709_240 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 12 0 6]Keep your guard up for his attacks![n][uf 1 1][e]

[msg MSG_709_004 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]You better be ready! [uf 4 2] and I are gonna take you down![n][uf 1 1][e]

[msg MSG_709_300 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 13 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_310 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 14 0 0]Celebrate life's grandeur... Its brilliance... Its magnificence...[n][uf 1 1][e]

[msg MSG_709_320 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 15 0 6]Nyx's feathers are floating... What is this!?[n][uf 1 1][e]

[msg MSG_709_330 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 16 0 6]There's some kind of special power in those feathers![n][uf 1 1][e]

[msg MSG_709_340 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 17 0 6]Be careful! You're going to be way more vulnerable to mental ailments![n][uf 1 1][e]

[msg MSG_709_005 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0]We've overcome every challenge we've faced![n][uf 1 1][e]

[msg MSG_709_400 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 18 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_410 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 19 0 0]Only courage in the face of doubt can lead one to the answer...[n][uf 1 1][e]

[msg MSG_709_420 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 20 0 6]I'm detecting a surge of power from Nyx's sword![n][uf 1 1][e]

[msg MSG_709_430 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 21 0 6]Be careful! It's even stronger than it was before![n][uf 1 1][e]

[msg MSG_709_006 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]I want to protect this world, and everyone in it... I know I can do it![n][uf 1 1][e]

[msg MSG_709_500 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 22 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_510 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 23 0 0]It is indeed a precious gift to understand the forces that guide oneself...[n][uf 1 1][e]

[msg MSG_709_007 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx just changed to the Hierophant![n][uf 1 1][e]

[msg MSG_709_008 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]We won't be defeated![n][uf 1 1][e]

[msg MSG_709_009 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]We will survive this... by beating you![n][uf 1 1][e]

[msg MSG_709_520 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 24 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_530 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 25 0 0]There is both joy and wonder in coming to understand the hearts of others...[n][uf 1 1][e]

[msg MSG_709_010 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx just changed to the Lovers type![n][uf 1 1][e]

[msg MSG_709_011 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]We're not giving up... no matter how long it takes![n][uf 1 1][e]

[msg MSG_709_540 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 26 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_550 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 27 0 0]One of the greatest blessings attained from the gift of life is the freedom to pursue one's personal goals...[n][uf 1 1][e]

[msg MSG_709_012 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx switched to the Chariot now![n][uf 1 1][e]

[msg MSG_709_013 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0]Everyone is with me... This time, I will defeat you![n][uf 1 1][e]

[msg MSG_709_560 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 28 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_570 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 29 0 0]To find the one true path, one must seek guidance amidst uncertainty...[n][uf 1 1][e]

[msg MSG_709_014 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx changed to the Justice Arcana![n][uf 1 1][e]

[msg MSG_709_015 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]I'm gonna send you all the way back to the moon![n][uf 1 1][e]

[msg MSG_709_580 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 30 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_590 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 31 0 0]It requires great courage to look within oneself, and forge one's own path...[n][uf 1 1][e]

[msg MSG_709_016 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]He changed himself to the Hermit![n][uf 1 1][e]

[msg MSG_709_017 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0]Arf arf![n][uf 1 1][e]

[msg MSG_709_018 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0]He says, "I will protect everyone!"[n][uf 1 1][e]

[msg MSG_709_600 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 32 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_610 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 33 0 0]Ever-present alongside time is fortune, cruel and unflinching...[n][uf 1 1][e]

[msg MSG_709_019 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Now it's the Fortune Arcana![n][uf 1 1][e]

[msg MSG_709_020 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Screw this fortune... I'm gonna tear it all down![n][uf 1 1][e]

[msg MSG_709_620 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 34 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_630 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 35 0 0]One needs strength to endure, and rise above suffering and torment.[n][uf 1 1][e]

[msg MSG_709_021 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx switched to the Strength Arcana![n][uf 1 1][e]

[msg MSG_709_022 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0]I have to be strong, for them...![n][uf 1 1][e]

[msg MSG_709_640 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 36 0 0]The Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_650 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 37 0 0]In the face of unavoidable disaster lies the opportunity to search for redemption.[n][uf 1 1][e]

[msg MSG_709_023 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Nyx changed to the Hanged Man![n][uf 1 1][e]

[msg MSG_709_024 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]Father, please watch over me...[n][uf 1 1][e]

[msg MSG_709_700 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 38 0 0]The moment man devoured the fruit of knowledge, he sealed his fate...[n][uf 1 1][e]

[msg MSG_709_710 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 39 0 0]Entrusting his future to the cards, man clings to a dim hope.[n][uf 1 1][e]

[msg MSG_709_720 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 40 0 0]Yet, the Arcana is the means by which all is revealed...[n][uf 1 1][e]

[msg MSG_709_730 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 41 0 0]Beyond the journey you have taken lies the absolute end.[n][uf 1 1][e]

[msg MSG_709_740 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 42 0 0]It matters not who you are... One thing is always certain: death awaits all.[n][uf 1 1][e]

[msg MSG_709_750 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 43 0 6]I sense... the Death Arcana... This is Nyx's true form...[n][uf 1 1][e]

[msg MSG_709_760 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 44 0 0]I didn't want you to suffer. But, the time for that is long past...[n][uf 1 1][e]

[msg MSG_709_820 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 45 0 0]Is this really what you desire...? Well, I already know the answer.[n][uf 1 1][e]

[msg MSG_709_830 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 46 0 0]Very well, let us continue... until the world meets its end.[n][uf 1 1][e]

[sel SEL_110_0_0 top]
[uf 0 5 65278][uf 2 1]The world won't end.[e]
[uf 0 5 65278][uf 2 1]Let's go, Ryoji.[e]

[msg MSG_709_770 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 8 65535 65535 0 0][uf 3 1 1 0 2 47 0 7]I am with you... to the very end![n][uf 1 1][e]

[msg MSG_709_025 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Stay strong, everyone![n][uf 1 1][e]

[msg MSG_709_800 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 48 0 0]You cannot avoid death. To live is to die. They are one and the same...[n][uf 1 1][e]

[msg MSG_709_810 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 2 49 0 0]Behold. This is the path you have chosen.[n][uf 1 1][e]

