[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 1 0 0]See? We got in no problem. Man, I'm a genius![n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Is there really something to brag about here?[n][uf 1 1][e]

[msg MSG_001_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 18 5 4 1 1 1 0][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 3 0 0]So you unlocked it earlier. Très bien![n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Oui, good job.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 4 0 25 25]We should find somewhere to get ourselves ready. Your classroom should work, right?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Uh, what?[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Tray Ben? Is that French or somethin'?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Why're they talkin' in different languages anyway...?[n][uf 1 1][e]

