[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Can we turn on the lights?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Aww, you scared?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 3 0 0]No, I'm not![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 4 0 0]...Stupei.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 5 0 0]H-Hey, that's uncalled for![n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Quiet. We need to get started.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 7 0 0]It's better for us if the lights are off. They cut the power at night anyway.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 8 0 0]I don't really like sneaking around...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 9 0 0]First, we have to find the key to the gym. It should be in either the faculty office or the janitor's room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]You three check the faculty office. Akihiko and I will take the janitor's room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]After that, we'll meet in the main hallway on the first floor. Understood?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]Fine by me.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]So we're searchin' the faculty office, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 3 1 25 25]Hey, maybe we'll find some test questions! Heheh.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Maybe I should go to the faculty office, too. It sounds interesting.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 15 0 0]You're not planning to do something unethical under my supervision, are you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 2 25 25]I suppose you'll need to be executed...[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 17 0 0]H-Hey, c'mon! Obviously I was joking! Haha, hahaha...[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 18 0 0]All I meant by "interesting" was that there's a higher chance of finding the key there.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 19 0 0]Enough with the excuses. Let's head to the janitor's room.[n][uf 1 1][e]

[msg MSG_013_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 20 0 0]Iori, you're coming with us.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 21 0 0]All right, let's get this over with.[n][uf 1 1][e]

