[msg MSG_000_0_0 [Temperamental Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Hmm, what do I feel like...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Darn, I should've checked my horoscope for today's lucky drink.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Maybe I should get an apple martini...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Nah, too sour. An oolong tea might be good...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Wait, that's kinda boring. I'll have a Bloody Mary.[n][uf 1 1][e]

[msg MSG_001_0_0 [Temperamental Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Huh? You forgot my order? Oh, fine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]An apple martini.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Nah, too sour. An oolong tea might be good...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 683]Wait, that's kinda boring. I'll have a Bloody Mary.[n][uf 1 1][e]

