[msg MSG_000_0_0 [Upbeat Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]Huh? Whaddaya want?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]Oh, you're taking orders? In that case, bring me a ginger ale.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]Wait, I changed my mind. Make that an oolong tea.[n][uf 1 1][e]

[msg MSG_001_0_0 [Upbeat Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]What? I can't hear you! Huh? My order?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]I'll have a ginger ale.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 686]Wait, I changed my mind. Make that an oolong tea.[n][uf 1 1][e]

