[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]You go on ahead to the shrine. I'll grab us some takoyaki.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds good.[e]
[uf 0 5 65278][uf 2 1]Want me to wait for you?[e]
[uf 0 5 65278][uf 2 1]Why the shrine?[e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Sweet, be right there![n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Aw, you gonna miss me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]It's fine, just go on ahead. I'll be there in a sec.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I wanna get away from the hustle and bustle of the city and enjoy some takoyaki in peace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Anywho, I'll catch up in a sec.[n][uf 1 1][e]

