[msg MSG_000_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]It's me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]I'm sorry to disturb you, but do you have a moment?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Coming...[e]
[uf 0 5 65278][uf 2 1]Just a minute.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 3 0 0]Good morning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 4 0 0]There's actually something I need to tell everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 5 0 0]...But, I think it would be best if you saw it for yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 6 0 0]So I'd like for all of us to meet in the command room tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 7 0 0]I'll see you then.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]That's okay. Just listen through the door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]There's something I need to tell everyone, so let's all meet in the command room tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]That's all I wanted to say. I'll see you then.[n][uf 1 1][e]

