[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I've been writing more of my story. How much did I tell you about...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Oh right... The pink alligator and the bird became friends, right?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]This was the alligator's first friend, and he was very happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...They started going to the river every day, and the alligator would listen to the little bird sing.[n][uf 1 1][e]

[msg MSG_001_3_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]But the pink alligator still had trouble hunting, because of his color.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]He was so terribly easy to spot, and his prey always had plenty of time to escape.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Eventually, he became so hungry that he grew dizzy...[n][uf 1 1][e]

[msg MSG_001_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]...And one afternoon, he accidentally ate the bird as it slept in his mouth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Of course, he immediately realized what he'd done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]He drank swamp water to vomit his friend back up... but he was too late. The bird was already dead.[n][uf 1 1][e]

[msg MSG_001_7_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]After that, he couldn't bring himself to eat anything.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]...That's as far as I've written. I haven't decided on an ending yet.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]That's a good story.[e]
[uf 0 5 65278][uf 2 1]It sounds really depressing.[e]
[uf 0 5 65278][uf 2 1]I've heard that one before.[e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 20 5 117]You really think so? Then, maybe you'll enjoy the final product.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I always thought the only thing I could give other people was hopelessness, but maybe...[n][uf 1 1][e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 5 13 20 15 117]Oh, is it really that dark...? For me, it's hard to tell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]The words I use come from my own life. I don't really have a point of reference.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]But I see. So, this is depressing for others.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 20 5 117]I see... So, I guess my life isn't so unusual after all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]I thought nobody understood me, but you're saying this story of mine has been done before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...Interesting.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]You know, when I mentioned I was writing a diary...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]That was a lie. I was writing my will.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I couldn't face reality... and I was essentially screaming curses into my notebook.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]For now though, I'm writing my story in the same notebook.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]It probably isn't very good, but it contains some things that I've learned during my short life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]When it's done, I'd like you to be the first to read it... Meeting you is why I started writing it, you know.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Kamiki is looking deep into my eyes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_010_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I've been trying to come up with a good ending, but I just can't decide...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 117 3 25 25]And I'm running out of time...[n][uf 1 1][e]

[msg MSG_011_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]...I've got to go now, but I hope to see you again.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

