[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]I always wondered what they meant by "hard" science fiction.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 2 0 0]So the last time I passed by this theater, I asked the ticket clerk.[n][uf 1 1][e]

[msg MSG_000_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 3 0 0]He said, "It's a science fiction story that could actually happen."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 4 0 0]I actually don't find movies about far away galaxies or magic and spellcasting that interesting...[n][uf 1 1][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 5 0 0]I like movies that make you think, "Ten years down the road, maybe this could happen."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 6 0 0]You get to see a familiar world, but just slightly more advanced.[n][uf 1 1][e]

[msg MSG_000_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 7 0 0]I think it's fun to imagine our world slowly changing like that...[n][uf 1 1][e]

[msg MSG_000_8_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 8 0 0]Oh, sorry! I got a little carried away. We still haven't even seen the movie yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 6 1 25 25]I hope we can get good seats.[n][uf 1 1][e]

[msg MSG_900_0_0 [Futuristic High School Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]...Morning, Roboco.[n][uf 1 1][e]

[msg MSG_901_0_0 [Helper Robot]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]GOOD MORNING, MASTER. THERE ARE NO CHANGES TO YOUR REGULAR SCHEDULE TODAY.[n][uf 1 1][e]

[msg MSG_902_0_0 [Futuristic High School Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]I'm so bored. When will I meet my shining android prince atop a gallant white steed...?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I got a look at what life could[n]be like in the near future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]And learned about cutting-edge[n]scientific theories...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 13 0 0]Wow, that was amazing. I wonder if our civilization will ever advance that far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 21 6 7]Like, did you see that iron!? It got rid of the wrinkles on their clothes in half a second.[n][uf 1 1][e]

[msg MSG_002_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 15 0 0]To get that much heat out of an iron so quickly, you'd probably have to keep it charged.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Though it wouldn't have to be with electricity. It could be gas-powered, or even a hybrid...[n][uf 1 1][e]

[msg MSG_002_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 17 0 0]Or maybe they have a totally new energy source! But they'd still need some sort of system to send energy into the iron...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 19 0 0]Oh! I-I'm sorry![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 6 0 25 25][uf 4 21 6 11]The movie got me all excited, so I got a bit carried away.[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 21 0 0]Anyway, I hope we can come again sometime.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I decided to go back to[n]the dorm with Fuuka.[n][uf 1 1][e]

