[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 1]-san, hurry![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I hope no one's bought that illustration collection... Ahh, please still be there...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Come on![n][uf 1 1][e]

[msg MSG_002_0_0 [Student's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Wait![n][uf 1 1][e]

[msg MSG_003_0_0 [Disgruntled Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]Fushimi! They said our class's materials fee hasn't been paid yet.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aloof Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 2]Yeah, I was totally getting grilled in the faculty office just now...[n][uf 1 1][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh right, the money...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I, um... gave it to Mr. Takenozuka... when he came to the office...[n][uf 1 1][e]

[msg MSG_006_0_0 [Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 3]You were the one responsible for that money, weren't you, Fushimi-san?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 3]That means you were the last one who saw it...[n][uf 1 1][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Um... But I just told you...[n][uf 1 1][e]

[msg MSG_008_0_0 [Disgruntled Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1]Well, the teacher told us we haven't paid yet. So doesn't that make this your fault?[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Umm... Uh... I...[n][uf 1 1][e]

[msg MSG_009_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 1]-san...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Try to remember.[e]
[uf 0 5 65278][uf 2 1]It's gotta be a misunderstanding.[e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]But, I'm positive I gave the money to the teacher![n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I know I've made mistakes before, but this time I'm sure...![n][uf 1 1][e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 9 5 109]Y-Yes, I think so too! I clearly remember giving the money to the teacher![n][uf 1 1][e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]It has to be some kind of mistake...[n][uf 1 1][e]

[msg MSG_015_0_0 [Aloof Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 2]...Look, just make sure you take care of it, all right?[n][uf 1 1][e]

[msg MSG_015_5_0 [Aloof Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 2]I'm sure it's exciting to have that much money, but you better do something before everyone finds out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 2]Don't worry, we won't tell anyone.[n][uf 1 1][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Wait! You think I...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 0 0 0 23 0 0]......[n][uf 1 1][e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Th-Those guys... They must think I stole the money...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I-I couldn't stand up to them, but I... I didn't take anything![n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry.[e]
[uf 0 5 65278][uf 2 1]We have to do something...[e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]B-But how could I not worry? I'm being accused of stealing...[n][uf 1 1][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]...I'm sorry. I didn't mean to take it out on you, [uf 4 1]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]I just... I didn't steal anything...[n][uf 1 1][e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 5 13 9 5 109]Y-Yes, you're right, [uf 4 1]-san. We have to do something...[n][uf 1 1][e]

[msg MSG_022_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]I have to prove to everyone that it wasn't me. But how do I do that...?[n][uf 1 1][e]

[msg MSG_023_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I'm certain I handed the money over. I'll just have to talk to Mr. Takenozuka about this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]B-But, what if he thinks I'm accusing him of stealing?[n][uf 1 1][e]

[msg MSG_023_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 1]-san! What should I do...?[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]Chihiro is on the verge of tears.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I have to do something about this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can sense that Chihiro is relying on me.[n][uf 1 1][e]

[msg MSG_025_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]I... I'm sorry. I know I can't just expect you to solve everything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]This is my problem, so... I need to figure it out on my own.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Bookworms... I think I have to pass today. Sorry...[n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]I walked with Chihiro until[n]it was time to part ways.[n][uf 1 1][e]

