[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]It feels nice, being able to pour tea for someone else like this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 5 1 25 25]Oh, my apologies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm supposed to be the host, and yet here I am thinking about myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 5 0 25 25]How about you, then? Are you having a good time?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]I'm a bit tense.[e]
[uf 0 5 65278][uf 2 1]I'd like a refill...[e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 5 1 25 25]Oh, that's good to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 6 0 0]Chamomile is known for its relaxing properties, so maybe that's taking its effect on you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 5 3 25 25]I... was actually a bit worried that I might be putting you off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 8 0 0]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 5 0 25 25]Sorry about that. Try to relax, if you can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 10 0 0]Then again, if it were that easy, it wouldn't be a problem, would it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 5 3 25 25]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 5 1 25 25]My apologies. Let me take care of that for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]Heh, I'm glad you aren't afraid to speak up when you want something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 5 0 25 25]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 5 0 25 25]Hm? We're running low on snacks. I'll have to ask my staff to—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0]Actually...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 17 0 0]Oh, never mind. Here, let me pour you another cup.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I drank herbal tea with Mitsuru as[n]we discussed our favorite snacks...[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 18 0 0]All right, I think that's enough for now. We should start cleaning up.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 5 1 25 25][uf 5 13 4 1 5]I'd like to invite you for this again, if time allows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 5 0 25 25]But for now, let's head back to our rooms.[n][uf 1 1][e]

