[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]That missing fee money from the other day still hasn't turned up yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]No one's said anything to me, but I know what they're all thinking...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I can't take this anymore... I... I don't want to be here...[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I-I'm sorry! I... I shouldn't say that. I'm supposed to be a member of the student council...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I'm... going to look for some books...[n][uf 1 1][e]

[msg MSG_003_0_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]Yeah, there's no way it could've been anyone else. It's gotta be her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]It's that first-year on the student council, Fushimi. The gloomy girl, with the long hair and glasses. The one who's always reading.[n][uf 1 1][e]

[msg MSG_004_0_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1]I hear she stole all the class's money.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]2,500 yen per person... Damn, I could buy a brand name purse with that much![n][uf 1 1][e]

[msg MSG_005_0_0 [Long-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]Well, I heard she has no father...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]So there's no way they could have that much money, since her mom only works part-time.[n][uf 1 1][e]

[msg MSG_006_0_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1]See, how could it not be her!? And with such an innocent face, too...[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]That's all a misunderstanding.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_008_0_0 [Long-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 2]...Huh? Who even are you...?[n][uf 1 1][e]

[msg MSG_008_5_0 [Long-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 2]Is he a friend of Fushimi-san's...? Probably not. He doesn't look like the type that would hang out with her.[n][uf 1 1][e]

[msg MSG_009_0_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1]Whoa! Hey, look! That guy is kinda hot![n][uf 1 1][e]

[msg MSG_009_5_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1]He's totally checking us out, isn't he!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Library Staff]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 3]Excuse me, this is the library. Please, show some respect.[n][uf 1 1][e]

[msg MSG_011_0_0 [Short-Haired Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1]Let's go outside. We can finish talking there.[n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...C-Couldn't find any books...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Chihiro looks like she's about to cry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]She must have heard everything.[n][uf 1 1][e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]...Let's go.[n][uf 1 1][e]

