[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]All right, everyone's here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Heck yeah! Let's get right into it![n][uf 1 1][e]

[msg MSG_018_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Now, I'd like your undivided attention.[n][uf 1 1][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]For a long time, Kirijo-kun and Sanada-kun were the only Persona-users we had.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]But that number has recently jumped to five.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]So, here's the plan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Starting tonight at 12 AM, I'd like us to finally begin exploring [uf 0 1 33]Tartarus[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Uhh... So I asked this yesterday, but what is that Tartar thing again?[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]...It's Tartarus. You seriously haven't seen it, Junpei?[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I mean...[n][uf 1 1][e]

[msg MSG_023_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]It's no surprise you haven't seen it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Tartarus only appears during the Dark Hour, after all.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Only during the Dark Hour...?[n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Just like the Shadows... Interesting, huh?[n][uf 1 1][e]

[msg MSG_025_1_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]The goal of our club—SEES—is to fight those Shadows. However...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Simply defeating Shadows during the Dark Hour isn't enough.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]We must get to the root of the problem. We need to destroy the Dark Hour itself.[n][uf 1 1][e]

[msg MSG_025_2_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Uh, I don't really get it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]You're sayin' if we run around Tartarus, we can somehow get rid of the Dark Hour?[n][uf 1 1][e]

[msg MSG_025_3_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]We don't know for certain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Sorry I can't give you a better answer, but investigating the mysteries of that tower is part of our job.[n][uf 1 1][e]

[msg MSG_025_4_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]The bottom line is: we need more information.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Everything we encounter there will be a vital clue for us.[n][uf 1 1][e]

[msg MSG_025_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]The exploration of Tartarus is of utmost importance. Consider it our top priority.[n][uf 1 1][e]

[msg MSG_025_6_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Our society, while remaining blissfully unaware of the Shadows, is slowly but surely succumbing to their influence.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I would go as far as to say that the fate of the world rests on the shoulders of you Persona-users.[n][uf 1 1][e]

[msg MSG_025_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]...That's one hell of a responsibility, but the heroes of justice will prevail![n][uf 1 1][e]

[msg MSG_025_8_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]It's also the perfect spot for us to train and improve our skills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 4 0 25 25]That place is like a nest of Shadows, you know.[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Whoa... Their nest, huh...?[n][uf 1 1][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]But Senpai... what about your injury?[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Akihiko's still recovering from his wounds. He'll accompany us, but won't participate in the exploration.[n][uf 1 1][e]

[msg MSG_029_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]...Yeah, I know.[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Relax, ol' Junpei's got your backs![n][uf 1 1][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]I'm not so sure about this...[n][uf 1 1][e]

[msg MSG_032_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]What about you, Mr. Chairman?[n][uf 1 1][e]

[msg MSG_033_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]I'll stay here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 221 6 25 25]Not much point anyway, since I can't summon a Persona...[n][uf 1 1][e]

