[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 1 0 0]Heeey, [uf 4 1]![n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0]Do you have a minute?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 3 0 0]There's something I wanna talk to you about.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Okay, let's hear it.[e]
[uf 0 5 65278][uf 2 1]What is it about?[e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 4 0 0]Ah, actually, let's go somewhere else. I don't want anyone from the team hearing.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 5 0 0]Plus it might take a while, so...[n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 6 0 0]Ah, actually, I don't want anyone from the team overhearing.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 7 0 0]Let's go somewhere—anywhere.[n][uf 1 1][e]

