[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 1 0 0]We're here...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 2 0 0]What...!?[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 3 0 0]That wasn't here before...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]It seems we truly do have one final battle ahead of us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Let's make sure we're as prepared as possible before proceeding.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Heh, works for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 1 0 0 7 0 0]We'll get to the bottom of this no matter what stands in our way.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]A new path in the Desert of Doors[n]will lead us to the final battle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The answers we seek lie just beyond it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We should take all possible measures to[n]prepare before going through the door.[n][uf 1 1][e]

