[msg MSG_000_0_0 [Excited Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Sanada-kun, wait![n][uf 1 1][e]

[msg MSG_001_0_0 [Noisy Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Sanada-kuuun![n][uf 1 1][e]

[msg MSG_002_0_0 [Man's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Hey, hold on a sec. You're the captain, aren't you?[n][uf 1 1][e]

[msg MSG_003_0_0 [Boxing Team Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Hey, quit pushing! Practice is over![n][uf 1 1][e]

[msg MSG_004_0_0 [Athletic Scout]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 3]You there! Sanada-kun, right?[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]...That's right.[n][uf 1 1][e]

[msg MSG_006_0_0 [Athletic Scout]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 3]That was an incredible bout! I've never seen a middle schooler deliver a KO like that![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 3]I'm with the school you were up against in the finals. What do you say to enrolling with us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 3]We'll give you a real generous scholarship—[n]you'd only have to pay half your tuition![n][uf 1 1][e]

[msg MSG_007_0_0 [Boxing Team Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]Wait, you're from another school!? Poaching's against the rules and you know it![n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 11 0 0]Sorry, but I don't see any reason to attend a school that places second.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 12 0 0]...Good luck finding someone else.[n][uf 1 1][e]

[msg MSG_009_0_0 [Noisy Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Sanada-kun, you're so cool![n][uf 1 1][e]

[msg MSG_010_0_0 [Excited Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]You hear that? He'd never go to your loser school![n][uf 1 1][e]

[msg MSG_011_0_0 [Boxing Team Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1]Seriously, will you all just go home already!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1]We can't leave until you guys do, dammit![n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 17 0 0]......[n][uf 1 1][e]

[msg MSG_013_0_0 [Female Student's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]Couldn't you have handled that with a little more tact?[n][uf 1 1][e]

[msg MSG_014_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 1 1 65535 0 0][uf 3 1 1 0 0 19 0 0]I heard it gets crowded after practice, so I decided to wait here instead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 253 1 1 65535 0 0][uf 3 1 1 0 0 20 0 0]Third-year, Class C... Akihiko Sanada-kun.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 21 0 0]What do you want?[n][uf 1 1][e]

[msg MSG_016_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 22 0 0]Hm...? You're not going to ask who I am?[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Why bother?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 24 0 0]Whatever it is you're here for, I'm not interested. All I want is to train and become stronger.[n][uf 1 1][e]

[msg MSG_018_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 1 1 65535 0 0][uf 3 1 1 0 0 25 0 0]Oh, it's nothing troublesome. In fact, I have a rather simple request.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 26 0 0]What request...?[n][uf 1 1][e]

[msg MSG_020_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 27 0 0]I have enemies that need defeating.[n][uf 1 1][e]

[msg MSG_021_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 28 0 0]Only thing is, they're not people—meaning, there's no need to play by the rules, not like in the ring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 29 0 0]No, these enemies... They're related to what you go through every midnight.[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 4 1 65535 0 0][uf 3 1 0 0 0 30 0 0]...!?[n][uf 1 1][e]

[msg MSG_023_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 31 0 0]You see, I'm in the same situation. I experience the same thing you do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 32 0 0]The difference is, I know what it means, so if you'll join me... I'll share what I know with you.[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 2 1 65535 0 0][uf 3 1 1 0 0 33 0 0]...Who are you?[n][uf 1 1][e]

[msg MSG_025_0_0 [Poised Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 34 0 0]Mitsuru Kirijo. I'm a third-year, like yourself.[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 0 1 65535 0 0][uf 3 1 1 0 0 35 0 0]"Kirijo"? Sounds familiar.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 0 1 65535 0 0][uf 3 1 1 0 0 36 0 0]Earlier, you said you wanted to train and become stronger, but what you really need is a challenge.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 253 1 1 65535 0 0][uf 3 1 1 0 0 37 0 0]And with this... you'll be able to defeat them.[n][uf 1 1][e]

[msg MSG_029_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 252 4 1 65535 0 0][uf 3 1 0 0 0 38 0 0]......[n][uf 1 1][e]

