[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 1 0 0]This is the source of the tread marks!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 2 0 0]It looks like the Shadow is using the tank as armor![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 3 0 0]Get ready, everyone! Here it comes![n][uf 1 1][e]

