[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I see Maya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 13 10 5 1]I chatted with Maya for a while.[n]The bond between us is growing...[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's almost dark...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out[n]and leave my room.[n][uf 1 1][e]

