[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono seems to have stepped out...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0][uf 3 1 3 0 65535 16221 0 0]Wow... How is it already so late?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]My darling's not home today, and I'm so lonely...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Hmm, maybe I'll have dinner with Ms. Toriumi. We could go to that restaurant with the interesting game...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]What was it called again...? A mahjong parlor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]I hope I don't lose again... But I don't think there's any way I can win against Ms. Toriumi.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0][uf 3 1 3 0 65535 16222 0 0]Oh. Hello, [uf 4 1]. How are you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Ms. Toriumi isn't here. I was just about to look for her myself, actually.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]...Say, [uf 4 1], do you play mahjong?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]It's very intriguing. The technical terms, in particular, are quite interesting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]If I play too much, I can't stop thinking about them for days.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Mentan pin doradora! Riichi ippatsu chiitoitsu tsumo![n][uf 1 1][e]

[msg MSG_005_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]I've said that stuff even in my sleep... My poor darling hasn't slept very well as a result.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Shall I teach you the other technical terms? Though I'd just be repeating what Ms. Toriumi taught me...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Well, for beginners, there's "Only riichi!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Then a few intermediate phrases, such as "I got a reverse dora!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]"Looks like you're waiting for one tile," or "You've gotta have more than two han."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]Ooh, or advanced stuff... "You have a hand, don't you?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]"I have all the tiles you're waiting for," and "Mangan booyah!"[n][uf 1 1][e]

[msg MSG_007_0_0 [Mrs. Terauchi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]...So far, I've only had chances to use the beginners' phrases, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]But Ms. Toriumi is a very patient teacher. She'll tell me, "You should throw this one away," or...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]"You won't get many points if you call that one, so I wouldn't," and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]"I dropped that tile by accident, so you can't ron it"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1583 0 65535 65535 0 0]She's taught me so much, but I haven't been able to win a single match.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I learned technical terms for mahjong...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono doesn't seem to be returning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to give up for today[n][uf 1 1][e]

