[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2108 0 0]What a wacky store, huh? Somethin' about, "Cleanse your soul and face your inner self"?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I don't really get it, but it sounds kinda cool.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2118 0 0]...Guess I'll give it a try. I wonder what my "inner self" is like...[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2105 0 0]This place again, huh?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Well, I did get some good sleep in last time, so... alright.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2017 0 0]Man, I slept like a log! I seriously don't remember anything...[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]But I feel super refreshed! I feel like I can do anything right now![n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2063 0 0]Oh, I'm gonna go try my luck at the arcade! See ya later, man![n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2017 0 0]*yawn* What a nap...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I was dead asleep again. But, uh... am I really facing my "inner self" like this?[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2063 0 0]Well, whatever. I'm feelin' great, so I'm gonna try to set some high scores at the arcade![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

