[sel INTO_HOME_SEL top]
[uf 0 5 65278][uf 2 1]Вернуться домой[e]
[uf 0 5 65278][uf 2 1]Задержаться[e]

[msg MND_GOINTO_HOME]
[uf 0 5 65278][uf 2 1]Почти наступила ночь...[n][uf 1 1][e]

[msg MND_HELP_GOINTO_HOME]
[uf 0 5 65278][uf 2 1]Если вернусь в общежитие сейчас, то у меня не будет времени на дела до темноты.[n][uf 1 1][e]

[msg MND_GOINTO_HOME_OK]
[uf 0 5 65278][uf 2 1]Мне пора домой...[n][uf 1 1][e]

