[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]The shrine is bustling with[n]people enjoying the festival.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Coming here by myself feels a little lonely...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 156 65535 0 0][uf 3 1 1 0 0 1 0 0]What are those?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 156 65535 0 0][uf 3 1 1 0 0 2 0 0]Those are masks. They're worn over the face as a form of recreation.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 156 65535 0 0][uf 3 1 1 0 0 3 0 0]One can find enjoyment by hiding one's face?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 156 65535 0 0][uf 3 1 1 0 0 4 0 0]Hiding your face isn't the objective, exactly. Rather, you get to experience having a different one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 156 65535 0 0][uf 3 1 1 0 0 5 0 0]Hm... Putting this into words is proving difficult...[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 156 65535 0 0][uf 3 1 1 0 0 6 0 0]So then, by wearing a different face, you are able to become a different version of yourself?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 156 65535 0 0][uf 3 1 1 0 0 7 0 0]Yes, that's about right. Your degree of comprehension is actually quite stunning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 156 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 5 0 25 25]At this rate, a few more tests and the chairman may give you permission to go out on your own.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 156 65535 0 0][uf 3 1 1 0 0 9 0 0]I look forward to that.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]They continue to chat...[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Call out to them[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]They didn't seem to hear me...[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After looking around a bit longer,[n]I decided to go back to the dorm.[n][uf 1 1][e]

