[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 3 0 65535 7007 0 0]Um... Today's the last day of summer vacation, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Well, since it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7111 0 0]...I was wondering if you had any plans today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]I-I just wanted to ask. No reason...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 25 8]......[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]It seems like Amada wants[n]to say something...[n][uf 1 1][e]

[msg MND_001_1_0]
[uf 0 5 65278][uf 2 1]Should I invite him to the film festival?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Invite him to the movies[e]
[uf 0 5 65278][uf 2 1]Remain silent[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7041 0 0]S-Sure![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Amada looks happy...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7084 0 0]I always thought there was something I had to do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]But I could never really figure out what it was...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]But I've made up my mind... The next chance I get, I'll do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]My mind is clear.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Amada has a serious expression...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I doubt he's in the mood[n]to go to the movies...[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]Now that I'm a part of the team, I see you all differently.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]...I'll do my best, as a member of SEES.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Amada has a serious expression...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I doubt he's in the mood[n]to go to the movies...[n][uf 1 1][e]

[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

