[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1137 0 0]Hm? What's up?[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth asked[n]me to get a specific item for her...[n][uf 1 1][e]

[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1098 0 0]Huh? You're looking for pine resin...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Why would I have something like that on me...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Ohhh, do you mean the powder we use on the archery team? The yellow stuff?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1068 0 0]We use it during practice, so it runs out pretty quick... Lemme check if I still have any left.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1149 0 0]I found some! Here you go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]It can get sticky if you use too much all at once, so go easy on it.[n][uf 1 1][e]

