[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2105 0 0]Yo, what's up?[n][uf 1 1][e]

[msg MND_000_5_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth asked[n]me to get a specific item for her...[n][uf 1 1][e]

[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2107 0 0]Ooh, you're lookin' for a handheld game console?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Are you hooked on games now? Is it 'cause of the game I gave you last time, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I can give you my old one if you're cool with it. Lately, I've only been using the newer, slimmer model.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]No point having two of the same consoles anyways. Hold on, lemme grab it for ya.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Here ya go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Let's play a match one day! I'll take you on anytime.[n][uf 1 1][e]

