[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4136 0 0]Hm? Is something the matter?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Just wanted to chat.[e]
[uf 0 5 65278][uf 2 1]What's everyone's status?[e]
[uf 0 5 65278][uf 2 1]Let's go to Tartarus.[e]
[uf 0 5 65278][uf 2 1]Never mind.[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4024 0 0]Very well. We'll meet at Tartarus around midnight. Don't be late.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I'll let the others know.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Everyone can go tonight.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]These people already have plans, so they can't go tonight:[n][uf 1 1][e]

[msg SYS_008_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0][uf 1 1][e]

[msg SYS_009_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1][n][uf 1 1][e]

[msg SYS_010_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1], [uf 2 4 2][n][uf 1 1][e]

[msg SYS_011_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1],[n][uf 2 4 2], [uf 2 4 3][n][uf 1 1][e]

[msg SYS_012_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1], [uf 2 4 2],[n][uf 2 4 3], [uf 2 4 4][n][uf 1 1][e]

[msg SYS_013_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1], [uf 2 4 2],[n][uf 2 4 3], [uf 2 4 4], [uf 2 4 5][n][uf 1 1][e]

[msg SYS_014_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1], [uf 2 4 2], [uf 2 4 3],[n][uf 2 4 4], [uf 2 4 5], [uf 2 4 6][n][uf 1 1][e]

[msg SYS_015_0_0 [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 2 4 0], [uf 2 4 1], [uf 2 4 2], [uf 2 4 3],[n][uf 2 4 4], [uf 2 4 5], [uf 2 4 6], [uf 2 4 7][n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Is there anything else?[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4060 0 0]Some are unable to take part in this excursion. Do you still wish to go?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Not now[e]

