[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]I just rented a DVD. It's a foreign film about a hardboiled detective.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I have a little free time right now, so...[n][uf 1 1][e]

[msg MSG_500_1113_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Um, I rented a DVD. It's a foreign film about a hardboiled detective.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I've got a lot of free time on days we don't go to Tartarus, so...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Watching a detective movie with Amada[n]might help me gain more [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]If you're free right now, do you want to watch it with me?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Let's watch it together.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Do you want to watch more of the film series we started together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I just rented another movie from the same series because I wanted to watch it sometime...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Watching a detective movie with Amada[n]might help me gain more [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]The reviews online all seemed pretty positive, so I'm sure it's worth watching.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Let's watch it together.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7064 0 0]I rented the final movie from that series.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I'm certain it'll be a good watch, too.[n][uf 1 1][e]

[msg MSG_500_1113_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Junpei-san and Chidori-san's relationship kinda feels like a movie plot, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Oh, by the way... I rented the final movie from that series.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I'm certain it'll be a good watch, too.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]It seems like Amada is looking[n]forward to hanging out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching a detective movie with Amada[n]might help me gain more [uf 4 30 2 1 1 0].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Amada might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Do you want to watch the movie with me, [uf 4 1]-san?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Let's watch it together.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]It looks like the director of the movies we watched has a huge repertoire...[n][uf 1 1][e]

[msg MSG_500_1113_4 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]I learned that the director of the movies we watched actually has a huge repertoire.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]So I rented a bunch of his other works.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]I don't want to bother you, but... I was kind of hoping we could give Junpei-san some good recommendations.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Amada will gain any more[n]new skills even if I watch a DVD with him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching a detective movie with him[n]might help me gain more [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]If you're not busy, do you want to watch the movie together?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Let's watch it together.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]Okay. I'll set it up.[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh, I guess you do seem pretty busy... Maybe the next time you're free then.[n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh! Did you want to watch?[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Amada will gain any more[n]new skills even if I watch a DVD with him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching a detective movie with him[n]might help me gain more [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Watching a detective film with Amada[n]might help me gain more [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_020_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Um, if you're okay with it, maybe we can watch the movie together...[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Let's watch it together.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]I know this is kinda coming out of nowhere, but... Um, would you like some coffee right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Not the instant stuff, but with properly ground beans and all that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I saw someone prepare coffee on a show, and I wanted to try doing it myself...[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Amada asked me to join him for coffee...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with him?[n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 4 1]-san, if you don't mind, could you maybe be my taste-tester?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]I studied up a little on coffee beans.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I wanted to test some things out. Do you have some free time right now?[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Amada asked me to join him for coffee...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with him?[n][uf 1 1][e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I promise I'll brew it correctly this time.[n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7002 0 0]I was thinking about brewing some coffee right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I wanted to show you that I can do it properly...[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Amada seems serious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He might gain a new ability soon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_032_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Um, do you have some time right now?[n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]

[msg MSG_034_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh, I was thinking about brewing some coffee. Would you like some?[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Amada will gain any more[n]new skills even if I have coffee with him...[n][uf 1 1][e]

[msg MSG_036_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]It's like I'm a barista or something. This is pretty fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]You can take your coffee to go if you want.[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, thanks.[e]
[uf 0 5 65278][uf 2 1]Now's a bad time.[e]

[msg MSG_038_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7088 0 0]Okay! I'll get started right away.[n][uf 1 1][e]

[msg MSG_039_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7095 0 0]Oh okay... Maybe next time, then.[n][uf 1 1][e]

[msg MSG_040_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh, you'll join me for coffee?[n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Amada will gain any more[n]new skills even if I have coffee with him...[n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_042_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I'd be happy if you could join me.[n][uf 1 1][e]

[sel SEL_043_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

