[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0][uf 4 2]-san, I'm glad you're here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Are you available tonight? I have borrowed a book about yakuza from the library.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I was searching for combat-related material, and the librarian suggested this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0]It seems to provide information on combat tactics as well as the proper mindset for battle.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]However, there are some elements that I don't fully comprehend...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]But you may be able to help me understand them more. Would you be willing to try?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I can't today.[e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]In regard to the yakuza novel that we had previously discussed...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I was able to acquire the entire series to which it belongs from the library.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]According to my data, this meets the prerequisite conditions for the activity known as a "binge."[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If you have sufficient leisure time available, would you like to participate in this activity with me?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6075 0 0]Do you remember the yakuza novel we talked about before?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Well, I was able to find the entire series in the library and decided to borrow them all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If I understand correctly, if I read all the books back to back, I would be "binging."[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If you have the time, would you like to "binge" with me?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0][uf 4 2]-san, are you currently free from predetermined obligations at this moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I would like to enlist your assistance in absorbing all necessary information from the yakuza novels.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Aigis looks serious about this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with her could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Aigis might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]There is another matter I wish to discuss with you as well.[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Let's read together.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6110 0 0][uf 4 2]-san, do you have a moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If possible, I would like to continue reading those novels together with you.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Aigis looks serious about this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with her could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Aigis might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Actually... there's something else I would like to talk with you about as well.[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]Let's read together.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]A classmate has recently lent me a number of various yakuza novels.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]She appeared pleased to have met "a fellow yakuza aficionado."[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if we read together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But reading yakuza novels with her[n]could help improve my [uf 4 30 1 1 1 0].[n][uf 1 1][e]

[msg MSG_22_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Would you like to read together once again?[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6004 0 0]A classmate has lent me some yakuza novels that I haven't read yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]She seemed very happy when we talked and called me "a fellow yakuza aficionado."[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if we read together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But reading yakuza novels with her[n]could help improve my [uf 4 30 1 1 1 0].[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If you're free, would you like to read some of them together?[n][uf 1 1][e]

[sel SEL_027_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6044 0 0]You have my gratitude.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Since the two of us will be reading from one book, please open it wide so that we may both view its contents.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6057 0 0]I understand. Very well.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]But, um, we'll be reading from the same book, so... please open it wide so that we can both read.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6056 0 0]I understand... Sorry for bringing this up so abruptly.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]If your schedule permits, I have a favor to ask of you.[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_033_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I would like you to help me improve my reading comprehension abilities.[n][uf 1 1][e]

[sel SEL_034_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's do it.[e]
[uf 0 5 65278][uf 2 1]Maybe another time.[e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6002 0 0]Um, if you have the time... there's something that I'd like your help understanding.[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_036_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm afraid there are some concepts that I have difficulty comprehending on my own...[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's do it.[e]
[uf 0 5 65278][uf 2 1]Maybe another time.[e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Then I shall retrieve the book from my room. Please stand by until I return.[n][uf 1 1][e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Understood.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0]Thank you very much! I will go get the book, then.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6089 0 0]Okay, I understand...[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Would you like to read together, [uf 4 2]-san?[n][uf 1 1][e]

[msg MND_043_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if we read together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But reading yakuza novels with her[n]could help improve my [uf 4 30 1 1 1 0].[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]Reading yakuza novels with Aigis could[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_044_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I would like to read together with you.[n][uf 1 1][e]

[sel SEL_045_0_0 top]
[uf 0 5 65278][uf 2 1]Let's read together.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_046_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Is it correct that you tend to the planters on the rooftop, [uf 4 2]-san?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am interested in attempting horticultural activities as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If such a task is within your purview of operations for the day, would it be acceptable for me to join?[n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_048_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am both prepared and motivated to undertake this action. Shall we commence gardening?[n][uf 1 1][e]

[sel SEL_049_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's go.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_046_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Is it correct that you tend to the planters on the rooftop, [uf 4 2]-san?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I am interested in attempting horticultural activities as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]If such a task is within your purview of operations for the day, would it be acceptable for me to join?[n][uf 1 1][e]

[msg MSG_048_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I am both prepared and motivated to undertake this action. Shall we commence gardening?[n][uf 1 1][e]

[msg MSG_500_0823_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6074 0 0]Is it correct that you tend to the planters on the rooftop, [uf 4 2]-san?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I am interested in attempting horticultural activities as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]If such a task is within your purview of operations for the day, would it be acceptable for me to join?[n][uf 1 1][e]

[msg MSG_050_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6077 0 0][uf 4 2]-san, you take care of the rooftop planters on occasion, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am actually somewhat interested in the process of growing plants myself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]So, um, would it be all right if I accompanied you?[n][uf 1 1][e]

[msg MND_051_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_052_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am ready if you are. Would you like to head to the rooftop?[n][uf 1 1][e]

[sel SEL_053_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_054_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0][uf 4 2]-san, I would like to suggest maintaining the rooftop garden today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]The plants are surely awaiting our continued care.[n][uf 1 1][e]

[msg MND_055_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_056_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I have further analyzed data on home gardens. Let us proceed to the rooftop.[n][uf 1 1][e]

[sel SEL_057_0_0 top]
[uf 0 5 65278][uf 2 1]All right, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_054_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6001 0 0][uf 4 2]-san, I would like to suggest maintaining the rooftop garden today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]The plants are surely awaiting our continued care.[n][uf 1 1][e]

[msg MSG_056_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I have further analyzed data on home gardens. Let us proceed to the rooftop.[n][uf 1 1][e]

[msg MSG_058_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6002 0 0][uf 4 2]-san, would you like to go tend to the planters together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I don't want to deprive our plants of the care that they need.[n][uf 1 1][e]

[msg MND_059_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_060_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I have been practicing how to properly mix fertilizer. I would like to try it out![n][uf 1 1][e]

[msg MSG_061_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Would you find it permissible to visit the rooftop again?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I believe it is time that we check on the progress of our cultivation efforts.[n][uf 1 1][e]

[msg MND_062_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems motivated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Aigis might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_063_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am ready to deploy at any time. Shall we engage, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_064_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_061_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Would you find it permissible to visit the rooftop again?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I believe it is time that we check on the progress of our cultivation efforts.[n][uf 1 1][e]

[msg MSG_063_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I am ready to deploy at any time. Shall we engage, [uf 4 2]-san?[n][uf 1 1][e]

[msg MSG_500_0823_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6059 0 0][uf 4 2]-san, I would like to suggest maintaining the rooftop garden today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]"Summer break" is a time for experiences that cannot be had at any other time of the year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]By tending to a garden in high-temperature conditions, you may be able to achieve this.[n][uf 1 1][e]

[msg MSG_065_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6061 0 0]If you have the time, would you like to go to the rooftop together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I think it would be good to check up on our plants again.[n][uf 1 1][e]

[msg MND_066_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems motivated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Aigis might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_067_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm ready whenever. How about you, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_068_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_069_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Do you intend to continue work on the rooftop planters today?[n][uf 1 1][e]

[msg MND_070_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if she helps me garden...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_071_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am concerned that the vegetation may require additional care.[n][uf 1 1][e]

[sel SEL_072_0_0 top]
[uf 0 5 65278][uf 2 1]All right, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_069_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Do you intend to continue work on the rooftop planters today?[n][uf 1 1][e]

[msg MSG_071_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]I am concerned that the vegetation may require additional care.[n][uf 1 1][e]

[msg MSG_073_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6072 0 0]Do you want to check on the rooftop planters today?[n][uf 1 1][e]

[msg MND_074_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if she helps me garden...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_075_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I have been wondering how our plants are doing lately...[n][uf 1 1][e]

[sel SEL_076_0_0 top]
[uf 0 5 65278][uf 2 1]All right, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_077_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. I will begin making my way to the rooftop with maximum efficiency.[n][uf 1 1][e]

[msg MSG_077_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. I will begin making my way to the rooftop with maximum efficiency.[n][uf 1 1][e]

[msg MSG_078_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. Then I will remain on standby.[n][uf 1 1][e]

[msg MSG_078_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. Then I will remain on standby.[n][uf 1 1][e]

[msg MSG_079_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0]Thank you! Then I will get prepared and head to the rooftop right away.[n][uf 1 1][e]

[msg MSG_080_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6055 0 0]I see. Then perhaps it would be better if I refrain from going up today as well.[n][uf 1 1][e]

[msg MSG_081_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Is your attention preoccupied with the plants as well? Then we are "like-minded," as they say.[n][uf 1 1][e]

[msg MND_082_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if I garden with her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MND_083_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_083_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Shall we make our way to the rooftop together?[n][uf 1 1][e]

[sel SEL_084_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_081_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Is your attention preoccupied with the plants as well? Then we are "like-minded," as they say.[n][uf 1 1][e]

[msg MSG_083_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0]Shall we make our way to the rooftop together?[n][uf 1 1][e]

[msg MSG_085_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6068 0 0]I'm sorry, but I just can't seem to get the garden off my mind...[n][uf 1 1][e]

[msg MND_086_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Aigis will gain any[n]more skills even if I garden with her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MND_087_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MND_088_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_088_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]So... would you like to go to the rooftop together?[n][uf 1 1][e]

[sel SEL_089_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[sel SEL_SEED_CHOOSE top]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 0]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 1]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 2]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 3]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 4]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 5]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 6]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 7]"[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MND_SEED_THINK]
[uf 0 5 65278][uf 2 1]What should I plant...?[n][uf 1 1][e]

[msg MND_SEED_DAY]
[uf 0 5 65278][uf 2 1]Looks like it can be harvested on [uf 0 1 2][uf 2 4 1]/[uf 2 4 2][uf 0 1 27]...[n][uf 1 1][e]

[sel SEL_PLANT_CHOOSE top]
[uf 0 5 65278][uf 2 1]Plant it[e]
[uf 0 5 65278][uf 2 1]Don't plant it[e]

[msg MND_NO_PLANT_DORMITORY]
[uf 0 5 65278][uf 2 1]Come to think of it, I don't think I've planted[n]anything in the rooftop planters yet...[n][uf 1 1][e]

[msg MND_PLANT_CAN_NOT]
[uf 0 5 65278][uf 2 1]Looks like I won't be able to harvest it[n]before the Promised Day, January 31st...[n][uf 1 1][e]

[msg MND_PLANT_OK]
[uf 0 5 65278][uf 2 1]There should still be produce in the rooftop[n]planter that has yet to be harvested.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should harvest those first...[n][uf 1 1][e]

