[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Woof![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Koromaru looks content. Maybe I should[n]take him for a walk tomorrow instead...[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MND_068_0_0]
[uf 0 5 65278][uf 2 1]Koromaru looks like he's having fun.[n][uf 1 1][e]

[msg MSG_071_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_072_0_0]
[uf 0 5 65278][uf 2 1]He seems apologetic about something...[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whimper*[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems dispirited...[n][uf 1 1][e]

[msg MSG_067_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof![n][uf 1 1][e]

[msg MND_069_0_0]
[uf 0 5 65278][uf 2 1]Koromaru looks calm.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems to be in a good mood.[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8005 0 0]*yawn*[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]He's yawning. He must be sleepy...[n][uf 1 1][e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]He seems ready for anything.[n][uf 1 1][e]

[msg MSG_010_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf...?[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6142 0 0]Hmm, I see. Then, I shall continue my observations.[n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0]Don't worry, Koromaru-san. I won't do anything reckless.[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]It almost looks like he's smiling.[n]He's also panting quite hard...[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof![n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems more[n]determined than usual...[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]He seems to be in a good mood.[n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Woof, woof![n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is gazing at me...[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]I can feel a strong sense of[n]determination from Koromaru...[n][uf 1 1][e]

[msg MSG_022_1_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]...Woof.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Koromaru isn't budging. Looks like[n]he won't go for a walk tonight...[n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]Koromaru doesn't look like he'll move.[n]I shouldn't try to take him on a walk...[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is tilting his head. He doesn't[n]seem to be in the mood for a walk...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is radiating with strong resolve. He[n]doesn't look like he wants to go for a walk...[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is relaxing. Looks like[n]he's not up for a walk today...[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is looking at[n]me with pleading eyes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He seems to want to go for a walk...[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]Take him for a walk[e]
[uf 0 5 65278][uf 2 1]Let someone else do it[e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]Go for a walk together[e]
[uf 0 5 65278][uf 2 1]Walk Koromaru alone[e]
[uf 0 5 65278][uf 2 1]Let someone else do it[e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Aigis can come with us tonight.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Sanada can come with us tonight.[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]Junpei can come with us tonight.[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Fuuka can come with us tonight.[n][uf 1 1][e]

[msg MND_037_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru can come with us tonight.[n][uf 1 1][e]

[msg MND_038_0_0]
[uf 0 5 65278][uf 2 1]Aragaki can come with us tonight.[n][uf 1 1][e]

[msg MND_039_0_0]
[uf 0 5 65278][uf 2 1]Amada can come with us tonight.[n][uf 1 1][e]

[msg MND_040_0_0]
[uf 0 5 65278][uf 2 1]Yukari can come with us tonight.[n][uf 1 1][e]

