[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The TV remote is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder if there's a TV[n]program he wants to watch...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching TV with Koromaru could[n]help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Woof?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Watch together[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]The TV remote is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching a show on animals with Koromaru[n]could help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*pant* *pant*[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Watch together[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]The TV remote is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru is looking at[n]me with anticipation...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching a show on animals with him[n]could help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_010_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Watch together[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]The TV remote is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't seem like Koromaru will gain any[n]more new skills even if I watch TV with him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching a show on animals with him[n]could help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*pant* *pant*[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Watch together[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]...! Arf, arf![n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Koromaru will gain any[n]more new skills even if I watch TV with him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching a show on animals with him[n]could help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MND_020_5_0]
[uf 0 5 65278][uf 2 1]Watching TV with Koromaru could[n]help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Watching a show on animals with Koromaru[n]could help with my [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MSG_020_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Watch together[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]A pet brush is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder if this means he[n]wants me to brush him...[n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*pant* *pant*[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Brush him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_026_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]The same pet brush is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru is looking at[n]me with anticipation...[n][uf 1 1][e]

[msg MSG_028_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf! Arf![n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]Brush him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_030_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems more lively than usual...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The usual pet brush is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_032_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]Brush him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_034_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]A familiar pet brush is at Koromaru's feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't seem like Koromaru will gain[n]any more new skills even if I brush him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend time with[n]Koromaru tonight...?[n][uf 1 1][e]

[msg MSG_036_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Brush him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_038_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_039_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MSG_040_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]...! Arf! Arf![n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Koromaru will gain[n]any more new skills even if I brush him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend time with[n]Koromaru tonight...?[n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time with[n]Koromaru tonight...?[n][uf 1 1][e]

[msg MSG_042_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf?[n][uf 1 1][e]

[sel SEL_043_0_0 top]
[uf 0 5 65278][uf 2 1]Brush him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

