[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]Oh, did you need something from the police station, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I just finished saying hi to Kurosawa-san. Took a look at some weapons while I was there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I know you're in charge of our equipment, but it doesn't hurt to check out what's in stock every now and then, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3130 0 0]Well, I'm looking forward to seeing a new haul of equipment.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]I'm in great condition.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]All I need is some equipment to match, and I can't lose.[n][uf 1 1][e]

