[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 5 151 65535 0 0][uf 3 1 1 0 0 1 0 0]M-My side is killing me... I might've overdone it a bit.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Don't push yourself.[e]
[uf 0 5 65278][uf 2 1]Toughen up![e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 5 151 65535 0 0][uf 3 1 1 0 0 2 0 0]I'm not giving up yet. I can keep going.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 8 5 105]Easy for you to say... But honestly, you're probably onto something.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 4 0 0]How 'bout you? You okay? You've really been pushing it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 5 0 0]You don't even look tired... Uh, what kind of training regimen do you have?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Just a normal routine.[e]
[uf 0 5 65278][uf 2 1]A very special routine.[e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 6 0 0]You say that like it's no big deal. Meanwhile I'm dying over here.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 7 0 0]I figured as much. Else I wouldn't be dying over here...[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 8 0 0]You're pretty crazy, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 9 0 0]It kinda sucks... You totally destroyed me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 10 0 0]I knew the standards were high around here, but I never thought someone so good would be right in front of me.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 151 65535 0 0][uf 3 1 1 0 0 11 0 0]Okay, I've made up my mind![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 151 65535 0 0][uf 3 1 1 0 0 12 0 0]Listen up, [uf 4 1]! I'm gonna make you eat my dust![n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Looks like Miyamoto sees me as a rival.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg SYS_011_0_0 [Kazushi Miyamoto]]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 13 0 0]Sorry, I didn't mean to get so worked up.[n][uf 1 1][e]

[msg MSG_012_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 5 151 65535 0 0][uf 3 1 1 0 0 14 0 0]Let's get go— Argh![n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]What's wrong?[e]
[uf 0 5 65278][uf 2 1]Come on, hurry up.[e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 5 151 65535 0 0][uf 3 1 1 0 0 15 0 0]I think I might've... twisted my knee.[n][uf 1 1][e]

[msg MSG_014_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 151 65535 0 0][uf 3 1 1 0 0 16 0 0]Ah, forget it. Let's go.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Miyamoto[n]and went back to the dorm.[n][uf 1 1][e]

