[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]It's almost midnight.[n][uf 1 1][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Oh, but I guess we're not going to Tartarus tonight, huh? Kirijo-senpai said she didn't think everyone would be back in time.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...Um, I'm not boring you, am I? I know this is a special night you're choosing to spend with me.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...Oh, sorry, was that rude? I don't know what I'm saying.[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]This is the first time I've ever done this for Christmas, so I think I'm just nervous.[n][uf 1 1][e]

[msg MSG_002_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]But really, I'm so happy to spend this night with you. I'll never forget it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Thank you for everything. Honestly, I feel like I rely on you so much.[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 1 0][uf 3 1 1 0 0 8 0 0]And not just because you're our leader. I mean for me, personally, because I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 9 0 0]I lo—[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 10 0 0]Ahhh, um, I meant— S-Sorry about that![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 0 0 0 11 0 0][uf 4 23 0 6 0 25 25]......[n][uf 1 1][e]

[msg MSG_004_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 12 0 0]So, what should we do after this?[n][uf 1 1][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 13 0 0]We still have some time left...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I spent time with Fuuka until night fell.[n][uf 1 1][e]

