[msg MSG_TARTAROS_BTL_YUKARI_ [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1128 0 0]If you're not gonna move, then we'll make you![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_YUKARI__2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]Ready? Let's go![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_JUNPEI_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2119 0 0]Move out, squad! Keep your eyes on me![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_JUNPEI__2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Looks tougher than I thought... But ain't nothin' stoppin' me![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_SANADA_ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]Sorry, but we're breaking through![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_SANADA__2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3117 0 0]This'll be fun. C'mon, let's move![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4007 0 0]Incoming! Brace yourselves![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4143 0 0]Let's get through this![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]I'll leave this to you![n][uf 1 1][e]

[msg MSG_TARTAR_BTL_PT_MITSUR [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]Stay alert! The enemy's powers are unknown![n][uf 1 1][e]

[msg MSG_TARTAR_BTL_PT_MITSUR_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4140 0 0]Are you ready? We're forcing our way through![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Approaching enemy Shadow. Eliminating target.[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Entering combat. Come and get it, as they say.[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6005 0 0]This may be a tough battle. Let's exercise caution![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6118 0 0]I'll give it everything I've got, so let's work together![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_KOROMAR [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrr... Arf![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_KOROMAR_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrrrrr...![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7119 0 0]Come on, bring it! I'll take you on![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AMADA_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]Here it comes! Let's take it down![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Get ready, here it comes![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_ARAGAKI_2 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9108 0 0]If we can't get through, then we're just gonna have to pulverize 'em.[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]Incoming enemy Shadow![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]I'll support you! We'll get through this together![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]You can do this! I believe in you![n][uf 1 1][e]

