[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Wha...!?[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Ah...![n][uf 1 1][e]

[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]No![n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]This is... not a Shadow...[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]I think it's...[n]It's all of humanity's...[n][uf 1 1][e]

[msg MSG_004_0_0 [Metis]]
[uf 0 5 65278][uf 2 1]Just as I thought... The purpose of his seal—[n]It's not meant to hold back Nyx.[n][uf 1 1][e]

[msg MSG_004_1_0 [Metis]]
[uf 0 5 65278][uf 2 1]It's to prevent something from reaching her.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]What do you mean?[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]That giant monster...[n]It's not a Shadow...[n][uf 1 1][e]

[msg MSG_006_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]It's... a mass of the worst traits and[n]feelings from every person's heart...[n][uf 1 1][e]

[msg MSG_006_2_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Deep down...[n]Everyone is calling for Nyx...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]That can't be...[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]There was a time...[n]when I also wished for death.[n][uf 1 1][e]

[msg MSG_008_1_0 [Aigis]]
[uf 0 5 65278][uf 2 1]It's probably true that everyone has[n]a part of them secretly yearning for it...[n][uf 1 1][e]

[msg MSG_008_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1]The only thing that separates[n]the living from the nonliving...[n][uf 1 1][e]

[msg MSG_008_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Is death... The greatest equalizer.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]I think I understand...[n][uf 1 1][e]

[msg MSG_009_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]When you feel like your life has no meaning,[n]the thought of death can be comforting...[n][uf 1 1][e]

[msg MSG_009_2_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]And that subconscious desire is so strong...[n]it could even create a monster like this.[n][uf 1 1][e]

[msg MSG_009_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]I guess that's... just how it is these days.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]What the hell...!?[n][uf 1 1][e]

