[msg MSG_000_0_0 [Energetic Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Hey, Amada![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]You on your way home? Us too, we just finished eating dinner.[n][uf 1 1][e]

[msg MSG_001_0_0 [Calm Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Oh, are you from the same class, Amada-kun?[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...Yes. It's nice to meet you.[n][uf 1 1][e]

[msg MSG_003_0_0 [Energetic Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Oh yeah, Amada, you gotta join next month's soccer tournament![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]We've all been waiting for you, y'know? We can even practice together after school![n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I'll have to pass.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 8 3 25 25]I'm not even sure if I could make it next month.[n][uf 1 1][e]

[msg MSG_005_0_0 [Energetic Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]Aww, come on, we can't win without you! You're better than all of us![n][uf 1 1][e]

[msg MSG_006_0_0 [Calm Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]You can't pressure someone like that. Can't you see you're bothering him?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]I'm sure Amada-kun has a lot going on, isn't that right?[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Oh, no, it's fine.[n][uf 1 1][e]

[msg MSG_008_0_0 [Calm Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]I'm sorry, please excuse us. You should hurry home too, Amada-kun.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Home...[n][uf 1 1][e]

[msg MSG_010_0_0 [(SE) Calm Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]Come on, let's get going. Your grandma is waiting for us.[n][uf 1 1][e]

[msg MSG_011_0_0 [(SE) Energetic Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]But Mooom, if Amada doesn't join us, we're gonna get totally creamed![n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Sorry about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 18 0 0][uf 4 23 0 8 3 25 25]......[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Do you not like playing soccer?[e]
[uf 0 5 65278][uf 2 1]Do you guys not get along?[e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]No, it's not that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 8 0 25 25]I just have enough to do. Second semester has already started, and we have to go to Tartarus at night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I know we'll be going through a lot from now on, so I decided to not make any promises.[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]More importantly, sorry for keeping you out so late.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 8 1 25 25]Let's make our way back to the dorm.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I parted with Amada and[n]returned to my room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 0 1 1 0][n]improved after thinking about[n]what's on Amada's mind...[n][uf 1 1][e]

