[msg MSG_000_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 3 0 65535 15207 0 0]Ah, [uf 4 1]. I've been waiting for you... Okay, not really.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]I looked and looked, but there's nothing at my house that's not related to Masamune.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]This didn't belong to Masamune personally, but it still has ties to him, so...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 4 25 1083]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Do you really need this? Maybe you've... reconsidered?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Not that I'm reluctant at all to give it to you, of course.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]So I'll give it to you, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]But...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]You'll take good care of it, right!? It'll become a family heirloom, right!?[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono gave me his (ITEM NAME).[n][uf 1 1][e]

[msg MSG_003_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 3 0 65535 15222 0 0]You must be proud, [uf 4 1]. You've got a family heirloom now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Yeah, I guess this is how it should be...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 4 25 1083]......[n][uf 1 1][e]

[msg MSG_004_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Well, I've still got a few of those left at home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]This is the second time I've given a helm to a student, after all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]That Bebe... Do you know him? He's an exchange student in my class.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Back in the spring, when he first came here, he admired it so much that I let him have it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]It does my heart good to see the samurai spirit is still alive in you kids, even those from a foreign country.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]It must be because the glorious lives of the Sengoku generals transcend history...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Masamune Date, for example. The amazing thing about him is that he...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I enjoyed even more[n]stories about Masamune.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I have a deeper understanding of history...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I managed to obtain a helm from Mr. Ono.[n][uf 1 1][e]

