[msg MSG_000_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0][uf 3 1 3 0 65535 14823 0 0]What brings you to the nurse's office? Eeeheehee...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]Now, what do we have here? You seem rather tired. Is it a wound? A virus? A curse? Or maybe love?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]This is the perfect opportunity to test my new concoction... Eeeheeheeheehee![n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0][uf 3 1 3 0 65535 14804 0 0]Here, try this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]It has bitter mugwort, poison carrot, henbane, jujube, rabbit's foot, etcetera, etcetera...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]Even Hakusan's finest alchemist would be astonished by these ingredients.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]I shall improve your condition right here and now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14808 0 0]Now, drink this... Come on... Bottoms up![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]The medicine Mr. Edogawa gave[n]me smells incredibly bizarre...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...Should I drink it?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Drink it[e]
[uf 0 5 65278][uf 2 1]Don't drink it[e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I downed the strange medicine, but[n]nothing seems to have changed...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0][uf 3 1 3 0 65535 14817 0 0]Phew... Well done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]Whether or not it works is inconsequential... You survived![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]You've already emptied your cup, but... cheers to your bravery![n][uf 1 1][e]

[msg MSG_006_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14815 0 0]Hm, if you'll excuse me, Saturn is calling...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14820 0 0]...What do you mean you won't drink it!? Coward! Even Algernon drank it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]That normally quiet mouse went out of here positively squeaking with energy![n][uf 1 1][e]

[msg MSG_008_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14822 0 0]Oh, Algernon is my familiar— Er, I mean, my pet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0]Well, it's best not to take too much medication when possible.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14803 0 0]You should head home and get some rest. Off you go now.[n][uf 1 1][e]

