[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30066 0 0]Huh... This is the first time I've witnessed a school student fulfilling their educational obligations.[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Why do you write out all of the calculations involved instead of just the answer? It's inefficient.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Um... I guess so you can prove that you know how to solve the problem correctly?[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]So providing the answer isn't considered sufficient proof that you know how to solve the problem correctly?[n][uf 1 1][e]

[msg MSG_004_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Did I... say something wrong?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]You're distracting her.[e]
[uf 0 5 65278][uf 2 1]We should just let her work.[e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30086 0 0]Oh... If you say so.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I'm sorry, it's just that this one is really difficult...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0]Hmmm...[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5075 0 0]Actually... I think it's because just finding the answer isn't the important part.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]What? But isn't that the goal of the assignment?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5064 0 0]Well, that's part of it. But I think the point is to learn the process.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 4 23 0 1 0 25 25]It's about knowing which formulas or techniques will help you solve the problem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 4 23 0 1 1 25 25]And once you know all that, finding the solution is easy, even when you start on another problem with different numbers.[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]I see... So studying is about acquiring specific mindsets.[n][uf 1 1][e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]Fuuka-san is a good teacher, isn't she, Sister? She makes things so easy to understand![n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, she is.[e]
[uf 0 5 65278][uf 2 1]She's the brains of the team.[e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 3 0 65535 5099 0 0]Oh, I'm not, really. You were just asking the right questions, Metis.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5051 0 0]Hehe, I don't know about that. But I appreciate the compliment.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5075 0 0]Oh, and also... I think it's fun to write out the calculations. It's like I'm having a conversation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 4 23 0 1 0 25 25]How do I explain it...? When I figure out an answer, I feel like I understand the intent of the person who wrote the problem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 4 23 0 1 0 25 25]For example, I can see when they're trying to mislead me, or I can tell they want me to use a certain formula.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 4 23 0 1 1 25 25]If I can figure out what the problems are getting at, I feel like I'll be more prepared for the exams.[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 3 0 65535 5068 0 0]Hm... Couldn't this apply to my navigation too? I think there are actually a lot of similarities...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Talking with us seems to have helped[n]Fuuka-san come up with something...[n][uf 1 1][e]

[msg MSG_019_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]So studying also helps with exploration...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Then I suppose school must enforce a rather intense regimen.[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 3 0 65535 5102 0 0]Oh, uh... Sorry, I may have given you the wrong idea...[n][uf 1 1][e]

