[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2074 0 0]We're comin' up on our last shot...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]This is it, guys. We're finally gonna get to the bottom of all this.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Supposedly, it has to do with us and our Personas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]You don't think that the only way out of this... is for us to die... do you?[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3123 0 0]Thinking like that gets you nowhere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]We only got this far because we believed there'd be another way.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0]Y-You're right... Sorry, I'm going back to my bad habits again.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4140 0 0]We won't have to endure this for much longer. Everyone, brace yourselves. We're going in.[n][uf 1 1][e]

