[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7075 0 0]There were seven doors in the Desert at the start... meaning we have to clear seven different areas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]I used to think this would take forever, but now there are only two doors left.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3026 0 0]Yeah... We're nearly there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Now's the time to step it up, guys. Let's press on![n][uf 1 1][e]

