[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]......[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Despite its simple appearance,[n]the soup has a complex flavor[n]that's enhanced by the noodles.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 10 25 25]Maaan... I'm so sick of this, dude.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]What, of ramen?[e]
[uf 0 5 65278][uf 2 1]What, of school?[e]
[uf 0 5 65278][uf 2 1]What, of life?[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 10 25 25]No, not that. Wouldn't be here if I was sick of ramen.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 3 25 25]Dude, I've been sick of school since day one.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 3 25 25][uf 5 13 2 15 101]Life? Dude, you watch too much reality TV.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 10 25 25]But I guess, yeah, you could say I'm sick of life.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]I mean, I get up, go to school, sit through lame-ass lectures, eat, watch TV, and go to bed.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Okay, that settles it, [uf 4 1]. I'm gonna get myself a girlfriend! Right now![n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds impossible.[e]
[uf 0 5 65278][uf 2 1]Good luck![e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 2 25 25]What're you talking about!? I'm a smooth operator! Smooth as hell![n][uf 1 1][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25][uf 5 13 2 5 101]What a cool thing to say! Soon I'll have a girlfriend and be just as cool as you![n][uf 1 1][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Alright, I think I'm gonna pull the trigger on my secret plan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]I told you about the teacher, right? I'm gonna ask her out and get her to fall in love with me.[n][uf 1 1][e]

[msg MSG_012_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]Her name is Ms. Kanou. You heard of her? She teaches third-year ethics. We get along pretty well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]She's not mainstream beautiful, but she's really pretty. She's got these cute little eyes, a sexy body...[n][uf 1 1][e]

[msg MSG_013_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 4 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 4 25 25]Uh, don't tell anyone about this, okay? You're the only one who knows.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Tomochika told me more about his plan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger...[n][uf 1 1][e]

[msg MSG_015_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Dude, I'm getting so psyched! Let's cook up a plan of attack![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Tomochika and I chatted[n]on the walk home.[n][uf 1 1][e]

