[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]My body feels light...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But my time wasn't that good.[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I beat my record![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm second on the team.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Just one person left...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The tournament is the[n]day after tomorrow...[n][uf 1 1][e]

