[msg MSG_037_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5086 0 0]I'm not picking up the signal anymore. It looks like we've won.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]He was so strong... He even had the same power as Aigis.[n][uf 1 1][e]

[sel SEL_060_0_0 top]
[uf 0 5 65278][uf 2 1]That was a formidable foe.[e]
[uf 0 5 65278][uf 2 1]That was an easy fight.[e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5010 0 0]You can say that again. Good work out there.[n][uf 1 1][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5131 0 0]Hehe. I never doubted you for a second.[n][uf 1 1][e]

[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]Still, though... I wonder who that was. He gave off such a strange reading.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]Like it wasn't a Shadow, but it wasn't human either. It was more like... a mass of someone's thoughts or desires?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]The more I think about it, the less sense it makes...[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30067 0 0][uf 4 23 1 11 4 25 25]If I had to guess... I'd say that person was likely the product of the Abyss of Time reflecting someone's wishes.[n][uf 1 1][e]

[msg MSG_032_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 50 0 0][uf 3 1 3 0 65535 30067 0 0][uf 4 23 1 11 4 25 25]If I had to guess... I'd say that person was likely the product of the Abyss of Time reflecting someone's wishes.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Really? But none of us know who that person is, so I don't think any of us would have wished to encounter them.[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 4 23 1 11 0 25 25]Maybe nobody wished to meet that specific person, but they could've wished for something like...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]"I want to fight someone really strong," for example. Something more vague.[n][uf 1 1][e]

[msg MSG_002_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 50 0 0][uf 4 23 1 11 0 25 25]Maybe nobody wished to meet that specific person, but they could've wished for something like...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 50 0 0]"I want to fight someone really strong," for example. Something more vague.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, I was wishing that.[e]
[uf 0 5 65278][uf 2 1]I wouldn't wish for that.[e]
[uf 0 5 65278][uf 2 1]Perhaps it was Sanada-san.[e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5025 0 0]Oh, in that case, I guess your wish was granted! Maybe it's because you've been going into the Abyss so often.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5062 0 0]Hmm... Maybe it wasn't exactly that, but something similar, like you wished to get stronger, or you wished for a challenge...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]I think it could make sense for wishes like that to be granted like this too.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3060 0 0]Yeah, that sounds like me, all right.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5094 0 0]That does certainly sound like something he would wish for...[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]I guess it's also possible that the Abyss had nothing to do with it, and this was the doing of some other thing in some other place...[n][uf 1 1][e]

[msg MSG_034_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 50 0 0]I guess it's also possible that the Abyss had nothing to do with it, and this was the doing of some other thing in some other place...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0]A place other than the Abyss...?[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30057 0 0]Maybe someone's—or multiple people's—inner thoughts were manifested somewhere else, and that place connected to the Abyss...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 4 23 1 11 4 25 25]And if the Abyss used that connection to grant a wish, then maybe both it and the other place are equally responsible...[n][uf 1 1][e]

[msg MSG_010_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 50 0 0][uf 3 1 3 0 65535 30057 0 0][uf 4 23 1 11 4 25 25]Maybe someone's—or multiple people's—inner thoughts were manifested somewhere else, and that place connected to the Abyss...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 50 0 0][uf 4 23 1 11 4 25 25]And if the Abyss used that connection to grant a wish, then maybe both it and the other place are equally responsible...[n][uf 1 1][e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 23 1 11 3 25 25]Um... This got too complicated. I'm lost.[n][uf 1 1][e]

[msg MSG_036_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 50 0 0][uf 4 23 1 11 3 25 25]Um... This got too complicated. I'm lost.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5062 0 0][uf 4 23 1 11 0 25 25]Me too. Maybe we're just not meant to understand what happened...[n][uf 1 1][e]

