[msg MSG_000_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[sel SEL_001_0_0_1 top]
[uf 0 5 65278][uf 2 1]未使用[e]
[uf 0 5 65278][uf 2 1]未使用[e]
[uf 0 5 65278][uf 2 1]未使用[e]

[msg MSG_002_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_003_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_004_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_005_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MND_006_0_0_1]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_007_0_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_000_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 50 0 0][uf 3 1 3 0 65535 2138 0 0]Hey, hey, can ya hear me? Oh, cool, looks like we're already connected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]Yo, how goes? It sounds like you guys are on a roll.[n][uf 1 1][e]

[msg MSG_001_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 50 0 0]...Ryoji was saying there's no way we could win.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]But the way things are goin', this'll be a cakewalk! Heh, I'm just kiddin', but it'd be sweet, though.[n][uf 1 1][e]

[sel SEL_002_0_0_2 top]
[uf 0 5 65278][uf 2 1]Don't get careless.[e]
[uf 0 5 65278][uf 2 1]Well, we'll see.[e]
[uf 0 5 65278][uf 2 1]It just might be a cakewalk.[e]

[msg MSG_003_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0][uf 3 1 3 0 65535 2133 0 0]Don't worry, man. I'm not takin' it lightly. I'm just bein' confident, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]Better to think you can do it than to think you can't, right?[n][uf 1 1][e]

[msg MSG_004_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0][uf 3 1 3 0 65535 2133 0 0]Ha, yeah, fair enough. We're goin' up against a legit monster, aren't we?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]But still, better to be confident so the nerves don't get the best of us, right?[n][uf 1 1][e]

[msg MSG_005_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0][uf 3 1 3 0 65535 2132 0 0]Heheh, even after all that doom and gloom about how we're gonna lose, you're not even fazed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]You're somethin' else, man. You might even give me a run for my money over who's MVP![n][uf 1 1][e]

[msg MSG_006_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 50 0 0]Don't get me wrong, I know he was serious when he said we couldn't beat Nyx.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]So I'm gonna laugh my ass off when we prove him wrong![n][uf 1 1][e]

[msg MND_007_0_0_2]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0]Alright, people, all the best to ya! If you're in a pinch, you know who to call![n][uf 1 1][e]

[msg MSG_000_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0][uf 3 1 3 0 65535 7002 0 0][uf 4 1]-san, can you hear me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 50 0 0]Good job taking down the Gatekeeper![n][uf 1 1][e]

[msg MSG_001_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]As we get closer to the top, I keep thinking about a lot of things.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]I wonder if this is how heroes feel right before the season finale.[n][uf 1 1][e]

[sel SEL_002_0_0_3 top]
[uf 0 5 65278][uf 2 1]Yeah, maybe.[e]
[uf 0 5 65278][uf 2 1]It's not exactly the same...[e]
[uf 0 5 65278][uf 2 1]No idea.[e]

[msg MSG_003_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0][uf 3 1 3 0 65535 7068 0 0]In that sense, it's quite an experience, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]I never expected my daydreams to become reality...[n][uf 1 1][e]

[msg MSG_004_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 50 0 0][uf 3 1 3 0 65535 7133 0 0]Haha, sorry. Don't worry, I know that, in their case, they're only acting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]I just thought it might help to think of ourselves as "heroes," or something.[n][uf 1 1][e]

[msg MSG_005_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0][uf 3 1 3 0 65535 7063 0 0]Oh, please don't get me wrong. I know it's only fiction.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]I just thought it might help me think more positively if I put myself in a hero's shoes.[n][uf 1 1][e]

[msg MSG_006_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 50 0 0]You know... heroes aren't strong because they never lose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 50 0 0]They're strong because they never give up. That's what I think, at least.[n][uf 1 1][e]

[msg MND_007_0_0_3]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0]According to Fuuka-san, there are still a lot of Gatekeepers before we reach the top.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 50 0 0]But we'll make it for sure. And I'm ready to go anytime![n][uf 1 1][e]

[msg MSG_000_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4086 0 0]Well done on that victory. Keep up your diligence.[n][uf 1 1][e]

[msg MSG_001_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You're approaching the 250th floor. We've come quite a long way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It hasn't even been a full year since most of you joined SEES. You've all done wonderfully.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 50 0 0]I can't thank you enough for putting up with everything despite what you've had to go through.[n][uf 1 1][e]

[sel SEL_002_0_0_4 top]
[uf 0 5 65278][uf 2 1]Don't mention it.[e]
[uf 0 5 65278][uf 2 1]You owe me one.[e]
[uf 0 5 65278][uf 2 1]Ramen's on you.[e]

[msg MSG_003_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4131 0 0]*chuckle* That's quite generous of you. Thank you.[n][uf 1 1][e]

[msg MSG_004_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4028 0 0]That's very true. Though it's not a debt I'm sure I'll ever be able to fully repay.[n][uf 1 1][e]

[msg MSG_005_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]Ramen? Why something so simple? You could always— ...No, you're absolutely right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]We've been fighting this whole time to return to a normal life, after all.[n][uf 1 1][e]

[msg MSG_006_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]...Those that we've lost are with us now in spirit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We will win. Everyone's future is in our hands.[n][uf 1 1][e]

[msg MND_007_0_0_4]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 65535 50 0 0]All right, keep dispatching the Gatekeepers just like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 65535 50 0 0]There are five left, so stay sharp. I'll also be prepared on my end, in case you need me.[n][uf 1 1][e]

[msg MSG_000_0_0_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]Good job, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Just a bit more to the top. Please be carefu— Hm?[n][uf 1 1][e]

[msg MSG_001_0_0_5 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_002_0_0_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]Oh, it looks like Koro-chan wants to tell us something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]What is it, Koro-chan?[n][uf 1 1][e]

[msg MSG_003_0_0_5 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0]Arf, arf![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0]Arf arf! Arf![n][uf 1 1][e]

[msg MND_004_0_0_5]
[uf 0 5 65278][uf 2 1]I feel a strong sense of[n]urgency from Koromaru...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems like he's encouraging us.[n][uf 1 1][e]

[msg MSG_005_0_0_5 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0]Ruff![n][uf 1 1][e]

[sel SEL_006_0_0_5 top]
[uf 0 5 65278][uf 2 1]We're counting on you, too.[e]
[uf 0 5 65278][uf 2 1]You get a treat after this.[e]
[uf 0 5 65278][uf 2 1]Woof, woof, woof![e]

[msg MSG_007_0_0_5 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 50 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MND_008_0_0_5]
[uf 0 5 65278][uf 2 1]Koromaru appears even[n]more motivated now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_009_0_0_5 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0]Grrr... Arf![n][uf 1 1][e]

[msg MSG_010_0_0_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]*chuckle* All set, Koro-chan? Then let's keep moving![n][uf 1 1][e]

[msg MSG_000_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0][uf 3 1 3 0 65535 3085 0 0]Good work with that fight. We should be getting close to the finish line now...[n][uf 1 1][e]

[msg MSG_001_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]You've fought your fair share of battles at this point.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]Any time you're in a slump, just remember all the blood and sweat you put into this.[n][uf 1 1][e]

[sel SEL_002_0_0_6 top]
[uf 0 5 65278][uf 2 1]That's deep.[e]
[uf 0 5 65278][uf 2 1]I haven't sweat that much.[e]
[uf 0 5 65278][uf 2 1]That stuff's irrelevant.[e]

[msg MSG_003_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 50 0 0][uf 3 1 3 0 65535 3130 0 0]Well, I hope it keeps you motivated.[n][uf 1 1][e]

[msg MSG_004_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 50 0 0][uf 3 1 3 0 65535 3130 0 0]True, you always seem to keep your cool.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]But we all know how much work you've put in.[n][uf 1 1][e]

[msg MSG_005_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0][uf 3 1 3 0 65535 3136 0 0]Hm... Are you saying perseverance alone won't cut it against our opponent?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]Well, that may be true, but I still believe in the skills that we got through that perseverance.[n][uf 1 1][e]

[msg MSG_006_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]Anyway, bottom line is I don't want to have any regrets.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]I'll do my job to the best of my ability, so you keep it up too, Leader.[n][uf 1 1][e]

[msg MND_007_0_0_6]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0]Sorry for interrupting in the middle of your streak. Keep doing what you're doing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 50 0 0]There's no point holding back from here on out, so give it your all! I'm ready too, anytime.[n][uf 1 1][e]

[msg MSG_000_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 50 0 0][uf 3 1 3 0 65535 1061 0 0]Hey, can you hear me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 50 0 0]You're doing great! You're almost there![n][uf 1 1][e]

[msg MSG_001_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 50 0 0]So, um... I know this goes without saying, but let's make sure we win this, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 50 0 0]It's just... we have so many great memories together, and we should keep making more, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 50 0 0]Oh, sorry, uh... I'm being weird, saying all this stuff out of nowhere, huh?[n][uf 1 1][e]

[sel SEL_002_0_0_7 top]
[uf 0 5 65278][uf 2 1]It's not weird at all.[e]
[uf 0 5 65278][uf 2 1]Yeah, weirdo.[e]
[uf 0 5 65278][uf 2 1]Actually, you're like this a lot.[e]

[msg MSG_003_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 50 0 0][uf 3 1 3 0 65535 1132 0 0]Oh, good! I thought maybe I was acting out of character, but I'm glad you're okay with it, haha.[n][uf 1 1][e]

[msg MSG_004_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 50 0 0][uf 3 1 3 0 65535 1132 0 0]Hey, knock it off! But yeah, it's kinda weird, haha! Still, that's how I feel, so I don't regret saying it.[n][uf 1 1][e]

[msg MSG_005_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 50 0 0][uf 3 1 3 0 65535 1098 0 0]O-Oh, really? Well, I guess I am this way more when I'm with you...[n][uf 1 1][e]

[msg MSG_006_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 50 0 0]Anyway... I won't give up until the very end. Actually, no... I won't let there be an end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 50 0 0]So... here's to making more memories, Leader.[n][uf 1 1][e]

[msg MND_007_0_0_7]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 50 0 0]All right, I'll let you get back to it. You're almost there! You got this![n][uf 1 1][e]

[msg MSG_000_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 50 0 0][uf 3 1 3 0 65535 6006 0 0]Good job, everyone! Now there's only one more left... You're very close.[n][uf 1 1][e]

[msg MSG_001_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 50 0 0]To be honest... I was a little worried.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 50 0 0]I thought my desire for the ones close to me to avoid pain may result in my inability to fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0]However, the opposite seems to be the case. I feel a stronger motivation to fight than before.[n][uf 1 1][e]

[sel SEL_002_0_0_8 top]
[uf 0 5 65278][uf 2 1]That's called "courage."[e]
[uf 0 5 65278][uf 2 1]How interesting.[e]
[uf 0 5 65278][uf 2 1]You're very reliable.[e]

[msg MSG_003_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0][uf 3 1 3 0 65535 6107 0 0]Oh, so this is courage! I suppose everyone has felt this all this time...[n][uf 1 1][e]

[msg MSG_004_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0][uf 3 1 3 0 65535 6131 0 0]Indeed. But I'm sure you have all felt this ever since you first decided to fight.[n][uf 1 1][e]

[msg MSG_005_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0][uf 3 1 3 0 65535 6025 0 0]Yes, please feel free to rely on me anytime.[n][uf 1 1][e]

[msg MSG_006_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0]I will embrace this new feeling and continue to fight alongside everyone.[n][uf 1 1][e]

[msg MND_007_0_0_8]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg MSG_008_0_0_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 50 0 0]Well, stay safe and good luck. And remember, I am always ready at a moment's notice.[n][uf 1 1][e]

[msg MSG_000_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5131 0 0]The Gatekeeper's signal just went down![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]We did it! That was the last one![n][uf 1 1][e]

[sel SEL_001_0_0_9 top]
[uf 0 5 65278][uf 2 1]It's about time.[e]
[uf 0 5 65278][uf 2 1]Now just the real battle.[e]

[msg MSG_002_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5144 0 0]I agree. It's been one harsh battle after another...[n][uf 1 1][e]

[msg MSG_003_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Yes, you're right. We're almost at our goal...[n][uf 1 1][e]

[msg MSG_004_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But now that the Gatekeepers are out of the way, our path is clear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]...I sense an area with no outer wall a little higher up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]That's probably the place Ryoji-kun was talking about...[n][uf 1 1][e]

[msg MSG_005_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Let's go, all of us, together![n][uf 1 1][e]

[msg MSG_006_0_0_9 [（ＳＥ）伊織 順平]]
[uf 0 5 65278][uf 2 1]おうよ！[n][uf 1 1][e]

[msg MSG_007_0_0_9 [（ＳＥ）岳羽 ゆかり]]
[uf 0 5 65278][uf 2 1]うん！[n][uf 1 1][e]

[msg MSG_008_0_0_9 [（ＳＥ）真田 明彦]]
[uf 0 5 65278][uf 2 1]ああ。[n][uf 1 1][e]

[msg MSG_009_0_0_9 [（ＳＥ）桐条 美鶴]]
[uf 0 5 65278][uf 2 1]そうだな。[n][uf 1 1][e]

[msg MSG_010_0_0_9 [（ＳＥ）コロマル]]
[uf 0 5 65278][uf 2 1]ワン！[n][uf 1 1][e]

[msg MSG_011_0_0_9 [（ＳＥ）天田 乾]]
[uf 0 5 65278][uf 2 1]はい！[n][uf 1 1][e]

[msg MSG_012_0_0_9 [（ＳＥ）アイギス]]
[uf 0 5 65278][uf 2 1]…はい！[n][uf 1 1][e]

[msg MND_013_0_0_9]
[uf 0 5 65278][uf 2 1]I can sense everyone's strengthened[n]resolve as we head into the final battle...[n][uf 1 1][e]

[msg SYS_014_0_0_9]
[uf 0 5 65278][uf 2 1]The Judgement Social Link reached its maximum level! You can now fuse [uf 0 1 35]Messiah[uf 0 1 27], the savior![n][uf 1 1][e]

[msg MSG_015_0_0_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Please be careful out there. And good luck![n][uf 1 1][e]

