[msg MSG_000_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 10]What a coincidence, seeing you today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 10]It must be another one of God's whims...[n][uf 1 1][e]

[msg MSG_001_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 10]Today is my son's... Akinari's birthday.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 10]He'd be twenty if he was still alive.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 10]Only nineteen years...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 10]...It was too soon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 10]He was almost an adult, but he never made it...[n][uf 1 1][e]

[msg MSG_003_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 10]Akinari had a genetic disease. I'm completely healthy, but him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 9 0 0]......[n][uf 1 1][e]

[msg MSG_003_3_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 10]The doctors detected it when he was born... They knew he wouldn't live to see adulthood.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 10]Every day, I worried whether he'd wake up the next morning... I blamed myself for what he inherited...[n][uf 1 1][e]

[msg MSG_003_7_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 10]But...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 10]He said something to me near the end.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kamiki's Words]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]"I'm sorry to have brought so much pain into your life, Mother."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]"I'm glad that I was born into this world."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]"I'm glad to have been your son."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]"Thank you for the life you've given me."[n][uf 1 1][e]

[msg MSG_005_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 10]"I'm sorry to have brought so much pain into your life, Mother."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 10]"I'm glad that I was born into this world."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 10]"I'm glad to have been your son."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 10]"Thank you for the life you've given me."[n][uf 1 1][e]

[msg MSG_006_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 10]He...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 10]He suffered so much, and yet he still said that to me...[n][uf 1 1][e]

[msg MSG_007_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 10]But... Akinari brought me so much happiness too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 10]Feeling his warmth as I carried him in my arms after he was born... Those tiny hands... That first smile...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 10]Hearing his breathing as he slept at night...[n][uf 1 1][e]

[msg MSG_007_3_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 10]Every day, I was so grateful he was alive... Every day, I found new joy in him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 10]Now... I'm so alone, and there's nothing I can do...[n][uf 1 1][e]

[msg MSG_007_7_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 10]But, my boy gave me so much...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 10]I have to keep going, looking straight ahead... That's how I want to live.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 10]I'll eat the finest foods, visit the most exotic places...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0][uf 5 21 0 10]I'll do everything, absolutely EVERYTHING, that Akinari couldn't...[n][uf 1 1][e]

[msg MSG_008_5_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0][uf 5 21 0 10]I'll have so many stories to tell him about the things I've done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0][uf 5 21 0 10]On that day... when we meet again, on the other side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0][uf 5 21 0 10]If I didn't have that to look forward to... I don't know how I could go on.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0][uf 5 21 0 10]That reminds me... When my son's condition worsened, he started writing a children's story.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0][uf 5 21 0 10]But when I was cleaning out his room, I never found his notebook...[n][uf 1 1][e]

[msg MSG_009_5_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0][uf 5 21 0 10]He said he wanted you to be the first one to see it, when he was done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0][uf 5 21 0 10]Then he laughed and said I would be second...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0][uf 5 21 0 10]I suppose... he wasn't able to finish the story...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]He did finish it.[e]
[uf 0 5 65278][uf 2 1]I have the notebook.[e]

[msg MSG_011_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0][uf 5 21 0 10]What...? So, did you get to read the story...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0][uf 5 21 0 10]What...? My son... He gave it to you?[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I explained how I received the notebook from[n]Kamiki, and that I heard the entire story...[n][uf 1 1][e]

[msg MSG_014_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0][uf 5 21 0 10]I... I see... So, you did...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0][uf 5 21 0 10]I'm so glad... That was my only regret...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 45 0 0][uf 5 21 0 10]It was awful to think that he wasn't able to finish his project...[n][uf 1 1][e]

[msg MSG_015_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 46 0 0][uf 5 21 0 10]...Oh, you should hold onto his notebook. I'm sure that's what he would want, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 47 0 0][uf 5 21 0 10]I'll hear the story from him directly, when I see him on the other side...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 48 0 0][uf 5 21 0 10]...Now I have one more thing to look forward to.[n][uf 1 1][e]

[msg MSG_016_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 49 0 0][uf 5 21 0 10]I'm glad I could finally meet you. Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 50 0 0][uf 5 21 0 10]...Before I go, let this old woman give you one piece of advice...[n][uf 1 1][e]

[msg MSG_016_3_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 51 0 0][uf 5 21 0 10]Take good care of the ones you hold dear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 52 0 0][uf 5 21 0 10]If you wait until their day comes... it's too late. Clinging to their cold bodies won't bring them back.[n][uf 1 1][e]

[msg MSG_016_5_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 53 0 0][uf 5 21 0 10]...Everyone who's born will die someday.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 54 0 0][uf 5 21 0 10]Not just Akinari, or me, or even you. It's all the same...[n][uf 1 1][e]

[msg MSG_016_7_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 55 0 0][uf 5 21 0 10]So before that happens...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 56 0 0][uf 5 21 0 10]It doesn't take a grand gesture. You don't have to make a big production of it, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 57 0 0][uf 5 21 0 10]If you love someone, let them know it.[n][uf 1 1][e]

[msg MSG_017_0_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 58 0 0][uf 5 21 0 10]We all go through life with the same struggles, the same heartbreak...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 59 0 0][uf 5 21 0 10]We should all lift each other up with the same love and kindness as well...[n][uf 1 1][e]

[msg MSG_017_5_0 [Kamiki's Mother]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 60 0 0][uf 5 21 0 10]I'm sure you have something precious you can share with people, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 61 0 0][uf 5 21 0 10]Don't ever forget it...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Kamiki's mother left without looking back...[n][uf 1 1][e]

