[msg MND_000_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]It's a promo message from the burger[n]place. Should I go there now...?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go[e]
[uf 0 5 65278][uf 2 1]Don't go[e]

[msg MSG_002_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_003_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MND_004_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]UNUSED[e]
[uf 0 5 65278][uf 2 1]UNUSED[e]

[msg MSG_006_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_007_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

