[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Looks like Junpei wants to[n]watch a movie together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, watching it could help[n]improve my [uf 4 30 1 37 1 0]...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go with Junpei[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I should reply to him...[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I'll reply later...[n][uf 1 1][e]

