[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I need to go to the faculty office to complete[n]the paperwork for joining the student council.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I head to the faculty office right now?[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]Maybe I should introduce myself to the rest[n]of the student council now that I've joined.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I head to the student[n]council room right now?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

