[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Yukari wants to[n]spend time together...[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]Should I meet up with her?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Yukari[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Yukari is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

