[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems troubled...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet with her?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Mitsuru[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Mitsuru is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Come to think of it, I still have Aragaki's[n]leave of absence extension form...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet with Mitsuru?[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I already gave her Aragaki's leave[n]of absence extension form...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I have Aragaki's leave of[n]absence extension form.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I try talking to Aragaki again?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I was asked to deliver the school[n]reinstatement form to Aragaki.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He's usually in the back alley near the[n]station. Should I go look for him there?[n][uf 1 1][e]

