[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Huh...? Junpei!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]You took off that fast, and you still haven't gone inside?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Well... I mean, it's kinda...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]We'll wait outside. It wouldn't be good for all of us to charge in...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]I agree. Go on, Iori...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 4 1], you go in too.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 0 0 0 7 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 0 0 0 8 0 0]...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]Her damaged endocrine system and other internal organs have completely healed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]She's still weak, but... there's no more danger of her dying in two years.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Chidori... Is it really you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]I'm not dreaming... am I...?[n][uf 1 1][e]

[msg MSG_009_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 1 0 0 13 0 0]Dreaming...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 15 0 0]It's true... It is you... Chidori...[n][uf 1 1][e]

[msg MSG_011_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 1 0 0 17 0 0]Who... are you?[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Huh...? Wh-What...?[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0]I thought so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Transmogrification is the proof that one lacks "potential"... I had a feeling this might be the case.[n][uf 1 1][e]

[msg MSG_014_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 1]This is Kirijo-san and Iori-kun. They were your friends last year.[n][uf 1 1][e]

[msg MSG_015_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 1 0 0 22 0 0]Friends...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 3 201 65535 0 0][uf 3 1 0 0 0 23 0 0][uf 4 23 0 213 3 25 25]......[n][uf 1 1][e]

[msg MSG_015_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 3 201 65535 0 0][uf 3 1 1 0 0 24 0 0]My name is Chidori Yoshino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 3 201 65535 0 0][uf 3 1 1 0 0 25 0 0]I'm sorry... It hasn't quite hit me yet, but I guess I don't remember anything of the past few years...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 3 201 65535 0 0][uf 3 1 1 0 0 26 0 0]It's like... I was having a really long dream.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 27 0 0]Chidori... Yoshino...[n][uf 1 1][e]

[msg MSG_017_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 1]It seems all of her memories after she awakened to her Persona are gone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 1]She remembers everything that happened before then, but as for you all...[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 2 65535 0 0][uf 3 1 0 0 0 30 0 0]......[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Iori...[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 32 0 0]Nah... I think... it's better for her that she doesn't remember.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 33 0 0]All that stuff about the fighting, and the suppressants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 34 0 0]When you're having a nightmare... it's better to be able to wake up.[n][uf 1 1][e]

[msg MSG_021_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 2 201 65535 0 0][uf 3 1 1 0 0 35 0 0]I didn't say it was a nightmare. Don't put words in my mouth.[n][uf 1 1][e]

[msg MSG_022_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 1 201 65535 0 0][uf 3 1 1 0 0 36 0 0]It was a dream of meeting a kind, warm person at the end of a long tunnel...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 1 201 65535 0 0][uf 3 1 1 0 0 37 0 0]I can't remember it clearly... But I wanted to make him happy, and I...[n][uf 1 1][e]

[msg MSG_022_3_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 3 201 65535 0 0][uf 3 1 1 0 0 38 0 0]I think... there were flowers... A room filled with them...[n][uf 1 1][e]

[msg MSG_022_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 5 201 65535 0 0][uf 3 1 1 0 0 39 0 0]Ngh...[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 40 0 0]Chidori! Take it easy, don't force yourself to remember.[n][uf 1 1][e]

[msg MSG_024_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0][uf 5 21 0 1]Flowers in a room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0][uf 5 21 0 1]If she can remember that part clearly, then maybe...[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 43 0 0]...?[n][uf 1 1][e]

[msg MSG_026_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0][uf 5 21 0 1]Do you remember how she'd occasionally use her power to make flowers bloom again?[n][uf 1 1][e]

[msg MSG_027_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 45 0 0][uf 5 21 0 1]She'd always do it for the flowers in her room on the days when Iori-kun would visit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 46 0 0][uf 5 21 0 1]And she would always spend more time on the flowers she received from you, Iori-kun.[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 47 0 0]She never even looked at me when I brought them in though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 48 0 0][uf 4 23 0 2 1 25 25]Heheh... Now I see.[n][uf 1 1][e]

[msg MSG_029_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 49 0 0]Any flower she touched would be mysteriously preserved...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 50 0 0][uf 5 21 0 1]I ended up keeping them all for my research.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 51 0 0][uf 5 21 0 1]But after the autopsy, I put them all on her chest as a tribute.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 52 0 0][uf 5 21 0 1]Now that I think about it, that must have been the night she began to transmogrify...[n][uf 1 1][e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 53 0 0]The power to share one's life with others...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 54 0 0]Could she have reclaimed the life energy she'd given to those flowers...?[n][uf 1 1][e]

[msg MSG_031_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 55 0 0][uf 5 21 0 1]Well, there's no real proof...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 56 0 0][uf 5 21 0 1]But, compared to her previous state, she's changed. The loss of her power is part of it, but furthermore—[n][uf 1 1][e]

[msg MSG_032_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 2 201 65535 0 0][uf 3 1 1 0 0 57 0 0]Excuse me... Are you talking about me?[n][uf 1 1][e]

[msg MSG_033_0_0 [Chidori's Doctor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 58 0 0][uf 5 21 0 1]We were talking about how you want to live now...[n][uf 1 1][e]

[msg MSG_034_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 0 0 0 59 0 0]...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 1 0 0 60 0 0]What do you mean by that? Of course I want to live.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 1 201 65535 0 0][uf 3 1 1 0 0 61 0 0][uf 4 23 0 213 1 25 25]I have to find the person in my dream someday... I don't have time to lie in bed forever.[n][uf 1 1][e]

[msg MSG_035_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 62 0 0]Supposing you do find him... What will you do after that?[n][uf 1 1][e]

[msg MSG_036_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 1 0 0 63 0 0]Well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 0 201 65535 0 0][uf 3 1 0 0 0 64 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 213 2 201 65535 0 1][uf 3 1 1 0 0 65 0 0][uf 4 23 0 213 2 25 25]That's none of your business.[n][uf 1 1][e]

[msg MSG_037_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 66 0 0]Chidori...[n][uf 1 1][e]

[msg MSG_038_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 67 0 0]The strength of two hearts connected brought about a miracle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 68 0 0]Or rather, a victory.[n][uf 1 1][e]

[msg MSG_039_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 69 0 0]Oh, Chidori...[n][uf 1 1][e]

[msg MSG_040_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 4 5 213 4 201 65535 0 0][uf 3 1 1 0 0 70 0 0]H-Hey... Why are you crying?[n][uf 1 1][e]

[msg MSG_041_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 71 0 0]I-I can't help it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 72 0 0]I... I've...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 73 0 0]I've never been so happy in my entire life![n][uf 1 1][e]

[msg MSG_041_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 61 2 65535 0 0][uf 3 1 1 0 0 74 0 0]Waaahhhhh...![n][uf 1 1][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 75 0 0]Haha, have some self-control now...[n][uf 1 1][e]

[msg MSG_043_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 76 0 0]Let's go, [uf 4 1].[n][uf 1 1][e]

[msg MSG_044_0_0 [（ＳＥ）岳羽 ゆかり]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 77 0 0]…うっ…[n][uf 1 1][e]

[msg MSG_045_0_0 [（ＳＥ）山岸 風花]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 78 0 0]ひぐっ…[n][uf 1 1][e]

[msg MSG_046_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 79 0 0]...?[n][uf 1 1][e]

[msg MSG_047_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 80 0 0]*sniffle*[n][uf 1 1][e]

[msg MSG_048_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 81 0 0]*sniffle*[n][uf 1 1][e]

[msg MSG_049_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 82 0 0]Ha...[n][uf 1 1][e]

