[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]This is... a pleasant surprise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 202 0 25 25]To think there would be a bastion of commerce within a house of academia...[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Could you please wait here for a moment? There's something I've been curious about for a while...[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Excuse me, I would like to purchase a "school lunch."[n][uf 1 1][e]

[msg MSG_003_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1001]Um... Sorry?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]They don't sell that here.[e]
[uf 0 5 65278][uf 2 1]They only sell bread.[e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]They don't deal in school lunches here...? How disappointing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 202 0 25 25]I would have liked a taste of this "school lunch," as it is a rare delicacy only served in select facilities...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Well, in that case, I shall order some bread. I've heard that having bread for lunch is part of the school experience.[n][uf 1 1][e]

[msg MSG_006_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I would have liked a taste of this "school lunch," as it is a rare delicacy only served in select facilities...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 202 0 25 25]But I've heard that having bread for lunch is also part of the school experience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]That will be a fine substitute.[n][uf 1 1][e]

[msg MSG_007_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Now that I've checked that off the list, let us proceed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 202 0 25 25]As for where I'd like to go next... Shall we visit your homeroom?[n][uf 1 1][e]

