[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I apologize for asking you to come on such short notice.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13226 0 0]Oh, how rude of me! I seem to be distracted, despite requesting your presence in the first place.[n][uf 1 1][e]

[msg MSG_003_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Now then, seeing as you have awakened to your new power and begun exploring, I have something of a proposal for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I happen to have a certain matter on my mind, you see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 23 0 1 3 25 25]However, it is a matter for which I have yet to find a solution. It has me feeling rather stumped. Quite perplexed. Positively discombobulated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 23 0 1 0 25 25]Therefore... Should you allow it, I would like to observe those newfound abilities of yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I ask that you fulfill my requests. I believe doing so would prove to be an adequate demonstration of your power.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Naturally, you will be rewarded upon the completion of any such tasks.[n][uf 1 1][e]

[msg MSG_004_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Well, that concludes the detailing of my proposal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13231 0 0][uf 4 23 0 1 1 25 25]I am... very much looking forward to witnessing you utilize the fullest extent of your power.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It seems I can now choose to[n]accept Elizabeth-san's requests.[n][uf 1 1][e]

