[msg Item_000]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_001]
[uf 0 5 65278][uf 2 1]Sturdy work boots. Effective for various uses.[n][e]

[msg Item_002]
[uf 0 5 65278][uf 2 1]Brown loafers with a simple design.[n][e]

[msg Item_003]
[uf 0 5 65278][uf 2 1]Generic boots, each adorned with a horizontal stripe.[n][e]

[msg Item_004]
[uf 0 5 65278][uf 2 1]Athletic shoes with a classic design.[n][e]

[msg Item_005]
[uf 0 5 65278][uf 2 1]Long, black boots that have a glossy sheen.[n][e]

[msg Item_006]
[uf 0 5 65278][uf 2 1]Black loafers with a simple design.[n][e]

[msg Item_007]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Made with pure iron.[n][e]

[msg Item_008]
[uf 0 5 65278][uf 2 1]Comfortable shoes made for indoor soccer.[n][e]

[msg Item_009]
[uf 0 5 65278][uf 2 1]The paw pads are extremely soft.[n][e]

[msg Item_00A]
[uf 0 5 65278][uf 2 1]Sturdy, low-heel boots. A little longer than average boots.[n][e]

[msg Item_00B]
[uf 0 5 65278][uf 2 1]Textured sandals that are easy to walk in.[n][e]

[msg Item_00C]
[uf 0 5 65278][uf 2 1]Casual boots with thick soles.[n][e]

[msg Item_00D]
[uf 0 5 65278][uf 2 1]Retro high geta that somehow feel barbaric.[n][e]

[msg Item_00E]
[uf 0 5 65278][uf 2 1]Leather boots made of sturdy material.[n][e]

[msg Item_00F]
[uf 0 5 65278][uf 2 1]Shoes, each with a single row of wheels that allow for quick movement.[n][e]

[msg Item_010]
[uf 0 5 65278][uf 2 1]Rugged boots used by the military.[n][e]

[msg Item_011]
[uf 0 5 65278][uf 2 1]Mechanized geta made with advanced technology.[n][e]

[msg Item_012]
[uf 0 5 65278][uf 2 1]Extremely fancy leopard-print tights.[n][e]

[msg Item_013]
[uf 0 5 65278][uf 2 1]Tough greaves that are dyed dark red.[n][e]

[msg Item_014]
[uf 0 5 65278][uf 2 1]Sandals with an eccentric design that strengthen magic power.[n][e]

[msg Item_015]
[uf 0 5 65278][uf 2 1]Extremely durable shoes that can even withstand being run over by a tank.[n][e]

[msg Item_016]
[uf 0 5 65278][uf 2 1]Greaves of a warrior dedicated to perfecting their swordplay.[n][e]

[msg Item_017]
[uf 0 5 65278][uf 2 1]Advanced shoes made from harnessing the power of science.[n][e]

[msg Item_018]
[uf 0 5 65278][uf 2 1]Black tabi used by ninjas that increase one's Agility.[n][e]

[msg Item_019]
[uf 0 5 65278][uf 2 1]Grandiose tabi that increase one's Attack and critical rate.[n][e]

[msg Item_01A]
[uf 0 5 65278][uf 2 1]Athletic shoes harboring unsettling power. Evokes rivulets of blood.[n][e]

[msg Item_01B]
[uf 0 5 65278][uf 2 1]Engine-equipped boots that surpass modern technology.[n][e]

[msg Item_01C]
[uf 0 5 65278][uf 2 1]Zori that smell of straw. Allow for nimble movement.[n][e]

[msg Item_01D]
[uf 0 5 65278][uf 2 1]Old-fashioned sandals. Plaintive lamentations dwell within.[n][e]

[msg Item_01E]
[uf 0 5 65278][uf 2 1]Extremely sturdy greaves that are very difficult to break.[n][e]

[msg Item_01F]
[uf 0 5 65278][uf 2 1]Lightweight pumps that are comfortable to wear.[n][e]

[msg Item_020]
[uf 0 5 65278][uf 2 1]Radio-controllable geta. Attack rises when on the receiving end of a Shift.[n][e]

[msg Item_021]
[uf 0 5 65278][uf 2 1]Geta made of wood as black as the pitiless depths.[n][e]

[msg Item_022]
[uf 0 5 65278][uf 2 1]Old-fashioned sandals with lions stylishly drawn on them.[n][e]

[msg Item_023]
[uf 0 5 65278][uf 2 1]Pleasantly airy sandals colored silver.[n][e]

[msg Item_024]
[uf 0 5 65278][uf 2 1]Shoes frequently used by hitmen. Can also be worn for everyday use.[n][e]

[msg Item_025]
[uf 0 5 65278][uf 2 1]Eccentric shoes thought to greatly increase one's attractiveness.[n][e]

[msg Item_026]
[uf 0 5 65278][uf 2 1]Sacred leather shoes with an ornate rose motif.[n][e]

[msg Item_027]
[uf 0 5 65278][uf 2 1]High-performance greaves in which the soul of a war god resides.[n][e]

[msg Item_028]
[uf 0 5 65278][uf 2 1]Lavish boots adorned with elaborate goldwork.[n][e]

[msg Item_029]
[uf 0 5 65278][uf 2 1]Shoes blessed by the power of an ancient king.[n][e]

[msg Item_02A]
[uf 0 5 65278][uf 2 1]Tabi that raise the Agility of all allies at the start of battle.[n][e]

[msg Item_02B]
[uf 0 5 65278][uf 2 1]Mysterious boots that raise Attack when on the receiving end of a Shift.[n][e]

[msg Item_02C]
[uf 0 5 65278][uf 2 1]Mysterious shoes that restore SP when on the receiving end of a Shift.[n][e]

[msg Item_02D]
[uf 0 5 65278][uf 2 1]Ornamented shoes which greatly decrease the hit rate of incoming attacks.[n][e]

[msg Item_02E]
[uf 0 5 65278][uf 2 1]Stimulates pressure points. Can be painful if the wearer is unhealthy.[n][e]

[msg Item_02F]
[uf 0 5 65278][uf 2 1]Heels that don't slip even on ice. Feel a bit cold when worn.[n][e]

[msg Item_030]
[uf 0 5 65278][uf 2 1]Sneakers that provide the courage needed to take the next step.[n][e]

[msg Item_031]
[uf 0 5 65278][uf 2 1]Shoes that enable anyone to become light and nimble.[n][e]

[msg Item_032]
[uf 0 5 65278][uf 2 1]Lightweight sandals that make the wearer feel weightless.[n][e]

[msg Item_033]
[uf 0 5 65278][uf 2 1]Shoes that let the wearer move nimbly in combat. Perfect for Sanada.[n][e]

[msg Item_034]
[uf 0 5 65278][uf 2 1]Women's tights that are resistant to electricity.[n][e]

[msg Item_035]
[uf 0 5 65278][uf 2 1]Special leather boots imbued with the essence of fallen tears.[n][e]

[msg Item_036]
[uf 0 5 65278][uf 2 1]Shoes that are said to have been worn by the ruler of the world.[n][e]

[msg Item_037]
[uf 0 5 65278][uf 2 1]A pair of socks yellowed with age. Radiates mysterious power.[n][e]

[msg Item_038]
[uf 0 5 65278][uf 2 1]Shoes that enable survival of a single Dark instakill attack with 1 HP.[n][e]

[msg Item_039]
[uf 0 5 65278][uf 2 1]Light and sturdy protector that guards the legs.[n][e]

[msg Item_03A]
[uf 0 5 65278][uf 2 1]Heels that imbue the wearer with a sudden passion for dancing.[n][e]

[msg Item_03B]
[uf 0 5 65278][uf 2 1]Leg armor resembling a tortoise shell. Low chance to Repel physical attacks.[n][e]

[msg Item_03C]
[uf 0 5 65278][uf 2 1]Futuristic shoes that bring out one's inner child.[n][e]

[msg Item_03D]
[uf 0 5 65278][uf 2 1]Shoes with a devil icon. SP is restored when on the receiving end of a Shift.[n][e]

[msg Item_03E]
[uf 0 5 65278][uf 2 1]Lightweight boots that restore SP to the ally being Shifted to.[n][e]

[msg Item_03F]
[uf 0 5 65278][uf 2 1]Geta with unknown origin. The wearer's abilities are heightened.[n][e]

[msg Item_040]
[uf 0 5 65278][uf 2 1]Heels once worn by a former angel.[n][e]

[msg Item_041]
[uf 0 5 65278][uf 2 1]Shoes that increase Agility to the point that afterimages are produced.[n][e]

[msg Item_042]
[uf 0 5 65278][uf 2 1]Shoes furnished with a perfect beauty that emits divinity.[n][e]

[msg Item_043]
[uf 0 5 65278][uf 2 1]Sandals popular among young boys. Great for Amada.[n][e]

[msg Item_044]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_045]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_046]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_047]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_048]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Made of carbon materials.[n][e]

[msg Item_049]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Easy to use in everyday life.[n][e]

[msg Item_04A]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Excels in durability and heat resistance.[n][e]

[msg Item_04B]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Contains the essence of fallen tears.[n][e]

[msg Item_04C]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Resistant to corrosion.[n][e]

[msg Item_04D]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_04E]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Strong and lightweight.[n][e]

[msg Item_04F]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Plaintive lamentations dwell within.[n][e]

[msg Item_050]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Highly resistant to abrasion.[n][e]

[msg Item_051]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_052]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Designed in the image of a beast god.[n][e]

[msg Item_053]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Experimental model used on a trial basis.[n][e]

[msg Item_054]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Manufactured with special techniques.[n][e]

[msg Item_055]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_056]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Slightly restores HP during battle.[n][e]

[msg Item_057]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Equipped with an exhaust heat recovery system.[n][e]

[msg Item_058]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Radiates angelic divinity.[n][e]

[msg Item_059]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. All performance capabilities enhanced.[n][e]

[msg Item_05A]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Aigis with an ornate rose motif.[n][e]

[msg Item_05B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_05C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_05D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_05E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_05F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_060]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_061]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_062]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_063]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_064]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_065]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_066]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_067]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_068]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_069]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06E]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Molded with tree resin.[n][e]

[msg Item_06F]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Shaped by firing in a kiln.[n][e]

[msg Item_070]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Forged from light alloys.[n][e]

[msg Item_071]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Forged from titanium.[n][e]

[msg Item_072]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Contains the essence of fallen tears.[n][e]

[msg Item_073]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Suited for dancing.[n][e]

[msg Item_074]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Contains a hidden art.[n][e]

[msg Item_075]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Colored a deep blood-red.[n][e]

[msg Item_076]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Has a mystical, glittering aura.[n][e]

[msg Item_077]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Bears a regal motif.[n][e]

[msg Item_078]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_079]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Plaintive lamentations dwell within.[n][e]

[msg Item_07A]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Absorbs all light that makes contact.[n][e]

[msg Item_07B]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_07C]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Bears the insignia of a god who can deflect lightning.[n][e]

[msg Item_07D]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis optimized for efficiency. Recovers HP during battle.[n][e]

[msg Item_07E]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Equipped with an exhaust heat recovery system.[n][e]

[msg Item_07F]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Once worn by a hero to prevent all magic attacks.[n][e]

[msg Item_080]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_081]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Metis with an ornate rose motif.[n][e]

[msg Item_082]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_083]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_084]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_085]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_086]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_087]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_088]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_089]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08C]
[uf 0 5 65278][uf 2 1]Special leather boots imbued with the essence of fallen tears.[n][e]

[msg Item_08D]
[uf 0 5 65278][uf 2 1]Special leather boots imbued with the essence of fallen tears.[n][e]

[msg Item_08E]
[uf 0 5 65278][uf 2 1]Athletic shoes harboring unsettling power. Evokes rivulets of blood.[n][e]

[msg Item_08F]
[uf 0 5 65278][uf 2 1]Athletic shoes harboring unsettling power. Evokes rivulets of blood.[n][e]

[msg Item_090]
[uf 0 5 65278][uf 2 1]Old-fashioned sandals. Plaintive lamentations dwell within.[n][e]

[msg Item_091]
[uf 0 5 65278][uf 2 1]Old-fashioned sandals. Plaintive lamentations dwell within.[n][e]

[msg Item_092]
[uf 0 5 65278][uf 2 1]Old-fashioned sandals. Plaintive lamentations dwell within.[n][e]

[msg Item_093]
[uf 0 5 65278][uf 2 1]Geta made of wood as black as the pitiless depths.[n][e]

[msg Item_094]
[uf 0 5 65278][uf 2 1]Geta made of wood as black as the pitiless depths.[n][e]

[msg Item_095]
[uf 0 5 65278][uf 2 1]Geta made of wood as black as the pitiless depths.[n][e]

[msg Item_096]
[uf 0 5 65278][uf 2 1]A pair of socks yellowed with age. Radiates mysterious power.[n][e]

[msg Item_097]
[uf 0 5 65278][uf 2 1]A pair of socks yellowed with age. Radiates mysterious power.[n][e]

[msg Item_098]
[uf 0 5 65278][uf 2 1]A pair of socks yellowed with age. Radiates mysterious power.[n][e]

[msg Item_099]
[uf 0 5 65278][uf 2 1]Sacred leather shoes with an ornate rose motif.[n][e]

[msg Item_09A]
[uf 0 5 65278][uf 2 1]Sacred leather shoes with an ornate rose motif.[n][e]

[msg Item_09B]
[uf 0 5 65278][uf 2 1]Sacred leather shoes with an ornate rose motif.[n][e]

[msg Item_09C]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Contains the essence of fallen tears.[n][e]

[msg Item_09D]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Contains the essence of fallen tears.[n][e]

[msg Item_09E]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_09F]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_0A0]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Plaintive lamentations dwell within.[n][e]

[msg Item_0A1]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Plaintive lamentations dwell within.[n][e]

[msg Item_0A2]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Plaintive lamentations dwell within.[n][e]

[msg Item_0A3]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0A4]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0A5]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0A6]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0A7]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0A8]
[uf 0 5 65278][uf 2 1]Leg equipment for Aigis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0A9]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Aigis with an ornate rose motif.[n][e]

[msg Item_0AA]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Aigis with an ornate rose motif.[n][e]

[msg Item_0AB]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Aigis with an ornate rose motif.[n][e]

[msg Item_0AC]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Contains the essence of fallen tears.[n][e]

[msg Item_0AD]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Contains the essence of fallen tears.[n][e]

[msg Item_0AE]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_0AF]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Harbors unsettling power, evoking rivulets of blood.[n][e]

[msg Item_0B0]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Plaintive lamentations dwell within.[n][e]

[msg Item_0B1]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Plaintive lamentations dwell within.[n][e]

[msg Item_0B2]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Plaintive lamentations dwell within.[n][e]

[msg Item_0B3]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0B4]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0B5]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis. Its matte finish is as black as the pitiless depths.[n][e]

[msg Item_0B6]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0B7]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0B8]
[uf 0 5 65278][uf 2 1]Leg equipment for Metis, yellowed with age. Emits a mysterious power.[n][e]

[msg Item_0B9]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Metis with an ornate rose motif.[n][e]

[msg Item_0BA]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Metis with an ornate rose motif.[n][e]

[msg Item_0BB]
[uf 0 5 65278][uf 2 1]Sacred leg equipment for Metis with an ornate rose motif.[n][e]

[msg Item_0BC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0ED]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

