[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30101 0 0]I comprehend...[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]My nerves are killing me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]All I did was mention the [uf 4 4 0 37 1 16788]. Why is this happening to me...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30094 0 0]So that's how you assemble a beverage... How very intriguing.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]I-It's nothing really. Um...[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7001 0 0]How's the taste?[n][uf 1 1][e]

[msg MSG_005_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]The taste?[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]The... taste?[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]You don't need to think that hard about it...[n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30096 0 0]Er, I-I'll give it another shot. Maybe I'll figure it out with another cup![n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I drank every last drop, but...[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Aigis-san hasn't touched hers yet. Would you like to try that one, too?[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30095 0 0]What!? Can I really...?[n][uf 1 1][e]

[sel SEL_063_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]You're overreacting.[e]
[uf 0 5 65278][uf 2 1]Remember to savor the taste.[e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30080 0 0]I-In that case, don't mind if I do![n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30044 0 0]I'm not! This is a really, really big deal to me![n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30090 0 0]Yes, of course! Since it was your cup to begin with, Sister, I'll be sure to savor it a hundredfold![n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 33 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Um... How does it taste this time?[n][uf 1 1][e]

[msg MSG_017_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30056 0 0]Much better than the first one.[n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]How? They were both brewed with the same coffee beans. There can't be that big of a difference...[n][uf 1 1][e]

[msg MSG_019_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]You can technically assign quantifiable values for comparison, but it's difficult to present the outputted data clearly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 11 52 65535 0 0][uf 3 1 3 0 65535 30106 0 0][uf 4 23 0 1 11 25 25]It's also unnecessary when the fact is... receiving this cup from my sister is what makes it better![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Metis seems pleased[n]with her new discovery...[n][uf 1 1][e]

[msg MSG_021_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7120 0 0]I just wanted to hear your impressions on the flavor profile...[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]It had a pleasant aroma.[e]
[uf 0 5 65278][uf 2 1]I apologize...[e]
[uf 0 5 65278][uf 2 1]Please don't be too upset.[e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7041 0 0]Haha... Thank you.[n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7037 0 0]Oh, you don't have anything to be sorry about, Aigis-san...[n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7112 0 0]I'm not, though... Not really...[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Why's it so hard to brew a good cup...?[n][uf 1 1][e]

[msg MSG_027_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30073 0 0]Oh, um... The coffee was, uh... really tasty?[n][uf 1 1][e]

