[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh man, I'm gettin' kinda hungry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 3 1 25 25]This mall rocks! So many places to chow down. Plus, they're open late![n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Speakin' of, I heard the ramen joint upstairs has a secret late-night menu...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]We'd better hurry to the dorm.[e]
[uf 0 5 65278][uf 2 1]Maybe next time.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Y-Yeah, yeah, I know...[n][uf 1 1][e]

