[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Daaamn... These fights got me on the edge of my seat![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 4 23 0 1 0 25 25]Don't see much I could use in an actual battle, though.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]Also, why the heck would you guard and run from the opponent here? Makes zero sense.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2146 0 0]Yo, perfect timing, Sanada-san! Mind if I pick your brain a bit?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]I see... So you're wondering why this guy didn't just follow up with another attack instead?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]I mean, look! His opponent's pretty much cornered, right? Don't get why you'd just back off after that.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3094 0 0]Well, I don't think it's a bad tactic at all. Seems obvious enough to me that he's getting baited.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]He's letting himself get hit on purpose—[n]probably because he's setting up a trap.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]What would you do here, Aigis? Would you still charge ahead, fists flying, when you know it's a trap?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]I would analyze the situation.[e]
[uf 0 5 65278][uf 2 1]I would overpower the target.[e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3108 0 0]Heh. Guess we're on the same page, then.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Seriously, you guys? C'mon, the answer's obvious: Go in guns blazing![n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3106 0 0]Oh yeah? I'd believe that.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Right? I'm with Ai-chan on this, man.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2095 0 0]After all, the best defense is a good offense. You just gotta turn the tables and all that jazz![n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 52 65535 0 0]Junpei, you're gonna get yourself killed one of these days with that thinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 52 65535 0 0]What if you meet your match one day? You've gotta be realistic.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2037 0 0]Well, yeah, but... I-It's just...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Goin' in for a one-hit KO is one heck of a power move![n][uf 1 1][e]

[msg MSG_014_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Don't you agree, Ai-chan?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]I think I do...[e]
[uf 0 5 65278][uf 2 1]I don't quite follow...[e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2026 0 0]Hell yeah! You get me![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2100 0 0]Really!? Personally, I think an ultimate attack is the one thing every good hero needs in their arsenal.[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Well... If that's how you really feel, then you better work hard and see it through.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Not like there's only one way to get stronger. You're just walking a different path from some of us, is all.[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2136 0 0]Sanada-san...[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Junpei-san appears to have[n]overcome an internal struggle...[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3020 0 0]Anyway... Show me where your path to strength takes you, Junpei, in our next battle.[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2061 0 0]Uhhh... I just wanted to talk about killer moves and ultimate attacks, though?[n][uf 1 1][e]

