[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]10/12/2009 14:56:22[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like Yukari's room...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 1 0 0 1 0 0]Like this, I guess...?[n][uf 1 1][e]

[msg MSG_002_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 2 0 0]"Welcome! I'll be taking care of you today!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 3 0 0]"Are you ready to order, or do you need a little more time?"[n][uf 1 1][e]

[msg MSG_002_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 1 0 0 4 0 0]Hmm, it's too bad the school festival got canceled...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 1 0 0 5 0 0]I already went to all the trouble of putting this on, so maybe I should wear it around the dorm for the day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 0 0 0 6 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 7 0 0]"'Sup, Yuka-tan? Hey, does that mean you gotta call me Master?"[n][uf 1 1][e]

[msg MSG_003_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 106 11 0 0][uf 3 1 1 0 0 8 0 0]"What's going on, Takeba? You planning to work at Mitsuru's mansion or something?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 106 11 0 0][uf 3 1 0 0 0 9 0 0]......[n][uf 1 1][e]

[msg MSG_003_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 106 11 0 0][uf 3 1 1 0 0 10 0 0]Ugh... Forget it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]I've been meaning to return this, but now that I look at it, it's a real uniform, huh? It's not just a costume.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 106 11 0 0][uf 3 1 1 0 0 12 0 0]Oh, I should take a picture before I give this back to Senpai.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Yukari-chan, are you there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]I need your help with something...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 15 0 0]Sure, one sec![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 16 0 0]I know! I'll drag Fuuka down with me! At least then I won't be alone in the embarrassment...[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 11 0 0][uf 3 1 1 0 0 17 0 0]Yukari-chan... Those clothes—![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 18 0 0]I've got a couple spares, if you wanna try one on. How about it?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 11 0 0][uf 3 1 1 0 0 19 0 0]Huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 11 0 0][uf 3 1 1 0 0 20 0 0]Um, wait...![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 21 0 0]Don't worry! Just hold still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 106 11 0 0][uf 3 1 1 0 0 22 0 0]It's a little tricky to put on, so it'll be faster if I help.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 11 0 0][uf 3 1 1 0 0 23 0 0]Um, wait— Yukari-chan! Eep![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

