[msg MSG_000_0_0 [Class Representative]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]The time to part has finally come.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Though this is our last day together, we want the third-year class to know that we're truly proud of you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]We wish each of you good health, happiness, and success.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]On this momentous occasion, I bid you all a fond farewell on behalf of the student body.[n][uf 1 1][e]

[msg MSG_001_0_0 [Teacher]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Next, a word from the valedictorian...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]From Class D, Mitsuru Kirijo-san.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Thank you.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]This past year, I accepted an important responsibility as student council president.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]When I first addressed you from this podium...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0]I spoke to you all about seizing opportunity while you had the chance...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]It must have been fate that intervened and gave me an important reminder of this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]As many of you know, my father unexpectedly...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]He unexpectedly passed away, due to sudden illness...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Sudden illness...?[n][uf 1 1][e]

[msg MSG_006_0_0 [Graduating Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]Wow, that's rare. I've never heard her stumble in a speech before.[n][uf 1 1][e]

[msg MSG_007_0_0 [Graduating Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]It's a big day... It must be tough to talk about her father.[n][uf 1 1][e]

