[msg TRL_000_0_0 [Spending Time with Your Peers in the Dorm]]
[uf 0 5 65278][uf 2 1][uf 4 8 280]At night, you'll have some time to spend with your party members. Doing so might lead to some interesting revelations.[n][uf 1 1][e]

[msg TRL_001_0_0 [Spending Time with Your Peers in the Dorm]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Sometimes, [uf 0 1 2]these discoveries can be helpful in battle[uf 0 1 27], so don't be shy about approaching your teammates.[n][uf 1 1][e]

