[msg TRL_000_0_0 [Elizabeth's Requests]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can now speak to Elizabeth about accepting and reporting requests.[n][uf 1 1][e]

[msg TRL_001_0_0 [Elizabeth's Requests]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Requests can involve anything from hunting for items to fusing specific Personas. When you complete a request, you will be rewarded.[n][uf 1 1][e]

[msg TRL_002_0_0 [Elizabeth's Requests]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You might see an influx of requests during specific times of the year. Additionally, there are requests that only become available after completing certain previous requests.[n][uf 1 1][e]

[msg TRL_003_0_0 [Elizabeth's Requests]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Some requests have deadlines. If you miss the deadline, the request will [uf 0 1 2]expire[uf 0 1 27], and you will no longer be able to complete it.[n][uf 1 1][e]

