[msg TRL_000_0_0 [Fortune Telling]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Speak to the fortune-teller at Club Escapade to learn your future. A positive reading will affect the next journey you make into Tartarus.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fortune Telling]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The results of a fortune [uf 0 1 2]will only last for the day you receive the fortune[uf 0 1 27]. You have a limited number of readings available to you in a given month which resets each full moon.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fortune Telling]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The fortune-teller will not be able to predict your future on nights when the moon is full, so you will have to plan your visits around the phase of the moon.[n][uf 1 1][e]

