[msg TRL_000_0_0 [Using the Stores in Town]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can partake in the services offered by various establishments in town, but doing so will cause time to pass.[n][uf 1 1][e]

[msg TRL_001_0_0 [Using the Stores in Town]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Many businesses will raise your [uf 4 30 0 1 1 0], [uf 4 30 1 1 1 0], or [uf 4 30 2 1 1 0]. High stats may help you form new relationships.[n][uf 1 1][e]

