[msg TRL_000_0_0 [Using the Shared Computer]]
[uf 0 5 65278][uf 2 1][uf 4 8 260]You can use the shared computer in the first floor lounge for research, or to run purchased software.[n][uf 1 1][e]

[msg TRL_001_0_0 [Using the Shared Computer]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]All software is single-use only, and can be purchased from MangaStar Net Café. Like many activities, using the computer will take up a portion of your day.[n][uf 1 1][e]

