[msg TRL_000_0_0 [Mayoido Antiques]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can now travel to Mayoido Antiques to conduct an Item Fusion or Item Exchange.[n][uf 1 1][e]

[msg TRL_001_0_0 [Mayoido Antiques]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Item Fusions involve expending one weapon part and a handful of required materials to create a unique piece of equipment.[n][uf 1 1][e]

[msg TRL_002_0_0 [Mayoido Antiques]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]In the Item Exchange, the proprietor will take any gemstones off your hands in exchange for items.[n][uf 1 1][e]

[msg TRL_003_0_0 [Mayoido Antiques]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Materials that are used in Item Fusions can often be found in Tartarus, so you'll be able to collect them as you explore.[n][uf 1 1][e]

