[msg TRL_000_0_0 [Tending to the Vegetable Garden with Friends]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]While you can garden alone, raising vegetables with the help of your friends [uf 0 1 2]will result in a more plentiful harvest[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Tending to the Vegetable Garden with Friends]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Veggies raised with help from others will take on different effects [uf 0 1 2]depending on who you were gardening with[uf 0 1 27].[n][uf 1 1][e]

