[msg TRL_000_0_0 [Drawing Fortunes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Imagine someone you are tied to via Social Link, and your relationship will deepen. If your bond has been damaged, it may be repaired. Time will pass as you read your fortune.[n][uf 1 1][e]

[msg TRL_001_0_0 [Drawing Fortunes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Depending on your luck, your fortune may have an effect on your wallet, for better or for worse.[n][uf 1 1][e]

