[msg TRL_000_0_0 [Growing Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The more time you [uf 0 1 2]spend with each of your Social Links[uf 0 1 27], the deeper your relationships will grow.[n][uf 1 1][e]

[msg TRL_001_0_0 [Growing Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The level of intimacy you have with each person will unlock certain benefits. Depending on the rank, you will receive bonus experience when you fuse Personas.[n][uf 1 1][e]

[msg MSG_002_0_0 [Growing Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Deepening your relationships with your current Social Links [uf 0 1 2]may lead to the discovery of new ones[uf 0 1 27]. Try to form as many as you can.[n][uf 1 1][e]

