[msg TRL_000_0_0 [Wakatsu Kitchen]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]At Wakatsu Kitchen, you can order the Prodigy Platter—rich in omega-3s—to help you raise your [uf 4 30 0 1 1 0]. Time will pass if you eat here.[n][uf 1 1][e]

[msg TRL_001_0_0 [Wakatsu Kitchen]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you come by on certain nights, there may be new items on the menu that aren't normally available.[n][uf 1 1][e]

