[msg TRL_000_0_0 [Game Parade Arcade]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Depending on what game you play at Game Parade, you can increase [uf 4 30 0 1 1 0], [uf 4 30 1 1 1 0], [uf 4 30 2 1 1 0], or a stat of your equipped Persona.[n][uf 1 1][e]

[msg TRL_001_0_0 [Game Parade Arcade]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The arcade cycles through which games are available each day of the week. Time will pass regardless of what game you play.[n][uf 1 1][e]

