[msg TRL_000_0_0 [Using the Rooftop Vegetable Garden]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]At the rooftop garden, you can raise crops of vegetables. Each one will take a different amount of time to grow.[n][uf 1 1][e]

[msg TRL_001_0_0 [Using the Rooftop Vegetable Garden]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You or your teammates can eat the vegetables you harvest to gain benefits that will be helpful when journeying into Tartarus.[n][uf 1 1][e]

