[msg TRL_000_0_0 [Hagakure Ramen]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Eating at Hagakure will allow the ramen's collagen to improve the quality of your skin, raising your [uf 4 30 1 1 1 0]. Time will pass if you eat here.[n][uf 1 1][e]

[msg TRL_001_0_0 [Hagakure Ramen]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you come by on certain nights, there may be new items on the menu that aren't normally available.[n][uf 1 1][e]

