[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, there you are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I'm feelin' down today, kid. You mind listenin' to what this old monk has to say?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Those folks downstairs, they're probably around your age, eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]It looks like they're havin' fun drinkin' and dancin', but... you look closely, their eyes say otherwise.[n][uf 1 1][e]

[msg MSG_001_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I bet they come here to relieve stress from the day. But, I wonder if any of 'em are actually enjoying themselves...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Stress won't go away unless you deal with the root of the issue... You can put it off, but it'll always come back.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]This place is more of a refuge than a club to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]If those kids really wanna relax, we should switch the music to the Heart Sutra, and...[n][uf 1 1][e]

[msg MSG_002_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]...Hey! There's a microphone over there. Bring it over, kid! I'll perform a live sutra reading.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Really?[e]
[uf 0 5 65278][uf 2 1]You probably shouldn't...[e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]...Is that supposed to be "really" in a good way? Or "really" in a don't-do-it way?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Don't just talk to talk, kid; say what you mean and get straight to the point.[n][uf 1 1][e]

[msg MSG_005_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]...Eh, forget it! I don't feel like doing it anymore. It's too late to apologize, kid.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 17 15 114]...Don't underestimate me, kid. My reading of the Heart Sutra will change your life![n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]...But, I guess you're right. This place is too small to recite it properly.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I've got a kid around their age, y'know... My one and only son.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]He'll be 21 this year... Just a little older than you... if he's alive, that is.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I felt an almost fatherly[n]concern from Mutatsu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Perhaps because he was projecting[n]his feelings for his son...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]You think it's okay to leave the future of this country in the hands of these kids?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]...I mean, what if they all end up like me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Well, it ain't like I've got high hopes for the future... Form is emptiness, emptiness is form.[n][uf 1 1][e]

[msg MSG_010_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...Oh, sorry. I'm done talkin' now.[n][uf 1 1][e]

[msg MSG_010_7_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Go home before it gets too late, alright? I'll see ya next time.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I said goodbye to Mutatsu[n]and went back to the dorm.[n][uf 1 1][e]

