[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]*whine*[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems sad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Is he thinking about that dog,[n]or the people who were harmed?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We're the only ones who[n]can change this situation...[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Let's defeat the Shadows.[e]
[uf 0 5 65278][uf 2 1]Let's do everything we can.[e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...Woof.[n][uf 1 1][e]

[msg MSG_004_3_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Arf arf![n][uf 1 1][e]

[msg MSG_004_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Awooooo![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I can feel a strong sense of[n]determination from Koromaru...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Dedicating myself to the cause along with[n]Koromaru gave me more [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Koromaru and I went back[n]to the dorm together...[n][uf 1 1][e]

