[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Junpei seems like he's having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I read some manga with Junpei.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Daaang, that story really went places! Now this is a shonen manga![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]The young hero's dedication[n]filled me with [uf 4 30 2 1 1 0]![n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Well, it's gettin' late. We better get to bed.[n][uf 1 1][e]

