[msg MSG_000_0_0 [Bewildered Policeman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 524]We received a call from this area. Is everything okay?[n][uf 1 1][e]

[msg MSG_001_0_0 [Man with Vacant Eyes]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 525]Ahhh... Ugh...[n][uf 1 1][e]

[msg MSG_002_0_0 [Bewildered Policeman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 524]Not this again... It's the same as that weird syndrome being reported all over the news.[n][uf 1 1][e]

