[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 0 0][uf 3 1 1 0 0 1 0 0]Wooow! This place looks so different from how it usually does![n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's beautiful.[e]
[uf 0 5 65278][uf 2 1]So, what's next?[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 0 0][uf 3 1 1 0 0 2 0 0]Yeah! Good job, Paulownia Mall! This is so exciting, let's go![n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 3 0 0]Well, it's not every day we get a chance to see something like this, so I wanna take it all in.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 0 0 0 4 0 0]Wow...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 1 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 106 1 25 25]It's kinda cold. Maybe we should stick close together...[n][uf 1 1][e]

[msg MSG_004_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 40 0 0][uf 3 1 1 0 0 6 0 0]Oh, look! That looks pretty too![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yuko and I walked around and looked[n]at the Christmas decorations.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 0 0][uf 3 1 1 0 0 7 0 0]That was so nice. There were couples around everywhere, huh?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 8 0 0]Oh yeah, before I forget...[n][uf 1 1][e]

[msg MSG_007_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 40 0 0][uf 3 1 1 0 0 9 0 0]This is a little embarrassing, but...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I received the item (ITEM NAME).[n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 10 0 0]It's supposed to work really well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 11 0 0]My grandma taught me how to make it a long time ago. The weather's a lot colder now, so be sure to take care of yourself.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 12 0 0]Christmastime is pretty magical, don't you think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 13 0 0]Honestly, I didn't think much of it up until last year. It was just another yearly event to me.[n][uf 1 1][e]

[msg MSG_010_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 14 0 0]We'd have Christmas cake and chicken as a family, and then we'd exchange presents.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 106 1 25 25]When I'd wake up and find the presents next to my pillow, I'd always shout, "Santa really came!"[n][uf 1 1][e]

[msg MSG_010_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 1 0 0 16 0 0]It was fun back then, sure, but this year, it's fun in a different way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 0 0][uf 3 1 0 0 0 17 0 0]......[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 40 1 0][uf 3 1 1 0 0 18 0 0]...Is it just me, or did it get hot all of a sudden? I wouldn't wanna sweat and catch a cold...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 40 1 0][uf 3 1 0 0 0 19 0 0][uf 4 23 0 106 0 25 25]......[n][uf 1 1][e]

[msg MSG_011_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 40 1 0][uf 3 1 1 0 0 20 0 0]Could I move closer to you... so I don't get too cold?[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]I shared a tender moment with Yuko...[n][uf 1 1][e]

