[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 1 0 0]Awoo... Awooooo...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I'm getting the hang of brushing[n]Koromaru. He's loving it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]His coat is looking even shinier![n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 2 0 0]Hwoooo...[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Hehe, Koro-chan looks so comfy. You sure know your way around a brush, [uf 4 1]-kun.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh, you might know something about this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Lots of people like to give Koro-chan gifts whenever he goes for a walk.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Do you know where he's keeping them?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]I've never seen them.[e]
[uf 0 5 65278][uf 2 1]Somewhere in the dorm.[e]
[uf 0 5 65278][uf 2 1]That's a secret.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh, hm. Then he must've hidden them really well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I wanted to make sure there wasn't any raw food that could go bad.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I see. So you're not sure exactly where they are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I wanted to make sure there wasn't any raw food that could go bad.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, well, I guess even Koromaru needs his own privacy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Do you think we should give him his own room?[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 0 13 0 0]*pant* Ruff?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Ah, right, you're still in the middle of brushing him. I'll leave you to it, then.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I brushed him with all my heart...[n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 15 0 0]Arf![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Koromaru's fur is unbelievably shiny![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He looks more fearless[n]than ever! What a dog![n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 16 0 0]Awooooooo![n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Looking sharp![e]
[uf 0 5 65278][uf 2 1]What a stud![e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 17 0 0]Raaarrr![n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 18 0 0]Arf![n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]To say thanks for the brushing,[n]Koromaru brought [uf 4 4 1 37 0 0].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder if this is what[n]Fuuka was talking about...[n][uf 1 1][e]

[msg MSG_019_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 19 0 0]Arf! Arf![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I played with an overly-excited[n]Koromaru before heading to my room.[n][uf 1 1][e]

