[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Phew... Running away is easy enough. It's losing them that's the hard part.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 4 1 25 25]Still, made for a good workout, right?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]That was some quick thinking, by the way. Just what I'd expect from our leader.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Not a problem.[e]
[uf 0 5 65278][uf 2 1]That was close.[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I don't exactly like turning my back to an opponent, but it doesn't matter in the end if I can't protect the ones beside me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]And being outnumbered increases our risk of injury or damaging our surroundings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 4 1 25 25]What I mean is you made the right call. I owe you one.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 0 0 0 7 0 0]Hm...?[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]It's addressed to me... Says it contains "fruits, snacks, and beverages."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Looks like it's from my parents. I'll take it to my room later.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Your parents?[e]
[uf 0 5 65278][uf 2 1]There sure is a lot.[e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Yeah. My foster parents that adopted me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]I haven't kept in touch lately since I'm so busy, but it sounds like they're doing well.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Yeah, it's probably because they think I'm a growing boy and all that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I haven't kept in touch lately since I'm so busy, but I should probably write back and thank them.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I appreciate how much they care, but this is a little too generous. Wanna take some of it off my hands?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 4 3 25 25]Then again, you'll hardly make a dent in this either...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Let's call the others.[e]
[uf 0 5 65278][uf 2 1]You can share with everyone.[e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Good idea. Would you mind gathering everyone up?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Oh my![n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]Ooh![n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]Oh?[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]Wow...[n][uf 1 1][e]

[msg MSG_015_4_0 [(SE) Ken Amada]]
[uf 0 5 65278][uf 2 1]Oh, wow![n][uf 1 1][e]

[msg MSG_015_6_0 [Aigis (SE)]]
[uf 0 5 65278][uf 2 1]Intriguing.[n][uf 1 1][e]

[msg MSG_015_8_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1]*pant* *pant*[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Everything is such high quality. I can tell just by looking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 6 0 25 25]Your parents must really care about you.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]At least you know how to behave in front of your parents, Akihiko.[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]...Don't you ever have anything nice to say about me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 4 0 25 25]My parents have been good to me. I obviously haven't told them about what we do here, though.[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Wow, when it comes to bein' considerate of others, you're a heavyweight! Glad to have you in our corner, Senpai![n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]There he goes again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 2 1 25 25]These sure look good, though. Thanks for sharing, Sanada-senpai.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]Take whatever you want.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Hey, this looks really good.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]Oh, goin' for that one huh, Yuka-tan?[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0]Hey, Kirijo-senpai, what's that?[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]Oh, this looks like it was meant for royalty...[n][uf 1 1][e]

[msg MSG_025_4_0 [(SE) Ken Amada]]
[uf 0 5 65278][uf 2 1]Oh, I see![n][uf 1 1][e]

[msg MSG_025_6_0 [Aigis (SE)]]
[uf 0 5 65278][uf 2 1]Much appreciated.[n][uf 1 1][e]

[msg MSG_025_8_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1]Arf, arf![n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]That took care of most of it. I'm surprised they were so happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 35 0 0][uf 4 23 0 4 0 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]I've really gotta show my gratitude. To my parents, and to everyone here.[n][uf 1 1][e]

[msg MSG_027_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]All this talk about my parents reminded me of some things from the past, like why I'm here right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I guess I feel like I remember my reason for fighting.[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]I don't really get it.[e]
[uf 0 5 65278][uf 2 1]Glad to hear it.[e]

[msg MSG_029_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Well, don't mind me. Let's just say I've got a lot of room to grow.[n][uf 1 1][e]

[msg MSG_030_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]The dorm's gotten so much busier. The orphanage used to be something like this, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]We all lived under the same roof, just having casual conversations. I'd forgotten what it was like, but it wasn't so bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 4 0 25 25]I remembered after you suggested we share with everyone.[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]You're exaggerating.[e]
[uf 0 5 65278][uf 2 1]Let's do it again sometime.[e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]You think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 4 0 25 25]People are always telling me I need to be more aware of things like that, though.[n][uf 1 1][e]

[msg MSG_033_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Tell that to my parents.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 4 0 25 25]I've really gotta repay you in particular though, or we'll never be squared away.[n][uf 1 1][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]All right, it's pretty late now. I guess we should clean up and call it a night.[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There's something mixed in here. It's a letter,[n]and some sort of hand-crafted object...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like a gold medal[n]that's made of cardboard.[n][uf 1 1][e]

[msg MSG_036_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]What? Is there something there?[n][uf 1 1][e]

[msg MSG_037_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]This is...[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Is it also a gift?[e]
[uf 0 5 65278][uf 2 1]Is it yours?[e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]No, this is mine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 4 23 0 4 0 25 25]You won't understand what it means, but it's from a long time ago.[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 0 0 0 53 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0][uf 4 23 0 4 0 25 25]This medal doesn't really belong to anyone. It's from a long time ago.[n][uf 1 1][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Do you mind if I ask you something?[n][uf 1 1][e]

[msg MSG_042_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]You take on the role of our leader, and you're stronger than anyone else in your own right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]That's more than just being talented. Where do you get that strength from?[n][uf 1 1][e]

[sel SEL_043_0_0 top]
[uf 0 5 65278][uf 2 1]I train.[e]
[uf 0 5 65278][uf 2 1]It's thanks to the bonds I have.[e]
[uf 0 5 65278][uf 2 1]I don't do anything.[e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]So you mean you're putting in work behind the scenes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]I thought I put a lot of time into training myself, but now I'm not so sure.[n][uf 1 1][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]Oh, I see. You mean you feel motivated because you have people in your corner?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]...Bonds with others, huh. That might be something I'm missing.[n][uf 1 1][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]Heh, so you don't even know what your own secret is? You're on a completely different level.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0][uf 4 23 0 4 0 25 25]But you know, I think that's just how it is for the ones who have true strength.[n][uf 1 1][e]

[msg MSG_047_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]Well, whatever it is, you've clearly got something that I don't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]But being jealous or trying to copy you isn't gonna help me. That strength is yours alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]I'm going to get stronger... But I'll do it my way.[n][uf 1 1][e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]Sorry, we were supposed to be cleaning up. I'll take care of the rest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]Things got so busy that I missed out on my chance to thank you again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]Hopefully the food was enough for today. I'll invite you out again some other time.[n][uf 1 1][e]

[msg MND_049_0_0]
[uf 0 5 65278][uf 2 1]I took Sanada's gesture of appreciation,[n]then returned to my room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]improved after seeing how[n]Sanada cares for his parents...[n][uf 1 1][e]

