[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I've been waiting for a while,[n]but Hayase still isn't here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Let's see...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I'll look around for him.[e]
[uf 0 5 65278][uf 2 1]I'll wait a bit longer.[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]He's not in any of the nearby shops...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Hayase still isn't here...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hmm...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Guess I'll kill some time.[e]
[uf 0 5 65278][uf 2 1]Guess I'll keep waiting.[e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hayase still isn't here...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hayase still isn't here...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Well...[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]I'll wait just a bit longer.[e]
[uf 0 5 65278][uf 2 1]I'm just gonna go home.[e]

[msg MSG_012_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 1 0 0]Hello, [uf 4 1]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 2 0 0]Sorry, but I don't think I can make it today.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Well, what happened?[e]
[uf 0 5 65278][uf 2 1]Don't worry, it's okay.[e]

[msg MSG_014_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 3 0 0]I'm really sorry...[n][uf 1 1][e]

[msg MSG_015_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 18 15 1]I just feel bad since I'm the one who wanted to hang out...[n][uf 1 1][e]

[msg MSG_016_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 5 0 0]But actually... my mom fainted.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 6 0 0]I'm at the hospital right now.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 7 0 0]They said it's exhaustion... since she works from morning till night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 8 0 0]Dammit! It's all my fault![n][uf 1 1][e]

[msg MSG_018_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 9 0 0]And my mom—she's trying to leave! She says we can't afford the medical bills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 10 0 0]Goddammit! Why can't I do anything!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 11 0 0]I'm useless! I'm just another one of her problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 12 0 0]......[n][uf 1 1][e]

[msg MSG_019_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 13 0 0]...I'm sorry about all that. I... I don't wanna be a problem for you, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 14 0 0]But I'm glad you were the one to hear me out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 15 0 0]Talking about this kinda helped.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Hayase is going through some awful times.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He opened up to me about it,[n]and I feel like we're closer now.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 90 65535 68 0 0][uf 3 1 1 0 0 16 0 0]I gotta get back to her room, so let's talk later, okay?[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]It's getting late, so I'll go back to the dorm.[n][uf 1 1][e]

