[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 4 101 65535 0 0][uf 3 1 1 0 0 1 0 0]Whoa, [uf 4 1]! Where's the fire!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 3 25 25]Yuko was pissed, wasn't she? I've missed a lot of practice lately.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 3 0 0]I should've told you last time, but um, my X-ray results...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 4 0 0]The muscles and tendons around my knee are inflamed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 5 0 0]The doctor said if I keep pushing it that I... won't be able to walk anymore.[n][uf 1 1][e]

[msg MSG_001_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 6 0 0]He said I strained it too hard during practice. So freakin' stupid...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 3 25 25]I want to win, so I have to practice.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]There's nothing you can do.[e]
[uf 0 5 65278][uf 2 1]Show some guts, man![e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 8 0 0]That's not an excuse![n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 8 5 105]Y-Yeah! You're right![n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 10 0 0]Every minute—every second counts! I can't waste any more time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 11 0 0]I promised I'd win at next year's meet and become the number one athlete in Japan.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]You promised?[e]
[uf 0 5 65278][uf 2 1]Why go so far?[e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 12 0 0]Yeah... I made a promise.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 8 5 105]Well, because it's not just about me.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 14 0 0]My nephew got into an accident, and his legs got messed up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 15 0 0]And now he can't walk.[n][uf 1 1][e]

[msg MSG_009_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0]But if he goes through rehab, he might be able to recover![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]He says the rehab hurts too much, though, so he doesn't want to do it.[n][uf 1 1][e]

[msg MSG_009_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 18 0 0]He's only five, y'know? There's still so much he hasn't done yet.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 19 0 0]So I made a deal with my nephew. Just, uh... don't laugh, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 20 0 0]If I become number one in Japan, he'll agree to go through rehab.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 21 0 0]That's why I have to win this meet—so I can make it to nationals![n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Do you think you can win?[e]
[uf 0 5 65278][uf 2 1]What about your knee?[e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 22 0 0]To tell you the truth... I don't think I can do it.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 8 5 105]Thanks for caring, man... but I can't worry about that now.[n][uf 1 1][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 24 0 0]Sorry for all the trouble I've caused. And for all the depressing conversations.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 25 0 0]It's really tough keeping it all bottled up. You were the only one I could talk to.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto opened up to[n]me about his troubles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 26 0 0]Yuko has good instincts when it comes to this stuff, so she might say something to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 27 0 0]Tell her to come talk to me if she does. I don't wanna drag you into this any deeper.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Miyamoto[n]and went back to the dorm.[n][uf 1 1][e]

