[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]Wow, that was so good! And the main character was cool and in control until the very end![n][uf 1 1][e]

[msg MSG_000_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]That last line he exchanged with the casino's boss gave me goosebumps![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]And how about that part when he was all, "Count to five!"?[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]I hope I can be like him when I'm an adult.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25][uf 4 1]-san, what do you think it takes for a guy to be hard-boiled?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Always keeping your cool.[e]
[uf 0 5 65278][uf 2 1]Excellent situational judgment.[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]That's true. You can't really be hard-boiled if you're quick-tempered.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 1 25 25]You have to keep calm and never let the enemy get under your skin.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]That's true. The detective did always make the right call, no matter what situation he was in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]He was compassionate but level-headed, and he never fell for the enemy's tricks.[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 3 25 25]...Come to think of it, that might be just what I need right now.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 3 25 25]I tend to get worked up about what's right in front of me, don't I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 3 25 25]That's exactly the kind of thing a kid would do... I need to fix that.[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]Well, now's as good a time as any to start. I'll give it my best shot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]If I do that, do you think I could become like him?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 1 25 25]A cool, hard-boiled guy, just like the detective in the movie...[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]That's impossible.[e]
[uf 0 5 65278][uf 2 1]It depends on your motivation.[e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]When I hear you say it, I really feel like it's possible.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]When you say it like that, I feel like I need to prove you wrong.[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]Yeah, you're right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 1 25 25]Don't worry, I'll work hard and prove that I'm not just all talk.[n][uf 1 1][e]

[msg MND_011_5_0]
[uf 0 5 65278][uf 2 1]Looks like Amada has learned[n]how to be an adult by observing[n]the movie's main character.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 0 25 25]Oh boy, look at the time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 3 25 25]But I still want to talk about the movie...[n][uf 1 1][e]

[msg MSG_012_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]...W-Wait, I'm not sleepy yet, okay?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]Zzz...[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I feel like I gained some [uf 4 30 2 1 1 0] after[n]watching how a man of conviction lives...[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 1]...Ones who should kill... prepared to be...[n][uf 1 1][e]

