[msg MSG_001_0_0 [Junpei's Voice]]
[uf 0 5 65278][uf 2 1]Dude, what are you even DOING? That's not gonna work![n][uf 1 1][e]

[msg MSG_002_0_0 [Amada's Voice]]
[uf 0 5 65278][uf 2 1]Junpei-san, could you please be quiet!?[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4104 0 0]...Sounds like tensions are running high.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Since we're essentially confined within an enclosed space, we should avoid such situations. Let's step in and mediate.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]What's with all the commotion? Is there a problem?[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2098 0 0]Oh, uh... Nothing, really. No big deal. Ahaha... Hahaha.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0]Junpei-san was getting worked up because he can't beat this game.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 52 65535 0 0][uf 3 1 3 0 65535 4105 0 0]What game...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Ah, you're referring to that object we found during our exploration? The [uf 4 4 0 37 1 16780], was it?[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Yep, that's the one! I was havin' a rough time tryin' to clear it.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2123 0 0]Then Amada here was all like, "Let me handle this!" So I let 'im take over, but he wasn't even any better![n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0]Because SOMEONE was being loud and distracting![n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0][uf 3 1 3 0 65535 4123 0 0]*sigh* So you two were arguing... over a game?[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0]No, seriously! You don't get it, this game is stupid hard![n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0]It really is. How could anyone possibly beat it with Junpei-san screaming in their ear...?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Stop fighting.[e]
[uf 0 5 65278][uf 2 1]Everyone, calm down.[e]
[uf 0 5 65278][uf 2 1]No more games.[e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7029 0 0]Ngh... Sorry.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7053 0 0]Awww... Really?[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]There's no need to go that far, Aigis.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4028 0 0]If this game is the source of your frustration, then this matter shall be put to rest once it's beaten, correct?[n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]I... I guess so?[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4085 0 0]...Then let's begin.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Amada, I want you to move per my directions. First, fall back.[n][uf 1 1][e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]Oh, uh, right![n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4140 0 0]One, two, three... Now head to the right, don't stop. There's an opening ahead. You can't miss it.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Whoa...![n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]...We won. We actually won. I can't believe it.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Well done.[e]
[uf 0 5 65278][uf 2 1]How did you do that?[e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4112 0 0]I didn't do anything particularly noteworthy.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4063 0 0]Oh, it was nothing. I'm sure you could have done it just as well.[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Remember: observe the enemy's positioning, then identify a weakness in their formation you can exploit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Once you've broken their defenses, they'll crumble, making it quite easy to wipe them out.[n][uf 1 1][e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7133 0 0]Ha... Haha... Quite easy, yes...[n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Takin' out the weakest link first, huh... Seems kinda dirty, though.[n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]I understand the feeling.[e]
[uf 0 5 65278][uf 2 1]It's a legitimate tactic.[e]

[msg MSG_033_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2124 0 0]Yeah? I mean, I know it's just a game, but at some point, I just felt sorry for 'em...[n][uf 1 1][e]

[msg MSG_034_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2124 0 0]Yeah, I get that, but... I dunno, it just feels bad steamrolling 'em like that.[n][uf 1 1][e]

[msg MSG_035_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0]I can't say I agree. Would you still feel the same way when facing a real enemy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 0 1 0 25 25]...Perhaps this is a good opportunity to remind you all of the proper combatant mindset.[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru-san seems to have steeled[n]her resolve after observing us...[n][uf 1 1][e]

[msg MSG_037_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7112 0 0]P-Please go easy on us...[n][uf 1 1][e]

