[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I really wish I had a bigger allowance...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]But I also don't want to make things hard for my mom...[n][uf 1 1][e]

[msg MSG_001_0_0 [Gaudy Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 150]Hey, I saw that! You were looking at that waitress, weren't you?[n][uf 1 1][e]

[msg MSG_002_0_0 [Nervous Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 100]I-I'm sorry! Forgive me! I'll do anything you want! Anything![n][uf 1 1][e]

[msg MSG_003_0_0 [Gaudy Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 150]Then how about you buy me that bag I was talking about before? Or else I'm breaking up with you![n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I used to think that money couldn't buy happiness... or friends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]That is, until recently...[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]What do you think now?[e]
[uf 0 5 65278][uf 2 1]What do you mean?[e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Of course, I still think that's mostly true... but I do have my doubts...[n][uf 1 1][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 9 5 109]...Oh, don't worry. I was just talking to myself.[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]But... I do sort of understand how he feels...[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]That man has no confidence in himself. That's why he's so desperate to stay on the woman's good side.[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I think I can relate to that feeling. He just wants to be with her... no matter the cost.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I can sense affection coming from Chihiro.[n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I think lonely people feel really insecure. That's why we seek connections, even if we have to pay for them.[n][uf 1 1][e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]If only I could be strong and confident in myself, like our student council president...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]...I think about that from time to time.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Chihiro has a serious look on her face.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Chihiro a little better now...[n][uf 1 1][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I can't help but feel like... there are so many things in this world that I'll never have.[n][uf 1 1][e]

[msg MSG_016_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Well, should we get going?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]If I stay here, I know I'll just want to go back to the bookstore and look at that illustration collection again.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I walked Chihiro part of the way[n]home, then went back to the dorm.[n][uf 1 1][e]

