[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Aigis wants to watch[n]a movie together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, watching it could help[n]improve my [uf 4 30 0 37 1 0]...[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]Should I take her up on that?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go with Aigis[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I should reply to her...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]This might be a good opportunity to[n]deepen my bond with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I'll reply later...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

