[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Ryoji wants to hang out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet up with him?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Ryoji[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Ryoji is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Ryoji is acting weird... I should head[n]to the [uf 0 1 2]music room[uf 0 1 27] later.[n][uf 1 1][e]

