[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Amada wants to hang out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet up with him?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Amada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Amada is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Fuuka seems worried about Amada...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I go check in on him?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems worried about Amada...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I go check in on him?[n][uf 1 1][e]

