[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Looks like Koromaru is out front.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I check up on Koromaru?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Check on Koromaru[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Let's head to where Koromaru is.[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Looks like Koromaru is out front again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I check up on Koromaru?[n][uf 1 1][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Looks like Koromaru is out front again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I check up on Koromaru?[n][uf 1 1][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Looks like Koromaru is out front today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I check up on Koromaru?[n][uf 1 1][e]

