[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Maiko seems worried about Kamiki...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I go to the shrine?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go[e]
[uf 0 5 65278][uf 2 1]Don't[e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Let's head to the shrine.[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

