[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Junpei wants to hang out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet up with him?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Junpei[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Junpei is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Junpei's asking if we could hang out. Maybe[n]I should meet with him after school...[n][uf 1 1][e]

