[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Looks like Aragaki wants to hang out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet up with him?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Meet with Aragaki[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Let's head to where Aragaki is.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Come to think of it, Mitsuru left me[n]with the school reinstatement form...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet with Aragaki?[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Come to think of it, I still have Aragaki's[n]leave of absence extension form...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I meet with him?[n][uf 1 1][e]

