[msg MSG_REAPER_CHASE_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 3 0 65535 4128 0 0]Wha—!? This presence...[n][uf 1 1][e]

[msg MSG_REAPER_CHASE_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4007 0 0]The Reaper pursued us all the way here! Run![n][uf 1 1][e]

[msg MSG_REAPER_CHASE_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5100 0 0]Huh...? It's still here!?[n][uf 1 1][e]

[msg MSG_REAPER_CHASE_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5091 0 0]The Reaper followed us down! Please run![n][uf 1 1][e]

