[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Three doors... I wonder where they lead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 50 0 0][uf 4 25 6]Hm...[n][uf 1 1][e]

[msg MSG_000_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]I'm detecting Shadows behind each door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Starting from the left and going right, the Shadow readings get stronger. But I'm picking up treasure chests with similar signals, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]So the leftmost one is the least dangerous, but has the smallest reward. And the rightmost one is the riskiest, with the greatest reward...[n][uf 1 1][e]

[msg MSG_000_2_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]It's up to you to decide which way to go, but please keep that information in mind.[n][uf 1 1][e]

[msg MSG_Monad04_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 1 20131 0 0]I'm not detecting anything in the immediate area, so we should be okay for now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Would you mind investigating those doors?[n][uf 1 1][e]

[msg MND_Monad04_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]I suppose I should examine the doors.[n][uf 1 1][e]

[msg MSG_Monad05_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 1 20136 0 0]Uh, please wait! There are only stairs up ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]I really think we should figure out what's going on, so please come back for now.[n][uf 1 1][e]

