[msg MSG_000_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]You're a weird one, y'know that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]The biggest bitch in school is leaving, and you're gonna miss her?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]You're transferring... and you didn't say anything...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]It's not like it would've made a difference. Why make us both depressed?[n][uf 1 1][e]

[msg MSG_003_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 5 0 0]But yeah, my dad suddenly collapsed...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]And they say it'll take a while for him to recover, because of some complications...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 7 0 0]We don't really have that much money, so we can't afford to stay in this area.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Y'know, now that I think about it, you're the only one who bothered being friends with a weirdo like me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0]But like I said before... we're both in the same boat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]My parents act like I don't even exist. I hate living with them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]That's why I was so jealous when you moved into the dorm.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Natsuki-chan...[n][uf 1 1][e]

[msg MSG_007_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]You know, you've really changed, Fuuka. You're a lot more cheerful now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]But why'd you move when your house is, like, right here?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Huh? Well, um...[n][uf 1 1][e]

[msg MSG_009_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]If you don't wanna say, that's okay. I'm sure you've got your reasons.[n][uf 1 1][e]

[msg MSG_010_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]But, if it's something that you and your parents can work out, then do it while you have a chance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]It'll be a while before my dad's in any condition for us to have a heart-to-heart.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 20 0 0]......[n][uf 1 1][e]

[msg MSG_012_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 11 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Haha, what am I doing? This isn't what I wanted to talk about.[n][uf 1 1][e]

[msg MSG_013_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Y'know, Fuuka... I used to think every day was just the same depressing routine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]And, I'm only saying this 'cause it's you, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]You don't really get many second chances in life.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Natsuki-chan...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]I guess this is the last time I'll see this view...[n][uf 1 1][e]

[msg MSG_015_5_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 27 0 0]I won't be in school next week 'cause I'll be packing, so... I guess this is goodbye.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 28 0 0]No![n][uf 1 1][e]

[msg MSG_017_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 29 0 0]Haha, don't you dare come see me off! I wanna say goodbye on my own terms.[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 30 0 0]......[n][uf 1 1][e]

[msg MSG_019_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]C'mon, don't give me that look.[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 32 0 0]But... you're leaving so suddenly...[n][uf 1 1][e]

[msg MSG_021_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 33 0 0]Hey, I'm not all broken up about this, just so you know. I've changed a lot since I met you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 34 0 0]I'm gonna try and figure out what I really wanna do with my life.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 35 0 0]I know you can do it, Natsuki-chan.[n][uf 1 1][e]

[msg MSG_023_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 11 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Haha, well now I really feel like I gotta do it. No pressure, right?[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 37 0 0]No...[n][uf 1 1][e]

[msg MSG_025_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 38 0 0]I got one last thing I wanna say before I go.[n][uf 1 1][e]

[msg MSG_026_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 39 0 0]If you just accept the way things are, then you'll never move forward... just like me.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 0 0 0 40 0 0]......[n][uf 1 1][e]

[msg MSG_028_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 41 0 0]So, I hope you can figure out what you want, too.[n][uf 1 1][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 42 0 0]What I want...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 43 0 0]I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 0 0 0 44 0 0]......[n][uf 1 1][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 45 0 0]I used to try and please everyone just to fit in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 46 0 0]I was afraid of not being liked, so I always went along with the people around me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 47 0 0]But, I never really thought about what I wanted.[n][uf 1 1][e]

[msg MSG_031_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 11 2 65535 0 0][uf 3 1 1 0 0 48 0 0]Hahaha, that's so you. Well, if they don't like you for who you are, I say screw 'em.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 1 0 25 25]But... I like you, Fuuka, even if you hate yourself.[n][uf 1 1][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 50 0 0]Natsuki-chan...[n][uf 1 1][e]

[msg MSG_033_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 51 0 0]Well... I better get going.[n][uf 1 1][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 52 0 0]......[n][uf 1 1][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 53 0 0]Ah...[n][uf 1 1][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 54 0 0]Huh? Natsuki-chan!?[n][uf 1 1][e]

[msg MSG_037_0_0 [Text Message]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 55 0 0][uf 5 21 0 2]"Here..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 56 0 0][uf 5 21 0 2]"Even if we're apart, we're still connected. So, we can always talk, right?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 57 0 0][uf 4 23 0 2 3 25 25][uf 5 21 0 2]"Thanks for being my friend. I'm kinda tearing up now."[n][uf 1 1][e]

[msg MSG_037_5_0 [Text Message]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 58 0 0]"Here..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 59 0 0]"Even if we're apart, we're still connected. So, we can always talk, right?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 60 0 0]"Thanks for being my friend. I'm kinda tearing up now."[n][uf 1 1][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 61 0 0]Natsuki-chan...[n][uf 1 1][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 62 0 0]"Even if we're apart, we're still connected."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 63 0 0]......[n][uf 1 1][e]

[msg MSG_039_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 64 0 0]I get it now, Natsuki-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 65 0 0]I'd always assumed my powers were a reflection of my faults...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 66 0 0]I was always worried about how other people see me, and that's why my powers let me "see" others...[n][uf 1 1][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 67 0 0]But, I guess there is something I want after all...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 68 0 0]Seeing everyone getting along and working together makes me so happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 69 0 0]So, I want us to treasure this forever.[n][uf 1 1][e]

[msg MSG_040_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 70 0 0]I have the power to connect people, even when they're apart...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 71 0 0]My Persona has given me this amazing gift—the friendship I've always wanted.[n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]The resolution in Fuuka's heart has awakened a new Persona...[n][uf 1 1][e]

[msg MND_041_5_0]
[uf 0 5 65278][uf 2 1]Fuuka's Persona, [uf 0 1 35]Lucia[uf 0 1 27], has given rise to [uf 0 1 35]Juno[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_042_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 72 0 0]There you are.[n][uf 1 1][e]

[msg MSG_043_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 73 0 0]Oh... What are you all doing here?[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 74 0 0]It is unusual to find you up on the rooftop.[n][uf 1 1][e]

[msg MSG_045_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 75 0 0]Well, we didn't see you around, so we weren't sure if you were alright...[n][uf 1 1][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 76 0 0]I think I've figured it out.[n][uf 1 1][e]

[msg MSG_047_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 77 0 0]Okay...?[n][uf 1 1][e]

[msg MSG_048_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 78 0 0]I've made up my mind. I'm going to do everything I can with the power I've been given.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 79 0 0]This is what I've decided I want to do.[n][uf 1 1][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 80 0 0]Um... Sure?[n][uf 1 1][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 81 0 0]Hehe, sorry. I guess that was out of nowhere, wasn't it?[n][uf 1 1][e]

[msg MSG_051_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 82 0 0]Uh... You sure you're alright?[n][uf 1 1][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 83 0 0]Hehe.[n][uf 1 1][e]

