[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3010 0 0]Hey. It's not often that you ask to meet like this. So, what is this store?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The staff said, "This treatment will help you face your inner self"...[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3140 0 0]Well, you never know till you try. I'll give it a go.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]Oh, this place again?[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Well, that's fine with me. I'll face my inner self for sure this time.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3112 0 0]...I didn't realize that I fell asleep until I woke up.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I feel rejuvenated, but... I don't feel like I fully faced my inner self...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3023 0 0]...Well, while I'm feeling good, I might as well get a quick run in. All right, I'm off.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 3 0 65535 3048 0 0]...I failed again. I slept through the whole thing this time too...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]But I'm feeling pretty good for some reason. I better take advantage of this and get to training.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3023 0 0]I'm gonna head off and jog home. I'll see you later.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

