[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Man, something just feels off... Like I'm in some kinda funk.[n][uf 1 1][e]

[msg MSG_000_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]But, c'mon... It's not like this is that much different from before, so what's up with me all of a sudden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]Maybe I'm just...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2037 0 0]Nah, no frickin' way! Quit thinkin' like that, Junpei![n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]What's gotten you so distressed, Iori?[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2084 0 0]"Distressed"? Who's distressed? Definitely not me, hahaha...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Was I mistaken? It certainly seemed like it to me.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4024 0 0]Our weakened Persona abilities have made for some difficult battles, haven't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I can understand your anxiety.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0]But you're not the only one dealing with this. We are all experiencing the same struggle.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2065 0 0]Yeah, I know... I get that, but...[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]...Hm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]This really isn't my strong suit—comforting people, I mean. It requires a certain intuition.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0][uf 4 23 0 1 6 25 25]It appears that making Aigis the leader was the right call.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2090 0 0]That's why!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 52 65535 0 0]Is it that surprising? It's only natural to seek assistance to cover one's weaknesses.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Huh... You've got a point. Now that I think about it, of course you'd say that.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2092 0 0]I should have known this already... Why'd I lose sight of it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]All that stuff about you, Senpai... and about myself.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 52 65535 0 0]Iori...?[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Heh, don't you worry about me! It's okay to be a loser, because nobody's perfect, right?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4061 0 0]I'm afraid I don't follow... But if that's what makes you feel better, then that's all that matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0]Honestly, I'm relieved. It's been quite a while since I've last seen that carefree smile of yours.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]Oh, uh, has it? Guess so...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4060 0 0]You know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0]Your smile reminded me of something as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0]Or rather, someone I want to protect—not for my family's sake, but for my own.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0]What, you mean like... a lover!?[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Do you think this is funny, Iori? Tread lightly.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Dang, tough crowd.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Anyway, I kinda get you, I think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0]The times we're all together, well... Those are the memories I treasure most.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4025 0 0]Precisely.[n][uf 1 1][e]

