[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]...I don't think I ever told you about how things were before you joined.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]SEES originally started off with only three members.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Back in middle school, I invited Akihiko to join, and Aragaki followed him soon after.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]...We had no idea what we were doing back then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]We were young, inexperienced... and we had almost no intel to work off of.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]We could barely even make it past the entrance to Tartarus back then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Actually exploring the tower, like we're doing now, was nothing more than a pipe dream.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Even with all our shortcomings, we worked decently as a team.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]As peers, it was easy for us to connect, and the work was hard, but fulfilling.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I can't even imagine.[e]
[uf 0 5 65278][uf 2 1]I wish I could've seen it.[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]...Oh, I'm sorry. I'm not complaining about our current circumstances.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]We've discovered how to eliminate the Dark Hour, and we've since grown much stronger.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 3 25 25]However... after what happened in Yakushima, and with Aragaki rejoining... it's hard not to remember the old days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 3 25 25]...Maybe I'm so concerned about re-enrolling him in school because I'm still living in the past.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Living in the past?[e]
[uf 0 5 65278][uf 2 1]Why's his attendance so vital?[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Yes.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Well...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]Some time after we started working as a team, we all came to an agreement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]We promised we'd all graduate together... No one left behind.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 0 25 25]Akihiko was just as reckless back then, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]Aragaki was always the one reminding him that our lives were at stake.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 1 25 25]Although, his wording certainly wasn't quite so thoughtful...[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]What a surprise.[e]
[uf 0 5 65278][uf 2 1]I can imagine.[e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 1 25 25]I know, right? I was surprised, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]But, Aragaki didn't use to distance himself from others like he does now.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]Heh, it suits him, doesn't it? I guess you've gotten to know him well.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 3 25 25]Ever since he left the team, he's acted like he's wanted to punish himself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 3 25 25]It's almost like he just wants to waste away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 10 25 25]I'm hoping he'll remember his promise and take a step back and look at himself.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]...That's why I gave you the paperwork to get him back in school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]That was my last hope, but I suppose it didn't work out. I'll tell Akihiko myself.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]All right, I'll take this. I'll start on the process for extending his leave of absence.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems like Mitsuru and Sanada were really[n]hoping Aragaki would return to school...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should think carefully about[n]whether to hand this over or not...[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 4 25 25]...What's the matter?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Wait a minute.[e]
[uf 0 5 65278][uf 2 1]Nothing.[uf 2 9 1 1 1312][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 4 25 25]...Oh, sure. What's wrong, though? Is it missing a page?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 0 25 25]I'll let you handle it, then. Make sure to let Aragaki know as well.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 0 25 25]Very well, thank you. I'm sorry you had to hold on to this for so long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 0 25 25]I'll take care of things from here. Make sure to let Aragaki know as well.[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]I took the leave of absence extension[n]form and left the student council room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should look for Aragaki[n]and get him to reconsider...[n][uf 1 1][e]

