[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I see Maya.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]listen tatsuya! ＞;)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]nowadays i just log on to MMOs with bedhead and all (liek today lol)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]but when i was little, ppl said i was a real cutie -_-;;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]guess i missed my chance rite? nobody thinks i'm hawt ne more T_T[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...do men only want younger women? b honest ._.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]What are you talking about?[e]
[uf 0 5 65278][uf 2 1]Age isn't the point.[e]
[uf 0 5 65278][uf 2 1]Well, yeah.[e]

[msg MSG_003_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]er, sry... kinda random i know ^^;;;[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Maya seems a little awkward.[n][uf 1 1][e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]when i get all worked up, i dun realize what comes outta my mouth =x[n][uf 1 1][e]

[msg MSG_031_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 5 1]that's wat im talkin about! u really get me ;D what's really important is tru luv![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]buuuut i think i tend to liek them on the younger side too tho :X lol[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]Maya seems very happy.[n][uf 1 1][e]

[msg MSG_006_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]thought so... everyone knows it but it still sux to hear it for real orz T_T[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 5 13 10 15 1]fair is fair tho =P i tend to liek them on the younger side myself lol[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...what ＞_＞;; im innocent!!!!![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Maya begins to cower.[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]btw, am i making ne sense? i hope so, cuz i teach composition!! o_O;;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]mkay, i'll be calm. i'll compose my bitching carefully for you ;P[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]one of my coworkers is really pissing me off. im trying to avoid her @_@[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]we use to teach teh same grade and we were together ALL THE TIME[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]its been a while but that kinda thing sticks w/ u, ya know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]ne way, she said she needed some advice, but then she just started bragging! ＞=([n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]some student asked her out, and a guy she doesn't liek proposed to her... UGH![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]im not jealous, its just so freakin annoying omg =_=;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i hate skanky hoes liek her! just give the puppy-dog eyes and guys will do whatever![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]she even stuffs her bra!! lol[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]She, um... what?[e]
[uf 0 5 65278][uf 2 1]Calm down.[e]

[msg MSG_010_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 5 1]...im afraid u know too much now tatusya...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]but thats rite, she's got fake tits[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]HAHahahahahhahaha!!!1 xDDDDDD ok for real tho keep dis between u an me, k? O=)[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Maya seems to be enjoying herself.[n][uf 1 1][e]

[msg MSG_012_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0][uf 5 13 10 5 1]not my fault shes so insecure she has to equip buffs on her boobs. :V how fake can u be[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]im fine w/ massaging in teh shower and drnking more milk. all natural ;)[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Maya's telling me more[n]than I wished to know.[n][uf 1 1][e]

[msg MSG_014_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]i swear omg, i saw Ms. K running in late one time, rite? and uh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]her pads fell down an it looked liek she had 4!!! O_O XDDD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...theyre fake for sure u_u[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]my school is FULL of teachers like taht! -_-;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]man tatsuya, talkin to u is better than gettin a massage =P ::blush::[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]complaining online is now an important part of my days off ^_^[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Maya seems to like talking to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_016_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]we r s'posed to be fighting demons from hell, rite? ＞;)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...but after what i jus said, i might go to hell ne way o_O;;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]well... i rented sum DVDs, sooo... later, tatsuya! thx for chattin[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

