[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey... Sorry about last time, when, you know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Forget about it, alright?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Anyway, would you mind listenin' to this old man complain?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I'm sober today, so... sit tight, will ya?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]All I had to do was look all serious and recite the sutras... I could make easy money from donations...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]That's what I thought. That's why I set aside my pride and begged my parents to let me take over the temple.[n][uf 1 1][e]

[msg MSG_001_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]But every day is someone's death anniversary! Kinda makes you think how long people've been around![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 114 2 25 25]I'm workin' memorial service after memorial service 24/7, as if my little temple was some kinda convenience store...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Why not take a break?[e]
[uf 0 5 65278][uf 2 1]Poor men know no leisure.[e]

[msg MSG_003_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 17 5 114]If only I could... But I have a strong sense of duty.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I can't say no to someone who needs my service. It's the burden of a strong moral compass.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 5 13 17 5 114]...That's only half true, kid. Sure, I've got no time for leisure, but I'm definitely not poor.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]It varies, of course, but an offering can sometimes be as much as a white-collar worker's year-end bonus.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]...But, as you can see, I'm too busy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 114 0 25 25]I gotta push this old body of mine to the limit. I hate this "work your ass off" mentality.[n][uf 1 1][e]

[msg MSG_007_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Maybe I should think of somethin' else to do with my life. I can't keep this up for much longer... My alcohol tolerance is weaker too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I've been drinkin' too much lately... Makin' a fool of myself like I did the other day.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Hang in there.[e]
[uf 0 5 65278][uf 2 1]Time to retire?[e]

[msg MSG_009_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 17 5 114]...Thanks. I know you're just tryin' to make me feel better, but... I'll take it.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 17 5 114]Yeah, maybe you're right. Ya gotta know when to quit when you're ahead.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Oh, then how's this for an excuse...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]We never filed for divorce, and I've got some pretty good real estate now that I've inherited this temple.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]It's not a bad deal. I've got enough money that I can retire and just enjoy the rest of my life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Whaddaya think?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]What's this about?[e]
[uf 0 5 65278][uf 2 1]I don't really care.[e]

[msg MSG_014_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 17 5 114]Oh, um... Well...[n][uf 1 1][e]

[msg MSG_015_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 5 13 17 5 114]Come on, don't gimme that. I really put a lotta thought into this.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I'm thinking about asking them to come back... You know, my wife... and my son.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]First, I gotta find out where they are. I'll hire a detective. I don't care how much it costs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]And when I see 'em, first thing I'm gonna do is tell 'em I'm sorry... from the bottom of my heart.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 114 3 25 25]I'm gonna be concentratin' on them, so... I probably won't be seein' ya anytime soon...[n][uf 1 1][e]

[msg MSG_017_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]W-Well, I'm glad this is it. One brat is all I can handle at a time, and I've gotta deal with my own son now.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Despite his harsh words, Mutatsu[n]sounds like he's going to miss me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_019_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]If I knew it was gonna end up like this, I never woulda become a monk...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I guess I'll go to a detective agency tomorrow...[n][uf 1 1][e]

[msg MSG_019_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Alright, let's get going, kid.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I left the club with Mutatsu.[n][uf 1 1][e]

