[msg MSG_000_0_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]Autumn, the year 199X...[n][uf 1 1][e]

[msg MND_000_3_0]
[uf 0 5 65278][uf 2 1]I have one new message.[n][uf 1 1][e]

[msg MSG_000_5_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]From: "PHIL."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Reality is just a series of events and players acting out what they believe to be true.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]When we accept that fact, our world becomes as real as any other.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Reality is but a reflection of our own thoughts and expectations.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But... what if we were merely reflections in someone else's mirror?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Are you prepared to look through that mirror to discover the truth?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I don't see any other players...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A girl in red approaches me.[n][uf 1 1][e]

[msg MSG_002_0_0 [Girl in Red]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17003 0 0]sup xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]asl...? oh wait, r u a nub? u r, huh? ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]oh wow. u haven't even finished makin your char yet... o_O[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]guess the new default skin thing was 4 real. i got dis cool outfit in the patch too[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]not liek it brought in many new ppl... this is kind of a dead MMO these days xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]eh, welcome to teh game! cool to seeya round :3[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Who are you...?[e]
[uf 0 5 65278][uf 2 1]It's not popular anymore?[e]

[msg MSG_004_0_0 [Girl in Red]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]sry. i got kinda ooc there =o[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]we r supposed to be our "alternate selves" rite? uhhhh... yeah =/[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]sooo... what r u gonna call ur char? all i c is "no data" o_O[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]hm... hey, i got a good name for u :3[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]how bout tatsuya? ya thats perfect, imo[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i'll change mine to maya, k? =D[n][uf 1 1][e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]have a little deja vu? ;P[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Heh, that's clever.[e]
[uf 0 5 65278][uf 2 1]I don't get it...[e]

[msg MSG_007_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]o rly? im impressed, i didn't think many people played that![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]well if u see any jokers, be sure to rescu me, k? ^^y[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]figures, its been a while hehe. i played that game soooooo much in college T_T[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]oops. hope u cant figure out how old i am... rofl!![n][uf 1 1][e]

[msg MSG_009_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]ne way, im usually idling here on my [uf 0 1 2]days off[uf 0 1 27]... ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]so if ur bored, maybe we can level together. it sux to be lonely =P[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I've become acquainted with a player[n]who goes by the name "Maya"...[n][uf 1 1][e]

[msg MSG_011_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]sry, gtg =x[n][uf 1 1][e]

[msg MSG_012_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]remember, let's think positive! traesto! xD[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

