[msg MSG_000_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]So if there's leftovers, we can keep them in the fridge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]But, we're cooking for two today, so there probably won't be leftovers.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh, I forgot to mention, but I'm making katsudon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 5 0 0]Make sure to eat it all, no matter how it tastes.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]You're making it?[e]
[uf 0 5 65278][uf 2 1]Only if it tastes good.[e]
[uf 0 5 65278][uf 2 1]I prefer ramen.[e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]I said I'd thank you, didn't I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]If you don't want it, I could put the meat away... But that's a pain, so just eat it.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0]...You got guts sayin' that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]Well, I'm makin' this to thank you, so I'm not gonna give you somethin' terrible.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 10 3 25 25]...I said I'd thank you, but this place ain't equipped to make that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 10 0 25 25]I want somethin' with rice. So we're havin' katsudon today, got it?[n][uf 1 1][e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 12 0 0]Alright then, time to get started.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 13 0 0]The rice is already cooked, so just scoop everything into a bowl once it's ready.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0]...I like extra large portions, by the way.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I watched Aragaki cook. His skill is on[n]par with that of a professional chef...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The katsudon is ready.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Crunchy, flaky breaded pork, topped with[n]half-cooked egg... I could eat this all day![n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 10 1 25 25]Looks like you're a fan, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 0 0 0 16 0 0][uf 4 23 0 10 0 25 25]......[n][uf 1 1][e]

[msg MSG_009_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 18 0 0]Anyone can make this, long as they practice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]Today we just had the rice and toppings, but you could add side dishes too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 20 0 0]Well, give it a try when you have time.[n][uf 1 1][e]

[msg MSG_010_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 21 0 0]Alright, I did my part to thank you. You handle the cleanup.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0]See ya around.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 23 0 0]We're havin' katsudon again, got it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 24 0 0]...Don't give me that look. We got a lot of pork 'cause it was cheap.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 25 0 0]Part of me thinks startin' with fried food might be hard, but the basics are pretty much the same.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 26 0 0]You're a real oddball, you know that? Askin' me to teach you how to cook.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 27 0 0]Why do you wanna learn so much?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]I care about my health.[e]
[uf 0 5 65278][uf 2 1]I just felt like it.[e]
[uf 0 5 65278][uf 2 1]I want to be popular.[e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0]...Ya do, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 29 0 0]Well, good a reason as any.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 10 4 25 25]You don't really think things through, do you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 10 0 25 25]Well, whatever. It can't hurt to know.[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 32 0 0]Well, we all got our own reasons...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 33 0 0]Can't hurt to know this stuff. But you better put in the work if you wanna be popular.[n][uf 1 1][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 34 0 0]I was taught how to cook by someone else too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 35 0 0]So, when I see someone who wants to learn, I can kinda relate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 36 0 0]Alright, that's enough rambling. Let's get started.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 37 0 0]...You're gonna do it this time. So first, get the meat ready.[n][uf 1 1][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 38 0 0]When you're frying something, stick a chopstick in the oil and check for little bubbles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 39 0 0]Wait, you're putting on too much heat. The meat ain't gonna taste good if it's too tough.[n][uf 1 1][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 10 1 25 25]Pretty good job, considering it was your first try.[n][uf 1 1][e]

[msg MSG_019_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 10 0 25 25]You've still got room for improvement though. Especially in the way you handle the knife and fryer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 42 0 0]But if you're serious about it, then just practice.[n][uf 1 1][e]

[msg MSG_020_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 43 0 0]Alright, let's clean up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 44 0 0]You ain't done cooking until everything's put away, so don't slack off.[n][uf 1 1][e]

