[msg MSG_000_0_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]== IMPORTANT ANNOUNCEMENT ==[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It has been our hope since the launch of Innocent Sin Online to maintain the game for as long as we are able.[n][uf 1 1][e]

[msg MSG_001_0_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]It has been our hope since the launch of Innocent Sin Online to maintain the game for as long as we are able.[n][uf 1 1][e]

[msg MSG_002_0_0 [Game Screen]]
[uf 0 5 65278][uf 2 1]Unfortunately, after careful consideration, we have made the difficult decision to terminate service.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We deeply apologize for any inconvenience this may cause for our loyal players.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The servers will remain open until the official end date. Please tie up any unfinished business before then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Thank you for understanding. We hope you've enjoyed your time with Innocent Sin Online.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sincerely,[n]     Innocent Sin Online staff[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]The game's booted up now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I see Maya.[n][uf 1 1][e]

[msg MSG_004_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]...u got that message from teh admins, rite tatsuya? T_T[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Maya faces away.[n][uf 1 1][e]

[msg MSG_006_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]it said their cancelling innocent sin. ...think its for real?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Not much we can do.[e]
[uf 0 5 65278][uf 2 1]No way![e]
[uf 0 5 65278][uf 2 1]Whatever, I guess.[e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]yeah... i guess not many ppl were playing ne more... :＜[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Maya seems sad.[n][uf 1 1][e]

[msg MSG_010_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]but it still sux... they prolly jus wanna save some munny -_-[n][uf 1 1][e]

[msg MSG_011_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 5 1]i know rite!? how dare they! ＞=/[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Maya is getting all worked up.[n][uf 1 1][e]

[msg MSG_013_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]i finally found a place to vent my frustration and now this!!![n][uf 1 1][e]

[msg MSG_014_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]yeah, i was a little stunned at first too[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Maya seems sad.[n][uf 1 1][e]

[msg MSG_016_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]this MMO started out as a way to kill some tiem, but now its diff -_-;[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Maya gets closer.[n][uf 1 1][e]

[msg MSG_018_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]tatsuya... do u think we'll still be able to see each other? T_T[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]No, this is the end.[e]
[uf 0 5 65278][uf 2 1]Don't worry about that.[e]

[msg MSG_020_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]yea... guess we gotta find another way ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]a diff MMO maybe? or irl somewhere... idk, i liked this one tho[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Maya seems a little down.[n][uf 1 1][e]

[msg MSG_022_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]so its just an ingame relationship to u tatsuya...? ur so cold...me am cry T_T[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...i dun wanna admit it but i guess your rite ._.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Maya seems sad.[n][uf 1 1][e]

[msg MSG_024_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]alrite, i'll try not to think about it ^^;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]wait but that'll jus make me think about it even more! T_T[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Maya seems troubled.[n][uf 1 1][e]

[msg MSG_026_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]NO! we have to stop wasting our tiem! :([n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]maya's not goin quietly! ＞=/ i'll beat em to the punch![n][uf 1 1][e]

[sel SEL_027_0_0 top]
[uf 0 5 65278][uf 2 1]What are you planning?[e]
[uf 0 5 65278][uf 2 1]This won't change anything.[e]

[msg MSG_028_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0][uf 5 13 10 5 1]...oh dun worry tatsu. i won't do ne thing dangerous 8)[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Maya seems a little happier.[n][uf 1 1][e]

[msg MSG_030_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]tatsuya, sumtimes in life u have to stand up for urself. times liek these.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Maya seems pretty serious.[n][uf 1 1][e]

[msg MSG_032_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]im gonna send them a log fo the convos we've been havin together here ^_^[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]if they knwo this game is important to us, maybe they'll reconsder =D[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]even tho u might be a middle aged man or a 12 y/o girl...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]that shouldn't matter!!!1[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0](to tell u the truth, i kinda hope ur a handsome guy tho...)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]dun worry, maya will protect u! we'll always be partners, k?[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]I can tell Maya cares about me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_034_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]kk! i'm gonna go write my email w/ our convo log! ^_^[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]dont mess w/ maya & friends or u'll regret it! MwahAHaHhaHa![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]next time we'll celebrate our victory, k? bai~~~[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

