[sel SEL_MISSING top]
[uf 0 5 65278][uf 2 1]Take back to the entrance[e]
[uf 0 5 65278][uf 2 1]Ask for an escort[e]
[uf 0 5 65278][uf 2 1]Do nothing for now[e]

[msg MSG_MISSING_PERSON_REACT [Student in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_2 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_3 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_4 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_5 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_6 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_7 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_8 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_9 [Old Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_10 [Student in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_11 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_12 [Girl in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_13 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_14 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_15 [Man in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_16 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_17 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_18 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_19 [Woman in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_REACT_20 [Student in Pain]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_RESCU [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]That must be one of the people who went missing.[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_RESCU_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]We need to provide treatment immediately. Please return to the entrance as soon as you can![n][uf 1 1][e]

[msg MSG_RESCUE_GO_ENTRANCE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Understood. I'll wait for you at the entrance![n][uf 1 1][e]

[msg MSG_RESCUE_RESERVE_MEMBE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]In that case, please stand by until an escort arrives at your location.[n][uf 1 1][e]

[msg MSG_RESCUE_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 50 0 0][uf 3 1 3 0 65535 1116 0 0]I'm on my way. Just wait a sec.[n][uf 1 1][e]

[msg MSG_RESCUE_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 50 0 0][uf 3 1 3 0 65535 2117 0 0]Aaand that's my cue! Hang tight![n][uf 1 1][e]

[msg MSG_RESCUE_SANADA_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 50 0 0][uf 3 1 3 0 65535 3085 0 0]I'm heading out now. Just wait, I'll be there soon.[n][uf 1 1][e]

[msg MSG_RESCUE_MITURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4115 0 0]I'll go, then. Just hold on for a little longer.[n][uf 1 1][e]

[msg MSG_RESCUE_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_RESCUE_AEGIS_00 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 50 0 0][uf 3 1 3 0 65535 6117 0 0]Please wait there. I will arrive shortly.[n][uf 1 1][e]

[msg MSG_RESCUE_AMADA_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 50 0 0][uf 3 1 3 0 65535 7119 0 0]Would you like me to go? Don't worry, I'll be there in a jiffy.[n][uf 1 1][e]

[msg MSG_RESCUE_KOROMARU_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 50 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_RESCUE_ARAGAKI_00 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 50 0 0][uf 3 1 3 0 65535 9107 0 0]Just hang on, I'll be quick.[n][uf 1 1][e]

[msg MSG_RESCUE_YUKARI_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Sorry to keep you waiting. You can leave the rest to me.[n][uf 1 1][e]

[msg MSG_RESCUE_JUNPEI_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2029 0 0]Alright, I'm here! Let me take care of this—you get goin'![n][uf 1 1][e]

[msg MSG_RESCUE_SANADA_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3023 0 0]Sorry for the wait. Just leave the rest to me. I'll keep 'em safe.[n][uf 1 1][e]

[msg MSG_RESCUE_MITURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]Apologies for the delay. I'll make sure this person is escorted back safely.[n][uf 1 1][e]

[msg MSG_RESCUE_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_RESCUE_AEGIS_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6020 0 0]Thank you for your patience. Please let me handle this.[n][uf 1 1][e]

[msg MSG_RESCUE_AMADA_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7116 0 0]Whew, sorry for making you wait. I'll make sure this person gets back safe and sound![n][uf 1 1][e]

[msg MSG_RESCUE_KOROMARU_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_RESCUE_ARAGAKI_10 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9010 0 0]Yo, sorry 'bout the wait. I'll handle it from here.[n][uf 1 1][e]

[msg MSG_RESCUE_KOROMARU_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]Oh, I think Koro-chan's volunteering to go! Well then, we're counting on you, Koro-chan.[n][uf 1 1][e]

[msg MSG_MISSING_PERSON_FUMI [Bunkichi]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

[msg MSG_RESCUE_KOROMARU_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Looks like he made it there safely. Well done, Koro-chan! Please bring them back quickly![n][uf 1 1][e]

[msg MSG_MISSING_PERSON_MAIKO [Maiko]]
[uf 0 5 65278][uf 2 1]Ahh... Nngh...[n][uf 1 1][e]

