[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 1 0 0]Good morning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 8 0 25 25]Oh, and, um... Happy New Year.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Yeah. Let's make it a good one.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Happy New Year.[e]
[uf 0 5 65278][uf 2 1]Let's make the most of it.[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Happy New Year to you, too, Koro.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Arf![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh man... I totally overslept. Why'd I stay up all night watchin' that stupid movie...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 3 0 25 25]It was about zombies in Italy, or somethin'... Anyone else catch it?[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Why would I watch something like that?[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Um, is anyone gonna visit the shrine?[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]I already stop by enough shrines on my jogs. I'd say I'm covered.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Yeah, I'll pass. I don't wanna deal with the New Year's traffic.[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 12 0 0]Oh, that's too bad. Yukari-san and the others are already there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Apparently, Mitsuru-san got kimonos for all of them.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Kimonos, huh?[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 6 65535 0 0][uf 3 1 1 0 0 15 0 0]Uh, I'm gonna run to the store...[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]Hold it.[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Huh?[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]You're going to the shrine? I thought you didn't want to go through the trouble.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 6 65535 0 0][uf 3 1 1 0 0 19 0 0]N-No, I'm not... I'm just goin' for a walk...[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]Uh-huh...[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]Well, I don't have anything better to do, so I'll tag along.[n][uf 1 1][e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Oh, I'll go too![n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Count me in, too.[e]
[uf 0 5 65278][uf 2 1]See you.[e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Look at that, turns out we all wanna go after all.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Well, everyone else is goin', so you're not gettin' out of it.[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 25 0 0]...Where is it?[n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 26 0 0]Oh, I have directions.[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Sweet![n][uf 1 1][e]

