[msg TRL_000_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Sometimes [uf 0 1 2]Monad doors[uf 0 1 27] will appear in the Abyss of Time. Defeating the special enemy in one will trigger a special Shuffle Time, where [uf 0 1 2]Major Arcana cards appear more frequently[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 22]From left to right, the three doors increase in both difficulty and value of items rewarded. Consecutive battles will sometimes await you, so be prepared before entering a door.[n][uf 1 1][e]

[msg TRL_002_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 23]Defeating these enemies will also reveal [uf 0 1 2]the layout of the current and next floor[uf 0 1 27] upon leaving. Once this is done, the power within the doors will be released, sealing them shut.[n][uf 1 1][e]

[msg TRL_003_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The Monad door is an unstable contraption. When one appears on a floor, the door will lose power and become inaccessible if you move to another floor, even if you return to it later.[n][uf 1 1][e]

