[msg TRL_000_0_0 [Monad Chambers]]
[uf 0 5 65278][uf 2 1][uf 4 8 43][uf 0 1 2]Formidable Shadows[uf 0 1 27] reside here, and beyond them lie treasure chests holding [uf 0 1 2]valuable items[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Monad Chambers]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can [uf 0 1 2]face these challenges as often as you like[uf 0 1 27], so if you feel outmatched, consider revisiting after training some.[n][uf 1 1][e]

[msg TRL_002_0_0 [Monad Chambers]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You may also find something in the Monad Chambers that you can't find anywhere else. You'll have to tread the Chambers themselves to figure out what.[n][uf 1 1][e]

