[msg TRL_000_0_0 [Skill Card Duplication at the Vermillion Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 47]By accessing the vermillion clock in the Desert of Doors, you can choose to make a copy of one of your existing Skill Cards.[n][uf 1 1][e]

[msg TRL_001_0_0 [Skill Card Duplication at the Vermillion Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Skill Cards can be duplicated at any time, but the process requires Twilight Fragments. Be sure to make a habit of collecting them for when a need arises.[n][uf 1 1][e]

