[msg TRL_000_0_0 [Expanded Desert of Doors Travel]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]After defeating a Shadow that guards a given floor, a new pathway to the Desert of Doors will be opened there.[n][uf 1 1][e]

[msg TRL_001_0_0 [Expanded Desert of Doors Travel]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]This allows you to use the Desert of Doors to travel between completed areas at your leisure.[n][uf 1 1][e]

