[msg TRL_000_0_0 [Fuuka's Skills: Sylphid Aura]]
[uf 0 5 65278][uf 2 1][uf 4 8 28]Sylphid Aura is a support skill that [uf 0 1 2]automatically raises the Defense and Accuracy/Evasion[uf 0 1 27] of the [uf 0 1 2]whole party[uf 0 1 27] at the beginning of combat.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fuuka's Skills: Sylphid Aura]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The effect duration [uf 0 1 2]lasts between floors[uf 0 1 27], but will be canceled [uf 0 1 2]after entering battle[uf 0 1 27]. It is best utilized before decisive battles and key encounters.[n][uf 1 1][e]

