[msg TRL_000_0_0 [Auto-Targeting]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When Aigis fires one of her weapons, an enemy a certain distance in front of her will be automatically targeted.[n][uf 1 1][e]

[msg TRL_001_0_0 [Auto-Targeting]]
[uf 0 5 65278][uf 2 1][uf 4 8 44]An auto-targeted unit will be indicated with a target mark. You will have greater precision when firing at these enemies.[n][uf 1 1][e]

