[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 1 0 0]All right, we should be safe now—[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 50 0 0][uf 3 1 1 0 0 2 0 0]Takeba, do you read me!?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Y-Yes! I hear you![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 50 0 0][uf 3 1 1 0 0 4 0 0]Be careful! There appears to be more than one enemy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 50 0 0][uf 3 1 1 0 0 5 0 0]The primary one's lurking somewhere nearby![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 6 0 0]What!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Wh-Whoa! Let's pull back![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 8 0 0]What are we going to do? It's at the front door...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 9 0 0]Should we go upstairs for now?[n][uf 1 1][e]

