[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono seems to have stepped out...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15021 0 0]Ugh, did Ms. Toriumi go home already? The teacher's log is a mess...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]If she's such an expert on composition, what's with this syntax?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]And these weird symbols to the side? Is this... some kind of face?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]Won't she ever grow up...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15022 0 0]...[uf 4 1]? Why didn't you speak up sooner?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]Don't think that people will lead you around by the hand once you're out in the real world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]...So, what do you want?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]Ms. Toriumi seems to have left her share of unfinished work behind.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15021 0 0]Having a teacher like her in charge of your class must be a severe impediment to your pursuit of education.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]You'll never guess what she said during the teacher's conference the other day...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]"I feel as if what I think you were saying isn't wrong."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]What's with that? I can't make heads or tails of syntax that tortured![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0]Because of teachers like her... I can hardly blame you youngsters for your grammar, can I?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15014 0 0]Now listen to me carefully. To begin with, proper grammar is...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I was lectured on proper[n]sentence structures...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono doesn't seem to be returning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to give up for today.[n][uf 1 1][e]

