[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I've got a text message...[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I've got a few messages...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I should start getting ready to head out.[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I should start getting ready to head out.[n][uf 1 1][e]

