[msg MSG_RESCUE_NPC_DONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Don't worry, we'll keep them safe at the entrance until you decide to leave for the night.[n][uf 1 1][e]

[msg MSG_RESCUE_NPC_DONE2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]If you find any more missing people, please rescue them as quickly as you can.[n][uf 1 1][e]

[msg MSG_RESCUE_CAT_DONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Don't worry, we'll keep the kitty safe at the entrance until you decide to leave for the night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]So you can keep exploring, if you want.[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]I tried searching again, but I don't sense any more people inside.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]I think we rescued everyone that had wandered in here. Thank goodness...[n][uf 1 1][e]

