[msg MSG_000_0_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]We go to the same school, right? One look at your uniform's all I need to know![n][uf 1 1][e]

[msg MSG_000_3_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Umm, I'm kind of embarrassed to ask you this right off the bat, but...[n][uf 1 1][e]

[msg MSG_000_5_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Would you mind not standing so close to me!? You're too thin and too cool![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]If people start thinking we're best friends or something, I'm gonna end up as "the uncool one"![n][uf 1 1][e]

[msg MSG_001_0_0 [Bitter-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1001]There you are. I thought your voice sounded familiar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1001]You know what I'm here for. Now hand it over.[n][uf 1 1][e]

[msg MSG_002_0_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Wh-Whoa! Not you![n][uf 1 1][e]

[msg MSG_002_3_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]H-Help! E-Emergency![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]H-Hey! Y-You! Call the fire truck— Er, I mean the, uh... Uh...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Call the police?[e]
[uf 0 5 65278][uf 2 1]Sorry, what?[e]

[msg MSG_004_0_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Yes! Right! Good thinking![n][uf 1 1][e]

[msg MSG_005_0_0 [Chubby Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Whoa, hey... I thought we were buddies, weren't we? C'mon, pal![n][uf 1 1][e]

[msg MSG_006_0_0 [Bitter-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1001]Quit making a scene, all right? People are looking at me funny.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1001]I've got some business to take care of now, but you... You're Nozomi Suemitsu-kun, aren't you? I did my homework, see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1001]You know I'm not letting you off that easy, right? I suggest you reconsider things.[n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]That was horrifying! My poor heart! I think it dropped into my coin purse for a minute there![n][uf 1 1][e]

[msg MSG_007_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]My name is Nozomi Suemitsu![n][uf 1 1][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]By the way! May I just say that you have a wonderfully big heart for someone so slim?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Suemitsu gave me a hearty thanks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I've become acquainted with[n]Nozomi Suemitsu, the Gourmet King.[n][uf 1 1][e]

[msg MSG_010_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Whew, all that drama made me hungry. My stomach is definitely not amused.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]You wanna tag along, friend? Shall I treat you to the finest dining? If so, you've come to the right place...[n][uf 1 1][e]

[msg MSG_011_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]For I am the king—the Gourmet King![n][uf 1 1][e]

[msg MSG_011_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]That's right! Gourmet King 2009! ...Or was it 2010? Eh, whatever.[n][uf 1 1][e]

[msg MSG_011_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]And as the king, I know all the kingliest places for... Ugh... Urrgh!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 5 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Wha—!? My... My tummy...! It's in horrible pain! I think it's an... e-emergency...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 5 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Sorry, but I'll treat you... another time![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It started getting dark, so I went home.[n][uf 1 1][e]

