[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Any luck?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 2 0 0]I only sense a faint presence. It seems so close, but... I can't reach it...![n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]All right, we can split up and search for it. There's no time to lose, so let's hurry![n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 4 0 0]Wait![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 5 0 0]Please, I can do it! This is what I'm here for![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 0 0 0 6 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 7 0 0]Feel the movement of the earth through your fingertips...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 8 0 0]Hear the answer of the wind flow through your hair...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 9 0 0]Taste the knowledge of the water on your lips...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 10 0 0]Tell me, Lucia... What shrouds me from the truth?[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Hey, is she okay...?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Don't break her concentration.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 13 0 0]This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 6 3 25 25]Some kind of... web... beneath us?[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]A web...? Perhaps it's related to the old power cables underground.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Back when the island was still being developed, this is where the main power station was located.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Underground cables...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Yes, a large number of power cables remain underground in a sprawling network, much like a web.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]So that's what's interfering with her ability?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 20 0 0]Thank you, Aigis. I've figured it out now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 6 2 25 25]It's not that the cables are interfering...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 0 22 0 0]...The cables themselves have been possessed by the Shadow![n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 23 0 0]They what...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 24 0 0]So, everything under our feet is part of the Shadow!?[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]No wonder you couldn't pinpoint it. It's covering this entire area.[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 1 0 0 26 0 0]H-How are we supposed to beat something like that!?[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Tch... Hiding underground, huh...[n][uf 1 1][e]

