[msg MSG_000_0_0 [Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 619]Oh, it's the Dream Team. Sheesh, you guys are always together. What's up?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 619]Hold on... You're not really going to Port Island Station right now, are you!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 619]Haven't you heard the reports!? It's super unsafe![n][uf 1 1][e]

[msg MSG_001_0_0 [Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 619]My friend's friend's classmate was found knocked out in the back alley.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 619]And your uniforms would make you stand out... You could get into some serious trouble there.[n][uf 1 1][e]

