[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I was shown to a spacious room where[n]I could enjoy solo karaoke to the fullest.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I sang many songs with all my heart...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Someone outside the room was looking[n]at me, but I sang loudly without a care...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]A waiter came into the room, but[n]I continued to sing wholeheartedly...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 2 1 1 0] has gone up[n]from not caring what other people think...[n][uf 1 1][e]

