[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]That's one magnificent melon, ain't she? It's the highlight of my day![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Sooo, I've been thinkin' of throwin' a watermelon-splitting party.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]We haven't really done anything summery since vacation started, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]'Specially Amada. He always looks so bored when I see him in the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 6 25 25]And man, that kills me to see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]It'd be a real shame if he didn't have a single entry in his summer picture diary.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]That's so thoughtful of you.[e]
[uf 0 5 65278][uf 2 1]You feel bad for him?[e]
[uf 0 5 65278][uf 2 1]What are you really getting at?[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Heh, I can already see the look on his face![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]He'll be like, "Junpei-san, you're super cool AND you're super nice!"[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]It's just one of those things you either pick up on or you don't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Amada's eyes tell it all, at least to me. That lonely stare...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Honest to god, I just want the kid to have a fun summer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Look into my eyes—would they lie to you?[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Oh, I mean, don't you know?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]They say women can't resist a guy with a soft spot for kids.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]And you know what that means—I'm gonna need your help![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]It's a win-win situation, don't ya think? Anywho... Oh boy...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I think my arms are gonna fall off...[n][uf 1 1][e]

