[msg MND_HIT_VENDINGMACHINE_0]
[uf 0 5 65278][uf 2 1]Looks like the power's out...[n][uf 1 1][e]

[msg MND_HIT_ELEVATOR_01]
[uf 0 5 65278][uf 2 1]None of the buttons are lit up...[n]Guess the elevator's out of order.[n][uf 1 1][e]

[msg MND_HIT_WORKFENCE_01]
[uf 0 5 65278][uf 2 1]Seems like the place is under construction.[n]Probably best if I don't trespass...[n][uf 1 1][e]

[msg MND_HIT_WORKSPACE_01]
[uf 0 5 65278][uf 2 1]Looks like the entire station is[n]undergoing construction.[n][uf 1 1][e]

[msg MND_HIT_WORKSPACE_02]
[uf 0 5 65278][uf 2 1]Better keep my distance...[n]Looks a little dangerous.[n][uf 1 1][e]

[msg MND_HIT_TELEPHONE_01]
[uf 0 5 65278][uf 2 1]The light in the phone booth is off.[n]Guess the power's out...[n][uf 1 1][e]

[msg MND_HIT_INFOBOARD_01]
[uf 0 5 65278][uf 2 1]The dorm doesn't seem to be on the map...[n][uf 1 1][e]

[msg MND_HIT_ESCALATOR_01]
[uf 0 5 65278][uf 2 1]It's out of order...[n][uf 1 1][e]

[msg MND_OUT_STOP_EAST]
[uf 0 5 65278][uf 2 1]I think the dorm's in the other direction...[n][uf 1 1][e]

[msg MND_OUT_STOP_STAIR]
[uf 0 5 65278][uf 2 1]I should probably head to the dorm...[n][uf 1 1][e]

