[msg MND_DUNGEON_CLEARED]
[uf 0 5 65278][uf 2 1]We've already finished exploring this area...[n][uf 1 1][e]

[sel SEL_ENTER top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER2 top]
[uf 0 5 65278][uf 2 1]Go to deepest explored floor[e]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER3 top]
[uf 0 5 65278][uf 2 1]Enter B8[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER4 top]
[uf 0 5 65278][uf 2 1]Go to deepest explored floor[e]
[uf 0 5 65278][uf 2 1]Enter B8[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_EXIT_FUKA_OK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Do you want to open and go through the door?[n][uf 1 1][e]

[msg MSG_EXIT_FUKA_NAVI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Got it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I'll find a safe route for you to traverse, so just follow my directions.[n][uf 1 1][e]

[msg MND_DOOR_CLOSED]
[uf 0 5 65278][uf 2 1]The door is tightly sealed.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 3 0 65535 5099 0 0]That dark figure from before... It went in here, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0]You don't think that was—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5058 0 0]Ah, sorry. I didn't mean to get carried away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]This appears to be the first door. I wonder what we'll find inside...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]Well, if we don't go through it, then we can't do anything about the current situation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0][uf 3 1 3 0 65535 5028 0 0]I suppose we have no choice but to enter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0]Are you ready? I'll do my best to support you![n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5062 0 0]This door... I wonder where it leads.[n][uf 1 1][e]

