[sel SEL_RETURN top]
[uf 0 5 65278][uf 2 1]Head back[e]
[uf 0 5 65278][uf 2 1]Continue exploring[e]

[sel SEL_TUTORIAL top]
[uf 0 5 65278][uf 2 1]Head back[e]
[uf 0 5 65278][uf 2 1]Continue exploring[e]

[msg MND_TUTORIAL_ESCAPE_POIN]
[uf 0 5 65278][uf 2 1]Should I return to the entrance?[n][uf 1 1][e]

[msg MSG_ESCAPE_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]Are you ready to return to the entrance?[n][uf 1 1][e]

[msg MSG_ESCAPE_MITSURU_GO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Roger that.[n][uf 1 1][e]

[msg MSG_ESCAPE_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Would you like to return to the Desert of Doors?[n][uf 1 1][e]

[msg MSG_ESCAPE_FUKA_GO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Okay. I'll be waiting for you.[n][uf 1 1][e]

[msg MSG_ESCAPE_FUKA_Monad [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Sorry to cut your exploration short, but please come back for now.[n][uf 1 1][e]

[sel SEL_TUTORIAL_Monad top]
[uf 0 5 65278][uf 2 1]Got it.[e]
[uf 0 5 65278][uf 2 1]In a bit.[e]

[msg FUKA_STOP_RETURN_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 3 0 65535 5073 0 0]Wait! There must be something on that floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]The rest of us were just about to head over there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]Do you want to return to the Desert of Doors without taking a look around?[n][uf 1 1][e]

