[msg MSG_TUTO_BTL01_DISCOVERE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 3 0 65535 5073 0 0]There's a Shadow directly ahead of you! Though it doesn't seem to have noticed you yet.[n][uf 1 1][e]

[msg MSG_TUTO_BTL01_DISCOVERE_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Aigis, since you're equipped with firearms, I bet you could shoot them from afar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]If there's enough distance between you and the Shadow, then I don't think they'll notice you. How about giving it a try?[n][uf 1 1][e]

[msg MSG_TUTO_BTL02_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20508 0 0]Another Shadow up ahead. Let's get you more accustomed to combat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 1 0 1 20509 0 0]The battle's about to begin! Everyone, stay focused![n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 81 0 0][uf 3 1 1 0 1 20517 0 0]The heck? Hey, I found some kinda boxy-lookin' thing.[n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20518 0 0]Yes, boxes like those seem to be scattered all throughout Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20519 0 0]Sometimes they contain useful items for battle. Seek them out as often as you can.[n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20520 0 0]Oh sweet, so they're basically like treasure chests![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20521 0 0]Hell yeah! Let's bust it open and see what's inside![n][uf 1 1][e]

[msg MSG_NOT_GET_TBOX [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 81 0 0][uf 3 1 1 0 1 20522 0 0]Hey, c'mon! Aren't you dyin' to know what's inside!?[n][uf 1 1][e]

[msg MSG_TUTO_BTL03_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20524 0 0]Shadow detected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20525 0 0]Looks like they haven't noticed you yet. Now's your chance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20526 0 0]Try sneaking up on them from behind! Make sure you stay out of their field of vision.[n][uf 1 1][e]

[msg MSG_TUTO_BTL03_RUN_AWAY_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 1 20527 0 0]Hold on, Aigis![n][uf 1 1][e]

[msg MSG_TUTO_BTL03_RUN_AWAY__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 1 20528 0 0]The enemy will notice you if you get too close. Try pulling back and shooting from afar.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20536 0 0]I detect another Shadow up ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20537 0 0]Take advantage of what you just learned. Try not to alert the enemy as you move.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_RUN_AWAY_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4561 0 0]The goal today is to gain experience in battle! Running away is not an option.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_RUN_AWAY__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20540 0 0]I hope you're not tired yet because it's time to step it up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20541 0 0]Now approach the enemy from behind, carefully.[n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20548 0 0]Hey, I found some stairs![n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 81 0 0][uf 3 1 1 0 1 20549 0 0]Wait! We're looking for the teleporter, aren't we?[n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20550 0 0]Exactly what Takeba said. Please prioritize getting back safely for now.[n][uf 1 1][e]

[msg MSG_NOT_GET_MEDAL_TBOX [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20557 0 0]Wait, don't waste this chance. Try opening that box.[n][uf 1 1][e]

[msg MSG_MEDAL_INFO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4567 0 0]That reaction... Do you have a [uf 0 1 39]Twilight Fragment[uf 0 1 27] with you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Try holding it up to the treasure chest.[n][uf 1 1][e]

[msg MSG_DISCOVERED_RETDEV_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20558 0 0]Looks like you found a teleporter.[n][uf 1 1][e]

[msg MSG_DISCOVERED_RETDEV_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20559 0 0]Now use it to return to the entrance.[n][uf 1 1][e]

