[msg MND_DUNGEON_CLEARED]
[uf 0 5 65278][uf 2 1]We've already finished exploring this area...[n][uf 1 1][e]

[sel SEL_ENTER top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER2 top]
[uf 0 5 65278][uf 2 1]Go to deepest explored floor[e]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER3 top]
[uf 0 5 65278][uf 2 1]Enter B8[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER4 top]
[uf 0 5 65278][uf 2 1]Go to deepest explored floor[e]
[uf 0 5 65278][uf 2 1]Enter B8[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER5 top]
[uf 0 5 65278][uf 2 1]Enter B17[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_ENTER6 top]
[uf 0 5 65278][uf 2 1]Go to deepest explored floor[e]
[uf 0 5 65278][uf 2 1]Enter B17[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_EXIT_FUKA_OK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_EXIT_FUKA_NAVI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Got it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I'll find a safe route for you to traverse, so just follow my directions.[n][uf 1 1][e]

[msg MSG_EXIT_FUKA_OK_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]All right. Then let's meet in the usual place.[n][uf 1 1][e]

[msg MSG_NO_EXIT_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Please let me know when you're ready.[n][uf 1 1][e]

[msg MND_DOOR_CLOSED]
[uf 0 5 65278][uf 2 1]The door is tightly sealed...[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5003 0 0]This is the fifth door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Are you ready?[n][uf 1 1][e]

