[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Metis asked to meet with me,[n]but I don't see her anywhere...[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Sisteeerrr![n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Apologies for the wait— Oh! I mean...[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Sorry, did I keep you waiting?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, you did.[e]
[uf 0 5 65278][uf 2 1]I just got here.[e]
[uf 0 5 65278][uf 2 1]What did you need?[e]

[msg MSG_005_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh... I'm so sorry. I should've known better—that was rude of me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]I was under the impression that I was observing proper etiquette... I must have been mistaken.[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Ooh, you actually said it! According to proper etiquette, that's the correct response![n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Huh? That's not in the script. Did I not follow proper etiquette?[n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 8 0 0]I read a book at the dorm that illustrated how two people in uniform rendezvous.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Is it not custom for those of similar age to don matching clothes and do all sorts of activities together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 10 0 0]I thought it'd be a shame should these outfits only be associated with exploration and combat...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 11 0 0]So I was hoping the two of us could make some more pleasant memories in them while we still have the chance.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]That's a wonderful idea.[e]
[uf 0 5 65278][uf 2 1]Should I have worn mine?[e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 12 0 0]You really think so? Well, in that case...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 13 0 0]You should wear your uniform, too! No, you must! Please![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Faced with Metis's enthusiasm,[n]I returned to the dorm to change[n]into my school uniform...[n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Y-You really don't mind!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 15 0 0]I mean, yes! Please do! I'll wait right here while you go get changed![n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Metis was vibrating with excitement[n]as she saw me off to the dorm...[n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 11 52 65535 0 0][uf 3 1 1 0 0 16 0 0]...Is this what true bliss feels like?[n][uf 1 1][e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Now that we're finally matching, I can't afford to squander even a single second of our time together![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 18 0 0]We must hurry and seize the opportunity to make new memories![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]Please take the lead, Sister. What kinds of things are supposed to be done in school uniforms?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Studying to gain knowledge.[e]
[uf 0 5 65278][uf 2 1]Drinking coffee to refine charisma.[e]
[uf 0 5 65278][uf 2 1]Singing karaoke to build tenacity.[e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]I see—you are a student, after all. So the real thrill of wearing a uniform isn't from going out and having fun with friends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 1 25 25]I learned something new today! Okay then, let's head back to the dorm and study there![n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]I decided to head back[n]home with Metis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]In the end, all we did was talk[n]instead of studying, but Metis[n]still seemed very satisfied...[n][uf 1 1][e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 22 0 0]So students drink coffee... to refine themselves? Does it make their skin smoother or something?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]I also want to polish and refine myself for your sake, so I hope drinking coffee works for me, too![n][uf 1 1][e]

[msg MSG_021_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 24 0 0]I wasn't sure what to make of karaoke, but... If it requires tenacity, doesn't that mean it's dangerous?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]Is the mundane world a more hazardous place than I had originally thought...? What a surprising discovery.[n][uf 1 1][e]

[msg MSG_022_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 26 0 0]Well then, no time to waste! Let's get going.[n][uf 1 1][e]

[msg MSG_023_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 11 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Just me and my sister—in our school uniforms![n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]We spent time at Paulownia Mall[n]until Metis was fully satisfied...[n][uf 1 1][e]

