[msg MSG_000_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 1 0 0]Hello? This is Elizabeth speaking.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 2 0 0]I would appreciate it if you could come to the Velvet Room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 3 0 0]There is a matter I would like to discuss with you.[n][uf 1 1][e]

[msg MSG_001_2_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 4 0 0]Goodbye, now.[n][uf 1 1][e]

[msg MSG_001_5_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 5 0 0]There is an alternate entrance you may use located in Paulownia Mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 6 0 0]You need only seek the door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 7 0 0]Well then... I shall be anxiously awaiting your arrival.[n][uf 1 1][e]

[msg MND_002_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]Elizabeth is waiting for[n]me at the Velvet Room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder what she wants to talk about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I guess I should head to Paulownia Mall.[n][uf 1 1][e]

