[msg TRL_000_0_0 [Fusion Spell]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Fusion Spell is a special Theurgy unique to [uf 4 2] that comes from obtaining certain Personas.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fusion Spell]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Fusion Spells can be acquired by registering certain Personas in the Compendium.[n][uf 1 1][e]

[msg TRL_002_0_0 [Fusion Spell]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Once these conditions are met in the Velvet Room, Elizabeth will inform you of a new Fusion Spell you can use.[n][uf 1 1][e]

