[msg TRL_000_0_0 [Full Analysis]]
[uf 0 5 65278][uf 2 1][uf 4 8 25]Press [uf 1 3 109] while on the Analyze screen to use Fuuka's skill, [uf 0 1 2]Full Analysis[uf 0 1 27]. Doing so will deplete her SP.[n][uf 1 1][e]

[msg TRL_001_0_0 [Full Analysis]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Carrying out a Full Analysis will reveal the enemy's weakness. Use it to battle more effectively.[n][uf 1 1][e]

[msg TRL_002_0_0 [Full Analysis]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Note that a Full Analysis can only be done [uf 0 1 2]after everyone—both allies and enemies—has ended their turn in the first round[uf 0 1 27].[n][uf 1 1][e]

