[msg TRL_000_0_0 [Shuffle Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]After a battle is won, [uf 0 1 2]Shuffle Time[uf 0 1 27] may occur.[n][uf 1 1][e]

[msg TRL_001_0_0 [Shuffle Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]During Shuffle Time, different types of cards formed by the possibilities within your soul will appear. You can choose one of these cards.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuffle Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 11]Each type of card has a different effect.[n][uf 0 1 2]Persona[uf 0 1 27]: Acquire a new Persona.[n][uf 1 1][e]

[msg MSG_003_0_0 [Shuffle Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 12][uf 0 1 2]Wand[uf 0 1 27]: Increases experience.[n][uf 0 1 2]Cup[uf 0 1 27]: Activates battle support effects.[n][uf 0 1 2]Sword[uf 0 1 27]: Obtain a Skill Card.[n][uf 0 1 2]Coin[uf 0 1 27]: Obtain money.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuffle Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The more 1 Mores you get in battle, the higher the chance Shuffle Time will occur. If you end a battle with an All-Out Attack, Shuffle Time will always occur.[n][uf 1 1][e]

