[msg TRL_000_0_0 [Analyze]]
[uf 0 5 65278][uf 2 1][uf 4 8 6]Pressing [uf 1 3 114] will allow you to view the affinities of a selected enemy.[n][uf 1 1][e]

[msg TRL_001_0_0 [Analyze]]
[uf 0 5 65278][uf 2 1][uf 4 8 7]The different affinities are [uf 0 1 2]Slash[uf 0 1 27], [uf 0 1 2]Strike[uf 0 1 27], [uf 0 1 2]Pierce[uf 0 1 27], [uf 0 1 2]Fire[uf 0 1 27], [uf 0 1 2]Ice[uf 0 1 27], [uf 0 1 2]Electricity[uf 0 1 27], [uf 0 1 2]Wind[uf 0 1 27], [uf 0 1 2]Light[uf 0 1 27], and [uf 0 1 2]Dark[uf 0 1 27]. The amount of damage inflicted depends on the enemy's affinity.[n][uf 1 1][e]

[msg TRL_002_0_0 [Analyze]]
[uf 0 5 65278][uf 2 1][uf 4 8 8][uf 0 1 2]Unknown[uf 0 1 27]: Affinity has not been used against an enemy yet.[n][uf 0 1 2]Weak[uf 0 1 27]: More damage dealt and knock down possible.[n][uf 1 1][e]

[msg TRL_003_0_0 [Analyze]]
[uf 0 5 65278][uf 2 1][uf 4 8 9][uf 0 1 2]Resist[uf 0 1 27]: Damage is halved.[n][uf 0 1 2]Null[uf 0 1 27]: No damage taken.[n][uf 1 1][e]

[msg TRL_004_0_0 [Analyze]]
[uf 0 5 65278][uf 2 1][uf 4 8 10][uf 0 1 2]Repel[uf 0 1 27]: Damage is deflected and inflicted on the one who initiated it.[n][uf 0 1 2]Drain[uf 0 1 27]: Damage is absorbed by the target and heals them instead.[n][uf 1 1][e]

