[msg TRL_000_0_0 [Assist]]
[uf 0 5 65278][uf 2 1][uf 4 8 16]During battle, press [uf 1 3 117] for an [uf 0 1 2]Assist[uf 0 1 27]. The attack most effective against an enemy will automatically be selected.[n][uf 1 1][e]

[msg TRL_001_0_0 [Assist]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]It works as a shortcut to select one of your attacks that targets an enemy's weakness. Take advantage of this shortcut whenever an enemy's weakness is known.[n][uf 1 1][e]

