[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, it's you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 114 3 25 25]Hey, can ya help me out, kid...? I don't feel so good...[n][uf 1 1][e]

[msg MSG_000_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Dammit... I can't believe I let this happen... How pathetic...[n][uf 1 1][e]

[msg MSG_000_7_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ugh... I'm in bad shape...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Are you okay?[e]
[uf 0 5 65278][uf 2 1]You should go home.[e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I just told you I'm in bad shape, didn't I!? Don't piss me off, kid. It's making my headache worse...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I'm not gonna waste my breath repeating myself.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 17 15 114]Yeah, you're right, kid... I should go home and sleep...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]But, even if I go home...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I completely forgot I have a memorial service to conduct... Reciting the Heart Sutra with a hangover is gonna be rough...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Back in the day, all I needed was a cold shower, and I'd be fine no matter how much I drank. I guess I'm gettin' old, huh...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]It's always in times like these... ah... when it's hardest to be alone...[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]You live by yourself?[e]
[uf 0 5 65278][uf 2 1]Do you have any coworkers?[e]

[msg MSG_009_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]You act like you don't care about others, kid, but you sure can be nosy when you want to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I got all these gaudy rings on now, but I used to wear a wedding ring, ya know.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 17 5 114]Hm? You asking if there are other monks at my temple?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]My temple's small, and I don't depend on nobody but myself. I'm the only one there.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]If ya think about it, it's better to be alone... Less stress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]You don't hafta wait for someone else to get outta the bathroom when ya need to go. My son took forever in there.[n][uf 1 1][e]

[msg MSG_011_3_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]...Yeah, livin' alone is the way to achieve peace and serenity![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...Everything we see has form. No form has permanence. It's all in constant motion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Form has no self... Its true face is that of "emptiness."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]And yet, form is emptiness, and emptiness is form. No two things in this world are the same.[n][uf 1 1][e]

[msg MSG_011_7_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Well, to put it simply...[n][uf 1 1][e]

[msg MSG_011_8_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]No matter how hard you try to live your life right, someone else can always mess it up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Because form is emptiness, and emptiness is form...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 114 1 25 25]Maybe getting involved with you messed up my life a bit, too. Heheh...[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Contrary to his words, I can sense[n]feelings of affection from Mutatsu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I'm gonna go home, kid... My head's killin' me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Oh, yeah, about the memorial service... It was a seventh-day memorial.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Kid was only nineteen... A random murder victim. What a harsh world we live in...[n][uf 1 1][e]

[msg MSG_014_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]You be careful on your way home too, kid.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I said goodbye to Mutatsu[n]and went back to the dorm.[n][uf 1 1][e]

