[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...Ah, here it is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]In this scene, the main character says, "That ass better not crack under pressure."[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Usually, people's asses are already cracked. Yours is as well, right, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Obviously.[e]
[uf 0 5 65278][uf 2 1]That's a secret.[e]
[uf 0 5 65278][uf 2 1]Who knows...?[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Good, that is a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]If that is the case, then this must be referring to a different "ass"...[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]...I understand, but please tell me someday.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]For now, I will put the question on hold.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I can always verify this by searching my database...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]However, I suspect it will currently be faster to investigate manually.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 7 0 25 25]Currently, this is the only section that I am unclear on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]But I suspect that if I continue reading, I will encounter even more confusing phrases.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]If you don't mind, could I ask you to read with me until the end?[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 22 1 7]Thank you very much, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]With your help, I've been able to update my records with new information.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Apparently, this book has a sequel.[n][uf 1 1][e]

[msg MSG_009_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]If it is possible, I would like to read with you again sometime.[n][uf 1 1][e]

[msg MND_10_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]It's gotten rather late.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]We should head back to our rooms... Or should I say, our turfs.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...Ah, here it is![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]In this scene, the main character says, "That ass better not crack under pressure."[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]But, humans already have cracked asses... Isn't that how they're born?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, that's true.[e]
[uf 0 5 65278][uf 2 1]Depends on the person.[e]
[uf 0 5 65278][uf 2 1]No idea.[e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 7 1 25 25]Oh, good. That's what I thought...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]If that is the case, then this must be referring to a different "ass"...[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 21 7 11]Y-You think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I was certain the "ass crack" was a universal feature... I need to study more on human anatomy.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]...Maybe it depends on the individual person?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm curious, but at the same time, I feel like I shouldn't delve too deeply...[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 7 0 25 25]So far, this is the only section that I'm unclear on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]But I think if I keep reading, I'm going to find other points that are confusing.[n][uf 1 1][e]

[msg MSG_19_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 7 1 25 25]If you don't mind... could I ask you to keep reading with me until the end?[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 5 13 22 1 7]Thank you very much, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I have a much better understanding now, as a result of your help.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Oh... It looks like this book has a sequel.[n][uf 1 1][e]

[msg MSG_021_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 7 1 25 25]If you don't mind, could we read together again sometime?[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]It's already gotten late. We should both head back to our turf...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Excuse me. I meant we should go back to our rooms. Good night.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]That reminds me. I was reading this book during class once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]One of our classmates saw and said to me, "Wow, I'm surprised. So, you're the type to talk with your fists."[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]What exactly do I look like to everyone else?[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]A normal high school student.[e]
[uf 0 5 65278][uf 2 1]Don't worry about that too much.[e]
[uf 0 5 65278][uf 2 1]A cute girl.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]That must mean that I don't appear to be strong in other people's eyes.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]No, it's important that I consider this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]He was surprised. That can only mean one thing...[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]"Cute"...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]From what I understand, that term is used to describe small animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Are you saying that I'm also being placed into that category?[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 7 0 25 25]I am an anti-Shadow weapon, but I don't seem to be regarded as such...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]I must correct this problem at once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]If it is not addressed, it could negatively impact my ability to carry out my duties.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Once I finish reading, I will start thinking of a solution.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]During combat, the mental states of both sides play a significant role in the outcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]I want my presence to strike fear in the hearts of my enemies, but galvanize my allies, as well.[n][uf 1 1][e]

[msg MSG_032_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]What can I do to convey that kind of impression?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Ideally, it would be something to encourage people to depend on me...[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Maybe I can find some tips in this book...[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0][uf 5 13 22 1 7]I think this is enough reading for now. We should return to our rooms.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]That reminds me. I was reading this book during class once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]And one of our classmates said to me, "Wow, I'm surprised. So you're the type to talk with your fists."[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]What exactly do I look like to everyone else?[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]A normal high school student.[e]
[uf 0 5 65278][uf 2 1]Don't worry about that too much.[e]
[uf 0 5 65278][uf 2 1]A cute girl.[e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]That must mean that I don't look strong in other people's eyes.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 62 0 0][uf 4 23 0 7 1 25 25]...Thank you. I know you're just being considerate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 63 0 0][uf 4 23 0 7 3 25 25]But still, I can't help but feel bothered by it...[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]"Cute"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]I know this is supposed to be a compliment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 66 0 0][uf 4 23 0 7 3 25 25]But if that's how they see me, it can only mean one thing...[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 67 0 0][uf 4 23 0 7 3 25 25]I'm an anti-Shadow weapon, but most people don't see me as one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0][uf 4 23 0 7 0 25 25]Isn't this a critical issue?[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]...Once I finish reading, I'll need to think of a solution.[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 70 0 0]During combat, the mental states of both sides play a significant role in the outcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 71 0 0]I want to be able to intimidate my enemies, but also encourage my teammates.[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 72 0 0]What can I do to give everyone that kind of impression?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 73 0 0]Ideally, it would be something that makes me appear reliable in battle...[n][uf 1 1][e]

[msg MSG_135_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 74 0 0][uf 4 23 0 7 3 25 25]Maybe I can find some tips in this book...[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 75 0 0][uf 4 23 0 7 1 25 25][uf 5 13 22 1 7]I think that's enough for today. Good night.[n][uf 1 1][e]

