[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 1 0 0]It appears they are growing well. Hip hip hooray, as they say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 2 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 3 0 0]I believe this is "mission complete." Well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]It's thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 4 0 0]I tried to do everything in my power. I'm glad I was of service.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 5 0 0]The ladybug put in a lot of work as well. We thank you for your service![n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0]That's true. We must be prepared for surprise attacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0]That reminds me, Junpei-san came here the other day trying to get some free samples, but I quickly gunned him down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]If he comes back, rest assured, he will be shot on sight.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 9 0 0]But, it's thanks to the ladybug that the plants didn't suffer any significant damage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 10 0 0]I will thank it for its service in your place, [uf 4 2]-san![n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 11 0 0]I've realized something, tending these plants alongside you.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 12 0 0]I've made many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 13 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 14 0 0]That goes for the plants, and the pests, and the ladybug too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 15 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 16 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 17 0 0]I will do my best to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 18 0 0]That is my new goal from now on.[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]I don't get it.[e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 22 1 7]I am impressed, [uf 4 2]-san. I hadn't expected a competition here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 20 0 0]Hearing that, my motivation is fully charged! ...As they say.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 5 13 22 1 7]It's difficult to explain, but I will do my best in everyday life, as well as in battle against the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 22 0 0]All for one and one for all! Let's go team! ...As they say.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 23 0 0]Naturally, I will still continue to look after them at full throttle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 24 0 0]Let's get started right away.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 25 0 0]Once again, our mission has concluded without incident today. Let's head back now.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 26 0 0]It looks like they're growing quite nicely. I'm amazed at how robust they are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 27 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 28 0 0]Does this mean our mission is complete? That's a job well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]It's all thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 29 0 0]I did my best to do everything in my power. I'm happy I was able to assist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 30 0 0]...Oh, and we can't forget to thank the ladybug for contributing as well.[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 31 0 0]That's true. We still need to watch out for birds and other animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 32 0 0]...But, maybe it will be okay to share a little with them, as well.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 33 0 0]...That just shows that the ladybug has been hard at work, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 34 0 0]I'll go ahead and express our gratitude to it. Thank you, little ladybug.[n][uf 1 1][e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 35 0 0]As I've tended these plants alongside you, I've realized something.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 36 0 0]I've made so many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 37 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 38 0 0]That goes for the plants, the pests, and the ladybug, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 39 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 40 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 41 0 0]I'll give it my all to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 42 0 0]Do you think I'll be able to?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]Don't push yourself too hard.[e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 5 13 22 1 7]...You're already working hard enough, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 44 0 0]But, hearing that from you is making me even more motivated.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 5 13 22 1 7]It's okay. I'm not going to act on my own anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 46 0 0]I just want to do a little bit to protect everyone's futures.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 47 0 0]Of course, I don't plan on sacrificing my attention here either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 48 0 0]Okay, it's time to get started![n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 7 1 25 25]I think we did another thorough job today. Shall we head back now?[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]It appears they are growing well. Hip hip hooray, as they say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 3 0 0]I believe this is "mission complete." Well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_034_0_0 top]
[uf 0 5 65278][uf 2 1]It's thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]I tried to do everything in my power. I'm glad I was of service.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]The ladybug put in a lot of work as well. We thank you for your service![n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]That's true. We must be prepared for surprise attacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]That reminds me, Junpei-san came here the other day trying to get some free samples, but I quickly gunned him down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]If he comes back, rest assured, he will be shot on sight.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]But, it's thanks to the ladybug that the plants didn't suffer any significant damage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0]I will thank it for its service in your place, [uf 4 2]-san![n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]I've realized something, tending these plants alongside you.[n][uf 1 1][e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]I've made many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]That goes for the plants, and the pests, and the ladybug too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]I will do my best to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]That is my new goal from now on.[n][uf 1 1][e]

[sel SEL_041_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]I don't get it.[e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 22 1 7]I am impressed, [uf 4 2]-san. I hadn't expected a competition here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Hearing that, my motivation is fully charged! ...As they say.[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 5 13 22 1 7]It's difficult to explain, but I will do my best in everyday life, as well as in battle against the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]All for one and one for all! Let's go team! ...As they say.[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]Naturally, I will still continue to look after them at full throttle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]Let's get started right away.[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Once again, our mission has concluded without incident today. Let's head back now.[n][uf 1 1][e]

[msg MSG_048_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]It looks like they're growing very well. I'm amazed at how robust they are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 27 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_049_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 28 0 0]Does this mean our mission is complete? That's a job well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_050_0_0 top]
[uf 0 5 65278][uf 2 1]It's all thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_051_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 29 0 0]I did my best to do everything in my power. I'm happy I was able to assist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 30 0 0]...Oh, and we can't forget to thank the ladybug for contributing as well.[n][uf 1 1][e]

[msg MSG_052_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]That's true. We still need to watch out for birds and other animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 32 0 0]...But, maybe it will be okay to share a little with them, as well.[n][uf 1 1][e]

[msg MSG_053_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 33 0 0]...That just shows that the ladybug has been hard at work, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 34 0 0]I'll go ahead and express our gratitude to it. Thank you, little ladybug.[n][uf 1 1][e]

[msg MSG_054_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 35 0 0]As I've tended these plants alongside you, I've realized something.[n][uf 1 1][e]

[msg MSG_055_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 36 0 0]I've made so many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 37 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 38 0 0]That goes for the plants, and the pests, and the ladybug too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 39 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_056_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 40 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 41 0 0]I'll give it my all to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 42 0 0]Do you think I'll be able to?[n][uf 1 1][e]

[sel SEL_057_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]Don't push yourself too hard.[e]

[msg MSG_058_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 5 13 22 1 7]...You're already working hard enough, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 44 0 0]But, hearing that from you is making me even more motivated.[n][uf 1 1][e]

[msg MSG_059_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 5 13 22 1 7]It's okay. I'm not going to act on my own anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 46 0 0]I just want to do a little bit to protect everyone's futures.[n][uf 1 1][e]

[msg MND_060_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_061_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 47 0 0]Of course, I don't plan on sacrificing my attention here either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 48 0 0]Okay, it's time to get started![n][uf 1 1][e]

[msg MND_062_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_063_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 7 1 25 25]I think we did another thorough job today. Shall we head back now?[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]It appears they are growing well. Hip hip hooray, as they say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_065_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 3 0 0]I believe this is "mission complete." Well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_066_0_0 top]
[uf 0 5 65278][uf 2 1]It's thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_067_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]I tried to do everything in my power. I'm glad I was of service.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]The ladybug put in a lot of work as well. We thank you for your service![n][uf 1 1][e]

[msg MSG_068_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]That's true. We must be prepared for surprise attacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]That reminds me, Junpei-san came here the other day trying to get some free samples, but I quickly gunned him down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]If he comes back, rest assured, he will be shot on sight.[n][uf 1 1][e]

[msg MSG_069_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]But, it's thanks to the ladybug that the plants didn't suffer any significant damage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]I will thank it for its service in your place, [uf 4 2]-san![n][uf 1 1][e]

[msg MSG_070_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]I've realized something, tending these plants alongside you.[n][uf 1 1][e]

[msg MSG_071_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0]I've made many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]That goes for the plants, and the pests, and the ladybug too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_072_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]I will do my best to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]That is my new goal from now on.[n][uf 1 1][e]

[sel SEL_073_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]I don't get it.[e]

[msg MSG_074_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 22 1 7]I am impressed, [uf 4 2]-san. I hadn't expected a competition here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 20 0 0]Hearing that, my motivation is fully charged! ...As they say.[n][uf 1 1][e]

[msg MSG_075_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 5 13 22 1 7]It's difficult to explain, but I will do my best in everyday life, as well as in battle against the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]All for one and one for all! Let's go team! ...As they say.[n][uf 1 1][e]

[msg MND_076_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_077_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Naturally, I will still continue to look after them at full throttle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Let's get started right away.[n][uf 1 1][e]

[msg MND_078_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_079_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 25 0 0]Once again, our mission has concluded without incident today. Let's head back now.[n][uf 1 1][e]

[msg MSG_080_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 26 0 0]It looks like they're growing very well. I'm amazed at how robust they are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 27 0 0]The ladybug has grown into a fine adult as well.[n][uf 1 1][e]

[msg MSG_081_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Does this mean our mission is complete? That's a job well done, [uf 4 2]-san.[n][uf 1 1][e]

[sel SEL_082_0_0 top]
[uf 0 5 65278][uf 2 1]It's all thanks to your help.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]
[uf 0 5 65278][uf 2 1]We aren't growing bugs here...[e]

[msg MSG_083_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 29 0 0]I did my best to do everything in my power. I'm happy I was able to assist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 30 0 0]...Oh, and we can't forget to thank the ladybug for contributing as well.[n][uf 1 1][e]

[msg MSG_084_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 31 0 0]That's true. We still need to watch out for birds and other animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 32 0 0]...But, maybe it will be okay to share a little with them, as well.[n][uf 1 1][e]

[msg MSG_085_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 33 0 0]...That just shows that the ladybug has been hard at work, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 34 0 0]I'll go ahead and express our gratitude to it. Thank you, little ladybug.[n][uf 1 1][e]

[msg MSG_086_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 35 0 0]As I've tended these plants alongside you, I've realized something.[n][uf 1 1][e]

[msg MSG_087_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 36 0 0]I've made so many new discoveries beside these planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 37 0 0]Everyone is doing the best they can to make their way in the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 38 0 0]That goes for the plants, and the pests, and the ladybug too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 39 0 0]And you as well, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_088_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 40 0 0]I may be a machine, but I also want to do the best I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 41 0 0]I'll give it my all to make my way in the world, just like everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]Do you think I'll be able to?[n][uf 1 1][e]

[sel SEL_089_0_0 top]
[uf 0 5 65278][uf 2 1]I won't let you beat me.[e]
[uf 0 5 65278][uf 2 1]Don't push yourself too hard.[e]

[msg MSG_090_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 5 13 22 1 7]...You're already working hard enough, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 44 0 0]But, hearing that from you is making me even more motivated.[n][uf 1 1][e]

[msg MSG_091_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 5 13 22 1 7]It's okay. I'm not going to act on my own anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 46 0 0]I just want to do a little bit to protect everyone's futures.[n][uf 1 1][e]

[msg MND_092_0_0]
[uf 0 5 65278][uf 2 1]Aigis seems to have found a new[n]purpose through tending the plants...[n][uf 1 1][e]

[msg MSG_093_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 47 0 0]Of course, I don't plan on sacrificing my attention here either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 48 0 0]Okay, it's time to get started![n][uf 1 1][e]

[msg MND_094_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like they're going to grow nicely...[n][uf 1 1][e]

[msg MSG_095_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 7 1 25 25]I think we did another thorough job today. Shall we head back now?[n][uf 1 1][e]

