[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Woof...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is eagerly watching[n]all the people pass by.[n][uf 1 1][e]

[msg MSG_002_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Oooh! Is that you there, Koromaru?[n][uf 1 1][e]

[msg MSG_003_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Do you remember me? I used to play shogi with the priest.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Arf! Arf Arf![n][uf 1 1][e]

[msg MSG_005_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]Hoho, I see, I see.[n][uf 1 1][e]

[msg MSG_006_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]Oh, dear...[n][uf 1 1][e]

[msg MSG_006_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]Whew, I'm sorry, but do you mind if I rest here for a bit?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]By all means.[e]
[uf 0 5 65278][uf 2 1]Want to rest inside?[e]

[msg MSG_008_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1]Much obliged. Sorry to bother you.[n][uf 1 1][e]

[msg MSG_008_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]Down we go...[n][uf 1 1][e]

[msg MSG_009_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]Oh, no, no. Here's fine.[n][uf 1 1][e]

[msg MSG_009_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1]Down we go...[n][uf 1 1][e]

[msg MSG_010_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1]Whew... The years are catching up to me.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]*whine* Arf arf, arf![n][uf 1 1][e]

[msg MSG_012_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1]Do you live here?[n][uf 1 1][e]

[msg MSG_013_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1]In that case, I have to give you my thanks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1]So thank you. For taking Koromaru in as your family.[n][uf 1 1][e]

[msg MSG_014_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 1]A lot's been going on ever since the priest's accident.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1]To tell you the truth, someone else was willing to take Koromaru in.[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]What was this person like?[e]
[uf 0 5 65278][uf 2 1]But he was always at the shrine.[e]

[msg MSG_016_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]A sweet and pleasant young lady. Koromaru took quite a shine to her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 1]Only... Well, he'd keep coming back to the shrine gate.[n][uf 1 1][e]

[msg MSG_017_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 1]That's right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 1]We eventually realized that Koromaru kept going back to the shrine.[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 0 0 0 23 0 0]......[n][uf 1 1][e]

[msg MSG_019_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 1]I'm not sure what it was, but it seemed like he had some unfinished business.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 1]And after that, no one else was able to take him in.[n][uf 1 1][e]

[msg MSG_020_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 1]However...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 1]If he's here now, I take it he achieved his goal, then?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Koromaru saw it through.[e]
[uf 0 5 65278][uf 2 1]He protected the shrine.[e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Arf![n][uf 1 1][e]

[msg MSG_023_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 1]I see, I see![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 1]I can't say I really understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 1]But if you do, then Koromaru must be happy.[n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Arf![n][uf 1 1][e]

[msg MSG_025_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0][uf 5 21 0 1]I see. You did well, didn't you, boy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0][uf 5 21 0 1]To be honest, I don't really understand any of this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0][uf 5 21 0 1]But if you do, then Koromaru must be happy.[n][uf 1 1][e]

[msg MSG_026_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0][uf 5 21 0 1]I believe that Koromaru's bright enough to choose where he wants to be.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0][uf 5 21 0 1]And that means it must be his choice to be here with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0][uf 5 21 0 1]Be good to each other, will you?[n][uf 1 1][e]

[sel SEL_027_0_0 top]
[uf 0 5 65278][uf 2 1]We will![e]
[uf 0 5 65278][uf 2 1]We'll see...[e]

[msg MSG_028_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Woof.[n][uf 1 1][e]

[msg MSG_029_0_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0][uf 5 21 0 1]All right, I've rested plenty. I'll get out of your hair before it gets too late.[n][uf 1 1][e]

[msg MSG_029_3_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0][uf 5 21 0 1]Upsy-daisy.[n][uf 1 1][e]

[msg MSG_029_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0][uf 5 21 0 1]Ow ow ow...[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Poor old man... He's hurting his[n]back from carrying too much.[n][uf 1 1][e]

[msg MSG_031_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]*whine*[n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]Can I help you out?[e]
[uf 0 5 65278][uf 2 1]Let me carry your bags.[e]

[msg MSG_032_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0][uf 5 21 0 1]I'm sorry to be such a bother. Yes, would you mind taking half of what I'm carrying?[n][uf 1 1][e]

[msg MSG_033_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Ruff![n][uf 1 1][e]

[msg MSG_033_5_0 [Old Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 46 0 0][uf 5 21 0 1]Oh, that's very sweet of you. I'd like that very much.[n][uf 1 1][e]

[msg MSG_034_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Ruff![n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]Koromaru and I walked with[n]the old man back to his place.[n][uf 1 1][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]Oh, [uf 4 1]-kun.[n][uf 1 1][e]

[msg MSG_036_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]Hehe, you're in a good mood, Koro-chan. Did you go for a walk?[n][uf 1 1][e]

[msg MSG_037_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Arf Arf![n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]...You helped? Ah, I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]I believe Koromaru-san wants to thank you, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]He says, "Let's do it again."[n][uf 1 1][e]

[msg MSG_039_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]*pant* *pant* Arf![n][uf 1 1][e]

[msg MND_040_0_0]
[uf 0 5 65278][uf 2 1]I think Koromaru appreciates me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has increased[n]after helping people with Koromaru.[n][uf 1 1][e]

[msg MSG_041_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Should we head in? It's almost Koro-chan's dinner time.[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]I'll be preparing your dinner today, Koromaru-san. I hope you look forward to it.[n][uf 1 1][e]

[msg MSG_043_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]*whimper*[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]We headed in the dorm after[n]Koromaru calmed down a bit.[n][uf 1 1][e]

