[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Can't believe the police station's sellin' weapons.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]What's more, they only gave us 5,000 yen! Ain't that kinda stingy? I mean, we're kinda savin' the world...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh, crap! It's this late already?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 2 0 25 25]I'm gonna miss the rerun of The Lonely Shogun! I gotta go![n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]What about stocking up?[e]
[uf 0 5 65278][uf 2 1]Okay.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Uh, well, about that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 2 1 25 25]I'll leave the rest to you, Leader! Let's meet up again you-know-where![n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Sweet. I'll leave the rest to you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 2 0 25 25]I know I'm the one who brought you here, but you'll see me again you-know-where.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]There's a ton of shops and stuff in this place, so you really should check it out while you can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 2 1 25 25]Alright, see ya back at the dorm![n][uf 1 1][e]

[msg SYS_006_0_0]
[uf 0 5 65278][uf 2 1]There are various facilities and stores throughout the city.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Stop by to find useful items to help with exploring Tartarus and meeting new Social Links.[n][uf 1 1][e]

