[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]There you are. Finally found you.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Hey, Takeba...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 3 0 0]You hardly ever miss student council meetings. I've been looking all over for you.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Did someone ask you to come find me?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Well, yeah. I'm not a member or anything, but still.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Ah, well... Sorry about that.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]They've been pretty busy, huh? What with the class trip and all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]It's for both second- and third-years, so I imagine you have your hands full, too.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 9 0 0]The class trip...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 3 25 25]Even if I did go, I'd only spoil the fun.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Wait, you're not thinking of skipping the trip, are you?[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 13 0 0]You can't do that! That's not an option![n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 14 0 0]...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]You know, I've been meaning to talk to you.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]About what?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Well, honestly, you're not the easiest person to relate to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 18 0 0]But I lost my dad, too. And I know what that's like.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]Takeba...[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]So I've decided I don't want our friendship to be over. I'm going to be more upfront with you from now on.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 21 0 0]......[n][uf 1 1][e]

[msg MSG_018_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Ah, there she is![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I've been looking everywhere for you.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]Huh? Ryoji-kun?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Why are you up here?[n][uf 1 1][e]

[msg MSG_020_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Huh? Weren't you looking for Miss President, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I was doing the same thing. Some guy asked me to find her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]He said if I didn't, the class trip might get canceled.[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 29 0 0]Odagiri-kun... He'll hit up anyone in arm's reach for a favor.[n][uf 1 1][e]

[msg MSG_022_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]In any case, looks like I found you, Mitsuru Kirijo-san![n][uf 1 1][e]

[msg MSG_022_5_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]And I have to say, you're quite stunning. Maybe we could go out sometime?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I know this place on the top floor of a five-star hotel.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]The restaurant up there has a view of the city nightscape that's almost as breathtaking as you.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 34 0 0]Nightscape?[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 35 0 0]Senpai! You better head back to the meeting![n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Oh, right.[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 37 0 0]Takeba... Thank you for coming to find me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 38 0 0]For now, I'd better see to my duties.[n][uf 1 1][e]

[msg MSG_027_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Hey, she left without giving me an answer.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 40 0 0]"For now," huh. I don't like the sound of that.[n][uf 1 1][e]

[msg MSG_029_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Well, how 'bout you, Yukari-san? Care to join me for dinner?[n][uf 1 1][e]

[msg MSG_029_5_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]I know this place on Shirakawa Boulevard—[n][uf 1 1][e]

[msg MSG_030_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 10 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]Ow![n][uf 1 1][e]

