[msg MSG_000_0_0 [Yo-Yo Fishing Stall Owner]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 432]Hey, kid. Here for your first shrine visit of the year, eh? I'll have to pay my own respects after work.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yo-Yo Fishing Stall Owner]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 432]Today's yo-yo fishing is a New Year's version. Great luck if you catch it, worst luck if it breaks![n][uf 1 1][e]

