[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 157 65535 0 0][uf 3 1 1 0 1 29 0 0]Seriously, Junpei? Of all the dumb things you could say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 157 65535 0 0][uf 3 1 1 0 1 30 0 0]Anyway... It's nice that we get the chance to go out like this every once in a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 157 65535 0 0][uf 3 1 1 0 1 31 0 0]Let's just try to stay positive and chin up.[n][uf 1 1][e]

