[msg MSG_000_0_0 [Fanatical Older Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]You hear many bad things these days, but never fear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]This world's salvation is at hand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]Oh, but I'm not telling you what you should believe or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]After all, I didn't believe it at first, either.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fanatical Older Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]I heard Nyx-sama will save our world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]My life's been going downhill and I'm getting tired of it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]At my lowest point, I found out about Nyx-sama and my heart came to life again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]How about it? Will you let Nyx-sama into your heart too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]Oh, but I'm not telling you what you should believe or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]After all, I didn't believe at first, either.[n][uf 1 1][e]

