[msg MSG_000_0_0 [Fanatical Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]In this world, there is much filth. This is one reason we require salvation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]At this rate, even when the Salvation is at hand, the world will not be totally clean.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]We must continue to prepare for that day. Heaven has charged us with preparing for the Salvation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]Our task is great, and of vital importance. Do not disturb our work.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fanatical Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]Listen to the emptiness, and empty your own heart... You will hear a sound.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]That is the sound of Nyx-sama. Her heartbeat... Her breath... Her whisper...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]When the Salvation is at hand, your heart will be free of pain, and you will be at peace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]But alas, there are still many irredeemable people in the world who cling to this world and doubt Nyx-sama...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 701]The pain in your heart will be as the burning red flames of Hell![n][uf 1 1][e]

