[msg MSG_000_0_0 [Student Back to Senses]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 751]Those posters and paintings... I used to be a little into that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 751]But between you and me, I only did it because everyone else was.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 751]At the time, I was so pumped... I thought I was doing something great.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 751]But now I can look back on it and realize how dumb I was.[n][uf 1 1][e]

