[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]So... I'd like you to celebrate with me. As of today, I am a free individual.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Free from what?[e]
[uf 0 5 65278][uf 2 1]You finished your story?[e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]From the hospital. They were going to put me under care, but now I don't have to do it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 20 5 117]No, not quite yet. Almost, though.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I just came from the hospital. They were going to admit me, but it's no longer needed.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I guess my body is too weak to undergo surgery. So, I've opted out of examinations and medication.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I'm done with the hospital.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]...Now, I'm just waiting for the end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]But, I don't feel like I'm being singled out anymore.[n][uf 1 1][e]

[msg MSG_006_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Everyone is waiting to die, all the same... Some just have longer to wait than others.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]But once the time comes, it's the same for all of us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]I'm still... a little lonely, but I've moved past the sadness.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Could I get a better look at you...? I want to remember your face.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Kamiki's smile is tinged with sadness...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Thank you... I'm... a little bit tired today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 117 0 25 25]The story is almost done, so I'll show it to you soon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I'll come see you again.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

