[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]07/15/2009 17:05:38[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like Fuuka's room...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 1 0 0]Hmmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 2 0 0]I wonder if I should have gone for the one-piece suit instead.[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 3 0 0]These halter top bikinis look almost like underwear...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 4 0 0]It feels a little weird to have my belly button exposed.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 5 0 0]Now that I think about it, this is the first time I've chosen my own swimsuit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 6 0 0]But there wasn't much of a selection for the one-pieces...[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 7 0 0]Hm, I wonder if I should ask Yukari-chan again what she thinks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 102 11 0 0][uf 3 1 1 0 0 8 0 0]Although... I don't really exercise, so I probably wouldn't look very good standing next to her...[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 11 0 0][uf 3 1 1 0 0 9 0 0]Oh, right! I have just the thing![n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 10 0 0]The low-frequency waist slimmer pad I bought from Tanaka's TV show![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 11 0 0]It said online it was very effective for its price, so maybe it could do some help before the trip.[n][uf 1 1][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 11 0 0][uf 3 1 1 0 0 12 0 0]Now let's see... How do I turn this on?[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 11 0 0][uf 3 1 1 0 0 13 0 0]Aah...! No... This...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 11 0 0][uf 3 1 1 0 0 14 0 0]I-It tickles! Hahahaha... What do I do!? Hahaha! Ahahahahaha![n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 11 102 11 0 0][uf 3 1 1 0 0 15 0 0]Wh-Wh-Why won't it come off...? Hahaha... Nooo...![n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Yamagishi, do you have a moment?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 11 0 0][uf 3 1 1 0 0 17 0 0]Ah! It's Kirijo-senpa— Hahaha! I-I have to get the door...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 11 102 11 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 15 25 25]Yes! I'm... Heehee... I'll be right there![n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]Oh, um... Am I interrupting anything?[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 11 102 11 0 0][uf 3 1 1 0 0 20 0 0]N-No, not at— Heehee... No, not at all... Hahahaha...![n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]It's... not that important. Um, never mind. Just... carry on.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 102 11 0 0][uf 3 1 1 0 0 22 0 0]Oh, Senpai...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 11 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]I-Is this... what it means... to train... your abs...?[n][uf 1 1][e]

[msg MSG_013_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 11 102 11 0 0][uf 3 1 1 0 0 24 0 0]Aaaah! Heeheeee! Someone help![n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

