[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Yukari looks serious...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]We spent time cooking together...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 7 1 2]Mmm... Putting in the effort to cook a homemade meal always makes it taste extra good![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Well, shall we start cleaning up?[n][uf 1 1][e]

