[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8007 0 0][uf 4 23 1 9 1 25 25]Awooo![n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Koro-chan was in top form for that fight! Maybe he's giving it his all because he just met back up with everyone.[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30001 0 0][uf 4 23 1 9 0 25 25]It sure seems like it. He's full of pride.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]And I can sense he has some affection for you, Sister... Hmph.[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30007 0 0][uf 4 23 1 11 2 25 25]Tell me, Sister, which one of us is more helpful to you? And be honest! Please![n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]You, Metis.[e]
[uf 0 5 65278][uf 2 1]Koromaru-san.[e]
[uf 0 5 65278][uf 2 1]I can't possibly compare you two.[e]

[msg MSG_005_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30080 0 0][uf 4 23 1 11 1 25 25]Yes... Yes![n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0][uf 4 23 1 9 0 25 25]Arf![n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 4 23 1 11 2 25 25]Oh, don't give me that look. It's like you're saying, "Fine, you can have this win." You're a dog![n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30028 0 0][uf 4 23 1 11 3 25 25]I was afraid you'd say that... I suppose that means I'll have to apply myself more.[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0][uf 4 23 1 9 0 25 25]Arf! Arf, arf![n][uf 1 1][e]

[msg MSG_010_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 4 23 1 11 2 25 25]I-I don't need your sympathy![n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30046 0 0][uf 4 23 1 11 4 25 25]Really...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 4 23 1 11 0 25 25]I... I wasn't expecting that. Honestly, I thought you'd choose one of your friends.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 4 23 1 11 1 25 25]But... You didn't.[n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0][uf 4 23 1 9 0 25 25]Ruff![n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 4 23 1 11 0 25 25]You say some profound things... for a dog.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5025 0 0]It seems like everything's going pretty well! I hope we can keep up the momentum as we progress...[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I admit I was worried about our battle prowess... But we managed to dispatch such a strong foe without much difficulty.[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8007 0 0][uf 4 23 1 9 1 25 25]Awooo![n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 4 23 1 5 1 25 25][uf 4 23 1 9 0 25 25]You did great, Koromaru. As for me, I've some catching up to do—since you all got a head start reacclimating yourselves.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 1 5 0 25 25]But with everyone helping Aigis, I was able to focus on my investigation. You have my appreciation for that.[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0][uf 4 23 1 9 0 25 25]Ruff![n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I know I'm rather late, but... I hope you'll still have me at your side as we face whatever comes next.[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]I'll be relying on you.[e]
[uf 0 5 65278][uf 2 1]This is all so overwhelming...[e]
[uf 0 5 65278][uf 2 1]I'd be fine on my own.[e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4131 0 0][uf 4 23 1 5 1 25 25]Hehe... There may not be much I can do to help, but I promise you I'll do the best I can.[n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4024 0 0]I'm sure we all feel the same way. That's precisely why we're here together.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4028 0 0][uf 4 23 1 5 1 25 25]Hm... That may be so. Allow me to rephrase myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 1 5 0 25 25]Let us fight together—to better our odds of escaping this place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Surely, you can get behind that, non?[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 1 5 0 25 25]I expect we have a lot of ground to cover. Let's make sure we're all prepared and press on.[n][uf 1 1][e]

[msg MSG_025_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 4 23 1 5 1 25 25]Heh, you've still got some fight in you, I see. How encouraging.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4061 0 0]What exactly is that figure? And why does it keep setting Shadows on us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Just what on earth is its motive...?[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3060 0 0]I've been mulling that over in my head for a while now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]But I'm happy to leave the thinking to you. You're the brains between the two of us.[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0][uf 4 23 1 5 3 25 25]Don't say that, Akihiko... Putting yourself down like that's a bad habit to develop.[n][uf 1 1][e]

[msg MSG_030_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]Nah, I figured my strong suit's more beating things with my fists, so my brain's completely tapped out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]While you were away, I ended up the oldest of the bunch, and I just had a hard time concentrating while looking out for everyone...[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]

[msg MSG_032_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4001 0 0][uf 4 23 1 5 0 25 25]Aigis, you heard what Akihiko said... Is that right? He watched out for everyone?[n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]He certainly did.[e]
[uf 0 5 65278][uf 2 1]I don't recall that.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_034_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 3 0 65535 4121 0 0][uf 4 23 1 5 3 25 25]Well... If you say so, then I believe you.[n][uf 1 1][e]

[msg MSG_035_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0][uf 3 1 3 0 65535 4112 0 0][uf 4 23 1 5 3 25 25]Ah, perhaps there was a discrepancy in how you both perceived the situation, then.[n][uf 1 1][e]

[msg MSG_036_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 52 65535 0 0][uf 3 1 3 0 65535 4106 0 0][uf 4 23 1 5 3 25 25]Well, your silence says it all. I do commend you for trying to do right by both sides, though.[n][uf 1 1][e]

[msg MSG_037_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 1 5 0 25 25]At any rate, it's true people have their own strengths and weaknesses. Let's move on. Akihiko, you take point.[n][uf 1 1][e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Heh. Roger that.[n][uf 1 1][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3085 0 0][uf 4 23 1 2 3 25 25]You've got a real knack for leading, Aigis. It's made combat easier for all of us.[n][uf 1 1][e]

[sel SEL_040_0_0 top]
[uf 0 5 65278][uf 2 1]Thank you.[e]
[uf 0 5 65278][uf 2 1]I still have a lot to learn.[e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3096 3085 0][uf 4 23 1 4 1 25 25]You were especially impressive in that last fight. Sure put up a fight against some difficult enemies.[n][uf 1 1][e]

[msg MSG_042_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3131 0 0][uf 4 23 1 4 1 25 25]Striving for improvement, huh? I respect that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]All right, time for me to get in the zone and follow your example.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 4 23 1 4 1 25 25]Right, Takeba?[n][uf 1 1][e]

[msg MSG_044_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1092 0 0][uf 4 23 1 2 4 25 25]Hm... Yeah, I guess.[n][uf 1 1][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 4 23 1 4 0 25 25]What's that supposed to mean?[n][uf 1 1][e]

[msg MSG_046_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 4 23 1 2 3 25 25]I don't mean anything by it. It's just... Well, I haven't given it much thought since a lot's been happening.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]I mean, I'm just more worried about that figure and all...[n][uf 1 1][e]

[msg MSG_047_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3060 0 0]Right, it ran on us... Would be nice if we could catch it next time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]The moment we see it again, let's drop everything and chase after it.[n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 4 25 2]......[n][uf 1 1][e]

[msg MSG_049_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2095 0 0][uf 4 23 1 3 1 25 25]Heh, handin' out brutal beatdowns is a breeze with my battle buddy around![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Ain't that right, Koromaru?[n][uf 1 1][e]

[msg MSG_050_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 3 0 65535 8002 0 0][uf 4 23 1 9 2 25 25]Grrr...[n][uf 1 1][e]

[msg MSG_051_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 4 23 1 3 3 25 25]Hey now, what's with the growlin'?[n][uf 1 1][e]

[msg MSG_051_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 4 23 1 3 0 25 25]Aigis, me n' Koromaru make one deadly duo, yeah?[n][uf 1 1][e]

[sel SEL_052_0_0 top]
[uf 0 5 65278][uf 2 1]I'm sure you do.[e]
[uf 0 5 65278][uf 2 1]I wonder...[e]

[msg MSG_053_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Ruff! Ruff![n][uf 1 1][e]

[msg MSG_054_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 4 23 1 3 3 25 25]I'm no dog whisperer, but... I can see into his soul, and it's tellin' me those are ruffs of rejection right there.[n][uf 1 1][e]

[msg MSG_055_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0][uf 4 23 1 9 0 25 25]Woof![n][uf 1 1][e]

[msg MSG_056_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 4 23 1 3 3 25 25]Awww, Ai-chan... And you too, boy? Cold as ice, the both of you.[n][uf 1 1][e]

[msg MSG_057_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2124 0 0]Man... So my affections were just one-sided, after all? S'okay, whatever, that's fine. I'm cool. We're cool.[n][uf 1 1][e]

[msg MSG_058_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Hehe. Oh, Koro-chan, you silly boy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Your tail's been wagging this whole time![n][uf 1 1][e]

[msg MSG_059_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30127 0 0][uf 4 23 1 11 1 25 25]And that's another one down![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Strong enemies are no doubt dangerous, but I love that I get to team up and face them at your side, Sister.[n][uf 1 1][e]

[msg MSG_060_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7030 0 0][uf 4 23 1 8 1 25 25]I know what you mean. There's nothing quite like fighting alongside other people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]I was really impressed by everyone's teamwork and comradery when I first joined you all in battle.[n][uf 1 1][e]

[msg MSG_061_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 4 23 1 11 0 25 25]Wow, really? Huh, I guess everyone feels the same way, then.[n][uf 1 1][e]

[msg MSG_062_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 4 23 1 8 0 25 25][uf 4 23 1 11 4 25 25]Oh! But don't get me wrong, Sister—it's EXTRA special when just you and I team up![n][uf 1 1][e]

[sel SEL_063_0_0 top]
[uf 0 5 65278][uf 2 1]I'm flattered.[e]
[uf 0 5 65278][uf 2 1]You should befriend the others, too.[e]
[uf 0 5 65278][uf 2 1]That's rude to Amada-san.[e]

[msg MSG_064_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30027 0 0][uf 4 23 1 11 1 25 25]Mhm, of course! I'm glad you understood what I meant.[n][uf 1 1][e]

[msg MSG_065_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30028 0 0][uf 4 23 1 11 3 25 25]Okay... If you say so, Sister.[n][uf 1 1][e]

[msg MSG_066_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30046 0 0][uf 4 23 1 11 4 25 25]It is?[n][uf 1 1][e]

[msg MSG_067_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 23 1 11 3 25 25]...Sorry.[n][uf 1 1][e]

[msg MSG_068_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 4 23 1 8 3 25 25]How am I supposed to react to this...?[n][uf 1 1][e]

[msg MSG_069_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MSG_070_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Koromaru-san is always fretting over the rest of the team after we take out a stronger opponent.[n][uf 1 1][e]

[msg MSG_070_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30057 0 0][uf 4 23 1 11 3 25 25]Or perhaps it's more apt to say that he's showing he cares... Hm.[n][uf 1 1][e]

[msg MSG_070_7_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 4 23 1 11 0 25 25]It's as if he considers himself the alpha.[n][uf 1 1][e]

[sel SEL_071_0_0 top]
[uf 0 5 65278][uf 2 1]Well, he is one.[e]
[uf 0 5 65278][uf 2 1]He doesn't, though.[e]
[uf 0 5 65278][uf 2 1]But I'm the leader.[e]

[msg MSG_072_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30034 0 0][uf 4 23 1 11 2 25 25]But you're the real leader here, Sister. Koromaru-san is simply excited from the battle.[n][uf 1 1][e]

[msg MSG_073_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30044 0 0][uf 4 23 1 11 0 25 25]That's what Koromaru-san would say, too.[n][uf 1 1][e]

[msg MSG_073_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 23 1 11 3 25 25]But he still tries to do all this leader-y stuff... It just doesn't make sense.[n][uf 1 1][e]

[msg MSG_074_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30085 0 0][uf 4 23 1 11 2 25 25]Well, I know that, but Koromaru-san here...[n][uf 1 1][e]

[msg MSG_075_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Woof...[n][uf 1 1][e]

[msg MSG_076_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 4 23 1 11 2 25 25]Hey, don't you feign ignorance with me.[n][uf 1 1][e]

[msg MSG_076_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30047 0 0][uf 4 23 1 11 3 25 25]...I really don't comprehend any of my sister's friends.[n][uf 1 1][e]

[msg MSG_077_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 3 0 65535 1022 0 0][uf 4 23 1 2 2 25 25]All right, now we can get back to exploring. Let's hurry to the next door.[n][uf 1 1][e]

[msg MSG_078_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 4 23 1 5 3 25 25]We just overcame a difficult battle, Yukari. Are you sure you don't need a moment to reorient yourself?[n][uf 1 1][e]

[msg MSG_078_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4001 0 0][uf 4 23 1 5 0 25 25]What say you, Aigis? Shall we push on or return and regroup?[n][uf 1 1][e]

[sel SEL_079_0_0 top]
[uf 0 5 65278][uf 2 1]I'd like to push on.[e]
[uf 0 5 65278][uf 2 1]I'd like to head back.[e]
[uf 0 5 65278][uf 2 1]I'm not sure...[e]

[msg MSG_080_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 3 0 65535 4094 0 0][uf 4 23 1 5 3 25 25]All right, understood. We'll abide by the leader's decision.[n][uf 1 1][e]

[msg MSG_081_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 4 23 1 2 3 25 25]...Thank you, Aigis.[n][uf 1 1][e]

[msg MSG_082_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4060 0 0]Agreed. That'd be for the best.[n][uf 1 1][e]

[msg MSG_083_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 4 23 1 2 3 25 25]Yeah, I get it... We all need a breather—to recuperate a bit before continuing.[n][uf 1 1][e]

[msg MSG_084_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4003 0 0]You ought to be more confident in your decision-making skills. After all, you did get us this far.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Take some time to assess our current situation, then make your call.[n][uf 1 1][e]

[msg MSG_085_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 4 23 1 2 3 25 25][uf 4 25 2]......[n][uf 1 1][e]

