[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]I'm glad you're feeling okay now. Well, I guess I'll head up first.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Like I said this morning, meet me on the fourth floor. The chairman should be waiting for us.[n][uf 1 1][e]

