[msg MSG_000_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Oh... That drink...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Can I see it? Ooooh... Is this the limited-edition drink you can only get in Kyoto?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Wow... Impressive![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I have to say, I love these rare drinks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Have you seen the [uf 4 4 1 37 1 0]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]It's only available in the fall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]You want some? Well... I can't let you have it for free.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I'll need... let's say 5,000 yen, to part with it.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Buy it at 5,000 yen[e]
[uf 0 5 65278][uf 2 1]Don't buy it[e]

[msg MND_001_1]
[uf 0 5 65278][uf 2 1]I don't have enough money...[n][uf 1 1][e]

[msg MSG_002_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]You don't have the money? That's not good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]You should always carry enough money for rare beverage emergencies![n][uf 1 1][e]

[msg MSG_003_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Wh-What!? Are you really going to pay me 5,000 yen for this!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Wow, you must be a rare drink maniac![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Thanks, though! Now I can get my own rare drink![n][uf 1 1][e]

[msg MSG_003_2_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Hey... Maybe you could help out a fellow rare drink maniac...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Do you think if we made those persimmons into a drink, maniacs all over the country would like it?[n][uf 1 1][e]

[msg MSG_004_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I see... I guess you're not a rare drink maniac. *sigh*[n][uf 1 1][e]

[msg MSG_005_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Kansai, huh...? So even if I take the bus, it'll cost around 10,000 yen...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Argh... How many drinks could I get with 10,000 yen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]...Yeah? What's up?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]You like drinks too, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]But all of yours are normal drinks...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]That Kansai-only drink is so rare and awesome that everyone wants a sip![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]She doesn't seem interested in[n]the drinks I can buy here...[n][uf 1 1][e]

[msg MSG_007_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Kansai, huh...? So even if I take the bus, it'll cost around 10,000 yen...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Argh... How many drinks could I get with 10,000 yen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]A rare Kansai drink... I wonder how it tastes...[n][uf 1 1][e]

[msg MSG_008_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]That tree seems special for some reason... I wonder why it's there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Does it commemorate something?[n][uf 1 1][e]

[msg MSG_009_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]That tree is a persimmon tree, right? Do you think it'll bear fruit? I hope so![n][uf 1 1][e]

[msg MSG_010_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]That persimmon tree is gonna be cut down! What a waste![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I soooo wanted to try its fruit...[n][uf 1 1][e]

[msg MSG_011_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Some people are protesting the decision to cut down the tree![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I guess they want to try its persimmons...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]Nah, there must be another reason...[n][uf 1 1][e]

[msg MSG_012_0_0 [Friendly Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]I saw an old man pick a persimmon from the tree![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 322]It wasn't even ripe![n][uf 1 1][e]

