[msg MSG_000_0_0 [Anxious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]My sister goes here, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]It's a good thing she's not the kind of girl who stays out all night...[n][uf 1 1][e]

[msg MSG_001_0_0 [Anxious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]One of the students who collapsed was in my sister's class...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]I guess she was running away from home as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]I heard she always hung around those thugs at that one place...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 303]Something must've happened there.[n][uf 1 1][e]

