[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Do you recall fighting that Shadow here on the rooftop a little while back?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Well, while cleaning up the aftermath, I happened upon some planters and gardening tools.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]And I couldn't help myself from setting up our own little garden![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]So what do you think? Not too shabby, eh?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Looks pretty good.[e]
[uf 0 5 65278][uf 2 1]You like gardening?[e]
[uf 0 5 65278][uf 2 1]Why am I here?[e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Ah, you have impeccable taste. I'm glad my efforts didn't go unappreciated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Unfortunately, I can feel my back giving out after all that hard work... Do you happen to know a good chiropractor?[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh, I wouldn't say it's a hobby of mine, really. The idea just popped into my head.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I mean, look at all this space we have here. It'd be a shame not to put it to use.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Oh? Are you not interested in this sort of thing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]Tending to plants can help calm the mind... or so they say. I don't have much gardening experience myself.[n][uf 1 1][e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]But I digress. There is, in fact, a reason I brought you here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I'd like you to use these planters however you see fit.[n][uf 1 1][e]

[msg MSG_007_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Although I did set them up, I'm afraid that I won't be able to tend to a garden as often as I'd like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I did mention it to Kirijo-kun, but it didn't catch on, I suppose, due to her upbringing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Besides, you're able to cook meals at the dorm, correct?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Well, now you can grow your own vegetables for healthy eating![n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds interesting.[e]
[uf 0 5 65278][uf 2 1]Sounds like a lot of work.[e]
[uf 0 5 65278][uf 2 1]I don't know how.[e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'm glad you think so. It would mean a lot to me if you made good use of the planters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Once you get started, you'll find there's a lot that can be done. Of course, you're free to do whatever you want.[n][uf 1 1][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Oh, I won't force you to work on this if you absolutely don't want to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I'm just giving you the option to do so. Come plant something whenever you feel like it.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, no need to worry your little head.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Just plant a couple and let nature take its course.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Here are some seedlings. Go ahead and plant them if you'd like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]You should be able to purchase other types of seedlings around the city. Feel free to experiment.[n][uf 1 1][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Well, that's everything. And now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]It's time to raise the roof and elevate this garden to new heights! And to top it off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Eat your veggies, peas![n][uf 1 1][e]

[msg MSG_037_0_0]
[uf 0 5 65278][uf 2 1]Temp tutorial message[n][uf 1 5 0]rooftop planters unlocked[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A number of days after planting a seedling, certain plants will be ready for harvest.[n][uf 1 1][e]

