[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Daaamn, this is some primo sushi![n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 2 0 0]The slices are huge![n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Man, I'm starving. Can we eat?[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Hey, where are Aigis-san and Ikutsuki-san?[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]He took her to the lab for a tune-up or something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]He said they'll join us later.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Hehe, the chairman just can't stay away from the lab, can he?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]That must be my father.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]We've been waiting for you.[n][uf 1 1][e]

[msg MSG_008_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]So it's finally over, then.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]That's right.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Wh-Who's he?[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Can't ya tell? That's Kirijo-senpai's dad. She looks exactly like him.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Y-You think so?[n][uf 1 1][e]

[msg MSG_013_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Congratulations, everyone. You've done well. No words can express my gratitude.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Though you'll never receive the recognition you deserve, your achievement was truly monumental.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Thank you, really.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MSG_016_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]To you, I owe a special thanks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]For lending us your power until the very end.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, i-it was no big deal.[n][uf 1 1][e]

[msg MSG_018_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Thanks to you, the twelve Shadows behind all this chaos have been destroyed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You've carried this burden long enough. You deserve a chance to experience the joys of youth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]As of midnight tonight, the Specialized Extracurricular Execution Squad will be disbanded.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Disbanded...[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 26 0 0]Oh, right...[n][uf 1 1][e]

[msg MSG_021_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]No longer must you risk your lives in battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Tomorrow, you can triumphantly return to a normal school life.[n][uf 1 1][e]

[msg MSG_022_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]...Is something the matter?[n][uf 1 1][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]Ah, it's nothin'.[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]All right, everyone. It's time to celebrate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 32 0 0]Your feast awaits. And don't worry about holding back. Eat as much as you'd like![n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 33 0 0]Sweet! Freakin' finally![n][uf 1 1][e]

