[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]You look half dead.[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 0 0 0 3 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]What are you doing out here?[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 0 0 0 5 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]When Mom died protecting me, no one believed the truth...[n][uf 1 1][e]

[msg MSG_004_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 7 0 0]To this day, they say she died in an accident that didn't even happen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 8 0 0]That's why I wanted to clear the record...[n][uf 1 1][e]

[msg MSG_004_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]I thought that's what she would've wanted... Maybe then she'd finally be at peace...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]They said he died in some violent crime, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]No one knows the truth... Just like with Mom.[n][uf 1 1][e]

[msg MSG_005_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 12 0 0]And now I'm going to be left behind, just like always...[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]The dead are never coming back. You have to accept that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]But you still have your life.[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 0 0 0 15 0 0]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]I'm not here to bring you back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]You can waste away here, if that's what you want.[n][uf 1 1][e]

[msg MSG_008_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]...But, if you still have the will to fight, then come back and stand on your own two feet.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 19 0 0]...I know that.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 20 0 0]I've known it all along... I've just been lying to myself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 21 0 0]I needed something to hate... to keep myself going.[n][uf 1 1][e]

[msg MSG_010_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 22 0 0]I couldn't face the thought of being alone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 23 0 0]But that's exactly what happened...[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 64 2 65535 0 0][uf 3 1 1 0 0 24 0 0]All this time, I've just been running away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 64 2 65535 0 0][uf 3 1 0 0 0 25 0 0]......[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 2 65535 0 0][uf 3 1 1 0 0 26 0 0]...All right.[n][uf 1 1][e]

[msg MSG_012_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 2 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm not running away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 2 65535 0 0][uf 3 1 1 0 0 28 0 0]I'm not running away anymore... I swear it.[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 2 65535 0 0][uf 3 1 1 0 0 29 0 0]Aragaki-san... I'll see this through to the end.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]The resolution in Amada's heart has awakened a new Persona...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Amada's Persona, [uf 0 1 35]Nemesis[uf 0 1 27], has given rise to [uf 0 1 35]Kala-Nemi[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 2 65535 0 0][uf 3 1 1 0 0 30 0 0]Goodbye, Mom... I'll be okay now.[n][uf 1 1][e]

