[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 1 0 0]Ahh... Got my sandals on, givin' my feet a chance to breathe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 2 0 0]Yup! Summer's here![n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 3 0 0]Darn. There's nothing out there I can use as a marker. Too bad. I was hoping for a good swim.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 4 0 0]Whoa, what's with that swimsuit!?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 5 0 0]What do you mean?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 6 0 0]Dude! Swim briefs? Nobody wants to see your junk.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 7 0 0]But they're better for swimming.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 102 65535 0 0][uf 3 1 1 0 0 8 0 0]You gotta be kidding me. We come all the way to the beach and you're gonna train?[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 102 65535 0 0][uf 3 1 1 0 0 9 0 0]What's wrong with that? You got a better idea?[n][uf 1 1][e]

[msg MSG_007_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 11 0][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 102 65535 0 0][uf 3 1 1 0 0 10 0 0]Damn right, I do! It's summertime at the beach! I've got the perfect activity![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]Wow, it's beautiful![n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 12 0 0]Oh hey, they're here![n][uf 1 1][e]

