[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1006 0 0]Is something the matter, Amada-kun? Everyone's heading back now.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]Sorry, I got distracted. There's just a lot on my mind...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]Yeah, I know. It's a lot to take in, but you don't have to think so hard about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]All we can do is keep exploring, so let's just focus on the road ahead of us.[n][uf 1 1][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]I know how you feel, but... All we can do is focus on exploring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]We don't have any other choice.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Is that really true, though?[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]I mean, this place is a reflection of our own minds, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Something tells me that it's going to take more than just exploration to get out of here.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1065 0 0]Amada-kun...[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]I want to understand why all of this is happening. How did we end up here?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]...Maybe you're right.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7057 0 0]Sorry, I didn't mean for it to sound like you were in the wrong![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]Nah, don't worry about it. Honestly, you made a really good point.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]Anyway, we're a team, right? It's important for us to speak our minds like this.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7030 0 0][uf 4 23 0 1 0 25 25]...Yeah, I agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 4 23 0 1 3 25 25]I'm not very good at it, though. I have a bad habit of keeping things like this bottled up...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 4 23 0 1 0 25 25]I didn't have anyone I could talk to before, but... It's different now.[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7040 0 0]I have to remember—I'm not alone anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]Thank you, Yukari-san.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]I didn't even do anything, though...[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]I wouldn't say that! I actually feel a lot better after talking to you. Anyway, I'll head back now and prep for our next trip.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 3 0 65535 1094 0 0]...Things are different now, huh.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 4 25 2]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]I'm not alone, either. I know that, but...[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1084 0 0]Oh... It's starting to make sense.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]I'm not just on edge...[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]All this time, I've been hurting inside...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]...I better head back. There's no time to dwell on this right now.[n][uf 1 1][e]

