[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]In the wake of your recent expedition, I bear news which may be of interest to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It seems that at this moment, your bonds will have a uniquely beneficial effect on the creation of new Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If you wish to take advantage of this opportunity, please visit the Velvet Room.[n][uf 1 1][e]

