[msg ItemAddEffectMSG_000]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg ItemAddEffectMSG_001]
[uf 0 5 65278][uf 2 1]+10 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_002]
[uf 0 5 65278][uf 2 1]+20 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_003]
[uf 0 5 65278][uf 2 1]+30 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_004]
[uf 0 5 65278][uf 2 1]+40 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_005]
[uf 0 5 65278][uf 2 1]+50 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_006]
[uf 0 5 65278][uf 2 1]+100 HP[n][uf 1 1][e]

[msg ItemAddEffectMSG_007]
[uf 0 5 65278][uf 2 1]+10 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_008]
[uf 0 5 65278][uf 2 1]+20 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_009]
[uf 0 5 65278][uf 2 1]+30 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_010]
[uf 0 5 65278][uf 2 1]+40 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_011]
[uf 0 5 65278][uf 2 1]+50 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_012]
[uf 0 5 65278][uf 2 1]+100 SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_013]
[uf 0 5 65278][uf 2 1]+Freeze (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_014]
[uf 0 5 65278][uf 2 1]+Freeze (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_015]
[uf 0 5 65278][uf 2 1]+Freeze (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_016]
[uf 0 5 65278][uf 2 1]+Shock (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_017]
[uf 0 5 65278][uf 2 1]+Shock (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_018]
[uf 0 5 65278][uf 2 1]+Shock (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_019]
[uf 0 5 65278][uf 2 1]+Confuse (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_020]
[uf 0 5 65278][uf 2 1]+Confuse (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_021]
[uf 0 5 65278][uf 2 1]+Confuse (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_022]
[uf 0 5 65278][uf 2 1]+Fear (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_023]
[uf 0 5 65278][uf 2 1]+Fear (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_024]
[uf 0 5 65278][uf 2 1]+Fear (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_025]
[uf 0 5 65278][uf 2 1]+Distress (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_026]
[uf 0 5 65278][uf 2 1]+Distress (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_027]
[uf 0 5 65278][uf 2 1]+Distress (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_028]
[uf 0 5 65278][uf 2 1]+Charm (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_029]
[uf 0 5 65278][uf 2 1]+Charm (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_030]
[uf 0 5 65278][uf 2 1]+Charm (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_031]
[uf 0 5 65278][uf 2 1]+Rage (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_032]
[uf 0 5 65278][uf 2 1]+Rage (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_033]
[uf 0 5 65278][uf 2 1]+Rage (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_034]
[uf 0 5 65278][uf 2 1]+Poison (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_035]
[uf 0 5 65278][uf 2 1]+Poison (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_036]
[uf 0 5 65278][uf 2 1]+Poison (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_037]
[uf 0 5 65278][uf 2 1]+Random ailment (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_038]
[uf 0 5 65278][uf 2 1]+Random ailment (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_039]
[uf 0 5 65278][uf 2 1]+Random ailment (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_040]
[uf 0 5 65278][uf 2 1]+Critical rate up (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_041]
[uf 0 5 65278][uf 2 1]+Critical rate up (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_042]
[uf 0 5 65278][uf 2 1]+Critical rate up (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_043]
[uf 0 5 65278][uf 2 1]+Slash Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_044]
[uf 0 5 65278][uf 2 1]+Strike Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_045]
[uf 0 5 65278][uf 2 1]+Pierce Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_046]
[uf 0 5 65278][uf 2 1]+Fire Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_047]
[uf 0 5 65278][uf 2 1]+Ice Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_048]
[uf 0 5 65278][uf 2 1]+Elec Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_049]
[uf 0 5 65278][uf 2 1]+Wind Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_050]
[uf 0 5 65278][uf 2 1]+Light Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_051]
[uf 0 5 65278][uf 2 1]+Dark Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_052]
[uf 0 5 65278][uf 2 1]+Counter[n][uf 1 1][e]

[msg ItemAddEffectMSG_053]
[uf 0 5 65278][uf 2 1]+Counterstrike[n][uf 1 1][e]

[msg ItemAddEffectMSG_054]
[uf 0 5 65278][uf 2 1]+High Counter[n][uf 1 1][e]

[msg ItemAddEffectMSG_055]
[uf 0 5 65278][uf 2 1]+Resist Freeze[n][uf 1 1][e]

[msg ItemAddEffectMSG_056]
[uf 0 5 65278][uf 2 1]+Resist Shock[n][uf 1 1][e]

[msg ItemAddEffectMSG_057]
[uf 0 5 65278][uf 2 1]+Resist Confuse[n][uf 1 1][e]

[msg ItemAddEffectMSG_058]
[uf 0 5 65278][uf 2 1]+Resist Fear[n][uf 1 1][e]

[msg ItemAddEffectMSG_059]
[uf 0 5 65278][uf 2 1]+Resist Distress[n][uf 1 1][e]

[msg ItemAddEffectMSG_060]
[uf 0 5 65278][uf 2 1]+Resist Charm[n][uf 1 1][e]

[msg ItemAddEffectMSG_061]
[uf 0 5 65278][uf 2 1]+Resist Rage[n][uf 1 1][e]

[msg ItemAddEffectMSG_062]
[uf 0 5 65278][uf 2 1]+Resist Poison[n][uf 1 1][e]

[msg ItemAddEffectMSG_063]
[uf 0 5 65278][uf 2 1]+Resist Dizzy[n][uf 1 1][e]

[msg ItemAddEffectMSG_064]
[uf 0 5 65278][uf 2 1]+Null Freeze[n][uf 1 1][e]

[msg ItemAddEffectMSG_065]
[uf 0 5 65278][uf 2 1]+Null Shock[n][uf 1 1][e]

[msg ItemAddEffectMSG_066]
[uf 0 5 65278][uf 2 1]+Null Confuse[n][uf 1 1][e]

[msg ItemAddEffectMSG_067]
[uf 0 5 65278][uf 2 1]+Null Fear[n][uf 1 1][e]

[msg ItemAddEffectMSG_068]
[uf 0 5 65278][uf 2 1]+Null Distress[n][uf 1 1][e]

[msg ItemAddEffectMSG_069]
[uf 0 5 65278][uf 2 1]+Null Charm[n][uf 1 1][e]

[msg ItemAddEffectMSG_070]
[uf 0 5 65278][uf 2 1]+Null Rage[n][uf 1 1][e]

[msg ItemAddEffectMSG_071]
[uf 0 5 65278][uf 2 1]+Null Poison[n][uf 1 1][e]

[msg ItemAddEffectMSG_072]
[uf 0 5 65278][uf 2 1]+Null Dizzy[n][uf 1 1][e]

[msg ItemAddEffectMSG_073]
[uf 0 5 65278][uf 2 1]+Auto Tarukaja[n][uf 1 1][e]

[msg ItemAddEffectMSG_074]
[uf 0 5 65278][uf 2 1]+Auto Rakukaja[n][uf 1 1][e]

[msg ItemAddEffectMSG_075]
[uf 0 5 65278][uf 2 1]+Auto Sukukaja[n][uf 1 1][e]

[msg ItemAddEffectMSG_076]
[uf 0 5 65278][uf 2 1]+Reduce Slash dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_077]
[uf 0 5 65278][uf 2 1]+Reduce Slash dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_078]
[uf 0 5 65278][uf 2 1]+Reduce Slash dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_079]
[uf 0 5 65278][uf 2 1]+Reduce Strike dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_080]
[uf 0 5 65278][uf 2 1]+Reduce Strike dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_081]
[uf 0 5 65278][uf 2 1]+Reduce Strike dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_082]
[uf 0 5 65278][uf 2 1]+Reduce Pierce dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_083]
[uf 0 5 65278][uf 2 1]+Reduce Pierce dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_084]
[uf 0 5 65278][uf 2 1]+Reduce Pierce dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_085]
[uf 0 5 65278][uf 2 1]+Reduce phys dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_086]
[uf 0 5 65278][uf 2 1]+Reduce phys dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_087]
[uf 0 5 65278][uf 2 1]+Reduce phys dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_088]
[uf 0 5 65278][uf 2 1]+Reduce Fire dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_089]
[uf 0 5 65278][uf 2 1]+Reduce Fire dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_090]
[uf 0 5 65278][uf 2 1]+Reduce Fire dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_091]
[uf 0 5 65278][uf 2 1]+Reduce Ice dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_092]
[uf 0 5 65278][uf 2 1]+Reduce Ice dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_093]
[uf 0 5 65278][uf 2 1]+Reduce Ice dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_094]
[uf 0 5 65278][uf 2 1]+Reduce Elec dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_095]
[uf 0 5 65278][uf 2 1]+Reduce Elec dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_096]
[uf 0 5 65278][uf 2 1]+Reduce Elec dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_097]
[uf 0 5 65278][uf 2 1]+Reduce Wind dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_098]
[uf 0 5 65278][uf 2 1]+Reduce Wind dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_099]
[uf 0 5 65278][uf 2 1]+Reduce Wind dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_100]
[uf 0 5 65278][uf 2 1]+Reduce Light dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_101]
[uf 0 5 65278][uf 2 1]+Reduce Light dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_102]
[uf 0 5 65278][uf 2 1]+Reduce Light dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_103]
[uf 0 5 65278][uf 2 1]+Reduce Dark dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_104]
[uf 0 5 65278][uf 2 1]+Reduce Dark dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_105]
[uf 0 5 65278][uf 2 1]+Reduce Dark dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_106]
[uf 0 5 65278][uf 2 1]+Reduce magic dmg (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_107]
[uf 0 5 65278][uf 2 1]+Reduce magic dmg (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_108]
[uf 0 5 65278][uf 2 1]+Reduce magic dmg (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_109]
[uf 0 5 65278][uf 2 1]+Slash evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_110]
[uf 0 5 65278][uf 2 1]+Slash evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_111]
[uf 0 5 65278][uf 2 1]+Slash evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_112]
[uf 0 5 65278][uf 2 1]+Strike evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_113]
[uf 0 5 65278][uf 2 1]+Strike evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_114]
[uf 0 5 65278][uf 2 1]+Strike evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_115]
[uf 0 5 65278][uf 2 1]+Pierce evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_116]
[uf 0 5 65278][uf 2 1]+Pierce evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_117]
[uf 0 5 65278][uf 2 1]+Pierce evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_118]
[uf 0 5 65278][uf 2 1]+Physical evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_119]
[uf 0 5 65278][uf 2 1]+Physical evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_120]
[uf 0 5 65278][uf 2 1]+Physical evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_121]
[uf 0 5 65278][uf 2 1]+Fire evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_122]
[uf 0 5 65278][uf 2 1]+Fire evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_123]
[uf 0 5 65278][uf 2 1]+Fire evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_124]
[uf 0 5 65278][uf 2 1]+Ice evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_125]
[uf 0 5 65278][uf 2 1]+Ice evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_126]
[uf 0 5 65278][uf 2 1]+Ice evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_127]
[uf 0 5 65278][uf 2 1]+Electricity evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_128]
[uf 0 5 65278][uf 2 1]+Electricity evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_129]
[uf 0 5 65278][uf 2 1]+Electricity evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_130]
[uf 0 5 65278][uf 2 1]+Wind evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_131]
[uf 0 5 65278][uf 2 1]+Wind evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_132]
[uf 0 5 65278][uf 2 1]+Wind evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_133]
[uf 0 5 65278][uf 2 1]+Light evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_134]
[uf 0 5 65278][uf 2 1]+Light evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_135]
[uf 0 5 65278][uf 2 1]+Light evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_136]
[uf 0 5 65278][uf 2 1]+Dark evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_137]
[uf 0 5 65278][uf 2 1]+Dark evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_138]
[uf 0 5 65278][uf 2 1]+Dark evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_139]
[uf 0 5 65278][uf 2 1]+Magic evasion (low)[n][uf 1 1][e]

[msg ItemAddEffectMSG_140]
[uf 0 5 65278][uf 2 1]+Magic evasion (med)[n][uf 1 1][e]

[msg ItemAddEffectMSG_141]
[uf 0 5 65278][uf 2 1]+Magic evasion (high)[n][uf 1 1][e]

[msg ItemAddEffectMSG_142]
[uf 0 5 65278][uf 2 1]+50% EXP[n][uf 1 1][e]

[msg ItemAddEffectMSG_143]
[uf 0 5 65278][uf 2 1]+15% EXP[n][uf 1 1][e]

[msg ItemAddEffectMSG_144]
[uf 0 5 65278][uf 2 1]+Slash damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_145]
[uf 0 5 65278][uf 2 1]+Strike damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_146]
[uf 0 5 65278][uf 2 1]+Pierce damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_147]
[uf 0 5 65278][uf 2 1]+Fire damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_148]
[uf 0 5 65278][uf 2 1]+Ice damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_149]
[uf 0 5 65278][uf 2 1]+Electricity damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_150]
[uf 0 5 65278][uf 2 1]+Wind damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_151]
[uf 0 5 65278][uf 2 1]+Light damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_152]
[uf 0 5 65278][uf 2 1]+Dark damage up[n][uf 1 1][e]

[msg ItemAddEffectMSG_153]
[uf 0 5 65278][uf 2 1]+Slash defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_154]
[uf 0 5 65278][uf 2 1]+Strike defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_155]
[uf 0 5 65278][uf 2 1]+Pierce defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_156]
[uf 0 5 65278][uf 2 1]+Fire defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_157]
[uf 0 5 65278][uf 2 1]+Ice defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_158]
[uf 0 5 65278][uf 2 1]+Electricity defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_159]
[uf 0 5 65278][uf 2 1]+Wind defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_160]
[uf 0 5 65278][uf 2 1]+Light defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_161]
[uf 0 5 65278][uf 2 1]+Dark defense up[n][uf 1 1][e]

[msg ItemAddEffectMSG_162]
[uf 0 5 65278][uf 2 1]+Attack when enraged[n][uf 1 1][e]

[msg ItemAddEffectMSG_163]
[uf 0 5 65278][uf 2 1]+Regenerate 1[n][uf 1 1][e]

[msg ItemAddEffectMSG_164]
[uf 0 5 65278][uf 2 1]+Regenerate 2[n][uf 1 1][e]

[msg ItemAddEffectMSG_165]
[uf 0 5 65278][uf 2 1]+Regenerate 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_166]
[uf 0 5 65278][uf 2 1]+Invigorate 1[n][uf 1 1][e]

[msg ItemAddEffectMSG_167]
[uf 0 5 65278][uf 2 1]+Invigorate 2[n][uf 1 1][e]

[msg ItemAddEffectMSG_168]
[uf 0 5 65278][uf 2 1]+Invigorate 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_169]
[uf 0 5 65278][uf 2 1]+Null Light instakill[n][uf 1 1][e]

[msg ItemAddEffectMSG_170]
[uf 0 5 65278][uf 2 1]+Null Dark instakill[n][uf 1 1][e]

[msg ItemAddEffectMSG_171]
[uf 0 5 65278][uf 2 1]+Ali Dance[n][uf 1 1][e]

[msg ItemAddEffectMSG_172]
[uf 0 5 65278][uf 2 1]+Null all except Almighty[n][uf 1 1][e]

[msg ItemAddEffectMSG_173]
[uf 0 5 65278][uf 2 1]+Firm Stance[n][uf 1 1][e]

[msg ItemAddEffectMSG_174]
[uf 0 5 65278][uf 2 1]+Soul Chain[n][uf 1 1][e]

[msg ItemAddEffectMSG_175]
[uf 0 5 65278][uf 2 1]+All-Out Attack dmg up[n][uf 1 1][e]

[msg ItemAddEffectMSG_176]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg ItemAddEffectMSG_177]
[uf 0 5 65278][uf 2 1]+Null Slash[n][uf 1 1][e]

[msg ItemAddEffectMSG_178]
[uf 0 5 65278][uf 2 1]+Null Strike[n][uf 1 1][e]

[msg ItemAddEffectMSG_179]
[uf 0 5 65278][uf 2 1]+Null Pierce[n][uf 1 1][e]

[msg ItemAddEffectMSG_180]
[uf 0 5 65278][uf 2 1]+Null Fire[n][uf 1 1][e]

[msg ItemAddEffectMSG_181]
[uf 0 5 65278][uf 2 1]+Null Ice[n][uf 1 1][e]

[msg ItemAddEffectMSG_182]
[uf 0 5 65278][uf 2 1]+Null Elec[n][uf 1 1][e]

[msg ItemAddEffectMSG_183]
[uf 0 5 65278][uf 2 1]+Null Wind[n][uf 1 1][e]

[msg ItemAddEffectMSG_184]
[uf 0 5 65278][uf 2 1]+Null Light[n][uf 1 1][e]

[msg ItemAddEffectMSG_185]
[uf 0 5 65278][uf 2 1]+Null Dark[n][uf 1 1][e]

[msg ItemAddEffectMSG_186]
[uf 0 5 65278][uf 2 1]+Slash Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_187]
[uf 0 5 65278][uf 2 1]+Strike Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_188]
[uf 0 5 65278][uf 2 1]+Pierce Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_189]
[uf 0 5 65278][uf 2 1]+Fire Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_190]
[uf 0 5 65278][uf 2 1]+Ice Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_191]
[uf 0 5 65278][uf 2 1]+Elec Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_192]
[uf 0 5 65278][uf 2 1]+Wind Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_193]
[uf 0 5 65278][uf 2 1]+Light Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_194]
[uf 0 5 65278][uf 2 1]+Dark Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_195]
[uf 0 5 65278][uf 2 1]+Resist Ailments[n][uf 1 1][e]

[msg ItemAddEffectMSG_196]
[uf 0 5 65278][uf 2 1]+Unshaken Will[n][uf 1 1][e]

[msg ItemAddEffectMSG_197]
[uf 0 5 65278][uf 2 1]+Fast Heal[n][uf 1 1][e]

[msg ItemAddEffectMSG_198]
[uf 0 5 65278][uf 2 1]+Insta-Heal[n][uf 1 1][e]

[msg ItemAddEffectMSG_199]
[uf 0 5 65278][uf 2 1]+Life Aid[n][uf 1 1][e]

[msg ItemAddEffectMSG_200]
[uf 0 5 65278][uf 2 1]+Endure[n][uf 1 1][e]

[msg ItemAddEffectMSG_201]
[uf 0 5 65278][uf 2 1]+Enduring Soul[n][uf 1 1][e]

[msg ItemAddEffectMSG_202]
[uf 0 5 65278][uf 2 1]+Arms Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_203]
[uf 0 5 65278][uf 2 1]+Spell Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_204]
[uf 0 5 65278][uf 2 1]+Apt Pupil[n][uf 1 1][e]

[msg ItemAddEffectMSG_205]
[uf 0 5 65278][uf 2 1]+Sharp Student[n][uf 1 1][e]

[msg ItemAddEffectMSG_206]
[uf 0 5 65278][uf 2 1]+Freeze Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_207]
[uf 0 5 65278][uf 2 1]+Shock Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_208]
[uf 0 5 65278][uf 2 1]+Confuse Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_209]
[uf 0 5 65278][uf 2 1]+Fear Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_210]
[uf 0 5 65278][uf 2 1]+Distress Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_211]
[uf 0 5 65278][uf 2 1]+Charm Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_212]
[uf 0 5 65278][uf 2 1]+Rage Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_213]
[uf 0 5 65278][uf 2 1]+Poison Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_214]
[uf 0 5 65278][uf 2 1]+Survive Light[n][uf 1 1][e]

[msg ItemAddEffectMSG_215]
[uf 0 5 65278][uf 2 1]+Endure Light[n][uf 1 1][e]

[msg ItemAddEffectMSG_216]
[uf 0 5 65278][uf 2 1]+Survive Dark[n][uf 1 1][e]

[msg ItemAddEffectMSG_217]
[uf 0 5 65278][uf 2 1]+Endure Dark[n][uf 1 1][e]

[msg ItemAddEffectMSG_218]
[uf 0 5 65278][uf 2 1]+Survival Trick[n][uf 1 1][e]

[msg ItemAddEffectMSG_219]
[uf 0 5 65278][uf 2 1]+Auto Mataru[n][uf 1 1][e]

[msg ItemAddEffectMSG_220]
[uf 0 5 65278][uf 2 1]+Auto Maraku[n][uf 1 1][e]

[msg ItemAddEffectMSG_221]
[uf 0 5 65278][uf 2 1]+Auto Masuku[n][uf 1 1][e]

[msg ItemAddEffectMSG_222]
[uf 0 5 65278][uf 2 1]+Auto Rebellion[n][uf 1 1][e]

[msg ItemAddEffectMSG_223]
[uf 0 5 65278][uf 2 1]+Anti-Fire Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_224]
[uf 0 5 65278][uf 2 1]+Anti-Ice Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_225]
[uf 0 5 65278][uf 2 1]+Anti-Electric Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_226]
[uf 0 5 65278][uf 2 1]+Anti-Wind Master[n][uf 1 1][e]

[msg ItemAddEffectMSG_227]
[uf 0 5 65278][uf 2 1]+Soul Shift[n][uf 1 1][e]

[msg ItemAddEffectMSG_228]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg ItemAddEffectMSG_229]
[uf 0 5 65278][uf 2 1]+Soul Link[n][uf 1 1][e]

[msg ItemAddEffectMSG_230]
[uf 0 5 65278][uf 2 1]+Shift Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_231]
[uf 0 5 65278][uf 2 1]+Shift Amp[n][uf 1 1][e]

[msg ItemAddEffectMSG_232]
[uf 0 5 65278][uf 2 1]+Dmg on downed enemy[n][uf 1 1][e]

[msg ItemAddEffectMSG_233]
[uf 0 5 65278][uf 2 1]+Dizzy Boost[n][uf 1 1][e]

[msg ItemAddEffectMSG_234]
[uf 0 5 65278][uf 2 1]Ignore enemy resistances[n][uf 1 1][e]

[msg ItemAddEffectMSG_235]
[uf 0 5 65278][uf 2 1]Orgia duration +1 turn[n][uf 1 1][e]

[msg ItemAddEffectMSG_236]
[uf 0 5 65278][uf 2 1]Faster overheat recovery[n][uf 1 1][e]

[msg ItemAddEffectMSG_237_0_0]
[uf 0 5 65278][uf 2 1]Strength[n][uf 1 1][e]

[msg ItemAddEffectMSG_238_0_0]
[uf 0 5 65278][uf 2 1]Magic[n][uf 1 1][e]

[msg ItemAddEffectMSG_239_0_0]
[uf 0 5 65278][uf 2 1]Endurance[n][uf 1 1][e]

[msg ItemAddEffectMSG_240_0_0]
[uf 0 5 65278][uf 2 1]Agility[n][uf 1 1][e]

[msg ItemAddEffectMSG_241_0_0]
[uf 0 5 65278][uf 2 1]Luck[n][uf 1 1][e]

[msg ItemAddEffectMSG_242_0_0]
[uf 0 5 65278][uf 2 1]All stats[n][uf 1 1][e]

[msg ItemAddEffectMSG_243_0_0]
[uf 0 5 65278][uf 2 1]+[n][uf 1 1][e]

[msg ItemAddEffectMSG_244_0_0]
[uf 0 5 65278][uf 2 1]-[n][uf 1 1][e]

[msg ItemAddEffectMSG_245_0_0]
[uf 0 5 65278][uf 2 1]/[n][uf 1 1][e]

[msg ItemAddEffectMSG_246_0_0]
[uf 0 5 65278][uf 2 1]Effect[n][uf 1 1][e]

[msg ItemAddEffectMSG_247_0_0]
[uf 0 5 65278][uf 2 1]Usable[n][uf 1 1][e]

[msg ItemAddEffectMSG_248_0_0]
[uf 0 5 65278][uf 2 1]+100 HP and SP[n][uf 1 1][e]

[msg ItemAddEffectMSG_249_0_0]
[uf 0 5 65278][uf 2 1]+Auto Tarukabellion[n][uf 1 1][e]

[msg ItemAddEffectMSG_250_0_0]
[uf 0 5 65278][uf 2 1]+Auto Charge[n][uf 1 1][e]

[msg ItemAddEffectMSG_251_0_0]
[uf 0 5 65278][uf 2 1]+Auto Concentrate[n][uf 1 1][e]

[msg ItemAddEffectMSG_252_0_0]
[uf 0 5 65278][uf 2 1]+Auto Heat Riser[n][uf 1 1][e]

[msg ItemAddEffectMSG_253_0_0]
[uf 0 5 65278][uf 2 1]Regenerate 3/Invigorate 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_254_0_0]
[uf 0 5 65278][uf 2 1]+Magic Ability[n][uf 1 1][e]

[msg ItemAddEffectMSG_255_0_0]
[uf 0 5 65278][uf 2 1]+Null all ailments[n][uf 1 1][e]

