[msg MSG_ARBEIT_CAFE]
[uf 0 5 65278][uf 2 1]Serve coffee that boosts a person's charm![n]Time: Night[n]Pay: ¥2,500+ daily[n]Location: Paulownia Mall[n][uf 1 1][e]

[msg MSG_ARBEIT_SKILLSHOP]
[uf 0 5 65278][uf 2 1]Those with knowledge of minerals welcome![n]Time: Day[n]Pay: ¥3,500+ daily[n]Location: Paulownia Mall[n][uf 1 1][e]

[msg MSG_ARBEIT_MOVIE]
[uf 0 5 65278][uf 2 1]Inspire people to learn and be courageous![n]Time: Day[n]Pay: ¥5,000+ daily[n]Location: In front of Port Island Station[n][uf 1 1][e]

