[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I've got a text message...[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I've got a few messages...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I'll head to the shrine when it's time.[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]UNUSED[e]
[uf 0 5 65278][uf 2 1]UNUSED[e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]UNUSED[e]
[uf 0 5 65278][uf 2 1]UNUSED[e]

[msg MND_007_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]DEVL UNUSED[n][uf 1 5 0]Please use MND_002_0_0[n][uf 1 1][e]

