[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Aigis... Here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]I know that you'll do what's best for everyone, so I'm with you all the way.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 3 0 0]This must be... the true key...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 4 0 0]You're all okay![n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 5 0 0]This may sound strange, given the circumstances, but... I'm so glad you're all safe.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Ha... Yeah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]So...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 8 0 0]You really... don't want to go back...?[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Wh— Hey![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 10 0 0]I want him back...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 11 0 0]I want him back! I don't care about anything else! I just want him to come back![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 12 0 0]I tried... so hard to be strong, and to look forward, and just accept it all, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 13 0 0]I can't... I can't do it! I just can't![n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 64 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Yukari-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 64 52 65535 0 0][uf 3 1 1 0 0 16 0 0]That's not...[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 17 0 0]I made him a promise, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 18 0 0]I told him I'd do my best to change this world, so people would stop wishing for the Fall...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 19 0 0]That's why I wanted to move on from the past and just focus on the future...[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 20 0 0]Yukari-san...[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 21 0 0]But...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 22 0 0]That was just a promise to myself, not to him... So it... It can't end like that![n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Yukari...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 24 0 0]It's hard... Unbearably hard. But if you don't face that pain, it will never heal.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 25 0 0]So, what, if I face it, it'll suddenly be okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 26 0 0]I'll just accept that he's gone, or forget all about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 27 0 0]That won't happen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 28 0 0]All of us should know by now... That never happens![n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 29 0 0]You face your pain because it'll never truly go away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Yukari... Would you help me fulfill the promise I made to him?[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 31 0 0]What...?[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 32 0 0]It was more a promise to myself, like yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 33 0 0]He... taught me so much. And showed me so many things that I've come to treasure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 34 0 0]But before I could thank him... He was gone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 35 0 0]The regret was... suffocating. So, I promised myself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 36 0 0]I would always be there for the ones I care about, and fight to protect them, no matter the cost.[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 37 0 0]And you're someone I care about, Yukari.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 38 0 0]What...? Me?[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 39 0 0]You may not have thought much of it, but to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 40 0 0]Last year, when you refused to give up on me and gave me something to fight for again... I will never forget that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 41 0 0]So this time, I... We... want to be here for you.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 42 0 0]Mitsuru-senpai, I...[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 43 0 0]The pain of losing someone close to you is terrible... But you don't have to hold it in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 44 0 0]And, Yukari... You've kept yours locked up for too long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 45 0 0]You've been trying so hard to push forward... that you never stopped to grieve.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 46 0 0]Ah... Ah...[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 47 0 0]It's all right. We're here for you. Your friends are here for you.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 52 65535 0 0][uf 3 1 1 0 0 48 0 0]Ah... Ahh... Aaaahhhhhhhhhh![n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 49 0 0]Yukari-san... I want him to come back too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 50 0 0]But... I stopped to think about everything, like you told us to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 51 0 0]And I realized something... So please, I'd like you to listen.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 52 0 0]I want to know what exactly he did... in that moment he used his power.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 53 0 0]We still aren't entirely sure what really happened to him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 54 0 0]I think we should know that before making a choice... So I won't use the key just yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 55 0 0]This is the answer I arrived at... after learning everyone else's feelings.[n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 56 0 0]Huh... "What really happened"...[n][uf 1 1][e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 57 0 0]I agree. We should know the whole story before acting.[n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 58 0 0]Sounds good to me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 59 0 0][uf 4 23 0 1 0 25 25]But, uh... Can we even do that?[n][uf 1 1][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 60 0 0]I'm not sure... All the doors to the past are gone, except the one to his room...[n][uf 1 1][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 61 0 0]There's actually one more, remember? We've been using it this whole time.[n][uf 1 1][e]

[msg MSG_034_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 52 65535 0 0][uf 3 1 1 0 0 62 0 0]That's right... The door to Paulownia Mall![n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 63 0 0]"The doors reflect the minds of those who pass through"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 64 0 0]If we wish strongly enough to look into the past, that door should allow us to do so.[n][uf 1 1][e]

[msg MSG_036_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 65 0 0]I see... It would certainly be worth a try.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 66 0 0]Is something wrong?[n][uf 1 1][e]

[msg MSG_038_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 67 0 0]I was just thinking... I don't really have a reason to be here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 68 0 0]And I... I did some horrible things to you all, so... I shouldn't go with you...[n][uf 1 1][e]

[msg MSG_039_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 69 0 0]Dude, what're you even talkin' about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 70 0 0]We got ourselves into this mess! None of this is on you.[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 71 0 0]Yeah, it's our own fault we got trapped here, and for squabbling with each other too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 72 0 0]You're sticking with us, whether you like it or not.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 73 0 0]Don't you remember? I told you I won't leave you behind.[n][uf 1 1][e]

[msg MSG_042_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 74 0 0]Ah...![n][uf 1 1][e]

[msg MSG_043_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 1 0 0 75 0 0]Now that I think about it, it's pretty lucky there's still that one door left, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 1 0 0 76 0 0]It almost seems too good to be a coincidence.[n][uf 1 1][e]

[msg MSG_044_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 77 0 0]Huh... Actually, that is unusual...[n][uf 1 1][e]

[msg MSG_045_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 78 0 0]If its purpose was to prepare everyone for battle, why is it still here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 79 0 0]We have the true key, so the fighting should be over. But the door hasn't disappeared...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 80 0 0]So then... Does it have another purpose...?[n][uf 1 1][e]

[msg MSG_046_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 81 0 0]I suppose it would make sense...[n][uf 1 1][e]

[msg MSG_047_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 82 0 0]If that door hasn't fulfilled its purpose of preparing us for combat...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 83 0 0]Perhaps there's still an enemy for us to defeat...?[n][uf 1 1][e]

[msg MSG_048_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 84 0 0]Our own feelings were the cause of this situation...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 85 0 0]And Aigis's proposal would take us to the source of that pain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 86 0 0]I wouldn't be surprised to find something waiting for us there.[n][uf 1 1][e]

[msg MSG_049_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 0 0 0 87 0 0]......[n][uf 1 1][e]

[msg MSG_050_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 88 0 0]So... What should we do? Come up with another plan?[n][uf 1 1][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 89 0 0]If there is something there... that's even more reason for us to go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 90 0 0]That's what I think.[n][uf 1 1][e]

[msg MSG_052_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 91 0 0]Then this should be our final battle.[n][uf 1 1][e]

[msg MSG_053_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 92 0 0]Ha, that sounds familiar... Feels like January again.[n][uf 1 1][e]

[msg MSG_054_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 93 0 0]I wonder what is waiting for us... Another large Shadow, maybe?[n][uf 1 1][e]

[msg MSG_055_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 94 0 0]No point thinking about it. We just gotta beat it, no matter what it is.[n][uf 1 1][e]

[msg MSG_056_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 1 0 0 95 0 0]Arf![n][uf 1 1][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 1 0 0 96 0 0]That's right! And I'll support you all as best as I can![n][uf 1 1][e]

[msg MSG_058_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 97 0 0]Okay, then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 98 0 0]When we work together, there's nothing we can't do. Now, let's go![n][uf 1 1][e]

[msg MND_059_0_0]
[uf 0 5 65278][uf 2 1]There's only one door left...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The door leading to Paulownia[n]Mall... We should get on our way.[n][uf 1 1][e]

