[msg MSG_000_0_0 [Theme Poem]]
[uf 0 5 65278][uf 2 1]Time never waits.[n]It delivers all equally to the same end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]You, who wish to safeguard the future, however limited it may be...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]You will be given one year;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]go forth without falter,[n]with your heart as your guide...[n][uf 1 1][e]

[msg MSG_001_0_0 [（ＳＥ）ガヤ男Ａ]]
[uf 0 5 65278][uf 2 1]ほら、こーいうフツーの醤油が[n]うまいのが名店なのよ。[n][uf 1 1][e]

[msg MSG_002_0_0 [（ＳＥ）ガヤ女Ａ]]
[uf 0 5 65278][uf 2 1]マジー？　つかノブ君、[n]普段あんまラーメンとか食べなくない？[n][uf 1 1][e]

[msg MSG_003_0_0 [（ＳＥ）ガヤ男Ｂ]]
[uf 0 5 65278][uf 2 1]そんなの常識じゃね？[n][uf 1 1][e]

[msg MSG_004_0_0 [（ＳＥ）ガヤ女Ｂ]]
[uf 0 5 65278][uf 2 1]コレ、超良くない！？[n][uf 1 1][e]

[msg MSG_005_0_0 [（ＳＥ）ガヤ女Ｃ]]
[uf 0 5 65278][uf 2 1]えー何？　みしてみしてー！[n][uf 1 1][e]

[msg MSG_006_0_0 [（ＳＥ）ガヤ女Ｄ]]
[uf 0 5 65278][uf 2 1]ヤバい、何コレ！？　カワイーー！[n][uf 1 1][e]

[msg MSG_007_0_0 [（ＳＥ）ホットペーパーの女]]
[uf 0 5 65278][uf 2 1]どうぞー。[n][uf 1 1][e]

[msg MSG_008_0_0 [（ＳＥ）ガヤ男Ｂ]]
[uf 0 5 65278][uf 2 1]しらねえの？　ダサ…[n][uf 1 1][e]

[msg MSG_009_0_0 [（ＳＥ）ガヤ男Ｃ]]
[uf 0 5 65278][uf 2 1]マジこいつ？[n][uf 1 1][e]

[msg MSG_010_0_0 [（ＳＥ）ガヤ男Ｄ]]
[uf 0 5 65278][uf 2 1]何？　今から行くの？[n][uf 1 1][e]

[msg MSG_011_0_0 [（ＳＥ）携帯会話の男Ａ]]
[uf 0 5 65278][uf 2 1]あー暇暇。すぐ行くわー。[n][uf 1 1][e]

[msg MSG_012_0_0 [Female Student]]
[uf 0 5 65278][uf 2 1]*gasp* *gasp*[n][uf 1 1][e]

[msg MSG_012_3_0 [Female Student]]
[uf 0 5 65278][uf 2 1]Just put it... to my head...[n][uf 1 1][e]

[msg MSG_012_5_0 [Female Student]]
[uf 0 5 65278][uf 2 1]And then pull the trigger...[n][uf 1 1][e]

[msg MSG_012_7_0 [Female Student]]
[uf 0 5 65278][uf 2 1]Come on...[n][uf 1 1][e]

[msg MSG_013_0_0 [Female Student]]
[uf 0 5 65278][uf 2 1]*sigh*[n][uf 1 1][e]

[msg MSG_013_5_0 [Female Student]]
[uf 0 5 65278][uf 2 1]*sigh*[n][uf 1 1][e]

[msg MSG_013_7_0 [Female Student]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MSG_014_0_0 [Female Student]]
[uf 0 5 65278][uf 2 1]Ugh, there's no way! I can't![n][uf 1 1][e]

[msg MSG_015_0_0 [Train Conductor]]
[uf 0 5 65278][uf 2 1]Your attention please. Today's[n]train schedule will be modified...[n][uf 1 1][e]

[msg MSG_015_5_0 [Train Conductor]]
[uf 0 5 65278][uf 2 1]...due to a rail switching malfunction.[n]We apologize for any inconvenience.[n][uf 1 1][e]

[msg MSG_015_7_0 [Train Conductor]]
[uf 0 5 65278][uf 2 1]The next stop is Iwatodai.[n][uf 1 1][e]

[msg MSG_016_0_0 [Train Announcement]]
[uf 0 5 65278][uf 2 1]Iwatodai, Iwatodai.[n][uf 1 1][e]

[msg MSG_016_5_0 [Train Announcement]]
[uf 0 5 65278][uf 2 1]This is the final train bound[n]for Tatsumi Port Island.[n][uf 1 1][e]

[msg MSG_016_7_0 [Train Announcement]]
[uf 0 5 65278][uf 2 1]Please board before the[n]scheduled departure time.[n][uf 1 1][e]

