[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Now, we're...[n][uf 1 1][e]

[msg MSG_000_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]How did we end up back—[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Hey, look over there![n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Whoa, uh... What's up with Tartarus?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]It's finally happening...[n]Everything's going back to normal...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]Our job is done.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Oh![n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Wait... Is that...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]

