[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]How are you... even standing right now...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]

[msg MSG_001_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]Hey... You can't be going out there by yourself![n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]No, don't go![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]No, wait...! What are you doing!?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Dammit... Why!? Why the hell can't we get up!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Don't do this! We've already come so far together...[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Ngh... Goddammiiiit![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Why aren't you listening!?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Come back![n][uf 1 1][e]

