[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]This is how we'll be getting to school every day.[n]It's a monorail! Pretty cool, huh?[n][uf 1 1][e]

[msg MSG_000_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]I honestly love the ride here. It almost[n]feels like we're flying over the ocean.[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Oh, by the way, our school's at the last stop[n]on this line. It's called Tatsumi Port Island.[n][uf 1 1][e]

[msg MSG_000_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Have you heard of it? The whole thing's man-made,[n]and our school's smack-dab in the middle.[n][uf 1 1][e]

[msg MSG_000_9_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Oh, look! There it is now![n][uf 1 1][e]

[msg MSG_001_0_0 [Female Student]]
[uf 0 5 65278][uf 2 1]Morning![n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Morning![n][uf 1 1][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Well, here we are.[n][uf 1 1][e]

[msg MSG_002_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Allow me to welcome you to Gekkoukan[n]High School. I hope you like it![n][uf 1 1][e]

