[msg MSG_703_000 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]This large Shadow is of the Hierophant Arcana![n][uf 1 1][e]

[msg MSG_703_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]We don't know what it'll do. Be ready for anything![n][uf 1 1][e]

[msg MSG_703_100 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 1 0 6]That skill seems to instill fear in its opponents![n][uf 1 1][e]

[msg MSG_703_110 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 2 0 6]You'll be paralyzed if you succumb to the fear. Don't push yourself, and try to calm down![n][uf 1 1][e]

