[msg MSG_000_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]All right, time for class...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]I know you've been busy lately, but you all remembered to do your homework, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Just because you're not taking a humanities class next year doesn't mean you can blow off classic lit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Hey... Are you all listening to me?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 0 0 0 5 0 0]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]What's wrong, Fuuka? You look kinda down.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 0 0 0 7 0 0]Huh...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Talk to me. What's bothering you?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]It's just... Aragaki-senpai...[n][uf 1 1][e]

[msg MSG_006_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh... Yeah, it's pretty shocking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]I'd never seen him in school, but he'd always be hanging around town...[n][uf 1 1][e]

[msg MSG_006_5_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 2 65535 0 0][uf 3 1 1 0 0 12 0 0]And now, he's just... gone. It's hard to put it into words.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 13 0 0]I took it for granted that everyone would always be around, that nothing would ever change...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 14 0 0]But, some things you can never get back... I didn't consider how easily it could happen.[n][uf 1 1][e]

[msg MSG_007_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 15 0 0]Once I realized that, I started thinking about my parents.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 16 0 0]I've sort of been avoiding the question, but... is it okay for me to leave things with them like this?[n][uf 1 1][e]

[msg MSG_008_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Parents, huh...? Yeah, that's a tough one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]But, I think you'll work it out, Fuuka.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]Moriyama, what are you waiting for? Come on up.[n][uf 1 1][e]

[msg MSG_010_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Yeah, yeah.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mr. Ekoda]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 5 21 0 1]Would it kill you to give your classmates a proper goodbye?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Huh? What's going on?[n][uf 1 1][e]

[msg MSG_013_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]Uhhh, hi, everyone. I know I haven't been here that long, but I feel like I've made some good friends.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]I'll remember each and every one of you after I transfer. Thank you all... How's that?[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Huh...? Wait, transfer...?[n][uf 1 1][e]

[msg MSG_014_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 17 6 4 0][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 26 0 0]WHAT!?[n][uf 1 1][e]

