[msg MSG_000_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I understand one of my group has caused you some trouble.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Is she in good health?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]It must be difficult looking after her. After all, you likely can't rein her in for very long...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Or, could it be you've already killed her?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]She's fine, for now.[e]
[uf 0 5 65278][uf 2 1]We don't kill people.[e]

[msg MSG_002_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I see. "For now," you say...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Then, I assume her symptoms have arisen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Considering Kirijo's resourcefulness, you would have had access to the suppressants as well.[n][uf 1 1][e]

[msg MSG_003_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]So, you're keeping her alive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Then, I take it you've had to use the suppressants.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]As I'd expect from Kirijo's resourcefulness. And, you now have someone with firsthand experience among your number as well...[n][uf 1 1][e]

[msg MSG_004_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]If you already know about the suppressants, that simplifies things.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Can you imagine it? A Persona-user, murdered by their other half...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Such is the fate of a Persona that has gone berserk.[n][uf 1 1][e]

[msg MSG_005_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]...As you have already seen for yourself.[n][uf 1 1][e]

[msg MSG_006_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]This power of ours is not meant to be wielded by just anyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]That holds true, even for those who were awakened by force...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]It comes at a great cost, and we can only harness it by walking the line between life and death. This power makes us who we are.[n][uf 1 1][e]

[msg MSG_007_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]And yet... you hold the ability to wield so many.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]The Dark Hour has graced you with its favor. Almost unjustly so, from our perspective.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 0 0 0 20 0 0]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Now, I ask you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Don't you think it'd be a shame for you to lose such a special power?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]It's for my friends.[e]
[uf 0 5 65278][uf 2 1]It's for the sake of the world.[e]

[msg MSG_010_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You stubbornly cling to that sentiment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Do you have no intention of understanding anything?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Choosing to turn a blind eye towards your own power, to the grief of the fallen, the unchosen, the unloved...[n][uf 1 1][e]

[msg MSG_010_5_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 2 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Such apathy... Such insolence... You trample upon everything we stand for![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 2 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]And worst of all, your rejection of my—[n][uf 1 1][e]

[msg MSG_011_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 0 0 0 28 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]You tread upon your gifts like dirt, and in doing so, reveal your own arrogance...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]It disgusts me.[n][uf 1 1][e]

[msg MSG_012_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I see now that nothing will change your mind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]If our beliefs are at odds with each other, and neither side is willing to concede...[n][uf 1 1][e]

[msg MSG_013_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Then a battle is unavoidable.[n][uf 1 1][e]

[msg MSG_014_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 0 0 0 34 0 0]......[n][uf 1 1][e]

[msg MSG_015_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Our final confrontation will come in our own time.[n][uf 1 1][e]

[msg MSG_016_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]You have been blessed with a power greater than any other, and yet you don't see its true value...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]...Such a shame.[n][uf 1 1][e]

