[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]And that concludes the tour.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 2 0 0]Being shown around kinda makes me feel more motivated to make use of those places.[n][uf 1 1][e]

[msg MSG_001_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 1], did you get all that? Anything you're still unclear about?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I got everything down.[e]
[uf 0 5 65278][uf 2 1]I'm not sure.[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 1 65535 0 0][uf 3 1 1 0 0 4 0 0]Good to hear. I hope your stay here is an enjoyable one.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Don't concern yourself with the details too much. Just go ahead and use the facilities as you please.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]As long as all of us remain considerate, the dorm will continue to be a comfortable living space for all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 7 0 0]If there's anything you'd like to do here, you may want to invite the others to join you.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 8 0 0]Yeah, we're all livin' under the same roof, after all. Better make the most of it![n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]I've never really done anything like this before, so I'm a little nervous...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 2 1 25 25]I'll try my best to enjoy myself here with you all.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 11 0 0]This may be coming a little late for most of you, but welcome to the dorm.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]Thanks![n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Thank you![n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Thanks.[n][uf 1 1][e]

