[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]The wind... It feels so nice...[n][e]

[msg MSG_000_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]I admit, I'm finally noticing the[n]beauty of spring. It's wonderful.[n][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]And yet, without exception, each and[n]every season will come to an end.[n][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]We fought side by side...[n][e]

[msg MSG_002_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]We faced the world's end...[n][e]

[msg MSG_002_4_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]And now... I'm finally beginning to understand...[n][e]

[msg MSG_002_6_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]...what it was I'd been searching for.[n][e]

[msg MSG_002_8_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]I always wondered what it really meant to "live."[n][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]Now, I think it's...[n][e]

[msg MSG_003_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]Following your heart...[n]Fighting for what you can change...[n][e]

[msg MSG_003_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]And accepting the things you can't.[n][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]Nothing on this earth lasts forever.[n][e]

[msg MSG_004_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Every life will one day fizzle out...[n][e]

[msg MSG_004_4_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]That holds true for all of us. And as soon as you[n]come to terms with it, you realize something.[n][e]

[msg MSG_004_6_0 [Aigis]]

[msg MSG_004_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]You see what really matters...[n][e]

[msg MSG_004_8_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]And find out what it is that gives your life meaning.[n][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]When I learned that I wasn't strong enough...[n][e]

[msg MSG_005_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]I was tormented by it. Now I understand why.[n][e]

[msg MSG_005_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]Protecting others is the duty I was given...[n][e]

[msg MSG_005_4_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]But to me, it was more than an obligation.[n][e]

[msg MSG_005_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]At some point, it became something[n]I wanted to do for myself.[n][e]

[msg MSG_005_6_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]Once I decided to try and prevent the Fall...[n]something inside me clicked.[n][e]

[msg MSG_005_8_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]When I thought about how I[n]might never see you again...[n][e]

[msg MSG_005_9_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]That's when I first understood...[n]what mattered to me the most.[n][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]And so, I made up my mind.[n][e]

[msg MSG_006_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]What I want... is to protect you.[n]From now, until the end of time.[n][e]

[msg MSG_006_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]I want to stay by your side.[n][e]

[msg MSG_006_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]And I know, I'm not the only one[n]out there who could do this...[n][e]

[msg MSG_006_6_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]But still... I want to.[n][e]

[msg MSG_006_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]Because I'm positive... if I do it for you...[n][e]

[msg MSG_006_8_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0]Then nothing's a waste.[n]My life... will have meaning.[n][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]So... thank you...[n][e]

[sel ASA_008_0_0 top]
[uf 0 5 65278][uf 2 1]Don't cry.[e]
[uf 0 5 65278][uf 2 1]It's okay.[e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0]Sorry... What's gotten into me?[n][e]

[msg MSG_009_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]It's good... I've finally found a reason to live.[n][e]

[msg MSG_009_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]So why am I...?[n][e]

[msg MSG_010_0_0 [Familiar Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Hey, hey, heyyy![n][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]They're here...[n][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]I see it now.[n][e]

[msg MSG_012_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0]I have friends... We support[n]each other through thick and thin...[n][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0]Not everything needs to be[n]for some greater purpose.[n][e]

[msg MSG_013_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0]Just caring about someone can be enough.[n][e]

[msg MSG_013_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0]That's all we need to give our lives meaning...[n][e]

[msg MSG_013_6_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0]As for me, I've found my path.[n][e]

[msg MSG_013_8_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 45 0 0]And that's to protect you with my life.[n][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 46 0 0]Thank you so much... for everything.[n][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 47 0 0]You must be tired.[n][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 48 0 0]Go ahead and rest now.[n][e]

[msg MSG_016_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 49 0 0]I'll be right here. I won't be going anywhere.[n][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 50 0 0]In a moment, the others will be joining us...[n][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]I'm getting sleepier...[n][e]

[msg MND_018_5_0]
[uf 0 5 65278][uf 2 1]Your eyes feel heavy...[n][e]

[sel ASB_019_0_0 top]
[uf 0 5 65278][uf 2 1]Close your eyes[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 51 0 0]It'll be okay.[n][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 52 0 0]I'm right by your side...[n]Here to protect you forevermore.[n][e]

