[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 1 0 0]The door vanished this time, too...[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]First Amada's past, and now mine... What in the world does this mean?[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]I have no idea, either...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 4 0 0]That certainly takes me back, though... We were both in middle school then.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Truth be told, I thought you lost it until the moment I first summoned my Persona.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 6 0 0]I mean, what else was I supposed to think when this random rich girl gave me a gun five minutes after we met?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Well, it grabbed your attention, didn't it? So I'd say my plan went off without a hitch.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Had I asked you to "fight for justice," you wouldn't have bothered listening.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 9 0 0]You know me so well.[n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]So that was a "school"...[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 11 0 0]Yes, it was. But it was only a small portion of one.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Really? Then, it's actually much bigger than that?[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 13 0 0]That's right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 14 0 0]...Have you really never been outside before?[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Well... I, um...[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 16 0 0]I didn't mean to embarrass you. It's nothing to be ashamed of.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 17 0 0]Come to think of it, I wasn't permitted to leave the dorm at first, either.[n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Do you... Do you also go to school?[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 19 0 0]I did... But I won't be attending as of this spring.[n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Huh? You won't? But why?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Everyone else is going. I thought you liked being with your friends.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 22 0 0]Why...? It's because I, um...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 23 0 0]It doesn't matter. I thought it over and came to a decision after some time.[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 24 0 0]Oh... I see.[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]You know... I don't think Metis is a bad person at all.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]Yeah, she's not "bad," more like...[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Maybe we've been taking her a little too seriously up 'til now because, honestly...[n][uf 1 1][e]

[msg MSG_021_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 28 0 0]She's really just a kid inside, isn't she?[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Maybe so.[n][uf 1 1][e]

