[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]The "Willpower!" series...[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 2 0 0]I was planning on seeing this with a friend from my club... I thought it might help motivate us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 5 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 6 25 25][uf 4 21 2 11]You might think it's kinda cheesy, though... Now I'm not so sure about this...[n][uf 1 1][e]

[msg MSG_900_0_0 [Sports Club Coach]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Come on, show me some guts! Push your limits! You swore you'd take us to nationals![n][uf 1 1][e]

[msg MSG_901_0_0 [Sports Club Coach]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]And then the big leagues, the World Series, and then the Olympics! That was our promise![n][uf 1 1][e]

[msg MSG_902_0_0 [Sports Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]I'll never forget! I'm gonna make it! I won't stop running till I reach the sunset![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Hot-blooded sweat is[n]flying across the screen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned that with enough willpower,[n]you can overcome anything...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 7 0 0]That was awesome! We were in there for a while, but it went by so fast![n][uf 1 1][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 8 0 0]I guess there really are times in life where you gotta push yourself through with sheer willpower.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 9 0 0]But I'm still young... I haven't really done anything that crazy just yet.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 5 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh wow, it's getting late. How many movies did we watch?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]We saw the baseball one, the judo one, the boot camp one... Oh right, even shot put![n][uf 1 1][e]

[msg MSG_003_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 12 0 0]The shot put stuff kinda lost me, but the scenes after that with the main guy running were so good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]I cried my eyes out when he did the hundred handstands into the sunset![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_004_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 15 0 0]I'm being weird, huh?[n][uf 1 1][e]

[msg MSG_004_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Anyway, I'm getting hungry. Why don't we grab a bite somewhere before heading back?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I decided to go back to[n]the dorm with Yukari.[n][uf 1 1][e]

