[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Why's it after us!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 2 0 0]It must want my sister! She has the same power as the one who created the seal![n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Are you... going to fight it!? You can't take on something like that![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 3 1 1 0 0 4 0 0]This is a battle we can't run from.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 3 1 1 0 0 5 0 0]The feelings that created this monster came from within me as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 3 1 1 0 0 6 0 0]I couldn't accept reality, so I wished for the past... despite that past harboring death and bloodshed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 3 1 1 0 0 7 0 0]There isn't a doubt in my mind... This is the cause of all our struggles.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Sounds good to me. Let's take it down![n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 1 0 0 9 0 0]This isn't just a fight against a monster... I'll be facing myself as well. And I'm ready![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 10 0 0]I won't run away this time... He's watching us, and we can't let him down![n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 11 0 0]This thing's got no chance of beatin' us! And I'm likin' those odds![n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Sister...[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 13 0 0]Don't worry. It won't stop us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 14 0 0]To live means to not give in to your own weaknesses...[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 15 0 0]So we won't lose! We will live![n][uf 1 1][e]

