[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Every time I get geared up, my brain gets into this mindset, like... "Time to get 'er done!" Y'know?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]No, actually, I don't know...[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm just happy I get to match with my sister.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]She got all pouty the moment we changed clothes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Who would've thought she just wanted an armband?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 1 0 0 6 0 0]...This doesn't make you one of us, though.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Still, it's a good thing you've got one on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]This way, I can get a detailed read on your vitals.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]I had some extras prepared, but I didn't expect we would need them again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]Well, is everyone ready to start exploring? Are we missing anything?[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 52 65535 0 0][uf 3 1 1 0 0 11 0 0]I don't think so, but... I've got a bad feeling about this.[n][uf 1 1][e]

[msg MSG_007_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Junpei here might not, but what about the rest of you?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]Yeah, I can't put my finger on it, but something does feel off...[n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Agreed. Something's not sitting quite right.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Huh? I'm the only one hyped...?[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Wait, hold up, I definitely feel something... I think? Maybe?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Yamagishi, have there been any changes to our readings?[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Um... Well, I don't know how to put this, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]They're indicating that everyone's strength has weakened significantly, which may prove to be an impediment...[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Uh, ain't that, like, really bad for us!? Is it 'cause of that Abyss of Time thing?[n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]I don't seem to be affected. Are you sure it's not simply because you're all weak?[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Oh, we're weak, are we?[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Save it for later, Akihiko.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 24 0 0]So if it's not because of the Abyss... Does it have something to do with us?[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 25 0 0]We did take a step back from fighting for a while, so that's probably the biggest factor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]More importantly, your Personas' output is currently unstable, so their abilities are partially limited right now.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Maybe we just forgot how to fight? Does muscle memory even go away...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Not that it really matters. All we can do right now is work with what we've got.[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Easy for you to say, but... Aigis, you're nervous too, aren'tcha?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]I'm uneasy.[e]
[uf 0 5 65278][uf 2 1]She's right. It doesn't matter.[e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Right? I don't know, this seems like it'll be pretty rough...[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 31 0 0]Man... Even Ai-chan's on Yuka-tan's side.[n][uf 1 1][e]

[msg MSG_025_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 32 0 0]You have nothing to worry about, Sister. I'll be there for you.[n][uf 1 1][e]

[msg MSG_026_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 1 0 0 33 0 0]Arf![n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Well, now that we've established the situation at hand...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 35 0 0]I'd like to set expectations a bit before we head out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 36 0 0]I should operate on my own to find out whether or not there's more to those materials we found underground.[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 37 0 0]Flying solo, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 38 0 0]I guess you are the only one who can identify that sort of thing, though.[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 39 0 0]I'll regroup with everyone once I learn more.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 40 0 0]There's something else I want to look into as well, so it's more efficient for the team to progress without me there.[n][uf 1 1][e]

[msg MSG_029_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 41 0 0]Your objective is to see if the Abyss of Time connects to anywhere else besides the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 42 0 0]And since we don't know how much time this will take, it's imperative that we secure our supply routes.[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 43 0 0]Oh, in that case, kinda seems like a job for Koromaru, don't it?[n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 44 0 0]I mean, he's sharper than a human! Y'know, with his sense of smell and all.[n][uf 1 1][e]

[msg MSG_032_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 1 0 0 45 0 0]Arf![n][uf 1 1][e]

[msg MSG_033_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 46 0 0]Yeah? You're game, bud? I'm a little worried about us being weaker than usual, though... So how 'bout I come with ya?[n][uf 1 1][e]

[msg MSG_034_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 1 0 0 47 0 0]Arf, arf! Awooo![n][uf 1 1][e]

[msg MSG_035_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 48 0 0]All right, I'll let the two of you handle that, then.[n][uf 1 1][e]

[msg MSG_035_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 0 1 2]Iori, Koromaru, and I will go about our own tasks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 0 1 27]Everyone else, follow Aigis's command and focus on exploring.[n][uf 1 1][e]

[msg MSG_036_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 51 0 0]I'm counting on you, Aigis.[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Leave it to me.[e]
[uf 0 5 65278][uf 2 1]I hope to reunite with you all soon.[e]

[msg MSG_038_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 52 0 0]That's what I like to hear—and you can count on me to bring back results, too.[n][uf 1 1][e]

[msg MSG_039_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 53 0 0]And I as well. Give it the best you've got, Aigis.[n][uf 1 1][e]

[msg MSG_040_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 54 0 0]Let's head out once you've decided on our course of action.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 55 0 0]If we want to make progress, then we better get to it.[n][uf 1 1][e]

