[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]08/13/2009 22:41:19[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like Sanada's room...[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 11 0 0][uf 3 1 1 0 0 1 0 0]Ugh, dammit... I still can't stop thinking about what happened in Yakushima...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 11 0 0][uf 3 1 1 0 0 2 0 0]You're telling me I can't carry a conversation any better than Junpei?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 11 0 0][uf 3 1 1 0 0 3 0 0]How can I be on the same level as that idiot and his lame pickup lines?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 4 0 0]"Are you able to make others laugh with a well-timed joke?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 5 11 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 4 3 25 25]Well... No specific examples come to mind, but I think I at least do that much.[n][uf 1 1][e]

[msg MSG_003_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 6 0 0]"Careful: Making others laugh and being laughed at are two entirely different things!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 5 11 0 0][uf 3 1 0 0 0 7 0 0][uf 4 23 0 4 3 25 25]......[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 8 0 0]"When people speak to you, do you tend to respond with pure logic and reason?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 9 0 0]"This is a common mistake among inarticulate men. Try to consider what the other party is feeling first."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]

[msg MSG_004_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 5 5 11 0 0][uf 3 1 1 0 0 11 0 0]Dammit. I guess they've got a point...[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 12 0 0]"Try practicing by imagining you're asking a female friend or colleague to your favorite store."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 13 0 0]"Remember, it's important to smile and have a sense of humor!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 5 11 0 0][uf 3 1 1 0 0 15 0 0]Um... H-Hey there! Uh... What great timing to see you here! Nice one![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 5 11 0 0][uf 3 1 1 0 0 16 0 0]I'm going to Umiushi, wanna come with?[n][uf 1 1][e]

[msg MSG_006_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 11 0 0][uf 3 1 1 0 0 17 0 0]Oh... Humor... Humor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 5 11 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 4 3 25 25]Y-Y'know, the beef bowl place... H-Hey... M-Maybe we could "meat" up there... Get it!?[n][uf 1 1][e]

[msg MSG_006_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 5 11 0 0][uf 3 1 1 0 0 19 0 0]Arrrgh...![n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 11 0 0][uf 3 1 1 0 0 20 0 0]What am I, the chairman!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 11 0 0][uf 3 1 1 0 0 21 0 0]Screw this![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

