[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems content[n]gnawing on the [uf 4 4 0 37 1 16786].[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrr...[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0]Woof, woof![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Is something happening...?[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 3 0 65535 3082 0 0]Then let me make this clear: you may be our ally for now, but I don't have a single ounce of trust in you![n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0]Oh, trust me, you were already perfectly clear! You made it clear just by how you treat me![n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]C'mon, guys! Let's just all take a deep breath...[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2061 0 0]Uhh...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]Hey, Aigis... I still exist, right?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Of course you do.[e]
[uf 0 5 65278][uf 2 1]Maybe you don't...[e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2030 0 0]Thank you! I wasn't so sure with them actin' like I ain't even here...[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2144 0 0]Yeah, I guess not... That'd explain why they're actin' like they don't hear anything I say...[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]I don't know what started it, but they've been at it since I got here.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0]Whoa, hey! I don't think you wanna get in the middle of this, buddy![n][uf 1 1][e]

[msg MSG_015_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Woof![n][uf 1 1][e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0]What!? I'm not being childish at all! I'm just as grown-up as anyone else here![n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 52 65535 0 0][uf 3 1 3 0 65535 3121 0 0]...I can't believe a dog had to point out I'm getting too worked up...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 4 23 0 1 0 25 25]All right, enough's enough. I admit that I'm at fault here too. Let's leave it at that.[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30086 0 0]Hmph... Fine.[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Damn... One bark and it's settled![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]You're freakin' amazing, Koromaru![n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Well done, Koromaru-san![e]
[uf 0 5 65278][uf 2 1]What a commanding presence![e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]I can feel a dignified aura[n]emanating from Koromaru-san...[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2111 0 0]If this all proved anything, it's that nothin' can beat that Koromaru charm! I bet I could learn a thing or two from him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 4 23 0 2 15 25 25]Wait a minute...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 4 23 0 2 3 25 25]I basically just said I'm less charming than a dog, didn't I...?[n][uf 1 1][e]

