[msg MSG_733_0_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 1 0 5]Next, I'm going to explain a tactic for defeating several enemies at once.[n][uf 1 1][e]

[msg MSG_733_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 2 0 5]First, go ahead and strike an enemy's weakness.[n][uf 1 1][e]

[msg MSG_733_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 3 0 5]I'll keep track of tactical data such as any enemy weaknesses you've identified.[n][uf 1 1][e]

[msg MSG_733_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 2 4 0 5]If you ever forget an enemy's affinities, just let me know and I'll get that data for you.[n][uf 1 1][e]

[msg MSG_733_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 5 0 5]All right, now knock down the other one. That's when you perform an All-Out Attack.[n][uf 1 1][e]

[msg MSG_733_0_6 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 2 6 0 3]An All-Out Attack?[n][uf 1 1][e]

[msg MSG_733_0_7 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 7 0 5]It's a maneuver that engages the entire team in a coordinated assault when all enemies have been knocked down.[n][uf 1 1][e]

[msg MSG_733_0_8 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 8 0 5]Naturally, the enemy has no way of defending against this. It's one of the most reliable means of attack.[n][uf 1 1][e]

[msg MSG_733_0_9 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 2 9 0 3]Whoa! That sounds so badass! Let's give it a try right now![n][uf 1 1][e]

[msg MSG_733_0_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 10 0 5]One other thing I should mention, though: as obvious as it sounds, you can't perform an All-Out Attack alone.[n][uf 1 1][e]

[msg MSG_733_0_11 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 11 0 5]So, if you want it in your arsenal, you'll need at least two members available in the fight.[n][uf 1 1][e]

[msg TRL_733_1_1]
[uf 0 5 65278][uf 2 1]Pressing the L1 button will allow you to view the affinities of a selected enemy.[n][uf 1 1][e]

[msg TRL_733_1_2]
[uf 0 5 65278][uf 2 1]This allows you to confirm which attack affinities you've used on that specific enemy.[n][uf 1 1][e]

[msg TRL_733_2_1]
[uf 0 5 65278][uf 2 1]When all enemies are knocked down, you will have the option to perform an All-Out Attack. This deals heavy damage to all enemies, so try and knock down enemies as often as possible.[n][uf 1 1][e]

[msg TRL_733_2_2]
[uf 0 5 65278][uf 2 1]All-Out Attacks cannot be performed with only one available party member. You will also be unable to perform All-Out Attacks if you are afflicted with certain status ailments.[n][uf 1 1][e]

[msg TRL_733_3_1]
[uf 0 5 65278][uf 2 1]After winning a battle, there is a rare chance of Shuffle Time occurring. During Shuffle Time, your potential will be shown in the form of cards.[n][uf 1 1][e]

[msg TRL_733_3_2]
[uf 0 5 65278][uf 2 1]Depending on the card you choose, you can receive various rewards.[n][uf 1 1][e]

