[msg MSG_000_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 1 0 0]Did you know this hot spring is open for guys at certain times and girls at others?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 154 65535 0 0][uf 3 1 1 0 0 2 0 0]No way, really? So there's a chance it could switch to girls-only while we're still in here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 154 65535 0 0][uf 3 1 1 0 0 3 0 0]But even if that happens, it wouldn't be on us, right?[n][uf 1 1][e]

[msg MSG_002_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 4 0 0]That's true. Something like that actually happening wouldn't be our fault.[n][uf 1 1][e]

[msg MSG_002_5_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 5 0 0]Don't you think?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]An accident for sure.[e]
[uf 0 5 65278][uf 2 1]I don't know about that.[e]
[uf 0 5 65278][uf 2 1]Maybe we'll get lucky?[e]
[uf 0 5 65278][uf 2 1]This might blow up in our faces.[e]

[msg MSG_004_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 4 154 65535 0 0][uf 3 1 1 0 0 6 0 0]Blow up how?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 221 0 25 25]Even still, can't help but think maybe fate wants us to be here.[n][uf 1 1][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 8 0 0]Anyway, I was just asking. Not like I'm being serious.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 154 65535 0 0][uf 3 1 1 0 0 9 0 0]...Hey, isn't it getting kinda hot in here?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Junpei and Ryoji seem[n]to be acting strange...[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 154 65535 0 0][uf 3 1 1 0 0 10 0 0]So, what time does this hot spring change from guys-only to girls-only, Junpei?[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 154 65535 0 0][uf 3 1 1 0 0 11 0 0]Uh, I'm not sure. I didn't bother to check. Right, Ryoji-kun?[n][uf 1 1][e]

[msg MSG_010_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 154 65535 0 0][uf 3 1 1 0 0 12 0 0]Right? It could happen at any moment, couldn't it, Junpei-kun?[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 154 65535 0 0][uf 3 1 1 0 0 13 0 0]You morons. So that's why we came at such a strange time?[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 154 65535 0 0][uf 3 1 1 0 0 14 0 0]Hahaha, calm down, man. We're just joking! I mean, yeah, we are here at a weird hour.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 154 65535 0 0][uf 3 1 1 0 0 15 0 0]But don't worry about it. I doubt any girls would come out here this la—[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 154 65535 0 0][uf 3 1 1 0 0 16 0 0]What!? Someone's here! Oh man, what're we gonna do?[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 154 65535 0 0][uf 3 1 1 0 0 17 0 0]Probably just another guy.[n][uf 1 1][e]

[msg MSG_015_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 154 65535 0 0][uf 3 1 1 0 0 18 0 0]Yeah, don't worry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 154 65535 0 0][uf 3 1 1 0 0 19 0 0]We can say we didn't know, that it's all just a misunderstanding.[n][uf 1 1][e]

[msg MSG_016_0_0 [Familiar Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]Wow! This hot spring is huge![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 154 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh shi—[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]Wow, you're right. It's as big as a swimming pool.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]So this is an outdoor hot spring. Unfortunately, its therapeutic benefits have no effect on me.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 154 65535 0 0][uf 3 1 1 0 0 24 0 0]Shiiit, it's them! What're they doing here this late?[n][uf 1 1][e]

[msg MSG_021_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 154 65535 0 0][uf 3 1 1 0 0 25 0 0]Yes! Yukari-san and Fuuka-san!? This is my lucky ni—[n][uf 1 2 160][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 154 65535 0 0][uf 3 1 1 0 0 26 0 0]Shut up, you dumbass! They'll hear you![n][uf 1 1][e]

[msg MSG_023_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 4 154 65535 0 0][uf 3 1 1 0 0 27 0 0]*gurgling*[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]Who's that!? Is someone there!?[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]What's wrong, Yukari? Did you hear something?[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 154 65535 0 0][uf 3 1 1 0 0 30 0 0]Mitsuru's here, too!? Oh, man. There's no way she'll see this as just a "misunderstanding"![n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 154 65535 0 0][uf 3 1 1 0 0 31 0 0]Uh, you don't think she'd get us expelled for this, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 154 65535 0 0][uf 3 1 1 0 0 32 0 0]Like, it was guys-only when we got here. It's not like we planned this. We were just goofing around![n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 154 65535 0 0][uf 3 1 1 0 0 33 0 0]You expect her to buy that? No, if she finds us, then...[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 154 65535 0 0][uf 3 1 1 0 0 34 0 0]...Then what?[n][uf 1 1][e]

[msg MSG_030_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 154 65535 0 0][uf 3 1 1 0 0 35 0 0]We'll be executed.[n][uf 1 1][e]

[msg MSG_031_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 4 154 65535 0 0][uf 3 1 1 0 0 36 0 0]E-Executed!?[n][uf 1 1][e]

[msg MSG_032_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Yeah, I think I did hear something. Fuuka, could you check over there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]I-It could be a ghost...[n][uf 1 1][e]

[msg MSG_033_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]Um... O-Okay...[n][uf 1 1][e]

