[msg MSG_000_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]Well, hello there. It's the inseparable duo.[n][uf 1 1][e]

[msg MSG_001_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Hehe! Yes, you're still a good boy today, too.[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Owaaooo! Owoooo![n][uf 1 1][e]

[msg MSG_003_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Oh! My gift is going to get cold.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]Look, I brought you some takoyaki today.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MSG_005_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]It's Octopia's specialty—tako-free takoyaki for dogs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1]There's one for people too, so enjoy them together, okay?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]The woman left the[n]takoyaki and walked off...[n][uf 1 1][e]

[msg MSG_007_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]*munch* *munch*[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]It's the stray dog that chased that[n]boy around a little while ago...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He looks like he's in bad shape...[n][uf 1 1][e]

[msg MSG_009_0_0 [Sad Dog]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]*whimper*[n][uf 1 1][e]

[msg MSG_010_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Woof![n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Let's share some.[e]
[uf 0 5 65278][uf 2 1]Should we chase him away?[e]
[uf 0 5 65278][uf 2 1]He looks pretty hungry...[e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 0 0 0 13 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Ruff! Ruff![n][uf 1 1][e]

[msg MSG_015_0_0 [Sad Dog]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]*munch* *munch*[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Now that I look closer,[n]I see he has a collar...[n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]*pant* Arf?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Let's find his owner.[e]
[uf 0 5 65278][uf 2 1]Let's talk to Officer Kurosawa.[e]

[msg MSG_019_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]*pant* Arf![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I decided to take the stray[n]dog to the police station.[n][uf 1 1][e]

