[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 2 1 1 3]No hard feelings, 'kay? So don't hold anything back![n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 1 0 2 2 0 0]Woof![n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 2 3 0 6]This is wrong... There has to be another way![n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 2 4 1 3]You're pretty tough, Ai-chan. But so am I![n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 2 5 1 3]Man, it hurts gettin' hit by you so much more this time... But I'm not out yet![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 5 52 65535 0 0][uf 3 1 1 0 2 6 1 3]Damn, that's some serious firepower... But I'm not losin'![n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 1 0 2 7 0 0]Woof! Woof![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems to[n]have energy to spare...[n][uf 1 1][e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 1 0 2 8 0 0]Grrrrr...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san is getting worn out.[n][uf 1 1][e]

[msg MSG_010_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 1 0 2 9 0 0]*whimper*[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san looks like he's in pain...[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 2 10 1 3]Sorry I dragged you into this, boy... Don't worry, I'll fight enough for both of us![n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 1 0 2 11 0 0]Awooooooooo![n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san's fighting[n]spirit has been reignited...![n][uf 1 1][e]

