[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Right, then. I decided to hold this study session for us to concentrate on the upcoming exams.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Amada, I invited you to join us so you can focus on your own studies. Your presence is welcome here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Thank you for inviting me. I'll make sure not to be a bother to everyone.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]To the rest of you, I want you to set a proper example and take your studies seriously.[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Woof![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Hehe... Are you going to study with us, Koro-chan? Good boy.[n][uf 1 1][e]

[msg MSG_005_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Koromaru-san says that he will accompany us here as we study.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Well, aren't you a little hard worker? Unlike Junpei over there, who can't stop yawning.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Uhh, can't really deny it... Wouldn't mind bein' in his place right about now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 3 1 25 25]Dogs never have to study for exams like this. Man, what a life... Woof![n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I'd love to be one.[e]
[uf 0 5 65278][uf 2 1]Being a dog isn't easy.[e]
[uf 0 5 65278][uf 2 1]Shake, Junpei![e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Right? If we were dogs, we could just play all day![n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Bark! Bark![n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]He says it's not all fun and games.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Koromaru-san tirelessly patrols the neighborhood each day.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]You hear that? You think you could keep that up, every single day?[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Dammit... The dog wins again...[n][uf 1 1][e]

[msg MSG_015_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]He is glad that you understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Koromaru-san never misses a day patrolling the neighborhood, after all.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]You hear that? Think you could keep that up, every single day?[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Dammit... The dog wins again...[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Woof![n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Stay![n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Woof![n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Um... Go home...?[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Time for me to go back to my room! Arf![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 3 4 25 25]...Wait, don't try to get rid of me! Arrooo...[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Koromaru-san may not have an obligation to study, but he has another important mission.[n][uf 1 1][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]True... He's been protecting that shrine this whole time. That sounds like something far more difficult.[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Guess if you want to be a dog, you'd better develop some diligence like Koromaru here.[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Being a dog is harder than it seems... You'd be better off just studying, Junpei-san.[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Oh, stop! Don't look at me like some pitiful creature![n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]All right, that's enough chitchat. Let's concentrate on our studies.[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Knowing everyone's watching[n]keeps me accountable...[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]All right, I think we can begin wrapping things up. Good work, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 5 0 25 25]And Iori... After all the dog talk, I do hope you were able to get through the material you needed to cover.[n][uf 1 1][e]

[msg MSG_032_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Uh... Woof?[n][uf 1 1][e]

[msg MSG_033_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Oh, I see. So you're still learning, then? As a dog, I'll need to give you strict behavioral training.[n][uf 1 1][e]

[msg MSG_034_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I-I'm kidding! It was a joke! I'm totally cool being human... No training needed, I'm good![n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]That will conclude the group study session. It is time for a much-deserved rest.[n][uf 1 1][e]

