[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]This is Tartarus—the labyrinth that reveals itself during the Dark Hour.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Labyrinth...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 3 0 0]What are you talking about!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 4 0 0]What happened to our school?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Once the Dark Hour passes, everything will return to normal.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 6 0 0]This is the "nest" you were talking about!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 7 0 0]But, why!? Why'd our school turn into a giant tower!?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 51 65535 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 9 0 0]You don't know either?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 51 65535 0 0][uf 3 1 1 0 0 10 0 0]...No.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]I'm sure it's complicated.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]If we don't know, we'll just have to find out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Mitsuru and I have only gone in to take a peek; this'll be our first time exploring it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 4 1 25 25]Exciting, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 15 0 0]There's gotta be something in there. Hopefully some sort of clue about the Dark Hour.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 16 0 0]Akihiko. I respect your enthusiasm, but you won't be exploring it today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 17 0 0]I know... You don't have to keep reminding me.[n][uf 1 1][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]So this is Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]In any case, we decide to enter the tower...[n][uf 1 1][e]

