[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Sanada is watching the match intently...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I watched a boxing DVD with Sanada.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]That final round was one of the greatest in the history of boxing.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 2 1 1 0] has improved[n]from watching the boxers fight so hard...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]All right, we should probably call it a night. Early to bed, early to rise, as they say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]Might not be a bad idea to take some protein before you sleep. In this situation, casein would be more effective than whey...[n][uf 1 1][e]

