[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 1 0 0]It has been a while since we attended class.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0]The teachers and our classmates seemed to be doing well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 7 0 25 25]By the way, did you notice that Junpei-san was missing?[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]I saw him head for the rooftop before afternoon classes started.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Perhaps he decided to skip the first day of the semester?[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Seems like both Junpei and[n]Yukari are on the rooftop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to meet them there.[n][uf 1 1][e]

