[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5076 0 0]Excuse me, Aigis... Would it be okay if I got a closer look at the parts you found while exploring?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5068 0 0]...It's just as I speculated. These parts can be equipped to Aigis's framework.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]This new base material is much lighter than her current hardware's. It also has different thermal properties and structural durability.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]Hey, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I think these parts will allow you to do things that would have been impossible before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Would you like me to install them? I'd understand if you were hesitant, though...[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]I leave it in your hands.[e]
[uf 0 5 65278][uf 2 1]I don't know...[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5025 0 0]Okay! You can count on me.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Yeah, again, I completely understand how you must feel, but please trust me on this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 4 23 0 1 1 25 25]I think I've gotten plenty familiar with your internal mechanism by now. You think so, too, right?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]All right, then. This would also be a good time to do some maintenance, so why don't we head to your room?[n][uf 1 1][e]

