[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 1 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 21 7 4]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 4 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 5 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0]This must the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 9 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 10 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 12 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 13 0 0]I will move it to another leaf then.[n][uf 1 1][e]

[msg MSG_029_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 15 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 16 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 17 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 18 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 19 0 0]......[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 20 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 21 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 22 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 22 1 7]Status reads all green. No problems to report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 24 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 21 7 4][uf 4 23 0 7 0 25 25]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 27 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 28 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 29 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 30 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 31 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 32 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 33 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 34 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 202 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 7 3 25 25]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]

[msg MSG_041_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 37 0 0][uf 4 23 0 7 0 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 38 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 39 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 40 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 41 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 42 0 0]......[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 7 1 25 25]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 202 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 7 3 25 25]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 46 0 0][uf 4 23 0 7 1 25 25]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 48 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

[msg MSG_072_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 21 7 4]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_073_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_074_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_075_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]This must the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_076_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_077_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]I will move it to another leaf then.[n][uf 1 1][e]

[msg MSG_077_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_078_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 19 0 0]......[n][uf 1 1][e]

[msg MSG_079_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_080_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_081_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_082_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_083_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 22 1 7]Status reads all green. No problems to report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_084_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 21 7 4][uf 4 23 0 7 0 25 25]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_085_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 27 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 28 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_086_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_087_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 29 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 31 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_088_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 32 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 33 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 34 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_089_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 7 3 25 25]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]

[msg MSG_089_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 37 0 0][uf 4 23 0 7 0 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 38 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 39 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_090_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 40 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 41 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 42 0 0]......[n][uf 1 1][e]

[msg MSG_091_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 7 1 25 25]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_092_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_093_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 7 3 25 25]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 46 0 0][uf 4 23 0 7 1 25 25]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_094_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_095_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 48 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

[msg MSG_305_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 21 7 4]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_307_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_308_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_311_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]This must the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_313_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_318_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]I will move it to another leaf then.[n][uf 1 1][e]

[msg MSG_318_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_323_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 19 0 0]......[n][uf 1 1][e]

[msg MSG_324_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_326_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_328_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_329_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_330_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_332_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 21 7 4][uf 4 23 0 7 0 25 25]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_335_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 7 0 25 25]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_336_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_339_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 29 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 31 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_342_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 32 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 33 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 34 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 21 7 7]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_346_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 7 3 25 25]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]

[msg MSG_346_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 37 0 0][uf 4 23 0 7 0 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 38 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 39 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_351_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 40 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 41 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 42 0 0]......[n][uf 1 1][e]

[msg MSG_352_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 7 1 25 25]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_354_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_356_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 7 3 25 25]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 46 0 0][uf 4 23 0 7 1 25 25]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_357_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_358_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 48 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

