[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf?[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I need to help him with the paperwork[n]so he'll be able to use this service...[n][uf 1 1][e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san looks happy...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I need to help him with the paperwork[n]so he'll be able to use this service...[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems satisfied.[n]In fact, he appears to be glowing.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]He happily returned to the dorm.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf! ![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems satisfied.[n]In fact, he appears to be glowing.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

