[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Grrr... Woof! Woof, woof![n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 52 65535 0 0]Hm...? That door... I don't believe it was there before.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Hey... Doesn't it look like one of those doors we find sometimes when we're exploring?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 65535 0 0][uf 4 25 6]Huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 65535 0 0]It does seem similar to those... Oh, but wait! This one looks like it leads to somewhere deeper than the others.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 65535 0 0]I'm sensing strong Shadows, treasure chests, and... something else. I'm not sure what it is...[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3060 0 0]So in other words, it's a great place to test how strong we really are![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]How is that what you got out of what she said?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]It does sound like we might be able to find some good stuff in there, so it could be worth exploring.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5025 0 0]It seems like you can enter and exit this one as much as you want, so keep that in mind if you do decide to go through it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Of course, deciding whether or not to use this door is up to you, Aigis.[n][uf 1 1][e]

