[msg Item_000]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_001]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Agi: Fire damage to 1 foe.[n][e]

[msg Item_002]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Agilao: Fire damage to 1 foe.[n][e]

[msg Item_003]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Agidyne: Fire damage to 1 foe.[n][e]

[msg Item_004]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maragi: Fire damage to all foes.[n][e]

[msg Item_005]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maragion: Fire damage to all foes.[n][e]

[msg Item_006]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maragidyne: Fire damage to all foes.[n][e]

[msg Item_007]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_008]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Garu: Wind damage to 1 foe.[n][e]

[msg Item_009]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Garula: Wind damage to 1 foe.[n][e]

[msg Item_00A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Garudyne: Wind damage to 1 foe.[n][e]

[msg Item_00B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Magaru: Wind damage to all foes.[n][e]

[msg Item_00C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Magarula: Wind damage to all foes.[n][e]

[msg Item_00D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Magarudyne: Wind damage to all foes.[n][e]

[msg Item_00E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Bufu: Ice damage to 1 foe.[n][e]

[msg Item_00F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Bufula: Ice damage to 1 foe.[n][e]

[msg Item_010]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Bufudyne: Ice damage to 1 foe.[n][e]

[msg Item_011]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mabufu: Ice damage to all foes.[n][e]

[msg Item_012]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mabufula: Ice damage to all foes.[n][e]

[msg Item_013]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mabufudyne: Ice damage to all foes.[n][e]

[msg Item_014]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Zio: Electric damage to 1 foe.[n][e]

[msg Item_015]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Zionga: Electric damage to 1 foe.[n][e]

[msg Item_016]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ziodyne: Electric damage to 1 foe.[n][e]

[msg Item_017]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mazio: Electric damage to all foes.[n][e]

[msg Item_018]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mazionga: Electric damage to all foes.[n][e]

[msg Item_019]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maziodyne: Electric damage to all foes.[n][e]

[msg Item_01A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Megido: Almighty damage to all foes.[n][e]

[msg Item_01B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Megidola: Almighty damage to all foes.[n][e]

[msg Item_01C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Megidolaon: Almighty damage to all foes.[n][e]

[msg Item_01D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Kouha: Light damage to 1 foe.[n][e]

[msg Item_01E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Kouga: Light damage to 1 foe.[n][e]

[msg Item_01F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Kougaon: Light damage to 1 foe.[n][e]

[msg Item_020]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Makouha: Light damage to all foes.[n][e]

[msg Item_021]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Makouga: Light damage to all foes.[n][e]

[msg Item_022]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Makougaon: Light damage to all foes.[n][e]

[msg Item_023]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Divine Judgment: Halves HP of 1 foe.[n][e]

[msg Item_024]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Hama: Light instakill to 1 foe.[n][e]

[msg Item_025]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mahama: Light instakill to all foes.[n][e]

[msg Item_026]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Hamaon: Light instakill to 1 foe.[n][e]

[msg Item_027]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mahamaon: Light instakill to all foes.[n][e]

[msg Item_028]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Eiha: Dark damage to 1 foe.[n][e]

[msg Item_029]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Eiga: Dark damage to 1 foe.[n][e]

[msg Item_02A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Eigaon: Dark damage to 1 foe.[n][e]

[msg Item_02B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maeiha: Dark damage to all foes.[n][e]

[msg Item_02C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maeiga: Dark damage to all foes.[n][e]

[msg Item_02D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Maeigaon: Dark damage to all foes.[n][e]

[msg Item_02E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Demonic Decree: Halves HP of 1 foe.[n][e]

[msg Item_02F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mudo: Dark instakill to 1 foe.[n][e]

[msg Item_030]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mamudo: Dark instakill to all foes.[n][e]

[msg Item_031]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mudoon: Dark instakill to 1 foe.[n][e]

[msg Item_032]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mamudoon: Dark instakill to all foes.[n][e]

[msg Item_033]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Marin Karin: Inflict Charm on 1 foe.[n][e]

[msg Item_034]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Sexy Dance: Inflict Charm on all foes.[n][e]

[msg Item_035]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Bewilder: Inflict Distress on 1 foe.[n][e]

[msg Item_036]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Eerie Sound: Inflict Distress on all foes.[n][e]

[msg Item_037]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Pulinpa: Inflict Confuse on 1 foe.[n][e]

[msg Item_038]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Tentarafoo: Inflict Confuse on all foes.[n][e]

[msg Item_039]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evil Touch: Inflict Fear on 1 foe.[n][e]

[msg Item_03A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evil Smile: Inflict Fear on all foes.[n][e]

[msg Item_03B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ghastly Wail: Instakill all foes afflicted with Fear.[n][e]

[msg Item_03C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Provoke: Inflict Rage on 1 foe.[n][e]

[msg Item_03D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Infuriate: Inflict Rage on all foes.[n][e]

[msg Item_03E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Poisma: Inflict Poison on 1 foe.[n][e]

[msg Item_03F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Poison Mist: Inflict Poison on all foes.[n][e]

[msg Item_040]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Virus Breath: Almighty and Poison to all foes.[n][e]

[msg Item_041]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Foul Breath: Makes it easier to inflict ailments.[n][e]

[msg Item_042]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Stagnant Air: Makes it easier to inflict ailments.[n][e]

[msg Item_043]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Life Drain: Drains HP from 1 foe.[n][e]

[msg Item_044]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Spirit Drain: Drains SP from 1 foe.[n][e]

[msg Item_045]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Bash: Strike damage to 1 foe.[n][e]

[msg Item_046]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Assault Dive: Strike damage to 1 foe.[n][e]

[msg Item_047]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_048]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Swift Strike: Strike damage to all foes.[n][e]

[msg Item_049]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Sonic Punch: Strike damage to 1 foe.[n][e]

[msg Item_04A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Heat Wave: Strike damage to all foes.[n][e]

[msg Item_04B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Gigantic Fist: Strike damage to 1 foe.[n][e]

[msg Item_04C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Akasha Arts: Strike damage to all foes.[n][e]

[msg Item_04D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows God's Hand: Strike damage to 1 foe.[n][e]

[msg Item_04E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_04F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Fatal End: Slash damage to 1 foe.[n][e]

[msg Item_050]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Getsu-ei: Slash damage to 1 foe.[n][e]

[msg Item_051]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Zan-ei: Slash damage to 1 foe.[n][e]

[msg Item_052]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Neuro Slash: Slash damage to all foes.[n][e]

[msg Item_053]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_054]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Blade of Fury: Slash damage to all foes.[n][e]

[msg Item_055]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Deathbound: Slash damage to all foes.[n][e]

[msg Item_056]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Tempest Slash: Slash damage to 1 foe.[n][e]

[msg Item_057]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_058]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_059]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Power Slash: Slash damage to 1 foe.[n][e]

[msg Item_05A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Vacuum Slash: Slash damage to all foes.[n][e]

[msg Item_05B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Brave Blade: Slash damage to 1 foe.[n][e]

[msg Item_05C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Herculean Strike: Strike damage to all foes.[n][e]

[msg Item_05D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_05E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Single Shot: Pierce damage to 1 foe.[n][e]

[msg Item_05F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_060]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Holy Arrow: Pierce damage to 1 foe.[n][e]

[msg Item_061]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Torrent Shot: Pierce damage to 1 foe.[n][e]

[msg Item_062]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Arrow Rain: Pierce damage to all foes.[n][e]

[msg Item_063]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Myriad Arrows: Pierce damage to all foes.[n][e]

[msg Item_064]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Primal Force: Pierce damage to 1 foe.[n][e]

[msg Item_065]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Vorpal Blade: Slash damage to all foes.[n][e]

[msg Item_066]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_067]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Cruel Attack: Pierce damage to 1 foe.[n][e]

[msg Item_068]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Vile Assault: Pierce damage to 1 foe.[n][e]

[msg Item_069]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Poison Arrow: Pierce damage to 1 foe.[n][e]

[msg Item_06A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dia: Restore 1 ally's HP.[n][e]

[msg Item_06B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Diarama: Restore 1 ally's HP.[n][e]

[msg Item_06C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Diarahan: Restore 1 ally's HP.[n][e]

[msg Item_06D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Media: Restore party's HP.[n][e]

[msg Item_06E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mediarama: Restore party's HP.[n][e]

[msg Item_06F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mediarahan: Restore party's HP.[n][e]

[msg Item_070]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Salvation: Restore party's HP and cure ailments.[n][e]

[msg Item_071]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Patra: Cure certain ailments for 1 ally.[n][e]

[msg Item_072]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Me Patra: Cure certain ailments for all allies.[n][e]

[msg Item_073]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_074]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_075]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Baisudi: Cure certain ailments for 1 ally.[n][e]

[msg Item_076]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mabaisudi: Cure certain ailments for all allies.[n][e]

[msg Item_077]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_078]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Amrita Drop: Cure status ailment of 1 ally.[n][e]

[msg Item_079]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Amrita Shower: Cure status ailment of all allies.[n][e]

[msg Item_07A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Recarm: Revive 1 ally with 50% HP.[n][e]

[msg Item_07B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Samarecarm: Revive 1 ally with full HP.[n][e]

[msg Item_07C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Tarunda: Lower Attack of 1 foe.[n][e]

[msg Item_07D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Matarunda: Lower Attack of all foes.[n][e]

[msg Item_07E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Sukunda: Lower hit rate of 1 foe.[n][e]

[msg Item_07F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Masukunda: Lower hit rate of all foes.[n][e]

[msg Item_080]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Rakunda: Lower Defense of 1 foe.[n][e]

[msg Item_081]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Marakunda: Lower Defense of all foes.[n][e]

[msg Item_082]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dekunda: Nullify stat debuffs for allies.[n][e]

[msg Item_083]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Tarukaja: Raise Attack of 1 ally.[n][e]

[msg Item_084]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Matarukaja: Raise Attack of all allies.[n][e]

[msg Item_085]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Sukukaja: Raise hit rate of 1 ally.[n][e]

[msg Item_086]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Masukukaja: Raise hit rate of all allies.[n][e]

[msg Item_087]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Rakukaja: Raise Defense of 1 ally.[n][e]

[msg Item_088]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Marakukaja: Raise Defense of all allies.[n][e]

[msg Item_089]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Heat Riser: Raise all stats of 1 ally.[n][e]

[msg Item_08A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Debilitate: Lower all stats of 1 foe.[n][e]

[msg Item_08B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Charge: Makes next physical attack stronger.[n][e]

[msg Item_08C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Concentrate: Makes next magic attack stronger.[n][e]

[msg Item_08D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dekaja: Nullify stat buffs for foes.[n][e]

[msg Item_08E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Tetrakarn: Repel 1 physical attack.[n][e]

[msg Item_08F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Makarakarn: Repel 1 magic attack.[n][e]

[msg Item_090]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Rebellion: Raise critical rate for 1 ally.[n][e]

[msg Item_091]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Revolution: Raise critical rate for all allies and foes.[n][e]

[msg Item_092]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Fire Break: Negate Fire resistance.[n][e]

[msg Item_093]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ice Break: Negate Ice resistance.[n][e]

[msg Item_094]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Wind Break: Negate Wind resistance.[n][e]

[msg Item_095]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Elec Break: Negate Electric resistance.[n][e]

[msg Item_096]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_097]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Recarmdra: Heal all allies. User's HP becomes 1.[n][e]

[msg Item_098]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_099]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Slash: Slash affinity becomes Resist.[n][e]

[msg Item_09B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Slash: Slash affinity becomes Null.[n][e]

[msg Item_09C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Slash: Slash affinity becomes Repel.[n][e]

[msg Item_09D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Slash: Slash affinity becomes Drain.[n][e]

[msg Item_09E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Strike: Strike affinity becomes Resist.[n][e]

[msg Item_09F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Strike: Strike affinity becomes Null.[n][e]

[msg Item_0A0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Strike: Strike affinity becomes Repel.[n][e]

[msg Item_0A1]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Strike: Strike affinity becomes Drain.[n][e]

[msg Item_0A2]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Pierce: Pierce affinity becomes Resist.[n][e]

[msg Item_0A3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Pierce: Pierce affinity becomes Null.[n][e]

[msg Item_0A4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Pierce: Pierce affinity becomes Repel.[n][e]

[msg Item_0A5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Pierce: Pierce affinity becomes Drain.[n][e]

[msg Item_0A6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Fire: Fire affinity becomes Resist.[n][e]

[msg Item_0A7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Fire: Fire affinity becomes Null.[n][e]

[msg Item_0A8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Fire: Fire affinity becomes Repel.[n][e]

[msg Item_0A9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Fire: Fire affinity becomes Drain.[n][e]

[msg Item_0AA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Ice: Ice affinity becomes Resist.[n][e]

[msg Item_0AB]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Ice: Ice affinity becomes Null.[n][e]

[msg Item_0AC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Ice: Ice affinity becomes Repel.[n][e]

[msg Item_0AD]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Ice: Ice affinity becomes Drain.[n][e]

[msg Item_0AE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Elec: Electric affinity becomes Resist.[n][e]

[msg Item_0AF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Elec: Electric affinity becomes Null.[n][e]

[msg Item_0B0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Elec: Electric affinity becomes Repel.[n][e]

[msg Item_0B1]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Elec: Electric affinity becomes Drain.[n][e]

[msg Item_0B2]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Wind: Wind affinity becomes Resist.[n][e]

[msg Item_0B3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Wind: Wind affinity becomes Null.[n][e]

[msg Item_0B4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Wind: Wind affinity becomes Repel.[n][e]

[msg Item_0B5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Wind: Wind affinity becomes Drain.[n][e]

[msg Item_0B6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Light: Light affinity becomes Resist.[n][e]

[msg Item_0B7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Light: Light affinity becomes Null.[n][e]

[msg Item_0B8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Light: Light affinity becomes Repel.[n][e]

[msg Item_0B9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Dark: Dark affinity becomes Resist.[n][e]

[msg Item_0BA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Dark: Dark affinity becomes Null.[n][e]

[msg Item_0BB]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Repel Dark: Dark affinity becomes Repel.[n][e]

[msg Item_0BC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Charm: Harder to be inflicted with Charm.[n][e]

[msg Item_0BD]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Charm: Cannot be inflicted with Charm.[n][e]

[msg Item_0BE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Distress: Harder to be inflicted with Distress.[n][e]

[msg Item_0BF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Distress: Cannot be inflicted with Distress.[n][e]

[msg Item_0C0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Confuse: Harder to be inflicted with Confuse.[n][e]

[msg Item_0C1]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Confuse: Cannot be inflicted with Confuse.[n][e]

[msg Item_0C2]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Fear: Harder to be inflicted with Fear.[n][e]

[msg Item_0C3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Fear: Cannot be inflicted with Fear.[n][e]

[msg Item_0C4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Rage: Harder to be inflicted with Rage.[n][e]

[msg Item_0C5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Rage: Cannot be inflicted with Rage.[n][e]

[msg Item_0C6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Freeze: Harder to be inflicted with Freeze.[n][e]

[msg Item_0C7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Freeze: Cannot be inflicted with Freeze.[n][e]

[msg Item_0C8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Shock: Harder to be inflicted with Shock.[n][e]

[msg Item_0C9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Shock: Cannot be inflicted with Shock.[n][e]

[msg Item_0CA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Poison: Harder to be inflicted with Poison.[n][e]

[msg Item_0CB]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Null Poison: Cannot be inflicted with Poison.[n][e]

[msg Item_0CC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Unshaken Will: Cannot be inflicted with ailments.[n][e]

[msg Item_0CD]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Slash: Easier to dodge Slash skills.[n][e]

[msg Item_0CE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Slash: Much easier to dodge Slash skills.[n][e]

[msg Item_0CF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Strike: Easier to dodge Strike skills.[n][e]

[msg Item_0D0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Strike: Much easier to dodge Strike skills.[n][e]

[msg Item_0D1]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Pierce: Easier to dodge Pierce skills.[n][e]

[msg Item_0D2]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Pierce: Much easier to dodge Pierce skills.[n][e]

[msg Item_0D3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Fire: Easier to dodge Fire skills.[n][e]

[msg Item_0D4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Fire: Much easier to dodge Fire skills.[n][e]

[msg Item_0D5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Ice: Easier to dodge Ice skills.[n][e]

[msg Item_0D6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Ice: Much easier to dodge Ice skills.[n][e]

[msg Item_0D7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Wind: Easier to dodge Wind skills.[n][e]

[msg Item_0D8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Wind: Much easier to dodge Wind skills.[n][e]

[msg Item_0D9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Elec: Easier to dodge Electric skills.[n][e]

[msg Item_0DA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Elec: Much easier to dodge Electric skills.[n][e]

[msg Item_0DB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Angelic Grace: Easier to dodge magic skills.[n][e]

[msg Item_0DD]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Slash Boost: Strengthens Slash skills by 25%.[n][e]

[msg Item_0DE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Slash Amp: Strengthens Slash skills by 50%.[n][e]

[msg Item_0DF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Strike Boost: Strengthens Strike skills by 25%.[n][e]

[msg Item_0E0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Strike Amp: Strengthens Strike skills by 50%.[n][e]

[msg Item_0E1]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Pierce Boost: Strengthens Pierce skills by 25%.[n][e]

[msg Item_0E2]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Pierce Amp: Strengthens Pierce skills by 50%.[n][e]

[msg Item_0E3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Fire Boost: Strengthens Fire skills by 25%.[n][e]

[msg Item_0E4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Fire Amp: Strengthens Fire skills by 50%.[n][e]

[msg Item_0E5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ice Boost: Strengthens Ice skills by 25%.[n][e]

[msg Item_0E6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ice Amp: Strengthens Ice skills by 50%.[n][e]

[msg Item_0E7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Elec Boost: Strengthens Electric skills by 25%.[n][e]

[msg Item_0E8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Elec Amp: Strengthens Electric skills by 50%.[n][e]

[msg Item_0E9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Wind Boost: Strengthens Wind skills by 25%.[n][e]

[msg Item_0EA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Wind Amp: Strengthens Wind skills by 50%.[n][e]

[msg Item_0EB]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Light Boost: Strengthens Light skills by 25%.[n][e]

[msg Item_0EC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Light Amp: Strengthens Light skills by 50%.[n][e]

[msg Item_0ED]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dark Boost: Strengthens Dark skills by 25%.[n][e]

[msg Item_0EE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dark Amp: Strengthens Dark skills by 50%.[n][e]

[msg Item_0EF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Light: Light affinity becomes Drain.[n][e]

[msg Item_0F0]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Dark: Dark affinity becomes Drain.[n][e]

[msg Item_0F1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F3]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Counter: Chance to Repel physical attacks.[n][e]

[msg Item_0F4]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Counterstrike: Chance to Repel physical attacks.[n][e]

[msg Item_0F5]
[uf 0 5 65278][uf 2 1]Skill Card that bestows High Counter: Chance to Repel physical attacks.[n][e]

[msg Item_0F6]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Regenerate 1: Recover 2% HP each turn.[n][e]

[msg Item_0F7]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Regenerate 2: Recover 4% HP each turn.[n][e]

[msg Item_0F8]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Regenerate 3: Recover 6% HP each turn.[n][e]

[msg Item_0F9]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Invigorate 1: Recover 3 SP each turn.[n][e]

[msg Item_0FA]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Invigorate 2: Recover 5 SP each turn.[n][e]

[msg Item_0FB]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Invigorate 3: Recover 7 SP each turn.[n][e]

[msg Item_0FC]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Growth 1: Gain EXP when not participating in battle.[n][e]

[msg Item_0FD]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Growth 2: Gain EXP when not participating in battle.[n][e]

[msg Item_0FE]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Growth 3: Gain EXP when not participating in battle.[n][e]

[msg Item_0FF]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Tarukaja: Attack up at the start of battle.[n][e]

[msg Item_100]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Rakukaja: Defense up at the start of battle.[n][e]

[msg Item_101]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Sukukaja: Hit rate up at the start of battle.[n][e]

[msg Item_102]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_103]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Sharp Student: Less likely to take a critical hit.[n][e]

[msg Item_104]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Apt Pupil: More likely to deal a critical hit.[n][e]

[msg Item_105]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ali Dance: Lower hit rate of incoming attacks.[n][e]

[msg Item_106]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Firm Stance: Halves damage, but can't dodge.[n][e]

[msg Item_107]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Spell Master: Halves SP cost of magic skills.[n][e]

[msg Item_108]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Arms Master: Halves HP cost of physical skills.[n][e]

[msg Item_109]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Divine Grace: Doubles healing effects.[n][e]

[msg Item_10C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Endure: Survive a fatal blow with 1 HP.[n][e]

[msg Item_10D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Enduring Soul: Survive a fatal blow with full HP.[n][e]

[msg Item_10E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Survive Light: Chance to endure 1 Light instakill.[n][e]

[msg Item_10F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Survive Dark: Chance to endure 1 Dark instakill.[n][e]

[msg Item_110]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Maraku: Raise Defense for all allies.[n][e]

[msg Item_111]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Mataru: Raise Attack for all allies.[n][e]

[msg Item_112]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Masuku: Raise hit rate for all allies.[n][e]

[msg Item_113]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_114]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_115]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_116]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_117]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_118]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_119]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Ailment Boost: Inflict status ailments easier.[n][e]

[msg Item_11A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Hama Boost: Raise success of Hama skills.[n][e]

[msg Item_11B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Mudo Boost: Raise success of Mudo skills.[n][e]

[msg Item_11C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Endure Light: Endure 1 Light instakill.[n][e]

[msg Item_11D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Endure Dark: Endure 1 Dark instakill.[n][e]

[msg Item_11E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_11F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Life Aid: Heal some HP and SP after a victory.[n][e]

[msg Item_120]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_121]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Phys: Physical affinities become Resist.[n][e]

[msg Item_122]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_123]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Resist Ailments: More resistant to ailments.[n][e]

[msg Item_124]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_125]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Fast Heal: Recover from ailments faster.[n][e]

[msg Item_126]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Insta-Heal: Recover from ailments in 1 turn.[n][e]

[msg Item_127]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Vidyaraja's Blessing: Raise evasion of physical skills.[n][e]

[msg Item_128]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Auto Rebellion: Raise critical rate temporarily.[n][e]

[msg Item_129]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Crit Rate Boost: Raise critical rate.[n][e]

[msg Item_12A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Crit Rate Amp: Greatly raise critical rate.[n][e]

[msg Item_12B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Survival Trick: Endure 1 instakill attack.[n][e]

[msg Item_12D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Anti-Fire Master: Resist Fire for 3 turns.[n][e]

[msg Item_12E]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Anti-Ice Master: Resist Ice for 3 turns.[n][e]

[msg Item_12F]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Anti-Electric Master: Resist Electric for 3 turns.[n][e]

[msg Item_130]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Anti-Wind Master: Resist Wind for 3 turns.[n][e]

[msg Item_131]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Soul Shift: Ally recovers SP when Shifted to.[n][e]

[msg Item_132]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Soul Chain: Recover SP when Shifted to.[n][e]

[msg Item_133]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Soul Link: Recover more SP when Shifted to.[n][e]

[msg Item_134]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Shift Boost: Raise Attack when Shifted to.[n][e]

[msg Item_135]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Shift Amp: Raise Attack when Shifted to.[n][e]

[msg Item_136]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Drain Ability: Doubles Life Drain/Spirit Drain effect.[n][e]

[msg Item_137]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Single-Target Boost: More damage on single foes.[n][e]

[msg Item_138]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Multi-Target Boost: More damage on multiple foes.[n][e]

[msg Item_139]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Light: Easier to dodge Light skills.[n][e]

[msg Item_13A]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Light: Much easier to dodge Light skills.[n][e]

[msg Item_13B]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Dodge Dark: Easier to dodge Dark skills.[n][e]

[msg Item_13C]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Evade Dark: Much easier to dodge Dark skills.[n][e]

[msg Item_13D]
[uf 0 5 65278][uf 2 1]Skill Card that bestows Almighty Boost: Raise strength of Almighty skills.[n][e]

[msg Item_13E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_140]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_141]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_142]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_143]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_144]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_145]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_146]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_147]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_148]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_149]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_150]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_151]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_152]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_153]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_154]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_155]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_156]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_157]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_158]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_159]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_160]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_161]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_162]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_163]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_164]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_165]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_166]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_167]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_168]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_169]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_170]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_171]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_172]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_173]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_174]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_175]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_176]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_177]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_178]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_179]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_180]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_181]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_182]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_183]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_184]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_185]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_186]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_187]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_188]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_189]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_190]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_191]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_192]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_193]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_194]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_195]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_196]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_197]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_198]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_199]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1ED]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

