[msg MSG_000_0_0]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]A priestess in service of the goddess Hera. When Zeus fell in love with her, he transformed her into a cow to hide her from Hera, but Hera saw through the ruse. She was rescued by Hermes, and escaped across the sea to safety.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Osiris's wife as well as his younger sister. Upon the death of her husband at the hands of Seth, she traveled all over Egypt to recover the pieces of his body, and revived him with her incredible magic power.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]A messenger god who served Zeus. His winged sandals allow him to fly, and he was worshiped as a god of travel and commerce. He was also known as a trickster, being able to freely cross between the mortal and godly realms.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]A Hellenistic figure who represents a blending of the Greek god Hermes and the Egyptian god Thoth. His full name, Hermes Trismegistus, means "Hermes, thrice greatest," and he is thought to be the author of the Corpus Hermeticum.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]A hero in Greek mythology. As the son of Zeus and the mortal Leda, he inherited his father's immortality. He and his half-brother Castor were famed fighters, and both became stars in the constellation Gemini.[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]A statesman, general, and author known for his rule over the Roman Republic. His full name was Gaius Julius Caesar. His many accomplishments led to his name being used as a title for later Roman emperors.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]A queen of the Amazons in Greek mythology. She fought for the Trojans during the Trojan War, but was slain by Achilles. When Achilles took off her helmet and saw her beautiful face, he felt great remorse for killing her.[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]The heroic queen of Halicarnassus mentioned in Herodotus's The Histories. During the Persian Wars between the Greek states and Persia, she was the only woman to take command in the Persian fleet.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]A saint who was martyred during the persecution of Christianity in the time of the Roman Empire. She was tortured and had her eyes gouged out, but a miracle restored her sight. She is revered as the patron saint of the blind.[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]The goddess of family and marriage, and wife to the Roman god Jupiter. She is often equated with the Greek goddess Hera. Though she is kind, she is also vengeful, seeking to punish women who have affairs with her husband.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]A guardian statue in ancient Greece, stolen from Troy, that protected the city in which it was enshrined. It is said that Athena was so saddened by the death of her friend, Pallas, that she had the wooden statue made in her image.[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]Daughter of Zeus, and a goddess of great martial ability. She fights to protect her land or family, but never for sheer bloodlust. Her symbol is the olive tree.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]A Greek goddess who was the personification of the gods' wrath, or "divine retribution." While known to administer vengeance, she was also perceived as fair and balanced, punishing only those that deserved it.[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]A Hindu goddess whose name means "edge of the wheel of time." The "wheel" refers to samsara, the cycle of death and rebirth, meaning she is a goddess who has transcended life itself.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]A hero in Greek mythology. He is Polydeuces's half-brother, but doesn't share his brother's immortality. He was struck and killed by an arrow, after which he and his brother became stars in the constellation Gemini.[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]The giant hound that guards the great abyss, Tartarus. He answers to Hades, the lord of the underworld, and keeps watch for both intruders and escapees. He was born from Typhon and Echidna, and is the older brother of Orthrus.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]A woman from Greek mythology said to rival the goddess of beauty herself. She fell in love with Eros, the god of love. After overcoming numerous trials, she was allowed to be with him, and became the goddess of the soul.[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_031_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_032_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_033_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_034_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_035_0_0]
[uf 0 5 65278][uf 2 1]Eighth of the nine orders of angels. Their duty is to minister to humans and deliver messages. They are warriors of Heaven and lead Heaven's forces during battle with the armies of evil.[n][uf 1 1][e]

[msg MSG_036_0_0]
[uf 0 5 65278][uf 2 1]The Hindu king of Asuras is named Maha Vairocana, or "One Who Shines On All." In Buddhism, he is known as Dainichi Nyorai.[n][uf 1 1][e]

[msg MSG_037_0_0]
[uf 0 5 65278][uf 2 1]One of the eight Yasha-o. His domain is war and protection. Once a child-eating demon, he became one of the greatest of the Wisdom Kings after the Buddha converted him to good.[n][uf 1 1][e]

[msg MSG_038_0_0]
[uf 0 5 65278][uf 2 1]A Phrygian god who symbolizes life, death, and revival. He rejected Cybele's love and was driven mad, dying after he castrated himself. Cybele then resurrected him.[n][uf 1 1][e]

[msg MSG_039_0_0]
[uf 0 5 65278][uf 2 1]One of the three Moirae Sisters in Greek mythology. She cuts the life threads of those whose time has come.[n][uf 1 1][e]

[msg MSG_040_0_0]
[uf 0 5 65278][uf 2 1]The thousand-headed serpent of Hindu myth. Ananta is Sanskrit for "infinite." After resting on him, Vishnu woke up and created the universe.[n][uf 1 1][e]

[msg MSG_041_0_0]
[uf 0 5 65278][uf 2 1]The jackal-headed god of Egyptian myth. He weighs the hearts of the dead to determine their final destination. He is also associated with embalming.[n][uf 1 1][e]

[msg MSG_042_0_0]
[uf 0 5 65278][uf 2 1]The "Destroyer" and "Angel of the Bottomless Pit" as described in ancient scriptures. He controls locusts, using them to cause massive destruction to villages.[n][uf 1 1][e]

[msg MSG_043_0_0]
[uf 0 5 65278][uf 2 1]Hindu water spirits, they are beautiful young women who dance for the gods. They also guide heroes fallen in battle to paradise.[n][uf 1 1][e]

[msg MSG_044_0_0]
[uf 0 5 65278][uf 2 1]A mysterious god of ancient Japan. Most famously worshiped by Nagasunehiko, who was defeated in battle against Emperor Jinmu, Arahabaki came to be treated as a symbol of rebellion and defiance.[n][uf 1 1][e]

[msg MSG_045_0_0]
[uf 0 5 65278][uf 2 1]One of the four aspects of Shinto thought, it has the power to grant ferocity. It is said to aid in one's bravery, growth, and endeavors, though it can lead in a negative direction.[n][uf 1 1][e]

[msg MSG_046_0_0]
[uf 0 5 65278][uf 2 1]A ghost who appears as a young, blonde girl. She seems young, but has formidable magic powers. Some say she's the ghost of a poor English girl who died an unfortunate death.[n][uf 1 1][e]

[msg MSG_047_0_0]
[uf 0 5 65278][uf 2 1]The Arabian mother goddess, also known as Allat. The Black Stone at the Kaaba was thought to be her residence. She and her son, Dushara, were worshiped there by desert nomads.[n][uf 1 1][e]

[msg MSG_048_0_0]
[uf 0 5 65278][uf 2 1]Spirits of dogs said to possess humans in Japanese lore. Those possessed go crazy. Onmyoji, or Japanese sorcerers, summon them to do their will.[n][uf 1 1][e]

[msg MSG_049_0_0]
[uf 0 5 65278][uf 2 1]A male demon of European lore in medieval times. They visit sleeping women and have sexual intercourse with them. The resulting children become witches or wizards.[n][uf 1 1][e]

[msg MSG_050_0_0]
[uf 0 5 65278][uf 2 1]The fifth of the nine orders of angels, also known as "The Shining Ones." They work miracles and support those struggling with their faith.[n][uf 1 1][e]

[msg MSG_051_0_0]
[uf 0 5 65278][uf 2 1]A giant serpent of Hindu legend. It is said the gods and demons used him to churn the sea of milk. The strain caused him to exhale incredibly potent venom, but Shiva swallowed it.[n][uf 1 1][e]

[msg MSG_052_0_0]
[uf 0 5 65278][uf 2 1]"Choosers of the slain" in Norse lore. Armed with shining armor and swords, they look for brave warriors to take to Valhalla, so that they may fight in Ragnarok.[n][uf 1 1][e]

[msg MSG_053_0_0]
[uf 0 5 65278][uf 2 1]One of the major Hindu gods, he is the preserver and protector of the universe. Legends claim that he will make ten appearances across time and space to strike down evil and uphold justice.[n][uf 1 1][e]

[msg MSG_054_0_0]
[uf 0 5 65278][uf 2 1]One of the four major archangels. His name means "Flame of God," and he knows all the celestial phenomena. He is the first angel Satan met on earth.[n][uf 1 1][e]

[msg MSG_055_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia. He looks like a knight and has the power to see things to come. He also knows much about wars.[n][uf 1 1][e]

[msg MSG_056_0_0]
[uf 0 5 65278][uf 2 1]Ninth of the nine orders of angels. The "watchers" who never sleep. Among these are the guardian angels who are assigned to every human at birth.[n][uf 1 1][e]

[msg MSG_057_0_0]
[uf 0 5 65278][uf 2 1]A Kunitsu deity of Japanese mythology that governs agriculture and medicine. Said to have built the country of Izumo with Susano-o's daughter, Suseri-Hime.[n][uf 1 1][e]

[msg MSG_058_0_0]
[uf 0 5 65278][uf 2 1]The father of all gods in Norse legend. He willingly sacrificed one eye to gain wisdom. In preparation for Ragnarok, he gathers the souls of fallen warriors to his hall, Valhalla.[n][uf 1 1][e]

[msg MSG_059_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia, he is known as the President of Hell. He can shape-shift from leopard to human and reveal the truth behind divine mysteries.[n][uf 1 1][e]

[msg MSG_060_0_0]
[uf 0 5 65278][uf 2 1]An evil monster from Japanese lore known for its hideous appearance and brute strength. They loot and plunder villages, massacring the townspeople with their iron clubs.[n][uf 1 1][e]

[msg MSG_061_0_0]
[uf 0 5 65278][uf 2 1]The king of the fairies and Titania's husband. He is quite old but, due to a curse, his looks are that of a young boy. He often flirts with human women, ending in a scolding from his wife.[n][uf 1 1][e]

[msg MSG_062_0_0]
[uf 0 5 65278][uf 2 1]A deity of knowledge in Japanese myth. He conceived the plan to draw Amaterasu from the Amato-Iwato, the cave she was hiding in.[n][uf 1 1][e]

[msg MSG_063_0_0]
[uf 0 5 65278][uf 2 1]The two-headed pet dog belonging to the giant, Geryon, in Greek myth. He guarded a herd of red oxen, but was killed by Hercules during one of his twelve labors.[n][uf 1 1][e]

[msg MSG_064_0_0]
[uf 0 5 65278][uf 2 1]A poet of Greek mythology skilled with the lyre. He tried to retrieve his wife from Hades, but she vanished when he looked upon her before reaching the surface.[n][uf 1 1][e]

[msg MSG_065_0_0]
[uf 0 5 65278][uf 2 1]By bonding with many people, Orpheus was once again born from the sea of the soul. He has awakened to a power that holds infinite possibilities.[n][uf 1 1][e]

[msg MSG_066_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia. Known as the Prince of Hell, he appears as a horse and answers questions of the past, present, and future. He is faithful to his conjurer.[n][uf 1 1][e]

[msg MSG_067_0_0]
[uf 0 5 65278][uf 2 1]A monstrous, fire-spitting, Japanese bird with a man's face. It is actually a corpse that was not given a proper memorial service. They appear before monks who neglect their duties.[n][uf 1 1][e]

[msg MSG_068_0_0]
[uf 0 5 65278][uf 2 1]A goddess of death and destruction. She is said to be another face of Parvati. She is violent, bloodthirsty, wears a string of skulls, and carries bloody weapons, but she also blesses her followers.[n][uf 1 1][e]

[msg MSG_069_0_0]
[uf 0 5 65278][uf 2 1]The Hindu elephant-headed god. He was originally created by Parvati to prevent anyone from watching her bathe. Shiva batted off his original head and replaced it with an elephant's head.[n][uf 1 1][e]

[msg MSG_070_0_0]
[uf 0 5 65278][uf 2 1]A spirit of Chinese folklore who dwells in trees once used for hangings. She is smaller than a human and cannot speak, but her voice is said to be as clear and as beautiful as a bird's song.[n][uf 1 1][e]

[msg MSG_071_0_0]
[uf 0 5 65278][uf 2 1]One of the four major archangels. She is also the only female angel at this rank. Her name comes from the Sumerian word for "governor." She is the angel who told Mary of her pregnancy.[n][uf 1 1][e]

[msg MSG_072_0_0]
[uf 0 5 65278][uf 2 1]A divine bird-man in Hindu lore. He once fought the gods and received immortality in exchange for becoming Vishnu's carrier.[n][uf 1 1][e]

[msg MSG_073_0_0]
[uf 0 5 65278][uf 2 1]The personification of the Ganges River. Originally from the heavens, she came to earth to clean the souls of the people as a result of the prayers of Bhagiratha.[n][uf 1 1][e]

[msg MSG_074_0_0]
[uf 0 5 65278][uf 2 1]A god in Assyrian legend. His name is interchangeable with that of Sakkut, another incarnation of the star god, Saturn.[n][uf 1 1][e]

[msg MSG_075_0_0]
[uf 0 5 65278][uf 2 1]The goddess of life in Shinto myth. She once mediated between Izanagi and Izanami during their confrontation in Yomi, the land of the dead.[n][uf 1 1][e]

[msg MSG_076_0_0]
[uf 0 5 65278][uf 2 1]The offspring of Typhon and Echidna, this monster of Greek myth is part lion, part goat, and part dragon.[n][uf 1 1][e]

[msg MSG_077_0_0]
[uf 0 5 65278][uf 2 1]The Phrygian mother goddess of the earth, she is often depicted with wild animals, and lions in particular. She had her priest, Attis, as a lover, but drove him insane when he was forced to marry another.[n][uf 1 1][e]

[msg MSG_078_0_0]
[uf 0 5 65278][uf 2 1]A giant elephant monster of Sri Lankan myth, it is typically portrayed as being ridden by the Evil One, Mara. Whoever looks into its evil eye is said to be met with misfortune.[n][uf 1 1][e]

[msg MSG_079_0_0]
[uf 0 5 65278][uf 2 1]The king of snow who rules over an infinite number of Jack Frosts. He has the power to freeze the entire world, but is unaware of it due to his naive personality.[n][uf 1 1][e]

[msg MSG_080_0_0]
[uf 0 5 65278][uf 2 1]The fairy queen in Celtic myth. Often identified with Titania, Oberon's wife. She would offer mead mixed with her blood to her many consorts.[n][uf 1 1][e]

[msg MSG_081_0_0]
[uf 0 5 65278][uf 2 1]A hero in Celtic folklore. He was called Setanta until he earned the name "Hound of Culann." There are many tales of his adventures. He received his spear, Gae Bolg, from his mentor, Scathach.[n][uf 1 1][e]

[msg MSG_082_0_0]
[uf 0 5 65278][uf 2 1]A demon of Buddhist myth said to drain human life energy. He has dark skin, stands three meters tall, and sometimes changes his shape to a gourd. Known to have once served Rudra, the god of storms.[n][uf 1 1][e]

[msg MSG_083_0_0]
[uf 0 5 65278][uf 2 1]One of the four aspects of Shinto thought, it uses its power to bring good omens. It is said to aid in one's wisdom, observation, and skill, and can mend fractured paths.[n][uf 1 1][e]

[msg MSG_084_0_0]
[uf 0 5 65278][uf 2 1]A type of tengu said to have lived on Mt. Kurama in Kyoto. The most powerful and well-known of the tengu, they have the power to fend off disease and bring good fortune.[n][uf 1 1][e]

[msg MSG_085_0_0]
[uf 0 5 65278][uf 2 1]A demon that takes the shape of a giant bird in Sri Lankan myth. It is thought to be a derivation of Garuda.[n][uf 1 1][e]

[msg MSG_086_0_0]
[uf 0 5 65278][uf 2 1]One of the three Moirae Sisters in Greek mythology. She spins the threads of fate.[n][uf 1 1][e]

[msg MSG_087_0_0]
[uf 0 5 65278][uf 2 1]An Aztec deity known as the Feathered Serpent. He created humans with his own blood and taught them how to sustain themselves.[n][uf 1 1][e]

[msg MSG_088_0_0]
[uf 0 5 65278][uf 2 1]One of the Ssu-Ling, celestial creatures of Chinese myth. It represents the direction north, the season of winter, and the element of water. Known to be a great warrior, it supports the earth from below.[n][uf 1 1][e]

[msg MSG_089_0_0]
[uf 0 5 65278][uf 2 1]Also known as Virupaksa, he is the protector of the west, and is one of the four Heavenly Kings of Buddhist origin. He keeps a close watch on the world with his sharp gaze.[n][uf 1 1][e]

[msg MSG_090_0_0]
[uf 0 5 65278][uf 2 1]Known as the Yellow Dragon and renowned as the most benevolent of the dragons. It reigns over the Ssu-Ling, celestial creatures in Chinese myth. It is located in the center of the four beasts.[n][uf 1 1][e]

[msg MSG_091_0_0]
[uf 0 5 65278][uf 2 1]One of the four aspects of Shinto thought, it brings great bounty from the hunt. It is said to aid in love, profit, and growth, and can create new paths.[n][uf 1 1][e]

[msg MSG_092_0_0]
[uf 0 5 65278][uf 2 1]A female demon of European lore in medieval times. They visit sleeping men and have sexual intercourse with them. The victims don't wake up, but may dream of the encounter.[n][uf 1 1][e]

[msg MSG_093_0_0]
[uf 0 5 65278][uf 2 1]The prince of darkness in Judeo-Christian lore, known for his role as the snake that tempted Adam and Eve at Eden. It is also said he is sent by God to test man's piety.[n][uf 1 1][e]

[msg MSG_094_0_0]
[uf 0 5 65278][uf 2 1]Shiva's first consort in Hindu myth, she threw herself into a sacrificial fire in protest of her father's treatment of Shiva. Reborn as Parvati, she was reunited with Shiva.[n][uf 1 1][e]

[msg MSG_095_0_0]
[uf 0 5 65278][uf 2 1]The Roman god of agriculture. He is commonly identified with Cronus. In an attempt to prevent his destiny, he ate his children, but was overthrown as was fated.[n][uf 1 1][e]

[msg MSG_096_0_0]
[uf 0 5 65278][uf 2 1]A mysterious angel with the name "Poison of God." He is often shown as a serpent. Opinions differ on whether he is fallen or not, but either way, he is linked with death.[n][uf 1 1][e]

[msg MSG_097_0_0]
[uf 0 5 65278][uf 2 1]The Hindu goddess of rivers, and patron of speech, writing, learning, the arts, and sciences. Brahma is her husband.[n][uf 1 1][e]

[msg MSG_098_0_0]
[uf 0 5 65278][uf 2 1]A revered bird of Native American mythology said to live atop cloud-shrouded peaks. Resembles an eagle. Its wingbeats create thunderclaps, and some legends say its eyes can unleash lightning.[n][uf 1 1][e]

[msg MSG_099_0_0]
[uf 0 5 65278][uf 2 1]Metatron's twin brother in Judeo-Christian lore, he is the master of heavenly songs. It is said that a human would take 500 years to walk the length of his body.[n][uf 1 1][e]

[msg MSG_100_0_0]
[uf 0 5 65278][uf 2 1]A fairy in German folklore who carries a bag of magical sand, which puts humans to sleep when thrown into their eyes. If the victim resists, the Sandman will sit on their eyelids.[n][uf 1 1][e]

[msg MSG_101_0_0]
[uf 0 5 65278][uf 2 1]The German name of the hero in the epic poem of the Nibelungenlied. The dragon Fafnir's blood made him invincible, but a single leaf on his back resulted in a weak spot.[n][uf 1 1][e]

[msg MSG_102_0_0]
[uf 0 5 65278][uf 2 1]A holy beast said to protect houses from evil and bring good fortune. It looks similar to a Shinto guardian dog, but is actually modeled after a lion. There are many stories about it in Ryukyu lore.[n][uf 1 1][e]

[msg MSG_103_0_0]
[uf 0 5 65278][uf 2 1]One of the major Hindu gods, he is known as the Destroyer but is also related to regeneration. His wife is Parvati.[n][uf 1 1][e]

[msg MSG_104_0_0]
[uf 0 5 65278][uf 2 1]An exceptionally powerful shikigami. Only the most elite onmyoji are able to summon it and bind it to paper. It can ward off disaster or cure illness, but its ordinary temperament is quite vicious.[n][uf 1 1][e]

[msg MSG_105_0_0]
[uf 0 5 65278][uf 2 1]Also known as Dhrtarastra, he is the protector of the east, and is one of the four Heavenly Kings of Buddhist origin. He helps maintain the security of the nation.[n][uf 1 1][e]

[msg MSG_106_0_0]
[uf 0 5 65278][uf 2 1]A Jack Frost that wished for evil powers. This powerful demon is born when a cute Jack Frost remembers its nature as a demon.[n][uf 1 1][e]

[msg MSG_107_0_0]
[uf 0 5 65278][uf 2 1]The king of birds in Hindu myth. In the Ramayana, he fought bravely, but lost to Ravana in an attempt to save Sita, Rama's wife, the 7th avatar of Vishnu.[n][uf 1 1][e]

[msg MSG_108_0_0]
[uf 0 5 65278][uf 2 1]A winter fairy of European descent. He leaves ice patterns on windows and nips people's noses. Though normally an innocent creature, he will freeze his victims to death if provoked.[n][uf 1 1][e]

[msg MSG_109_0_0]
[uf 0 5 65278][uf 2 1]A drunkard who tricked the Devil out of taking him to Hell. When refused entry to Heaven, he was forced to wander the earth with only an ember as a light.[n][uf 1 1][e]

[msg MSG_110_0_0]
[uf 0 5 65278][uf 2 1]A Chinese god of war, he is said to have invented many weapons. He and his followers rebelled against the Yellow Emperor, Huang Di, but were ultimately defeated.[n][uf 1 1][e]

[msg MSG_111_0_0]
[uf 0 5 65278][uf 2 1]A fairy of England and Scotland. She carries out household chores while everyone sleeps and is a welcome spirit. It is said you can hear her silk skirt rustle as she works.[n][uf 1 1][e]

[msg MSG_112_0_0]
[uf 0 5 65278][uf 2 1]A warrior woman of the Land of Shadows in Celtic lore. She taught the hero Cu Chulainn the art of war and gave him the spear Gae Bolg.[n][uf 1 1][e]

[msg MSG_113_0_0]
[uf 0 5 65278][uf 2 1]A Norse giantess called the "snow-shoe goddess" and the embodiment of winter. According to legend, all the gods will return to her at the end of Ragnarok.[n][uf 1 1][e]

[msg MSG_114_0_0]
[uf 0 5 65278][uf 2 1]One of the Ssu-Ling, celestial creatures of Chinese myth. It is a giant bird that is said to chirp in five beautiful voices. It represents the direction south, the season of summer, and the element of fire.[n][uf 1 1][e]

[msg MSG_115_0_0]
[uf 0 5 65278][uf 2 1]A god of Japanese legend, born along with Amaterasu and Tsukuyomi. He was cast out for lewd behavior, but redeemed himself with heroic deeds like slaying Yamata-no-Orochi.[n][uf 1 1][e]

[msg MSG_116_0_0]
[uf 0 5 65278][uf 2 1]A primitive monster with a viscous body. There are various theories as to its origin, but it is still under debate. Said to compulsively collect shiny objects.[n][uf 1 1][e]

[msg MSG_117_0_0]
[uf 0 5 65278][uf 2 1]A fire giant in Norse mythology. He rules the fire realm, Muspelheim, and brandishes a burning sword. At Ragnarok, he will set the world ablaze.[n][uf 1 1][e]

[msg MSG_118_0_0]
[uf 0 5 65278][uf 2 1]Also known as "Sun Wukong," he was supposedly born from a rock. After wreaking havoc, he was punished by Buddha, but was eventually saved by a monk named Sanzang.[n][uf 1 1][e]

[msg MSG_119_0_0]
[uf 0 5 65278][uf 2 1]The noblest of the Ssu-Ling, celestial creatures of Chinese myth. It represents the direction east, the season of spring, and the element of wood. It dwells in a palace at the bottom of the ocean.[n][uf 1 1][e]

[msg MSG_120_0_0]
[uf 0 5 65278][uf 2 1]A brave young man in Celtic myth. After defeating a fierce guard dog, he volunteered to take its place, earning him the nickname "Hound of Culann."[n][uf 1 1][e]

[msg MSG_121_0_0]
[uf 0 5 65278][uf 2 1]The Egyptian god of the desert, chaos, and evil. He murdered his brother, Osiris, and tried to become chief god, but he was castrated by Osiris's son, Horus.[n][uf 1 1][e]

[msg MSG_122_0_0]
[uf 0 5 65278][uf 2 1]Also known as Virudhaka, he is the protector of the south and is one of the four Heavenly Kings of Buddhist origin. He is the god of the five grains, and was once the chief of the gods.[n][uf 1 1][e]

[msg MSG_123_0_0]
[uf 0 5 65278][uf 2 1]The third of the nine orders of angels. They are the angels of dignity and justice who carry God's throne and govern thought. They are angels of knowledge.[n][uf 1 1][e]

[msg MSG_124_0_0]
[uf 0 5 65278][uf 2 1]Hindu deities of passion and relations. They are Kali's attendants. They eat human flesh and gather at graveyards and crematories each night. Their name means "sky dancer."[n][uf 1 1][e]

[msg MSG_125_0_0]
[uf 0 5 65278][uf 2 1]A monk who died while fasting. His spiritual power allows his body to continue to exist without rotting. It is said that he will appear before people on the day of salvation.[n][uf 1 1][e]

[msg MSG_126_0_0]
[uf 0 5 65278][uf 2 1]The Japanese god of thunder. He carries the divine sword Totsuka-no-Tsurugi and is said to be the founder of ancient sumo wrestling.[n][uf 1 1][e]

[msg MSG_127_0_0]
[uf 0 5 65278][uf 2 1]A Japanese god of war, hunting, and fertility. He fought Take-Mikazuchi for control of Japan and lost. He escaped to Suwa, but was prohibited to leave.[n][uf 1 1][e]

[msg MSG_128_0_0]
[uf 0 5 65278][uf 2 1]The Greek god of death, he is the son of Nyx and the brother of Hypnos. He is depicted as a young man with an inverted torch and a wreath or butterfly in his hands.[n][uf 1 1][e]

[msg MSG_129_0_0]
[uf 0 5 65278][uf 2 1]A fae knight of the Seelie Court, said to protect the forest of Carterhaugh. After being kidnapped by the faeries at the tender age of nine, he lived much of his life among them.[n][uf 1 1][e]

[msg MSG_130_0_0]
[uf 0 5 65278][uf 2 1]A cursed god of the darkness in Slavic myth. His name means "Black God." He is the counterpart of the "White God" Belobog.[n][uf 1 1][e]

[msg MSG_131_0_0]
[uf 0 5 65278][uf 2 1]The Greek god of wine and theater. He had two births. When his mother died while bearing him, Zeus took the premature infant and let him mature in Zeus's own thigh so that Dionysus may have a proper birth.[n][uf 1 1][e]

[msg MSG_132_0_0]
[uf 0 5 65278][uf 2 1]The queen of the fairies and Oberon's wife. She is derived from the Roman goddess Diana. She was later immortalized in Shakespeare's play A Midsummer Night's Dream.[n][uf 1 1][e]

[msg MSG_133_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia, this demon appears as a pentacle. Keeper of jewels and herbal lore, Decarabia is said to have the ability to shape-shift at will.[n][uf 1 1][e]

[msg MSG_134_0_0]
[uf 0 5 65278][uf 2 1]The Egyptian moon god who takes the form of a baboon, he is the one who measures time. He gave Isis the power to resurrect Osiris after he was killed by the evil god Seth.[n][uf 1 1][e]

[msg MSG_135_0_0]
[uf 0 5 65278][uf 2 1]The Norse thunder god and son of Odin. He owns the power-enhancing belt, Megingjard, and wields Mjolnir, a hammer that causes lightning to strike and returns to its owner if thrown.[n][uf 1 1][e]

[msg MSG_136_0_0]
[uf 0 5 65278][uf 2 1]The fourth of the nine orders of angels. Their duty is to oversee the other angels. Their actions are the manifestation of God's will.[n][uf 1 1][e]

[msg MSG_137_0_0]
[uf 0 5 65278][uf 2 1]Angels said to sound the trumpets at the apocalypse. Each trumpet brings more plagues and disasters, turning the earth into a land of death and suffering.[n][uf 1 1][e]

[msg MSG_138_0_0]
[uf 0 5 65278][uf 2 1]Half-snake, half-human, they are divine beings in Hindu mythology. Worshiped as bringers of fertility.[n][uf 1 1][e]

[msg MSG_139_0_0]
[uf 0 5 65278][uf 2 1]The king of the Naga, a half-man, half-snake tribe in Hindu lore. The dragon kings Nanda and Takshaka of Buddhist myth fall into this royal category.[n][uf 1 1][e]

[msg MSG_140_0_0]
[uf 0 5 65278][uf 2 1]A young man of Greek myth. He rejected the nymph Echo, who faded to a whisper out of despair. Cursed by Nemesis, he fell in love with his own reflection and wasted away.[n][uf 1 1][e]

[msg MSG_141_0_0]
[uf 0 5 65278][uf 2 1]An evil dragon that gnaws on the roots of Yggdrasil, the World Tree. It rules over the evil snakes that live there. Capable of surviving Ragnarok by feeding on the slain corpses that drift to it.[n][uf 1 1][e]

[msg MSG_142_0_0]
[uf 0 5 65278][uf 2 1]One of the four aspects of Shinto thought, it works gently to help maintain a calm mind. It is said to aid in one's relations and sociability, and can lead one in a positive direction.[n][uf 1 1][e]

[msg MSG_143_0_0]
[uf 0 5 65278][uf 2 1]A prophetic Taoist god, originally known as Mao Shogun. Due to a linguistic error involving the Chinese word for cat, his name became Neko Shogun.[n][uf 1 1][e]

[msg MSG_144_0_0]
[uf 0 5 65278][uf 2 1]Incarnations of long-lived cats in Japanese mythology. They have various powers, including human speech and control over the dead.[n][uf 1 1][e]

[msg MSG_145_0_0]
[uf 0 5 65278][uf 2 1]The general of Hell, he keeps watch over other demons. One of the greatest necromancers in Hell, he can control souls and corpses.[n][uf 1 1][e]

[msg MSG_146_0_0]
[uf 0 5 65278][uf 2 1]Goddesses of fate in Norse myth. They live below the roots of Yggdrasil and weave the threads of fate, which even the gods are bound by.[n][uf 1 1][e]

[msg MSG_147_0_0]
[uf 0 5 65278][uf 2 1]Demon whose name means "Lord of the High Place." Possibly derived from the Syrian deity Ba'al, he presides over death and the spirits of the deceased. Many worshiped him because of this power.[n][uf 1 1][e]

[msg MSG_148_0_0]
[uf 0 5 65278][uf 2 1]A beautiful Hindu goddess of love and one of Shiva's wives. Always by his side, she played a role in opening his third eye. She can turn into Durga or Kali when angered.[n][uf 1 1][e]

[msg MSG_149_0_0]
[uf 0 5 65278][uf 2 1]The leader of a swarm of pixies. Any pixie in a leadership role or with remarkable power is called by this name.[n][uf 1 1][e]

[msg MSG_150_0_0]
[uf 0 5 65278][uf 2 1]The Babylonian lord of wind and scorching sands. Has a lion's head and arms, eagle-clawed feet, bird wings, and deadly poison. The diseases he spreads can only be cured by magical means.[n][uf 1 1][e]

[msg MSG_151_0_0]
[uf 0 5 65278][uf 2 1]A monkey god of Hindu descent. His father is Vayu, the wind god. Extremely nimble, he performed many heroic deeds in the Ramayana. He is powerful, can fly, and can change his shape into many forms.[n][uf 1 1][e]

[msg MSG_152_0_0]
[uf 0 5 65278][uf 2 1]A goat-headed demon that is worshiped in Black Sabbaths. His name is sometimes used as a generic name for any demon. He would become an object of worship for witches.[n][uf 1 1][e]

[msg MSG_153_0_0]
[uf 0 5 65278][uf 2 1]Also known as Kishimojin, she once ate children, but stopped after Buddha changed her ways. She now eats pomegranates and is a goddess of parenting.[n][uf 1 1][e]

[msg MSG_154_0_0]
[uf 0 5 65278][uf 2 1]A mystical creature in Balinese lore, it represents good and is Rangda's eternal rival. Even if defeated, it will be reborn. The result is a never-ending struggle.[n][uf 1 1][e]

[msg MSG_155_0_0]
[uf 0 5 65278][uf 2 1]The sixth of the nine orders of angels. It is said that they were the first order to be created. Their duty is to protect human souls from demons.[n][uf 1 1][e]

[msg MSG_156_0_0]
[uf 0 5 65278][uf 2 1]Friendly fairies of the forest that tend to hide from humans. They like to play tricks on lazy people. It is said they are the souls of dead, unbaptized children.[n][uf 1 1][e]

[msg MSG_157_0_0]
[uf 0 5 65278][uf 2 1]A type of preta, or "hungry ghost," in Hindu lore that eats human corpses. It enters a human through the mouth and causes harm. Those who see one are said to die within nine months.[n][uf 1 1][e]

[msg MSG_158_0_0]
[uf 0 5 65278][uf 2 1]Also known as Tamonten and Vaisravana in Buddhist lore, he is the strongest of the Heavenly Kings. He protects the north and is the god of war.[n][uf 1 1][e]

[msg MSG_159_0_0]
[uf 0 5 65278][uf 2 1]One of the Ssu-Ling, celestial creatures of Chinese myth. It represents the direction west, the season of autumn, and the element of metal. He is believed to be the king of all beasts.[n][uf 1 1][e]

[msg MSG_160_0_0]
[uf 0 5 65278][uf 2 1]The Roman goddess of luck, she spins the Wheel of Fortune. She is believed to have originally been a fertility goddess. Her Greek counterpart is Tyche.[n][uf 1 1][e]

[msg MSG_161_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia, he appears as a great sea monster. Known as a Great Marquis of Hell, he is skilled linguistically and is a master of rhetoric.[n][uf 1 1][e]

[msg MSG_162_0_0]
[uf 0 5 65278][uf 2 1]The Nihonshoki sword deity who pacified Ashihara-no-Nakatsukuni. His name comes from "futsu," the fashion in which things are cut, and "nushi," his nature as a god.[n][uf 1 1][e]

[msg MSG_163_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia. He appears as a leopard and can see the past and future. He can control fire and burn all his adversaries to death.[n][uf 1 1][e]

[msg MSG_164_0_0]
[uf 0 5 65278][uf 2 1]The seventh of the nine orders of angels. They guard cities and nations, and protect various religious figures.[n][uf 1 1][e]

[msg MSG_165_0_0]
[uf 0 5 65278][uf 2 1]One of the Four Horsemen of the Apocalypse, he rides a pale horse and represents death. He has the power to destroy life.[n][uf 1 1][e]

[msg MSG_166_0_0]
[uf 0 5 65278][uf 2 1]Giants in Greek mythology, born from Uranus and Gaia. The name means "hundred-handed." Enlisted by Zeus in the war against the Titans; thanks to their help, the gods were victorious.[n][uf 1 1][e]

[msg MSG_167_0_0]
[uf 0 5 65278][uf 2 1]One of the 72 demons of the Goetia. Known as the Duke of Hell, he rides a gigantic horse and burns those without manners.[n][uf 1 1][e]

[msg MSG_168_0_0]
[uf 0 5 65278][uf 2 1]A motorcyclist whose violent nature turned him into a demon. His anger at himself and the world causes him to lash out, so that everyone else will suffer as well.[n][uf 1 1][e]

[msg MSG_169_0_0]
[uf 0 5 65278][uf 2 1]Demonic Lord of the Flies whose insect minions carry souls for him to control. He is mentioned in the Bible as a leader of evil spirits and is seen as a powerful demon.[n][uf 1 1][e]

[msg MSG_170_0_0]
[uf 0 5 65278][uf 2 1]Demonic governor of the deadly sin of sloth. He also excels at invention and discovery. May derive from Ba'al Pe'or, Syrian god of abundant crops.[n][uf 1 1][e]

[msg MSG_171_0_0]
[uf 0 5 65278][uf 2 1]The legendary bird of myth said to appear only in times of peace. It is the ruler of all birds. When it dies, birds across the land chirp with sadness.[n][uf 1 1][e]

[msg MSG_172_0_0]
[uf 0 5 65278][uf 2 1]An ancient god of Egypt whose eyes are the sun and moon. Revered by some as the chief god, he is often depicted as a hawk or a falcon.[n][uf 1 1][e]

[msg MSG_173_0_0]
[uf 0 5 65278][uf 2 1]One of the Four Horsemen of the Apocalypse, he rides a white horse with a bow in hand. A crown was granted to him, and he promises victory.[n][uf 1 1][e]

[msg MSG_174_0_0]
[uf 0 5 65278][uf 2 1]A Buddhist demon that represents the fear of death. Also known as "The Evil One," he sent his daughters to tempt Buddha during his meditations.[n][uf 1 1][e]

[msg MSG_175_0_0]
[uf 0 5 65278][uf 2 1]The fiend known as the "Whore of Babylon," riding a beast with seven heads and ten horns, she carries a golden cup of abominations and the filth of her acts.[n][uf 1 1][e]

[msg MSG_176_0_0]
[uf 0 5 65278][uf 2 1]Taira no Masakado, hero of the Heian period. He claimed the title "Shinno" (New Emperor) and rebelled against the government. He was killed, but it is said he became a demigod.[n][uf 1 1][e]

[msg MSG_177_0_0]
[uf 0 5 65278][uf 2 1]A giant Hindu monster. Its mouth is so enormous, it can swallow the earth and the heavens in one bite. Its name means, "he who intoxicates."[n][uf 1 1][e]

[msg MSG_178_0_0]
[uf 0 5 65278][uf 2 1]A master sportsman who entertains the audience in exchange for his own life: one mistake can mean death. Some believe that matadors who die while performing remain in this world.[n][uf 1 1][e]

[msg MSG_179_0_0]
[uf 0 5 65278][uf 2 1]One of the four major archangels, he is at the top of the angelic hierarchy. He carries a long spear that can cut through anything, and his name means "one who is like God."[n][uf 1 1][e]

[msg MSG_180_0_0]
[uf 0 5 65278][uf 2 1]An indigenous god of the Shinano region from before the forces of Yamato occupied the land. Said to be born from the belief that divine spirits dwelled in rocks and stones.[n][uf 1 1][e]

[msg MSG_181_0_0]
[uf 0 5 65278][uf 2 1]An ancient Persian god of contracts, who was also revered as a sun god who brought harvests when he was introduced to the Zoroastrian religion.[n][uf 1 1][e]

[msg MSG_182_0_0]
[uf 0 5 65278][uf 2 1]A sun deity who was worshiped in the Roman Empire from the 1st to the 4th century AD. He was said to be reborn after death, and a festival was held on the winter solstice for him.[n][uf 1 1][e]

[msg MSG_183_0_0]
[uf 0 5 65278][uf 2 1]Appears before Judgment Day to save the virtuous. He is a universal figure, appearing in myths around the world. Many stories involve his death and rebirth.[n][uf 1 1][e]

[msg MSG_184_0_0]
[uf 0 5 65278][uf 2 1]The greatest angel in Judeo-Christian legend. He is known as the Voice of God or the Angel of Contracts. Despite his duty to maintain the world's order, he shows no mercy towards humanity.[n][uf 1 1][e]

[msg MSG_185_0_0]
[uf 0 5 65278][uf 2 1]An angel of Gnosticism, governing over peace and righteousness. Though said to be the savior of the angels, he used to be a human, the king of Salem.[n][uf 1 1][e]

[msg MSG_186_0_0]
[uf 0 5 65278][uf 2 1]Evil spirits of Murngin lore believed to be reborn shadows. They kidnap and eat children, and strike down any sorcerer who uses black magic.[n][uf 1 1][e]

[msg MSG_187_0_0]
[uf 0 5 65278][uf 2 1]A cryptid sighted between the 60s and 80s in West Virginia. It has shining red eyes and is named for the fin-like appendages on its sides. It uses its keen sense for blood to track down the source and feed on it.[n][uf 1 1][e]

[msg MSG_188_0_0]
[uf 0 5 65278][uf 2 1]The Canaanite god of death. Every year, Mot attempts to kill Baal, the god of fertility, only to see him raised from the dead with the help of his sister, Anat.[n][uf 1 1][e]

[msg MSG_189_0_0]
[uf 0 5 65278][uf 2 1]A female demon in Hindu lore. Though originally a Dravidian fertility goddess, the spread of Hinduism changed perception of her to a demonic figure. Usually depicted as a nude, voluptuous female.[n][uf 1 1][e]

[msg MSG_190_0_0]
[uf 0 5 65278][uf 2 1]A divine creature in Japanese lore. They are three-legged birds sent by Amaterasu to help humans. They are said to have helped Emperor Jinmu claim victory.[n][uf 1 1][e]

[msg MSG_191_0_0]
[uf 0 5 65278][uf 2 1]A giant snake with eight heads that Susano-o defeated to save Kushinada-Hime. The legendary sword Ame-no-Murakumo-no-Tsurugi, also known as the Sword of Kusanagi, emerged from its belly.[n][uf 1 1][e]

[msg MSG_192_0_0]
[uf 0 5 65278][uf 2 1]A legendary white horse with a single spiral horn. It can only be tamed by a pure maiden, and its horn supposedly has miraculous healing capabilities.[n][uf 1 1][e]

[msg MSG_193_0_0]
[uf 0 5 65278][uf 2 1]未使用（イベント用ペルソナにつき）[n][uf 1 1][e]

[msg MSG_194_0_0]
[uf 0 5 65278][uf 2 1]A snake with a rainbow body from Murngin lore. He is a fertility deity who controls the weather and resides in a holy pond filled with rainbow-colored water.[n][uf 1 1][e]

[msg MSG_195_0_0]
[uf 0 5 65278][uf 2 1]Demon of Hindu myth. He is an enemy of the gods, and attacks humans to feed on them. His hideous appearance strikes fear into those who see him. Can shift his shape to deceive his enemies.[n][uf 1 1][e]

[msg MSG_196_0_0]
[uf 0 5 65278][uf 2 1]The Hindu goddess of beauty and good fortune, Vishnu's wife, and Kama's mother. She is the goddess of love, believed to have been born from an ocean of milk.[n][uf 1 1][e]

[msg MSG_197_0_0]
[uf 0 5 65278][uf 2 1]The middle sister of the three Moirae Sisters of Greek legend. She is the apportioner, measuring the thread which determines each person's lifespan.[n][uf 1 1][e]

[msg MSG_198_0_0]
[uf 0 5 65278][uf 2 1]One of the four major archangels, his name means "healer." He recites the history of the fallen angels and the creation of Adam and Eve.[n][uf 1 1][e]

[msg MSG_199_0_0]
[uf 0 5 65278][uf 2 1]A serpentine woman of Greek myth, she was once the queen of Libya. Zeus's jealous wife, Hera, killed her children, causing her to go mad and transform into a monster.[n][uf 1 1][e]

[msg MSG_200_0_0]
[uf 0 5 65278][uf 2 1]A wicked witch of Balinese lore, she represents evil and is Barong's eternal rival. Even if defeated, she will come back to life, and their battle will have no end.[n][uf 1 1][e]

[msg MSG_201_0_0]
[uf 0 5 65278][uf 2 1]A beautiful fairy of Irish lore that yearns for the love of a human man. She drains the life of her lovers in return for granting them artistic inspiration.[n][uf 1 1][e]

[msg MSG_202_0_0]
[uf 0 5 65278][uf 2 1]Said to have been Adam's first wife, she desired to be his equal and refused to obey him. She was cast out of Eden and became a demon of the night. She is the mother of the demoness, Lilim.[n][uf 1 1][e]

[msg MSG_203_0_0]
[uf 0 5 65278][uf 2 1]A demon who tempts sleeping men and attacks infants. She is the daughter of the demoness Lilith. Like her mother, she drains men of their essence.[n][uf 1 1][e]

[msg MSG_204_0_0]
[uf 0 5 65278][uf 2 1]A fallen angel and the lord of demons in Judeo-Christian lore. His pride led him to revolt against God, taking a third of the heavenly host with him. He now waits for a second chance to challenge God.[n][uf 1 1][e]

[msg MSG_205_0_0]
[uf 0 5 65278][uf 2 1]A fallen angel in Judeo-Christian lore whose name means "morning star." Primarily known for defying God, but also worshiped as a bringer of light to mankind.[n][uf 1 1][e]

[msg MSG_206_0_0]
[uf 0 5 65278][uf 2 1]The spirit who said in ancient scripture, "For we are many." The name comes from the Roman military term for an army unit of 3,000 to 6,000 men.[n][uf 1 1][e]

[msg MSG_207_0_0]
[uf 0 5 65278][uf 2 1]A group of deities worshiped in voodoo. They control the forces of nature and influence human activities. Some also have powerful magic used to curse others.[n][uf 1 1][e]

[msg MSG_208_0_0]
[uf 0 5 65278][uf 2 1]A malignant god of Norse mythology. Impulsive and devious, but not always driven by malice. He had an uneasy peace with Odin and the gods, but his part in Baldur's death drove them to finally punish him.[n][uf 1 1][e]

[msg MSG_209_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_210_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_211_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_212_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_213_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_214_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_215_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_216_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_217_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_218_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_219_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_220_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_221_0_0]
[uf 0 5 65278][uf 2 1]未使用（ストレガ専用につき）[n][uf 1 1][e]

[msg MSG_222_0_0]
[uf 0 5 65278][uf 2 1]未使用（ストレガ専用につき）[n][uf 1 1][e]

[msg MSG_223_0_0]
[uf 0 5 65278][uf 2 1]未使用（ストレガ専用につき）[n][uf 1 1][e]

[msg MSG_224_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_225_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_226_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_227_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_228_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_229_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_230_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_231_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_232_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_233_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_234_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_235_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_236_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_237_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_238_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_239_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_240_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_241_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_242_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_243_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_244_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_245_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_246_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_247_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_248_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_249_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_250_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_251_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_252_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_253_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_254_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_255_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_256_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_257_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_258_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_259_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_260_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_261_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_262_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_263_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_264_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_265_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_266_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_267_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_268_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_269_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_270_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_271_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_272_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_273_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_274_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_275_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_276_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_277_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_278_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_279_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_280_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_281_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_282_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_283_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_284_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_285_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_286_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_287_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_288_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_289_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_290_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_291_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_292_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_293_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_294_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_295_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_296_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_297_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_298_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_299_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_300_0_0]
[uf 0 5 65278][uf 2 1]A Persona that granted power to a hero in another story. He is a being based off the main character of Maurice Leblanc's novels, Arsène Lupin. He appears everywhere and is a master of disguise.[n][uf 1 1][e]

[msg MSG_301_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He was a 17th-century privateer who eventually became a world-renowned pirate. At his execution, he declared he had a hidden treasure, leaving behind many legends.[n][uf 1 1][e]

[msg MSG_302_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He was a masked swordsman of justice who fought in California against corrupt officials during the era of Spanish rule. He always left his "Z" mark wherever he appeared.[n][uf 1 1][e]

[msg MSG_303_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. She is a thief from the novel by Mérimée, which became famous through the opera by Bizet. She is a femme fatale who is beautiful but very capricious.[n][uf 1 1][e]

[msg MSG_304_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. Ishikawa Goemon was a thief who stole from the rich and gave to the poor in Japan during the Azuchi-Momoyama period. The kabuki scene of him sitting on the gate of Nanzen-ji is famous.[n][uf 1 1][e]

[msg MSG_305_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. She is the mysterious female pope of the Middle Ages. She posed as a man and eventually made it all the way up to pope due to her unrivaled intellect.[n][uf 1 1][e]

[msg MSG_306_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. She is the beautiful woman that appears in Dumas's The Three Musketeers. Branded with a fleur-de-lis symbol, she used many aliases to control nobility and get her vengeance.[n][uf 1 1][e]

[msg MSG_307_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He is a noble thief that made waves in England during the Middle Ages. He is an expert archer and leader of the Merry Men, outlaws of justice who made Sherwood Forest their home.[n][uf 1 1][e]

[msg MSG_308_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. The French name of the titular heroine of Cinderella, a tale of great renown in which a mistreated waif gains luxury, beauty, and a single night's dance with a prince through the power of magic.[n][uf 1 1][e]

[msg MSG_309_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. An archangel who is said to be the form of Satan before he fell from Heaven. The second son of God, he rebelled against Him for freedom and bestowed free will and chaos upon humanity.[n][uf 1 1][e]

[msg MSG_310_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. This is a title Sun Wukong had given himself. After wreaking havoc, he was punished by Buddha, who imprisoned him under a mountain. Eventually, he was saved by a monk named Xuanzang.[n][uf 1 1][e]

[msg MSG_311_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He is the Roman god of travelers and thieves. He is seen as a symbol of the human unconscious and the mental world. He is equated with the philosopher's stone, the ultimate mystery in alchemy.[n][uf 1 1][e]

[msg MSG_312_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. She is a Greek goddess of crossroads, ghosts, and witchcraft, and is commonly attended to by dogs. She is also known to be the chief of the witches that appears in the play Macbeth.[n][uf 1 1][e]

[msg MSG_313_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He was a Japanese god found in the Izumo Fudoki, and was one of the three gods born from Izanagi. He was violent, but also had a sensitive side, showing love for his mother and reading poems.[n][uf 1 1][e]

[msg MSG_314_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. She is the daughter of Ugaritic's highest god, El. She is the goddess of fertility, as well as hunting and war.[n][uf 1 1][e]

[msg MSG_315_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. A Middle Eastern goddess of fertility. Many scriptures note her folklore, and there is even a mention of her as the "Queen of Heaven" in the Bible.[n][uf 1 1][e]

[msg MSG_316_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He is a malevolent god of Norse mythology. He can be capricious and is quite cunning. Despite being a blood brother to Odin, he was punished for the murder of Odin's child, Baldur.[n][uf 1 1][e]

[msg MSG_317_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. The true name of Freyja, of the Norse Vanir deities. Her name means "dis of the Vanir"—"dis" being a goddess. Known to be a great beauty and a witchlike master of magic.[n][uf 1 1][e]

[msg MSG_318_0_0]
[uf 0 5 65278][uf 2 1]A Persona that granted power to a hero in another story. He is one of the gods who existed before Japan was formed. He created the Oyashima from chaos, then birthed countless children and laid the foundation of soil and nature.[n][uf 1 1][e]

[msg MSG_319_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. He is Izanagi's rival and looks just like him. Magatsu means "calamity." Unlike Izanagi, who founded the land and brought order, he leads all back into chaos.[n][uf 1 1][e]

[msg MSG_320_0_0]
[uf 0 5 65278][uf 2 1]A Persona of another story. A divine being born from a glowing bamboo shoot. Though many proposed to her, none could complete her strict tasks. She eventually returned to her home, the moon.[n][uf 1 1][e]

[msg MSG_321_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_322_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_323_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_324_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_325_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_326_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_327_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_328_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_329_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_330_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_331_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_332_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_333_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_334_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_335_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_336_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_337_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_338_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_339_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_340_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_341_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_342_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_343_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_344_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_345_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_346_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_347_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_348_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_349_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_350_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_351_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_352_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_353_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_354_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_355_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_356_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_357_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_358_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_359_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_360_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_361_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_362_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_363_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_364_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_365_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_366_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_367_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_368_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_369_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_370_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_371_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_372_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_373_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_374_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_375_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_376_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_377_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_378_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_379_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_380_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_381_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_382_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_383_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_384_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_385_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_386_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_387_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_388_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_389_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_390_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_391_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_392_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_393_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_394_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_395_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_396_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_397_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_398_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_399_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_400_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_401_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_402_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_403_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_404_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_405_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_406_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_407_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_408_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_409_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_410_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_411_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_412_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_413_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_414_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_415_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_416_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_417_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_418_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_419_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_420_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_421_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_422_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_423_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_424_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_425_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_426_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_427_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_428_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_429_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_430_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_431_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_432_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_433_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_434_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_435_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_436_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_437_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_438_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_439_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_440_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_441_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_442_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_443_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_444_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_445_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_446_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_447_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_448_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_449_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_450_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_451_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_452_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_453_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_454_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_455_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_456_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_457_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_458_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_459_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_460_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_461_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_462_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_463_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

