[msg TheurgiaFlavorMSG_BLANK_]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_HERO]
[uf 0 5 65278][uf 2 1]After summoning a Persona, power within gradually enhances.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_YUKARI]
[uf 0 5 65278][uf 2 1]After healing someone, her desire to prevent death strengthens.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_JUNPEI]
[uf 0 5 65278][uf 2 1]After landing a critical hit, he becomes motivated by his own potential.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_SANADA]
[uf 0 5 65278][uf 2 1]After strengthening himself, his fighting spirit rises.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_MITURU]
[uf 0 5 65278][uf 2 1]After weakening enemies or inflicting an ailment, her will burns brighter.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_FUKA]
[uf 0 5 65278][uf 2 1]After analyzing an enemy, her yearning for her friends' trust grows.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_AEGIS]
[uf 0 5 65278][uf 2 1]After using physical skills, her drive to complete her mission intensifies.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_AMADA]
[uf 0 5 65278][uf 2 1]Once his SP is less than half, his competitiveness is incited.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_KOROMA]
[uf 0 5 65278][uf 2 1]After exploiting an enemy's weakness, his will to fight grows.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_ARAGAK]
[uf 0 5 65278][uf 2 1]Once his HP is less than half, his determination ignites.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_METIS]
[uf 0 5 65278][uf 2 1]After being Shifted to from Aigis, her drive to protect her sister rises.[n][uf 1 1][e]

[msg TheurgiaFlavorMSG_HEROAE]
[uf 0 5 65278][uf 2 1]After summoning a Persona, power within gradually enhances.[n][uf 1 1][e]

