[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]...And that's the summary of what happened on the night of the 7th.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]These Shadows seem to be quite a bit more formidable than the ordinary ones.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I see. So our enemies are growing stronger as well.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Well, it's not all bad news. In fact, I called today's meeting because—[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Hold on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]Before we go on, I'd like to ask Kirijo-senpai something.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 8 0 0]I know I'm not the only one thinking this. So much has been happening lately...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]I feel like I've just been getting dragged along without really understanding anything. But now, I want answers.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 10 0 0]So I'm gonna ask you straight out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 11 0 0]You've been hiding something from us, haven't you, Senpai?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 12 0 0]You're always acting like you don't know anything about the Dark Hour or Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 13 0 0]But they're connected to that [uf 0 1 33]accident ten years ago[uf 0 1 27], aren't they?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 14 0 0]What accident?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 1 65535 0 0][uf 3 1 1 0 0 15 0 0]Y-Yukari-chan...?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 16 0 0]There was an explosion near our school, and a lot of people died.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 17 0 0]It must've been big news back then. You know about it, don't you?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 18 0 0]...Yes.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 19 0 0]Luckily, no students were injured. But something is off here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 20 0 0]At the time of the incident, there were several unexplained absences.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 21 0 0]Seems like more than just a coincidence to me.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 22 0 0]What do you mean?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Well, I dug up some old school records, and found something interesting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 24 0 0]Those students weren't just absent. They all suddenly collapsed and had to be sent to the hospital![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 25 0 0]Sounds familiar, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 26 0 0]Remember those girls who bullied Fuuka? They had to be hospitalized too.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 0 0 0 27 0 0]......[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 28 0 0]I want an explanation![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 29 0 0]What really happened on the day of that accident?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 30 0 0]The Kirijo Group built our school, so you have to know something![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 1 65535 0 0][uf 3 1 1 0 0 31 0 0]Tell me the truth![n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 32 0 0]I wasn't trying to hide anything from you. It just never seemed relevant.[n][uf 1 1][e]

[msg MSG_016_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 1 0 0 33 0 0]But...[n][uf 1 1][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]It's okay. It's not your fault.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 35 0 0]All right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 36 0 0]I'll tell you everything.[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 37 0 0]Shadows have many mysterious abilities.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 38 0 0]Some research indicates they can even affect time and space.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 39 0 0]We think of them as our enemies, but what if we could somehow use them to our advantage?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 40 0 0]They could be a source of unimaginable power, couldn't they?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 0 0 0 41 0 0]What...?[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 42 0 0]Fourteen years ago, one man pursued that very line of thinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 43 0 0]He was the former leader of the Kirijo Group, Kouetsu Kirijo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 44 0 0]...My grandfather.[n][uf 1 1][e]

