[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]Huh? Junpei-kun?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]Oh, hey, Fuuka.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]What brings you here?[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Nothing, really.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]I've been coming here a bunch lately.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 6 0 0]Is that sketchbook, um...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]Hm? Ah, yeah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]This is where Chidori and I first met.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]What're you doing here, Fuuka?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh, I went home for a bit. I've been going back a lot recently.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh yeah?[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 12 0 0]You know, you've really changed, Fuuka.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 13 0 0]You're a totally different person from when you first showed up.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]I am?[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]Honestly, you were kind of a wimp before, but now... you're somethin' else. I can't even describe it.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 6 65535 0 0][uf 3 1 1 0 0 16 0 0]You've changed too, Junpei-kun.[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Yuka-tan said the exact same thing, but I just don't see it myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 3 3 25 25]I mean, just the other day, I was freakin' out and throwin' all that blame around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 3 0 25 25]I'm a real piece of work, aren't I?[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]That's not true.[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 21 0 0]Man, I was so damn scared. I just couldn't keep my shit together.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 22 0 0]...I know.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 23 0 0]I hate to admit it, but even now, I can't help bein' scared.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Yuka-tan said the exact same thing, but I just don't see it myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 3 3 25 25]I mean, just the other day, I got all scared and freaked out...[n][uf 1 1][e]

[msg MSG_018_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 26 0 0]I can be a real baby.[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 27 0 0]That's not true.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 28 0 0]But really, I was afraid. And I'm still afraid, to be honest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 3 0 25 25]But I've been thinking about it, and I don't wanna sit around doin' nothing.[n][uf 1 1][e]

[msg MSG_020_3_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]If I forget everything, that means I'd forget Chidori, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 3 3 25 25]I wouldn't even be alive right now if it wasn't for her.[n][uf 1 1][e]

[msg MSG_020_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 3 0 25 25]And I say to hell with that.[n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 33 0 0]You're only scared because you're choosing not to run away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 34 0 0]We all feel that way. It's nothing to be ashamed of.[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 35 0 0]Fuuka...[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 36 0 0]That's why I want to protect everyone...[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 37 0 0]After all, the Dark Hour is horrifying to think about, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 38 0 0]But our Personas awakened, and we're here now.[n][uf 1 1][e]

[msg MSG_024_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 39 0 0]The future hasn't been written in stone yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 40 0 0]And I want to be true to myself.[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 41 0 0]True to yourself... Huh...[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]You're really somethin', Fuuka.[n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 43 0 0]Let's fight together.[n][uf 1 1][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 6 65535 0 0][uf 3 1 1 0 0 44 0 0]Okay.[n][uf 1 1][e]

