[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 40 0 0][uf 3 1 1 0 0 1 0 0]Dad!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 40 0 0][uf 3 1 1 0 0 2 0 0]Dad![n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 2 40 0 0][uf 3 1 1 0 0 3 0 0]*sob*[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 2 40 0 0][uf 3 1 1 0 0 4 0 0]I know one thing for sure now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 64 2 40 0 0][uf 3 1 1 0 0 5 0 0]I was right to believe in you.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 40 0 0][uf 3 1 1 0 0 6 0 0]I'm... doing okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 40 0 0][uf 3 1 1 0 0 7 0 0]It took a while, but I finally got your message.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]The resolution in Yukari's heart has awakened a new Persona...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yukari's Persona, [uf 0 1 35]Io[uf 0 1 27], has given rise to [uf 0 1 35]Isis[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 40 0 0][uf 3 1 1 0 0 8 0 0]I'll fight for what I believe in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 40 0 0][uf 3 1 1 0 0 9 0 0]That's what you would've wanted. Right, Dad?[n][uf 1 1][e]

