[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I studied by myself in the library.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel smarter after working on some[n]difficult problems without giving up...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's getting dark out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should wrap up and return to the dorm.[n][uf 1 1][e]

