[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 1 0 0]The door's gone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 2 0 0]But the first door didn't disappear. It just opened up to a new place...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Never mind that. What we just saw was...[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 1 0 0 4 0 0]...That sure brings back memories.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]All I thought of back then was finding my mom's murderer, but in the end, I couldn't manage it on my own.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0]All I could do was ask myself why he had special powers... and if things would've turned out differently if I had them, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 52 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 10 25 25]Maybe that night... was the reason I started experiencing the Dark Hour.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Amada...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 9 0 0]My family must have fabricated the "accident" as a cover-up.[n][uf 1 1][e]

[msg MSG_005_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 10 0 0]...I'm sorry for that.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Hey, Metis! What was that all about!?[n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 1 0 0 12 0 0]What was what about...? Oh, I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 2 1 25 25]Apparently, we can only witness past events if not everyone was involved in the first place... That's new.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 52 65535 0 0][uf 3 1 1 0 0 14 0 0]That's not what I meant! Why did we see such a painful memory!?[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Huh? How would I know? It's your past.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 16 0 0]You better not be hiding anything.[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 17 0 0]How would I benefit from that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]This is just speculation, but I think the doors reflect the minds of those who pass through.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]That's why we were able to find a place to acquire supplies and return to the dorm directly.[n][uf 1 1][e]

[msg MSG_011_2_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Right now, you wish to erase the Abyss of Time as soon as possible and make it out alive, correct?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]If so, then although what's beyond these doors may seem irrelevant, there might be a reason we're seeing it.[n][uf 1 1][e]

[msg MSG_011_4_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Perhaps your time would be better spent thinking about that reason rather than accusing me.[n][uf 1 1][e]

[msg MSG_011_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 4 2 0][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 52 65535 0 0][uf 3 1 1 0 0 23 0 0]What did you say!?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 24 0 0]It's all right, really. What she's saying... is probably true.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Amada...[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]I've been doing a lot of thinking lately...[n][uf 1 1][e]

[msg MSG_015_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Back then, things weren't perfect, but everything seemed so much more... straightforward, when we were fighting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 28 0 0]That feeling we all shared just wasn't something you can get by going to school every day.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Sanada-san, recently you've dedicated yourself to boxing again, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Isn't that because... you don't want to forget that feeling?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 31 0 0]...Or maybe I'm just projecting.[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 0 0 0 32 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 1 0 0 33 0 0]...No, I think you're right.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Why don't we just drop the subject?[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 35 0 0]There's no point in dredging up the past...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 36 0 0]Don't you remember why we put everything on the line?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 37 0 0]If we stop moving forward, then this all would be a waste of time.[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 38 0 0]Yukari...[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 39 0 0]...C'mon, let's go.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]For what reason did we witness[n]a vision of our friend's past...?[n][uf 1 1][e]

