[msg MND_GOINTO_HOME_OK]
[uf 0 5 65278][uf 2 1]Maybe I should head inside...[n][uf 1 1][e]

[sel INTO_HOME_SEL top]
[uf 0 5 65278][uf 2 1]Go inside[e]
[uf 0 5 65278][uf 2 1]Stay out a little longer[e]

[msg MND_GOINTO_HOME_CMM_NO]
[uf 0 5 65278][uf 2 1]It's nice out today. Maybe I should spend[n]some more time walking around town...[n][uf 1 1][e]

[sel SEL_INTO_HOME_CMM top]
[uf 0 5 65278][uf 2 1]Keep exploring[e]
[uf 0 5 65278][uf 2 1]Go inside[e]

