[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 51 65535 0 0][uf 3 1 1 0 0 1 0 0]So it's the real deal from here on, huh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Looks easy to get lost in...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 3 0 0]Can you all hear me?[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Whoa! Is that you, Senpai?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 5 0 0]I'll be providing audio backup from here on out. Keep that in mind.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Wait... Are you sayin' you can see this place from all the way out there?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 7 0 0]It's my Persona's ability.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 8 0 0]The structure of Tartarus actually changes from day to day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 51 50 0 0][uf 3 1 1 0 0 9 0 0]I'd like to join you up there, but we need someone to provide outside support.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 10 0 0]That's even more concerning...[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 11 0 0]Now, based on your current location, you can expect to encounter enemies at any time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 12 0 0]They shouldn't be too tough, but proceed with caution.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 13 0 0]You'll get the hang of it as you go.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Right![n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 15 0 0]Got it.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 16 0 0]Why is she always like that...?[n][uf 1 1][e]

