[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]That's strange... I swear I left it around here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I don't see it anywhere...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Looking for something?[e]
[uf 0 5 65278][uf 2 1]Cleaning the store?[e]

[msg MSG_002_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 6 5 103]Oh! [uf 4 2]-chan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]How'd you know I was looking for something? Are you psychic?[n][uf 1 1][e]

[msg MSG_003_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I'm looking for my glasses— Er, not my glasses, my wallet! I can't seem to find it...[n][uf 1 1][e]

[msg MSG_004_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Nooo! Stay right there, don't go walking around![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]My contact lens...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Oh wait, that was what happened last year.[n][uf 1 1][e]

[msg MSG_005_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]It's not my contact lens I'm looking for, it's my wallet. My wallet! Now, where did I put it?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Best of luck.[e]
[uf 0 5 65278][uf 2 1]Can I help?[e]

[msg MSG_007_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 6 5 103]You don't have to be so polite, [uf 4 2]-chan. We're friends! We're all in this together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Reminds me of my days in the military academy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]All right, Sergeant [uf 4 2]! You take the right wing! Leave no stone unturned and find that wallet![n][uf 1 1][e]

[msg MSG_008_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 6 15 103]Wow! Honestly, I do wonder if you can read minds![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]I was just thinking how nice it would be if someone lent us a hand over here.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]The three of us searched high[n]and low for the missing wallet.[n][uf 1 1][e]

[msg MSG_010_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]We've searched everywhere, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]Wait... What were we looking for again?[n][uf 1 1][e]

[msg MSG_011_0_0 [Someone's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Bonjour![n][uf 1 1][e]

[msg MSG_012_0_0 [Mysterious Foreigner]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I found something important on the ground outside! Does this belong to you?[n][uf 1 1][e]

[msg MSG_013_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Oh, yes, that's it! I've been looking for this wallet everywhere![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]It may not be full of silver or gold, but this here is an even bigger treasure to me![n][uf 1 1][e]

[msg MSG_014_0_0 [Mysterious Foreigner]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Ah! Excuse me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Are you not the transfer student everyone is talking about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I am one as well! I am a student at Gekkoukan![n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Nice to meet you.[e]
[uf 0 5 65278][uf 2 1]...Who are you?[e]

[msg MSG_016_0_0 [Mysterious Foreigner]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I am here from France as an exchange student. My name is André Laurent Jean Geraux.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]But you can call me "Bebe"! It's quite nice to meet you![n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Nice to meet you.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_018_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I am delighted to, erm, make your acquaintance! Yoroshiku![n][uf 1 1][e]

[msg MSG_019_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I train in the [uf 0 1 2]home economics room[uf 0 1 27] every day. If you get bored, come join me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Well then, au revoir and sayonara![n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]My, my... What a classy young man.[n][uf 1 1][e]

[msg MSG_021_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Hmm... I know I kept it in my wallet... I didn't want to forget about it at any cost...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Ah, there it is! I knew I put it in here! Good going, me![n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 4 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Dear? That key... Is it...?[n][uf 1 1][e]

[msg MSG_023_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Come on, dear, you know what it is. It's the key to our son's car.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 1 25 25]Such a nice boy coming to visit us has a way of making me feel young again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Been a while since I felt like putting the pedal to the metal. What age do I look, dear?[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Please don't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Why must you get into a car...? Do you want me to end up all alone!?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]What's this about a car?[e]
[uf 0 5 65278][uf 2 1]All alone?[e]

[msg MSG_026_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Oh, um, [uf 4 2]-chan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I'm sorry for raising my voice. Did I scare you?[n][uf 1 1][e]

[msg MSG_027_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Our son... Remember what I told you? How he passed away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]On his way home from work, he got into an accident... He was hit by a dump truck driver who was drunk on the job...[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]I'm sorry to hear that.[e]
[uf 0 5 65278][uf 2 1]That's terrible luck.[e]

[msg MSG_029_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Oh... Please punch me, [uf 4 2]-chan... Just punch me for being so insensitive...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]With all my excitement, I forgot to consider how my wife might feel. I'm such a... Such a...[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Bunkichi-san shared the truth[n]about their son's death.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_031_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]...Hm? Why are we all just mopin' around here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Since my wallet's been located, why don't we go out and have a nice dinner, dear?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0][uf 4 23 0 1 1 25 25]And this is for you. Consider it your reward for helping us look around.[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]Bunkichi-san stuffed a bottle[n]of medicine into my pocket.[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]I parted with the elderly couple[n]and went back to the dorm.[n][uf 1 1][e]

