[msg MSG_000_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]Oh, it's you again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Is everything all right?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]How should I tell her about[n]Koromaru's true feelings?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can't talk about Personas[n]or the Dark Hour...[n][uf 1 1][e]

[msg MSG_002_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Would this happen to be about Koromaru?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, sort of.[e]
[uf 0 5 65278][uf 2 1]He had a reason...[e]

[msg MSG_004_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Hehe, don't worry about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]I know Koromaru has his own reasons and his own problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]He's such a sweet, smart boy, isn't he?[n][uf 1 1][e]

[msg MSG_005_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]Don't worry, I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1]Sometimes you don't even need words, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]He's such a sweet, smart boy, isn't he?[n][uf 1 1][e]

[msg MSG_006_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]So really, I'm all right. But thank you for being so thoughtful.[n][uf 1 1][e]

[msg MSG_007_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1]The way he's by your side...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1]He looks just like he did when he was with the priest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1]He must really trust you from the bottom of his heart.[n][uf 1 1][e]

[msg MSG_008_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1]Please, take good care of Koromaru.[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]We'll always be together.[e]
[uf 0 5 65278][uf 2 1]I'll look after him till the end.[e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Looks like Koromaru heard me...[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Ruff![n][uf 1 1][e]

[msg MSG_012_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1]Koromaru really has been blessed with so many wonderful friends.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 1]Be sure to cherish them, okay?[n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Woof![n][uf 1 1][e]

[msg MSG_014_0_0 [Gentle Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]You'll be at that dorm from now on, won't you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 1]Hehe, well I'll have to visit you again, then.[n][uf 1 1][e]

[msg MSG_015_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 0 0 0 21 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel a strong sense of trust[n]coming from Koromaru.[n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]*pant* Ruff! Ruff![n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]I took an overjoyed Koromaru[n]on a walk before going home.[n][uf 1 1][e]

[msg PFM_SPEEDUP_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]The Agility of Koromaru's Persona, [uf 0 1 1]Cerberus[uf 0 1 27], was raised by 3.[n][uf 1 1][e]

