[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 0 0]Your power has grown, it seems. Theurgy, was it...? An impressive feat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]On the topic of such power, I must ask—are you familiar with the Major Arcana?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I am.[e]
[uf 0 5 65278][uf 2 1]The what?[e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13207 0 0]To utilize metaphor, the Major Arcana are the parent plants which will help propagate your ever-growing garden of abilities.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]After defeating particularly strong Shadows, these Major Arcana will appear to you as cards.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It would be in your best interest to collect these cards as you find them.[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 0 0]That aside... It seems that when you change, Tartarus changes as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A number of strange doors have appeared within Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Where these doors lead, whether this bodes ill or well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Even I do not have that knowledge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]However, I believe you have the wherewithal to find out. Take the leap. You may discover something useful.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I can do that.[e]
[uf 0 5 65278][uf 2 1]I'd rather not...[e]
[uf 0 5 65278][uf 2 1]Why?[e]

[msg MSG_016_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Excellent. I have faith in you.[n][uf 1 1][e]

[msg MSG_017_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Come now, there's little room for modesty in matters such as these.[n][uf 1 1][e]

[msg MSG_003_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13228 0 0]Those who challenge the unknown, choosing risk over comfort, often achieve greatness.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I believe such challenges necessarily facilitate some form of growth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Your courage will lead to your betterment, [uf 4 2]. I sincerely hope you will continue to act on it.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Something weird's going on in Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]These doors... Should I go investigate?[n][uf 1 1][e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]I must congratulate you on your recent victory. Your power continues to grow, it seems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]On the topic of such power, I must ask—are you familiar with the Major Arcana?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I am.[e]
[uf 0 5 65278][uf 2 1]The what?[e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The Major Arcana...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]That'll be a useful resource going forward...[n][uf 1 1][e]

[msg MSG_006_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13217 0 0]While awaiting your arrival, I sensed something shifting within Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A number of strange doors have appeared there, it seems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Where these doors lead, whether this bodes ill or well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Even I do not have that knowledge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]However, I believe you have the wherewithal to find out. Take the leap. You may discover something useful.[n][uf 1 1][e]

