[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]All right... I don't think anyone will come up here for a while.[n][uf 1 1][e]

[msg MSG_000_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I leveraged my position on the student council to make it happen.[n][uf 1 1][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]This is, um, the first time I've ever used my authority for personal reasons...[n][uf 1 1][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Wait, that's not important right now.[n][uf 1 1][e]

[msg MSG_000_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 3 25 25]What am I doing...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]What I'm trying to say is, we need to talk.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Firstly, I have to apologize...[n][uf 1 1][e]

[msg MSG_001_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I'm sorry for what happened last time.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]What happened?[e]
[uf 0 5 65278][uf 2 1]Don't worry about it.[e]
[uf 0 5 65278][uf 2 1]It made me happy.[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 9 0 0]You know... The other day, in front of the station...[n][uf 1 1][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 4 5 5]Oh, I see. You're pretending it was nothing to spare me the embarrassment.[n][uf 1 1][e]

[msg MSG_003_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 3 25 25]I don't know what's wrong with me...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 12 0 0]That's... kind of you. Thank you.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]The things my ex-fiancé said to you were inexcusable, but more importantly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 3 25 25]I wanted to apologize for my own behavior.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 0 0 0 15 0 0][uf 5 13 4 15 5]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Oh, so it did...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]When that happened, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I said all manner of things about you. And then I just... ran off.[n][uf 1 1][e]

[msg MSG_007_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]That was unbelievably insensitive of me. I'm sorry.[n][uf 1 1][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I had been planning on telling you my feelings...[n][uf 1 1][e]

[msg MSG_007_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I just didn't think I'd end up shouting them in public like that.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Talk about bold.[e]
[uf 0 5 65278][uf 2 1]Your feelings?[e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 22 0 0]Hey, don't tease me like that! I didn't think I had it in me either...[n][uf 1 1][e]

[msg MSG_009_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Ever since I started spending time with you, my life has been full of new experiences.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I've felt shock, joy, even outrage... But every time, I've always been thinking of you.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 25 0 0]Wha!? Well, I mean, um...[n][uf 1 1][e]

[msg MSG_010_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Ever since I started spending time with you, my life has been full of new experiences.[n][uf 1 1][e]

[msg MSG_010_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I've felt shock, joy, even outrage... But every time, I've always been thinking of you.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 0 0 0 28 0 0]......[n][uf 1 1][e]

[msg MSG_011_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]Now that it's come to this, I'm obligated to tell you exactly how I feel.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 30 0 0]Here goes. I...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 31 0 0]I... love you.[n][uf 1 1][e]

[msg MSG_013_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 0 0 0 32 0 0][uf 4 23 0 1 3 25 25]......[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru's voice is trembling. I'd better[n]choose my words carefully...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Come to think of it, [uf 0 1 2]I have a special[uf 0 1 27][n][uf 0 1 2]relationship with another person already[uf 0 1 27]...[n][uf 1 1][e]

[msg MSG_015_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 33 0 0]...I feel like I'm going to die of embarrassment.[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]I love you too.[uf 2 9 1 1 349][e]
[uf 0 5 65278][uf 2 1]I'm sorry, but...[e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 0 0 0 34 0 0]...![n][uf 1 1][e]

[msg MSG_017_1_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 35 0 0]Y-You... love me too...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 0 0 0 36 0 0][uf 4 23 0 1 3 25 25]......[n][uf 1 1][e]

[msg MSG_017_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 37 0 0]I... I'm so happy to hear that. Or should I say... I'm thankful?[n][uf 1 1][e]

[msg MSG_017_4_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 1 3 25 25]Ngh, my heart... At this rate, it's going to end up like last time...[n][uf 1 1][e]

[msg MSG_017_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 39 0 0]It really is wonderful, though... To know that the feeling is mutual.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Heh, I'm glad I managed to open my heart. As of today, you're more than just a friend to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 1 1 25 25]That said, given my situation, I can't go public about this just yet.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]I can sense Mitsuru's deep affection for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Things seem to be getting serious...[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]There's no going back now...[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 42 0 0]Say, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 43 0 0]I've been thinking about this for a while now, but the way you address me...[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]"Mitsuru"?[e]
[uf 0 5 65278][uf 2 1]What about it?[e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 44 0 0]Er— That's exactly what I mean![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 1 3 25 25]You're on a first-name basis with me, while I've been sticking to formalities... It's a bit unbalanced.[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 46 0 0]Er— Don't act like you don't know![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 1 0 25 25]You're on a first-name basis with me, while I've been sticking to formalities... It's a bit unbalanced.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 48 0 0]All right, I've decided.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 49 0 0]From now on, when it's just the two of us, I'll call you by your first name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 50 0 0]It's going to be a bit awkward for me, but trust that this is what I want.[n][uf 1 1][e]

[msg MSG_025_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]In any case, today marks a change. I'm not going to let myself be constrained by my family heritage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]It's because of who I am as an individual that I ended up meeting you...[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 53 0 0]Er— Look at all these things you're making me say. You'd better take responsibility for this![n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Ah... [uf 4 2]... Well, this is a start...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 55 0 0]Don't let go just yet...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]We spent some more time together,[n]and then returned to the dorm...[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 1 1 25 25]That's unfortunate, but I'm glad I cleared the air.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]You told me it was up to me how to handle these emotions. Thanks to that, I was able to be honest with myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]If I had kept my feelings locked up, I never would have been able to move forward...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 60 0 0][uf 4 23 0 1 1 25 25]It is imperative to be true to our hearts... Just as you were with your answer.[n][uf 1 1][e]

[msg MSG_030_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]Thank you, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]If I hadn't harbored these emotions, I would have continued lying to myself, justifying it all under the Kirijo name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]And if that had happened... there's no doubt I would have failed on my path in the future.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]From now on, I'm not going to let myself be constrained by my family heritage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]It's because of who I am as an individual that I ended up meeting you.[n][uf 1 1][e]

[msg MND_031_2_0]
[uf 0 5 65278][uf 2 1]I can sense Mitsuru's deep trust.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_031_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]Now then... I certainly have a lot to thank you for, but there's one more matter I'd like to bring up.[n][uf 1 1][e]

[msg MSG_032_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]I haven't eaten since this morning, so I'm terribly famished. I'd say you bear some responsibility for this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]I could do with some takoyaki on our way back. Your treat?[n][uf 1 1][e]

[msg MSG_032_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]I'd hardly complain if you were to do at least that much to mend a broken heart...[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]We stopped by the strip mall[n]and then returned to the dorm...[n][uf 1 1][e]

