[msg MSG_000_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0][uf 3 1 3 0 65535 14823 0 0]What brings you to the nurse's office? Eeeheehee...[n][uf 1 1][e]

[msg MSG_000_1_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]...What? You want some potent medicine?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]I can't just give you potent medication whenever you want. Haven't you heard of the Pharmaceutical Affairs Law?[n][uf 1 1][e]

[msg MSG_000_3_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14822 0 0]Hm? It's an emergency? And you absolutely, without a doubt need my medicine?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]Oookay, but if you're lying to me, I'll curse your kneecaps so they'll crack every waking moment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]Well... here you are.[n][uf 1 1][e]

[msg MSG_000_5_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14815 0 0]This is a special medicine I brewed myself, but I don't know if I would call it potent.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14803 0 0]You got what you wanted, so off you go now.[n][uf 1 1][e]

