[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Fuuka-san installed the new parts...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5004 0 0]I adjusted your mobility unit and power output to improve overall stability. Now you should have a wider range of movement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]That'll make transitioning from running to attacking smoother, which should be more energy efficient.[n][uf 1 1][e]

[msg SYS_011_0_0]
[uf 0 5 65278][uf 2 1]You can now perform [uf 0 1 2]Ambush[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]So... What do you think?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]I quite like it.[e]
[uf 0 5 65278][uf 2 1]It's incredible![e]
[uf 0 5 65278][uf 2 1]I'm eager to test it out.[e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5131 0 0]I'm glad you like it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Just let me know if you find any more parts. Then I can install them for you![n][uf 1 1][e]

