[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hello, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I gathered you all here because I wanted to let you know how my research has been going.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]It concerns the Shadows that have been appearing during full moons.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Now, I want you to listen closely. It might be hard to follow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 22 0 222 25 25 20]Shadows can be divided into twelve categories, according to their characteristics.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]This, we've known for a while. We can think of it like their class or order.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 22 0 222 33 25 20]I've classified the special Shadows we've seen so far and, well, it's simply fascinating![n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 8 0 0]Wh-Why're you so excited about it...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 9 0 0]So...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ah, right.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Those four Shadows belonged to Categories I through IV, in order of their appearance![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]They may have looked different than the more common ones, but the classification scheme still applies.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]And that's something we should be excited about?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, I get it. There are twelve in all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 15 0 0]And eight we haven't seen yet.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]That's exactly right, Yamagishi-kun! You're quite sharp.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 17 0 0]Oh, uh, okay. But, what are they after?[n][uf 1 1][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]That's a good question, and that's what we haven't figured out yet: their motive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]They don't kill their prey; they feed on their minds.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Now, it could be considered predation, but is it really? Is there actually an underlying intent behind their behavior?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 22 0 222 34 25 37]The purpose of the Shadows as a whole... That's what we need to consider.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 22 0 0]This is interesting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 23 0 0]But no matter what their intent, we still have to beat the rest of 'em.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 24 0 0]I agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 25 0 0]That's about all we can do at this point.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 26 0 0]Eight more, huh? Lucky us.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 27 0 0]According to the data, each one has been stronger than the last. That means we better start training harder.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 28 0 0]We'll manage. We've got plenty of time.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 29 0 0]But why does Tartarus even exist in the first place...?[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 1 65535 0 0][uf 3 1 0 0 0 30 0 0]......[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 0 0 0 31 0 0]......[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]The puzzle pieces are falling[n]into place, one by one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Those large Shadows that only[n]appear on the full moon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder what their purpose is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eight more remain...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We have a long road ahead of us.[n][uf 1 1][e]

