[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Say, how do you feel about a pink alligator?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds fine to me.[e]
[uf 0 5 65278][uf 2 1]I dunno...[e]
[uf 0 5 65278][uf 2 1]Uh, what?[e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 20 15 117]I thought so too. I knew you'd understand.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]There are many times when people don't agree in life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...Though I suppose there are many things that could be disagreed upon.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, sorry... I was just thinking about something.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]See, it's the main character of a story that I'm writing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]He was born in a lush green forest, but he turned out to be pink.[n][uf 1 1][e]

[msg MSG_005_3_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]He stands out so much that he can't hunt for food easily, so he's always hungry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]The other animals dislike him, and call him disgusting... almost like he's cursed.[n][uf 1 1][e]

[msg MSG_005_7_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]So, he was used to living alone... But one day, he made a friend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]It was a little bird that had trouble flying...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Every day, the bird would stand on the pink alligator's back and practice.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]...It's kind of embarrassing to tell you this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 117 0 25 25]So, what do you think?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]It sounds interesting.[e]
[uf 0 5 65278][uf 2 1]It needs work...[e]
[uf 0 5 65278][uf 2 1]I'd need to hear more.[e]

[msg MSG_008_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 5 13 20 15 117]Really?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I've never written a story before, so I'm worried it's not going to be very good.[n][uf 1 1][e]

[msg MSG_008_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]But what matters is that I'm writing it for myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Perhaps I can show you the entire novel someday...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...Well, this is my first time writing a story like this, so it's not going to be perfect.[n][uf 1 1][e]

[msg MSG_009_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]But, I'm writing it for myself, so that's what matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Hopefully, you can learn something from the story once it's finished...[n][uf 1 1][e]

[msg MSG_010_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 20 5 117]Well, it's still a work in progress...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]...I've never tried writing a story before, so maybe I'm not good at it.[n][uf 1 1][e]

[msg MSG_010_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]But, I'm writing it for myself, so that's what matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I hope you can take something positive away from it, though...[n][uf 1 1][e]

[msg MSG_011_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I actually came up with it the other day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]I decided I wanted to write a heartwarming story just for myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]I'd like it to be a hopeful tale... about finding the meaning in one's life.[n][uf 1 1][e]

[msg MSG_011_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]I think of you when I write... It's like I can hear you telling me not to die just yet.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Kamiki smiled weakly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_013_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]...The wind is going to pick up soon. I can feel these kinds of things now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I hope I have enough time...[n][uf 1 1][e]

[msg MSG_014_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]We should leave. I'd like to see you again sometime.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

