[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]It's a strong enemy! Please watch your health![n][uf 1 1][e]

[msg MSG_000_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]We can't let our guard down against this enemy! I'll do everything I can to support you![n][uf 1 1][e]

[msg MSG_000_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]Enemy incoming! Be cautious of what they do![n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]We have no data on this opponent...! Don't let your guard down![n][uf 1 1][e]

[msg MSG_MONAD_BTL_YUKARI_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]No matter what shows up, I'll do this![n][uf 1 1][e]

[msg MSG_MONAD_BTL_YUKARI_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]All right, come and get me![n][uf 1 1][e]

[msg MSG_MONAD_BTL_JUNPEI_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Alright! Make sure you watch me in action![n][uf 1 1][e]

[msg MSG_MONAD_BTL_JUNPEI_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Well then... time to do this![n][uf 1 1][e]

[msg MSG_MONAD_BTL_SANADA_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]Looks like this'll be interesting. Let's go![n][uf 1 1][e]

[msg MSG_MONAD_BTL_SANADA_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]I can't afford to lose. Now, come get me![n][uf 1 1][e]

[msg MSG_MONAD_BTL_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]There will always be an opening to strike. Let's take it down![n][uf 1 1][e]

[msg MSG_MONAD_BTL_MITSURU_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]Get ready! Incoming![n][uf 1 1][e]

[msg MSG_MONAD_BTL_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Unused[n][uf 1 1][e]

[msg MSG_MONAD_BTL_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Unused[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]The enemy is within range. Commencing battle.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]A powerful reading, as expected...! I'm going all out![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]It looks strong... We can do this![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AMADA_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]All right, I'll take you on![n][uf 1 1][e]

[msg MSG_MONAD_BTL_KOROMARU_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grr... Arf![n][uf 1 1][e]

[msg MSG_MONAD_BTL_KOROMARU_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrrrr...[n][uf 1 1][e]

[msg MSG_MONAD_BTL_ARAGAKI_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Well... time to do this. Hope you're ready.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_ARAGAKI_1 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Talk about a pain... Don't let your guard down.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6117 0 0]This seems like a tough target. Be careful, everyone![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6118 0 0]Let's work together on this. I'll give this my all as well![n][uf 1 1][e]

