[msg SYS_DIFFICULTY_CHECK_AST]
[uf 0 5 65278][uf 2 1]Begin the game at [uf 0 1 2][uf 2 4 0][uf 0 1 27] difficulty?[n][uf 1 4 1][uf 1 1][e]

[msg SYS_DIFFICULTY_INFO_SAFE]
[uf 0 5 65278][uf 2 1]Your party auto-revives after defeat. [uf 0 1 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Heartless).[uf 0 1 27][n][uf 1 1][e]

[msg SYS_DIFFICULTY_INFO_EASY]
[uf 0 5 65278][uf 2 1]Low-stress combat. [uf 0 1 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Heartless).[uf 0 1 27][n][uf 1 1][e]

[msg SYS_DIFFICULTY_INFO_NORM]
[uf 0 5 65278][uf 2 1]Moderately challenging combat. [uf 0 1 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Heartless).[uf 0 1 27][n][uf 1 1][e]

[msg SYS_DIFFICULTY_INFO_HARD]
[uf 0 5 65278][uf 2 1]Significantly challenging combat. [uf 0 1 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Heartless).[uf 0 1 27][n][uf 1 1][e]

[msg SYS_DIFFICULTY_INFO_HEAR]
[uf 0 5 65278][uf 2 1]Exceedingly challenging combat. [uf 0 1 43]Your choice of difficulty will not affect the story and can be changed at any time, but you cannot return to Heartless once leaving it.[n][uf 1 1][e]

[msg SYS_INHERITANCE_LOAD_CHE]
[uf 0 5 65278][uf 2 1]Carry over this data?[n][uf 1 5 0][uf 1 4 1][uf 1 1][e]

[msg SYS_SAVE_VERSION_ERROR]
[uf 0 5 65278][uf 2 1]Unable to resume play. The loaded save data and game version do not match.[n][uf 1 1][e]

[msg SYS_SAVE_EPISODE_ERROR]
[uf 0 5 65278][uf 2 1]Unable to resume play. The loaded save data does not match the selected story episode.[n][uf 1 1][e]

[msg SYS_VELVETROOM_INFO_INHE]
[uf 0 5 65278][uf 2 1]When summoning from the Compendium, you now have the option to use the one carried over from the main story.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Press [uf 1 3 118] to switch between the two Compendiums.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Summoning from the carried-over Compendium will cost more than usual. You must also be at the same level or higher than the desired Persona.[n][uf 1 1][e]

[msg MSG_FLORIST_CHECK [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Does this look right?[n][uf 1 1][e]

[sel SEL_FLORIST_CHECK top]
[uf 0 5 65278][uf 2 1]Yes.[e]
[uf 0 5 65278][uf 2 1]Maybe not.[e]

[msg SYS_CONF_DIFF_CHECK_ASTR]
[uf 0 5 65278][uf 2 1]If you reduce the difficulty from the highest level, you won't be able to change it back. Are you sure you want to proceed?[n][uf 1 5 0][uf 1 4 1][uf 1 1][e]

