[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11267 0 0]I've seen them before on commercials, but they looked even better in person![n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]That was the first time I ever ate a beef bowl! I didn't expect it to taste that good![n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]My parents were always strict about table manners and what kind of food I could eat...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11254 0 0]I doubt I'd ever see something like a beef bowl on the dinner table at home...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I guess this was your last one.[e]
[uf 0 5 65278][uf 2 1]Let's eat here again, then.[e]
[uf 0 5 65278][uf 2 1]Maybe you should ask them.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0][uf 3 1 3 0 65535 11275 0 0]O-Oh no, you're right! I might never be able to eat a beef bowl ever again![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 4 23 0 108 3 25 25]If I'd known that, I'd have savored it more slowly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 4 23 0 108 2 25 25]Wait a second... I can just come here again if I want another beef bowl! Don't scare me like that.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems a little annoyed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11223 0 0][uf 5 13 11 30 108]Yeah! Let's come here again! Please be sure to let me know the next time you want to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 4 23 0 108 0 25 25]It... might be a bit difficult for me to come to a place like this on my own... So let me know![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11221 0 0][uf 5 13 11 15 108]Hm... Maybe I could ask the housekeeper... We'd have to keep it a secret, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]And I don't know about going through all that trouble just for a beef bowl... you know?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems to be deep in thought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I've never really stopped at the strip mall here before, but it has a lot of interesting shops.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11293 0 0]Maybe I'll start thinking about the next one I'd like to visit.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]We walked around the strip mall for a while,[n]and then I decided to return to the dorm.[n][uf 1 1][e]

