[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6012 0 0]I apologize for making you wait. Is this store the location of our business today?[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]According to my data, the services here are capable of making one "face" their "inner self."[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6051 0 0]Is there truly a distinction to be made between one's inner and outer selves? I will investigate.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Thank you for waiting. Hm, this shop has quite a mysterious feel to it...[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]I have heard that undergoing a treatment here will help you face your inner self.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6022 0 0]I wonder what exactly that means... I am curious to try it out.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Thank you for waiting. I see that we will be continuing our research on this facility today.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]I will put forth greater effort to remain operational this time. Let us commence.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Sorry for making you wait. Oh, were you planning to utilize this store's service again?[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]In that case, I'd like to try it again, too. I hope I will be able to stay awake this time...[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6016 0 0]I seem to have unintentionally spent the duration of the treatment in sleep mode.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]However, it appears that the results are identical to having undergone maintenance.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6142 0 0]I shall return to the dorm at full throttle to confirm these results. Please excuse me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6060 0 0]It seems that I fell asleep during the treatment...[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0]But, for some reason, I feel very refreshed. How mysterious...[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6020 0 0]Hm... Maybe I should run diagnostics back at the dorm... I will leave immediately, then. So long.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6016 0 0]It appears that undergoing this treatment caused me to enter sleep mode again.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0]Furthermore, the resulting effects resemble post-maintenance performance again as well.[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6044 0 0]The reason behind these phenomena remains unclear... Regardless, I appreciate you inviting me.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6060 0 0]Oh, it seems I fell asleep this time too...[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0]But I woke up feeling as refreshed as last time as well.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 3 0 65535 6020 0 0]Thank you for inviting me again, [uf 4 2]-san.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6012 0 0]I apologize for making you wait. Is this store the location of our business today?[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]According to my data, the services here are capable of making one "face" their "inner self."[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6051 0 0]Is there truly a distinction to be made between one's inner and outer selves? I will investigate.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Thank you for waiting. Hm, this shop has quite a mysterious feel to it...[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]I have heard that undergoing a treatment here will help you face your inner self.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6022 0 0]I wonder what exactly that means... I am curious to try it out.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Thank you for waiting. I see that we will be continuing our research on this facility today.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]I will put forth greater effort to remain operational this time. Let us commence.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Sorry for making you wait. Oh, were you planning to utilize this store's service again?[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]In that case, I'd like to try it again, too. I hope I will be able to stay awake this time...[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6016 0 0]I seem to have unintentionally spent the duration of the treatment in sleep mode.[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]However, it appears that the results are identical to having undergone maintenance.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6142 0 0]I shall return to the dorm at full throttle to confirm these results. Please excuse me.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6060 0 0]It seems that I fell asleep during the treatment...[n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0]But, for some reason, I feel very refreshed. How mysterious...[n][uf 1 1][e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6020 0 0]Hm... Maybe I should run diagnostics back at the dorm... I will leave immediately, then. So long.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6016 0 0]It appears that undergoing this treatment caused me to enter sleep mode again.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0]Furthermore, the resulting effects resemble post-maintenance performance again as well.[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6044 0 0]The reason behind these phenomena remains unclear... Regardless, I appreciate you inviting me.[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6060 0 0]Oh, it seems I fell asleep this time too...[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0]But I woke up feeling as refreshed as last time as well.[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 3 0 65535 6020 0 0]Thank you for inviting me again, [uf 4 2]-san.[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

