[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]The TV has been left on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It's showing the news right now...[n][uf 1 1][e]

[msg MSG_001_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Coming up next...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]A special report on the Amazing Commodities Corporation, producer of Tanaka's Amazing Commodities.[n][uf 1 1][e]

[msg MSG_001_5_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]President Tanaka has made an undisclosed private expenditure that caused quite a stir in the media.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]With us is our reporter live on scene. Take it away.[n][uf 1 1][e]

[msg MSG_002_0_0 [Field Reporter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]I'm reporting from the Amazing Commodities head office, where a swarm of journalists has convened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Word has it that President Tanaka will be coming out shortly to make a statement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]The tension in the air is thick.[n][uf 1 1][e]

[msg MSG_003_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Thank you. We'll be looking forward to updates as things unfold. Back to the studio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]The unaccounted-for expenditure has sparked a massive investigation. Some theorize he is guilty of tax evasion...[n][uf 1 1][e]

[msg MSG_004_0_0 [Commentator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]Oh, no question! This is President Tanaka we're talking about![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]All he cares about is lining his own pockets. And he does it by swindling his own viewers![n][uf 1 1][e]

[msg MSG_004_5_0 [Commentator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]He could become the richest man on the planet and still never be satisfied![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Why doesn't he donate some of that money for a change!? Damn scrooge...[n][uf 1 1][e]

[msg MSG_005_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]W-Well, I'm sure he's not as bad as all that... Oh, this just in—something's happened at the scene.[n][uf 1 1][e]

[msg MSG_006_0_0 [Field Reporter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]President Tanaka has emerged![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Wha— He's carrying a microphone! It... It looks like he's about to sing![n][uf 1 1][e]

[msg MSG_007_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Ready to go, in your TV, Tanaka's Commodities![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Everybody's ultimate friend in greed![n][uf 1 1][e]

[msg MSG_008_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Hiii, everyone! Amazing Commodities is here for you year-round, rain or shine![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]We have a monopoly on the cheapest, highest quality goods! Our customers shout for joy so loud it's considered noise pollution![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Our stocks rise so high they're a hazard to birds, and we make losers every day out of people who don't buy![n][uf 1 1][e]

[msg MSG_008_5_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]We're the only miracle left in this sad, desolate world! That's the Amazing Commodities guarantee![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]We look forward to your business![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]President Tanaka's car drove off...[n][uf 1 1][e]

[msg MSG_010_0_0 [Field Reporter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]Oh... H-He's gone![n][uf 1 1][e]

[msg MSG_011_0_0 [Commentator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]What the hell are you doing!? You call yourself a reporter!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]If you can't get one lousy comment out of him, you're just givin' him free advertising![n][uf 1 1][e]

[msg MSG_012_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]We'll have to interrupt you there, as we've just received a fax.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]It... It's from President Tanaka! The message reads...[n][uf 1 1][e]

[msg MSG_013_0_0 [Fax from President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]"Hiii! This is Tanaka, the best friend your pocketbook ever had!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]"And what's in my pocketbook is my own business."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]"It's not my company's money, so what's it to them how I use it?"[n][uf 1 1][e]

[msg MSG_013_5_0 [Fax from President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0]"But let me make one thing clear: I am not ashamed of a single thing!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]"My conscience is clear, dear viewers—so buy my products, guilt-free!"[n][uf 1 1][e]

[msg MSG_013_7_0 [Fax from President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0]"Amazing Commodities, here for you year-round, rain or shine! Buy now or you'll miss your chance. You'll see!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]"Buh-bye!"[n][uf 1 1][e]

[msg MSG_014_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]...Apparently, he had no intention of revealing his use for the funds.[n][uf 1 1][e]

[msg MSG_015_0_0 [Commentator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Does he have no shame!? This Tanaka guy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]Just because he's made some money for himself doesn't mean that we're his little playthings![n][uf 1 1][e]

[msg MSG_015_5_0 [Commentator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]On behalf of the people, I have something to say and I am not afraid to say it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0]Fat pigs like him who gorge themselves on the excesses of capitalism should be—[n][uf 1 1][e]

[msg MSG_016_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0]Yes, thank you very much. This concludes our special report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0]With no clues as to the utilization of said funds, we can only hope that they went to humanitarian purposes.[n][uf 1 1][e]

[msg MSG_016_5_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0]Next up, your daily glimpse into the stock market.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0]...This just in, we have reports that Amazing Commodities' stocks have suddenly skyrocketed.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]The report continues...[n][uf 1 1][e]

