[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, sorry. No one was here, so I figured it'd be okay.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]It's rare to see you here... Is it for the archery team?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Yes. The teacher wanted a report...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]I see... That's a lot of responsibility.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, not really. It's nothing compared to what you have to do...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Actually, uh, I wanted to ask you something.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 7 0 0]Hm?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Senpai... What are you fighting for?[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Well, I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]I guess you could say... it's my way of atoning for the past.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]In my case... I don't think I really have a reason anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 12 0 0]I mean, I know the whole story about my father now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 13 0 0]I guess I could still fix the mistakes he left behind though...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]Maybe I should have thought about this earlier, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]But it took me this long to start questioning myself.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]That's understandable.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]It seems like everyone has their own reason for fighting...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]Well, defeating the Shadows is probably a good enough reason, huh?[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]What are you trying to say?[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 21 0 0]...I'm not exactly sure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 22 0 0]But it's all gonna be over after the next full moon, so there's not much point in thinking about it.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 23 0 0]...That's true.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 2 65535 0 0][uf 3 1 1 0 0 24 0 0]Once we put an end to this, we can go back to a normal high school life.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]The rest of the student council will be here soon. We can pick this up later though, if you want...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 26 0 0]Oh, no, that's okay. Thanks for listening.[n][uf 1 1][e]

