[msg MND_000_0_0 [(Unused)]]
[uf 0 5 65278][uf 2 1](Unused)[n][uf 1 1][e]

[msg MSG_001_0_0 [Man Wearing a Helm]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 1 0 5 18 303 0]Now, listen closely. A true man should always carry the fiery soul of a samurai within them![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 1 0 5 19 303 0]Our school curriculum nurtures the samurai spirit within our students so that they contribute to society...![n][uf 1 1][e]

[msg MSG_002_0_0 [Foreign Exchange Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 5 20 14 0]Oh là là! How wonderful! I wish to set my soul on fire and learn the ways of the great samurai also![n][uf 1 1][e]

[msg MSG_003_0_0 [Man Wearing a Helm]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 1 0 5 21 303 0]That's what I like to hear, my boy! Though you hail from a foreign land, the samurai spirit burns within you all the same![n][uf 1 1][e]

[msg MND_004_0_0 [(Unused)]]
[uf 0 5 65278][uf 2 1](Unused)[n][uf 1 1][e]

[msg MND_005_0_0 [(Unused)]]
[uf 0 5 65278][uf 2 1](Unused)[n][uf 1 1][e]

[msg MSG_006_0_0 [Man Wearing a Helm]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 1 0 5 22 303 0]Yes... And in that very moment, Lord Masamune's eye was, without a doubt, brimming with tears.[n][uf 1 1][e]

[msg MSG_007_0_0 [Foreign Exchange Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 5 23 14 0]A fascinating story! It brings eyes to my tears![n][uf 1 1][e]

[msg MSG_008_0_0 [Man Wearing a Helm]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 1 0 5 24 303 0]Yes, yes, yes! It does indeed![n][uf 1 1][e]

[msg MND_009_0_0 [(Unused)]]
[uf 0 5 65278][uf 2 1](Unused)[n][uf 1 1][e]

