[msg MSG_000_0_0 [Faculty Member]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15021 0 0][uf 5 21 1 200]Hmph. Kids these days don't know how to show respect for their elders.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 5 21 1 200]We're their teachers. We've lived longer than them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 5 21 1 200]But Moriyama and her friends had to pull that on me at the very beginning of the term...[n][uf 1 1][e]

[msg MSG_001_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22505 0 0][uf 5 21 1 100]...I'm sorry to interrupt, but I need to get back to managing the shop.[n][uf 1 1][e]

[msg MSG_002_0_0 [Faculty Member]]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 3 1 3 0 65535 15019 0 0][uf 5 21 1 200]Even YOU'RE shooing me away? Some way to start the school year...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1082 0 65535 65535 0 0][uf 5 21 1 200]I don't think my nerves can take this.[n][uf 1 1][e]

[msg MSG_003_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22507 0 0][uf 5 21 1 100]All right, all right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]You want me to order more of those cream-filled breads you like so much, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]You could have just asked...[n][uf 1 1][e]

