[msg MSG_000_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 10]Hey, [uf 4 1]. Do you have a minute?[n][uf 1 1][e]

[msg MSG_001_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 10]It's about the track team. Since you just transferred, you probably haven't heard about the Myouou Cup, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 10]Well, lemme tell ya. On August 2nd, there's a major competition for track and field.[n][uf 1 1][e]

[msg MSG_002_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 10]There's this guy named Hayase—total speed demon. We can't let him trounce us this year![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 10]I've got high hopes for you, so get ready to train hard![n][uf 1 1][e]

[msg MSG_003_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 10]I'm gonna need you to show up from July 27th to August 1st. Don't go skippin' school now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 10]I've got a special training regimen in mind for you. Hayase won't stand a chance![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 10]The competition's on August 2nd! Let's do this thing![n][uf 1 1][e]

