[msg MSG_706_100 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 6 65535 65535 0 0][uf 3 1 1 0 2 1 0 10]So this is one of those huge Shadows, huh. Well, not like it changes what we usually do...[n][uf 1 1][e]

[msg MSG_706_110 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 2 2 0 8]I'll help, too...[n][uf 1 1][e]

[msg MSG_706_000 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]This large Shadow's Arcana is the Hermit. Watch out for attacks that use electricity![n][uf 1 1][e]

[msg MSG_706_200 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 3 0 6]The enemy Shadow is charging a lot of electricity inside its body![n][uf 1 1][e]

[msg MSG_706_210 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 4 0 6]It might be up to something. I'll analyze it on my end as well![n][uf 1 1][e]

[msg MSG_706_300 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 5 0 6]I've got it. The enemy gets stronger by absorbing electrical power.[n][uf 1 1][e]

[msg MSG_706_310 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 6 0 6]But, it seems the enemy's defense drops temporarily while it's charging up...[n][uf 1 1][e]

[msg MSG_706_320 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 7 0 6]To stop the enemy from powering up, you'll need to attack while it's charging![n][uf 1 1][e]

[msg MSG_706_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]The enemy Shadow is charging up now![n][uf 1 1][e]

[msg MSG_706_002 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]We've stopped the enemy from powering up![n][uf 1 1][e]

[msg MSG_706_400 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 8 0 6]The enemy is stronger than before! Everyone, be careful![n][uf 1 1][e]

[msg MSG_706_500 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 9 0 6]This is different from how it's been charging up till now...[n][uf 1 1][e]

[msg MSG_706_510 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 10 0 6]Is it sucking electricity from the entire city...!? If it absorbs all that power, we'll be in trouble![n][uf 1 1][e]

[msg MSG_706_520 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 11 0 6]If we attack it now, we can stop it from powering up![n][uf 1 1][e]

[msg MSG_706_600 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 12 0 6]I sense an enormous amount of energy from the enemy![n][uf 1 1][e]

[msg MSG_706_610 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 13 0 6]It's powered up significantly. Everyone, hang in there![n][uf 1 1][e]

