[msg MSG_000_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]So, where's my drink?[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]I told him that I've ordered his drink...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]That must have impressed the monk. He[n]seems to have taken an interest in me...[n][uf 1 1][e]

[msg MSG_001_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]You look awfully young, kid. You still in high school?[n][uf 1 1][e]

[msg MSG_001_3_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]What're the employees here thinkin', letting someone like you in...?[n][uf 1 1][e]

[msg MSG_001_5_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Well, since ya got me a drink, I'll pretend I'm your guardian so ya don't get thrown outta here. Take a seat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 114 2 25 25]...Well? C'mon, kid, sit down. Havin' to look up at ya is strainin' my neck.[n][uf 1 1][e]

[msg MSG_002_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]So, you wanted to see where adults spend their time, eh? Not that I can't relate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 114 0 25 25]Well, don't worry, in two or three more years you'll be old enough to hang out here unsupervised.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Just take it easy, kid. You'll be legal before ya know it. No need to rush.[n][uf 1 1][e]

[msg MSG_002_5_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Tryin' to act like an adult just makes ya look more like a kid, y'know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Heh... I guess that sounds funny comin' out of an alcohol-drinkin', cigar-smokin' monk, eh?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Is alcohol good?[e]
[uf 0 5 65278][uf 2 1]What's a cigar taste like?[e]

[msg MSG_004_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Some people like it... So I guess it is? Probably. I have no idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I just drink to get drunk. When you get drunk, it makes you feel good.[n][uf 1 1][e]

[msg MSG_005_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]What does it taste like...? Like leaves. I can't think of any other way to describe it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]It ain't supposed to taste good. I just smoke 'cause it helps me think straight.[n][uf 1 1][e]

[msg MSG_006_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Young people always think the grass is greener on the other side...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Well, don't get your hopes up too high, kid. That way you won't be disappointed when things don't work out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]'Cause there might come a time when you'll hafta drink when you don't want to, and smoke just to get through the day...[n][uf 1 1][e]

[msg MSG_006_3_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]You're nothin' like those punks I see runnin' around town these days. Can't say the same for my son, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...Always bein' taken in by the police for questioning... It's disgraceful.[n][uf 1 1][e]

[msg MSG_006_7_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...I'm gonna remember your face, kid. Next time you come in here, I'm gonna have you thrown out. Got it?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]...I became acquainted with a strange monk.[n][uf 1 1][e]

[msg MSG_008_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Well, when you've had your fill, hit the road... And don't come back.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

