[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Just from looking at a single jab, you can tell how different everything is at the top level.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]And not only are both fighters strong, they each have their own unique fighting style.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Well, what kind of fighter is your favorite?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]A boxer with a strong punch.[e]
[uf 0 5 65278][uf 2 1]A fighter with slick footwork.[e]
[uf 0 5 65278][uf 2 1]Someone with a big mouth.[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]Yeah, it's exciting to see when someone's at a disadvantage, but they can instantly turn the tables with a single, crippling blow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]You don't see it much in amateur matches because they wear headgear, but KO's are one of the most thrilling parts of boxing.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]I get that. The essence of boxing is to land hits without getting hit yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]I tend to rely on footwork in my matches too, but someday I'm hoping to master the style of in-fighting.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Haha, yeah. Some of the great champions are great performers, too. They really know how to put on a good show.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]A lot of people go to watch these matches, so knowing how to keep them engaged is part of the job.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]So if you're just looking to get strong, professional boxing might not be the path to take.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Now that I'm watching these again, I can see there's a lot to learn from professional matches.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]Plus, when I do it here, I have someone to discuss things with.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]Let's do this again next time you're free.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 2 1 1 0] has improved[n]from watching the intense boxing matches...[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Man...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 1 25 25]Watching those guys fighting is making it hard for me to sit still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]You wanna head to my room and whale on the punching bag for a bit?[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]In this fight, each side had one win and one loss. A serious all-or-nothin' match.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]And the fact that they were lifelong rivals only helped them push each other to the top.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]Do you have anyone you'd consider a rival?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]Nope.[e]
[uf 0 5 65278][uf 2 1]You're my rival.[e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 1 25 25]Well, good. Make sure you don't lose to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 1 25 25]They must be pretty good if they're on your radar. Kinda makes me wanna see how I'd fare against them.[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 1 25 25]Haha, yeah. I can't imagine there are too many people out there who can match you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]If you ever do find someone though, I'd be curious to see how I'd fare against them.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 1 25 25]Heh, interesting. I think facing off against you would make for a good match.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]But I have no intention of losing. Maybe we should try sparring sometime.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]Anyways, you'd have to be really lucky to find a partner like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 1 25 25]All the athletes from the other schools avoid me, so it's tough finding an opponent to spar with.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]And I don't think a longtime childhood friend is quite the same thing as a rival...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 1 25 25]But hey, the world is a big place. I'll just keep polishing my skills until I find the right person.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 1 25 25]Haha, sorry. We were supposed to be relaxing, but I just ended up talking the whole time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 1 25 25]Let's do this again. I'll put on some real good matches then.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 2 1 1 0] has improved[n]from watching these two rivals clash...[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 4 25 25]Ah, I didn't notice the time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 1 25 25]Before you go to sleep... you wanna crack a raw egg for some protein first?[n][uf 1 1][e]

