[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey, sorry to bother you, Fuuka...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]It's okay. What's on your mind?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, uh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 4 0 0]I was hoping you could do me a favor. With your skill, I mean.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 5 0 0]I was doing some research on our school, and I came across something strange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]Ten years ago, a lot of students stopped coming to school for some reason.[n][uf 1 1][e]

[msg MSG_003_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 7 0 0]They were reported as absent at the time, but I found some records that suggest otherwise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 8 0 0]Do you know anything about it, Fuuka?[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Me? Um, not really.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 10 0 0]I know it was a long time ago, but... doesn't it seem suspicious to you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 11 0 0]From what I've heard, this isn't the first time Shadows have appeared.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 12 0 0]Wait, are you saying...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]I don't know. But I do wonder.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 2 3 25 25][uf 4 23 0 1 3 25 25]And I'm not trying to make trouble or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 1 65535 0 0][uf 3 1 1 0 0 15 0 0]But Kirijo-senpai acts kinda weird whenever someone brings up Tartarus.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 16 0 0]Does she?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 17 0 0]I just wanna know what happened back then. And if it doesn't have anything to do with the Shadows, then fine.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 18 0 0]I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 19 0 0]Okay, I'll see what I can do.[n][uf 1 1][e]

