[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 81 0 0][uf 3 1 1 0 1 20551 0 0]Look, that treasure chest looks different from the one before.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20552 0 0]Yes, that particular box is sealed in a special way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20553 0 0]The box can be unlocked by its own mechanism, but it needs something else to work during the Dark Hour...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]The [uf 0 1 39]Twilight Fragment[uf 0 1 27] I found in my[n]room seems to be reacting...[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 81 0 0][uf 3 1 1 0 1 20554 0 0]What's that ya got there...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20555 0 0]Interesting, you had one on you... Good, then try using it.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 1 20556 0 0]It's what I handed to you. Try using it.[n][uf 1 1][e]

