[msg MSG_DUNGE_FUKA_START [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]I'm detecting a major presence upstairs! It has to be our target![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's hiding in [uf 0 1 2]a larger room on the third floor[uf 0 1 27]. Head that way and track it down![n][uf 1 1][e]

[msg MSG_DUNGE_SHOWER_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]I'm sorry... I only sensed the one Shadow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]And I hate to bear more bad news on top of this, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]A barrier has gone up within the building... You won't be able to reach it this way.[n][uf 1 1][e]

[msg MSG_DUNGE_SHOWER_FUKA2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1089 0 0]So we can blame that Shadow for getting us trapped down here...[n][uf 1 1][e]

[msg MSG_DUNGE_SHOWER_FUKA3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm going to try and find a way to break this barrier. In the meantime, please reconvene on the second floor.[n][uf 1 1][e]

[msg MSG_DUNGE_204BREAK_HANSE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Is everyone all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It seems that breaking the wrong mirror will cause the Shadow to target you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Try breaking the [uf 0 1 2]mirror in Room 205[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm certain that will trigger something. Please head there right away![n][uf 1 1][e]

[msg MSG_DUNGE_HANSEI1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Is everyone all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It seems that breaking the wrong mirror will cause the Shadow to target you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Try breaking a mirror that [uf 0 1 2]doesn't show your reflection[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_DUNGE_HANSEI2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Are you all okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It looks like that wasn't the right mirror. This Shadow is determined...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It may be hard to tell in the darkness, but remember: you're looking for a [uf 0 1 2]mirror that doesn't show your reflection[uf 0 1 27]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Keep searching. I'll do what I can to hone in on its location![n][uf 1 1][e]

[msg MSG_DUNGE_HANSEI3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]Is everyone okay? I hope you can forgive me for not being of much help...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But I've finally got a lock on the reading! You have to break [uf 0 1 2]the mirror in Room 304[uf 0 1 27]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 0 1 2]Room 304[uf 0 1 27] isn't far. Please hurry and find it![n][uf 1 1][e]

