[msg MSG_000_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20304 0 0]Then what does the girl standing by the table in the back want?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Apple martini[e]
[uf 0 5 65278][uf 2 1]Bloody Mary[uf 2 9 1 1 647][e]
[uf 0 5 65278][uf 2 1]Oolong tea[e]
[uf 0 5 65278][uf 2 1]Margarita[e]
[uf 0 5 65278][uf 2 1]Go ask their order again[e]

[msg MSG_002_5_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 0 0 0]Hmm... I see.[n][uf 1 1][e]

[msg MSG_002_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20303 0 0]What did that girl by the entrance order?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Dark beer[e]
[uf 0 5 65278][uf 2 1]Bloody Mary[e]
[uf 0 5 65278][uf 2 1]Screwdriver[e]
[uf 0 5 65278][uf 2 1]Margarita[uf 2 9 1 1 647][e]
[uf 0 5 65278][uf 2 1]Go ask their order again[e]

[msg MSG_004_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20304 0 0]And the girl in the middle of the floor?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Apple martini[e]
[uf 0 5 65278][uf 2 1]Screwdriver[uf 2 9 1 1 647][e]
[uf 0 5 65278][uf 2 1]Margarita[e]
[uf 0 5 65278][uf 2 1]Oolong tea[e]
[uf 0 5 65278][uf 2 1]Go ask their order again[e]

[msg MSG_006_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20301 0 0]Let's see, who else...? Oh, what about that guy over there? What does he want?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Ginger ale[e]
[uf 0 5 65278][uf 2 1]Screwdriver[e]
[uf 0 5 65278][uf 2 1]Margarita[e]
[uf 0 5 65278][uf 2 1]Oolong tea[uf 2 9 1 1 647][e]
[uf 0 5 65278][uf 2 1]Go ask their order again[e]

[msg MSG_008_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20304 0 0]All right, I'll start on the drinks.[n][uf 1 1][e]

[msg MSG_009_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20302 0 0]Hey, you got everyone's order right. Thanks for your help.[n][uf 1 1][e]

[msg MSG_010_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20303 0 0]Hey, ya screwed up the order![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Come on, I'm tryin' to run a business here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I know you're still a kid, but pay attention, will ya?[n][uf 1 1][e]

