[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]Today, they're showing the "Eternal Love" series... It appears to be a set of classic romances.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 2 0 0]Now that I think about it, I may never have seen such a straightforward love story before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 5 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 5 1 25 25]Well, this should be something of an experience. Let's make the most of it.[n][uf 1 1][e]

[msg MSG_900_0_0 [Prince from Another Country]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]There's something I need to tell you... I'm sorry I couldn't say this sooner, but I'm actually a prince from another country.[n][uf 1 1][e]

[msg MSG_901_0_0 [Prince from Another Country]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Forgive me for not being more honest with you. But believe me when I say that my love could not be more real![n][uf 1 1][e]

[msg MSG_902_0_0 [Village Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]But... I love you, too! Wherever you go, I'll be right by your side![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]It seems love takes many forms...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I've learned the difference[n]between love and infatuation...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 7 0 0]...Is that really the standard for "eternal love"?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 8 0 0]In the final scene, how did the man so conveniently determine where the woman was?[n][uf 1 1][e]

[msg MSG_002_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 5 65535 0 0][uf 3 1 1 0 0 9 0 0]And why would he wait until the last moment to announce that he's secretly a prince?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 5 5 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 5 5 25 25]Why couldn't he tell her sooner? That's simply lackluster storytelling![n][uf 1 1][e]

[msg MSG_002_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 11 0 0]And not only that, but the film ended just as the two began to settle down. Nothing to show of what comes after.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 5 3 25 25]If the writers knew how royalty actually lived, they wouldn't have called that a happy ending.[n][uf 1 1][e]

[msg MSG_002_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 13 0 0]In fact, that's when the most difficult part begins.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 5 65535 0 0][uf 3 1 1 0 0 15 0 0]Er— My apologies. I didn't intend to be overly critical...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 3 25 25]I just... couldn't help but compare it to my own life.[n][uf 1 1][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 5 65535 0 0][uf 3 1 1 0 0 17 0 0]In a way, I suppose that means I must have enjoyed it quite a bit.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru and I returned to the dorm.[n][uf 1 1][e]

