[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 1 0 0]...You're late... What kept ya, huh?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Mutatsu stinks of alcohol[n]more than he usually does...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He must have been drinking a lot.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 2 0 0]Don't you think it's... *hic* rude to make sum'one wait?[n][uf 1 1][e]

[msg MSG_002_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 114 2 25 25]Didn't Dad tell you not to do that, huh?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Dad?[e]
[uf 0 5 65278][uf 2 1]It's my first time hearing it.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 4 0 0][uf 5 13 17 15 114]"Dad"? Did you jush call me "Dad"?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 5 0 0]You alwaysh call me an ol' bastard, but you're only nice whenever ya need sum money...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 6 0 0][uf 5 13 17 5 114]...Huh? *hic* It'sh the first time I'm telling you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 7 0 0]Oh... Thas right, I guess it is...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 8 0 0]...Tch, Ignorin' me? Well, *hic* I guessh I can't ecshpect much from a kid of your generation.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 9 0 0]I thought you got in an' dropped dead somewhere or somethin'...[n][uf 1 1][e]

[msg MSG_008_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 10 0 0]Don't make me worry like that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 11 0 0]Where the hell were ya wanderin' around? Iss late![n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I was with a friend.[e]
[uf 0 5 65278][uf 2 1]I was studying.[e]
[uf 0 5 65278][uf 2 1]None of your business.[e]

[msg MSG_010_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 1 0 0 12 0 0][uf 5 13 17 5 114]A friend, huh? A girl? It's a girl, ain't it? Even though you're still sponging off your parents...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 114 0 25 25]Hmph, well, like father, like son, I guess...[n][uf 1 1][e]

[msg MSG_011_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 1 0 0 14 0 0]Studyin'!? What, you wanna go to college so you can work at some big company?[n][uf 1 1][e]

[msg MSG_011_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 114 0 25 25]Don't bother... Even if you busht your ass... Don'tcha remember what you and your mom did to me...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 16 0 0][uf 5 13 17 5 114]W-Well, thas true... *hic* It's none of my business...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 1 0 0 17 0 0]But watch your mouth! Who the hell do you think raished you, huh!?[n][uf 1 1][e]

[msg MSG_014_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 1 0][uf 3 1 1 0 0 18 0 0]Uh... Hmm...? YOU...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Wh-What the...? All this time, I thought you were... I guess my eyesight is getting bad after all...[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]It seems Mutatsu was worried about me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...Spending all my time with clients... Missing anniversaries and birthdays...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 114 0 25 25]I wonder if they felt the same way I did, when I was waiting for you earlier...[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Who's "they"?[e]
[uf 0 5 65278][uf 2 1]What're you talking about?[e]

[msg MSG_019_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]My wife and son... We were all together back when I was still a businessman.[n][uf 1 1][e]

[msg MSG_019_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]It's already been four years now... since they left me...[n][uf 1 1][e]

[msg MSG_020_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Before I became a monk... I was a plain ol' businessman. The three of us were just a typical family.[n][uf 1 1][e]

[msg MSG_020_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]But, they both left me... My wife and my son... It's been four years now.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I used to stay out past midnight all the time, and my wife and I would always fight about it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]...Now when I go home, I don't know what to do with myself, so I just come here and drink every night.[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]Do you miss your family?[e]
[uf 0 5 65278][uf 2 1]Are you running away?[e]

[msg MSG_023_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]O-Of course not! They're the ones that abandoned me y'know!?[n][uf 1 1][e]

[msg MSG_024_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Besides... after all this time... I don't know how to face them...[n][uf 1 1][e]

[msg MSG_025_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 5 13 17 5 114]Yeah... You're absolutely right. I shaved my head, but that was just for show...[n][uf 1 1][e]

[msg MSG_026_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I get drunk to avoid facing my problems... So, yeah, I guess you could say I'm runnin' away.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]...She hasn't contacted me since then. They must've gotten over me already.[n][uf 1 1][e]

[msg MSG_027_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 114 3 25 25]I have no idea where they are... Or if they'd even wanna see me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 114 0 25 25]It's too much of a hassle.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Alright, kid, enough of the depressing talk. Let's get outta here. I wanna go home and take a shower.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]I left the club with Mutatsu.[n][uf 1 1][e]

