[msg TOWNMAP_DETAIL_TEXT_0]
[uf 0 5 65278][uf 2 1]A private institute funded by the Kirijo Group that includes elementary, middle, and high school. Established in 1982, with the building rebuilt since.[n][uf 1 1][e]

[msg TOWNMAP_DETAIL_TEXT_1]
[uf 0 5 65278][uf 2 1]Formerly a hotel, renovated as a dormitory for Gekkoukan High students. Unlike other school dorms, it is inhabited by both boys and girls.[n][uf 1 1][e]

[msg TOWNMAP_DETAIL_TEXT_2]
[uf 0 5 65278][uf 2 1]A large mall located in the vast shopping area in the northern part of Port Island.[n][uf 1 1][e]

[msg TOWNMAP_DETAIL_TEXT_3]
[uf 0 5 65278][uf 2 1]The last stop of the passenger train Anehazuru. One of the two entryways to Port Island.[n][uf 1 1][e]

[msg TOWNMAP_DETAIL_TEXT_4]
[uf 0 5 65278][uf 2 1]A strip mall built at Iwatodai Station, the connecting station of the local train line and the monorail.[n][uf 1 1][e]

[msg TOWNMAP_DETAIL_TEXT_5]
[uf 0 5 65278][uf 2 1]A historic shrine located in Iwatodai.[n][uf 1 1][e]

