[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I spent time with Maiko on the playground.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]My tummy's grumbling! Can we go to Wilduck?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's go.[e]
[uf 0 5 65278][uf 2 1]Let's keep playing.[e]

[msg MSG_003_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 13 15 110]Yaaay! You're the best! I wonder what the daily burger is today...[n][uf 1 1][e]

[msg MSG_004_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]But I'm too hungry to play! Let's go eat![n][uf 1 1][e]

