[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...Maybe this is what they call divine guidance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]The detective called me this morning and said he found my wife and son.[n][uf 1 1][e]

[msg MSG_000_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]He said they're runnin' a small restaurant. It sounds like it's pretty popular among the locals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]My son's married, and his wife is pregnant... Sure makes me feel old...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I ain't comin' back 'til I earn their forgiveness. So... I'll be outta town for a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I decided the next time I saw your face would be the day I leave. So, I'll be goin' tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I'll get down on my knees if I hafta. If my son wants to sock me in the face, well, that's fine too.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I-I've been thinkin' about proposing to my wife again... even though I'm not so good with words...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 114 1 25 25]I'm gonna say, "I wanna recite the sutras with you by my side, for the rest of my life." ...Well? How's that sound?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]That's awesome.[e]
[uf 0 5 65278][uf 2 1]It's missing something.[e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 17 15 114]Aw, c'mon, kid, you're... you're embarrassin' me.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 5 13 17 15 114]You don't know nothin'! She's gonna burst into tears when she hears that! No copyin' it, alright?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Might not mean much comin' from a monk who couldn't relinquish thoughts of the family he lost...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]But I was finally able to face the fact that I was drinkin' to hide my true feelings. It was... an enlightenment of sorts.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Hmph, it's all your fault, kid. After lecturin' you all those nights...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]You started remindin' me of my son.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Maybe Buddha sent you to help me... I gotta admit, I believe in fate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 114 0 25 25]Had I not met you, I don't think I'd ever see my family again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I owe ya, kid...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Mutatsu thanked me from[n]the bottom of his heart...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we really[n]understand each other now...[n][uf 1 1][e]

[msg SYS_010_0_0]
[uf 0 5 65278][uf 2 1]The Tower Social Link reached its maximum level! You can now fuse [uf 0 1 35]Chi You[uf 0 1 27], the warrior king![n][uf 1 1][e]

[msg MSG_011_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Here, take this... Think of it as a goodbye gift.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]DEV: *Unused message label. *If this appears, it is a bug.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]When you mix Cointreau with white rum and lemon juice, and shake it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]You get a cocktail called "XYZ."[n][uf 1 1][e]

[msg MSG_013_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Movies and manga often use the initials "XYZ" to symbolize the end of something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 114 1 25 25]But, I consider XYZ to be the best of the best... It tastes sooo good goin' down.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I'll be prayin' that your future will be XYZ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]...So long, kid.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I held the reserve tag tightly[n]and returned to the dorm.[n][uf 1 1][e]

