[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Aigis, um...[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]So, you're here.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Yukari-chan...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]You thought about what I said, didn't you? I can see it in your face.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 6 0 0]I did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 7 0 0]I understand what you meant now.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]There are four lit flames... Then the victors of this battle will be awarded the true key.[n][uf 1 1][e]

[msg MSG_006_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]So, Aigis... Have you decided which choice you would make?[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 10 0 0]I can't go back to the past yet. So I won't give up this key.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]I see... Then it appears we are in opposition.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 12 0 0]Yes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 13 0 0]I won't give up on what's important to me. It may be painful... But I will stand by my choice.[n][uf 1 1][e]

[msg MSG_009_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 54 65535 0 0][uf 3 1 1 0 0 14 0 0]I understand now thanks to her.[n][uf 1 1][e]

[msg MSG_010_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Sister...[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 16 0 0]You know... All of this may've actually been for the best.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 17 0 0]You've been acting so empty and mechanical lately, like when we first met.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 18 0 0]I actually thought you were just gonna hand over your key 'cause you didn't want to fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 19 0 0]But what you just said... It's like you're alive again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Which means we'll both be giving it our all, right?[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 21 0 0]Yes. And I'm ready to prove it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 54 65535 0 0][uf 3 1 1 0 0 22 0 0]I feel just as strongly about him as everyone else.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 23 0 0]All right, then... Guess we're done talking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 8 25 25]And I'm not giving up on what's important to me either![n][uf 1 1][e]

