[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono seems to have stepped out...[n][uf 1 1][e]

[msg MSG_001_0_0 [Ms. Ounishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0][uf 3 1 3 0 65535 16014 0 0]The main ingredients are... d-glucose, erythritol, saccharin sodium...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]These are all sweeteners...[n][uf 1 1][e]

[msg MSG_002_0_0 [Ms. Ounishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]Oh, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0][uf 3 1 3 0 65535 16021 0 0]Take a look at this.[n][uf 1 1][e]

[msg MND_003_0_0 [Ms. Ounishi]]

[msg MSG_004_0_0 [Ms. Ounishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]I ordered a bag of sand through the mail the other day, and it came with this supplement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]It says here that this will "boost your brain power." I don't know how they could make such an outlandish claim with these ingredients.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]See for yourself. The active ingredients in this are all sweeteners.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]At the very end, it lists an omega-3 fatty acid called DHA, but that means there's only trace amounts of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]I know it was free, but what a joke. Maybe I'm in the wrong line of work...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ms. Ounishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0][uf 3 1 3 0 65535 16022 0 0]Go ahead and take it if you want it, though the best it'll do is be a placebo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]The food they serve at Wakatsu has better benefits than that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]It's made with loads of fish eyes, a prime source of DHA![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]It's not my thing, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1582 0 65535 65535 0 0]Speaking of DHA, did you know the full term is docosahexaenoic acid? You see, it's...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I learned about DHA...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono doesn't seem to be returning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to give up for today.[n][uf 1 1][e]

