[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 11 10 108]Sorry to make you wait. Shall we?[n][uf 1 1][e]

[msg MSG_900_0_0 [Barista]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]All right, the coffee's brewed. And the beans are Kilimanjaro, of course.[n][uf 1 1][e]

[msg MSG_901_0_0 [Mountaineer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Mmm, that aroma is unbelievable. To think we trekked almost six kilometers for this one cup of coffee.[n][uf 1 1][e]

[msg MSG_902_0_0 [Barista]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]It truly is a magnificent sight, my friend. This view, being here with you... I'll cherish this memory for as long as I live.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]So much beautiful scenery in the movie...[n]I feel like I've sharpened my aesthetic sense.[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Wow, that was a spectacle for the ages! I'm so glad we came![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 108 0 25 25][uf 4 22 0 108 33 25 20]Well, we should probably head back.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Hiraga[n]and went back to the dorm.[n][uf 1 1][e]

