[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]You were all alone, trying to combat the Kirijo Group's deceptions, for so long...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]I was just...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Hm... It would've been nice if the scene from your past could have included your father.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]I would've liked to meet him.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 5 0 0]It doesn't matter. No point dwelling on the past.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 6 0 0]I'm tired of dealing with Shadows. Let's just hurry and get this over with.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 25 5]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Yukari... Remember not to push yourself too hard.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 25 2]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 10 0 0]You know how... Aigis has the same power as him?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 11 0 0]That has to mean that she... got something from him. Even if she doesn't know it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 12 0 0]I guess... I want some kind of proof that I'm making progress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 13 0 0]I made a promise to him...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Yukari...[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Now that I've seen my own, I know for sure that we were right...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]About how all the memories we've been seeing have something in common.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]So you mean... The night after what we just saw...[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Amada-kun's memory, Sanada-senpai's, Junpei and Koromaru's...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Mitsuru-senpai's was the most obvious.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Uh, I don't think I'm following...[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]What we've been seeing are the moments that gave us our reasons for awakening to our Personas.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 22 0 0]It fits. The majority of us were there for Fuuka's awakening, and Aigis and Metis could always use theirs...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0]That would explain why we haven't been shown their memories—there was no need.[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 24 0 0]But if that's what it is... then why those memories specifically?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Is it saying there's a lesson we need to learn from our reasons or something?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 26 0 0]Aigis-san, what do you think?[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 27 0 0]Hm... Well...[n][uf 1 1][e]

[msg MSG_015_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 25 11]......[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Yo, li'l sis![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Don't act like this doesn't involve you. C'mon, let us know what you think too.[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 31 0 0]Why? It's not like I can talk about the past with you all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 32 0 0]I don't know anything about it...[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 33 0 0]What's wrong?[n][uf 1 1][e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Nothing. It's true, that's all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 35 0 0]I just... I asked you to not leave me behind, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 36 0 0]Unlike all of you, I don't know anything about your pasts, so... It's like I'm the only one who doesn't belong...[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 37 0 0]Oh, you're feelin' left out, huh? You really are just a kid inside.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 38 0 0]Makes sense now why you got all well-behaved when we said we'd leave you behind before.[n][uf 1 1][e]

[msg MSG_021_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 11 2 1][e]

[msg MSG_022_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 39 0 0]I'm not "just a kid."[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 40 0 0]You may not know anything about us, but it's true the other way too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 41 0 0]You must have memories that we know nothing about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 42 0 0]Like the memory of when you discovered your emotions.[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 43 0 0]Isn't it about time you let us in on some of those memories?[n][uf 1 1][e]

[msg MSG_025_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 44 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 1 0 0 45 0 0]But... But I don't...[n][uf 1 1][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 46 0 0]Oh. It closed.[n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 47 0 0]Sheesh...[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 48 0 0]Metis, you may be misunderstanding. It's not as though our pasts have been purely enjoyable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 49 0 0]In fact, there are likely more painful memories than pleasant ones.[n][uf 1 1][e]

[msg MSG_029_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 31 52 65535 0 0][uf 3 1 1 0 0 50 0 0]That's clearly not true.[n][uf 1 1][e]

[msg MSG_030_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 31 52 65535 0 0][uf 3 1 1 0 0 51 0 0]All the things you talk and laugh about are from your past.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 52 0 0]......[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 53 0 0]She certainly doesn't mince words... And[n]this time, that trait forced a realization.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 54 0 0]It occurred to me for the first time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 55 0 0]That the reason time stopped may[n]have something to do with us...[n][uf 1 1][e]

