[msg MSG_006_0_0 [Voice in Your Head]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]I am the voice of your inner self...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Revel in the moment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]That which cannot be felt is merely a dream... The present is all we have.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]That's right...[e]
[uf 0 5 65278][uf 2 1]That's not true...[e]
[uf 0 5 65278][uf 2 1]Who cares...?[e]

[msg MSG_008_0_0 [Voice in Your Head]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]The future is but a fantasy, memory a fabrication...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Let your desire free you from your shackles... Such is your wish...[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I can't give in...[e]
[uf 0 5 65278][uf 2 1]Maybe so...[e]
[uf 0 5 65278][uf 2 1]I don't understand...[e]

[msg MSG_010_0_0 [Voice in Your Head]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Pleasure is what you truly seek.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]You stand before the doorway to bliss.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]You cannot deny your instincts... Embrace your desire...[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]I don't really get it...[e]
[uf 0 5 65278][uf 2 1]I'm listening...[e]
[uf 0 5 65278][uf 2 1]I'll pass...[e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]My consciousness is starting to blur...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I know I still have work to do...[n][uf 1 1][e]

[msg MSG_013_0_0 [Voice in Your Head]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]Why do you resist...? Do not avert your eyes from the truth...[n][uf 1 1][e]

