[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 1 0 0]I... Huh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Ominous Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Welcome to the Velvet Room.[n][uf 1 1][e]

[msg MSG_002_0_0 [Strange-Faced Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Ah... It appears we have a very rare guest indeed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Are you human? Or merely humanoid?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]It seems your destiny is similar to mine.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 6 0 0]Where... Where am I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 7 0 0]Who are you?[n][uf 1 1][e]

[msg MSG_004_0_0 [Strange-Faced Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Ah, forgive my manners. Allow me to introduce myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]My name is Igor. And this is my assistant Elizabeth.[n][uf 1 1][e]

[msg MSG_004_5_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]We both reside here in the Velvet Room.[n][uf 1 1][e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Pleased to meet you.[n][uf 1 1][e]

[msg MSG_006_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0]This place exists between mind and matter. It is a room for those who have forged a contract.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Yes... In awakening to the power of the wild card, you are now bound to a contract.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Henceforth, you shall be our guest in the Velvet Room.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 15 0 0]Wild card...?[n][uf 1 1][e]

[msg MSG_008_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]Surely you know that of which I speak. The ability to wield multiple Personas and their powers...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Until recently, a young man with the same talent was our guest here.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 18 0 0]Are you saying that you knew him?[n][uf 1 1][e]

[msg MSG_010_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0]Indeed I did. He achieved a marvelous thing—finding the answer to life.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 20 0 0]The answer to life...[n][uf 1 1][e]

[msg MSG_012_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]The power you have gained is a means to attain that answer.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 22 0 0]If I were to find this answer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 23 0 0]Would it mean my death?[n][uf 1 1][e]

[msg MSG_014_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]All who live journey in search of the answer, and they find it at the journey's end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 25 0 0]If you have close ties to people you call friends, remember this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 26 0 0]"Strength of heart, when united, is barred by no door."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 27 0 0]It was the same for that young man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 28 0 0]And that is all I can tell you.[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 0 0 0 29 0 0]......[n][uf 1 1][e]

[msg MSG_016_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Well then, I mustn't hold you here any longer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 31 0 0]It would appear that an ordeal is about to unfold upon your return.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 53 65535 0 0][uf 3 1 1 0 0 32 0 0]...That feeling again![n][uf 1 1][e]

[msg MSG_018_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 33 0 0]I am certain you will require our help in the future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Please, take this.[n][uf 1 1][e]

[msg MSG_020_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 35 0 0]It would be best if you came here of your own free will next time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 6 65535 0 0][uf 3 1 1 0 0 36 0 0]Until then, farewell...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]I once made a choice to live.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]So much has changed[n]since then, myself included.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]If this new power is a sign[n]that I'm drawing closer to life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0]...does it mean that the answer[n]at the end of the journey is... death?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0]I was surprised, at the time, to discover[n]how little the possibility bothered me.[n][uf 1 1][e]

