[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 1 0 0]You'll be okay on your own from here, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 2 0 25 25]Let's see... I guess you should go see your homeroom teacher first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]The faculty office is over there on the left. They'll tell you more when you get there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 2 1 25 25]Well, that about does it. Any questions before I go?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Which class are you in?[e]
[uf 0 5 65278][uf 2 1]Not really.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Me? I dunno... I haven't looked at the classroom assignments yet.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Hey...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 7 0 0]About last night... Don't tell anyone what you saw, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 2 1 25 25]See you![n][uf 1 1][e]

