[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I thought your face looked familiar... You here again, kid?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Even Buddha's not that forgiving. Alright, that's it. I'm gonna hand you over to the bouncer and...[n][uf 1 1][e]

[msg MSG_000_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, there's no Buddha in this world, so... Stop lookin' at me like that and sit down, kid.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...So tell me, is it that fun hanging out with an old monk whose own wife and kid left him?[n][uf 1 1][e]

[msg MSG_001_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]How come you're always alone when I see ya? Don'tcha got any friends?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I can't say I don't.[e]
[uf 0 5 65278][uf 2 1]I don't have any friends.[e]

[msg MSG_003_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]What the hell's that supposed to mean? Either ya do or ya don't. Don't get smart with me, kid.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]What would you call a "friend," anyway? Where do you draw the line between "friend" and "acquaintance"?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 17 15 114]Either ya like being alone, or ya got problems... In any case, well said. No hesitation whatsoever.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Don't worry if ya don't got any friends. Most of life's troubles come from human relationships anyway.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]...Let's define a "friend" as... someone you hold dear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]The way I see it, no one in this world ever really cares for others...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]People always want somethin' out of a relationship. They only really love themselves.[n][uf 1 1][e]

[msg MSG_007_3_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]You don't call someone who doesn't like you your friend, do ya? No, 'cause you know you won't get nothin' from 'em.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Which means, in this world, there's no one you can truly hold dear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]At the end of the lonely road of love, kid, you're the only one left standin' there.[n][uf 1 1][e]

[msg MSG_007_7_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]But, you see those gals over there, the ones on the dance floor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]If you can bring one of 'em over here, I'll be your friend in return. Eh? Whaddaya think? I know you can do it![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I felt Mutatsu's warped trust in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_009_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]...Too tired to go talk to 'em, eh? Heh, you look like you're gonna doze off any second now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Go home for now, kid. Besides, I know you're gonna come again anyway, even if I tell you not to.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I said goodbye to Mutatsu[n]and went back to the dorm.[n][uf 1 1][e]

