[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I was hoping to go for another run after rehydrating...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I believe you've done enough physical activity for one day. Any more, and you'll hurt yourself.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Fine. So, [uf 4 1], were there any subjects you needed help with?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Any tips for grasping formulas?[e]
[uf 0 5 65278][uf 2 1]Any tips for remembering kanji?[e]
[uf 0 5 65278][uf 2 1]Any tips for memorizing vocab?[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Nothing beats using them in practice problems. Are you concerned about getting bored and losing focus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]In that case, try a quick workout between problems. The brain perks up once you get the circulation flowing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Not to mention, looking forward to your next workout is a great way to stay motivated.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]The most basic method is writing them over and over again... But I get that's a tough way to stay motivated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]That's why I reward myself with workout reps based on the number of new kanji I've learned.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]The more you study, the stronger you'll get. Pretty motivating, huh?[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I increase the number of reps in my workout by the number of new words I've committed to memory.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]The more you learn, the further you can push your limits. Killing two birds with one stone, as they say.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]In any case, I advise having a good workout ready to treat yourself with after a study session.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]It all comes down to making it a regular habit. Just a little each day really adds up.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I wasn't going to say anything, but... Akihiko, working out isn't normally a "reward" for most people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]On top of that, what good does it do to preach about long-term habits mere days before the exam?[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Hm, I guess you have a point... In that case, how would you recommend cramming for it?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]It's not my usual style, but I would focus on memorizing material that is likely to be tested.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]If you give it your all, it shouldn't be too difficult. Easier than facing the enemy wholly unprepared, at least.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Well, we can talk all night, but doing is where the magic happens. Here, let me give you some practice problems.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]The two of them continued[n]giving me rigorous advice...[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]You catch on quick, [uf 4 1]. You immediately took what you learned and put it into practice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]All you need now is some strength training and you'll be unstoppable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Once the exams are over, why don't we dive into Tartarus for a bit and get some workouts in?[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You never change... I'll need to continue keeping an eye on you to make sure you don't overdo it.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Heh. The more you study and the more you train, the better results you'll get.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I look forward to seeing what you'll accomplish from here on, [uf 4 1].[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Let's call it here for today. I want to get some stretches in before heading to bed.[n][uf 1 1][e]

