[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Fuuka asked me to check on Amada...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This could be a good opportunity[n]to get to know him better.[n][uf 1 1][e]

[msg MND_000_1_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Looks like Amada is in his room...[n]This could be a good opportunity[n]to get to know him better.[n][uf 1 1][e]

[msg MND_001_1_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]...Yes?[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 7130 0 0]Ha...! Hyah![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sounds like he's doing[n]something in his room.[n][uf 1 1][e]

[msg MND_005_1_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 7129 0 0]Hah! Hyah...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Looks like Amada is in his room.[n][uf 1 1][e]

[msg MND_007_1_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 3 0 65535 7099 0 0]Oh. Who's ther—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]...Gah! Ow![n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7009 0 0]Oh. [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I know you must be busy, but do you have time to come with me tonight?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Seems like Amada wants me to[n]accompany him somewhere.[n][uf 1 1][e]

[msg MND_011_1_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7009 0 0][uf 4 1]-san, do you have some spare time?[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7040 0 0]Thanks. I wasn't sure if I'd be able to go there alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I'd like to head over to Port Island Station now if that's okay with you...[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]Oh, well... That's too bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I probably need your help to go there... I'll ask again when you seem free.[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Did you see my message? I have a request for you...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Seems like he has some business with me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7009 0 0]Um, [uf 4 1]-san, do you have some spare time right now?[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Seems like he has some business with me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7040 0 0]Thank you. Well, let's head to the roof first...[n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7021 0 0]Oh, I see. Well, maybe next time. Hopefully, you'll be free then.[n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Thanks for coming. Do you have a moment?[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Seems like he was waiting for me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7009 0 0][uf 4 1]-san, do you have some time to spare right now?[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Amada?[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_029_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7087 0 0]Okay. Let's head out then.[n][uf 1 1][e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]I see. Well, next time, I guess, then.[n][uf 1 1][e]

