[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Looks like there's only educational manga here. Man, I wish they had some shonen stuff...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Ah well. At least I have that one I borrowed from what's-his-name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Yo, you wanna read it too? It's this baseball manga that finished up a while back.[n][uf 1 1][e]

[msg MSG_500_0616_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Man, looks like they only got educational manga. I was hoping for some shonen stuff...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Ah well. At least I still have that one I borrowed from what's-his-name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]You wanna give it a read too? It's this baseball manga that finished up a while back.[n][uf 1 1][e]

[msg MSG_500_0821_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]I thought just sittin' inside and reading manga'd help me beat the heat, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I'm still friggin' hot! ...But this manga's pretty hot too, heh heh. Wait, not like that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]It's this cool baseball manga that... Actually, why don't you just read it yourself?[n][uf 1 1][e]

[msg MSG_500_0824_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]No matter how bored I get, I don't think I'll ever touch any of the books here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Not much else to do, though... Well, there's that one manga I borrowed from what's-his-name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You wanna read it too? It's this baseball manga that finished up a while back.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Reading the baseball manga with Junpei[n]could help improve my [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]C'mon, let's read it.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I'll pass.[e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2079 0 0]Hey, guess what! I just borrowed some more of that manga from last time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I got way more volumes this time. Carrying them all was a drag though...[n][uf 1 1][e]

[msg MSG_500_0821_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]Damn, it's hot... It'd be nice to have something to distract me from the heat, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oh, right! The manga! I borrowed some more of it.[n][uf 1 1][e]

[msg MSG_500_0824_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2114 0 0]Nothin' to do in my room, nothin' to do out here... Pretty boring, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Oh, wait, I forgot! I borrowed more of that manga we were reading last time![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Reading the baseball manga with Junpei[n]could help improve my [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You wanna read some more of it?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I'll pass.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2002 0 0]Yo! I got the rest of that manga![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]It's gettin' down to the final inning! We gotta finish it![n][uf 1 1][e]

[msg MSG_500_0821_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2007 0 0]Man, this heat is killin' me. I wouldn't be surprised if all these books just burst into flames...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oh, that reminds me, I borrowed the rest of that manga.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]It's gettin' down to the final inning! We gotta finish it![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]It seems like Junpei has been[n]looking forward to this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Reading the baseball manga with Junpei[n]could help improve my [uf 4 30 2 1 1 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Junpei might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You up for it? If you want, I can bring 'em out now.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I'll pass.[e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]It's pretty relaxing just reading manga here, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You remember that we finished that baseball one last time, right? Well, I borrowed another one.[n][uf 1 1][e]

[msg MSG_500_0821_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Dude, it's so hot, even here. But I guess complaining's not gonna make it better...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]That's why I got the perfect thing to distract us from the heat! I borrowed a new manga series.[n][uf 1 1][e]

[msg MSG_500_0824_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]What even are these books? They don't exactly look like something someone could read for fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Eh, whatever. I'll just read some manga. I borrowed a different series this time.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Junpei will gain any[n]more skills even if we read together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But reading manga with him could[n]help improve my [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You wanna get in on some of this manga action?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I'll pass.[e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Aw yeah! That's what I like to hear![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2050 0 0]Eh, suit yourself. This series is tight as hell, though. Just sayin'.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]It's nice and quiet here, huh? I ain't like a huge reader, but this'd be the place to do it.[n][uf 1 1][e]

[msg MND_018_2_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Junpei will gain any[n]more skills even if we read together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But reading manga with him could[n]help improve my [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg MSG_018_3_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Whaddaya think? Wanna read some manga?[n][uf 1 1][e]

[msg MND_018_5_0]
[uf 0 5 65278][uf 2 1]Reading the baseball manga with Junpei[n]could help improve my [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MSG_018_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Whaddaya think? Wanna read some manga?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2067 0 0]Yo, whaddup?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You're takin' care of the planters up top, right? Mind if I give it a try?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Girls are into slim dudes, right? Might be good to eat some vegetables after all...[n][uf 1 1][e]

[msg MSG_500_0801_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, you doin' some prep tonight for that competition tomorrow?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Well, if you got the time, you think we can go see what's up with those planters on the roof?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I just wanna check 'em out real quick.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Wanna head up?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, uh... You think we should check on those planters up there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I know you're not supposed to give 'em too much water, but what if they're not getting enough?[n][uf 1 1][e]

[msg MSG_500_0801_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2074 0 0]Wanna go check on the planters on the roof? It'd suck if the plants all died on us all of a sudden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oh, wait, you have that competition tomorrow, huh? Well, we don't need to do it now, but...[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I'm not too confident doing it on my own, so if you're free, that'd be cool.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]I can help.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, wanna head to the roof and work on those planters?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I check on 'em once in a while, but I thought I prolly shouldn't touch 'em without you around.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Junpei seems motivated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Junpei might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]So how 'bout it? You're free, right?[n][uf 1 1][e]

[sel SEL_030_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, if you're gonna do some gardening, I'll come too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]It's actually a pretty good workout. I didn't think I'd get this into it.[n][uf 1 1][e]

[msg MSG_500_0801_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, if you're gonna do some gardening, I'll come too. It's actually a pretty good workout.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Might be some good training for your competition tomorrow, right?[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Junpei will gain any[n]more skills even if he helps me garden...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_033_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]C'mon, let's build up a sweat and release some indoor fins. Or, wait... What're they called?[n][uf 1 1][e]

[sel SEL_034_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's go.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_035_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Sweet! Let's get to it.[n][uf 1 1][e]

[msg MSG_036_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2067 0 0]Busy, huh? Well, if you ever feel like it, let me know.[n][uf 1 1][e]

[msg MSG_037_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Oh, change your mind? Alright, let's get upstairs, then.[n][uf 1 1][e]

[msg MND_037_2_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Junpei will gain any[n]more skills even if he helps me garden...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But the quality of the produce might improve[n]if we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_037_4_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Can't really do it without you, dude.[n][uf 1 1][e]

[msg MND_037_6_0]
[uf 0 5 65278][uf 2 1]The quality of the produce might improve if[n]we tend to the rooftop planters together.[n][uf 1 1][e]

[msg MSG_037_8_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]C'mon, it might be fun![n][uf 1 1][e]

[sel SEL_SEED_CHOOSE top]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 0]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 1]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 2]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 3]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 4]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 5]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 6]"[e]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 0 7]"[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MND_SEED_THINK]
[uf 0 5 65278][uf 2 1]What should I plant...?[n][uf 1 1][e]

[msg MND_SEED_DAY]
[uf 0 5 65278][uf 2 1]Looks like it can be harvested on [uf 0 1 2][uf 2 4 1]/[uf 2 4 2][uf 0 1 27]...[n][uf 1 1][e]

[sel SEL_PLANT_CHOOSE top]
[uf 0 5 65278][uf 2 1]Plant it[e]
[uf 0 5 65278][uf 2 1]Don't plant it[e]

[msg MND_NO_PLANT_DORMITORY]
[uf 0 5 65278][uf 2 1]Come to think of it, I don't think I've planted[n]anything in the rooftop planters yet...[n][uf 1 1][e]

[msg MND_PLANT_CAN_NOT]
[uf 0 5 65278][uf 2 1]Looks like I won't be able to harvest it[n]before the Promised Day, January 31st...[n][uf 1 1][e]

[msg MND_PLANT_OK]
[uf 0 5 65278][uf 2 1]There should still be produce in the rooftop[n]planter that has yet to be harvested.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should harvest those first...[n][uf 1 1][e]

