[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_000_5_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth asked[n]me to get a specific item for her...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Koromaru seems to be happy[n]after eating his fill of dog food.[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 4 25 9]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It looks like he thinks I'm hungry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru is giving me a meaningful[n]stare, his eyes full of sympathy...[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I think he's trying to share[n]his dog food with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should accept it...[n][uf 1 1][e]

