[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4136 0 0]What is it?[n][uf 1 1][e]

[msg MND_000_5_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth asked[n]me to get a specific item for her...[n][uf 1 1][e]

[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]Hm? You're looking for a triangular sword?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]Is that supposed to be a riddle? I'm not sure what you mean...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Hm, a triangular object used for dueling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]By any chance, are you talking about a fencing épée?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's not a triangular sword, no, but the cross-section does resemble a triangle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Let me retrieve mine for you.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]Here you go. Do you plan on taking up fencing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]If so, I can teach you a thing or two once I have some spare time.[n][uf 1 1][e]

