[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]Yo, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Did you see my text message? Wanna go grab a bite?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Sanada has invited me to join him.[n]This might be a good opportunity[n]to get to know him better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3001 0 0]Oh, [uf 4 1]. If you've got time, wanna get some food now?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Sanada has invited me to join him.[n]This might be a good opportunity[n]to get to know him better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Sanada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]Great! Let's go.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]All right. I guess it is pretty late already.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Lately, I'm only free at night... Let me know when you have some time to hang out.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]...Oh, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Today's the day I finally return the favor. Are you free?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3001 0 0]Today's the day I finally return the favor. Are you free now?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Sanada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]All right, then let's go.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Sorry that I only have time at night... Let me know the next time you're free.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]Ah, there you are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]I've actually finished my shopping already...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Do you have some time now? I want your help for something.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3005 0 0]There's something I want to try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]If you're free, I'd like you to accompany me.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Sanada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3039 0 0]Thanks. Then let's head back to the dorm together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]...Ah, crap. I forgot to buy eggs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Sorry, but can you go back first and make sure no one uses the kitchen? I'll meet you there in a bit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Don't worry, I won't keep you waiting long. I'm quicker on my feet than you are, you know.[n][uf 1 1][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]I see. That's fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Maybe next time. Let me know when you're free.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]Thanks for coming. It's pretty cold today, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]You saw my text, right? Wanna get moving and warm up a little?[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]I wanted to talk to you about something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I know it's a little late, but feel like getting a quick warm-up in?[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Sanada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]Cool. Let's do this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]I know this wasn't your idea, but I'm not planning on letting you cut corners.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]All right. First on the list is jogging to Naganaki Shrine. Let's go![n][uf 1 1][e]

[msg MSG_027_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]I see. Well, I'm not gonna force you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]But it's not so bad once in a while, you know? Let me know if you're up for it another time.[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3010 0 0]There you are. Are you free now?[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[msg MSG_030_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3002 0 0]Are you free tonight? Let me know if you have some time to spare.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Sanada?[n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Sanada[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_033_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]All right. Have you decided what you want to eat?[n][uf 1 1][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]I see. I'm sure you have a lot going on right now.[n][uf 1 1][e]

