[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 2 1 0 6]What is that...? I don't like the looks of it...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 2 2 0 6]Maybe it's preparing something...? Be careful![n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 2 3 0 6]I'm picking up a massive energy surge within the enemy![n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 2 4 0 6]That power... It's terrible...[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 2 5 0 6]If that attack were to land multiple times... Um, I'm gonna try scanning![n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 2 6 0 6]You can't afford to keep taking that attack! You have to stop it somehow![n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 2 7 0 6]These readings... Oh! While it's charging up, its power levels become unstable![n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 2 8 0 6]If you can disrupt it, that should prevent its attack! Everyone, go on the offensive![n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 2 9 0 6]Focus on attacking, just like before! That should disrupt the enemy's charging![n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 2 10 0 6]It's gathering even more power than before...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 2 11 0 6]Brace for— No, it's too strong... You have to stop it from attacking at all![n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 2 12 0 6]It's even stronger...!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 2 13 0 6]You don't stand a chance against this one! You need to interrupt that attack![n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 2 14 0 6]It's gone...! And it looks like the enemy can't move![n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 2 15 0 6]Now's your chance![n][uf 1 1][e]

