[msg MSG_000_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22501 0 0][uf 5 21 1 100]Hi there! Welcome![n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Shop[e]
[uf 0 5 65278][uf 2 1]Buy something[e]
[uf 0 5 65278][uf 2 1]Talk[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]Maybe I should ask about the rumors[n]of the [uf 0 1 2]taiyaki[uf 0 1 27] I read on the website...[n][uf 1 1][e]

[msg MSG_048_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]Oh, taiyaki? It's our long-awaited new product that's getting rave reviews![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]I got so many requests from students that I started bringing them in every day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]And you know what, it's a big hit... Sorry, I'm starting to ramble.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22502 0 0][uf 5 21 1 100]Anyway, this taiyaki is [uf 0 1 2]delicious even if you chill it in the fridge at home[uf 0 1 27]... So try it out![n][uf 1 1][e]

[msg SYS_049_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Lukewarm Taiyaki[uf 0 1 27] can now be bought at the school store.[n][uf 1 1][e]

[msg MSG_050_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22505 0 0][uf 5 21 1 100]Oh, sorry, I'm talking too much, aren't I? So, what would you like to buy?[n][uf 1 1][e]

[msg MSG_002_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]Hm? You seem interested in what we've got for sale... You must be new or a transfer student![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]We don't have a huge variety of bread, but they're all very popular.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]I prepare a lot of food for the kids who are doing club activities.[n][uf 1 1][e]

[msg MSG_003_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]I heard that the captain of the boxing team got injured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]Some girls were gossiping about it. That's a rough way to start the new school year.[n][uf 1 1][e]

[msg MSG_004_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22507 0 0][uf 5 21 1 100]Did you hear that one of the students fainted? Is she all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]Hmmm... There's a lot of weird stuff going on out there. You should watch out too.[n][uf 1 1][e]

[msg MSG_005_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]I guess the heat doesn't bother you guys when you're wearing your summer clothes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]As for me... There's no air conditioner in here, and it gets so hot![n][uf 1 1][e]

[msg MSG_006_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]It's almost summer vacation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]The shop will be closed for the duration, so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]That means I won't get paid. *sigh* This month is going to be tight...[n][uf 1 1][e]

[msg MSG_007_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]I see that Apathy Syndrome stuff on the news a lot these days. It seems like there's more of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]How worrying... You should be careful about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]If it spreads too wide and the school shuts down, I'd have to look for another job...[n][uf 1 1][e]

[msg MSG_008_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22507 0 0][uf 5 21 1 100]The culture festival got canceled... Well, with how bad that typhoon was, I'm not surprised.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]My house got soaked in that typhoon... It was a huge hassle![n][uf 1 1][e]

[msg MSG_009_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22507 0 0][uf 5 21 1 100]It's sad when any student dies, no matter what they were like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]I feel like I lost one of my own children...[n][uf 1 1][e]

[msg MSG_010_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]It's cooling down outside lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]There's no heater here, so it gets freezing cold in the winter.[n][uf 1 1][e]

[msg MSG_011_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22502 0 0][uf 5 21 1 100]Pick anything you like.[n][uf 1 1][e]

[msg MSG_012_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22502 0 0][uf 5 21 1 100]Pick anything you like.[n][uf 1 1][e]

[msg MSG_013_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22503 0 0][uf 5 21 1 100]Pick anything you like.[n][uf 1 1][e]

[msg MSG_017_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22506 0 0][uf 5 21 1 100]Are you here to buy some taiyaki, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]Sorry, but we're all sold out on those.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]I stock up on them every now and then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 100]Seems like they've [uf 0 1 2]been trending on some website[uf 0 1 27], and that's why they sell out so quickly.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]There's no taiyaki on sale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should try to gather more information[n]on the [uf 0 1 2]website[uf 0 1 27] it's trending on...[n][uf 1 1][e]

[msg MSG_019_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22502 0 0][uf 5 21 1 100]I don't have any taiyaki, but go ahead and look at what else there is.[n][uf 1 1][e]

[msg MSG_014_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22504 0 0][uf 5 21 1 100]Thanks.[n][uf 1 1][e]

[msg MSG_015_0_0 [School Store Vendor]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22504 0 0][uf 5 21 1 100]Sorry, but we're sold out of everything. Come by again.[n][uf 1 1][e]

[msg MSG_016_0_0 [School Store Vendor]]

