[msg MSG_000_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0][uf 5 21 1 101]Welcome to Rafflesia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20201 0 0][uf 5 21 1 101]What kind of flowers are you looking for today?[n][uf 1 1][e]

[msg MSG_001_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20204 0 0][uf 5 21 1 101]Thank you for stopping by. Please come again.[n][uf 1 1][e]

[msg MSG_011_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0][uf 5 21 1 101]Welcome. We have some new items in stock.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]We have a new variety called [uf 4 4 1 37 1 0]s... They gwow to be vewy yum-yum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]...Ah! I'm sorry, I—![n][uf 1 1][e]

[msg SYS_012_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Golden Tomato Sprouts[uf 0 1 27] can now be purchased at Rafflesia.[n][uf 1 1][e]

[msg MSG_013_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Um, so... what kind of flowers are you looking for today?[n][uf 1 1][e]

[msg MSG_002_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20205 0 0][uf 5 21 1 101]Thank you for your business.[n][uf 1 1][e]

[msg MSG_003_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20204 0 0][uf 5 21 1 101]I'm very sorry. Everything is out of stock at the moment. Please come by another day.[n][uf 1 1][e]

[msg MSG_004_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]...Oh, yes. Our seedlings have a reputation for growing very fast.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]We also stock special varieties that you won't find anywhere else... Why don't you try growing some?[n][uf 1 1][e]

[msg MSG_019_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0]How may I help you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ah, I see your friend isn't with you today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm talking about the boy in the cap who came by the other day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...Oh, by the way, those white flowers he was eyeing just sold out a while ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The next shipment of them hasn't been scheduled yet... I'm sorry about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20201 0 0]But, we do have other varieties available. Please take your time looking around.[n][uf 1 1][e]

