[msg MSG_000_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20501 0 0][uf 5 21 1 104]Welcome. If you want to make an impression, accessorizing is a must.[n][uf 1 1][e]

[msg MSG_001_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20504 0 0][uf 5 21 1 104]Come by any time you need a little sparkle.[n][uf 1 1][e]

[msg MSG_002_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20506 0 0][uf 5 21 1 104]Well, then... Come again.[n][uf 1 1][e]

[msg MSG_003_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20503 0 0][uf 5 21 1 104]By the way, I just got a designer pair of glasses in stock.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Not only are they hip, they even work with a more feminine style. Well, if you can spare 150,000 yen, that is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Although, if you bring me a [uf 4 4 1 37 1 0], I may be able to... adjust the price.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]It's an extremely rare collector's item, you see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Anyway, it's up to you how much you're willing to give up for these glasses.[n][uf 1 1][e]

[msg MSG_004_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Huh...? You don't happen to have a [uf 4 4 1 37 1 0], by any chance, do you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]If you'd be willing to part with that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20502 0 0][uf 5 21 1 104]I'll sell you those glasses for only 10,000 yen. What do you say?[n][uf 1 1][e]

[msg MSG_005_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Oh? I see you got your hands on a [uf 4 4 1 37 1 0].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]I won't force you, but if you're willing to hand that over...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20502 0 0][uf 5 21 1 104]I'll sell you those glasses for just 10,000 yen. What do you say?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Then it's yours.[e]
[uf 0 5 65278][uf 2 1]Sorry, it's mine.[e]

[msg MSG_006_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20504 0 0][uf 5 21 1 104]Thanks. Why don't you take the glasses at a discount, then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Go ahead and have a look around.[n][uf 1 1][e]

[msg MSG_007_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]I see... Well, it's your choice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20503 0 0][uf 5 21 1 104]Go on and have a look at our products.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Browse products[e]
[uf 0 5 65278][uf 2 1]Buy glasses for 10,000 yen[e]
[uf 0 5 65278][uf 2 1]Buy glasses for 150,000 yen[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Should I buy these Designer[n]Glasses for 10,000 yen...?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Should I buy these Designer[n]Glasses for 150,000 yen...?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Buy[e]
[uf 0 5 65278][uf 2 1]Don't buy[e]

[msg MSG_012_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20501 0 0][uf 5 21 1 104]Oh, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]If you can just bring me a [uf 4 4 1 37 1 0], I'll give you a discount on those glasses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Of course, you could also just buy them at the regular price. It's up to you.[n][uf 1 1][e]

[msg MSG_013_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20504 0 0][uf 5 21 1 104]Thank you for your business.[n][uf 1 1][e]

[msg MSG_014_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20505 0 0][uf 5 21 1 104]Hmmm... Looks like you're a little short on change. Come back when you can afford it.[n][uf 1 1][e]

[msg MSG_015_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20501 0 0][uf 5 21 1 104]Oh, it's you. I'll give you a discount on those glasses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 104]Go on and have a look at our products.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1][uf 4 4 1 37 1 0]... I wonder[n]if it's some kind of gemstone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Come to think of it, the Shadows[n]in Tartarus drop gems sometimes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Elizabeth[uf 0 1 27] might know something about it...[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1][uf 4 4 1 37 1 0]...[n]Elizabeth already told me about it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I recall, she said that the [uf 0 1 2]Lustful Snakes[uf 0 1 27] on[n]the higher floors of the [uf 0 1 2]Arqa[uf 0 1 27] block have it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should try checking the next[n]time I go to Tartarus...[n][uf 1 1][e]

[msg MSG_018_0_0 [Luxury Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20502 0 0][uf 5 21 1 104]Go on and have a look at our products.[n][uf 1 1][e]

