[msg MSG_000_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20603 0 0][uf 5 21 1 105]Hmmm... This is certainly a fascinating forum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]Hm? Are you interested in the dark web too...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]I collect information from various people about "interesting" sites and forums...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 105]If you want, I can sell you some info... Top secret stuff, even...[n][uf 1 1][e]

[msg MSG_001_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20602 0 0][uf 5 21 1 105]Heh, you're a curious one, aren't you...? Well, go on and take a look.[n][uf 1 1][e]

[msg MSG_002_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20604 0 0][uf 5 21 1 105]Thanks... I'll be on the search for more exquisite info...[n][uf 1 1][e]

[msg MSG_003_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20606 0 0][uf 5 21 1 105]Come again...[n][uf 1 1][e]

[msg MSG_004_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20605 0 0][uf 5 21 1 105]Sorry, I'm a little busy tonight... Come back some other time, won't ya?[n][uf 1 1][e]

[msg MSG_005_0_0 [Suspicious Man]]
[uf 0 5 65278][uf 2 1]Hm? What do you want?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]You got guts, comin' to a place like this on your own...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Well, I'd be happy to sell you some info on... "unconventional" websites, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Do you have your own computer? You'll need one to make use of my services...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Looks like I can get information[n]on unusual websites here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 0 1 2]If I can use a computer at the dorm[uf 0 1 27], I might[n]be able to look into these websites...[n][uf 1 1][e]

