[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 2 10 101]Hey, dude! Let's grab some seats up front![n][uf 1 1][e]

[msg MSG_900_0_0 [Refugee Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Ahh! They're all over the third floor already! This is it... We're gonna die here![n][uf 1 1][e]

[msg MSG_901_0_0 [Refugee Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Stay calm! We can't give up now! There's always hope, no matter how damned the world is![n][uf 1 1][e]

[msg MSG_902_0_0 [Refugee Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]As god as my witness, I won't die in this mall![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching the humans fight for survival[n]in that movie made me a little braver.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, man! My hands were sweating like crazy. Everything was so well done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 22 0 101 33 25 20]But dude, three movies in a row is way too much. Anyway, it's getting dark, so let's bounce.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Tomochika[n]and went back to the dorm.[n][uf 1 1][e]

