[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Screen Shot Movie Theater...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I gave it my all working part-time[n]at the concession stand...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I restocked the drink machine efficiently...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Someone asked for a recommendation,[n]so I picked a movie that fit their taste...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]In my spare time, I read brochures[n]and learned about trending movies...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]While working, I made eye contact[n]with zombies on the movie posters...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]There was a complaint about noisy[n]customers, so I gave them a warning...![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I confidently recommended popcorn to[n]a customer, and they bought some...[n][uf 1 1][e]

[msg MSG_009_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]I really appreciate your help. I'll be raising your hourly rate.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Since I'm getting the hang of things,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_011_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]You're really getting good at this! I'm looking forward to seeing you continue to improve![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Since I've gotten better at my work,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_013_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]Well, here's your paycheck.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I feel like I've improved my [uf 4 30 0 1 1 0][n]and [uf 4 30 2 1 1 0] because of work...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

