[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 30 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 30 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Please, just wait a little while longer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 30 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...Even if the tree is gone... you'll still live on... inside us...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Bunkichi-san is sleep talking.[n]Looks like he's taking a nap...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Take a closer look[e]
[uf 0 5 65278][uf 2 1]Leave him be[e]

[msg MSG_003_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh! [uf 4 2]-chan, you're here? You could've woken me up...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Or did you just want to admire my pretty face sleeping like a baby?[n][uf 1 1][e]

[msg MSG_003_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Upsy-daisy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 1 25 25]We recently closed the book on a difficult matter, so I s'pose the relief has put me at ease.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]It's the middle of the day, but I feel awfully sleepy...[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]What matter?[e]
[uf 0 5 65278][uf 2 1]Why are you relieved?[e]

[msg MSG_005_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I'm deeply touched that you and so many others tried to help us, but...[n][uf 1 1][e]

[msg MSG_005_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]The truth is, we sent a letter to Gekkoukan.[n][uf 1 1][e]

[msg MSG_006_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]While we're all here, I think it's time we told you...[n][uf 1 1][e]

[msg MSG_006_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]The truth is, we sent a letter to Gekkoukan.[n][uf 1 1][e]

[msg MSG_007_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]We asked them to go ahead and cut the persimmon tree down.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]But... why?[e]
[uf 0 5 65278][uf 2 1]Oh well.[e]

[msg MSG_009_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 6 15 103]Just the reaction I was hoping for, [uf 4 2]-chan! It was more than worth it to surprise you like that![n][uf 1 1][e]

[msg MSG_010_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Sorry for doing this without running it by you.[n][uf 1 1][e]

[msg MSG_011_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 5 13 6 5 103]Yeesh, I thought you'd be more surprised than that... Well, I guess I needn't have worried.[n][uf 1 1][e]

[msg MSG_012_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Sorry for doing this without running it by you.[n][uf 1 1][e]

[msg MSG_013_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]When we went to visit the tree together, I met a school faculty member on my way back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]He told me the administration is planning to put up a new school building where the tree currently is.[n][uf 1 1][e]

[msg MSG_013_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]It would be selfish of an old man like me to deprive those young people of new learning opportunities...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Helping children reach their potential is more important than clinging onto old memories. I think our son would agree.[n][uf 1 1][e]

[msg MSG_013_7_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]He was a teacher, after all![n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]That's true.[e]
[uf 0 5 65278][uf 2 1]Are you really sure?[e]

[msg MSG_015_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Yes... We had a long talk about it, and this was the conclusion we came to.[n][uf 1 1][e]

[msg MSG_016_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]You really set an example for young people, being so considerate to old folks like us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]We pray, with our son in Heaven, that more kind souls like you will graduate from Gekkoukan.[n][uf 1 1][e]

[msg MSG_016_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Here... We'd like you to have this.[n][uf 1 1][e]

[msg MSG_016_7_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]It's the first fruit produced by the persimmon tree. A little rough around the edges, just like our son...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 1 25 25]My dear was the one who suggested we give it to you.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]This must be something very[n]meaningful to the both of them...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Their deep gratitude reached my heart...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]

[msg SYS_018_0_0]
[uf 0 5 65278][uf 2 1]The Hierophant Social Link reached its maximum level! You can now fuse [uf 0 1 35]Kohryu[uf 0 1 27], the guardian of nature![n][uf 1 1][e]

[msg MSG_019_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Now, we have to cheer up and get on with our lives! We're too old to waste a single day![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]If we kicked the bucket while wasting our days away... I'm sure he'd laugh at us from Heaven![n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]It's hard on the parents to have such a well-respected son.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Oh, my... Does it sound like I'm boasting?[n][uf 1 1][e]

[msg MSG_021_0_0 [(SE) Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0][Laughing heartily][n][uf 1 1][e]

[msg MSG_022_0_0 [(SE) Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0][chuckling][n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]The three of us chatted until sunset...[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]I parted with the elderly couple[n]and went back to the dorm.[n][uf 1 1][e]

