[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 9 10 109]I just know I'm going to cry, so I brought two handkerchiefs with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 6 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 109 1 25 25]Let's go find our seats.[n][uf 1 1][e]

[msg MSG_900_0_0 [Handkerchief Deliveryman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]A man must always carry a handkerchief... You never know when you might encounter a woman in need.[n][uf 1 1][e]

[msg MSG_901_0_0 [Heartbroken Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]This is so wonderful... If only I'd fallen in love with someone like you...[n][uf 1 1][e]

[msg MSG_902_0_0 [Handkerchief Deliveryman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Please, I am but a humble deliveryman. If I can deliver just a bit of kindness to another, that's enough for me.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned some romantic[n]one-liners from the movie...[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 6 65535 0 0][uf 3 1 1 0 0 6 0 0]Those movies were all so beautiful. I was crying the whole time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 6 65535 0 0][uf 3 1 1 0 0 7 0 0]Thanks for coming with me. We should probably get going now, though.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]After saying goodbye to Chihiro,[n]I decided to go back to the dorm.[n][uf 1 1][e]

