[msg MSG_737_1_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 1 0 5]All right, let me tell you about a new tactic called "Shifting."[n][uf 1 1][e]

[msg MSG_737_1_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 2 0 5]When you knock an enemy down, Shifting allows you to leverage that opening to let someone else take action.[n][uf 1 1][e]

[msg MSG_737_1_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 3 0 5]Once you do, your offense can follow up with whoever you passed your action to.[n][uf 1 1][e]

[msg MSG_737_1_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 2 4 0 5]If you can coordinate well with your team, you'll be able to claim victory with even greater efficiency.[n][uf 1 1][e]

[msg MSG_737_1_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 5 0 5]You should all be experienced enough to pull this off now. Go ahead and give it a try.[n][uf 1 1][e]

[msg TRL_737_1_1]
[uf 0 5 65278][uf 2 1]You are able to Shift your own "1 More" action to another teammate. Press the L2 button to pass your action to someone else and navigate battles more effectively.[n][uf 1 1][e]

