[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]All right, today we're gonna see some of the greatest matches the champs have ever—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 2 0 0][uf 4 23 0 1 0 25 25][uf 4 21 4 4]Hm?[n][uf 1 1][e]

[msg MSG_001_0_0 [Female Announcer (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]...And here we are with the first match of the qualifiers. In the red corner, we have...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Akihiko Sanada-kun, from Gekkoukan High School![n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]It's me...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]This is footage from my first official match. My coach from back then recorded it for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Ah, sorry, looks like I put on the wrong video. Let me switch it out.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I want to see this.[e]
[uf 0 5 65278][uf 2 1]You look so young.[e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 6 25 25]Hey, come on. It's not that interesting.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]Yeah, I guess it has been quite some time.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]But I guess this might be a good opportunity. Let's watch it.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 11 0 0][uf 4 23 0 1 0 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]I look so stiff and nervous. And my form is all over the place...[n][uf 1 1][e]

[msg MSG_008_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]How did I even win this? At least I can tell I've improved since then.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Here's where I get my left straight in.[n][uf 1 1][e]

[msg MSG_010_0_0 [Female Announcer (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]And the winner is Sanada-kun, from the red corner![n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Check out my face. I'm trying to look calm, but on the inside I can barely contain myself.[n][uf 1 1][e]

[msg MSG_011_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]I know I said before that I just wanted to learn how to fight with my bare hands, but this might actually be why I stuck with boxing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 0 25 25]This victory gave me confidence. I wasn't so stiff in any of my later matches.[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]Are you the type to get nervous in front of a bunch of people like that?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]I'd say so.[e]
[uf 0 5 65278][uf 2 1]I don't know.[e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 1 25 25]That's what I like to hear. You're just as reliable as a leader ought to be.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 1 25 25]If you ever wanna try getting in the ring, I'd be glad to have you.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 4 25 25]Well, that's a surprise. You don't seem like you let the small things bother you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]But I guess you're good at not letting your weakness show, huh?[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 1 25 25]Yeah, I guess you wouldn't really know how tense that feels without experiencing it for yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]If you ever wanna try getting in the ring, I'd be glad to have you.[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 0 25 25]I've learned a lot from boxing, but there's a strict rule I follow when it comes to winning.[n][uf 1 1][e]

[msg MSG_017_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]Find your opportunity, then strike without hesitation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]It's easy enough to remember, but hard to apply. You could say the same thing about fighting Shadows, too.[n][uf 1 1][e]

[msg MSG_017_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]I've always tried to keep those words in mind, but now I'll be even more conscious of them.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Sanada seems to have found new potential[n]within himself after watching the DVD.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 9 25 25]You know, I never thought you'd see me like that... But it did help remind me how I felt when I was starting out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 1 25 25]Anyway, sorry you had to sit through that. We'll save the champion matches for next time.[n][uf 1 1][e]

[msg MND_019_5_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 2 1 1 0] has improved[n]after seeing Sanada fighting his hardest...[n][uf 1 1][e]

[msg MSG_020_0_0 [Female Announcer (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0]...Now we move on to round two of the qualifiers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]In the red corner: Akihiko Sanada-kun, from Gekkoukan High School![n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 1 25 25]...There's another one? Well, since we're already here, wanna watch some more before we go to sleep?[n][uf 1 1][e]

