[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Yo! Just who I was lookin' for![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]You guys wanna check out this [uf 4 4 0 37 1 16774] with me?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]Are you serious? We have more important things to do, you know.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2036 0 0]Wait, hear me out! We found this in the Abyss of Time, so it coulda been made by our minds or somethin', right?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]That's a good point.[e]
[uf 0 5 65278][uf 2 1]You just want to slack off.[e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0][uf 3 1 3 0 65535 2026 0 0]Right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]And I've actually wanted to watch this series for a while anyways. Look how productive I'm bein'![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2103 0 0]I so totally don't! This is some serious shit right here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 4 23 0 2 3 25 25]I mean, it does happen to be a series I've been wantin' to watch, but that's just a coincidence.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 3 0 65535 1122 0 0]Wow...[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]C'mooon, just one episode? Then I'll shut up about it, I swear![n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Only one episode, remember? No trying to get us to watch more.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Yeah, yeah, I know![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 4 23 0 2 4 25 25]Man, shit's hittin' the fan now, huh? Talk about the fate of the entire world...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1101 0 0]No kidding... And the production is insane![n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Whew... That was a close one.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1090 0 0]Wait, THAT'S where it ends!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 4 23 0 1 2 25 25]They didn't resolve anything! What ended up happening to the daughter!?[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Yeah, these foreign shows do that a lot. They always got so much goin' on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]But damn, Yuka-tan... For someone who was so against watching it, you sure got into it, huh?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1035 0 0]Well... You were so loud, I had to pay extra attention to it to tune you out![n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]Anyway, what are we even doing? This is a waste of time...[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Breaks are important too.[e]
[uf 0 5 65278][uf 2 1]We can still work hard later.[e]
[uf 0 5 65278][uf 2 1]It was fun, though.[e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 3 0 65535 1027 0 0]Sure, but still...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 3 0 65535 1093 0 0]Yeah, I guess...[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 3 0 65535 1065 0 0]I mean...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]I'll admit, it was fun, but...[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0]Well... It was kinda relaxing, so... It's probably fine once in a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0]It's not like we'd be able to give it everything we've got when we really need to if we're stressed out all the time...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]It seems watching the drama has helped Yukari-san acknowledge the value of taking breaks...[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0][uf 3 1 3 0 65535 2118 0 0]Alright, next episode![n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 3 0 65535 1143 0 0]No. We made a deal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Breaktime's over. Let's go.[n][uf 1 1][e]

