[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]※テスト※[n]スクリプトから発行されたメッセージです。[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I'd better get going...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]My phone won't turn on...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Doesn't seem like anyone's[n]trying to get a hold of me.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I'm not feeling very well... I should[n]go to my room and get some rest.[n][uf 1 1][e]

