[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Whoa, check out the moon! It's huge![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 3 0 25 25]I don't think I've ever seen it so bright.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 3 0 0]There's some research that indicates the Shadows are affected by the phases of the moon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Although, the same thing is true about humans.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]That would explain Yuka-tan's mood swings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Hey, wasn't it a full moon the night we went to the monorail?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Hm? It was?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Uh, is somethin' wrong?[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 9 0 0]Hey, did you see the moon on the night the dorm was attacked back in April?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]It was full.[e]
[uf 0 5 65278][uf 2 1]No, I didn't.[e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Today is June 8th... The monorail incident happened on May 9th...[n][uf 1 1][e]

[msg MSG_007_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 11 0 0]And the assault on the dorm was on April 9th! They were all on a full moon![n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 12 0 0]Mitsuru, are you there!?[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Akihiko...? Shadows are—[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Hey, can you hear me? Mitsuru, come in![n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]...Be caref...[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 16 0 0]Mitsuru!? Mitsuru![n][uf 1 1][e]

[msg MSG_012_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 6 4 0][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 17 0 0]What... is that...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 18 0 0]It's much bigger than the others... And it's attacking someone![n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 19 0 0]Dammit![n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 20 0 0]What the hell's goin' on!? I'm totally lost here![n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 21 0 0]It's one of them! If my guess is right, they come every full moon![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 22 0 0]We've gotta hurry![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 23 0 0]H-Hey! Wait for me![n][uf 1 1][e]

