[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]This character really drinks a lot of alcohol.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25][uf 4 1]-san, when you grow up, are you going to drink alcohol too?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]I would like to.[e]
[uf 0 5 65278][uf 2 1]I want to avoid alcohol.[e]
[uf 0 5 65278][uf 2 1]Will you?[e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I see. You should be careful about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I heard that drinking too much is bad for your health.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]But don't they say it's sometimes necessary to drink for work?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]And that sometimes it's hard to say no. Being an adult is all about taking the shots you're given.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 4 25 25]...Oh, I just made a pun, didn't I?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Me? I've never thought about it, actually...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]But I do hear that a lot of adults these days don't drink.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Alcohol has a very... mature feeling about it, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]I don't think I'm a fan of all the rowdy parties, but having a nice glass does look kind of cool.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]Speaking of, remember that bar scene...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Wow, it's late! Watching those bonus clips took longer than I thought.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel like I gained some [uf 4 30 2 1 1 0] after[n]watching how a man of conviction lives...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]It's about time I head to bed. Good night.[n][uf 1 1][e]

