[msg MSG_START_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There it is! Please chase it![n][uf 1 1][e]

[msg MSG_START_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]You're slowly catching up to the Shadow! Hang in there![n][uf 1 1][e]

[msg MSG_START_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]The Shadow is slowing down. Just a little more to go. Don't give up![n][uf 1 1][e]

[msg MSG_BRANCH_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]It's so fast that I lost its reading... Which way could it have gone...?[n][uf 1 1][e]

[msg MSG_BRANCH_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]I'm sorry, I lost sight of it again... Which way did it go...?[n][uf 1 1][e]

[msg MSG_BRANCH_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5086 0 0]Considering how far we've come, we have to catch up to it! This is the last one![n][uf 1 1][e]

[sel SEL_BRANCH_00 top]
[uf 0 5 65278][uf 2 1]Let's make a right![e]
[uf 0 5 65278][uf 2 1]未使用[e]
[uf 0 5 65278][uf 2 1]Let's make a left![e]
[uf 0 5 65278][uf 2 1]未使用[e]

[sel SEL_BRANCH_01 top]
[uf 0 5 65278][uf 2 1]Now right![e]
[uf 0 5 65278][uf 2 1]Right here as well![e]
[uf 0 5 65278][uf 2 1]Now left![e]
[uf 0 5 65278][uf 2 1]Left here as well![e]

[sel SEL_BRANCH_02 top]
[uf 0 5 65278][uf 2 1]Let's finish with a right![e]
[uf 0 5 65278][uf 2 1]未使用[e]
[uf 0 5 65278][uf 2 1]Let's finish with a left![e]
[uf 0 5 65278][uf 2 1]未使用[e]

[msg MSG_BRANCH_YUKARI_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]I saw it when it made the turn![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]It's definitely this way! Let's go![n][uf 1 1][e]

[msg MSG_BRANCH_JUNPEI_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Hehe, I totally saw where that shiny, giant thing went.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]It's this way! Everyone follow me![n][uf 1 1][e]

[msg MSG_BRANCH_SANADA_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]I could see a glimpse of its shadow from my point of view.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0]It ran off this way. Let's go![n][uf 1 1][e]

[msg MSG_BRANCH_MITSURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]It was faint, but I saw light gleam off of its body.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I'm not completely certain, but it should be this way. Let's hurry![n][uf 1 1][e]

[msg MSG_BRANCH_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5099 0 0]Koro-chan, you were able to tell which way it went?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Aigis, follow Koro-chan![n][uf 1 1][e]

[msg MSG_BRANCH_AEGIS_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6064 0 0]I should be able to identify the direction it went based on the location that can be deduced from its footsteps.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am quite certain it went this way. Let us go.[n][uf 1 1][e]

[msg MSG_BRANCH_AMADA_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7087 0 0]I saw a glimpse of it running away from us![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]I'm pretty sure it went that way! Let's go![n][uf 1 1][e]

[msg MSG_BRANCH_KOROMARU_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof! Woof woof![n][uf 1 1][e]

[msg MSG_BRANCH_ARAGAKI_10 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9005 0 0]I saw where it went from my position.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]It's this way. We going after it?[n][uf 1 1][e]

[msg MSG_BRANCH_METIS_10 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30080 0 0]I saw it go that way![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0]Come on! Let's corner it![n][uf 1 1][e]

[msg MSG_SUCCESS_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Unused[n][uf 1 1][e]

[msg MSG_FAILURE_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 5 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]It's a dead end! It seems we went the wrong way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Oh no, the reading is getting farther and farther away... I guess this might be it...[n][uf 1 1][e]

[msg MSG_TBOX_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]It's a dead end... It seems we went the opposite direction as that Shadow...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]The Shadow's reading is getting further away. It escaped...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]At the very least, we can get this treasure chest it missed.[n][uf 1 1][e]

[msg MSG_BATTLE_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]The Shadow's movement has stopped. It seems it's hit a dead end![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Let's hurry! Just keep going straight![n][uf 1 1][e]

