[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 0 0 0 1 0 0]Hrm...[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]You're still at it?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Yes. You never know when an enemy might appear.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]But... I thought you couldn't scan outside of Tartarus.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 51 65535 0 0][uf 3 1 1 0 0 5 0 0]To be honest, I am indeed lacking in that area...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]Maybe this is the best Penthesilea can do in terms of data-gathering.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Though I must say, the power of Persona seems to be much more diverse than I once thought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 8 0 0]We even have someone who can switch Personas in the midst of battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 9 0 0]There's something special about his ability...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]And it hasn't even been that long since his awakening.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Yeah, I was surprised too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]But in the end, it's up to him whether or not he reaches his full potential.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 0 0 0 13 0 0]Hm...?[n][uf 1 1][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 17 5 4 0][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 51 65535 0 0][uf 3 1 1 0 0 14 0 0]It's a Shadow![n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 15 0 0]What!? You actually found one?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 65535 0 0][uf 3 1 1 0 0 16 0 0]Wait, something's not right. The reading is too big.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 65535 0 0][uf 3 1 1 0 0 17 0 0]I've never detected an enemy of this size...[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Wait... Is it like that huge one from last month!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 19 0 0]I think so.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 20 0 0]Well then, this is gonna be fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 2 0 25 25]I'll wake up the others.[n][uf 1 1][e]

