[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]To quickly make room for more customers,[n]I carried off a lot of dishes all at once...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Despite being busy, I responded to complaints[n]about the slow service with sincerity...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I mustered up my courage and helped[n]arguing customers resolve their issues...![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]The customers are ordering a lot today.[n]The café is filled with pheromones...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I offered my support to a coworker who[n]got scolded for messing up an order...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]A customer's baby was bawling, but I[n]managed to soothe them gracefully...![n][uf 1 1][e]

[msg MSG_009_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]Thanks for sticking it out today. I've decided to increase your hourly wage. Keep it up.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Since I'm getting the hang of things,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_011_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]Your handling of customers is truly wonderful. I've increased your hourly wage. Good work.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Since I've gotten better at my work,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_013_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]I gave you a little bonus on top of your usual pay. Thanks for helping out during peak time.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]After dealing with difficult customers,[n]I feel like my [uf 4 30 1 1 1 0] and[n][uf 4 30 2 1 1 0] have increased...![n][uf 1 1][e]

