[msg TRL_000_0_0 [The Leader's Characteristic]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 4 2]'s characteristic is boosted according to the percentage of Personas registered in the Persona Compendium.[n][uf 1 1][e]

[msg TRL_001_0_0 [The Leader's Characteristic]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]These special characteristics are unique abilities that automatically activate during combat. More information can be found on the status screen.[n][uf 1 1][e]

