[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 8 10 105]A war movie, huh? Sounds pretty heavy. Alright, let's do this![n][uf 1 1][e]

[msg MSG_900_0_0 [Soldier A]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Don't you die, Ryan! You swore we'd go back home together! You swore![n][uf 1 1][e]

[msg MSG_901_0_0 [Soldier B]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Hey man, don't gimme that look. You know I... I can't live without your smile... bro...ther...[n][uf 1 1][e]

[msg MSG_902_0_0 [Soldier A]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Ryan...? Ryan! Ryaaaaaaan![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel braver after watching the[n]fearless soldiers in that movie.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 5 0 0]Dude, that was insane! I wish I had that kind of fire in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 22 0 105 25 25 20][uf 4 23 0 105 1 25 25]Okay, I'll see you later![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Miyamoto[n]and went back to the dorm.[n][uf 1 1][e]

