[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Fuuka and the others are talking[n]about that door from earlier.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13217 0 0][uf 4 2], may I borrow you for a moment?[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13228 0 0]It would appear you've faced the threat beyond that door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A door connecting to the tunnel which was created within Tartarus... Perhaps an appropriate name for it would be a "[uf 0 1 2]Monad door[uf 0 1 27]."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]The Shadows that congregate past such doors will prove to be a valuable means of accelerating your growth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I must know how you fared. Did your enemies provide you with a challenge?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]It was a rough fight.[e]
[uf 0 5 65278][uf 2 1]They went down easy.[e]

[msg MSG_004_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]Excellent. I am pleased to hear that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]I believe challenging more daunting foes will act as a sort of shortcut in your development.[n][uf 1 1][e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]On another note...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I've detected some sort of structure on the 91st floor. It emanates an energy not dissimilar to the door you entered.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]The dimensions of this structure resemble a tunnel. One might call it a "[uf 0 1 2]Monad Passage[uf 0 1 27]."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Entering this passage may provide you with another opportunity to test your mettle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]For the time being, I will log that investigation as a personal request.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I've received a new request from Elizabeth.[n][uf 1 1][e]

[msg MSG_007_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 0 0]I look forward to observing your continual progress.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]A [uf 0 1 2]Monad door[uf 0 1 27]... And a passage, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tartarus is never gonna stop[n]being a mystery to me...[n][uf 1 1][e]

