[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 3 0 65535 10436 0 0][uf 5 13 6 3 103]Don't you think so, [uf 4 2]-chan?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 3 0 65535 10693 0 0][uf 5 13 6 2 104]Oh, you...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I can feel my bond with the two of them[n]grow stronger as we spend time together...[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's almost dark...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

