[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]You're late. I was just thinkin' about leaving...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]You been comin' here a lot too, huh?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Are you alright, kid? You know, financially, paying for the drinks here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]High school kids don't have much money, do they? At least, I never gave much to my son.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I have enough.[e]
[uf 0 5 65278][uf 2 1]I'm not NOT struggling...[e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 17 5 114]Do you, now...? Hmph, I guess you kids have ways to make money these days.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]You're not doin' anything illegal, though, are ya, kid? Not that I care.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]...What the hell kinda answer is that? What're they teachin' you kids at school these days?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I don't like your roundabout way of talkin'. It's a yes or a no. Speak clearly.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]By the way, lemme ask you: Is there anything you want right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]...And I mean somethin' you can buy with money. Not some crap like "love" or "a sense of humor."[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Yes.[e]
[uf 0 5 65278][uf 2 1]No.[e]

[msg MSG_008_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 5 13 17 5 114]Hmph, that was a stupid question. I should've guessed.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Materialistic desire can lead to aspiration, but still...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 17 15 114]Hmph, don't tell me you've attained enlightenment at your age.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Back when I was a young man, I never had enough money to buy the things I wanted.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]When you get to be my age... Hmm, well. Try thinkin' about it this way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]You work to make money so you can have a better life, but to make enough money, you gotta work all the time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]So you never get to enjoy that better life you're working so hard to have... Quite a paradox, isn't it?[n][uf 1 1][e]

[msg MSG_012_3_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]...Do you know what the average lifetime income of a white-collar worker is?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Including a retirement fund and an annual pension...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]It's 250,000,000 yen! That's not even close to a lottery jackpot.[n][uf 1 1][e]

[msg MSG_012_7_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Thanks to me, you learned somethin' new today, eh, kid?[n][uf 1 1][e]

[msg MSG_012_8_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Now, don't waste your life workin' all the time tryin' to get rich. Just take life as it comes.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Mutatsu's words are harsh,[n]but I can feel his kindness...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Mutatsu a little better now...[n][uf 1 1][e]

[msg MSG_014_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I worked my ass off for a lousy 250,000,000 yen! And for what!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I wish I could buy back all the time I lost...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I said goodbye to Mutatsu[n]and went back to the dorm.[n][uf 1 1][e]

