[msg MSG_000_0_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]...Huh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]What the...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Wh... What's happening to me...?[n][uf 1 1][e]

[msg MSG_002_3_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Uh... Ahh... Aaaaaaaaagh![n][uf 1 1][e]

[msg MSG_002_5_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]Waaaaaaaaaaaaagh![n][uf 1 1][e]

