[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_ELIZ_T_001 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]Oh? Is there something I can assist you with?[n][uf 1 1][e]

[msg MSG_ELIZ_T_002 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Did you need anything else?[n][uf 1 1][e]

[msg MSG_ELIZ_T_005 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]How may I assist you?[n][uf 1 1][e]

[msg MSG_ELIZ_T_003 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Thank you for earlier. Now then... How may I be of assistance?[n][uf 1 1][e]

[msg MSG_ELIZ_EXIT [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]If you require anything else, please do not hesitate to ask.[n][uf 1 1][e]

[sel SEL_ELIZ_T_Daily_01 top]
[uf 0 5 65278][uf 2 1]About requests[e]
[uf 0 5 65278][uf 2 1]Ask Elizabeth out[e]
[uf 0 5 65278][uf 2 1]Hand over the drinks[e]
[uf 0 5 65278][uf 2 1]Hand over your cooking[e]
[uf 0 5 65278][uf 2 1]Hand over a potato[e]
[uf 0 5 65278][uf 2 1]Talk[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_ELIZ_T_Field_01 top]
[uf 0 5 65278][uf 2 1]About requests[e]
[uf 0 5 65278][uf 2 1]Hand over the drinks[e]
[uf 0 5 65278][uf 2 1]Hand over your cooking[e]
[uf 0 5 65278][uf 2 1]Hand over a potato[e]
[uf 0 5 65278][uf 2 1]About missing persons[e]
[uf 0 5 65278][uf 2 1]Ask for healing[e]
[uf 0 5 65278][uf 2 1]Talk[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_NPC_ELIZ_DATE_START [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]My...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]I've been waiting for you to ask. Shall we be on our way?[n][uf 1 1][e]

[msg MSG_NPC_ELIZ_DATE_NG_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 202 0]I'm terribly sorry, but... I would much rather you extend an invitation during the day.[n][uf 1 1][e]

[msg MSG_NPC_ELIZ_DATE_NG_2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 202 0]I'm terribly sorry... but I'm afraid it will have to wait for another day.[n][uf 1 1][e]

[msg MND_NPC_ELIZ_DATE_NG_2]
[uf 0 5 65278][uf 2 1]She turned down my invitation...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should just focus on[n]other requests for now.[n][uf 1 1][e]

[msg MSG_NPC_ELIZ_DATE_NG_3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]I'm taking our next destination into great consideration. Please wait awhile until I've made up my mind.[n][uf 1 1][e]

[msg MND_NPC_ELIZ_DATE_NG_3]
[uf 0 5 65278][uf 2 1]Elizabeth is figuring out where to go next...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe if I fulfill more of her requests,[n]I'll be able to invite her out...[n][uf 1 1][e]

[msg MSG_NPC_ELIZ_DATE_NG_4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]From what I've gathered, I believe your school is having a "holiday," correct?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I wish to experience the average student's daily routine... Could you invite me on a regular school day?[n][uf 1 1][e]

[msg MSG_NPC_ELIZ_DATE_NG_ALL [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 202 0]I... can't do that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]As I've told you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]It is my utmost priority to fulfill my duty.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_1_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]A moment if you will? There is something I must inform you of.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Whenever you complete one of my many requests, I become ever curiouser about this world...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]And now an urge to investigate this place for myself has arisen within me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Therefore, I would like to request that you escort me to various locations.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]First, I would like you to guide me through the Paulownia Mall here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]If you have the time, then please come fetch me so long as the sun is out.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_1_2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]I've been waiting for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Regarding my request to have you escort me to various locations in this world...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I would like you to show me around this Paulownia Mall first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]If you have the time, then please come fetch me so long as the sun is out.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_1_3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]A moment if you will? There is something I must inform you of.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Thus far, you have completed a number of my requests...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]And, just as I had thought, this world truly is interesting... So much so that an urge to investigate it myself has risen within me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Therefore, I would like to request that you escort me to various locations.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]Please come to Paulownia Mall at a later date. I will give you more details then.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]May I have a moment of your time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I humbly request that you escort me somewhere once again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This time, I would like to investigate a certain area known as Iwatodai.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]If you have the time, then please come fetch me so long as the sun is out.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]May I have a moment of your time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Do you mind... escorting me yet again?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This time, I would like to go to a location known as Naganaki Shrine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]If you have the time, then please come fetch me so long as the sun is out.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]May I have a moment of your time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I apologize if this is becoming repetitive, but... I'd like to ask you to escort me once more.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This time, could you take me to this Gekkoukan High School you attend?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]If you have the time after school, please come by and let me know.[n][uf 1 1][e]

[msg MSG_ELIZ_DATE_OPEN_5 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13201 202 0]May I have a moment of your time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]There is yet another location I would like to visit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]Would it be all right if, um... well, if you could invite me to your room?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]...I'll be waiting for you here.[n][uf 1 1][e]

[msg MSG_GIFT_RAREMEDAL_01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]It's as if your presence emanates a far brighter radiance than before. Perhaps all your hard work is starting to show.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Here. It may not be much, but this is my gift to you. Please accept it.[n][uf 1 1][e]

[msg MSG_GIFT_RAREMEDAL_02 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]I can sense that the power growing within you stems from the bonds you have forged and nurtured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Here. It may not be much, but this is my gift to you. Please accept it.[n][uf 1 1][e]

[msg MSG_GIFT_RAREMEDAL_03 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]Even in the face of tremendous hardship, you continue to make great progress nonetheless.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This is less of a reward and more of a gift from me to you. Please, take it.[n][uf 1 1][e]

[msg MSG_GIFT_RAREMEDAL_04 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]I still cannot foresee the limits of your potential... I look forward to witnessing you grow even further.[n][uf 1 1][e]

[msg MSG_MISSING_INFO_01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13236 202 0]...I sense someone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]There seems to be a human presence within Tartarus between floors [uf 2 4 0] and [uf 2 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It would be best for you to search the tower and locate them as soon as possible.[n][uf 1 1][e]

[msg MSG_MISSING_INFO_02 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 202 0]I see that you have rescued those who were trapped inside Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]You may now rest easy... I no longer sense anyone within that tower.[n][uf 1 1][e]

[msg MSG_MISSING_INFO_03 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]...It seems a little guest was feline curious and mew-andered their way to floor [uf 2 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Do keep that in mind as you explore.[n][uf 1 1][e]

[msg MSG_MISSING_INFO_04 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]I don't sense any lost persons within Tartarus at this moment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]However... it appears a little guest was feline curious enough to mew-ander inside.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]They should be somewhere around floor [uf 2 4 2]. Perhaps you should go find them.[n][uf 1 1][e]

[msg MSG_INFO_LAST_DAY_HEAL [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]At long last... you will soon arrive at the top of this tower to overcome its challenges.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I will do everything in my power to assist you up to the very end so that you may grasp victory.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Please come see me if you feel your strength waning. I shall heal you.[n][uf 1 1][e]

[msg MSG_LAST_DAY_HEAL_01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]Very well.[n][uf 1 1][e]

[msg SYS_LAST_DAY_HEAL]
[uf 0 5 65278][uf 2 1]Everyone's HP and SP recovered![n][uf 1 1][e]

[msg MSG_ELIZ_TALK_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 202 0]I see you are here to challenge the Abyss of Time. Make sure you prepare appropriately...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Should you have any business related to Personas, please visit the Velvet Room.[n][uf 1 1][e]

[msg MSG_ELIZ_TALK_01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 202 0]If you have any business related to Personas, please visit the Velvet Room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]However, you may speak with me about my personal requests here.[n][uf 1 1][e]

[msg MSG_ELIZ_TALK_02 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]I will add new requests periodically. You can expect new ones about once a month.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Some, however, may only become available upon completion of other requests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Also, do pay attention to the "number" of the request.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13232 202 0]If there is a number missing, then there may be a request that is still hidden.[n][uf 1 1][e]

[msg MSG_ELIZ_TALK_03 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]As my master has said, deepening your bonds will bolster the strength of your Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I hope you enjoy a fulfilling life, one where you forge many meaningful relationships.[n][uf 1 1][e]

[msg MSG_ELIZ_TALK_04 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 202 0]The time has finally come.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If you are in need of assistance, please let me know... for I intend to aid you to the very end.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Oh my...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Hehe... That is quite impressive.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]My, my... I see you have acquired a [uf 0 1 35]Jack Frost[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This adorable, round figure, this mischievous countenance that makes it impossible to discern his thoughts...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]He is true perfection.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Oh, and when paired with [uf 0 1 35]Jack-o'-Lantern[uf 0 1 27], they put on quite a hysterical performance. Why, it may just knock you off your feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If you haven't seen it yet, I highly recommend you do so.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_02 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]My, my...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]Your [uf 0 1 35]Jack Frost[uf 0 1 27]... has reached level 99.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]I can't believe my eyes... To think you could even make this happen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]You must have undergone incredible hardship to have him obtain such astounding power...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 202 0]Oh, how magnificent... Please, allow me to give you my sincerest praise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]On top of his adorableness, he now has unparalleled strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]He has truly become an unstoppable force.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]...Weak to fire, you say? Well, that only makes him even more charming.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_03 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]Hm, that Persona of yours... Orpheus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A being that was birthed only after forging a number of powerful bonds...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I sense unfathomable strength and unrivaled potential dwelling within.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]I can hardly contain myself at the prospect of further growth...[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_04 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_05 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]I wonder. When will the wish I made at the fountain be granted?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]I have yet to receive any confirmation or even a progress report...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13227 202 0]...Perhaps I should have tossed in more coins.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I suppose I'll double the amount to 2,000,000 yen next time.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_06 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]I thank you for allowing me to try so many delicacies the other day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]They were all so very delectable, especially that takoyaki... It has become a new favorite of mine, one that can rival kinako.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 2 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]My interest in culinary delights has been piqued since then. However, my current position poses a bit of an obstacle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]After much consideration, I have decided to increase the number of food-related requests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]I am very much looking forward to seeing them fulfilled.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_07 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]I attempted to negotiate terms for incorporating playground equipment in the Velvet Room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 202 0]Unfortunately, my proposition was denied. How disappointing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 2 65535 65535 0 0]If I cannot obtain permission, then all that remains is to exploit my master's absence.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13225 202 0]Victory shall be mine... Please await the good news.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_08_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Oh, yes... I've heard that this "high school" of yours holds festivals from time to time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]This particular "culture festival" seems to be a very exciting occasion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]Moreover, I hear that it could trigger distortions in the space-time continuum, transporting you back to the "teenage years."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Unfortunately, I was unable to observe this phenomenon during my visit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]But if the opportunity arises, I would very much like to partake in this festival with you one day.[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_08 top]
[uf 0 5 65278][uf 2 1]未使用[e]

[msg MSG_ELIZ_UNIQUE_TALK_08__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_09 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Thank you... For the other day, that is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]About what happened in your room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 1 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 1 0]A-Ahem... Pardon me, but the memory is still... ah, quite vivid.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 1 0]I'd greatly appreciate it if you could keep what happened a secret... Especially from my master.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_10_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]Oh? Your aura seems very different from usual... Did something happen?[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_10 top]
[uf 0 5 65278][uf 2 1]I went to the beach.[e]
[uf 0 5 65278][uf 2 1]It's a secret.[e]

[msg MSG_ELIZ_UNIQUE_TALK_10__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Ah... The beach.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Perhaps I am picking up the ocean's scent lingering on you.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_10__3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13214 202 0]Oh, how disappointing. I don't mean to pry, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Did you have what they call a "once in a lifetime experience"? I hear they tend to occur during summertime.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_10__4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]Regardless, I'm glad you were able to enjoy yourself.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_11_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]I noticed that you were absent for some time. Did you take a trip somewhere?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Ah, a school trip... Where one embarks on a journey to better refine your body and soul.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]Then you must have overcome the final examination. You were once a student, but now you have become the master.[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_11 top]
[uf 0 5 65278][uf 2 1]It was just a trip.[e]
[uf 0 5 65278][uf 2 1]That's not really a thing.[e]

[msg MSG_ELIZ_UNIQUE_TALK_11__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13214 202 0]Oh, is that so? My apologies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]Regardless, all that matters is that it was a good experience for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]...Hm? Is something the matter? You look rather morose.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_12 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 202 0]Oh my... It looks as though you've forged a new bond, one that is far stronger and different from the others.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]And the bond you share will deepen even further, entwining their fate with yours...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]I must admit, I'm a little envious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 202 0]Oh, my apologies. Please, hold on tightly to that bond... That very precious, very special bond.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_13_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]

[sel SEl_ELIZ_UNIQUE_TALK_13 top]
[uf 0 5 65278][uf 2 1]What's the matter?[e]
[uf 0 5 65278][uf 2 1]You look a little down.[e]

[msg MSG_ELIZ_UNIQUE_TALK_13__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13226 202 0]My apologies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]Ever since that bout with you, it seems I've been getting lost in my own thoughts more often...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]But you needn't worry about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]I believe... it is something that I will be able to overcome.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_14_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]The time has finally come.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It seems you have a special strength that allows you to overcome any obstacle that stands in your way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Though your story may end in tragedy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I can say, with confidence, you will persevere for the best possible outcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]...May the goddess of fortune smile upon you.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_14__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I truly believe that there is no hardship you cannot conquer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]...May the goddess of fortune smile upon you.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_15 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]Hm... It appears you have grown spectacularly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I believe you will now be able to wield a veritable plethora of Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]But in regard to your potential, this is only the beginning of what you can achieve...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13230 202 0]Hone your Personas, and reach for even greater heights...[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_16 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]My... It appears you have undergone significant growth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]One could say this is the culmination of your ability to attract others.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]Perhaps you may now be able to forge bonds with anyone with ease.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_17 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]...And with that, all requests have been marked completed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Which means you will not receive any more requests from me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]To think this day would come... It's quite moving, really.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I know I may have had some rather unreasonable requests, but you've performed so splendidly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Allow me to give you my formal thanks.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_18_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]Oh, is that perhaps...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]May I take a look at that brooch you have there?[n][uf 1 1][e]

[msg MND_ELIZ_UNIQUE_TALK_18_ [Elizabeth]]
[uf 0 5 65278][uf 2 1]I gave my [uf 4 4 1 37 1 0] to Elizabeth.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_18__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]What intricate craftsmanship... And with platinum, no less![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]To tell you the truth, I absolutely adore things made of platinum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]How exquisite... I had no idea such masterful creations are purchasable in your world.[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_18 top]
[uf 0 5 65278][uf 2 1]You want it?[e]
[uf 0 5 65278][uf 2 1]I'd like you to have it.[e]

[msg MSG_ELIZ_UNIQUE_TALK_18__3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Oh, may I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 1 0]...Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 1 0]Though this is not exactly a request, allow me to bestow upon you a reward nonetheless.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_18__4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 202 0]I will treasure this, always.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_19_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 202 0]Oh my, what do you have there? It looks like a doll of sorts.[n][uf 1 1][e]

[msg MND_ELIZ_UNIQUE_TALK_19_ [Elizabeth]]
[uf 0 5 65278][uf 2 1]I showed the [uf 4 4 1 37 1 0] to Elizabeth.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_19__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13214 202 0]So... this is called the "Goggle-Eyed Idol"?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It appears to be quite old... And I see the craftsman put a great amount of effort into the details.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]Come to think of it... does it not remind you of a certain Persona?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13224 202 0]Hm... Perhaps that's why it caught my attention in the first place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Thank you for letting me study it. You may have this back now.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20_ [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]For some inexplicable reason... I have a sudden urge to, as you humans say, "accessorize."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]Perhaps this is the perfect opportunity to don those items you have brought me...[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Do you have any requests?[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_20_ top]
[uf 0 5 65278][uf 2 1]Designer Glasses[e]
[uf 0 5 65278][uf 2 1]Cat Ears[e]
[uf 0 5 65278][uf 2 1]Gag Glasses[e]
[uf 0 5 65278][uf 2 1]Santa Hat[e]

[msg MSG_ELIZ_UNIQUE_TALK_20__3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13235 202 0]Then without further ado...[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 901 65535 0 0]What do you think?[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__5 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 902 65535 0 0]What do you think?[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__6 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 903 65535 0 0]What do you think?[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__7 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 904 65535 0 0]What do you think?[n][uf 1 1][e]

[sel SEL_ELIZ_UNIQUE_TALK_20__2 top]
[uf 0 5 65278][uf 2 1]Lookin' cool.[e]
[uf 0 5 65278][uf 2 1]Make it part of your look.[e]

[msg MSG_ELIZ_UNIQUE_TALK_20__8 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 901 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Why, thank you. I look quite stunning, if I do say so myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 901 65535 0 0]Nothing raises the spirits more than adorning oneself with a little embellishment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 901 65535 0 0]Ah, but I mustn't get too carried away and forget my duties. That's enough distraction for today.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__9 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 902 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Why, mew-ci beaucoup— Ahem... I mean to say, thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 902 65535 0 0]Wearing these really does make you feel as if you are slowly transforming into a cat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 902 65535 0 0]But that's enough of that for now. I wouldn't really want to become a cat, after all.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__10 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 903 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Thank you— Achoo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 903 65535 0 0]...My apologies. I'm still getting used to how itchy this mustache is, you see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 903 65535 0 0]But that has certainly satisfied my urge, so that's enough dress-up for today.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__11 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 904 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Why, thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 904 65535 0 0]Wearing this hat has put me in a rather festive mood. The impulse to pass out presents is strong...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 904 65535 0 0]Unfortunately, I have nothing to give at the moment. Perhaps another time.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__12 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 901 65535 0 0][uf 3 1 3 0 65535 13220 202 0]I don't deny that such urges do arise within me from time to time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 901 65535 0 0]However, my duty is to serve my master. I do not wish to cause trouble for him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 901 65535 0 0]Therefore... I believe that is enough distraction for today.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__13 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 902 65535 0 0][uf 3 1 3 0 65535 13220 202 0]Perhaps if my situation allowed it, I would have loved to do so.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 902 65535 0 0]Alas, wearing this enables me to metamorphose into a cat in both mind and body...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 902 65535 0 0]In order to fulfill my duties, I must refrain from wearing this on a regular basis...[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__14 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 2 903 65535 0 0][uf 3 1 3 0 65535 13220 202 0]I don't deny that such urges do arise within me from time to time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 903 65535 0 0]However, wearing these causes my nose to itch quite a bit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 903 65535 0 0]I fear it would interfere with my duties. I will have to save it for a special occasion.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__15 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 904 65535 0 0][uf 3 1 3 0 65535 13220 202 0]Perhaps if my situation allowed it, I would have loved to do so.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 904 65535 0 0]However, wearing this makes it difficult for me to suppress the impulse of giving out presents...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 904 65535 0 0]But, in order to fulfill my duties, I will wear this whenever you desire.[n][uf 1 1][e]

[msg MSG_ELIZ_UNIQUE_TALK_20__16 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]Thank you for indulging me.[n][uf 1 1][e]

[msg MSG_SUBMIT_DRINK_QUERY_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Were you able to gather beverages sold in the vending machines?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13231 202 0]I see... Of the different drinks available, you've managed to gather [uf 2 4 0]. Would you be able to collect [uf 2 4 1] more?[n][uf 1 1][e]

[msg MSG_SUBMIT_DRINK_QUERY_2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]It appears you've gathered all the different drinks. May I collect them from you now?[n][uf 1 1][e]

[sel SEL_SUBMIT_DRINK_2 top]
[uf 0 5 65278][uf 2 1]Hand over the drinks[e]
[uf 0 5 65278][uf 2 1]No[e]

[msg MSG_SUBMIT_DRINK_END_CAN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]I see. How disappointing. Perhaps some other time then.[n][uf 1 1][e]

[msg MSG_SUBMIT_DRINK_COMPLET [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Oh my... There are this many!? It'd be such a waste to simply drink them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Perhaps tonight I will hold the ritual known as the "after-work drink" performed by laborers...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]In any case, the request is now completed. Please take this as your reward.[n][uf 1 1][e]

[msg MSG_SUBMIT_ITEM_IMO_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 202 0]I sense an unusual power emanating from you. Do you perhaps have one of the potatoes you have grown?[n][uf 1 1][e]

[sel SEL_SUBMIT_ITEM_IMO_2 top]
[uf 0 5 65278][uf 2 1]Tarukaja Potato[e]
[uf 0 5 65278][uf 2 1]Sukukaja Potato[e]
[uf 0 5 65278][uf 2 1]Rakukaja Potato[e]
[uf 0 5 65278][uf 2 1]Matarukaja Potato[e]
[uf 0 5 65278][uf 2 1]Heat Riser Potato[e]
[uf 0 5 65278][uf 2 1]Don't give her a potato[e]

[msg MSG_SUBMIT_ITEM_IMO_3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]What a truly bizarre potato... I can sense an unusual power radiating from it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13228 202 0]I imagine it would make a rather a-peeling meal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]...Hm? Why are you giving me such a strange look?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 202 0]In any case, the request is now completed. Please take this as your reward.[n][uf 1 1][e]

[msg MSG_SUBMIT_ITEM_IMO_4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]I see. How disappointing. Perhaps some other time then.[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 202 0]Hm? It appears you have what I believe to be a "home-cooked meal"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]What would you like to give me?[n][uf 1 1][e]

[sel SEL_SUBMIT_DISH top]
[uf 0 5 65278][uf 2 1]Chicken Sauté[e]
[uf 0 5 65278][uf 2 1]Cabbage Cream Stew[e]
[uf 0 5 65278][uf 2 1]Iron-Athlete Meal[e]
[uf 0 5 65278][uf 2 1]Super-Athlete Meal[e]
[uf 0 5 65278][uf 2 1]Okay Coffee[e]
[uf 0 5 65278][uf 2 1]Excellent Coffee[e]
[uf 0 5 65278][uf 2 1]Luxe Night Tea[e]
[uf 0 5 65278][uf 2 1]Karume-yaki[e]
[uf 0 5 65278][uf 2 1]Exquisite Katsudon[e]
[uf 0 5 65278][uf 2 1]Ultimate Tempura[e]
[uf 0 5 65278][uf 2 1]Decadent Tea[e]
[uf 0 5 65278][uf 2 1]Nothing[e]

[msg MSG_SUBMIT_DISH_REPLY_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Oh? I believe this is the first time I've ever had this, yet this flavor tastes rather... nostalgic.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]...I see. So this is what a "home-cooked meal" is.[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_REPLY_2 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 202 0]Though simple and rustic in presentation, you can tell it was made with care.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This thoughtfulness must be an important element in what makes a dish truly "home-cooked"...[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_REPLY_3 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]The concept of "home" itself evokes a feeling of warmth and comfort—allegedly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Though this coffee has a bitter taste, its warmth exudes a sort of comforting feeling as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]In other words, something that's been "home-cooked" can be... soothing to the soul.[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_REPLY_4 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 202 0]Ah, so this is what "home cooking" tastes like...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]An elegant, rich flavor. One with a luxurious mouthfeel.[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_REPLY_5 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13222 202 0]Oh my! A presentation that showcases both the charm and appeal of the dish...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]An innovative combination of flavor profiles that deceives one's mind into savoring this taste for all eternity...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13212 202 0]Oh, how divine, absolutely divine! I never would have thought food could stir one's emotions...[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_END [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I believe I now understand why people crave the taste of home cooking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 202 0]Thank you very much for sharing this culinary delight. Please take this as your reward.[n][uf 1 1][e]

[msg MSG_SUBMIT_DISH_CANCEL [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 202 0]I see. How disappointing. Perhaps some other time then.[n][uf 1 1][e]

[msg MSG_REQ_HELP_030_1 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Oh? Is something the matter?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13214 202 0]Ah, I see... So there are people in your world who seek these materials.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]This [uf 4 4 1 37 1 0] you seek can be found in the second block of Tartarus, Arqa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I've heard the [uf 0 1 2]Lustful Snakes[uf 0 1 27] that appear in the latter half of the block are quite fond of collecting them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 202 0]A material that captivates both Shadows and humans... How remarkably peculiar.[n][uf 1 1][e]

[msg MSG_123_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Deepening your bonds will bolster the strength of your Personas. Do try and forge as many connections as...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13226 0 0]Oh, my apologies. I got rather caught up in the motions. Force of habit, I suppose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Considering that you've already forged such tightly-knit bonds with your comrades, I implore you to mind my master's words:[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]"Strength of heart, when united, is barred by no door."[n][uf 1 1][e]

[msg MSG_124_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0]Please bear in mind that the current selection of requests is not all of them. I shall be adding more in the future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Oh, but hm... The concept of time holds no meaning here. Very well then, I'll simply add more at my own pace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Note that some may only become available upon completing other requests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Should there be a number missing, then please assume that there may be a hidden request.[n][uf 1 1][e]

[msg MSG_125_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]No matter how long or hard I mull it over... I'm afraid the solution still deludes me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]No, not "deludes." Perhaps, it illudes me? Or is it "alludes"...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 0 0]...My, the word simply escapes me.[n][uf 1 1][e]

[msg MSG_126_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 0 0]By the way... It appears that your companions have regained the power they once possessed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]By searching within oneself, bonds are forged, strengthened... and can even become a source of power.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 0 0]How fascinating, indeed. You have my gratitude for sharing such a revelation.[n][uf 1 1][e]

[msg MSG_127_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]Do you possess the power to overcome any adversity as well? Just as he did...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It seems all I can do is watch over you from here, so please... Do journey with caution.[n][uf 1 1][e]

[msg MSG_128_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]What power will you exhibit? What path will you choose?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]And how does it all relate to me? I admit, I'm rather looking forward to the answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13230 0 0]I sincerely wish you the best on your journey.[n][uf 1 1][e]

[msg MSG_129_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Hm... It appears you have grown spectacularly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I believe you will now be able to wield a veritable plethora of Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13212 0 0]You have made splendid progress, in fact. Perhaps you may even—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13226 0 0]...Oh, my apologies. I seem to have gotten a bit lost in thought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Well... In any case, I commend your efforts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Continue to hone your Personas, and reach for even greater heights...[n][uf 1 1][e]

[msg MSG_130_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 0 0]I must say... What curious scenery. There truly is nothing but sand as far as the eye can see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I've heard that some people even spend their days in such an environment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]What sort of lives do they lead, I wonder? I would love to witness it myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]No doubt their lifestyle must be drastically different from those I've observed at Paulownia Mall...[n][uf 1 1][e]

[msg MSG_131_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13215 0 0]Endless sand... Sand... at the beach.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Were there a large body of water here, could it be considered an ocean?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]...Never mind me. I doubt I'm capable of recreating an exhilarating summertime romance solely by myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]So please, forget I said anything.[n][uf 1 1][e]

[msg MSG_132_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I have been tallying the number of Shadows you've defeated up to this point, naturally.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13228 0 0]Indeed I have—undeniably, irrefutably, and indubitably so. You can trust in my impeccable record-keeping prowess.[n][uf 1 1][e]

[msg MSG_133_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]When exactly did that door appear here...? Why, it must possess exceptional skill to have escaped my notice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]That which exists beyond the threshold overflows with danger... Does it stir the challenger's spirit within you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If you dare explore its depths, I only pray that you are adequately prepared.[n][uf 1 1][e]

[msg MSG_134_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0]I couldn't help but notice your attire...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Ah, I see. So that was a possibility—should the need arise...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13218 0 0]Hehe, pay me no mind. The look suits you.[n][uf 1 1][e]

[msg MSG_135_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]So, after passing through that door, you met with someone who could use a Persona?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Intriguing... So that sort of thing may transpire in this place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Perhaps nothing is truly beyond the realm of possibility here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 0 0]Just as how you've encountered that mysterious figure time and again throughout your long, perilous journey...[n][uf 1 1][e]

[msg MSG_136_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]When the time is right, could I perhaps ask you to—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 0 0]No, that'd be wrong of me. This matter seems to be weighing more heavily on my mind than ever before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]My apologies. Please allow me to continue watching over you.[n][uf 1 1][e]

[msg MSG_137_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]Now that you've demonstrated your power and showed me your potential...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I confess, I may have been somewhat stubborn. Such hardheaded behavior is almost laughable in hindsight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 3 0 65535 13218 0 0]Hehe, not that I'm opposed to having a hard head. In fact, I rather like how powerful it sounds.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]Consider this: what would happen should I butt my head into my master's nose...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Unfortunately, I'm afraid the answer will have to wait. My attention is currently occupied by another matter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]And to that end, I shall continue to watch over you and your journey.[n][uf 1 1][e]

[msg MSG_146_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If you have any business related to Personas, please visit the Velvet Room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13211 0 0]My personal requests... seem to have all been fulfilled already. Thank you for your hard work.[n][uf 1 1][e]

[msg MSG_138_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13222 0 0]Completing tasks evokes a feeling of satisfaction. I presume you experience the same sensation as well?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]...Perhaps being driven by emotions is not such a terrible thing after all.[n][uf 1 1][e]

[msg MSG_139_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Despite having completed my every request... you still wish to speak with me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]Hehe. My, what an honor. Then shall I regale you with tales of my master's strange habits?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]...Though perhaps I ought to save them for another time.[n][uf 1 1][e]

[msg MSG_140_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]You wish to talk?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 0 0]Apologies. It seems my mind immediately went blank...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]...Though I'm not clear as to why.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]

[msg MSG_141_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]You wish to talk?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It feels as though my mind is stuck on a loading screen. I can't seem to think of anything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 3 0 65535 13220 0 0]...What a tragic state of affairs.[n][uf 1 1][e]

[msg MSG_142_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13223 0 0]One thing I've learned about myself is that I seem to get lost in my thoughts more often as of late...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]This is the first time I've ever encountered such a problem.[n][uf 1 1][e]

[msg MSG_143_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13208 0 0]While it's true I've had a lot on my mind, were you to ask me why, I couldn't give you a proper answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 4 25 202]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0]Am I... bedazzled?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0]Or perhaps... bifurcated?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Well, whatever I may be, the answer is likely to be of little to no significance... I hope.[n][uf 1 1][e]

[msg MSG_144_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0]Truth be told, I am quite fond of singing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It is the perfect means of expression, one that allows me to give form to the fire within my being.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]And yes, I delight in the art of wordplay as well, hehe.[n][uf 1 1][e]

[msg MSG_145_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13218 0 0]You are not human. The two of us are similar in that respect... As such, I shall be watching over you with great interest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I wish you the best of luck.[n][uf 1 1][e]

