[msg MSG_096_0_0]
[uf 0 5 65278][uf 2 1][uf 4 17 2 4 1][e]

[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 1 0 0]What's going on!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0][uf 3 1 1 0 0 2 0 0]The hell're these cracks in the floor!?[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 3 0 0]This is bad... It's becoming unstable...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 4 0 0]We still have time, but not much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 5 0 0]If these fissures reach the door, we might not be able to leave even with the keys...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Tch... It's just one thing after another, isn't it?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 7 0 0]So, uh... Guess we gotta decide what to do with these keys, huh?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Um, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 10 0 0]I want to stay in the present. I think that's what he would've wanted, too.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]"What he would've wanted," huh...?[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 12 0 0]I've been thinking... He died so suddenly, and they never even figured out the cause.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]I get the feeling that he... He must've given his life to make some kind of miracle happen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 14 0 0]He thought about it, weighed his options... and ultimately chose to leave this world to us.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]"Died"...? "Miracle"...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 16 0 0]That's why... personally... I don't want to just undo his decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 17 0 0]I want to... respect his sacrifice.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Oh, Amada-kun...[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]I'm with Amada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]We all saw the resolve it takes to face death head-on and accept it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]That resolve, and what it brought about...[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Even if it hurts, we have to accept it too. That's how we honor his memory.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Yukari, what about you?[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 24 0 0]You're all about the here and now, right, Yuka-tan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]"You gotta look forward!" That's practically your motto, ain't it?[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]I...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 27 0 0]I... want to go back.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Yeah, I always tell myself to look forward and let go of the past.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 29 0 0]But... This is different. We might be able to change something... We can't pass that up![n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Yukari...[n][uf 1 1][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 31 0 0]So you'd take away his choice for your own?[n][uf 1 1][e]

[msg MSG_020_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 17 2 2 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 32 0 0]That's not what I said![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 33 0 0]We can actually change the past! What's wrong with wanting that!?[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Then let me ask you... If you prevented your father's death, what would happen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 35 0 0]The people you've met, what you've gone through with them... It'd all be gone. And you wouldn't be the person you are now.[n][uf 1 1][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 1 0 0 36 0 0]It's the same for Shinji and Miki... I wouldn't erase their deaths either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 1 0 0 37 0 0]Every single thing about my past is important... Because it all shaped who I am.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 38 0 0]But that's not even—![n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 39 0 0]Guys, guys! Let's all take it down a notch, okay?[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 40 0 0]"Take it down a notch"? Are you kidding!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 41 0 0]If anything, we're not taking this seriously enough! We can save him from dying![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 42 0 0]Don't you want to bring him back!?[n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 43 0 0]Of course I want him back![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 44 0 0]But is yellin' at each other like this really gonna solve anything!?[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 45 0 0]And think about it... If we go back, we'd have to face Nyx again.[n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 46 0 0]What, so you're just afraid to fight?[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 47 0 0]No! I'm... Well... I am, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 48 0 0]Aghh... I don't know what I'm trying to say, but everyone needs to calm down, alright!?[n][uf 1 1][e]

[msg MSG_031_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 49 0 0]Aigis-san, how do you think we should use the keys?[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 50 0 0]I, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 51 0 0]The past or the present...? I'm just not sure.[n][uf 1 1][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 52 0 0]You seriously won't make a choice?[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 53 0 0]The day we said our goodbyes, you were the only one who didn't show up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 54 0 0]You got to hear his last words, and now you even have his power...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 55 0 0]But you still don't know how you feel about him?[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 56 0 0]Listen... I know it hurts, believe me. It hurts so much, I can't stand it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 57 0 0]But...[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 58 0 0]Yukari-san, I...[n][uf 1 1][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 1 0 0 59 0 0]...Forget it. Nothing I say will make a difference anyway.[n][uf 1 1][e]

[msg MSG_037_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 60 0 0]Metis, does everyone have to agree for the keys to combine?[n][uf 1 1][e]

[msg MSG_038_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 61 0 0]Not necessarily. The keys themselves don't have opinions.[n][uf 1 1][e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 62 0 0]So, in other words, it's possible to take them by force and combine them.[n][uf 1 1][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 63 0 0]"By force"...? Are you saying you want to fight!?[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 64 0 0]I don't want to. But if we can't agree, we don't have a choice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 65 0 0]We're running out of time, and talking hasn't gotten us anywhere.[n][uf 1 1][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 66 0 0]You have a point...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 67 0 0]This matter concerns the life of a dear friend. I doubt any of us will be easily swayed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 68 0 0]So in that case...[n][uf 1 1][e]

[msg MSG_043_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 69 0 0]Wait, Kirijo-senpai...?[n][uf 1 1][e]

[msg MSG_044_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 70 0 0]I had already made my decision—I will stand with Yukari.[n][uf 1 1][e]

[msg MSG_045_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 71 0 0]Senpai...[n][uf 1 1][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 72 0 0]You're siding with Takeba? Are you sure?[n][uf 1 1][e]

[msg MSG_047_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 73 0 0]All right. I guess you've got your reasons and I've got mine.[n][uf 1 1][e]

[msg MSG_048_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 74 0 0]Well, I'm sticking with my sister! I'll protect her no matter what![n][uf 1 1][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 75 0 0]That makes sense, Metis. You know what's important to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 76 0 0]So you understand why I can't back down either, right?[n][uf 1 1][e]

[msg MSG_050_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 77 0 0]Yes.[n][uf 1 1][e]

[msg MSG_051_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 78 0 0]Everyone, wait! Don't do this![n][uf 1 1][e]

[msg MSG_052_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 79 0 0]I made my feelings clear. Now you— No...[n][uf 1 1][e]

[msg MSG_053_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 80 0 0]Now everyone needs to recognize their own feelings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 81 0 0]Think about who he was and what he meant to us...[n][uf 1 1][e]

[msg MSG_054_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 82 0 0]We'll need a proper venue for the battles. A place where the results will be absolute...[n][uf 1 1][e]

[msg MSG_055_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 83 0 0]I'll show you the way. Let me know when you're ready.[n][uf 1 1][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 84 0 0]We're really... going to fight each other...?[n][uf 1 1][e]

[msg MND_057_0_0]
[uf 0 5 65278][uf 2 1]My friends are irreconcilably divided...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]What decision will I come to myself...?[n][uf 1 1][e]

