[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5100 0 0]What...? That shadowy figure again...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Wait, no... This is something else. I've never sensed anything like it before![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]I doubt it's just a regular Shadow, so if you decide to track it down, please be careful.[n][uf 1 1][e]

