[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]That reminds me. I was reading this book during class once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]One of our classmates saw and said to me, "Wow, I'm surprised. So, you're the type to talk with your fists."[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 21 7 4]What exactly do I look like to everyone else?[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]A normal high school student.[e]
[uf 0 5 65278][uf 2 1]Don't worry about that too much.[e]
[uf 0 5 65278][uf 2 1]A cute girl.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]That must mean that I don't appear to be strong in other people's eyes.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]No, it's important that I consider this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]He was surprised. That can only mean one thing...[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 21 7 4]"Cute"...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]From what I understand, that term is used to describe small animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Are you saying that I'm also being placed into that category?[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 7 0 25 25]I am an anti-Shadow weapon, but I don't seem to be regarded as such...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I must correct this problem at once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]If it is not addressed, it could negatively impact my ability to carry out my duties.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Once I finish reading, I will start thinking of a solution.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]During combat, the mental states of both sides play a significant role in the outcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I want my presence to strike fear in the hearts of my enemies, but galvanize my allies, as well.[n][uf 1 1][e]

[msg MSG_032_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]What can I do to convey that kind of impression?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Ideally, it would be something to encourage people to depend on me...[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Maybe I can find some tips in this book...[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 5 13 22 1 7]I think this is enough reading for now. We should return to our rooms.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]That reminds me. I was reading this book during class once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]And one of our classmates said to me, "Wow, I'm surprised. So you're the type to talk with your fists."[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 21 7 4]What exactly do I look like to everyone else?[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]A normal high school student.[e]
[uf 0 5 65278][uf 2 1]Don't worry about that too much.[e]
[uf 0 5 65278][uf 2 1]A cute girl.[e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 7 3 25 25]...I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 0 25 25]That must mean that I don't look strong in other people's eyes.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 7 1 25 25]...Thank you. I know you're just being considerate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 7 3 25 25]But still, I can't help but feel bothered by it...[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]"Cute"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 3 25 25]I know this is supposed to be a compliment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]But if that's how they see me, it can only mean one thing...[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 7 3 25 25]I'm an anti-Shadow weapon, but most people don't see me as one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 7 0 25 25]Isn't this a critical issue?[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]...Once I finish reading, I'll need to think of a solution.[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]During combat, the mental states of both sides play a significant role in the outcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]I want to be able to intimidate my enemies, but also encourage my teammates.[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]What can I do to give everyone that kind of impression?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Ideally, it would be something that makes me appear reliable in battle...[n][uf 1 1][e]

[msg MSG_135_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 7 3 25 25]Maybe I can find some tips in this book...[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 23 0 7 1 25 25][uf 5 13 22 1 7]I think that's enough for today. Good night.[n][uf 1 1][e]

