[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 1 0 0]How very puzzling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 2 0 0]The plants seem much livelier than they did when we started.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 3 0 0]Do you suppose... they're happy that you are tending to them?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinating... There's no data on this, but it seems like you understand them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 5 0 0]Hello, plants. I will be tending to you as well this time. Don't worry, I'll make sure to decrease my pressure output.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]But if anything starts hurting, just raise your left hand... Or rather, your left leaf.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]That is what I thought, as well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]However, some reports suggest that plants grow better when you speak to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 9 0 0]Could it be that they have some sort of ability that we aren't yet aware of?[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Good idea. I'll give it a try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 11 0 0]Hello, hello. This is Aigis. If you can hear me, plants, then please respond.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 13 0 0]Unfortunately, there was no answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 14 0 0]Communication will be difficult with my current abilities. This is something to consider for the future.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 15 0 0]I had some prior knowledge of "plants," but this was my first time observing them directly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 16 0 0]These little seeds and buds in the earth can morph and change so quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 17 0 0]Is this proof that they are living as well? How fascinating.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 18 0 0]I would like to watch these plants grow and document this experience for my records.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]I will tend to them with my full power![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 20 0 0]This took more time than I'd anticipated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 21 0 0]I will need to run more simulations to ensure there are no delays next time.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 22 0 0]It's gotten late. We should head back now.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 23 0 0]I've been wondering...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 24 0 0]The plants look much livelier now compared to before they were tended to.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Do you think... they're happy you're taking care of them, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]It's possible.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Yes, you handle them so delicately, it's clear that you care about them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm sure the plants know how much work you're putting in for them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 28 0 0]I'll do the best I can to make them happy too![n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]I agree... But that's why I find it so strange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 30 0 0]They say talking to plants can help them grow, don't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 31 0 0]Do you think... maybe these plants have a heart as well, but we just aren't aware of it?[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]...It would be nice if that were possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 33 0 0]I wonder... Maybe these plants have a heart as well, but we just aren't aware of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 34 0 0]If we keep tending to them, will we understand them better?[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Looking at them like this really makes me think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 36 0 0]These plants are just like you and the others. They're living, too...[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 37 0 0]I want to see them grow with my own eyes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]So I'm going to do everything in my power to care for them.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]I'm sorry. This was my first time doing this, so I think I slowed you down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]I'll keep training in my room so that I can work faster next time.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 41 0 0]Thank you for your help. We should head back now.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 42 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 43 0 0]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 45 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 46 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 47 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 48 0 0]This must be the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 49 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 50 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 51 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 52 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 53 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 54 0 0]I will move it to another leaf then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 56 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 57 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 58 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 59 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 61 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 62 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 63 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Status reads all green. No problems to report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 65 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 66 0 0]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 67 0 0]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 69 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 70 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 71 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 72 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 73 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 74 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 75 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 76 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 77 0 0]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 79 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 80 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 81 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 82 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 84 0 0]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 86 0 0]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 87 0 0]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 89 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

[msg MSG_048_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]How very puzzling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]The plants seem much livelier than they did when we started.[n][uf 1 1][e]

[msg MSG_049_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Do you suppose... they're happy that you are tending to them?[n][uf 1 1][e]

[sel SEL_050_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_051_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinating... There's no data on this, but it seems like you understand them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Hello, plants. I will be tending to you as well this time. Don't worry, I'll make sure to decrease my pressure output.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]But if anything starts hurting, just raise your left hand... Or rather, your left leaf.[n][uf 1 1][e]

[msg MSG_052_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]That is what I thought, as well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]However, some reports suggest that plants grow better when you speak to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Could it be that they have some sort of ability that we aren't yet aware of?[n][uf 1 1][e]

[msg MSG_053_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Good idea. I'll give it a try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Hello, hello. This is Aigis. If you can hear me, plants, then please respond.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Unfortunately, there was no answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Communication will be difficult with my current abilities. This is something to consider for the future.[n][uf 1 1][e]

[msg MSG_054_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]I had some prior knowledge of "plants," but this was my first time observing them directly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]These little seeds and buds in the earth can morph and change so quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Is this proof that they are living as well? How fascinating.[n][uf 1 1][e]

[msg MSG_055_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]I would like to watch these plants grow and document this experience for my records.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]I will tend to them with my full power![n][uf 1 1][e]

[msg MND_056_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_057_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]This took more time than I'd anticipated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0]I will need to run more simulations to ensure there are no delays next time.[n][uf 1 1][e]

[msg MND_058_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_059_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]It's gotten late. We should head back now.[n][uf 1 1][e]

[msg MSG_060_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]I've been wondering...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]The plants look much livelier now compared to before they were tended to.[n][uf 1 1][e]

[msg MSG_061_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Do you think... they're happy you're taking care of them, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_062_0_0 top]
[uf 0 5 65278][uf 2 1]It's possible.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_063_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Yes, you handle them so delicately, it's clear that you care about them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm sure the plants know how much work you're putting in for them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 28 0 0]I'll do the best I can to make them happy too![n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]I agree... But that's why I find it so strange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]They say talking to plants can help them grow, don't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Do you think... maybe these plants have a heart as well, but we just aren't aware of it?[n][uf 1 1][e]

[msg MSG_065_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]...It would be nice if that were possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 33 0 0]I wonder... Maybe these plants have a heart as well, but we just aren't aware of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 34 0 0]If we keep tending to them, will we understand them better?[n][uf 1 1][e]

[msg MSG_066_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Looking at them like this really makes me think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 36 0 0]These plants are just like you and the others. They're living, too...[n][uf 1 1][e]

[msg MSG_067_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 37 0 0]I want to see them grow with my own eyes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]So I'm going to do everything in my power to care for them.[n][uf 1 1][e]

[msg MND_068_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_069_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]I'm sorry. This was my first time doing this, so I think I slowed you down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]I'll keep training in my room so that I can work faster next time.[n][uf 1 1][e]

[msg MND_070_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_071_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 41 0 0]Thank you for your help. We should head back now.[n][uf 1 1][e]

[msg MSG_072_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 42 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 43 0 0]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_073_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 45 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_074_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_075_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 46 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 47 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 48 0 0]This must the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_076_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 49 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 50 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 51 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 52 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_077_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 53 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 54 0 0]I will move it to another leaf then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 56 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 57 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_078_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 58 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 59 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_079_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 61 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_080_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_081_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 62 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 63 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_082_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_083_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Status reads all green. No problems to report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 65 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_084_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 66 0 0]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 67 0 0]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_085_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 69 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_086_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_087_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 70 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 71 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 72 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_088_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 73 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 74 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 75 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 76 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_089_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 77 0 0]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 79 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 80 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_090_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 81 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 82 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_091_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 84 0 0]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_092_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_093_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 86 0 0]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 87 0 0]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_094_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_095_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 89 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

[msg MSG_247_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]How very puzzling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]The plants seem much livelier than they did when we started.[n][uf 1 1][e]

[msg MSG_248_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Do you suppose... they're happy that you are tending to them?[n][uf 1 1][e]

[sel SEL_249_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_252_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinating... There's no data on this, but it seems like you understand them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Hello, plants. I will be tending to you as well this time. Don't worry, I'll make sure to decrease my pressure output.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]But if anything starts hurting, just raise your left hand... Or rather, your left leaf.[n][uf 1 1][e]

[msg MSG_256_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]That is what I thought, as well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]However, some reports suggest that plants grow better when you speak to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Could it be that they have some sort of ability that we aren't yet aware of?[n][uf 1 1][e]

[msg MSG_259_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Good idea. I'll give it a try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Hello, hello. This is Aigis. If you can hear me, plants, then please respond.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Unfortunately, there was no answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Communication will be difficult with my current abilities. This is something to consider for the future.[n][uf 1 1][e]

[msg MSG_263_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]I had some prior knowledge of "plants," but this was my first time observing them directly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]These little seeds and buds in the earth can morph and change so quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Is this proof that they are living as well? How fascinating.[n][uf 1 1][e]

[msg MSG_265_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]I would like to watch these plants grow and document this experience for my records.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]I will tend to them with my full power![n][uf 1 1][e]

[msg MND_267_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_269_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]This took more time than I'd anticipated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]I will need to run more simulations to ensure there are no delays next time.[n][uf 1 1][e]

[msg MND_270_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_271_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]It's gotten late. We should head back now.[n][uf 1 1][e]

[msg MSG_277_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]I've been wondering...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]The plants look much livelier now compared to before they were tended to.[n][uf 1 1][e]

[msg MSG_278_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Do you think... they're happy you're taking care of them, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_279_0_0 top]
[uf 0 5 65278][uf 2 1]It's possible.[e]
[uf 0 5 65278][uf 2 1]That's not possible.[e]
[uf 0 5 65278][uf 2 1]Why don't you ask?[e]

[msg MSG_282_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Yes, you handle them so delicately, it's clear that you care about them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm sure the plants know how much work you're putting in for them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 28 0 0]I'll do the best I can to make them happy too![n][uf 1 1][e]

[msg MSG_285_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]I agree... But that's why I find it so strange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]They say talking to plants can help them grow, don't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 31 0 0]Do you think... maybe these plants have a heart as well, but we just aren't aware of it?[n][uf 1 1][e]

[msg MSG_288_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]...It would be nice if that were possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 33 0 0]I wonder... Maybe these plants have a heart as well, but we just aren't aware of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 34 0 0]If we keep tending to them, will we understand them better?[n][uf 1 1][e]

[msg MSG_292_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Looking at them like this really makes me think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 36 0 0]These plants are just like you and the others. They're living, too...[n][uf 1 1][e]

[msg MSG_294_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 37 0 0]I want to see them grow with my own eyes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]So I'm going to do everything in my power to care for them.[n][uf 1 1][e]

[msg MND_296_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_298_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]I'm sorry. This was my first time doing this, so I think I slowed you down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]I'll keep training in my room so that I can work faster next time.[n][uf 1 1][e]

[msg MND_299_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it[n]looks like this will be a big harvest...[n][uf 1 1][e]

[msg MSG_300_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 41 0 0]Thank you for your help. We should head back now.[n][uf 1 1][e]

[msg MSG_305_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]There appears to be less damage from pests than the data in my predictions suggests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 43 0 0]We haven't taken any specific measures against them. What is the cause of this?[n][uf 1 1][e]

[msg MSG_307_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 45 0 0]Look, [uf 4 2]-san! I've sighted a ladybug larva! It's very small and adorable.[n][uf 1 1][e]

[sel SEL_308_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_311_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 46 0 0]No, we mustn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 47 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 48 0 0]This must the reason why they've been growing so well.[n][uf 1 1][e]

[msg MSG_313_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 49 0 0]Agreed. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 50 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 51 0 0]That would explain why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 52 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_318_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 53 0 0]You don't look so well. You don't have to worry about it biting you though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 54 0 0]I will move it to another leaf then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 56 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 57 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_323_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 58 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 59 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_324_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 61 0 0]My apologies, I got distracted. Let's keep working.[n][uf 1 1][e]

[msg MND_326_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_328_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 62 0 0]Excuse me, [uf 4 2]-san. Please apply the repellant on that end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 63 0 0]Pests deserve no mercy.[n][uf 1 1][e]

[msg MND_329_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_330_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Status reads all green. No problems to report.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 65 0 0]That concludes our mission for today. We should head back now.[n][uf 1 1][e]

[msg MSG_332_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 66 0 0]There isn't as much damage from pests as I was expecting. That's a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 67 0 0]But we haven't taken any special measures. What's going on...?[n][uf 1 1][e]

[msg MSG_335_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh? This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 69 0 0]Look, [uf 4 2]-san! There's a ladybug larva! It's so small and adorable.[n][uf 1 1][e]

[sel SEL_336_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get rid of it.[e]
[uf 0 5 65278][uf 2 1]Just leave it alone.[e]
[uf 0 5 65278][uf 2 1]Please keep it away from me.[e]

[msg MSG_339_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 70 0 0]No, we can't![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 71 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 72 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]

[msg MSG_342_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 73 0 0]Yes. We wouldn't want to interrupt it while it's eating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 74 0 0]Ladybugs are the natural predators of pests that damage plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 75 0 0]That explains why there weren't any harmful insects around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 76 0 0]Thank you very much, little ladybug.[n][uf 1 1][e]

[msg MSG_346_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 77 0 0]I'm sorry. Are you uncomfortable with insects? I'll move it to another leaf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 79 0 0]...It won't stay still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 80 0 0]It looks like the ladybug would prefer to be near you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MSG_351_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 81 0 0]Even in just these tiny planters, there is so much life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 82 0 0]There's no one to teach them. They're just doing the best they can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_352_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 84 0 0]Sorry, I got distracted. Shall we keep going?[n][uf 1 1][e]

[msg MND_354_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aigis...[n][uf 1 1][e]

[msg MSG_356_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2]-san, look over there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 86 0 0]It may be rude to interfere, but we can't let them ruin our harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 87 0 0]Let's give the ladybug some assistance this time.[n][uf 1 1][e]

[msg MND_357_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_358_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Status reads all green. I don't see any problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 89 0 0]That should be enough for today. Let's head back now.[n][uf 1 1][e]

