[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 3 1 6]I bet these taste really good when they're freshly harvested.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 3 1 6]Wow, they've gotten so big since we last saw them.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 3 1 6]The smell of the soil really makes it feel like we're growing something, doesn't it?[n][uf 1 1][e]

