[msg MSG_000_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 500]Are you ready to hear the voice of the Messiah and welcome the Salvation?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]If I accept, I wonder what they'll tell me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It could be dangerous. What should I do...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 500]Time will not wait. Now's the time to take action...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'll meet the Messiah.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_004_0_0 [Suspicious-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 500]Well, then... Follow me.[n][uf 1 1][e]

