[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Did we make it in time?[n][uf 1 1][e]

[msg MSG_000_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 4 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Hey, wait! Why're we still moving!?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]We're going too fast! We need to put on the brakes, or...![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 1 0 0 4 0 0]What are you waiting for!? You're coming up on the next train, fast![n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Dammit! I don't know how to stop this thing![n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]We have no choice![e]
[uf 0 5 65278][uf 2 1]Leave it to me![e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Aaaaaah![n][uf 1 1][e]

