[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]There's something you have to know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Do you remember Chidori, the girl who was with Strega?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]I don't mean to alarm you, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 4 0 0]The truth is... there's a chance that she may wake up today.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Chidori is still alive...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 5 0 0]I know what you're going to say. And yes, we did see her die with our own eyes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 5 0 25 25]However... a few days later, her body began to undergo transmogrification.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 5 0 25 25]For the past few weeks, she's been in a sort of stasis, neither living nor dead.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]How is this possible?[e]
[uf 0 5 65278][uf 2 1]Why didn't you tell us?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 8 0 0]I don't know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]It may be related to her Persona's abilities, but that's mere speculation.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]Honestly... I didn't know if I should.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]There was a chance I could've made things worse without knowing whether she would live or die.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 12 0 0]The reason I wanted to talk to you is... How do you think we should tell Iori?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 2 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 5 10 25 25]You see, she's probably—[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Yes, it's me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 5 3 25 25]I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 3 25 25]Yes, I understand.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]That was the hospital.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]They say she's just awakened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 5 3 25 25]It's hard to believe, but it seems that Chidori really has come back to life—[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 20 0 0]D-Did I hear that right...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Iori!?[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Chidori is...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 23 0 0]Huh...? I-Is this a joke? Some kinda trick...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]No... It's not a joke, or a trick. She's currently recovering in the same hospital as before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 5 3 25 25]But... Iori... She probably...[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]Chidori...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 27 0 0]Chidori's... alive...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 0 0 0 28 0 0][uf 4 23 0 3 2 25 25]......[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]Wha— Hey, Junpei! What about your cleanup duty!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Geez... What's gotten into him?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Well, I guess it's a moot point now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 5 0 25 25]But... perhaps it's for the best that he found out this way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 5 0 25 25]I think I'll head to the hospital after this, too. Could I ask you to come along?[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]We all decided to go to Tatsumi[n]Memorial Hospital together.[n][uf 1 1][e]

