[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Sorry for calling you all again so soon, but I brought something special today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Well, let me just show you before I get into explaining what it is.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'd like to provide you with some [uf 0 1 33]new equipment[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]After spending quite some time in development, we're now ready for the battle testing phase.[n][uf 1 1][e]

[msg MSG_003_0_0 [（ＳＥ）伊織 順平]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]おお…[n][uf 1 1][e]

[msg MSG_004_0_0 [（ＳＥ）岳羽 ゆかり]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]へえ…[n][uf 1 1][e]

[msg MSG_005_0_0 [（ＳＥ）真田 明彦]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]ほう…[n][uf 1 1][e]

[msg MSG_006_0_0 [（ＳＥ）桐条 美鶴]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]フム…[n][uf 1 1][e]

[msg MSG_007_0_0 [（ＳＥ）山岸 風花]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]わ…[n][uf 1 1][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]The Shadows are getting stronger. You just barely won the last battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]We can only assume they'll grow even more powerful still. That's why you all need something more to stay in the fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]From now on, I want everyone to use these during your operations.[n][uf 1 1][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Combat gear, complete with a matching armband, and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Your new trump card in the battle against the Shadows: cartridges that enable the use of [uf 0 1 33]Theurgy[uf 0 1 27].[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Trump card?[e]
[uf 0 5 65278][uf 2 1]Theurgy...?[e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Theurgy means "spiritual magic that could reach the gods" in Greek.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]To put it simply, it synchronizes with the user's emotions, and when the right conditions are met, allows them to unleash an attack of immense power.[n][uf 1 1][e]

[msg MSG_011_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 1 0][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 17 0 0]Oh, you're talking about signature attacks! Aw, yeah! I've been waitin' for something like this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 18 0 0]Okay, how does it work!?[n][uf 1 1][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Well, about that... It's a bit difficult to explain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 222 1 25 25]I think it might be easier if you just try it out for yourselves.[n][uf 1 1][e]

[sel SEL_013_5_0 top]
[uf 0 5 65278][uf 2 1]You're asking a lot.[e]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]Is it dangerous?[e]

[msg MSG_013_3_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, please. If you can handle a Persona, this should hardly be any more difficult.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]It's been thoroughly tested for safety, too. So nothing to worry about there.[n][uf 1 1][e]

[msg MSG_013_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Hold on, isn't it dangerous to use something like this without knowing how it works?[n][uf 1 1][e]

[msg MSG_013_7_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Oh, don't worry about that. It's been well-tested and determined completely safe.[n][uf 1 1][e]

[msg MSG_013_9_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Oh, don't worry about that. It's been well-tested and determined completely safe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I'm sure you'll get a chance to see it in action as you continue your battles.[n][uf 1 1][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Oh, there's a manual for it as well. Take a look at it if you feel the need.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Well, I'm sure glad I made it in today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 222 0 25 25]With Yamagishi-kun joining us, Kirijo-kun can go back to being a frontline fighter. That means SEES is going to have a new lineup after today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 222 1 25 25]And what better time than now to roll out this new weapon, don't you agree?[n][uf 1 1][e]

[msg MSG_016_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Oh, would you look at the time?[n][uf 1 1][e]

[msg MSG_016_3_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I'd like to talk more about this, but I've been quite busy with the investigation into those large Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 222 1 25 25]I think we're on the verge of a breakthrough though, so I'll be sure to let you know what we find out soon.[n][uf 1 1][e]

[msg MSG_016_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Okay. I'm leaving the rest to you, Kirijo-kun.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 35 0 0]And there he goes...[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 36 0 0]I sort of thought this before, but he's rather laid-back, isn't he?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 37 0 0]More like careless.[n][uf 1 1][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 38 0 0]It's fine. We should just give it a go, like the chairman said.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 1 65535 0 0][uf 3 1 1 0 0 39 0 0]In fact, since everyone's already here, now might be the best opportunity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 5 0 25 25]Let's head into Tartarus and try out our new equipment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 41 0 0]I've been wanting to get back into the swing of things, anyway. And this will serve as a good test of our team lineup with Yamagishi as backup.[n][uf 1 1][e]

[msg MSG_021_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 42 0 0]How does that sound, [uf 4 1]?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]I don't mind.[e]
[uf 0 5 65278][uf 2 1]Looking forward to this.[e]
[uf 0 5 65278][uf 2 1]Sounds like a pain.[e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 1 65535 0 0][uf 3 1 1 0 0 43 0 0]Then it's settled.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 1 65535 0 0][uf 3 1 1 0 0 44 0 0][uf 4 23 0 4 9 25 25]Let's give this Theurgy stuff a shot. Can't wait to see what kind of punch it's packing.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 45 0 0]Man, this trump card stuff is getting me so pumped up![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 46 0 0]I'm gonna be all like, "Take this! Super Ace Junpei Attack!" ...Or something like that.[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 47 0 0]Aw, don't be like that. He brought these just for us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 48 0 0]And you wouldn't wanna miss out on my super cool finishing move, would ya?[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 49 0 0]That I don't care about, but we should go for Fuuka's sake, so she can get used to things.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 50 0 0]I'm a little nervous since it's my first time, but I'll follow your lead.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 51 0 0]All right, we'll go into Tartarus once everyone is geared up.[n][uf 1 1][e]

[msg MSG_029_0_0 [（ＳＥ）伊織 順平]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 52 0 0]おうっス！[n][uf 1 1][e]

[msg MSG_030_0_0 [（ＳＥ）岳羽 ゆかり]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 53 0 0]はい。[n][uf 1 1][e]

[msg MSG_031_0_0 [（ＳＥ）真田 明彦]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 54 0 0]ああ。[n][uf 1 1][e]

[msg MSG_032_0_0 [（ＳＥ）山岸 風花]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 55 0 0]はいっ。[n][uf 1 1][e]

