[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I have [uf 0 1 2][uf 2 4 1][uf 0 1 27] Twilight Fragments.[n]I need [uf 0 1 2][uf 2 4 2][uf 0 1 27] to duplicate a Skill Card...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Duplicate a card[e]
[uf 0 5 65278][uf 2 1]Do nothing[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]What kind of card should I duplicate?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Physical[e]
[uf 0 5 65278][uf 2 1]Magic[e]
[uf 0 5 65278][uf 2 1]Healing/Support[e]
[uf 0 5 65278][uf 2 1]Passive[e]
[uf 0 5 65278][uf 2 1]Cancel duplication[e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Should I duplicate [uf 4 4 1 37 1 0]?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]No[e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I can't carry any more [uf 4 4 1 37 1 0]...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I don't have any Skill Cards to duplicate...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I don't have enough Twilight Fragments...[n][uf 1 1][e]

