[sel SEL_BOSS top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MSG_OPE_STOP_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]What are you doing? C'mon, hurry up and choose a party.[n][uf 1 1][e]

[msg MSG_OPE_STOP_JUNPEI [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Dude, what're you doin'? Choose some party members already![n][uf 1 1][e]

[msg MSG_OPE_STOP_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]What exactly are you doing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We don't have time to waste. Please decide who will be going with you.[n][uf 1 1][e]

[msg MSG_OPE_STOP_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hey, where do you think you're going?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]We have to get out of here as soon as we can, so hurry up and pick who's going.[n][uf 1 1][e]

[msg MSG_OPE_STOP_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]It's dangerous to fight with such a small group. You should bring more people with you.[n][uf 1 1][e]

[msg MSG_GOTO_OPE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Okay, I'll get ready to provide support, then. Please head on over.[n][uf 1 1][e]

[msg MND_BOOK_SHELF_01]
[uf 0 5 65278][uf 2 1]Many encyclopedia[n]volumes are lined up here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There are also star charts[n]and books on geology.[n][uf 1 1][e]

[msg MND_BOOK_SHELF_02]
[uf 0 5 65278][uf 2 1]There are many files labeled,[n]"Shadow Appearance Dates."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They are stamped with[n]"Do Not Remove" labels.[n][uf 1 1][e]

[msg MND_BOOK_SHELF_03]
[uf 0 5 65278][uf 2 1]The titles contain many esoteric[n]terms that I can't understand...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They seem to have to do with[n]psychology and psychoanalysis.[n][uf 1 1][e]

[msg MND_NOZOKI_ANYONE1]
[uf 0 5 65278][uf 2 1]It's a bank of consoles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There are others in the room right now,[n]so I shouldn't watch the videos...[n][uf 1 1][e]

[msg MND_NOZOKI_ANYONE2]
[uf 0 5 65278][uf 2 1]It's a bank of consoles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A surveillance camera seems to have[n]turned itself on and recorded a video...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But there are others in the room right[n]now, so I shouldn't watch it...[n][uf 1 1][e]

[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]No[e]

[msg MSG_OPE_STOP_AEGIS [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Please decide who will be joining you in battle.[n][uf 1 1][e]

[msg MSG_OPE_STOP_AMADA [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Is something wrong?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Um... Please decide who's going.[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Okay, let's go.[n][uf 1 1][e]

[msg MSG_1103_MITURU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Well then, we're off.[n][uf 1 1][e]

[msg MSG_1103_IKUTUKI_01 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0]All right. Be careful.[n][uf 1 1][e]

[msg MSG_1103_MITURU_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Let's go![n][uf 1 1][e]

[msg MND_WAREHOUSE]
[uf 0 5 65278][uf 2 1]The door is tightly sealed. I wonder[n]if it's a storage room...[n][uf 1 1][e]

[msg MND_CABINET]
[uf 0 5 65278][uf 2 1]There are all kinds of[n]decorations on the shelf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]On either side are pictures of a[n]woman and a stern-looking man...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder who they are...[n][uf 1 1][e]

