[msg MND_BARRIER]
[uf 0 5 65278][uf 2 1]The path to the next floor is blocked off...[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_FIR [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]It seems to continue on upwards, but the path is blocked...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Looks like there's no way to progress any further right now, so let's stop here for tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]We've still managed to cover a lot of ground. Well done, everyone.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_FIR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_FIRS [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Guess that's it, then. But how are we gonna get past this roadblock?[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_FIRS [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Tartarus changes every day, right? So maybe it won't be blocked off tomorrow night, or somethin'.[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_FIRS_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4031 0 0]Unfortunately, that logic doesn't seem to apply here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Some floors have fixed structures and layouts. This appears to be one of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Some other factor may have caused this. I'll look into it.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_FIRS_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2066 0 0]Guess we just gotta wait. C'mon, let's bounce, [uf 4 2].[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Looks like we still won't be able to proceed after all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]No need to rush, however. I'm sure the path will open at some point.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Looks like this is the end of the line... How much more do we have to explore after this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Well, not like we're gonna unlock it by dwelling on it. All we gotta do now is wait.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2063 0 0]Couldn't we just bring a ladder or something? But it'd be a pretty nasty fall if we slipped, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Guess we'll just have to wait and see. You'll just have to witness my mad skills next time![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]It looks like we can't proceed any further. I'm sure the opportunity will present itself in time.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]We can't go any further than this. Looks like we'll just have to wait.[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]We hit a dead end... What now? Should we stop for tonight?[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]I wonder why it's blocked off now when it's just gonna open up later...[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Whew, what a climb! C'mon, let's head back and grab some grub.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]I mean, who knows when it'll open up? How the heck does it even work anyways?[n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3093 0 0]This is as far as we can go, huh. Guess it's time to head back.[n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3062 0 0]Even if we can't press forward right now, we have plenty more to do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Like gaining combat experience. If we train now, we'll be ready for what comes later.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Looks like this is as far as we can go for now. It's a good mark of our progress.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4122 0 0]It's strange. I've come to accept that it's the tower stopping us like this. This place is really unfathomable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's almost as if it's luring us in... Am I overthinking it?[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5138 0 0]Koro-chan, that's the furthest we can go for now. We did a good job.[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5086 0 0]Koro-chan, well done. Good work.[n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_01 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0]It seems we can't proceed now. Let's wait for the time to come.[n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_02 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]It's frustrating, but "good things come with waiting," as they say.[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]There's nothing we can do if the path is blocked. Shall we turn in for the night?[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7062 0 0]Looks like we've hit a stopping point. Does that mean we're taking a break from Tartarus for a bit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]But, I guess we could still come back and train up by fighting the Shadows.[n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_01 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_02 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_01 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9108 0 0]We're just gonna have to wait. Time for ya to head to bed.[n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_02 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9113 0 0]A dead end... Tch, wasting our time like this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Just gotta wait it out.[n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_02_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0]It's frustrating, but as the saying goes, "Good things come to those who wait."[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5077 0 0]Looks like we can't go any further than this... The path will probably only open on the Promised Day...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Let's wait for January 31st while we prepare for the final battle.[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1006 0 0]Is there anything else we can do for now? ...I don't want to have any regrets.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]You'll be waiting for us beyond this point, won't you? Ryoji... We're on our way.[n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]Now, all we have to do... is prepare ourselves for the moment, with no regrets.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4116 0 0]...There's still some time. We should do whatever we can.[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]Koro-chan seems to understand that we need to prepare ourselves for what's to come.[n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6003 0 0]This is as far as we can go for now, until the Promised Day. And what awaits us then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0]I can hardly imagine. Still, let's do everything we can.[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7119 0 0][uf 4 1]-san, please let me know if there's anything I can do to help![n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf![n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_10 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_20 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4102 0 0]What're these tremors...? Watch out![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_21 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4112 0 0]Is it over? What was that...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It's one thing just to know Tartarus changes daily, but to actually see it transform before our very own eyes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Regardless, the path has opened. Let's try exploring further beyond that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]As for our next goal... I can only assume there'll be a similar obstruction up ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Let's aim for that. I'm counting on you.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_20 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5073 0 0]These vibrations...! Please watch out![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_21 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5114 0 0]The blocked path opened up...! Now we can move forward![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]But, I wonder how it works... Tartarus is full of mysteries.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The labyrinth continues on beyond this point.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There'll probably be a similar obstruction further up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Let's aim to reach that next![n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1119 0 0]Argh, I wish it wouldn't start shaking all of a sudden. My heart almost stopped...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'm worried about what else could be in store for us down the road... But since the path opened up, I guess we gotta press on.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_20 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]That was kinda exciting. It was almost like watching a giant robot transform![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I wonder what other gimmicks we'll see. Anyways, let's keep going.[n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_20 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3121 0 0]That was quite a contraption. What was its purpose...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hm, no point dwelling on it. All I need to do is keep moving forward.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_20 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]Now, we can proceed further. It will only grow more treacherous from here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We'll need to be on high alert. We're counting on you, [uf 4 1].[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_20 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]Did that surprise you too, Koro-chan? We'll be counting on you, too![n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_20 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6100 0 0]The change in structure was so surprising, I "jumped out of the skin," as they say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...Although, I don't fully understand that expression. Anyway, we should proceed on.[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_20 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7120 0 0]It was a huge shock when the path started moving. I wonder how it works...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Oh, not that I thought it was cool or anything![n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_20 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_20 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]At least we can move on, yeah, but don't you think we're taking it a little slow?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Shouldn't we be picking up the pace a little? Either way, I'll leave it up to you.[n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_20_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6100 0 0]I didn't expect the structure to change. My "jaw dropped."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...Which is to say I was extremely surprised. Anyway, we should hurry on ahead.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_30 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]Here it comes! Stay away from the stairs![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_31 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4115 0 0]Great. Now we can continue onward.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Expect the enemies to grow stronger. Stay alert, everyone.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_30 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Here it is...! Please watch out![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_31 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]Looks like the shaking has subsided. Is everyone all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The path towards the staircase has opened up. You can advance further now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We don't know what's waiting ahead, so please be careful going forward.[n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1116 0 0]All right, let's go. I wonder what the next area's gonna be like.[n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_30 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Stay tuned for more from the mighty Junpei![n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_30 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3115 0 0]...Made it to the next stage. Let's see how far my fists can carry me.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_30 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]It's thanks to all of you that we've made it this far.[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_30 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]Koro-chan is all pumped up too. You can do it, Koro-chan![n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_30 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6106 0 0]It must take an enormous amount of energy to move a structure that large.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Although, such physical laws might not apply here.[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_30 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Another new area beyond this point, huh? I wonder what we'll find there...[n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_30 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_30 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9107 0 0]We're going to the next floor, right? Don't let your guard down.[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_40 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_MITU_41 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_40 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5073 0 0]Here it comes...! Stay back![n][uf 1 1][e]

[msg MSG_GATE_ACCESS_FUKA_41 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]This is the last of it. Let's go![n][uf 1 1][e]

[msg MSG_GATE_RES_YUKARI_40 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Everything ends today... Let's go![n][uf 1 1][e]

[msg MSG_GATE_RES_JUNPEI_40 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Alright, let's do this! Get ready to face us, Nyx![n][uf 1 1][e]

[msg MSG_GATE_RES_SANADA_40 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]...Let's go. Doesn't matter what's waiting for us ahead.[n][uf 1 1][e]

[msg MSG_GATE_RES_MITSURU_40 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4143 0 0]Let's go, for the sake of our future. We'll do this together, as a team.[n][uf 1 1][e]

[msg MSG_GATE_RES_FUKA_40 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]Koro-chan... Let's do our best![n][uf 1 1][e]

[msg MSG_GATE_RES_AEGIS_40 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6083 0 0]Let's go. I... want to find out.[n][uf 1 1][e]

[msg MSG_GATE_RES_AMADA_40 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]I'm ready for this.[n][uf 1 1][e]

[msg MSG_GATE_RES_KOROMARU_40 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8014 0 0]Grrr... Woof! Woof![n][uf 1 1][e]

[msg MSG_GATE_RES_ARAGAKI_40 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_256F_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]The path is open.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]This should lead to the place Ryoji-kun told us about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 4 25 6]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]I sense a strong presence on the floor above! But, this feeling is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5100 0 0]A human!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please be careful! This is... Strega's presence![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]They're really here... Stay on high alert![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Shall we go, then?[n][uf 1 1][e]

[msg MSG_256F_TWICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]This should lead to the place Ryoji-kun told us about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 4 25 6]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]I sense a strong presence on the floor above! But, this feeling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5100 0 0]...It's not a Shadow![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please be careful! This is... Strega's presence![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]They're really here... Stay on high alert![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Shall we go, then?[n][uf 1 1][e]

