[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I can't get up...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]We've won. Though it doesn't feel much like a victory...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]So... What now, Yukari?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 0 0 0 4 0 0]......[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]My resolve wasn't strong enough after all...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I can no longer pursue the[n]outcome I decided is best...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]My consciousness is fading...[n][uf 1 1][e]

