[msg MSG_000_0_0 [Principal]]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]And so, another new school year is upon us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]I'd like each of you to remember the proverb, "If a job's worth doing, it's worth doing well."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]When applied to student life, this means...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The principal continues with his speech...[n][uf 1 1][e]

[msg MSG_002_0_0 [Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]Psst... Hey.[n][uf 1 1][e]

[msg MSG_003_0_0 [Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 2]You came to school with Takeba-san this morning, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 2]I saw you two walking together. You must be pretty close, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 2]What's the deal between you and her?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 2]Oh, and does she have a boyfriend? Nobody seems to know.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]She does.[e]
[uf 0 5 65278][uf 2 1]She doesn't.[e]
[uf 0 5 65278][uf 2 1]I don't know.[e]

[msg MSG_005_0_0 [Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 2]Man, I knew it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]I mean, why wouldn't she, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]Wait, how close are you guys?[n][uf 1 1][e]

[msg MSG_006_0_0 [Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]Really? You asked her?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Wow, I'm surprised...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Wait, how close are you guys?[n][uf 1 1][e]

[msg MSG_007_0_0 [Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 2]Oh, really?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 2]I thought you might know, but... I guess not.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 2]Wait, how close are you guys?[n][uf 1 1][e]

[msg MSG_008_0_0 [Teacher from Another Class]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1]Who's that? Someone's talking![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]Sounds like it's coming from Ms. Toriumi's class.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ms. Toriumi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1581 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Hey, shhh! Be quiet! You're gonna get me in trouble![n][uf 1 1][e]

