[msg TRL_000_0_0 [Persona Compendium]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]All previously acquired Personas can be withdrawn and added to your Persona inventory. They can also be re-registered to the Compendium after leveling up.[n][uf 1 1][e]

[msg TRL_001_0_0 [Persona Compendium]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Note that there is a fee for withdrawing Personas, so keep an eye on your wallet.[n][uf 1 1][e]

