[msg TRL_000_0_0 [Persona Conception]]
[uf 0 5 65278][uf 2 1][uf 4 8 1]Occasionally, a newly created Persona will come [uf 0 1 2]bearing an item[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Persona Conception]]
[uf 0 5 65278][uf 2 1][uf 4 8 1]This item can be obtained by raising the item-bearing Persona to a predetermined level.[n][uf 1 1][e]

[msg TRL_002_0_0 [Persona Conception]]
[uf 0 5 65278][uf 2 1][uf 4 8 1]You can check the attainable item under Persona status on the Skills Details screen.[n][uf 1 1][e]

