[msg MSG_000_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 3 0 65535 14001 0 0]Oh, [uf 4 2]-kun. Are you free?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0]I'm going out with a few ladies later, but I guess some of their friends want to talk with me first...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0]Maybe we can all go together! Wouldn't that be so much more fun?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0]I think they're waiting for me on the roof. Want to come along?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Ryoji's invited me to join him. This might be a[n]good opportunity to get to know him better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school with Ryoji?[n][uf 1 1][e]

[msg MSG_002_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 3 0 65535 14002 0 0]...[uf 4 2]-kun, are you busy right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0]I've got a meeting on the roof in a moment. Why don't you come along?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Ryoji's invited me to join him. This might be a[n]good opportunity to get to know him better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school with Ryoji?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Ryoji[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 3 0 65535 14016 0 0]Great! Then let's go.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 3 0 65535 14020 0 0]Oh, that's unfortunate...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0]I'm not very familiar with the people I'm meeting... Hopefully it isn't too awkward...[n][uf 1 1][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0][uf 3 1 3 0 65535 14001 0 0]Oh, [uf 4 2]-kun. I had a favor to ask.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0]Yukari-san told me there's a riverbank nearby with a great view.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 155 65535 0 0]Would you like to check it out with me tomorrow?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Should I spend my free time[n]with Ryoji tomorrow...?[n][uf 1 1][e]

[msg MSG_009_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0][uf 3 1 3 0 65535 14002 0 0]We shouldn't let this opportunity slip by. If you're up for it, let's go check it out tomorrow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 155 65535 0 0]It's really close by, too. What do you say?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Should I spend my free time[n]with Ryoji tomorrow...?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Promise Ryoji[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_012_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 155 65535 0 0][uf 3 1 3 0 65535 14016 0 0]Great! Sounds like a plan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 155 65535 0 0]I'll come find you when we start heading back tomorrow. I'm looking forward to it![n][uf 1 1][e]

[msg MSG_013_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0][uf 3 1 3 0 65535 14019 0 0]No...? Oh, did you already make plans?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0]Well, let me know if you change your mind. I'd prefer to finalize my plans now, if possible.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 155 65535 0 0][uf 3 1 3 0 65535 14007 0 0]I'll come find you when we start heading back tomorrow. I hope it won't be too cold out.[n][uf 1 1][e]

