[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]I have heard that high school students engage in a social event called a "study group" before exams.[n][uf 1 1][e]

[msg MSG_000_1_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Such an activity may allow us to learn more about one another. Is this permissible?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Let's study together.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Roger that. Allow me to retrieve my textbooks and other studying materials.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6057 0 0]Understood. I shall remain on standby, should you change your mind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm ready to undertake this "study group" operation anytime.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6068 0 0]Have you decided to engage in my previously requested study group activities?[n][uf 1 1][e]

[msg MSG_004_1_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]What do you think?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Let's study together.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Roger that. Allow me to retrieve my textbooks and other studying materials.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6057 0 0]Understood. Please inform me if you change your mind.[n][uf 1 1][e]

[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

