[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 5 1 25 25]Help yourself to the snacks as well, if you'd like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Today, I wanted to show my thanks for your hard work, as well as check in to see how you're doing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 5 0 25 25]Ever since you joined us, you've been taking on a lot of responsibility as leader of our group.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Have you been running into any trouble? If you have, please, don't be afraid to let me know.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]A little, I guess...[e]
[uf 0 5 65278][uf 2 1]Does it have to be now?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 5 1 25 25]...Well, that's good to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 6 0 0]I have to say, I'm always inspired by the way you remain calm no matter the situation.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 5 3 25 25]I apologize for putting so much pressure on you. I'll do whatever I can to help.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 5 0 25 25]I have to say, I am grateful that you agreed to take on the leadership role.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]And I want you to know that you're doing an excellent job. Akihiko was right about you.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 5 3 25 25]Well, I won't force you or anything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 5 0 25 25]I just thought that this time we have might be a good opportunity to talk things over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 12 0 0]But I suppose it's only natural for you to have your own problems. For today, let's enjoy the refreshments.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 5 0 25 25]Your cup is empty... Let's pour you another.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru and I enjoyed tea together...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0]...It's late. We ended up spending a lot of time here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 15 0 0]Let's turn in for the night.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 1 25 25]Oh, I'll take care of the cleanup.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 4 1 5]I'm glad we had the chance to talk today. I'd like to invite you again when the opportunity arises.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 5 0 25 25]Then with that, I bid you a good night.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]It feels nice, being able to pour tea for someone else like this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 5 1 25 25]Oh, my apologies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 21 0 0]I'm supposed to be the host, and yet here I am thinking about myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 5 0 25 25]How about you, then? Are you having a good time?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]I'm a bit tense.[e]
[uf 0 5 65278][uf 2 1]I'd like a refill...[e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 5 1 25 25]Oh, that's good to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 24 0 0]Chamomile is known for its relaxing properties, so maybe that's taking its effect on you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 5 3 25 25]I... was actually a bit worried that I might be putting you off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 26 0 0]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 5 0 25 25]Sorry about that. Try to relax, if you can...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0]Then again, if it were that easy, it wouldn't be a problem, would it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 5 3 25 25]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 5 1 25 25]My apologies. Let me take care of that for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 31 0 0]Heh, I'm glad you aren't afraid to speak up when you want something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 5 0 25 25]Apparently, the popular opinion is that I'm difficult to approach...[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 5 0 25 25]Hm? We're running low on snacks. I'll have to ask my staff to—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 34 0 0]Actually...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 35 0 0]Oh, never mind. Here, let me pour you another cup.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I drank herbal tea with Mitsuru as[n]we discussed our favorite snacks...[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 36 0 0]All right, I think that's enough for now. We should start cleaning up.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 37 0 0][uf 4 23 0 5 1 25 25][uf 5 13 4 1 5]I'd like to invite you for this again, if time allows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 5 0 25 25]But for now, let's head back to our rooms.[n][uf 1 1][e]

