[msg MSG_FIRST_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]That was quite the trip, but we found a familiar sight beyond that imposing enemy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It seems rather secure... Can you get it open?[n][uf 1 1][e]

[msg MND_FIRST_HERO_00]
[uf 0 5 65278][uf 2 1]...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This treasure chest isn't locked...[n][uf 1 1][e]

[msg MSG_FIRST_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Huh? You can open it as-is...?[n][uf 1 1][e]

[sel SEL_FIRST_HERO_01 top]
[uf 0 5 65278][uf 2 1]Saves us some trouble.[e]
[uf 0 5 65278][uf 2 1]This is suspicious...[e]

[msg MSG_FIRST_FUKA_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We are in a rather irregular area... I wonder if that's a special feature of the place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm not detecting any danger, so please, check what's inside.[n][uf 1 1][e]

[msg MSG_REACTION_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 0 0 0][uf 3 1 3 0 65535 1096 0 0]Ah, there it is. We're gonna open it, right?[n][uf 1 1][e]

[msg MSG_REACTION_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 0 0 0][uf 3 1 3 0 65535 2095 0 0]That's what I'm talkin' about! I wonder what's in it this time...[n][uf 1 1][e]

[msg MSG_REACTION_SANADA_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 0 0 0][uf 3 1 3 0 65535 3086 0 0]And now, we get to reap the rewards. C'mon, let's see what we've got.[n][uf 1 1][e]

[msg MSG_REACTION_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 0 0 0][uf 3 1 3 0 65535 4143 0 0]We should be able to open that without worry. Check what's inside.[n][uf 1 1][e]

[msg MSG_REACTION_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]Good find! Now, try opening it...[n][uf 1 1][e]

[msg MSG_REACTION_AEGIS_00 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 0 0 0][uf 3 1 3 0 65535 6106 0 0]This is our reward for victory. May I see what you find?[n][uf 1 1][e]

[msg MSG_REACTION_AMADA_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 0 0 0][uf 3 1 3 0 65535 7096 0 0]These open up in such a cool way... I want to try it myself sometime![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 0 0 0]Uh, I-I mean... Never mind! Let's just empty it and move on![n][uf 1 1][e]

[msg MSG_REACTION_KOROMARU_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 0 0 0][uf 3 1 3 0 65535 8013 0 0]Arf! Arf arf![n][uf 1 1][e]

[msg MSG_REACTION_ARAGAKI_00 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 0 0 0][uf 3 1 3 0 65535 9057 0 0]I don't get the big deal about these... but you're gonna open that before we leave, right?[n][uf 1 1][e]

[msg MSG_REACTION_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Koro-chan's excited too! Now, try opening it...[n][uf 1 1][e]

[msg MSG_FIRST_FUKA_20 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5071 0 0]A tarot card...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's similar to the ones you already have, Leader.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It was also reacting to the entrance, so there may be some connection there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's possible that other doors elsewhere would react to that card as well.[n][uf 1 1][e]

[msg MSG_REACTION_YUKARI_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 0 0 0][uf 3 1 3 0 65535 1107 0 0]Another card? What's the deal?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 0 0 0]Well, we're not figuring it out here. Let's move on.[n][uf 1 1][e]

[msg MSG_REACTION_JUNPEI_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 0 0 0][uf 3 1 3 0 65535 2123 0 0]Another stupid card? We busted our asses for THAT?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 0 0 0]Hang on—it's too soon to be bummed out! Maybe if we collect enough of 'em, we can trade 'em in for something cool?[n][uf 1 1][e]

[msg MSG_REACTION_SANADA_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 0 0 0][uf 3 1 3 0 65535 3113 0 0]That's just a useless card to me, but it has some kind of meaning to you, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 0 0 0]Well, all I need is the opportunity to fight strong opponents. The experience I gain is reward enough for me.[n][uf 1 1][e]

[msg MSG_REACTION_MITSURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 0 0 0][uf 3 1 3 0 65535 4106 0 0]Puzzling cards hidden away in this already strange space...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 0 0 0]This Tartarus truly is a tower filled with mysteries.[n][uf 1 1][e]

[msg MSG_REACTION_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5060 0 0]Will that card open another door? Who would make such a mechanism, and why...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Well, in any case, well done! I'll await your return.[n][uf 1 1][e]

[msg MSG_REACTION_AEGIS_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 0 0 0][uf 3 1 3 0 65535 6060 0 0]A card. Who could have put this here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 0 0 0]Or is it simply coincidence? I do not know.[n][uf 1 1][e]

[msg MSG_REACTION_AMADA_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 0 0 0][uf 3 1 3 0 65535 7061 0 0]Another tarot card... Are these hinting at something?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 0 0 0]I mean, each one has a certain meaning, right? Maybe I'll look into it later...[n][uf 1 1][e]

[msg MSG_REACTION_KOROMARU_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 0 0 0][uf 3 1 3 0 65535 8004 0 0]Woof?[n][uf 1 1][e]

[msg MSG_REACTION_ARAGAKI_10 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 0 0 0][uf 3 1 3 0 65535 9054 0 0]I don't care what's in the damn boxes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 0 0 0]But if there's gonna be another fight like this one, take me with you. I don't wanna miss the chance to throw down like this again.[n][uf 1 1][e]

[msg MSG_REACTION_FUKA_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5131 0 0]I guess this isn't something that would hold Koro-chan's interest. I'll have to get him a treat when we get back.[n][uf 1 1][e]

[msg MSG_REACTION_FUKA_20 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5137 0 0]There wasn't a tarot card in that one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]If we can't open any of the unopened doors, maybe it's best to come back for now.[n][uf 1 1][e]

[msg PFM_GET_CARD_TEMPERANCE]
[uf 0 5 65278][uf 2 1]The Temperance Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_DEVIL]
[uf 0 5 65278][uf 2 1]The Devil Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_TOWER]
[uf 0 5 65278][uf 2 1]The Tower Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_STAR]
[uf 0 5 65278][uf 2 1]The Star Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_MOON]
[uf 0 5 65278][uf 2 1]The Moon Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_SUN]
[uf 0 5 65278][uf 2 1]The Sun Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_JUDGEMENT]
[uf 0 5 65278][uf 2 1]The Judgement Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg SYS_GET_CARD_TEMPERANCE]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Temperance[uf 0 1 27]: The next time you do a daily activity, your [uf 4 30 0 1 0 0], [uf 4 30 2 1 0 0], and [uf 4 30 1 1 0 0] will increase more than usual for that day.[n][uf 1 1][e]

[msg SYS_GET_CARD_DEVIL]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Devil[uf 0 1 27]: The number of items obtained by defeating enemies and destroying breakable objects will increase until you quit exploring.[n][uf 1 1][e]

[msg SYS_GET_CARD_TOWER]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Tower[uf 0 1 27]: All of your current Personas will have their stats increased by 1.[n][uf 1 1][e]

[msg SYS_GET_CARD_STAR]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Star[uf 0 1 27]: You will be able to pick one additional card during Shuffle Time.[n][uf 1 1][e]

[msg SYS_GET_CARD_MOON]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Moon[uf 0 1 27]: All current party members will have their HP and SP fully restored.[n][uf 1 1][e]

[msg SYS_GET_CARD_SUN]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Sun[uf 0 1 27]: You will be able to fuse Personas up to 5 levels above your current level until you quit exploring.[n][uf 1 1][e]

[msg SYS_GET_CARD_JUDGEMENT]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Judgement[uf 0 1 27]: The member of the current party with the lowest level will gain a large amount of EXP.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP]
[uf 0 5 65278][uf 2 1]By acquiring [uf 4 4 1 0 1 0], the number of Major Arcana cards attainable in a day has increased by one.[n][uf 1 1][e]

