[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah, there you are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Looks like you've recovered. I'm glad to see that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 222 0 25 25]There are some things I need to discuss with you. That's why I asked you to see me so soon after your discharge from the hospital.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Please, have a seat.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, before that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I believe I mentioned his name before, but this is Sanada-kun.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Hey there.[n][uf 1 1][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Okay, let me start off by asking you this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Would you believe me if I said that a day consists of more than 24 hours?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I wouldn't believe it.[e]
[uf 0 5 65278][uf 2 1]...Excuse me?[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Heh, that's a reasonable reaction.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 5 0 25 25]However, you've already experienced this truth firsthand.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Do you remember the night you first arrived here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]You had to have noticed the signs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Streetlights going out... Things that stopped working... The inexplicable appearance of coffins...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]With so many things amiss, didn't it feel like you'd stepped into a different time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]That's the [uf 0 1 33]Dark Hour[uf 0 1 27]—a time period hidden between one day and the next.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Hidden?[e]
[uf 0 5 65278][uf 2 1]Between?[e]
[uf 0 5 65278][uf 2 1]I don't get it.[e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I guess it's more like something people simply aren't cognizant of.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]But the Dark Hour does exist, and it occurs each night at midnight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]It will happen tonight, and every night to come.[n][uf 1 1][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]It occurs each night, as the clock strikes twelve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]It will happen tonight, and every night to come.[n][uf 1 1][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]I know how you feel. Who would believe such a fantastical claim?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]But the Dark Hour does exist, and it occurs each night as the clock strikes twelve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]It will happen tonight, and every night to come.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Normal people don't realize it, since they're all sleeping inside their coffins.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 4 1 25 25]But that's not what makes the Dark Hour so interesting.[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]You saw them... Those creatures.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]We call them [uf 0 1 33]Shadows[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]They only appear during the Dark Hour and attack anyone who roams free outside the coffins.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 4 1 25 25]It's our job to defeat them. Pretty exciting, huh?[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Akihiko! Why are you always like this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]You just got hurt the other day![n][uf 1 1][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Now, now. He does his work well, in any case.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]I'll get to the point.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]We are the [uf 0 1 33]Specialized Extracurricular Execution Squad[uf 0 1 27]—SEES for short.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]On paper, we're classified as a school club. But in reality, this group is dedicated to defeating the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Mitsuru Kirijo-kun is the leader, and I'm the club advisor.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]A Shadow feeds on the mind of its prey; the victim becomes a living corpse.[n][uf 1 1][e]

[msg MSG_016_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 0 1 33]Apathy Syndrome[uf 0 1 27]—I'm sure you've heard of it. We sometimes refer to those who suffer from this as "the Lost."[n][uf 1 1][e]

[msg MSG_016_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]They're responsible for most of the incidents on the news, if not all of them.[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]How do you fight them?[e]
[uf 0 5 65278][uf 2 1]What about the police?[e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Unfortunately, the police can't do a thing during the Dark Hour...[n][uf 1 1][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Although rare, there are those who can function during the Dark Hour.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]Some may even awaken to a power that enables them to fight Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]That's known as "[uf 0 1 33]Persona[uf 0 1 27]"—the power you called upon the other night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Shadows can only be defeated by Persona-users.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]That means you are the only ones who stand a chance against them.[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]I see.[e]
[uf 0 5 65278][uf 2 1]I don't understand.[e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]I'm glad you're quick to understand.[n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]What he's trying to say is, we want you to join us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]We've prepared an [uf 0 1 33]Evoker[uf 0 1 27] for you. We'd like you to lend us your strength.[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]I'm not sure I'm ready.[e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Whew... I was afraid you'd say no.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]I'm glad to hear you're on board.[n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]Don't think too hard on it. Just hang out with us for a while.[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]Please, we need your help.[n][uf 1 1][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Wait, don't pressure him like that! What if he feels like he can't say no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]I mean, I'd like it if he joined too, but...[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]...All right.[e]
[uf 0 5 65278][uf 2 1]Okay, for now.[e]
[uf 0 5 65278][uf 2 1]I don't mind.[e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]If you have any questions, don't hesitate to ask.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]Does that mean you accept?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]Whew... I was afraid you wouldn't do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]I'm glad to hear you're on board.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]We really appreciate it. If you have any questions, don't hesitate to ask.[n][uf 1 1][e]

[msg MSG_032_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]Thank you so much, truly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0][uf 4 23 0 222 0 25 25]Oh, I almost forgot. About your room assignment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]Why don't you just stay in the room you have now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 65 0 0][uf 4 23 0 222 1 25 25]I don't know what the holdup is, but I guess it worked out in the end! Hahahaha![n][uf 1 1][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]Holdup? But, wasn't that—[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]Oh, never mind...[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]I joined SEES to fight the Shadows...[n][uf 1 1][e]

[msg MND_035_5_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can hear a voice ringing inside my head...[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]I feel my inner strength growing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I recall what Igor said about[n]the power of Social Links.[n][uf 1 1][e]

[msg MSG_037_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]Well, that's all for today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]I'll follow up with you regarding our "club activities" later on.[n][uf 1 1][e]

[msg MSG_037_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 70 0 0]I apologize for gathering you all here on your precious day off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 71 0 0]Tomorrow is Sunday, so take some time to relax.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 72 0 0][uf 4 23 0 222 1 25 25]Well then, shall week-end this meeting?[n][uf 1 1][e]

[msg MSG_038_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 73 0 0]You know, because it's the weekend?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 74 0 0][uf 4 23 0 222 1 25 25]"Shall we end"... "Shall week-end"... Get it?[n][uf 1 1][e]

