[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Yukari Takeba[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Junpei Iori[uf 4 27 3 0][e]
[uf 0 5 65278][uf 2 1]Akihiko Sanada[uf 4 27 4 0][e]
[uf 0 5 65278][uf 2 1]Mitsuru Kirijo[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Aigis[uf 4 27 7 0][e]
[uf 0 5 65278][uf 2 1]Ken Amada[uf 4 27 8 0][e]
[uf 0 5 65278][uf 2 1]Koromaru[uf 4 27 9 0][e]
[uf 0 5 65278][uf 2 1]Shinjiro Aragaki[uf 4 27 10 0][e]
[uf 0 5 65278][uf 2 1]Metis[uf 4 27 11 0][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Skill Recall[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Who should I choose...?[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I don't have enough money...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Junpei-san?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Yukari-san?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Sanada-san?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Mitsuru-san?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Koromaru-san?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Aigis?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Amada-san?[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Aragaki?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I'd like to use the store's service...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]However, there is no one[n]who has a skill to recall.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Should I invite Metis?[n][uf 1 1][e]

