[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]Yes?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 2 0 0]Can I talk to you for a moment?[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 3 0 0]Senpai... This is unusual.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 4 0 0]Please, come in.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 5 0 0]So, not only do you excel at providing support during battle, you are also quite skilled at gathering information.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh, I-I'm sorry for doing that without permission.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 7 0 0]Don't worry, you're not in trouble. But I do have an important favor to ask of you.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 8 0 0]I want you to find out as much as you can about that incident ten years ago.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 5 65535 0 0][uf 3 1 1 0 0 9 0 0]Oh, well, very little of that was made public...[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 10 0 0]I know. That's why I want you to access the Kirijo Group's database.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 11 0 0]You mean, hack into their system?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 6 0 25 25]Is that allowed?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 13 0 0]I'll give you my ID and password. Then you won't be held accountable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 14 0 0]But I need to know the truth. In detail.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 15 0 0]Senpai...[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Of course, I'll understand if you refuse.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 17 0 0]Okay. I'll see what I can do.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 5 65535 0 0][uf 3 1 1 0 0 18 0 0]Are you sure?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 5 0 25 25]I appreciate it.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 20 0 0]Yamagishi... Aren't you resentful?[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 21 0 0]Regardless of my good intentions, I did drag you into this without fully explaining.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 22 0 0]I'm sure you must have at least a few complaints?[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 23 0 0]Not really.[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 24 0 0]Did you know my entire family's made up of doctors? My parents are the one exception.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 5 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 6 3 25 25]It gives them a bit of an inferiority complex. That's why they're so hard on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 5 65535 0 0][uf 3 1 1 0 0 26 0 0]...I don't like being at home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 6 0 25 25]But here, I'm able to do something no one else can. I have a purpose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 28 0 0]So no, I don't have any complaints.[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 29 0 0]You're right. We can't do this without you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 30 0 0]No one could take your place.[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 31 0 0]O-Oh...[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 5 65535 0 0][uf 3 1 1 0 0 32 0 0]Thank you. I'll see you later.[n][uf 1 1][e]

