[msg MSG_000_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]The number of Apathy Syndrome cases is down from last month, which seems to mark an end to the strange illness.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]In spite of this, surveys have shown that the public's everyday stress levels remain high.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]According to an investigation by the Ministry of Health and Welfare...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Whoa, when'd it get so late?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]It's almost midnight...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]It's hard to believe we passed the evening so quickly, even without doing anything in particular.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]I suppose it's because sitting here with you all brings me back to the time we spent together.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 6 65535 0 0][uf 3 1 1 0 0 8 0 0]I think I know what you mean.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]I have so many memories of this lounge that I find myself wanting to come back to it.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]It's the same for me. When I'm here, I can't help but reminisce on those days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 1 25 25]It's funny, since... Well, the things that happened back then weren't exactly pleasant.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 12 0 0]I getcha on the past and all, but... Isn't there something still off about the present?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 13 0 0]I feel like everywhere I go, I see people goofin' around like nothing else matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 14 0 0]It's like Strega's dumb ideas never got out of their heads, y'know?[n][uf 1 1][e]

[msg MSG_005_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 15 0 0]I mean... Is that the kind of world we almost died to protect?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]Wow, you've really grown up, Junpei-san![n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 17 0 0]I don't need to hear that from you![n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]It's out of our hands, I'm afraid.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0]We may have prevented the Fall, but there's only so much we can do to reform society.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 20 0 0]Yeah, I guess. But still...[n][uf 1 1][e]

[msg MSG_010_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]...And that's all for the weather.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]At the tone, the time will be 12 AM.[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 6 65535 0 0][uf 3 1 1 0 0 23 0 0]What was that!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 201 65535 0 0][uf 3 1 1 0 0 24 0 0]Woof! Rarf arf![n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 65535 0 0][uf 3 1 1 0 0 25 0 0]Right at midnight... No way, is it the Dark Hour again!?[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 8 6 65535 0 0][uf 3 1 1 0 0 26 0 0]Nah... Everything's fine out there![n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Wait... The news![n][uf 1 1][e]

[msg MSG_016_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]Good evening.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]It is now March 31st. Here are the latest news reports...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Huh? The 31st just ended, didn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 6 65535 0 0][uf 3 1 1 0 0 31 0 0]Did the anchor misread the date?[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 32 0 0]Geez, man... Is that all it was?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 33 0 0]Guess even the news people screw up every once in a while. Really had me going there for a second...[n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Weird... My phone says it's the 31st, too...[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 35 0 0]So like... It's gotta be a false alarm, yeah?[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 36 0 0]That's... a sensible assumption to make for now.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 37 0 0]But something felt... off...[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 38 0 0]Eh, it's getting late... We should probably call it a night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 39 0 0]I know we wanted to say goodbye to the dorm with a bang, but not like this.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 6 65535 0 0][uf 3 1 1 0 0 40 0 0]Um... Would it be all right if I returned to my room?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 6 65535 0 0][uf 3 1 1 0 0 41 0 0]I have preparations to make for the move tomorrow...[n][uf 1 1][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 6 65535 0 0][uf 3 1 1 0 0 42 0 0]Oh, of course. Good night, Aigis.[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 43 0 0]Niiiiiight...[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 44 0 0]I'd best contact Yukari and Akihiko... Just in case.[n][uf 1 1][e]

