[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]How do I convince him...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Male Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 100]Wh-Why am I...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0][uf 3 1 0 0 0 3 0 0]...![n][uf 1 1][e]

[msg MSG_003_0_0 [Male Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 100]Ugh... I feel... kinda weak...[n][uf 1 1][e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Your breathing is impaired, and your lips are pale.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Did you get enough sleep last night? And what do you usually have for lunch?[n][uf 1 1][e]

[msg MSG_005_0_0 [Male Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 100]Ungh... Now that I think about it, I didn't eat breakfast today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Mhm, I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]Just as I thought—looks like anemia, probably from an unbalanced diet. It must be all the fast food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I recommend adding more shellfish to your diet, like oyster and abalone. They're packed with iron and easy to cook.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Good work, Doc Junior.[e]
[uf 0 5 65278][uf 2 1]Will he be okay?[e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 10 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]D-Don't call me that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 10 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]This is just common sense. Being the son of a doctor doesn't have anything to do with it.[n][uf 1 1][e]

[msg MSG_009_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Well, this is just my amateur diagnosis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]But you should still see a professional. I'm not a real doctor, after all.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I'll take him to the nurse's office. You guys should head on home.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Hiraga[n]and went back to the dorm.[n][uf 1 1][e]

