[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 1 0 0]She's not waking up...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]How's it looking, Fuuka?[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm on it. I've used this equipment a number of times before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]It should be designed to allow us to operate the most basic systems on our own.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 5 0 0]...No good. If only it wasn't so late at night...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 6 0 0]I'm sorry. I tried contacting the lab, but they're unlikely to send help anytime soon.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 7 0 0]It's okay. I think I've almost got it...[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Is that it?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Her vitals are onscreen now! Let's see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 11 0 0]No... This can't be...[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Did you find something?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]Her synaptic circuits... They're completely burned out...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 14 0 0]There must have been a massive system overload that took her way over capacity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 15 0 0]I imagine it's related to her gaining the ability to use multiple Personas...[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Burned out? But... She can be fixed, right?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 17 0 0]It would be easy enough to replace the necessary parts, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 18 0 0]The Aigis we know is already... gone.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]No...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 32 53 65535 0 0][uf 3 1 1 0 0 21 0 0]Mm...[n][uf 1 1][e]

[msg MSG_014_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 22 0 0]Did you... call my name?[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Aigis![n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 53 65535 0 0][uf 3 1 1 0 0 24 0 0]Um... Did something happen?[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Geez! Way to give us a heart attack, you sleepyhead![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]You took so long to wake up, we thought you were dead...[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 27 0 0]But... How?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Her synaptic circuits shouldn't even be receiving power anymore...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 29 0 0]It's almost like... she's really alive.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 30 0 0]Um, I'm sorry if I caused you all concern.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 31 0 0]I was... having a dream. The first one in quite some time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 32 0 0]It was full of memories of the time I spent with everyone... and...[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 53 65535 0 0][uf 3 1 1 0 0 33 0 0]"Strength of heart, when united, is barred by no door"...[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 53 65535 0 0][uf 3 1 1 0 0 34 0 0]It's nothing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 53 65535 0 0][uf 3 1 1 0 0 35 0 0]Painful goodbyes may be one of the most difficult aspects of living...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 53 65535 0 0][uf 3 1 1 0 0 36 0 0]But I believe that spending time with those who care about you is one of the most joyous.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 53 65535 0 0][uf 3 1 1 0 0 37 0 0]I... really am lucky to have such wonderful friends.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 38 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 39 0 0]We were right next to each other, suffering over the exact same things...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 40 0 0]Looking back, I feel kinda stupid. Why did we ever think we were all alone?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 41 0 0]I guess we're more alike than we thought.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 1 0 0 42 0 0]Man... Is this nightmare finally over? We're not gonna wake up and see April 1st again, are we?[n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 43 0 0]Hey, quit tempting fate, would you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 44 0 0]In any case... That's it for now.[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 1 0 0 45 0 0]Aw, crap... With the danger gone, I feel like I'm gonna pass out! I could practically sleep standing up...[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 46 0 0]Oh... Junpei-kun![n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 47 0 0]All right... Let's head back to our rooms and get some rest for tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 48 0 0]Was there anything else to take care of before we turn in?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 0 0 0 49 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 50 0 0]Actually, there is one thing I'd like to announce.[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 51 0 0]With regard to collecting everyone's Evokers... I'd like to reverse that decision.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 52 0 0]This whole incident gave me a lot to think about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 53 0 0]In a way, I may have been trying to bury the past by collecting the symbols of our power and locking them away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 54 0 0]But even with no Shadows left to fight, we remain in a battle against ourselves.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 55 0 0]So... Everyone should hold onto their own.[n][uf 1 1][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 56 0 0]Until the day when everyone can change...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 52 65535 0 0][uf 3 1 1 0 0 57 0 0]...Right?[n][uf 1 1][e]

