[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]I'm so sorry I'm making you leave the movie partway through...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]I just... I couldn't focus on the movie because I kept worrying that...[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]I-I was afraid that I might see that guy from before who tried to, um...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'd help you again.[e]
[uf 0 5 65278][uf 2 1]It could happen anytime.[e]
[uf 0 5 65278][uf 2 1]Don't let it bother you.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11451 0 0][uf 5 13 9 30 109]R-Right. I'm sure I'll be fine if I'm with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Oh, but please try not to get into any fights. I don't want you to get hurt.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Chihiro is smiling.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11489 0 0]H-Hey! Please don't say things like that! It was really scary last time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]First you help me, and now you try to scare me... I don't understand you sometimes...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]It looks like I made Chihiro upset.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11493 0 0][uf 5 13 9 15 109]Y-Yeah, I'll try... I mean, it's not like it was here that we ran into him before anyway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]I'm sorry I was so distracted today. It was rude of me, wasn't it?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Chihiro seems to be feeling[n]a little better now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11465 0 0]Oh, right. My mom asked me to buy some things for her on my way back...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]I should take care of that before it gets too dark. Thank you for today, [uf 4 1]-san.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I waved goodbye to Chihiro as she headed to[n]the strip mall, then I returned to the dorm.[n][uf 1 1][e]

