[msg MSG_000_0_0 [Someone's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Hey, [uf 4 1]![n][uf 1 1][e]

[msg MSG_000_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0]Let's walk home together.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 3 0 0]So, the coach told me my performance has been slipping.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 4 0 0]I know you didn't say anything. I just think he can tell something's up.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]How's your knee?[e]
[uf 0 5 65278][uf 2 1]Can you hide it?[e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 8 5 105]It's sore, sure, but I managed to make it through practice today.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 6 0 0]O-Oh, yeah! It's still sore, but, uh, I think can play it off like nothing's going on.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 7 0 0]He said I'd be suspended from the team if I'm hurt. But I told him I was fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 105 2 25 25]I've already missed practice three times this year! I'm gonna have to seriously step up my game![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 9 0 0]Otherwise, I won't be able to keep my promise to my nephew![n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]You have to get tougher![e]
[uf 0 5 65278][uf 2 1]You can't win like this.[e]
[uf 0 5 65278][uf 2 1]You need to take a break...[e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 8 15 105]You're right! In the end, it's the toughest one who wins![n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 5 13 8 5 105]You're right. I've fallen way behind by missing practice, anyway.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 12 0 0]I know you mean well, but that's not an option for me.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 13 0 0]I've decided that I'll take my chances for my nephew's sake.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 14 0 0]...Even if I mess up my knee for the rest of my life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 15 0 0]If that happens, I want you to be the next captain, [uf 4 1].[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto opened up about his decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0]It's, uh, not exactly the happiest topic.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]B-But that's just the worst-case scenario![n][uf 1 1][e]

[msg MSG_012_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 18 0 0]I'm gonna keep my promise and win the meet, then the nationals! Then I'll take care of my knee![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 19 0 0]Nothing can stop me now![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I walked part of the way[n]home with Miyamoto.[n][uf 1 1][e]

