[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Welcome back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]So, [uf 4 1], how was it?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]No problem.[e]
[uf 0 5 65278][uf 2 1]I don't know about this...[e]
[uf 0 5 65278][uf 2 1]I'm exhausted.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 3 0 0]I see. Well, if you gained confidence, that's the best thing you could have achieved.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Don't be discouraged.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]You completed your task, and that's something to be proud of.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 6 0 0]It must've hit you all at once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Don't worry, you'll get used to it.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Wow... I never knew I had that kinda power![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]But damn, why do I feel so exhausted?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 10 0 0]'Cause you were bouncing around like a little kid.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 11 0 0]You say that, but you look pretty tired yourself, Yuka-tan.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 12 0 0]This is different... It's like I'm having trouble breathing. What's going on?[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 13 0 0]That's the effect of the Dark Hour. You'll become fatigued more easily.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Don't worry. You'll get used to it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 15 0 0]I have to say, though... I'm surprised. You all did much better than I expected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 16 0 0]At this rate, they'll catch up to you in no time, Akihiko.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 17 0 0]Heh, we'll see about that.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]By combining my powers with the team's,[n]I was able to stand against the Shadows...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I sense a strong bond with them...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Just like Yukari and Junpei,[n]I feel tired as well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided that it would be best[n]to return to my room and rest...[n][uf 1 1][e]

