[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I spent some time working[n]with the student council.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The hours flew by as I[n]worked hard on my tasks.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I don't see Odagiri. Is he absent today?[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Um, no... I'm pretty sure he came to school today.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Then where is he?[n][uf 1 1][e]

[msg MSG_004_0_0 [Secretary]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1001]Probably busy playing Detective Asshole.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Ah, so this is what Fushimi was telling me about... I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 3 25 25]Well, his intentions are good, so you can't really blame him. But I understand how you feel.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]...Ah, you're all free to leave now. Good work today.[n][uf 1 1][e]

