[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I passed some time reading with Mitsuru...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]She's turning the pages intently...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 4 1 5]"A wise man harmonizes, but does not conform"... This story resonates no matter how many times I read it.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]By learning about the exploits[n]of renowned individuals, my[n][uf 4 30 0 1 1 0] have improved...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Whew, I think we've hit a good stopping place. Let's retire for the night.[n][uf 1 1][e]

