[msg MSG_000_0_0 [Unfriendly Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1011]...Hey, don't be like that. I know a place that'd be perfect for us, girl.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fan from Earlier]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1001]Please, just leave us alone! We're not interested.[n][uf 1 1][e]

[msg MSG_001_5_0 [Man Showing Off]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1012]One drink, that's all we're askin'. C'mon, it'll be fun.[n][uf 1 1][e]

[msg MSG_001_7_0 [Scared Fan]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1002]We said no, okay!?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]It's those girls from earlier.[e]
[uf 0 5 65278][uf 2 1]Are they being hit on...?[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 0 0 0 5 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]...Hey.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Leave them alone. You don't want the police to get involved, do you?[n][uf 1 1][e]

[msg MSG_007_0_0 [Unfriendly Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1011]Huh? Who the hell're you?[n][uf 1 1][e]

[msg MSG_008_0_0 [Man Showing Off]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1012]What, you wanna call the cops? Quit tryin' to act like a big man, you little punk.[n][uf 1 1][e]

[msg MSG_009_0_0 [Unfriendly Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1011]Yeah, it's time for you to piss off![n][uf 1 1][e]

[msg MSG_010_0_0 [Man Showing Off]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1012]You piece of—![n][uf 1 1][e]

[msg MSG_011_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1013]...Hold up.[n][uf 1 1][e]

[msg MSG_012_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1013]You got some slick moves. I bet you know how to fight, that right?[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]So what if I do?[n][uf 1 1][e]

[msg MSG_014_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1013]How about you and I go a few rounds? If ya ain't too busy, there's a spot around back.[n][uf 1 1][e]

[msg MSG_023_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1013]Whenever I see guys who think they're hot shit, all I wanna do is put 'em in their place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 1013]I bet a lotta people call you a tough guy, so how 'bout we put it to the test?[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MSG_025_0_0 [Lackey]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1014]What, is he scared now? Hahahaha![n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...See? I told you—nothing but trouble.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 4 2 25 25]Stay here. I'll be done in a minute.[n][uf 1 1][e]

[msg MSG_027_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 1013]What!? You think you're gonna beat me just like that!?[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Don't worry, I won't go all out against an amateur. It's gotta be a fair fight.[n][uf 1 1][e]

[msg MSG_029_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 1013]Agh...![n][uf 1 1][e]

[msg MSG_030_0_0 [Voice from Police Car]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]Hey, over there! Break it up![n][uf 1 1][e]

[msg MSG_031_0_0 [Tough Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 1013]...Tch. Let's beat it![n][uf 1 1][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 1][uf 3 1 1 0 0 27 0 0]...I told you, officer. They were the ones antagonizing us.[n][uf 1 1][e]

[msg MSG_032_5_0 [Young Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 1021]And I told you, we'll hear all about it down at the station.[n][uf 1 1][e]

[msg MSG_032_7_0 [Middle-Aged Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 1022]You're high school students, aren't you? We'll need your contact information to notify your parents about this.[n][uf 1 1][e]

[msg MSG_098_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 5 21 0 1086]If I could butt in...[n][uf 1 1][e]

[msg MSG_099_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Kurosawa-san![n][uf 1 1][e]

[msg MSG_102_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 21 0 1086]I'll handle these two. I've already cleared it with the brass.[n][uf 1 1][e]

[msg MSG_033_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 5 21 0 1086]...I don't know what's going on here, but you better not be starting any trouble.[n][uf 1 1][e]

[sel SEL_033_5_0 top]
[uf 0 5 65278][uf 2 1]There was no trouble.[e]
[uf 0 5 65278][uf 2 1]It wasn't our fault.[e]
[uf 0 5 65278][uf 2 1]That was a close call.[e]

[msg MSG_033_2_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 5 21 0 1086]Then why'd we get a report from two ladies saying you were attacked by a group of punks?[n][uf 1 1][e]

[msg MSG_033_4_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]They wanted to test my strength. I was just giving them what they wanted.[n][uf 1 1][e]

[msg MSG_033_6_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 5 21 0 1086]In the middle of a public street? You really need to think things through.[n][uf 1 1][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Heh, you didn't think we were in actual trouble, did you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 4 0 25 25]Even if things got tense, I'd never put you in danger.[n][uf 1 1][e]

[msg MSG_034_5_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 5 21 0 1086]Then why'd we get a report from two ladies saying you were attacked by a group of punks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 5 21 0 1086]If you want to show off to your buddy, there's a time and place for it.[n][uf 1 1][e]

[msg MSG_035_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 5 21 0 1086]Listen, I'm an officer of the law. I don't care who you are—anyone who disturbs the peace is gonna have to deal with me.[n][uf 1 1][e]

[msg MSG_036_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 5 21 0 1086]As you can see, your friend here is a bit of a hothead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 5 21 0 1086]I know it won't be easy, but try and keep an eye on him, would you?[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Leave it to me.[e]
[uf 0 5 65278][uf 2 1]I'm not sure I can.[e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Those are some bold words. But thanks.[n][uf 1 1][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Don't worry about it. I know how to pick my battles.[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]My arm's healed, and we've got way more dependable people now. There's no better time to test my strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Especially now that we have someone like you. We really lucked out on that one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]So I'm gonna keep honing my skills. That way, I can put down anyone I face with my own two hands.[n][uf 1 1][e]

[msg MSG_041_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 5 21 0 1086]You really haven't changed at all...[n][uf 1 1][e]

[msg MSG_042_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 5 21 0 1086]In any case, don't get in over your heads.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0][uf 5 21 0 1086]I have a hunch the guys you ran into were from a gang that's been active around here recently.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 5 21 0 1086]Just be careful. You don't wanna get on their bad side, because once you're on it, you'll never get off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0][uf 5 21 0 1086]All right, it's late. You'd better head on home.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]So much for eating out. It's been nonstop interruptions all night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Kurosawa-san's right, though. We should probably head home. Sorry about this—I'll treat you some other time.[n][uf 1 1][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]I'm gonna do some jogging on the way back. You wanna join?[n][uf 1 1][e]

[sel SEL_045_0_0 top]
[uf 0 5 65278][uf 2 1]Sure...[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Good answer. It's dark, so watch out for cars.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]I'm gonna run ahead. You just follow at your own pace![n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I ran back to the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my stamina has improved[n]after running that long of a distance...[n][uf 1 1][e]

[msg SYS_HPUP_0_0]
[uf 0 5 65278][uf 2 1]Max HP increased by 5.[n][uf 1 1][e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]You sure? You'd get home faster if you did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]Well, I'm goin' ahead. Be careful on your way back![n][uf 1 1][e]

[msg MND_049_0_0]
[uf 0 5 65278][uf 2 1]I saw Sanada off, then[n]went back to the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]My mind feels sharper after[n]seeing Sanada's stoic expression...[n][uf 1 1][e]

[msg PFM_SPUP_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 61 0 0]Max SP increased by 3.[n][uf 1 1][e]

