[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Come with me.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Metis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_YUKARI_PARTY_IN_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1006 0 0]Let's get this over with quick. What do you say?[n][uf 1 1][e]

[msg MSG_YUKARI_PARTY_IN_AFTE [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]All right, got it.[n][uf 1 1][e]

[msg MSG_YUKARI_PARTY_OUT_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]No time to waste.[n][uf 1 1][e]

[msg MSG_YUKARI_PARTY_OUT_AFT [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Oh, all right...[n][uf 1 1][e]

[msg MSG_YUKARI_PARTY_OVER_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]I don't think there's an open spot, though...[n][uf 1 1][e]

[msg MSG_YUKARI_PARTY_CHANGE [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Who should I switch with?[n][uf 1 1][e]

