[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Add to party[e]
[uf 0 5 65278][uf 2 1]Remove from party[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Metis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_FUKA_BACK_UP_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]I'll support you all from here. Now, is there anything I can do for you?[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_RE_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Anything else?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I believe the furthest you've gotten is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Malebolge is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Cocytus is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Caina is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Antenora is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Ptolomea is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_06 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Judecca is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_07 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It seems the furthest you can explore Empyrean is floor [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_START [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Let's see... You're about to start exploring, right? Let's proceed slowly but surely.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_ADD_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Please explore as much as you can for now.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_ADD_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]There must be something to that floor... Could you look into it some more?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_ADD_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]You should be done exploring this area. Could you maybe try another door?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSYS_END_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5092 0 0]A new door... And it'll take us to where we'll be fighting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]What do I do...?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSYS_END_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5116 0 0]...Sorry. I'm still trying to process all of this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0]Is this really for the best...?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSYS_END_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0][uf 3 1 3 0 65535 5025 0 0]We'll have to fight Yukari-chan and Kirijo-senpai next... Then it'll all be over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0]Stay strong, Aigis. I'll be with you all the way.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSYS_END_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Whatever's on the other side of that door... We'll all face it—together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0]I might not be able to do much aside from providing support, but I want to witness the truth for myself![n][uf 1 1][e]

[msg MSG_FUKA_FIELDATTACK_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5002 0 0]Oh, about what you found during your exploration—I'd like to take a closer look over at the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Could you give me some time once we're back? Thanks, Aigis.[n][uf 1 1][e]

