[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Come with me.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Metis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_METIS_PARTY_IN_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]Let's go, Sister![n][uf 1 1][e]

[msg MSG_METIS_PARTY_IN_AFTER [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]You can count on me![n][uf 1 1][e]

[msg MSG_METIS_PARTY_OUT_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Oh... I'm not coming with you this time?[n][uf 1 1][e]

[msg MSG_METIS_PARTY_OUT_AFTE [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Oh, of course... If that's what you want, Sister.[n][uf 1 1][e]

[msg MSG_METIS_PARTY_OVER [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]I would, but... It looks like there's no open spot?[n][uf 1 1][e]

[msg MSG_METIS_PARTY_CHANGE [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Who should I switch with?[n][uf 1 1][e]

