[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Come with me.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Metis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_KOROMARU_PARTY_IN_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_AF [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_A [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0]*whine*[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OVER_ [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_CHANG [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_KOROMARU_SEEOFF_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0]Arf![n][uf 1 1][e]

[msg MND_KOROMARU_SEEOFF_01]
[uf 0 5 65278][uf 2 1]Koromaru-san certainly seems[n]to be in high spirits...[n][uf 1 1][e]

