[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Come with me.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Metis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[msg MSG_JUNPEI_PARTY_IN_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2002 0 0]Need my help, do ya?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Hell yeah. Leave it to ol' Junpei![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]Let's get this show on the road, Ai-chan.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]Aight, whatever you say.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Uh... Looks like you've got a full party![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]Oh, you want me to swap places with someone? Sure thing. Who?[n][uf 1 1][e]

[msg MSG_JUNPEI_SEEOFF [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Let me n' Koromaru take care of this. We'll find a supply route in no time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Seriously, you can rest easy with us on the case, Ai-chan. Just focus on exploring![n][uf 1 1][e]

