[msg MSG_IKUTSUKI_0707 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 70 0 0][uf 3 1 3 0 65535 14210 0 0]Don't worry, I know you can do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 70 0 0]Just be careful. Well, you better be off.[n][uf 1 1][e]

[msg MSG_IKUTSUKI_1103 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 70 0 0][uf 3 1 3 0 65535 14227 0 0]The day I've been waiting for has finally come.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 70 0 0]I'll leave the rest to you all. A new future is upon us...[n][uf 1 1][e]

[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Add to your party[e]
[uf 0 5 65278][uf 2 1]Remove from your party[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Ask about the target[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head to Club Escapade[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head toward the station[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[msg MSG_1103_MITURU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 70 0 0]Well then, we're off.[n][uf 1 1][e]

[msg MSG_1103_IKUTSUKI_01 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 70 0 0]All right. Be careful.[n][uf 1 1][e]

[msg MSG_1103_MITURU_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 70 0 0]Let's go![n][uf 1 1][e]

[msg MND_LEADER_NEARLY_DEAD]
[uf 0 5 65278][uf 2 1]He seems to be unconscious.[n][uf 1 1][e]

