[msg MSG_718_1_1 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 2 1 1 211]You needn't hurry. The moment we await is predestined.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 1 65535 65535 0 0][uf 3 1 1 0 2 2 1 211]It makes no difference whether it comes sooner or later.[n][uf 1 1][e]

[msg MSG_718_1_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 1 0 2 3 0 3]I got some words for you bastards... But today, we're here to save the world![n][uf 1 1][e]

[msg MSG_718_1_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Please be careful! I sense an even greater power than before![n][uf 1 1][e]

[msg MSG_718_2_1 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 11 65535 65535 0 0][uf 3 1 1 0 2 4 1 211]Even as I speak, I can feel it. The end of everything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 11 65535 65535 0 0][uf 3 1 1 0 2 5 1 211]I pity those who cannot see the blessing it truly is.[n][uf 1 1][e]

[msg MSG_718_3_1 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 1 65535 65535 0 0][uf 3 1 1 0 2 6 1 211]We are mere mortals; we cannot change our fate.[n][uf 1 1][e]

[msg MSG_718_3_2 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 2 7 1 211]I don't like the look in your eyes... What is it that you see before you now?[n][uf 1 1][e]

[sel SEL_718_3_3 top]
[uf 0 5 65278][uf 2 1]A promise with my friends.[e]
[uf 0 5 65278][uf 2 1]Hope for tomorrow.[e]
[uf 0 5 65278][uf 2 1]Only the opponent in front of me.[e]

[msg MSG_718_3_4 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 2 65535 65535 0 0][uf 3 1 1 0 2 8 1 211]A promise. That's truly ridiculous. How absurd... I can't bear to watch you all![n][uf 1 1][e]

[msg MSG_718_3_5 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 2 65535 65535 0 0][uf 3 1 1 0 2 9 1 211]Hope. That's truly ridiculous. How absurd... I can't bear to watch you all![n][uf 1 1][e]

[msg MSG_718_3_6 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 11 65535 65535 0 0][uf 3 1 1 0 2 10 1 211]An admirable spirit. That's right... That's how it should be![n][uf 1 1][e]

[msg MSG_718_4_1 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 4 65535 65535 0 0][uf 3 1 1 0 2 11 1 211]Why...? Fate is supposed to have chosen me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 4 65535 65535 0 0][uf 3 1 1 0 2 12 1 211]This again... Is my resolve still not strong enough...?[n][uf 1 1][e]

[msg MSG_718_4_2 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 11 65535 65535 0 0][uf 3 1 1 0 2 13 1 211]If so... I'll throw away my trivial pride![n][uf 1 1][e]

[msg MSG_718_4_4 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 2 65535 65535 0 0][uf 3 1 1 0 2 14 1 211]With my entire being! [uf 4 3]! I will bring you to your knees![n][uf 1 1][e]

[msg MSG_718_4_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 65535 0 0]Ah! Everyone has been struck by fear! I have a bad feeling about this! Please get up![n][uf 1 1][e]

[msg MSG_718_5_1 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 1 65535 65535 0 0][uf 3 1 1 0 2 15 1 211]Hahaha... It seems we are destined to be at odds...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 1 65535 65535 0 0][uf 3 1 1 0 2 16 1 211]How can you summon such power even in the face of death...? Incorrigible, as always...[n][uf 1 1][e]

[msg MSG_718_6_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]This isn't about revenge... We're fighting to protect something.[n][uf 1 1][e]

[msg MSG_718_7_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 65535 65535 0 0]What the hell...? Why can he use Theurgy!?[n][uf 1 1][e]

[msg MSG_718_7_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 5 65535 65535 0 0]I have to heal everyone... quickly...![n][uf 1 1][e]

