[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Screen Shot Movie Theater...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]There are many more moviegoers[n]than usual today...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I worked tirelessly attending to[n]the endless flow of customers...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I spent a long time listening to[n]a film buff talk about movies...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I got all kinds of questions from customers,[n]but I was able to answer all of them...![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]There were frequent incidents of customers[n]bickering, but I handled them with poise...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I made public announcements about lost[n]items, even though I wasn't used to it...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I delivered popcorn to a customer in the[n]middle of a horror movie screening...![n][uf 1 1][e]

[msg MSG_009_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]Thanks for working through such a tough day. I'll be raising your hourly rate.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Since I'm getting the hang of things,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_011_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]You're really a one-of-a-kind worker! I hope you continue to stop by and help out![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Since I've gotten better at my work,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_013_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]Phew, what a day. Here's your paycheck.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I feel like I've improved my [uf 4 30 0 1 1 0][n]and [uf 4 30 2 1 1 0] because of work...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

