[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]No[e]

[sel SEL_ORDER top]
[uf 0 5 65278][uf 2 1]Use Fuuka's skill[e]
[uf 0 5 65278][uf 2 1]Check current situation[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel FSS_FUKA_ORDER top]
[uf 0 5 65278][uf 2 1][uf 2 4 6] / [uf 2 4 7] SP[e]
[uf 0 5 65278][uf 2 1][uf 2 4 8] / [uf 2 4 9] SP[e]
[uf 0 5 65278][uf 2 1][uf 2 4 10] / [uf 2 4 11] SP[e]
[uf 0 5 65278][uf 2 1][uf 2 4 12] / [uf 2 4 13] SP[e]
[uf 0 5 65278][uf 2 1][uf 2 4 14] / [uf 2 4 15] SP[e]
[uf 0 5 65278][uf 2 1]What's the situation?[e]

[sel SEL_FUKA_YESNO top]
[uf 0 5 65278][uf 2 1]That'd be great.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MSG_MITSURU_RETURN_ADVIC [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It's too dangerous to go alone. Come back and choose teammates to fight at your side.[n][uf 1 1][e]

[msg MSG_FUKA_RETURN_ADVICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's not safe to go alone. Please come back and form a party![n][uf 1 1][e]

[msg MSG_MITSURU_NOT_ORDER_BT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Anything could happen. Keep your guard up.[n][uf 1 1][e]

[msg MSG_FUKA_NOT_ORDER_BTL [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Keep an eye out and be ready for anything.[n][uf 1 1][e]

[msg MSG_MITSURU_NOT_ORDER_NO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]I don't detect any enemies on this floor. I believe you'll be safe for now.[n][uf 1 1][e]

[msg MSG_FUKA_NOT_ORDER_NOBTL [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]I don't sense any enemies around. You should be safe on this floor.[n][uf 1 1][e]

[msg MSG_MITU_ORDER_IN_GATE_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4025 0 0]The path forward has opened. Exercise caution as you proceed.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_IN_GATE_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5020 0 0]Looks like we can keep going.[n][uf 1 1][e]

[msg MSG_MITU_ORDER_IN_GATE_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]You should be able to progress further... Could you take a closer look?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_IN_GATE_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5020 0 0]Has the path opened up yet? Could you please get closer and check it out?[n][uf 1 1][e]

[msg MSG_MITU_ORDER_IN_GATE_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4112 0 0]Looks like you can't progress any further. Let's wait for the right time before we try again.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_IN_GATE_0_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I don't think it's possible to go any farther than this for now... I guess all we can do now is wait.[n][uf 1 1][e]

[msg MSG_MITU_ORDER_IN_HIGH_R [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Keep a lookout for the enemy that escaped earlier.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_IN_HIGH_R [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Try to look for the enemy that escaped earlier![n][uf 1 1][e]

[msg MSG_FUKA_SUPPORT_SKILL_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5009 0 0]What is it?[n][uf 1 1][e]

[msg MSG_FUKA_SUPPORT_SKILL_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]Do you need my help?[n][uf 1 1][e]

[msg MSG_FUKA_SUPPORT_SKILL_0_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 20131 0 0]Did you need something?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_FIRST [Mitsuru Kirijo]]

[msg MSG_FUKA_ORDER_ESCAPE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. Are you sure you want to return to the entrance right now?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_ESCAPE_DO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Roger that! Then please stay put.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_ESCAPE_NO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]I'm sorry, but... it looks like my ability can't be used there.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SEARCH [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. You want information on this floor, correct?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SEARCH_DO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]Okay, I'll run a search and display what information I can find, then.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SEARCH_NO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]I'm sorry, but... it looks like my ability can't be used there.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SEARCH_DO_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]We've already gathered all the information we can on this floor, so there's no need for that.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_JAMMING [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. You don't want to be detected by the enemies on this floor, right?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_JAMMING_D [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Okay! This won't work on all enemies, so please exercise caution.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_JAMMING_N [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]I'm sorry, but... looks like this won't have any effect there.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_JAMMING_D_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Jamming is still in effect, so we don't need to activate it again![n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SFAURA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. You want to boost your defense and speed, right?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SFAURA_DO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Okay! Just keep in mind that these boons will only take effect in the next battle.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SFAURA_DO_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5064 0 0]That's still in effect right now, so we don't have to activate it again. It'll show during the next battle![n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SHOCKN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. You want to scare all the enemies on this floor, right?[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SHOCKN_DO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5117 0 0]Okay, here goes nothing![n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SHOCKN_NO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]I'm sorry, but... looks like this won't have any effect there.[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_SHOCKN_DO_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I've already used Shock Noise on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It may not affect any more enemies. Are you sure you want to use it again?[n][uf 1 1][e]

[msg MSG_FUKA_NOT_ENOUGH_SP [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5058 0 0]I'm sorry, but I don't have enough energy...[n][uf 1 1][e]

[msg MSG_FUKA_ORDER_RESTART [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Do you need anything else?[n][uf 1 1][e]

[msg MSG_TARTARUS_FIRST_TRY_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4585 0 0]Defeat all the Shadows on the floor.[n][uf 1 1][e]

[msg MSG_TARTARUS_FIRST_TRY_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Since there aren't any enemies at the moment, there's no need to issue that order.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Now's a good time to instruct your party members to split up.[n][uf 1 1][e]

[msg MSG_TARTARUS_FIRST_TRY_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4565 0 0]There are no enemies left to defeat. Use the teleporter to return to the entrance.[n][uf 1 1][e]

[msg TRL_TARTARUS_FIRST_TRY_H]
[uf 0 5 65278][uf 2 1]DEV: Display help on instructions to split up at this time.[n][uf 1 1][e]

[msg MSG_F031_OPERATION_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4143 0 0]I'm worried about the passengers, too. That's why we must secure the monorail immediately.[n][uf 1 1][e]

[msg MSG_F031_OPERATION_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4114 0 0]Fortunately, no one on the monorail was hurt...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]But why hasn't the enemy attacked us yet? Does that mean they're not attacking at random?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm not sure what the enemy is thinking... so proceed with caution.[n][uf 1 1][e]

[msg MSG_F031_OPERATION_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4099 0 0]Was the enemy waiting for this opportunity?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]It's too dangerous for Iori to be alone! Go after him![n][uf 1 1][e]

[msg MSG_F031_OPERATION_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4127 0 0]There's no time! Get to the front![n][uf 1 1][e]

[msg MSG_F031_OPERATION_05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4092 0 0]I can tell that the monorail has sped up from where I am, too![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]If it gets any faster, there won't be much time left until a collision![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]Concentrate on getting to the front, defeating the enemy, and stopping the train immediately![n][uf 1 1][e]

[msg MND_F052_OPERATION]
[uf 0 5 65278][uf 2 1]I can't contact Mitsuru. All I hear is static...[n][uf 1 1][e]

[msg MSG_THEURGIA_OPERATION_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]There's an enemy close by. Be careful![n][uf 1 1][e]

[msg MSG_THEURGIA_OPERATION_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]I still sense some enemies nearby. Keep an eye out if you decide to engage them.[n][uf 1 1][e]

[msg MSG_THEURGIA_OPERATION_0_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Looks like you've defeated all the Shadows on this floor. Please look for the stairs that'll take you up.[n][uf 1 1][e]

[msg MSG_THEURGIA_OPERATION_0_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]Something feels off on the floor above us... If you're going up, proceed with caution.[n][uf 1 1][e]

[msg MSG_F034_OPERATION_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]The target is on the third floor. Please hurry![n][uf 1 1][e]

[msg MSG_F034_OPERATION_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]Good job. It should be safe for you to return now.[n][uf 1 1][e]

[msg MSG_F034_OPERATION_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5091 0 0]Be careful! There seems to be a Shadow in that room still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But... where is it?[n][uf 1 1][e]

[msg MSG_F034_OPERATION_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]I'll see what I can find out, so please join up with the others for now.[n][uf 1 1][e]

[msg MSG_F034_OPERATION_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]I sense something similar to a Shadow coming from the mirror.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please break the mirror![n][uf 1 1][e]

[msg MSG_F034_OPERATION_06 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]There should be something different about the mirrors we're looking for... Take a closer look and see if you can find out what it is.[n][uf 1 1][e]

[msg MSG_F034_OPERATION_07 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]Break any mirror that doesn't show your own reflection![n][uf 1 1][e]

[msg MSG_F034_OPERATION_08 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5020 0 0]The seal is broken! Head to the target right away![n][uf 1 1][e]

[msg MSG_F035_OPERATION_START [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I'm picking up two powerful readings from our target somewhere below you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's like the two signals are overlapping, forming one giant mass.[n][uf 1 1][e]

[msg MSG_F035_OPERATION_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]The target is heading downward.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please go after it![n][uf 1 1][e]

[msg MSG_F035_OPERATION_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]The target is waiting at the end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please be careful![n][uf 1 1][e]

[msg MSG_TAR_ARRIVAL_FLOOR_MI [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4065 0 0]The furthest you've gotten is floor [uf 2 4 0].[n][uf 1 1][e]

[msg MSG_TAR_ARRIVAL_FLOOR_FU [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]I believe the highest you've gotten is floor [uf 2 4 0].[n][uf 1 1][e]

[msg MSG_TAR_REAPER_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4143 0 0]The Reaper has appeared! Retreat immediately![n][uf 1 1][e]

[msg MSG_TAR_REAPER_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5103 0 0]The Reaper showed up! Please run![n][uf 1 1][e]

[msg MSG_TAR_REAPER_WARNING_M [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 3 0 65535 4099 0 0]These readings...!? It's getting closer![n][uf 1 1][e]

[msg MSG_TAR_REAPER_WARNING_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5120 0 0]I sense something powerful, and it's approaching quickly![n][uf 1 1][e]

[msg MSG_TAR_MISNPC [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]There's someone on this floor! Please rescue them![n][uf 1 1][e]

[msg MSG_TAR_MISNPC_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]There's something on this floor. It's... a person? Please look for them![n][uf 1 1][e]

[msg MSG_TAR_FDOOR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Looks like one of those doors is on this floor. Maybe we should go look for it.[n][uf 1 1][e]

[msg MSG_TAR_ACCIDENT_00_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4104 0 0]Something different is happening on this floor. Stay alert.[n][uf 1 1][e]

[msg MSG_TAR_ACCIDENT_00_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]There's something different about this floor. Please be careful.[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_00_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4115 0 0]The path forward has opened up. Exercise caution as you proceed.[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_00_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Looks like there's more to this path. Let's keep going.[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_01_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4143 0 0]You should be able to progress further... Could you take a closer look?[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_01_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5020 0 0]Has the path opened up yet? Could you please get closer and check it out?[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_02_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Looks like you can't progress any further. Let's wait for the right time before we try again.[n][uf 1 1][e]

[msg MSG_TAR_ENDGATE_02_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I don't think it's possible to go any farther than this for now... I guess all we can do now is wait.[n][uf 1 1][e]

[msg MSG_TAR_GK_DEFEATED_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]The enemy has been annihilated. Let's move on.[n][uf 1 1][e]

[msg MSG_TAR_GK_DEFEATED_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You've already defeated the enemy here. Let's get moving![n][uf 1 1][e]

[msg MSG_TAR_GK_EXIST_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I sense a powerful enemy up ahead. Make sure you're well-prepared before entering battle.[n][uf 1 1][e]

[msg MSG_TAR_GK_EXIST_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's an enemy blocking the path up ahead, and a tough one at that. Get ready for battle.[n][uf 1 1][e]

[msg MSG_TAR_JIN_DEFEATED [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm picking up a human presence on the 263rd floor. It must be the last member of Strega.[n][uf 1 1][e]

[msg MSG_TAR_JIN_EXIST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense someone on the 259th floor. I'm positive it's a member of Strega... Please be careful.[n][uf 1 1][e]

[msg MSG_TAR_TAKAYA_DEFEATED [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We finally did it... We finally conquered this enormous tower.[n][uf 1 1][e]

[msg MSG_TAR_TAKAYA_EXIST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Looks like the last member of Strega, the leader, is on the 263rd floor.[n][uf 1 1][e]

[msg MSG_TAR_NYX_EXIST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]We've finally made it to the top of Tartarus... where we'll have our final battle.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_ENDGATE_MIT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We've almost reached the end of this area. Let's press on.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_ENDGATE_FUK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We're almost at the end of this area! Just hang on, everyone![n][uf 1 1][e]

[msg MSG_TAR_MIDDLE_ENDGATE_M [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We've made decent progress in this area, but we still have a bit of ground to cover.[n][uf 1 1][e]

[msg MSG_TAR_MIDDLE_ENDGATE_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We've made a lot of progress. Just a little more, and we'll reach the next area![n][uf 1 1][e]

[msg MSG_TAR_FAR_ENDGATE_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You've defeated the stronger enemies in this area, but there's still a ways to go until you reach the end of it.[n][uf 1 1][e]

[msg MSG_TAR_FAR_ENDGATE_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You've cleared out all of the powerful enemies in this area. Let's try to get as close as we can to the next area.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_GK_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's a strong enemy nearby. Brace yourself for battle.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_GK_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense a strong enemy close by! It might be a good idea to prepare for battle.[n][uf 1 1][e]

[msg MSG_TAR_MIDDLE_GK_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm getting readings from a strong enemy. We're still far from it, but don't let your guard down.[n][uf 1 1][e]

[msg MSG_TAR_MIDDLE_GK_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense a strong enemy a little further up... Please take care when exploring.[n][uf 1 1][e]

[msg MSG_TAR_FAR_GK_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Looks like it'll be some time until we cross paths with the next strong enemy. Tread carefully.[n][uf 1 1][e]

[msg MSG_TAR_FAR_GK_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It'll be a while until we encounter the next strong enemy, but please remain vigilant while exploring.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_JIN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense someone on the 259th floor! I think it's a member of Strega, so please be careful![n][uf 1 1][e]

[msg MSG_TAR_NEAR_TAKAYA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense a person on the 263rd floor... It must be Takaya. Looks like it's time to settle the score with him.[n][uf 1 1][e]

[msg MSG_TAR_NEAR_NYX [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We're nearly at the top floor... And then it'll be time for our final battle.[n][uf 1 1][e]

[msg MSG_Monad_NotDiscovery [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]I sense something completely new... It doesn't seem to be a Shadow.[n][uf 1 1][e]

[msg MSG_Monad_NotAccess [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It's a huge door... I wonder what we'll find inside.[n][uf 1 1][e]

[msg MSG_Monad_BackEntrance [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Please return for now. I'd like to go over the information we have on the door.[n][uf 1 1][e]

[msg MSG_Monad_NowIn [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]The atmosphere here feels different from the usual floors we explore... Please proceed carefully.[n][uf 1 1][e]

[msg MSG_MonadPass_NotAccess [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Let's investigate the door. Maybe we can figure out what makes this one different from the rest.[n][uf 1 1][e]

[msg MSG_MonadPass_NowIn [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]The tension is so thick, it's almost suffocating...[n][uf 1 1][e]

[msg MSG_JinFloor_NotDefeat [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]I can sense Strega's presence just up ahead. Please proceed with caution.[n][uf 1 1][e]

[msg MSG_JinFloor_Defeated [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]There's another person on the 263rd floor... It must be the other member of Strega.[n][uf 1 1][e]

[msg MSG_TakayaFloor_NotDefea [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Seems like the leader of Strega is just up ahead.[n][uf 1 1][e]

