[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel exhausted... Maybe it's because[n]I haven't gotten used to living here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Just who was that old man from[n]the dream I had last night...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]And what was that "contract" all about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

