[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Wha...!?[n][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Father...[n][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Father![n][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Urgh... Blasted...[n][e]

[msg MSG_003_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Aigis... Execute the sacrifices now![n][e]

[msg MSG_003_7_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]I'm putting an end to this...![n][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 7 0 0]......[n][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Aigis![n][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]Hey c'mon, I know you wouldn't do this![n][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 10 0 0]......[n][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]Do it, Aigis![n][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]......[n][e]

[msg MSG_009_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]......[n][e]

[msg MSG_009_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 14 0 0]......[n][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]What the...?[n][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Aigis![n][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Wha...!?[n][e]

[msg MSG_012_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]You good-for-nothing failure of a machine![n][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]I'll do it![n][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]...!?[n][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]Koromaru![n][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]It's all over, Chairman...[n][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 23 0 0]......[n][e]

[msg MSG_017_2_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]Hahaha... You don't get it, do you?[n][e]

[msg MSG_017_4_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]Why do you waste your time searching[n]for a reason to live in this broken world?[n][e]

[msg MSG_017_6_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]There's no point to it at all![n][e]

[msg MSG_046_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]The only possible way to fix this is to start over![n][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 28 0 0]......[n][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]Ahh...[n][e]

[msg MSG_020_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Yes... Yes, I was chosen![n][e]

[msg MSG_020_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]I'm going to be the god of the new world![n][e]

[msg MSG_020_7_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0]Hahahaha![n][e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]What a shame... I was so close...[n][e]

[msg MSG_022_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0]Hahaha.[n][e]

[msg MSG_023_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]Haha...[n][e]

