[msg MSG_Monad01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]*gasp* There it is![n][uf 1 1][e]

[msg MSG_Monad01_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 20134 0 0]Is this... a door? Could you please get a little closer to it for me?[n][uf 1 1][e]

[msg MSG_Monad02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 20131 0 0]Um, is something wrong? The door isn't that way.[n][uf 1 1][e]

[msg MSG_Monad04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 1 20136 0 0]Uh, please wait! There are only stairs up ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I really think we should figure out what's going on, so please come back for now.[n][uf 1 1][e]

