[sel SEL_BATTLE top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Give me a second.[e]

[msg MSG_VS_LEADER_BATTLE_OK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]If we head up from here, we'll reach the Promised Place, the summit of Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]This truly will be our final battle. Are you ready?[n][uf 1 1][e]

[msg MSG_NOT_ENOUGH [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]It's too dangerous to go without more people![n][uf 1 1][e]

[msg MSG_VS_LEADER_BATTLE_OK_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5008 0 0]This is it... Are you ready?[n][uf 1 1][e]

