[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Let's go.[e]
[uf 0 5 65278][uf 2 1]I'm not ready yet.[e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4116 0 0]It's enemy territory up ahead. Are you ready for battle?[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]The enemy is strong. Please make sure you're ready before fighting![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4001 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]Are you fully prepared?[n][uf 1 1][e]

