[msg MSG_RARE01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]Wait! Is that Shadow up ahead a...!?[n][uf 1 1][e]

[msg MSG_RARE01_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Please wait a moment! The Shadow up ahead might be a...[n][uf 1 1][e]

[msg MSG_RARE02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Well, now... That Shadow took off like a bandit, didn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Those ones are fairly rare... I suppose we can simply call them "rare Shadows."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]They can be tough to catch, but the potential rewards are worth the trouble.[n][uf 1 1][e]

[msg MSG_RARE02_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]It seems to have turned left up ahead. Why don't you try tracking it down?[n][uf 1 1][e]

[msg MSG_RARE02_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Wow, it took off quickly, didn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I believe that's an unusual breed called a "rare Shadow."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]They're real fast on the run, but catching them apparently yields big rewards.[n][uf 1 1][e]

[msg MSG_RARE02_02_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]It looks like it made a left up ahead. Would you mind pursuing it?[n][uf 1 1][e]

[msg MSG_RARE03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4001 0 0]Is something the matter? Track down that rare Shadow before it gets away.[n][uf 1 1][e]

[msg MSG_RARE03_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Please try tracking down that rare Shadow first.[n][uf 1 1][e]

[msg MSG_RARE04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4113 0 0]Ah, it seems to have escaped... I told you it'd be tough to catch, didn't I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Well, the next time you see one, I want you to try engaging it in battle.[n][uf 1 1][e]

[msg MSG_RARE04_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]Oh, it got away... They really are fast, aren't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If you see one again, try your best to catch up to it and fight it.[n][uf 1 1][e]

