[msg MSG_DISCOVERD_MONAD_DOOR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, please hold on a moment.[n][uf 1 1][e]

[msg MSG_DISCOVERD_MONAD_DOOR_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's one of those doors, but... Huh... This one isn't shining like the others.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It feels different, too...[n][uf 1 1][e]

[msg MND_DISCOVERD_MONAD_DOOR]
[uf 0 5 65278][uf 2 1]Is this the "structure" Elizabeth referred[n]to as "not dissimilar" to the other door...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should probably check this door...[n][uf 1 1][e]

[msg MSG_DISCOVERD_MONAD_DOOR_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Shall we take a look at it, Leader?[n][uf 1 1][e]

[sel SEL_DISCOVERD_MONAD_DOOR top]
[uf 0 5 65278][uf 2 1]Let's check it out.[e]
[uf 0 5 65278][uf 2 1]Yeah, watch out for me.[e]

[msg MSG_DISCOVERD_MONAD_DOOR_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. I'll keep watch for anything on my end.[n][uf 1 1][e]

[msg MSG_STOP_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5137 0 0]Oh, are we not going to take a closer look at that door?[n][uf 1 1][e]

[sel SEL_STOP top]
[uf 0 5 65278][uf 2 1]I was checking the perimeter.[e]
[uf 0 5 65278][uf 2 1]I just got lost for a second...[e]

[msg MSG_STOP_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Oh, I see. Well, do you want to check it now?[n][uf 1 1][e]

[msg MSG_DISCOVERD_STAIRS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]That's a long flight of stairs down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It leads deeper into the depths of Tartarus compared to the other doors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It's almost like it's luring us to go all the way in... It's a little disturbing...[n][uf 1 1][e]

[msg MSG_DISCOVERD_DOOR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Yet another door, even inside the first door... It feels like a very long pathway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's a layout I've never seen before. Please be careful as you go on.[n][uf 1 1][e]

[msg MSG_DISCOVERD_MONAD_DOOR_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5070 0 0]It's one of those doors again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Since the layout of this floor doesn't change, this door likely won't disappear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]So we can explore it anytime. We'll leave it up to you, Leader.[n][uf 1 1][e]

[msg MSG_DISCOVERD_ENEMY_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]I sense a Shadow up ahead![n][uf 1 1][e]

[msg MSG_REACTION_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 0 0 0]Huh... It doesn't look very strong...[n][uf 1 1][e]

[msg MSG_REACTION_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 0 0 0]Looks weak to me! Let's take it down quickly.[n][uf 1 1][e]

[msg MSG_REACTION_SANADA_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 0 0 0]It doesn't seem like a very strong opponent to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 0 0 0]All we have to do is beat this guy to move on?[n][uf 1 1][e]

[msg MSG_REACTION_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 0 0 0]It looks like we'll have to defeat it to continue on.[n][uf 1 1][e]

[msg MSG_DISCOVERD_ENEMY_FUKA_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It seems rather weak for a Shadow inside one of these doors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]I have a bad feeling about this... Please be fully prepared if you plan to battle it.[n][uf 1 1][e]

[msg SYS_TUTORIAL]
[uf 0 5 65278][uf 2 1]Strong Shadows exist behind this door as well. Defeating them will earn you rewards. If enemies are too strong, you can always try again later.[n][uf 1 1][e]

