[msg MSG_Darkzone_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Oh, look at that![n][uf 1 1][e]

[msg MSG_Darkzone_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There may be items worth gathering on this floor, so keep an eye out.[n][uf 1 1][e]

[msg MSG_Darkzone_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]Over there! Be careful—you're not alone![n][uf 1 1][e]

[msg MSG_Darkzone_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's hard to see anything in this darkness, but that goes for the enemy as well.[n][uf 1 1][e]

