[sel SEL_BATTLE top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MSG_VS_LEADER_BATTLE_OK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5076 0 0]There's one member of Strega left. If we want to proceed, we'll have to fight him...[n][uf 1 1][e]

[msg MSG_NOT_ENOUGH [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's too dangerous to go without more people![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]He seems to be unconscious.[n][uf 1 1][e]

[msg MSG_VS_LEADER_BATTLE_OK_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5076 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_Ask_Full_VoiceOff [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_Ask_NotFull_VoiceOn [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5076 0 0]There's an opening in your party... Are you sure you still want to go?[n][uf 1 1][e]

[msg MSG_Ask_NotFull_VoiceOff [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]There's an opening in your party... Are you sure you still want to go?[n][uf 1 1][e]

