[sel SEL_EXPLORATION top]
[uf 0 5 65278][uf 2 1]Resume from [uf 2 4 0]F[e]
[uf 0 5 65278][uf 2 1]Use the teleporter[e]
[uf 0 5 65278][uf 2 1]Don't use[e]

[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Yeah.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[sel SEL_CheckFull top]
[uf 0 5 65278][uf 2 1]Use the teleporter[e]
[uf 0 5 65278][uf 2 1]Don't use[e]

[msg MSG_ACCESS_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]You've currently explored up to floor [uf 2 4 0]. Where do you want to resume the expedition?[n][uf 1 1][e]

[msg MSG_ACCESS_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Looks like you've made it to floor [uf 2 4 0]. Where would you like to jump to now?[n][uf 1 1][e]

[msg MSG_THEURGIA_FUKA_OK_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_THEURGIA_FUKA_OK_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]I'll try to guide you to a more stable floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]I can't go with you, but I'll do my best to back you up from here![n][uf 1 1][e]

[msg MSG_START_MITSURU_OK_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Understood.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]As long as you follow my instructions, I'll be able to point you down a safe route.[n][uf 1 1][e]

[msg MSG_START_MITSURU_OK_11 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Floor [uf 2 4 0], you said? Understood. The teleporter should take you there right away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Stay safe out there.[n][uf 1 1][e]

[msg MSG_START_FUKA_OK_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Okay, got it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]I'll find a safe route for you to traverse, so just follow my directions.[n][uf 1 1][e]

[msg MSG_START_FUKA_OK_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]You want to go to floor [uf 2 4 0]? Okay, if you take the teleporter, you'll be there before you know it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Have a safe trip![n][uf 1 1][e]

[msg MSG_ADVICE_MITSURU_MAY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4073 0 0]There's something I need to tell you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Do you remember what I said? About Tartarus being divided into different areas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Well, through Penthesilea's power, I picked up on an unusual signal just past the 20th floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Something may have shifted, so I'd like you to head there and check it out immediately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We're counting on you.[n][uf 1 1][e]

[msg MSG_ADVICE_FUKA_MAY [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Leader, do you have a moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Do you remember how Kirijo-senpai said Tartarus is divided into different areas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Well, one of those areas should end on the 22nd floor, but I'm getting a funny signal from there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]It seems unstable, like it's about to move or something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]So, for today's exploration, I'd recommend investigating the 22nd floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Stay safe, and good luck.[n][uf 1 1][e]

[msg MND_WARP_FIRST]
[uf 0 5 65278][uf 2 1]The console is displaying[n]a series of numbers...[n][uf 1 1][e]

[msg MSG_WARP_FIRST_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Hmm, I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Go ahead and select the 1st floor on that device. That should bring you back.[n][uf 1 1][e]

[msg MSG_WARP_FIRST_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5079 0 0]Oh, how interesting![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Could you pick the 1st floor on that? I think that should bring you back here.[n][uf 1 1][e]

[msg MND_WARP_NOT_BOOT]
[uf 0 5 65278][uf 2 1]What is this? I've never seen[n]something like it before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Regardless, it doesn't seem to[n]be functioning right now.[n][uf 1 1][e]

[msg MND_WARP_NOT_BOOT_2]
[uf 0 5 65278][uf 2 1]Apparently, using a one-way teleporter[n]in Tartarus brings me back here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't seem like I can use one to[n]return to the floor I came from, though.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10099 0 0]Thanks to Yamagishi, I can explore with you too. But I'd still like to stick to the four-person strategy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10100 0 0]Just so we have backup or anyone who can come to our aid in the event of an emergency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10101 0 0]And don't forget what happened during the last full moon. We can't leave Yamagishi alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10102 0 0]I'll leave it up to you to decide on the party members. I know you can handle it.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 1 0 1 10103 0 0]I'll do everything I can to help. Let's give it our best![n][uf 1 1][e]

[msg DESC_FLOOR21_NG_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4032 0 0]Hold on a moment... All right, the path ahead is safe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]...And I'm curious what's on the next floor. Please continue forward.[n][uf 1 1][e]

[msg DESC_FLOOR21_NG_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Please wait just a second... Okay, it seems safe past here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'd like to know what's on the next floor. Would it be okay with you to keep going?[n][uf 1 1][e]

[msg MSG_Mitsuru_NotFull [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Are you all ready?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]I personally recommend bringing a full party whenever possible.[n][uf 1 1][e]

[msg MSG_Fuka_NotFull [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5008 0 0]Are you ready to start exploring?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Oh, um... Are you sure you don't want to bring a full party? Will you be okay?[n][uf 1 1][e]

