[msg MSG_DUNGE_FUKA_B2FKAISI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10069 0 0]I sense the target two blocks ahead of you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10070 0 0]It seems to be moving slowly downward.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10071 0 0]Don't let it get away![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B3FKAISI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10072 0 0]This place...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10073 0 0]It seems it was some kind of armory during the war.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10074 0 0]I've never seen so many weapons lying around before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10075 0 0]They were all designed to kill people...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10076 0 0]Having to kill others to survive...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10077 0 0]It's hard to believe a time like that is part of our history.[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B4FKAISI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10078 0 0]The target's gaining speed! It's continuing down the tunnel![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10079 0 0]Hurry and chase it down![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B5FKAISI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10080 0 0]The target's stopped![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10081 0 0]It turned around! It's waiting for us one block down![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 1 10082 0 0]Please be careful![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B1FNOTFUL [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]It's too dangerous to go without more people![n][uf 1 1][e]

[msg MND_DUNGE_TOBIRA_HAZIKI]
[uf 0 5 65278][uf 2 1]The door's too heavy to open.[n]I think we're trapped...[n][uf 1 1][e]

[msg MND_DUNGE_B2FLU_BED]
[uf 0 5 65278][uf 2 1]...That skeleton used to be somebody.[n][uf 1 1][e]

[msg MND_DUNGE_B2FRU_COBWEB]
[uf 0 5 65278][uf 2 1]There are cobwebs[n]stretching over the boxes...[n][uf 1 1][e]

[msg MND_DUNGE_B2FLD_CAMPIN]
[uf 0 5 65278][uf 2 1]Looks like canned food.[n][uf 1 1][e]

[msg MND_DUNGE_B2FRD_DESK]
[uf 0 5 65278][uf 2 1]Tables and boxes clutter the room...[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B8FHE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 1 10084 0 0]The target's up ahead![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 1 10085 0 0]Are you ready?[n][uf 1 1][e]

[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Yes, I'm ready.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MND_DUNGE_B2F_SKELETON_0]
[uf 0 5 65278][uf 2 1]There's a diary next to the skeleton's hand.[n][uf 1 1][e]

[msg MSG_DUNGE_B2F_SKELETON_0 [Diary Text]]
[uf 0 5 65278][uf 2 1]"We have toiled until our fingers bled in hopes of protecting our country... protecting my family..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"We've failed."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"But while the temptation to succumb to despair is strong, we cannot afford that luxury."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"The sky may boil crimson, but we shall persevere."[n][uf 1 1][e]

[msg MND_DUNGE_B2F_SENSYAPART]
[uf 0 5 65278][uf 2 1]Stacks of heavy artillery are stored here...[n][uf 1 1][e]

[msg MND_DUNGE_B2F_TAIHOU]
[uf 0 5 65278][uf 2 1]It's a huge, wheeled cannon.[n][uf 1 1][e]

[msg MND_DUNGE_B2F_CYLINDER]
[uf 0 5 65278][uf 2 1]These weapon parts look complicated...[n][uf 1 1][e]

[msg MND_DUNGE_B3F_WHEEL]
[uf 0 5 65278][uf 2 1]Some kind of large disk is resting here...[n][uf 1 1][e]

[msg MND_DUNGE_B3F_SKELETON]
[uf 0 5 65278][uf 2 1]There's a skeleton crushed[n]under the machinery...[n][uf 1 1][e]

[msg MND_DUNGE_B3F_SKELETON2_]
[uf 0 5 65278][uf 2 1]A diary with a desiccated lock[n]is lying near the skeleton.[n][uf 1 1][e]

[msg MSG_DUNGE_B3F_SKELETON2_ [Journal Text]]
[uf 0 5 65278][uf 2 1]"In the hopes that this message will reach my loved ones, I have sealed this journal for its protection."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"We few survivors have ensured the completion of our goal."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"So many of our cohorts will never know our success... I pray their spirits find rest in the wake of this turmoil."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"To my mother, my wife, and my children: please do not think that I have abandoned you."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"If securing your futures means giving my life, then I will have done so happily. Honor my memory by living."[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B21F_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10074 0 0]I've never seen so many weapons lying around before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10075 0 0]They were all designed to kill people...[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B21F_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10076 0 0]Having to kill others to survive...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10077 0 0]It's hard to believe a time like that is part of our history.[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B21F_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10072 0 0]This place...[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_B21F_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 1 10073 0 0]It seems it was some kind of armory during the war.[n][uf 1 1][e]

[msg MSG_DUNGE_AEGIS_B21F_01 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 1 20667 0 0]These tread marks... They're new.[n][uf 1 1][e]

[msg MSG_DUNGE_SANADA_B21F_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 1 20665 0 0]These tracks on the ground seem to be made recently...[n][uf 1 1][e]

[msg MSG_DUNGE_JUNPEI_B21F_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 1 20664 0 0]Huh? Why the hell are there tread marks?[n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_B21F_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4067 0 0]These might belong to our target... Let's keep an eye out.[n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_B21F_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4067 0 0]These could belong to the target... Stay alert, everyone.[n][uf 1 1][e]

[msg MND_DUNGE_ML_MEDAL_GET_0]
[uf 0 5 65278][uf 2 1]What's that on the ground...?[n][uf 1 1][e]

[msg MND_DUNGE_ML_MEDAL_GOT_0]
[uf 0 5 65278][uf 2 1]I haven't seen anything like this before...[n]I should hold onto it for now.[n][uf 1 1][e]

[msg MND_DUNGE_ML_MEDAL_GET_0_2]
[uf 0 5 65278][uf 2 1]Something's on the desk.[n][uf 1 1][e]

[msg MND_DUNGE_ML_MEDAL_GOT_0_2]
[uf 0 5 65278][uf 2 1]...?[n][uf 1 1][e]

[msg MND_DUNGE_B3F_SKELETON2__2]
[uf 0 5 65278][uf 2 1]...What are all these documents?[n][uf 1 1][e]

