[msg MSG_HIGHRARE_DEFEAT_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]The Shadow has been eliminated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I don't sense any other enemies nearby. Let's keep moving.[n][uf 1 1][e]

[msg MSG_HIGHRARE_DEFEAT_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The Shadow has been defeated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm not sensing any other enemies. Let's move on.[n][uf 1 1][e]

[msg MSG_HIGHRARE_ESCAPE_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Wait, the Shadow is making a move...[n][uf 1 1][e]

[msg MSG_HIGHRARE_ESCAPE_MITU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 50 0 0]...I don't sense it anymore. It seems it ran away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There don't appear to be other enemies around either. Well, let's keep moving.[n][uf 1 1][e]

[msg MSG_HIGHRARE_ESCAPE_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh! I'm sensing movement from the Shadow![n][uf 1 1][e]

[msg MSG_HIGHRARE_ESCAPE_FUKA_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]...I don't detect it anymore. I guess it ran away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There don't seem to be any other enemies around here, so let's move on.[n][uf 1 1][e]

[msg MSG_HIGHRARE_STEAL_MITU_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0]What!? It's ransacking the treasure chest![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]A Shadow that goes after treasure chests... I wonder why...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Also, it may be a coincidence, but there are more chests than usual on this floor.[n][uf 1 1][e]

[msg MSG_HIGHRARE_STEAL_FUKA_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]It's... stealing from the treasure chest!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Why would a Shadow do that? I wonder if it's searching for something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Oh, and there are more chests than usual on this floor. Is that just a coincidence?[n][uf 1 1][e]

[sel SEL_HIGHRARE_STEAL_00 top]
[uf 0 5 65278][uf 2 1]More chests, huh?[e]
[uf 0 5 65278][uf 2 1]Just a "coincidence"?[e]

[msg MSG_HIGHRARE_STEAL_MITU__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Hm... It would seem that the Shadow came specifically for the treasure chests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If that's the case, we could take advantage of its obsession with treasure.[n][uf 1 1][e]

[msg MSG_HIGHRARE_STEAL_FUKA__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Well, by the looks of it... the Shadow came here for those treasure chests.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If it loves treasure so much, maybe we could use that to our advantage![n][uf 1 1][e]

[msg SYS_HIGHRARE_STEAL_00]
[uf 0 5 65278][uf 2 1]Greedy Shadows appear on floors with many treasure chests. They will scurry around and open the treasure chests one after another.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They are quick and nearly impossible to catch on foot. Take advantage of their obsession and intercept them on their way to treasure chests.[n][uf 1 1][e]

[msg MSG_HIGHRARE_STEAL_MITU__3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]First, look for a treasure chest that the Shadow has yet to get its hands on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If we take its beloved treasure first, it will likely try to come after us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Once it gets close, we'll be able to strike![n][uf 1 1][e]

[msg MSG_HIGHRARE_STEAL_FUKA__3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]First, find a treasure chest that the Shadow hasn't gotten to yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It might come looking for us if we take the treasure it was after.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If it does, then we'll have a chance to fight it![n][uf 1 1][e]

[msg MSG_HIGHRARE_BLOCK_MITU_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Are you giving up on catching that Shadow?[n][uf 1 1][e]

[msg MSG_HIGHRARE_BLOCK_MITU__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]All right, then. Carry on.[n][uf 1 1][e]

[msg MSG_HIGHRARE_BLOCK_FUKA_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Oh, are you done trying to catch that Shadow?[n][uf 1 1][e]

[msg MSG_HIGHRARE_BLOCK_FUKA__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Okay, keep trying, then. You can do it![n][uf 1 1][e]

[sel SEL_HIGHRARE_BLOCK top]
[uf 0 5 65278][uf 2 1]I won't give up![e]
[uf 0 5 65278][uf 2 1]I guess I should keep trying.[e]

