[msg MSG_SHITT_ENEMY_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4069 0 0]There's a Shadow up ahead...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'll take this opportunity to teach you about Shifting.[n][uf 1 1][e]

[msg MSG_SHITT_ENEMY_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1086 0 0]I see. So, basically, we're working together to battle more effectively![n][uf 1 1][e]

[msg MSG_SHITT_ENEMY_JUNPEI [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2086 0 0]Aw snap! It'd be sweet if we could pull this kinda thing off a lot, huh?[n][uf 1 1][e]

[msg MSG_SHITT_ENEMY_01_END [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]In combat, you should be as coordinated as possible. Put it to good use.[n][uf 1 1][e]

