[msg MSG_Yakekuso_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5070 0 0]That Shadow seems especially aggressive, doesn't it?[n][uf 1 1][e]

[msg MSG_Yakekuso_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]I'm not sure why, but it appears to be agitated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's fast, but not well coordinated. Stay calm and dodge, and you should be fine.[n][uf 1 1][e]

