[msg AST_BattleEnd_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]I'm so glad we were able to win![n][uf 1 1][e]

[msg MND_Encount_Try01]
[uf 0 5 65278][uf 2 1]Should we challenge a strong foe...?[n][uf 1 1][e]

[sel SEL_Encount top]
[uf 0 5 65278][uf 2 1]Let's do it.[e]
[uf 0 5 65278][uf 2 1]Just a sec...[e]

[msg MSG_Encount_Try_Yukari [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 0 0 0][uf 3 1 3 0 65535 1128 0 0]It looks tough... Are you sure you wanna do this?[n][uf 1 1][e]

[msg MSG_Encount_Try_Junpei [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 0 0 0][uf 3 1 3 0 65535 2118 0 0]Alright, let's go for it![n][uf 1 1][e]

[msg MSG_Encount_Try_Sanada [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 0 0 0][uf 3 1 3 0 65535 3117 0 0]Seems like a worthy opponent. You ready?[n][uf 1 1][e]

[msg MSG_Encount_Try_Mitsuru [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 0 0 0][uf 3 1 3 0 65535 4117 0 0]It's a formidable opponent... Are you prepared?[n][uf 1 1][e]

[msg MSG_Encount_Try_Aegis [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 0 0 0][uf 3 1 3 0 65535 6117 0 0]The enemy appears to be significantly stronger than average. Awaiting your orders.[n][uf 1 1][e]

[msg MSG_Encount_Try_Amada [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 0 0 0][uf 3 1 3 0 65535 7119 0 0]I'm ready! Let's take it down![n][uf 1 1][e]

[msg MSG_Encount_Try_Aragaki [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 0 0 0][uf 3 1 3 0 65535 9109 0 0]Well? We goin'?[n][uf 1 1][e]

[msg MSG_Encount_Try_Fuka [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The battle ahead will be unavoidable. Are you sure you want to go on?[n][uf 1 1][e]

[msg MND_Encount_Tutorial]
[uf 0 5 65278][uf 2 1]Something welled up within me even[n]more than usual during battle...[n][uf 1 1][e]

[msg MSG_Encount_Tutorial_Fuk [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]I detect a Shadow ahead! It seems to be a very powerful one![n][uf 1 1][e]

[msg MSG_Encount_Tutorial_Fuk_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It looks like we have no choice but to fight it if we want to keep going...[n][uf 1 1][e]

[msg MSG_Encount_Tutorial_Fuk_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]I don't sense any more enemies around...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh! There's a treasure chest further ahead![n][uf 1 1][e]

[msg MSG_Encount_Tutorial_Fuk_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I wonder if that Shadow was guarding this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I don't think we've run into one like this before. Please inspect it.[n][uf 1 1][e]

[msg MSG_Encount_Tutorial_Fuk_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]It looks like we'll have to battle if we want to explore beyond here.[n][uf 1 1][e]

[sel SEL_TutoEncount top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Let's retreat for now.[e]

