[sel SEL_BATTLE top]
[uf 0 5 65278][uf 2 1]Let's go.[e]
[uf 0 5 65278][uf 2 1]Hang on a sec.[e]

[msg MSG_DUNGE_FUKA_STOP [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5092 0 0]This Shadow is too much for a crew so small. You could be killed![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_CONF [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]All right... This is it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_STOP_ESCA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5076 0 0]We can't afford to backtrack now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Let's take a moment to breathe, then prepare to engage.[n][uf 1 1][e]

