[sel SEL_BATTLE top]
[uf 0 5 65278][uf 2 1]Let's go.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MSG_VS_LEADER_BATTLE_OK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5128 0 0]He's waiting for us... The only way to get past him is to fight.[n][uf 1 1][e]

[msg MSG_NOT_ENOUGH [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's too dangerous to go without more people![n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Understood, let's go![n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Yes, let's make sure we're fully prepared before proceeding.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_Ask_NotFull_VoiceOn [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]There's an opening in your party... Are you sure you still want to go?[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4033 0 0]Don't hesitate. That's the least we can do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]There's no time to look back.[n][uf 1 1][e]

[msg MSG_Ask_Full_VoiceOff [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_Ask_NotFull_VoiceOff [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]There's an opening in your party... Are you sure you still want to go?[n][uf 1 1][e]

