[msg MSG_YUKARI_BIBIRU [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 1 10005 0 0]Geez, it's so quiet it's creepy...[n][uf 1 1][e]

[msg MSG_INAI_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10006 0 0]Junpei's not in this car, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10007 0 0]Come on...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10008 0 0]He should know it's too dangerous to go alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10009 0 0]Junpei was acting kind of strange, wasn't he? Why'd he snap and get so upset?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10010 0 0]Well, I guess we can ask him once we've caught up to him. Let's go![n][uf 1 1][e]

[msg MSG_CATCH_JUNPEI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 1 10011 0 0]There he is![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 1 10012 0 0]Oh no, he's surrounded by enemies! We gotta help him quick![n][uf 1 1][e]

[msg MSG_KASOKU_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 1 10013 0 0]What's happening!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 1 10014 0 0]No way... Is the train getting faster!?[n][uf 1 1][e]

[msg MND_KANOKE_MES]
[uf 0 5 65278][uf 2 1]No time for that now...[n][uf 1 1][e]

[msg MSG_KANOKE_MES_TEST [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]For the last train of the day, there are quite a few people on board.[n][uf 1 1][e]

[msg MSG_KANOKE_MES_CAPP [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1093 0 0]It's weird to think this is actually a person...[n][uf 1 1][e]

[msg MSG_HOUKOU_TIGAU_Y [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 1 10015 0 0]There's no time to go back! Come on![n][uf 1 1][e]

[msg MSG_SOTIJYANAI [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10016 0 0]You don't have time to go back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10017 0 0]If the Dark Hour ends, it'll be a disaster.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10018 0 0]The passengers could be at risk... Secure the monorail immediately.[n][uf 1 1][e]

[msg MSG_DUNGE_BOSS [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10019 0 0]Your primary target is up ahead! Are you ready?[n][uf 1 1][e]

[msg MSG_DUNGE_BOSS_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10020 0 0]There's no time. Hurry![n][uf 1 1][e]

[sel SEL_BOSS top]
[uf 0 5 65278][uf 2 1]Yes, I'm ready.[e]
[uf 0 5 65278][uf 2 1]Hold on.[e]

[msg MSG_KANOKE_JUNPEI [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2077 0 0]...This isn't gonna pop open and jump scare us, is it?[n][uf 1 1][e]

[msg MSG_CHIGAU_JUNPEI [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2007 0 0]Dude, what're you lookin' at that for? C'mon, let's go.[n][uf 1 1][e]

[msg MSG_INAI_YUKARI_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10009 0 0]Junpei was acting kind of strange, wasn't he? Why'd he snap and get so upset?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 1 10010 0 0]Well, I guess we can ask him once we've caught up to him. Let's go![n][uf 1 1][e]

[msg MSG_KASOKU_YUKARI_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 1 10013 0 0]What's happening!?[n][uf 1 1][e]

[msg MSG_KASOKU_YUKARI_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 1 10014 0 0]No way... Is the train getting faster!?[n][uf 1 1][e]

