[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30092 0 0]Hehe, I'm so happy I get to come to a place like this with you![n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]But what's this about "healing stones" "cleansing the soul"? I can't wrap my head around it...[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30135 0 0]Not that it really matters. I'm fine with anything as long as I'm with you! I'll go check it out now![n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]I'm so glad we get to go somewhere together again! Thank you for inviting me here.[n][uf 1 1][e]

[msg MSG_004_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Okay, time to head in. I'll be right back![n][uf 1 1][e]

[msg MSG_005_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30028 0 0]I feel like... I fell into a deep, deep sleep. What a strange sensation.[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Is this how you and your friends usually spend time together?[n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30041 0 0]It's nice to experience these kinds of things with someone else. Thank you again for inviting me![n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30104 0 0]*yawn* I was fast asleep again... But that was a really refreshing nap![n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]The best part is, when I wake up, I get to come out and see you waiting for me, hehe![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

