[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 1 0 0 1 0 0]I can't sense it anymore! Nice work, everyone.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 2 0 0]Oh, by the way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 3 0 0]I think I sensed Junpei-kun earlier.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 4 0 0]He's back at the dorm, but something felt off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 5 0 0]The chairman's there too, so he should be okay, but... we should hurry back, just in case.[n][uf 1 1][e]

