[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]I have detected a gaze upon us for an estimated seven minutes now.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 2 4 25 25]Oh, sorry... I just wanted to watch. Was I bothering you?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry about it.[e]
[uf 0 5 65278][uf 2 1]This isn't a show.[e]
[uf 0 5 65278][uf 2 1]I can stare too...[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 2 1 25 25]Thanks...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 2 1 25 25]I was just curious what it's like to study for an exam.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 2 3 25 25]S-Sorry, I didn't mean to be rude...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 2 4 25 25]Huh!? Are you... trying to get back at me? I'm sorry...[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 2 3 25 25]Um... Is it all right if I study with you? If it isn't too much trouble, I mean...[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]My data states that elementary school does not feature regular examinations. Is this information inaccurate?[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 2 0 25 25]No, you're right... We don't really have tests that we need study a whole week in advance for...[n][uf 1 1][e]

[msg MSG_008_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 2 3 25 25]Sorry, um... If you're not okay with it, I can just...[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Come study with us.[e]
[uf 0 5 65278][uf 2 1]Go get your books.[e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 2 1 25 25]Oh, thank you! I'll go get my workbooks now![n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]...Next question. What is the term used to describe the property of having zero electrical resistance?[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 2 1 25 25]Oh, I know! Superconductivity![n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Correct, Amada-san.[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]You're so smart.[e]
[uf 0 5 65278][uf 2 1]How did you know?[e]
[uf 0 5 65278][uf 2 1]Go! Superconductive Cyclone![e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 2 4 25 25]I-I just happened to see it on TV! It was an ultimate technique in Featherman... Not that I care about that stuff![n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 2 1 25 25]Yeah, that's it! The Featherman technique! It's so cool— I mean, that's what I heard from a friend, anyway...[n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 3 0 25 25]Bark![n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 2 3 25 25]Oh, sorry, Koromaru... I guess I was being a little loud. Let's get back to studying.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]We all started taking our studies seriously...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I'm focusing better than usual...[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]It appears that Amada-san has entered a state of non-REM sleep. He is in a deep slumber.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 0 25 25]Sleeping here may cause his body temperature to decline sharply, risking illness. Shall we wake him?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Let's let him sleep.[e]
[uf 0 5 65278][uf 2 1]Let's carry him to his room.[e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 0 25 25]Understood.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]I wonder what kind of dreams Amada-san will have...[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Let's transport him carefully to prevent waking. I will accompany you on the way to his room.[n][uf 1 1][e]

