[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Forgive me for calling you so suddenly, but there's something I must bring to your attention...[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]There seems to be a human presence within Tartarus between floors 48 and 53.[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]It appears to be someone without the potential who heard the voices of the Shadows...[n][uf 1 1][e]

[msg MSG_003_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]If left alone, I fear they will become Lost and may perish...[n][uf 1 1][e]

[msg MSG_004_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13204 0 0]Please find and rescue them.[n][uf 1 1][e]

