[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Sorry to keep you waiting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]To make a long story short, I'd like you to join student council.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds like a lot of work.[e]
[uf 0 5 65278][uf 2 1]I'm not so sure...[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]We meet regularly, but I don't expect you to participate every time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Just come to the student council room when you can.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]That's it?[e]
[uf 0 5 65278][uf 2 1]Why me?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Yes, that's it. All I want is for you to be a member.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Being president is very time-consuming. I'd like to have an ally to support me in the event of an emergency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]An ally meaning someone who understands my situation. You know what it means to be a leader, so I'm asking you.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Because of your ability to lead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Being president is very time-consuming. I'd like to have an ally to support me in the event of an emergency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]An ally meaning someone who understands my situation. You know what it means to be a leader, so I'm asking you.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]All right, I'll do it.[e]
[uf 0 5 65278][uf 2 1]Fine, I guess...[e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Excellent, I knew I could count on you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]...And I've already filed and approved your student council membership on your behalf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]But you'll have to go to the faculty office on your own to sign everything.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Seems like in order to join the student[n]council, [uf 0 1 2]I have to go find Ms. Toriumi[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I need to tell her that I'm[n]going to [uf 0 1 2]join student council[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I'm sorry for making arrangements without your permission, but I hope you understand the position I'm in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Once you're ready, come to the student council room. I'll be waiting for you there, [uf 4 1].[n][uf 1 1][e]

