[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Это рекламная рассылка от кафе «Шагал». Сходить туда?..[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Пойти[e]
[uf 0 5 65278][uf 2 1]Не ходить[e]

[msg MSG_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Похоже, они ищут сотрудника на полставки. Сходить туда?..[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Пойти[e]
[uf 0 5 65278][uf 2 1]Не ходить[e]

[msg MSG_006_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_007_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

