[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65535 0 0][uf 3 1 3 0 65535 11293 0 0]I really like hanging out here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0]This is a cool-looking fountain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 4 25 108]Hmmm...[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 3 1 3 0 65535 11261 0 0]Hey, we should organize an outdoor sketching session one of these days.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds like a hassle.[e]
[uf 0 5 65278][uf 2 1]That would be cool.[e]
[uf 0 5 65278][uf 2 1]Think we can do it?[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 6 65535 0 0][uf 3 1 3 0 65535 11271 0 0]Oh, you don't want to...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 6 65535 0 0]Well, we probably wouldn't have been able to set something like that up anyways...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems a little sad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65535 0 0][uf 3 1 3 0 65535 11282 0 0][uf 5 13 11 30 108]I don't know if we could actually do it or not, but I think it's a fun idea.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga looks happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 6 65535 0 0][uf 3 1 3 0 65535 11250 0 0][uf 5 13 11 15 108]Well, realistically...[n][uf 1 1][e]

[msg MSG_008_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 4 23 0 1 1 25 25]...But it sounds like fun, doesn't it?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga looks happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 6 65535 0 0][uf 4 25 108]......[n][uf 1 1][e]

[msg MSG_010_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65535 0 0][uf 3 1 3 0 65535 11243 0 0]Oh, sorry. So what should we do next? Should we get something to eat?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]The two of us hung out for a while longer[n]and then I decided to go back to the dorm.[n][uf 1 1][e]

