[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]The mysterious readings seem to be coming from this door.[n][uf 1 1][e]

[msg MND_000_0_1]
[uf 0 5 65278][uf 2 1]Could this be the door[n]Elizabeth was talking about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should check it out...[n][uf 1 1][e]

[msg MSG_000_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I sense Shadows beyond the door as well. If you plan on entering, please proceed with caution.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]Thanks for the info.[e]

[msg MSG_000_0_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Okay! Please go ahead and open the door.[n][uf 1 1][e]

