[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 4 101 65535 0 0][uf 3 1 1 0 0 1 0 0]Whoa! [uf 4 1]![n][uf 1 1][e]

[msg MSG_000_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0]Wh-What's up? I was just gonna sneak back into practice.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Where have you been?[e]
[uf 0 5 65278][uf 2 1]Did you ditch?[e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 3 0 0]M-My mom's been on my case![n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 4 0 0]She took me to the hospital. She insisted after I told her about my knee.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 5 0 0]No way! I had a legit reason![n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 6 0 0]I was at the hospital. My mom insisted. I shouldn't have told her about my knee.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 7 0 0]She made the appointment without telling me, so there was nothing I could do![n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]How did it go?[e]
[uf 0 5 65278][uf 2 1]That really sucks.[e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 8 0 0]Hell if I know.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 9 0 0]Ah, sorry, I know you're just worried about me.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 8 15 105]You said it. I don't get why my mom and the rest of the team are acting like this.[n][uf 1 1][e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 11 0 0]It's exhausting having everyone up in your business![n][uf 1 1][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 12 0 0]Today, they took some X-rays. They'll give me the results in a few days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 13 0 0]Not sure why that has to take so long...[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, hey! Don't tell anyone about me going to the hospital, alright?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 3 25 25]I'm counting on you, [uf 4 1]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 16 0 0]I feel bad for always asking you to keep things quiet. Sorry 'bout that.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems appreciative of me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg MSG_015_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]Alright! The doctor told me to take it easy today, but we should still get to practice![n][uf 1 1][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 18 0 0]Oh, wait... If you're leaving, that means practice is already over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 3 25 25]Well, I guess I'll just go home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 20 0 0]See ya, [uf 4 1].[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

