[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 51 65535 0 0][uf 3 1 1 0 0 1 0 0]This is just what the enemy wants...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 2 0 0]There's not much we can do about it now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 3 0 0]You have to go after him, or you'll be picked off one by one.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Dammit, Junpei! What are you thinking!?[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 50 0 0][uf 3 1 1 0 0 5 0 0]From what I can tell, he's only a few cars ahead.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Okay, we'll catch up to—[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Gah! Get out of our way![n][uf 1 1][e]

