[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Woohoo! School's out! And boy, do I have a hankering for sushi tonight![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Just wait for me, my precious, beloved sushi. I'll be sure to come home hungry![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Sooo I'm gonna take the long way home to work up an appetite. You go on ahead without me.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 5 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]Ugh... God, I want a hamburger so bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0]No! I gotta resist! My scrumptious sushi is waiting for me tonight![n][uf 1 1][e]

