[msg TRL_000_0_0 [Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you meet certain people in school or in the city, you may develop a Social Link with them. When fusing Personas, these Social Links will affect the results of the fusion.[n][uf 1 1][e]

[msg TRL_001_0_0 [Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you fuse a Persona that has the same Arcana as one of your Social Links, [uf 0 1 2]the resulting Persona will gain bonus experience[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Social Links]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Try to establish relationships with many people to enhance your Personas' capabilities.[n][uf 1 1][e]

