[msg TRL_000_0_0 [Outings with Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]As you complete more requests, Elizabeth will start asking you to escort her to different places from time to time.[n][uf 1 1][e]

[msg TRL_001_0_0 [Outings with Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can accompany her on these outings any time during daylight hours.[n][uf 1 1][e]

[msg TRL_002_0_0 [Outings with Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Going out with Elizabeth will take no time at all, so you don't need to worry about planning your day around her.[n][uf 1 1][e]

