[msg TRL_000_0_0 [Social Stats]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When going about your day-to-day life, you will come across certain actions that require the use of one of these stats: [uf 4 30 0 1 1 0], [uf 4 30 1 1 1 0], and [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg TRL_001_0_0 [Social Stats]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Social Stats can be raised by doing various things around the city or by answering questions correctly in class. Keep an eye out for activities that might help you hone those skills.[n][uf 1 1][e]

