[msg TRL_000_0_0 [Tatsumi East Police Station]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]At Tatsumi East Police Station, you can purchase equipment for you and your party to use in battle.[n][uf 1 1][e]

[msg TRL_001_0_0 [Tatsumi East Police Station]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can also sell any equipment you aren't using, if you need a little extra cash.[n][uf 1 1][e]

[msg TRL_002_0_0 [Tatsumi East Police Station]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]There's no telling what dangers Tartarus will throw your way, so be sure to gear up with the highest quality equipment you can afford.[n][uf 1 1][e]

