[msg TRL_000_0_0 [Leaving Money as an Offering]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Leaving money as an offering will raise your [uf 4 30 0 1 1 0]. The amount you choose to donate may yield different results. Those who approach with generosity will be rewarded in kind.[n][uf 1 1][e]

[msg TRL_001_0_0 [Leaving Money as an Offering]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Time will pass if you make an offering.[n][uf 1 1][e]

