[msg TRL_000_0_0 [Entering the Velvet Room from the City]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can access the Velvet Room from an alternate entrance in Paulownia Mall.[n][uf 1 1][e]

[msg TRL_001_0_0 [Entering the Velvet Room from the City]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Now you can take advantage of fast access to fusions and other Velvet Room functions without having to travel to Tartarus.[n][uf 1 1][e]

