[msg TRL_000_0_0 [Linked Episodes]]
[uf 0 5 65278][uf 2 1][uf 4 8 300]You may sometimes have the opportunity to spend time with your friends separate from Social Links.[n][uf 1 1][e]

[msg TRL_001_0_0 [Linked Episodes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]By doing so, you will be able to grow closer to and learn more about them.[n][uf 1 1][e]

[msg TRL_002_0_0 [Linked Episodes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Spending time with them can lead to other opportunities to hang out later, so be proactive about it.[n][uf 1 1][e]

[msg TRL_003_0_0 [Linked Episodes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Ignoring these relationships will [uf 0 1 2]stunt their growth[uf 0 1 27], so make sure to show your friends you value them.[n][uf 1 1][e]

