[msg TRL_000_0_0 [Equipment Types]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Equipment is listed in four categories: Weapons, Armor, Footwear, and Accessories.[n][uf 1 1][e]

[msg TRL_001_0_0 [Equipment Types]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Weapons primarily influence attack damage, Armor reduces the damage taken by the wearer, Footwear affects the wearer's evasiveness, and Accessories grant the wearer various special effects.[n][uf 1 1][e]

[msg TRL_002_0_0 [Equipment Types]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Sometimes, equipment other than Accessories will also grant special effects. Try out different combinations to optimize and specialize your loadout.[n][uf 1 1][e]

