[msg TRL_000_0_0 [Using Mail Order]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]The home shopping show airs every Sunday afternoon[uf 0 1 27]. You can catch it on the TV in your room or on the one in the lounge.[n][uf 1 1][e]

[msg TRL_001_0_0 [Using Mail Order]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The inventory changes every week, and as long as you've got the money, you can buy right from your home. Your delivery will arrive at a later date.[n][uf 1 1][e]

[msg TRL_002_0_0 [Using Mail Order]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Since you can only watch each show once, you may want to check how much money you have on hand before tuning in.[n][uf 1 1][e]

