[msg TRL_000_0_0 [Screen Shot Movie Theater]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Seeing a film at Screen Shot Movie Theater will raise your [uf 4 30 0 1 1 0], [uf 4 30 1 1 1 0], or [uf 4 30 2 1 1 0] depending on the movie's theme. The lineup will change every day, so be sure to check back often.[n][uf 1 1][e]

[msg TRL_001_0_0 [Screen Shot Movie Theater]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you get a part-time job working at the theater, you can pick up a shift [uf 0 1 2]during the afternoon on non-school days[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Screen Shot Movie Theater]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Both watching a movie and working a shift will pass the time.[n][uf 1 1][e]

