[msg TRL_000_0_0 [After-School Activities]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Starting today, you're free to use your "after school" hours however you wish.[n][uf 1 1][e]

[msg TRL_001_0_0 [After-School Activities]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Making use of various school facilities or visiting certain spots in town can raise your [uf 4 30 0 1 1 0], [uf 4 30 1 1 1 0], or [uf 4 30 2 1 1 0].[n][uf 1 1][e]

[msg TRL_002_0_0 [After-School Activities]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]However, the number of activities you can engage in each day is limited. Think carefully about how to spend your time and plan ahead.[n][uf 1 1][e]

