[msg TRL_000_0_0 [Going to Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You may now venture into Tartarus at your discretion.[n][uf 1 1][e]

[msg TRL_001_0_0 [Going to Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 200]You can go there by talking to your allies or by checking the bulletin board in the lounge.[n][uf 1 1][e]

[msg TRL_002_0_0 [Going to Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Because Tartarus is unavailable until the Dark Hour, time will pass if you decide to make the journey. Give yourself ample time to prepare beforehand.[n][uf 1 1][e]

