[msg TRL_000_0_0 [Missing Persons Reports]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Due to the influence of Shadows, civilians will sometimes get lost in Tartarus and become [uf 0 1 2]missing persons[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Missing Persons Reports]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Missing persons will be somewhere in Tartarus, and [uf 0 1 2]must be rescued within a set time limit[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Missing Persons Reports]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]In the event someone goes missing, details will be posted on [uf 0 1 2]the bulletin board in front of the police station[uf 0 1 27], so keep an eye peeled.[n][uf 1 1][e]

