[msg MND_AfterSchool_General]
[uf 0 5 65278][uf 2 1]Class has ended for today.[n][uf 1 1][e]

[msg MND_AfterSchool_Test_End]
[uf 0 5 65278][uf 2 1]I've finished today's exams.[n][uf 1 1][e]

[msg MND_AfterSchool_No_0408]
[uf 0 5 65278][uf 2 1]I should head back to the dorm.[n][uf 1 1][e]

[msg MND_1ST_TERM_END_0725]
[uf 0 5 65278][uf 2 1]Today marks the end of the first term.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Summer break begins tomorrow.[n][uf 1 1][e]

[msg MND_2ST_TERM_END_1226]
[uf 0 5 65278][uf 2 1]Today marks the end of the second term.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Winter break begins tomorrow.[n][uf 1 1][e]

[msg MND_FULLMOON_0509]
[uf 0 5 65278][uf 2 1]There will be a full moon tonight. It is[n]the day I was forewarned about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I wonder if something will happen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should probably head back[n]to the dorm, just in case.[n][uf 1 1][e]

[msg MND_FULLMOON_0707]
[uf 0 5 65278][uf 2 1]There will be a full moon tonight.[n]A powerful Shadow may appear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should return to the[n]dorm and prepare myself.[n][uf 1 1][e]

[msg MND_FULLMOON_0905]
[uf 0 5 65278][uf 2 1]There will be a full moon tonight.[n]A powerful Shadow will appear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should return to the[n]dorm and prepare myself.[n][uf 1 1][e]

[msg MND_INFO_0427]
[uf 0 5 65278][uf 2 1]Mitsuru has left the classroom...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems I can join the student council if I[n]submit some paperwork at the faculty office.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to the faculty office[n]when I have some free time.[n][uf 1 1][e]

[msg MND_INFO_0513]
[uf 0 5 65278][uf 2 1]The library is open for students to study in.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It might be worth taking advantage[n]of it ahead of next week's exams.[n][uf 1 1][e]

[msg MND_INFO_0514]
[uf 0 5 65278][uf 2 1]Apparently, the teacher in the nurse's[n]office gives out strange medicine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should check it out sometime...[n][uf 1 1][e]

[msg MND_Call_GoToHOME_0420]
[uf 0 5 65278][uf 2 1]It seems that something important[n]will be happening at the dorm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head back early.[n][uf 1 1][e]

[msg MND_Call_Sanada_0902]
[uf 0 5 65278][uf 2 1]That's right, I received a message from[n]Sanada earlier asking to meet after school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should go meet up with him.[n][uf 1 1][e]

[msg MND_Strega_0814]
[uf 0 5 65278][uf 2 1]I should go to Tatsumi Memorial[n]Hospital for my checkup.[n][uf 1 1][e]

[msg MND_Storm_Coming_0918]
[uf 0 5 65278][uf 2 1]The clouds look ominous...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head back to the dorm.[n][uf 1 1][e]

[msg MND_SportsClub_Join_0423]
[uf 0 5 65278][uf 2 1]Apparently, the track team is[n]recruiting new members.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I can find where they practice, maybe[n]I could see about possibly joining the team.[n][uf 1 1][e]

[msg MND_UsedBookstoreOPEN_04]
[uf 0 5 65278][uf 2 1]Apparently, the bookstore at[n]the strip mall is reopening today.[n][uf 1 1][e]

[msg MND_MAIKOisShrine_0506]
[uf 0 5 65278][uf 2 1]Apparently, there is a lonely[n]little girl at the shrine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should check up on[n]her to see if she's okay...[n][uf 1 1][e]

[msg MND_CultureClub_Join_061]
[uf 0 5 65278][uf 2 1]Apparently, the art club[n]is recruiting new members.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I might be able to learn more about[n]them if I visit their club room.[n][uf 1 1][e]

[msg MND_RYOJI_LINK3_1201]
[uf 0 5 65278][uf 2 1]Oh yeah, I got a message from Ryoji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looked like he wasn't at school today.[n]Maybe something urgent came up...?[n][uf 1 1][e]

[msg MND_ToVelvetRoom_0430]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth mentioned she[n]had something important to discuss with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to the Velvet Room.[n][uf 1 1][e]

[msg MND_ToVelvetRoom_0618]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth mentioned she[n]had something important to discuss with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to the Velvet Room.[n][uf 1 1][e]

[msg MSG_Missing_0708_only [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know that person who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda spooky, isn't it?[n][uf 1 1][e]

[msg MSG_Missing_0708_some [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know those people who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Multiple missing people found with Apathy Syndrome... Think it's just a coincidence?[n][uf 1 1][e]

[msg MSG_Missing_0807 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]...And now to more disturbing news. A missing resident was found, but with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The victim displayed no signs of external trauma, and police have ruled out the possibility that this was the cause of a criminal incident.[n][uf 1 1][e]

[msg MSG_Missing_0907_only [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know that person who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda unnerving, huh?[n][uf 1 1][e]

[msg MSG_Missing_0907_some [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know those people who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda creepy, don'tcha think?[n][uf 1 1][e]

[msg MSG_Missing_1006_BNKC_on [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]I was wondering why I haven't seen that old man at the bookstore lately. So, he went missing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Turns out he got Apathy Syndrome. I guess he is getting up there in years...[n][uf 1 1][e]

[msg MSG_Missing_1006_BNKC_so [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]I was wondering why I haven't seen that old man at the bookstore lately. So, he went missing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, they still haven't found him... Isn't that scary?[n][uf 1 1][e]

[msg MSG_Missing_1006_some [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know those people who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda spooky, isn't it?[n][uf 1 1][e]

[msg MSG_Missing_1006_only [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know that person who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda spooky, isn't it?[n][uf 1 1][e]

[msg MSG_Missing_1106_MAIKO_o [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, did you see the news? That grade-schooler is still missing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I hadn't heard that yet. That's kinda scary...[n][uf 1 1][e]

[msg MSG_Missing_1106_MAIKO_s [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, I heard those missing people still haven't been found.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, one of them was a grade-schooler. What is the world coming to...?[n][uf 1 1][e]

[msg MSG_Missing_1106_some [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know those people who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda unnerving, huh?[n][uf 1 1][e]

[msg MSG_Missing_1106_only [Male Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know that person who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Kinda unnerving, huh?[n][uf 1 1][e]

[msg MSG_Missing_1204_only [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know that person who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There've been a lot of Apathy Syndrome cases lately, haven't there?[n][uf 1 1][e]

[msg MSG_Missing_1204_some [Female Student's Voice]]
[uf 0 5 65278][uf 2 1]Hey, you know those people who went missing? I heard they were found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apathy Syndrome cases have been going through the roof lately, haven't they?[n][uf 1 1][e]

[msg MSG_Missing_1231 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]...Now to another missing person report. A missing woman was found with Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The victim displayed no signs of external trauma, and police have ruled out the possibility that this was the cause of a criminal incident.[n][uf 1 1][e]

[msg MSG_Missing_0131 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]Now an update on the recent disappearances. We can confirm that at least one of those located were found to have Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Our reporter on the scene says police are investigating a lead on a recent cult gathering...[n][uf 1 1][e]

[msg MND_HolidayNoon_0504]
[uf 0 5 65278][uf 2 1]Today is Greenery Day, the[n]second day of Golden Week.[n][uf 1 1][e]

[msg MND_HolidayNoon_0505]
[uf 0 5 65278][uf 2 1]Today is Children's Day, the[n]last day of Golden Week.[n][uf 1 1][e]

[msg MSG_HolidayNoon_0510 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Oh, [uf 4 1]. Were you able to get some rest after last night?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I apologize for the trouble, but I'm counting on you. And don't worry, Akihiko will be rejoining the front lines soon enough as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]That aside, don't forget that exams are coming up, so why don't you take today to relax a little?[n][uf 1 1][e]

[msg MND_HolidayNoon_0719]
[uf 0 5 65278][uf 2 1]The post-exam break begins today.[n][uf 1 1][e]

[msg MND_HolidayNoon_0803]
[uf 0 5 65278][uf 2 1]Summer vacation continues...[n][uf 1 1][e]

[msg MND_HolidayNoon_0820]
[uf 0 5 65278][uf 2 1]Summer vacation is starting to wind down...[n][uf 1 1][e]

[msg MND_HolidayNoon_0824]
[uf 0 5 65278][uf 2 1]The film festival only[n]runs for one more week.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should invite someone[n]from the dorm to go with me...[n][uf 1 1][e]

[msg MND_HolidayNoon_0825_083]
[uf 0 5 65278][uf 2 1]Summer vacation will be over soon...[n]The film festival is almost over, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should invite someone[n]from the dorm to go with me...[n][uf 1 1][e]

[msg MND_HolidayNoon_0831]
[uf 0 5 65278][uf 2 1]Today is the last day of summer vacation,[n]and the film festival ends today as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should invite someone[n]from the dorm to go with me...[n][uf 1 1][e]

[msg MND_HolidayNoon_0922]
[uf 0 5 65278][uf 2 1]Today is a national holiday. There's no school.[n][uf 1 1][e]

[msg MND_HolidayNoon_0923]
[uf 0 5 65278][uf 2 1]Today is the autumnal equinox.[n]There's no school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There's a one-day film festival today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should invite someone[n]from the dorm to go with me...[n][uf 1 1][e]

[msg MND_HolidayNoon_1012]
[uf 0 5 65278][uf 2 1]Today is Health and Sports[n]Day. There's no school.[n][uf 1 1][e]

[msg MND_HolidayNoon_1123]
[uf 0 5 65278][uf 2 1]Today is Labor Thanksgiving[n]Day. There's no school.[n][uf 1 1][e]

[msg MND_HolidayNoon_1223]
[uf 0 5 65278][uf 2 1]Today is the Emperor's birthday.[n]There's no school.[n][uf 1 1][e]

[msg MND_HolidayNoon_0104]
[uf 0 5 65278][uf 2 1]Winter vacation is almost over...[n][uf 1 1][e]

[msg MND_HolidayNoon_0107]
[uf 0 5 65278][uf 2 1]Today is the last day of winter vacation...[n][uf 1 1][e]

[msg MND_HolidayNoon_0111]
[uf 0 5 65278][uf 2 1]Today is Coming of Age[n]Day. There's no school.[n][uf 1 1][e]

[msg MND_HolidayNoon_testweek]
[uf 0 5 65278][uf 2 1]Exams are coming up...[n][uf 1 1][e]

[msg MND_HolidayNoon_General]
[uf 0 5 65278][uf 2 1]There's no school today.[n][uf 1 1][e]

[msg MND_Mail_Order_Today]
[uf 0 5 65278][uf 2 1]It's almost time for the home shopping show.[n][uf 1 1][e]

[msg MSG_Mail_Order_0807_01 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]Today, we're sprucing things up with a summer-only Amazing Commodities Monday special![n][uf 1 1][e]

[msg MND_Mail_Order_0807_02]
[uf 0 5 65278][uf 2 1]There's a colorful voice[n]coming from the TV...[n][uf 1 1][e]

[msg MND_0102_0]
[uf 0 5 65278][uf 2 1]The news is on...[n][uf 1 1][e]

[msg MSG_0102_1 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]It was reportedly a gathering organized by a new religious group. Police are working to confirm...[n][uf 1 1][e]

[msg MND_SHYUKAKU_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go get it...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK_QUEST]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MND_XB_6630_RYOJI_LE]
[uf 0 5 65278][uf 2 1]Ryoji is acting weird... I should[n]head to the [uf 0 1 2]music room[uf 0 1 27] later.[n][uf 1 1][e]

[msg MSG_108_0_0 [Voice on the TV]]
[uf 0 5 65278][uf 2 1]（※仮テキスト）[n][uf 1 5 0]失踪者解禁イベントが本来発生します。[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]現在イベントがまだないので今回は仮処理で[n][uf 1 5 0]ポロニアンモールに移動します。[n][uf 1 1][e]

