[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]*gasp* *huff*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I got really into my reading last night... and never went to sleep...[n][uf 1 1][e]

[msg MSG_000_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I thought I'd be fine, since I've lost sleep from the pain and anxiety of my illness before, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I suppose I'm not doing my health any favors like this...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]You need to listen to your body.[e]
[uf 0 5 65278][uf 2 1]Maybe you should go rest?[e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 20 15 117]...Thank you. Or rather, I suppose I should apologize.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]It's been so long since anyone told me off for anything...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Don't worry, I know my limits... and how to convince my body that it's still doing fine.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I came out here because I was hoping to find you. I only have so much time left, you know...[n][uf 1 1][e]

[msg MSG_004_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]...Do you remember when I said I like reading heartwarming stories?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]There are as many stories as there are stars in the sky, but I don't think any of them are what I'm looking for.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]The problem is... none of those stories were written for people like me.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I guess I'm just being selfish...[n][uf 1 1][e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]...Just like I am with you, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]You're always coming to visit me, keeping me company and talking with me...[n][uf 1 1][e]

[msg MSG_006_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]How much of your valuable time have you spent with me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I don't deserve it. You're spoiling me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]That's why I like you so much, though.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Kamiki smiled weakly at me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_008_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]*huff* *huff*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 117 1 25 25]Sorry... I was in such a good mood that I overexerted myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 117 0 25 25]I'd like to see you again sometime...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

