[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]As always, countless books line[n]the shelves inside the store.[n][uf 1 1][e]

[msg MSG_001_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 6 2 103]Oh, [uf 4 2]-chan! Looks like today's going to be a great day![n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 6 3 104]I'm so happy to see you. Make yourself at home, [uf 4 2]-chan.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I spent a while talking[n]with the elderly couple.[n][uf 1 1][e]

