[msg jyokyohelp_BLANK_PLAYER]
[uf 0 5 65278][uf 2 1]使用禁止[n][uf 1 1][e]

[msg jyokyohelp_BLANK_ENEMY]
[uf 0 5 65278][uf 2 1]使用禁止[n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_RES]
[uf 0 5 65278][uf 2 1]Attack reverted![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_RES_2]
[uf 0 5 65278][uf 2 1]Attack reverted![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_RESET]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion reverted![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_RESET_2]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion reverted![n][uf 1 1][e]

[msg jyokyohelp_DEF_RESET_PLA]
[uf 0 5 65278][uf 2 1]Defense reverted![n][uf 1 1][e]

[msg jyokyohelp_DEF_RESET_ENE]
[uf 0 5 65278][uf 2 1]Defense reverted![n][uf 1 1][e]

[msg jyokyohelp_HIRISK_RESET_]
[uf 0 5 65278][uf 2 1]Critical rate reverted![n][uf 1 1][e]

[msg jyokyohelp_HIRISK_RESET__2]
[uf 0 5 65278][uf 2 1]Critical rate reverted![n][uf 1 1][e]

[msg jyokyohelp_RISKHG_RESET_]
[uf 0 5 65278][uf 2 1]Effect of Revolution ended![n][uf 1 1][e]

[msg jyokyohelp_RISKHG_RESET__2]
[uf 0 5 65278][uf 2 1]Effect of Revolution ended![n][uf 1 1][e]

[msg jyokyohelp_BADx2_RESET_P]
[uf 0 5 65278][uf 2 1]Ailment susceptibility reverted![n][uf 1 1][e]

[msg jyokyohelp_BADx2_RESET_E]
[uf 0 5 65278][uf 2 1]Ailment susceptibility reverted![n][uf 1 1][e]

[msg jyokyohelp_AGINDA_RESET_]
[uf 0 5 65278][uf 2 1]Fire affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_AGINDA_RESET__2]
[uf 0 5 65278][uf 2 1]Fire affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_BUFNDA_RESET_]
[uf 0 5 65278][uf 2 1]Ice affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_BUFNDA_RESET__2]
[uf 0 5 65278][uf 2 1]Ice affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_GALNDA_RESET_]
[uf 0 5 65278][uf 2 1]Wind affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_GALNDA_RESET__2]
[uf 0 5 65278][uf 2 1]Wind affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_JIONDA_RESET_]
[uf 0 5 65278][uf 2 1]Electricity affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_JIONDA_RESET__2]
[uf 0 5 65278][uf 2 1]Electricity affinity reverted![n][uf 1 1][e]

[msg jyokyohelp_REDWALL_F_PLA]
[uf 0 5 65278][uf 2 1]Fire resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_REDWALL_F_ENE]
[uf 0 5 65278][uf 2 1]Fire resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_F_P]
[uf 0 5 65278][uf 2 1]Ice resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_F_E]
[uf 0 5 65278][uf 2 1]Ice resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_F_PL]
[uf 0 5 65278][uf 2 1]Electricity resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_F_EN]
[uf 0 5 65278][uf 2 1]Electricity resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_F_P]
[uf 0 5 65278][uf 2 1]Wind resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_F_E]
[uf 0 5 65278][uf 2 1]Wind resistance reverted...[n][uf 1 1][e]

[msg jyokyohelp_BAD_ATTACK_PL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] frenzies![n][uf 1 1][e]

[msg jyokyohelp_BAD_ATTACK_EN]
[uf 0 5 65278][uf 2 1][uf 2 4 0] frenzies![n][uf 1 1][e]

[msg jyokyohelp_BAD_SKIP_PLAY]
[uf 0 5 65278][uf 2 1]Cannot move due to ailment![n][uf 1 1][e]

[msg jyokyohelp_BAD_SKIP_ENEM]
[uf 0 5 65278][uf 2 1]Cannot move due to ailment![n][uf 1 1][e]

[msg jyokyohelp_BAD_BLANK1]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK2]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_HP_PLAYER]
[uf 0 5 65278][uf 2 1]Insufficient HP![n][uf 1 1][e]

[msg jyokyohelp_HP_ENEMY]
[uf 0 5 65278][uf 2 1]Insufficient HP![n][uf 1 1][e]

[msg jyokyohelp_SP_PLAYER]
[uf 0 5 65278][uf 2 1]Insufficient SP![n][uf 1 1][e]

[msg jyokyohelp_SP_ENEMY]
[uf 0 5 65278][uf 2 1]Insufficient SP![n][uf 1 1][e]

[msg jyokyohelp_BLANK3]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK4]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK5]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_ESCAPE_ENEMY]
[uf 0 5 65278][uf 2 1][uf 2 4 0] ran away...[n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_SET]
[uf 0 5 65278][uf 2 1]Attack up![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_SET_2]
[uf 0 5 65278][uf 2 1]Attack up![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_SET_P]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_SET_E]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_DEF_SET_PLAYE]
[uf 0 5 65278][uf 2 1]Defense up![n][uf 1 1][e]

[msg jyokyohelp_DEF_SET_ENEMY]
[uf 0 5 65278][uf 2 1]Defense up![n][uf 1 1][e]

[msg jyokyohelp_ENG_SET_PLAYE]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_ENG_SET_ENEMY]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_RND_SET_PLAYE]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion down![n][uf 1 1][e]

[msg jyokyohelp_RND_SET_ENEMY]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion down![n][uf 1 1][e]

[msg jyokyohelp_HIRISK_SET_PL]
[uf 0 5 65278][uf 2 1]Critical rate up![n][uf 1 1][e]

[msg jyokyohelp_HIRISK_SET_EN]
[uf 0 5 65278][uf 2 1]Critical rate up![n][uf 1 1][e]

[msg jyokyohelp_RISKHG_SET_PL]
[uf 0 5 65278][uf 2 1]Critical rate way up![n][uf 1 1][e]

[msg jyokyohelp_RISKHG_SET_EN]
[uf 0 5 65278][uf 2 1]Critical rate way up![n][uf 1 1][e]

[msg jyokyohelp_BADx2_SET_PLA]
[uf 0 5 65278][uf 2 1]Ailment susceptibility up![n][uf 1 1][e]

[msg jyokyohelp_BADx2_SET_ENE]
[uf 0 5 65278][uf 2 1]Ailment susceptibility up![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_DOW]
[uf 0 5 65278][uf 2 1]Attack down![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_DOW_2]
[uf 0 5 65278][uf 2 1]Attack down![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_DOWN_]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion down![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_DOWN__2]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion down![n][uf 1 1][e]

[msg jyokyohelp_DEF_DOWN_SET_]
[uf 0 5 65278][uf 2 1]Defense down![n][uf 1 1][e]

[msg jyokyohelp_DEF_DOWN_SET__2]
[uf 0 5 65278][uf 2 1]Defense down![n][uf 1 1][e]

[msg jyokyohelp_DEKAJA_PLAYER]
[uf 0 5 65278][uf 2 1]All stat increases nullified![n][uf 1 1][e]

[msg jyokyohelp_DEKAJA_ENEMY]
[uf 0 5 65278][uf 2 1]All stat increases nullified![n][uf 1 1][e]

[msg jyokyohelp_DEKUNDA_PLAYE]
[uf 0 5 65278][uf 2 1]All stat decreases nullified![n][uf 1 1][e]

[msg jyokyohelp_DEKUNDA_ENEMY]
[uf 0 5 65278][uf 2 1]All stat decreases nullified![n][uf 1 1][e]

[msg jyokyohelp_POWERCHARGE_P]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has charged up![n][uf 1 1][e]

[msg jyokyohelp_POWERCHARGE_E]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has charged up![n][uf 1 1][e]

[msg jyokyohelp_MINDCHARGE_PL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is focused![n][uf 1 1][e]

[msg jyokyohelp_MINDCHARGE_EN]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is focused![n][uf 1 1][e]

[msg jyokyohelp_K_AGINDA2_PLA]
[uf 0 5 65278][uf 2 1]Fire resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_AGINDA2_ENE]
[uf 0 5 65278][uf 2 1]Fire resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_BUFUNDA2_PL]
[uf 0 5 65278][uf 2 1]Ice resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_BUFUNDA2_EN]
[uf 0 5 65278][uf 2 1]Ice resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_JIONDA2_PLA]
[uf 0 5 65278][uf 2 1]Electricity resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_JIONDA2_ENE]
[uf 0 5 65278][uf 2 1]Electricity resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_GARUNDA2_PL]
[uf 0 5 65278][uf 2 1]Wind resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_K_GARUNDA2_EN]
[uf 0 5 65278][uf 2 1]Wind resistance nullified![n][uf 1 1][e]

[msg jyokyohelp_OKANE_PLAYER]
[uf 0 5 65278][uf 2 1]Threw [uf 2 4 1] yen away![n][uf 1 1][e]

[msg jyokyohelp_OKANE_ENEMY]
[uf 0 5 65278][uf 2 1]Threw [uf 2 4 1] yen away![n][uf 1 1][e]

[msg jyokyohelp_TETORABLAKE_P]
[uf 0 5 65278][uf 2 1]Tetrakarn nullified![n][uf 1 1][e]

[msg jyokyohelp_TETORABLAKE_E]
[uf 0 5 65278][uf 2 1]Tetrakarn nullified![n][uf 1 1][e]

[msg jyokyohelp_MAKARABLAKE_P]
[uf 0 5 65278][uf 2 1]Makarakarn nullified![n][uf 1 1][e]

[msg jyokyohelp_MAKARABLAKE_E]
[uf 0 5 65278][uf 2 1]Makarakarn nullified![n][uf 1 1][e]

[msg jyokyohelp_TETORAJA_PLAY]
[uf 0 5 65278][uf 2 1]Tetraja activated![n][uf 1 1][e]

[msg jyokyohelp_TETORAJA_ENEM]
[uf 0 5 65278][uf 2 1]Tetraja activated![n][uf 1 1][e]

[msg jyokyohelp_REDWALL_PLAYE]
[uf 0 5 65278][uf 2 1]Fire resistance up![n][uf 1 1][e]

[msg jyokyohelp_REDWALL_ENEMY]
[uf 0 5 65278][uf 2 1]Fire resistance up![n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_PLA]
[uf 0 5 65278][uf 2 1]Ice resistance up![n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_ENE]
[uf 0 5 65278][uf 2 1]Ice resistance up![n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_PLAY]
[uf 0 5 65278][uf 2 1]Electricity resistance up![n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_ENEM]
[uf 0 5 65278][uf 2 1]Electricity resistance up![n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_PLA]
[uf 0 5 65278][uf 2 1]Wind resistance up![n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_ENE]
[uf 0 5 65278][uf 2 1]Wind resistance up![n][uf 1 1][e]

[msg jyokyohelp_TETRKN_PLAYER]
[uf 0 5 65278][uf 2 1]Physical-reflecting wall erected![n][uf 1 1][e]

[msg jyokyohelp_TETRKN_ENEMY]
[uf 0 5 65278][uf 2 1]Physical-reflecting wall erected![n][uf 1 1][e]

[msg jyokyohelp_MAKRKN_PLAYER]
[uf 0 5 65278][uf 2 1]Magic-reflecting wall erected![n][uf 1 1][e]

[msg jyokyohelp_MAKRKN_ENEMY]
[uf 0 5 65278][uf 2 1]Magic-reflecting wall erected![n][uf 1 1][e]

[msg jyokyohelp_TTRJYA_PLAYER]
[uf 0 5 65278][uf 2 1]Instakill-blocking wall erected![n][uf 1 1][e]

[msg jyokyohelp_TTRJYA_ENEMY]
[uf 0 5 65278][uf 2 1]Instakill-blocking wall erected![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_ADD]
[uf 0 5 65278][uf 2 1]Attack boost extended![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_ADD_2]
[uf 0 5 65278][uf 2 1]Attack boost extended![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_ADD_P]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion boost extended![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_ADD_E]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion boost extended![n][uf 1 1][e]

[msg jyokyohelp_DEF_ADD_PLAYE]
[uf 0 5 65278][uf 2 1]Defense boost extended![n][uf 1 1][e]

[msg jyokyohelp_DEF_ADD_ENEMY]
[uf 0 5 65278][uf 2 1]Defense boost extended![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_DOW_3]
[uf 0 5 65278][uf 2 1]Attack drop extended![n][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_DOW_4]
[uf 0 5 65278][uf 2 1]Attack drop extended![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_DOWN__3]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion drop extended![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_DOWN__4]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion drop extended![n][uf 1 1][e]

[msg jyokyohelp_DEF_DOWN_ADD_]
[uf 0 5 65278][uf 2 1]Defense drop extended![n][uf 1 1][e]

[msg jyokyohelp_DEF_DOWN_ADD__2]
[uf 0 5 65278][uf 2 1]Defense drop extended![n][uf 1 1][e]

[msg jyokyohelp_RND_ADD_PLAYE]
[uf 0 5 65278][uf 2 1]All stat drops extended![n][uf 1 1][e]

[msg jyokyohelp_RND_ADD_ENEMY]
[uf 0 5 65278][uf 2 1]All stat drops extended![n][uf 1 1][e]

[msg jyokyohelp_REDWALL_ADD_P]
[uf 0 5 65278][uf 2 1]Fire resistance extended![n][uf 1 1][e]

[msg jyokyohelp_REDWALL_ADD_E]
[uf 0 5 65278][uf 2 1]Fire resistance extended![n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_ADD]
[uf 0 5 65278][uf 2 1]Ice resistance extended![n][uf 1 1][e]

[msg jyokyohelp_WHITEWALL_ADD_2]
[uf 0 5 65278][uf 2 1]Ice resistance extended![n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_ADD_]
[uf 0 5 65278][uf 2 1]Electricity resistance extended![n][uf 1 1][e]

[msg jyokyohelp_BLUEWALL_ADD__2]
[uf 0 5 65278][uf 2 1]Electricity resistance extended![n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_ADD]
[uf 0 5 65278][uf 2 1]Wind resistance extended![n][uf 1 1][e]

[msg jyokyohelp_GREENWALL_ADD_2]
[uf 0 5 65278][uf 2 1]Wind resistance extended![n][uf 1 1][e]

[msg jyokyohelp_K_AGINDA2_ADD]
[uf 0 5 65278][uf 2 1]Fire Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_AGINDA2_ADD_2]
[uf 0 5 65278][uf 2 1]Fire Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_BUFUNDA2_AD]
[uf 0 5 65278][uf 2 1]Ice Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_BUFUNDA2_AD_2]
[uf 0 5 65278][uf 2 1]Ice Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_JIONDA2_ADD]
[uf 0 5 65278][uf 2 1]Elec Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_JIONDA2_ADD_2]
[uf 0 5 65278][uf 2 1]Elec Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_GARUNDA2_AD]
[uf 0 5 65278][uf 2 1]Wind Break extended![n][uf 1 1][e]

[msg jyokyohelp_K_GARUNDA2_AD_2]
[uf 0 5 65278][uf 2 1]Wind Break extended![n][uf 1 1][e]

[msg jyokyohelp_BLANK6]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK7]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_SET_BAD_TOUKE]
[uf 0 5 65278][uf 2 1]Inflicted with Freeze...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_TOUKE_2]
[uf 0 5 65278][uf 2 1]Inflicted with Freeze![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KANDE]
[uf 0 5 65278][uf 2 1]Inflicted with Shock...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KANDE_2]
[uf 0 5 65278][uf 2 1]Inflicted with Shock![n][uf 1 1][e]

[msg jyokyohelp_BLANK8]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK9]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_SET_BAD_PANIC]
[uf 0 5 65278][uf 2 1]Inflicted with Confuse...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_PANIC_2]
[uf 0 5 65278][uf 2 1]Inflicted with Confuse![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KYOUH]
[uf 0 5 65278][uf 2 1]Inflicted with Fear...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KYOUH_2]
[uf 0 5 65278][uf 2 1]Inflicted with Fear![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_CHARM]
[uf 0 5 65278][uf 2 1]Inflicted with Charm...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_CHARM_2]
[uf 0 5 65278][uf 2 1]Inflicted with Charm![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_UPSET]
[uf 0 5 65278][uf 2 1]Inflicted with Distress...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_UPSET_2]
[uf 0 5 65278][uf 2 1]Inflicted with Distress![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_POISO]
[uf 0 5 65278][uf 2 1]Inflicted with Poison...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_POISO_2]
[uf 0 5 65278][uf 2 1]Inflicted with Poison![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_GEKID]
[uf 0 5 65278][uf 2 1]Inflicted with Rage...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_GEKID_2]
[uf 0 5 65278][uf 2 1]Inflicted with Rage![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KIZET]
[uf 0 5 65278][uf 2 1]Dizzy and can't get up...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_KIZET_2]
[uf 0 5 65278][uf 2 1]Dizzy and can't get up![n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_SENNO]
[uf 0 5 65278][uf 2 1]Brainwashed...[n][uf 1 1][e]

[msg jyokyohelp_SET_BAD_SENNO_2]
[uf 0 5 65278][uf 2 1]Brainwashed![n][uf 1 1][e]

[msg jyokyohelp_BLANK19]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK20]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BAD_ESCAPE_PL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] ran away![n][uf 1 1][e]

[msg jyokyohelp_BAD_ESCAPE_EN]
[uf 0 5 65278][uf 2 1][uf 2 4 0] ran away![n][uf 1 1][e]

[msg jyokyohelp_BLANK21]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK22]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK23]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK24]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLOOD_SET_PLA]
[uf 0 5 65278][uf 2 1]Critical rate and physical strength up![n][uf 1 1][e]

[msg jyokyohelp_BLOOD_SET_ENE]
[uf 0 5 65278][uf 2 1]Critical rate and physical strength up...![n][uf 1 1][e]

[msg jyokyohelp_BLANK27]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK28]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK29]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK30]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK31]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK32]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_KUISIB_PLAYER]
[uf 0 5 65278][uf 2 1][uf 2 4 0] withstood the attack![n][uf 1 1][e]

[msg jyokyohelp_KUISIB_ENEMY]
[uf 0 5 65278][uf 2 1][uf 2 4 0] withstood the attack![n][uf 1 1][e]

[msg jyokyohelp_FUKUTU_PLAYER]
[uf 0 5 65278][uf 2 1]Survived and restored HP![n][uf 1 1][e]

[msg jyokyohelp_FUKUTU_ENEMY]
[uf 0 5 65278][uf 2 1]Survived and restored HP![n][uf 1 1][e]

[msg jyokyohelp_WAIT_MAGIC_CH]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is gathering magic power...[n][uf 1 1][e]

[msg jyokyohelp_BLANK33]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK34]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK35]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK36]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK37]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK38]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK39]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK40]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK41]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK42]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK43]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK44]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK45]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK46]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_NO_TARGET]
[uf 0 5 65278][uf 2 1]No target available.[n][uf 1 1][e]

[msg jyokyohelp_HOMUNCULUS]
[uf 0 5 65278][uf 2 1]The Homunculus sacrificed itself![n][uf 1 1][e]

[msg jyokyohelp_NO_SHIFT]
[uf 0 5 65278][uf 2 1]Can't Shift right now![n][uf 1 1][e]

[msg jyokyohelp_BLANK48]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK49]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK50]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK51]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK52]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK53]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK54]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK55]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK56]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK57]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK58]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK59]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK60]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK61]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK62]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BADSTATUS_REC]
[uf 0 5 65278][uf 2 1]Status ailment recovered![n][uf 1 1][e]

[msg jyokyohelp_BLANK63]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK64]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_EXCESS]
[uf 0 5 65278][uf 2 1]No effect.[n][uf 1 1][e]

[msg jyokyohelp_HIRISK_ADD]
[uf 0 5 65278][uf 2 1]Critical rate boost extended![n][uf 1 1][e]

[msg jyokyohelp_BADx2_ADD]
[uf 0 5 65278][uf 2 1]Ailment susceptibility extended![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_HEAL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] healed the enemy![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_TAL]
[uf 0 5 65278][uf 2 1]Enemy Attack up![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_RAK]
[uf 0 5 65278][uf 2 1]Enemy Defense up![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_SUK]
[uf 0 5 65278][uf 2 1]Enemy Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_ITEM_DIS]
[uf 0 5 65278][uf 2 1]Threw away [uf 2 4 1]![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_TAL_AD]
[uf 0 5 65278][uf 2 1]Attack boost extended![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_RAK_AD]
[uf 0 5 65278][uf 2 1]Defense boost extended![n][uf 1 1][e]

[msg jyokyohelp_SENNOH_SUK_AD]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion boost extended![n][uf 1 1][e]

[msg jyokyohelp_BAD_TOUKETU_N]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is frozen![n][uf 1 1][e]

[msg jyokyohelp_BAD_KANDEN_NO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is shocked![n][uf 1 1][e]

[msg jyokyohelp_BAD_PANIC_NOW]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is confused![n][uf 1 1][e]

[msg jyokyohelp_BAD_KIZETU_NO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] can't get up![n][uf 1 1][e]

[msg jyokyohelp_BAD_CHARM_NOW]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is charmed![n][uf 1 1][e]

[msg jyokyohelp_BAD_GEKIDO_NO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is enraged![n][uf 1 1][e]

[msg jyokyohelp_BAD_MOUSE_NOW]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is distressed![n][uf 1 1][e]

[msg jyokyohelp_ALREADY]
[uf 0 5 65278][uf 2 1]Already in effect.[n][uf 1 1][e]

[msg jyokyohelp_UNNECESSARY]
[uf 0 5 65278][uf 2 1]Not necessary.[n][uf 1 1][e]

[msg jyokyohelp_DONTUSE]
[uf 0 5 65278][uf 2 1]Can't be used right now![n][uf 1 1][e]

[msg jyokyohelp_SKILL_NONE]
[uf 0 5 65278][uf 2 1]No skills for use in battle![n][uf 1 1][e]

[msg jyokyohelp_GOODS_NONE]
[uf 0 5 65278][uf 2 1]No items for use in battle![n][uf 1 1][e]

[msg jyokyohelp_OPERATION_IMP]
[uf 0 5 65278][uf 2 1]No one to give orders to![n][uf 1 1][e]

[msg jyokyohelp_ESCAPE_IMPOSS]
[uf 0 5 65278][uf 2 1]Can't escape![n][uf 1 1][e]

[msg jyokyohelp_ESCAPE_FAILUR]
[uf 0 5 65278][uf 2 1]Failed to escape![n][uf 1 1][e]

[msg jyokyohelp_NOEFFECT]
[uf 0 5 65278][uf 2 1]No effect![n][uf 1 1][e]

[msg jyokyohelp_DEADRCV_SET_A]
[uf 0 5 65278][uf 2 1]Ally has been revived![n][uf 1 1][e]

[msg jyokyohelp_ENG_ADD]
[uf 0 5 65278][uf 2 1]All stat boosts extended![n][uf 1 1][e]

[msg jyokyohelp_BLANK68]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BATK_MATK_SET_3]
[uf 0 5 65278][uf 2 1]Party Attack up![n][uf 1 1][e]

[msg jyokyohelp_DEF_SET_ASSIS]
[uf 0 5 65278][uf 2 1]Party Defense up![n][uf 1 1][e]

[msg jyokyohelp_HIT_ESC_SET_A]
[uf 0 5 65278][uf 2 1]Party Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_W_CHARGE_SET_]
[uf 0 5 65278][uf 2 1]Party is charged up and focused![n][uf 1 1][e]

[msg jyokyohelp_HP_HEAL_SET_A]
[uf 0 5 65278][uf 2 1]Party recovered some HP![n][uf 1 1][e]

[msg jyokyohelp_SP_HEAL_SET_A]
[uf 0 5 65278][uf 2 1]Party recovered some SP![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_HP_P]
[uf 0 5 65278][uf 2 1]Drained HP![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_HP_E]
[uf 0 5 65278][uf 2 1]Drained HP![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_SP_P]
[uf 0 5 65278][uf 2 1]Drained SP![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_SP_E]
[uf 0 5 65278][uf 2 1]Drained SP![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_TALK]
[uf 0 5 65278][uf 2 1]Attack has been changed![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_RAKK]
[uf 0 5 65278][uf 2 1]Defense has been changed![n][uf 1 1][e]

[msg jyokyohelp_ROULETTE_SUKK]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion have been changed![n][uf 1 1][e]

[msg jyokyohelp_BLANK69]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK70]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_KOUTAIKINSHI]
[uf 0 5 65278][uf 2 1]Incapacitated allies cannot switch![n][uf 1 1][e]

[msg jyokyohelp_BLANK71]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK72]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK73]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_P_CHANGE]
[uf 0 5 65278][uf 2 1]Change Persona[n][uf 1 1][e]

[msg jyokyohelp_BLANK74]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK75]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK76]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK77]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK78]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_TOOFAR]
[uf 0 5 65278][uf 2 1]The enemy is too far away![n][uf 1 1][e]

[msg jyokyohelp_BLANK79]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK80]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_DAME_BATON]
[uf 0 5 65278][uf 2 1]Can't Shift right now![n][uf 1 1][e]

[msg jyokyohelp_NO_BATON]
[uf 0 5 65278][uf 2 1]There is nobody to Shift to![n][uf 1 1][e]

[msg jyokyohelp_KYOHU_NOACT]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is paralyzed with fear![n][uf 1 1][e]

[msg jyokyohelp_BAD_MOUSE_ESC]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is trying to flee![n][uf 1 1][e]

[msg jyokyohelp_CHARM_NOACT]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is too charmed to move![n][uf 1 1][e]

[msg jyokyohelp_BAD_PANIC_ITE]
[uf 0 5 65278][uf 2 1]Threw away [uf 2 4 1]![n][uf 1 1][e]

[msg jyokyohelp_BLANK83]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BAD_OVHEAT_NO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is overheating...[n][uf 1 1][e]

[msg jyokyohelp_BLANK85]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK86]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK87]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK88]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK89]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK90]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BOSS_WAIT_1]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is charging up...[n][uf 1 1][e]

[msg jyokyohelp_ENEMY_PRE_ESC]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is starting to panic![n][uf 1 1][e]

[msg jyokyohelp_SUMMON_TEKI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] appeared![n][uf 1 1][e]

[msg jyokyohelp_GK_EX_HENYO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] identified weaknesses![n][uf 1 1][e]

[msg jyokyohelp_GK_EX_BULLET_]
[uf 0 5 65278][uf 2 1][uf 2 4 0] loaded 1 bullet![n][uf 1 1][e]

[msg jyokyohelp_GK_EX_BULLET__2]
[uf 0 5 65278][uf 2 1][uf 2 4 0] loaded 2 bullets![n][uf 1 1][e]

[msg jyokyohelp_GK_EX_BULLET__3]
[uf 0 5 65278][uf 2 1][uf 2 4 0] loaded 3 bullets![n][uf 1 1][e]

[msg jyokyohelp_GK_EX_BULLET__4]
[uf 0 5 65278][uf 2 1][uf 2 4 0] loaded 4 bullets![n][uf 1 1][e]

[msg jyokyohelp_DR_DEATH_SPEL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is chanting a death spell...[n][uf 1 1][e]

[msg jyokyohelp_DR_ATTACK_BU]
[uf 0 5 65278][uf 2 1][uf 2 4 0] readied their sword![n][uf 1 1][e]

[msg jyokyohelp_DR_ATTACK_MA]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has started casting a spell![n][uf 1 1][e]

[msg jyokyohelp_DR_STOP_MOTIO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is warming up its engine...[n][uf 1 1][e]

[msg jyokyohelp_GK_EX_BULLET__5]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is out of bullets...[n][uf 1 1][e]

[msg jyokyohelp_GK_SP_SUMMON]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is calling for their minions![n][uf 1 1][e]

[msg jyokyohelp_GK_CANNOT_SUM]
[uf 0 5 65278][uf 2 1]There is no one inside [uf 2 4 0]...[n][uf 1 1][e]

[msg jyokyohelp_BLANK103]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK104]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK105]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK106]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK107]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK108]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK109]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BAD_KANDEN_MO]
[uf 0 5 65278][uf 2 1]Shock transferred![n][uf 1 1][e]

[msg jyokyohelp_BLANK110]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK111]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_KANTU]
[uf 0 5 65278][uf 2 1]Pierced the enemy's resistance![n][uf 1 1][e]

[msg jyokyohelp_BLANK112]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK113]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK114]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK115]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_TGET_MONEY]
[uf 0 5 65278][uf 2 1]Obtained [uf 2 4 1] yen![n][uf 1 1][e]

[msg jyokyohelp_TGET_ITEM]
[uf 0 5 65278][uf 2 1]Obtained [uf 2 4 1]![n][uf 1 1][e]

[msg jyokyohelp_TLOST_MONEY]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg jyokyohelp_TLOST_ITEM]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg jyokyohelp_TGET_CARD]
[uf 0 5 65278][uf 2 1]Obtained [uf 2 4 1] Skill Card![n][uf 1 1][e]

[msg jyokyohelp_TSUCKED_HP]
[uf 0 5 65278][uf 2 1]The enemy drained HP![n][uf 1 1][e]

[msg jyokyohelp_TSUCKED_SP]
[uf 0 5 65278][uf 2 1]The enemy drained SP![n][uf 1 1][e]

[msg jyokyohelp_BLANK116]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK117]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK118]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_TCURE_BADSTAT]
[uf 0 5 65278][uf 2 1]Enemy status ailment recovered![n][uf 1 1][e]

[msg jyokyohelp_BLANK119]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_TGET_BLANKCAR]
[uf 0 5 65278][uf 2 1]Obtained a Blank Card![n][uf 1 1][e]

[msg jyokyohelp_BLANK120]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK121]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK122]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK123]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_DOUBLE_SUMMON]
[uf 0 5 65278][uf 2 1]Summoned [uf 2 4 0]![n][uf 1 1][e]

[msg jyokyohelp_BLANK124]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_UMEKI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is groaning...[n][uf 1 1][e]

[msg jyokyohelp_BLANK125]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_NIYANIYA]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is smirking...[n][uf 1 1][e]

[msg jyokyohelp_YOUSUMI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is waiting...[n][uf 1 1][e]

[msg jyokyohelp_SABORI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is staring off into space.[n][uf 1 1][e]

[msg jyokyohelp_KOBUSHI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] clenched their fist tight![n][uf 1 1][e]

[msg jyokyohelp_TIRED]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is exhausted...[n][uf 1 1][e]

[msg jyokyohelp_SENTOU_TAISEI]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is ready for combat![n][uf 1 1][e]

[msg jyokyohelp_POWER_CHARGE]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has charged up![n][uf 1 1][e]

[msg jyokyohelp_POWER_MAX]
[uf 0 5 65278][uf 2 1][uf 2 4 0]'s power is fully charged![n][uf 1 1][e]

[msg jyokyohelp_BLANK132]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK133]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK134]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK135]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK136]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK137]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK138]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK139]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK140]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK141]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK142]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_DUMMY_01]
[uf 0 5 65278][uf 2 1][uf 2 4 0] prepares...[n][uf 1 1][e]

[msg jyokyohelp_DUMMY_02]
[uf 0 5 65278][uf 2 1][uf 2 4 0]'s glare sharpens![n][uf 1 1][e]

[msg jyokyohelp_DUMMY_03]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is composed...[n][uf 1 1][e]

[msg jyokyohelp_BLANK143]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BOSSONLY1]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has run out of power...[n][uf 1 1][e]

[msg jyokyohelp_BLANK145]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK146]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK147]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK148]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK149]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK150]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_ABLANK151]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK153]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK154]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK155]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK156]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK157]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK158]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK159]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_MND_DICE_01]
[uf 0 5 65278][uf 2 1]The rolled die shows 1...[n][uf 1 1][e]

[msg jyokyohelp_MND_DICE_02]
[uf 0 5 65278][uf 2 1]The rolled die shows 2...[n][uf 1 1][e]

[msg jyokyohelp_MND_DICE_03]
[uf 0 5 65278][uf 2 1]The rolled die shows 3...[n][uf 1 1][e]

[msg jyokyohelp_MND_DICE_04]
[uf 0 5 65278][uf 2 1]The rolled die shows 4...[n][uf 1 1][e]

[msg jyokyohelp_MND_DICE_05]
[uf 0 5 65278][uf 2 1]The rolled die shows 5...[n][uf 1 1][e]

[msg jyokyohelp_MND_DICE_06]
[uf 0 5 65278][uf 2 1]The rolled die shows 6...[n][uf 1 1][e]

[msg jyokyohelp_MND_HAND_01]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has sprained its finger...[n][uf 1 1][e]

[msg jyokyohelp_MND_HAND_02]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is waving...[n][uf 1 1][e]

[msg jyokyohelp_MND_HAND_03]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is warming up...[n][uf 1 1][e]

[msg jyokyohelp_BLANK169]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_MND_ANIMAL]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is grieving...[n][uf 1 1][e]

[msg jyokyohelp_MND_DEATH_01]
[uf 0 5 65278][uf 2 1]The scripture is marked, "D"...[n][uf 1 1][e]

[msg jyokyohelp_MND_DEATH_02]
[uf 0 5 65278][uf 2 1]The scripture is marked, "DE"...[n][uf 1 1][e]

[msg jyokyohelp_MND_DEATH_03]
[uf 0 5 65278][uf 2 1]The scripture is marked, "DEA"...[n][uf 1 1][e]

[msg jyokyohelp_MND_DEATH_04]
[uf 0 5 65278][uf 2 1]The scripture is marked, "DEAT"...[n][uf 1 1][e]

[msg jyokyohelp_MND_DEATH_05]
[uf 0 5 65278][uf 2 1]The scripture is marked, "DEATH"...[n][uf 1 1][e]

[msg jyokyohelp_MND_ABDON_01]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is worn out...[n][uf 1 1][e]

[msg jyokyohelp_BLANK177]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK178]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK179]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK180]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK181]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK182]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK183]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK184]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK185]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK186]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK187]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK188]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK189]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK191]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK192]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK193]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK194]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK195]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK196]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK197]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK198]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK199]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_MIX_CADENZA_S]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_MIX_CADENZA_O]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion reverted![n][uf 1 1][e]

[msg jyokyohelp_MIX_CADENZA_A]
[uf 0 5 65278][uf 2 1]Accuracy/Evasion boost extended![n][uf 1 1][e]

[msg jyokyohelp_TRG_ALCONC_SE]
[uf 0 5 65278][uf 2 1]Everyone's magic strength increased![n][uf 1 1][e]

[msg jyokyohelp_TRG_HEATST_SE]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_TRG_HEATST_AD]
[uf 0 5 65278][uf 2 1]All stat boosts extended![n][uf 1 1][e]

[msg jyokyohelp_TRG_RNDMBA_SE]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion down![n][uf 1 1][e]

[msg jyokyohelp_TRG_RNDMBA_AD]
[uf 0 5 65278][uf 2 1]All stat drops extended![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACLE_HP]
[uf 0 5 65278][uf 2 1]Party recovered some HP![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACLE_SP]
[uf 0 5 65278][uf 2 1]Party recovered some SP![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACL2_HP]
[uf 0 5 65278][uf 2 1]Party recovered some HP and ailments![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACL2_SP]
[uf 0 5 65278][uf 2 1]Party recovered some SP![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACL2_HE]
[uf 0 5 65278][uf 2 1]ATK/DEF/Accuracy/Evasion up![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORGIAM_SE]
[uf 0 5 65278][uf 2 1]Orgia Mode activated![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORGIAM_EN]
[uf 0 5 65278][uf 2 1]Aigis has overheated![n][uf 1 1][e]

[msg jyokyohelp_TRG_OVHEAT_NO]
[uf 0 5 65278][uf 2 1][uf 2 4 0] can't move![n][uf 1 1][e]

[msg jyokyohelp_TRG_ALCHAR_SE]
[uf 0 5 65278][uf 2 1]Koromaru's howl fills everyone with vigor![n][uf 1 1][e]

[msg jyokyohelp_MIX_BEST_F_SE]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has charged up and focused![n][uf 1 1][e]

[msg jyokyohelp_MIX_TRIKST_SE]
[uf 0 5 65278][uf 2 1]Enemy afflicted with a status ailment![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORACL2_AL]
[uf 0 5 65278][uf 2 1]Party recovered some HP/SP and ailments![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORGIAM_SH]
[uf 0 5 65278][uf 2 1]Can't Shift during Orgia Mode![n][uf 1 1][e]

[msg jyokyohelp_TRG_ORGIAM_AI]
[uf 0 5 65278][uf 2 1]Can't switch out during Orgia Mode![n][uf 1 1][e]

[msg jyokyohelp_TRG_AMADA2]
[uf 0 5 65278][uf 2 1]Physical/magic wall erected![n][uf 1 1][e]

[msg jyokyohelp_BLANK223]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK224]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK225]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK226]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK227]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK228]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK229]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK230]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK231]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK232]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK233]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK234]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK235]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK236]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK237]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK238]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK239]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK240]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK241]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK242]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK243]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK244]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK245]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK246]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK247]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK248]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK249]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK250]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK251]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK252]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK253]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK254]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK255]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK256]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK257]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK258]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK259]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK260]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK261]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK262]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK263]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK264]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK265]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK266]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK267]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK268]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK269]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK270]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK271]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK272]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK273]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK274]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK275]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK276]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK277]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK278]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK279]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK280]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK281]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK282]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK283]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK284]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK285]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK286]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK287]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK288]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK289]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK290]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK291]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK292]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK293]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK294]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK295]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK296]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK297]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK298]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_LOCALIZATION_]
[uf 0 5 65278][uf 2 1]これはローカライズ対応用の状況ヘルプテストです[n][uf 1 5 0]これはローカライズ対応用の状況ヘルプテストです[n][uf 1 1][e]

[msg jyokyohelp_BOSS001]
[uf 0 5 65278][uf 2 1][uf 2 4 0]'s affinities have changed![n][uf 1 1][e]

[msg jyokyohelp_BOSS002]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is laughing audaciously...[n][uf 1 1][e]

[msg jyokyohelp_BOSS003]
[uf 0 5 65278][uf 2 1]Attack for all allies/enemies increased![n][uf 1 1][e]

[msg jyokyohelp_BOSS004]
[uf 0 5 65278][uf 2 1]Defense for all allies/enemies decreased...[n][uf 1 1][e]

[msg jyokyohelp_BOSS005]
[uf 0 5 65278][uf 2 1]Magic strength for all allies/enemies increased![n][uf 1 1][e]

[msg jyokyohelp_BOSS006]
[uf 0 5 65278][uf 2 1]Nothing happened...[n][uf 1 1][e]

[msg jyokyohelp_BOSS007]
[uf 0 5 65278][uf 2 1]The power of friendship surges within you![n][uf 1 1][e]

[msg jyokyohelp_BOSS008]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is recovering HP![n][uf 1 1][e]

[msg jyokyohelp_BOSS009]
[uf 0 5 65278][uf 2 1]A new power is available![n][uf 1 1][e]

[msg jyokyohelp_BOSS010]
[uf 0 5 65278][uf 2 1][uf 2 4 0] gets more actions...![n][uf 1 1][e]

[msg jyokyohelp_BOSS011]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has settled down...[n][uf 1 1][e]

[msg jyokyohelp_BOSS012]
[uf 0 5 65278][uf 2 1]The monorail is starting to shake...![n][uf 1 1][e]

[msg jyokyohelp_BOSS013]
[uf 0 5 65278][uf 2 1]The monorail is shaking even more...![n][uf 1 1][e]

[msg jyokyohelp_BOSS014]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is consuming electricity...![n][uf 1 1][e]

[msg jyokyohelp_BOSS015]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting [uf 4 1]![n][uf 1 1][e]

[msg jyokyohelp_BOSS016]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting Mitsuru![n][uf 1 1][e]

[msg jyokyohelp_BOSS017]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting Sanada![n][uf 1 1][e]

[msg jyokyohelp_BOSS018]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting Yukari![n][uf 1 1][e]

[msg jyokyohelp_BOSS019]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting Junpei![n][uf 1 1][e]

[msg jyokyohelp_BOSS020]
[uf 0 5 65278][uf 2 1][uf 2 4 0] has set its sights![n][uf 1 1][e]

[msg jyokyohelp_BOSS021]
[uf 0 5 65278][uf 2 1][uf 2 4 0] lost sight of its target...[n][uf 1 1][e]

[msg jyokyohelp_BOSS022]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is targeting Aigis![n][uf 1 1][e]

[msg jyokyohelp_BOSS023]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is almost done charging up...![n][uf 1 1][e]

[msg jyokyohelp_BOSS024]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is loading grenades...![n][uf 1 1][e]

[msg jyokyohelp_BOSS025]
[uf 0 5 65278][uf 2 1][uf 2 4 0] ran out of electricity...[n][uf 1 1][e]

[msg jyokyohelp_BOSS026]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is about to discharge...![n][uf 1 1][e]

[msg jyokyohelp_BLANK326]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK327]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK328]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK329]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK330]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK331]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK332]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK333]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK334]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK335]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK336]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK337]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK338]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK339]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK340]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK341]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK342]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK343]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK344]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK345]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK346]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK347]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK348]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK349]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_JIN_WEAK]
[uf 0 5 65278][uf 2 1]Weakness revealed![n][uf 1 1][e]

[msg jyokyohelp_JIN_GEKIYAKU]
[uf 0 5 65278][uf 2 1]Sacrificed life to considerably boost Attack![n][uf 1 1][e]

[msg jyokyohelp_BLANK352]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_TAKAYA_01]
[uf 0 5 65278][uf 2 1][uf 2 4 0] is waiting...[n][uf 1 1][e]

[msg jyokyohelp_BLANK354]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK355]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK356]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK357]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK358]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK359]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg jyokyohelp_BLANK360]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK361]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK362]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK363]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK364]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK365]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK366]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK367]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK368]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK369]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK370]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK371]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK372]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK373]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK374]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK375]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK376]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK377]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK378]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK379]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK380]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK381]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg jyokyohelp_BLANK382]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

