[msg MSG_TUTORIAL_START [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10115 0 0]Right, let's begin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10116 0 0]Defeat all the Shadows on that floor.[n][uf 1 1][e]

[msg MND_MITSURU_NOISE]
[uf 0 5 65278][uf 2 1]Communication is breaking up...[n][uf 1 1][e]

[msg MND_NOISE_MES]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_MITSURU_OVER]
[uf 0 5 65278][uf 2 1]Communication has been lost...[n][uf 1 1][e]

[msg MSG_MITSURU_CALL_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10118 0 0]Are— ...all ri—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10119 0 0]...too far— ...can't provi— ...backup—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 10121 0 0]I'm sor— ...Akihiko— ...the others—[n][uf 1 1][e]

[msg MSG_MITSURU_CALL_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_MITSURU_CALL_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]What's— ...current loca— ...Reply immed—[n][uf 1 1][e]

[msg MSG_UNKNOWN_02 [Mysterious Voice]]
[uf 0 5 65278][uf 2 1]Who's there...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Where am I? Why am I here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Please, answer me...[n][uf 1 1][e]

[msg MSG_MITSURU_TYPE1_BURST [Mitsuru Kirijo]]

[msg MSG_MITSURU_TYPE2_BURST [Mitsuru Kirijo]]

[msg MSG_MITSURU_TYPE3_BURST [Mitsuru Kirijo]]

[msg MSG_MITSURU_TYPE4_BURST [Mitsuru Kirijo]]

[msg MSG_MITSURU_TYPE5_BURST [Mitsuru Kirijo]]

[msg MSG_MITSURU_TYPE8_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE1_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE2_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE3_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE4_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE5_BURST [Mitsuru Kirijo]]

[msg MSG_FUKA_TYPE8_BURST [Mitsuru Kirijo]]

[msg MND_TYPE6_BURST [Mitsuru Kirijo]]

[msg MND_TYPE7_BURST [Mitsuru Kirijo]]

[msg MND_HELP_011F [Mitsuru Kirijo]]

[msg MSG_MITSURU_002F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4008 0 0]Each floor's dimensions may vary, but don't feel compelled to explore every inch of each new layout.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Rushing directly for the stairs is a completely viable strategy. I leave that choice to your discretion.[n][uf 1 1][e]

[msg MSG_MITSURU_003F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4063 0 0]You're likely to find a plethora of these strange mineral deposits scattered throughout Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Supposedly, these formations are the crystallized remains of Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's sure to be useful materials inside them. When you find one, try cracking it open.[n][uf 1 1][e]

[msg MSG_MITSURU_004F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4073 0 0]I keep a running record on hand of each area you explore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]After you've established a route, navigating you through it again should be no issue.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]However, due to Tartarus's changing nature, these records become useless the next time you visit.[n][uf 1 1][e]

[msg MSG_MITSURU_005F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]Judging by the frequency of the signal, this is undoubtedly a stronger foe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]It would be a wise decision to regroup before approaching...[n][uf 1 1][e]

[msg MSG_MITSURU_006F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4138 0 0]It would seem your enemies grow stronger with every floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Despite the imminent danger, it stands to reason we've gained valuable experience. Let's continue on.[n][uf 1 1][e]

[msg MSG_MITSURU_007F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to manage your energy and resources. Don't overexert yourself—sometimes retreating is the smartest option.[n][uf 1 1][e]

[msg MSG_MITSURU_008F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4077 0 0]How are you feeling? You're not likely to make much meaningful progress when you're worn down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Be sure to recover if your health is low. It isn't prudent to risk your wellbeing unnecessarily.[n][uf 1 1][e]

[msg MSG_MITSURU_009F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_010F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4071 0 0]There's trouble waiting for us one floor up. It's like the Shadow we faced on the fifth floor...[n][uf 1 1][e]

[msg MSG_MITSURU_011F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]I've observed that every few floors, you'll encounter a powerful foe blocking your way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]These "Gatekeepers," as we'll call them, aren't going to simply let you pass—you'll need to be prepared for a real fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Ensure you are ready before engaging a Gatekeeper, and make use of teleporters if needed.[n][uf 1 1][e]

[msg MSG_MITSURU_012F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4068 0 0]Is that...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's a rare Shadow up ahead. Perhaps you can ambush it.[n][uf 1 1][e]

[msg MSG_MITSURU_013F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4078 0 0]I'm detecting a stronger foe on an upcoming floor. Another Gatekeeper...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It'd be wise to conserve our strength. Have you made use of the [uf 0 1 2]Escape[uf 0 1 27] order?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]A strategic retreat can mean the difference between life and death. You can always regroup and try again.[n][uf 1 1][e]

[msg MSG_MITSURU_014F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_015F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4103 0 0]We're coming up on a tougher foe. Be aware this will be more of a challenge than your standard Shadow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You can always use a teleporter if you need to regroup beforehand.[n][uf 1 1][e]

[msg MSG_MITSURU_016F_NONE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_017F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4001 0 0]I see you're making good progress. And you appear to be getting the hang of things in combat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]On the topic, have you been paying attention to enemy weaknesses?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Exploiting a weakness will make you hit harder and more often. Doing so can turn the tide of a battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]The more kinds of attacks you can use, the more chances you'll have to hit a weakness. That's where your ability comes in handy.[n][uf 1 1][e]

[msg MSG_MITSURU_018F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4094 0 0]Huh, well, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]The Shadows on this floor are much weaker than you. This may be a good opportunity to try the "Rush" command.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Rushing can be greatly useful if you're trying to move through a floor without spending much time in battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]When you choose "Rush," all party members will default to their basic weapon attacks in rapid succession.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]While this isn't the most tactically involved strategy, it will allow you to move much faster through combat encounters.[n][uf 1 1][e]

[msg MSG_MITSURU_019F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_020F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_021F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]There don't appear to be any enemies on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0]Wait... What's going on? There aren't any enemies on the next floor either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]...Ah, these seem to be special floors. I'll need you to go up through them for the investigation.[n][uf 1 1][e]

[msg MSG_MITSURU_022F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_023F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]Hmm... There are more Shadows on this floor than normal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]They're roaming in droves, and they look particularly formidable. Proceed with caution.[n][uf 1 1][e]

[msg MSG_MITSURU_024F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4122 0 0]This is some rugged terrain... Keep your eyes peeled for any blind spots.[n][uf 1 1][e]

[msg MSG_MITSURU_025F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_026F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4067 0 0]There's a Gatekeeper on a floor not far from here. Have you healed up recently?[n][uf 1 1][e]

[msg MSG_MITSURU_027F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_028F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]This foe is... unique. I wish there were a way to glean information on them preemptively...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]No matter. Once you're in combat, I can analyze our enemies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Use this information at your discretion. Plan strategically, and you're sure to come out on top.[n][uf 1 1][e]

[msg MSG_MITSURU_029F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4073 0 0]Have you had a chance to explore status ailments yet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If you run into a powerful enemy, you may be able to weaken them with a status ailment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]For instance, inflict Distress to diminish their attack, or Confuse them to render them passive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You'll want to gauge the situation and pick your tactics accordingly.[n][uf 1 1][e]

[msg MSG_MITSURU_030F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]Hang on. This floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]I'm getting an unusual enemy signal. Stay alert.[n][uf 1 1][e]

[msg MSG_MITSURU_031F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_032F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4073 0 0]By the way, have you been taking advantage of your physical skills?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Physical skills have a chance to knock enemies down regardless of their weaknesses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Akihiko and Iori specialize in that regard, if I recall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Give it a try in the next battle.[n][uf 1 1][e]

[msg MSG_MITSURU_033F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_034F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4106 0 0]There don't seem to be any enemies on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]That should spell some reprieve for us, but it could very well be the calm before a storm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Fortunately, there's a two-way teleporter nearby, so I'd say a quick regroup may be warranted.[n][uf 1 1][e]

[msg MSG_MITSURU_035F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]What? There's no teleporter!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]We'll just have to barrel through for now. Better be prepared for the worst.[n][uf 1 1][e]

[msg MSG_MITSURU_036F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4099 0 0]These battles are just going to keep coming... Hang in there![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 4 25 5]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]I'm picking up on another [uf 0 1 2]border floor[uf 0 1 27]. It's [uf 0 1 2]seven[uf 0 1 27] floors from here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]I suppose that means this is a border guard, in a manner of speaking. We've got our work cut out for us. I'm counting on you.[n][uf 1 1][e]

[msg MSG_MITSURU_037F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4071 0 0]There's a faint enemy presence on a floor much higher up from where we are...[n][uf 1 1][e]

[msg MSG_MITSURU_038F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_039F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_040F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]So this is floor forty. The number probably doesn't mean much...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]But this is a veritable accomplishment. Keep up the good work.[n][uf 1 1][e]

[msg MSG_MITSURU_041F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_042F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4077 0 0]If an enemy isn't letting up, consider using skills to buff your allies or enervate enemies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]By raising your defense and lowering an enemy's attack, you may be able to weather the storm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It's an effective strategy in battles that might get more involved than expected. Think tactically to fight efficiently.[n][uf 1 1][e]

[msg MSG_MITSURU_043F [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take care to watch your stamina. Knowing when to retreat is as much a life-saving skill as any battle tactic.[n][uf 1 1][e]

[msg MSG_MITSURU_IMPOSSIBLE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0]What? No, it can't be...![n][uf 1 1][e]

[msg MSG_FUKA_002F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Floors sizes may vary as you explore, but there's no need to check every nook and cranny.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You can just make a beeline for the stairs if that works best for you. The decision's up to you, Leader.[n][uf 1 1][e]

[msg MSG_FUKA_003F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]I'm sure you've noticed these crystal-like things growing all over this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Supposedly, those are Shadow remains. You'll want to break any you come across.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There might be some useful items inside.[n][uf 1 1][e]

[msg MSG_FUKA_004F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]I keep a log of all the places you've explored.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]After you've established a route, navigating you through it again shouldn't be a problem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But only until you leave for the night, since Tartarus changes every day.[n][uf 1 1][e]

[msg MSG_FUKA_005F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]This signal is strong. We've got a tough fight ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I think it'd be a good idea for us to regroup...[n][uf 1 1][e]

[msg MSG_FUKA_006F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health and stamina are low.[n][uf 1 1][e]

[msg MSG_FUKA_007F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_008F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]We're making some good progress, but how are you feeling?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please don't forget to heal as you need it.[n][uf 1 1][e]

[msg MSG_FUKA_009F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_010F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]There's a powerful enemy on the next floor. It's the same type of Shadow as the one we faced on the fifth floor.[n][uf 1 1][e]

[msg MSG_FUKA_011F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]There seems to be an extra powerful Shadow every few floors.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It's like these Gatekeepers are put here to test us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please, if you need to take some time to regroup, use a teleporter to fall back.[n][uf 1 1][e]

[msg MSG_FUKA_012F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5073 0 0]Huh? This Shadow's giving off an unusual signal...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's on this floor. Though I don't get the impression it's particularly strong...[n][uf 1 1][e]

[msg MSG_FUKA_013F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]I'm detecting a stronger foe on a floor not too far off. It must be another Gatekeeper...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It'd be best if you went into that fight refreshed. Have you made use of the [uf 0 1 2]Escape[uf 0 1 27] order?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's no shame in retreating. Keep that option in mind going forward.[n][uf 1 1][e]

[msg MSG_FUKA_014F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_015F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]We're getting close to the Gatekeeper. Stay sharp.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Hopefully there's a teleporter nearby so that we can recoup.[n][uf 1 1][e]

[msg MSG_FUKA_016F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_017F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]It's risky to try and progress while your health is low. Please be sure to heal frequently, all right?[n][uf 1 1][e]

[msg MSG_FUKA_018F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5066 0 0]There don't seem to be too many powerful Shadows on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The "Rush" command is most effective when you're up against weaker enemies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]When you order a Rush, the party will default to their basic weapon attacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]You won't have the opportunity to make tactical decisions during a Rush, but it will end combat quickly.[n][uf 1 1][e]

[msg MSG_FUKA_019F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_020F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_021F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I'm not detecting any enemies on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Huh? There aren't any on the next floor either... What's going on?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Maybe it's a special floor. Well, I don't sense any danger, so let's keep going.[n][uf 1 1][e]

[msg MSG_FUKA_022F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_023F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_024F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]There are so many twists and turns here. Be careful not to get ambushed by any Shadows.[n][uf 1 1][e]

[msg MSG_FUKA_025F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_026F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]There's a Gatekeeper on the next floor. Please be careful![n][uf 1 1][e]

[msg MSG_FUKA_027F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_028F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5004 0 0]If you're having trouble against the enemies on one floor, try challenging some Shadows on a lower floor first.[n][uf 1 1][e]

[msg MSG_FUKA_029F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Have you experimented with status ailments yet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Inflicting ailments can give you an edge against stronger enemies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]For example, Distress lowers attack, and Confuse prevents an enemy from acting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Such effects could turn the tide of battle. I think they're worth utilizing if you find an opportunity.[n][uf 1 1][e]

[msg MSG_FUKA_030F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]What IS this!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]An enemy on this floor is giving off an abnormal signal. Stay alert.[n][uf 1 1][e]

[msg MSG_FUKA_031F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_032F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]By the way, have you been making use of your physical skills?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Physical skills have a chance to knock enemies down regardless of their weaknesses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]If you're ever unsure about an enemy's weak spot, a basic attack might just do the trick.[n][uf 1 1][e]

[msg MSG_FUKA_033F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_034F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]I don't detect any enemy presences on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]This might be a good time to take a break... I have a feeling there's trouble ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You can always use a teleporter if you want to come back to the entrance and prepare.[n][uf 1 1][e]

[msg MSG_FUKA_035F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5073 0 0]No way! There aren't any teleporters here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Looks like the only path forward is through... Stay sharp, everyone![n][uf 1 1][e]

[msg MSG_FUKA_036F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]Back-to-back battles... Stay calm, team. You can do this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm detecting another [uf 0 1 2]border floor[uf 0 1 27] not too far from us. It's... [uf 0 1 2]seven[uf 0 1 27] floors up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Once we get past this, it's not much further. In the meantime, I'll do everything I can to support everyone![n][uf 1 1][e]

[msg MSG_FUKA_037F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5092 0 0]I'm sensing another strong presence. It's still a ways away...[n][uf 1 1][e]

[msg MSG_FUKA_038F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_039F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_040F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]This is the 40th floor. It might be a milestone, but it's hard to tell with Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I wonder how tall this tower really is...[n][uf 1 1][e]

[msg MSG_FUKA_041F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_042F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5004 0 0]When enemies have you in a tight spot, you can always use support skills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]These skills can buff allies or debuff enemies. Even a single buff could mean the difference between life and death.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Using them effectively, you might be able to wiggle out of a tight spot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]They're also helpful in battles that look like they might drag on, so don't hesitate to use them when needed.[n][uf 1 1][e]

[msg MSG_FUKA_043F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_044F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5042 0 0]I remember how helpless I felt being here alone.[n][uf 1 1][e]

[msg MSG_FUKA_045F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_046F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_047F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]You'll be going up against another Gatekeeper. It won't be an easy fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]You can do this, though. I'll do my best to support you from here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]With my [uf 0 1 35]Full Analysis[uf 0 1 27], I'll be able to give you a complete breakdown of enemy weaknesses on the spot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]And remember that I can use Theurgy as well. Hopefully, it'll come in handy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Well, this is it. Stay safe, and good luck, team. I'm here if you need me![n][uf 1 1][e]

[msg MSG_FUKA_048F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5098 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_049F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_050F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5067 0 0]This brings us to the 50th floor, but we've still a long ways to go...[n][uf 1 1][e]

[msg MSG_FUKA_051F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Enemy defenses seem to be getting tighter by the floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Enemies without weaknesses are especially difficult to wear down. That's where status ailments come in handy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Enemies afflicted with status ailments are more likely to be knocked down by physical attacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I know Kirijo-senpai specializes in skills that inflict these ailments.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I really recommend testing combinations of status ailments and physical skills.[n][uf 1 1][e]

[msg MSG_FUKA_052F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_053F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]There's a strong enemy on the next floor! Be careful.[n][uf 1 1][e]

[msg MSG_FUKA_054F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Are you sure you're not too tired? Please don't overexert yourself, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If you're low on stamina, do consider coming back.[n][uf 1 1][e]

[msg MSG_FUKA_055F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_056F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_057F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5091 0 0]Huh!? I'm sensing high-level threats all over this floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]This entire area is crawling with strong enemies![n][uf 1 1][e]

[msg MSG_FUKA_058F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_059F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_060F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]This fight's going to be a tough one... We can't get careless![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Give it your all. Just say the word, and I'll support you with my Theurgy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Hang on... I'm picking up another signal![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's another [uf 0 1 2]border floor[uf 0 1 27] coming up. It's [uf 0 1 2]nine[uf 0 1 27] floors from here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's still pretty far off... Let's focus on the path ahead of us, first.[n][uf 1 1][e]

[msg MSG_FUKA_061F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_062F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]My goodness... This floor is huge, isn't it? I imagine mapping it out in its entirety would be a lot of work...[n][uf 1 1][e]

[msg MSG_FUKA_063F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5091 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_064F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_065F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5114 0 0]I think it's incredible how you're able to juggle so many different Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You can practically guarantee favorable match-ups by swapping them out to correlate with enemy weaknesses...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, sorry! I was thinking out loud.[n][uf 1 1][e]

[msg MSG_FUKA_066F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_067F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_068F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Oh! The [uf 0 1 2]floor after this one[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It seems like the coast is clear for now, so you'll get a bit of a break.[n][uf 1 1][e]

[msg MSG_FUKA_069F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_070F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_071F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Is this... some kind of machine? I wonder what it's powered by...[n][uf 1 1][e]

[msg MSG_FUKA_072F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5122 0 0]What is this place? It feels... different here.[n][uf 1 1][e]

[msg MSG_FUKA_073F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_074F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5079 0 0]There's a strong enemy coming up on a nearby floor! Let's be sure to pace ourselves.[n][uf 1 1][e]

[msg MSG_FUKA_075F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_076F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_077F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]No matter how strong the enemy, there's almost always some way to gain the upper hand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The key is maintaining your composure long enough to seize the opportunity when it presents itself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]With that in mind, make sure you're rested and prepared before battle. Can't have you keeling over after the first blow.[n][uf 1 1][e]

[msg MSG_FUKA_078F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_079F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Huh? What is this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's different from any response I've gotten until now. It's... shrouded.[n][uf 1 1][e]

[msg MSG_FUKA_080F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_081F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's a Gatekeeper on the next floor. What kind of Shadow could it be this time...?[n][uf 1 1][e]

[msg MSG_FUKA_082F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Do you suppose the Shadows have some reason to keep trying to stop us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]This reading...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 0 1 2]Ten[uf 0 1 27] floors up from here, there's a [uf 0 1 2]border floor[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]That's coming up much sooner than it seems. Let's keep at it.[n][uf 1 1][e]

[msg MSG_FUKA_083F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_084F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5114 0 0]Do you ever wonder—I mean, given how heavy this place must be—whether or not it'll topple over...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]Then again, it does seem different from your typical building. Probably no use worrying... Hopefully...[n][uf 1 1][e]

[msg MSG_FUKA_085F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_086F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_087F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_088F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_089F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]There aren't any enemies here. That's a relief...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]But I have an uneasy feeling about what's ahead. How about turning back for now?[n][uf 1 1][e]

[msg MSG_FUKA_090F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]There isn't a teleporter here, so we'll have to fight our way through.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Please prepare as best you can![n][uf 1 1][e]

[msg MSG_FUKA_091F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5103 0 0]We're going straight into another fight, but this is where we test our mettle![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The [uf 0 1 2]next floor[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27]. We need to get through this, no matter what![n][uf 1 1][e]

[msg MSG_FUKA_092F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_093F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Yikes... There isn't much cover in this area, so we'll be spotted more easily.[n][uf 1 1][e]

[msg MSG_FUKA_094F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_095F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]There are enemies on this floor as well. But...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]They're acting strange. Almost fidgety, restless...[n][uf 1 1][e]

[msg MSG_FUKA_096F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_097F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_098F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_099F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Against tougher enemies like these, Theurgy will go a long way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]One option is to have it ready as soon as you enter combat so you can unload a barrage.[n][uf 1 1][e]

[msg MSG_FUKA_100F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]Finally, we're on the 100th floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]That's a mind-boggling number, but the end's not even in sight... Well, there's no hurry, so let's keep a steady pace.[n][uf 1 1][e]

[msg MSG_FUKA_101F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_102F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5098 0 0]This again?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The enemies are acting strangely. Please be careful.[n][uf 1 1][e]

[msg MSG_FUKA_103F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_104F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]You've probably noticed the mineral chunks lying around...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Supposedly, there are different types, some of which are quite rare.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The rare ones [uf 0 1 2]give off a blue glow[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]They yield [uf 0 1 39]Twilight Fragments[uf 0 1 27], so try breaking them when you spot them.[n][uf 1 1][e]

[msg MSG_FUKA_105F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]If you ever feel worn down, please don't be reckless—err on the side of caution and come back to the entrance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You can keep everyone on the front lines fresh by subbing in new people. That way, progress will be a team effort.[n][uf 1 1][e]

[msg MSG_FUKA_106F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]It's still a short ways off, but I'm detecting a strong enemy coming up![n][uf 1 1][e]

[msg MSG_FUKA_107F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_108F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I'm getting a slightly different reading from the Shadows on this floor.[n][uf 1 1][e]

[msg MSG_FUKA_109F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]It's hard to visualize a building with over a hundred floors, isn't it?[n][uf 1 1][e]

[msg MSG_FUKA_110F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_111F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_112F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5103 0 0]There are still strong foes ahead, so please prepare as much as possible if you want to keep going.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, and is this...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Yes, there's a [uf 0 1 2]border floor[uf 0 1 27] coming up in [uf 0 1 2]six[uf 0 1 27] floors.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We'll be there shortly if we can win this fight. Ready to do this?[n][uf 1 1][e]

[msg MSG_FUKA_113F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_114F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_115F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5094 0 0]I can't imagine anyone believing us about the Dark Hour or Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I mean, I've seen them in person and I can still hardly believe everything that's happened.[n][uf 1 1][e]

[msg MSG_FUKA_116F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_117F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]There aren't any Shadows here, but I'm picking up the signal of a certain kind of door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]And the [uf 0 1 2]next floor[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27]. We've finally hit another checkpoint.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There won't be any enemies here, so you can check out the area without stressing over it.[n][uf 1 1][e]

[msg MSG_FUKA_118F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_119F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]How are you feeling? Please don't push yourself too hard.[n][uf 1 1][e]

[msg MSG_FUKA_120F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5114 0 0]This is quite the shift in atmosphere... It's more like ruins this time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Just like before, the enemies are stronger than they were below here. Stay sharp![n][uf 1 1][e]

[msg MSG_FUKA_121F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5103 0 0]What happened!? It's too dark to make anything out![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The entire floor's pitch black. Use your map and tread carefully![n][uf 1 1][e]

[msg MSG_FUKA_122F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_123F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_124F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]There's a teleporter. A breather might be a good idea...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm sensing a high-level threat on the next floor. Make sure you're ready.[n][uf 1 1][e]

[msg MSG_FUKA_125F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It's another Gatekeeper floor, but this one seems more intimidating than anything we've faced so far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Focus on the weaknesses and remember your fundamentals![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Plus, I can help too. Just say when, and I'll be ready![n][uf 1 1][e]

[msg MSG_FUKA_126F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Another fight with no rest in between... I guess all we can do is endure it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]We'll tough it out together! I'm here to support you any way I can![n][uf 1 1][e]

[msg MSG_FUKA_127F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]Phew... Consecutive battles really test your endurance, but it's such a relief when it's all over.[n][uf 1 1][e]

[msg MSG_FUKA_128F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_129F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_130F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]I'm sensing another strong presence. It's still a ways off, though.[n][uf 1 1][e]

[msg MSG_FUKA_131F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_132F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Are you sure you're not too tired? Please come back if you have any concerns about your condition.[n][uf 1 1][e]

[msg MSG_FUKA_133F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_134F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_135F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_136F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5030 0 0]There's a strong enemy on this floor. Are you prepared?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's also a [uf 0 1 2]border floor[uf 0 1 27] coming up in [uf 0 1 2]eight[uf 0 1 27] floors.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We're reaching the final stretch! Hang in there![n][uf 1 1][e]

[msg MSG_FUKA_137F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_138F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]There's another strong enemy up ahead. Don't let up![n][uf 1 1][e]

[msg MSG_FUKA_139F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_140F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_141F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_142F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]While everyone has different conditions for activating Theurgy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Understanding each person's quirks should make it easier to prepare for times of need.[n][uf 1 1][e]

[msg MSG_FUKA_143F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5067 0 0]Oh! The [uf 0 1 2]next floor[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27]. Just a little more of a push and we're on to the next area.[n][uf 1 1][e]

[msg MSG_FUKA_144F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_145F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]Floor 145... with the end of the labyrinth nowhere in sight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's a strong presence, but it's still a ways ahead of us. Let's take our time getting there.[n][uf 1 1][e]

[msg MSG_FUKA_146F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_147F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_148F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It's a little suffocating when the scenery never changes, isn't it?[n][uf 1 1][e]

[msg MSG_FUKA_149F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_150F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_151F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Watch out for coordinated attacks when facing multiple enemies at once.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It may be safest to concentrate on taking one down at a time.[n][uf 1 1][e]

[msg MSG_FUKA_152F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_153F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_154F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_155F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]It's a long road to travel... If nothing else, please don't force yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We even have a teleporter at our disposal, so let's play it safe.[n][uf 1 1][e]

[msg MSG_FUKA_156F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_157F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_158F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5077 0 0]We're currently on the 158th floor, but there's a strong presence on a floor not too high above us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There doesn't seem to be a set pattern for where the Gatekeepers are. Let's just focus on one at a time.[n][uf 1 1][e]

[msg MSG_FUKA_159F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_160F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_161F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]It's important to know your enemies' weaknesses, but pay attention to the other relevant intel as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Knowledge of an enemy's tactics can help you predict their next move.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]That means less damage taken and more opportunities to—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, what's that...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 0 1 2]Eleven[uf 0 1 27] floors away, I'm sensing another [uf 0 1 2]border floor[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's still a ways off. It might be best for you to return.[n][uf 1 1][e]

[msg MSG_FUKA_162F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_163F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's another strong presence guarding the way to the [uf 0 1 2]border floor[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's still a ways away, but we'll want to be ready regardless.[n][uf 1 1][e]

[msg MSG_FUKA_164F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_165F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_166F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]The roaming Shadows seem to spawn without limit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I hope we're able to cut them off at the source...[n][uf 1 1][e]

[msg MSG_FUKA_167F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_168F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_169F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]There aren't any enemies on this floor, but there is a teleporter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The strong presence awaits us on the next floor... How about stopping here for now?[n][uf 1 1][e]

[msg MSG_FUKA_170F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]You may have expected this, but there are strong presences on both this floor and the next one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Let's get past here first![n][uf 1 1][e]

[msg MSG_FUKA_171F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]There's only one enemy... But we can't get careless![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm pretty sure this one will hit especially hard. When you feel threatened, raise your guard![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]There's a [uf 0 1 2]border floor[uf 0 1 27] just past here, like before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]We're in the final stretch of this area! We can overcome this![n][uf 1 1][e]

[msg MSG_FUKA_172F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_173F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_174F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]This place hurts your eyes, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's awfully distracting, so be on the lookout for ambushes.[n][uf 1 1][e]

[msg MSG_FUKA_175F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_176F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_177F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_178F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's a strong enemy on the next floor! We'll want to be good and ready.[n][uf 1 1][e]

[msg MSG_FUKA_179F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]There's a teleporter here, so make sure you use it if you need to.[n][uf 1 1][e]

[msg MSG_FUKA_180F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_181F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]What a colorful wall. I wonder what it's modeled after...[n][uf 1 1][e]

[msg MSG_FUKA_182F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]There's a strong presence not too far ahead! You'll want to keep an eye on your stamina.[n][uf 1 1][e]

[msg MSG_FUKA_183F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_184F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]The further you climb, the more combinations of enemies you'll encounter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Choosing your squad based on the enemy types is one useful approach you could take.[n][uf 1 1][e]

[msg MSG_FUKA_185F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_186F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_187F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_188F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5036 0 0]You can always restock on consumables, so don't hesitate to use them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I know it can feel wasteful sometimes, but our top priority is survival, right?[n][uf 1 1][e]

[msg MSG_FUKA_189F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]There's a strong enemy waiting a few floors up— Wait, just how many are there...?[n][uf 1 1][e]

[msg MSG_FUKA_190F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_191F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_192F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_193F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]We're almost at the 200th floor. There's another Gatekeeper first, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]We should also be getting close to— Oh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Yes, I'm sensing a [uf 0 1 2]border floor[uf 0 1 27]! It's [uf 0 1 2]five[uf 0 1 27] floors up from here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Just a little further to go. Let's get through here first![n][uf 1 1][e]

[msg MSG_FUKA_194F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_195F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_196F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_197F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]I'm not sensing any enemies... The next floor also seems safe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It ought to be a [uf 0 1 2]border floor[uf 0 1 27]. Let's investigate.[n][uf 1 1][e]

[msg MSG_FUKA_198F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_199F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_200F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]I've detected a strong enemy a few floors up from here.[n][uf 1 1][e]

[msg MSG_FUKA_201F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_202F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_203F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5139 0 0]We've beaten so many strong Shadows... How many has it been so far?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]However many it is, we can't get careless now. Let's stay focused![n][uf 1 1][e]

[msg MSG_FUKA_204F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_205F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm sensing another Gatekeeper! It's still quite a ways off, though...[n][uf 1 1][e]

[msg MSG_FUKA_206F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5091 0 0]We've reached the 206th floor. The floor numbers are unspeakably high now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Do you think the floors will ever end? If only we had a clue...[n][uf 1 1][e]

[msg MSG_FUKA_207F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_208F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_209F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_210F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Even the run-of-the-mill Shadows have gotten too strong to let your guard down around...[n][uf 1 1][e]

[msg MSG_FUKA_211F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_212F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5004 0 0]Please return to the entrance whenever you're tired, okay?[n][uf 1 1][e]

[msg MSG_FUKA_213F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_214F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_215F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's a strong enemy a few floors above you... What kind could it be this time?[n][uf 1 1][e]

[msg MSG_FUKA_216F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_217F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_218F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]We've reached the floor with the strong enemy. Please get ready if you intend to confront it now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]And... What's this? There's a [uf 0 1 2]border floor[uf 0 1 27] coming up in [uf 0 1 2]eight[uf 0 1 27] floors.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Keep on pushing and we'll be there in no time. You've got this![n][uf 1 1][e]

[msg MSG_FUKA_219F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_220F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5123 0 0]You've reached the 220th floor. Just how tall is this place?[n][uf 1 1][e]

[msg MSG_FUKA_221F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_222F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_223F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_224F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's a strong presence on the next floor. We should start preparing now.[n][uf 1 1][e]

[msg MSG_FUKA_225F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]The [uf 0 1 2]next floor[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I must be picking up the Gatekeeper guarding the path there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]This won't be an easy fight! You'll need to be ready![n][uf 1 1][e]

[msg MSG_FUKA_226F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_227F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_228F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It's been a long road... But we've made it so far.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Let's stay calm and keep at it one step at a time.[n][uf 1 1][e]

[msg MSG_FUKA_229F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_230F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The enemies may be no pushovers, but neither are we...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Let's use what we've learned to teach them a lesson—and I'm here to help, too.[n][uf 1 1][e]

[msg MSG_FUKA_231F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]It's still a ways off, but I'm picking up a strong enemy on a floor above yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm anticipating a tough fight, so we'll want to be ready.[n][uf 1 1][e]

[msg MSG_FUKA_232F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_233F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_234F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_235F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_236F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]These Shadows are strong... And five of them to boot...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The order you take them out in is going to be the key to your success in battle. Make sure you're thoroughly prepared for them, too.[n][uf 1 1][e]

[msg MSG_FUKA_237F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_238F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]There's another high-level threat... It's a few floors up.[n][uf 1 1][e]

[msg MSG_FUKA_239F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_240F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_241F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]This enemy is going to be a real test. You'll need to be at the top of your game.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Don't worry, you can win this together. Full speed ahead![n][uf 1 1][e]

[msg MSG_FUKA_242F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_243F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_244F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_245F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]I don't sense any Shadows. This floor seems safe...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]But there's a strong presence on the next floor! And two floors up as well![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It looks like we're in for back-to-back battles. Let's prepare while we still can.[n][uf 1 1][e]

[msg MSG_FUKA_246F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]No teleporter again... That means we're in for back-to-back battles with strong enemies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]First things first—let's get through here! Don't hold back![n][uf 1 1][e]

[msg MSG_FUKA_247F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]All right, on to the next one! Try to prepare as best you can![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Huh? Isn't this...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]In [uf 0 1 2]nine[uf 0 1 27] floors, we'll be coming up on a [uf 0 1 2]border floor[uf 0 1 27]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Could this be the last one? Let's find out for ourselves![n][uf 1 1][e]

[msg MSG_FUKA_248F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_249F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_250F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_251F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_252F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5120 0 0]No way... What's that!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]I'm sensing a very powerful presence on the next floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]And I'm picking up equal-level threats from multiple floors after it... We're in for two fights in a row... No, maybe more![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]This is our toughest test so far... You'll want to be armed to the teeth for this one![n][uf 1 1][e]

[msg MSG_FUKA_253F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]There's no teleporter... You'll have to defeat them all to get back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]First round—show it who's boss! I'll support you as best I can![n][uf 1 1][e]

[msg MSG_FUKA_254F_NONE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Round two, coming up! Expect this one to be just as tough as the last.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]You can do it, though! I know you can![n][uf 1 1][e]

[msg MSG_FUKA_255F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]The third battle... This is the last one![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The [uf 0 1 2]border floor[uf 0 1 27] is right above us on the [uf 0 1 2]next floor[uf 0 1 27]. We're so close![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Let's put it all out there! Last big push, everyone![n][uf 1 1][e]

[msg MSG_FUKA_256F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_257F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_258F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]We're getting closer to Strega. I'm getting a reading one floor above us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Once you cross paths... I don't think you'll be able to avoid combat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There is a teleporter here, though, so make sure you're prepared.[n][uf 1 1][e]

[msg MSG_FUKA_259F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5128 0 0]Going by the signal... they're blocking our path upwards.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]But there's only one signal... They're not together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]I don't know what they have up their sleeve, but for now, our only way is up.[n][uf 1 1][e]

[msg MSG_FUKA_260F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_261F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please come back to the entrance if your health is low.[n][uf 1 1][e]

[msg MSG_FUKA_262F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]This signal that likely belongs to the Strega leader is fast approaching...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The next floor is a safe area, so let's get prepared there.[n][uf 1 1][e]

[msg MSG_FUKA_263F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5008 0 0]This floor seems safe. You ought to get the team organized and prepare for the upcoming battle here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Once you're ready... we'll have to settle the score.[n][uf 1 1][e]

[msg MSG_FUKA_220F_AB [Mitsuru Kirijo]]

[msg MSG_FUKA_228F_AB [Mitsuru Kirijo]]

[msg MSG_FUKA_236F_AB [Mitsuru Kirijo]]

[msg MSG_FUKA_244F_AB [Mitsuru Kirijo]]

[msg MSG_FUKA_252F_AB [Mitsuru Kirijo]]

[msg MSG_GATE_NOT_OPEN_MITU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20105 0 0]This floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's no mistaking it! Do you recall, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]How I once told you Tartarus was separated into multiple areas by borders resembling rifts?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I believe... this is one of those [uf 0 1 2]border floors[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm not sensing any enemies. Would you mind taking a look around?[n][uf 1 1][e]

[msg MSG_GATE_NOT_OPEN_MITU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20111 0 0]Another dead end... This is as far as we can go for now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Nice work—that's another checkpoint under our belt. Come on back whenever you're ready.[n][uf 1 1][e]

[msg MSG_GATE_NOT_OPEN_MITU_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_GATE_NOT_OPEN_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_GATE_NOT_OPEN_FUKA_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 20134 0 0]A dead end. Looks like we can't progress any further for now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]On the other hand, we've made good headway—nicely done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Come back whenever you're ready. It's your call to make, Leader.[n][uf 1 1][e]

[msg MSG_GATE_NOT_OPEN_FUKA_0_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]We've made it to the 256th floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]I sense an open area with no walls a few floors up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]That's probably what Ryoji-kun was talking about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]The way to the Promised Place... That's where we're supposed to go on January 31st.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We've made it this far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I have faith in you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]No matter what's waiting for us ahead, you won't... We won't lose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's time to put it all on the line... This is the fight to end them![n][uf 1 1][e]

[msg MSG_GATE_OPEN_MITU_00_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20105 0 0]This floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's no mistaking it! Do you recall, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]How I once told you Tartarus was separated into multiple areas by borders resembling rifts?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I believe... this is one of those [uf 0 1 2]border floors[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Take a look around for me, would you? Fortunately, there aren't any enemies nearby, but still, don't get careless.[n][uf 1 1][e]

[msg MSG_GATE_OPEN_MITU_00_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20111 0 0]All right, we're here. As I thought, this floor is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm not sensing any enemies. Could you take a look around the area, [uf 4 1]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's no knowing what might happen, so be careful, all right?[n][uf 1 1][e]

[msg MSG_GATE_OPEN_MITU_01_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]It seems to be a dead end... But I sense something from the walls and floors of this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Perhaps it's the precursor of the place rearranging itself? Take care not to get caught in the action.[n][uf 1 1][e]

[msg MSG_GATE_OPEN_MITU_01_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]This floor seems to be the last of its area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You should be able to progress now. Go ahead and give it a try.[n][uf 1 1][e]

[msg MSG_GATE_OPEN_FUKA_00_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]This floor used to be a dead end...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But I'm sensing that may have changed. Could you search the area?[n][uf 1 1][e]

[msg MSG_GATE_OPEN_FUKA_01_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]You should be able to get past the dead end now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please be careful not to get caught up in the floor shift...[n][uf 1 1][e]

[msg MSG_GATE_OPEN_FUKA_01_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]This area ends here. Now, there's a dead end...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But you should be able to get past it. Could you check?[n][uf 1 1][e]

[msg MSG_GATE_OPEN_FUKA_02_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]We've made it to the 256th floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]I sense an open area with no walls a few floors up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]That's probably what Ryoji-kun was talking about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]The way to the Promised Place... That's where we're supposed to go on January 31st.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We've made it this far...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I have faith in you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]No matter what's waiting for us ahead, you won't... We won't lose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's time to put it all on the line... This is the fight to end them![n][uf 1 1][e]

[msg MSG_GATE_OPEN_FUKA_02_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]You should be able to progress now. Let's go![n][uf 1 1][e]

[msg MND_COMU_LV_MAX_MES]
[uf 0 5 65278][uf 2 1]The Judgement Social Link reached its maximum level! You can now fuse Messiah, the savior![n][uf 1 1][e]

[msg MSG_FUKA_DISAPPEAR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]I'm sure there's someone here... Check everywhere, please![n][uf 1 1][e]

[msg MSG_MITURU_DISAPPEAR [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]I'm worried about the person who wandered in here... You need to find them before it's too late.[n][uf 1 1][e]

[msg MSG_FUKA_DISAPPEAR_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]It's a faint signal, but it's there... You just have to find them![n][uf 1 1][e]

[msg MSG_MITURU_DISAPPEAR_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]It's faint, but this signal definitely belongs to a living thing. Locating them is now our top priority.[n][uf 1 1][e]

[msg MSG_FUKA_FDOOR_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm getting a strange signal. Could this be... one of the doors?[n][uf 1 1][e]

[msg MSG_FDOOR_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Sometimes, Tartarus puts up a Monad door on a floor. If you happen to pass one up, it won't open for you during your current exploration.[n][uf 1 1][e]

[msg MSG_FUKA_FDOOR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]This signal... There's a Monad door here. Keep your eyes open for it![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5122 0 0]Ah— Is that...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's definitely a Shadow, but this is the first I've seen of its type![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5122 0 0]Huh!? What the...? I lost a signal from one of the treasure chests![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Could it be... a Shadow's snatching up treasure on this floor?[n][uf 1 1][e]

[sel SEL_HIGH_RARE_TUTO_00 top]
[uf 0 5 65278][uf 2 1]It's on now.[e]
[uf 0 5 65278][uf 2 1]Why, though?[e]

[msg MSG_FUKA_HIGH_RARE_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]Could it be attracted to the loot somehow?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]The Shadow's on the move now![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's headed your way—brace for combat![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]It seemed like some kind of rare Shadow...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]Shocking size to it though, right? Yet it got away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Given its size, I imagine defeating it would be well worth our while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]What do you say, Leader?[n][uf 1 1][e]

[sel SEL_HIGH_RARE_TUTO_01 top]
[uf 0 5 65278][uf 2 1]Let's hunt it down.[e]
[uf 0 5 65278][uf 2 1]I'm not done with that thing.[e]

[msg MSG_FUKA_HIGH_RARE_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5069 0 0]This signal—this movement...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]The Greedy Shadow's closing in on you![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]There it goes again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I think we'd get a really nice haul if we could defeat it. Would you like to chase it down?[n][uf 1 1][e]

[sel SEL_HIGH_RARE_00 top]
[uf 0 5 65278][uf 2 1]Let's chase the thing down.[e]
[uf 0 5 65278][uf 2 1]I'll let it off the hook this time.[e]

[msg MSG_HIGH_RARE_YUKARI_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1086 0 0]You're kidding, right? Obviously, we go after it, right?[n][uf 1 1][e]

[msg MSG_HIGH_RARE_JUNPEI_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Mr. Sticky Fingers stole our loot! We need to straighten him out.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_SANADA_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3080 0 0]Let's see how it carries itself in a fight. No sense letting it go scot-free.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_MITSURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]A specimen of that size is certainly a rare sight.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5086 0 0]Koro-chan's chomping at the bit! What do you say, Leader?[n][uf 1 1][e]

[msg MSG_HIGH_RARE_AEGIS_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6065 0 0]It was so big and golden and shiny... Almost larger than life. What's your decision, [uf 4 2]-san?[n][uf 1 1][e]

[msg MSG_HIGH_RARE_AMADA_10 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7075 0 0]It sure was something, wasn't it? Don't you think we should go after it?[n][uf 1 1][e]

[msg MSG_HIGH_RARE_KOROMARU_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_HIGH_RARE_ARAGAKI_10 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9049 0 0]So... are we goin' after it?[n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Understood![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Our target is fleeing at breakneck speed. You'll need to track it down quickly![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5123 0 0]Understood. We shouldn't get too distracted trying to chase it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Let's return to our exploration, shall we?[n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Understood! In that case...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We can use my Tartarus Search to make sure we corner it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]What would you like to do?[n][uf 1 1][e]

[sel FSS_FUKA_ORDER top]
[uf 0 5 65278][uf 2 1]Please do a [uf 2 4 2].[e]
[uf 0 5 65278][uf 2 1]I'll track it down myself.[e]

[msg MSG_FUKA_HIGH_RARE_SKILL_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Got it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Readyyy... Now![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'll call out directions for you—follow them to guide the Shadow into a dead end![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Make a left there! You're so close—hang in there![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Make a right![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_6 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Left, please![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_7 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's a right there! Almost there![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_8 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Okay, go straight from there! We've got him where we want him![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_SKILL_9 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]D-Do you have something up your sleeve?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Okay, you're the boss! He's quick though, so be careful![n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_DEFEA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Well, that was a lucky find, wasn't it? Now that that's settled, shall we get back to exploring?[n][uf 1 1][e]

[msg MSG_FUKA_HIGH_RARE_KEYFR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Back to business for us![n][uf 1 1][e]

[msg MSG_MITSURU_005F_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4070 0 0]Hmm, that device there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We may be able to use it. Do check it out.[n][uf 1 1][e]

[msg MSG_FUKA_005F_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5071 0 0]Oh, that device there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We may be able to use it. Would you mind inspecting it?[n][uf 1 1][e]

[msg MSG_FA_RBOX_MITSURU_001 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm sensing a valuable chest nearby. See if you can retrieve it.[n][uf 1 1][e]

[msg MSG_FA_RBOX_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's a valuable chest close by. Can you get it?[n][uf 1 1][e]

[msg MSG_FA_MBOX_MITSURU_001 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm detecting a chest that requires fragments to open. Try to find it.[n][uf 1 1][e]

[msg MSG_FA_MBOX_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It looks like one of those chests that need fragments to open is around here.[n][uf 1 1][e]

[msg MSG_FA_CLOCK_MITSURU_001 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]This floor seems like it's connected to somewhere else for some reason...[n][uf 1 1][e]

[msg MSG_FA_CLOCK_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Is that a... door on this floor? It feels similar to the entrance...[n][uf 1 1][e]

[msg MSG_FA_RENEMY_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Hm... I'm sensing a rare Shadow on this floor.[n][uf 1 1][e]

[msg MSG_FA_RENEMY_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, it looks like there's a rare Shadow on this floor![n][uf 1 1][e]

[msg MSG_FA_BUGENEMY_MITSURU_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Hm, the enemies here seem to be acting strangely...[n][uf 1 1][e]

[msg MSG_FA_BUGENEMY_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Huh? The Shadows on this floor are acting weird...[n][uf 1 1][e]

[msg MSG_FA_ALLRARE_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]This is quite astonishing... There appear to only be rare Shadows on this floor.[n][uf 1 1][e]

[msg MSG_FA_ALLRARE_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]I thought I detected rare Shadows on this floor, but... only rare Shadows?[n][uf 1 1][e]

[msg MSG_FA_ALLSTR_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]We've got trouble![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]It appears all the enemies on this floor are powerful. Exercise extreme caution![n][uf 1 1][e]

[msg MSG_FA_ALLSTR_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]What!? These enemies...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]This whole floor is full of strong enemies! Be careful here![n][uf 1 1][e]

[msg MSG_FA_DARK_MITSURU_001 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]It's difficult to see anything on this floor. Keep your guard up![n][uf 1 1][e]

[msg MSG_FA_DARK_FUKA_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]It's too dark to make anything out here! Please be careful![n][uf 1 1][e]

[msg MSG_MISSING_FOUND_CONECT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]This is...[n][uf 1 1][e]

[msg MSG_MISSING_FOUND_NEAR1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]There's a person nearby. It must be one of those missing people who wandered in here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm getting a signal from floor [uf 2 4 1]. Let's hurry![n][uf 1 1][e]

[msg MSG_MISSING_FOUND_NEAR2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Are those...? I'm sensing humans nearby! They must be those missing people...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm getting readings from floors [uf 2 4 1] and [uf 2 4 2]. We have to rescue them![n][uf 1 1][e]

[msg MSG_MISSING_UPPER [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]I'm getting a faint reading of a person. It could be one of the people who got lost in here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It's too far for me to pinpoint their location. They seem to be on a much higher floor...[n][uf 1 1][e]

[msg MSG_MISSING_LOWER [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]There's someone in here. It's probably a missing person...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]But they're far away. It seems like they're on a much lower floor.[n][uf 1 1][e]

[msg MSG_MISSING_NOT_REACHED0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense someone on a higher floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]It's a floor we haven't been to yet, though. I hope we can get there soon...[n][uf 1 1][e]

[msg MSG_MISSING_NOT_REACHED0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's another human presence, too. It's coming from above us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]But they're on a floor we haven't reached yet. I hope we can make it there before it's too late...[n][uf 1 1][e]

[msg MND_TUTO_MONAD01 [Mitsuru Kirijo]]

[msg MSG_TUTO_MONAD02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It doesn't seem like a Shadow... It's larger and seems almost like a wall...[n][uf 1 1][e]

[sel SEL_TUTO_MONAD top]
[uf 0 5 65278][uf 2 1]How curious...[e]
[uf 0 5 65278][uf 2 1]Let's take a closer look.[e]

[msg MSG_TUTO_MONAD_ADDTALK01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4028 0 0]Hmm... If it's dangerous, it's possible that it could in fact be riskier to simply ignore it.[n][uf 1 1][e]

[msg MSG_TUTO_MONAD_ADDTALK02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3062 0 0]Well, fortune favors the brave, right? Besides, we didn't come this far by running from our fights.[n][uf 1 1][e]

[msg MSG_TUTO_MONAD03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Okay, then. Going by the signal I'm getting, it shouldn't be far from you![n][uf 1 1][e]

[msg SYS_TUTO_StrongSymbol01]
[uf 0 5 65278][uf 2 1][uf 1 4 0]While exploring, you may come across enemies in altered status conditions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 1 4 0]Enraged enemies will rapidly charge at you in a straight line. If combat is triggered, some of the enemies may be afflicted with Rage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 1 4 0]Rage is just one possible altered enemy status. Pay attention to enemies' behavior to glean what you might be dealing with.[n][uf 1 1][e]

[msg MND_RareUranai]
[uf 0 5 65278][uf 2 1]The fortune-teller mentioned that[n]I will "face an adversary clad in gold"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I'll run into a rare enemy...[n][uf 1 1][e]

[msg MSG_TUTO_REAPER_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Oh, I should tell you something Kirijo-senpai told me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]She said there's a Reaper that appears in Tartarus.[n][uf 1 1][e]

[sel SEL_TUTO_REAPER top]
[uf 0 5 65278][uf 2 1]A "Reaper"?[e]
[uf 0 5 65278][uf 2 1]"Appears"?[e]

[msg MSG_TUTO_REAPER_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Apparently, it will appear out of nowhere and chase you endlessly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]And if you get caught, um... I think you know what is supposed to happen if a "Reaper" catches you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Maybe it's trying to get rid of us since we're outsiders in Tartarus...?[n][uf 1 1][e]

[msg MSG_TUTO_REAPER_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]She wasn't too sure on the details, but I guess it appears when you stay on one floor for too long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 0 1 2]Jamming may not work[uf 0 1 27] on it, so please evacuate to another floor if you ever encounter it.[n][uf 1 1][e]

[msg MSG_TUTO_JAMMING_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5102 0 0]There are so many enemies, I don't think we'll be able to avoid them entirely...[n][uf 1 1][e]

[sel SEL_TUTO_JAMMING top]
[uf 0 5 65278][uf 2 1]Let's just press through, then.[e]
[uf 0 5 65278][uf 2 1]We'll be fine—we have Fuuka.[e]

[msg MSG_TUTO_JAMMING_02_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Please wait! It could be dangerous without a plan...[n][uf 1 1][e]

[msg MSG_TUTO_JAMMING_02_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Um, I appreciate your confidence in me, but I mostly just locate enemies...[n][uf 1 1][e]

[msg MSG_TUTO_JAMMING_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Hm... Actually, I may be able to help out here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm going to use my [uf 0 1 35]Jamming[uf 0 1 27] skill![n][uf 1 1][e]

[msg MSG_TUTO_JAMMING_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 0 1 35]Jamming[uf 0 1 27] obstructs enemy detection, making it harder for them to find you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]In other words, enemies shouldn't attack you even if you enter their line of sight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It won't always work on all enemies, but for these ones here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Help me, Lucia...![n][uf 1 1][e]

[msg MSG_TUTO_ENEMY_ESCAPE_M0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4103 0 0]Hm? The enemies on this floor seem restless...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]I see... They're intimidated by us. We should be able to avoid any unnecessary combat.[n][uf 1 1][e]

[msg MSG_TUTO_ENEMY_ESCAPE_F0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5098 0 0]Huh? The enemies on this floor seem strangely agitated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It looks like they're afraid of us. Maybe you won't have to fight them if you don't want to.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SYLP01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Before fighting a stronger enemy, there's a skill of mine I'd like you to use. It's called [uf 0 1 35]Sylphid Aura[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SYLP02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It'll enhance everyone's abilities a bit at the start of battle. It might give you some peace of mind.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SHOCK01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5066 0 0]If you want to be able to explore a little easier, you might want to use my [uf 0 1 35]Shock Noise[uf 0 1 27] skill.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SHOCK02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It'll inflict Distress on all enemies on a floor so they flee when they see you.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_ESCAPE01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5075 0 0]If you ever get stuck somewhere and can't find a teleporter to use...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You can use my skill [uf 0 1 35]Escape Route[uf 0 1 27] to return to the entrance whenever you like.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_ESCAPE02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]If you're running low on health or stamina, please don't push yourself—come back and regroup.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SEARCH01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5086 0 0]You can use my skill [uf 0 1 35]Tartarus Search[uf 0 1 27] to analyze the floor you're currently on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It'll give you a layout of the whole floor, and you can even move right to the next floor if you want.[n][uf 1 1][e]

[msg MSG_TUTO_SKILL_SEARCH02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It does take stamina, though, so you can't use it over and over, but use it when you need to.[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_M01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4078 0 0]By the way, I received a report from the chairman.[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_F01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]Oh, by the way, the chairman sent me a report.[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_M02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]You know that [uf 0 1 2]clock[uf 0 1 27] by the stairs at the entrance? The one that's about as tall as you?[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_F02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]You know how there's a [uf 0 1 2]clock[uf 0 1 27] about our height next to the stairs at the entrance?[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_M03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]At first glance, it may look ornamental, but it can actually be operated by using [uf 0 1 39]Twilight Fragments[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_F03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It might just look decorative, but it apparently works with [uf 0 1 39]Twilight Fragments[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_M04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Supposedly, it can "restore the user to his or her rightful state."[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_F04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]According to the chairman, it's supposed to "restore the user to his or her rightful state."[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_M05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]I suppose its purpose is recovery. I'm curious how it works, but regardless, let's take advantage of it.[n][uf 1 1][e]

[msg MSG_TUTO_HEALCLOCK_F05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]I guess it's supposed to help you recover. It seems mysterious, but I think we should make use of it.[n][uf 1 1][e]

[msg MSG_KF_INFO_042F_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Hm... I don't sense any enemies above here. We may be approaching a [uf 0 1 2]border floor[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Reaching it would be a great accomplishment. I'll be counting on you.[n][uf 1 1][e]

[msg MSG_KF_INFO_042F_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Oh, it looks likely that the [uf 0 1 2]next floor[uf 0 1 27] is a [uf 0 1 2]border floor[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If we make it, that'll be one milestone cleared. Good luck![n][uf 1 1][e]

[msg MSG_KF_INFO_060F_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, hang on![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'm picking up on another [uf 0 1 2]border floor[uf 0 1 27] in... [uf 0 1 2]nine[uf 0 1 27] floors.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's still pretty far off, so let's focus on getting through here first.[n][uf 1 1][e]

[msg MSG_TUTO_TheurgiaGauge01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]Leader, do you have a moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I'd like to share something I've found out about using [uf 0 1 2]Theurgy[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Theurgy can't be used just any time. The user has to reach an emotional peak first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]In other words, Theurgy can only be used [uf 0 1 2]after enough power has built up[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Also, how someone builds up this power is different depending on the person.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]For Kirijo-senpai, it's when she inflicts status ailments on an enemy, but for Yukari-chan, it's when she heals someone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Try out different things and see what works for different teammates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Theurgy is very powerful. We'll definitely want to use it as much as we can.[n][uf 1 1][e]

[msg PFM_SHIFT_GET]
[uf 0 5 65278][uf 2 1]You can now perform Shifts in combat.[n][uf 1 1][e]

[msg MND_Uranai_Type01_0]
[uf 0 5 65278][uf 2 1]I had a [uf 0 1 2]Rarity Fortune[uf 0 1 27] read today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, [uf 0 1 2]I will face an adversary clad in[n]gold[uf 0 1 27]. Maybe I'll run into a rare enemy...[n][uf 1 1][e]

[msg MND_Uranai_Type02_0]
[uf 0 5 65278][uf 2 1]I had a [uf 0 1 2]Blighting Fortune[uf 0 1 27] read today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, [uf 0 1 2]I will gain an advantage in[n]conflicts[uf 0 1 27]. I might be luckier in battle...[n][uf 1 1][e]

[msg MND_Uranai_Type03_0]
[uf 0 5 65278][uf 2 1]I had a [uf 0 1 2]Gamble Fortune[uf 0 1 27] read today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, [uf 0 1 2]my destiny holds a double-edged[n]sword[uf 0 1 27]. Maybe I'll run into unusual enemies...[n][uf 1 1][e]

[msg MND_Uranai_Type04_0]
[uf 0 5 65278][uf 2 1]I had a [uf 0 1 2]Soul Fortune[uf 0 1 27] read today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, [uf 0 1 2]I will feel a powerful drive[uf 0 1 27].[n]My Theurgy gauge may charge faster...[n][uf 1 1][e]

[msg MND_Uranai_Type05_0]
[uf 0 5 65278][uf 2 1]I had a [uf 0 1 2]Safety Fortune[uf 0 1 27] read today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, [uf 0 1 2]my destiny holds a moment[n]of tranquility[uf 0 1 27]. Maybe I'll avoid setbacks...[n][uf 1 1][e]

[msg SYS_Tuto_BadStatus01]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Status Ailments[uf 0 1 27] has been added to Tutorials.[n][uf 1 1][e]

