[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 1 0 0]What is this...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]That's... his life essence.[n][uf 1 1][e]

[msg MSG_002_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]This is what happened that night...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Using the power of the Great Seal, his own essence became the seal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 5 0 0]But when someone's life essence leaves their body, they die...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 6 0 0]To do this intentionally... He must have already found his answer to life.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 7 0 0]"His answer to life"...[n][uf 1 1][e]

[msg MSG_004_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 8 0 0]I don't think he has any regrets.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 1 0 0 9 0 0]He even managed to keep his promise to you all before his consciousness finished fading away...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]"His promise"? You mean to meet up on graduation day?[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Wait... How do you know about all that?[n][uf 1 1][e]

[msg MSG_007_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]"How"...? I just do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 13 0 0]I'm probably like Nyx, or this person who became the seal... I think I belong on this side.[n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Hm... Nyx is able to bring death to all things, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]If she's that powerful... then what was stopping her before he became the seal?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Huh... Was there someone else...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Then what about before humanity existed?[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]What are you getting at?[n][uf 1 1][e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]I'm not sure why this occurred to me, but I don't think Nyx is malicious...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Normally, a seal shouldn't be necessary.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 1 0 0 21 0 0]What!? Are you saying he did this for nothing!?[n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 22 0 0]No, I think what he was actually trying to do—[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Uhh, the hell was that!?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 24 0 0]Everyone, look![n][uf 1 1][e]

