[msg MSG_JUNPEI_BIBIRU [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 1 10002 0 0]Huh? Where're all the Shadows?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 1 10003 0 0]Damn, I was all ready to go and everything.[n][uf 1 1][e]

[msg MSG_KAUNTO_MITURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 1 0 1 10004 0 0]There's no time! Run![n][uf 1 1][e]

[msg MSG_SHINPAI_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 1 20621 0 0]What's up with Junpei? Did something happen...?[n][uf 1 1][e]

