[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5067 0 0]I don't detect any more Shadows on this floor... That figure's disappeared, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]There's a lot that still concerns me, but for now—good job, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]That was our first encounter with a tough enemy... Do you think we'll be able to progress at our current strength?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]We'll be fine.[e]
[uf 0 5 65278][uf 2 1]I'm not sure...[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5116 0 0]It's reassuring to see you so confident.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5119 0 0]But you did take down a strong foe just now without any major issue. Isn't that something to be proud of?[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]I'll also be providing you with navigational assistance. The going might be tough, but let's do the best we can![n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5138 0 0]We managed to take down that tough enemy. Do you think we should head back now, or keep going?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Now that we've secured a supply route, we should be clear to proceed so long as we stay cautious.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Let's head back.[e]
[uf 0 5 65278][uf 2 1]Let's keep going.[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5116 0 0]All right. No good will come of pushing ourselves too hard, I suppose. Let's resume once we're ready.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5116 0 0]Okay, then. Let's try to keep riding this momentum.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Whatever you decide, Aigis, I'll be here to help. You can count on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Okay then, shall we?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5010 0 0]Phew, looks like the coast is clear. Now we'll be able to progress. Great job, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Your orders were spot-on. Impressive strategy, as always.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Thank you very much.[e]
[uf 0 5 65278][uf 2 1]I still have a lot to learn.[e]
[uf 0 5 65278][uf 2 1]It's due to your help, Fuuka-san.[e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5032 0 0]Oh, no, I'm the one who ought to be thanking you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Hehe, that was a very Aigis response, though.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5131 0 0]Hehe, I should've known you'd say that. You're so humble, Aigis.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5122 5122 0]Huh? Oh, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]I'm just a little flustered, is all. But thank you, Aigis.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5116 0 0]Well, now that the enemy's down, shall we press on? I'm detecting some stairs nearby. Should we look for them?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5062 0 0]If that figure is the one calling the Shadows, then that means it intends to stop us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Does that make it our enemy...? What do you think, Aigis?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]It's an enemy.[e]
[uf 0 5 65278][uf 2 1]It might be an ally.[e]
[uf 0 5 65278][uf 2 1]I'm not sure.[e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5028 0 0]That'd be the logical conclusion... But what is it after?[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5067 0 0]Right... What we see here may reflect our inner thoughts, was it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0]At least, that's what Metis said, if I recall correctly.[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5028 0 0]That's fair... We don't have enough information to go off of, anyway.[n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]I just get worried so easily. It's a bad habit of mine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Right now, let's focus on pursuing that figure since it got away.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5086 0 0]Well, we managed to drive back the enemy. Do you feel like we've gotten back up to speed, combat-wise?[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]We're in good shape.[e]
[uf 0 5 65278][uf 2 1]Not yet, no.[e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5025 0 0]That's great to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]It seemed like you all were struggling a bit when you first started fighting again. I was a little worried.[n][uf 1 1][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5094 0 0]Really...? Well, I guess you were fighting pretty frequently back then. It may take a while to regain that lost experience.[n][uf 1 1][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]I think the fighting's only going to get more intense. Let's make sure we're all prepared before we keep going.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5138 0 0]The enemy's gone down. Well done, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 0 0 0]That figure disappeared sometime during the battle, though. It's like it doesn't want to fight...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]Is that even possible...? For a Shadow to dislike fighting?[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]Maybe it is...[e]
[uf 0 5 65278][uf 2 1]It's too early to tell.[e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5028 0 0]Yeah, maybe. We don't know enough about Shadows to rule it out.[n][uf 1 1][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5028 0 0]You're right. Maybe it's just observing us for now, only to attack us later.[n][uf 1 1][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]There's still so much for us to learn...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]But now's not the time to dwell on that, is it? Let's get going, Aigis.[n][uf 1 1][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5010 0 0]We'll be able to make more progress now. Great work, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Well, now that we've taken down the enemy, what should we do next? Keep going?[n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]Let's keep exploring.[e]
[uf 0 5 65278][uf 2 1]Let's head back for a bit.[e]
[uf 0 5 65278][uf 2 1]I'm not sure...[e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5025 0 0]All right then! No objections here.[n][uf 1 1][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5025 0 0]All right then. Remember, taking breaks is important.[n][uf 1 1][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5061 0 0]R-Right, erm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]If you're not sure, maybe we should head back and prep before setting out. Better safe than sorry, don't you think?[n][uf 1 1][e]

[msg MSG_037_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]You can count on me to navigate![n][uf 1 1][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5001 0 0]Nicely done, Aigis. These fights are really tough...[n][uf 1 1][e]

[sel SEL_039_0_0 top]
[uf 0 5 65278][uf 2 1]It doesn't seem that way to me.[e]
[uf 0 5 65278][uf 2 1]They really are difficult...[e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5098 0 0]It doesn't?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Hehe, I was starting to get a little worried, but you just made me feel so much better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]You really are something, Aigis.[n][uf 1 1][e]

[msg MSG_041_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5062 0 0]Perhaps we need to spend some time training on the upper floors to improve our combat capabilities.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]I know our priority is to make progress, but it's something to consider.[n][uf 1 1][e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5086 0 0]You did great in that last battle, Aigis. Now we can move on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Oh, as for the things I'm looking into...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Well, I haven't made much progress on that front... Sorry, Aigis.[n][uf 1 1][e]

[sel SEL_043_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry about it.[e]
[uf 0 5 65278][uf 2 1]That's a shame...[e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5042 0 0]Okay... I'll try. Thank you.[n][uf 1 1][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0][uf 3 1 3 0 65535 5090 0 0]Yes, it really is... I'm disappointed in myself as well.[n][uf 1 1][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Just a little longer, and this will all be over... Soon, we'll be able to understand what's happening.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0]I'll work even harder than before. Keep up the good work, Aigis![n][uf 1 1][e]

[msg MSG_047_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5138 0 0]Nicely done in that last battle, Aigis. How are you faring?[n][uf 1 1][e]

[sel SEL_048_0_0 top]
[uf 0 5 65278][uf 2 1]No issues to report.[e]
[uf 0 5 65278][uf 2 1]I've performed better...[e]
[uf 0 5 65278][uf 2 1]I'm in top condition.[e]

[msg MSG_049_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5109 0 0]Hehe, good to hear. Remember not to push yourself too hard, though. Okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Now let's get moving. We need to catch up with that figure.[n][uf 1 1][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5116 0 0]Yeah, I'm sure... That was a really tough fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]There's that figure, too... Perhaps we should consider heading back to heal up before we keep going.[n][uf 1 1][e]

[msg MSG_051_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5108 0 0]Hehe, I could tell. I knew you had it in you, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]We have to catch up to that figure though, so we'll have to press on.[n][uf 1 1][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5072 0 0]Oh, sorry, I didn't mean to overstep! It's your call whether we keep going or head back, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Anyway, you're doing great![n][uf 1 1][e]

[msg MSG_053_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 3 0 65535 5003 0 0]Hey, Aigis... Now that the fighting's over, could we talk for a moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]Do you think we might... have an encounter that we never thought possible?[n][uf 1 1][e]

[sel SEL_054_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, I do.[e]
[uf 0 5 65278][uf 2 1]No, I don't.[e]
[uf 0 5 65278][uf 2 1]I'll worry about that later.[e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5098 0 0]Y-You really think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 50 0 0]Well... I suppose you never know what might happen when it comes to Personas and Shadows.[n][uf 1 1][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5062 0 0]Ah... Yeah, I guess that would be the logical conclusion...[n][uf 1 1][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5098 0 0]Um, I don't think that really answers my question...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Hehe, you're right, though. We'll cross that bridge when we get to it.[n][uf 1 1][e]

[msg MSG_058_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5057 0 0]Sorry, it's just... a lot's happened since we've come here, so I've been overthinking things.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Well, it's back to navigating for me.[n][uf 1 1][e]

[msg MSG_059_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 3 0 65535 5077 0 0]After taking down those Shadows... the end can't be too far now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]I'm honestly a little scared of what's waiting for us... Everything I imagine is downright terrible.[n][uf 1 1][e]

[sel SEL_060_0_0 top]
[uf 0 5 65278][uf 2 1]I'm also afraid...[e]
[uf 0 5 65278][uf 2 1]Everything will be fine, I know it.[e]

[msg MSG_061_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5092 0 0]Really? You are?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]I see... But we still have each other.[n][uf 1 1][e]

[msg MSG_062_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 3 0 65535 5122 0 0]Aigis, I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]No, you're right. Everything's going to be just fine...[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0][uf 3 1 3 0 65535 5042 0 0]I'm glad I got to talk to you about this. It's helped me calm down a bit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 50 0 0]Okay... Should we get going?[n][uf 1 1][e]

