[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Let's see... My large items have been shipped... Am I forgetting anything...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]I just got word. Our transportation will be here shortly.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]You're taking everyone else too?[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Yes, their new dorms are on the way to the lab anyway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]And since we're all here, I thought we might as well travel together. It would be dull otherwise.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 6 65535 0 0][uf 3 1 1 0 0 6 0 0]Has anyone seen Junpei? I told him not to be late...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Waaaaaaahhh![n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Junpei-kun!?[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]I bet he's trying to carry everything at once. Just ignore him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]He did the same thing last year.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 2 65535 0 0][uf 3 1 1 0 0 11 0 0]I see... That sounded like it really hurt, though...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Owww, my face... No one saw that, right?[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Are you all right? Can't leave him alone for five minutes...[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Sounds like they're here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]Let's get going, shall we?[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Um...![n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 17 0 0]I... actually have a favor to ask...[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]What is it?[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0]I, uh... I know it's last-minute and might be too late, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Would it be okay for me to... not go back to the lab?[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Before... I thought I'd lost my purpose. My reason to live...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 22 0 0]But now I realize that isn't the case.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 2 65535 0 0][uf 3 1 1 0 0 23 0 0]If possible... I would like to keep attending school with Yukari-san and everyone.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]I want to continue experiencing new things with you all![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]If it's not too late...[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 6 65535 0 0][uf 3 1 0 0 0 27 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Well... It would be difficult, since I'm no longer involved with Gekkoukan High...[n][uf 1 1][e]

[msg MSG_020_0_0 [Driver]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 20]Your transportation has arrived, ma'am.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Thank you.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 31 0 0]Senpai![n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 32 0 0]I apologize, but there's been a sudden change in plans. We'll now be going to the school's Tatsumi Hall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 33 0 0]The transfer to the lab has been canceled.[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 34 0 0]Senpai... You mean...!?[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 2 65535 0 0][uf 3 1 1 0 0 35 0 0]Hell yeah! That's what I'm talkin' about![n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Thank you so much![n][uf 1 1][e]

[msg MSG_026_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 2 65535 0 0][uf 3 1 1 0 0 37 0 0]It's an honor to be able to stay with you all![n][uf 1 1][e]

