[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 201 65535 0 0][uf 3 1 1 0 0 1 0 0]What...!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 2 0 0]This is the Abyss of Time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 3 0 0]It's uncharted territory that I believe spreads underground, much like the roots of a tree.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 201 65535 0 0][uf 3 1 1 0 0 4 0 0]How could something like this have appeared under the lounge?[n][uf 1 1][e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 5 0 0]At first, the Abyss of Time was just a small, self-contained space.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 6 0 0]But then one day, it started growing rapidly and eventually spread to your dorm.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]It's clear just by looking at it that this place wasn't man-made.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 6 65535 0 0][uf 3 1 1 0 0 8 0 0]It might be the product of some dangerous power, just like Tartarus was.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Sheesh... Haven't we had enough of that kinda stuff already?[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 10 0 0]I'm not sure words alone can fully convey what's happening, but the flow of time here is abnormal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 11 0 0]That's why time is looping—and why you can't leave the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 12 0 0]The only solution is to find a way to somehow [uf 0 1 2]eradicate the Abyss of Time[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Eradicate it? How're we supposed to do that?[n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 14 0 0]I've already tried the simplest method that has the highest probability of success...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 15 0 0]...Eliminating all of you.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 16 0 0]The Abyss of Time is linked to this dorm, as if drawn to it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 17 0 0]And for some reason, you are the only ones who can perceive the time loop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 18 0 0]Clearly, there is a strong connection between all of you and what's happening.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 6 65535 0 0][uf 3 1 1 0 0 19 0 0]So that's why you attacked? To eliminate us...?[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 20 0 0]What the hell!? We've never even heard of this place before![n][uf 1 1][e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 21 0 0]If there is another way, it can only be found by entering the Abyss of Time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 22 0 0]You'll have to discover the cause and strike at its source.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]So you want us to investigate it under the assumption that we'll have to fight?[n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 24 0 0]That's why I insisted on the extra equipment to protect Aigis.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 6 65535 0 0][uf 3 1 1 0 0 25 0 0]Hold on... You're joking, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 6 65535 0 0][uf 3 1 1 0 0 26 0 0]Are you seriously telling us that we have to risk our lives again like we did with Tartarus!?[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Never mind that! How are we supposed to just believe whatever you say and jump into that freaky place blind!?[n][uf 1 1][e]

[msg MSG_017_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 28 0 0]Well, do you have a better plan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 29 0 0]The basement of your dorm is an infinite abyss, time is looping, and you can't reach the outside world...[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Ah, if we can't leave the dorm, how will we eat!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 3 25 25]If we're stuck here long enough, and we run out of food...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 6 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 4 25 25]Are we going to starve to death!?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 6 65535 0 0][uf 3 1 1 0 0 33 0 0]Noooooo![n][uf 1 1][e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 34 0 0]If the current situation continues, things could get worse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 35 0 0]This is your only option if you want to survive.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 36 0 0]Naturally, we all want to survive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 37 0 0]But you attacked us the minute you saw us. You must understand that we can't simply entrust our lives to you.[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 6 65535 0 0][uf 3 1 1 0 0 38 0 0]I'm not even buying your reason for being here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 6 65535 0 0][uf 3 1 1 0 0 39 0 0]You say you want to protect Aigis, but what's in it for you?[n][uf 1 1][e]

[msg MSG_022_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 17 11 4 1][e]

[msg MSG_023_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 40 0 0]What's in it for me? I'm doing this because I care about her![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 41 0 0]I mean, she's all I have![n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]About that... Your story doesn't fit the facts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 43 0 0]Aigis was the last of her series—no other units were produced after her.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 6 65535 0 0][uf 3 1 1 0 0 44 0 0]And on top of that, it bothers me that you talk like you've been in the Abyss of Time from the start.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 6 65535 0 0][uf 3 1 1 0 0 45 0 0]I thought this was supposed to be uncharted territory that was unconnected to the outside world until recently.[n][uf 1 1][e]

[msg MSG_026_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 46 0 0]W-Well...[n][uf 1 1][e]

[msg MSG_027_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 6 65535 0 0][uf 3 1 1 0 0 47 0 0]Aren't you supposed to be an anti-Shadow weapon anyway? Attacking us humans to save Aigis doesn't make sense.[n][uf 1 1][e]

[msg MSG_028_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 48 0 0]That's... I... Um...[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 49 0 0]Well? We're waiting... Hope you've got a good answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 50 0 0]You better not be thinking you can get away with pullin' a fast one on us again...[n][uf 1 1][e]

[msg MSG_030_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 51 0 0]E-Enough about me! What good is knowing any of this anyway!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 52 0 0]Besides, haven't I already told you that there's no time to waste!?[n][uf 1 1][e]

[msg MSG_031_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 53 0 0]Now, follow me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 201 65535 0 0][uf 3 1 1 0 0 54 0 0]Or are you giving up so soon? Because if you are, you should have just let me kill you in the first place![n][uf 1 1][e]

[msg MSG_031_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 4 2 0][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 6 65535 0 0][uf 3 1 1 0 0 55 0 0]What did you just say!?[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 56 0 0]You're right. We may have no choice but to enter this place...[n][uf 1 1][e]

[msg MSG_033_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 201 65535 0 0][uf 3 1 1 0 0 57 0 0]But if you continue to act this way, we'll have to go on without you.[n][uf 1 1][e]

[msg MSG_033_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 17 11 4 1][e]

[msg MSG_034_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 58 0 0]Huh...? Without me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 201 65535 0 0][uf 3 1 1 0 0 59 0 0]Haha... You couldn't possibly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 201 65535 0 0][uf 3 1 1 0 0 60 0 0]Y-You need me! I know the most about the Abyss. A-And...[n][uf 1 1][e]

[msg MSG_035_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 61 0 0]As if! What do you know about what we need?[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 201 65535 0 0][uf 3 1 1 0 0 62 0 0]We all risk our lives for each other.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 2 201 65535 0 0][uf 3 1 1 0 0 63 0 0]If you think so little of my friends, then you can't come with us.[n][uf 1 1][e]

[msg MSG_037_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 64 0 0]No...[n][uf 1 1][e]

[msg MSG_038_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 65 0 0]Might suck, but if that's how you're gonna be, then we'll just leave you here by yourself.[n][uf 1 1][e]

[msg MSG_039_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 66 0 0]...![n][uf 1 1][e]

[msg MSG_039_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 67 0 0]By... myself?[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 6 65535 0 0][uf 3 1 1 0 0 68 0 0]Aw, not happy with that? If you'd rather be our enemy, then we can settle things right here.[n][uf 1 1][e]

[msg MSG_041_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 69 0 0]W-We don't have to go that far...[n][uf 1 1][e]

[msg MSG_042_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 201 65535 0 0][uf 3 1 1 0 0 70 0 0]I'm... sorry.[n][uf 1 1][e]

[msg MSG_043_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 71 0 0]I'm sorry... Please don't be mad at me, Aigis.[n][uf 1 1][e]

[msg MSG_043_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 72 0 0]I'll listen to you from now on! I will! So please don't leave me...[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 0 0 0 73 0 0]......[n][uf 1 1][e]

[msg MSG_045_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 74 0 0]Look, even if you change your tune now, it's not like we're gonna start trusting you...[n][uf 1 1][e]

[msg MSG_046_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 6 65535 0 0][uf 3 1 1 0 0 75 0 0]Still though, maybe it's true that all she really wants is to protect Aigis-san...[n][uf 1 1][e]

[msg MSG_047_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 76 0 0]...Well, Senpai? Should we take her with us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 6 65535 0 0][uf 3 1 1 0 0 77 0 0]...'Cause if this is our only choice, I just wanna hurry up and get it over with.[n][uf 1 1][e]

[msg MSG_048_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 78 0 0]Okay, everyone, listen up.[n][uf 1 1][e]

[msg MSG_048_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 79 0 0]It seems that once again, we must engage in both exploration and battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 80 0 0]I've been thinking it over, and I believe Aigis should take command.[n][uf 1 1][e]

[msg MSG_049_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 81 0 0]If someone with the power to change Personas is in charge, we can proceed the same way as before.[n][uf 1 1][e]

[msg MSG_050_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 82 0 0]And if you, as the leader, approve of it... then I have no objections to Metis accompanying us.[n][uf 1 1][e]

[msg MSG_051_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 83 0 0]Mitsuru-san...[n][uf 1 1][e]

[msg MSG_052_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 0 0 0 84 0 0]......[n][uf 1 1][e]

[msg MSG_053_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 85 0 0]If you want to protect me, you must fight to protect us all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 201 65535 0 0][uf 3 1 1 0 0 86 0 0]Whatever happens, you can't hurt my friends. Can you promise me that?[n][uf 1 1][e]

[msg MSG_054_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 201 65535 0 0][uf 3 1 1 0 0 87 0 0]Yes! I promise![n][uf 1 1][e]

[msg MSG_055_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 10 6 65535 0 0][uf 3 1 1 0 0 88 0 0]This better not come back to bite us in the ass.[n][uf 1 1][e]

[msg MSG_056_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 89 0 0]Hey, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 6 65535 0 0][uf 3 1 1 0 0 90 0 0][uf 4 23 0 2 2 25 25]Since Mitsuru-senpai just mentioned it... What's up with you suddenly having his power?[n][uf 1 1][e]

[msg MSG_057_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 201 65535 0 0][uf 3 1 1 0 0 91 0 0]I... honestly don't know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 201 65535 0 0][uf 3 1 1 0 0 92 0 0]When I thought we might lose someone else, I got scared, and suddenly...[n][uf 1 1][e]

[msg MSG_058_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 6 65535 0 0][uf 3 1 1 0 0 93 0 0]Metis, was it? Do you know anything about this?[n][uf 1 1][e]

[msg MSG_059_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 201 65535 0 0][uf 3 1 1 0 0 94 0 0]I just met her. How would I know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 95 0 0]Anyway, if you already know someone with that same power, why not just ask them?[n][uf 1 1][e]

[msg MSG_060_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 0 0 0 96 0 0]......[n][uf 1 1][e]

[msg MSG_061_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 97 0 0]If we're going to end up fighting again, we'd better make sure we're outfitted properly.[n][uf 1 1][e]

[msg MSG_062_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 98 0 0]Well, as far as the school records are concerned, you and I are technically still Gekkoukan students.[n][uf 1 1][e]

[msg MSG_063_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 99 0 0]Yamagishi, could I ask you to retrieve the armbands from the command room?[n][uf 1 1][e]

[msg MSG_064_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 100 0 0]Of course.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 101 0 0]Oh, and as for the things we found when the floor opened up—I put them in the command room, so I'll look into them once I have a chance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 102 0 0]Maybe I can learn something.[n][uf 1 1][e]

[msg MSG_065_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 103 0 0]All right, let's get back upstairs.[n][uf 1 1][e]

[msg MSG_066_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 201 65535 0 0][uf 3 1 1 0 0 104 0 0]Um, Aigis?[n][uf 1 1][e]

[msg MSG_067_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 105 0 0]I-I promise to listen to what you say, so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 201 65535 0 0][uf 3 1 1 0 0 106 0 0]Could I... call you my sister?[n][uf 1 1][e]

[msg MSG_068_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 201 65535 0 0][uf 3 1 0 0 0 107 0 0]......[n][uf 1 1][e]

[msg MSG_069_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 1 201 65535 0 0][uf 3 1 1 0 0 108 0 0]...Go right ahead.[n][uf 1 1][e]

[msg MSG_069_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 17 11 1 1][e]

[msg MSG_070_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 201 65535 0 0][uf 3 1 1 0 0 109 0 0]Thank you... Sister![n][uf 1 1][e]

[msg MND_071_0_0]
[uf 0 5 65278][uf 2 1]The Abyss of Time...[n]A strange and mysterious dimension[n]that has suddenly appeared out of nowhere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Until we find the reason[n]for its presence, we'll be[n]unable to leave the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We must begin looking[n]into its depths at once...[n][uf 1 1][e]

