[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1001 0 0]So that "Abyss of Time" down there is what caused all this, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Guess we'll have to go in and try to figure this all out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Sounds like no one has a clue what's really in there, but that's all the more reason to check it out.[n][uf 1 1][e]

[msg MSG_079_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1102 0 0]A door that leads to the past...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0]Didn't your sister say there are multiple of them too?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Now that we can get to Kurosawa-san, I guess we're good to go for a long haul.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0]Ugh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0]How long is this all gonna take...?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1003 0 0]We've checked out barely any of the doors down there. We should pick up the pace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Let's try to just get this over with as fast as we can. Otherwise, we'll be here forever...[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1062 0 0]About Metis... Maybe I've just been misunderstanding her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]I mean, she doesn't seem like a bad person or anything... We just didn't exactly get off on the right foot with her, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]What do you think?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Agreed—she's not a bad person.[e]
[uf 0 5 65278][uf 2 1]I'm not sure yet...[e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1107 0 0]Yeah, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]I get the feeling she's just... overly protective.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]So as long as you keep an eye on her, I don't think she'll really be dangerous to us.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Hm... Well, make sure you keep a close eye on her, then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]If nothing else, it seems like she'll at least listen to you.[n][uf 1 1][e]

[msg MSG_017_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1077 0 0]I know there isn't really a reason to check the schedule since we're just exploring all the time now, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]I don't know... I guess I keep looking at it out of habit.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1028 0 0]I never knew his dad's an alcoholic... I think I kinda get how he feels.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]It's not like I just pity him or anything. It's... I don't know...[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1084 0 0]It feels so long ago now, but... I used to not really like Mitsuru-senpai very much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]It's like I thought I was the only one going through stuff. And I had all these assumptions and made her out to be the bad guy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]*sigh*[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1006 0 0]That strange figure somehow always appears just ahead of us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]How long is it gonna keep this up? I wish it'd just show itself already.[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1061 0 0]When someone says something that hits a nerve, it's probably because there's some truth in what they said.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]When she said how all we talk and laugh about is stuff from our past, I wanted to be like, "You don't know anything about our past!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]But maybe her not having the whole picture of our past is exactly why she's actually right. Even if we're not doing it intentionally...[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1076 0 0]If we want to solve this, we just gotta reach the end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]So we might as well get going instead of wasting our time trying to figure it all out ourselves first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]I wanna see what that figure really is too... Let's go end this whole thing already.[n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1065 0 0]I'm not trying to say I'm objectively right here or anything, but we don't have enough time to keep arguing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]I just...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]Toward the end of our fight with Nyx, I couldn't even move. All I could do was watch as he left us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]So I want to go back and leave no regrets this time. I mean, facing our regrets was the whole point of all this, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]And you need to come to a decision too. I won't accept that you just don't have any opinions about this.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1004 0 0]I think... I'm actually glad that I lost to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0]If I tried to do the past over again with the mindset I was in, I probably would've ended up having even more regrets...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0]It's... honestly embarrassing how little I've processed everything.[n][uf 1 1][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 52 65535 0 0][uf 3 1 3 0 65535 1076 0 0]Oh, I heard from Fuuka...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]You could've died if you lost your key?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0]Why didn't you say anything? I would've...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 52 65535 0 0][uf 3 1 3 0 65535 1056 0 0]Actually... I probably would've done everything the same anyways. I was only thinking about myself. I'm so sorry...[n][uf 1 1][e]

[msg MSG_053_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1009 0 0]What's up? Need something?[n][uf 1 1][e]

[msg MND_054_0_0]
[uf 0 5 65278][uf 2 1]Should I spend some[n]time with Yukari-san...?[n][uf 1 1][e]

[sel SEL_055_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_056_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1075 0 0]Oh. Okay, then. Uh... Wanna chat for a bit?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1020 0 0]All right. See ya.[n][uf 1 1][e]

[msg MSG_065_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1001 0 0]I've been reading this [uf 4 4 0 37 1 16775] and it's really getting good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]Maybe we can read together. Are there any books you've been meaning to check out?[n][uf 1 1][e]

