[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I can't understand what Koromaru-san[n]is trying to say as well as I did before...[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]It seems as though he wishes to head[n]inside the Abyss and explore... I think.[n][uf 1 1][e]

[msg MSG_071_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8005 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_072_0_0]
[uf 0 5 65278][uf 2 1]I can't understand what he is trying[n]to convey as well as I did before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Koromaru-san is looking[n]curiously beyond the path...[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I can't understand what he is trying[n]to convey as well as I did before...[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems motivated...[n]I think.[n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems to be[n]encouraging me... I think.[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf?[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems calm...[n]I think.[n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8005 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems to be[n]quietly watching over everyone...[n][uf 1 1][e]

[msg MSG_026_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san seems excited...[n]I think.[n][uf 1 1][e]

[msg MSG_028_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san keeps looking in my[n]direction as if he's worried for me...[n][uf 1 1][e]

[msg MSG_030_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san is looking[n]over at Junpei-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems that he's chosen[n]a partner to side with...[n][uf 1 1][e]

[msg MSG_032_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]It seems as if Koromaru-san[n]is ready for the final fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I get the impression that[n]I'm beginning to understand him[n]a little better than before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]DEV: blank[n][e]

[msg MSG_049_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_050_0_0]
[uf 0 5 65278][uf 2 1]Koromaru-san is staring at me[n]as though he wants something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I give him[n]the [uf 4 4 0 37 1 16786]?[n][uf 1 1][e]

[sel SEL_053_0_0 top]
[uf 0 5 65278][uf 2 1]I think I should.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_054_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MSG_055_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 4 25 9]......[n][uf 1 1][e]

[msg MSG_063_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_064_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1]Koromaru-san is staring at me[n]as if he wants something... I think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend time[n]with Koromaru-san...?[n][uf 1 1][e]

[msg MSG_065_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0][uf 3 1 3 0 65535 8007 0 0]Arf![n][uf 1 1][e]

[msg MND_067_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1]It seems as if Koromaru-san[n]wants to go somewhere...[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 4 25 9]......[n][uf 1 1][e]

