[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2142 0 0]Kinda worried about what could happen in there, but Koromaru and I will go check things out![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Leave finding supplies to us! You just concentrate on exploring, Ai-chan.[n][uf 1 1][e]

[msg MSG_077_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2115 0 0]Huh... Didn't expect to end up here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Guess that solves the starve-to-death problem we had, though![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Koromaru and I are finally back to exploring with you guys![n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Who woulda thought we'd be back at it again with this endless exploration? I'll just do what I do best![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]No slacking off for me. Don't want to cause trouble for our leader Ai-chan![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2061 0 0]Say, Ai-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]Has Yuka-tan been kinda... gloomy lately? Or is it just me?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, she has.[e]
[uf 0 5 65278][uf 2 1]It must be your imagination.[e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]But what can we do? I guess we should keep an eye on her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]It's so hard to understand what a girl's thinking, especially Yuka-tan.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 3 0 65535 2099 0 0]Oh. Uh, really? Was my read on her that bad...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]I mean, she looks all normal and stuff, but I can't shake the feeling there's something a little off...[n][uf 1 1][e]

[msg MSG_045_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2074 0 0]Back then, when I stood here, I used to question whether or not I actually wanted to go exploring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]Exploring for days in a row is no joke. If you asked me back then, I'd scream and run away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Wait... If the same day is repeating, does this even count as going multiple days in a row?[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2061 0 0]So... that was Sanada-san before high school, and I'm a year younger than him... Wait, he was a third-year in middle school then!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]It had been barely half a year since I transferred! And he was fightin' Shadows already?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0]Damn, that's badass. Don't you think, Koromaru? The will to fight was coursing through his veins back then, too![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2088 0 0]In any case, we, the Daring Duo, are ready to join the exploration whenever you need us![n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2092 0 0]My dad's gotten better since then, but he's still... Well, he ain't exactly the most upstanding citizen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Aaagh, that's enough of that! And don't feel like you have to make me feel better or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0]Besides, I think what's going on right now is way more important! So to get us out of this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2119 0 0]Your best option is to bring me, the Great Junpei Iori! I'll get us out of this![n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 3 0 65535 2061 0 0]So, with those freaky doors that show the past, we've seen Amada, Sanada-san, me and Koromaru, and Kirijo-senpai.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]And if we're the reason this thing exists, then I wonder if there's a door for each of us. That means there's, uh, how many left...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]No use thinking about it now. Let's just get in there and open those doors.[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2093 0 0]I don't think Metis has some evil plan or anything. But she can be a little difficult to talk to at times...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]No offense to you, Ai-chan, but what's up with an anti-Shadow weapon that gets all cranky like that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]*sigh*[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 3 0 65535 2084 0 0]I dunno if I can explain this well, but I don't think anybody's right here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]I mean, even you don't know what to do here. Right, Aigis?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2056 0 0]That also doesn't sit well with me. That's why... I can't take your side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]She said to think about how we feel... So I'm going to do just that.[n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2097 0 0]Now that I've had time to calm down and think... I've realized that li'l sis is just as cute as you, Ai-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0]Never really noticed it before. Man, I must have been out of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]That butterfly thing on her face is actually... kinda mysterious and irresistible, y'know?[n][uf 1 1][e]

[msg MSG_032_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 3 0 65535 2116 0 0]Really glad things didn't end with li'l sis in tears.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0]I know it's a bit late coming from me now, but if you died there, Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0]Or even worse, if I was the one to take the key from you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 8 52 65535 0 0][uf 3 1 3 0 65535 2031 0 0]That would have been the worst friggin' thing to live with! Let's never do something like that again![n][uf 1 1][e]

[msg MSG_049_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2013 0 0]Oh, Ai-chan. You free at all? Wanna do something fun?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Check out this [uf 4 4 0 37 1 16776]! Let's see if we can learn a thing or two from what we found in the Abyss of Time![n][uf 1 1][e]

[msg MND_050_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time with Junpei-san?[n][uf 1 1][e]

[sel SEL_049_5_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_054_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0][uf 3 1 3 0 65535 2088 0 0]That's the spirit![n][uf 1 1][e]

[msg MSG_055_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2029 0 0]Alright then. Well, if you have some time, feel free to drop by.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2002 0 0]Oh, Ai-chan. You free at all? Wanna do something fun?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0]I'm actually not so sure I can do this on my own... You think you could help me out?[n][uf 1 1][e]

[msg MSG_061_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2040 0 0]Thanks! You're a lifesaver![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]We found this [uf 4 4 0 37 1 16777] in the Abyss of Time, right? So I wanted to try cooking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0]Never cooked in my life, but I think it'll be fine! Let's head to the kitchen pronto![n][uf 1 1][e]

