[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4025 0 0]It doesn't seem as though this problem will simply resolve itself. We may have to fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Don't worry. Whatever the cause may be, we'll overcome it. We've already saved the world once, after all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]That said... I'll be investigating on my own for some time. I'll leave the rest to you, Aigis.[n][uf 1 1][e]

[msg MSG_094_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Looks like we won't have to worry about supplies now. I didn't expect us to find a solution like this, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]The Abyss of Time, huh...[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4060 0 0]They reflect the minds of those who pass through...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Then if there are other doors that lead to the past, will we witness more of our personal memories?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]What does it all mean...? And why would we be the cause of all this?[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4009 0 0]I apologize I was gone for so long. I'll be joining the expedition from here on out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]You've been doing well as the leader, though. I'll try my best to make up for my absence.[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4082 0 0]I never thought about how much of my time as a student was dedicated to finding a way to eradicate the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]"She'll spend her prime years bound to our vile legacy"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4052 0 0]Oh, sorry. Ignore that. It's just something I heard once, when I was younger.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4060 0 0]Amada's, then Akihiko's, and now Iori's past...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]And each event took place before they started fighting Shadows... Is that how they're all related?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Is it linked to the "reason" that will help us get rid of the Abyss of Time...?[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4112 0 0]We still don't know what that figure's motive could be... I can't deny it's been weighing on my mind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]But our current objective is to explore the Abyss of Time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]We should keep moving.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 3 0 65535 4083 0 0]I vowed to protect my father... But I couldn't even manage that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0]Every time I want to protect someone... I lose them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]...But no longer, not anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4143 0 0]Aigis, would you lend me your strength?[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4073 0 0]Yukari seems to believe you inherited your new Persona abilities from him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]What do you think, Aigis? Is it possible?[n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]I have no idea...[e]
[uf 0 5 65278][uf 2 1]Inherited...? But how?[e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4113 0 0]I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]Well... All I wanted to say is that Yukari's words may have had an edge to them, but she doesn't mean you any malice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]She lost her temper since he meant so much to her... But I suppose he meant just as much to you as well.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 3 0 65535 4055 0 0]Apologies, I didn't intend to distress you. I'm sure Yukari didn't mean any ill will toward you, either, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]You are the only one who heard his final words... She must be taking it especially hard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]Sorry, I know this couldn't have been easy on you, either, but I only wanted you to understand where she's coming from.[n][uf 1 1][e]

[msg MSG_031_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4052 0 0]Sorry if I troubled you. I'll talk to Yukari when I get the chance.[n][uf 1 1][e]

[msg MSG_032_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4082 0 0]Just as I said earlier... I will be joining Yukari in this fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I'm sorry it turned out this way. I know it's irresponsible of me to choose sides after appointing you as our leader...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0]But I won't budge on this... That's why there's no need for you to hold back. Come at us with everything you have.[n][uf 1 1][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4038 0 0]Thank you for stepping up as the leader... You've done well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0]We may have fractured at one point, but you're the reason why we're all together again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]You have my gratitude. I apologize for giving you such a heavy burden.[n][uf 1 1][e]

[msg MSG_043_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Also...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0]There's something I need to discuss with you, Aigis—about your life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 52 65535 0 0]You are one of the people I want to protect. That's why, next time... You can come to me for anything.[n][uf 1 1][e]

[msg MSG_053_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4009 0 0]Oh, hello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I was thinking about taking a short break. Would you like to join me?[n][uf 1 1][e]

[msg MND_054_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time with Mitsuru-san...?[n][uf 1 1][e]

[sel SEL_056_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not right now, no.[e]

[msg MSG_055_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4038 0 0]Thank you. I thought it would've been rather dull if it were just me alone.[n][uf 1 1][e]

[msg MSG_060_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4113 0 0]I see. Well, let me know if you ever need the company.[n][uf 1 1][e]

[msg MSG_067_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4009 0 0]Oh, Aigis. Koromaru wanted me to play with him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Since we came across that [uf 4 4 0 37 1 16781] in the Abyss, I thought I'd indulge him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Would you care to join us?[n][uf 1 1][e]

[msg MSG_069_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Then shall we get going? Koromaru ought to be waiting.[n][uf 1 1][e]

[msg MSG_068_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4113 0 0]I see. Perhaps another time, then.[n][uf 1 1][e]

[msg MSG_071_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4013 0 0]Yes? What is it? Did you want to play with Koromaru?[n][uf 1 1][e]

