[msg MSG_000_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20202 0 0][uf 5 21 1 101]Welcome to Rafflesia, Paulownia Mall branch.[n][uf 1 1][e]

[msg MSG_001_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20201 0 0][uf 5 21 1 101]What can I help you with today?[n][uf 1 1][e]

[msg MSG_002_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Can I help you with anything else?[n][uf 1 1][e]

[sel SEL_000_0_0 top]
[uf 0 5 65278][uf 2 1]Shop[e]
[uf 0 5 65278][uf 2 1]Hand over seeds[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Shop[e]
[uf 0 5 65278][uf 2 1]Check on seeds[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MSG_003_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20205 0 0][uf 5 21 1 101]Thank you for stopping by. Please come again.[n][uf 1 1][e]

[msg MSG_004_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]It's our grand opening! We look forward to doing business with you![n][uf 1 1][e]

[msg MSG_005_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Oh! Did you bring a flyer? Wonderful. Here's a gift for you.[n][uf 1 1][e]

[msg MSG_006_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]We also offer a service for growing vegetables on your behalf. Let us know if you're interested![n][uf 1 1][e]

[msg MSG_021_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Since you've been such a loyal customer, we've gone ahead and upgraded our seed-growing service for you![n][uf 1 1][e]

[msg SYS_022_0_0]
[uf 0 5 65278][uf 2 1]The shop can now grow an additional plot of seeds.[n][uf 1 1][e]

[msg MSG_022_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20204 0 0][uf 5 21 1 101]We'll take good care of them. Please stop by again another day.[n][uf 1 1][e]

[msg MSG_023_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]Your seeds from the other day have grown splendidly! Here you are.[n][uf 1 1][e]

[msg MSG_024_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]It looks like they still need more time.[n][uf 1 1][e]

[msg MSG_025_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]It looks like they'll be ready soon.[n][uf 1 1][e]

[msg MSG_027_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]It doesn't look like you're carrying any seeds.[n][uf 1 1][e]

[msg MSG_028_0_0 [Flower Shop Lady]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 101]We have a nice selection of seeds here, so do consider buying some from us![n][uf 1 1][e]

