[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I enjoyed a cup of Pheromone Coffee.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It feels like people are looking at me...[n]Is this the effect of pheromones...?[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]It had an enchanting aroma.[n]I feel a little more mature now...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]My reflection in the window looks[n]more attractive than before...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Strangely, I feel like my [uf 4 30 1 1 1 0][n]has increased after drinking the coffee...[n][uf 1 1][e]

