[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Kyoto, huh? That's so cliché...[n][uf 1 1][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1]Huh? You're not a fan?[n][uf 1 1][e]

[msg MSG_001_5_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1]I'd say it's a beautiful city to make some[n]good memories in while we're still young.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Man, is that really the first thing you think?[n][uf 1 1][e]

[msg MSG_002_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]It makes you sound like an old geezer[n]when you say that kinda stuff.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1]It does?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Thank goodness... She actually made it.[n][uf 1 1][e]

