[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]My grandfather was obsessed with the Shadows...[n][uf 1 1][e]

[msg MSG_000_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]He wanted to harness their power[n]to create something extraordinary.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Create something extraordinary...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]To that end, he assembled a research team[n]and had them amass a number of Shadows.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]He was collectin' 'em!?[n]Damn, that's freakin' crazy![n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]But ten years ago, during the final stages of the project,[n]there was an accident... and the experiment failed.[n][uf 1 1][e]

[msg MSG_004_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]They lost control of the Shadows' power,[n]altering the nature of the entire world.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]You can't mean...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]Yes... Tartarus and the Dark Hour.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Huh!?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Huh!?[n][uf 1 1][e]

