[msg MSG_000_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I can only hope that this recording[n]reaches someone with a conscience...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Isn't this... that video...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]My employer has become[n]obsessed with a loathsome idea.[n][uf 1 1][e]

[msg MSG_002_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]This experiment should never[n]have been conceived...[n][uf 1 1][e]

[msg MSG_003_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]That's why I had to do[n]something to put a stop to it.[n][uf 1 1][e]

[msg MSG_003_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]However, in doing so, I released a number of Shadows[n]that are certain to torment future generations.[n][uf 1 1][e]

[msg MSG_003_7_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]But... I didn't have a choice... If I didn't do this...[n]it could have destroyed the entire world![n][uf 1 1][e]

[msg MSG_004_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]Please, you need to listen very carefully...[n][uf 1 1][e]

[msg MSG_004_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]Whatever you do, it is imperative that you[n]do not hunt the Shadows that have dispersed.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Huh? This part's...[n][uf 1 1][e]

[msg MSG_006_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I wasn't able to do anything to stop this madness...[n][uf 1 1][e]

[msg MSG_006_3_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]He won't listen to a word I say... He's been[n]seduced by the devil's temptations...[n][uf 1 1][e]

[msg MSG_006_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]Those monsters will try to reunite and become one[n]again... If they succeed, then we're all doomed![n][uf 1 1][e]

[msg MSG_006_7_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I'll say it once more... Do not go after[n]the Shadows that were released![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]This is... the original video. The real one...[n]before Ikutsuki went and tampered with it...[n][uf 1 1][e]

[msg MSG_007_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Dad was trying to put a stop to the experiment.[n][uf 1 1][e]

[msg MSG_008_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]There's not much hope for me now.[n][uf 1 1][e]

[msg MSG_008_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I have just one request...[n][uf 1 1][e]

[msg MSG_008_7_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]Whoever finds this... please...[n]give my daughter Yukari this message...[n][uf 1 1][e]

[msg MSG_009_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I know I promised I'd be home soon...[n]and I'm sorry to break that promise...[n][uf 1 1][e]

[msg MSG_009_5_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]But I want you to know... as your father, I was[n]never happier in my life than when I was with you.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]This really is... my dad...[n][uf 1 1][e]

[msg MSG_011_0_0 [Eiichiro Takeba]]
[uf 0 5 65278][uf 2 1]I love you, Yukari. Please...[n]Take care of yourself.[n][uf 1 1][e]

