[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]What is that!?[n][uf 1 1][e]

[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]It's the moon...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]It kind of looks like... Ryoji-kun's getting pulled into it...[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]No, wait... It's the moon that's[n]being pulled down to us![n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]You're kidding me. Are you saying[n]that... Nyx is the moon itself!?[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]It's coming...[n][uf 1 1][e]

[msg MSG_004_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Soon, it will descend upon us...[n]Crashing into the Earth.[n][uf 1 1][e]

[msg MSG_005_0_0 [（ＳＥ）市民・若い女性１]]
[uf 0 5 65278][uf 2 1]Huh...? What the...?[n][uf 1 1][e]

[msg MSG_006_0_0 [市民・若い男性１]]
[uf 0 5 65278][uf 2 1]Where am I...?[n][uf 1 1][e]

[msg MSG_007_0_0 [市民・中年男性]]
[uf 0 5 65278][uf 2 1]What the hell...? What's going on!?[n][uf 1 1][e]

[msg MSG_008_0_0 [（ＳＥ）市民・若い女性２]]
[uf 0 5 65278][uf 2 1]Oh god![n][uf 1 1][e]

[msg MSG_009_0_0 [（ＳＥ）市民・若い男性２]]
[uf 0 5 65278][uf 2 1]Oh gosh...[n][uf 1 1][e]

[msg MSG_010_0_0 [（ＳＥ）市民・若い女性３]]
[uf 0 5 65278][uf 2 1]What is that?[n][uf 1 1][e]

[msg MSG_011_0_0 [（ＳＥ）市民・若い男性２]]
[uf 0 5 65278][uf 2 1]Oh no...[n][uf 1 1][e]

[msg MSG_011_5_0 [市民・若い男性２]]
[uf 0 5 65278][uf 2 1]I don't know what this is![n][uf 1 1][e]

[msg MSG_012_0_0 [（ＳＥ）群集・男１]]
[uf 0 5 65278][uf 2 1]I'm not supposed to be here...![n][uf 1 1][e]

[msg MSG_013_0_0 [（ＳＥ）群集・男２]]
[uf 0 5 65278][uf 2 1]I can't get a signal![n][uf 1 1][e]

[msg MSG_014_0_0 [群集・男３]]
[uf 0 5 65278][uf 2 1]What the...? My phone isn't[n]working. What's going on?[n][uf 1 1][e]

[msg MSG_015_0_0 [群集・女１]]
[uf 0 5 65278][uf 2 1]Oh my god...[n][uf 1 1][e]

[msg MSG_016_0_0 [（ＳＥ）群集・女２]]
[uf 0 5 65278][uf 2 1]Oh no...[n][uf 1 1][e]

[msg MSG_017_0_0 [（ＳＥ）群集・女３]]
[uf 0 5 65278][uf 2 1]Why is there... red stuff on[n]the ground? What is that!?[n][uf 1 1][e]

[msg MSG_018_0_0 [Believer]]
[uf 0 5 65278][uf 2 1]Holy crap... Look at the moon...[n][uf 1 1][e]

[msg MSG_018_3_0 [Believer]]
[uf 0 5 65278][uf 2 1]Hahaha, holy shit, this is amazing![n]It's really happening... The apocalypse![n][uf 1 1][e]

[msg MSG_018_5_0 [Believer]]
[uf 0 5 65278][uf 2 1]The world is finally ending![n][uf 1 1][e]

[msg MSG_018_7_0 [Believer]]
[uf 0 5 65278][uf 2 1]Hehehe... Ahahahaha![n][uf 1 1][e]

[msg MSG_018_9_0 [（ＳＥ）終末思想の男性]]
[uf 0 5 65278][uf 2 1]...Urgk![n][uf 1 1][e]

[msg MSG_019_0_0 [（ＳＥ）若い女性]]
[uf 0 5 65278][uf 2 1]Aaaaah![n][uf 1 1][e]

[msg MSG_020_0_0 [（ＳＥ）茶髪の男性]]
[uf 0 5 65278][uf 2 1]Go, go, go, go, go![n][uf 1 1][e]

[msg MSG_021_0_0 [（ＳＥ）恐怖におののく男性]]
[uf 0 5 65278][uf 2 1]Oh my god![n][uf 1 1][e]

[msg MSG_022_0_0 [（ＳＥ）うずくまる男性]]
[uf 0 5 65278][uf 2 1]I don't want to die...[n][uf 1 1][e]

