[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 1 0 0]Is this... the deepest part of the Abyss of Time...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 2 0 0]You think so? Looks the same as everywhere else to me...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]It would make sense, considering the path we've taken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]And that means the source of the Abyss, and therefore the time loop, should be here.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, I almost forgot! Speaking of the Abyss...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 3 25 25]I found something in those notes about it that I mentioned earlier.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]You did?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]They said that this place came to be as a reaction to the creation of Tartarus.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]A "reaction"...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 10 0 0]Yes, because a giant tower appeared out of nowhere, it ended up leaving a massive hollow in its place—that's the Abyss.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]So they've known about this place for ten years?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 12 0 0]They thought that it would be harmless if left alone, and that it would probably disappear when Tartarus did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 1 0 0 13 0 0]But the notes also said that since the Abyss is just a byproduct of Tartarus, there shouldn't be any Shadows in it...[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 7 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Seriously!? Uh, counterpoint: there's a shitload of Shadows here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 15 0 0]And if it was supposed to go poof along with Tartarus, then why're we standin' in it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 16 0 0]They forget a decimal place or somethin'?[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]No, their logic makes sense.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]But some kind of force prevented it from vanishing, so the other side's disappearance caused an imbalance...[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]What could that force be?[n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Who knows? Maybe it's down here somewhere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]But one thing's for certain: it's deeply connected to all of you...[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 52 65535 0 0][uf 3 1 1 0 0 22 0 0]The hell's up with that!? What'd we do to deserve this!?[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Well, there's another door...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 24 0 0]If it is down here, then maybe...[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 1 0 0 25 0 0]So whatever's past that could be what's causing all this?[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]If we leave out Aigis, Metis, and me... Whose past is left?[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Yeah... Gotta be someone else with a "reason" for their power, right?[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Well, there's no point wasting time thinking about it. It's literally right there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Let's just open it, then we'll know.[n][uf 1 1][e]

[msg MSG_020_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Whatever the cause is, it's strong enough to keep the Abyss of Time from disappearing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 31 0 0]And we'll be trying to destroy it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 1 0 0 32 0 0]We could be in for a battle. We should make sure we're prepared for that.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 33 0 0]She's right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 34 0 0]This is where we aim to settle everything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 35 0 0]And I know we can do this.[n][uf 1 1][e]

