[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 1 0 0]That was Senpai's...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Hm...? Oh, yes... Well...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Senpai...? What's the matter?[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 4 0 0]I'm sorry, it's... It's just that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Seeing my father, as if he were still alive, was...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Senpai...[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Awww... Wasn't Kirijo-senpai just so gosh darn cute when she was younger?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Excuse me, Iori? Are you saying that's no longer the case?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Er, no, that's not what I— I-I mean, you're just so... y'know! C'mon, cut a guy some slack here![n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]...It's just as I thought.[n][uf 1 1][e]

[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Of the past events we've seen up to this point...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]The first one seemed to be about getting ready for battle, but the others... How should I put it...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 13 0 0]There seems to be some aspect they all have in common.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Don't you all get that feeling, too? At least... a little bit?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Just a little bit, yes...[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]We've reached the fifth door now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]We should be getting closer to the source...[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Oh... I just remembered! There's something I have to tell you all![n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Remember the equipment and documents Kirijo-senpai found?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]I looked into them, and it turns out they were things that the chairman hid when he was still alive...[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Most of them were from the accident about ten years ago. He must have hidden them to keep them from being destroyed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 22 0 0]...And some of the notes seem to mention the Abyss of Time.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 23 0 0]They do!?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 24 0 0]It won't be long before we discover what this place really is.[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Feels like we're closing in on the truth...[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 0 54 65535 0 0][uf 3 1 1 0 0 26 0 0]Then we should press on.[n][uf 1 1][e]

