[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]No way...[n][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]That's it. One of the monsters that attacked us...[n][e]

[msg MSG_001_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]It's a Shadow![n][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]It's here![n][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Wait.[n][e]

[msg MSG_002_0_0 [Mysterious Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]...Go on.[n][e]

[msg MSG_005_0_0 [Mysterious Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Per...[n][e]

[msg MSG_005_5_0 [Mysterious Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]so...[n][uf 1 1][e]

[msg MSG_005_7_0 [Mysterious Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]na...[n][uf 1 1][e]

[msg MSG_005_9_0 [Mysterious Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 0 0 0]Na...[n][uf 1 1][e]

[msg MSG_006_0_0 [Orpheus]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]I am thou... Thou art I...[n][e]

[msg MSG_006_5_0 [Orpheus]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]From the sea of thy soul, I cometh.[n][e]

[msg MSG_006_7_0 [Orpheus]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]I am Orpheus, master of strings...[n][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Just as we thought...[n][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Ngh... Aaaaaaaaaah![n][e]

