[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Juno!? Um, d-did something happen!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Yukari? What's the matter?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, I realized it's a full moon tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 4 0 0]You did too, huh? Oh god, I'm turning into a workaholic![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 0 0 0 5 0 0]......[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Wait, is something actually going on?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]We're not certain of anything yet, but... we can't find Aigis.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]What? Where could she have gone?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 9 0 0]At one point, I was able to sense a Persona, but I lost Aigis right after that.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 10 0 0]You sensed a Persona? Could it have been Strega?[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Well, she hasn't detected any of them, but we can't be positive.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 12 0 0]I've pinpointed her location![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 13 0 0]The Moonlight Bridge![n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 14 0 0]All right, call the others. Let's see what's going on over there.[n][uf 1 1][e]

