[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4102 0 0]I can't see as well here... It's difficult for me to follow your readings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]However, the enemy can't detect you either. I'll keep sending you information, so stay alert.[n][uf 1 1][e]

[msg MSG_000_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5120 0 0]The visibility here is rather poor. I can manage to see you all, but barely...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]At least the enemy won't be able to see you. Please stay calm, and you'll pull through![n][uf 1 1][e]

