[msg MSG_000_0_0 [Young Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 2]Well, Sergeant?[n][uf 1 1][e]

[msg MSG_001_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Eh, you can go. Just another one of 'em freak accidents.[n][uf 1 1][e]

[msg MSG_002_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Hey, kid. Sorry I took so long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Says here your name's... Ken Amada. Is that right?[n][uf 1 1][e]

[msg MSG_003_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]Er... Geez... Sorry about what happened to your mom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]Heard she gave her life to protect you from the wreckage.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 0 0 0 7 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1]Anyway, I gotta take your statement—since you're a witness and all.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 6 65535 0 0][uf 3 1 1 0 0 9 0 0]If I told you what happened... would you believe me?[n][uf 1 1][e]

[msg MSG_007_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1]Of course I would! Helping people out is our job.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 1 0 0 11 0 0]My mom was... murdered.[n][uf 1 1][e]

[msg MSG_009_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1]...What?[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Around midnight, when I got up to use the bathroom... I heard voices by the door...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 1 0 0 14 0 0]I looked and saw this teenager, holding his head and yelling...[n][uf 1 1][e]

[msg MSG_011_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1]Hold on, you're saying he did it? But the whole house collapsed![n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 6 65535 0 0][uf 3 1 1 0 0 16 0 0]There was this shining, horse-like monster that came right out of him![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 4 3 25 25]It roared, and just like that, my mom and my house were—[n][uf 1 1][e]

[msg MSG_013_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1]Ohhh, a monster, was it? Haha... C'mon now, there's no way that actually happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]Oh, um, sorry, I shouldn't laugh... It's just, sometimes after a traumatic incident like this, people can—[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 6 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 4 2 25 25]I'm not lying! I really did see it, I did![n][uf 1 1][e]

[msg MSG_015_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 1]Look, kid... It was all an accident, plain and simple. A drunk driver crashed his car into your house.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 6 65535 0 0][uf 3 1 1 0 0 22 0 0]What...? A car crash...?[n][uf 1 1][e]

[msg MSG_017_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 1]We've already found the car and what's left of the driver. Now all we need is an account of the accident.[n][uf 1 1][e]

[msg MSG_017_5_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 4 17 8 2 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 6 65535 0 0][uf 3 1 1 0 0 24 0 0]That's a lie! You're just making that up![n][uf 1 1][e]

[msg MSG_019_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 1]I know you might think so, but... It's true.[n][uf 1 1][e]

[msg MSG_020_0_0 [Officer Outside]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]Sergeant, can you come out here?[n][uf 1 1][e]

[msg MSG_021_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 1]Yeah, be right there![n][uf 1 1][e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Wait! I really did see it![n][uf 1 1][e]

[msg MSG_023_0_0 [Veteran Officer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 1]Listen, I'm sorry for your loss, but... I have to go, uh... I hope things get better.[n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 1 0 0 30 0 0]Liar... You said you'd believe me![n][uf 1 1][e]

[msg MSG_024_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 6 65535 0 0][uf 3 1 0 0 0 31 0 0]......[n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 6 65535 0 0][uf 3 1 1 0 0 32 0 0]Adults can't be trusted.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 6 65535 0 0][uf 3 1 1 0 0 33 0 0]So I'll find him myself...[n][uf 1 1][e]

