[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If you get attacked by the enemy, the battle will begin at a disadvantage to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Try and make certain that you strike the enemy first to guarantee the initiative in battles.[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]If you are able to strike the enemy before you are spotted, then you will gain the initiative.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]On the other hand, if the enemy hits you first, the opposite will occur.[n][uf 1 1][e]

