[msg MSG_000_0_0 [Angry Old Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 690]The hell you kids doin' out here this late?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 690]You delinquents keep loitering in the wrong places, gettin' up to god knows what.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 690]Whichever one of your gang wears the heavy clothes to cover his tattoos, tell him I got my eye on him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 690]Now, scram! I'll call the cops.[n][uf 1 1][e]

[msg MSG_001_0_0 [Angry Old Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 690]Now, scram! I'll call the cops.[n][uf 1 1][e]

