[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 4 0 25 25]I recently expanded my outdoor exercise regimen, and I wanted to boost my nutrition to match.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]So I got some pork liver today because it's supposed to be rich in iron.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]But I don't think it'll taste like much if I just boil it like usual...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]That's why I'm gonna try cooking a pork liver stir-fry. I already looked up how to make it. Think you can help out?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]You bet.[e]
[uf 0 5 65278][uf 2 1]That sounds hard.[e]
[uf 0 5 65278][uf 2 1]Do it yourself.[e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 4 1 25 25]Good to hear. You like this dish, too?[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 4 1 25 25]I thought so too, but the recipe is actually pretty simple.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 4 0 25 25]...The only thing I can't handle is flipping the food in the pan. So I'm hoping you can manage that part.[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0]Hey, don't be like that. I don't think I can flip the food in the pan myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]Come on, call it a favor. This is supposed to be a really healthy dish.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 4 0 25 25]I've already cleaned the meat ahead of time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0]All that's left is to cook the liver, then stir the chives and bean sprouts in, and that should be it.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 4 1 25 25]Wow, this is great![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]I guess it was a good thing I took the time for all that prep.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 14 0 0]They say a boxing match is decided before the bell even rings. Maybe this is kind of the same thing.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0]Oh, sorry. Obviously this wouldn't have been possible without your help.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 4 0 25 25]I've still got a lot to learn, but it's hard to make time for it with all my training and stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 17 0 0]...Maybe if I attach weights to the pan when I'm flipping, I could kill two birds with one stone?[n][uf 1 1][e]

