[msg MSG_000_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]It's me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Sorry for interrupting, but do you have a moment to talk?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Be right there.[e]
[uf 0 5 65278][uf 2 1]Just a minute.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 3 0 0]Good morning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 4 0 0]The chairman is visiting again tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 5 0 0]When the time comes, let's all meet up in the command room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 6 0 0]I'll see you then.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]That's fine, I'll just talk through the door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]The chairman is visiting again tonight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]When the time comes, let's all meet up in the command room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]I'll see you then.[n][uf 1 1][e]

