[msg SYS_000_0_0]
[uf 0 5 65278][uf 2 1]A portion of your existing save data can be carried over when starting.[n][uf 1 1][e]

[msg SYS_001_0_0]
[uf 0 5 65278][uf 2 1]By carrying over save data, you'll be able to use any costumes you've previously obtained, as well as your Persona Compendium.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Note that your Persona Compendium data won't be able to be used on the highest difficulty, [uf 0 1 2]Heartless[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Furthermore, you will not be able to carry over save data later or redo the carryover using a different save.[n][uf 1 1][e]

[msg SYS_002_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Carry over save data?[n][uf 1 1][e]

[msg SYS_003_0_0]
[uf 0 5 65278][uf 2 1]Costumes have been carried over.[n][uf 1 1][e]

[msg SYS_004_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Carry over save data?[n][uf 1 1][e]

[msg SYS_005_0_0]
[uf 0 5 65278][uf 2 1]Starting new game with save data carried over.[n][uf 1 1][e]

[msg SYS_006_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Your save data will not be carried over.[n][uf 1 5 0]Proceed?[n][uf 1 1][e]

[msg SYS_007_0_0]
[uf 0 5 65278][uf 2 1]Episode Aigis -The Answer- takes place after the events of Persona 3 Reload.[n][uf 1 5 0]It is recommended to reach its conclusion before continuing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Begin Episode Aigis -The Answer-?[n][uf 1 1][e]

[msg SYS_008_0_0]
[uf 0 5 65278][uf 2 1]Episode Aigis -The Answer- takes place after the events of Persona 3 Reload.[n][uf 1 5 0]It is recommended to reach its conclusion before continuing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Begin Episode Aigis -The Answer-?[n][uf 1 1][e]

[msg SYS_009_0_0]
[uf 0 5 65278][uf 2 1]There were no costumes to carry over.[n][uf 1 1][e]

[msg SYS_010_0_0]
[uf 0 5 65278][uf 2 1]Save data cannot be carried over from the network slot. If you wish to carry over this data, please save it to a regular slot.[n][uf 1 1][e]

[msg SYS_010_5_0]
[uf 0 5 65278][uf 2 1]Save data cannot be carried over from the network slot. If you wish to carry over this data, please save it to a regular slot.[n][uf 1 1][e]

