[msg TRL_000_0_0 [Major Arcana Cards]]
[uf 0 5 65278][uf 2 1][uf 4 8 13]Besides the Minor Arcana cards that occasionally appear during Shuffle Time, [uf 0 1 2]Major Arcana cards[uf 0 1 27] may also rarely appear.[n][uf 1 1][e]

[msg MSG_001_0_0 [Major Arcana Cards]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Only one of each Major Arcana card may be acquired per expedition[uf 0 1 27]. The number of Major Arcana cards you can acquire in the same trip to the Abyss of Time is also limited.[n][uf 1 1][e]

[msg MSG_002_0_0 [Major Arcana Cards]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you've acquired the maximum number of Major Arcana cards, an [uf 0 1 2]Arcana Burst[uf 0 1 27] will occur and increase the ranks of your Minor Arcana cards. Collect as many Major Arcana cards as you can.[n][uf 1 1][e]

