[msg TRL_000_0_0 [Fleeing from Battle]]
[uf 0 5 65278][uf 2 1][uf 4 8 24]While in battle, press [uf 1 3 104] to open the Tactics menu and select [uf 0 1 2]Escape[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Fleeing from Battle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The battle will end if an escape route can be found after three turns. However, keep in mind that an escape route may not be found.[n][uf 1 1][e]

[msg TRL_002_0_0 [Fleeing from Battle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]While in the process of looking for an escape route, commands can still be given to other party members.[n][uf 1 1][e]

