[msg TRL_000_0_0 [Arcana Burst]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you've acquired the maximum number of Major Arcana cards possible per expedition, an [uf 0 1 2]Arcana Burst[uf 0 1 27] will occur and you can acquire a Minor Arcana card of your choice.[n][uf 1 1][e]

[msg TRL_001_0_0 [Arcana Burst]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]During Arcana Burst, [uf 0 1 2]the ranks of the Minor Arcana cards that appear will increase[uf 0 1 27] until you leave the Abyss of Time.[n][uf 1 1][e]

[msg TRL_002_0_0 [Arcana Burst]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Try activating Arcana Burst as often as possible to collect stronger Minor Arcana cards.[n][uf 1 1][e]

