[msg TRL_000_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you have been afflicted with an [uf 0 1 2]ailment[uf 0 1 27], an enemy's attack will leave you at a disadvantage or restrict your actions until you can recover.[n][uf 1 1][e]

[msg TRL_000_1_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The following ailments exist:[n][uf 1 1][e]

[msg TRL_001_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 18][uf 0 1 2]Shock[uf 0 1 27]: Unable to move.[n][uf 0 1 2]Freeze[uf 0 1 27]: Unable to move. Landing a physical attack will result in a critical hit.[n][uf 1 1][e]

[msg TRL_002_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 19][uf 0 1 2]Charm[uf 0 1 27]: Attack allies or buff/heal enemy at random.[n][uf 0 1 2]Confuse[uf 0 1 27]: Throw away money or use items randomly.[n][uf 1 1][e]

[msg TRL_003_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 20][uf 0 1 2]Poison[uf 0 1 27]: Take damage after each turn. Cannot recover naturally, so a skill or item will need to be used.[n][uf 0 1 2]Rage[uf 0 1 27]: Attack increases while Defense and Accuracy decrease. Will attack enemies unprompted.[n][uf 1 1][e]

[msg TRL_004_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 21][uf 0 1 2]Distress[uf 0 1 27]: Attack decreases. Will be unable to evade.[n][uf 0 1 2]Fear[uf 0 1 27]: High chance of ignoring commands. May try to escape battle unprompted.[n][uf 1 1][e]

[msg TRL_005_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 22][uf 0 1 2]Down[uf 0 1 27]: Unable to evade. Damage taken will increase. Chance of getting Dizzy when attacked while Down. Higher chance of getting Dizzy when attacked with a weapon.[n][uf 1 1][e]

[msg TRL_006_0_0 [Ailments]]
[uf 0 5 65278][uf 2 1][uf 4 8 23][uf 0 1 2]Dizzy[uf 0 1 27]: Unable to move. Will take critical hits more often.[n][uf 1 1][e]

