[msg TRL_000_0_0 [Guarding]]
[uf 0 5 65278][uf 2 1][uf 4 8 17]You can guard against an enemy's attack by pressing [uf 1 3 999]. Guarding will reduce damage by half.[n][uf 1 1][e]

[msg TRL_001_0_0 [Guarding]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Guarding can also keep you from getting knocked down even if an enemy targets your weakness. You will not be afflicted with status ailments while guarding either.[n][uf 1 1][e]

[msg TRL_002_0_0 [Guarding]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If an enemy is winding up for a powerful attack, or if you think your weakness will be targeted, try guarding to play it safe.[n][uf 1 1][e]

