[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1]The [uf 4 4 1 0 1 0] is reacting...[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1]The [uf 4 4 1 0 1 0] and[n][uf 4 4 1 0 1 1] are reacting...[n][uf 1 1][e]

[msg MND_CARD_INFO_03]
[uf 0 5 65278][uf 2 1]The card in my hand is reacting...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]The High Priestess Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]The Empress and Emperor Major Arcana[n]cards have been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]The Hierophant and Lovers Major Arcana[n]cards have been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]The Chariot and Justice Major Arcana[n]cards have been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]The Hermit Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]The Fortune and Strength Major Arcana[n]cards have been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]The Hanged Man Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CARD_INFO_VARIOUS]
[uf 0 5 65278][uf 2 1]Multiple Major Arcana cards[n]have been added to Shuffle Time.[n][uf 1 1][e]

[msg SYS_DETAIL_PRIESTESS]
[uf 0 5 65278][uf 2 1]High Priestess: [uf 0 1 2]All-Out Attack[uf 0 1 27] damage will increase until you leave Tartarus for the day.[n][uf 1 1][e]

[msg SYS_DETAIL_EMPRESS]
[uf 0 5 65278][uf 2 1]Empress: The [uf 0 1 36]En[uf 0 1 27], [uf 0 1 36]Ag[uf 0 1 27], and [uf 0 1 36]Lu[uf 0 1 27] of Personas in your possession will increase by 2.[n][uf 1 1][e]

[msg SYS_DETAIL_EMPEROR]
[uf 0 5 65278][uf 2 1]Emperor: The [uf 0 1 36]St[uf 0 1 27] and [uf 0 1 36]Ma[uf 0 1 27] of Personas in your possession will increase by 2.[n][uf 1 1][e]

[msg SYS_DETAIL_HIEROPHAN]
[uf 0 5 65278][uf 2 1]Hierophant: The [uf 0 1 2]level[uf 0 1 27] of your [uf 0 1 2]currently equipped Persona[uf 0 1 27] will increase by [uf 0 1 2]1[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_DETAIL_LOVERS]
[uf 0 5 65278][uf 2 1]Lovers: Increases [uf 0 1 2]Social Link bonuses[uf 0 1 27] for Persona fusions until you leave Tartarus.[n][uf 1 1][e]

[msg SYS_DETAIL_CHARIOT]
[uf 0 5 65278][uf 2 1]Chariot: Your [uf 0 1 34]maximum HP[uf 0 1 27] will increase by [uf 0 1 2]10[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_DETAIL_JUSTICE]
[uf 0 5 65278][uf 2 1]Justice: You will be able to [uf 0 1 2]pick one additional card[uf 0 1 27] from Shuffle Time until you leave Tartarus.[n][uf 1 1][e]

[msg SYS_DETAIL_HERMIT]
[uf 0 5 65278][uf 2 1]Hermit: Your [uf 0 1 34]maximum SP[uf 0 1 27] will increase by [uf 0 1 2]7[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_DETAIL_FORTUNE]
[uf 0 5 65278][uf 2 1]Fortune: All current party members' [uf 0 1 34]maximum HP[uf 0 1 27] will increase by [uf 0 1 2]8[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_DETAIL_STRENGTH]
[uf 0 5 65278][uf 2 1]Strength: All current party members' [uf 0 1 34]maximum SP[uf 0 1 27] will increase by [uf 0 1 2]5[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_DETAIL_HANGEDMAN]
[uf 0 5 65278][uf 2 1]Hanged Man: Obtain [uf 0 1 2]1[uf 0 1 27] [uf 0 1 39]Incense Card[uf 0 1 27], which [uf 0 1 2]increases a Persona stat[uf 0 1 27].[n][uf 1 1][e]

