[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]09/06/2009 19:10:36[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It's the lounge. Aragaki and[n]Koromaru are watching TV.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 6 10 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [TV Chef]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]—You, too, can follow along on page 39 of this month's issue.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Today we're making spicy pepper pasta. It's a great dish to keep your energy up in the summer heat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]The key ingredient is the Manganji pepper. Remember to remove the seeds first![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]After that, we'll prepare some kombu soup stock. You'll need a pasta cooker about this size, and...[n][uf 1 1][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 6 10 0 0][uf 3 1 1 0 0 6 0 0]A pasta cooker... Do we even have one of those here?[n][uf 1 1][e]

[msg MSG_005_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 7 0 0]Arf...?[n][uf 1 1][e]

[msg MSG_006_0_0 [Voice from Outside]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]It's still pretty hot...[n][uf 1 1][e]

[msg MSG_007_0_0 [Voice from Outside]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]It requires excess energy to maintain an appropriate external temperature.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 4 6 10 0 0][uf 3 1 1 0 0 10 0 0]Shit—[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 11 0 0]Arf![n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 10 0 0][uf 3 1 1 0 0 12 0 0]We have returned.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 6 10 0 0][uf 3 1 1 0 0 13 0 0]Woof, woof![n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 10 0 0][uf 3 1 1 0 0 14 0 0]We're home, Koro-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 10 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Oh... Shhh! We should be quiet. It looks like Aragaki-senpai's asleep...[n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 16 0 0]Arf.[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 10 0 0][uf 3 1 1 0 0 17 0 0]He says... "Aragaki-san is not asleep."[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 10 0 0][uf 3 1 1 0 0 18 0 0]Huh?[n][uf 1 1][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 10 0 0][uf 3 1 1 0 0 19 0 0]Senpai's magazine... It's the monthly guide to the Family Cooking show...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 10 0 0][uf 3 1 1 0 0 20 0 0]Does Aragaki-senpai enjoy cooking shows...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 10 0 0][uf 3 1 1 0 0 21 0 0]I didn't even know this month's issue was out.[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 22 0 0]Arf.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 10 0 0][uf 3 1 1 0 0 23 0 0]"Aragaki-san frequently watches programs like—"[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 10 0 0][uf 3 1 1 0 0 24 0 0]Uh, it's okay, Aigis![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 10 0 0][uf 3 1 1 0 0 25 0 0]Come on, let's go.[n][uf 1 1][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 6 10 0 0][uf 3 1 0 0 0 26 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 6 10 0 0][uf 3 1 1 0 0 27 0 0]Damn... I forgot she can understand dogs...[n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 6 10 0 0][uf 3 1 1 0 0 28 0 0]*whine*[n][uf 1 1][e]

[msg MSG_021_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 6 10 0 0][uf 3 1 1 0 0 29 0 0]Ah, don't sweat it. It ain't your fault.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 6 10 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 2 1 25 25]Don't worry, Koro-chan... Next time, I'll make you something, too.[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 6 10 0 0][uf 3 1 1 0 0 31 0 0]Arf![n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

