[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Amada seems to be having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We just finished watching a[n]hard-boiled fiction movie together.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]That action scene during the climax was amazing, wasn't it?[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like I gained some [uf 4 30 2 1 1 0] after[n]watching how a man of conviction lives...[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]Speaking of action scenes, Japan's live-action superhero shows are just as good. Really![n][uf 1 1][e]

