[msg TRL_000_0_0 [Social Links and Fusion]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When a new Persona shares an Arcana with an established Social Link, the Persona will gain experience during fusion.[n][uf 1 1][e]

[msg TRL_001_0_0 [Social Links and Fusion]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The bonus experience gained from Social Links is called the [uf 0 1 2]Social Link bonus[uf 0 1 27]. The higher the rank of the Social Link, the greater the bonus.[n][uf 1 1][e]

