[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Um, excuse me.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Will you please add me as a member in today's search party?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I want to participate in lots of battles and get used to handling my Persona.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Okay, come with me.[e]
[uf 0 5 65278][uf 2 1]Don't push yourself too hard.[e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]All right! I hope I can prove myself useful to all of you![n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Don't worry, I have no intention of doing so.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]But, I do want to do whatever I can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 3 25 25]So, um... I'd be very grateful if you let me come and fight alongside you![n][uf 1 1][e]

