[msg MSG_000_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]This is the first time we've met during the day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Let's have a chat while the opportunity presents itself.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]But we're enemies.[e]
[uf 0 5 65278][uf 2 1]What about the typhoon?[e]

[msg MSG_002_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 4 5 211 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]That doesn't concern me. Now, let's be off.[n][uf 1 1][e]

