[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]So today's theme is the "Hidden Fist: Martial Arts" series...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 5 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 4 6 25 25][uf 4 21 4 10]Somehow I get the feeling we're gonna see a lot of clichés in here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 4 0 25 25]Oh well. Let's check it out.[n][uf 1 1][e]

[msg MSG_900_0_0 [Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Red Three... This can't be! You should have already reached your limit! How are you still standing...!?[n][uf 1 1][e]

[msg MSG_901_0_0 [Red Three]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Limits exist to be broken. Now, witness my ultimate technique! Goenji Rekka Shinken: Final Form...![n][uf 1 1][e]

[msg MSG_902_0_0 [Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Ohh! Such an impressive ability... But it is I who shall prevail! Hrraaaaah![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...The action scene continues.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I cheered for the main character,[n]who pulled himself up every[n]time he was knocked down...[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 5 65535 0 0][uf 3 1 1 0 0 7 0 0]Did you see that move? His hands were on fire...[n][uf 1 1][e]

[msg MSG_002_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 4 0 25 25]And the way he jumped so high... It looked like he was suspended from the ceiling.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 9 0 0]I guess that's why they call it "wire fu," huh?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 11 0 0]But from what I saw, I didn't really spot any specialized training.[n][uf 1 1][e]

[msg MSG_003_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 4 0 25 25]They won't give up their secrets that easily. Must be why it's called the "Hidden Fist."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 4 2 25 25]Ngh... I've gotta train even harder![n][uf 1 1][e]

[msg MSG_003_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 5 65535 0 0][uf 3 1 1 0 0 14 0 0]All right, I'm gonna do squats on the monorail the whole way back![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I went back to the dorm with Sanada.[n][uf 1 1][e]

