[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]It looks like Sanada isn't here yet...[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Sorry I'm late. I ran into some unexpected trouble.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]All right, here goes. Back me up, would you?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm gonna make pancakes. Think you can help?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]I guess you could say I've got a craving... I used to eat them all the time at the orphanage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]I know they sell frozen ones nowadays, but nothing beats freshly cooked, right?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Why now?[e]
[uf 0 5 65278][uf 2 1]You're making a lot...[e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I don't really need a reason, do I? I just felt like it.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]You think so? I just thought more would be better than less.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Well, let's go on and get started. Okay, first things first...[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]...Uh, what exactly do we do first?[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I think the recipe said to use lots of butter and to regulate the pan's temperature with a damp washcloth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]...Wait, we put a washcloth in the pan? Won't it burn?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Want me to do it...?[e]
[uf 0 5 65278][uf 2 1]Please, just let me handle it...[e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]You sure? Thanks. I don't know how to cook anything besides the stuff I use for bodybuilding.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I can break the eggs and mix the batter. I'll leave the actual cooking part to you.[n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Oh, so that's how you use the washcloth.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]How about we add some protein powder...?[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Hey, don't look at me like that.[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]

[msg MSG_016_0_0 [Akihiko Sanada]]

[msg MSG_017_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]Oh, I better go get the plates.[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]All right, I think this'll be enough.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, check it out![n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Wow, look at all the pancakes! I knew something smelled good.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Yeah, just give me a minute. We can eat once I bring them out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Would you mind getting everyone else? And don't forget Amada.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba (SE)]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Okayyy![n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka (SE)]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Okay![n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Whoa... It's like a Tartarus of pancakes![n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Did the two of you make all of these yourselves?[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Yeah, although [uf 4 1] was the one who cooked 'em. I said I had a hankering, but we might've made too much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]I like pancakes, but no way I can eat all of these myself. If you guys could pitch in, that'd be great.[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]...So you like pancakes too, Sanada-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Thank you! I can't wait to have some![n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]I'll make some tea. I've got some leaves that'd be great for the occasion.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]It's pancake party time! ...As they say.[n][uf 1 1][e]

[msg MSG_030_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Arf![n][uf 1 1][e]

[msg MSG_031_0_0 [Ken Amada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]...These are so good! I could eat them all day.[n][uf 1 1][e]

[msg MSG_032_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Oh yeah? Good to hear.[n][uf 1 1][e]

[msg MSG_033_0_0 [Fuuka Yamagishi (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]The flavor brings a smile to my face![n][uf 1 1][e]

[msg MSG_034_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]Would ya say it... takes the cake?[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0]What are you, the chairman?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0]These really are good though![n][uf 1 1][e]

[msg MSG_036_0_0 [Mitsuru Kirijo (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 42 0 0]They've been cooked to absolute perfection. My compliments to the chef.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0]What is the difference between pancakes and hotcakes?[n][uf 1 1][e]

[msg MSG_038_0_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 44 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_039_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Thanks for the pancakes. They were really good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Tasted like a lot of care went into them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]If you ever make some again, I'd like to help out, too![n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]For as many as we made, they sure did disappear fast.[n][uf 1 1][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]Cooking's not really one of my strong points.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]A certain someone would always say, "If you pour protein powder on the ingredients, then you shouldn't be in the kitchen, dumbass."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]Most of the time I only ever got to watch someone else cook, so I never really learned myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 4 23 0 1 1 25 25]Anyways, thanks for helping out today. I'm hoping that cheered everyone up a little.[n][uf 1 1][e]

[sel SEL_042_0_0 top]
[uf 0 5 65278][uf 2 1]You planned this from the start?[e]
[uf 0 5 65278][uf 2 1]What made you want to do this?[e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]Yeah, pretty much.[n][uf 1 1][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]They did things like this back when I was at the orphanage. I just wanted to re-create it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]My sister used to cry all the time there, but the pancakes always brought a smile to her face.[n][uf 1 1][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 56 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]...Do you remember that medal you found in the package from my parents?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]My sister, Miki... She made that back when we were at the orphanage.[n][uf 1 1][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]Based on the letter that came with it, I guess my parents found it when they were cleaning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]Miki was gonna give that to me after we learned I was getting adopted out and leaving.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 61 0 0][uf 4 23 0 1 3 25 25]...But then that fire happened right after, and this medal was all that was left of her.[n][uf 1 1][e]

[sel SEL_047_0_0 top]
[uf 0 5 65278][uf 2 1]Sounds like you two were close.[e]
[uf 0 5 65278][uf 2 1]I'm sorry to hear that.[e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]...Apparently, Miki used to always say she wanted to thank me for being so strong and kind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]She was really quiet, and she'd always be following me around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]I don't really remember doing anything special for her, but I guess she was relying on me as her older brother.[n][uf 1 1][e]

[msg MSG_049_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]Seeing that medal made me think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]Would my sister be proud of who I am now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]Am I really strong and kind enough to deserve that medal?[n][uf 1 1][e]

[msg MSG_050_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]If I'm being honest, I don't really know what it means to be strong or kind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]Everyone who's ever said that to me has left without telling me the most important part.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 70 0 0]You saw how I was today... This is all I'm capable of right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 1 0 0 71 0 0]I haven't grown at all since I was a kid. They'd laugh if they saw me now.[n][uf 1 1][e]

[sel SEL_051_0_0 top]
[uf 0 5 65278][uf 2 1]That's not true.[e]
[uf 0 5 65278][uf 2 1]You're plenty strong and kind.[e]
[uf 0 5 65278][uf 2 1]Can't fight on an empty stomach.[e]

[msg MSG_052_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 72 0 0][uf 4 23 0 1 0 25 25]...Maybe my sister would say that, but you know not everyone would cut me that much slack.[n][uf 1 1][e]

[msg MSG_053_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 73 0 0][uf 4 23 0 1 1 25 25]Heh. I'm glad you feel that way, but I've still got a long way to go.[n][uf 1 1][e]

[msg MSG_054_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 74 0 0][uf 4 23 0 1 1 25 25]That's true. Sweet foods can relieve fatigue. I think I'll be ready to fight again by tomorrow.[n][uf 1 1][e]

[msg MSG_055_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 75 0 0]I realized I'd just been running away all this time, making excuses about having my own problems.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 76 0 0]But from now on, I'm gonna protect it all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 77 0 0]We promised we'd become strong together... I won't let him down.[n][uf 1 1][e]

[sel SEL_056_0_0 top]
[uf 0 5 65278][uf 2 1]I know you can do it.[e]
[uf 0 5 65278][uf 2 1]I'll help whenever you need.[e]
[uf 0 5 65278][uf 2 1]Best of luck.[e]

[msg MSG_057_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 78 0 0]Well, if that's how you feel, then I better not disappoint.[n][uf 1 1][e]

[msg MSG_058_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 79 0 0]Thanks, I really appreciate that. I'll be counting on you next time.[n][uf 1 1][e]

[msg MSG_059_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 80 0 0]Yeah. I've got people like you looking up to me, so I can't let them down.[n][uf 1 1][e]

[msg MSG_060_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 81 0 0]Heh, the point of this whole thing was to cheer everyone up, and yet I'm the one getting supported here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 82 0 0]You know, I think you're the kind of person my sister would've looked up to.[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 83 0 0]All right, that's enough talking about the past. Let's hurry up and finish clean—[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 5 65535 65535 0 0][uf 3 1 1 0 0 84 0 0]...Ngh.[n][uf 1 1][e]

[sel SEL_062_0_0 top]
[uf 0 5 65278][uf 2 1]What's wrong?[e]
[uf 0 5 65278][uf 2 1]Are you hurt?[e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 85 0 0]Well, I ran into that group of punks on my way home from shopping today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 86 0 0]There were even more of 'em this time, and one guy managed to get a good hit in.[n][uf 1 1][e]

[msg MSG_064_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 87 0 0]Don't worry though. I didn't do anything that would get me in trouble with the police.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 88 0 0]I just let them throw as many punches as they wanted until they got tired and gave up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 89 0 0]I thought I could dodge them all, but, uh... I guess I've still got room to improve.[n][uf 1 1][e]

[msg MND_065_0_0]
[uf 0 5 65278][uf 2 1]I finished cleaning up with Sanada,[n]then went back to my room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has improved[n]after seeing how caring Sanada is...[n][uf 1 1][e]

