[msg TRL_000_0_0 [Shortcuts]]
[uf 0 5 65278][uf 2 1][uf 4 8 231][uf 4 8 231]Pressing [uf 1 3 114] will give you access to [uf 0 1 2]shortcuts[uf 0 1 27] that will allow you to fast travel[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Shortcuts]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 4 8 0]Some shortcut destinations or even the shortcut function itself may be unavailable in certain situations.[n][uf 1 1][e]

