[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...And that concludes the disciplinary committee's forecast report.[n][uf 1 1][e]

[msg MSG_001_0_0 [(SE) Vice President]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Next up is the treasurer's report.[n][uf 1 1][e]

[msg MSG_002_0_0 [(SE) Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Yes.[n][uf 1 1][e]

[msg MSG_003_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Hey, sorry, but I was hoping you had some time once this meeting's over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]We can talk up on the roof.[n][uf 1 1][e]

