[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Yes, this looks good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]Just to be safe, we should adjust the amount of fertilizer and make sure they get enough sun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]They look like they're growing fine now. What a relief...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's all thanks to you, Fuuka.[e]
[uf 0 5 65278][uf 2 1]I worked hard too.[e]
[uf 0 5 65278][uf 2 1]It's too early to relax.[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh, I only lent a helping hand. I'm sure tending them is important...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]But it's all thanks to the plants themselves for being so strong.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Of course. They wouldn't be this healthy without you taking such good care of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]That's why they've grown up to be so strong![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]That's true. If we get a streak of bad weather, they might get sick again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]It sure is a lot of work to raise healthy plants...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]But I think they'll be fine if we make sure to look after them.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]You know, after I treated the plants when they were sick, I kept coming back here to check on them.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I noticed that the spots where we had cut off the leaves were already sprouting new ones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]And in just a little while, they were healthy and green all over again![n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Maybe I'm making a big deal of this, but it made me realize that life is actually quite amazing.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]It didn't matter that they had been weakened, or had damaged parts...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Just giving them a little support was enough for them to show how strong they really are.[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]We could learn from this.[e]
[uf 0 5 65278][uf 2 1]Let's keep at it.[e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 3 1 6]Yes, it really gave me hope. I think in a lot of ways, we're just like them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I'm not sure how to say it, but... I hope I can be as resilient as these plants are.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 3 1 6]Yes. If we hadn't had to take care of them like this, I never would have noticed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 1 25 25]I'm not sure how to say it, but... I hope I can be as resilient as these plants are.[n][uf 1 1][e]

[msg MND_011_5_0]
[uf 0 5 65278][uf 2 1]Fuuka is looking tenderly at the[n]plants we've grown together.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I think I'll check on the plants one more time, just to show my appreciation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Maybe if I keep thanking them, they'll grow even healthier.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]All right, that should do it. Shall we head back down?[n][uf 1 1][e]

