[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]The main character's [uf 4 30 2 1 1 0][n]and determination lit a fire in my soul...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The cinematic shots filled with beauty and[n][uf 4 30 1 1 1 0] made me appreciate the arts...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Watching the characters use body language to[n]communicate honed my [uf 4 30 0 1 1 0]...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Watching how the kids faced their[n]fears gave me some [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]My heart was captivated by the[n][uf 4 30 1 1 1 0] in this epic love story...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Seeing someone earnestly pursue the[n]truth helped refine my [uf 4 30 0 1 1 0]...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

[msg MSG_032_0_0 [Patriarch]]
[uf 0 5 65278][uf 2 1]Tch, you think some two-bit merc like you has what it takes to kill me!?[n][uf 1 1][e]

[msg MSG_033_0_0 [Patriarch]]
[uf 0 5 65278][uf 2 1]Son, you're the one who'll take over the family, so save yourself. Get the hell out of here![n][uf 1 1][e]

[msg MSG_034_0_0 [Son-in-Law]]
[uf 0 5 65278][uf 2 1]I won't become your successor... but no way am I leaving you behind! You're my father-in-law![n][uf 1 1][e]

[msg MSG_038_0_0 [Troubled Boy]]
[uf 0 5 65278][uf 2 1]I can't... I can't look... The top of the tower... It's terrifying![n][uf 1 1][e]

[msg MSG_039_0_0 [Counselor]]
[uf 0 5 65278][uf 2 1]You'll be all right. That point can't hurt you. Go on, take a look. It's not even that sharp.[n][uf 1 1][e]

[msg MSG_040_0_0 [Counselor]]
[uf 0 5 65278][uf 2 1]Open your eyes. It's Paris, the most beautiful city in the world. Face forward, turn away from your past...[n][uf 1 1][e]

[msg MSG_042_0_0 [American Girl]]
[uf 0 5 65278][uf 2 1]All right, Taro. Ready for the first session of your private English lessons? Repeat after me![n][uf 1 1][e]

[msg MSG_043_0_0 [Korean Girl]]
[uf 0 5 65278][uf 2 1]Nancy, could you stop hogging him? Taro is going out to eat dak hanmari with me![n][uf 1 1][e]

[msg MSG_044_0_0 [French Girl]]
[uf 0 5 65278][uf 2 1]Hold on now, So-yeon. Taro and I have a date at the museum today. He must witness the beauty of French art himself![n][uf 1 1][e]

[msg MSG_046_0_0 [Human Anatomy Model Ghost]]
[uf 0 5 65278][uf 2 1]Look behind you, children... Fear me! Scream and cower before me![n][uf 1 1][e]

[msg MSG_047_0_0 [Girl]]
[uf 0 5 65278][uf 2 1]Eek! The anatomical model from the science lab is moving![n][uf 1 1][e]

[msg MSG_048_0_0 [Boy]]
[uf 0 5 65278][uf 2 1]That's scientifically impossible. It's just a lame prank. I'm not gonna turn around and look like an idiot.[n][uf 1 1][e]

[msg MSG_050_0_0 [TV Announcer]]
[uf 0 5 65278][uf 2 1]...While the newly excavated box itself dates back to the Heian era, the letter inside appears to be written in modern Japanese...[n][uf 1 1][e]

[msg MSG_051_0_0 [High Schooler]]
[uf 0 5 65278][uf 2 1]Th-That's it! That's my letter! It really did travel back in time...[n][uf 1 1][e]

[msg MSG_050_5_0 [High Schooler]]
[uf 0 5 65278][uf 2 1]That means... you really did get my message—that I love you, Murasaki Shikibu.[n][uf 1 1][e]

[msg MSG_054_0_0 [Junior Investigator]]
[uf 0 5 65278][uf 2 1]This must be the method the culprit used to seemingly vanish into thin air.[n][uf 1 1][e]

[msg MSG_055_0_0 [Senior Investigator]]
[uf 0 5 65278][uf 2 1]I see. The statute of limitations ran out three years ago, but with modern technology, we may be able to shed some light on this case.[n][uf 1 1][e]

[msg MSG_056_0_0 [Junior Investigator]]
[uf 0 5 65278][uf 2 1]Perhaps... But it's just as likely we may never discover the truth—like the past 127 cases.[n][uf 1 1][e]

[msg MSG_058_0_0 [Movie Protagonist]]
[uf 0 5 65278][uf 2 1]Just crossing the street is going to take twenty minutes at my current size![n][uf 1 1][e]

[msg MSG_059_0_0 [Movie Protagonist]]
[uf 0 5 65278][uf 2 1]And it's way too dangerous, what with all these kids running around and the dogs out for walks![n][uf 1 1][e]

[msg MSG_060_0_0 [Movie Protagonist]]
[uf 0 5 65278][uf 2 1]But I'm not giving up! Nothing's gonna stand in my way! Just you wait, 3rd Street![n][uf 1 1][e]

[msg MSG_062_0_0 [Voice Over the Radio]]
[uf 0 5 65278][uf 2 1]Agent G, this is a covert operation. Wouldn't your cover be blown by your attire?[n][uf 1 1][e]

[msg MSG_063_0_0 [Agent G]]
[uf 0 5 65278][uf 2 1]Do you think me incompetent? My outfit hardly matters when the enemy won't notice a thing.[n][uf 1 1][e]

[msg MSG_064_0_0 [Agent G]]
[uf 0 5 65278][uf 2 1]Right then. The next time I'll be in contact, it's to report a mission well done. Now, allons-y![n][uf 1 1][e]

[msg MSG_066_0_0 [Detective Pompadour]]
[uf 0 5 65278][uf 2 1]That testimony is bullshit, man! YOU'RE the real perp![n][uf 1 1][e]

[msg MSG_067_0_0 [Culprit]]
[uf 0 5 65278][uf 2 1]Ugh... My plan was perfect. I just didn't account for you showing up on your motorcycle.[n][uf 1 1][e]

[msg MSG_068_0_0 [Detective Pompadour]]
[uf 0 5 65278][uf 2 1]Heh! I swear on my sick-ass hair that I'll solve any case—and don't you forget it![n][uf 1 1][e]

