[sel SEL_BOSS top]
[uf 0 5 65278][uf 2 1]I have plenty.[e]
[uf 0 5 65278][uf 2 1]Wait...[e]

[msg MND_STOP_UFO_CATCHER]
[uf 0 5 65278][uf 2 1]Looks like the power's out...[n][uf 1 1][e]

[msg MSG_SHOP_STOP_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]What's the matter?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]The Dark Hour's gonna be over if we don't get a move on.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_AEGIS [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]The enemy awaits, but we have very little time to spare.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Please prepare to enter combat.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]What are you doing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Have you finished prepping? I'm ready anytime.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9003 0 0]What's up with you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Move your ass and take charge already.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_AMADA [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Um, shouldn't we go fight now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]The Shadow's nearby, right? We should take it out sooner rather than later.[n][uf 1 1][e]

[msg MSG_OUT_STOP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]If you waste any more time, the Dark Hour will end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Get ready to infiltrate Escapade.[n][uf 1 1][e]

[msg MND_NO_VDOOR]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I don't see a door right now.[n][uf 1 1][e]

[msg MSG_CLUB_STOP [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]You need to bring more of our teammates with you. Come back and set up a full party.[n][uf 1 1][e]

[msg MSG_GO_INTO_CLUB [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Please be careful...[n][uf 1 1][e]

[sel SEL_BOSS_G top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Hold on a bit.[e]

[sel SEL_MALL_SHORTCUT top]
[uf 0 5 65278][uf 2 1]Police Station[e]
[uf 0 5 65278][uf 2 1]Aohige Pharmacy[e]
[uf 0 5 65278][uf 2 1]Mayoido Antiques[e]
[uf 0 5 65278][uf 2 1]Back Alley[e]
[uf 0 5 65278][uf 2 1]Town Map[e]
[uf 0 5 65278][uf 2 1]Cancel[e]

[msg MND_FLD_ORDERN]
[uf 0 5 65278][uf 2 1]Where should I go...?[n][uf 1 1][e]

