[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Let's not fight yet.[e]

[msg MSG_MONAD_BTL_QUESTION_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 1 5343 0 0]It's a strong enemy! Are you ready to fight it?[n][uf 1 1][e]

[msg MSG_MONAD_BTL_QUESTION_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 1 5343 0 0]You'll have to defeat this enemy to move on... Are you ready?[n][uf 1 1][e]

[msg MSG_MONAD_BTL_QUESTION_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 1 5343 0 0]It's a very powerful enemy! Please make sure you're fully prepared for battle![n][uf 1 1][e]

