[msg MSG_MITSURU_CALL_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10021 0 0]...Akihiko and— ...aren't— ...this floor—[n][uf 1 1][e]

[msg MSG_UNKNOWN_01 [Mysterious Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10022 0 0]Who's there...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10023 0 0]Are you... human?[n][uf 1 1][e]

[msg MSG_MITSURU_CALL_05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10024 0 0]Can y— ...hear me? ...Please ans—[n][uf 1 1][e]

[msg MSG_UNKNOWN_03 [Mysterious Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10025 0 0]Is someone there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10026 0 0]Please, answer me...[n][uf 1 1][e]

[msg MND_MITSURU_NOISE [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Communication is breaking up...[n][uf 1 1][e]

[msg MND_NOISE_MES [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_MITSURU_OVER [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Communication has been lost...[n][uf 1 1][e]

