[msg MSG_Strong_01_Mituru [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 3 0 65535 4102 0 0]Wait![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]There's an enemy nearby, but...[n][uf 1 1][e]

[msg MSG_Strong_01_Mituru_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]It's in a league of its own, far different from the run-of-the-mill Shadows in this area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]This will be a tough fight. If you're not feeling confident, then don't engage in combat.[n][uf 1 1][e]

[msg MSG_Strong_01_Mituru_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]Should we enter battle, retreat is a viable option.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0]We need a leader capable of making level-headed decisions so we don't end up in dire straits.[n][uf 1 1][e]

[msg MSG_Strong_01_Fuka [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]...Hang on![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I'm sensing an enemy nearby, but, um...[n][uf 1 1][e]

[msg MSG_Strong_01_Fuka_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]This Shadow seems a bit tougher than the other ones in this area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It'll be a tough fight, so if you think you can't handle it, try to avoid combat.[n][uf 1 1][e]

[msg MSG_Strong_01_Fuka_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If you do get caught, it'd be wise to retreat immediately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]And, most importantly, please don't make any reckless decisions. We need you to keep a calm head.[n][uf 1 1][e]

