[msg MSG_TAR_STOP_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Hold on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It's not safe to continue any further. Check that device over there.[n][uf 1 1][e]

[msg MSG_TAR_STOP_MITSURU_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4031 0 0]I know you're eager to go on, but use that device to return here for now.[n][uf 1 1][e]

[msg MSG_TAR_STOP_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Please wait![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's dangerous to keep going. Could you go take a look at that device over there?[n][uf 1 1][e]

[msg MSG_TAR_STOP_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]Please come back for now. You should be able to use that device to return.[n][uf 1 1][e]

[msg MSG_MITSURU_DEFEAT_GK_FI [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]You're doing great, but I'm sure that last battle must have worn you out some.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If you continue on now, there's no telling when you'll find another teleporter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Since there's one right here, I suggest you make use of it and stop for a break.[n][uf 1 1][e]

[msg MSG_FUKA_DEFEAT_GK_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]It looks like you can move forward now, but are you tired from that last battle?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If you keep going, I don't know when you'll encounter another teleporter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]I think it would be good to use the one here to return to the entrance for now.[n][uf 1 1][e]

