[msg MSG_SECRET_GATE_APPEAR [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5092 0 0]What's this...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]I think something new has appeared on this floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It's nothing huge, but I'll give you another heads-up when you're closer to it.[n][uf 1 1][e]

[msg MSG_059_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]I think this device caused that tremor just now.[n][uf 1 1][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]The reading that I'm getting from it is similar to the one from the entrance...[n][uf 1 1][e]

[msg MND_057_0_0]
[uf 0 5 65278][uf 2 1]The shape is similar as well. Could it[n]be a portal leading somewhere else...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I better take a closer look.[n][uf 1 1][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Hmm... Something seems different about this floor...[n][uf 1 1][e]

[msg MSG_047_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Is this clock... maybe like the one on the first floor?[n][uf 1 1][e]

[msg MND_048_0_0]
[uf 0 5 65278][uf 2 1]There's a booklet in front of the clock...[n][uf 1 1][e]

[msg MND_052_0_0]
[uf 0 5 65278][uf 2 1]The title on the cover reads,[n]"Great Clock Manual."[n][uf 1 1][e]

[msg MSG_049_0_0 [Great Clock Manual]]
[uf 0 5 65278][uf 2 1]"For those who seek to gain greater power from a common experience..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"To activate the Great Clock, a prerequisite quantity of Twilight Fragments is required."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"After an offering is made and the hands strike twelve, then the Great Clock can be used."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"The observer shall then reach for the pendulum while picturing a recipient of the Clock's power."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"...Last day of the month, activity verified."[n][uf 1 1][e]

[msg MND_050_0_0]
[uf 0 5 65278][uf 2 1]The document seems to[n]be from ten years ago.[n][uf 1 1][e]

[msg MND_051_0_0]
[uf 0 5 65278][uf 2 1]The clock's hands are already[n]pointing at twelve...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I might as well follow the instructions[n]and picture one of my teammates...[n][uf 1 1][e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5101 0 0]What the...!?[n][uf 1 1][e]

[msg MND_053_0_0]
[uf 0 5 65278][uf 2 1]Let's try this again... Who should I think of?[n][uf 1 1][e]

[msg MSG_044_0_0]
[uf 0 5 65278][uf 2 1]Select a teammate to receive growth.[n][uf 1 1][e]

[msg MSG_044_5_0]
[uf 0 5 65278][uf 2 1]Choose one more teammate.[n][uf 1 1][e]

[msg MSG_045_0_0]
[uf 0 5 65278][uf 2 1]Choose two more teammates.[n][uf 1 1][e]

[msg MSG_044_7_0]
[uf 0 5 65278][uf 2 1]Choose three more teammates.[n][uf 1 1][e]

[sel SEL_CLOCK_MENU top]
[uf 0 5 65278][uf 2 1]Level up a teammate[e]
[uf 0 5 65278][uf 2 1]Raise a teammate's stat[e]
[uf 0 5 65278][uf 2 1]Enhance a teammate's skill[e]

[msg SYS_ADD_EXP_CONFIRM]
[uf 0 5 65278][uf 2 1][uf 1 4 1]The selected teammate will gain a large amount of experience in their next battle. Proceed?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_YUKA]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Yukari Takeba will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_JUNP]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Junpei Iori will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_SANA]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Akihiko Sanada will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_MITU]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Mitsuru Kirijo will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_FUKA]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Fuuka Yamagishi will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_AIGI]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Aigis will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_AMAD]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Ken Amada will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_KORO]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Koromaru will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_ADD_EXP_CONFIRM_ARAG]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Shinjiro Aragaki will grow from [uf 0 1 37]level [uf 2 4 11][uf 0 1 27] to [uf 0 1 37]level [uf 2 4 12][uf 0 1 27] in the next battle. Confirm?[n][uf 1 1][e]

[msg SYS_PARAMETER_UP_CONFIRM]
[uf 0 5 65278][uf 2 1][uf 1 4 1]A teammate's stat will be increased. The boosted stat depends on the teammate, and cannot be selected by you. Proceed?[n][uf 1 1][e]

[msg SYS_SIKILL_ENHANCE_CONFI]
[uf 0 5 65278][uf 2 1][uf 1 4 1]A teammate's skill will receive enhancement. Examples include damage boosts or reduced SP costs, but the skill cannot be selected. Proceed?[n][uf 1 1][e]

[msg SYS_ADD_EXP_END [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Experience bonuses have been applied to your selected teammates. Add them to your party and win a battle to finalize their gains.[n][uf 1 1][e]

[msg PFM_YUKARI_PARAM_UP]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Yukari's Persona, [uf 0 1 35]Io[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_009_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Yukari's Persona, [uf 0 1 35]Isis[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_006_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Junpei's Persona, [uf 0 1 35]Hermes[uf 0 1 27], has had its Strength raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_007_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Junpei's Persona, [uf 0 1 35]Trismegistus[uf 0 1 27], has had its Strength raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_010_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Sanada's Persona, [uf 0 1 35]Polydeuces[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_011_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Sanada's Persona, [uf 0 1 35]Caesar[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_012_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Mitsuru's Persona, [uf 0 1 35]Penthesilea[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_010_5_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Mitsuru's Persona, [uf 0 1 35]Artemisia[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_013_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Fuuka's Persona, [uf 0 1 35]Lucia[uf 0 1 27], has had its Luck raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_015_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Fuuka's Persona, [uf 0 1 35]Juno[uf 0 1 27], has had its Luck raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_014_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Aigis's Persona, [uf 0 1 35]Palladion[uf 0 1 27], has had its Strength raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_016_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Aigis's Persona, [uf 0 1 35]Athena[uf 0 1 27], has had its Strength raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_018_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Amada's Persona, [uf 0 1 35]Nemesis[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_017_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Amada's Persona, [uf 0 1 35]Kala-Nemi[uf 0 1 27], has had its Magic raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_019_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Koromaru's Persona, [uf 0 1 35]Cerberus[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_021_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Koromaru's Persona, [uf 0 1 35]Cerberus[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_020_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Aragaki's Persona, [uf 0 1 35]Castor[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[msg PFM_022_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Aragaki's Persona, [uf 0 1 35]Castor[uf 0 1 27], has had its Agility raised by [uf 2 4 0].[n][uf 1 1][e]

[sel SEL_CHARA_SELECT_LEVEL top]
[uf 0 5 65278][uf 2 1][uf 4 27 2 0]Yukari level up: [uf 0 1 3][uf 2 4 2][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 3 0]Junpei level up: [uf 0 1 3][uf 2 4 3][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 4 0]Sanada level up: [uf 0 1 3][uf 2 4 4][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 5 0]Mitsuru level up: [uf 0 1 3][uf 2 4 5][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 6 0]Fuuka level up: [uf 0 1 3][uf 2 4 6][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 7 0]Aigis level up: [uf 0 1 3][uf 2 4 7][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 8 0]Amada level up: [uf 0 1 3][uf 2 4 8][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 9 0]Koromaru level up: [uf 0 1 3][uf 2 4 9][uf 0 1 27].[e]
[uf 0 5 65278][uf 2 1][uf 4 27 10 0]Aragaki level up: [uf 0 1 3][uf 2 4 10][uf 0 1 27].[e]

[sel SEL_CHARA_SELECT_NOMAL top]
[uf 0 5 65278][uf 2 1]Yukari Takeba[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Junpei Iori[uf 4 27 3 0][e]
[uf 0 5 65278][uf 2 1]Akihiko Sanada[uf 4 27 4 0][e]
[uf 0 5 65278][uf 2 1]Mitsuru Kirijo[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Fuuka Yamagishi[uf 4 27 6 0][e]
[uf 0 5 65278][uf 2 1]Aigis[uf 4 27 7 0][e]
[uf 0 5 65278][uf 2 1]Ken Amada[uf 4 27 8 0][e]
[uf 0 5 65278][uf 2 1]Koromaru[uf 4 27 9 0][e]
[uf 0 5 65278][uf 2 1]Shinjiro Aragaki[uf 4 27 10 0][e]

