[msg MSG_THEURGIA_ENEMY_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 20560 0 0]You're approaching a Shadow! Get ready for battle![n][uf 1 1][e]

[msg MSG_THEURGIA_ENEMY_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 1 20561 0 0]Roger that. I'm always ready.[n][uf 1 1][e]

[msg MSG_THEURGIA_ENEMY_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 20562 0 0]Leader, are you ready?[n][uf 1 1][e]

[msg MSG_THEURGIA_STOP_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Uhh, should we really be just ignoring the enemy?[n][uf 1 1][e]

[msg MSG_THEURGIA_STOP_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1116 0 0]Okay, let's go![n][uf 1 1][e]

[msg MSG_THEURGIA_STOP_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]There are still Shadows on this floor. Please defeat them before moving on.[n][uf 1 1][e]

