[sel SEL_OPEN top]
[uf 0 5 65278][uf 2 1]Open it[e]
[uf 0 5 65278][uf 2 1]Leave it alone[e]

[sel SEL_RemainTBox top]
[uf 0 5 65278][uf 2 1]Exit[e]
[uf 0 5 65278][uf 2 1]Stay longer[e]

[msg MSG_RemainTBoxTalk00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I sense a treasure chest. It looks like there's one at the end of the room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It might have something valuable inside... Do you really want to leave without it?[n][uf 1 1][e]

[msg MSG_RemainTBoxTalk01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's still an unopened treasure chest... Do you want to leave without it?[n][uf 1 1][e]

[msg MSG_ACCESS_DOOR_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]This place is...![n][uf 1 1][e]

[msg MSG_OPEN_DOOR_FIRST [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Sorry, but could you spend some more time exploring this area?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]My powers aren't strong enough to see everything in there...[n][uf 1 1][e]

[msg MSG_NOT_EXIT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Could you explore a little further in?[n][uf 1 1][e]

[msg MSG_TUTO01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]There's still an unopened treasure chest. I think you should open it before leaving.[n][uf 1 1][e]

[msg MSG_TUTO_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]It feels different in here compared to outside.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]The atmosphere is unstable and the walls look like they're rippling...[n][uf 1 1][e]

[msg MSG_TUTO_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]My powers aren't working very well here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]I can at least tell that it's not a very large area, but please be careful.[n][uf 1 1][e]

[msg MND_NOT_OPEN]
[uf 0 5 65278][uf 2 1]The door is tightly sealed.[n][uf 1 1][e]

[msg MSG_Monad03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0]Can you please return here? I'd like to go through what we know about that door.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Luckily, there seems to be a teleporter nearby.[n][uf 1 1][e]

[sel SEL_Monad03 top]
[uf 0 5 65278][uf 2 1]Sure thing.[e]
[uf 0 5 65278][uf 2 1]If you say so...[e]

[msg MSG_Monad03_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Thank you. I'll be waiting at the entrance.[n][uf 1 1][e]

