[msg MSG_ELIZABETH_TALK [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Thank you for a wonderful time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Now, please make your way to the entrance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I have some thinking to do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I shall see you again in the Velvet Room.[n][uf 1 1][e]

[msg MND_000 [Elizabeth]]

[msg MND_001 [Elizabeth]]

[sel SEL_000 top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]No[e]

