[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]All right... It's finally time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]I know we've put a lot on you guys, but that's over now.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]We're counting on you.[e]
[uf 0 5 65278][uf 2 1]Don't overdo it now.[e]
[uf 0 5 65278][uf 2 1]What are your strengths?[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Don't worry, I've been preparing for this day. You won't be disappointed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 4 0 0]I'll follow whatever orders you give. You're the leader here.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Heh, don't worry. I'm in perfect condition.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 6 0 0]I almost feel sorry for our enemy. Well, just give me a chance and you'll see.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 7 0 0]I'm a power fighter that overwhelms my foes with my fists.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 9 25 25]...Or so you'd think, right? But that's definitely not all there is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 9 0 0]I've been sharpening my skills as well, and that includes the ability to target an enemy's weakness. Just wait, you'll see.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]I'll make up for all that time I lost before you know it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Plus, I've gotta show my stuff as one of the veteran members. Just make sure to put me in the advance team.[n][uf 1 1][e]

