[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I was told to fetch Aigis,[n]but she's not around...[n][uf 1 1][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, the next one up for career consultation...? That'd be Aigis-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]She was just here a second ago, but I guess she went out.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 3 0 0]Maybe she's on the roof. I've seen her go up there alone every now and then.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Thanks.[e]
[uf 0 5 65278][uf 2 1]I'll go look.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 4 0 0]Sure, good luck.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 5 0 0]So, do you think she's gonna go to college or get a job? She's full of mysteries, isn't she?[n][uf 1 1][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]She's changed recently though, don't you think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Like her expressions and stuff.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 8 0 0]Again with that? Are you ever gonna stop thinking about hitting on girls?[n][uf 1 1][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 2 65535 0 0][uf 3 1 1 0 0 9 0 0]I don't mean it like that! All I'm saying is...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I should head to the rooftop.[n][uf 1 1][e]

