[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5039 0 0]Thank you both so much for coming! You were a great help![n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Um... Sorry for making you come with us, Aigis-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]I guess, in the end, just the two of us could've handled it, so...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0]Oh, um... I don't think there's any need to worry about that.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7061 0 0]But we have to conserve our energy. We don't know how long we'll be stuck here...[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]It could be a while...[e]
[uf 0 5 65278][uf 2 1]You're just overthinking.[e]
[uf 0 5 65278][uf 2 1]Don't worry, we'll escape.[e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7062 0 0]Um, yeah... But I guess I might also just be too anxious about everything.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7062 0 0]Yeah, you're probably right. I'm just feeling pretty anxious about everything.[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7132 0 0]...Haha, jeez look at me. I guess I'm just feeling really anxious about everything.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]I understand how you feel, Amada-kun. I agree that we should try to conserve our strength and resources.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]But at the same time... It was really fun doing this with both of you! I think things like that are important too.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 4 25 8]Huh...[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7117 0 0]Yeah... you're right... I feel the same way...[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]I had fun shopping with both of you too![n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]I did as well![e]
[uf 0 5 65278][uf 2 1]Yes, fun is important.[e]
[uf 0 5 65278][uf 2 1]Let's do this again soon.[e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7030 0 0]Yeah![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]Getting too worried can drain your energy too... So I guess this is also a good way to conserve it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]Haha... I'm kind of embarrassed I was too closed-minded to realize that earlier.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]It seems like Amada-san[n]has had a great realization...[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5096 0 0]"Closed-minded"...? Hehe...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]I wouldn't worry, Amada-kun. I think you're a very sensitive young man.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7113 0 0]"Sensitive"...? Uh, I guess I'll take that as a compliment...[n][uf 1 1][e]

