[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0][uf 5 13 7 5 2]Hahaha! And then what happened?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Yukari grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's almost dark...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

