[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 4 101 65535 0 0][uf 3 1 3 0 65535 10879 0 0]Dang, dude... You sure know how to dress to impress.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]I wanna get some new threads, but I don't have time for that now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]On the weekends, I just wear my track suits—helps me get my head in the game and all that.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10893 0 0]That way, I'm ready to go 24/7, y'know? That's real dedication, man.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Impressive.[e]
[uf 0 5 65278][uf 2 1]I don't really care.[e]
[uf 0 5 65278][uf 2 1]You need to chill.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10823 0 0][uf 5 13 8 30 105]It's mental strength, man. That's what I'm all about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0]Nobody out there can beat me! Well, in spirit. You're not half-bad though, I'll give you that.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems to be having a lot of fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10829 0 0][uf 5 13 8 15 105]Heh, you think you're some kinda big shot now just 'cause you beat me once?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0]You better watch out, pal, 'cause next time you're goin' down! Er, once I'm in better condition...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems to be having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10852 0 0]...Yuko told me the exact same thing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]I thought she just didn't get the whole dedication thing... But if you're saying it, too, then maybe I'm coming off a little too strong?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems a little depressed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10854 0 0]So, what's the plan? Should we just walk around and find a place to eat?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]We walked around the strip mall for a little[n]while before I had to head back to the dorm.[n][uf 1 1][e]

