[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3092 0 0][uf 4 25 4]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]Guess I need to push my limits even harder...[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Ruff![n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3053 0 0]Oh, sorry, Koromaru. Hey, listen, I was just thinking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]What do you say to a little exploring, just you and me? Might make for decent training.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 3 0 65535 3107 0 0]Heh, rarin' to go, huh? Glad I can always count on you, Koromaru.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 3 0 65535 3027 0 0]Phew... That was pretty tough on our own. Should've figured.[n][uf 1 1][e]

[msg MSG_007_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0]*whimper*[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]Don't get me wrong, I'm not beating myself up over it.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3005 0 0]I know there's only so much I handle by myself... Not like I can think fast on my feet, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]No matter what's in front of me, I always come out swinging the second the bell rings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 4 23 0 1 2 25 25]I've gone through this exact same thing before, but I guess I just forgot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 3 0 65535 3031 0 0]Was it after we got weaker...? No, it must have happened way before that.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3042 0 0]Thanks for this, Koromaru. Sorry you had to put up with such a moron.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0]Awoooooo![n][uf 1 1][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 52 65535 0 0][uf 3 1 3 0 65535 3068 0 0]...Hang on, was there something weighing on your mind, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 4 23 0 1 1 25 25]I had no clue. You just look like the same ol' handsome devil to me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Well, should we start heading back?[n][uf 1 1][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]But don't tell Aigis or Mitsuru about any of this. It'll be our heads if they find out we went off exploring on our own.[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

