[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Are you ready, [uf 4 1]?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 3 25 25]You didn't invite anyone else, did you? Wait, what am I saying...?[n][uf 1 1][e]

[msg MSG_000_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]Sorry, I'm having some trouble remaining calm. I'll let you decide where we should go...[n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I decided to spend[n]Christmas Eve with Mitsuru...[n][uf 1 1][e]

