[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MSG_001_0_0 [School PA]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]...Attention please.[n][uf 1 1][e]

[msg MSG_001_5_0 [School PA]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Fushimi-san of Class 1-C... [uf 4 1]-san of Class 2-F...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]The student council president would like to speak with you. Please report to the student council room immediately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]I repeat...[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]The president wants to speak with me...?[n][uf 1 1][e]

[msg MSG_002_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]D-Don't tell me she thinks I stole the money too![n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry, she'll help us.[e]
[uf 0 5 65278][uf 2 1]Mitsuru's not like that.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 9 5 109]Y-Yes, you're right! She'll help us, won't she?[n][uf 1 1][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]And if I talk to her, at least I won't have to trouble you anymore, [uf 4 1]-san...[n][uf 1 1][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh? "Mitsuru"...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]O-Oh, I see! I didn't realize you two knew each other so well.[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]...Um, shall we head to the student council room then?[n][uf 1 1][e]

