[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I spend my breaks doing nothing but reading, so I think it's about time I bought some new ones...[n][uf 1 1][e]

[msg MSG_000_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Oh, all of the books on this shelf are only 100 yen each! That means I can afford them with my allowance.[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 0 0 0 3 0 0]Hmmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]We can go now. I don't really see anything that interests me...[n][uf 1 1][e]

[msg MSG_001_3_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 0 0 0 5 0 0]...Hm?[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]W-Wait, is this...!?[n][uf 1 1][e]

[msg MSG_002_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]It is! I've been looking for this collector's edition for forever![n][uf 1 1][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]This is a collection of illustrations from the shojo manga I read! It even has a set of new short stories inside![n][uf 1 1][e]

[msg MSG_003_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I never thought I'd find this in a used bookstore. And in the novels section too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Maybe the shop owner saw the "short stories" label and made a mistake.[n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]...It's got all three volumes too. This is amazing...[n][uf 1 1][e]

[msg MSG_004_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Each volume is 6,000 yen, so that means... 18,000 yen total!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 21 109 11]Wh-What should I do...?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Is it good?[e]
[uf 0 5 65278][uf 2 1]You're not buying it?[e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 9 15 109]Of course! All three volumes are great![n][uf 1 1][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]The characters are portrayed so realistically! It's like they really exist![n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Well, it... It's kind of... expensive.[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I can't afford it with what I have right now, and I don't want to go and take money out of my savings...[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]My monthly allowance is 5,000 yen. So it's not enough, even if I save my lunch money...[n][uf 1 1][e]

[msg MSG_010_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]But I'll get it, no matter what! I just need to wait until next month... or the month after... or...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...I'll get them by the time I graduate![n][uf 1 1][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I-I need to hide this where no one will see it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Oh, please don't get bought by someone else...[n][uf 1 1][e]

