[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 12 10 106]Let's go find our seats![n][uf 1 1][e]

[msg MSG_900_0_0 [High School Baseball Player]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]This last pitch will mark the end of our summer... Focus, give it everything you've got![n][uf 1 1][e]

[msg MSG_901_0_0 [Narrator]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Everyone in the stadium fell silent. That final pitch was the hardest fastball of the day.[n][uf 1 1][e]

[msg MSG_902_0_0 [High School Baseball Player]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Did you see that!? That's the result of all my training![n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel inspired by the athletes[n]playing their absolute hardest.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Wow, wasn't that great? Now that's what youthful passion looks like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 6 0 0]It's getting dark, let's head home.[n][uf 1 1][e]

[msg MND_003_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]After saying goodbye to Yuko,[n]I decided to go back to the dorm.[n][uf 1 1][e]

