[msg MSG_000_0_0 [Pale Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 320]I couldn't sleep last night because I kept thinking about school starting, so I came to the nurse's office to nap...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 320]But that nurse gave me some weird medicine instead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 320]I turned it down 'cause it looked really gross... Only a brave soul would dare drink something like that![n][uf 1 1][e]

