[msg MSG_000_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]There are all kinds of shops here at the Iwatodai strip mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you're craving delicious food, then head to Wakatsu! There's also Hagakure, a famous ramen shop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You can also find dessert here, and burgers, and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Hehe, sorry, I'm just going on about food, huh. Guess it's eating time! Just kidding.[n][uf 1 1][e]

