[msg MSG_000_0_0 [Club-Ditching Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]Oh, you're that transfer student. You gonna join a club or something?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I'm planning to.[e]
[uf 0 5 65278][uf 2 1]I'm still thinking about it.[e]

[msg MSG_001_0_0 [Club-Ditching Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]Oh yeah? You won't be able to join right away though. I hear a lot of them are at max capacity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]Well, just keep an eye out for an open spot. They might start recruiting again in late April.[n][uf 1 1][e]

[msg MSG_002_0_0 [Club-Ditching Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]Well, club activities suck anyway. You have to socialize and be considerate of other people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]I guess it's a good way to make new friends, but I also just wanna enjoy high school, you know?[n][uf 1 1][e]

