[msg MSG_000_0_0 [Preachy Teacher]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 318]You have some nerve dozing off in class this early in the new semester...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 318]Why, back in my day, it was unheard of! Hmph, kids these days...[n][uf 1 1][e]

[msg MSG_000_5_0 [Smirking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 319]Yeah, yeah, I'm sorry, all right? Yeesh, the semester's just started, and I'm already being nagged at.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 319]Man, just when I was planning on going to Hagakure for some ramen...[n][uf 1 1][e]

