[msg MSG_000_0_0 [Caring Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]That uniform... You must be a student at Gekkoukan High. That's nice. Do you live in this dorm?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]It looks like Gekkoukan High went through a rough patch a while back, but it's been rebuilt into such a magnificent building...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]...Oh, never mind me. Enjoy your new school semester this spring![n][uf 1 1][e]

[msg MSG_001_0_0 [Caring Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 703]I hear that there's a weird disease going around, so take care of yourself.[n][uf 1 1][e]

