[msg MSG_000_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Don't you feel completely lost whenever you transfer to a new school?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]This is the second floor, and the one below has the faculty office, club rooms, and more hands-on classes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]If you go down either of the two staircases, you'll be able to reach the front entrance.[n][uf 1 1][e]

