[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]Um, about last time...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]I-I just wanted to apologize for bringing up an uncomfortable topic like that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 4 23 0 109 0 25 25]But I think your advice really, um... helped my friend.[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0]Um... Your coffee is going to get cold.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]It needs to cool down.[e]
[uf 0 5 65278][uf 2 1]Do you want sugar?[e]
[uf 0 5 65278][uf 2 1]I know.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11454 0 0][uf 5 13 9 15 109]O-Oh, um... Maybe you should've ordered iced coffee, then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 4 23 0 109 4 25 25]...Oh! Sorry! I wasn't trying to tell you what to do. I-I just thought my suggestion could help a little...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Chihiro is smiling a bit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11475 0 0][uf 5 13 9 30 109]Oh, uh, yes! Could I have... three cubes, please?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 4 23 0 109 1 25 25]To be honest, I've got quite a sweet tooth. I can never say no to anything sweet.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Chihiro is smiling again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11447 0 0]S-Sorry! I didn't mean to nag...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]...It seems like all I've been doing is apologizing today... Sorry about that, [uf 4 1]-san...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Chihiro has fallen silent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]But, um...[n][uf 1 1][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11493 0 0]I... I really enjoy getting coffee with you like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]I kind of wish my time with you would just last forever...[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]We chatted for a while longer before[n]I decided to go back to the dorm.[n][uf 1 1][e]

