[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 0 0 0]Aragaki is working silently...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I tended the rooftop planters with Aragaki...[n][uf 1 1][e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hope they don't taste too bitter...[n][uf 1 1][e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]If these temperatures keep up, they'll probably get pretty big.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]That's probably enough fertilizer. The rest is up to the weather.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Let's head back now.[n][uf 1 1][e]

