[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]You came... Just like we agreed.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Do you know why I called you here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]You probably have an idea, since you skipped the operation for it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Two years ago today... on October 4th.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0]That was the day my mom died here.[n][uf 1 1][e]

[msg MSG_003_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]They called it a car accident... But it wasn't.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 3 25 25]I saw the whole thing... I saw my mom get killed.[n][uf 1 1][e]

[msg MSG_003_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 17 8 2 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 9 0 0]YOU murdered her![n][uf 1 1][e]

[msg MSG_005_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Since then, not one good thing has happened... Just being alive is torture.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 12 0 0]And all I get from people is sympathy, no matter where I go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]What's the point of living like this...?[n][uf 1 1][e]

[msg MSG_006_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 14 0 0]I've even thought about killing myself... But, I wouldn't be able to face Mom like that.[n][uf 1 1][e]

[msg MSG_006_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 15 0 0]That's why I vowed to live until I found her killer—YOU![n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 16 0 0]I once heard you say you wanted to forget what you did on that day...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]So, when I realized it was a full moon today, I knew I had to confront you.[n][uf 1 1][e]

[msg MSG_007_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Today, Mom is with me.[n][uf 1 1][e]

[msg MSG_007_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 19 0 0]I'll make you remember what you did to her... I'm gonna kill you![n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 0 0 0 20 0 0]......[n][uf 1 1][e]

[msg MSG_009_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Do it.[n][uf 1 1][e]

