[msg MSG_000_0_0 [Preachy Teacher]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 318]There's a saying, "He who hunts two hares at once will catch neither."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 318]That means a student like you who's always trying to do two things at once will—[n][uf 1 1][e]

[msg MSG_000_5_0 [Smirking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 319]That's something you did too, right, teach?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 319]Last year, you cheated on two girls you met at a group date, and it ended up a disaster...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 319]And in the end, both of them ditched you... Don't worry, I wouldn't do something so lame![n][uf 1 1][e]

