[msg MSG_000_0_0 [Somber Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 302]I never expected anything like this to happen to someone from this school...[n][uf 1 1][e]

[msg MSG_001_0_0 [Somber Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 302]That girl who collapsed is in my class...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 302]I heard she would run away from home and stay out all night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 302]Maybe she got caught up in something bad...[n][uf 1 1][e]

