[msg MSG_000_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Since you just transferred here, do you find yourself getting lost inside the school?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I do.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]

[msg MSG_002_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]I don't blame you... Where do you need help getting to?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Sports club rooms.[e]
[uf 0 5 65278][uf 2 1]Culture club rooms.[e]
[uf 0 5 65278][uf 2 1]Student council room.[e]
[uf 0 5 65278][uf 2 1]The faculty office.[e]

[msg MSG_004_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Leave the classroom and go down the stairs to the right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Then, go through the double doors on your right-hand side and head straight.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Leave the classroom and go down the stairs to the right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]The culture clubs like the art club room will be right there.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]It's located right across the hall from this room.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]Leave the classroom and go down the stairs to the left.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]While facing the shoe lockers, go right to enter the hallway where the faculty office is located.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kind-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]But walking all the way to each location is quite a hassle, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 307]If only we could get somewhere with the push of a button, just like in games nowadays.[n][uf 1 1][e]

