[msg MSG_000_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]*sigh* He's sooo hot...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Wait, why am I telling you this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Well, whatever. You have to admit, he is a hottie.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]*sigh*[n][uf 1 1][e]

[msg MND_001_5_0]
[uf 0 5 65278][uf 2 1]The fawning student continues to sigh...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He's different than I imagined...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]From what I can tell, he has no personality.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Eww! Did you see that!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]That guy over there just picked his nose and then... flung it everywhere![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]So gross...[n][uf 1 1][e]

[msg MSG_004_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]That guy there... Isn't he acting funny?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, he is.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]

[msg MSG_006_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Yeah... I thought he seemed weird...[n][uf 1 1][e]

[msg MSG_007_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Really? Well, if you ask me, he seems weird...[n][uf 1 1][e]

[msg MSG_008_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Uh-oh... That guy's staring at me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]I hope he's not going to ask me out...[n][uf 1 1][e]

[msg MSG_009_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]You really have to be careful who you date nowadays.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]They say love is blind, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]There's no way I could ever date a guy like that.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1]The first thing I do when I get to school is look for him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Just seeing him makes me smile.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]*sigh* What should I do...? How should I express my feelings for him...?[n][uf 1 1][e]

[msg MSG_011_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]I know I can't go on without talking to him, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Maybe I would be satisfied just staring at him from afar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]*sigh* What should I do...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Oh my god! Did you see that!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He just threw a rock at a bird resting on that branch![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]That's so cruel...[n][uf 1 1][e]

[msg MSG_013_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1]Did you see that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He just threw a rock at a bird resting on that branch![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]If he keeps that up, he might get possessed by evil spirits...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]But that's just a rumor, so probably not.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Did you just see that!? Look at that guy over there![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He just spit his gum into the fountain![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]So disgusting... What is he thinking!?[n][uf 1 1][e]

[msg MSG_015_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]That guy who's been following me... Is he blushing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Umm, am I in trouble...?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Is this what they call "disillusionment"? I didn't realize he was that kind of guy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]I'm gonna stop following him. This is so disappointing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]The last thing I need is another guy like him.[n][uf 1 1][e]

[msg MSG_017_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Is that guy who keeps following me around gonna talk to me or what?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]No normal guy would wait this long to talk to a girl, right?[n][uf 1 1][e]

[msg MSG_018_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]See that guy over there? I think he's been following me around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]What should I do in a situation like this?[n][uf 1 1][e]

[msg MSG_019_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Hmm... It feels like someone's watching me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Is it just me...?[n][uf 1 1][e]

[msg MSG_020_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]God! This guy following me around just won't quit![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He must be one stubborn guy to follow anyone around this much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]He'll probably be a detective or something when he grows up.[n][uf 1 1][e]

[msg MSG_021_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Huh... I still get the sense that someone's following me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]Hey, there's someone over there. Hm, that guy looks familiar...[n][uf 1 1][e]

[msg MSG_022_0_0 [Fawning Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]You see that guy over there, right? You know, the one who's been following me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 301]I don't know how to get rid of him... So I guess I'll just let him do whatever it is he's doing.[n][uf 1 1][e]

