[msg MSG_000_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]See that weirdo over there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Isn't he a victim of those mysterious incidents...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]It's so creepy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Hey, did you come for the arcade?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]If you wanna know about the games, I can tell you all about 'em.[n][uf 1 1][e]

[msg MSG_001_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Are you here for the arcade?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]If you wanna know about the games, I can tell you all about 'em.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]Nah.[e]

[msg MSG_003_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Today, you can play either High School of Youth or Punch Boxer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]You can learn about dating in High School of Youth, so you can increase your Charm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Punch Boxer is pretty self-explanatory. You'll increase your Strength if you play it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]That about covers it.[n][uf 1 1][e]

[msg MSG_004_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Today, you can play either House of the Deceased or Real Wheel Racer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]House of the Deceased is pretty scary... You'd increase your Courage if you can stand it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Real Wheel Racer requires nimble finger work, so it increases your Agility.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]That about covers it.[n][uf 1 1][e]

[msg MSG_005_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]You can play You're the Answer today, or try Edgar's House of Fortunes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]You're the Answer is pretty difficult... It's a good way to increase your Academics.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I'm not sure what Edgar's House of Fortunes does, but I hear you gain some kinda Magic powers...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Well, that about covers it.[n][uf 1 1][e]

[msg MSG_006_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Today, you can play either Punch Boxer, Real Wheel Racer, or Edgar's House of Fortunes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Punch Boxer is pretty self-explanatory. You'll increase your Strength if you play it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Real Wheel Racer requires nimble finger work, so it increases your Agility.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I'm not sure what Edgar's House of Fortunes does, but I hear you gain some kinda Magic powers...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]The games are pretty addicting! You can end up pumping in lots of coins, but you get something in return.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]My strategy is to play all the games and improve myself.[n][uf 1 1][e]

[msg MSG_008_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Arcade games only start when you put in a coin, not like the home consoles where you turn them on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I didn't realize how they worked until my friend told me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]What about you? You got any friends who help you out like that?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I do.[e]
[uf 0 5 65278][uf 2 1]I don't need friends.[e]

[msg MSG_010_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]That's cool. Be nice to them.[n][uf 1 1][e]

[msg MSG_011_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]You sure, man?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I mean, what if you come up against a problem you can't solve on your own?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]No one's perfect... You should have friends who can help, in case you get into a jam.[n][uf 1 1][e]

[msg MSG_012_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]There are more of those people every day... They're so creepy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Maybe I should go on home...[n][uf 1 1][e]

[msg MSG_013_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Let's see... To start the game, insert one coin...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Control it using the two buttons, and... What are you looking at?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I'm not just reading the directions, I'm carefully planning my moves.[n][uf 1 1][e]

[msg MSG_014_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I came into the arcade the other day, and I saw this guy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]He was tossing a ball up in the air and catching it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I wonder what that was about...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]It didn't look like any kind of toy or prize they offer here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Maybe I should ask him next time I see him.[n][uf 1 1][e]

[msg MSG_015_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I saw a girl in a white, frilly dress the other day, in front of the station...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Don't get me wrong, I love that kind of outfit—I've got tons of figures dressed that way in my room—but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]In real life, I think it's better to dress casually...[n][uf 1 1][e]

[msg MSG_016_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Hey, I saw that guy tossing the ball in the arcade again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I walked up to him so I could ask what the ball was...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]But he just glared at me over his sunglasses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Then he walked out of the arcade without another word.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Man, he's scarier than I thought...[n][uf 1 1][e]

[msg MSG_017_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]My friend knows a lot about that revenge website. Like, a little TOO much, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]It makes me wonder if he's been using the site to take revenge...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]He kept bringing it up, so I came out and said, "Isn't that just a stupid rumor?"[n][uf 1 1][e]

[msg MSG_018_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]This machine has some peculiar quirks...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]The crane's claw is close to the player, so the opening and closing motions are limited...[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]How'd you learn that?[e]
[uf 0 5 65278][uf 2 1]Okay.[e]

[msg MSG_020_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]One of the employees secretly told me. It seems they already consider me a regular.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Maybe you should get to know the guys here. You might learn something.[n][uf 1 1][e]

[msg MSG_021_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I guess I can't force people to care...[n][uf 1 1][e]

[msg MSG_022_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]There's more of those creeps again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I know they'll start disappearing again soon, but it's still creepy...[n][uf 1 1][e]

[msg MSG_023_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Man, that one was close...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I never miss now, but somehow, I still can't get it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]The claw grabs the prize, but it'll fall before it reaches the hole, or the prize just gets stuck.[n][uf 1 1][e]

[msg MSG_024_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Hey, guess what! I finally got the prize![n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Congrats.[e]
[uf 0 5 65278][uf 2 1]Whatever.[e]

[msg MSG_026_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I basically just lucked into it, but I'm still psyched.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I'll keep training until I can get a prize even without luck![n][uf 1 1][e]

[msg MSG_027_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Dude... That was uncalled for![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]If you keep acting like that, you'll end up with no friends.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Mark my words, man.[n][uf 1 1][e]

[msg MSG_028_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I can grab it, but I can't win... This can't be a coincidence.[n][uf 1 1][e]

[msg MSG_029_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I asked my friend if there's some trick to it, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]He gave me the cold shoulder and told me to never talk to him again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I wonder if I said something to piss him off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]What should I do...? I guess everyone has a sore spot that you shouldn't mess with...[n][uf 1 1][e]

[msg MSG_030_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Hmm... I can't get the timing down anymore...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I'm so worried about my friend that I can't concentrate.[n][uf 1 1][e]

[msg MSG_031_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I tried reaching out to my friend again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I can't just give up after being rejected once, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]If I keep trying, I'm sure I can restore our friendship.[n][uf 1 1][e]

[msg MSG_032_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I managed to make up with my friend! Now I can concentrate on this...[n][uf 1 1][e]

[msg MSG_033_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]It's probably because of the holiday season, but it's so noisy here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]I can't concentrate... M-My coins...![n][uf 1 1][e]

[msg MSG_034_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]When I get a little better, I'm gonna come here with my friend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]He's been acting weird lately... All talking about how "the end is nigh" and stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]What he needs is to kick back and relax, here in the arcade...[n][uf 1 1][e]

[msg MSG_035_0_0 [Gamer Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]Everyone's talking about how the end is coming, but I don't care.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]All I care about now is this game! I'm getting a lot better at it! I can win a prize almost every time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 323]My ultimate goal: to complete my collection![n][uf 1 1][e]

