[msg MSG_000_0_0 [Flustered Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Oh man, this is bad... Where did I drop my student handbook...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Do you need something? I'm a little busy now... Hey, wait, that handbook you're holding...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Can I see that student handbook? I was just looking for mine...![n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]This might be it.[e]
[uf 0 5 65278][uf 2 1]You're mistaken.[e]

[msg MSG_002_0_0 [Flustered Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]It IS mine! Phew... Thanks, you saved me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]...Oh yeah, as a thank-you, here, take this.[n][uf 1 1][e]

[msg MSG_002_5_0 [Flustered Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]I got this for free when I was shopping at Aohige Pharmacy, but I don't own a cat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Anyway, if you have no use for it, just give it to one of the cats at the strip mall.[n][uf 1 1][e]

[msg MSG_003_0_0 [Flustered Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]I see... Sorry for demanding to see your stuff all of a sudden...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Oh man, where did I drop it...? I gotta try to remember...[n][uf 1 1][e]

[msg MSG_004_0_0 [Relieved Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]Thanks again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 324]If you have no use for that, just give it to one of the cats at the strip mall.[n][uf 1 1][e]

