[msg MSG_000_0_0 [Club-Ditching Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]I hear that, starting on the 23rd, some athletic teams will be recruiting new members...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]...Actually, it's just the track and field team. I guess the others are full.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]If you're interested in joining, why don't you go check it out?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]From the classroom, go down the stairs to the right and eventually you'll find it.[n][uf 1 1][e]

[msg MSG_001_0_0 [Club-Ditching Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]Looks like some of the athletic teams are recruiting new members...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]...Actually, it's just the track and field team. I guess the others are full.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]If you're interested in joining, why don't you go check it out?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 306]From the classroom, go down the stairs to the right and eventually you'll find it.[n][uf 1 1][e]

