[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4010 0 0]Heh... Are you having a hard time, Koromaru? Just keep at it. I know you can find it.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]We're playing a little game I learned from Yamagishi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Koromaru has to find a specific object by scent alone. In a way, it's like treasure hunting.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]That sounds like fun.[e]
[uf 0 5 65278][uf 2 1]He's like a police dog.[e]
[uf 0 5 65278][uf 2 1]You're not taking him for a walk?[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4046 0 0]Oh? You think so, too? Truth be told, I've found that hiding the target is rather fun as well.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4074 0 0]Apparently, police dogs undergo similar training for scent tracking as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Considering how talented Koromaru is, perhaps he'd do quite well in that field.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 3 0 65535 4060 0 0]I wish I could, but there's only so much space we have to work with.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0]That's why I'm testing different ways to enrich his mind while we're trapped indoors.[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 52 65535 0 0]Grrr...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Growl all you want. I'm not telling you where it is.[n][uf 1 1][e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 3 0 65535 8003 0 0][uf 4 25 9]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0]*whine*[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]But he's so pitiful...[e]
[uf 0 5 65278][uf 2 1]Don't give up![e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4032 0 0]Don't give into the puppy eyes, Aigis. We both know Koromaru is very much capable.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4026 0 0]Precisely. I know you can do this, Koromaru.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]I admit, I did make this round harder. The scent is weaker, and there are more dead ends to throw him off the trail.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]Not only that, but I also hid it in an elevated location that's difficult for him to access.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]That seems excessive...[e]
[uf 0 5 65278][uf 2 1]Koromaru-san will pull through.[e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4059 0 0]Amada and Yamagishi said the same thing.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4024 0 0]Agreed. I prepared this puzzle bearing that in mind.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 3 0 65535 4081 0 0]In the face of a challenge, I believe what's most important... is upholding respect.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]From where I stand, disregarding one's weakness is neither kindness nor fairness.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]In actuality, it's overconfidence, plain and simple—and no different from looking down on the opponent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0]That's why I never hold back, no matter who or what I'm up against.[n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru's Voice]]
[uf 0 5 65278][uf 2 1]Arf![n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4141 0 0]Yes! Très bien! I never doubted you for a moment, Koromaru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 4 23 0 1 0 25 25]I'm fortunate to be surrounded by such reliable friends... Perhaps that's why I can afford to be more optimistic.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]After her game with Koromaru-san,[n]Mitsuru-san seems to have[n]reaffirmed her principles...[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 3 0 65535 4065 0 0]I'll have to ramp up the difficulty as well so that you won't find the next one so quickly.[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 52 65535 0 0]Arf![n][uf 1 1][e]

