[msg MSG_701_000 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]I've never seen one this big before, but there's no time... We have to end this, now![n][uf 1 1][e]

[msg MSG_701_001 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 2 65535 0 0]Ngh... It called in reinforcements! Just what we needed...[n][uf 1 1][e]

[msg MSG_701_2_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 1 0 2 1 0 5]It sped up the monorail!?[n][uf 1 1][e]

[msg MSG_701_2_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 65535 50 0 0][uf 3 1 1 0 2 2 0 5]There's even less time until impact now! Hurry![n][uf 1 1][e]

[msg MSG_701_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]Hurry how!? Arrgh, we gotta take it down soon...![n][uf 1 1][e]

[msg MSG_701_2_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]The monorail is going even faster now! You're running out of time![n][uf 1 1][e]

[msg MSG_701_3_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]Oh man, we're in deep shit here...![n][uf 1 1][e]

[msg MSG_701_1_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 1 0 2 3 0 5]Hey! Are you all right!? Say something![n][uf 1 1][e]

