[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Today, I'd like to make a snack food that would pair well with tea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]That said, I'm not terribly well-versed in the art of cuisine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]So, I'm hoping to make some simple karume-yaki. Did your teachers ever show you how to make it?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I think so.[e]
[uf 0 5 65278][uf 2 1]I don't remember.[e]
[uf 0 5 65278][uf 2 1]Karume-what?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Excellent. Then I don't need to explain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 5 0 0]All right, let's get started.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]Well, you take baking soda—also known as sodium bicarbonate—and when it undergoes thermal decomposition...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]Actually, it would be faster to show you while we work. Let's get started.[n][uf 1 1][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0]Karume-yaki is a confectionary that was passed down from Portugal during the Sengoku period.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]"Karume" derives from the Portuguese word "caramelo," or "caramel" in English...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]Well, it might be faster if you just see for yourself. Let's get started.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0]Temperature control is key. We want to turn off the heat right before it hits 130 degrees Celsius...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 4 25 25]Oh, we should keep things moving. Let's put the sugar in the ladle first...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I cooked karume-yaki with Mitsuru.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]What a nostalgic flavor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]It may not require hours in the kitchen, and the taste isn't particularly complex...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 15 0 0]But I'm quite fond of these. And more than anything, it's nice that we can make it ourselves.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0]You know... when I saw this for the first time, I thought it was like magic.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 17 0 0]I've tried making it myself a number of times, but I ended up burning it on every attempt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]I guess you could call it a bittersweet memory. But I didn't give up—I continued practicing.[n][uf 1 1][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]And that's finally led to our success today. What do you think?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]That's so inspiring.[e]
[uf 0 5 65278][uf 2 1]Not much of a cook?[e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 5 13 4 1 5]Hearing you say that makes me glad to have shared it.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 159 65535 0 0][uf 3 1 1 0 0 21 0 0]You didn't know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25][uf 5 13 4 1 5]In any case, now that I've grasped how to do it, I won't forget so easily.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 23 0 0]Back home, there were plenty of opportunities to host formal dinners and tea parties...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 24 0 0]But I never considered it particularly admirable to have someone else prepare the extravagant dishes.[n][uf 1 1][e]

[msg MSG_011_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 25 0 0]Doing the cooking myself also allows me to talk with you like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]And isn't that sort of familiarity the key to understanding each other better?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 27 0 0]I think... this might have been what I was missing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]Instead of complaining about being difficult to approach, I needed to create an opportunity for change.[n][uf 1 1][e]

[msg MND_012_3_0]
[uf 0 5 65278][uf 2 1]By cooking this nostalgic dish,[n]Mitsuru seems to have learned[n]something new about herself...[n][uf 1 1][e]

[msg MSG_012_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 29 0 0]It's fascinating, the kind of things you learn by simply inviting someone over for tea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 0 25 25]Thank you, [uf 4 1]. I hope we can talk again like this sometime.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 31 0 0]Oh, right. I had a favor to ask.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 32 0 0]There's still some sugar and baking soda left. Do you think you could help me make another batch?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 1 25 25]Karume-yaki keeps for a long time. This could be a good chance to make some for the others.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]After making karume-yaki with[n]Mitsuru, I went back to my room.[n][uf 1 1][e]

