[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1094 0 0]Ohhh! That makes so much more sense now.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]Oops, sorry. Sometimes I think out loud when I read. Um... What're you reading, Aigis? What's it about?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Mechanical engineering.[e]
[uf 0 5 65278][uf 2 1]Physiological psychology.[e]
[uf 0 5 65278][uf 2 1]It's a shojo manga.[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1071 0 0]Oh, so like... So you can learn how your body works or something? That's cool.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1071 0 0]"Physio"... Uh, the "psychology" part means it has to do with the mind and mental health and stuff, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0]I didn't know you were into that kinda thing.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1107 0 0]Really? I never would've thought you'd be into that, given the other kinds of stuff you read.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 3 0 65535 1001 0 0]This dorm sure has all kinds of books, huh? Everything from casual manga to super complicated stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]When we picked up this book in the Abyss of Time... It reminded me of this place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0]And of how I never really read any of the books here...[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 3 0 65535 1077 0 0]So I kinda thought... Maybe now's a good time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 4 23 0 1 1 25 25]You gotta make time to take breaks once in a while, right? Like when we watched that show together.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1061 0 0]A lot of the others used to read here, right? Fuuka, Mitsuru-senpai... Him, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]It was kinda relaxing even just watching them from a distance. But I could never bring myself to just walk up and ask to join them...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0]But yeah... When they took breaks, they were definitely getting something out of it.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1131 0 0]So, I guess I'm trying to follow their example or something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 4 23 0 1 3 25 25]That probably sounds kinda dumb, huh?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Not at all.[e]
[uf 0 5 65278][uf 2 1]It's good to follow examples.[e]
[uf 0 5 65278][uf 2 1]You can join me anytime.[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1093 0 0]Oh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 4 23 0 1 1 25 25]Um... Thanks.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Haha, you sounded so serious just now. But I guess that's not exactly out of character for you.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 3 0 65535 1098 0 0]Oh, uh... Okay, thanks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 4 23 0 1 1 25 25]I wasn't really expecting someone to just come right out and say it, haha.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 52 65535 0 0]So, anyway... Yeah, let's just take it easy for a little while longer.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Yukari-san's voice sounds[n]calm, yet empowered...[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1116 0 0]But that means we're gonna have to work twice as hard later to make up for it.[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Of course.[e]
[uf 0 5 65278][uf 2 1]Do we have to...?[e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Yeah. We'll have more time to relax after we get out of here.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 3 0 65535 1123 0 0]Come on, get with the program! We'll have plenty of time to relax after we get out of here.[n][uf 1 1][e]

