[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 1 0 0]Koro-chan, shake![n][uf 1 1][e]

[msg MSG_001_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 2 0 0]Arf![n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Oooh, he did it! What a smart dog.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh, welcome back, [uf 4 1]-kun.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Hey there![n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]What's with the dog?[e]
[uf 0 5 65278][uf 2 1]Can I pet him?[e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]He was passing by just a little while ago.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 7 0 0]Go on, Koro-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 8 0 0]You know how to say hi, right?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Sure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 10 0 0]Go on, Koro-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 11 0 0]You know how to say hi, right?[n][uf 1 1][e]

[msg MSG_009_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 12 0 0]Woof![n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]His name's Koromaru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 14 0 0]I've seen him sitting by the steps of the shrine.[n][uf 1 1][e]

[msg MSG_011_0_0 [Passing Housewife]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 10]Oh, this dog still goes on walks all by himself?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 16 0 0]What do you mean?[n][uf 1 1][e]

[msg MSG_013_0_0 [Passing Housewife]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 10]He used to belong to the priest at the Naganaki Shrine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 10]Every afternoon, the two of them went this way for a walk.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 19 0 0]So that's what he was doing here.[n][uf 1 1][e]

[msg MSG_015_0_0 [Passing Housewife]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 10]That is, until the priest passed away.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 21 0 0]He passed away?[n][uf 1 1][e]

[msg MSG_017_0_0 [Passing Housewife]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 10]Oh, you haven't heard the story?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 10]I think it was about six months ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 10]The priest was hit by a car while walking his dog. He didn't survive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 10]Ever since then, that dog has continued to go on walks, always stopping to sit by the site of the accident.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 10]But he refuses to let anyone take him in. Why, just the other day, my son—[n][uf 1 1][e]

[msg MND_018_0_0 [Fuuka Yamagishi]]

[msg MSG_019_0_0 [Passing Housewife]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 10]Oh my goodness, look at the time! I must be going! My son will be home soon.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 28 0 0]Aww, you're such a loyal dog! Good boy![n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 1 65535 0 0][uf 3 1 1 0 0 29 0 0]Huh? Is he...?[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 30 0 0]What's wrong?[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 31 0 0]Oh, nothing. Sorry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 32 0 0]More importantly, isn't the chairman coming today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 33 0 0]We should probably go get ready.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 34 0 0]Yeah, you're right. See you later, Koro-chan.[n][uf 1 1][e]

[msg MSG_025_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 35 0 0]Arf![n][uf 1 1][e]

