[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Amada seems calm.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]We passed the time[n]drinking coffee together...[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Sometimes adding milk and sugar is nice. But I usually take it black, of course.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0]If you feel like meeting up for coffee again, just let me know.[n][uf 1 1][e]

