[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I'm doing better today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I know it probably looked dire last time, right? Sorry if I scared you.[n][uf 1 1][e]

[msg MSG_000_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'd been reading a book before we met that day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I guess I got so absorbed in it that I didn't realize how cold the wind was.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]...Do you enjoy reading books?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I'd say so.[e]
[uf 0 5 65278][uf 2 1]No, I don't.[e]
[uf 0 5 65278][uf 2 1]It depends on the book.[e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 20 15 117]I see... That's something we have in common, then.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 20 5 117]I see... I suppose I didn't like them much either, back when I was healthier.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 20 5 117]Heh... I'll admit I'm somewhat picky, myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 117 0 25 25]A terrible book is a terrible waste of time. And there's no more grievous sin than that.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Nowadays, reading books is all I do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]I find that they give me a way to escape everything else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I can just get lost in the book's private world...[n][uf 1 1][e]

[msg MSG_005_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]...Do you read books all the way through?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Of course I do.[e]
[uf 0 5 65278][uf 2 1]I stop if I get bored.[e]

[msg MSG_007_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, you do...? I don't like to see them end.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 5 13 20 5 117]Oh, do you...? I don't usually reach the end either, although I think our reasoning differs.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]The more engaging a story is, the more I want to get lost in it, but... I'm always afraid to finish it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]...Because once I finish the story, I'll have to come back to reality.[n][uf 1 1][e]

[msg MSG_009_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]This inescapable body of mine...[n][uf 1 1][e]

[msg MSG_010_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Heartwarming stories, filled with hope...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Those are the kinds of books I like to read.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 117 1 25 25]They give me a little solace, when I have to come back to the real world.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Kamiki smiled weakly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_012_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]It looks like the sun is already setting... Time is so ruthless...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 117 1 25 25]I hope we have another chance to talk.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

