[msg MSG_000_0_0 [Unemotional Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 684]You're taking orders?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 684]Okay, um... Can I have a margarita?[n][uf 1 1][e]

[msg MSG_001_0_0 [Unemotional Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 684]What? You forgot my order already? Seriously?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 684]I want a margarita.[n][uf 1 1][e]

