[msg MSG_000_0_0 [Active Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Are you trying to hit on me? Oh, you're just taking orders... *sigh*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]I'll have a Screwdriver.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Wait, make that a margarita.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Actually, scratch that. I'll go with my original order.[n][uf 1 1][e]

[msg MSG_001_0_0 [Active Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Are you trying to hit on me this time? Oh, you're just checking my order...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]I'll have a Screwdriver.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Wait, make that a margarita.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 685]Actually, scratch that. I'll go with my original order.[n][uf 1 1][e]

