[msg MSG_000_0_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]"How's it going, [uf 4 1]? I don't know your address so I'm sending this to the school."[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Hayase's firm handwriting fills the page...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can almost see Hayase's face.[n][uf 1 1][e]

[msg MSG_002_0_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]"I'm doing good. I'm starting to get used to the job, too."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]"But the real reason I'm writing is because of track."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]"Before, I'd pretty much given up hope of ever continuing."[n][uf 1 1][e]

[msg MSG_002_3_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]"Except there was a part of me that refused to let it go."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]"I don't care what it sounds like—track and field was my whole life!"[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I can tell Hayase was in a good[n]mood when he wrote that.[n][uf 1 1][e]

[msg MSG_004_0_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]"I guess the factory manager realized what's up, and he wants to help me out."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]"We're gonna make a track team here!"[n][uf 1 1][e]

[msg MSG_004_1_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]"Well, I call it a team, but it's really just a few guys at the factory."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]"We practice after work and sometimes on our days off."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]"The other day, we did endurance swimming at Lake Biwa. We've even climbed Mt. Hiei."[n][uf 1 1][e]

[msg MSG_004_2_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]"We don't have fancy equipment like before, so we're not as efficient. But I'm still having a blast."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]"Most of the guys are just in it for fun, so I don't really get to do any serious training."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]"But I guess it'll even the playing field for them."[n][uf 1 1][e]

[msg MSG_004_3_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]"How about you? You're still at it, right?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]"I'm sure you're just gonna keep getting better and better."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]"It's weird how badly I wanna see you improve."[n][uf 1 1][e]

[msg MSG_004_4_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]"Look, [uf 4 1]."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]"One day... you and I are gonna go at it again."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]"And if I'm gonna be a good rival, then I've got a lot of work to do."[n][uf 1 1][e]

[msg MSG_004_5_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]"It feels nice having a goal to work toward."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]"Almost forgot what it was like..."[n][uf 1 1][e]

[msg MSG_004_6_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]"Oh yeah, and my mom's getting better! She's in a long-term care facility with lots of fresh air."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]"My relatives and friends come by the house, so my siblings are in good hands, too."[n][uf 1 1][e]

[msg MSG_004_7_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]"Things have been pretty great these days."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]"I feel like I can take care of the people who matter to me. It's really fulfilling."[n][uf 1 1][e]

[msg MSG_004_8_0 [Letter from Hayase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]"And I get to feel that way because of you."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]"So thank you."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]"Can't wait to see you again, [uf 4 1]!"[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]The letter ends there...[n][uf 1 1][e]

