[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]So the other day I recommended the novel I'm reading to a classmate...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I don't talk to her much, but at the time we were discussing a movie we'd both seen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]She wasn't too keen on the recommendation and turned me down, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]It was because the series looked hard to get into. There are so many volumes.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]She's missing out.[e]
[uf 0 5 65278][uf 2 1]Can't really blame her.[e]
[uf 0 5 65278][uf 2 1]It's about presentation.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]If she just gave it a chance, I know she would see how interesting it is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]The basic premise is about journeying to other planets, and even that by itself already sounds intriguing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]And the writing is so unique and poetic. I can't help but get sucked in...[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I know. I'd probably feel the same way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]It's hard for someone to pick up a series that's been going on for so long.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 6 0 25 25]Presentation? You mean like, talking in front of a group of people...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Hmm, interesting... So you think I should have slides or something to go with it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I could probably show them in a room with a projector, or— Wait, that's not what you meant, is it?[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 6 0 25 25]...Recommending something to someone is a really tricky thing, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Well, thank you anyways, [uf 4 1]-kun. I appreciate you showing interest in that book.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Okay, I think I'll read a little further myself.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Whew... I finished the whole thing.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 0 1 1 0][n]have improved thanks to the[n]skillful expression in the writing...[n][uf 1 1][e]

[msg MSG_016_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 3 1 6]Time flies by so quickly. Let me know your thoughts on it next time.[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Well then, good night.[n][uf 1 1][e]

