[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 1 0 0]...Is it just me, or is the air conditioning in here too high? I feel a little light-headed...[n][uf 1 1][e]

[msg MSG_000_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 2 0 0]I haven't been feeling well lately... I couldn't even finish my lunch today.[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 3 0 0]I think I may have caught a cold...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 4 0 0]I'm sorry, but do you think we could go to the pharmacy?[n][uf 1 1][e]

