[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]Aigis, do you have a minute? I wanted to ask you something.[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Oh, um... Should I leave?[n][uf 1 1][e]

[msg MSG_001_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]...I'll come back later, then.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0]No, no, I didn't mean it like that. Actually, I'd like your opinion, too, Metis.[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0]No, wait! I'd actually like your opinion, too, Metis.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Have I, um... Have I been doing a good job providing support? It's been a while, so I'm not that confident anymore...[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]You're doing as well as ever.[e]
[uf 0 5 65278][uf 2 1]I can't really say...[e]
[uf 0 5 65278][uf 2 1]You should be more confident.[e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5049 0 0]Really...? Well, if you say so...[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]Because it's too hard to say it out loud...? I'm so sorry, Aigis. I didn't mean to pressure you.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5094 0 0]Yeah... You're right. I need to get my act together.[n][uf 1 1][e]

[msg MSG_008_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]...I don't understand. Why do you lack confidence in your area of expertise?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Even if we had said that your performance was flawless, you still wouldn't have believed us.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 3 0 65535 5098 0 0]Huh...? Y-You think so? I didn't mean that at all...[n][uf 1 1][e]

[msg MSG_010_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Aren't you in the support role because you wanted it?[n][uf 1 1][e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30081 0 0]Take me, for example. I'm here because I want to protect my sister![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]And I don't second-guess my decisions.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Hehe, wow... You're so cool, Metis.[n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Huh...? Isn't this just normal?[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5084 0 0]Well... It's hard for me to have as much confidence as other people would. I see what you mean, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 4 23 0 1 1 25 25]And the way you're so sure of yourself is actually really inspiring.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5025 0 0]I doubt I can change right away, but... I do want to be more confident in myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]I need some time to think about what it is I want to accomplish.[n][uf 1 1][e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Don't make this weird... I was just saying what anyone else would. Right, Sister?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]You're truly inspirational.[e]
[uf 0 5 65278][uf 2 1]There's no need to be shy.[e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30107 0 0]Y-You really think so? Ehehe...[n][uf 1 1][e]

[msg MSG_019_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30105 0 0]I'm not, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]...Okay, maybe just a little bit.[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5043 0 0]Regardless, thank you both for your help. Rest assured, you can count on me for our next trip![n][uf 1 1][e]

[msg MSG_021_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0]Wh-What!? You're not going to outclass me! Just watch, Sister—I'll handle everything myself next time![n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]It took a joint effort between[n]Fuuka-san and me to get Metis[n]to calm down.[n][uf 1 1][e]

