[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]For as long as life exists, so too shall death.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The flame of life burns bright,[n]stoked by pain and hardship.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Now with the light of life snuffed out,[n]    the clock has come to a stop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]What is the meaning of life?[n]Alas, the answer shall remain forever out of grasp...[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Game Over[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Resume play?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Lower difficulty level [uf 4 26 10 0][e]
[uf 0 5 65278][uf 2 1]Retry battle [uf 4 26 11 0][e]
[uf 0 5 65278][uf 2 1]Start from arena entrance [uf 4 26 12 0][e]
[uf 0 5 65278][uf 2 1]Return to title screen [uf 4 26 14 0][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Lower difficulty level [uf 4 26 10 0][e]
[uf 0 5 65278][uf 2 1]Retry battle [uf 4 26 11 0][e]
[uf 0 5 65278][uf 2 1]Start from Desert of Doors [uf 4 26 13 0][e]
[uf 0 5 65278][uf 2 1]Return to title screen [uf 4 26 14 0][e]

[msg SYS_004_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]You will return to the entrance of the arena and lose this visit's progress, except for the change in difficulty. Are you sure?[n][uf 1 1][e]

[msg SYS_005_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]You will return to the Desert of Doors and lose this visit's progress, except for the change in difficulty. Are you sure?[n][uf 1 1][e]

[msg SYS_006_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]You will return to the title screen and lose all progress made since you last saved the game. Are you sure?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Yes[e]
[uf 0 5 65278][uf 2 1]No[e]

[msg SYS_009_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]If you change the difficulty from Heartless, [uf 0 1 2]you cannot change it back to Heartless later[uf 0 1 27]. Do you still want to change to Hard difficulty?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Lower the difficulty by one level.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Start over from the beginning of the battle.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Start again from the entrance to the arena.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Start again from the Desert of Doors.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Return to the title screen.[n][uf 1 1][e]

[msg SYS_012_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]The difficulty is currently set to [uf 0 1 2]Easy[uf 0 1 27]. Would you like to change it to [uf 0 1 2]Peaceful[uf 0 1 27]?[n][uf 1 1][e]

[msg SYS_011_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]The difficulty is currently set to [uf 0 1 2]Normal[uf 0 1 27]. Would you like to change it to [uf 0 1 2]Easy[uf 0 1 27]?[n][uf 1 1][e]

[msg SYS_010_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]The difficulty is currently set to [uf 0 1 2]Hard[uf 0 1 27]. Would you like to change it to [uf 0 1 2]Normal[uf 0 1 27]?[n][uf 1 1][e]

[msg SYS_008_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]The difficulty is currently set to [uf 0 1 2]Heartless[uf 0 1 27]. Would you like to change it to [uf 0 1 2]Hard[uf 0 1 27]?[n][uf 1 1][e]

[msg SYS_016_0_0]
[uf 0 5 65278][uf 2 1]The difficulty has been changed to [uf 0 1 2]Peaceful[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_021_0_0]
[uf 0 5 65278][uf 2 1]The difficulty has been changed to [uf 0 1 2]Easy[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_022_0_0]
[uf 0 5 65278][uf 2 1]The difficulty has been changed to [uf 0 1 2]Normal[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_023_0_0]
[uf 0 5 65278][uf 2 1]The difficulty has been changed to [uf 0 1 2]Hard[uf 0 1 27].[n][uf 1 1][e]

