[msg MSG_000_0_0 [(SE) Gang-Looking Person]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]So then, I took it apart and put it somewhere...[n][uf 1 1][e]

[msg MSG_001_0_0 [(SE) Heavily Made-Up Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Gahahahaha![n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I want to go to a bar called "Que Sera Sera." It's down this way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...I was thinking of getting Mitsuru-san a gift.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 8 3 25 25]And I heard I might be able to buy what I'm looking for at the bar...[n][uf 1 1][e]

[msg MSG_003_0_0 [(SE) Dull-Looking Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Hey, what's up with them?[n][uf 1 1][e]

[msg MSG_004_0_0 [(SE) Fierce-Looking Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Who knows? What's a kid doin' here?[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Maybe it's too dangerous. But supposedly, it's only open at night...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Let's check it out.[e]
[uf 0 5 65278][uf 2 1]Just stay close.[e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 8 1 25 25]Okay![n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Hmm, is it a bit further down?[n][uf 1 1][e]

[msg MSG_009_0_0 [Fierce-Looking Guy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1001]Now there's little kids running around...? It's become so wholesome here.[n][uf 1 1][e]

[msg MSG_010_0_0 [Gang-Looking Person]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1002]Hey, it's past your bedtime, little boy![n][uf 1 1][e]

[msg MSG_011_0_0 [Heavily Made-Up Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1003]Mommy's waiting for you... Ahaha![n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Ignore it.[e]
[uf 0 5 65278][uf 2 1]I'll shut them up.[e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Thank you, but I'm all right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]If I let it bother me, then it'll never go away. I just want to finish what I came here for.[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]N-No, it's fine, [uf 4 1]-san![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 8 0 25 25]I'm totally okay. I don't want you to go out of your way for that.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]This looks like the place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]The owner here is really particular about the taste of his drinks. They say he has ingredients you can't normally find.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]And for one of the cocktails he makes, he uses an extremely rare tea leaf.[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Is that what you're looking for?[e]
[uf 0 5 65278][uf 2 1]You did your research.[e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Yes, I've seen Mitsuru-san drinking tea in the lounge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]So when I was thinking of a gift that would make her happy, this is what came to mind.[n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]I borrowed a computer from Fuuka-san and gathered some information.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Mitsuru-san seems to know her teas well, so I figured I shouldn't give her anything weird.[n][uf 1 1][e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]I hope the bar owner is willing to share some of it, though...[n][uf 1 1][e]

[msg MSG_021_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]...Well, he looked scary, but at least he agreed to sell it to us in the end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Boy, I'm glad that worked out. I can't wait to give this to Mitsuru-san![n][uf 1 1][e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]With everything that happened, I'm sure she's been having a hard time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 8 3 25 25]It's sad and painful to be in a home, knowing that you'll never see a loved one there with you again...[n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]So, I'm hoping this makes things more pleasant for her, at least while she's at the dorm.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Although, it is Mitsuru-san we're talking about, so I'm sure she'll be fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 8 1 25 25]I just thought it would be nice if she was able to think about things over a delicious cup of tea.[n][uf 1 1][e]

[sel SEL_024_0_0 top]
[uf 0 5 65278][uf 2 1]You're really kind.[e]
[uf 0 5 65278][uf 2 1]I'm sure she'll like it.[e]
[uf 0 5 65278][uf 2 1]You've grown strong.[e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Oh, no! It's just, she's always looking after me, so I thought I'd show my appreciation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0][uf 4 23 0 8 1 25 25]When I think about what it was like for me, I feel like this is the least I can do.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Thanks, I feel a lot better hearing you say that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I thought about it a lot, and this is the best I could come up with.[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]You really mean that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 8 3 25 25]I was just... thinking about when the same thing happened to me.[n][uf 1 1][e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Well, we should head back before it gets too late.[n][uf 1 1][e]

[msg MSG_029_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 43 0 0]......[n][uf 1 1][e]

[sel SEL_030_0_0 top]
[uf 0 5 65278][uf 2 1]What's wrong?[e]
[uf 0 5 65278][uf 2 1]Something happen?[e]

[msg MSG_031_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]...Nah, it's nothing.[n][uf 1 1][e]

