[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5099 0 0]What was that...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]It's as if the energy from the door surged through the entire floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]I can see the floor layout! That makes it easier for me to guide you now.[n][uf 1 1][e]

[msg SYS_000_0_1 [Fuuka Yamagishi]]

[msg SYS_001_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 0]With the energy released from the Monad door, you have now obtained the map information of the current floor and the floor above.[n][uf 1 1][e]

