[msg MSG_000_0_0 [（ＳＥ）ガヤ男Ａ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]いいじゃーん、行こうぜ？[n]外とか、まだちっと寒みぃしさ、な～？[n][uf 1 1][e]

[msg MSG_001_0_0 [（ＳＥ）ガヤ女Ａ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]え、どーする、マユミ？[n][uf 1 1][e]

[msg MSG_002_0_0 [（ＳＥ）ガヤ女Ｂ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]え、全然行きたいのは行きたいけどー、[n]なにげに親とかさ…[n][uf 1 1][e]

[msg MSG_003_0_0 [（ＳＥ）ガヤ男Ｂ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]関係ねーじゃん、メールしときゃバレねって！[n][uf 1 1][e]

[msg MSG_004_0_0 [（ＳＥ）ガヤ女Ｂ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]まぁ…行っちゃおっかっ！[n][uf 1 1][e]

[msg MSG_005_0_0 [Man Listening to the Radio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]This sucks...[n][uf 1 1][e]

[msg MSG_006_0_0 [（ＳＥ）ガヤ女Ｃ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]キャハハハ…[n][uf 1 1][e]

[msg MSG_007_0_0 [（ＳＥ）ガヤ男Ｃ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]大マジだって！　超ビビったモン俺。[n][uf 1 1][e]

[msg MSG_008_0_0 [（ＳＥ）ガヤ女Ｃ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]ありえねー！　え、作ってなーい？[n][uf 1 1][e]

[msg MSG_009_0_0 [Radio DJ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]That was the Bay Side Rockers, brought to you by K.J.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]And that's all for tonight, folks. Tune in again next week—same time, same place.[n][uf 1 1][e]

[msg MSG_010_0_0 [Radio Announcer]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]The program you just heard was sponsored by Kirijo Electronics: bringing the future to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]The time is now 12 AM.[n][uf 1 1][e]

