[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Huh... No one else is back yet?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Man, I wonder why Sanada-san was acting so weird. Somethin' about the date?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]What's so special about October 4th?[n][uf 1 1][e]

[msg MSG_001_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 5 4 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 4 0 0]October 4th...! That's right![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 5 0 0]I was so focused on the operation that I didn't realize it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Today is the anniversary of the day Amada's mother was killed![n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 7 0 0]She was killed...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Yamagishi, I need you to locate Aragaki and Amada immediately.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 9 0 0]There's a good chance they'll be together. Akihiko must have already realized it.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 10 0 0]I-I'm on it.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Uh... What's going on?[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Public records say that Amada's mother was killed in an accident...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]...But in truth, we were the ones responsible for her death.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 14 0 0]What...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 15 0 0]It happened [uf 0 1 33]two years ago, when we were hunting down a Shadow[uf 0 1 27] that appeared in the city...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Aragaki had only just awakened his Persona, and he lost control of it for a moment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 17 0 0]We'd been so focused on the Shadow, we hadn't accounted for any civilians in the area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Unfortunately... there was one casualty.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]...It was Amada's mother.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 20 0 0]No way... Are you kidding me!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Wait, so to Amada-kun, Aragaki-senpai is...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 22 0 0]I should've considered this when Amada volunteered to join us. It's possible that he...[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 23 0 0]I've found them! They're at Tatsumi Port Island![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 24 0 0]They're together, and I'm picking up someone else, too...[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Is it Akihiko?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 26 0 0]Wait... This is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 27 0 0]No! It's Strega![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Hey, isn't that a problem!?[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Ngh... This couldn't be worse![n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Senpai![n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 31 0 0]C'mon! We gotta follow her![n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 65535 0 0][uf 3 1 1 0 0 32 0 0]R-Right![n][uf 1 1][e]

