[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6078 0 0][uf 5 13 22 5 7]Wow, look at that... The color of the sea is so deep...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Aigis grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's about time to leave school...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We decided to go back to the dorm.[n][uf 1 1][e]

