[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Who should I go to the[n]summer festival with...?[n][uf 1 1][e]

[msg MND_000_5_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Should I go to the summer[n]festival with Mitsuru...?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Go with Yukari[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Go with Yuko[uf 4 27 106 0][e]
[uf 0 5 65278][uf 2 1]Go with Chihiro[uf 4 27 109 0][e]
[uf 0 5 65278][uf 2 1]Go with Fuuka[uf 4 27 6 0][e]
[uf 0 5 65278][uf 2 1]Go with Mitsuru[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Go alone[e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Should I decline the invitation[n]and go by myself?[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Should I decline the invitations[n]and go by myself?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Reconsider[e]
[uf 0 5 65278][uf 2 1]Go alone[e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]There are no characters that[n]can currently be displayed![n][uf 1 1][e]

