[msg MSG_000_0_0 [Tourist Mood Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 606]I love wearing a yukata. It makes me feel so classy and traditional![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 606]It's getting me all excited.[n][uf 1 1][e]

[msg MSG_001_0_0 [Tourist Mood Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 606]I bought a lot of Kyoto sweets when we were allowed to walk around on our own![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 606]I want to try them, but if I eat them all now, I'll get chunky... What should I do!?[n][uf 1 1][e]

