[msg MSG_000_0_0 [Carefree Third-Year]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 508]The student council president seems upset.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 508]Does she think we're being immature or something?[n][uf 1 1][e]

[msg MSG_001_0_0 [Astounded Second-Year]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 509]You don't read the newspaper, do you, Senpai? Her father recently died...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 509]You seriously didn't know?[n][uf 1 1][e]

