[msg MSG_000_0_0 [Shinsengumi Fan Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 614]Kinkakuji temple? Kiyomizu temple? Are you kidding me...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 614]If we're in Kyoto, it's gotta be about the Shinsengumi! That's what I'm talking about![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 614]Iketaya's remains... And the Nishihongan temple, right!? Nooo... I won't have enough time![n][uf 1 1][e]

