[msg MSG_000_0_0 [Particular Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 650]I'm calling dibs on this futon! This corner is the best one...[n][uf 1 1][e]

[msg MSG_001_0_0 [Particular Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 650]There were doodles all over my face when I woke up this morning...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 650]In oil-based ink! This is pathetic![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 650]I'll get my revenge if I have to stay up all night...[n][uf 1 1][e]

