[msg MSG_000_0_0 [Well-Behaved Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 653]I can't sleep with a pillow that isn't mine...[n][uf 1 1][e]

[msg MSG_001_0_0 [Well-Behaved Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 653]I was worried about not being able to sleep, but I slept like a log last night![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 653]This is one fine inn! Their cushions are world-class![n][uf 1 1][e]

