[msg MSG_000_0_0 [Concerned Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 504]I wonder if Kirijo-san will be all right... She's been so depressed lately.[n][uf 1 1][e]

[msg MSG_001_0_0 [Worried Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 505]I'm worried too, but we should leave her be for now. Us trying to cheer her up won't help...[n][uf 1 1][e]

[msg MSG_002_0_0 [Concerned Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 504]Yeah... You're right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 504]Still, it feels so heavy in there that I can't bring myself to talk about anything...[n][uf 1 1][e]

[msg MSG_003_0_0 [Worried Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 505]Kirijo-san left somewhere. A second-year came by earlier looking for her too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 505]I think her name was Takeba-san. I have no idea where either of them went, though.[n][uf 1 1][e]

