[msg MSG_000_0_0 [Energetic Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 607]I usually sleep in a bed, so sleeping on a futon is a new experience for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 607]But I tend to move around a lot at night. I'm worried that I'll end up kicking the girl sleeping next to me...[n][uf 1 1][e]

[msg MSG_001_0_0 [Energetic Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 607]My friend said that this inn is haunted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 607]But you hear ghost stories no matter where you go. It's all just superstition.[n][uf 1 1][e]

