[msg MSG_000_0_0 [Calm Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 646]Everyone says tomorrow is the ordinary sightseeing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 646]What's so "ordinary" about it? Well, I'll just follow along and see for myself.[n][uf 1 1][e]

[msg MSG_001_0_0 [Calm Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 646]Tomorrow's the last day of the trip... I should find somewhere else to sightsee.[n][uf 1 1][e]

