[msg MSG_001_0_0 [Sweaty Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]Are you here to pick up chicks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]You're doing it wrong! You have to be more subtle or it'll put them off![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]I'm here today with the intention of getting a girlfriend, too! That makes us rivals, doesn't it?[n][uf 1 1][e]

[msg MSG_004_0_0 [Sweaty Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]Those girls were kinda harsh... You shouldn't argue with them when they're like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]Just agree with what they say and shower them with compliments! This is a very basic technique.[n][uf 1 1][e]

[msg MSG_006_0_0 [Sweaty Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]Looks like she already has a boyfriend... Tough luck.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]"It's lame to hit on girls at the beach," they said...[n][uf 1 1][e]

[msg MSG_008_0_0 [Sweaty Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]Whoa, did you get a girlfriend!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 693]How could you make such a cutie cry!? Hurry up and go after her![n][uf 1 1][e]

