[msg MSG_000_0_0 [Student by the Paper Sliding Door]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 510]How come our school trip is in Japan? Dude, we've gotta go abroad or there's no point![n][uf 1 1][e]

[msg MSG_001_0_0 [Student by the Entrance]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 511]I hear it's Ekoda's fault.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 511]Every other teacher wanted to go out of the country, but Ekoda insisted on Kyoto.[n][uf 1 1][e]

[msg MSG_002_0_0 [Student by the Paper Sliding Door]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 510]Seriously? That guy sucks...[n][uf 1 1][e]

[msg MSG_003_0_0 [Student by the Entrance]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 511]Man, the hot spring is huge! It felt so good that I swam around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 511]I swam a whole lap![n][uf 1 1][e]

[msg MSG_004_0_0 [Student by the Paper Sliding Door]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 510]Dude, just because it's big doesn't mean you should swim in it.[n][uf 1 1][e]

