[msg MSG_000_0_0 [Realistic Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 512]I've gotta study my ass off for the exams when I get back...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 512]The university entrance exams are in less than two months. The competition's about to begin.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mood Spoiled Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 513]*sigh*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 513]Why'd you have to remind me about the exams...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 513]Way to kill the trip's mood.[n][uf 1 1][e]

