[msg MSG_TUTO_BTL03_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20531 0 0]How'd ya like our all-out combo attack, ya filthy Shadows!?[n][uf 1 1][e]

[msg MSG_TUTO_BTL03_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 81 0 0][uf 3 1 1 0 1 20532 0 0]When I saw my opening, it's like my body just knew what to do.[n][uf 1 1][e]

[msg MSG_TUTO_BTL03_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20533 0 0]That was magnificent teamwork. It's hard to believe it's your first time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20534 0 0]As you grasp the flow of battle, you'll learn to coordinate with each other seamlessly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20535 0 0]Let's apply what we've learned so far and continue exploring.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4585 0 0]Okay, I think this is a good place to stop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There's a device nearby that will teleport you back. Look around for it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]There should also be some stairs nearby, but I can't approve any more exploration right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We'll explore the upper floors next time.[n][uf 1 1][e]

[msg MSG_THEURGIA_4TH_BTL_END [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 1 10032 0 0]I no longer detect any Shadows. All the ones on this floor have been defeated.[n][uf 1 1][e]

[msg MSG_THEURGIA_4TH_BTL_END_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 82 0 0][uf 3 1 1 0 1 10033 0 0]It's all coming back to me. It would be wise for me to keep battling.[n][uf 1 1][e]

[msg MSG_THEURGIA_4TH_BTL_END_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 82 0 0][uf 3 1 1 0 1 10034 0 0]Let's keep going then.[n][uf 1 1][e]

[msg MSG_THEURGIA_4TH_BTL_END_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]You've already found the stairs, right? Should we head there now?[n][uf 1 1][e]

[sel SEL_THEURGIA_YESNO top]
[uf 0 5 65278][uf 2 1]Head for the stairs[e]
[uf 0 5 65278][uf 2 1]Continue exploring[e]

[msg MSG_SUGGEST_TUTO_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]All right, we've secured the perimeter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We still have a little time before the Shadows reappear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It might be a good idea to do some reconnaissance.[n][uf 1 1][e]

[msg MSG_SUGGEST_TUTO_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5143 0 0]Nice work. We've secured the perimeter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We still have some time to spare before the Shadows reappear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]It should be a little safer for you to scout ahead right now.[n][uf 1 1][e]

[sel SEL_SEPARATELY_TUTO_00 top]
[uf 0 5 65278][uf 2 1]What do you mean?[e]
[uf 0 5 65278][uf 2 1]What should we do?[e]

[msg MSG_SUGGEST_TUTO_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4065 0 0]One of you will split from the group to canvass the floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]That way, we'll be able to explore more efficiently, correct?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It's still risky, of course, but one person should have an easier time avoiding Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If the scout can find the stairs, it'll lighten the load for [uf 4 1] and the main squad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]So how about it? Anyone up to the task?[n][uf 1 1][e]

[msg MSG_SUGGEST_TUTO_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5064 0 0]One person will split from the party to scout the floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Exploring would be more efficient if we divide and conquer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 50 0 0]Going solo makes it easier to evade Shadows as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]And if the scout can locate the stairs, it'd make everyone's lives a lot easier.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]So what do you think? Should we ask someone to scout ahead?[n][uf 1 1][e]

[msg MSG_SUGGEST_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4085 0 0]All right, we've secured the area. Shall we have someone scout ahead?[n][uf 1 1][e]

[msg MSG_SUGGEST_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]We've secured the area. Do you want to send someone out to scout ahead?[n][uf 1 1][e]

[msg MSG_SEPARATELY_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]I'm on it! Just let me handle this![n][uf 1 1][e]

[msg MSG_SEPARATELY_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]C'mon, dude. You know I'm the man for the job.[n][uf 1 1][e]

[msg MSG_SEPARATELY_SANADA_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3001 0 0]I'll go. My training's prepared me for this.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]Allow me. Don't worry, I'll clear us a path.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5068 0 0]Oh, I think Koro-chan's volunteering to go! Well then, we're counting on you, Koro-chan.[n][uf 1 1][e]

[msg MSG_SEPARATELY_AEGIS_00 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6019 0 0]I'll go. I have experience conducting solo missions.[n][uf 1 1][e]

[msg MSG_SEPARATELY_AMADA_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7002 0 0]Leave it to me! There's no way those Shadows will find me![n][uf 1 1][e]

[msg MSG_SEPARATELY_KOROMARU_ [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_SEPARATELY_ARAGAKI_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9005 0 0]I got this. You cool with that?[n][uf 1 1][e]

[sel SEL_SEPARATELY_00 top]
[uf 0 5 65278][uf 2 1]I'm counting on you.[e]
[uf 0 5 65278][uf 2 1]Let's not.[e]

