[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]It makes me kind of nervous being alone together in my room like this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 1 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Hey, um... Since you're here, why don't we have some fun together?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 1 0][uf 3 1 1 0 0 4 0 0][uf 5 13 7 5 2]W-Wait, I didn't mean it like that! We could just, y'know... play cards or something![n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I spent a long time with Yukari.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond between us...[n][uf 1 1][e]

