[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I can hear people talking.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The first bell has rung.[n][uf 1 1][e]

[msg MSG_002_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22003 0 0][uf 5 21 0 100]Hey, have you heard the rumor about, uh... What was it again? The bathroom?[n][uf 1 1][e]

[msg MSG_003_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22208 0 0][uf 5 21 0 150]That's old news. Besides, it's just a ghost story, not a rumor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]You're talking about that one girl, right? The first-year?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]She stopped coming to school and just sits around staring at walls all day long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Whenever her mom tries to talk to her, the only thing she says is, "It's coming... It's coming!"[n][uf 1 1][e]

[msg MSG_004_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22007 0 0][uf 5 21 0 100]Is that really how the story goes? Eh, whatever. It's probably all made up anyway.[n][uf 1 1][e]

[msg MSG_005_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22101 0 0][uf 5 21 0 100]G'morning... Ugh, I always feel super sleepy waking up on Mondays.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]And there's another special morning assembly today? Didn't we just have one last week?[n][uf 1 1][e]

[msg MSG_006_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22005 0 0][uf 5 21 0 150]Remember how Kirijo-senpai gave that great speech last week?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Apparently, that got the principal really fired up, and now he wants to make a follow-up speech.[n][uf 1 1][e]

[msg MSG_007_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22207 0 0][uf 5 21 0 100]Seriously!? The heck? Why do we have to suffer just 'cause he wants to stroke his ego!?[n][uf 1 1][e]

[msg MSG_008_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22208 0 0][uf 5 21 0 100]Oh no! There's a test today! I didn't study at all yesterday because... I fell asleep![n][uf 1 1][e]

[msg MSG_009_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22008 0 0][uf 5 21 0 150]Come on... You don't need to lie about it every time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Don't you think it's rude to people who really haven't studied?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Sure, it's nice to be smart, but you gotta be considerate of other people's feelings, too...[n][uf 1 1][e]

[msg MSG_010_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22207 0 0][uf 5 21 0 100]Whatever, quit being such a nag! I totally forgot five vocabulary words listening to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]I spent last night cramming... and now I gotta memorize them all over again![n][uf 1 1][e]

[msg MSG_011_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22202 0 0][uf 5 21 0 100]Hey, have you heard about that second-year...?[n][uf 1 1][e]

[msg MSG_012_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 150]Oh yeah! The one they found lying in front of the school gate this morning, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Hopefully, she just ran away from home... But I feel like this is the start of something big.[n][uf 1 1][e]

[msg MSG_013_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 100]Yeah, there might be reporters and camera crews and stuff... I'd rather not deal with that.[n][uf 1 1][e]

[msg MSG_014_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21504 0 0][uf 5 21 0 100]The Kirijo Group was on the news yesterday. Something about showing their true colors...[n][uf 1 1][e]

[msg MSG_015_0_0 [Loud Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21906 0 0][uf 5 21 0 150]Kirijo...? Oh, the student council president?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]I hear they're involved in a lot of things. Even this school's owned by the Kirijo Group, right?[n][uf 1 1][e]

[msg MSG_016_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21506 0 0][uf 5 21 0 100]I wonder why a company that big decided to build a school...[n][uf 1 1][e]

[msg MSG_017_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21905 0 0][uf 5 21 0 100]By the way, you know Mitsuru Kirijo? The student council president?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]I heard she's gonna study abroad after high school. Probably to prepare herself to run the Kirijo Group in the future.[n][uf 1 1][e]

[msg MSG_018_0_0 [Loud Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21510 0 0][uf 5 21 0 150]Wow, that's crazy. It's like she lives in a different world from us plebs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]But she's staying in a dorm, right? Why would a rich girl wanna live in a dump like that?[n][uf 1 1][e]

[msg MSG_019_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21907 0 0][uf 5 21 0 100]Maybe her family made her? To understand how us ordinary folks live or something.[n][uf 1 1][e]

[msg MSG_020_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22005 0 0][uf 5 21 0 100]Hey, get this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]The other night, my boyfriend casually tried to take me to Shirakawa Boulevard on a date.[n][uf 1 1][e]

[msg MSG_021_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22207 0 0][uf 5 21 0 150]What!? No way! THAT Shirakawa Boulevard? Ewww, he totally had an ulterior motive.[n][uf 1 1][e]

[msg MSG_022_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 100]We just started dating, but I'm already getting creeped out... His head's always in the gutter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Maybe I should dump him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]I don't wanna end up like those couples from the rumors. You know, the ones "found unconscious" somewhere.[n][uf 1 1][e]

[msg MSG_023_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21705 0 0][uf 5 21 0 100]You know, our campus is actually pretty clean and new. I only noticed after my club had to visit another school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]My parents said that our school was rebuilt after an explosion ten years ago.[n][uf 1 1][e]

[msg MSG_024_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22205 0 0][uf 5 21 0 150]I also heard that the explosion wasn't the only reason...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Around that time, a lot of students suddenly stopped coming to school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Maybe that's why they put up the new building—to start with a clean slate...[n][uf 1 1][e]

[msg MSG_025_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21708 0 0][uf 5 21 0 100]Haha, what, you think there's a dark side to Gekkoukan High? You watch way too much TV.[n][uf 1 1][e]

[msg MSG_026_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22110 0 0][uf 5 21 0 100]Ugh... We have exams starting tomorrow. And they're cumulative, so it's hard to remember everything.[n][uf 1 1][e]

[msg MSG_027_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 150]What if I fail again...? I really wish the school would stop posting our names with our scores.[n][uf 1 1][e]

[msg MSG_028_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 100]Right? It's embarrassing if we're near the bottom of the list... Smart people like Kirijo-senpai wouldn't get it though.[n][uf 1 1][e]

[msg MSG_029_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]What is your class gonna do for the culture festival?[n][uf 1 1][e]

[msg MSG_030_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]A haunted house! I bet I'll be stuck playing the ghost.[n][uf 1 1][e]

[msg MSG_031_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]That doesn't sound too bad. You can just show up and put on the costume. I actually need to practice for a magic show...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]But I also heard a typhoon is on its way, and that it's a big one... Are people really gonna turn up?[n][uf 1 1][e]

[msg MSG_032_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21902 0 0][uf 5 21 0 100]I heard there's a nasty typhoon on the way. You think we'll still have the culture festival Saturday?[n][uf 1 1][e]

[msg MSG_033_0_0 [Loud Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21508 0 0][uf 5 21 0 150]Nah, I don't think so. The way they're talking, the typhoon's gonna be way too destructive.[n][uf 1 1][e]

[msg MSG_034_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21909 0 0][uf 5 21 0 100]You seriously think it's gonna be canceled? Man, after all that work we put in preparing for it...[n][uf 1 1][e]

[msg MSG_035_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22005 0 0][uf 5 21 0 100]Someone in my neighborhood actually has those symptoms...[n][uf 1 1][e]

[msg MSG_036_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22406 0 0][uf 5 21 0 150]There are a few in mine, too... I'm scared.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]They said on TV that it's not contagious, but I feel like it's a sign of the end of the world...[n][uf 1 1][e]

[msg MSG_037_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22010 0 0][uf 5 21 0 100]D-Don't joke like that. "The end of the world"? There's no way...[n][uf 1 1][e]

[msg MSG_038_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22005 0 0][uf 5 21 0 100]It's finally time to break out the winter uniforms... They're so heavy, my shoulders hurt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]At least I found my lapel pin in the pocket! It'd haunt me forever if I couldn't find it.[n][uf 1 1][e]

[msg MSG_039_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 150]My shoulders have been hurting lately, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Plus, I'm hearing weird voices... And I've also been getting headaches.[n][uf 1 1][e]

[msg MSG_040_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22009 0 0][uf 5 21 0 100]Y-You're haunted!?[n][uf 1 1][e]

[msg MSG_041_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 100]Is it just me, or are more people coming down with Apathy Syndrome lately?[n][uf 1 1][e]

[msg MSG_042_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 150]My friend's brother's friend got it, too.[n][uf 1 1][e]

[msg MSG_043_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22307 0 0][uf 5 21 0 100]It's starting to scare me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]And it's on the news every day now. Oh, did you see the special program they ran?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Apparently, Nostradamus predicted that all this would happen![n][uf 1 1][e]

[msg MSG_044_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22005 0 0][uf 5 21 0 100]Geez... There's someone with Apathy Syndrome at my cram school, too.[n][uf 1 1][e]

[msg MSG_045_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 150]I heard that this city isn't the only one affected. It's also happening in other places.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]I wonder what's going to happen to this country...[n][uf 1 1][e]

[msg MSG_046_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22007 0 0][uf 5 21 0 100]C-C'mon, don't say such scary things. I'm sure someone will take care of it...[n][uf 1 1][e]

[msg MSG_047_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22002 0 0][uf 5 21 0 100]Hey, have you talked to the new transfer student yet? Isn't he handsome?[n][uf 1 1][e]

[msg MSG_048_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22106 0 0][uf 5 21 0 150]Yeah, I have! Mochizuki-kun, right? He's so sweet and dreamy... Also, he looks rich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]I'm going for him for real this time![n][uf 1 1][e]

[msg MSG_49_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22007 0 0][uf 5 21 0 100]Th-That's not fair! I called dibs![n][uf 1 1][e]

[msg MSG_050_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22002 0 0][uf 5 21 0 100]The school trip's tomorrow! Are you all packed?[n][uf 1 1][e]

[msg MSG_051_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22203 0 0][uf 5 21 0 150]You bet I am! I've got it all covered. Yukata, bathing suit, flashlight, snacks...[n][uf 1 1][e]

[msg MSG_052_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22010 0 0][uf 5 21 0 100]...You don't travel light, do you?[n][uf 1 1][e]

[msg MSG_053_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22004 0 0][uf 5 21 0 100]I heard some people saying that Apathy Syndrome is nothing to worry about.[n][uf 1 1][e]

[msg MSG_054_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22406 0 0][uf 5 21 0 150]I heard the same thing. They're saying it puts people at ease, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]You think it's some kinda new religion? I think I get what they mean, though.[n][uf 1 1][e]

[msg MSG_055_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22007 0 0][uf 5 21 0 100]No way, are you seriously falling for that? It's all a scam![n][uf 1 1][e]

[msg MSG_056_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22001 0 0][uf 5 21 0 100]Morning! It's cold today, but at least winter vacation starts tomorrow![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]What are you gonna do with your New Year's allowance?[n][uf 1 1][e]

[msg MSG_057_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22108 0 0][uf 5 21 0 150]Haha, I didn't get mine yet![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]But I want to buy a grab bag! I'm aiming for one with a purse...[n][uf 1 1][e]

[msg MSG_058_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 100]Ooh, me too! Hey, do you want to start waiting in line today? We could bring a kotatsu...[n][uf 1 1][e]

[msg MSG_059_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21905 0 0][uf 5 21 0 100]Hey, have you heard the rumors about that cult?[n][uf 1 1][e]

[msg MSG_060_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22207 0 0][uf 5 21 0 150]Hey, don't call it that if you don't know anything about it. Besides, it's pretty much fact the Fall is coming.[n][uf 1 1][e]

[msg MSG_061_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21907 0 0][uf 5 21 0 100]Oh... Well, nothing we can do about that, I guess.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]By the way, about the homework for second period...[n][uf 1 1][e]

[msg MSG_062_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22202 0 0][uf 5 21 0 100]By the way... I wanted to show you this magazine that hit the stands today.[n][uf 1 1][e]

[msg MSG_063_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22007 0 0][uf 5 21 0 150]Which one? Don't tell me it's an article about cults.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Everyone's been saying "The end is near" lately... What's up with that?[n][uf 1 1][e]

[msg MSG_064_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22208 0 0][uf 5 21 0 100]...Just read it. You'll see how true it really is.[n][uf 1 1][e]

[msg MSG_065_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21905 0 0][uf 5 21 0 100]Oh yeah, my brother was invited to join that cult.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]They approached him when he was at Escapade. Isn't that crazy?[n][uf 1 1][e]

[msg MSG_066_0_0 [Loud Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21509 0 0][uf 5 21 0 150]Whoa. Didn't think someone all about salvation and stuff would be at a nightclub.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]Guess they're everywhere these days.[n][uf 1 1][e]

[msg MSG_067_0_0 [Chatty Male Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 21907 0 0][uf 5 21 0 100]Apparently, the guy had a crazy look in his eye. He kept rambling about the "moment of salvation" or whatever...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]You can find him lurking in the corner of the dance floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]I'm probably gonna stop going to Escapade for a while...[n][uf 1 1][e]

[msg MSG_068_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22002 0 0][uf 5 21 0 100]They were handing out flyers at Paulownia Mall the last time I went.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]It's the same one that's plastered all over the city.[n][uf 1 1][e]

[msg MSG_069_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22110 0 0][uf 5 21 0 150]Oh yeah, the one about Nyx, right?[n][uf 1 1][e]

[msg MSG_070_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22010 0 0][uf 5 21 0 100]Huh, is that how you say it? I dunno, I just liked the logo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]The stuff written here is kinda interesting, too. Maybe I should ask them about it next time...[n][uf 1 1][e]

[msg MSG_071_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22307 0 0][uf 5 21 0 100]I'm so sleepy... It's been so cold that it's actually painful to leave the comfort of my bed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]I'm starting to think that living life with Apathy Syndrome would be easier...[n][uf 1 1][e]

[msg MSG_072_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22406 0 0][uf 5 21 0 150]I know, right? I could sleep all day, and people would get all concerned for me![n][uf 1 1][e]

[msg MSG_073_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 100]Yeah, exactly! Maybe I really should get Apathy Syndrome—at least for a little while.[n][uf 1 1][e]

[msg MSG_074_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22204 0 0][uf 5 21 0 100]I've heard a lot of talk lately about salvation, and the world becoming renewed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]If everyone ends up getting Apathy Syndrome, we really might need something like that...[n][uf 1 1][e]

[msg MSG_075_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22006 0 0][uf 5 21 0 150]Yeah, I always hear people talk about it on TV.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]I thought the cult sounded suspicious at first, but maybe it isn't...[n][uf 1 1][e]

[msg MSG_076_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22307 0 0][uf 5 21 0 100]I mean, if the whole world believes in it, I'd feel stupid to be the only one denying it.[n][uf 1 1][e]

[msg MSG_077_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22203 0 0][uf 5 21 0 100]I've made zero progress studying for exams... I just can't concentrate at home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Even if I wanted to go somewhere else to study, I don't have the money for it right now.[n][uf 1 1][e]

[msg MSG_078_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22002 0 0][uf 5 21 0 150]Why don't you go to [uf 0 1 2]the library[uf 0 1 27] then?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]It's nice and quiet, and you can find lots of reference materials there. Plus, it's free![n][uf 1 1][e]

[msg MSG_079_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22307 0 0][uf 5 21 0 100]Hm, yeah, you've got a point. I could study there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Argh, I just wish I had the money for the Prodigy Platter at Wakatsu![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Do you think it's really true? That just one bite could make you smarter? Oh, I envy the rich...[n][uf 1 1][e]

[msg MSG_080_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22203 0 0][uf 5 21 0 100]I spent my entire day off at the net café...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]You can play computer games there, so I ended up trying a bunch of different ones.[n][uf 1 1][e]

[msg MSG_081_0_0 [Chatty Female Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22107 0 0][uf 5 21 0 150]I knew that [uf 0 1 2]they sell computer software[uf 0 1 27] there, but I didn't realize you could use them in the private booths too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 150]It's always so packed there though, so I never feel like going.[n][uf 1 1][e]

[msg MSG_082_0_0 [Loud Female Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Yeah, it was super crowded yesterday, too. It was a miracle I managed to get my own booth.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 0 100]Next time I'll just buy the game. It's probably more relaxing to play it at home, anyways.[n][uf 1 1][e]

