[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Let's go together.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Ask about the target[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head to Club Escapade[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head toward the station[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[msg MSG_KOROMARU_PARTY_IN_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_AF [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_A [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0]*whimper*[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OVER [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_CHANG [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_AF_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_0_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_A_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0]*whine*[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_01 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrrrrrr...[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_A_3 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_02 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrrrr...[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_0_3 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrrrr...[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_10 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "I'm worried about our missing allies," and, "Let's hurry."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is very motivated.[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_20 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "I'm ready."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san appears to be in a good mood.[n][uf 1 1][e]

[msg MND_KOROMARU_PARTY_IN_20]
[uf 0 5 65278][uf 2 1]It seems like Koromaru wants[n]to join me in battle.[n][uf 1 1][e]

[msg MND_KOROMARU_PARTY_OUT_2]
[uf 0 5 65278][uf 2 1]Koromaru seems very motivated.[n][uf 1 1][e]

[msg MND_KOROMARU_PARTY_OVER_]
[uf 0 5 65278][uf 2 1]Koromaru seems troubled because[n]there's no more space in the party.[n][uf 1 1][e]

[msg MND_KOROMARU_PT_CHANGE_2]
[uf 0 5 65278][uf 2 1]Who should I switch out[n]so Koromaru can join...?[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_TK [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "I'll put this to an end."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_T [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is saying, "Are we not going yet?"[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_HG [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "We will be victorious!"[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is ready to engage in battle.[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_CH [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "This is worrisome..."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_C [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is saying, "Let's go after them quickly."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_JI [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "This won't be easy... but we can do it."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_J [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is saying, "You can count on me."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_TK_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is trying to cheer us up, saying, "Hang in there."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_T_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is enthusiastically saying, "We'll finish this."[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_IN_TK_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Koromaru-san is saying, "This is it!" He appears ready for anything![n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OUT_T_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Koromaru-san is saying, "I got your back." He is very reliable.[n][uf 1 1][e]

[msg MSG_KOROMARU_PARTY_OVER_ [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]It seems the current party's lineup does not have adequate space for Koromaru-san.[n][uf 1 1][e]

[msg MSG_KOROMARU_PT_CHANGE_8 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Will you remove someone else so that Koromaru-san may join?[n][uf 1 1][e]

[msg MSG_0808_0820_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MND_0808_0820_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems enthusiastic.[n][uf 1 1][e]

[msg MSG_0821_0827_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_0821_0827_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_0828_0902_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_0828_0902_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be welcoming[n]Amada to the team.[n][uf 1 1][e]

[msg MSG_0903_0904_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_0903_0904_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be welcoming[n]Aragaki to the team.[n][uf 1 1][e]

[msg MSG_0906_0918_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_0906_0918_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_0919_1003_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_0919_1003_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_1005_1016_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MND_1005_1016_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be showing[n]respect for Aragaki...[n][uf 1 1][e]

[msg MSG_1019_1102_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][uf 1 1][e]

[msg MND_1019_1102_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems fired up...[n][uf 1 1][e]

[msg MSG_1106_1109_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_1106_1109_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_1110_1117_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_1110_1117_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be[n]worrying about Mitsuru...[n][uf 1 1][e]

[msg MSG_1121_KORO_DUNGE_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_1121_KORO_DUNGE_01]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_1122_1127_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 3 0 65535 8003 0 0]*whine*[n][uf 1 1][e]

[msg MND_1122_1127_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be[n]worrying about Junpei...[n][uf 1 1][e]

[msg MSG_1203_1213_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_1203_1213_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_0101_0114_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_0101_0114_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems more[n]enthusiastic than usual.[n][uf 1 1][e]

[msg MSG_0115_0130_KORO_DUNGE [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Ruff! Ruff![n][uf 1 1][e]

[msg MND_0115_0130_KORO_DUNGE]
[uf 0 5 65278][uf 2 1]Koromaru seems to be filled with motivation.[n][uf 1 1][e]

[msg MSG_0131_KORO_DUNGE_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 8 65535 65535 0 0][uf 3 1 3 0 65535 8007 0 0]Awoooo![n][uf 1 1][e]

[msg MND_0131_KORO_DUNGE_01]
[uf 0 5 65278][uf 2 1]I can feel a strong sense of[n]resolve from Koromaru...[n][uf 1 1][e]

[msg MSG_HANYOU1_KORO_DUNGE_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Woof.[n][uf 1 1][e]

[msg MND_HANYOU1_KORO_DUNGE_0]
[uf 0 5 65278][uf 2 1]Koromaru seems as confident as usual.[n][uf 1 1][e]

[msg MSG_HANYOU2_KORO_DUNGE_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Ruff! Ruff![n][uf 1 1][e]

[msg MND_HANYOU2_KORO_DUNGE_0]
[uf 0 5 65278][uf 2 1]Koromaru seems like he's doing well.[n][uf 1 1][e]

[msg MSG_KORO_ZEKKOCHO_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Ruff! Ruff![n][uf 1 1][e]

[msg MND_KORO_ZEKKOCHO_01]
[uf 0 5 65278][uf 2 1]Koromaru seems to be[n]in top condition today.[n][uf 1 1][e]

