[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Let's go together.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Ask about the target[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head to Club Escapade[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head toward the station[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[msg MSG_SANADA_PARTY_IN_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Okay, here we go.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]That's what I like to hear![n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]All right, let's get going.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_AFT [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, it's up to you. All right, then...[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OVER_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Looks like the party's already full.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_CHANGE_ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Who should I switch with?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_CHANGE__2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Whose place should I take?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OVER_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The party is already full.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Should be a worthy opponent. You ready?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_AFT_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]All right.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Leave it to me.[n][uf 1 1][e]

[msg MSG_SANADA_TUTORIAL_BEFO [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Remember, Takeba and Junpei have no real battle experience, so make sure you back them up.[n][uf 1 1][e]

[msg MSG_SANADA_TUTORIAL_AFTE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]You guys did a great job, but you won't have to shoulder the burden forever.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0]I'll help you out too... Just as soon as this damn injury is healed...[n][uf 1 1][e]

[msg MSG_SANADA_THEURGIA_BEFO [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]"Theurgy," was it? I'm looking forward to seeing how it works.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]That aside, let's handle this like we always do. It's Mitsuru's first real battle in a while, too.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_AFT_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]We all want to finish this, but don't get careless.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Got it.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OVER_02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The party's full.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_CHANGE__3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Who should I switch with?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]If they're so willing to take us on again after last time, they're either very confident...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Or they've got something up their sleeve. But it doesn't matter either way—we won't lose.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]What're you waiting for? Let's go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]If they insist on getting in our way, then I'll just clear the way with my fists.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I hope Shinji's giving that Jin guy a piece of his mind right about now...[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_03 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Anyway, let's hurry. We can't afford to waste too much time here.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_03 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Looks like we'll get a chance to settle this before we can move forward.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0]You gotta let me fight this one with you, [uf 4 1].[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_04 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]All right, you ready, then?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0]Let's show him what we're made of![n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_04 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]There's no one left in our way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The stage is set and our opponent's waiting. I'll give it everything I've got.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_05 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]This is it. Everything will be decided by this fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]I only made it this far because everyone here was in my corner. Now let's go grab our victory.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I got this.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_06 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]What're you waiting for?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_CHANGE__4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Then who should I switch with?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_05 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Our path of retreat's been cut off, and we're locked in a cage with the Shadow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Heh, this should be interesting.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_5 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]All right, let's get to it.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OVER_03 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The party is already full.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_CHANGE__5 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Who should I switch with?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_06 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Don't get overconfident.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_07 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]A Shadow and Strega... Fine. We'll take 'em both out in one fell swoop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I'm warmed up and ready to start when you are.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_08 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]I don't know what to expect, but if Strega's involved...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]It could be a trap, but we don't have much of a choice right now. Let's go.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_09 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]Whatever our opponent's like, it doesn't matter. It makes no difference to my fists.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_10 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Hey, so about Shinji...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]...Never mind. This is no time to get distracted. You ready?[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Yeah, all right.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_07 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3136 0 0]Hm? What's up?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Make sure you're confident with whoever you're bringing into battle.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_AFT_4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Yeah, all right.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OVER_04 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The party's full.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_11 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Now our true battle begins.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Let's go. Time for the final round.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_IN_AFTE_7 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]All right, let's go.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_08 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]You ready?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Let's knock it out in one round![n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_TKJ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]This isn't about revenge...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]This is about doing what needs to be done.[n][uf 1 1][e]

[msg MSG_SANADA_PARTY_OUT_CHI [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Huh... Her again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I'm concerned about Junpei. Let's move.[n][uf 1 1][e]

[msg MSG_0523_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]I can finally move around the way I want to again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Of course, I continued to train even while I was recovering.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]So I shouldn't be any less capable now. You can count on me.[n][uf 1 1][e]

[msg MSG_0602_0605_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]I'm looking forward to learning the truth behind those ghost stories.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, good luck with it.[n][uf 1 1][e]

[msg MSG_0606_0607_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]You have to get stronger in order to protect yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]And fighting in real battles is the best way to train for future battles, so let's go.[n][uf 1 1][e]

[msg MSG_0613_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Mitsuru's coming back to fight, and Yamagishi will be providing assistance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Battles are going to get more interesting. As the leader, you better get motivated.[n][uf 1 1][e]

[msg MSG_0623_0707_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]The further up we go, the stronger our enemies become.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Make sure you know all our strengths and weaknesses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I don't want us to get wiped out because we were careless.[n][uf 1 1][e]

[msg MSG_0709_0717_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3121 0 0]I didn't expect the Shadows at the hotel to attack us mentally.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]It was a good lesson in expecting the unexpected, even if it wasn't exactly an enjoyable experience.[n][uf 1 1][e]

[msg MSG_0718_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Our trip to Yakushima's coming up, but don't start slacking just yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The Shadows aren't going to take it easy on us.[n][uf 1 1][e]

[msg MSG_0724_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Honestly, I thought an "anti-Shadow weapon" would be something more imposing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]But, for the most part, she looks just like a regular human.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, I'm sure she'll seem more like a weapon in battle.[n][uf 1 1][e]

[msg MSG_0725_0805_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]The news of Amada joining us in the dorm sure was unexpected, even if it's only temporary.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Honestly, I've got reservations about this... But that doesn't matter right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Getting distracted by outside things while in Tartarus is only going to end in failure.[n][uf 1 1][e]

[msg MSG_0806_0809_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]If you don't want miserable test scores, you should take advantage of your summer classes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]What'll be your excuse if you get poor grades? "I was fighting monsters in the school at night"?[n][uf 1 1][e]

[msg MSG_0810_0820_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Unlike us, Koromaru can't tell us when he's hurt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]We'll have to keep a close eye on him.[n][uf 1 1][e]

[msg MSG_0821_0827_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Are you bummed that you're spending your summer break exploring Tartarus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, think about it like this: it's a unique experience most people will never have.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]How's that for summer memories?[n][uf 1 1][e]

[msg MSG_0828_0902_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Shadows will attack anyone, even children.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I'm impressed with Amada. He asked to join our group, even though he knew the risks.[n][uf 1 1][e]

[msg MSG_0903_0904_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3131 0 0]I can't believe I can fight alongside him again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]I'm glad I was persistent.[n][uf 1 1][e]

[msg MSG_0919_1003_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]There are only three more Shadows...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The countdown has begun... But don't let your guard down until it's all over.[n][uf 1 1][e]

[msg MSG_1005_1016_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Don't bring your emotions into Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]That may sound cold, but your life is constantly on the line here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]If you let yourself get distracted, you'll just be making yourself an easy target.[n][uf 1 1][e]

[msg MSG_1019_1102_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]We'll be saying farewell to Tartarus soon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I'd always wanted it to disappear, but now that it's actually going to happen, it doesn't feel real.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, I'll be sure to raise as much hell as I can here in the meantime.[n][uf 1 1][e]

[msg MSG_1106_1109_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3090 0 0]Of course, right when we thought Tartarus was finally going to disappear...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I guess we have to keep putting up with this damn tower.[n][uf 1 1][e]

[msg MSG_1110_1117_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3048 0 0]Are you worried about Mitsuru?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, I don't think there's anything we can do...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Just worry about yourself for now. You never know when a Shadow's going to attack.[n][uf 1 1][e]

[msg MSG_1121_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 3 0 65535 3092 0 0]Tartarus seems like heaven compared to the hell of Mitsuru's execution.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 4 25 4]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0]Though it's pretty pathetic thinking that way, too...[n][uf 1 1][e]

[msg MSG_1121_SANADA_DUNGE_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3112 0 0]I'm relieved Mitsuru's back to her old self.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Now I can fully concentrate on Tartarus.[n][uf 1 1][e]

[msg MSG_1122_1127_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]I know that if we push Junpei forward, he'll be able to take that first step towards getting better.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]The problem is figuring out how to do it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I wish there was a good way.[n][uf 1 1][e]

[msg MSG_1203_1213_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]You probably have a million things running through your head, but focus on Tartarus for now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Getting yourself killed before the world ends would just be pathetic.[n][uf 1 1][e]

[msg MSG_0101_0114_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]The battle with Nyx will be tough.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]We have to train as much as we can beforehand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]And the Shadows are always getting stronger too. Don't underestimate them.[n][uf 1 1][e]

[msg MSG_0115_0130_SANADA_DUN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]I tried thinking about what the battle with Nyx would be like, but I gave up pretty quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Shinji would be disappointed with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]He'd say something like, "If you've got time to daydream, you've got time to fight."[n][uf 1 1][e]

[msg MSG_0131_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]This day has been a long time coming...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]There's no point getting antsy on the day of the fight. But you probably know that by now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Let's leave it all in the ring.[n][uf 1 1][e]

[msg MSG_HANYOU1_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Shadows spawn without limit here. In terms of sheer numbers, they've got the upper hand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]To offset our disadvantage, we'll have to strategize. Exploiting weaknesses is an example.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]But the first strike is crucial, too. Don't let them see you coming.[n][uf 1 1][e]

[msg MSG_HANYOU2_SANADA_DUNGE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]If you skimp on items, you'll be sorry when you take a wallop from an enemy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]But using items excessively isn't good either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Figuring out a good balance for item use is an important part of combat strategy.[n][uf 1 1][e]

[msg MSG_SANADA_ZEKKOCHO [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Hey, put me on the attack today. I'm itching for a good fight.[n][uf 1 1][e]

