[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]'Sup?[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]*whine*[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Junpei-kun... Koro-chan...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 0 0 0 4 0 0]......[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]So... I think I mostly get what's goin' on.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0]That's... what happens to the losers, huh?[n][uf 1 1][e]

[msg MSG_006_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]That's correct.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]And no one's taking my sister's key... no matter who we have to beat.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]That's what I expected from li'l sis, but... Aigis, what about you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]You wanna redo the past, or move forward?[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Huh... Well, I didn't exactly make a choice myself, but I've been thinking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]The past or the present... I dunno, I feel like that's the wrong way to look at it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 13 0 0]And maybe... Maybe the problem's us for seein' it that way.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 14 0 0]I mean, just look at us! Beatin' each other down 'cause we can't agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Do we really got what it takes to go back and make an even better future?[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 16 0 0]What if we end up makin' a worse future instead?[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Huh...!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Look, I get that we don't got much time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 1 0 0 19 0 0]But if we rush this fightin' each other, no question we're gettin' a worse future.[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 20 0 0]So, this is my choice, and I'm standin' by it all the way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 21 0 0]If we gotta fight anyway, then I'll just knock some sense into all of ya! That's the best I got.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 1 25 25]Heh... If he was here... I bet he'd know what to do.[n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 0 0 0 23 0 0]......[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 12 3 54 65535 0 0][uf 3 1 1 0 0 24 0 0]Junpei-san...[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Sorry, Aigis, but you can't be the one movin' on to the finals if you don't even know what you wanna do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 26 0 0]So I gotta do it myself, no matter how tough it gets.[n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Arf![n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Ha... Thanks, Koromaru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Alright, I'm ready! Let's get this show on the road![n][uf 1 1][e]

