[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 2 3 25 25]Why am I only ever right about the worst things...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 3 0 0]Am I stupid for trusting in something so blindly?[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 4 0 0]Dad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 5 0 0]I got this letter from you last spring.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 6 0 0]I must've read it a thousand times since then.[n][uf 1 1][e]

[msg MSG_001_0_0 [Letter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]"To my family, ten years into the future."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]"Tomorrow, I'll bring this letter to the opening ceremony for the Moonlight Bridge."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]"It will be stored in a time capsule, and sent to you in ten years' time."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]"Yukari... You may be small now, but in ten years, you'll be sixteen. You'll be in high school."[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 0 0 0 11 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Letter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]"I know you've been sad because I have to work so late, but you always manage to greet me with a smile."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]"I'm really proud of myself. Kirijo-san appointed me Head Researcher."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]"I'll be starting on a big project soon. It feels good to receive so much recognition for my work."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]"But I swear to you, nothing is more important to me than you and your mother."[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Oh, Dad...[n][uf 1 1][e]

[msg MSG_005_0_0 [Letter]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]"Yukari... I wonder. Are you enjoying life? Do you have high hopes for the future?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]"Do you still look towards tomorrow with excitement and wonder, like you do now?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]"No matter what happens in the next ten years, I hope you're happy."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]"And I hope this letter brings a smile to both you and your mother's faces."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]"Eiichiro Takeba. March 6th, 2000."[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 22 0 0]No matter what happens, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 0 0 0 23 0 0]......[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 24 0 0]All I can do is believe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 0 0 0 25 0 0]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 26 0 0]I won't turn my back. I won't be like Mom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 27 0 0]Not ever.[n][uf 1 1][e]

