[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 155 65535 0 0][uf 3 1 1 0 0 1 0 0]I don't know how, but we made it out, all thanks to you, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 155 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 3 25 25]One wrong step, and Mitsuru would've had our heads.[n][uf 1 1][e]

[msg MSG_000_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 155 65535 0 0][uf 3 1 1 0 0 3 0 0]Uh... Where'd Junpei and Mochizuki go?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Huh? Junpei-kun and Ryoji-kun are lying on the ground over there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Their faces are all red. Are they okay?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]I bet they were doing something stupid again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Just leave 'em alone.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 155 65535 0 0][uf 3 1 1 0 0 8 0 0]Looks like the heat got to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 155 65535 0 0][uf 3 1 1 0 0 9 0 0]Guess they got what was coming.[n][uf 1 1][e]

