[sel SEL_ENTER_00 top]
[uf 0 5 65278][uf 2 1]Yes.[e]
[uf 0 5 65278][uf 2 1]No, actually.[e]

[sel SEL_ENTER_01 top]
[uf 0 5 65278][uf 2 1]Let's go.[e]
[uf 0 5 65278][uf 2 1]Not yet.[e]

[msg MSG_ENTER_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]Are you ready to start exploring?[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_OK_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Okay, I'll let the others know.[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_NO_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I understand. You can never be too prepared.[n][uf 1 1][e]

[msg MND_NO_ENTER_AEGIS_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Now's not the time for exploring...[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5089 0 0]Heading to the Desert of Doors, Aigis?[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_OK_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]All right... I'll let Metis know, then.[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_NO_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]Okay. Let me know when you're ready, then.[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]You want to go to the Desert of Doors?[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_OK_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]All right, I'll let everyone know... Good luck, Aigis.[n][uf 1 1][e]

[msg MSG_ENTER_FUKA_NO_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Okay then. I'll use this time to get myself ready, too.[n][uf 1 1][e]

[msg MSG_ENTER_JUNPEI_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Oh, by the way—Ai-chan, have you heard about this?[n][uf 1 1][e]

[msg MSG_ENTER_JUNPEI_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]I guess the flower shop's opening a new branch at Paulownia Mall. They've been handing out flyers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0]Doesn't mean much to me, but maybe you can check it out if you're interested.[n][uf 1 1][e]

