[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]There it is![n][e]

[msg MSG_000_3_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Whoa, the hell is this...?[n][e]

[msg MSG_000_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]That's our target?[n][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]It has to be. There's nowhere else to go![n][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]You're approaching the other train! Hurry![n][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Hurry? What're we even supposed to do here!?[n][e]

[msg MSG_003_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]...!?[n][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Whoa![n][e]

