[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I gave it my all working part-time,[n]attending to customers...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I detailed various products[n]to a number of patrons...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I crammed information about charmstones[n]in order to improve my sales pitch...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I was taught about the products and[n]their connections to various practices...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I worked hard to serve customers in a store[n]dedicated to relaxation and healing...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I worked hard, surrounded by crystals[n]that were glowing mysteriously...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Tired customers left the store[n]looking completely rejuvenated...![n][uf 1 1][e]

[msg MSG_008_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]All right, I'm going to increase your hourly wage! People need to be rewarded for their hard work.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Since I'm getting the hang of things,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_010_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]Hey, a customer complimented you earlier. You should work here full-time after you graduate![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Since I've gotten better at my work,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_012_0_0 [Manager]]
[uf 0 5 65278][uf 2 1][uf 5 21 0 10]Here you go. Come by and help out again when you feel like it.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]After working awhile with spiritual[n]gemstones, my [uf 4 30 0 1 1 0][n]and [uf 4 30 1 1 1 0] increased...![n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]It's getting late... I should[n]head back to the dorm.[n][uf 1 1][e]

