[msg MSG_000_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Meow.[n][uf 1 1][e]

[msg MND_000_1_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat looks carefree.[n][uf 1 1][e]

[msg MSG_003_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Mewww.[n][uf 1 1][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat is staring at the boy.[n][uf 1 1][e]

[msg MSG_007_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22602 0 0]Mrowwl.[n][uf 1 1][e]

[msg MND_008_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat is staring at the boy...[n][uf 1 1][e]

[msg MSG_009_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22602 0 0]Hssss...![n][uf 1 1][e]

[msg MND_010_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]His fur is standing upright. He seems[n]to be bothered by something...[n][uf 1 1][e]

[msg MSG_011_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Meww...?[n][uf 1 1][e]

[msg MND_012_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat's head is cocked to one side.[n][uf 1 1][e]

[msg MSG_013_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Mew...[n][uf 1 1][e]

[msg MND_014_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat is sitting very still[n]with half-closed eyes.[n][uf 1 1][e]

[msg MSG_015_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Meow...[n][uf 1 1][e]

[msg MND_016_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat is looking around...[n][uf 1 1][e]

[msg MSG_017_0_0 [Stray Cat]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_018_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The cat is staring into space...[n][uf 1 1][e]

