[msg MSG_000_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]My friend has a cat, and it's sooo cute![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I want one too, but my mom hates animals...[n][uf 1 1][e]

[msg MSG_001_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I played with my friend's cat at his house again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]*sigh* I want a cat, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I know my mom hates animals, but maybe I should ask her...[n][uf 1 1][e]

[msg MSG_002_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I asked my mom for a cat, and she said no.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]"No," "No," "No"... That's all she ever says.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]*sigh* I want a cat...[n][uf 1 1][e]

[msg MSG_003_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I tried to convince my dad to get a cat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]He said no, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Cats cost a lot, and their food and stuff costs a lot too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]So we can't afford one.[n][uf 1 1][e]

[msg MSG_004_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I asked my friend if his cat was really expensive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]You know what? He said it was free![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]He said his mom got the cat from the animal shelter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I didn't know you could do that. I thought you could only get cats from pet stores.[n][uf 1 1][e]

[msg MSG_005_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I talked to my dad about getting a cat again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I told him cats from the animal shelter are free...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]But he still said no.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Even though he's okay with it, if my mom says no, he has to say no, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]So only my mom can decide... My dad sucks.[n][uf 1 1][e]

[msg MSG_006_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]My friend at school said there was a stray cat around here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm waiting here until he comes out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm not gonna catch him or anything, I just want to see him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I wonder what kind of cat he is...[n][uf 1 1][e]

[msg MSG_007_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]You know how there's a lot of food places here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]That stray cat gets leftovers from the owners.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I asked them what time the cat usually comes, and they told me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm gonna see that cat no matter what![n][uf 1 1][e]

[msg MSG_008_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]What kind of cat do you think this is?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I don't know.[e]
[uf 0 5 65278][uf 2 1]A stray cat.[e]
[uf 0 5 65278][uf 2 1]I don't care.[e]

[msg MSG_010_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Okay! Then I'll tell you![n][uf 1 1][e]

[msg MSG_011_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Aww... You could tell, huh?[n][uf 1 1][e]

[msg MSG_012_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]You're so mean! But I'll tell you the answer anyway...[n][uf 1 1][e]

[msg MSG_013_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]It's a stray cat![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]But he's my friend. The first time I met him, he didn't even run away. He came up to my hand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]So that means he's my "soulmate," right?[n][uf 1 1][e]

[msg MSG_014_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]He only eats leftovers from the shops...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I think he's getting tired of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Maybe I should get a saucer of milk for him![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Yeah, I'm gonna go buy some milk. He'll like that, I think.[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]That's a good idea.[e]
[uf 0 5 65278][uf 2 1]That's a bad idea.[e]

[msg MSG_016_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Yeah! He'll probably love it![n][uf 1 1][e]

[msg MSG_017_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]R-Really!? He'll get a stomachache if he drinks regular milk?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I didn't know that! Thanks so much for telling me![n][uf 1 1][e]

[msg MSG_018_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm gonna buy him some milk for next time.[n][uf 1 1][e]

[msg MSG_019_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]So regular milk is bad for cats... Okay, I'll remember that.[n][uf 1 1][e]

[msg MSG_020_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I asked my friends about what to feed cats, and I read about it, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I found out there's a lot of things that cats shouldn't eat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Like that milk I wanted to give him last time, that's one of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I was surprised, but I learned something.[n][uf 1 1][e]

[msg MSG_021_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I asked my dad if I can take this cat home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]He said he wouldn't mind, but it's all up to my mom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]*sigh* I know what she's going to say... What should I do...?[n][uf 1 1][e]

[msg MSG_022_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]What should I do? That cat went somewhere...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]No one knows where he went.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Maybe it was 'cause of that typhoon?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]If he could've come home with me before, this wouldn't have happened...[n][uf 1 1][e]

[msg MSG_023_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Hey, look! Look! The cat came back![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Wow... He survived the typhoon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Or did he just hide somewhere?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Well, it doesn't matter. Either way, I'm glad he's okay.[n][uf 1 1][e]

[msg MSG_024_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I decided I want to take that cat home with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm going to convince my mom to let me keep him as a pet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]No matter what she says, I'm not gonna back down.[n][uf 1 1][e]

[msg MSG_025_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]That man and the lady... The old man and old lady, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Why are they just standing there, staring at nothing...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Are they so tired that they don't want to do anything anymore?[n][uf 1 1][e]

[msg MSG_026_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]My mom said I can't have a cat, no matter what.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]But it's okay. My dad is on my side![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'm gonna learn all about cats, and show her I can take care of one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Then my dad will convince my mom![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I'll do my best![n][uf 1 1][e]

[msg MSG_027_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]It's getting cold...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I can just go inside, but I wonder about him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I heard there's a lot of warm places around here, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Is he really going to be okay?[n][uf 1 1][e]

[msg MSG_028_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I studied all about cats.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I learned cats can't see the color red. I wonder what that's like...[n][uf 1 1][e]

[msg MSG_029_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I studied all about cats, and I told my dad about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]He said I did a great job, and he was impressed![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]And he promised he was gonna convince my mom![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I hope I can get this cat...[n][uf 1 1][e]

[msg MSG_030_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]This cat has been acting weird. He keeps staring into space.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I don't understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]But I think my mom's going to let me keep this cat soon![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Today, when my dad comes home from work, we're going to ask together.[n][uf 1 1][e]

[msg MSG_031_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I tried putting on cat ears, but the cat still won't even look at me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Maybe if I had a cat toy... But I don't think I have enough to buy one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Oh! Is that a cat toy!? Do you have a pet cat?[n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]Nope. You can have this.[e]
[uf 0 5 65278][uf 2 1]Yeah, this is for my cat.[e]

[msg MSG_033_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I can!? Thanks![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]I should give you something in exchange... Oh, I know![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]You can have this cat ear headband. I don't need it anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Here you go.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Maybe Elizabeth would like this headband...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should try showing it to her.[n][uf 1 1][e]

[msg MSG_035_0_0 [Cat-Loving Boy]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 413]Oh, really? I wish I had a cat.[n][uf 1 1][e]

