[msg MSG_000_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Oh, are you interested in these Max Safety Shoes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]You have good taste! I can sell them to you for a reasonable price.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Let's say... How about just 20,000 yen?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Buy them[e]
[uf 0 5 65278][uf 2 1]Don't buy them[e]

[msg MSG_002_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Woohoo, lucky me! ...Er, by which I mean, "Lucky us"! Especially you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Well then, these Max Safety Shoes are all yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Hehe, nice doin' business with ya![n][uf 1 1][e]

[msg MSG_003_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Woohoo, lucky me! ...Wait, you ain't got enough money...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Listen, I can't lower the price any more. If you want 'em, you gotta have the money for 'em.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]The hell? You're wastin' my time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]If you don't need nothin', then get outta here. I'm a busy man![n][uf 1 1][e]

[msg MSG_005_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Still need something? Sorry, kid, but I'm busy.[n][uf 1 1][e]

[msg MSG_006_0_0 [Shady-Looking Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 431]Hm, you need something? I'm busy getting ready to sell shoes.[n][uf 1 1][e]

