[msg MSG_000_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I've known that girl since we were in elementary school together. She loves fortune telling stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She used to pull out these weird props from her bag...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She claimed they were her lucky charms.[n][uf 1 1][e]

[msg MSG_001_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I didn't know she was a fortune-teller.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I guess she does look weird, sitting there all by herself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]A fortune-teller, huh...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]That girl's been shy all her life. She doesn't talk to people she doesn't know easily.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Though I guess that fortune-teller does have a different air about her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She seems like someone who has something special.[n][uf 1 1][e]

[msg MSG_003_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Her fortunes are abstract, but she's not trying to confuse you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]You're meant to interpret them, and decide how to act from there.[n][uf 1 1][e]

[msg MSG_004_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Well, normally, meeting new friends is something that just happens.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]In this case, I guess you might rely on fortune telling, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]It's not my style.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I'd rather look for friends on my own.[n][uf 1 1][e]

[msg MSG_005_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Amazing! Her fortune came true...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She seems pretty caught up in the moment, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Is she going to be all right?[n][uf 1 1][e]

[msg MSG_006_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Amazing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I've got a few things I'd like to find, too. Maybe I should ask her...[n][uf 1 1][e]

[msg MSG_007_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I know there's such a thing as lucky colors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]But we're talking about clothes, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I think it's okay to just choose the clothes you like best...[n][uf 1 1][e]

[msg MSG_008_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I think all she needs to get closer to her friend is a better understanding.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She says she understands fine, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I'm not sure...[n][uf 1 1][e]

[msg MSG_009_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Something new about her friend, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Aren't you supposed to find stuff like that out on your own?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I have a really bad feeling about this.[n][uf 1 1][e]

[msg MSG_010_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She's a little too into this fortune telling stuff...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I don't think it's good for her.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]You should stop her.[e]
[uf 0 5 65278][uf 2 1]Why not just wait and see?[e]
[uf 0 5 65278][uf 2 1]Why not just leave her be?[e]

[msg MSG_012_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Yeah... I should confront her, huh?[n][uf 1 1][e]

[msg MSG_013_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]No... I should talk to her.[n][uf 1 1][e]

[msg MSG_014_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I can't do that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I should talk to her.[n][uf 1 1][e]

[msg MSG_015_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I told her she's getting obsessed with fortune telling, but she doesn't seem to listen to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I won't give up on her, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I'm her friend... She needs my help, especially at times like this.[n][uf 1 1][e]

[msg MSG_016_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Now does seem like the time to use fortune telling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]But I wonder what she was trying to say.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]"Light will pierce the shadow... Until then, have patience..."[n][uf 1 1][e]

[msg MSG_017_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]That stuff about not being able to order food without her fortune... She's just kidding, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Right...? Oh god...[n][uf 1 1][e]

[msg MSG_018_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]She can't go through the day without her fortune...? This is bordering on addiction.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]What should I do? Maybe I should ask Mama...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Wait, wouldn't it be weird to get a fortune-teller's advice on shaking an addiction to fortune telling?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Now I'm really lost...[n][uf 1 1][e]

[msg MSG_019_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]This is just wrong...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]But I can't do anything about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I can't stop her from doing what she thinks is right.[n][uf 1 1][e]

[msg MSG_020_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]A puppet who obeys fortune-tellers, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]That sounds like a pretty accurate description to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I hope she wakes up soon...[n][uf 1 1][e]

[msg MSG_021_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]That girl disappeared... She hasn't even been home...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I should've tried harder to stop her...[n][uf 1 1][e]

[msg MSG_022_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]They say if you truly believe, nothing can go wrong, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]Isn't that the way those cultists think, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I think it's better to decide things for yourself and not rely so much on others...[n][uf 1 1][e]

[msg MSG_023_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]A puppet who obeys fortune-tellers, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]That sounds like a pretty accurate description to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I hope she wakes up soon...[n][uf 1 1][e]

[msg MSG_024_0_0 [Candid Woman]]
[uf 0 5 65278][uf 2 1]The girl that I always came here with was finally found...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But she seems like just a husk of her old self. I guess it's that Apathy Syndrome thing people have been getting these days...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 406]I have no other choice but to stay by her side now...[n][uf 1 1][e]

