[msg MSG_000_0_0 [Elderly Man Taking a Break]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]Hello there. My, my, you look like a pleasant young'un.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]What are you doing at a shrine, though? You don't look like the prayerful type...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]Me? Well, I've come a long way to pray to the god here. He's a strong one![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]The offertory box and the written fortunes both bring great blessings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]Then there's Inari-san by the red gates... Whoo! Some crazy things might happen if you pray to him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 427]But you have to pray for a long time... It's no problem for me, but some people might be too busy.[n][uf 1 1][e]

