[msg MSG_000_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]Th-The weather is nice today...[n][uf 1 1][e]

[msg MSG_000_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah. It is, isn't it?[n][uf 1 1][e]

[msg MSG_003_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]H-How's your club going?[n][uf 1 1][e]

[msg MSG_006_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Eh, not bad.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]D-Do you think I could become a first-stringer...?[n][uf 1 1][e]

[msg MSG_007_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Sure. If you work hard, I think you can make it.[n][uf 1 1][e]

[msg MSG_006_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]I-It's getting hot outside, huh?[n][uf 1 1][e]

[msg MSG_009_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah. Summer's almost here.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]Th-The weather is nice... The sky is blue, and there's a cool breeze...[n][uf 1 1][e]

[msg MSG_011_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah. The sky's pretty.[n][uf 1 1][e]

[msg MSG_009_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]Th-There are a lot of weirdos out there... It's creepy, huh...?[n][uf 1 1][e]

[msg MSG_012_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah, it's pretty creepy.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]W-We couldn't go to the beach, but... how about the mountains?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]I-It'll be autumn pretty soon, so the leaves will turn red...[n][uf 1 1][e]

[msg MSG_014_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah, that'll be nice.[n][uf 1 1][e]

[msg MSG_013_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]Th-Thanks for looking at my report...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]I-I'd like to take you to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]No, wait! I-I take that ba—[n][uf 1 1][e]

[msg MSG_016_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Sure! Anywhere is fine with me.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]I-It's getting cold, huh? It's almost winter...[n][uf 1 1][e]

[msg MSG_018_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yup, almost winter indeed.[n][uf 1 1][e]

[msg MSG_021_0_0 [Shy Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]I'm really worried...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]We're spending so much time together... But I feel like it can't last.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 420]Is it just me...?[n][uf 1 1][e]

[msg MSG_023_5_0 [Calm Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]Yeah, it's just you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 421]This will never end...[n][uf 1 1][e]

