[msg MSG_000_0_0 [Weak Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22602 0 0]Mew...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]This cat looks very weak. It seems[n]like it might be hungry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should give it [uf 4 4 1 37 1 0]...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Give it [uf 4 4 1 37 0 0][e]
[uf 0 5 65278][uf 2 1]Don't give it anything[e]

[msg MSG_003_0_0 [Weak Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22602 0 0]...Mew.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]It's mewing very weakly. Maybe it's hungry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I don't have anything it can eat...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I can buy cat food somewhere...[n][uf 1 1][e]

[msg MSG_005_0_0 [Weak Cat]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Meow... Meowww...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]The cat is purring loudly. It seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe the cat will feel better if I come[n]back and feed it again tomorrow...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The cat is purring loudly. It seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Its purring seems more[n]energetic than it did last time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe the cat will feel even better if[n]I come back and feed it again tomorrow...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]The cat is purring loudly. It seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The light in its eyes has returned.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe the cat will feel even better if[n]I come back and feed it again tomorrow...[n][uf 1 1][e]

[msg MSG_009_0_0 [Energetic Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Meoooowwww!![n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]The cat is purring loudly. It seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]And it seems to have regained all[n]its energy by eating the cat food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I think it'll be okay without me[n]having to feed it anymore.[n][uf 1 1][e]

[msg MSG_010_0_0 [Energetic Cat]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 22601 0 0]Meoooowwww!![n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]The cat seems to have regained all[n]its energy by eating the cat food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It also seems to have grown...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I think it'll be okay without me[n]having to feed it anymore.[n][uf 1 1][e]

