[msg MSG_000_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Oh my! How did I forget to buy shampoo!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]No rush. Just wait for the sale.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Isn't Saturday the sale day at Aohige Pharmacy?[n][uf 1 1][e]

[msg MSG_002_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Aohige Pharmacy has sales on Saturdays, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Today's Saturday... We should stop by there later![n][uf 1 1][e]

[msg MSG_003_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]You see Mandragora, the karaoke studio at the top of those stairs?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I saw someone coming out of there alone. Were they singing alone...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Well, it's not that weird... But I bet you'd draw some strange looks from the staff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]It builds courage, in a way, to do whatever you want, no matter what other people may think.[n][uf 1 1][e]

[msg MSG_005_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Last week was my 15th wedding anniversary.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]But my lousy husband didn't give me anything! He didn't even remember it was our anniversary![n][uf 1 1][e]

[msg MSG_006_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]It makes you wonder why we even married them when they pull stuff like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]It doesn't take much to make us feel loved. Even a single flower from Rafflesia would do.[n][uf 1 1][e]

[msg MSG_007_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Did you hear? That, uh, what was it, the Apathy Syndrome?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]There was a victim at Gekkoukan High. He was friends with my son's senpai.[n][uf 1 1][e]

[msg MSG_008_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]A victim in your own neighborhood? Oh my... I guess we can't say it's none of our business now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My son's teacher's relative's son's calligraphy teacher caught Apathy Syndrome too.[n][uf 1 1][e]

[msg MSG_009_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I'm getting hungry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Should we stop somewhere and grab a bite to eat?[n][uf 1 1][e]

[msg MSG_010_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Ooh, let's get some of Octopia's takoyaki![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]It's at the Iwatodai strip mall, so we'll have to take the monorail.[n][uf 1 1][e]

[msg MSG_011_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I heard from my son that there's this freaky website on the Internet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Apparently, you can have someone carry out revenge for you.[n][uf 1 1][e]

[msg MSG_012_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]They have online revenge agents now!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I don't know much about computers, but that sounds terrifying...[n][uf 1 1][e]

[msg MSG_013_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I get tired of coming up with new things to cook for dinner.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]My family always complains when I end up making something similar to what they had for lunch.[n][uf 1 1][e]

[msg MSG_014_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My friend told me that, one time, her kid who goes to Gekkoukan bought a pork cutlet sandwich for lunch...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]And when she made him pork cutlet for dinner, he yelled at her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]She told him, "Well, you should've bought some sweet pastries or apple strudel instead."[n][uf 1 1][e]

[msg MSG_015_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Our kids are off on their summer vacation. I'm exhausted from making their meals every day.[n][uf 1 1][e]

[msg MSG_016_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]One of the women in my neighborhood says she precooks massive amounts of udon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Then she rotates between sesame dressing, ponzu, and shredded daikon so it always tastes differently.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I figure we housewives need summer vacation too, so I decided to copy her method.[n][uf 1 1][e]

[msg MSG_017_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Don't those kids look strange? That one near the clubhouse... Is he from Gekkoukan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]They look sort of slack and unmoving... Is he being lazy since it's summer vacation?[n][uf 1 1][e]

[msg MSG_018_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]One of the women in my neighborhood has a kid who goes to Gekkoukan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]But she's energetic and sweet—very different from those kids.[n][uf 1 1][e]

[msg MSG_019_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]My son became nocturnal over summer vacation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]He wakes up in the afternoon, leaves at night, and usually doesn't come back until sunrise.[n][uf 1 1][e]

[msg MSG_020_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Where do they go that late at night? That Escapade club?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]The security is too lax at those kinds of places. I heard they don't even care if a high school student just walks in wearing their uniform.[n][uf 1 1][e]

[msg MSG_021_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I think the hot summer sun got to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]See? My arms are burned and my skin is all rough.[n][uf 1 1][e]

[msg MSG_022_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Do you know the ramen restaurant Hagakure at the Iwatodai strip mall?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]The ramen they sell there has plenty of collagen to boost your beauty! That's what I heard, anyway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]If you make your skin more youthful, I bet your mind will follow, and your husband will love you more![n][uf 1 1][e]

[msg MSG_023_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]A woman in my neighborhood said part of her roof was destroyed by the typhoon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]No matter how much we try to prevent disasters, there's no way we can completely guard against them...[n][uf 1 1][e]

[msg MSG_024_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Well, I don't know. You can't trust those building contractors, you know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]It could be that her house was just made of cheap, non-regulation materials.[n][uf 1 1][e]

[msg MSG_025_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]That kid in front of the club bothers me... He's so motionless.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]He's from Gekkoukan, right? It's been a while since the second term started.[n][uf 1 1][e]

[msg MSG_026_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I understand how relaxed they are since autumn has just begun...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]But they seem too relaxed to me.[n][uf 1 1][e]

[msg MSG_027_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I was thinking of having my older son take the Gekkoukan entrance exam, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I don't want him to go to a dangerous school. Maybe I should reconsider...[n][uf 1 1][e]

[msg MSG_028_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]You mean the Gekkoukan student who was caught up in that fight? He died, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I feel sorry for him... He was too young to die. How could that have happened?[n][uf 1 1][e]

[msg MSG_029_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]The other day, my husband was saying that he's regained that passion he once had in his youth...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]It's quite suspicious... I wonder if he's cheating on me...[n][uf 1 1][e]

[msg MSG_030_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Maybe he just went to Be Blue V. You know, that healing shop next to the police station.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]They say going there can help you remember things you've long forgotten.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]We should go there sometime too![n][uf 1 1][e]

[msg MSG_031_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]H-Hey... Those motionless kids near the club...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Are they... Are they the ones with that Apathy Syndrome everyone is talking about?[n][uf 1 1][e]

[msg MSG_032_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Oh, you're worrying too much. Aren't they just relaxing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Although... they have been like that for a while. Are they going to stay there forever...?[n][uf 1 1][e]

[msg MSG_033_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]I heard the head of the Kirijo Group passed away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]His young daughter is all alone in the world now. He must regret having to leave her so early.[n][uf 1 1][e]

[msg MSG_034_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Well, officially, his death was due to illness. But judging by the way the man looked...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I think it might have been foul play. Maybe he was involved in organized crime...[n][uf 1 1][e]

[msg MSG_035_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Your daughter is looking so confident lately. She came over to say hi to me, and I didn't recognize her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Is she getting married? Or did she just get a boyfriend?[n][uf 1 1][e]

[msg MSG_036_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Oh, it's nothing like that... Do you see the Chagall Café next to the club?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My daughter said that just drinking their coffee makes you more charming. It's pheromones, or something...[n][uf 1 1][e]

[msg MSG_037_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]My son isn't stressed at all, even with exams coming up... I'm a little worried about him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Do you know the Wilduck Burger at the Iwatodai strip mall? He's trying something new on the menu every day.[n][uf 1 1][e]

[msg MSG_038_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]Is that the place that uses the mysterious ingredients? I doubt they'd use anything inedible...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]But I wouldn't be able to eat there. I don't have the courage those kids have to try weird food.[n][uf 1 1][e]

[msg MSG_039_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]My eldest is having his entrance exams soon. The atmosphere at home is very tense now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Even I get tense, remembering the time when I took my own exams...[n][uf 1 1][e]

[msg MSG_040_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I took my kid to the Iwatodai strip mall and we had lunch together at Wakatsu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My husband saw an ad for them that talked about omega-3s making you smarter or something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I don't know if my kid got smarter from eating the meal, but she did pass the exam.[n][uf 1 1][e]

[msg MSG_041_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]Did you see the news? Some thug broke into the hall where the university testing is held...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]My eldest is entering high school next month... I'm worried.[n][uf 1 1][e]

[msg MSG_042_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My neighbor's son was apparently taking the test then...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]He said the man was screaming "Nyx" or something with a crazed look on his face...[n][uf 1 1][e]

[msg MSG_043_0_0 [Short-Haired Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]You know how that cult is spreading all over the country now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 502]D-Do you think there are cultists in this mall right now...?[n][uf 1 1][e]

[msg MSG_044_0_0 [Talkative Housewife]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]My neighbor's kid was approached by one of them too, something about "the Fall"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 503]I-I think there really might be some cultists here... The people around us look suspicious...[n][uf 1 1][e]

