[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 1 0 0]So, the Shadow controls a whole underground network...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]This is a problem. We have no means of attack.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 3 0 0]Your notes from previous battles mentioned a Shadow that was able to take control of the monorail.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 4 0 0]I'm guessing this Shadow must have its own body, just like that one.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 0 5 0 0]Let me see if I can pinpoint it.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 50 0 0][uf 3 1 0 0 0 6 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Fuuka...[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Even if we know where it is, we still have to get to it...[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]If it's abandoned, there may still be a way to enter the facility where the cables converge.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]We'll see...[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 11 0 0]Ah... Hah... I found it.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 12 0 0]It's here... in the mall![n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 13 0 0]In here!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 14 0 0]It's inside a small chamber underground.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 15 0 0]It's rectangular, so I assume it's man-made.[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Is it some sort of basement?[n][uf 1 1][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Wait a minute...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]I overheard the manager of Escapade a while back...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 19 0 0]He was sayin' the power supply's been acting up lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 20 0 0]There was a big outage because of it that forced him to cancel some important event.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]An outage?[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Yeah. Mentioned they remodeled the basement into a control room a while ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Maybe we should take a look...[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 0 24 0 0]That's got to be it![n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Good job, Yamagishi.[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 26 0 0]All right. As soon as we're ready, we'll make our move![n][uf 1 1][e]

