[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10887 0 0]...I guess I kinda stand out like a sore thumb. Maybe I shouldn't have worn my track suit...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Eh, I'll just think of it as part of my mental training.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]This is kind of a weird thing to bring up, but I actually, uh... How do I put it...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]I crack under pressure. Like, I get really nervous and stuff. I've gotten a lot better lately though.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10871 0 0]The more I want to win, I can just feel myself tense up...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]It's a part of who you are.[e]
[uf 0 5 65278][uf 2 1]You can get through this.[e]
[uf 0 5 65278][uf 2 1]Winning isn't everything.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10828 0 0]But if you don't try to overcome your weakness... isn't that kinda like running away?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]You know how they say you gotta "run away to fight another day"? Yeah, that's not my style.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto's mood has soured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10820 0 0][uf 5 13 8 15 105]Yeah, you're right! Whining won't get me through this—only mental strength will![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 4 23 0 105 3 25 25]...Actually, I dunno, man. Maybe that won't be enough this time. What exactly am I missing...?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto is deep in thought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10850 0 0][uf 5 13 8 30 105]So, you're telling me not to think about it? I dunno if I can, man...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]But... I see where you're coming from. That's kinda deep.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems impressed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10883 0 0]Wish they'd hurry and tell me what's up with my knee though... The suspense is killing me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]I'm feeling pretty good today, so maybe I'll jog a bit on my way back home.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After I saw Miyamoto off, I decided[n]to head back to the dorm.[n][uf 1 1][e]

