[msg MSG_000_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 2]I just had a call with your mom about your knee.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 21 0 3]You're throwing caution to the wind, young man...[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 3 0 0]That blabbermouth![n][uf 1 1][e]

[msg MSG_003_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]I want you to stop before things get any worse, you got that?[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 5 0 0]Please, don't do this to me... I need to practice.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 101 65535 0 0][uf 3 1 1 0 0 6 0 0]I heard, Kaz.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 7 0 0]Yuko!? And [uf 4 1], too!?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 8 0 0]Take some time off, Kaz! Practice can wait till you're all better.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 9 0 0]I can't! I don't have time![n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 101 65535 0 0][uf 3 1 1 0 0 10 0 0]Huh? What's the rush? Why do you do these things to yourself?[n][uf 1 1][e]

[msg MSG_010_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2][uf 4 1], you've been hanging around with Miyamoto lately, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 2]You must know what's going on.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]I don't know anything.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 13 0 0]Stop. Stop... I don't want you to lie for me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 8 5 105]......[n][uf 1 1][e]

[msg MSG_013_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 15 0 0]W-Wait! [uf 4 1] has nothing to do with this![n][uf 1 1][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 16 0 0]I don't want you to get dragged into this, so I'll come clean.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto is trying to protect me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 17 0 0]So the truth is...[n][uf 1 1][e]

[msg MSG_017_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 18 0 0]...And that's the gist of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 2 25 25]So I need to practice! I have to win, or else...[n][uf 1 1][e]

[msg MSG_018_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 2]I know how you feel, Miyamoto, but...[n][uf 1 1][e]

[msg MSG_019_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 21 0 0]It all depends on me if my nephew ever walks again![n][uf 1 1][e]

[msg MSG_020_0_0 [Someone's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]So that's what's going on.[n][uf 1 1][e]

[msg MSG_021_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 4]I don't mind if he competes in the regionals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 4]It's just the individual competition, so we don't have to worry about him bringing us down.[n][uf 1 1][e]

[msg MSG_022_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 2]Hey, what happened to practice?[n][uf 1 1][e]

[msg MSG_023_0_0 [Third-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 5]We were worried about Miyamoto.[n][uf 1 1][e]

[msg MSG_024_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 27 0 0]Guys...[n][uf 1 1][e]

[msg MSG_025_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 2]I'll let you keep training for now, and we'll see how things go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 2]But if I tell you to stop, I'm sorry. You're gonna have to listen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 2]And I want you to go home today. Your mother will be upset with me if I let you stay.[n][uf 1 1][e]

[msg MSG_026_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 31 0 0]Sorry, Coach. Everyone, I...[n][uf 1 1][e]

[msg MSG_027_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 0 0][uf 5 21 0 2]I think we're done here. The rest of you, back to training![n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]I finished training with everyone[n]and went back to the dorm.[n][uf 1 1][e]

