[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I ordered shoyu ramen with pork.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the collagen in the food, I feel[n]like the texture of my skin has improved...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I drank every drop of[n]the collagen-rich soup...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the plump pork belly,[n]my skin feels more supple...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I ordered the Special Hagakure Bowl.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I felt my body's radiance[n]increase with each bite...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The pork belly and boiled eggs are delicious.[n]Every cell in my body is rejoicing...![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]The special-made pork belly[n]is bursting with collagen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my skin has become smoother...![n][uf 1 1][e]

