[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I feel as if I've become an entirely different person compared to when I first set foot in your world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_000_3_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]If I stay on this side any longer, I fear I will forget my duties entirely...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]But I understand that wouldn't be ideal for you.[n][uf 1 1][e]

[msg MSG_000_7_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]That is why... I am drawing the line—no more visits here. I shall remain on my side.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]...Thank you very much for acting as a guide on my journey of discovery.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 202 1 25 25]I am truly grateful...[n][uf 1 1][e]

[msg MSG_001_5_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 202 0 25 25]Now then, though the sorrow may be sweet... let us part.[n][uf 1 1][e]

[msg MND_002_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I returned to the Velvet Room with Elizabeth.[n][uf 1 1][e]

