[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]A treasurer who's not even good at math... Doesn't that sound pathetic?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I never even wanted this job... Someone else entered me into the running. I didn't think I would actually get elected though...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...Oh! But I don't regret joining the student council or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]If I hadn't joined, then I wouldn't have met such kind people, like you, or the president.[n][uf 1 1][e]

[msg MSG_002_0_0 [Garish Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 150]...Shut up. You're distracting us.[n][uf 1 1][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh...! I-I'm... I'm sorry...[n][uf 1 1][e]

[msg MSG_004_0_0 [Garish Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 150]If you're gonna flirt with each other, go do it outside.[n][uf 1 1][e]

[msg MSG_005_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 100]I'm so tired of this. I can't even pick up my pencil anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 100]...But if you give me a kiss, maybe I can study for another thirty minutes.[n][uf 1 1][e]

[msg MSG_006_0_0 [Garish Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 150]What're you going on about now...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 150]C'mon, you gotta take this seriously. Don't you want us to go to the same college?[n][uf 1 1][e]

[msg MSG_007_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 100]Just gimme a kiss! Please![n][uf 1 1][e]

[msg MSG_008_0_0 [Garish Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 150]...All right, fine.[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]They're really gonna kiss...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]...Do they not know where they are!?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]They have no shame.[e]
[uf 0 5 65278][uf 2 1]They're gonna kiss...?[e]
[uf 0 5 65278][uf 2 1]Where did they go?[e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 5 13 9 5 109]That's right, [uf 4 1]-san! I agree![n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]This is supposed to be a place of learning. And they're still just kids![n][uf 1 1][e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]That's not what's important right now![n][uf 1 1][e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]This is supposed to be a place of learning. And they're still just kids...![n][uf 1 1][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I don't know! And I don't want to know![n][uf 1 1][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]This is supposed to be a place of learning. And they're still just kids...![n][uf 1 1][e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]So I say this, as a member of the student council...[n][uf 1 1][e]

[msg MSG_018_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]That kind of inappropriate behavior should not be tolerated at school![n][uf 1 1][e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]We should notify the student council president right away, and discuss this at our next meeting![n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]I agree.[e]
[uf 0 5 65278][uf 2 1]That's kind of extreme...[e]
[uf 0 5 65278][uf 2 1]You don't like kissing?[e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 5 13 9 5 109]If you're on my side, [uf 4 1]-san, then I have nothing to fear![n][uf 1 1][e]

[msg MSG_022_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]...I'm sorry. I shouldn't be raising my voice in the library...[n][uf 1 1][e]

[msg MSG_023_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]What do you mean by that? You... You really don't think it's a big deal!?[n][uf 1 1][e]

[msg MSG_024_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Ah... I'm sorry. I shouldn't be raising my voice in the library...[n][uf 1 1][e]

[msg MSG_025_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Th-That's not the point here! I'm just trying to say that there's a time and place for everything![n][uf 1 1][e]

[msg MSG_026_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]...Oh no, I...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I shouldn't be raising my voice in the library...[n][uf 1 1][e]

[msg MSG_027_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I-I don't mind if I get in trouble, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]I don't want you to get criticized too, [uf 4 1]-san...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]I can tell Chihiro is concerned about me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_030_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Oh, I didn't notice the time![n][uf 1 1][e]

[msg MSG_030_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Um... I think I'm going to be stuck here for a while, so... you don't need to wait for me.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Chihiro, then[n]headed back to the dorm.[n][uf 1 1][e]

