[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Why don't we try adding some spice today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Go ahead and blend it however you like.[n][uf 1 1][e]

[msg MND_001_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]I enjoyed brewing tea with Mitsuru...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 4 1 5]I always find this to be so relaxing... I suppose you could call it a moment of bliss.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Let me know whenever you're in the mood for more tea. I'd be happy to treat you.[n][uf 1 1][e]

