[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]This is... a box full of sawdust...[n][uf 1 1][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]...Today, we're usin' that to make tempura bowls.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Go ahead and take out what's in the box.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's a box of shrimp![n]Living... wriggling... shrimp...[n][uf 1 1][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 6 159 65535 0 0][uf 3 1 1 0 0 3 0 0]Getting these delivered is a royal pain in the ass, so I went and got 'em just now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 10 0 25 25]I'm gonna get the other stuff ready. You focus on prepping those guys.[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Leave it to me.[e]
[uf 0 5 65278][uf 2 1]Let's do it together.[e]
[uf 0 5 65278][uf 2 1]I can't do living things...[e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 5 0 0]Yeah, it's all you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 10 0 25 25]I'll handle the first one, so pay attention and just do the same.[n][uf 1 1][e]

[msg MSG_007_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 6 159 65535 0 0][uf 3 1 1 0 0 7 0 0]...Sorry, but I gotta work on the fish and other parts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 10 0 25 25]I'll do the first one, and then you do the rest.[n][uf 1 1][e]

[msg MSG_007_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]First, put it on its back. Then, you work the knife into the edge of the shell...[n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 159 65535 0 0][uf 3 1 1 0 0 10 0 0]Don't get squeamish on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 10 0 25 25]I'll do the first one, and then you do the rest.[n][uf 1 1][e]

[msg MSG_008_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 12 0 0]First, put it on its back. Then, you work the knife into the edge of the shell...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I struggled to prep the live shrimp,[n]following Aragaki's instructions...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We managed to work together[n]to finish the tempura bowls![n][uf 1 1][e]

[msg MSG_010_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]...The taste is pretty good, although I guess we did use good shrimp.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 14 0 0]You've gotten a lot better too. You're more comfortable with the knife and fryer now.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 15 0 0]All you gotta do now is keep practicin'.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0]Get the basics down, then just find the right way to cook the stuff you have.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 10 1 25 25]...That's how I was taught.[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]You had a great teacher.[e]
[uf 0 5 65278][uf 2 1]Who'd you learn from?[e]

[msg MSG_013_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 18 0 0]Hah, more like, a stubborn old man.[n][uf 1 1][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 19 0 0]I'd say... he was an oddball who couldn't mind his own business.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 20 0 0]A long time ago, I used to work part-time at a restaurant.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 21 0 0]The manager drilled me on how to cook. He gave me so much shit back then, but...[n][uf 1 1][e]

[msg MSG_015_2_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 22 0 0]When I think back on it now, it wasn't really a bad experience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 23 0 0]He always used to say, "Learning to cook is the first step to supporting yourself."[n][uf 1 1][e]

[msg MSG_015_4_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 24 0 0]But, not only that...[n][uf 1 1][e]

[msg MSG_015_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 25 0 0]If I didn't know how to do it myself, I wouldn't be teaching you like I am right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 26 0 0]I ain't gonna teach you every little thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 10 1 25 25]I can at least be here to show you how it's done. Gives me somethin' to do, too.[n][uf 1 1][e]

[msg MND_015_7_0]
[uf 0 5 65278][uf 2 1]Aragaki has a genuine smile on his face...[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0]...Oh, right. Let's eat up and then put everything away.[n][uf 1 1][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 29 0 0]You can head back to your room once you're finished. I'll handle the cleanup.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 30 0 0]I'm gonna give some to Koro-cha— ...[n][uf 1 1][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 1][uf 3 1 1 0 0 31 0 0]...I gotta make Koromaru's dinner still.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 6 159 65535 0 1][uf 3 1 0 0 0 32 0 0][uf 4 23 0 10 6 25 25]......[n][uf 1 1][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 159 65535 0 0][uf 3 1 1 0 0 33 0 0]...You got a problem?[n][uf 1 1][e]

