[msg MSG_REUNION_YUKARI_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, there you are. I was taking a quick look up ahead![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Here you go. I picked this up while I was at it.[n][uf 1 1][e]

[msg MSG_REUNION_JUNPEI_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2013 0 0]Yo, found ya! I made sure to clear you a path.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Oh, here. I picked it off the ground earlier and thought of you![n][uf 1 1][e]

[msg MSG_REUNION_SANADA_00 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3010 0 0]There you are. I went ahead and scouted the area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Here, take this. I picked it up while I was looking around.[n][uf 1 1][e]

[msg MSG_REUNION_MITSURU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4009 0 0]Good, we've rendezvoused. I've already gone ahead and done some reconnaissance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I also found this. Put it to good use.[n][uf 1 1][e]

[msg MSG_REUNION_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5109 0 0]Looks like Koro-chan found something we could use! Good boy![n][uf 1 1][e]

[msg MSG_REUNION_AEGIS_00 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]I have been waiting for you. The path ahead has been cleared.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Also, this is for you. I collected it during my reconnaissance.[n][uf 1 1][e]

[msg MSG_REUNION_AMADA_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7011 0 0]Oh, there you are. I did a little scouting up ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I also found this. Here, Aigis-san.[n][uf 1 1][e]

[msg MSG_REUNION_KOROMARU_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf! Arf, arf![n][uf 1 1][e]

[msg MSG_REUNION_ARAGAKI_00 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9009 0 0]There you are. I checked out the area further ahead, so let's move.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Oh yeah... I picked this up, too. You hang onto it.[n][uf 1 1][e]

[msg MSG_REUNION_METIS_00 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]Hey, Sis! I finished scouting ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Oh, right. I found this on the way. Could it be helpful to you?[n][uf 1 1][e]

[msg MSG_REUNION_MITSURU_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Looks like you've all safely rendezvoused. Well done on the reconnaissance.[n][uf 1 1][e]

[msg MSG_REUNION_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]It seems like you all met up safely. Thank you for scouting ahead.[n][uf 1 1][e]

