[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Huh? Clothes shopping... with me?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 2 0 0]K-Keep your voice down![n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Sure! Let's go together next time, Mitsuru-senpai.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Go right, Fuuka. You gotta go around from the right.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]O-Okay... Huh?[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]No, no, that's left... Oh, wait. That's right for you, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Eh, whatever... Why don't you just climb to the top of the jungle gym?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]What!? I'm not going down the slide head-first. My clothes will get all dirty...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]When I was your age, we used to compete over who could slide down in the funniest way.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Funniest? Like what?[n][uf 1 1][e]

[msg MSG_008_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 8 4 25 25]Er— You don't have to take your shirt off! It's fine![n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Shake.[n][uf 1 1][e]

[msg MSG_010_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Woof.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]...Is "shake" the command given to request paws on one's head?[n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Woof.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I comprehend.[n][uf 1 1][e]

[msg MND_014_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]The day of the final battle draws near...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Everyone is having fun, as if trying[n]to make the most of this moment...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We spent a pleasant evening together...[n][uf 1 1][e]

