[msg MSG_000_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1091]Welcome! Take any open seat.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...He's not here.[n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh, uh, it's nothing![n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Sorry for asking you to go out all of a sudden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I just wanted someone to come with me. It's a little intimidating going to get food by myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]People tend to stare when they see an elementary school kid like me out on his own.[n][uf 1 1][e]

[msg MSG_004_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1091]Your order?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Two specials.[e]
[uf 0 5 65278][uf 2 1]Two regulars.[e]
[uf 0 5 65278][uf 2 1]A kid's ramen.[e]

[msg MSG_006_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1091]Two specials, comin' right up![n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Seems like that's the thing to get, huh. Thanks for ordering.[n][uf 1 1][e]

[msg MSG_008_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1091]Two regulars, comin' right up![n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Hm, looks like there's a special ramen too. I wonder if that's what most people get.[n][uf 1 1][e]

[msg MSG_010_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1091]Err, sorry, we don't have that here...[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I-I'm fine with the regular! I can totally eat that much![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 8 3 25 25]That was mean, [uf 4 1]-san... Please don't treat me like a kid.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]...So I saw some people from our dorm stop by here a while back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Like Sanada-san, and that guy who recently joined... Aragaki-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Do you come here with them too, [uf 4 1]-san? What kinds of things do you talk about?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...Oh, sorry for asking something so weird.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I just thought I should know a bit more about everyone, since we'll be fighting together from now on.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]But it's good either way, 'cause I've always wanted to have a proper chat with you, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Everyone in the dorm is amazing, but you're on a completely different level.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 8 0 25 25]I can't believe how many Personas you're able to use![n][uf 1 1][e]

[msg MSG_015_0_0 [Server]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 1091]Here you are![n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Ikutsuki-san and Mitsuru-san said that each person normally has only one Persona, and that it doesn't change.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 8 3 25 25]That means, what I saw back then was really...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]...Uh, it's nothing! Sorry. Shall we eat?[n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Whew, I finished all the soup too. I'm stuffed![n][uf 1 1][e]

[msg MSG_019_0_0 [TV Sound]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Phoenix Ranger Featherman R: The Melancholy of Swallow will air this winter as a TV special![n][uf 1 1][e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 0 0 0 31 0 0]Huh!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 8 1 25 25]Wow, a spin-off with Swallow as the main character! I gotta make sure I record that![n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Do you like that series?[e]
[uf 0 5 65278][uf 2 1]What's this about?[e]
[uf 0 5 65278][uf 2 1]That sounds interesting.[e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Yeah, I watch it every week without fail! But this TV special is big news![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Swallow doesn't usually make much of an impression, but there's a theory that he's actually stronger than Hawk![n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]They just announced a TV special for an ongoing superhero series![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]And it's with Feather Swallow. Out of the five members, he's the one you'd least expect![n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Yeah, it is! This is big news![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Swallow doesn't usually make much of an impression, but there's a theory that he's actually stronger than Hawk![n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Ah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 8 0 25 25]I, uh... heard that from a friend. TV shows like that seem to be popular in my class.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]I only watch them so I have something to talk about... Haha.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Anyway, it's been a while since I've enjoyed a meal like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]I guess it's because I'm eating with you, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0][uf 4 23 0 8 0 25 25]You're really easy to talk to, and the ramen was delicious. Maybe next time we can—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 0 0 0 45 0 0][uf 4 23 0 8 3 25 25]......[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]...Um, it's nothing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]It's getting late. We should start heading back.[n][uf 1 1][e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]It was... delicious?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]...No. This food was not delicious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 4 23 0 8 2 25 25]Don't let yourself think like that.[n][uf 1 1][e]

