[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]So, I was hoping you could watch me as I make the coffee...[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Thank you![n][uf 1 1][e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]Okay, the beans are freshly ground and accurately measured. The water is about 90 degrees Celsius.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Now, the pace and angle when pouring the water are really important. All right, here I go.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 5 0 0]Pour slowly and quietly, in a circular motion...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]You'll know you're doing it right when it starts smelling really good![n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 8 1 25 25]It's not exactly what you'd get at a café, but I think I've improved a lot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 9 0 0]There's so much to consider when making coffee. I get why people are so particular about it.[n][uf 1 1][e]

[msg MSG_004_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 10 0 0]Um, I know it's a bit weird to ask at this point, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0]When do you feel like drinking coffee the most?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Right after waking up.[e]
[uf 0 5 65278][uf 2 1]When I'm taking a break.[e]
[uf 0 5 65278][uf 2 1]I don't really drink it much.[e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 12 0 0]That does seem to be common for a lot of people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 8 0 25 25]The taste and smell are a signal to start the day. It's sort of like flipping a switch in your head.[n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, I see... You know, that's the weird thing about the smell of coffee.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 8 1 25 25]Drinking it is supposed to wake us up, but the smell has a relaxing effect, too.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0]Oh... Are you more of a tea person, like Mitsuru-san?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 17 0 0]In all honesty, I never really went out of my way to drink it, either.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 18 0 0]...When my mom was still alive, the house used to smell like this every morning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]Now I realize how often she'd make coffee, even on days she was busy.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 20 0 0]I saw on TV the other day that smells and memories are linked closely together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 21 0 0]The smell of coffee reminded me of my mom. But in your case...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0]I wonder if it'll remind you of the times we spent here, drinking coffee together.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]It's a possibility.[e]
[uf 0 5 65278][uf 2 1]Let's do it more often, then.[e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 23 0 0]Well, I better try extra hard when I'm making coffee for you, then![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 24 0 0]It'd be pretty sad if you only remembered my coffee being bitter.[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 25 0 0]In that case, I'd better practice and treat you to another cup while we still have time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 26 0 0]It'd be pretty sad if you only remembered my coffee being bitter.[n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 27 0 0]I feel like I haven't gotten into something like this for a long time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0]I also think it's helped me practice staying focused. Maybe it's because I've been doing it so diligently.[n][uf 1 1][e]

[msg MND_016_5_0]
[uf 0 5 65278][uf 2 1]Amada looks so satisfied[n]as he talks about coffee...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 29 0 0]Anyways, thanks a lot, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 30 0 0]Because of you, I think I understand the taste of coffee a little better now.[n][uf 1 1][e]

[msg MSG_017_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 22 0 8 9 25 8]Besides, if my mom liked it, I'm sure I will too.[n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 32 0 0]...Oh, there's still more, if you want a refill![n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 33 0 0]I've gotten a lot better now, so I hope you'll join me again sometime![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 159 65535 0 0][uf 3 1 1 0 0 34 0 0]Next time, it's gonna be even better than it was today![n][uf 1 1][e]

