[msg MSG_731_0_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 1 0 5]All right. Let's start by going over how to attack Shadows.[n][uf 1 1][e]

[msg MSG_731_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 2 0 5]When faced with an enemy, you have two primary options for fending them off. The first option is to use your equipped weapon.[n][uf 1 1][e]

[msg MSG_731_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 3 0 5]The second option is to use your Persona. But remember, every Persona has its own strengths and weaknesses.[n][uf 1 1][e]

[msg MSG_731_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 2 4 0 5]Knowing how Personas work will be crucial. Try summoning yours right now.[n][uf 1 1][e]

[msg MSG_731_0_5 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 2 5 0 3]Okay... Looks like I'm up![n][uf 1 1][e]

[msg MSG_731_0_6 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 1 0 2 6 0 3]Here goes. Check this out...[n][uf 1 1][e]

[msg MSG_731_0_7 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 1 0 2 7 0 3]Persona![n][uf 1 1][e]

