[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Heh, my thumb's gettin' a little greener every day, don't ya think?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]For an amateur vegetable patch, it's really comin' along. All that back-breakin' work was worth it![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Listen! You hear that? That's the sound of our precious little veggies cheerin' us on.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, I think I do.[e]
[uf 0 5 65278][uf 2 1]Let's hurry up and eat them![e]
[uf 0 5 65278][uf 2 1]...You get enough sleep?[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Right? They're kinda growin' on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]This might actually be my callin'. Maybe I should just ride this wave and start a farm or somethin'.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Uh, we're tryin' to have a chat with 'em here. Don't let your stomach do your thinkin' for ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Although, I guess it'd be rude not to gobble 'em up after all that work.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I'm not trippin' out or whatever! What I'm tryin' to say is that they're growin' on me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I mean, I get it. Gardening isn't all just fun and games.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]It's really cool how well they respond if you take care of 'em right.[n][uf 1 1][e]

[msg MSG_006_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]It's one of those times where you see the fruits of your labor after lots of slow, steady work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I never follow through on anything, and even I pulled it off! That counts for somethin', right?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]You've really grown up.[e]
[uf 0 5 65278][uf 2 1]Hope you learned your lesson.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Haha, I thought I was the one raisin' them, but maybe they were raisin' me all along.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Wait... Did real, actual wisdom just come outta me? Holy crap, I grew up more than I thought![n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Oh, get off your high horse! These veggies raised you just as much as you raised them.[n][uf 1 1][e]

[msg MSG_009_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]We owe a lot to our nutritious little veggie babies. Aw, who am I kiddin'—our veggie mentors.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Well, whatever we do in life, we can't expect to hit a home run on the first swing.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]We gotta stay on our toes and wait for the perfect chance to strike.[n][uf 1 1][e]

[msg MSG_011_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]And when that time comes, you knock it outta the park. That's how the real sluggers do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]A valuable lesson straight from our vegetable teachers. Don't go forgettin' it, ya hear?[n][uf 1 1][e]

[msg MND_011_7_0]
[uf 0 5 65278][uf 2 1]Junpei learned new things by[n]tending to the vegetable garden.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Maybe I'm finally figurin' this whole life thing out, huh?[n][uf 1 1][e]

[msg MSG_012_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Y'know, I think I'll write a book. I could call it somethin' like, "Life's a Vegetable Garden: The Junpei Iori Story."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Sellin' books and vegetables? Oooh, we're gonna be rollin' in dough! Maaan, am I a genius or what?[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Alright, enough dreamin'. Let's get a little bit more work done.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I tended the rooftop planters with Junpei...[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Whew, we did a heck of a job![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]See ya later, my darlin' veggies. I'll be back again when I'm free![n][uf 1 1][e]

[msg MSG_015_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]Welp, let's call it a night. Hit me up again when you have some time.[n][uf 1 1][e]

