[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11061 0 0][uf 5 13 12 5 106]So they aired the athlete's training regimen, and...[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I can feel my bond with Yuko grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's getting dark...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

