[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]After the fighting ends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Once the battle is over, Iwatodai Dorm[n]will have completed serving its purpose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We'll all eventually go our separate ways.[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Arf?[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I wonder what Koromaru wants[n]to do after all the fighting ends...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should ask him...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Ask if he wants to join me[e]
[uf 0 5 65278][uf 2 1]Ask what he wants to do[e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I asked if he wants to come[n]with me when this is all over...[n][uf 1 1][e]

[msg MSG_005_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]Arf![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I asked him what he wants[n]to do when this is all over...[n][uf 1 1][e]

[msg MSG_007_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]*whine*[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]It seems like Koromaru wants to[n]stick with me after the fighting's over...[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]Arf![n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Let's see this through.[e]
[uf 0 5 65278][uf 2 1]Let's deal with Nyx first.[e]
[uf 0 5 65278][uf 2 1]Let's protect the future.[e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Arf! Arf, arf![n][uf 1 1][e]

[msg MSG_012_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]...Arf.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It's an old, ragged collar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There's an amulet sewn into the back...[n]Could the priest have made this?[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Woof![n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Isn't this important to you?[e]
[uf 0 5 65278][uf 2 1]Don't you want to keep this?[e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]...Arf.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]He seems to want me[n]to keep it for him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I brought this along to our next home,[n]that might make Koromaru happy...[n][uf 1 1][e]

[msg MSG_018_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]Arf![n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems happy[n]that I have it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should keep this safe for him until[n]we figure out the post-dorm situation...[n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 0 0 0 10 0 0][uf 4 23 0 1 0 25 25]......[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]You can count on me.[e]
[uf 0 5 65278][uf 2 1]I'll take good care of this.[e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Arf![n][uf 1 1][e]

[msg MSG_023_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 8 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Awoooooo![n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]Koromaru's howl resounds[n]throughout the quiet shrine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can feel a strong sense of[n]resolve from Koromaru...[n][uf 1 1][e]

[msg MSG_025_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]Arf![n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]Koromaru and I slowly made[n]our way back to the dorm...[n][uf 1 1][e]

[msg SYS_027_0_0]
[uf 0 5 65278][uf 2 1]You have forged a powerful bond with Koromaru! You can now fuse [uf 0 1 35]Byakko[uf 0 1 27], the sacred white beast![n][uf 1 1][e]

