[msg SYS_AUTO_RECOVER [DEV: System MES]]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Применить автолечение?[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_HP_FULL [DEV: System MES]]
[uf 0 5 65278][uf 2 1]У всех участников команды полное здоровье.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_NO_SKIL [DEV: System MES]]
[uf 0 5 65278][uf 2 1]В команде нет участников с навыками лечения.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_SP_LESS [DEV: System MES]]
[uf 0 5 65278][uf 2 1]Недостаточно ОД для автолечения.[n][uf 1 1][e]

[msg SYS_AUTO_RECOVER_SP_LESS_2 [DEV: System MES]]
[uf 0 5 65278][uf 2 1]Не хватает ОД для использования навыка лечения. Автолечение отменено.[n][uf 1 1][e]

