[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11249 0 0]So, this is just my personal opinion...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]But I think that all our lives are predestined.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]If unexpected events in life are actually course corrections from whoever decides our destinies...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Then our lives can be described as scenarios written by an author.[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11228 0 0]But I don't mean that pessimistically.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Even if your life is predestined, I think you should give it your all while on that path.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]You have a point.[e]
[uf 0 5 65278][uf 2 1]That's just giving up.[e]
[uf 0 5 65278][uf 2 1]Sounds like an excuse.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11234 0 0][uf 5 13 11 30 108]Y-You agree? Well, I'm glad I decided to talk to you about this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 4 23 0 108 0 25 25]I was worried that I'd sound too preachy about it, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]If I only met you because I was written to, then I'd like to thank the author of my life.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems very happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11252 0 0]I know it's not a philosophy that everyone will agree with, but... Don't get the wrong idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 4 23 0 108 2 25 25]It doesn't mean that I'm giving up. In fact, I'm more motivated than ever before![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 4 23 0 108 3 25 25]A-Anyway, let's just drop it. I shouldn't push my opinions on you like that...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga has fallen silent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11226 0 0][uf 5 13 11 15 108]Hm... Maybe. But think about it. When you come to a crossroads, you have to make a decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]And if what decision you make has already been written before you even make it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]...A-Actually, let's just drop it. This conversation is getting way too complicated.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga is smiling bashfully.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11251 0 0]Well, I have to continue my preparations. I think I'll check for some books on the way back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, if you need help with your studies, feel free to ask. I can teach you my studying techniques.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]The two of us talked for a while longer[n]before I headed back to the dorm.[n][uf 1 1][e]

