[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Do you ever feel encouraged reading about the influential figures of the past?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Even leaders who forged great nations faced the challenges of interpersonal relationships...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]I feel that.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]Something on your mind?[e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Yes... It becomes easier to bear when you consider it's something everyone has to go through.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]Or is it presumptuous of me to relate to such illustrious figures?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Heh, does it tarnish your image of such illustrious figures to imagine them on the same level as us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Everyone interprets art in their own way. That's part of what makes it so interesting.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Well, it's natural to consider things, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Oh, were you expressing concern for me? Thank you, [uf 4 1].[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Sorry, I didn't mean to distract from our reading.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Shall we get back to it?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]...Oh, look at the time. I think that's enough for today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25][uf 5 13 4 1 5]That was a pleasant time together, hearing nothing but the sound of each other's pages.[n][uf 1 1][e]

[msg MND_016_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]By learning about the exploits[n]of renowned individuals, my[n][uf 4 30 0 1 1 0] have improved...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I'd like to hear your thoughts on our reading again sometime. But for now, good night.[n][uf 1 1][e]

