[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 2 1 1 4]We're doing this! Show me what you've got![n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 2 2 1 8]I know you don't want to fight... But we can't back down![n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 2 3 0 6]This is really happening...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 2 4 0 6]Aigis... I'll provide support. It doesn't seem like we can talk them out of this...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 1 0 2 5 1 4]Heh... That's enough warming up.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 5 52 65535 0 0][uf 3 1 1 0 2 6 1 4]Good one... Now this is a fight![n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 52 65535 0 0][uf 3 1 1 0 2 7 1 4]I won't go down... No more holding back![n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 2 8 1 8]You're even tougher than I thought![n][uf 1 1][e]

[msg MSG_007_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 5 52 65535 0 0][uf 3 1 1 0 2 9 1 8]Okay, I need to get serious... I'm stronger than this![n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 52 65535 0 0][uf 3 1 1 0 2 10 1 8]I don't care how hard it gets... I'll never give up![n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 2 11 1 4]You did good, Amada... Just leave the rest to me.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 52 65535 0 0][uf 3 1 1 0 2 12 1 8]Sanada-san... It's okay, you can rest. I'll take care of this![n][uf 1 1][e]

