[msg TRL_000_0_0 [Attacks and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can choose whether to use an [uf 0 1 2]attack[uf 0 1 27] or a [uf 0 1 2]skill[uf 0 1 27] on your enemies.[n][uf 1 1][e]

[msg TRL_001_0_0 [Attacks and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can attack with whatever weapon you have currently equipped on you. While it doesn't do the most damage, it will not deplete your HP or SP.[n][uf 1 1][e]

[msg TRL_002_0_0 [Attacks and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 1]Launch an attack by selecting the target and pressing [uf 1 3 998].[n][uf 1 1][e]

[msg TRL_003_0_0 [Attacks and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 2]On the other hand, using a skill will deplete your HP or SP. To use one, press [uf 1 3 112], then select the skill you want to use and the target you want to use it on.[n][uf 1 1][e]

