[msg TRL_000_0_0 [Theurgy Gauge]]
[uf 0 5 65278][uf 2 1][uf 4 8 27]Your Theurgy gauge will increase throughout battle whenever you attack or summon a Persona.[n][uf 1 1][e]

[msg TRL_001_0_0 [Theurgy Gauge]]
[uf 0 5 65278][uf 2 1][uf 4 8 28]How much the Theurgy gauge increases will vary from ally to ally. [uf 0 1 2]Acting according to a party member's personality[uf 0 1 27] will cause their Theurgy gauge to increase significantly.[n][uf 1 1][e]

[msg TRL_002_0_0 [Theurgy Gauge]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Fuuka also has a Theurgy gauge. Once it's maxed, you will be able to activate her Theurgy during a party member's turn.[n][uf 1 1][e]

[msg TRL_003_0_0 [Theurgy Gauge]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Be warned that a combatant's gauge will be disabled while afflicted with a status ailment, and [uf 0 1 2]if an ally is KO'd, their gauge will drop by half[uf 0 1 27].[n][uf 1 1][e]

