[msg TRL_000_0_0 [Theurgy Activation]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When emotions run high in battle, you or your party members will be able to activate Theurgy.[n][uf 1 1][e]

[msg TRL_001_0_0 [Theurgy Activation]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Theurgy can be activated on your turn when your Theurgy gauge is at max. Unlike normal skills, they do not cost HP or SP.[n][uf 1 1][e]

[msg MSG_002_0_0 [Theurgy Activation]]
[uf 0 5 65278][uf 2 1][uf 4 8 26]Press [uf 1 3 118] to activate your Theurgy. Please note that it cannot be used while you are afflicted with a status ailment.[n][uf 1 1][e]

