[msg TRL_000_0_0 [Critical Hits]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]There is a rare chance that a critical hit may occur when using physical skills or attacks. Landing a critical hit can knock down an enemy without targeting its weakness.[n][uf 1 1][e]

[msg TRL_001_0_0 [Critical Hits]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Attacking an enemy with a status ailment will increase the likelihood of landing a critical hit.[n][uf 1 1][e]

[msg TRL_002_0_0 [Critical Hits]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]There is a high chance of landing a critical hit when attacking an enemy in [uf 0 1 2]Distress[uf 0 1 27], but a critical is guaranteed when attacking a [uf 0 1 2]frozen[uf 0 1 27] enemy.[n][uf 1 1][e]

