[msg TRL_000_0_0 [Oracle]]
[uf 0 5 65278][uf 2 1][uf 4 8 29]Once Fuuka's Theurgy gauge is maxed, press [uf 1 3 109] to activate her Theurgy, [uf 0 1 2]Oracle[uf 0 1 27], during the party's turn.[n][uf 1 1][e]

[msg TRL_001_0_0 [Oracle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Using [uf 0 1 2]Oracle[uf 0 1 27] will benefit the party in battle with effects such as HP recovery, SP recovery, and stat buffs.[n][uf 1 1][e]

[msg TRL_002_0_0 [Oracle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Oracle[uf 0 1 27] can be activated during any party member's turn. Try to use it when you feel the time is right.[n][uf 1 1][e]

