[msg TRL_000_0_0 [Fusion Spells]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]By harnessing the power of the wild card and her Theurgy, Aigis can use Fusion Spells, special skills that are performed between certain Personas.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fusion Spells]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]They can be acquired by registering the relevant Personas in the Compendium.[n][uf 1 1][e]

[msg TRL_002_0_0 [Fusion Spells]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Once these conditions are met in the Velvet Room, Elizabeth will inform you of a new Fusion Spell you can use.[n][uf 1 1][e]

