[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Let's go together.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Ask about the target[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head to Club Escapade[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head toward the station[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[msg MSG_AMADA_PARTY_IN_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Please bring me with you for tonight's exploration.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Okay! I'll do my best![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I'm ready to go when you are.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_AFTE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Okay...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OVER_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Um, it looks like your party is already full.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Should I change with someone?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OVER_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Oh, it looks like there's no more room...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I'll give it my best![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Okay, got it.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]We should get going, right?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_AFTE_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Oh, okay. I understand...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]I won't let anyone get in our way! We have to keep going![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]I'm ready...![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]I'm sure they've gotten stronger since last time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]But so have we! So if we just...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Why would he...?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_03 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]...We have to keep going. We have to fight Nyx...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_03 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]We'll settle this once and for all this time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Please, allow me to fight![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_04 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]I can't lose... because I said I'd go on for him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]So I won't let Strega or anyone else stop me! Let's go![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_04 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Maybe, in a way, these guys actually weren't that different from me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]But that doesn't matter right now. Let's go![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_05 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]Don't worry. I'm looking straight ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Let's go, Senpai.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_05 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]If I'm being honest... I'd be lying if I said I wasn't scared...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_4 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]All right.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_06 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Let's finish this.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Whose place should I take?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_06 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]So those guys have come here, too... I won't let them get in our way![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Please let me go with you![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_07 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]I'm worried about Junpei-san... We should go after him, quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Let me know what I can do to help![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_08 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]I wonder where Junpei-san went...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_09 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]So much has happened, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]That's why we have to end this! I know we can do it![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_5 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]We'll win, no matter what.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_07 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]We have to put a stop to this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]I can go whenever you're ready.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Who should I switch with?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_TKJI [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]I can do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]What are you going to do?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_CHID [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]We should go after Junpei-san, quickly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]I can go whenever you're ready.[n][uf 1 1][e]

[msg MSG_0828_0902_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Don't worry about me. Something like Tartarus doesn't scare me at all.[n][uf 1 1][e]

[msg MSG_0903_0904_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]I heard that Aragaki-san used to fight alongside Sanada-san and Mitsuru-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]He certainly seems strong, but I'm not so sure about him...[n][uf 1 1][e]

[msg MSG_0919_1003_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]If we beat the last three Shadows, it'll all go away, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]The Dark Hour, the Lost, even Tartarus...[n][uf 1 1][e]

[msg MSG_1005_1016_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]I'm all right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I can still fight, so please don't worry.[n][uf 1 1][e]

[msg MSG_1019_1102_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]I decided that I would fight in his place...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]That's why I'll defeat them all. The Shadows here, and the very last Shadow...[n][uf 1 1][e]

[msg MSG_1106_1109_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Irresponsible adults do whatever they want and only leave behind problems for everyone else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Tartarus is a prime example of that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]I never want to become that kind of adult...[n][uf 1 1][e]

[msg MSG_1110_1117_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]I wonder if Mitsuru-san is okay...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]The rest of us too, for that matter. We don't really know what to do anymore, do we...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Well, we'll just have to do what we can.[n][uf 1 1][e]

[msg MSG_1121_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7096 0 0]Mitsuru-san seems different now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]She seems more positive than she did not too long ago.[n][uf 1 1][e]

[msg MSG_1122_1127_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]Junpei-san hasn't eaten much since... that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I understand how he feels, but... it's worrisome.[n][uf 1 1][e]

[msg MSG_1203_1213_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]The end of the world, an inescapable death...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Maybe we would be happier if we didn't know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 25 8]......[n][uf 1 1][e]

[msg MSG_0101_0114_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]I know what I'm going to do, and I'm not going to let anything distract me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I'll do everything I can with all I've got.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]That's how I stay motivated for the battles in Tartarus.[n][uf 1 1][e]

[msg MSG_0115_0130_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]I never really thought about what I want to do or be in the future before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]But I've been thinking about that kind of stuff a lot lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]...We have to beat Nyx, for sure.[n][uf 1 1][e]

[msg MSG_0131_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7145 0 0]Today's fight will decide everything. Our future... and the future of the whole world, even...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I'm kind of nervous, but... I'm not worried. It's a strange feeling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I know that we can win.[n][uf 1 1][e]

[msg MSG_HANYOU1_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Fighting in Tartarus sure is tiring...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Oh, but I'm okay, though. I'm tougher than I look, you know.[n][uf 1 1][e]

[msg MSG_HANYOU2_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Tartarus can be really different just floor to floor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Some floors are creepy, but the next floor could be really flashy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]It's strange.[n][uf 1 1][e]

[msg MSG_AMADA_ZEKKOCHO [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]Please leave it all to me today! Those Shadows won't stand a chance![n][uf 1 1][e]

