[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Let's go together.[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]
[uf 0 5 65278][uf 2 1]Let me think about it.[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Check progress[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Stay on standby for now.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Enter[e]
[uf 0 5 65278][uf 2 1]Don't enter[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Ask about the target[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head to Club Escapade[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Head toward the station[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Check everyone's status[e]
[uf 0 5 65278][uf 2 1]Commence operation[e]
[uf 0 5 65278][uf 2 1]Hold on[e]

[msg MSG_JUNPEI_PARTY_IN_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You know you're gonna need my help. We good to go?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Alright, let's do this![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]C'mon, let's get going.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]*sigh* Fine, I get it...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Yo, what gives? You already got a full team![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]So who am I gonna switch with?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE__2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]So who am I gonna switch with?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]You got it, dude![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Alright...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2025 0 0]Let's get goin', man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Dude, what!? I'm not just dead weight... Right?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]The team's already full, man.[n][uf 1 1][e]

[msg MSG_JUNPEI_TUTORIAL_BEFO [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2118 0 0]Alright, let's do this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'll prove that I should be in charge![n][uf 1 1][e]

[msg MSG_JUNPEI_TUTORIAL_AFTE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]Dude, I can't take it anymore...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]I'm starvin'...[n][uf 1 1][e]

[msg MSG_JUNPEI_THEURGIA_BEFO [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2010 0 0]It's all you, dude.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'll hold things down here, so go give 'em hell![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I got your back![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Just don't die, man...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Dude, there's no room.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE__3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]You want me to switch with someone?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Alright... You ready to get this show on the road?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]You're lookin' at your ace in the hole![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]I'm ready whenever.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Just leave it all to me![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Tch... If he was so smart, why didn't he do something more useful with his life?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_03 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Well, no point thinkin' about it too much... Let's go.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_03 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]That asshole's up next, right? Mind letting me come with?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]I got some unfinished business with him...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_04 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]I guess it's not like beating the shit outta him will suddenly fix everything, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]Anyways, we gotta get past him either way. You ready to do this?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_04 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Alright, now it's time for the real battle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Let's end this with a bang![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_05 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Heh, we'll be fine. We got this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Your cleanup hitter, Junpei Iori, is gonna knock it outta the park![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_05 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Alright, let's get going.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_06 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Somethin' up? C'mon, let's go.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_06 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]The hell was up with them? Poppin' in to preach all high and mighty just to hightail it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]You bastards think we're scared of bein' locked up!? ...Whatever. Let's do this![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_07 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2098 0 0]Yo, I'm gettin' kinda psyched![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_03 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]C'mon, man... You got a full party already![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE__4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]So who do I switch with?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_07 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]This'll be my first time goin' to a place like this, y'know? Man, I'm gettin' butterflies...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_08 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2118 0 0]We're so close... Let's kick some ass, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Hey, am I gonna be in the starting lineup?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_09 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]I wonder what Amada and Aragaki-san are up to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Wait, you think this is their way of saying they're leaving things in my capable hands...? Dude...[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_IN_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2118 0 0]Last up is that big boy, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]Alright, this is my time to shine! I'll take us all the way home, baby![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_08 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Let's do this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'm ready to step up to the plate! Let's get this done![n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Okay, fine... But you better not lose, alright?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OVER_04 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Dude, there's no more room.[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_CHANGE__5 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Who do I swap spots with?[n][uf 1 1][e]

[msg MSG_JUNPEI_PARTY_OUT_TKJ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]I'm not gonna let them have their way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]But hey, uh, you're not gonna bench me, right?[n][uf 1 1][e]

[msg MSG_0425_0508_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]I don't care where those enemies come from. I'll smash 'em down one right after another![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]You can count on me![n][uf 1 1][e]

[msg MSG_0510_0514_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]That stuff that happened on the monorail was friggin' crazy, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I kinda wanna make it into like a script for a TV show or something, but I probably can't...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Sucks... I bet it woulda been kickass, too...[n][uf 1 1][e]

[msg MSG_0523_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2066 0 0]Sanada-san's back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'm glad I finally have a rival that can stand up to my good looks![n][uf 1 1][e]

[msg MSG_0602_0605_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2066 0 0]Junpei's Believe It, or Don't is a smash hit! Its rise into continued popularity knows no bounds![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Even in the blistering heat of summer, Junpei's Believe It, or Don't will make you shiver in fear![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]...Heh, I'm just messin'.[n][uf 1 1][e]

[msg MSG_0606_0607_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]That guy who saved us, Aragaki-san, was real tough, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]He took that dude down with a single headbutt! I don't care who you are; that's just badass.[n][uf 1 1][e]

[msg MSG_0613_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Kirijo-senpai's beautiful fencing, and Fuuka's soothing voice...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Truly an oasis in the desert![n][uf 1 1][e]

[msg MSG_0623_0707_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Ta-dah da-daah! Junpei has leveled up![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]...I wish I could say that like a hundred times a day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]The more I level up, the more awesome I get![n][uf 1 1][e]

[msg MSG_0709_0717_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2011 0 0]...What? NOW you need somethin' from me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 4 25 3]Tch...[n][uf 1 1][e]

[msg MSG_0718_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Dude, I'm so pumped for Yakushima![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'm thinkin' about it so much, even Tartarus is starting to look like the beach to me.[n][uf 1 1][e]

[msg MSG_0724_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Ai-chan is amazing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]She's so cute, but she can also shoot bullets from her fingers![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]It's a good thing she's on our side... It'd suck to have her as an enemy.[n][uf 1 1][e]

[msg MSG_0725_0805_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Sure, Amada's mature for his age...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]But don't you think Yuka-tan's giving him too much credit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]It'd be nice if she praised me like that once in a while...[n][uf 1 1][e]

[msg MSG_0806_0809_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]I seriously can't believe we have to go to summer school![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Maybe if I just stay in Tartarus, I won't have to go...[n][uf 1 1][e]

[msg MSG_0810_0820_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2066 0 0]Now that Koromaru's on our side, things are gonna be better than ever![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]With so many team members, Tartarus is gonna be a lot funner! ...I hope.[n][uf 1 1][e]

[msg MSG_0821_0827_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]Man... Summer break's almost over...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Well, at least I can still make some beautiful memories here in Tartarus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0]...Like anyone could do that![n][uf 1 1][e]

[msg MSG_0828_0902_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Amada's just in elementary school, but he's so determined. It's kind of amazing, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Me, on the other hand...[n][uf 1 1][e]

[msg MSG_0903_0904_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Aragaki-san is our senpai in school and in SEES... Oh, and in Personas! He's like a triple senpai![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]If he asked me to go buy him some yakisoba pan, there's no way I could turn him down...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]But what if he asks me to in here? I mean, there's no yakisoba pan in Tartarus![n][uf 1 1][e]

[msg MSG_0906_0918_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Since I began talking to Chidori, I've been thinking a lot...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Ya know... I've never really thought that deeply about things like life and death and stuff...[n][uf 1 1][e]

[msg MSG_0919_1003_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]Those dudes from Strega are prolly gonna come out during the next full moon, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]I can't lose... for me, or for Chidori...[n][uf 1 1][e]

[msg MSG_1005_1016_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2093 0 0]There's no way I could accept my death so easily like that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Aragaki-san is amazing...[n][uf 1 1][e]

[msg MSG_1019_1102_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]When Tartarus disappears, the first thing I'm gonna do is go see Chidori.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Haha, kinda makes me feel like I'm a hero in a video game or somethin'.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]"Then, I will check up on the fair maiden after I have defeated the final enemy!" Heheh...[n][uf 1 1][e]

[msg MSG_1106_1109_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]So Ikutsuki was playin' us the whole time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]The more I think about it, the more I hate Tartarus...[n][uf 1 1][e]

[msg MSG_1110_1117_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]Dude, Kirijo-senpai looks pretty rough... It's like there's no life in her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]But I don't blame her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]If I lost someone close to me, I'd probably be like that, too...[n][uf 1 1][e]

[msg MSG_1121_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 3 0 65535 2111 0 0]Man, I'm still sore... Kirijo-senpai didn't have to go that far with her "execution."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]After that, we shouldn't even be here tonight. We're working too hard...[n][uf 1 1][e]

[msg MSG_1121_JUNPEI_DUNGE_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]I wonder if something happened to Kirijo-senpai on the school trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I mean, she was so depressed, but she seems fine all of a sudden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]...Well, I'm glad she's okay, at least.[n][uf 1 1][e]

[msg MSG_1122_1127_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]...Chidori gave me my life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]And it's not just my own now. I have to take care of it...[n][uf 1 1][e]

[msg MSG_1203_1213_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2129 0 0]Ryoji dropped a real bomb on us, didn't he?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]The world is ending? How can I just accept that!?[n][uf 1 1][e]

[msg MSG_0101_0114_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2066 0 0]Ai-chan is different now. I dunno, it's like... her face seems brighter, or somethin'.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Well, I haven't stopped growing yet, either! I'm still gonna level up like crazy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]So let's go![n][uf 1 1][e]

[msg MSG_0115_0130_JUNPEI_DUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2086 0 0]It's the top of the final inning![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Let's fight and level up and blast Nyx into outer space![n][uf 1 1][e]

[msg MSG_0131_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0]Man, I guess this is the last night we'll be calling you "Leader," huh, [uf 4 2]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Kinda hard to call you that outside of Tartarus. We'd get a lot of weird looks at school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Well, I guess we'll just have to come up with a new nickname to call ya starting tomorrow![n][uf 1 1][e]

[msg MSG_TEST_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2102 0 0]Don't say anything about exams![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]I don't wanna think about 'em while I'm in Tartarus![n][uf 1 1][e]

[msg MSG_HANYOU1_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 3 0 65535 2093 0 0]Gaaahhh, I'm so hungry![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0]Tartarus... Tartarus... Tartar sauce...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oh, crap... I want some deep-fried shrimp to munch on now...[n][uf 1 1][e]

[msg MSG_HANYOU2_JUNPEI_DUNGE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]I wish there was a convenience store inside Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]They could have all kinds of stuff, and we wouldn't have to worry about going hungry![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I wish the Kirijo Group would really make one here...[n][uf 1 1][e]

[msg MSG_JUNPEI_ZEKKOCHO [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Come on out, Shadows... Don't worry, I won't bite...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I'll just chop you up into itty-bitty pieces![n][uf 1 1][e]

