[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]They recommended this at the store when I said I was looking for a movie with a cool, hard-boiled main character.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]But so far, he just seems like a reckless old man to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]He even fell for that woman's lies... Do people really think this guy is cool?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]That's right.[e]
[uf 0 5 65278][uf 2 1]Probably not.[e]
[uf 0 5 65278][uf 2 1]Just wait and see.[e]

[msg MSG_002_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Really? I don't get it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I thought so. It's definitely not cool to fall for such an obvious trick.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh, that's right. We are only halfway through the movie.[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]He's surrounded by gangsters again...[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Wow... He was so cool![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]He actually knew it was a lie the whole time, and he was just pretending to be tricked![n][uf 1 1][e]

[msg MSG_006_3_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]His signature phrase was so good, too.[n][uf 1 1][e]

[msg MSG_006_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]"You can't be a detective without smarts, and you've got no right being a detective without a heart!"[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I feel like I gained some [uf 4 30 2 1 1 0] after[n]watching how a man of conviction lives...[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Ohh, looks like this movie is part of a series![n][uf 1 1][e]

[msg MSG_008_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Let's watch the other ones together when you have time![n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]This character really drinks a lot of alcohol.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 1]-san, when you grow up, are you going to drink alcohol too?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]I would like to.[e]
[uf 0 5 65278][uf 2 1]I want to avoid alcohol.[e]
[uf 0 5 65278][uf 2 1]Will you?[e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I see. You should be careful about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I heard that drinking too much is bad for your health.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]But don't they say it's sometimes necessary to drink for work?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]And that sometimes it's hard to say no. Being an adult is all about taking the shots you're given.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 4 25 25]...Oh, I just made a pun, didn't I?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Me? I've never thought about it, actually...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]But I do hear that a lot of adults these days don't drink.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Alcohol has a very mature feeling about it, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I don't think I'm a fan of all the rowdy parties, but having a nice glass does look kind of cool.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Speaking of, remember that bar scene...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Wow, it's late! Watching those bonus clips took longer than I thought.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel like I gained some [uf 4 30 2 1 1 0] after[n]watching how a man of conviction lives...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]It's about time I head to bed. Good night.[n][uf 1 1][e]

