[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Aragaki is working at a brisk pace...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I spent time cooking with Aragaki...[n][uf 1 1][e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Looks like you got the hang of things. The food wasn't bad today.[n][uf 1 1][e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Alright, let's clean up.[n][uf 1 1][e]

