[msg MSG_000_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Wow, I didn't know you could come all the way down here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]Going on trips is great, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]I've seen a lot of the sights here now, and everything is so fascinating.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]There's so much I've never seen before, my mind's having trouble keeping up.[n][uf 1 1][e]

[msg MSG_002_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]I even bought myself a souvenir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 1 25 25]Look, it's a music box.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 1 25 25]Doesn't it sound nice? I don't know the name of the song, though.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I think I like it.[e]
[uf 0 5 65278][uf 2 1]You could buy that anywhere.[e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Haha, I'm kinda glad to hear you say that.[n][uf 1 1][e]

[msg MSG_006_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]Haha, is that right? But I think it's chance encounters like this that end up holding true meaning.[n][uf 1 1][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]Sometime, way down the line, I'll listen to this melody...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]And when I do, I'll think back fondly on this trip.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]The evening sun is so bright reflecting off the water's surface.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]It's different from the view we get from the school roof. I wonder if this is the reason why people come to visit.[n][uf 1 1][e]

[msg MSG_009_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]But did you know? A long time ago, this place used to be an execution site.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]How do you know that?[e]
[uf 0 5 65278][uf 2 1]That's ominous...[e]

[msg MSG_011_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Well, that teacher with the helmet, um... Mr. Ono—he was talking about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]He said there are numerous records of historical figures being publicly executed here.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]Haha, sorry. I didn't mean to darken the mood all of a sudden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]And that stuff happened a long time ago. Besides, it's still nice and bright out right now.[n][uf 1 1][e]

[msg MSG_013_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]I've heard rivers have long been thought to be a border between this world and the afterlife.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 0 25 25]But with so many couples around, it doesn't really give that impression, huh?[n][uf 1 1][e]

[msg MSG_015_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 0 25 25]You know, I've been thinking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]Every one of us will die someday, right?[n][uf 1 1][e]

[msg MSG_016_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Eventually, the time will come when we have to part. So then, why? Why do people try so hard to connect with each other?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 0 25 25]I'm not just talking about romance, either. It's the same for friends, family... Everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 0 25 25]For each person you connect with, it just makes saying goodbye that much harder. So what's the point?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]It's necessary to survive.[e]
[uf 0 5 65278][uf 2 1]We don't want to feel lonely.[e]
[uf 0 5 65278][uf 2 1]Those connections are inevitable.[e]
[uf 0 5 65278][uf 2 1]I don't know.[e]

[msg MSG_018_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 0 25 25]So you mean... we're forced to help each other in order to survive?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]But look at everyone around us. They all genuinely like each other, don't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 3 25 25]They want to be together. They're not being forced... That doesn't add up.[n][uf 1 1][e]

[msg MSG_019_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]So you mean... we just can't stand the pain of being alone?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 0 25 25]But look at everyone around us. They've chosen their partners out of a large crowd, haven't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 3 25 25]So it's not about loneliness. They genuinely want to be with each other... Right?[n][uf 1 1][e]

[msg MSG_020_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 0 25 25]So you mean... you can't escape it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 0 25 25]But from what I can tell, everyone around here wants to have that kind of relationship.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 1 25 25]If they were just forced together by circumstances, I don't think they'd look so happy.[n][uf 1 1][e]

[msg MSG_021_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 1 3 25 25]Right? It just doesn't make sense. But still...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 0 0 0 36 0 0][uf 4 23 0 1 3 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0][uf 4 23 0 1 3 25 25]Perhaps reaching our end before we figure it out is for the best.[n][uf 1 1][e]

[msg MSG_022_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 1 1 25 25]Whoops, sorry, the conversation got a bit heavy there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 23 0 1 1 25 25]Looking out at the river just made me think about things for some reason.[n][uf 1 1][e]

[msg MSG_023_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 1 1 25 25]If you follow the flow of water, you'll eventually reach the ocean, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 1 0 25 25]Its destination is already decided, but it takes so many different forms before it gets there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 4 23 0 1 0 25 25]Sometimes it's quiet and calm... Other times it's choppy rapids. Sometimes it's clear, but other times murky...[n][uf 1 1][e]

[msg MSG_024_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 1 0 25 25]I imagine we're the same way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 44 0 0][uf 4 23 0 1 0 25 25]We're all in the midst of a long journey, with all kinds of things happening as we go along.[n][uf 1 1][e]

[msg MSG_025_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 1 1 25 25]I never realized any of this until coming on this trip with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0][uf 4 23 0 1 1 25 25]Everything feels that much more fascinating when you're here. I guess you could say... it expands my horizons.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 1 1 25 25]Time spent talking together with you like this just feels... precious to me.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 48 0 0][uf 4 23 0 1 1 25 25]...Ahaha, it kinda sounds like I'm confessing my love or something, huh?[n][uf 1 1][e]

[msg MSG_027_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 1 1 25 25]The wind is chilly out here by the water...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 4 23 0 1 1 25 25]We should probably head back. Don't want to get in the way of all the couples.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]I walked along the riverbank with[n]Ryoji, then returned to the hotel...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]him a little better now...[n][uf 1 1][e]

[msg PFM_029_0_0]
[uf 0 5 65278][uf 2 1]All stats of the equipped Persona have been raised by 1.[n][uf 1 1][e]

