[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 1 0 0]Another Shadow![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 2 0 0]If that figure is summoning these Shadows... I guess it's an enemy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 3 0 0]But then... Why does it seem so similar to...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 4 0 0]Um, anyway, it still seems like it won't attack, so focus on the Shadow![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 1 0 0 5 0 0]You can do it![n][uf 1 1][e]

