[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11261 0 0]I've traveled outside of Japan a few times with my family.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]It was always a lot of fun, and I have a lot of great memories, but...[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Studying abroad is long-term...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11250 0 0]I mean, I won't just be visiting; I'll be living there...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Think of all the new girls.[e]
[uf 0 5 65278][uf 2 1]Think of the new inspirations.[e]
[uf 0 5 65278][uf 2 1]Think of your new lifestyle.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11224 0 0][uf 5 13 11 15 108]O-Oh! You might have a point there! A romantic encounter in a foreign land, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 4 23 0 108 0 25 25]Wait, what am I saying!? It's not like I'll be on vacation! I'll be there to study![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems like he's having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11220 0 0][uf 5 13 11 30 108]You have a point there... I'm sure I'll encounter a lot of things that I wouldn't if I stayed here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 4 23 0 108 0 25 25]Learning about different cultures could be an invaluable experience for a young artist like me.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems impressed by my words.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11255 0 0]That's right, if I study abroad, I won't have to listen to my dad's nagging all the time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 4 23 0 108 3 25 25]But I won't be able to see you or the other club members, either! I'll get so homesick...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems anxious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11264 0 0]Oh, by the way, that fortune telling book I got the other day was pretty interesting.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]There's a method called Tasseography that tells your fortune through interpreting patterns left by coffee grounds...[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]We chatted for a while longer before[n]I decided to go back to the dorm.[n][uf 1 1][e]

