[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Customers asked lots of questions... But I[n]explained everything politely and clearly...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I worked hard to satisfy each[n]customer on a frantically busy day...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]A customer was pleased when I suggested[n]a healing stone that suited them...![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]The spell dolls sold like hotcakes... I attended[n]to customers while restocking products...![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It was a stressful day, but the soothing effect[n]of the store helped me get through it...![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The healing music playing in the[n]store helped me stay relaxed...[n][uf 1 1][e]

[msg MSG_008_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]All right, I'm going to increase your hourly wage! People need to be rewarded for their hard work.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Since I'm getting the hang of things,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_010_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]Hey, a customer complimented you earlier. You should work here full-time after you graduate![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Since I've gotten better at my work,[n]they're giving me a slight raise...![n][uf 1 1][e]

[msg MSG_012_0_0 [Manager]]
[uf 0 5 65278][uf 2 1]Whew, you were a big help today! Thanks. I added a bit of a bonus for you![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]After working awhile with spiritual[n]gemstones, my [uf 4 30 0 1 1 0][n]and [uf 4 30 1 1 1 0] increased...![n][uf 1 1][e]

