[msg MSG_000_0_0 [Happy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 652]Hey, did you see them filming something in the city?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 652]I guess it's a really touristy spot. They must be used to seeing celebrities around here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Happy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 652]Did you check out the souvenir shop downstairs? 6HARA is a pretty weird name for it![n][uf 1 1][e]

