[msg MSG_000_0_0 [Student with Heavy Makeup]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]I can't let people see me without my makeup on...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]I'll have to wait for everyone to go to sleep before I take it off.[n][uf 1 1][e]

[msg MSG_001_0_0 [Student with Heavy Makeup]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]I made sure to wake up earlier than anyone else this morning so I could put my makeup on first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]I really don't want anybody seeing me without it...[n][uf 1 1][e]

[msg MSG_002_0_0 [Student with Heavy Makeup]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]It's been a really rough three days, but it's almost over...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]What, can't you tell what I'm talking about?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 608]Trying to keep anyone from seeing me without my makeup, of course![n][uf 1 1][e]

