[msg MSG_000_0_0 [Anticipating Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Hey, do you have anyone to go around with tomorrow?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Oh, wait... Are you going out with someone?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I am.[e]
[uf 0 5 65278][uf 2 1]Nope.[e]
[uf 0 5 65278][uf 2 1]It's a secret.[e]

[msg MSG_002_0_0 [Anticipating Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Aww... Bummer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]But if you've got a girlfriend, don't think you can fool around just because you're on a trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Girls get really mad when you do that, you know...[n][uf 1 1][e]

[msg MSG_003_0_0 [Anticipating Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Really? Then are you trying to decide who you'll go after?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]I wish I had someone cool, so I wouldn't be as bored...[n][uf 1 1][e]

[msg MSG_004_0_0 [Anticipating Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 613]Ugh, that's no fun... Way to kill the conversation there.[n][uf 1 1][e]

