[msg MSG_000_0_0 [High-Spirited Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]Some people think that visiting shrines is boring, but I'm really looking forward to it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]I'm gonna go to romance shrines and pray a lot.[n][uf 1 1][e]

[msg MSG_001_0_0 [High-Spirited Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]When I went to the romance shrine, there were loads and loads of girls just praying desperately![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]I asked what all the fuss was about, and it turns out that they were all fans of Sanada-senpai![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]Normally, they'd get angry if one of them made a move like that, but if they were all there together...[n][uf 1 1][e]

[msg MSG_002_0_0 [High-Spirited Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]A local guy talked to me today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]I wonder if my prayers at the romance shrine are starting to have an effect![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 609]Maybe I'll score a boyfriend by Christmas this year![n][uf 1 1][e]

