[msg MSG_000_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 3 0 65535 12290 0 0]*hic* Where's my booze!?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The lazy-eyed monk is drinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm worried about what will happen[n]if I stay, and I don't have the[n][uf 4 30 2 1 1 0] to approach him...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If my [uf 4 30 2 1 1 0] was at least[n][uf 4 31 2 3 1 0], maybe I could talk to him...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]The lazy-eyed monk is drinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I mustered up enough[n][uf 4 30 2 1 1 0] to talk to him![n][uf 1 1][e]

[msg MSG_003_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 1 0][uf 3 1 3 0 65535 12251 0 0]Booze! ...Where's my booze?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 1 0]I don't got nothin' to say if you don't got any booze...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]If I order some alcohol for this monk,[n]maybe he'll be willing to speak with me...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12268 0 0]Oh, you...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Mutatsu seems to be drinking by himself.[n][uf 1 1][e]

[msg MSG_007_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12204 0 0]未使用[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]The monk seems to be drinking by himself.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12203 0 0]未使用[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]It seems like Mutatsu wants to talk...[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Should I spend some time with Mutatsu?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MND_013_3_0]
[uf 0 5 65278][uf 2 1]I feel like I might grow[n]closer to the monk soon...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Should I spend some time with him?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with the monk[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_015_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12292 0 0]Heh, what a strange kid...[n][uf 1 1][e]

[msg MSG_016_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 3 0 65535 12253 0 0]Heh, alright then.[n][uf 1 1][e]

[msg MSG_017_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12292 0 0]未使用[n][uf 1 1][e]

[msg MSG_018_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 3 0 65535 12253 0 0]未使用[n][uf 1 1][e]

[msg MSG_019_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 0 0][uf 3 1 3 0 65535 12251 0 0]Whaddaya want? You're killin' my buzz here...[n][uf 1 1][e]

[msg MSG_020_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12268 0 0]Oh, wait, you're...[n][uf 1 1][e]

[msg MSG_021_0_0 [Monk]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12253 0 0]Hmph. Kids these days got no respect...[n][uf 1 1][e]

[msg MSG_022_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 3 0 65535 12282 0 0]Whew... More... I need more...[n][uf 1 1][e]

[msg MSG_023_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12207 0 0]What? You again...?[n][uf 1 1][e]

[msg MSG_024_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12270 0 0]...Weird kid. Run on home, then.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12268 0 0]Oh, you...[n][uf 1 1][e]

[msg MSG_026_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12292 0 0]Heh, what a strange kid...[n][uf 1 1][e]

[msg MSG_027_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12282 0 0]Hmph. So be it.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12201 0 0]Huh, you're here again...[n][uf 1 1][e]

[msg MSG_029_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12292 0 0]Heh, you really are an odd kid. Well, have a seat.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12213 0 0]Hmph. So be it.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 3 0 65535 12270 0 0]Ahh... I don't think I can do it...[n][uf 1 1][e]

[msg MSG_032_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12251 0 0]Huh...? Leave me alone...[n][uf 1 1][e]

[msg MSG_033_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12268 0 0]Yeah, just leave me alone...[n][uf 1 1][e]

[msg MSG_034_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12208 0 0]...Oh, you're here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0]Well? You gonna stick around?[n][uf 1 1][e]

[msg MSG_035_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12218 0 0]...Alright, then go ahead and have a seat.[n][uf 1 1][e]

[msg MSG_036_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12213 0 0]Hmph. So be it.[n][uf 1 1][e]

[msg MSG_037_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 1 0][uf 3 1 3 0 65535 12281 0 0]Woooo... C'mon, booze! I want more booze...[n][uf 1 1][e]

[msg MSG_038_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 1 0][uf 3 1 3 0 65535 12268 0 0]...Huh? Oh, took yer sweet time gettin' here...[n][uf 1 1][e]

[msg MSG_039_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 2 65535 65535 1 0][uf 3 1 3 0 65535 12288 0 0]Whaaat, ya don't wanna join me...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 1 0]Figures... *hic* Why're you always like this...?[n][uf 1 1][e]

[msg MSG_040_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12211 0 0]Oh... It's you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 30 65535 65535 0 0]Look, uh... You got some time to talk?[n][uf 1 1][e]

[msg MSG_041_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12218 0 0]Alright... Make yourself comfortable.[n][uf 1 1][e]

[msg MSG_042_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 3 65535 65535 0 0][uf 3 1 3 0 65535 12216 0 0]Yeah, guess I can't blame you...[n][uf 1 1][e]

[msg MSG_043_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12201 0 0]Hey, I've been waiting for ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0]You got a minute?[n][uf 1 1][e]

[msg MSG_044_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12234 0 0]Heh, you never change, do ya...? Well, have a seat.[n][uf 1 1][e]

[msg MSG_045_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12213 0 0]...Alright, then. Be seein' ya.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Mutatsu]]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I still spend time with them...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Should I spend the day[n]with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Should I spend time online playing[n]the MMORPG with [uf 2 4 0]...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Should I spend the evening[n]with [uf 2 4 0]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Spend time with [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with the [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Should I spend the day at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Should I spend the night[n]with [uf 2 4 1]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Spend time w/ [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Enter the bookstore[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, right. There's something else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

