[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh, [uf 4 1]-kun. Are you going home?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]You look a bit pale... Are you doing all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Don't overwork yourself, okay? Maybe you should rest in the nurse's office before you leave.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]I was actually about to head to the faculty office. Would you like me to walk you downstairs?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 1 0][uf 3 1 1 0 4 5 0 0]I... want to spend as much time with you as I can...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Let's do it.[e]
[uf 0 5 65278][uf 2 1]I'm a little busy today...[e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]I'd be happy to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Okay, let's head down to the faculty office together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 4 8 0 0]Oh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 1 0][uf 3 1 1 0 4 9 0 0]It'll be kind of embarrassing to walk side by side at school, huh?[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Oh... Well, be careful on your way home, okay?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Let's do it.[e]
[uf 0 5 65278][uf 2 1]I'm a little busy today...[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Sounds good. People often get sick when the seasons change, so maybe you're coming down with something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Okay, let's head over to the faculty office together.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Do you have plans already? Well, just make sure you go home soon and get some rest.[n][uf 1 1][e]

