[msg MSG_000_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 3 0 65535 10289 0 0]Just because it's a new school year doesn't mean that students should be running wild.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]It's up to me to reinforce order. That is, once I've officially become a member of the disciplinary committee.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11237 0 0]You're making such a sour face again, Odagiri-kun... I guess some things never change.[n][uf 1 1][e]

[msg MSG_001_5_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11293 0 0]Aren't you excited? The spring season always feels like the beginning of something new.[n][uf 1 1][e]

[msg MSG_002_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 3 0 65535 10272 0 0]Keisuke... You haven't changed either.[n][uf 1 1][e]

