[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Well, well, look who it is! It's been a while, [uf 4 2]-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]You've grown so much since the last time I saw ya![n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Now, now, dear. They don't grow that fast.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]What must have happened is that we shrank! Isn't that right?[n][uf 1 1][e]

[msg MSG_002_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Ohoho! Is that how it is? Looks like you got one over on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]...Say, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Y'know our old shop here, Bookworms? I'm thinkin' it's due for a makeover.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Somethin' fresh, avant-garde... I can't let Gekkoukan's new school building hog the spotlight![n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Good idea.[e]
[uf 0 5 65278][uf 2 1]It's fine the way it is.[e]

[msg MSG_004_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Ain't it? I'll hash out some plans with my dear and make this place even better![n][uf 1 1][e]

[msg MSG_005_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Oh, you think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]I s'pose that's just as well. I'm honored you like the place, young man.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Speaking of the new school building... They've decided to replant the persimmon tree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]It'll be moved to a special location on a hill overlooking the whole campus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Our dear boy will be able to watch over those students for many more years to come...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]...I know the tree isn't actually our son. And yet... this makes me feel so happy...[n][uf 1 1][e]

[msg MSG_007_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Ever since my dear heard the news, she's turned into a leaky faucet![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]C'mon, give me a smile! Googoo googoo gaga![n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 18 0 0]Please, dear, I think your dentures are falling out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 4 19 0 0]Anyhow... We'll be supporting the Gekkoukan students with renewed strength in our hearts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 4 20 0 0]Looking at you again... You really did grow, didn't you, [uf 4 2]-chan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 4 21 0 0]You've overcome great hardships... I can tell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 22 0 0]Come back and visit us anytime. We'd always love to see you.[n][uf 1 1][e]

[msg MSG_009_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 23 0 0]If we can get [uf 4 2]-chan to spread the word at Gekkoukan, there'll be no end to our customers![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 4 24 0 0]Not a bad idea, eh, dear?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 4 25 0 0]Come now... Don't make him do our work for us.[n][uf 1 1][e]

[msg MSG_011_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 4 26 0 0]You don't have to put it like that! Besides, what are grandchildren for?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 4 27 0 0]Oh, you...[n][uf 1 1][e]

