[msg MSG_000_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12807 0 0]You are...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]Hm... From my point of view, everyone else leads a fairy tale life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]That would include you... Or would you say you are a victim of sorrow?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Huh?[e]
[uf 0 5 65278][uf 2 1]I'm normal.[e]

[msg MSG_002_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12841 0 0]...Never mind. Hope and hopelessness are two sides of the same coin, anyhow.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's difficult to figure out[n]what he's trying to say...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I want to talk with him, I'll need[n]to improve my [uf 4 30 0 1 1 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I were at least [uf 4 31 0 4 1 0], then I[n]might be able to understand him...[n][uf 1 1][e]

[msg MSG_004_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12854 0 0]...I see. Then it appears we have nothing more to discuss.[n][uf 1 1][e]

[msg MSG_005_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12807 19 0]Huh... Your eyes are so clear...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]Your soul must be burning brightly.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It seems the young man has noticed me[n]thanks to my impressive [uf 4 30 0 1 1 0].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This might be my chance to[n]get to know him better...[n][uf 1 1][e]

[msg MSG_007_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12835 0 0]The me that I see reflected in your eyes and the real me—if there is one... How far apart are they?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Almost zero.[e]
[uf 0 5 65278][uf 2 1]About arm's length.[e]
[uf 0 5 65278][uf 2 1]Three lightyears...?[e]

[msg MSG_009_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12876 0 0]Hmm... That works.[n][uf 1 1][e]

[msg MSG_010_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12892 0 0]Oh, you mean literally? Haha, I guess you have a point.[n][uf 1 1][e]

[msg MSG_011_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12819 0 0]Yes, that's about right... A long, lonely distance to travel.[n][uf 1 1][e]

[msg MSG_012_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12863 0 0]Your words are very beautiful. If I had something to write with, I'd note them down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]I have a fountain pen... It uses red ink—blood red.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]My pen is my supporter, my spokesman, and my friend. However, it seems to have disappeared.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]Without it, my screams are silenced...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]The young man seems sad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparently, his fountain pen is missing.[n][uf 1 1][e]

[msg MSG_014_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12835 0 0]I'm still looking for my fountain pen. Please let me know if you find it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]Perhaps the creature with white fur and bright red eyes kidnapped it...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Apparently, his fountain pen is missing.[n][uf 1 1][e]

[msg MSG_016_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12864 0 0]Oh... The pen in your possession... By any chance, is that my missing fountain pen?[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I handed him the [uf 4 4 1 37 1 0].[n][uf 1 1][e]

[msg MSG_018_0_0 [Thin Young Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12830 0 0]Ahh... Welcome home, dear friend... And thank you, for finding it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]Now the mighty scream quietly bellowing within me has regained its voice... My "diary"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]My name is Akinari Kamiki.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12807 0 0]Have a seat, if you'd like. I'll write something for the two of us...[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]The young man seems to have[n]taken an interest in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the day with him...?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_022_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12854 0 0]That's unfortunate... Then farewell, my benefactor.[n][uf 1 1][e]

[msg MSG_023_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12802 0 0]Oh, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]Why don't you have a seat? This bench is too big for me alone.[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]It seems Kamiki would enjoy my company.[n][uf 1 1][e]

[msg MSG_025_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12810 0 0]Ah, you— *cough*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*cough* *wheeze* *wheeze*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*cough* *cough*[n][uf 1 1][e]

[msg MSG_026_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12894 0 0]Sorry... *pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]If you... *pant* don't mind... *pant* please stay... until I've caught my breath...[n][uf 1 1][e]

[msg MSG_027_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12822 0 0]Ah, hello there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]It's good to see you. Please, have a seat, if you'd like.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the day with Kamiki?[n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with him[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_030_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12818 0 0]Then this bench shall be our meeting place.[n][uf 1 1][e]

[msg MSG_031_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12830 0 0]Thank you...[n][uf 1 1][e]

[msg MSG_032_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12854 0 0]I see... Then perhaps we can speak some other time.[n][uf 1 1][e]

[msg MSG_033_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12807 0 0]You...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 4 25 117]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]...Oh, it's nothing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]Why don't you have a seat? This bench is too big for me alone.[n][uf 1 1][e]

[msg MSG_034_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12818 0 0]Then this bench shall be our meeting place.[n][uf 1 1][e]

[msg MSG_035_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12854 0 0]I see. Well, it's probably better this way...[n][uf 1 1][e]

[msg MSG_036_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12822 0 0]Ah, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]Would you like to talk with me again? But only if you're so inclined, of course...[n][uf 1 1][e]

[msg MSG_037_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12833 0 0]Thanks. I suppose I had actually been waiting for you.[n][uf 1 1][e]

[msg MSG_038_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12810 0 0]Ah, you— *cough*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*cough* *wheeze* *wheeze*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*cough* *cough*[n][uf 1 1][e]

[msg MSG_039_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 3 0 65535 12894 0 0]Sorry... *wheeze* It's happening again... *pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]It'll pass soon... but would you mind... staying with me until then...?[n][uf 1 1][e]

[msg MSG_040_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12833 0 0]Thank you... You're very kind...[n][uf 1 1][e]

[msg MSG_041_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12809 0 0]Ah, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]I'd like to speak with you again, should fate allow.[n][uf 1 1][e]

[msg MSG_042_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12832 0 0]Ah, I'm glad to hear it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]Through our conversations, this bench becomes the bridge that connects me to humanity.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12822 0 0]Ah, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0]I've been looking forward to the next time I could speak with you.[n][uf 1 1][e]

[msg MSG_044_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12830 0 0]You'll stay? Thank you, truly...[n][uf 1 1][e]

[msg MSG_045_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12810 0 0]Ah, you— *cough* *cough*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*wheeze* *wheeze*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]*cough* *cough* *pant* *pant*[n][uf 1 1][e]

[msg MSG_046_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12896 0 0]I'm... *cough* all right...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0]Sorry... *cough* *cough* It'll pass... soon...[n][uf 1 1][e]

[msg MSG_047_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 3 0 65535 12894 0 0]Thank y— *cough* I'm glad... you came...[n][uf 1 1][e]

[msg MSG_048_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12802 0 0]Ah, it's you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]Would you like to talk for a bit? You can sit here, as usual...[n][uf 1 1][e]

[msg MSG_049_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12830 0 0]Thank you. Today is actually a special day...[n][uf 1 1][e]

[msg MSG_050_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 3 0 65535 12830 0 0]Thank you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]This bench really is our special little place.[n][uf 1 1][e]

[msg MSG_051_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 3 0 65535 12896 0 0]I see... *cough* *pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]Don't worry, I'm all right. I'm just... going to rest here for a bit...[n][uf 1 1][e]

[msg MSG_052_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 3 0 65535 12896 0 0]I see... *cough* *pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]...I'm okay. I'm just... going to stay here a little longer.[n][uf 1 1][e]

[msg MSG_053_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12814 0 0]Oh, I see. That's all right. Your time is your own.[n][uf 1 1][e]

[msg MSG_054_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12814 0 0]I see... Well, I look forward to when we meet again.[n][uf 1 1][e]

[msg MSG_055_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 3 0 65535 12896 0 0]I see... *cough* *pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0]It's okay... I'm all right. It's... nice and warm here.[n][uf 1 1][e]

[msg MSG_056_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12817 0 0]I see... I hope I'll have a chance to see you again.[n][uf 1 1][e]

[msg MSG_057_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 3 0 65535 12818 0 0]I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0]I'll see you later, then. I'm going to stay here for now.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I still spend time with them...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Should I spend the day[n]with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Should I spend time online playing[n]the MMORPG with [uf 2 4 0]...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Should I spend the evening[n]with [uf 2 4 0]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Spend time with [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with the [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Should I spend the day at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Should I spend the night[n]with [uf 2 4 1]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Spend time w/ [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Enter the bookstore[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, right. There's something else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

