[msg MSG_000_0_0 [Upset Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 8 0 0]Wha— Kaz, what are you doing? Why are you wearing a jersey!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Boy Wearing a Jersey]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 1 9 0 0]What do you mean "why"? We've got practice after class, remember?[n][uf 1 1][e]

[msg MSG_002_0_0 [Upset Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 10 0 0]But we've got to attend the opening ceremony and go to class before all that![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 11 0 0]Hurry and head into your classroom so you can change into your normal uniform![n][uf 1 1][e]

[msg MSG_003_0_0 [Boy Wearing a Jersey]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 1 12 0 0]What? But I just... Okay, okay, fine. Just quit glaring at me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 1 13 0 0]So where's the bulletin board with all the class assignments?[n][uf 1 1][e]

[msg MSG_004_0_0 [Upset Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 14 0 0]It's literally right there, Kaz! You're in Class F.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 15 0 0]I'm in a different homeroom, so I can't keep an eye on you all the time... You got that!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Upset Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 1 16 0 0]...I worry about you sometimes.[n][uf 1 1][e]

[msg MSG_006_0_0 [Boy Wearing a Jersey]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 1 17 0 0]Who are you, my mom?[n][uf 1 1][e]

