[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Rest easy. You and I will be together all the time now, [uf 4 2]-san.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6080 0 0]I have inspected the entire school, but I did not locate anyone suffering from Apathy Syndrome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Should I conclude that they are absent?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Junpei-san has already left school. He went to the hospital.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Lately, he seems to be emotionally distressed.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Junpei-san went to the hospital again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]He seemed quite eager to get there. Has the questioning been going smoothly?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Yep.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]He's making... "progress."[e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6030 0 0]We can expect some useful information, then.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6057 0 0]That is unfortunate, but not unexpected.[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6051 0 0]Do I detect an underlying meaning? Is there something between her and Junpei-san that I am not aware of?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]In any case, I have difficulty grasping those kinds of subtleties.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6064 0 0]Everyone seems excited about the upcoming festival.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I have yet to experience such an event, so I cannot relate.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]I have heard that Yukari-san is going to be working at a maid café during the festival.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I am not familiar with the concept. However...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]The male students in particular seem exceptionally excited to see her new outfit.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]That was quite a sizable typhoon. I had expected the school would have sustained some damage.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]However, I was mistaken. It must have been durably constructed.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]She's still far from passing as a human...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't look like she understands[n]ordinary feelings and conversation yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If she could, I might be able[n]to form a bond with her.[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6051 0 0]May I ask you something?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Do you think anyone suspects that I am a robot?[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]No way.[e]
[uf 0 5 65278][uf 2 1]It's possible.[e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6030 0 0]Understood. Then, no adjustments are necessary.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6064 0 0]Do I lack human mannerisms?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]From now on, I will attempt to mimic various idiosyncrasies to avoid detection.[n][uf 1 1][e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6080 0 0]The moon will soon be full again. Have you made adequate preparations for the battle?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If you feel unprepared, you should go to the mall immediately after school.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6064 0 0]It is unfortunate, but not many students appear to be saddened by Aragaki-san's death.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Apparently, human relationships are quickly forgotten, though our case is exceptional.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6030 0 0]It is rational for students to concentrate on their exams, rather than Aragaki-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]However, for some unknown reason...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I question the value of thinking like that.[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6051 0 0]Fuuka-san said she "figured it out."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]What do you think, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]I understand her.[e]
[uf 0 5 65278][uf 2 1]I don't get it.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6030 0 0]That's good to hear.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6037 0 0]Neither do I.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0][uf 4 25 7]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm sorry, I was just thinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I was considering what I might stand to gain from attending school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]But, I suppose nothing will come of this line of thought. It's not something I should entertain.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6074 0 0]Junpei-san seems to sleep a great deal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]He must be conserving energy to remain prepared for combat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]It is quite an interesting tactic.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0][uf 4 25 7]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm sorry, I was just thinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I was wondering what will become of me once we have defeated all the Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I hope I can continue to attend school.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Tomorrow is the final battle. Are you ready?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]If you need supplies or equipment, make sure to get everything today.[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6050 0 0]For some reason, I was unable to concentrate on the lesson today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]This is very unlike me. I have never lost focus on an assignment before...[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6143 0 0]Ryoji-san is dangerous.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0]I have re-analyzed him, and still detect nothing out of the ordinary. Nonetheless, I have a "bad feeling" about him.[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6074 0 0]The fact that this school conducts its field trips every other year is unusual, is it not?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]So there was no trip last year, which means the current third-years haven't gone on their school trip yet...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]First-year students don't go on a trip, so this year, the second- and third-years are going together.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]Most of the people I meet appear nervous about the upcoming trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Are you nervous, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Naturally.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]How about you, Aigis?[e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6142 0 0]That's good. You're just like everyone else, then.[n][uf 1 1][e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0]You seem calm. Perhaps you should be a little more nervous...[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6081 0 0]I don't know. Do I seem like I am?[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6106 0 0]Deciding on one's career seems to be a fascinating process.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]However, since I am designed primarily for combat, it wouldn't be very useful for me.[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6074 0 0]Junpei-san went home early today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]He was clearly in low spirits. It seems he hasn't fully recovered from the incident...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]I'm worried about him...[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6119 0 0]I'm worried about Ryoji-san, and it's even affecting my concentration...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]This is a grave situation. What should I do...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]

[msg MSG_044_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0]Ryoji-san didn't come to school today... I wonder what happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]

[msg MSG_045_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2078 0 0]UNUSED[n][uf 1 1][e]

[msg MSG_046_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 4 25 7]Unused[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 157 65535 0 0][uf 3 1 3 0 65535 6087 0 0]I drew a paper fortune, and it said, "Great Luck."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 157 65535 0 0]I'm sure that means everything will work out for the best.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Aigis]]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I still spend time with them...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Should I spend the day[n]with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Should I spend time online playing[n]the MMORPG with [uf 2 4 0]...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Should I spend the evening[n]with [uf 2 4 0]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Spend time with [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with the [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Should I spend the day at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Should I spend the night[n]with [uf 2 4 1]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Spend time w/ [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Enter the bookstore[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, right. There's something else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

