[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Who should I spend time with...?[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]Should I spend time[n]with [uf 2 4 0]...?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with Mitsuru[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Spend time with Yuko[uf 4 27 106 0][e]
[uf 0 5 65278][uf 2 1]Spend time with Yukari[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Spend time with Fuuka[uf 4 27 6 0][e]
[uf 0 5 65278][uf 2 1]Spend time with Chihiro[uf 4 27 109 0][e]
[uf 0 5 65278][uf 2 1]Spend time alone[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Should I decline the invitation[n]and spend time alone?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Should I decline the invitations[n]and spend time alone?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Reconsider[e]
[uf 0 5 65278][uf 2 1]Politely decline[e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]恋人がいないと選択肢を表示出来ません。[n][uf 1 5 0]エディタを使用して恋人を設定してください。[n][uf 1 1][e]

