[msg MSG_000_0_0 [Maiko's Mom]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]*huff* *huff* What's going on? She's not here![n][uf 1 1][e]

[msg MSG_001_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 2]Where else would she go...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 2]Wait... Maybe she went to get takoyaki![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]She must be hungry by now, right? Takoyaki is her favorite![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 2]Let's go![n][uf 1 1][e]

