[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]This is a ridiculous amount of burgers.[n]I wonder if I'll be able to finish everything...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]No matter how much I eat, the amount[n]of burgers doesn't seem to decrease...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Focus on a single burger[uf 2 9 1 2 3481][e]
[uf 0 5 65278][uf 2 1]Look away from the burgers[e]
[uf 0 5 65278][uf 2 1]Glance at the pile of burgers[uf 2 9 1 2 3481][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Eating while staring off into the distance[n]made me feel a little better...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Instead of flavor, each bite only brings more[n]pain... I don't think I can finish everything...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I feel like I'm making progress, but[n]I shouldn't get ahead of myself...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Eat without stopping[e]
[uf 0 5 65278][uf 2 1]Take breaks in between bites[uf 2 9 1 2 3481][e]
[uf 0 5 65278][uf 2 1]Wash it down with soda[uf 2 9 1 2 3481][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Working through the pain, I managed to[n]maintain my pace without stopping...![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]My stomach hurts... I lost pace and[n]I can't seem to get back on track...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]It's the final stretch... How can I keep[n]this up and complete the challenge...?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Savor the flavors[uf 2 9 1 2 3481][e]
[uf 0 5 65278][uf 2 1]Imagine something sour[e]
[uf 0 5 65278][uf 2 1]Chew properly and slowly[uf 2 9 1 2 3481][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Imagining eating something sour instead[n]helped me maintain my pace...![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]My stomach feels like it's going to burst...[n]It seems like I'm not making any progress.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Time's up...[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I managed to eat the mountain of burgers...![n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Pacing, technique, and mental fortitude[n]were all required. I feel like I've grown...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Thanks to completing[n]the Big Eater Challenge...[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I can now order the limited Weekend[n]Wilduck Set when it's available![n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]First, I should report back to Elizabeth...[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]...I couldn't eat it all. I'll have to[n]try again some other time...[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Although I couldn't finish it, I feel like[n]I've grown just by taking the challenge...[n][uf 1 1][e]

