[msg SYS_000_0_0]
[uf 0 5 65278][uf 2 1]In New Game+, you can carry over some content from your clear data to your new game.[n][uf 1 1][e]

[msg SYS_001_0_0]
[uf 0 5 65278][uf 2 1]Content carried over into the new game is as follows (note that [uf 0 1 2]items in red will always carry over[uf 0 1 27]):[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- Personas[n]- Persona Compendium[n]- Analysis information[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- Stats[n]- Social Stats[n]- Protagonist level[n]- Protagonist HP/SP gains outside of leveling[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- Teammate stat boosts from Incense[n]- Teammate HP/SP gains outside of leveling[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- Items[n]- Equipment[n]- Skill Cards[n]- Materials[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- Twilight Fragments[n]- [uf 0 1 2]All costumes besides SEES uniforms[uf 0 1 27][n]- [uf 0 1 2]Some souvenirs received from characters[uf 0 1 27][n]- Items received from characters for unlocking Personas[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]- [uf 0 1 2]Play time[uf 0 1 27][n]- Money[n][uf 1 1][e]

[msg SYS_002_0_0]
[uf 0 5 65278][uf 2 1]Carry over clear data?[n][uf 1 4 1][uf 1 1][e]

[msg SYS_003_0_0]
[uf 0 5 65278][uf 2 1]Starting new game with clear data carried over.[n][uf 1 1][e]

[msg SYS_004_0_0]
[uf 0 5 65278][uf 2 1]Clear data will not be carried over. Will you proceed?[n][uf 1 4 1][uf 1 1][e]

[msg SYS_005_0_0]
[uf 0 5 65278][uf 2 1]Starting new game without carrying over clear data.[n][uf 1 1][e]

[msg SYS_006_0_0]
[uf 0 5 65278][uf 2 1]In [uf 0 1 2]Merciless[uf 0 1 27] difficulty, only the following content is carried over:[n][uf 1 1][e]

[msg SYS_007_0_0]
[uf 0 5 65278][uf 2 1]- [uf 0 1 2]All costumes besides SEES uniforms[uf 0 1 27][n]- [uf 0 1 2]Some souvenirs received from characters[uf 0 1 27][n]- [uf 0 1 2]Play time[uf 0 1 27][n][uf 1 1][e]

[msg SYS_008_0_0]
[uf 0 5 65278][uf 2 1]Proceed with [uf 0 1 2]Merciless[uf 0 1 27] difficulty?[n][uf 1 4 1][uf 1 1][e]

