[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]The scratching of pencils echoes[n]throughout the art room...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It's been so fun that the hours flew by.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Let's wrap up for today. Good work, everyone.[n][uf 1 1][e]

[msg MSG_002_0_0 [Female Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 150]Whew, all done![n][uf 1 1][e]

[msg MSG_003_0_0 [Male Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 100]All right, let's clean up and go home.[n][uf 1 1][e]

