[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]So in the last volume, we left off just as the hero passed out from pushin' himself too hard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]That part where his teammates manage to keep an even score while he's out was such a tear-jerker![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 3 1 25 25]The game's almost over, and our hero—still weak after a short rest—steps up to bat...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's getting exciting![e]
[uf 0 5 65278][uf 2 1]It's pretty cliché.[e]
[uf 0 5 65278][uf 2 1]What happens next?[e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Hey, you totally get it! I honestly thought you wouldn't be into it so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]It's predictable, but it doesn't stop it from being awesome! Man I forgot how good stories like these are.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Well sure, but... you gotta just enjoy it for what it is, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 3 1 25 25]It's predictable, but it doesn't stop it from being awesome! Man I forgot how good stories like these are.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Well read it and find out! Unless you want me to just spoil it all for ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 3 9 25 25]I know it's only a manga, but it's been a long time since I've been this pumped up![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Alright, now that we're at the best part, let's go full speed 'til the end![n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Whew... What a ride.[n][uf 1 1][e]

[msg MSG_006_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]The hero totally kicks everyone's asses in the end. And that part where he's so exhausted that he, like, surges with power...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]It's like his senses heightened to a whole 'nother level. Wouldn't it be so freakin' cool if we could do that?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Why don't you give it a shot?[e]
[uf 0 5 65278][uf 2 1]That only happens in manga.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Think so? It's gonna be intense, y'know. It's what separates the chumps from the masters.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]No way, man! I think it's worth a shot! It's what separates the chumps from the masters![n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]You can't just rely on raw strength. You gotta concentrate, let go of all that tension...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 3 1 25 25]Then gzzzzt! Your power's all like womwomwom, and you unleash it like pchooooo![n][uf 1 1][e]

[msg MSG_010_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Or maybe you power up like HNNNGH, then let 'er rip—FYOOO, PCHOOOOO! That make sense?[n][uf 1 1][e]

[msg MND_010_7_0]
[uf 0 5 65278][uf 2 1]Junpei picked up some combat tips[n]from the hero of the baseball manga.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Dude, I think I might actually be able to pull this off. I gotta look into this more.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Wanna read it one more time? Just the last part, I mean.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]The young hero's dedication[n]filled me with [uf 4 30 2 1 1 0]![n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]And that, my friend, wraps up the series.[n][uf 1 1][e]

[msg MSG_013_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Reading alone's fine, but with gems like this one, it's better to share the fun with a pal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I'll bring you somethin' else next time. We should do this again when you're free.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Let's call it a night, shall we? Man, I'm gonna sleep like a log.[n][uf 1 1][e]

