[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey.[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]I had the usual for lunch...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]I was wondering what ramen tastes like when you skip class.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]It's surprisingly good... You could've invited me at least once, you know.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Come on, say something.[n][uf 1 1][e]

[msg MSG_002_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Why do you have to be like that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Always going off without saying a word.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Put yourself in my shoes, for a change...[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]...You think it's the other way around?[n][uf 1 1][e]

[msg MSG_003_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]Yeah, you're right...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]I was the one always running off on my own. I was too obsessed with getting stronger...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Ever since I lost Miki, that's all I've cared about.[n][uf 1 1][e]

[msg MSG_003_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 13 0 0]I thought if I was strong enough, I could protect anyone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 14 0 0]But I was wrong... And now you're gone, too. God, it's like the world is laughing at me...[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 15 0 0]I knew what we were getting into... I knew we were putting our lives on the line![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 16 0 0]But I was so focused on fighting that I didn't see anything else![n][uf 1 1][e]

[msg MSG_004_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 17 0 0]It doesn't matter how strong I was! Look what happened![n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 64 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Aaaaaahhh...![n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0]...I know, Shinji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Crying won't change anything, right?[n][uf 1 1][e]

[msg MSG_006_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 21 0 0]I don't need you to tell me that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 22 0 0]In the end, I can't run away from who I am.[n][uf 1 1][e]

[msg MSG_006_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 23 0 0]...I've had enough of this.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The resolution in Sanada's heart has awakened a new Persona...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Sanada's Persona, [uf 0 1 35]Polydeuces[uf 0 1 27], has given rise to [uf 0 1 35]Caesar[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]Rest easy, Shinji. You just watch from there with Miki.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]I've still got a job to do...[n][uf 1 1][e]

[msg MSG_009_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]...Isn't that right?[n][uf 1 1][e]

