[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Sure. Hmm... This one's difficult. Let's see...[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]I know the answer.[e]
[uf 0 5 65278][uf 2 1]Let's work it out together.[e]
[uf 0 5 65278][uf 2 1]You're up, Junpei.[e]

[msg MND_022_5_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I don't know how to solve this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If my [uf 4 30 0 1 1 0] were[n]at least [uf 4 31 0 3 1 0], maybe[n]I could figure it out...[n][uf 1 1][e]

