[msg MSG_000_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Aahh... Aaaaghhh...[n][uf 1 1][e]

[msg MSG_001_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ah... Uh...[n][uf 1 1][e]

[msg MSG_002_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Uhhh... Ah... Aaah...[n][uf 1 1][e]

[msg MSG_003_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Uahhhh... Auhhh...[n][uf 1 1][e]

[msg MSG_004_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Uhh... Uhwa... Aah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Uhhh...[n][uf 1 1][e]

[msg MSG_005_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Aaaaaah... Uhh... Nnhhh...[n][uf 1 1][e]

[msg MSG_006_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Auhhhh... Uaaaahhhh...[n][uf 1 1][e]

[msg MSG_007_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Uh... Uhhhh...[n][uf 1 1][e]

[msg MSG_008_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Uhhhh... Uhhh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Uhhhhhh... Uh...[n][uf 1 1][e]

[msg MSG_009_0_0 [Apathy Syndrome Woman]]
[uf 0 5 65278][uf 2 1]Uaaahhhh... Ahhh... Auhhh...[n][uf 1 1][e]

