[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono seems to have stepped out...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Takenozuka]]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0][uf 3 1 3 0 65535 15603 0 0]I should get going since there's no time to waste. If I power walk to the station, it'll take seven minutes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]But if I consider the speed at which the train pulls into the station, three minutes might not be enough...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]Oh yeah... I'm in charge of dinner tonight, so that's another twelve minutes to get groceries...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]I better compensate for the pressure ratio when mashing potatoes to avoid inefficiency...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]If an average potato's diameter is about twelve centimeters, then that comes out to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]...Oh, forget it! Going home isn't worth the trouble! I'm staying at school![n][uf 1 1][e]

[msg MSG_002_0_0 [Mr. Takenozuka]]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0][uf 3 1 3 0 65535 15621 0 0]Oh, it's you, [uf 4 1]. Did you want to stay the night at school too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]...You're looking for Mr. Ono?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]Now that you mention it, I haven't seen that helmet lately... Oh, uh, I mean, that teacher.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]I don't have time to fritter away looking for him either, so try again later.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mr. Takenozuka]]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0][uf 3 1 3 0 65535 15622 0 0]You know, that helm of his really is a nice piece.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]I'd never say that to Mr. Ono's face because I'd never hear the end of it, but it's fine craftsmanship.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]The curved line at the top... It's an ideal arc for absorbing impact.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]An arc like that can absorb about 48% of the impact from above.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]Then there's the material. It's not just a thick chunk of metal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]It's extremely thin metal, in fact, layered with finely-braided hemp for added practicality...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Mr. Takenozuka keeps going[n]on and on with his lecture...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mr. Takenozuka]]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0][uf 3 1 3 0 65535 15606 0 0]So, that explains that. See? Isn't it a wonderful specimen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1084 0 65535 65535 0 0]Hm? Its origin? I wouldn't know anything about that. I have zero interest in archaeology.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I learned how ancient[n]helms are constructed...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono doesn't seem to be returning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to give up for today.[n][uf 1 1][e]

