[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Yukari seems to be having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We enjoyed watching a DVD together...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25][uf 5 13 7 1 2]Phew, that was fun![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]By observing the main character, I've begun to[n]understand the [uf 4 30 1 1 1 0] of an adult...[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]Well, we should probably head to bed. Have a good night![n][uf 1 1][e]

