[msg MSG_000_0_0 [Third-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]Anemia?[n][uf 1 1][e]

[msg MSG_001_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 2]C'mon, we're counting on you to be captain next year.[n][uf 1 1][e]

[msg MSG_002_0_0 [Third-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]The big meet's next year, so you've got time. Just don't overdo it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Third-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Hey, [uf 4 1], why don't you leave practice early and take him home?[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 5 0 0]...Sorry.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 6 0 0]What are you looking at? I'm fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 105 3 25 25]It's just, um... my anemia's acting up.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Sorry, that sounds awful![e]
[uf 0 5 65278][uf 2 1]Are you going to be okay?[e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 8 0 0]Oh, no, no. I-It's nothing serious...[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 8 5 105]O-Of course. It's just, you know, a touch of anemia...[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 10 0 0]Argh, dammit! I can't do it! I can't lie to you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 105 3 25 25]Look, the truth is...[n][uf 1 1][e]

[msg MSG_009_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 12 0 0]It's my knee. It hasn't felt right ever since that day you first came to practice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 13 0 0]I tried medicine, I tried wrapping it, but the pain won't stop.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Will it heal?[e]
[uf 0 5 65278][uf 2 1]Take a break from practice.[e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 8 5 105]Of course it will! But I can't afford to stop training, so I'll play through the pain![n][uf 1 1][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 15 0 0]No can do. And there's no way you're gonna make me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0]Next year, there's a national competition.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]Athletes from all over Japan will be there. The regionals don't hold a candle in comparison.[n][uf 1 1][e]

[msg MSG_013_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 18 0 0]And if I want to win, then I have to spend the next year training![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 105 3 25 25]A lot of guys on the team are nosy as hell. If they find out about my knee, they won't leave me alone.[n][uf 1 1][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 20 0 0]So please, keep it a secret, okay? We gotta look out for each other![n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems to be counting on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming closer...[n][uf 1 1][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 21 0 0]If I go easy on it, I can make it home by myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 22 0 0]Don't worry about me. You get on back to training.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Miyamoto[n]and went home after practice.[n][uf 1 1][e]

