[msg TRL_000_0_0 [Status Ailment: Confuse]]
[uf 0 5 65278][uf 2 1][uf 4 8 36]Enemies who are [uf 0 1 2]Confused[uf 0 1 27] will roam around unsteadily, as though drunk.[n][uf 1 1][e]

[msg TRL_001_0_0 [Status Ailment: Confuse]]
[uf 0 5 65278][uf 2 1][uf 4 8 36][uf 0 1 2]They move slowly, and are prone to missing their attacks[uf 0 1 27], making them prime targets to pick off with Chance Encounters.[n][uf 1 1][e]

