[msg TRL_000_0_0 [Changing the Party]]
[uf 0 5 65278][uf 2 1][uf 4 8 10]You can decide who to take into combat at [uf 0 1 2]locations where you can change party members[uf 0 1 27], such as the Desert of Doors.[n][uf 1 1][e]

[msg TRL_001_0_0 [Changing the Party]]
[uf 0 5 65278][uf 2 1][uf 4 8 10]You can change party members by talking to your teammates or by opening the menu with [uf 1 3 112] and selecting [uf 0 1 2]STATS[uf 0 1 27].[n][uf 1 1][e]

