[msg TRL_000_0_0 [Dashing]]
[uf 0 5 65278][uf 2 1][uf 4 8 7]You can [uf 0 1 2]dash[uf 0 1 27] by pressing and holding [uf 1 3 118] while moving. You'll cover ground more quickly, making your exploration of the Abyss of Time more efficient.[n][uf 1 1][e]

[msg TRL_001_0_0 [Dashing]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]However, [uf 0 1 2]enemies will spot you more easily when dashing[uf 0 1 27], so be careful.[n][uf 1 1][e]

