[msg TRL_000_0_0 [Fuuka's Skills: Jamming]]
[uf 0 5 65278][uf 2 1][uf 4 8 27]Jamming is a support skill that [uf 0 1 2]makes you undetectable to enemies[uf 0 1 27]. Use it when you're running low on HP or when you want to pick up treasure chests without being detected.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fuuka's Skills: Jamming]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Jamming is [uf 0 1 2]ineffective against certain enemies[uf 0 1 27], and will be disabled once you [uf 0 1 2]enter combat or change floors[uf 0 1 27].[n][uf 1 1][e]

