[msg TRL_000_0_0 [Auto-Recover]]
[uf 0 5 65278][uf 2 1][uf 4 8 8]You can press [uf 1 3 117] during an exploration to automatically recover HP. A party member's recovery skill will be used to [uf 0 1 2]instantly restore HP for all party members[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Auto-Recover]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Using a recovery skill to auto-recover HP will also cost SP, so if you run out of SP, you will not be able to auto-recover. Be sure to monitor your SP whenever you use it.[n][uf 1 1][e]

