[msg TRL_000_0_0 [Types of Attacks and Encounters]]
[uf 0 5 65278][uf 2 1][uf 4 8 4]You can fire by pressing [uf 1 3 111] while exploring to hit an enemy. Doing so will start combat.[n][uf 1 1][e]

[msg TRL_001_0_0 [Types of Attacks and Encounters]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Striking an enemy from behind will trigger a [uf 0 1 2]Chance Encounter[uf 0 1 27], where [uf 0 1 2]you have the advantage[uf 0 1 27] at the start of combat. If the enemy attacks you first, a [uf 0 1 2]Pinch Encounter[uf 0 1 27] will occur, [uf 0 1 2]placing you at a disadvantage[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Types of Attacks and Encounters]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Although you can fire at enemies from afar, the sound may attract other foes. Try to quickly initiate Chance Encounters to gain the upper hand for easy victories.[n][uf 1 1][e]

