[msg TRL_000_0_0 [Returning to the Furthest Explored Floor]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]One-way teleporters are found throughout the Abyss of Time, and can be used to instantly return to the Desert of Doors.[n][uf 1 1][e]

[msg TRL_001_0_0 [Returning to the Furthest Explored Floor]]
[uf 0 5 65278][uf 2 1][uf 4 8 46]Even after returning to the Desert of Doors, you can speak to Fuuka by the entrance to return to your [uf 0 1 2]furthest explored floor[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Returning to the Furthest Explored Floor]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Heading back could be a good idea if you find yourself stuck.[n][uf 1 1][e]

