[msg TRL_000_0_0 [Crumbling Objects]]
[uf 0 5 65278][uf 2 1][uf 4 8 45]You are now able to [uf 0 1 2]Crumble[uf 0 1 27] breakable objects while exploring.[n][uf 1 1][e]

[msg TRL_001_0_0 [Crumbling Objects]]
[uf 0 5 65278][uf 2 1][uf 4 8 45]While in the [uf 0 1 2]assault state[uf 0 1 27], you will destroy breakable objects simply by making contact with them. Keep in mind, however, that Shadows will not be affected by Crumble in any way.[n][uf 1 1][e]

