[msg TRL_000_0_0 [Returning from the Abyss of Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can use the stairs in the Desert of Doors to return to the dorm. Doing so will fully restore your HP and SP.[n][uf 1 1][e]

[msg TRL_001_0_0 [Returning from the Abyss of Time]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]The layout of the Abyss of Time will change[uf 0 1 27] each time you enter it. [uf 0 1 2]Treasure chests you have already found can be rediscovered[uf 0 1 27] as well, so returning could be a good idea if you find yourself stuck.[n][uf 1 1][e]

