[msg TRL_000_0_0 [Formidable Shadows]]
[uf 0 5 65278][uf 2 1][uf 4 8 15]While exploring the Abyss of Time, you may encounter the rare [uf 0 1 2]Formidable Shadow[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Formidable Shadows]]
[uf 0 5 65278][uf 2 1][uf 4 8 15]Defeating them will yield greater rewards than usual, but [uf 0 1 2]brace yourself for a trying battle[uf 0 1 27] and take care not to become the hunted.[n][uf 1 1][e]

