[msg TRL_000_0_0 [Minimap and Movement Shortcuts]]
[uf 0 5 65278][uf 2 1][uf 4 8 12]While exploring, you can press [uf 1 3 114] to open the [uf 0 1 2]Minimap[uf 0 1 27], which shows your current location as well as the path you traveled.[n][uf 1 1][e]

[msg TRL_001_0_0 [Minimap and Movement Shortcuts]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]It also displays information on [uf 0 1 2]enemy and treasure chest locations[uf 0 1 27], so don't hesitate to check it every now and then.[n][uf 1 1][e]

[msg TRL_002_0_0 [Minimap and Movement Shortcuts]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]After finding the stairs[uf 0 1 27], you can use the shortcut to move to the next floor [uf 0 1 2]from any spot[uf 0 1 27]. It could be worth your while to scour the current floor before moving on to the next.[n][uf 1 1][e]

