[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]It's day three of our vacation in Yakushima...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 102 65535 0 0][uf 3 1 1 0 0 1 0 0]Man, I can't believe it's already the third day of our trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 102 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 3 3 25 25]It's too bad we have to go home tomorrow. I'd totally stay longer if I could.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 102 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 3 0 25 25]But I can't complain too much. We went through a hell of a lot here![n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 102 65535 0 0][uf 3 1 1 0 0 4 0 0]Yeah, like hearing you and the chairman singing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 102 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 21 4 10]I barely got any sleep last night.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0]Do we have a mission at the beach today?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 7 0 0]Nah, it's nothing like that. We just came here to have some fun.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 65535 0 0][uf 3 1 1 0 0 8 0 0]Do you understand what it means to have fun, Aigis?[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 9 0 0]Yes, I am informed of the concept. Recreation is sustenance for one's mental wellbeing.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 10 0 0]Yeah, exactly! Wow, you sure know a lot about us humans.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 0 11 0 0]Alright, let's take one last dip before we leave![n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 102 65535 0 0][uf 3 1 1 0 0 12 0 0]Uh, wait, Junpei-kun...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 102 65535 0 0][uf 3 1 1 0 0 13 0 0]Is it okay for Aigis to go in the water?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 102 65535 0 0][uf 3 1 1 0 0 14 0 0]I'm sure she's fine.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 65535 0 0][uf 3 1 1 0 0 15 0 0]Oh, are you done already?[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 16 0 0]It is best that everyone partake in this activity together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 17 0 0]Deriving enjoyment alone is not the optimal method to "have fun."[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 102 65535 0 0][uf 3 1 1 0 0 19 0 0]You've got some strong feelings on pretty weird things, don't you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 102 65535 0 0][uf 3 1 1 0 0 20 0 0]But what the heck, might as well![n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 102 65535 0 0][uf 3 1 1 0 0 21 0 0]We should join them.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 102 65535 0 0][uf 3 1 1 0 0 22 0 0]Agreed.[n][uf 1 1][e]

[msg MSG_016_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Enjoying yourselves?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Quite a lot's happened during our time here, but it looks like we'll get to relax a bit today.[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 102 65535 0 0][uf 3 1 1 0 0 25 0 0]That would be nice.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]Sanada-san! What're you doin'!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]C'mon, it's your turn![n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 28 0 0]My turn? What are they doing?[n][uf 1 1][e]

[msg MSG_020_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Hahaha! Glad to see everyone's having so much fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 0 25 25]I've already told you what time the ship is arriving tomorrow, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I'll probably head over to the port early, so don't be late.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 32 0 0]Okay, I'll let everyone know.[n][uf 1 1][e]

[msg MSG_022_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]We can get back to business once we've returned to the dorm.[n][uf 1 1][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 102 65535 0 0][uf 3 1 1 0 0 34 0 0]Got it.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]Heeey, [uf 4 2]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]Sanada-san![n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 102 65535 0 0][uf 3 1 1 0 0 37 0 0]All right. I guess we should join too, [uf 4 1].[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 38 0 0]Aigis, wait! That's not what water gun means![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 39 0 0]Aaaaaack![n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 102 65535 0 0][uf 3 1 1 0 0 40 0 0]Junpei-kun is down![n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 102 65535 0 0][uf 3 1 1 0 0 41 0 0]All right, here's our chance for an All-Out Attack![n][uf 1 1][e]

[sel SEL_029_0_0 top]
[uf 0 5 65278][uf 2 1]All-Out Attack![e]
[uf 0 5 65278][uf 2 1]Maybe not.[e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 42 0 0]Wait, time out! I seriously can't take—! Gyaaaaaah![n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 102 65535 0 0][uf 3 1 1 0 0 43 0 0]I'm saved...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 102 65535 0 0][uf 3 1 1 0 0 44 0 0]Seriously guys, it's just a game. Could ya not treat this like a life-or-death battle?[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]I had a fun time with[n]everyone in Yakushima...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]With Aigis joining, things[n]are likely to get livelier...[n][uf 1 1][e]

