[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 157 65535 0 0][uf 3 1 1 0 0 1 0 0]What did you wish for, Fuuka?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 157 65535 0 0][uf 3 1 1 0 0 2 0 0]I... I wished for a great year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 157 65535 0 0][uf 3 1 1 0 0 3 0 0]I know it sounds boring, but that's what I really want.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 157 65535 0 0][uf 3 1 1 0 0 4 0 0]That's what I wished for as well.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 157 65535 0 0][uf 3 1 1 0 0 5 0 0]We all wished for the same thing![n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 157 65535 0 0][uf 3 1 1 0 0 6 0 0]However, I'm not praying for divine help.[n][uf 1 1][e]

[msg MSG_004_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 157 65535 0 0][uf 3 1 1 0 0 7 0 0]There's nothing to worry about. I have the utmost certainty that we can do this.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 157 65535 0 0][uf 3 1 1 0 0 8 0 0]Yeah. I know we can.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 157 65535 0 0][uf 3 1 1 0 0 9 0 0]We should get going.[n][uf 1 1][e]

