[msg MND_GOINTO_HOME_OK]
[uf 0 5 65278][uf 2 1]Наверное, мне пора домой...[n][uf 1 1][e]

[sel INTO_HOME_SEL top]
[uf 0 5 65278][uf 2 1]Вернуться домой[e]
[uf 0 5 65278][uf 2 1]Задержаться[e]

[msg MND_GOINTO_HOME_CMM_NO]
[uf 0 5 65278][uf 2 1]На улице так хорошо. Пожалуй, стоит дольше погулять по городу.[n][uf 1 1][e]

[sel SEL_INTO_HOME_CMM top]
[uf 0 5 65278][uf 2 1]Гулять дальше[e]
[uf 0 5 65278][uf 2 1]Вернуться домой[e]

