[msg ItemAddEffectMSG_000]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg ItemAddEffectMSG_001]
[uf 0 5 65278][uf 2 1]+10 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_002]
[uf 0 5 65278][uf 2 1]+20 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_003]
[uf 0 5 65278][uf 2 1]+30 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_004]
[uf 0 5 65278][uf 2 1]+40 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_005]
[uf 0 5 65278][uf 2 1]+50 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_006]
[uf 0 5 65278][uf 2 1]+100 ОЗ[n][uf 1 1][e]

[msg ItemAddEffectMSG_007]
[uf 0 5 65278][uf 2 1]+10 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_008]
[uf 0 5 65278][uf 2 1]+20 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_009]
[uf 0 5 65278][uf 2 1]+30 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_010]
[uf 0 5 65278][uf 2 1]+40 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_011]
[uf 0 5 65278][uf 2 1]+50 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_012]
[uf 0 5 65278][uf 2 1]+100 ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_013]
[uf 0 5 65278][uf 2 1]+Заморозка (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_014]
[uf 0 5 65278][uf 2 1]+Заморозка (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_015]
[uf 0 5 65278][uf 2 1]+Заморозка (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_016]
[uf 0 5 65278][uf 2 1]+Электрошок (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_017]
[uf 0 5 65278][uf 2 1]+Электрошок (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_018]
[uf 0 5 65278][uf 2 1]+Электрошок (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_019]
[uf 0 5 65278][uf 2 1]+Смятение (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_020]
[uf 0 5 65278][uf 2 1]+Смятение (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_021]
[uf 0 5 65278][uf 2 1]+Смятение (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_022]
[uf 0 5 65278][uf 2 1]+Страх (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_023]
[uf 0 5 65278][uf 2 1]+Страх (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_024]
[uf 0 5 65278][uf 2 1]+Страх (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_025]
[uf 0 5 65278][uf 2 1]+Паника (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_026]
[uf 0 5 65278][uf 2 1]+Паника (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_027]
[uf 0 5 65278][uf 2 1]+Паника (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_028]
[uf 0 5 65278][uf 2 1]+Очарование (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_029]
[uf 0 5 65278][uf 2 1]+Очарование (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_030]
[uf 0 5 65278][uf 2 1]+Очарование (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_031]
[uf 0 5 65278][uf 2 1]+Ярость (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_032]
[uf 0 5 65278][uf 2 1]+Ярость (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_033]
[uf 0 5 65278][uf 2 1]+Ярость (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_034]
[uf 0 5 65278][uf 2 1]+Отравление (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_035]
[uf 0 5 65278][uf 2 1]+Отравление (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_036]
[uf 0 5 65278][uf 2 1]+Отравление (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_037]
[uf 0 5 65278][uf 2 1]+Случ. нег. эффект (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_038]
[uf 0 5 65278][uf 2 1]+Случ. нег. эффект (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_039]
[uf 0 5 65278][uf 2 1]+Случ. нег. эффект (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_040]
[uf 0 5 65278][uf 2 1]+Повыш. шанса крит. удара (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_041]
[uf 0 5 65278][uf 2 1]+Повыш. шанса крит. удара (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_042]
[uf 0 5 65278][uf 2 1]+Повыш. шанса крит. удара (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_043]
[uf 0 5 65278][uf 2 1]+Увеличение рассечения[n][uf 1 1][e]

[msg ItemAddEffectMSG_044]
[uf 0 5 65278][uf 2 1]+Увеличение дроб. удара[n][uf 1 1][e]

[msg ItemAddEffectMSG_045]
[uf 0 5 65278][uf 2 1]+Увеличение пронзания[n][uf 1 1][e]

[msg ItemAddEffectMSG_046]
[uf 0 5 65278][uf 2 1]+Увеличение огня[n][uf 1 1][e]

[msg ItemAddEffectMSG_047]
[uf 0 5 65278][uf 2 1]+Увеличение льда[n][uf 1 1][e]

[msg ItemAddEffectMSG_048]
[uf 0 5 65278][uf 2 1]+Увеличение молнии[n][uf 1 1][e]

[msg ItemAddEffectMSG_049]
[uf 0 5 65278][uf 2 1]+Увеличение ветра[n][uf 1 1][e]

[msg ItemAddEffectMSG_050]
[uf 0 5 65278][uf 2 1]+Увеличение света[n][uf 1 1][e]

[msg ItemAddEffectMSG_051]
[uf 0 5 65278][uf 2 1]+Увеличение тьмы[n][uf 1 1][e]

[msg ItemAddEffectMSG_052]
[uf 0 5 65278][uf 2 1]+Ответный удар[n][uf 1 1][e]

[msg ItemAddEffectMSG_053]
[uf 0 5 65278][uf 2 1]+Месть[n][uf 1 1][e]

[msg ItemAddEffectMSG_054]
[uf 0 5 65278][uf 2 1]+Вендетта[n][uf 1 1][e]

[msg ItemAddEffectMSG_055]
[uf 0 5 65278][uf 2 1]+Сопротивление заморозке[n][uf 1 1][e]

[msg ItemAddEffectMSG_056]
[uf 0 5 65278][uf 2 1]+Сопротивление электрошоку[n][uf 1 1][e]

[msg ItemAddEffectMSG_057]
[uf 0 5 65278][uf 2 1]+Сопротивление смятению[n][uf 1 1][e]

[msg ItemAddEffectMSG_058]
[uf 0 5 65278][uf 2 1]+Сопротивление страху[n][uf 1 1][e]

[msg ItemAddEffectMSG_059]
[uf 0 5 65278][uf 2 1]+Сопротивление панике[n][uf 1 1][e]

[msg ItemAddEffectMSG_060]
[uf 0 5 65278][uf 2 1]+Сопротивление очарованию[n][uf 1 1][e]

[msg ItemAddEffectMSG_061]
[uf 0 5 65278][uf 2 1]+Сопротивление ярости[n][uf 1 1][e]

[msg ItemAddEffectMSG_062]
[uf 0 5 65278][uf 2 1]+Сопротивление отравлению[n][uf 1 1][e]

[msg ItemAddEffectMSG_063]
[uf 0 5 65278][uf 2 1]+Сопротивление головокружению[n][uf 1 1][e]

[msg ItemAddEffectMSG_064]
[uf 0 5 65278][uf 2 1]+Блок заморозки[n][uf 1 1][e]

[msg ItemAddEffectMSG_065]
[uf 0 5 65278][uf 2 1]+Блок электрошока[n][uf 1 1][e]

[msg ItemAddEffectMSG_066]
[uf 0 5 65278][uf 2 1]+Блок смятения[n][uf 1 1][e]

[msg ItemAddEffectMSG_067]
[uf 0 5 65278][uf 2 1]+Блок страха[n][uf 1 1][e]

[msg ItemAddEffectMSG_068]
[uf 0 5 65278][uf 2 1]+Блок паники[n][uf 1 1][e]

[msg ItemAddEffectMSG_069]
[uf 0 5 65278][uf 2 1]+Блок очарования[n][uf 1 1][e]

[msg ItemAddEffectMSG_070]
[uf 0 5 65278][uf 2 1]+Блок ярости[n][uf 1 1][e]

[msg ItemAddEffectMSG_071]
[uf 0 5 65278][uf 2 1]+Блок отравления[n][uf 1 1][e]

[msg ItemAddEffectMSG_072]
[uf 0 5 65278][uf 2 1]+Блок головокружения[n][uf 1 1][e]

[msg ItemAddEffectMSG_073]
[uf 0 5 65278][uf 2 1]+Авто-Тарукайя[n][uf 1 1][e]

[msg ItemAddEffectMSG_074]
[uf 0 5 65278][uf 2 1]+Авто-Ракукайя[n][uf 1 1][e]

[msg ItemAddEffectMSG_075]
[uf 0 5 65278][uf 2 1]+Авто-Сукукайя[n][uf 1 1][e]

[msg ItemAddEffectMSG_076]
[uf 0 5 65278][uf 2 1]+Сниж. рубящ. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_077]
[uf 0 5 65278][uf 2 1]+Сниж. рубящ. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_078]
[uf 0 5 65278][uf 2 1]+Сниж. рубящ. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_079]
[uf 0 5 65278][uf 2 1]+Сниж. дробящ. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_080]
[uf 0 5 65278][uf 2 1]+Сниж. дробящ. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_081]
[uf 0 5 65278][uf 2 1]+Сниж. дробящ. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_082]
[uf 0 5 65278][uf 2 1]+Сниж. колющ. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_083]
[uf 0 5 65278][uf 2 1]+Сниж. колющ. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_084]
[uf 0 5 65278][uf 2 1]+Сниж. колющ. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_085]
[uf 0 5 65278][uf 2 1]+Сниж. физ. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_086]
[uf 0 5 65278][uf 2 1]+Сниж. физ. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_087]
[uf 0 5 65278][uf 2 1]+Сниж. физ. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_088]
[uf 0 5 65278][uf 2 1]+Сниж. огн. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_089]
[uf 0 5 65278][uf 2 1]+Сниж. огн. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_090]
[uf 0 5 65278][uf 2 1]+Сниж. огн. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_091]
[uf 0 5 65278][uf 2 1]+Сниж. лед. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_092]
[uf 0 5 65278][uf 2 1]+Сниж. лед. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_093]
[uf 0 5 65278][uf 2 1]+Сниж. лед. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_094]
[uf 0 5 65278][uf 2 1]+Сниж. молн. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_095]
[uf 0 5 65278][uf 2 1]+Сниж. молн. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_096]
[uf 0 5 65278][uf 2 1]+Сниж. молн. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_097]
[uf 0 5 65278][uf 2 1]+Сниж. ветр. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_098]
[uf 0 5 65278][uf 2 1]+Сниж. ветр. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_099]
[uf 0 5 65278][uf 2 1]+Сниж. ветр. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_100]
[uf 0 5 65278][uf 2 1]+Сниж. урона светом (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_101]
[uf 0 5 65278][uf 2 1]+Сниж. урона светом (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_102]
[uf 0 5 65278][uf 2 1]+Сниж. урона светом (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_103]
[uf 0 5 65278][uf 2 1]+Сниж. урона тьмой (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_104]
[uf 0 5 65278][uf 2 1]+Сниж. урона тьмой (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_105]
[uf 0 5 65278][uf 2 1]+Сниж. урона тьмой (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_106]
[uf 0 5 65278][uf 2 1]+Сниж маг. урона (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_107]
[uf 0 5 65278][uf 2 1]+Сниж маг. урона (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_108]
[uf 0 5 65278][uf 2 1]+Сниж маг. урона (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_109]
[uf 0 5 65278][uf 2 1]+Уклонение от рассечения (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_110]
[uf 0 5 65278][uf 2 1]+Уклонение от рассечения (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_111]
[uf 0 5 65278][uf 2 1]+Уклонение от рассечения (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_112]
[uf 0 5 65278][uf 2 1]+Уклонение от удара (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_113]
[uf 0 5 65278][uf 2 1]+Уклонение от удара (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_114]
[uf 0 5 65278][uf 2 1]+Уклонение от удара (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_115]
[uf 0 5 65278][uf 2 1]+Уклонение от пронзания (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_116]
[uf 0 5 65278][uf 2 1]+Уклонение от пронзания (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_117]
[uf 0 5 65278][uf 2 1]+Уклонение от пронзания (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_118]
[uf 0 5 65278][uf 2 1]+Физ. уклонение (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_119]
[uf 0 5 65278][uf 2 1]+Физ. уклонение (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_120]
[uf 0 5 65278][uf 2 1]+Физ. уклонение (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_121]
[uf 0 5 65278][uf 2 1]+Уклонение от огня (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_122]
[uf 0 5 65278][uf 2 1]+Уклонение от огня (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_123]
[uf 0 5 65278][uf 2 1]+Уклонение от огня (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_124]
[uf 0 5 65278][uf 2 1]+Уклонение от льда (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_125]
[uf 0 5 65278][uf 2 1]+Уклонение от льда (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_126]
[uf 0 5 65278][uf 2 1]+Уклонение от льда (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_127]
[uf 0 5 65278][uf 2 1]+Уклонение от молний (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_128]
[uf 0 5 65278][uf 2 1]+Уклонение от молний (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_129]
[uf 0 5 65278][uf 2 1]+Уклонение от молний (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_130]
[uf 0 5 65278][uf 2 1]+Уклонение от ветра (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_131]
[uf 0 5 65278][uf 2 1]+Уклонение от ветра (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_132]
[uf 0 5 65278][uf 2 1]+Уклонение от ветра (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_133]
[uf 0 5 65278][uf 2 1]+Уклонение от света (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_134]
[uf 0 5 65278][uf 2 1]+Уклонение от света (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_135]
[uf 0 5 65278][uf 2 1]+Уклонение от света (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_136]
[uf 0 5 65278][uf 2 1]+Уклонение от тьмы (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_137]
[uf 0 5 65278][uf 2 1]+Уклонение от тьмы (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_138]
[uf 0 5 65278][uf 2 1]+Уклонение от тьмы (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_139]
[uf 0 5 65278][uf 2 1]+Уклонение от магии (мал.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_140]
[uf 0 5 65278][uf 2 1]+Уклонение от магии (сред.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_141]
[uf 0 5 65278][uf 2 1]+Уклонение от магии (выс.)[n][uf 1 1][e]

[msg ItemAddEffectMSG_142]
[uf 0 5 65278][uf 2 1]+50% опыта[n][uf 1 1][e]

[msg ItemAddEffectMSG_143]
[uf 0 5 65278][uf 2 1]+15% опыта[n][uf 1 1][e]

[msg ItemAddEffectMSG_144]
[uf 0 5 65278][uf 2 1]+Повыш. рубящ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_145]
[uf 0 5 65278][uf 2 1]+Повыш. дробящ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_146]
[uf 0 5 65278][uf 2 1]+Повыш. колющ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_147]
[uf 0 5 65278][uf 2 1]+Повыш. огн. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_148]
[uf 0 5 65278][uf 2 1]+Повыш. лед. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_149]
[uf 0 5 65278][uf 2 1]+Повыш. молн. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_150]
[uf 0 5 65278][uf 2 1]+Повыш. ветр. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_151]
[uf 0 5 65278][uf 2 1]+Повыш. урона светом[n][uf 1 1][e]

[msg ItemAddEffectMSG_152]
[uf 0 5 65278][uf 2 1]+Повыш. урона тьмой[n][uf 1 1][e]

[msg ItemAddEffectMSG_153]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от рубящ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_154]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от дробящ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_155]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от колющ. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_156]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от огн. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_157]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от лед. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_158]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от молн. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_159]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от ветр. урона[n][uf 1 1][e]

[msg ItemAddEffectMSG_160]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от урона светом[n][uf 1 1][e]

[msg ItemAddEffectMSG_161]
[uf 0 5 65278][uf 2 1]+Повыш. защ. от урона тьмой[n][uf 1 1][e]

[msg ItemAddEffectMSG_162]
[uf 0 5 65278][uf 2 1]+Атака при ярости[n][uf 1 1][e]

[msg ItemAddEffectMSG_163]
[uf 0 5 65278][uf 2 1]+Восстановление 1[n][uf 1 1][e]

[msg ItemAddEffectMSG_164]
[uf 0 5 65278][uf 2 1]+Восстановление 2[n][uf 1 1][e]

[msg ItemAddEffectMSG_165]
[uf 0 5 65278][uf 2 1]+Восстановление 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_166]
[uf 0 5 65278][uf 2 1]+Воодушевление 1[n][uf 1 1][e]

[msg ItemAddEffectMSG_167]
[uf 0 5 65278][uf 2 1]+Воодушевление 2[n][uf 1 1][e]

[msg ItemAddEffectMSG_168]
[uf 0 5 65278][uf 2 1]+Воодушевление 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_169]
[uf 0 5 65278][uf 2 1]+Блок смерт. ударов светом[n][uf 1 1][e]

[msg ItemAddEffectMSG_170]
[uf 0 5 65278][uf 2 1]+Блок смерт. ударов тьмой[n][uf 1 1][e]

[msg ItemAddEffectMSG_171]
[uf 0 5 65278][uf 2 1]+Танец Али[n][uf 1 1][e]

[msg ItemAddEffectMSG_172]
[uf 0 5 65278][uf 2 1]+Блок всего, кроме всемогущ.[n][uf 1 1][e]

[msg ItemAddEffectMSG_173]
[uf 0 5 65278][uf 2 1]+Твердая стойка[n][uf 1 1][e]

[msg ItemAddEffectMSG_174]
[uf 0 5 65278][uf 2 1]+Цепь души[n][uf 1 1][e]

[msg ItemAddEffectMSG_175]
[uf 0 5 65278][uf 2 1]+Повыш. урона совместной атаки[n][uf 1 1][e]

[msg ItemAddEffectMSG_176]
[uf 0 5 65278][uf 2 1]ブランク[n][uf 1 1][e]

[msg ItemAddEffectMSG_177]
[uf 0 5 65278][uf 2 1]+Блок рассечения[n][uf 1 1][e]

[msg ItemAddEffectMSG_178]
[uf 0 5 65278][uf 2 1]+Блок дроб. удара[n][uf 1 1][e]

[msg ItemAddEffectMSG_179]
[uf 0 5 65278][uf 2 1]+Блок пронзания[n][uf 1 1][e]

[msg ItemAddEffectMSG_180]
[uf 0 5 65278][uf 2 1]+Блок огня[n][uf 1 1][e]

[msg ItemAddEffectMSG_181]
[uf 0 5 65278][uf 2 1]+Блок льда[n][uf 1 1][e]

[msg ItemAddEffectMSG_182]
[uf 0 5 65278][uf 2 1]+Блок молнии[n][uf 1 1][e]

[msg ItemAddEffectMSG_183]
[uf 0 5 65278][uf 2 1]+Блок ветра[n][uf 1 1][e]

[msg ItemAddEffectMSG_184]
[uf 0 5 65278][uf 2 1]+Блок света[n][uf 1 1][e]

[msg ItemAddEffectMSG_185]
[uf 0 5 65278][uf 2 1]+Блок тьмы[n][uf 1 1][e]

[msg ItemAddEffectMSG_186]
[uf 0 5 65278][uf 2 1]+Усиление рассечения[n][uf 1 1][e]

[msg ItemAddEffectMSG_187]
[uf 0 5 65278][uf 2 1]+Усиление ударов[n][uf 1 1][e]

[msg ItemAddEffectMSG_188]
[uf 0 5 65278][uf 2 1]+Усиление пронзания[n][uf 1 1][e]

[msg ItemAddEffectMSG_189]
[uf 0 5 65278][uf 2 1]+Усиление огня[n][uf 1 1][e]

[msg ItemAddEffectMSG_190]
[uf 0 5 65278][uf 2 1]+Усиление льда[n][uf 1 1][e]

[msg ItemAddEffectMSG_191]
[uf 0 5 65278][uf 2 1]+Усиление молнии[n][uf 1 1][e]

[msg ItemAddEffectMSG_192]
[uf 0 5 65278][uf 2 1]+Усиление ветра[n][uf 1 1][e]

[msg ItemAddEffectMSG_193]
[uf 0 5 65278][uf 2 1]+Усиление света[n][uf 1 1][e]

[msg ItemAddEffectMSG_194]
[uf 0 5 65278][uf 2 1]+Усиление тьмы[n][uf 1 1][e]

[msg ItemAddEffectMSG_195]
[uf 0 5 65278][uf 2 1]+Сопротивление нег. эфф.[n][uf 1 1][e]

[msg ItemAddEffectMSG_196]
[uf 0 5 65278][uf 2 1]+Непоколебимость[n][uf 1 1][e]

[msg ItemAddEffectMSG_197]
[uf 0 5 65278][uf 2 1]+Быстрое лечение[n][uf 1 1][e]

[msg ItemAddEffectMSG_198]
[uf 0 5 65278][uf 2 1]+Мгновенное лечение[n][uf 1 1][e]

[msg ItemAddEffectMSG_199]
[uf 0 5 65278][uf 2 1]+Подмога жизни[n][uf 1 1][e]

[msg ItemAddEffectMSG_200]
[uf 0 5 65278][uf 2 1]+Стойкость[n][uf 1 1][e]

[msg ItemAddEffectMSG_201]
[uf 0 5 65278][uf 2 1]+Стойкий дух[n][uf 1 1][e]

[msg ItemAddEffectMSG_202]
[uf 0 5 65278][uf 2 1]+Мастер-оружейник[n][uf 1 1][e]

[msg ItemAddEffectMSG_203]
[uf 0 5 65278][uf 2 1]+Мастер-заклинатель[n][uf 1 1][e]

[msg ItemAddEffectMSG_204]
[uf 0 5 65278][uf 2 1]+Адепт[n][uf 1 1][e]

[msg ItemAddEffectMSG_205]
[uf 0 5 65278][uf 2 1]+Приверженец[n][uf 1 1][e]

[msg ItemAddEffectMSG_206]
[uf 0 5 65278][uf 2 1]+Увеличение заморозки[n][uf 1 1][e]

[msg ItemAddEffectMSG_207]
[uf 0 5 65278][uf 2 1]+Увеличение электрошока[n][uf 1 1][e]

[msg ItemAddEffectMSG_208]
[uf 0 5 65278][uf 2 1]Увеличение смятения[n][uf 1 1][e]

[msg ItemAddEffectMSG_209]
[uf 0 5 65278][uf 2 1]+Увеличение страха[n][uf 1 1][e]

[msg ItemAddEffectMSG_210]
[uf 0 5 65278][uf 2 1]+Увеличение паники[n][uf 1 1][e]

[msg ItemAddEffectMSG_211]
[uf 0 5 65278][uf 2 1]+Увеличение очарования[n][uf 1 1][e]

[msg ItemAddEffectMSG_212]
[uf 0 5 65278][uf 2 1]+Увеличение ярости[n][uf 1 1][e]

[msg ItemAddEffectMSG_213]
[uf 0 5 65278][uf 2 1]+Увеличение отравления[n][uf 1 1][e]

[msg ItemAddEffectMSG_214]
[uf 0 5 65278][uf 2 1]+Выживание в свете[n][uf 1 1][e]

[msg ItemAddEffectMSG_215]
[uf 0 5 65278][uf 2 1]+Стойкость к свету[n][uf 1 1][e]

[msg ItemAddEffectMSG_216]
[uf 0 5 65278][uf 2 1]+Выживание во тьме[n][uf 1 1][e]

[msg ItemAddEffectMSG_217]
[uf 0 5 65278][uf 2 1]+Стойкость к тьме[n][uf 1 1][e]

[msg ItemAddEffectMSG_218]
[uf 0 5 65278][uf 2 1]+Секрет долголетия[n][uf 1 1][e]

[msg ItemAddEffectMSG_219]
[uf 0 5 65278][uf 2 1]+Авто-Матару[n][uf 1 1][e]

[msg ItemAddEffectMSG_220]
[uf 0 5 65278][uf 2 1]+Авто-Мараку[n][uf 1 1][e]

[msg ItemAddEffectMSG_221]
[uf 0 5 65278][uf 2 1]+Авто-Масуку[n][uf 1 1][e]

[msg ItemAddEffectMSG_222]
[uf 0 5 65278][uf 2 1]+Авто-Бунт[n][uf 1 1][e]

[msg ItemAddEffectMSG_223]
[uf 0 5 65278][uf 2 1]+Подавление огня[n][uf 1 1][e]

[msg ItemAddEffectMSG_224]
[uf 0 5 65278][uf 2 1]+Подавление льда[n][uf 1 1][e]

[msg ItemAddEffectMSG_225]
[uf 0 5 65278][uf 2 1]+Подавление молнии[n][uf 1 1][e]

[msg ItemAddEffectMSG_226]
[uf 0 5 65278][uf 2 1]+Подавление ветра[n][uf 1 1][e]

[msg ItemAddEffectMSG_227]
[uf 0 5 65278][uf 2 1]+Передача души[n][uf 1 1][e]

[msg ItemAddEffectMSG_228]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg ItemAddEffectMSG_229]
[uf 0 5 65278][uf 2 1]+Звено души[n][uf 1 1][e]

[msg ItemAddEffectMSG_230]
[uf 0 5 65278][uf 2 1]+Увеличение передачи хода[n][uf 1 1][e]

[msg ItemAddEffectMSG_231]
[uf 0 5 65278][uf 2 1]+Усиление передачи хода[n][uf 1 1][e]

[msg ItemAddEffectMSG_232]
[uf 0 5 65278][uf 2 1]+Урон по упавшему врагу[n][uf 1 1][e]

[msg ItemAddEffectMSG_233]
[uf 0 5 65278][uf 2 1]+Увеличение головокруж.[n][uf 1 1][e]

[msg ItemAddEffectMSG_234]
[uf 0 5 65278][uf 2 1]Игнор. сопротивлений врага[n][uf 1 1][e]

[msg ItemAddEffectMSG_235]
[uf 0 5 65278][uf 2 1]Длительность «Вакханалии» +1 ход[n][uf 1 1][e]

[msg ItemAddEffectMSG_236]
[uf 0 5 65278][uf 2 1]Ускор. восстановления при перегреве[n][uf 1 1][e]

[msg ItemAddEffectMSG_237_0_0]
[uf 0 5 65278][uf 2 1]Сила[n][uf 1 1][e]

[msg ItemAddEffectMSG_238_0_0]
[uf 0 5 65278][uf 2 1]Магия[n][uf 1 1][e]

[msg ItemAddEffectMSG_239_0_0]
[uf 0 5 65278][uf 2 1]Выносливость[n][uf 1 1][e]

[msg ItemAddEffectMSG_240_0_0]
[uf 0 5 65278][uf 2 1]Ловкость[n][uf 1 1][e]

[msg ItemAddEffectMSG_241_0_0]
[uf 0 5 65278][uf 2 1]Удача[n][uf 1 1][e]

[msg ItemAddEffectMSG_242_0_0]
[uf 0 5 65278][uf 2 1]Все показатели[n][uf 1 1][e]

[msg ItemAddEffectMSG_243_0_0]
[uf 0 5 65278][uf 2 1]+[n][uf 1 1][e]

[msg ItemAddEffectMSG_244_0_0]
[uf 0 5 65278][uf 2 1]-[n][uf 1 1][e]

[msg ItemAddEffectMSG_245_0_0]
[uf 0 5 65278][uf 2 1]/[n][uf 1 1][e]

[msg ItemAddEffectMSG_246_0_0]
[uf 0 5 65278][uf 2 1]Эффект[n][uf 1 1][e]

[msg ItemAddEffectMSG_247_0_0]
[uf 0 5 65278][uf 2 1]Используем.[n][uf 1 1][e]

[msg ItemAddEffectMSG_248_0_0]
[uf 0 5 65278][uf 2 1]+100 ОЗ и ОД[n][uf 1 1][e]

[msg ItemAddEffectMSG_249_0_0]
[uf 0 5 65278][uf 2 1]+Авто-Тарука-Бунт[n][uf 1 1][e]

[msg ItemAddEffectMSG_250_0_0]
[uf 0 5 65278][uf 2 1]+Авто-Заряд[n][uf 1 1][e]

[msg ItemAddEffectMSG_251_0_0]
[uf 0 5 65278][uf 2 1]+Авто-Концентрация[n][uf 1 1][e]

[msg ItemAddEffectMSG_252_0_0]
[uf 0 5 65278][uf 2 1]+Авто-Экзотермия[n][uf 1 1][e]

[msg ItemAddEffectMSG_253_0_0]
[uf 0 5 65278][uf 2 1]Восстановление 3/Воодушевление 3[n][uf 1 1][e]

[msg ItemAddEffectMSG_254_0_0]
[uf 0 5 65278][uf 2 1]+Способность к магии[n][uf 1 1][e]

[msg ItemAddEffectMSG_255_0_0]
[uf 0 5 65278][uf 2 1]+Блок всех негат. эффектов[n][uf 1 1][e]

