[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 201 65535 0 0][uf 3 1 1 0 0 1 0 0]How did it come to this?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Ikutsuki-san...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Father![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Father![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Father...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 6 0 0]My father once made a promise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 52 65535 0 0][uf 3 1 1 0 0 7 0 0]He swore he would atone for putting our generation in danger, even if it cost him his life.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 64 52 65535 0 0][uf 3 1 1 0 0 8 0 0]But I... I wanted him to live.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 64 52 65535 0 0][uf 3 1 1 0 0 9 0 0]I became a Persona-user so I could protect him.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 64 52 65535 0 0][uf 3 1 1 0 0 10 0 0]*sob*[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 201 65535 0 0][uf 3 1 0 0 0 11 0 0]......[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru slumped to the[n]floor, crying like a child...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Soon, the Dark Hour will end...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sanada picked up the stunned Mitsuru...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Everyone returned to[n]the dormitory in silence...[n][uf 1 1][e]

