[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I see Maya.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]i went to the gym yesterday to work out! =D[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...my muscles are sore, but i'm sooooo buff! ;)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]theres nothin a little endorphins wont cure, rite?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]orz (...sooooo much pain)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]actually, i only went cuz i was so pissed at that bastard! ＞=/[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Calm down.[e]
[uf 0 5 65278][uf 2 1]What bastard?[e]

[msg MSG_003_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]ur rite, i should just calm down -_- ::breathes::[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]nuuuuuuuuuuu! i just cant get it out of my mind!! x_x[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Maya seems upset.[n][uf 1 1][e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 15 1]...errr sry ^^;; have kind of a dirty mouth today ＞_＞[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Maya seems embarrassed.[n][uf 1 1][e]

[msg MSG_007_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]what i meant was... i was upset cuz of this guy...[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]remember that Mr. E guy? (the SOB, rite?)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i made a small error on some paperwork and now he's all on my ass[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]"ur s'posed to b teaching correct grammar" he told me!! ＞=/ stfu old man![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]he thinks he's all that just cuz he's a classic lit teacher ffs[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]doesnt he know who i am? im maya, u old bastard! t(^_^) xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]if Mr. E starts playin this game too im putting him on Ignore! xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]u can't talk to him either, k? hee hee... pwned![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Maya is confiding in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_010_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]Mr. E prolly doesnt have a computer @ his house ne way... ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]he prolly uses an abacus! talk about "classic"! xD roflcopter[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]phew... much better. maybe i'll go take a shower now ::blush::[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]dun worry! i won't let that old geezer get me down, tatsuya!! ^_^[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to log out as well.[n][uf 1 1][e]

