[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]This tantalizing fragrance... Can it be...!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Octopia Cook]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1001]Whoa, you can figure out our secret ingredient with just a whiff?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1001]I guess you got a funky sense of smell to go with your funky sense of style, lady.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1001]Well, there ain't a law sayin' takoyaki shops can't cook other stuff besides octopus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1001]So how 'bout it? Wanna buy some? I swear, my takoyaki's so good it'll make your jaw drop![n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Cuisine so scrumptious that one's jaw can drop off!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 202 0 25 25]...I imagine that would warrant urgent medical care, realistically speaking, but I would very much like a taste.[n][uf 1 1][e]

[msg MSG_003_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Unfortunately, this is all I have on me at the moment. I do hope this is sufficient.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]It's not that expensive...[e]
[uf 0 5 65278][uf 2 1]You're buying that many...?[e]

[msg MSG_005_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]No need to console me. My curiosity far exceeds any monetary—[n][uf 1 1][e]

[msg MSG_005_5_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, I see... Upon closer inspection, a single serving is only 400 yen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]

[msg MSG_005_7_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]W-Well then! Two orders of your finest takoyaki, please.[n][uf 1 1][e]

[msg MSG_006_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I have yet to see someone who has actually lost their jaw.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 202 1 25 25]That must mean that the ordinary citizen cannot easily afford these.[n][uf 1 1][e]

[msg MSG_006_5_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Oh...? Upon closer inspection, a single serving is only 400 yen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 0 0 0 17 0 0]......[n][uf 1 1][e]

[msg MSG_006_7_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]W-Well then! Two orders of your finest takoyaki, please.[n][uf 1 1][e]

[msg MSG_007_0_0 [Octopia Cook]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1001]Thanks! Here you go, and come again![n][uf 1 1][e]

[msg MSG_008_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]This distinct texture... The firm, chewy skin... There's no doubt about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 202 0 25 25]I must say, I'm surprised to see this used as a cooking ingredient.[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]See what...?[e]
[uf 0 5 65278][uf 2 1]How's your jaw?[e]

[msg MSG_010_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]The human mind... It is cursed to forever retain whatever knowledge it gains, whether good or ill.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Forgive my reticence, but some questions are better left unanswered.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 0 0 0 24 0 0][uf 4 23 0 202 0 25 25]......[n][uf 1 1][e]

[msg MSG_011_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]It has yet to even unhinge...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]But for the better, I suppose. There are many other delicacies I must try.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 202 1 25 25]It wouldn't do to lose my jaw before sampling each and every one of them.[n][uf 1 1][e]

[msg MSG_012_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]There appear to be several dining establishments around here... We must simply visit all of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]My first priority is to go to something called a "net café" where one may use something called a "soda fountain."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 202 1 25 25]This apparatus allows for an infinite combination of flavors by mixing various solutions...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Just thinking about it gives me a sort of electric tingle across my tongue.[n][uf 1 1][e]

[msg MSG_013_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Ahhh... I see.[n][uf 1 1][e]

[msg MSG_014_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]My, oh my...[n][uf 1 1][e]

[msg MSG_015_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 4 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Oh, how intriguing...[n][uf 1 1][e]

[msg MSG_016_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]We appear to have exhausted every dining option in this area.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 202 3 25 25]...Oh dear, is something the matter?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Now that I think about it, you haven't eaten much since our seventh meal...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 202 0 25 25]In any event, I must thank you for your delightful company. I shall certainly savor this experience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]If you don't mind, I'd very much appreciate it if you were to escort me again sometime.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I returned to the Velvet Room with Elizabeth.[n][uf 1 1][e]

