[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]09/25/2009 00:45:12[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like Mitsuru's room...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 1 0 0]Whew...[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 2 0 0]Oh... I've gotten used to walking around without my bathrobe lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 3 0 0]Not a very good habit to fall into...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 4 0 0]Well. I'm away from home, so it's no big deal, I suppose...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 5 0 0]This fashion magazine... I thought I'd take a look after I saw Takeba purchasing one...[n][uf 1 1][e]

[msg MSG_005_0_0 [Camera Footage]]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 7 0 0]"256 snazzy looks to knock the socks off of your BFFs!"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 8 0 0]"Get her look! Sweet but glam do's and don'ts"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 0 0 0 9 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 10 0 0]What is this even saying?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 11 0 0]I don't follow fashion myself... I usually wear whatever the family stylist selects for me.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 12 0 0]"The cutest essentials"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 13 0 0]W-Well... I would be open to trying this pink one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 15 0 0]Heh... Not that it would suit me anyway. I'm no Takeba.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 16 0 0]I should remember there's a difference between what appeals to me and what I can actually pull off.[n][uf 1 1][e]

[msg MSG_008_0_0 [Camera Footage]]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 22 0 0]...Achoo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 23 0 0]Not good... I'm going to catch a cold.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 11 0 0][uf 3 1 1 0 0 24 0 0]I should turn in... I have to be up early again tomorrow.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]Now, which pajamas shall I wear tonight?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

