[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0][uf 4 25 5]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 4 23 0 5 1 25 25]The food here is delicious.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]Um, I want to ask you something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 23 0 5 0 25 25]A-And I'd like you to answer honestly...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4076 0 0]Are you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]...interested in anyone?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Yes.[e]
[uf 0 5 65278][uf 2 1]Nope.[e]
[uf 0 5 65278][uf 2 1]Why do you ask?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 3 0 65535 4093 0 0]I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]But I—[n][uf 1 1][e]

[msg MSG_004_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]O-Oh, never mind... Please forget I said anything.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems a little sad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4093 0 0][uf 5 13 4 15 5]Oh, I see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 23 0 5 0 25 25]So, I have a chance...[n][uf 1 1][e]

[msg MSG_006_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0]O-Oh, never mind... Please forget I said anything.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru is mumbling to herself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4098 0 0][uf 4 25 5][uf 5 13 4 30 5]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 4 23 0 5 3 25 25]Um, I mean, you know... I just—[n][uf 1 1][e]

[msg MSG_008_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]Wh-What's with the smile!?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru looks flustered.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 3 0 65535 4121 0 0]I've lost my appetite...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]I really wanted to try asking for a "second helping" while we're here, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 23 0 5 0 25 25]I'm a little overwhelmed right now, so you should ask for seconds in my stead.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I ate until my stomach felt like it'd explode[n]before heading back to the dorm.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4124 0 0]So this is one of Wakatsu's meals. I can see why it's so popular.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 23 0 5 0 25 25]Mmm... The smell of freshly fried food only makes it look even more delicious.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Um, could I ask you something?[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4059 0 0]Why did they give us this lemon on the side? I don't suppose it's dessert...[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Squeeze it over your food.[e]
[uf 0 5 65278][uf 2 1]You don't have to use it.[e]
[uf 0 5 65278][uf 2 1]It's dessert.[e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4071 0 0][uf 4 25 5][uf 5 13 4 30 5]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]I see... The acidity of the lemon juice provides a nice contrast to the fried food, enhancing the flavor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]How sensible! Everything you need is provided on this one plate![n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems to be having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4048 0 0]Really now?[n][uf 1 1][e]

[msg MSG_018_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Then why include it? Is it for dessert, after all?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Oh well, I suppose it doesn't matter. Let's just eat.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru is talking to herself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4099 0 0][uf 5 13 4 15 5]...R-Really!?[n][uf 1 1][e]

[msg MSG_020_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]So I was right? But I imagine it'd be far too sour...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]No, wait... Eating fried food may lead to heartburn, so perhaps this lemon is meant for cleansing your palate after a meal...?[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru's eyes are sparkling[n]with excitement...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]I also wanted to try asking for a "second helping" while we're here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Can you show me how it's done by ordering seconds for yourself?[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]I ate until I was stuffed and[n]returned to the dorm.[n][uf 1 1][e]

