[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I'm going to spend my time studying.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel smarter after working on some[n]difficult problems without giving up...![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's getting dark out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I think I've studied enough for now.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I'm feeling pretty drowsy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I think I've studied enough for today.[n][uf 1 1][e]

