[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Koromaru is eagerly watching all[n]the people pass by again today.[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]Arf!?[n][uf 1 1][e]

[msg MSG_002_0_0 [Girl in a Floral Shirt]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]H-Help![n][uf 1 1][e]

[msg MSG_003_0_0 [Girl in a Floral Shirt]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]*pant* *pant*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1]Um, earlier— *cough cough*[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]What happened?[e]
[uf 0 5 65278][uf 2 1]Take a deep breath.[e]

[msg MSG_005_0_0 [Girl in a Floral Shirt]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1]We're in trouble! It's my friend![n][uf 1 1][e]

[msg MSG_006_0_0 [Girl in a Floral Shirt]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1]He accidentally stepped on a doggy's tail![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]And now he won't stop chasing him! I think the doggy's real mad![n][uf 1 1][e]

[msg MSG_007_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Ruff![n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]We better hurry.[e]
[uf 0 5 65278][uf 2 1]Where are they?[e]

[msg MSG_009_0_0 [Girl in a Floral Shirt]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1]Th-This way![n][uf 1 1][e]

