[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Thanks for being so patient. That just about concludes your checkup.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Sorry yours ended up taking so much longer than everyone else's.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's about time.[e]
[uf 0 5 65278][uf 2 1]That's all right.[e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm sorry, really.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]If I'd known how long it would take, I would've scheduled an entire day for it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I'm glad to hear you say that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Although, we could have done it another time and taken a full day for it.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Your Persona abilities are rather unusual compared to the others', aren't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]That's why we had to run so many more tests on you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Well, based on how you've performed so far, I don't expect there to be any problems...[n][uf 1 1][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Persona abilities can be dangerous, depending on how they're used.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]With that in mind, it can't hurt to err on the side of caution.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]How are you feeling about it? Do you have any concerns about your power?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]None at all.[e]
[uf 0 5 65278][uf 2 1]You could say that.[e]

[msg MSG_007_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Good to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]And I don't think there will be any issues with your test results either.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]That's understandable, but I don't think there will be any issues with your test results.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]And based on what I'm hearing from Kirijo-kun's reports, you've been performing just fine.[n][uf 1 1][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I truly am grateful for everything the team has done.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Especially you.[n][uf 1 1][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Things have really changed for the better since you arrived.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Our team has grown, and we've even figured out how we can eliminate the Dark Hour.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]In a way, you've sort of gotten the clock ticking for us again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]It's almost as if... we were just waiting for you these past ten years.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I'm afraid I can only support you from behind the scenes, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I'll be counting on you to eliminate the four remaining Shadows.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Now then, it's getting pretty late. Why don't we get you back to the dor—[n][uf 1 1][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Oops, excuse me for a second...[n][uf 1 1][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Hello?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Oh! Thanks for your help the other day. Uh-huh... Yes... It's missing from that document?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]It's urgent...? Wai— B-By today!?[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Looks like he received an urgent call...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head back to the dorm alone.[n][uf 1 1][e]

