[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11267 0 0]Eating Japanese sweets makes me feel connected to my home country... I might be exaggerating.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Well, I decided that I'm going to study overseas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]So that means I won't be seeing you anymore...[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]O-Oh, sorry, that may have sounded weird. It's just...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]I'm an only child, and I've always wondered what it'd be like to have a sibling...[n][uf 1 1][e]

[msg MSG_002_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11263 0 0]So... I was wondering... what it'd be like if you called me something in that vein...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]How about "Kid Brother"?[e]
[uf 0 5 65278][uf 2 1]What about "Senpai"?[e]
[uf 0 5 65278][uf 2 1]Okay, Brother.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11270 0 0]"Kid"? B-But, I'm older than you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Well, I guess I'm not very reliable, so I can see why you would think of me like that...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems depressed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11250 0 0][uf 5 13 11 15 108]W-Well, I am your senpai, but... Hm, maybe I didn't convey that right...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I guess I should be more direct about what I want to say. At least I learned that now, before I leave...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga is nodding to himself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11282 0 0][uf 5 13 11 30 108]"Brother"... Oh, I love how that sounds...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Hey, um... C-Can you say it again?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga seems very happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11251 0 0]Oh, I always get carried away when I talk to you... But I need to buy more things before I go abroad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I should probably bring some products from here that I'm used to, at least for the beginning.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After shopping with Hiraga,[n]I returned to the dorm.[n][uf 1 1][e]

