[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Aigis looks serious...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I spent time reading with Aigis...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 22 1 7]I knew it. Conducting raids against our enemies is a highly efficient tactical strategy.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]It's almost bedtime. We should return to our rooms.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Aigis looks serious...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I spent time reading with Aigis...[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 22 1 7]It's amazing how combat-effective these raids are.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I feel like my [uf 4 30 1 1 1 0] has[n]increased after reading about the[n]main character's righteous spirit...[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 7 1 25 25]Ah, it's almost time to go to sleep. We should head back to our rooms.[n][uf 1 1][e]

