[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I can't get up...[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 1 0 0]I thought I was prepared for this, but... It still feels awful...[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 1 0 0 2 0 0]It does...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 1 0 0 3 0 0]But we can't stop here. We have to keep fighting for what we believe.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Yeah.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0][uf 3 1 1 0 0 5 0 0]He gave his life for this world... I won't let anyone dishonor that![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Fix the past or accept the present...[n]Which path should I have chosen?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Or... Was there another possibility...?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Regardless, I can't make[n]that choice anymore...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]My consciousness is fading...[n][uf 1 1][e]

