[msg TRL_000_0_0 [Rewinding to a Previous Point]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you save your game, it also saves [uf 0 1 2]a little bit of your past[uf 0 1 27]. You can go back to that time by opening the menu with [uf 1 3 112], going to SYSTEM, and selecting REWIND.[n][uf 1 1][e]

[msg TRL_001_0_0 [Rewinding to a Previous Point]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you select a REWIND slot, you will be returned to a point where you could roam freely shortly before you saved your game.[n][uf 1 1][e]

[msg TRL_002_0_0 [Rewinding to a Previous Point]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Note that the REWIND function [uf 0 1 2]does not save your new starting point automatically[uf 0 1 27]. If you use this function, make sure you continue to save your game as necessary.[n][uf 1 1][e]

