[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Are there more of them?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Don't worry, it's over.[n][uf 1 1][e]

[msg MSG_002_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Fuuka... You...[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Are you okay?[n][uf 1 1][e]

[msg MSG_004_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Yeah...[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Thank goodness...[n][uf 1 1][e]

[msg MSG_006_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 8 1 65535 0 0][uf 3 1 1 0 0 7 0 0]Fuuka!?[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 8 0 0]It's all right. She's just exhausted.[n][uf 1 1][e]

[msg MSG_008_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Fuuka...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 223 10 25 25]Fuuka, I...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Where did those two Shadows come from?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]Somewhere outside of Tartarus, just like with the dorm and the monorail.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Outside, huh...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Um, what are we gonna do about Moriyama-san? She knows about the Dark Hour and the Shadows.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 15 0 0]It doesn't matter. She's not like us, so she won't remember anything that happens in the Dark Hour.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 16 0 0]The good news is she didn't fall victim to the Shadows, despite hearing their call.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 17 0 0]So I don't think she'll get drawn in again. She's safe now.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 18 0 0]But doesn't that mean she'll forget Yamagishi-san saved her life?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 19 0 0]That doesn't seem right...[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 20 0 0]Actually, I get the feeling that things will work out.[n][uf 1 1][e]

[msg MSG_016_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 21 0 0]I'm sorry, Fuuka. I'm so sorry...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 22 0 0]It looks like she's learned her lesson.[n][uf 1 1][e]

[msg MSG_018_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 23 0 0]I'm sorry...[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]It wasn't easy, but we managed[n]to rescue Fuuka Yamagishi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]That mysterious boy appeared again...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]His warnings don't seem to be just dreams.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I can't make any sense of it right now.[n]I feel way too exhausted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get some rest as soon[n]as I get back to the dorm...[n][uf 1 1][e]

