[msg TRL_000_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 22]Sometimes [uf 0 1 2]a Monad door[uf 0 1 27] will appear in Tartarus. Defeating the special enemy inside will trigger a special Shuffle Time, where [uf 0 1 2]Major Arcana cards appear more frequently[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 23]Defeating the special enemy will also reveal [uf 0 1 2]the layout of the current floor and the floor directly above it[uf 0 1 27] once you exit through the door.[n][uf 1 1][e]

[msg TRL_002_0_0 [Monad Doors]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The Monad door is an unstable contraption. When one appears on a floor, the door will lose power and become inaccessible if you move to another floor, even if you return using a teleporter on the same day.[n][uf 1 1][e]

