[msg TRL_000_0_0 [Saving in Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]While exploring Tartarus, you can save at [uf 0 1 2]locations where you can change your party[uf 0 1 27]. However, you cannot save on the floor you're currently exploring.[n][uf 1 1][e]

[msg TRL_001_0_0 [Saving in Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can save from the menu or by pressing [uf 1 3 108].[n][uf 1 1][e]

