[msg TRL_000_0_0 [Teleporters]]
[uf 0 5 65278][uf 2 1][uf 4 8 13]Not all teleporters are one-way. You will sometimes encounter another type of [uf 0 1 2]teleporter[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Teleporters]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]This teleporter works like an elevator. It allows you to [uf 0 1 2]travel between floors[uf 0 1 27] with teleporters or return to the entrance. Use them to explore Tartarus more efficiently.[n][uf 1 1][e]

