[msg TRL_000_0_0 [Greedy Shadows]]
[uf 0 5 65278][uf 2 1][uf 4 8 40]You may encounter [uf 0 1 2]Greedy Shadows[uf 0 1 27] while exploring. These Shadows amass items by looting treasure chests, so expect [uf 0 1 2]greater rewards[uf 0 1 27] for defeating them than rare Shadows.[n][uf 1 1][e]

[msg TRL_001_0_0 [Greedy Shadows]]
[uf 0 5 65278][uf 2 1][uf 4 8 40]Greedy Shadows are always scampering helter-skelter, so catching them is [uf 0 1 2]a matter of luck[uf 0 1 27]. If you lose sight of one at a juncture, [uf 0 1 2]track them to the best of your ability[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Greedy Shadows]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Even if one slips away, they will sometimes [uf 0 1 2]drop items[uf 0 1 27]. The more correct guesses you make on [uf 0 1 2]which way they go at junctures[uf 0 1 27], the more items they'll drop.[n][uf 1 1][e]

