[msg TRL_000_0_0 [Fuuka's Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Fuuka's skills support the party not only during combat, but also during exploration.[n][uf 1 1][e]

[msg TRL_001_0_0 [Fuuka's Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]She learns unique utility skills such as [uf 0 1 35]Jamming[uf 0 1 27], which renders you undetectable to foes.[n][uf 1 1][e]

[msg TRL_002_0_0 [Fuuka's Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 26]Press [uf 1 3 109] during exploration to activate Fuuka's abilities. Like your other teammates' skills, this costs SP, so use items to recover if you're running low.[n][uf 1 1][e]

