[msg TRL_000_0_0 [Status Ailment: Rage]]
[uf 0 5 65278][uf 2 1][uf 4 8 35]The [uf 0 1 2]Rage[uf 0 1 27] ailment causes one to lose their sense of reason. Enraged enemies will aggressively target you, [uf 0 1 2]even from a distance[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Status Ailment: Rage]]
[uf 0 5 65278][uf 2 1][uf 4 8 35]They will [uf 0 1 2]charge upon spotting you[uf 0 1 27], but [uf 0 1 2]struggle to redirect the force of their trajectory[uf 0 1 27], so keep your calm, sidestep, and wait for your opening to attack.[n][uf 1 1][e]

