[msg TRL_000_0_0 [Ambush]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You can now [uf 0 1 2]Ambush[uf 0 1 27] enemies while exploring. When Ambushing an enemy, you'll trigger Chance Encounters [uf 0 1 2]regardless of the direction an enemy is facing[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Ambush]]
[uf 0 5 65278][uf 2 1][uf 4 8 33]Press and hold [uf 1 3 118] to dash for a set distance to enter the [uf 0 1 2]assault state[uf 0 1 27]. By pressing [uf 1 3 111] while in this state, you will [uf 0 1 2]Ambush[uf 0 1 27] the enemy.[n][uf 1 1][e]

[msg TRL_002_0_0 [Ambush]]
[uf 0 5 65278][uf 2 1][uf 4 8 34]Triggering an encounter from behind will slightly [uf 0 1 2]increase [uf 4 2]'s Theurgy gauge[uf 0 1 27] and may [uf 0 1 2]Distress[uf 0 1 27] the enemy at the beginning of battle.[n][uf 1 1][e]

