[msg TRL_000_0_0 [Entrance to the Great Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 42]If you've used a [uf 4 4 0 37 1 16667] in Tartarus, an entrance to a special dimension with a [uf 0 1 2]Great Clock[uf 0 1 27] may appear.[n][uf 1 1][e]

[msg TRL_001_0_0 [Entrance to the Great Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The Great Clock grants a large experience boost to a teammate of your choosing. Although you can only choose allies at a lower level than [uf 4 2], the greater the level difference, the bigger the bonus.[n][uf 1 1][e]

[msg TRL_000_5_0 [Entrance to the Great Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Remember, the entrance will only appear after you've used a [uf 0 1 39]Twilight Fragment[uf 0 1 27], so don't be shy about using them.[n][uf 1 1][e]

[msg TRL_002_0_0 [Entrance to the Great Clock]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]However, entrances to the Great Clock will [uf 0 1 2]vanish[uf 0 1 27] if you move to another floor, so be sure to use them when they appear.[n][uf 1 1][e]

