[msg TRL_000_0_0 [Monad Passage]]
[uf 0 5 65278][uf 2 1][uf 4 8 24]The Monad Passage is a type of Monad door leading to [uf 0 1 2]the depths of Tartarus[uf 0 1 27]. There is [uf 0 1 2]one per section of a block[uf 0 1 27]. Each Monad Passage opens in response to a [uf 0 1 2]Major Arcana card[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Monad Passage]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]A [uf 0 1 2]Formidable Shadow[uf 0 1 27] resides in the innermost area, and beyond it lies a treasure chest holding a [uf 0 1 2]valuable item[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_002_0_0 [Monad Passage]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The entrance to the Monad Passage will remain permanently on the same floor in the same location, [uf 0 1 2]even after the turn of a new day[uf 0 1 27]. If you feel outmatched, consider revisiting after training some.[n][uf 1 1][e]

