[msg TRL_000_0_0 [Returning from Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]After returning from Tartarus, [uf 0 1 2]the Dark Hour will end[uf 0 1 27]. This will start the next day. Use this time wisely to recuperate for your next expedition.[n][uf 1 1][e]

[msg TRL_001_0_0 [Returning from Tartarus]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]The structure of Tartarus will have changed[uf 0 1 27] by your next expedition. [uf 0 1 2]Treasure chests you have already found can be rediscovered[uf 0 1 27] as well, so returning could be a good idea if you find yourself stuck.[n][uf 1 1][e]

