[msg TRL_000_0_0 [Scouting]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]After combat, you may have the opportunity to [uf 0 1 2]scout[uf 0 1 27]. If you decide to scout the area, one of your teammates will temporarily leave your party to look for a path to the next floor.[n][uf 1 1][e]

[msg TRL_001_0_0 [Scouting]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]The ally scouting ahead will also collect items and hand over anything they've collected upon rejoining the party on the next floor. Note that you will be down a party member if you choose to scout.[n][uf 1 1][e]

