[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1][uf 1 5 0][uf 1 1][e]

[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Officer Kurosawa[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Something for you.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]I've got something for you today. Consider it restitution for you and the others for working diligently every day.[n]-Kurosawa[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Come by the station.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I have something for you. Come by whenever it's convenient for you.[n]-Kurosawa[n][uf 1 1][e]

