[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]☆Maiko☆[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Let's play! [uf 1 3 145][n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]I'm at the shrine[n][uf 1 5 0]Let's play together![n][uf 1 5 0][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Hello! [uf 1 3 145][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I'm hereee! Let's play at the shrine![n][uf 1 5 0][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 6 0][uf 1 5 0][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 138][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]How are you? I'm doing okay [uf 1 3 145][n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 138][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]I want to see you[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Promise[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Did you tell anyone that I'm running away from home? [uf 1 3 156][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Take care [uf 1 3 137][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]I want to see you one last time[n][uf 1 5 0]Come to the shrine [uf 1 3 137][n][uf 1 5 0]I'm leaving my phone behind so I won't pick up[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Let's play[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]I'm not running away from home[n][uf 1 5 0]So let's play at the shrine[n][uf 1 5 0][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]It's Maiko[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]Can you play today?[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 145]Hello[uf 1 3 145][n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]I want to play with you[n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137]a loooooot[n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137]I want to talk to you too[n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Hiii[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Are we playing today?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Are you busy?[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]I can play today[n][uf 1 5 0]Come to the shrine [uf 1 3 137][uf 1 3 137][n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]What are we playing today?[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]I want to play a lot today![n][uf 1 5 0]And eat takoyaki too!!![n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Sunday [uf 1 3 140][n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]Do you think Stripey will be at the shrine today?[n][uf 1 5 0]I can't go because I have school so please play with him[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Hello[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]Are you coming today?[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]I really want to see you[n][uf 1 1][e]

