[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Kenji Tomochika[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]you free today?[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]finally!!! class is over![n][uf 1 5 0]you wanna hang out after school?[n][uf 1 5 0]i'm gonna stick around for a bit, so just swing by my desk if you're down [uf 1 3 137][n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]i'm sooo boreddd[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]you got any plans after this? if you're free, let's hang.[n][uf 1 5 0]i'll be at my seat, as usual [uf 1 3 137][n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]HELP!!![n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]sorry dude, but you're the only one I can count on... don't ask why, just come, ok!?[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]wassup?[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]let's hang out after school [uf 1 3 135][uf 1 3 135][n]there's something i wanna talk to you about!!![n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]let's go grab some...[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]RAMEN! RAMEN! RAMEN![n][uf 1 5 0]RAMEN! RAMEN! RAMEN![n][uf 1 5 0]bet you're cravin' some RAMEN now! whaddaya say? [uf 1 3 137][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]you busy today?[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]just when i finally made up my mind to work hard for a brighter future, something's gotta drag me down [uf 1 3 138][n]will you hear me out?[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]what do I do?[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]sorry, i know it's short notice, but i'm in a real pinch [uf 1 3 138][uf 1 3 138][uf 1 3 138][n]you're the only one i've got...[n][uf 1 5 0]can we talk?[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]this is it[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]i've made up my mind. i wanna explain everything to you, from beginning to end.[n][uf 1 5 0]can we meet up?[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]Hey, cutie~ [uf 1 3 132][n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san, are you free today?[n][uf 1 5 0]Let's go on a date [uf 1 3 132][n]I wanna eat ramen together~[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]'sup?[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]let's hang after school if you're free [uf 1 3 137][n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]yo![n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]you busy? gimme a shout if you wanna hang. i'll be in the classroom[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]hey[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]you're free, right? let's hang out [uf 1 3 136][n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]hey, you free?[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]since we've got the day off, hit me up if you wanna go somewhere. i'll be free 'til the afternoon [uf 1 3 137][n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]let's watch a movie![n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]they're showing a flick i really wanna catch [uf 1 3 151][n]it'll light a fire in your heart, man![n][uf 1 5 0]i already got tickets, so lemme know if you wanna come by noon![n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1]this florist sells weird stuff![n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]you know the flower shop at port island station?[n][uf 1 5 0]the lady working there is kinda cute, but the flowers are so friggin' expensive [uf 1 3 155] i can only afford a few seedlings![n][uf 1 5 0]anyways, that's all i wanted to complain about [uf 1 3 138][n][uf 1 1][e]

