[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Shinjiro Aragaki[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]It's Aragaki.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I got your number from Kirijo.[n][uf 1 5 0]If you're free, come by the back alley again.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Can we talk?[n][uf 1 5 0]Come to the back alley.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Did you give my leave of absence form to Kirijo?[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]You free?[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]Wanna meet up if you are? Don't worry, I won't bite.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Come see me if you have a sec.[n][uf 1 1][e]

