[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Rafflesia[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]New Products In Stock[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]We have Buff Potato Sprouts in stock! Please come take some cute seedlings home with you. [uf 1 3 132][uf 1 3 132][n]=========================[n]Color your heart and lifestyle.[n]~Rafflesia Flower Shop~[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]New Products In Stock[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]We have Amronion Sprouts in stock! Please come take some cute seedlings home with you. [uf 1 3 132][uf 1 3 132][n]=========================[n]Color your heart and lifestyle.[n]~Rafflesia Flower Shop~[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]New Products In Stock[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]We have Soul Spinach Sprouts in stock! Please come take some cute seedlings home with you. [uf 1 3 132][uf 1 3 132][n]=========================[n]Color your heart and lifestyle.[n]~Rafflesia Flower Shop~[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]New Products In Stock[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]We have Golden Tomato Sprouts in stock! Please come take some cute seedlings home with you. [uf 1 3 132][uf 1 3 132][n]=========================[n]Color your heart and lifestyle.[n]~Rafflesia Flower Shop~[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]New Products In Stock[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]We have Simple Herb Sprouts in stock! Please come take some cute seedlings home with you. [uf 1 3 132][uf 1 3 132][n]=========================[n]Color your heart and lifestyle.[n]~Rafflesia Flower Shop~[n][uf 1 1][e]

