[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Junpei Iori[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]yo![n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]y'know, the two of us have never really hung out before [uf 1 3 138][n]seems like a good time for a breather, so how 'bout we go have some fun?[n][uf 1 5 0]i'll stick around in the classroom, so just lemme know if you're down [uf 1 3 137][n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]some summertime fun! [uf 1 3 140][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]if you spend your vacation doing nothing, summer will be over before you know it! [uf 1 3 138][n]listen man, you gotta help me with my crazy genius idea [uf 1 3 135][n]so hurry and haul your ass to the strip mall! [uf 1 3 140][n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]how you doing?[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]a lot's been happening all at once, so i was wondering how you've been holding up.[n][uf 1 5 0]wanna grab a bite for a change of pace?[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]hey, you free today?[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]'sup?[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]you good, man? [uf 1 3 137][n]come hang with me after school [uf 1 3 136][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]summer! [uf 1 3 140][uf 1 3 140][uf 1 3 140][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]dude, it's so freakin' hot outside, i'm melting.[n][uf 1 5 0]wanna go cool off at the movie theater? let's watch a cool hero flick and chill.[n][uf 1 5 0]i heard there's only one screening right now, so hit me up if you're down[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]heyyy [uf 1 3 138][n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]dude, are you even checking your messages?[n][uf 1 5 0]you're killing me man, why you gotta leave me hanging? [uf 1 3 133][n]let's hang out soon [uf 1 3 136][n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]hellooo [uf 1 3 138][uf 1 3 138][uf 1 3 138][n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]you get my last message?[n][uf 1 5 0]all my genius summer plan needs is you, dude![n][uf 1 5 0]i'll be at the strip mall, so hurry on over after you see this [uf 1 3 140][n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]let's hit up the hot spring![n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]we're going! no ifs ands or buts about it! i mean, we just gotta![n][uf 1 5 0]come find me when you're free[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]wanna grab some grub?[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]let's catch a meal together sometime. we can go whenever you have time[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]hey[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]sorry for sounding like a broken record, but i gotta talk to you about something. so... please just hear me out[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]'suuup [uf 1 3 140][n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]hey, lemme know if you got time today [uf 1 3 136][n][uf 1 1][e]

