[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Kazushi Miyamoto[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]IT'S MIYAMOTO!!![n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]You're heading to practice, right!?!?!?[n][uf 1 5 0]I'll be in the classroom, so holler at me!!![n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]RE: IT'S MIYAMOTO!!![n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Let's head to practice!!![n][uf 1 5 0]I'll show you what I'm made of today for sure!!![n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]RE: RE: IT'S MIYAMOTO!!![n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Time for practice! Don't be skippin' on me now!!![n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]RE: RE: RE: IT'S MIYAMOTO![n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Are you heading to practice today? You are, right!?[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]RE: RE: RE: RE: IT'S MIYAMO[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]You ready!? Let's go to practice![n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]RE: RE: RE: RE: RE: IT'S MIYA[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]You ready!? Let's go to practice![n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]RE: RE: RE: RE: RE: RE: IT'S M[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]ARE YOU READY!?!?!? LET'S RACE TO PRACTICE!!![n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]I'm gonna win!!![n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]I'm gonna give it 110% today!!![n][uf 1 5 0]Let's sprint to practice!!![n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]RE: I'm gonna win!!![n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]Let's head to practice!!! Today's the day I finally beat you!!![n][uf 1 5 0]Well. In my head!!![n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]TRACK PRACTICE!!![n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]You're coming today, right!? You better!!![n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]LET'S RUN!!![n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]C'mon, let's go!!! You best pick up the pace!!![n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]PRACTICE!!![n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]THAT'S TODAY!!! LET'S GOOO!!![n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]A little refresher!!![n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]What are you up to today? If you're free, let's go somewhere![n][uf 1 5 0]Let me know if you can make it before the afternoon![n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]MOVIE!!![n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]Are you free today?[n][uf 1 5 0]Let's go watch a movie! I heard this flick is really burning with passion, so it's bound to get us fired up![n][uf 1 5 0]I got some tickets from a friend, so let me know if you can make it by the afternoon![n][uf 1 1][e]

