[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Ken Amada[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]I have a favor to ask[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Hello, [uf 4 1]-san.[n][uf 1 5 0]I'd like to ask you a favor. Are you available tonight? I'll be waiting in front of the dorm.[n][uf 1 5 0]I know this is a difficult period, so thank you for your time.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Sorry for the short notice[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Can we meet today? I'll explain everything when you come.[n][uf 1 5 0]I'll be waiting on the fourth floor of the dorm. See you then.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]I challenge you again[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]I've been training even harder since last time. This time, I'm not going to lose, so let's go again.[n][uf 1 5 0]I'll be on the fourth floor of the dorm.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]No more summer vacation[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]We'll be starting school again tomorrow, but in the end, I didn't do much over summer vacation. I wish I could do something fun today...[n][uf 4 1]-san, do you have any ideas?[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Good evening[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Are you free tonight? I really need your help with something.[n][uf 1 5 0]I'll be waiting in front of the dorm.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]How curious[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san, you're close with Koromaru, right? I wonder what he's doing outside the dorm entrance. Please ask him the next time you see him.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]I know you're a busy person, but do you have some time to spare?[n][uf 1 5 0]I'll be waiting on the fourth floor of the dorm.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Hello[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]I just need a bit of your time.[n][uf 1 5 0]I want to ask you another favor. You're the only person I can count on.[n][uf 1 5 0]I'll be waiting on the fourth floor of the dorm.[n][uf 1 1][e]

