[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Bunkichi Kitamura[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Greetings[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1][uf 4 2]-chan, how do you do?[n][uf 1 5 0]Come swing by the store some time to say hello, okay?[n][uf 1 5 0]Best regards.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Who is this?[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I have this number saved on my phone, but I can't seem to recall who you are.[n][uf 1 5 0]I bet I'll remember right away once I see your face, so drop by the store.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]this is mitsuko[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]from the bookstore[n]texting is hard are you[n]getting this im waiting at[n]the shop for[n]you[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 140][uf 1 3 141][uf 1 3 142][uf 1 3 143][uf 1 3 144][uf 1 3 145][uf 1 3 146][uf 1 3 149][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]A [uf 1 3 154] for [uf 4 2]-chan![n][uf 1 5 0]I tried to use emojis [uf 1 3 155][uf 1 3 155] Isn't that rad? Totally gnarly.[n][uf 1 5 0]I'll teach you how to use them, too, so come by the shop. [uf 1 3 157][uf 1 3 158][n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]From Bunkichi[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]I miss your cute little face, [uf 4 2]-chan [uf 1 3 138][n]This old man doesn't have much longer to live, so come visit me soon, okay?[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]This is Mitsuko[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]I learned how to do[n]capital letters Are you getting these Anyway[n]come visit us at[n]the shop[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Bunkichi [uf 1 3 132] you[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]How do you do, [uf 4 2]-chan?[n][uf 1 5 0]When I send you a [uf 1 3 153] like this, it reminds me of the time I used to write love letters to Mitsuko-chan. [uf 1 3 132][n]Come visit us when you have time. We'll always welcome you with open arms. [uf 1 3 137][n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]This is Mitsuko [uf 1 3 137][n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]Hello, [uf 4 2]-chan.[n][uf 1 5 0]I'm getting better at sending messages. It's because I practiced with you.[n][uf 1 5 0]Bunkichi is feeling much better now. [uf 1 3 137] Thank you for everything.[n][uf 1 5 0]Come visit us soon. [uf 1 3 137][n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]TO: [uf 4 2]-chan[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]You've helped us so much.[n][uf 1 5 0]There is something I would like to tell you, so please come to the shop at your earliest convenience.[n][uf 1 5 0]We await your arrival.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Dear [uf 4 2]-chan[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]How have you been?[n][uf 1 5 0]Come swing by the shop to say hello, will you?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Bookworms is open at the cr...[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]You see, lately, my wife has been saying that she wants to see [uf 4 2]-chan.[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]An old man's request[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]My dear [uf 4 2]-chan,[n][uf 1 5 0]Won't you come visit us?[n][uf 1 5 0]From,[n]Bunkichi[n][uf 1 1][e]

