[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Akinari Kamiki[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]UNUSED[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]I don't use my phone much.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]This feels new and refreshing.[n][uf 1 5 0]The weather was just so pleasant that I decided to take a walk to the shrine.[n][uf 1 5 0]What are you doing now?[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Words on a tiny screen[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]seem to convey something more than a letter could.[n][uf 1 5 0]I'm sitting at the bench again, the weather is fine too.[n][uf 1 5 0]Would you come meet me?[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Morning sun in your eyes[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]for a moment, I feel forgiven.[n][uf 1 5 0]While this happiness lasts, that bench springs to mind.[n][uf 1 5 0]If you were next to me, there'd be nothing more I could ask for.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Upon a dry spring[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]a faint light shines, sparkling down upon its remnants.[n][uf 1 5 0]Though I know it's but an illusion, I find myself longing to reach out to it.[n][uf 1 5 0]I want to talk with you today, at the usual place.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Fiction and reality[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]may seem disparate, but their boundaries meld and flow together, just like the changing of the seasons.[n][uf 1 5 0]Will you hear my lie out?[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]My time[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]is closing in; I've been feeling lighter and lighter.[n][uf 1 5 0]If only I could ride a gust of wind that was you... then maybe I'd make it just a little farther.[n][uf 1 5 0]I have a favor to ask of you. Will you meet me?[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Once I stopped lamenting[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]it felt like time began to rush by.[n][uf 1 5 0]It may be ironic, but this is just enough for me.[n][uf 1 5 0]I miss you. I want to see you again. That's all there is.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]If it weren't for you[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]the words spelled out by my hand would never have been read.[n][uf 1 5 0]I want to tell you the rest in person, on the bench where the sun shines through the trees.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Before I knew it[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]I was fervently typing on my cell phone.[n][uf 1 5 0]Would you come meet me?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]It's quiet here.[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]You don't have to cover your ears to feel the calm passage of time.[n][uf 1 5 0]Come join me if you'd like.[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Only a thread[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]binds the two of us together in this world.[n][uf 1 5 0]I'm at the shrine today too.[n][uf 1 1][e]

