[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Wilduck Burger[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]We have a new burger! [uf 1 3 149][n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Have you tried our NEW burger with UNKNOWN ingredients?[n][uf 1 5 0]Plus, now our fries are extra SALTY![n][uf 1 5 0]We await your visit, Wilducklings![n]=========================[n]Secret recipes, mysterious ingredients... Do you have the guts to go Wilduck!?[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]THE WAIT IS OVER [uf 1 3 135][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]The Weekend Wilduck Set is finally HERE! [uf 1 3 136][n]Plus, your free drink that comes with the set will have extra ICE![n][uf 1 5 0]Peck away, Wilducklings![n]=========================[n]Secret recipes, mysterious ingredients... Do you have the guts to go Wilduck!?[n][uf 1 1][e]

