[msg MSG_000_0_0 [Thin Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1501]Look, it's Sanada-senpai![n][uf 1 1][e]

[msg MSG_001_0_0 [Gaudy Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1502]Wait for us![n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 3 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Have you noticed how popular Sanada-san is with the ladies? Man, take a look at that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I guess neither of us really got to know him before all this crazy stuff happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 3 0 25 25]He's the captain of the boxing team. Never lost a single match. I know that's cool and all, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Who'da thought boxing would turn you into a chick magnet!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I mean, come on! They're fawning on him more than a harem manga! I wonder where they're going...[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Hey, are you guys free this afternoon?[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Huh!? Er, us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 3 1 25 25]I-I mean, hell yeah! We'd love to join your little, uh, group here...[n][uf 1 1][e]

[sel SEL_005_2_0 top]
[uf 0 5 65278][uf 2 1]What about our shopping?[e]
[uf 0 5 65278][uf 2 1]What about the fate of the world?[e]

[msg MSG_005_3_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]We can shop later![n][uf 1 1][e]

[msg MSG_005_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Ah, don't be lame... Even heroes need some rest now and then, y'know?[n][uf 1 1][e]

[msg MSG_005_6_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Well? Are you free or not?[n][uf 1 1][e]

[msg MSG_005_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]O-Of course! Uh... No problemo![n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I want the two of you to meet me at Paulownia Mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]You know where it is, right? I'll be waiting at the police station.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Got it?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Th-The police station?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 3 3 25 25]You mean, we're not hangin' out with your friends...?[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Who, these girls?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 4 0 25 25]No, I don't even know their names. Hearing so much chitchat gives me a headache.[n][uf 1 1][e]

[msg MSG_008_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Anyway, I'm going on ahead. Don't keep me waiting.[n][uf 1 1][e]

[msg MSG_009_0_0 [Thin Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 1501]Wait, Senpai! Don't leave us![n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Man, how can he not know their names!? I mean, seriously! Just look at them![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Uhh, anyway, let's go![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Sanada asked us to meet him at[n]the Paulownia Mall police station...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Junpei and I decided to head over.[n][uf 1 1][e]

