[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 1 0 0]I'm glad you're all safe.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Excellent work. The enemy was clever, but you came out on top.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]Thank you.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]You did good too, Takeba. It's no wonder you volunteered.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 1 0 0 5 0 0]Uh, yeah. Right...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 6 0 0]And you as well, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]You were able to remain calm during the enemy's mental assault.[n][uf 1 1][e]

[msg MSG_005_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Maybe you're finally starting to recognize yourself as a leader. Keep up the good work.[n][uf 1 1][e]

[msg MSG_005_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 52 65535 0 0][uf 3 1 0 0 0 9 0 0]......[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Our team survived another dangerous fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It feels like the level of trust[n]between us all has grown...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]All right, let's call it a night.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, Yukari-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Um, about that thing you mentioned the other day...[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 13 0 0]You found something?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Y-Yes.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Okay, tell me about it later.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 16 0 0]All right! We should head back, too.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Hey, come on, Junpei. Let's go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 2 1 25 25]Fuuka played a big role in this one again. Seems like the second-years are really putting in the work![n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Looks like you're really shining out there, [uf 4 2].[n][uf 1 1][e]

[msg MSG_014_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 2]... So, you're the hero again, huh?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]It was just luck.[e]
[uf 0 5 65278][uf 2 1]We all did our part.[e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Yeah, right. You know it's not.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Really, now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Well, whatever, I guess.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 24 0 0]Don't tell me you're jealous someone else is getting all the attention.[n][uf 1 1][e]

[msg MSG_018_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 2 0][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Shut up![n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]What's his problem?[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We successfully defeated the[n]Shadows this month, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There should be fewer victims for a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But I'm too exhausted to[n]think about all that right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should hurry back to the[n]dorm and get some rest...[n][uf 1 1][e]

