[msg MSG_010_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]It's nice that we don't have as much crap to deal with up here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]There aren't as many weeds or pests on the roof, and no moles or other critters that'll dig our plants up.[n][uf 1 1][e]

[msg MSG_010_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Still gotta watch out, though...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 10 1 25 25]Some hungry asshole might try to help himself to the whole crop.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Normally, that wouldn't happen.[e]
[uf 0 5 65278][uf 2 1]They're getting executed.[e]
[uf 0 5 65278][uf 2 1]Sorry about that...[e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 10 1 25 25]Yeah. Normally...[n][uf 1 1][e]

[msg MSG_013_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 10 1 25 25]...Didn't know you were so hot-blooded.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 10 0 25 25]Most of us here are decent and mature enough that we'd ask before doin' something like that.[n][uf 1 1][e]

[msg MSG_013_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 10 1 25 25]...With one exception.[n][uf 1 1][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 10 0 25 25]Nah, you're fine. You're the one growin' 'em, after all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Just know when to hold back. Don't end up like a certain other dumbass around here.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]...I mentioned I did a bit of gardening back at the orphanage, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]If someone sneaks a bite, it's no big deal, but this one time some older kids stole our whole crop...[n][uf 1 1][e]

[msg MSG_015_3_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Aki got so pissed when that happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]He went after 'em all by himself, even though they were twice as tall as he was...[n][uf 1 1][e]

[msg MSG_015_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]...Then again, that's probably not much different from how he is now.[n][uf 1 1][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]He hasn't changed at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Compare that to these guys, growing bigger every day...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]I tended the plants with Aragaki...[n][uf 1 1][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]This should be good for today.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Thanks to the care we put in, it looks[n]like the plants will grow nicely...[n][uf 1 1][e]

[msg MSG_021_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]You can head on back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I'll stay and finish up. You can thank me by helpin' out again sometime.[n][uf 1 1][e]

