[msg MSG_702_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 50 0 0][uf 3 1 1 0 2 1 0 6]I'll begin searching for the monsters' weaknesses.[n][uf 1 1][e]

[msg MSG_702_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 50 0 0][uf 3 1 1 0 2 2 0 6]Please give me some time...![n][uf 1 1][e]

[msg MSG_702_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 50 0 0][uf 3 1 1 0 2 3 0 6]It's done. I can start the analysis at any time![n][uf 1 1][e]

[msg MSG_702_1_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 50 0 0][uf 3 1 1 0 2 4 0 6]Please tell me when to activate it![n][uf 1 1][e]

[msg MSG_702_2_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 50 0 0][uf 3 1 1 0 2 5 0 6]I-I didn't know I had this kind of power...[n][uf 1 1][e]

[msg MSG_702_6_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Your ability is just what we'd hoped for. It's even more accurate than Mitsuru's...![n][uf 1 1][e]

[msg MSG_702_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]The enemy's aura has shifted...![n][uf 1 1][e]

[msg MSG_702_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]So, they were changing their affinity! No wonder...[n][uf 1 1][e]

[msg MSG_702_5_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Hey, I can see the enemy's weakness now![n][uf 1 1][e]

[msg SYS_702_0_9]
[uf 0 5 65278][uf 2 1]You can now use Full Analysis. It can be activated from the analysis screen. Try using it when you don't know the affinity of an enemy Shadow.[n][e]

