[msg MSG_000_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]Have you noticed the clock over there, by any chance?[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 1 65535 65535 0 0]You see, it was I who decided to place it at that location...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]...Of course, that was a bold-faced lie. It actually appeared completely of its own accord.[n][uf 1 1][e]

[msg MSG_002_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]I suspect it may prove useful somehow... Do give it a try, if you are so inclined.[n][uf 1 1][e]

