[msg MSG_DISCOVER_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5117 0 0]We've caught the Shadow! Now it's time to defeat it![n][uf 1 1][e]

[msg MSG_DISCOVER_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5117 0 0]Now! It's in your hands, everyone![n][uf 1 1][e]

[msg MSG_DISCOVER_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5117 0 0]This is our chance! Don't let it escape![n][uf 1 1][e]

[msg MSG_REACTION_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 1 20040 0 0]Ugh, it's so fast! We're taking it down right here and now![n][uf 1 1][e]

[msg MSG_REACTION_JUNPEI [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2095 0 0]Got 'em! You ain't goin' anywhere, pal![n][uf 1 1][e]

[msg MSG_REACTION_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3117 0 0]This is turning into a hassle... We're dealing with it now![n][uf 1 1][e]

[msg MSG_REACTION_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]So it's been consumed by its obsession with treasure... No matter, we'll deal with it here![n][uf 1 1][e]

[msg MSG_REACTION_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]未使用[n][uf 1 1][e]

[msg MSG_REACTION_AEGIS [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6117 0 0]We finally cornered it. There is no escape![n][uf 1 1][e]

[msg MSG_REACTION_AMADA [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Huh, it's actually pretty big now that we've closed in on it. Let's take it down![n][uf 1 1][e]

[msg MSG_REACTION_KOROMARU [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_REACTION_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Why you gotta run...? Let's just hurry up and beat the crap out of it.[n][uf 1 1][e]

