[msg MSG_000_0_0 [Leisurely Businessman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]I decided to get another job, but I've been keeping it secret from my wife and daughter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]So even if I don't succeed, I've got a plan B.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]I guess that's how the world works.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]People think nothing of ruining someone else's life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]I've just got to do my best. I'll deal with what happens when it comes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 401]What about you kids? Are you satisfied with your lives?[n][uf 1 1][e]

