[msg MSG_000_0_0 [Taxi Driver]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 416]I thought about following Nyx-sama to see if I could get my family back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 416]But that wouldn't have helped. It was my fault, sticking with this job and ignoring them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 416]I'm thinking about going to see my wife and trying to patch things up with her.[n][uf 1 1][e]

