[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Have you seen this photo before?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]There's Sanada-senpai, Kirijo-senpai, and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]And that one student who passed away last year in an incident, um... Aragaki-senpai?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]They all look so young, so maybe this is from when they started high school? I wonder if Aragaki-senpai also used to live in the dorms.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]I always thought he looked kinda scary, but in this picture...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]He seems so kind. It's a really nice picture.[n][uf 1 1][e]

