[msg MSG_000_0_0 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16603 0 0][uf 5 21 1 151]Oh, hey, it's you! Why do you look so grim?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]You come here a lot, don'tcha? You shouldn't rely so much on medicine, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]You're still young. You should build strength by exercising, eating well, and doing schoolwork.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]Don't worry obsessively over your health. That's the doctor's job. Haha![n][uf 1 1][e]

[msg MSG_001_0_0 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16603 0 0][uf 5 21 1 151]Oh, you... I think I've seen you come here a couple times.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]You're still young, so you shouldn't rely so much on medicine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]You can live a healthy life without the need for medicine if you exercise, eat well, and study hard.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16603 0 0][uf 5 21 1 151]Hey there. You here for some medicine?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]That's fine and all, but you're young; you should try not to rely on medicine too much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 5 21 1 151]You can live a healthy life without the need for medicine if you exercise, eat well, and study hard.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16628 0 0][uf 5 21 1 151]Try not to rely on pharmacies so much.[n][uf 1 1][e]

