[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]'Sup, dude? Wanna grab a bite at Hagakure?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]I haven't had their special in a while.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]If you spot me.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Wai— Hold up, I ain't made outta money! I'm just a poor, broke high school kid here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]C'mon, man, we're buds, right? We even bonded while playing catch and everything, riiight?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Er... Guess we never actually got around to that, huh?[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Aw, c'mon! Don't give me the cold shoulder, man![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]We're buds, right? We even bonded while playing catch and everything, riiight?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Er... Guess we never actually got around to that, huh?[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]'Sup, dude? Wanna grab a bite at Hagakure?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]I haven't had their special in a while.[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]If you spot me.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Hold up, I ain't made outta money! I'm just a poor, broke high school kid here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]C'mon, we're buds, right? Just two pals dreamin' about being superheroes someday?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Yeahhh... Those were some real good times.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Aw, c'mon! Don't give me the cold shoulder, man![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]We're buds, right? Just two pals dreamin' about being superheroes someday?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Yeahhh... Those were some real good times.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Hey, something's been buggin' me for a while now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 18 0 0]That seat's been empty this whole time. Who even sits there?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Well...[e]
[uf 0 5 65278][uf 2 1]I don't know.[e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 4 19 0 0]Yeah, I know, I know. You don't remember either, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 4 20 0 0]But, dude, this is driving me crazy. I'm seriously gonna lose all my marbles before the end of the school year.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 4 21 0 0]You don't remember either, huh? Seriously, who the heck sat there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 22 0 0]Gah, this is driving me crazy. I'm gonna lose all my marbles before the end of the school year.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 23 0 0]Well, anyways... Hear me out for a bit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 24 0 0]I got called in to Ms. Toriumi's office again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 25 0 0]She asked me what I was planning to do after April. Dude, like I know![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 26 0 0]And I was tryna play it off, but then she got all worked up and gave me one hell of a lecture...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 27 0 0]Is it just me, or has she gotten way more serious than before?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 28 0 0]Tomochika was sayin' that you can't even bribe her with cake anymore.[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 29 0 0]Oh hey, didja hear from Tomochika about the new teachers coming in April? Apparently, they're all women.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 30 0 0]You have no idea how stoked he was. Honestly, I was getting major secondhand embarrassment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 31 0 0]Well, none of that really matters to me. I already got a special someone...[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 32 0 0]Hm?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 33 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 34 0 0]I... did have a special someone, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 35 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 4 36 0 0]I-I'm not making this up or anything! I wouldn't tell such a pathetic lie to try and look cool![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 37 0 0]I just thought that... that there was someone special in my life...[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 39 0 0]Have I... forgotten something important? Something I never should've forgotten...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 40 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 41 0 0]Sorry, man... I think I'll pass on the ramen, actually.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 42 0 0]Something's been bugging me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 43 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 44 0 0]I just... don't know what.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 1 0 4 45 0 0]But... I feel like it's something I shouldn't have forgotten.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 46 0 0]Well, I guess a lot's happened this year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 47 0 0]I'm a bit fuzzy on the details, but I just know it was jam-packed with all sorts of thrills and chills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 48 0 0]Weird though... If it was that exciting, why can't I remember anything?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 49 0 0]I dunno, man. Feels like my head's a right mess thinking about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 50 0 0]Dude, what the hell did we even do this entire year?[n][uf 1 1][e]

