[msg MSG_000_0_0 [Informed Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 313]The third semester is almost over. After spring vacation ends, we'll be third-years...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 313]And when that happens, we can't take it easy anymore.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 313]I think we were talking about this before, too—during the third semester of our first year?[n][uf 1 1][e]

[msg MSG_001_0_0 [Gossip-Loving Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 314]Yeah, the year flew by way too quickly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 314]I need to start studying more seriously soon if I want to get into a good college...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 314]I think I said the same thing last year, too. Guess I haven't grown up at all since then...[n][uf 1 1][e]

