[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 4 1 0 0]Arf![n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Koromaru seems to be staring[n]into the shrine...[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 4 2 0 0]*whine*[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Koromaru seems sad...[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 4 3 0 0]Arf...[n][uf 1 1][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It seems like Koromaru doesn't want[n]to move from where he's sitting...[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 4 4 0 0]*whine*[n][uf 1 1][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It seems like Koromaru doesn't want[n]to move from where he's sitting...[n][uf 1 1][e]

[msg MSG_008_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 4 5 0 0]Arf![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 4 6 0 0][uf 4 25 9]......[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 4 7 0 0]*whine*[n][uf 1 1][e]

[msg MND_010_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It seems like Koromaru is worried about me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I probably look like a mess.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 4 8 0 0]*whine*[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]It's okay, I'm fine.[e]
[uf 0 5 65278][uf 2 1]I'll get some rest later.[e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 4 9 0 0]Woof.[n][uf 1 1][e]

[msg MSG_014_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 4 10 0 0]...Arf.[n][uf 1 1][e]

[msg MND_015_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Koromaru's expression brightened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He seems relieved.[n][uf 1 1][e]

[msg MSG_016_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 4 11 0 0]Arf![n][uf 1 1][e]

[msg MSG_017_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 4 12 0 0]Arf![n][uf 1 1][e]

[msg MND_018_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Koromaru isn't budging from his spot.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Guess he won't be leaving any time soon.[n][uf 1 1][e]

