[msg MSG_000_0_0 [Elderly Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Welcome![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]What would you like to order? Our special today is fresh mackerel![n][uf 1 1][e]

[msg MSG_001_0_0 [Elderly Woman]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]...As you might suspect, we don't serve sushi here.[n][uf 1 1][e]

[msg MSG_002_0_0 [Elderly Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh? You're a student, aren't you? Then you must be from Gekkoukan High, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]That means... you probably know about the persimmon tree there, don't you?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'm afraid I don't.[e]
[uf 0 5 65278][uf 2 1]Persimmon tree?[e]

[msg MSG_004_0_0 [Elderly Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]You... truly don't know? Not a day goes by that we don't think about that tree![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]At Gekkoukan High, there's an open courtyard area. The tree grows beside a walkway there.[n][uf 1 1][e]

[msg MSG_005_0_0 [Elderly Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Do you think I'm making this up? I assure you, it's real![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]At Gekkoukan High, there's an open courtyard area. The tree grows beside a walkway there.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]It seems there's a persimmon tree[n]somewhere at Gekkoukan High.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Does this elderly couple have[n]some kind of connection to it...?[n][uf 1 1][e]

[msg MSG_007_0_0 [Elderly Woman]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Please excuse my husband. Just consider it the ramblings of an old man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 2 0 25 25]Don't you worry your little head, okay?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]After saying goodbye to the old couple,[n]I decided to leave the bookstore.[n][uf 1 1][e]

