[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Meat and eggs are essential for building a healthy body, and there's no better choice than chicken.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I cooked food an athlete[n]would eat with Sanada.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]This should last a while. Let's put it in the freezer.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]Thanks for always helping out. Let me know when you want some more.[n][uf 1 1][e]

