[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Tanaka[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Congratulations! You won![n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Did that get your heart fluttering? Well, if you want to be successful in life, then come see me.[n][uf 1 5 0]Where am I? Hint: "Pau."[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Southern cassowary kills hu...[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]...As if![n][uf 1 5 0]I'll be at "Pau" today as well. Come right away.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]I'm a girl looking for a good ti...[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Well, well, well... Look at you, getting all excited over a message.[n][uf 1 5 0]Let's correct that personality of yours. Come see me right away.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]URGENT!!! Amazing Commodi...[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Listen. Do NOT fall for these kinds of tricks, all right?[n][uf 1 5 0]If you want to learn more life skills, come see me right away.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Your application has been s...[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Do you feel confident nobody could ever fool you? Well, think again![n][uf 1 5 0]Come see me right away. I'll give you a special nighttime lecture.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]FLASH SALE! 100% OFF ON...[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]This time, it's real. I'm in a good mood, so come see me if you want to hear all about it.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]How old are you?[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]If you're in high school, that makes you around... 16? 17 years old? Don't ask me about my age though.[n][uf 1 5 0]Come quickly now. Time is money.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Beware of fundraising sca...[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]Isn't it exhausting, having to doubt everything you see or hear?[n][uf 1 5 0]People can be quite cruel and malicious... Is that really all right?[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]CLOSEOUT SALE! Thanks fo...[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]Don't worry, it's not about my business.[n][uf 1 5 0]I do, however, have something very important to tell you, so come quickly.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Appointment[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Did you forget? In that case, I'll head on home if you don't show up soon.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Ready to go♪ in your TV♪ Ta...[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]Well? Is it stuck in your head? ♪♪♪[n][uf 1 5 0]Come quickly now.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Reminder: Appointment[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]Stop fooling around. Come right now.[n]=========================[n]Do not reply to this message. Please contact us through the official inquiry portal.[n]©Amazing Commodities Corp.[n][uf 1 1][e]

