[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Unknown Sender[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]At this time, of rains past and leaves verdant, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]At this time, of summer suns and vibrant festivals, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]At this time, of autumn and its bountiful rice harvests, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]While autumn has finally gifted us with pleasant weather, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Early sunsets herald the advent of winter (as does the calendar), and a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]It is now December, the busiest season of the year, and a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Though the new year steadily approaches, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]You ought to know...[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]At the dawn of the new year, when one eases into a new beginning, a human presence can be found within Tartarus... albeit a weakening one.[n][uf 1 5 0]I believe it best for you to hurry if you wish to save them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]The deadline approaches[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]The deadline for a request you accepted a while ago is fast approaching. If you wish to complete it, I believe it best for you to take action soon.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Requests[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Greed is such a terrible sin. Alas, I cannot help but want, and now the number of requests I have for you has increased.[n][uf 1 5 0]I would be incredibly pleased should you spare the time to fulfill them.[n][uf 1 5 0]Sincerely yours, forevermore,[n]Elizabeth[n][uf 1 1][e]

