[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Hagakure Ramen[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]It's good for your skin.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]We'll let you in on a secret—our ramen is really good for your skin. The collagen that our dishes contain is sure to make you stunning![n]=========================[n]Our tender pork is a friend of beautiful skin. Make yourself shine by eating at Hagakure.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Limited menu today.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Today is our special menu day.[n][uf 1 5 0]We only have limited quantities, so get yours before they run out! First come, first served![n]=========================[n]Our tender pork is a friend of beautiful skin. Make yourself shine by eating at Hagakure.[n][uf 1 1][e]

