[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]IS Online[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Tatsuyaaa! ^_^[n][uf 1 5 0]lets have some fun today too! lets play ☆[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]finally done with work =w=[n][uf 1 5 0]u too, tatsu! just throw all ur irl tasks away~ XD[n][uf 1 5 0]hop online and play w meee ^^[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]TATSUYAAAAAA!!!!!![n][uf 1 5 0]u online?[n][uf 1 5 0]WE PLAY TODAY!!!!!!!!![n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]COME ON! TATSU! (/ *-*)/[n][uf 1 5 0]LETS GO!!! TATSU!!! \(*-* \)[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]tatsu, do you copy? come in, ur partner in crime is calling 4 u! B)[n][uf 1 5 0]im waiting in the SNGW dungeon!!![n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1](＞ '-')＞ T[n]＜( '-' )＞ A[n]＜('-' ＜) T[n]＜( '-' )＞ S[n](＞ '-')＞ U[n]＜( '-' )＞ Y[n]＜('-' ＜) A[n]＜( '-' )＞ A[n](＞ '-')＞ A[n]\( '-' )/ !!![n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Tis a nice sunny day! :)[n]Although im spending it inside[n]Thats ok cuz I got u[n]Since u dont care if i look cute[n]U better be online tho!!! =_=[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]heyo friendo~ :3c[n][uf 1 5 0]hehe time to go monster huntin!!![n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]this game is ded but im still gonna play!!! X3[n][uf 1 5 0]tatsuuuuuuuuu!!![n][uf 1 5 0]i miss u ToT[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]imma log on now~ ^_^[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]lets wreck some demons todayyy XD[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]New message from Maya[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]hop online, lets play together~ :D[n][uf 1 1][e]

