[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Hidetoshi Odagiri[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri of the disciplinary committee.[n][uf 1 5 0]This is a reminder that the student council meets today.[n][uf 1 5 0]The agenda today:[n]- Check-in reports[n]- Reviewing tasks[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri of the disciplinary committee.[n][uf 1 5 0]I recommend attending student council meetings regularly so as not to disappoint the president.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri of the disciplinary committee.[n][uf 1 5 0]The student council president will be present at today's meeting. I strongly advise that you attend as well.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]The agenda today:[n]- Check-in reports[n]- Reviewing tasks[n][uf 1 5 0]I will arrive early in order to investigate that incident. I look forward to seeing you today.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]There is nothing of great importance today in regard to student council activities. Therefore, attending will be optional. Do come if you have time.[n][uf 1 5 0]I will be in the student council room dealing with that problematic issue.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]I would appreciate it if you could attend the student council meeting today.[n][uf 1 5 0]I have an important announcement to make as the representative for the disciplinary committee. As I would like to hear your opinion as well, I hope to see you there.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]I have finalized the list of suspects and submitted it. I will debrief the others at the meeting, but I simply wanted to let you know ahead of time.[n][uf 1 5 0]See you in the student council room.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]After poking around about the cigarette butt incident, I can confirm that the suspicions about you have been dropped.[n][uf 1 5 0]I have returned to the regular duties and will be waiting for you in the student council room.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]I have a favor to ask you.[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]I apologize for making such a sudden request, but know that I am only asking you because I hold you in high regard.[n][uf 1 5 0]Come find me in the student council room if you have the time.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]There's a student council meeting today.[n][uf 1 5 0]No need to respond to me. Just come to the student council room.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]Today's student council duties are the same as usual. Come to the student council room if you'd like to attend.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Work Related[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]This is Odagiri.[n][uf 1 5 0]I have high hopes for you. It would be great if you could attend the meeting today.[n][uf 1 5 0]That's all.[n][uf 1 1][e]

