[msg MSG_SENDER_NAME_1]
[uf 0 5 65278][uf 2 1]Yukari Takeba[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]It's nice and warm out today.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Wanna come to the rooftop?[n][uf 1 5 0]It'd be nice to have a little chat up here.[n][uf 1 1][e]

[msg MSG_SENDER_NAME_2]
[uf 0 5 65278][uf 2 1]Junpei Iori[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Hey.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]You're free, right? Come hang out on the rooftop for a bit![n][uf 1 1][e]

