[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Screen Shot[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Want a good cry? [uf 1 3 151][n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Happiness, sadness, anger... Emotions are meant to be felt and expressed, and movies are an excellent way to keep your brain and soul stimulated. [uf 1 3 133][n]Our soft seats are waiting for you. [uf 1 3 132][n]Fun Fact: Different movies will have different effects on you! (But maybe that's common sense.)[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Work at the movies! [uf 1 3 151][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]A rewarding job that provides a range of emotions. Students may apply. Visit the theater for more details.[n][uf 1 5 0]Fun Fact: Movie theaters stimulate the mind in various ways. For example, flex your brain muscles by learning more about movies, or conquer your fears by watching a scary movie in the dark![n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Urgent announcement![n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]The theater is packed today! It's as hectic as a drama![n][uf 1 5 0]We're urgently looking for someone who can work as fast as an action movie protagonist![n][uf 1 5 0]The paycheck will be as big as a Hollywood star's! Well, that's not true... But it'll be more than usual![n][uf 1 5 0]We hope to welcome you to the team![n][uf 1 1][e]

