[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Game Parade Newsletter[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 146][uf 1 3 146][uf 1 3 146] GAMES [uf 1 3 146][uf 1 3 146][uf 1 3 146][n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Come play our popular crane game and try to win a prize! [uf 1 3 146][n]Then stick around and hop into one of our many immersive video games! [uf 1 3 146][n]There's great fun to be had whether you're alone or with friends! [uf 1 3 146][n]We can't wait to see you![n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 146][uf 1 3 146][uf 1 3 146][uf 1 3 146] GAMES [uf 1 3 146][uf 1 3 146][uf 1 3 146][uf 1 3 146][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Game Parade is the safest place to hang out and have fun, with the police just a few steps away! [uf 1 3 146][n]Hop on by and play one of our many immersive video games! [uf 1 3 146][n]There's great fun to be had whether you're alone or with friends! [uf 1 3 146][n]Let's get GAME PARADING!!![n][uf 1 1][e]

