[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]The Information Gatherer[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Security training website[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]You interested in training videos? I found this site with a bunch of self-defense courses for security teams.[n][uf 1 5 0]This kind of stuff is supposed to be trade secret, you know—but I'm letting you in on this because you're my kind of weird.[n][uf 1 5 0]If you're interested, come to Escapade.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Sites for weird ones like you[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]You're weird, so I'm sure you're interested in stuff like secret assassin techniques. I found a good site about it.[n][uf 1 5 0]I also have some info on a waning forum site about history.[n][uf 1 5 0]Sound interesting? Come by Escapade and I'll let you in on it all.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Online forum discovered[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]I found an interesting online forum all about ninjas and their skills.[n][uf 1 5 0]If you're interested, ninja stealth your way over to Escapade.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Legit matchmaking site[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Have you seen the rumors online about a popular new matchmaking site? It requires payment, but it supposedly really works.[n][uf 1 5 0]I'm sure a high school student like you would be all over that stuff, so I'll graciously share my info with you.[n][uf 1 5 0]If you want to check it out, come to Escapade.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Intriguing blog[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]It's been a while since I found a personal blog this intriguing...[n][uf 1 5 0]This is just the kind of thing an oddball like you would be into. You'll want to cradle a tomato after you read it.[n][uf 1 5 0]If you don't know what I'm talking about, get over to Escapade, pronto.[n][uf 1 1][e]

