[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Akihiko Sanada[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]It's me[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Sorry for the sudden invite, but I'm thinking about getting something to eat right now. Do you want to join me?[n][uf 1 5 0]I'm in front of Iwatodai Station.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Sorry[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]It's been a while since I told you I'd return the favor. It's about time for me to pay up, so meet me in front of Iwatodai Station.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Somehow, even after all that's happened, I can still feel hungry.[n][uf 1 5 0]If you're free, I'd like you to come shopping with me. I wanna try something out, so if you can make it, come meet me at Iwatodai Station.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Every once in a while[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]It'd be nice if you could join me in my training regimen.[n][uf 1 5 0]Come meet me at Iwatodai Station if you're feeling up to it.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]This time for sure[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]It's a new year already, but I still intend on keeping my word.[n][uf 1 5 0]I know it's a busy time, but let's go grab a meal together.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Movie[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]Can you survive this heat? Don't forget to stay hydrated.[n][uf 1 5 0]On another note, do you wanna catch a movie together? I hope they're showing something that would get our blood pumping.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Are you free?[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]I have some free time today. Do you wanna accompany me somewhere?[n][uf 1 5 0]I'm in front of Iwatodai Station.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Koromaru[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]I usually see Koromaru in front of the dorm.[n][uf 1 5 0]The other day, I brought him along with me on my jog. It was a good workout.[n][uf 1 5 0]You should hang out with him sometime.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]How're you doing?[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]You're probably busy, but do you have time to meet me right now? I want to have a little chat with you.[n][uf 1 5 0]Come find me at Iwatodai Station.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Sorry[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]If you're free, can you spare a minute to help me out?[n][uf 1 5 0]I'm at Iwatodai Station.[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Training[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]Do you want to join me today?[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Are you busy?[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]Can you set some time aside for me?[n][uf 1 5 0]I'll be waiting at Iwatodai Station.[n][uf 1 1][e]

