[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Chagall Café[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Quality coffee.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]How are you doing on this lovely afternoon?[n][uf 1 5 0]Chagall is open for business today. Our café's most popular item, Pheromone Coffee, is guaranteed to increase your ability to captivate the hearts of everyone around you.[n][uf 1 5 0]We look forward to your visit. [uf 1 3 150][n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Part-time position open.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]We hope everyone is having a great day.[n][uf 1 5 0]Chagall is looking for someone to work at the café today. Students may apply, no experience required. This is a paid position, and perks include free Pheromone Coffee.[n][uf 1 5 0]We look forward to meeting you.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Urgently seeking workers.[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Chagall is very busy today, and we could use all the help we can get.[n][uf 1 5 0]Students may apply, no experience required. Those who work today will receive a bonus on top of the normal paycheck.[n][uf 1 5 0]We look forward to meeting you.[n][uf 1 1][e]

