[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Aigis[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Initiating correspondence.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]I had been refraining from engaging in private correspondence, but I have recently attained permission to do so from Mitsuru-san.[n][uf 1 5 0]I plan to make use of this new responsibility with some regularity.[n][uf 1 5 0]Would you like to walk home together with me?[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Good morning.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Typing accurately on a small device such as a cellular telephone provides more difficulty than I had anticipated.[n][uf 1 5 0]Perhaps I should undergo special training so that I may learn to type as efficiently as Yukari-san.[n][uf 1 5 0]In any case, would you like to walk home together today as well?[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]I have a favor to ask.[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]I apologize for the sudden request.[n][uf 1 5 0]I would like to "drop by" somewhere with you today.[n][uf 1 5 0]If this is acceptable, I will meet you by your seat after school so that we may leave together.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]This is incredible.[uf 1 3 158][n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Did you notice the image? Here it is again: [uf 1 3 158][n]Despite the small number of pixels used and suboptimal resolution of the cell phone screen, it remains clear that the image is depicting a cat. [uf 1 3 158][n]By the way, I would like to go back together today too. Would you please accompany me?[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 158][uf 1 3 158][uf 1 3 158][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]I apologize if I'm being a nuisance. [uf 1 3 158][n]However, I hope that you are able to share my fondness for this small image. [uf 1 3 158][uf 1 3 158][n]I continue to find it quite magnificent. [uf 1 3 158][uf 1 3 158][uf 1 3 158][n]Regardless, would you like to go back together today? [uf 1 3 158][uf 1 3 158][uf 1 3 158][uf 1 3 158][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]No issues to report.[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]I recently underwent maintenance in preparation for the final battle, and I am pleased to report that no abnormalities were found.[n][uf 1 5 0]How about you? How are you doing?[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Would you care to go to the rooftop after school?[n][uf 1 5 0]I would like to look out over the ocean with you.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]There's something that I wish to tell you. Will you please listen to what I have to say?[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]I would really like to walk home with you today.[n][uf 1 5 0]I want to be with you and to stay by your side.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]There's something I would like to ask of you. Will you please indulge me?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Hello. [uf 1 3 158][n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]Are you available after school? There is something I would like to do with you at the dorm. [uf 1 3 158][n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]It is Aigis.[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]I will be near your desk after school for easy access should you wish to spend time together.[n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]After school.[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]I would like to be by your side. Is that all right?[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Let's go back together.[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]I will see you after school. Please consider walking home with me.[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1]Let's watch a movie.[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]Apparently, the facility near Port Island Station that shows motion pictures specializes in that singular activity.[n][uf 1 5 0]I have heard that these "movies" are enhanced by the facility's use of large screens and high quality audio.[n][uf 1 5 0]I would like to experience this together with you.[n][uf 1 1][e]

