[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Mitsuru Kirijo[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Thank you for your time[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]I'm not quite used to sending messages this way, so I apologize in advance if I say something rude.[n][uf 1 5 0]Are you available after school today? If you've already made plans, I don't mind joining you either.[n][uf 1 5 0]Should you find that agreeable, come find me in the hallway on the first floor.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Once again[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I'd like your help. Would you mind showing me another place again? Ideally, after school today.[n][uf 1 5 0]You can find me in the hallway on the first floor.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]If you have the time[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]I won't ask you to take me somewhere to eat this time. In fact, I need your help and wisdom regarding a certain matter.[n][uf 1 5 0]Shall we head to the library together?[n][uf 1 5 0]I'll be waiting at the usual spot.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]I'd like to ask you a favor[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]I apologize for the short notice, but there's a place I'd like to stop by on the way back. You seem familiar with the area, so I was hoping you could show me around.[n][uf 1 5 0]Come find me if you find that agreeable.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Nothing important [uf 1 3 153][n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Yukari told me, "You sound so angry [uf 1 3 138]" and, "You're so stiff [uf 1 3 138]" in response to my messages, so I've been trying to use emojis. [uf 1 3 137] Is it working? [uf 1 3 139][n]I'm thinking of stopping by the library later. [uf 1 3 137] Would you care to join me? [uf 1 3 140][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]On the way home [uf 1 3 150][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]I'm surprised there's even an emoji for this. [uf 1 3 150][n]Shall we stop by somewhere again on the way back? If you have the time, that is. [uf 1 3 150][n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Another movie?[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]I'm not trying to bring up your promise the other day as an excuse, but would you indulge me in another favor?[n][uf 1 5 0]I'd like to stop by the theater on the way home.[n][uf 1 5 0]You can find me at the usual place.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]I know I gave you some trouble the other day. It's been on my mind this whole time.[n][uf 1 5 0]Could we meet? I'd like to talk with you.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1](No Subject)[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]I'm not sure how to express these feelings of mine... All I know is that you're responsible for making me this way.[n][uf 1 5 0]If you have the time, could you come see me?[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]I'd like to apologize[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]I would like a chance to apologize for the rude encounter the other day, as well as to inform you of the aftermath.[n][uf 1 5 0]May I have some of your time? Come look for me if that's all right with you.[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]It's me [uf 1 3 137][n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]It's as if there's no end to this cold weather. [uf 1 3 140] Take care of yourself so as not to get sick. [uf 1 3 152][n]How does your schedule look? Could you accompany me somewhere today?[n][uf 1 5 0]I still can't get used to using emojis. [uf 1 3 138][n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Sorry to bother you[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]Are you free today? I'd like for us to do something together.[n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Sorry for the trouble[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]I have some time to spare today. How about you?[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Are you busy?[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]If you have time, let's do something together. I'll be waiting for you after school.[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1]Let's go somewhere[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]We rarely ever get a day off, so it doesn't feel right to shut ourselves inside the dorm.[n][uf 1 5 0]I don't plan on going somewhere far. Would you care to join me?[n][uf 1 1][e]

[msg MSG_031_0_0]
[uf 0 5 65278][uf 2 1]Shall we watch a movie?[n][uf 1 1][e]

[msg MSG_032_0_0]
[uf 0 5 65278][uf 2 1]Apologies for the sudden invitation, but would you like to watch a movie with me?[n][uf 1 5 0]I'd rather not go alone so we could discuss it afterwards.[n][uf 1 5 0]I believe it will help broaden your perspective—if you have the time.[n][uf 1 5 0]Come find me if you'd like to go.[n][uf 1 1][e]

[msg MSG_033_0_0]
[uf 0 5 65278][uf 2 1]Student council[n][uf 1 1][e]

[msg MSG_034_0_0]
[uf 0 5 65278][uf 2 1]How's your progress? Have you spoken with Ms. Toriumi about joining the student council?[n][uf 1 5 0]If not, you should be able to find her in the [uf 0 1 2]faculty office[uf 0 1 27] after school.[n][uf 1 5 0]I look forward to you joining.[n][uf 1 1][e]

[msg MSG_035_0_0]
[uf 0 5 65278][uf 2 1]Student council[n][uf 1 1][e]

[msg MSG_036_0_0]
[uf 0 5 65278][uf 2 1]Congratulations on joining the student council. Now you'll be permitted to enter the [uf 0 1 2]student council room[uf 0 1 27] for meetings.[n][uf 1 5 0]Today is one such day where we meet. I look forward to seeing you there.[n][uf 1 1][e]

[msg MSG_037_0_0]
[uf 0 5 65278][uf 2 1]Are you free tonight?[n][uf 1 1][e]

[msg MSG_038_0_0]
[uf 0 5 65278][uf 2 1]Naganaki Shrine is hosting a summer festival tonight.[n][uf 1 5 0]I was planning on taking Aigis there to show her around, but I'm not certain if I'd make a good guide.[n][uf 1 5 0]If it's not too much trouble, could you come along as well?[n][uf 1 1][e]

[msg MSG_039_0_0]
[uf 0 5 65278][uf 2 1]Merry Christmas[n][uf 1 1][e]

[msg MSG_040_0_0]
[uf 0 5 65278][uf 2 1]I've never thought of spending Christmas together with someone before... But then I met you.[n][uf 1 5 0]Today, I want it to be just the two of us.[n][uf 1 5 0]I'll be waiting for your response.[n][uf 1 1][e]

[msg MSG_041_0_0]
[uf 0 5 65278][uf 2 1]Can we talk?[n][uf 1 1][e]

[msg MSG_042_0_0]
[uf 0 5 65278][uf 2 1]There's a personal matter I'd like to discuss with you. Could you hear me out?[n][uf 1 5 0]But you must keep this a secret from the others.[n][uf 1 5 0]Let's talk in school. You can find me in the first-floor hallway.[n][uf 1 1][e]

[msg MSG_043_0_0]
[uf 0 5 65278][uf 2 1]I'd like some assistance[n][uf 1 1][e]

[msg MSG_044_0_0]
[uf 0 5 65278][uf 2 1]As I've mentioned before, there's something I'd like to discuss with you.[n][uf 1 5 0]I know you're not personally involved, but I'd appreciate your assistance.[n][uf 1 5 0]Come find me whenever you have time.[n][uf 1 1][e]

[msg MSG_045_0_0]
[uf 0 5 65278][uf 2 1]Can I ask you a favor?[n][uf 1 1][e]

[msg MSG_046_0_0]
[uf 0 5 65278][uf 2 1]It concerns Amada.[n][uf 1 5 0]He seems to be keeping to himself inside his room these days. You can also hear noises coming from his room at night...[n][uf 1 5 0]Could you check in on him? It seems he respects you a lot.[n][uf 1 1][e]

[msg MSG_047_0_0]
[uf 0 5 65278][uf 2 1]About Amada[n][uf 1 1][e]

[msg MSG_048_0_0]
[uf 0 5 65278][uf 2 1]Have you been able to talk to him? I would really appreciate it if you did.[n][uf 1 5 0]It seems like he's holed up in his room again today...[n][uf 1 5 0]I'm counting on you.[n][uf 1 1][e]

[msg MSG_049_0_0]
[uf 0 5 65278][uf 2 1]About Aragaki[n][uf 1 1][e]

[msg MSG_050_0_0]
[uf 0 5 65278][uf 2 1]Have you heard anything from Aragaki about returning to school?[n][uf 1 5 0]I suppose it'd be best not to get our hopes up, but I'd still like to know how things are going.[n][uf 1 5 0]Can we meet to talk about it?[n][uf 1 1][e]

[msg MSG_051_0_0]
[uf 0 5 65278][uf 2 1]Do you have time right now?[n][uf 1 1][e]

[msg MSG_052_0_0]
[uf 0 5 65278][uf 2 1]I'd like an update regarding the matter with Aragaki. Could you come talk to me when you're free?[n][uf 1 1][e]

[msg MSG_053_0_0]
[uf 0 5 65278][uf 2 1]Just letting you know[n][uf 1 1][e]

[msg MSG_054_0_0]
[uf 0 5 65278][uf 2 1]I'll be on the second floor today. Come let me know if you want to go to Tartarus.[n][uf 1 1][e]

[msg MSG_055_0_0]
[uf 0 5 65278][uf 2 1]Just letting you know[n][uf 1 1][e]

[msg MSG_056_0_0]
[uf 0 5 65278][uf 2 1]I'll be on the third floor today. If you want to go to Tartarus, come find me.[n][uf 1 1][e]

[msg MSG_057_0_0]
[uf 0 5 65278][uf 2 1]For your information[n][uf 1 1][e]

[msg MSG_058_0_0]
[uf 0 5 65278][uf 2 1]I'll be in the command room today. If you want to go to Tartarus, come and let me know. I'll be able to join you as well.[n][uf 1 1][e]

[msg MSG_059_0_0]
[uf 0 5 65278][uf 2 1]About the girl from last night[n][uf 1 1][e]

[msg MSG_060_0_0]
[uf 0 5 65278][uf 2 1]Good morning.[n][uf 1 5 0]The hospital notified us earlier today that her condition has stabilized.[n][uf 1 5 0]For now, Akihiko and I will handle questioning her. You should just go about your usual routine.[n][uf 1 1][e]

[msg MSG_061_0_0]
[uf 0 5 65278][uf 2 1]Regarding that matter[n][uf 1 1][e]

[msg MSG_062_0_0]
[uf 0 5 65278][uf 2 1]Have you delivered the form to Aragaki?[n][uf 1 5 0]If you haven't, then you should be able to find him at [uf 0 1 2]the back alley on Port Island[uf 0 1 27].[n][uf 1 5 0]Thank you for doing this.[n][uf 1 1][e]

