[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Chihiro Fushimi[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]It's Fushimi.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Hello.[n][uf 1 5 0]Please excuse me for contacting you without notice.[n][uf 1 5 0]I don't mean to impose, but I wonder if I could trouble you to meet after school...?[n][uf 1 5 0]I'll be in front of the student council room. I hope it's not an inconvenience.[n][uf 1 5 0]Thank you.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Hello.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Good afternoon. It's Fushimi.[n][uf 1 5 0]Forgive me for asking for help so suddenly, but do you have time to meet me after school?[n][uf 1 5 0]I'll be at the usual spot in the hallway, but it's not a problem if you can't make it.[n][uf 1 5 0]Thank you.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]It's Fushimi.[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Good afternoon.[n][uf 1 5 0]I hope my messaging you on such short notice hasn't been an issue. I appreciate the time you've been able to spare.[n][uf 1 5 0]Would you be able to go somewhere with me after school? Anywhere is fine.[n][uf 1 5 0]I'll be waiting in the hall again.[n][uf 1 5 0]Thank you.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]I have a favor to ask.[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Hello, [uf 4 1]-san.[n][uf 1 5 0]I wanted to ask this of you in person, but couldn't summon the courage this time...[n][uf 1 5 0]Could I borrow your attention after classes? There's something I'd like to talk to you about.[n][uf 1 5 0]I'll be in front of the student council room, as usual.[n][uf 1 5 0]Thank you.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Hello [uf 1 3 137][n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Good afternoon, [uf 4 1]-san.[n][uf 1 5 0]Your advice the other day was greatly appreciated. Although I don't have anything to give you in return, I hope to one day return the favor.[n][uf 1 5 0]I think I've finally gotten used to messaging you.[n][uf 1 5 0]Would you like to walk home together? [uf 1 3 137][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Sorry [uf 1 3 138][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san, hello.[n][uf 1 5 0]I hope this doesn't come at an inconvenient time for you.[n][uf 1 5 0]I'm in need of a favor. Could you meet me at the usual spot?[n][uf 1 5 0]Sorry for always asking for your help... But I truly appreciate it.[n][uf 1 5 0]-Fushimi [uf 1 3 137][n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Hello![n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Good afternoon.[n][uf 1 5 0]Another sudden request. Sorry.[n][uf 1 5 0]Do you have time to help me study?[n][uf 1 5 0]I'm thinking about that illustration collection and am having trouble concentrating. I feel like having you around would help me to focus.[n][uf 1 5 0]It'd be great to see you~[n][uf 1 5 0]-Fushimi [uf 1 3 137][n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Please help... [uf 1 3 138][n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]Sorry, [uf 4 1]-san.[n][uf 1 5 0]I don't mean to alarm you, but I'm feeling very on edge. That's not unusual for me, but it's gotten so bad lately that I'm having trouble eating.[n][uf 1 5 0]I keep worrying about what everyone is saying... But when I'm with you, that feeling goes away.[n][uf 1 5 0]I hope I'm not bothering you.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san [uf 1 3 140][n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]Hi~[n][uf 1 5 0]I should be used to messaging you by now, but I'm still nervous typing this. [uf 1 3 138][n]Would it be all right if I asked you to go out with me?[n][uf 1 5 0]I really want to see you...[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]What should I do?[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Between glares from classmates and whispers from strangers, I worry I won't be able to repair my reputation.[n][uf 1 5 0]No one seems to care about what the truth really is. I can't help but think this would go away if I left school outright.[n][uf 1 5 0]I need to think this through...[n][uf 1 5 0]Will you walk home with me?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Hi there [uf 1 3 140][n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]-san,[n][uf 1 5 0]Thank you so much for the other day. And please thank the president of the student council for me, too. [uf 1 3 137][n]When you have some time, there's something I'd like to discuss with you. Let me know when you're free~[n][uf 1 5 0]-Chihiro[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]It's Fushimi.[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]Hello, [uf 4 1]-san.[n][uf 1 5 0]Are you available to meet me today?[n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Dear [uf 4 1]-san.[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]I hope I'm not disturbing your afternoon.[n][uf 1 5 0]Do you have time to meet?[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Hello.[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]I'm sorry to keep asking this way, but do you have some time to spare for me?[n][uf 1 5 0]I'll be waiting to hear from you.[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1]Sorry to bother you.[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]Hello! It's Fushimi.[n][uf 1 5 0]Would you like to go somewhere together?[n][uf 1 5 0]Sorry for the short notice. If you have some time and are interested, please let me know before the end of the afternoon.[n][uf 1 5 0]Thank you.[n][uf 1 1][e]

[msg MSG_031_0_0]
[uf 0 5 65278][uf 2 1]It's too hot [uf 1 3 138][n][uf 1 1][e]

[msg MSG_032_0_0]
[uf 0 5 65278][uf 2 1]Hello! It's Fushimi.[n][uf 1 5 0]It seems that summer vacation is coming to a close.[n][uf 1 5 0]I've acquired some tickets for a movie showing today. It's a bit of a tragedy, but it features some very charismatic acting performances...[n][uf 1 5 0]Would you like to go together?[n][uf 1 1][e]

[msg MSG_033_0_0]
[uf 0 5 65278][uf 2 1]If possible...[n][uf 1 1][e]

[msg MSG_034_0_0]
[uf 0 5 65278][uf 2 1]Hello.[n][uf 1 5 0]It's still so hot every day. [uf 1 3 140][n]Do you know about the festival tonight at Naganaki Shrine?[n][uf 1 5 0]If you were planning to go, I would love to go together. It would be nice to make some last summer memories with you.[n][uf 1 5 0]Please let me know what you think.[n][uf 1 1][e]

[msg MSG_035_0_0]
[uf 0 5 65278][uf 2 1]Plans for Christmas?[n][uf 1 1][e]

[msg MSG_036_0_0]
[uf 0 5 65278][uf 2 1]The end of the year swept in so quickly.[n][uf 1 5 0]We've made very pleasant memories this year, and I was hoping to make one more before this chapter comes to a close.[n][uf 1 5 0]I'm very grateful to have met you, [uf 4 1]-san. Would you like to spend Christmas together...? [uf 1 3 154][n][uf 1 1][e]

