[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Gekkoukan High School, practice field...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We trained all day to prepare for[n]the competition on August 2nd.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]My body feels light...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But my time wasn't that good.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I beat my record![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm second on the team.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Just one person left...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The tournament is the[n]day after tomorrow...[n][uf 1 1][e]

