[msg MSG_000_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Mom...[n][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]...![n][e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]...Gugh![n][e]

[msg MSG_004_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Just what was that for?[n][e]

[msg MSG_004_5_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 5 0]What reason could you possibly have[n]to risk your life for this child?[n][e]

[msg MSG_004_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Ah... Ah...[n][e]

[msg MSG_005_0_0 [Distant Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Shinji![n][e]

[msg MSG_006_0_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]...Your companions?[n][e]

[msg MSG_006_5_0 [Takaya]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 5 0]How very unfortunate. The fun had just begun...[n][e]

[msg MSG_007_0_0 [Ken Amada]]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]Shinji! Hang in there![n][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]Aragaki![n][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Senpai![n][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Aragaki-san![n][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]No...[n][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 16 0 0]......[n][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Heh... What's with the long face?[n][e]

[msg MSG_014_1_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 1 0]Isn't this... exactly what you wanted?[n][e]

[msg MSG_014_3_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 3 0]It's alright... Hold onto that anger.[n][e]

[msg MSG_014_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 5 0]Let it be your strength...[n][e]

[msg MSG_014_6_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 6 0]You've still got your whole life ahead of you...[n][e]

[msg MSG_014_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 7 0]Don't ya, kid...?[n][e]

[msg MSG_014_8_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 8 0]From now on...[n][e]

[msg MSG_014_9_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 9 0]You're gonna have to live... for yourself...[n][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]But I... But I can't...[n][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]Aki... Look after 'im.[n][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]I will.[n][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]This is how it... should be...[n][e]

[msg MSG_018_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 29 0 0]......[n][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Ah...[n][e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]Ah... Ah...[n][e]

[msg MSG_021_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 5 0]AAAAAAAAAAAAH...![n][e]

