[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 81 0 0][uf 3 1 1 0 1 20510 0 0]Whoa, I did it...![n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 1 20511 0 0]Fantastic work, Takeba! You performed as well as I hoped you would.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20512 0 0]Totally! I couldn't take my eyes off you![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 81 0 0][uf 3 1 1 0 1 20513 0 0]Can you try not being a creep...?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20514 0 0]Great, looks like everyone's gotten used to handling their Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20515 0 0]Leader, take note of each member's strengths and conduct the battle accordingly.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20516 0 0]I can still sense some enemies around. Let's move on.[n][uf 1 1][e]

