[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 1 0 0]How're you holding up, Kaz?[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 5 151 65535 0 0][uf 3 1 1 0 0 2 0 0]My knee's not so good. I can't put too much weight on it.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 3 0 0]Okay, then let's take an early break.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 4 0 0]You mind giving Kaz's leg a quick massage?[n][uf 1 1][e]

[msg MSG_003_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]No problem. Let's see that leg.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 151 65535 0 0][uf 3 1 1 0 0 6 0 0]Sorry. You're missing practice because of me.[n][uf 1 1][e]

[msg MSG_005_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Hey, don't be like that! This is for your nephew, right?[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 151 65535 0 0][uf 3 1 1 0 0 8 0 0]Still, I'm really sorry.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I started on my way back[n]to the dorm after practice.[n][uf 1 1][e]

