[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Did we do it!?[n][uf 1 1][e]

[msg MSG_001_0_0 [Nyx Avatar]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Such a pity...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]You understand your fate, yet you still fight against it with all your might...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]If only there were more like you, then perhaps the Fall could have been prevented...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]But... it's too late now.[n][uf 1 1][e]

