[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10860 0 0]Wouldn't it be funny if all my knee problems turned out to be growing pains?[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]But, honestly, I don't wanna get any bigger than I am right now. It's not like I'm gonna go into pro wrestling.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Oh, you can have my rice if you want... Here, take it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10872 0 0]I'm trying to cut down on carbs.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]You prefer bread?[e]
[uf 0 5 65278][uf 2 1]Are you on a diet?[e]
[uf 0 5 65278][uf 2 1]Are you feeling sick?[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10877 0 0][uf 5 13 8 15 105]What, you think I'm a bread guy just 'cause I don't want my rice?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]Y'know, I honestly was not expecting you to say that. Didn't take you for a jokester.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto seems to be having fun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10824 0 0][uf 5 13 8 30 105]Yeah. I gotta watch what I eat these days so I can build muscle mass.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]I'll do whatever it takes to win the regionals... Remember, it's all about the mindset, [uf 4 1].[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto has shown me his resolve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10827 0 0]Dude, you think my dedication is that weak? Remember, I'm ready 24/7.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]I always keep my body in perfect condition... 'Cept my knee right now, I guess.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto looks a little sullen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10869 0 0]Ugh, dammit... I really do want some rice. Just having it right in front of me is torture...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 4 23 0 105 0 25 25]No, I gotta snap out of it. This is perfect mental training. Go ahead and eat it, [uf 4 1]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]C'mon, just shovel it down![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After finishing the meal under Miyamoto's[n]watch, I headed back to the dorm.[n][uf 1 1][e]

