[msg TRL_000_0_0 [Rush]]
[uf 0 5 65278][uf 2 1][uf 4 8 15]Pressing [uf 1 3 108] during battle will let you [uf 0 1 2]Rush[uf 0 1 27] through combat. Every party member will attack automatically and continuously.[n][uf 1 1][e]

[msg TRL_001_0_0 [Rush]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]This allows the battle to proceed at high speed without any player input. To stop Rushing, press [uf 1 3 999].[n][uf 1 1][e]

