[msg TRL_000_0_0 [Retries During Battle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If the game difficulty is set to Peaceful, then you can choose to retry a battle even if your HP drops to 0.[n][uf 1 1][e]

[msg TRL_001_0_0 [Retries During Battle]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When selecting "I can't die yet," all your party members will have their HP and SP restored. All status ailments will be lifted, and the battle will resume.[n][uf 1 1][e]

