[msg TRL_000_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Fool[uf 0 1 27]: EXP acquired from battles will increase until you leave Tartarus.[n][uf 0 1 2]Magician[uf 0 1 27]: Acquire rare items.[n][uf 1 1][e]

[msg TRL_001_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]High Priestess[uf 0 1 27]: All-Out Attack damage will increase until you leave Tartarus for the day.[n][uf 1 1][e]

[msg TRL_002_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Empress[uf 0 1 27]: The Endurance, Agility, and Luck of Personas in your possession will increase by 2.[n][uf 0 1 2]Emperor[uf 0 1 27]: The Strength and Magic of Personas in your possession will increase by 2.[n][uf 1 1][e]

[msg TRL_003_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Hierophant[uf 0 1 27]: The level of your currently equipped Persona will increase by 1.[n][uf 0 1 2]Lovers[uf 0 1 27]: Social Link bonuses for Persona fusions will increase until you leave Tartarus.[n][uf 1 1][e]

[msg TRL_004_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Chariot[uf 0 1 27]: Your maximum HP will increase by 10.[n][uf 0 1 2]Justice[uf 0 1 27]: You will be able to pick one additional card from Shuffle Time.[n][uf 1 1][e]

[msg TRL_005_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Hermit[uf 0 1 27]: Your maximum SP will increase by 7.[n][uf 1 1][e]

[msg TRL_006_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Fortune[uf 0 1 27]: All current party members' maximum HP will increase by 8.[n][uf 0 1 2]Strength[uf 0 1 27]: All current party members' maximum SP will increase by 5.[n][uf 1 1][e]

[msg TRL_007_0_0 [Major Arcana Effects 1]]
[uf 0 5 65278][uf 2 1][uf 4 8 0][uf 0 1 2]Hanged Man[uf 0 1 27]: Obtain one Incense Card at random.[n][uf 1 1][e]

