[msg TRL_000_0_0 [All-Out Attack]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]When you've knocked down every enemy, you'll get the chance to execute an [uf 0 1 2]All-Out Attack[uf 0 1 27] that will deal significant damage to all enemies.[n][uf 1 1][e]

[msg TRL_001_0_0 [All-Out Attack]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Once an All-Out Attack is possible, there will be a prompt asking whether or not you want to initiate it. Press [uf 1 3 999] to cancel and [uf 1 3 998] to perform an All-Out Attack. Choose wisely depending on the situation.[n][uf 1 1][e]

[msg TRL_002_0_0 [All-Out Attack]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you are afflicted with a status ailment, or if you are the only one mobile at the time, then an All-Out Attack cannot be executed.[n][uf 1 1][e]

[msg TRL_003_0_0 [All-Out Attack]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If any party member is afflicted with a status ailment at the time of an All-Out Attack, they will not be able to join in. This will reduce the amount of damage dealt to enemies.[n][uf 1 1][e]

