[msg TRL_000_0_0 [Weaknesses and 1 More]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Each skill and attack has an [uf 0 1 2]affinity[uf 0 1 27], and enemies will have weaknesses towards certain affinities.[n][uf 1 1][e]

[msg TRL_000_1_0 [Weaknesses and 1 More]]
[uf 0 5 65278][uf 2 1][uf 4 8 3]Attacking an enemy with its weakness will deal more damage than usual. It will also knock down the enemy.[n][uf 1 1][e]

[msg TRL_001_0_0 [Weaknesses and 1 More]]
[uf 0 5 65278][uf 2 1][uf 4 8 4]When an enemy is down, you'll be able to attack [uf 0 1 2]1 More[uf 0 1 27] time.[n][uf 1 1][e]

[msg TRL_002_0_0 [Weaknesses and 1 More]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you use this extra turn to knock down a different enemy, you can attack 1 More time again. As long as you keep knocking the enemies down, you'll be able to attack continuously.[n][uf 1 1][e]

