[msg MSG_705_100 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 5 65535 50 0 0][uf 3 1 1 0 2 1 0 6]Its Arcana is Justice... No, wait, it's Chariot...? Wh-What...?[n][uf 1 1][e]

[msg MSG_705_110 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 2 0 6]I only see one enemy, but I'm sensing two of them... I've never seen a Shadow like this before![n][uf 1 1][e]

[msg MSG_705_001 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]No way... It split into two!?[n][uf 1 1][e]

[msg MSG_705_200 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 3 0 6]I see now. The turret is Justice, and the larger one is Chariot![n][uf 1 1][e]

[msg MSG_705_210 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 4 0 6]The smaller one seems to have less stamina. Now we can defeat them individually.[n][uf 1 1][e]

[msg MSG_705_002 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]What...!? It revived it...!?[n][uf 1 1][e]

[msg MSG_705_300 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 5 0 6]It looks like both enemies can revive one another. You're going to have to defeat them at the same time.[n][uf 1 1][e]

[msg MSG_705_400 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 6 0 6]That tank's armor... It seems to be much harder than any Shadow so far...[n][uf 1 1][e]

[msg MSG_705_410 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 7 0 6]If only we could sever their link with a stronger attack...[n][uf 1 1][e]

[msg MSG_705_003 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]I, too, request to be enhanced through fusion.[n][uf 1 1][e]

[msg MSG_705_004 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_705_005 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]They've separated again! But our damage is split equally between them![n][uf 1 1][e]

[msg MSG_705_006 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Are you kidding me...? They fused again!?[n][uf 1 1][e]

