[msg MSG_000_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0]Oh, right! I better explain how my Orgia Mode works to you.[n][uf 1 1][e]

[msg MSG_001_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]As you may know, Sister, I can also activate Orgia Mode.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]This ability allows me to temporarily disable my limiters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]As a result, my offensive capabilities will increase significantly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]However, in exchange, I won't be able to receive direct commands.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]And after using Orgia Mode, I'll eventually overheat and briefly become immobile.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]It'll take some time before my systems cool down and become operational again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]So it's best to use it at the most opportune moment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]...That's about it. Should I go over it again?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, can you?[e]
[uf 0 5 65278][uf 2 1]No, I'm good.[e]

[msg MSG_003_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]You can give me the command to activate Orgia Mode once my Theurgy's ready![n][uf 1 1][e]

[msg SYS_004_0_0]
[uf 0 5 65278][uf 2 1]Metis's Neo Orgia Mode is different from Aigis's Orgia Mode.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Metis's version lasts longer than Aigis's. During this duration, there will be no SP or HP consumption to use skills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Once her Orgia Mode ends, Metis will overheat and be rendered immobile among other significant drawbacks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Use it when the time is right for maximum effectiveness.[n][uf 1 1][e]

