[msg MSG_PRF_DUMMY_NAME]
[uf 0 5 65278][uf 2 1]ダミー：ふりがな[n][uf 1 1][e]

[msg MSG_PRF_DUMMY]
[uf 0 5 65278][uf 2 1]ダミーのプロフィール[n][uf 1 1][e]

[msg MSG_PRF_SEES_NAME]
[uf 0 5 65278][uf 2 1]SEES[n][uf 1 1][e]

[msg MSG_PRF_SEES]
[uf 0 5 65278][uf 2 1]Also known as the "Specialized Extracurricular Execution Squad." Officially, it is designated as a school club.[n][uf 1 1][e]

[msg MSG_PRF_YUKARI_NAME]
[uf 0 5 65278][uf 2 1]Yukari Takeba[n][uf 1 1][e]

[msg MSG_PRF_YUKARI]
[uf 0 5 65278][uf 2 1]A second-year classmate at Gekkoukan High School, Class F. A member of the archery team.[n][uf 1 1][e]

[msg MSG_PRF_YUKARI_REVERSE]
[uf 0 5 65278][uf 2 1]A second-year Gekkoukan High School student, Class F. A member of the archery team. Things are a little awkward right now.[n][uf 1 1][e]

[msg MSG_PRF_JUNPEI_NAME]
[uf 0 5 65278][uf 2 1]Junpei Iori[n][uf 1 1][e]

[msg MSG_PRF_JUNPEI]
[uf 0 5 65278][uf 2 1]A second-year classmate at Gekkoukan High School, Class F. Not a member of any club.[n][uf 1 1][e]

[msg MSG_PRF_AKIHIKO_NAME]
[uf 0 5 65278][uf 2 1]Akihiko Sanada[n][uf 1 1][e]

[msg MSG_PRF_AKIHIKO]
[uf 0 5 65278][uf 2 1]A third-year at Gekkoukan, Class C. Captain of the boxing team, undefeated for 16 matches. Has outstanding grades and is very popular with girls.[n][uf 1 1][e]

[msg MSG_PRF_MITSURU_NAME]
[uf 0 5 65278][uf 2 1]Mitsuru Kirijo[n][uf 1 1][e]

[msg MSG_PRF_MITSURU]
[uf 0 5 65278][uf 2 1]A third-year Gekkoukan High School student, Class D. A member of the fencing team. Also the student council president.[n][uf 1 1][e]

[msg MSG_PRF_FUKA_NAME]
[uf 0 5 65278][uf 2 1]Fuuka Yamagishi[n][uf 1 1][e]

[msg MSG_PRF_FUKA]
[uf 0 5 65278][uf 2 1]A second-year Gekkoukan High School student, Class E. A member of the art club. A somewhat shy and introverted girl.[n][uf 1 1][e]

[msg MSG_PRF_KEN_NAME]
[uf 0 5 65278][uf 2 1]Ken Amada[n][uf 1 1][e]

[msg MSG_PRF_KEN]
[uf 0 5 65278][uf 2 1]A fifth grader at Gekkoukan Elementary School. Since his mother died in an accident two years ago, he has been living at the school dormitories.[n][uf 1 1][e]

[msg MSG_PRF_KOROMARU_NAME]
[uf 0 5 65278][uf 2 1]Koromaru[n][uf 1 1][e]

[msg MSG_PRF_KOROMARU]
[uf 0 5 65278][uf 2 1]An albino Shiba Inu with white fur and red eyes. He was formerly owned by the priest at Naganaki Shrine.[n][uf 1 1][e]

[msg MSG_PRF_SHINJIRO_NAME]
[uf 0 5 65278][uf 2 1]Shinjiro Aragaki[n][uf 1 1][e]

[msg MSG_PRF_SHINJIRO]
[uf 0 5 65278][uf 2 1]A third-year Gekkoukan High School student, Class C. One of the original members of SEES and an old friend of Akihiko Sanada.[n][uf 1 1][e]

[msg MSG_PRF_AEGIS_NAME]
[uf 0 5 65278][uf 2 1]Aigis[n][uf 1 1][e]

[msg MSG_PRF_AEGIS]
[uf 0 5 65278][uf 2 1]An anti-Shadow weapon created by the Kirijo Group. She's labeled as a seventh-generation model, and has a Plume of Dusk implanted within her.[n][uf 1 1][e]

[msg MSG_PRF_TOMOCHIKA_NAME]
[uf 0 5 65278][uf 2 1]Kenji Tomochika[n][uf 1 1][e]

[msg MSG_PRF_TOMOCHIKA]
[uf 0 5 65278][uf 2 1]A second-year classmate at Gekkoukan, Class F. A cheerful student with a thing for older women.[n][uf 1 1][e]

[msg MSG_PRF_ODAGIRI_NAME]
[uf 0 5 65278][uf 2 1]Hidetoshi Odagiri[n][uf 1 1][e]

[msg MSG_PRF_ODAGIRI]
[uf 0 5 65278][uf 2 1]A second-year at Gekkoukan. Member of the student council's disciplinary committee. Not very popular with the other students.[n][uf 1 1][e]

[msg MSG_PRF_BUNKICHI_NAME]
[uf 0 5 65278][uf 2 1]Bunkichi Kitamura[n][uf 1 1][e]

[msg MSG_PRF_BUNKICHI]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with his wife at the Iwatodai strip mall. Turned 80 years old this year. Has a great relationship with his wife.[n][uf 1 1][e]

[msg MSG_PRF_BUN_MISSING]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with his wife at the Iwatodai strip mall. Turned 80 years old this year. He went missing recently...[n][uf 1 1][e]

[msg MSG_PRF_BUN_LOST]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with his wife at the Iwatodai strip mall. Turned 80 years old this year. He's gone missing...[n][uf 1 1][e]

[msg MSG_PRF_MITSUKO_NAME]
[uf 0 5 65278][uf 2 1]Mitsuko Kitamura[n][uf 1 1][e]

[msg MSG_PRF_MITSUKO]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with her husband at the Iwatodai strip mall. Turned 72 years old this year.[n][uf 1 1][e]

[msg MSG_PRF_MIT_MISSING]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with her husband at the Iwatodai strip mall. Turned 72 years old this year. Her husband has gone missing...[n][uf 1 1][e]

[msg MSG_PRF_MIT_LOST]
[uf 0 5 65278][uf 2 1]Runs the bookstore Bookworms with her husband at the Iwatodai strip mall. Turned 72 years old this year. The store is quiet without her husband...[n][uf 1 1][e]

[msg MSG_PRF_MIYAMOTO_NAME]
[uf 0 5 65278][uf 2 1]Kazushi Miyamoto[n][uf 1 1][e]

[msg MSG_PRF_MIYAMOTO]
[uf 0 5 65278][uf 2 1]A second-year classmate at Gekkoukan High School, Class F. Fellow track team member and candidate for team captain.[n][uf 1 1][e]

[msg MSG_PRF_FUSIMI_NAME]
[uf 0 5 65278][uf 2 1]Chihiro Fushimi[n][uf 1 1][e]

[msg MSG_PRF_FUSIMI]
[uf 0 5 65278][uf 2 1]A first-year Gekkoukan High School student. She was appointed to the student council as treasurer, but she's not very good at math.[n][uf 1 1][e]

[msg MSG_PRF_FUSIMI_REVERSE]
[uf 0 5 65278][uf 2 1]A first-year Gekkoukan High School student. She was appointed to the student council as treasurer. Things are a little awkward right now.[n][uf 1 1][e]

[msg MSG_PRF_INTERNET_NAME]
[uf 0 5 65278][uf 2 1]Maya[n][uf 1 1][e]

[msg MSG_PRF_INTERNET]
[uf 0 5 65278][uf 2 1]A friend from the game Innocent Sin Online. Her avatar is a woman garbed in red.[n][uf 1 1][e]

[msg MSG_PRF_HIRAGA_NAME]
[uf 0 5 65278][uf 2 1]Keisuke Hiraga[n][uf 1 1][e]

[msg MSG_PRF_HIRAGA]
[uf 0 5 65278][uf 2 1]A third-year Gekkoukan High School student. President of the art club. He's very well-versed in medical knowledge.[n][uf 1 1][e]

[msg MSG_PRF_NISHIWAKI_NAME]
[uf 0 5 65278][uf 2 1]Yuko Nishiwaki[n][uf 1 1][e]

[msg MSG_PRF_NISHIWAKI]
[uf 0 5 65278][uf 2 1]A second-year Gekkoukan High School student. Manager of the track team. Childhood friends with Kazushi Miyamoto.[n][uf 1 1][e]

[msg MSG_PRF_MAIKO_NAME]
[uf 0 5 65278][uf 2 1]Maiko Oohashi[n][uf 1 1][e]

[msg MSG_PRF_MAIKO]
[uf 0 5 65278][uf 2 1]An elementary school girl encountered at Naganaki Shrine. Both her parents work, so she usually spends time after school alone.[n][uf 1 1][e]

[msg MSG_PRF_MAIKO_MISSING]
[uf 0 5 65278][uf 2 1]An elementary school girl encountered at Naganaki Shrine. She usually spends time at the shrine after school, but she seems to have disappeared...[n][uf 1 1][e]

[msg MSG_PRF_MAIKO_LOST]
[uf 0 5 65278][uf 2 1]An elementary school girl encountered at Naganaki Shrine. She usually spends time at the shrine after school, but she seems to have gone missing...[n][uf 1 1][e]

[msg MSG_PRF_PHAROS_NAME]
[uf 0 5 65278][uf 2 1]Pharos[n][uf 1 1][e]

[msg MSG_PRF_PHAROS]
[uf 0 5 65278][uf 2 1]A boy that often appears before [uf 4 3], leaving behind cryptic messages.[n][uf 1 1][e]

[msg MSG_PRF_BEBE_NAME]
[uf 0 5 65278][uf 2 1]Bebe[n][uf 1 1][e]

[msg MSG_PRF_BEBE]
[uf 0 5 65278][uf 2 1]An exchange student from France who loves Japan. A member of the fashion club. His full name is André Laurent Jean Geraux.[n][uf 1 1][e]

[msg MSG_PRF_TANAKA_NAME]
[uf 0 5 65278][uf 2 1]President Tanaka[n][uf 1 1][e]

[msg MSG_PRF_TANAKA]
[uf 0 5 65278][uf 2 1]Known for personally standing before the camera to promote products on his telemarketing program. President of Tanaka's Amazing Commodities.[n][uf 1 1][e]

[msg MSG_PRF_MUTATSU_NAME]
[uf 0 5 65278][uf 2 1]Mutatsu[n][uf 1 1][e]

[msg MSG_PRF_MUTATSU]
[uf 0 5 65278][uf 2 1]A rather boorish monk encountered in Club Escapade. Loves alcohol and cigars.[n][uf 1 1][e]

[msg MSG_PRF_HAYASE_NAME]
[uf 0 5 65278][uf 2 1]Mamoru Hayase[n][uf 1 1][e]

[msg MSG_PRF_HAYASE]
[uf 0 5 65278][uf 2 1]The ace of a track team from another school who entered the Myouou Cup. He is a well-known runner with a special talent for speed eating.[n][uf 1 1][e]

[msg MSG_PRF_SUEMITSU_NAME]
[uf 0 5 65278][uf 2 1]Nozomi Suemitsu[n][uf 1 1][e]

[msg MSG_PRF_SUEMITSU]
[uf 0 5 65278][uf 2 1]A third-year at Gekkoukan known as the Gourmet King. Has a never-ending appetite and knowledge of every local dish—even items on secret menus.[n][uf 1 1][e]

[msg MSG_PRF_KAMIKI_NAME]
[uf 0 5 65278][uf 2 1]Akinari Kamiki[n][uf 1 1][e]

[msg MSG_PRF_KAMIKI]
[uf 0 5 65278][uf 2 1]A young man who usually sits at the benches at Naganaki Shrine. He appears to have a terminal illness. Acquainted with Maiko Oohashi.[n][uf 1 1][e]

[msg MSG_PRF_SEES2_NAME]
[uf 0 5 65278][uf 2 1]Nyx Annihilation Team[n][uf 1 1][e]

[msg MSG_PRF_SEES2]
[uf 0 5 65278][uf 2 1]The former SEES members who are standing to oppose Nyx, with [uf 4 3] as their leader.[n][uf 1 1][e]

