[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]01/15/2010 18:29:08[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It's the third floor lounge.[n]Koromaru's looking this way.[n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 1 0 0]Ruff![n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Speaking of, career counseling is coming up.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Yeah. What are we even supposed to talk about the whole time?[n][uf 1 1][e]

[msg MSG_005_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 4 0 0]Woof![n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 10 0 0][uf 3 1 1 0 0 5 0 0]Oh, Koro-chan.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 10 0 0][uf 3 1 1 0 0 6 0 0]You're gonna get sick if you go sleeping anywhere you want, you know.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 0 0 0 7 0 0]Hm?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 10 0 0][uf 3 1 1 0 0 8 0 0]What's up, Aigis?[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 9 0 0]There's a miniature camera near the ceiling. It's been camouflaged.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 10 0 0][uf 3 1 0 0 0 10 0 0]Wha!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 10 0 0][uf 3 1 1 0 0 11 0 0]So it's been recording everyone who walks past here?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 10 0 0][uf 3 1 1 0 0 12 0 0]Oh, yeah... I forgot you can see anywhere in the dorm from the command room.[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 13 0 0]Does that mean one has been placed in each of our rooms as well?[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 10 0 0][uf 3 1 1 0 0 14 0 0]I-I never thought about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 10 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 3 25 25]But... I think it might. I did use the system last year.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 10 0 0][uf 3 1 1 0 0 16 0 0]Huh!? I-Is that true!?[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 10 0 0][uf 3 1 1 0 0 17 0 0]W-Well, you need a key to use it, and I doubt any of the guys would have the guts to look in our rooms.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 10 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 10 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 2 25 25]If they did, Nyx can wait. I'll tear them apart first![n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 20 0 0]Are you experiencing the psychological breakdown known as "dying of shame"?[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 10 0 0][uf 3 1 1 0 0 21 0 0]A-Anyway, we don't need that stupid system anymore! Let's ask Mitsuru-senpai to have it removed![n][uf 1 1][e]

[msg MSG_020_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 6 10 0 0][uf 3 1 1 0 0 22 0 0]Woof![n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 23 0 0]Yes, that's right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 24 0 0]The camera's recording right now.[n][uf 1 1][e]

[msg MSG_021_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 10 0 0][uf 3 1 1 0 0 25 0 0]Yoo-hoo.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

