[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 2 0 0]Is it... over?[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0]The operation is over. Or should I say, "Mission complete."[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Yes... It's finally over.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 6 0 0]I believe a celebration is in order.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]What will be our victory cheer?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Hip hip hooray![e]
[uf 0 5 65278][uf 2 1]Let's eat![e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]One... Two... Three... Hip hip hooray![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Hip... hip hooray...?[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 10 0 0]Hip hip hooray![n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Hip hip hooray![n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 12 0 0]One... Two... Three... Let's eat![n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 13 0 0]Let's... eat?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 14 0 0]Haha! What was that!?[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 1 0 0 15 0 0]Huh. I wonder if Aigis-san can even get hungry...[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Sooo, Kirijo-senpai... You're gonna help us with the victory party tomorrow, right?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 17 0 0]You certainly don't waste any time. Well, I do suppose we've earned it.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Well, in that case, how 'bout sushi!?[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Sushi, huh... It has been a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 20 0 0]Well, I've got dibs on the halibut and sea urchin![n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, uh, then I call the fatty tuna![n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 22 0 0]O-Oh, we're divvying it up already? Um, can I get the salmon roe then?[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Hey, wait a minute... You can't do that![n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 52 65535 0 0][uf 3 1 1 0 0 24 0 0]I reserve the fatty tuna, bluefin, shrimp, squid, scallops... and sea eel.[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Hey! That's not fair! You don't even eat![n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 26 0 0]How immature, fighting over sushi...[n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Woof![n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Mitsuru-san, please order tamago for me. They say you can tell a chef's skill by how he prepares eggs.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 29 0 0]A chef's skill? Geez, how old are you again?[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Okay, okay. I'll have the very best delivered tomorrow.[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 31 0 0]You mean it!? Aw man, I'm so glad I'm still alive![n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 32 0 0]Junpei, you can have the leftover dried gourd roll.[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 33 0 0]What!? But it was my idea in the first place![n][uf 1 1][e]

[msg MSG_031_0_0 [（ＳＥ）伊織 順平]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0]くうう～！[n][uf 1 1][e]

[msg MSG_032_0_0 [（ＳＥ）岳羽 ゆかり]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]あはははっ！[n][uf 1 1][e]

[msg MSG_033_0_0 [（ＳＥ）山岸 風花]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]ふふふっ！[n][uf 1 1][e]

[msg MSG_034_0_0 [（ＳＥ）真田 明彦]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]ははは…[n][uf 1 1][e]

[msg MSG_035_0_0 [（ＳＥ）桐条 美鶴]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0]フフッ…[n][uf 1 1][e]

[msg MSG_036_0_0 [（ＳＥ）天田 乾]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0]へへっ…[n][uf 1 1][e]

[msg MSG_037_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 40 0 0]...I guess it's time to say goodbye to the Dark Hour.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 41 0 0]Even though it seemed like a curse, for some reason I feel sad to see it go.[n][uf 1 1][e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 42 0 0]Yeah...[n][uf 1 1][e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 43 0 0]We really did it, didn't we...?[n][uf 1 1][e]

[msg MSG_040_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 44 0 0]Yes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 45 0 0]We've saved the world, even if no one knows it.[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 46 0 0]...Yeah.[n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The battle has ended.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The Dark Hour has come to an end...[n][uf 1 1][e]

