[msg MSG_000_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 1 0 0]Good morning. This is Elizabeth.[n][uf 1 1][e]

[msg MSG_001_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 2 0 0]There is something I wish to discuss with you, so please come to the Velvet Room posthaste.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 3 0 0]I believe this matter is of great import to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 4 0 0]I shall be anticipating your arrival.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Elizabeth wants to tell me something.[n]What could be so important?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should go to the Velvet[n]Room after school...[n][uf 1 1][e]

[msg MSG_003_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 5 0 0]Good morning. This is Elizabeth.[n][uf 1 1][e]

[msg MSG_004_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 6 0 0]I am calling to inform you that more humans have wandered into Tartarus.[n][uf 1 1][e]

[msg MSG_035_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 2 4 1] this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_036_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 8 0 0]Goodbye, now.[n][uf 1 1][e]

[msg MSG_004_1_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 9 0 0]One this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_004_2_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 10 0 0]Two this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_004_3_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 11 0 0]Three this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_004_4_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 12 0 0]Four this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_004_5_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 13 0 0]Five this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]

[msg MSG_005_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 14 0 0]Good morning. This is Elizabeth.[n][uf 1 1][e]

[msg MSG_006_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 15 0 0]I am calling to inform you that more humans have wandered into Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 16 0 0]One this time, I believe. Please swiftly and safely conduct a search and rescue.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 17 0 0]This time in particular, I believe this human is an [uf 0 1 2]acquaintance of yours[uf 0 1 27]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 18 0 0]Goodbye, now.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]It seems that someone[n]I know is lost in Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I don't save them, the consequences[n]could be [uf 0 1 2]irreversible[uf 0 1 27]...[n][uf 1 1][e]

[msg MSG_008_0_0 [Voice on the Phone]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 19 0 0]Good morning. This is Elizabeth.[n][uf 1 1][e]

[msg MSG_009_0_0 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 20 0 0]I am calling to inform you that more humans have wandered into Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 21 0 0][uf 2 4 1] this time, I believe, and there seems to be [uf 0 1 2]an acquaintance of yours[uf 0 1 27] among them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 22 0 0]I suggest you carry out a rescue posthaste.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 90 65535 68 0 0][uf 3 1 1 0 0 23 0 0]Goodbye, now.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]It seems that someone[n]I know is lost in Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I don't save them, the consequences[n]could be [uf 0 1 2]irreversible[uf 0 1 27]...[n][uf 1 1][e]

