[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I'm in Shinagawa Dungeon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maya isn't in the area...[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]A mysterious light engulfs Tatsuya![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Shinagawa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A gray-colored sky stretches[n]as far as the eye can see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A barren wasteland lies before me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maya is staring into the distance...[n][uf 1 1][e]

[msg MSG_002_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]i saw u log on so i brought u here w/ magic. sry ^^;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]...i should apologize[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]About what?[e]
[uf 0 5 65278][uf 2 1]Oh, no worries.[e]

[msg MSG_004_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]about, uh... all that stuff i said? o_O;;[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Maya seems troubled.[n][uf 1 1][e]

[msg MSG_006_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0][uf 5 13 10 5 1]no tatsuya, if u keep being nice i won't ever move fwd =S[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Maya seems a little happier.[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]remember how i said i would send our chat log to the admins before? ＞_＞[n][uf 1 1][e]

[msg MSG_009_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]i dun think i will...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Now they'll end it for sure.[e]
[uf 0 5 65278][uf 2 1]Is that why you're sorry?[e]

[msg MSG_011_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]......yeah pretty much huh -_-[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Maya seems genuinely sorry.[n][uf 1 1][e]

[msg MSG_013_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0][uf 5 13 10 5 1]kinda, but... i meant sumthing else too ._.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Maya seems nervous.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]She's fidgeting in the sand with her feet...[n][uf 1 1][e]

[msg MSG_016_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0]i read over our chat log and i didnt like waht i saw =/[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]what kind fo person plays an MMO jus to bitch about coworkers? -_-[n][uf 1 1][e]

[msg MSG_017_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]u shouldnt have had to put up w/ me doin that. im sry m(_ _)m[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]sum teacher i am, rite? =/[n][uf 1 1][e]

[msg MSG_018_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]i kno it'll look like i'm chickening out an stuff, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]im thinkin bout quittin the MMO today. i... dun think i'll c u again T_T[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]This is sudden...[e]
[uf 0 5 65278][uf 2 1]I'll miss you.[e]

[msg MSG_020_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]yea... sry, i kno ive never been gud w/ this kind of thing...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Maya seems sad.[n][uf 1 1][e]

[msg MSG_022_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0][uf 5 13 10 15 1]i'll totally miss u more *^_^*[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Maya seems happy.[n][uf 1 1][e]

[msg MSG_024_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]since no1 can see my face on teh intarwebs, i said some p mean stuff... ^^;[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]so i jus have to look @ myself in the mirror and make it rite! ^_^[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]shyeah rite. =P i never woulda figured this out w/out ur help[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]tatsuya taught me to be thoughtful even when im not around ppl =)[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Maya really trusts me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg SYS_026_0_0]
[uf 0 5 65278][uf 2 1]The Hermit Social Link reached its maximum level! You can now fuse [uf 0 1 35]Arahabaki[uf 0 1 27], the aboriginal god![n][uf 1 1][e]

[msg MSG_027_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]...well, i better go now ._.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i drew something in the sand for u[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]check the ground once i log off, k? :3[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]its kinda embarrassing, but i worked hard on it~[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]if u upload a screenie to ur cellphone, u can keep it always! ^^[n][uf 1 1][e]

[msg MSG_028_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17003 0 0][uf 4 25 107]......... ._.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]i dun ever cry during romance movies but my eyes'll be red tonite... T_T[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]remember, lets think positive! ...gg, tatsu. thx 4 everything[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Maya's player signed off...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I looked at the area where[n]Maya was standing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A message is written in the sand...[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]i ＜--read downward!![n]luv[n]u[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]I sent the screencap to my phone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]After taking a moment to reminisce on my[n]memories with Maya, I logged off the game.[n][uf 1 1][e]

