[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 1 0 0]These readings I've been getting... There's no other possibility...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 2 0 0]It could only be...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 50 0 0][uf 3 1 1 0 0 3 0 0]But... It can't be...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 4 0 0]Sorry! I didn't mean to distract you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 52 50 0 0][uf 3 1 1 0 0 5 0 0]Shadows approaching![n][uf 1 1][e]

