[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 155 65535 0 0][uf 3 1 1 0 4 1 0 0]...Anyway, my friends and I are really into the dessert they serve at the café there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 155 65535 0 0][uf 3 1 1 0 4 2 0 0]Oh! Do you wanna come with us after school sometime, Mitsuru-senpai?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 155 65535 0 0][uf 3 1 1 0 4 3 0 0]Yes, of course.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 155 65535 0 0][uf 3 1 1 0 4 4 0 0]I'd like to try this "special strawberry parfait" you mentioned.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 155 65535 0 0][uf 3 1 1 0 4 5 0 0]Okay, cool! It's a date, then![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 155 65535 0 0][uf 3 1 1 0 4 6 0 0]If you have any other recommendations, I'd love to hear them, Yukari.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 155 65535 0 0][uf 3 1 1 0 4 7 0 0]Oh, there's this new place one city over.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 155 65535 0 0][uf 3 1 1 0 4 8 0 0]If you have any other recommendations, I'd love to hear them, Yukari.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 155 65535 0 0][uf 3 1 1 0 4 9 0 0]Hm... Oh, there's this new place one city over.[n][uf 1 1][e]

