[msg MSG_000_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11801 0 0]I have been waiting, [uf 4 2]-dono![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Let us be off to the home economics room![n][uf 1 1][e]

[msg MSG_001_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11878 0 0]Ahhh, [uf 4 2]-dono...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Will you be joining me today? There is something I must tell you...[n][uf 1 1][e]

[msg MSG_002_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Ah, [uf 4 2]-dono. What are your plans for today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]If you are not busy, then please do come to the home economics room.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_005_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11834 0 0]Sewing is such fun! And I shall sew to my heart's content![n][uf 1 1][e]

[msg MSG_006_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11849 0 0]Many, many thanks... And now, away we go![n][uf 1 1][e]

[msg MSG_007_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11902 0 0]Oh... Then, I shall be all alone today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11898 0 0]I understand...[n][uf 1 1][e]

[msg MSG_009_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Now, let us make our way to the home economics room![n][uf 1 1][e]

[msg MSG_010_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Ah, yes... Will you be coming today? There is something I must tell you.[n][uf 1 1][e]

[msg MSG_011_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Ah, yes... What are you doing today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]If you are not busy, then please do come to the home economics room.[n][uf 1 1][e]

[msg MSG_012_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11805 0 0]Oh, [uf 4 2]-dono! Exams have come to an end.[n][uf 1 1][e]

[msg MSG_013_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11811 0 0]Ahhh, [uf 4 2]-dono... Exams have come to an end, at long last.[n][uf 1 1][e]

[msg MSG_014_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]We both fought hard... Now my brain is exhausted.[n][uf 1 1][e]

[msg MSG_015_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]We both fought an intense battle... Now my brain is exhausted.[n][uf 1 1][e]

[msg MSG_016_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11812 0 0]I have been waiting, [uf 4 2]-dono![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Let us be off to the home economics room![n][uf 1 1][e]

[msg MSG_016_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Now then, let us be off to the home economics room![n][uf 1 1][e]

[msg MSG_017_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]Sewing is such fun! And I shall sew to my heart's content![n][uf 1 1][e]

[msg MSG_018_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11802 0 0]Oh, [uf 4 2]-dono! How do you do?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]If you have the time to spare, would you care to join me for sewing?[n][uf 1 1][e]

[msg MSG_018_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]By the way, how do you do?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]If you have the time to spare, would you care to join me for sewing?[n][uf 1 1][e]

[msg MSG_019_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]Many thanks—katajikenai![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]You have a great sense for sewing, [uf 4 2]-dono. Please do show me more of your skills today![n][uf 1 1][e]

[msg MSG_020_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11887 0 0]Oh, [uf 4 2]-dono...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Are you now departing for home? Or will you come to the home economics room?[n][uf 1 1][e]

[msg MSG_020_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Now then, are you departing for home? Or will you come to the home economics room?[n][uf 1 1][e]

[msg MSG_021_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]At times like these, I must sew... Let us continue where we left off.[n][uf 1 1][e]

[msg MSG_022_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11808 0 0]Greetings, [uf 4 2]-dono.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]I humbly request you join me in the fashion club![n][uf 1 1][e]

[msg MSG_022_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Now then, I humbly request you join me in the fashion club![n][uf 1 1][e]

[msg MSG_023_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11882 0 0]Ohhh, then off we go! To the home economics room![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Your skills continue to flourish, but I shall not be outdone...[n][uf 1 1][e]

[msg MSG_024_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11802 0 0]I have been waiting for you, [uf 4 2]-dono![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]It seems the threads of fate have brought us together. Could you spare some time to talk?[n][uf 1 1][e]

[msg MSG_024_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 4 2]-dono! It seems the threads of fate have brought us together. Could you spare some time to talk?[n][uf 1 1][e]

[msg MSG_025_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11897 0 0]Oh, joyous day! Then let us speak, with a sewing machine in one hand![n][uf 1 1][e]

[msg MSG_026_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11805 0 0][uf 4 2]-dono, are you busy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]To master the way of the kimono, I have need of your strength![n][uf 1 1][e]

[msg MSG_026_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 4 2]-dono, are you busy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]To master the way of the kimono, I have need of your strength![n][uf 1 1][e]

[msg MSG_027_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]Katajikenai, I am eternally grateful! Then today, I shall sew as I have never sewed before![n][uf 1 1][e]

[msg MSG_028_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11812 0 0]Oh! Salutations upon you, [uf 4 2]-dono.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Rest assured, I shall create the ultimate kimono, but there is still more work to be done...[n][uf 1 1][e]

[msg MSG_028_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Rest assured, I shall create the ultimate kimono, but there is still more work to be done...[n][uf 1 1][e]

[msg MSG_029_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11908 0 0]Oh, happy day! I do not know what to say! Let us hurry to the home economics room![n][uf 1 1][e]

[msg MSG_030_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11809 0 0]Ahhh, [uf 4 2]-dono![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]It is the final countdown. Today, my project shall be completed![n][uf 1 1][e]

[msg MSG_030_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]It is the final countdown. Today, my kimono shall be completed![n][uf 1 1][e]

[msg MSG_031_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11847 0 0]Katajikenai, you have my thanks! Now... to finish this![n][uf 1 1][e]

[msg MSG_032_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_033_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Oh, is that so...? Then, please, do join me another time.[n][uf 1 1][e]

[msg MSG_034_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]How unfortunate... But I understand.[n][uf 1 1][e]

[msg MSG_035_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]...I understand.[n][uf 1 1][e]

[msg MSG_036_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]If you already have plans, then there is nothing to be done...[n][uf 1 1][e]

[msg MSG_037_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Oh no... Then I shall ask another time.[n][uf 1 1][e]

[msg MSG_038_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Ngh... Then that leaves me with no choice, but to wait.[n][uf 1 1][e]

[msg MSG_039_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Oh, I see... I shall wait for another time, then.[n][uf 1 1][e]

[msg MSG_040_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Oh, is that so...? Then I shall be patient today.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Bebe]]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I still spend time with them...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Should I spend the day[n]with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Should I spend time online playing[n]the MMORPG with [uf 2 4 0]...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Should I spend the evening[n]with [uf 2 4 0]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Spend time with [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with the [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Should I spend the day at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Should I spend the night[n]with [uf 2 4 1]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Spend time w/ [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Enter the bookstore[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, right. There's something else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

