[msg MSG_000_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 1 17 0]Oh, [uf 4 1]. I was just looking for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 2 17 0]This came for you. It's from Hayase.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 3 17 0]I bet his school is sorry he's gone. He was a heck of an athlete.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 4 17 0]But it's good news for us. Now there's nothing standing between us and total victory![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 5 17 0]Well, I'll see you around.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I received a letter from Hayase.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I better read it.[n][uf 1 1][e]

