[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6061 0 0]It's been a while since I last came to school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I know this isn't exactly the best situation, but... I have a new outlook on so many things.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...Um, [uf 4 2]-san, do you have any plans after school today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6002 0 0]If you don't mind... I would like to walk home with you.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Oh, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]Do you have any plans after school?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6002 0 0]If you don't mind... I would like to walk home with you.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Walk home with her[e]
[uf 0 5 65278][uf 2 1]Don't go with her[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6114 0 0]Thank you...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Oh, but there is one place I would like to visit before returning to the dorm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]...Shall we go?[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6123 0 0]Oh... That's too bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Well... I'll see you back at the dorm, then.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6002 0 0]Um, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...I want to be by your side.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Aigis is gazing directly into my eyes...[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6072 0 0]Oh, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Do you have time to talk today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Although, I'm not sure if I can communicate this properly...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school with Aigis?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Spend time with her[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Not now[e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you very much. Shall we go, then?[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you very much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...U-Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 1 0]I would like to... show you my room.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 1 0]I would like you to see how I live, and... Um...[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go to Aigis's room.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6123 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Well then... please take care.[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6101 0 0]Um, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm going to do my best...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]I want to be with you. I want to live by your side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6110 0 0]So, please...[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with Aigis...[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6101 0 0]Ah, [uf 4 2]-san. Are you heading home?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]I have a favor to ask. It's something I can't do alone...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Oh, thank you so much![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]Let's return to the dorm, then. I can hardly wait.[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6123 0 0]Oh, I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Um, maybe next time...[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6101 0 0]Ah, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm going to do my best.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]I want to stay by your side and make all kinds of memories together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6110 0 0]So, don't worry...[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with Aigis...[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Hello, [uf 4 2]-san. The weather is lovely today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]...If you don't mind, I'd like to walk home with you again.[n][uf 1 1][e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Um... Before we leave, could we take a slight detour? I want to go to the roof.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Oh, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]Are you leaving already? Then I'll come with you...[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]It's cold out, so we should head straight home. Let's see, when is the next train...?[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6020 0 0][uf 4 2]-san... Are you going home for today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]If you don't mind, I'd like to stop by somewhere with you on the way back...[n][uf 1 1][e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Oh, thank you so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Does Paulownia Mall work? I know everyone always hangs out there.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6075 0 0]I've been continuing my search for Mii-chan-san, but I haven't had any luck yet...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Anyways, [uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]I would like to walk home with you again. Is that okay?[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Today is another cold day. Let's hurry before it gets dark.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Oh, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I would like to walk home with you again today. Would you mind?[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you so much![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]Could we go to the strip mall? I really enjoy how lively it is there...[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6010 0 0]...[uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Oh, I'm sorry. Do you mind if I accompany you again today?[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6038 0 0]...Thank you so much.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Could we go for a walk today? I'd like to observe people somewhere busy.[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6067 0 0]Oh, [uf 4 2]-san. Today feels a little warmer than usual.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Are you leaving? If you don't mind, could we go to the roof...?[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]...Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Shall we go, then?[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6005 0 0][uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]I need to speak with you right now, if possible...[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]...Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]Do you mind if we go to the roof? I think the view will be nice today.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6005 0 0][uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]I have a favor to ask... Could you hear me out?[n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]...Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Do you mind if we go to the roof? I think the view will be nice today.[n][uf 1 1][e]

[msg MSG_098_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_099_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_100_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_101_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6026 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I will see you at the dorm, then. Please take care.[n][uf 1 1][e]

[msg MSG_102_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6026 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 10 65535 65535 0 0]...Never mind, it's nothing. Please take care.[n][uf 1 1][e]

[msg MSG_103_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6026 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 10 65535 65535 0 0][uf 4 25 7]......[n][uf 1 1][e]

[msg MSG_104_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6026 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm sorry for imposing. I'll see you back at the dorm.[n][uf 1 1][e]

[msg MSG_105_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6026 0 0]Oh... I-I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Sorry for being so sudden. Please take care.[n][uf 1 1][e]

[msg MSG_106_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6089 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]I hope there will be another opportunity in the future, then.[n][uf 1 1][e]

[msg MSG_107_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]...I see. I understand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]I'm sure you must be busy. Please take care.[n][uf 1 1][e]

[msg MSG_108_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0]I hope we'll have another chance in the future, then.[n][uf 1 1][e]

[msg MSG_109_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6131 0 0]You can always rely on me. No matter what happens, I will help you in any way that I can.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]I feel as if we can grow closer thanks to the[n][uf 2 4 2] Persona, [uf 0 1 35][uf 2 4 5][uf 0 1 27]...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to [uf 2 4 0] soon...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Aigis]]
[uf 0 5 65278][uf 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I still spend time with them...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Should I spend the day[n]with [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Should I spend time online playing[n]the MMORPG with [uf 2 4 0]...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Should I spend the evening[n]with [uf 2 4 0]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Spend time with [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school with the [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Should I spend some time after[n]school at the fashion club?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Should I spend the day at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Should I spend some time[n]after school at the bookstore?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Should I spend the night[n]with [uf 2 4 1]?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Spend time w/ [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Go to the fashion club[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Enter the bookstore[e]
[uf 0 5 65278][uf 2 1]Check Social Link status[e]
[uf 0 5 65278][uf 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, right. There's something else...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Here, this is from the chairman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Since I placed at the top in the exams,[n]I also got this [uf 4 4 1 37 1 3].[n][uf 1 1][e]

