[msg MSG_000_0_0 [Elderly Man]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 3 0 65535 10424 0 0]Oh, are you a student from a school around here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0]Well, you'll be glad to know you can get some quality sushi close by! I make it right here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0]Drop by sometime if you want! ...Oh, actually, our shop is still under renovation. Sorry.[n][uf 1 1][e]

[msg MSG_004_0_0 [Elderly Woman]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 3 0 65535 10607 0 0]...We are a bookstore, not a sushi restaurant.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0]I'm sorry. He's always like that.[n][uf 1 1][e]

