[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 3 0 65535 5006 0 0]So that's where that reading was coming from!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0]I can't make sense of this data. It's powerful, but somehow faint... It's like he's not actually here.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 3 0 65535 5091 0 0]He's going to attack! Aigis, get ready![n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 17 6 4 1][e]

