[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4095 0 0]It's nice to let loose and sing every once in a while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I didn't know you could change the song's key with the karaoke machine either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 4 23 0 5 1 25 25]I thought I wouldn't get to sing much since I can't hit any high notes, but thanks to that, I got to sing my fair share of songs.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Oh, look at the time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We ended up spending the entire three hours we paid for.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Even though each song only lasts a few minutes... Well, as they say, time flies when you're having fun.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 3 0 65535 4076 0 0]Should we... head back now?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]I guess we should.[e]
[uf 0 5 65278][uf 2 1]Let's hang out more.[e]
[uf 0 5 65278][uf 2 1]You don't want to?[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Y-You're right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I suppose I ought to set a good example as the student council president and get home before curfew.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 4 23 0 5 3 25 25][uf 4 25 5]......[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems a little disappointed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4097 0 0][uf 5 13 4 15 5]A-All right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Yes, it should be fine as long as we're home before curfew.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 4 23 0 5 1 25 25]Then... shall we walk around a little more?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems rather happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4037 0 0]N-No, that's not what I meant![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 4 23 0 5 3 25 25]It's just that...[n][uf 1 1][e]

[msg MSG_009_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]How should I say this...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]

[msg MSG_009_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 5 13 4 30 5]It's no big deal...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 4 23 0 5 1 25 25]I just thought it might be fun to go somewhere else before we head home.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Mitsuru seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Shall we go, then? I need to rejuvenate myself for tomorrow while I can.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]We walked around together for a[n]while before returning to the dorm.[n][uf 1 1][e]

