[msg MSG_000_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]...And that's all for the weather. At the tone, the time will be 12 AM.[n][uf 1 1][e]

[msg MSG_001_0_0 [Newscaster]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]Good evening.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]It is now April 1st. Here are the latest news reports...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Hm? What...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 5 0 0]When did we... fall asleep?[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 6 0 0]Huh? This is the dorm. Is everything back to normal?[n][uf 1 1][e]

[msg MSG_005_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Woof, woof![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Mm... What is it, Koromaru?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 9 0 0]Huh...? What happened?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 10 0 0]Weren't we all by the entrance, talking about a key or something?[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Yeah, we were... But it looks like that's been settled.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Everything outside is back to normal. We're no longer blocked from leaving, either.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 13 0 0]So the Abyss of Time is gone, then.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 1 0 0 14 0 0]The date... It's April 1st![n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 15 0 0]So... It's all over then, right?[n][uf 1 1][e]

[msg MSG_036_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 1 0][e]

[msg MSG_012_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 11 52 65535 0 0][uf 3 1 1 0 0 16 0 0]Aw, hell yeah! About damn time![n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 17 0 0]Hey, Aigis, wake up. We made it out in one piece![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 52 65535 0 0][uf 3 1 1 0 0 18 0 0]Aigis?[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Wait a second...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 1 0 0 20 0 0]After we used the key to open the front door, we ended up in a room that looked like an elevator...[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 1 0 0 21 0 0]And while we were there, Aigis-san...[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 22 0 0]Hey, c'mon, Aigis! You're not gonna lie there forever, are you? Wake up![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Aigis![n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 24 0 0]Kirijo-senpai...[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Let's not jump to conclusions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 26 0 0]We'll take her to her room for now. We can use the equipment there to check on her condition.[n][uf 1 1][e]

