[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 1 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 2 0 0]That dumbass...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Seriously, getting drunk on cooking wine? That's damn pathetic, even for a deadbeat dad.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 4 0 0]But... So am I, I guess, for running out like this every day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Man... What am I gonna do now? I got nowhere to go.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]'Sup, pooch? You got nowhere better to be, either?[n][uf 1 1][e]

[msg MSG_003_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 7 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Sorry, bud, I don't got any food for ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Y'know, you look kinda familiar... Have I seen you 'round here before?[n][uf 1 1][e]

[msg MSG_005_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 3]Yo, it's Junpei![n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Huh...? Oh, hey, guys.[n][uf 1 1][e]

[msg MSG_007_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 3]Aw, why the long face? You sad we're in different homerooms now?[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Nah, only thing sad here is your IQ.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Wait, ain't it way past your dorm's curfew? What're you guys doin' out here?[n][uf 1 1][e]

[msg MSG_009_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 3]Oh, you know, we snuck out. Once you're a second-year, you learn where the secret exit is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 3]Anyway, we're headin' to Escapade to celebrate my guy here finally striking out. Wanna come with?[n][uf 1 1][e]

[msg MSG_010_0_0 [Lovelorn Friend]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 2]Whatever! I still have a shot![n][uf 1 1][e]

[msg MSG_011_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 3]Heh, still in denial, huh? C'mon, face it, man. Yukari Takeba is way out of your league in the first place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 3]I never expected her to hook up with that new transfer student right off the bat, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 3]Guess she's into the dark and mysterious type.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]I dunno, he seemed like a normal dude to me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 3]Nah, man. Get this—that transfer kid? Rumor has it both his parents died when he was younger.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 3]Someone got a peek at his file when Toriumi left it lying around.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Man, you're so gullible... That stuff only happens in soap operas.[n][uf 1 1][e]

[msg MSG_015_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 3]Hey, I did say it was just a rumor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 3]Look, man, forget that—let's get going! I know a guy who knows a guy who can grab us some booze.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Booze...? Uh, sorry, I... think I'm gonna pass.[n][uf 1 1][e]

[msg MSG_017_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 3]What? C'mon! Live a little why don'tcha—[n][uf 1 1][e]

[msg MSG_017_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 2 0][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 6 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 2 25 25]Dude, I already said no! I just... ain't in the mood.[n][uf 1 1][e]

[msg MSG_019_0_0 [Former Classmate]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 3]Well, looks like I'm the only one nursing your broken heart tonight.[n][uf 1 1][e]

[msg MSG_020_0_0 [Lovelorn Friend]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 2]Dude, I'm telling you, I still have a shot![n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 32 0 0]Heh... Just had to turn 'em down. Today's really not my day.[n][uf 1 1][e]

[msg MSG_022_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 0 33 0 0]*whimper*[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Man... Wonder if I'll actually be happy with my life one day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 1 3 25 25]I wish I could like... change the world somehow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 6 65535 0 0][uf 3 1 1 0 0 36 0 0]If only I could do something that no one else can do... Like, having some kinda special skill or power, you know?[n][uf 1 1][e]

[msg MSG_024_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 201 65535 0 0][uf 3 1 1 0 0 37 0 0]*whine*[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 38 0 0]Haha, aw, don't gimme that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 39 0 0]I'm sure someday... Someday we'll be able to make real friends—friends who actually understand us.[n][uf 1 1][e]

[msg MSG_026_0_0 [White Dog]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 40 0 0]Arf![n][uf 1 1][e]

