[msg MSG_000_0_0 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_EXIT_CONFIRM_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 3 1087 0]Done already?[n][uf 1 2 1][e]

[msg MSG_EXIT_CONFIRM_02 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 2 1087 0]You got everything you need?[n][uf 1 2 1][e]

[msg MSG_EXIT_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 1002 1087 0]Thanks![n][uf 1 1][e]

[msg MSG_EXIT_02 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 1003 1087 0]Come again, yeah?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Keep shopping[e]
[uf 0 5 65278][uf 2 1]Exit[e]

[msg MSG_ITEM_TUTORIAL [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16601 1087 0]Welcome![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]The competition between pharmacies is heating up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16624 1087 0]I've got to make my store more unique, or I'll be sunk.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]I'm doing my best to "pill" in the gaps, so drop by anytime and support my store![n][uf 1 1][e]

[msg MSG_ITEM_GREET [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 1000 1087 0]Welcome![n][uf 1 1][e]

[msg MSG_ITEM_GREET_FILLER_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]I won't bother you with my stories. Take your time and browse.[n][uf 1 1][e]

[msg MSG_ITEM_GREET_FILLER_02 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Go on, don't be shy! Have a look around![n][uf 1 1][e]

[msg MSG_ITEM_GREET_SALE [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 3 1000 1087 0]Welcome![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Saturdays are our regular sale days! It's the perfect chance to stock up on supplies![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_00 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16623 1087 0]Gosh, is it sweltering. This kind of heat calls for some Aojiru Sorbet![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]...It's a product I tried pushing once, but it didn't sell. Apparently, people only used it for dares...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]But enough of that! Take your time and do some browsin'![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16617 1087 0]My pharmacy's detoxifier is famous! It sucks the poison outta ya like a healing vacuum cleaner.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Girlfriends' pimples, wives' sharp tongues... It can cure anything![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Got anyone around who won't stop naggin' ya? Give it a try on them! Gahahahah![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_02 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16608 1087 0]You don't want to become overly reliant on meds. Excess can turn tonics into toxins, ya know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Even in an emergency, make sure to follow the instructions on the label, capeesh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Anyway, what catches your eye?[n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_03 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16624 1087 0]Vitamins and mineral water are common shopping items these days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Things like that used to be taken for granted, but not now. Which helps my business, but it's sad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]That's enough of that, though. Take your time and look around![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_04 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16617 1087 0]Back in the good ol' days, every household had an aloe plant for their health.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Thanks to that, I've never been constipated in my life! Gahahah![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16628 1087 0]Enough about me, though. Browse to your heart's content![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_05 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16623 1087 0]I hear more people have been carrying their meds around in pill cases in case they suddenly get sick.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]It's good to be prepared, but we have traditions... Don't people remember what an inro is...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Shoot, listen to me lecturin' you like an old-timer. Forget what I said. Have a look around![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_06 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16614 1087 0]I got this great concoction from Ken-chan, my wholesaler! They say it enhances... Heheheh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Well, not that I have anyone to use it on. Huh... I wonder how she's doing these days...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Whoa, that's not the type of talk for your ears, is it? Anyway, have a look around.[n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_07 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16616 1087 0]Back in the good ol' days, every household had an aloe plant for their health.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Thanks to that, I've never been constipated in my life! Gahahah![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Enough about me, though. Browse to your heart's content![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_08 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16614 1087 0]I hear more people have been carrying their meds around in pill cases in case they suddenly get sick.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]It's good to be prepared, but we have traditions... Don't people remember what an inro is...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16609 1087 0]Shoot, listen to me lecturin' you like an old-timer. Forget what I said. Have a look around![n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_09 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16623 1087 0]I got this great concoction from Ken-chan, my wholesaler! They say it enhances... Heheheh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Well, not that I have anyone to use it on. Huh... I wonder how she's doing these days...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16610 1087 0]Whoa, that's not the type of talk for your ears, is it? Anyway, have a look around.[n][uf 1 1][e]

[msg MSG_ITEM_GREET_TALK_10 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16614 1087 0]This area's getting more dangerous. Someone even broke into our storage basement a bit ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]But I bet he had the scare of a lifetime once he saw what was inside! Heheheh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Now then, peruse away![n][uf 1 1][e]

[msg MND_REQ_AOJIRU_START_00]
[uf 0 5 65278][uf 2 1]Come to think of it, Elizabeth said that[n]she wanted to try some tasty aojiru...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I might be able to find some here...[n][uf 1 1][e]

[msg MSG_REQ_AOJIRU_START_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16602 1087 0]Hey, kid. What can I get you today?[n][uf 1 1][e]

[sel SEL_REQ_AOJIRU_START_02 top]
[uf 0 5 65278][uf 2 1]I'd like some aojiru.[e]
[uf 0 5 65278][uf 2 1]Do you sell aojiru?[e]

[msg MSG_REQ_AOJIRU_START_03 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16624 1087 0]Oh, sorry, I don't have any for sale right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]I used to, but it didn't sell well and was apparently only used for dares...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16609 1087 0]That said... I did recently come up with a new aojiru creation that I consider my magnum opus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]And maybe I'd be willing to exchange it for the [uf 4 4 1 37 1 0] from the antique shop next door...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Haha, I'm joking! That thing's way out of a student's budget.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Sorry, but you'll have to give up on the aojiru. But don't worry, I've got plenty of other fine goods![n][uf 1 1][e]

[msg MSG_REQ_AOJIRU_REMIND_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 4 25 1087]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]That [uf 4 4 1 37 1 0] from next door would really help streamline things...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]But she probably won't sell it to me... What to do...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Whoops, don't mind me. Just talkin' to myself. Take your time and look around![n][uf 1 1][e]

[msg MSG_REQ_AOJIRU_END_01 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16615 1087 0]Hey, kid. What's up? Wait, is that...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]The [uf 4 4 1 37 1 0]! How the hell'd you get your hands on this!?[n][uf 1 1][e]

[sel SEL_REQ_AOJIRU_END_02 top]
[uf 0 5 65278][uf 2 1]I made an exchange for it.[e]
[uf 0 5 65278][uf 2 1]Trade secret.[e]

[msg MSG_REQ_AOJIRU_END_03 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16622 1087 0]Uh, I see... Well, as long as you didn't break any laws, I'm not gonna pry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16625 1087 0]Anyhow, I'm impressed with your dedication. Well, I won't go back on my word... This is yours![n][uf 1 1][e]

[msg MSG_REQ_AOJIRU_END_04 [Aohige Pharmacy Owner]]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16623 1087 0]If you ever want more, just say the word. This isn't for sale, but I'll make an exception for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0]Oh, and I'll be making full use of the [uf 4 4 1 37 0 0] for my future research.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1087 0 65535 65535 0 0][uf 3 1 3 0 65535 16606 1087 0]Bottom line, thanks a ton! You take your time lookin' around, now![n][uf 1 1][e]

