[msg MSG_000_0_0 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_EXIT_CONFIRM_01 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 2 1586 0]Is that all you need?[n][uf 1 2 1][e]

[msg MSG_EXIT_CONFIRM_02 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 3 1586 0]Will that be all?[n][uf 1 2 1][e]

[msg MSG_EXIT_01 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 1002 1586 0]Hope to see you again soon.[n][uf 1 1][e]

[msg MSG_EXIT_02 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 1003 1586 0]Come again.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Keep shopping[e]
[uf 0 5 65278][uf 2 1]Exit[e]

[msg MSG_ANTQ_GREET_FIRST_01 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16801 1586 0]Well, well... You're quite the rare customer. Welcome.[n][uf 1 1][e]

[msg MND_ANTQ_GREET_FIRST_02]
[uf 0 5 65278][uf 2 1]It seems this lady owns the antique shop.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_FIRST_03 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16813 1586 0]Ah... Officer Kurosawa told me about you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 4 25 1586]This is but a humble antique shop... Having said that, I believe I can be of some assistance to you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16820 1586 0]You know what a base model is, right? For crafting weapons, I mean.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_FIRST_04 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]By fusing it with various materials, you can craft special equipment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I can help with the crafting process, but you'll have to collect the required materials yourself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16808 1586 0]These base materials can be found in places that tend to be quite... unwelcoming.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]That's why it'll be up to you to collect them.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_FIRST_05 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16817 1586 0]Also, if you find any gems or the like, I'd be willing to exchange them for some of my wares here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Well then, go ahead and have a gander.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_00 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 1001 1586 0]Welcome. Take your time looking around.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_01 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 3 1001 1586 0]Welcome. Make sure you get all your preparations in order.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I don't want you failing to save the world because you ordered a new weapon too late.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_01 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16816 1586 0]Don't you have any gems? I highly suggest you try to find as many as you can.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I may be the only shop owner who accepts gems as currency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16823 1586 0]I can detect the true power of a gem, you see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Even if others consider them useless rocks, I may still need them. So bring the gems you find to me.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_02 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16815 1586 0]The cards I carry can be used to strengthen your Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]You can use them to offset Personas' weaknesses or enhance their strengths.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I'm willing to exchange these cards for gems.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_03 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16823 1586 0]Personas are interesting, aren't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Summoning them must be easy for you and your friends... I've never been able to summon one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Although, I understand that being able to summon a Persona comes with its own set of difficulties.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]...Well, good luck.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_04 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16827 1586 0]I wonder what the essence of a Persona truly is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I've studied them tirelessly, often only to end up with even more questions...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I hope I won't be searching for the answers for the rest of my life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16807 1586 0]...Sorry, I don't mean to complain to you.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_05 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16816 1586 0]I heard the news...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Kirijo-san passed away. How's his daughter faring?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]...Well, we don't need to talk about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16824 1586 0]So, how can I help you today?[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_06 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16801 1586 0]I can see in your eyes that you're getting stronger. I wonder if that's because of your Personas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]A great deal of strife is often required to awaken to a Persona, but maybe they're not all bad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16807 1586 0]Well, fight hard. And if you need anything I can provide, don't hesitate to come.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_07 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16802 1586 0]Item fusion is kind of like having a good team. Don't you think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]When you put things together, you might get something more powerful than you ever expected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]If you have big ambitions, you've got to keep your teammates close.[n][uf 1 1][e]

[msg MSG_ANTQ_GREET_TALK_08 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16801 1586 0]The time has almost come, hm? I can tell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]How long has it been since you started coming here...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16827 1586 0]To think I'm cooperating with a Persona-user ten years after I stopped working with Kirijo-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]But I'm glad that Persona-user is you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16823 1586 0]You had me on tenterhooks with how new you were... But look how capable you are now.[n][uf 1 1][e]

[msg MSG_REQ_AOJIRU_ANTIQUE_0 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16801 1586 0]Welcome. What can I do for you today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]The [uf 4 4 1 37 1 0]? That's quite the rarity you've set your eyes on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16808 1586 0]Well, that's fine. Bring me the gems and it's yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Mind you, that's one of my more valuable wares, so it'll cost you more than you might be used to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16823 1586 0]Just let me know whenever you're ready to swap for it.[n][uf 1 1][e]

[msg MSG_ANTQ_INFO_BASEITEM_0 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16807 1586 0]So, you found a new base model? Ah, this will make for a fine piece of equipment.[n][uf 1 1][e]

[msg MSG_ANTQ_INFO_BASEITEM_0_2 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16823 1586 0]Oh, would you look at that? This base model is quite rare.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I should be able to make a fairly interesting piece of equipment with this.[n][uf 1 1][e]

[msg MSG_ANTQ_INFO_BASEITEM_0_3 [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16813 1586 0]Base models don't come any better than this. Seeing one firsthand is practically a spectacle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Equipment made with this will surely be invaluable. I highly recommend using it.[n][uf 1 1][e]

[msg MSG_ANTQ_INFO_JEWELRY_SH [Mayoido Shopkeeper]]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16816 1586 0]You know of Club Escapade?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]I heard through the grapevine that the owner there's been collecting gemstones as a hobby.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0][uf 3 1 3 0 65535 16824 1586 0]Good grief... What's he even going to do with them? I could get so much more use out of them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1586 0 65535 65535 0 0]Ah, there I go again... Sorry, I don't mean to complain. What can I do for you today?[n][uf 1 1][e]

