[msg MSG_000_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_INFO_ALL_MAT_SELL [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1]All Valuables in your possession will be sold.[n][uf 1 1][e]

[msg MSG_EXIT_CONFIRM_01 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 2 1086 0]All done here?[n][uf 1 2 1][e]

[msg MSG_EXIT_CONFIRM_02 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 3 1086 0]Hm? You finished?[n][uf 1 2 1][e]

[msg MSG_EXIT_01 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1002 0 0]Come back when you need to.[n][uf 1 1][e]

[msg MSG_EXIT_02 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1003 0 0]See ya.[n][uf 1 1][e]

[msg MSG_EXIT_FIRST [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1002 1086 0]If you want to buy anything, you know where to find me. Drop by anytime.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Keep shopping[e]
[uf 0 5 65278][uf 2 1]Exit[e]

[msg MSG_WEAPON_GREET_FIRST [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16425 0 0]Now, then... I don't have that much, but you should be able to find what you need.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1000 1086 0]I don't have that much, but you should be able to find what you need.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_SALE [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1001 1086 0]Running a little sale today. See if anything catches your eye.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_00 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 3 1001 0 0]Don't worry, I won't ask what you want any of this for.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]I just do what I think is right.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_01 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16420 0 0]I'm ashamed to admit it, but there isn't much we adults can do for you when it really counts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Now, then... I don't have that much, but you should be able to find what you need.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_02 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16405 0 0]This is all I can do for you right now, but don't you be reckless, ya hear?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Now, then... Take your time.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_03 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]Some people with Apathy Syndrome have suddenly returned to normal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]I don't know how it happened, but I do know you guys did it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]You have my thanks, too. I gotta tip my hat to ya—you guys are impressive.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_04 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16420 0 0]The number of people infected with Apathy Syndrome seems to be increasing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]I thought it would decrease, but I guess that was just wishful thinking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]We could be in for the long haul, so feel free to get prepped here.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_05 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16417 0 0]Those girls from your school who had Apathy Syndrome seem to have regained their senses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]I'm guessing you all had a hand in that, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Now, then... Is there anything you need?[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_06 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]Lately, there's been an increase in Apathy Syndrome cases among pairs of men and women.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]That's all I know, but could there be a reason for it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]In any case, feel free to take a look around if you need anything.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_07 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]Those Apathy Syndrome cases in pairs came to an abrupt halt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Some have even regained consciousness. I'm sure you've all been at it again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]So, what can I get you today?[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_09 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 0 0 0]Apathy Syndrome may be on the decline, but people are still on edge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16419 0 0]I mean, who can blame them? Rumors spread, and the media fans the flames.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Anyway... Pick what you like.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_10 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16427 0 0]Apathy Syndrome may be a serious issue, but the people panicking over it are also a handful.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]The world is always like that. Powerlessness is a knave.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Well... Take your time and look around.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_08 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16407 0 0]There's been another spike in Apathy Syndrome cases. The entire city is in a panic.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]It's times like these when the police need to step up, but the reality is we've got no recourse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]In any case... take your time and browse.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_11 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]You know your buddy, the kid with the hat? Iori, was it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]He seemed real down about something. Did something happen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Well, anyway... What'll you take today?[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_12 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]There's been a lotta talk about Apathy Syndrome both online and in the news lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16427 0 0]The rumors have gotten out of hand. Some say it's contagious, others insist it's a foreign conspiracy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Well, I'm just going to do what I can.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_13 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16407 0 0]I heard about the incident. What a terrible thing to happen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]You guys are putting your lives on the line, and I can only gripe about my ineptitude...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]At the very least, I want to do what I can to help you out.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_14 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]I hear this is gonna be the last stand.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Well, then... prepare yourself as much as possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Don't die out there...[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_15 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16420 0 0]Seeing as you're here, I take it things aren't over yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]With the Kirijo Group in the state they're in, there's no telling how things will turn out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]All I can do right now is fulfill my duties.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_16 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16424 0 0]I won't pry for details, but I know something happened to you guys.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Don't dwell on it for too long. No one blames you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16405 0 0]This is all I can do for you, but I don't want you pushing yourselves too hard.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_17 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16401 0 0]The look on your face tells me you're ready to finish off one last big job.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]No matter what you're up against, I have faith you can pull this off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]Spare no preparation and make sure you come back alive.[n][uf 1 1][e]

[msg MSG_WEAPON_GREET_TALK_SE [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16415 0 0]You'd best be equipped for all contingencies. It's anyone's guess what could happen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]If there's anything you don't need, I can take it off your hands.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_00 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]There's still more...[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REQUEST_01 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]The missing person's family sent a thank-you letter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Take this, too.[n][uf 1 1][e]

[msg MND_DISAPPEAR_REQUEST_02]
[uf 0 5 65278][uf 2 1]That reminds me, didn't that supposed Santa[n]tell me to do something good for the world?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should show him this letter...[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_01 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]...You're here. Take this envelope.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Hm? Oh, it's something that missing schoolgirl brought in as a reward to the one who found her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]There was a lot about the case that stymied us on the force, so I figured you guys were involved.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_02 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16415 0 0]...This money is from the salaryman who went missing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]I couldn't make out the full picture from questioning him, but you're the ones who saved him, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]The police can't accept gifts, so this is yours. Use it wisely.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_03 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]They found that missing girl the other day. I tried questioning her, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Her answers didn't make any sense. She said some kids saved her from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]She left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_04 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]I've got something for you, so here you go.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]It's a token of gratitude the missing housewife left with us a short while ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16411 0 0]You rescued her, right? I won't ask questions. Just take it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_05 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]They found that missing schoolboy the other day. I tried questioning him, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]His answers didn't make any sense. He said some kids saved him from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]He left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_06 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]Here, take this envelope.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]It's a token of gratitude the missing housewife left with us a short while ago.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16411 0 0]You rescued her, right? I won't ask questions. Just take it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_07 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]See those rocks with the strange patterns on them? The man they found the other day left them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16427 0 0]I'm fine with one or two, but this many just gets in the way of our work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]...You saved him, didn't ya? Just go ahead and take them all.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_08 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16417 0 0]They found that missing office lady the other day. I tried questioning her, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]She wasn't making any sense. She said some kids saved her from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]She left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_09 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]For some reason, we just got a delivery of a bunch of mysterious dolls... You know anything about this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16420 0 0][uf 4 25 1086]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Your face says you do. Just take them...[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_10 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]They found that missing schoolgirl the other day. I tried questioning her, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Her answers didn't make any sense. She said some kids saved her from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]She left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_11 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]They found a missing person the other day... Oddly, he handed over a big wad of cash.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Seems he was the president of some company. He was pretty damn low-profile for someone so self-important.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]...Anyway, the police can't accept reward money, so you can have it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_12 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]They found that grade school kid the other day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]She brought this here as a way of saying, "Thanks."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Here, it's all yours.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_13 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]They found that missing guy the other day. I tried questioning him, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]His answers didn't make any sense. He said some kids saved him from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]He left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_14 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16417 0 0]They found that missing woman the other day. I tried questioning her, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Her answers didn't make any sense. I'm guessing her memory's fuzzy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16411 0 0]At any rate, she left this as a token of her appreciation, so I think you should have it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_15 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]Take this box. Something tells me it's for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]It's a token of gratitude the missing salaryman left with us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]You rescued him, right? I won't ask questions. Just take it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_16 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16417 0 0]They found that missing woman the other day. I tried questioning her, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Her answers didn't make any sense. She said some kids saved her from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]She left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_17 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16415 0 0]This is a token of gratitude the woman who was missing brought us, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16420 0 0][uf 4 25 1086]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]These coins look awfully pricey. Kids today sure are loaded...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Whatever. You guys saved her, so they're yours.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_18 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16402 0 0]Take this box. Something tells me it's for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]Hm? Oh, it's something that missing woman brought in as thanks to the one who found her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16411 0 0]You rescued her, right? I won't ask questions. Just take it.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_19 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16401 0 0]Will you take a look at this for me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]The girl they found the other day brought this in as a gift...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16413 0 0]It looks like... some sort of liquid. By the looks of the container, I'm guessing you're supposed to drink it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]She was murmuring something about fortune telling, so maybe it has something to do with that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16406 0 0]...Anyway, just take it. We can't have something this suspicious at the police station.[n][uf 1 1][e]

[msg MSG_DISAPPEAR_REWARD_20 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16416 0 0]They found that missing student the other day. I tried questioning him, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0]His answers didn't make any sense. He said some kids saved him from an attack by a black thing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 3 0 65535 16412 0 0]He left a reward with us, so I'll hand it over to you.[n][uf 1 1][e]

