[msg MSG_REQUEST_HELP_000 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_001 [Retrieve the first old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the top floor of Thebel, the first block in Tartarus. Unless... you already have it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_002 [Retrieve the second old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the halfway point of Arqa, the second block in Tartarus. No need to rush—there is no deadline for this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_003 [Retrieve the third old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the top floor of Arqa, the second block in Tartarus. Have you had the chance to read the contents of these documents? They are truly intriguing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_004 [Retrieve the fourth old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the halfway point of Yabbashah, the third block in Tartarus. As for why these documents can be found within that deformed tower... The answer may be on another floor higher up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_005 [Retrieve the fifth old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the top floor of Yabbashah, the third block in Tartarus. I wonder who left behind these writings... Just what sort of person are they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_006 [Retrieve the sixth old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the halfway point of Tziah, the fourth block in Tartarus. Has your perspective changed after discovering the truth, one unbeknownst to the ordinary person?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_007 [Retrieve the seventh old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the top floor of Tziah, the fourth block in Tartarus. This will be fairly high up in the tower. I wish you a safe journey there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_008 [Retrieve the last old document.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the halfway point of Harabah, the fifth block in Tartarus. This will be my final request regarding the old documents. I look forward to your report of success.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_009 [Retrieve the progress report.]]
[uf 0 5 65278][uf 2 1]Please bring me the [uf 4 4 1 0 0 2] from the top floor of Harabah, the fifth block in Tartarus. This document lies even higher up, waiting to be discovered... I'd love to see it for myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_010 [Traverse the Monad Passage.]]
[uf 0 5 65278][uf 2 1]Please investigate a certain passage in Yabbashah, the third block, on the 91st floor. Though the entrance appears the same as a Monad door, the inside seems to differ.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat all the Shadows lurking within the Monad Passage on the 91st floor in Yabbashah, the third block.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_011 [Defeat the Shadow of the Void.]]
[uf 0 5 65278][uf 2 1]I sense a presence of immense malevolence... Please defeat the Shadow of the Void lurking within the Monad Passage in the sixth block, Adamah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat the Shadow of the Void lurking within the Monad Passage on the 255th floor in Adamah, the sixth block.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_012 [Bring me a Muscle Drink.]]
[uf 0 5 65278][uf 2 1]Have you ever tried something called a "Muscle Drink"? I have long pondered its taste. Could you please bring me one to satiate my curiosity? I believe you may be able to purchase it somewhere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring Elizabeth [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_013 [Bring me a giant, creepy doll.]]
[uf 0 5 65278][uf 2 1]I heard there's a "creepy-looking" doll in your world that is also used for educational purposes. I would like to see it for myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a doll that is also used for teaching.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_014 [I'd like to try all kinds of drinks.]]
[uf 0 5 65278][uf 2 1]I heard that there exists a contraption called a "vending machine" that automatically dispenses a variety of beverages. Could you please collect these aforementioned beverages and deliver them to me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Collect 12 different drinks from vending machines for Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_015 [I'd like to try aojiru.]]
[uf 0 5 65278][uf 2 1]Have you heard of a drink called "aojiru"? Rumor says it is "super gross." I prefer my drinks tasty and flavorful though. Therefore... would you please bring me a delicious aojiru?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_016 [Bring me some potent medicine.]]
[uf 0 5 65278][uf 2 1]I've heard that a powerful medicine is being produced in an ominous research facility known as the "nurse's office." Could you please get your hands on that medicine for me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_017 [Let me hear music unique to Gekkoukan.]]
[uf 0 5 65278][uf 2 1]I'd very much love to listen to a song that is associated with your school. Perhaps it would be wise to check a location within the school that broadcasts music...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a CD associated with Gekkoukan High School.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_018 [I'd like to try a beef bowl.]]
[uf 0 5 65278][uf 2 1]A dish called the "Umiushi Beef Bowl" is allegedly all the rage in town now. If it truly is as exquisite as the rumors suggest, then I would love to have a taste myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_019 [Please prevail in the Big Eater Challenge.]]
[uf 0 5 65278][uf 2 1]The Big Eater Challenge, a unique event in which one must devour more food than the other contestants... Such a battle shall be held at the burger establishment at the Iwatodai strip mall. Would you please participate in my stead?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Complete the Big Eater Challenge at Wilduck Burger.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_020 [I'd like to be gifted a bouquet of flowers.]]
[uf 0 5 65278][uf 2 1]I hear there is a custom in your world where a woman may receive roses. I would love to experience this myself. Would you please bring me some roses?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_021 [Experiment with fortune telling.]]
[uf 0 5 65278][uf 2 1]I hear there is a fortune-teller at the club in Paulownia Mall. Could you verify the accuracy of her readings? One such fortune promises higher chances of encountering rare Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Make use of the Rarity Fortune that increases the appearances of rare Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_022 [I'd like to see a pair of Max Safety Shoes.]]
[uf 0 5 65278][uf 2 1]In the online shopping world, these "Max Safety Shoes" appear to be extremely popular as of late. I wonder what makes them so "Max"... As my curiosity is killing me, I'd love to take a look at them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] pair of [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_023 [Bring me the mysterious person's autograph.]]
[uf 0 5 65278][uf 2 1]I hear a certain individual from the online shopping world often appears in your world as well. It seems he has quite the distinctive personality. Would you please meet this person and get me his autograph?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Get an autograph from President Tanaka of Tanaka's Amazing Commodities.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_024 [I want to eat a chilled taiyaki.]]
[uf 0 5 65278][uf 2 1]I heard that your world has a strange "taiyaki" that is cold despite having been grilled. It must be filled with flavors that are simply out of this world... I'd love to have a taste myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_025 [I'd like to try a home-cooked meal.]]
[uf 0 5 65278][uf 2 1]I wonder what a "home-cooked meal" tastes like... You may bring either food or beverage—I've no preference.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a food or drink you made together with someone at the dorm.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_026 [I'd like to see a mysterious potato.]]
[uf 0 5 65278][uf 2 1]There's a rumor that claims a potato raised with love and care will develop a mysterious power... Could you verify if such a potato can really be grown?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a potato that you've grown.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_027 [Attempt a hundred shrine visits.]]
[uf 0 5 65278][uf 2 1]There is a ritual called "a hundred shrine visits" that supposedly grants wishes... I would love to witness the miracle of the gods myself. My wish is for a 500-yen bill.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring what you receive from praying at the shrine.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_028 [Look for the drink with my name.]]
[uf 0 5 65278][uf 2 1]According to rumors, the beverage bearing the same name as me is only available in an unpopular location. Please search for it and bring it to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a drink that shares a name with Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_029 [I'd like to see proof of a bond.]]
[uf 0 5 65278][uf 2 1]A bond is normally invisible to the naked eye. However, it is sometimes shown through the act of gift-giving... Would you please show me an item that represents a strong bond you share with someone?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring an item you can only receive when a Social Link has been maxed out.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_030 [I want to look fashionable.]]
[uf 0 5 65278][uf 2 1]Please bring me a stylish item that would look good on me. I believe you may find something where the young and trendy gather to have a good time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a fashionable item.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_031 [Find me a beautiful tile.]]
[uf 0 5 65278][uf 2 1]I'm looking for a small, rectangular tile with a peacock painted on it. Apparently, being in possession of one can cause people to go into a frenzy... I'd like to see one myself, if possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a tile with a peacock design.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_032 [I wish to feel the ocean.]]
[uf 0 5 65278][uf 2 1]The ocean... To me, it is akin to a realm of dreams since I am unable to leave my post. Would you please bring me a memento that reminds you of the ocean?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring something you find from the ocean.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_033 [I wish to become a straw millionaire.]]
[uf 0 5 65278][uf 2 1]I hear there is a method to acquire wealth by simply bartering one item for another continuously. Would you please try it out?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring what you get after bartering items.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_034 [Bring me my Christmas present.]]
[uf 0 5 65278][uf 2 1]It appears that Santa has been so busy with Christmas this year that he forgot to deliver my present... Would you please find Santa and bring me my present?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Get Elizabeth's Christmas present from Santa.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_035 [Defeat a Greedy Shadow.]]
[uf 0 5 65278][uf 2 1]Checkmate the king of all rare Shadows that appears in Harabah, the fifth block of Tartarus, and bring me a [uf 4 4 1 0 0 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat the Greedy Shadow in Harabah, the fifth block of Tartarus, and bring back [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_036 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_037 [I want Jack Frost dolls.]]
[uf 0 5 65278][uf 2 1]Word has it there are Jack Frost dolls in your world. I want one to display, one to trade, and one to cherish... Could you please bring me three?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring Elizabeth not 1 [uf 4 4 1 0 1 2], but [uf 2 4 1] of them.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_038 [I'd like to try sushi.]]
[uf 0 5 65278][uf 2 1]I hear a food called "sushi" in your world is consumed during feasts. It must be one tantalizing dish... I would like to try it myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring sushi.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_039 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_040 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_041 [Create a Persona that's level 13 or above.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that meets or exceeds the required level. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona that is level 13 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_042 [Create a Persona with Kouha.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that has the specified skill. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona with the skill Kouha in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_043 [Create a Persona that's level 23 or above.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that meets or exceeds the required level. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona that is level 23 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_044 [Create a Persona with Torrent Shot.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that has the specified skill. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona with the skill Torrent Shot in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_045 [Create a Persona that's level 38 or above.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that meets or exceeds the required level. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona that is level 38 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_046 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_047 [Create a Persona that's level 46 or above.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that meets or exceeds the required level. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona that is level 46 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_048 [Create a Persona with Tempest Slash.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that has the specified skill. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona with the skill Tempest Slash in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_049 [Create a Persona with Auto-Maraku.]]
[uf 0 5 65278][uf 2 1]Please show me a Persona that has the specified skill. Any Persona will do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Persona with the skill Auto-Maraku in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_050 [Fusion Series #1: Emperor, Oberon]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. There are various combinations that would give birth to an Emperor, such as Lovers and Justice, Strength and Magician.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have an Oberon with the skill Mazio in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_051 [Fusion Series #2: Chariot, Mithras]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. As the required level is fairly high, I suggest you make good use of your Social Link.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Mithras at level 26 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_052 [Fusion Series #3: Hermit, Mothman]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. The Mithras from the previous task will learn Agilao, and it would be wise to make use of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Mothman with the skill Agilao in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_053 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_054 [Fusion Series #4: Lovers, Titania]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. If you have a Persona with the specified skill, please search for a combination that will allow it to be inherited.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Titania with the skill Matarukaja in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_055 [Fusion Series #5: Magician, Rangda]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. Have you been cultivating the bonds you share with your Social Links? The stronger your bonds, the greater the blessings you'll receive during fusion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Rangda at level 54 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_056 [Fusion Series #7: Hierophant, Daisoujou]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. One option is to use a Skill Card. It seems that there exists a shop carrying them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Daisoujou with the skill Regenerate 3 in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_057 [Fusion Series #8: Death, Alice]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. Know that Alice can only be created through Special Fusion. Do you have the requisite Personas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have Alice in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_058 [Fusion Series #9: Fool, Loki]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. There seems to be a particular time when your bonds may bless you even more than usual... Why not attempt a fusion during that period?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Loki at level 75 or higher in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_059 [Fusion Series #10: Tower, Masakado]]
[uf 0 5 65278][uf 2 1]This shall be the final task for creating Personas. As you have managed to complete all fusion-related tasks thus far, I am confident you will succeed with this one as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Masakado with the skill Charge in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_060 [Fusion Series #6: Strength, Siegfried]]
[uf 0 5 65278][uf 2 1]My intent in preparing this task is to help nurture your abilities. You will not receive any hints for this one. If you manage to obtain this Persona, then you will surely gain invaluable strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Have a Siegfried with the skill Endure in your possession and report to Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_061 [Bring me a Sengoku-era helm.]]
[uf 0 5 65278][uf 2 1]I would like to see something called a "helm," a protective covering for the head, one rich with history... I'm sure there exists a person who still cherishes one to this day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring a helm from the Sengoku era.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_062 [I'd like to try Oden Juice.]]
[uf 0 5 65278][uf 2 1]I would like to get my hands on this legendary "Oden Juice." I advise that you first speak with an expert on beverages. My hunch tells me you may find one such person near a persimmon tree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring some Oden Juice.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_063 [Bring me food for a furry friend.]]
[uf 0 5 65278][uf 2 1]Will you bring me the sort of food a furry friend on four legs would enjoy? You might be able to get some from that close friend of yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_064 [Go clean a restroom.]]
[uf 0 5 65278][uf 2 1]Would you please clean the restroom at the station in an attempt to beautify the city? The tools I have given you should be of use.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the cleaning supplies and clean the restroom.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_065 [Go water the flowers.]]
[uf 0 5 65278][uf 2 1]When I visited Gekkoukan High School, the flowers in the flowerbed appeared to be wilting... Would you please water them?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Water the flowerbed at school.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_066 [Please feed the cat.]]
[uf 0 5 65278][uf 2 1]Somewhere in the city, there appears to be a hungry cat who is having trouble finding food. Would you please find and feed the poor thing?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Give the hungry cat some food.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_067 [Bring me a Featherman R action figure.]]
[uf 0 5 65278][uf 2 1]Please bring me a Featherman R action figure. Again, it has to be a Featherman R action figure and no other Featherman.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_068 [I'd like to walk around Paulownia Mall.]]
[uf 0 5 65278][uf 2 1]I've developed a yearning to explore your world. Would you please escort me around Paulownia Mall during the daytime?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth around Paulownia Mall.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_069 [I'd like to visit Iwatodai Station.]]
[uf 0 5 65278][uf 2 1]My yearning to explore your world has grown even stronger. Please escort me around Iwatodai during the daytime.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Walk around Iwatodai with Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_070 [I'd like to visit Naganaki Shrine.]]
[uf 0 5 65278][uf 2 1]My yearning to explore your world grows ever stronger still... I would like you to escort me around Naganaki Shrine during the daytime.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Walk around Naganaki Shrine with Elizabeth.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_071 [I'd like to visit Gekkoukan High.]]
[uf 0 5 65278][uf 2 1]I can no longer suppress my desire to explore your world. Would you escort me around Gekkoukan High School after its hours of operation?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth around Gekkoukan High.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_072 [I'd like to visit your room.]]
[uf 0 5 65278][uf 2 1]My desire to explore your world cannot possibly be abated. Please accompany me to your room during the daytime.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Invite Elizabeth to your room.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_073 [Bring me pine resin.]]
[uf 0 5 65278][uf 2 1]Bring me this "pine resin" that is used in archery. Rumor says it looks exactly like soybean powder. I have a feeling you may be able to get some from a close friend of yours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_074 [Bring me a handheld game console.]]
[uf 0 5 65278][uf 2 1]Could you bring me a tiny device known as a "handheld game console"? Perhaps you could acquire one from a close friend who enjoys using it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_075 [Bring me a triangular sword.]]
[uf 0 5 65278][uf 2 1]Bring me what is known as a "triangular sword." I hear this sword has a long history behind it... Perhaps you ought to ask a close friend about it, one who happens to be knowledgeable on such matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_076 [Bring me protein not for pros.]]
[uf 0 5 65278][uf 2 1]I would like you to bring me some protein that not only pros can drink, but amateurs, too... I have a hunch that you may be able to acquire some from a very athletic friend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_077 [Bring me a glasses wipe.]]
[uf 0 5 65278][uf 2 1]Will you please bring me a "glasses wipe"? Based on its name alone, it is my understanding that anyone who wears glasses should be in possession of this item.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_078 [Bring me a Christmas star.]]
[uf 0 5 65278][uf 2 1]Please bring me a "Christmas star." Perhaps a close friend well-versed in plants would know something about it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_079 [Bring me a fruit knife.]]
[uf 0 5 65278][uf 2 1]Please bring me a blade that likes to cut through fruit, also known as a "fruit knife." Should there be someone close to you well-versed in the culinary arts, I suggest you ask them first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_080 [Bring me oil.]]
[uf 0 5 65278][uf 2 1]Would you bring me some oil frequently used by one of your acquaintances?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the item that Elizabeth is asking for.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_081 [Bring me a Juzumaru.]]
[uf 0 5 65278][uf 2 1]Please bring me the sword [uf 4 4 1 0 0 2]. You may find it within a special treasure chest on a lower floor of Arqa, the second block in Tartarus. Tread carefully, for I sense a powerful Shadow in its vicinity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth a [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_082 [Bring me an Onimaru Kunitsuna.]]
[uf 0 5 65278][uf 2 1]Please bring me the sword [uf 4 4 1 0 0 2]. You may find it within a special treasure chest on a lower floor of Arqa, the second block in Tartarus. Tread carefully, for I sense a powerful Shadow in its vicinity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth an [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_083 [Bring me a Mikazuki Munechika.]]
[uf 0 5 65278][uf 2 1]Show me a [uf 4 4 1 0 0 2]. I have a feeling you can obtain it from the antique shop in Paulownia Mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth a [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_084 [Bring me an Ote-gine.]]
[uf 0 5 65278][uf 2 1]Please bring me the spear [uf 4 4 1 0 0 2]. You may find it within a special treasure chest on a lower floor of Tziah, the fourth block in Tartarus. Tread carefully, for I sense a powerful Shadow in its vicinity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth an [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_085 [Bring me an Outenta Mitsuyo.]]
[uf 0 5 65278][uf 2 1]Show me an [uf 4 4 1 0 0 2]. I have a feeling you can obtain it from the antique shop in Paulownia Mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth an [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_086 [Bring me a Rai Kunimitsu.]]
[uf 0 5 65278][uf 2 1]Please bring me the knife [uf 4 4 1 0 0 2]. You can find it within a special treasure chest on a lower floor of Harabah, the fifth block in Tartarus. Tread carefully, for I sense a powerful Shadow in its vicinity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth a [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_087 [Bring me a Dojigiri Yasutsuna.]]
[uf 0 5 65278][uf 2 1]Please bring me the sword [uf 4 4 1 0 0 2]. You can find it within a special treasure chest on an upper floor of Harabah, the fifth block in Tartarus. Tread carefully, for I sense a powerful Shadow in its vicinity.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth a [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_088 [Bring me a Tonbo-kiri.]]
[uf 0 5 65278][uf 2 1]Show me a [uf 4 4 1 0 0 2]. I have a feeling you can obtain it from the antique shop in Paulownia Mall.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Show Elizabeth a [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_089 [Defeat a rare Shadow #1]]
[uf 0 5 65278][uf 2 1]Please retrieve the [uf 4 4 1 0 1 2] that drops from rare Shadows found in Yabbashah, the third block of Tartarus. Do keep in mind that these Shadows are extremely quick on their feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a rare Shadow in the third block, Yabbashah, and bring back [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_090 [Defeat a rare Shadow #2]]
[uf 0 5 65278][uf 2 1]Please retrieve the [uf 4 4 1 0 1 2] that drops from rare Shadows found in Tziah, the fourth block of Tartarus. Do keep in mind that these Shadows are extremely quick on their feet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a rare Shadow in the fourth block, Tziah, and bring back [uf 2 4 1] [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_091 [Shadow Hunting Milestone]]
[uf 0 5 65278][uf 2 1]Practice makes perfect. This applies to everything. So long as you persevere, you will surely begin to see results... Given that, please defeat a certain number of Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 100 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_092 [Shadow Hunting Milestone #2]]
[uf 0 5 65278][uf 2 1]The trick to combat is simple, you see. Just end it all in an instant. Strike down the enemy before they can act. This decreases the odds of sustaining injuries, so I advise you keep this in mind. Now, please report to me after defeating a certain number of Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 200 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_093 [Shadow Hunting Milestone #3]]
[uf 0 5 65278][uf 2 1]Always remain alert the first time you encounter a new Shadow. One surprise attack can land you in hot water... Please exercise the utmost caution as you continue defeating Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 300 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_094 [Shadow Hunting Milestone #4]]
[uf 0 5 65278][uf 2 1]Have you gotten used to battling Shadows? If you find that the same opponents are much too easy to defeat now, then take that as proof of your improvement. Please report to me after you've defeated even more Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 450 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_095 [Shadow Hunting Milestone #5]]
[uf 0 5 65278][uf 2 1]Have you noticed that every Shadow wears a mask representing the Arcana to which it belongs? A change in perspective can help you discover something new. Now then, report to me once you've reached the target.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 600 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_096 [Shadow Hunting Milestone #6]]
[uf 0 5 65278][uf 2 1]You must find this sort of task terribly facile now. Asking you to undertake these requests, then, was well worth it... Now, please let me know once you've managed to defeat a great deal of Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat a total of 800 Shadows.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_097 [Treasure Hunting Milestone]]
[uf 0 5 65278][uf 2 1]Labyrinths and treasure chests... It is certainly a charming combination. By some twist of fate, you can find treasure chests scattered about Tartarus as well. Please retrieve the contents inside whenever you encounter them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Open a total of 50 treasure chests.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_098 [Treasure Hunting Milestone #2]]
[uf 0 5 65278][uf 2 1]Though treasure chests may be enticing, try not to get distracted by them. You wouldn't want a Shadow to creep up on you now, would you? Hm? You've already experienced that? Well, no matter. Simply report back to me once you've reached the goal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Open a total of 100 treasure chests.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_099 [Treasure Hunting Milestone #3]]
[uf 0 5 65278][uf 2 1]A variety of treasure chests exist. Some only contain precious metals, and others require a "key" to open. There seems to be more than meets the eye with these treasure chests... Now then, I look forward to your report of success.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Open a total of 150 treasure chests.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_100 [Treasure Hunting Milestone #4]]
[uf 0 5 65278][uf 2 1]Since Tartarus is a labyrinthine construct with an ever-changing structure, it may prove difficult to locate a treasure chest that contains the item you're looking for... However, that is part of the fun in exploring. Well then, I await your report of success.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Open a total of 200 treasure chests.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_101 [Persona Fusion Milestone]]
[uf 0 5 65278][uf 2 1]Have you been fusing your Personas? I recommend doing so once you have reached your limit and are unable to hold any more Personas. I await your report on this matter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Conduct a total of 20 Persona fusions.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_102 [Persona Fusion Milestone #2]]
[uf 0 5 65278][uf 2 1]"If I combine these two, I'll get this, but if I combine those two, what do I get then...?" If, perhaps, you are struggling to decide which Personas to fuse, then I recommend utilizing "Search Fusion." I look forward to your report of success.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Conduct a total of 35 Persona fusions.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_103 [Persona Fusion Milestone #3]]
[uf 0 5 65278][uf 2 1]During fusion, sometimes a Persona's skill will change, or an accident may occur. There are rumors of veterans who make use of these irregularities. Well then, please report to me once you've reached the target.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Conduct a total of 50 Persona fusions.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_104 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_105 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_106 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_107 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_108 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_109 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_110 [Bring me a Bloody Button.]]
[uf 0 5 65278][uf 2 1]You may find this one of the most challenging requests to undertake. Defeat the Reaper and bring me the [uf 4 4 1 0 1 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bring the [uf 4 4 1 0 1 2].[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_111 [Take out the ultimate adversary.]]
[uf 0 5 65278][uf 2 1]We have made arrangements for you to battle with the ultimate adversary at the deepest point of Tartarus. Please take down your opponent—alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Defeat the ultimate adversary.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_112 [Perform King and I.]]
[uf 0 5 65278][uf 2 1]Fusion Spell, a hidden power that belongs to you and only you... One of several is called "King and I." To execute this Fusion Spell, you'll need King Frost and the biggest, baddest boy of all Jack Frosts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Carry out the "King and I" Fusion Spell.[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_113 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_114 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_115 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_116 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_117 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_118 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_119 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_120 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_121 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_122 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_123 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_124 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_125 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_126 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_REQUEST_HELP_127 [未使用]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

