[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Oh![n][e]

[msg MSG_000_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 5 0]What the... hell...?[n][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Junpei-kun![n][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Junpei![n][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]It's her Persona...[n]Does it have the power to bestow life?[n][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]I don't believe it...[n]She brought him back from the dead?[n][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]But wait, if she goes as far as[n]completely reviving someone...[n][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 5 0]The cost for that would be...![n][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]Chidori![n][e]

[msg MSG_007_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]So it worked...[n][e]

[msg MSG_008_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]I can hear you...[n][e]

[msg MSG_008_3_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 3 0]The sound of... your beating heart...[n][e]

[msg MSG_008_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 5 0]Ba-dump... Ba-dump... Hehe...[n][e]

[msg MSG_008_7_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 7 0]That's all I needed to know...[n]Now I can go on living... in you...[n][uf 1 1][e]

[msg MSG_008_9_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 9 0]I'll always be with you...[n][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]Huh...?[n][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Hey, Chidori... Stay with me![n][e]

[msg MSG_010_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 5 0]The hell're you even talkin' about!? Hey![n][e]

[msg MSG_011_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]This is how it has to be... But don't worry...[n][e]

[msg MSG_011_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 5 0]I'll protect you, Junpei... Always...[n][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]Y-Yeah... Same. I've got your back![n][e]

[msg MSG_012_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 5 0]I'll do everything I can to protect you![n][e]

[msg MSG_012_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 7 0]So come on![n][e]

[msg MSG_013_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]Hehe...[n][e]

[msg MSG_013_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 5 0]This might... be all I ever needed...[n][e]

[msg MSG_013_7_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 7 0]Just being in each other's arms... It's nice...[n][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]Chidori![n][e]

[msg MSG_015_0_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]I love you... Junpei...[n][e]

[msg MSG_015_5_0 [Chidori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 5 0]Thank... you...[n][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]...!?[n][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0]Chi...dori...?[n][e]

[msg MSG_017_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 32 5 0]You're kidding, right?[n][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]Chidori...[n][e]

[msg MSG_018_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 5 0]Say something, please![n][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]CHIDORI![n][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]AAAAAAAAAAH![n][e]

