[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 1 0 0]I found it. It's at the south end of the Moonlight Bridge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 50 0 0][uf 3 1 1 0 0 2 0 0]The twelfth and final Shadow...[n][uf 1 1][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Mmm, so this is it...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 4 0 0]And as we expected, I'm detecting more Persona-users nearby...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 5 0 0]It's Strega.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 6 0 0]They know this is their last chance. We expected as much, but don't be careless.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0][uf 3 1 1 0 0 7 0 0]So it's them...[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 1 0 0 8 0 0]Heh. Saves us the trouble of looking for them.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]You've all fought admirably thus far.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 10 0 0]This will be our last operation. Let's all come back safely.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Got it.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 52 65535 0 0][uf 3 1 1 0 0 12 0 0]Roger that.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 13 0 0]Of course.[n][uf 1 1][e]

[msg MND_010_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]The final battle is here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The last Shadow and Strega await us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This is serious. I should choose[n]my team lineup carefully...[n][uf 1 1][e]

