[msg MSG_000_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1093]Everybody, gather 'round![n][uf 1 1][e]

[msg MSG_001_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1093]You've probably all heard already, but Miyamoto's knee is in bad shape.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1093]If you see him having a hard time, I want you to stop him immediately.[n][uf 1 1][e]

[msg MSG_002_0_0 [Track Team Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1093]That's it for today![n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 151 65535 0 0][uf 3 1 1 0 0 5 0 0]Let's grab a bite before we head home.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I left school with Miyamoto.[n][uf 1 1][e]

