[msg TRL_000_0_0 [Using Items and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]If you get injured while exploring Tartarus, you can use items and skills to restore HP or SP.[n][uf 1 1][e]

[msg TRL_001_0_0 [Using Items and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 3]Open the [uf 1 3 112] menu, select [uf 0 1 2]ITEM[uf 0 1 27], and choose a recovery item, such as [uf 4 4 0 37 1 16385] or [uf 4 4 0 37 1 16412]. Then choose a party member.[n][uf 1 1][e]

[msg TRL_002_0_0 [Using Items and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 2]Skills work in a similar way. Start by opening the menu, select [uf 0 1 2]SKILL[uf 0 1 27], and pick a recovery skill, such as [uf 0 1 35]Dia[uf 0 1 27]. Then choose a party member.[n][uf 1 1][e]

[msg TRL_003_0_0 [Using Items and Skills]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]It's best to prioritize [uf 4 2]'s HP so that he doesn't faint while exploring.[n][uf 1 1][e]

