[msg TRL_000_0_0 [Dark Zone]]
[uf 0 5 65278][uf 2 1][uf 4 8 38]While exploring, your periphery may occasionally become shrouded in a darkness known as the [uf 0 1 2]Dark Zone[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [Dark Zone]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]With your vision obscured, you'll need to use your map to find your way around. Fortunately, [uf 0 1 2]enemies can't detect you either[uf 0 1 27], so you can take your time looking for the stairs to the next floor.[n][uf 1 1][e]

[msg TRL_002_0_0 [Dark Zone]]
[uf 0 5 65278][uf 2 1][uf 4 8 39][uf 0 1 2]Breakable objects[uf 0 1 27] are also guaranteed to contain a [uf 4 4 0 37 1 16667], so don't be deterred by the darkness and take your time exploring.[n][uf 1 1][e]

