[msg TRL_000_0_0 [One-Way Teleporters]]
[uf 0 5 65278][uf 2 1][uf 4 8 6]Occasionally, you will encounter [uf 0 1 2]one-way teleporters[uf 0 1 27] in Tartarus that can be used to return to the entrance.[n][uf 1 1][e]

[msg MSG_001_0_0 [One-Way Teleporters]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Keep in mind that, since these teleporters are only one-way, [uf 0 1 2]you cannot return to the same floor where it was used[uf 0 1 27].[n][uf 1 1][e]

