[msg TRL_000_0_0 [The Reaper]]
[uf 0 5 65278][uf 2 1][uf 4 8 17]While inside Tartarus, the [uf 0 1 2]Reaper[uf 0 1 27] may appear if you [uf 0 1 2]stay on the same floor for too long[uf 0 1 27].[n][uf 1 1][e]

[msg TRL_001_0_0 [The Reaper]]
[uf 0 5 65278][uf 2 1][uf 4 8 17]The Reaper is a terrifying foe. You'll want to avoid combat and hurry to the next floor as quickly as possible.[n][uf 1 1][e]

