[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14201 0 0]About Yakushima... Remember that you won't be able to go if you don't score well on your exams.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0]Since everyone is here, why don't you have the third-years overlook your studies?[n][uf 1 1][e]

[msg MSG_000_1_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0]If that sounds good, I can ask Kirijo-kun and Sanada-kun for their help. What do you say?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, please.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14207 0 0]All right. I'll let the other second-years know too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0]Hm... With a ferry trip to Yakushima on the line... I hope you perform ferry well on your exams![n][uf 1 1][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14220 0 0]Oh, is that so? Well, there's no rush to make a decision right this moment.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0]Let me know if you change your mind. I'll let everyone else know just in case.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14205 0 0]Hello, again. Do you feel up for that study session now?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, I'd like to.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14210 0 0]Now that's what I like to hear![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0]Hm... With a ferry trip to Yakushima on the line... I hope you perform ferry well on your exams![n][uf 1 1][e]

[msg MSG_007_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14220 0 0]Well, it's not mandatory, so you can join in when you feel like it.[n][uf 1 1][e]

[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

