[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3012 0 0]...Oh, [uf 4 1]. You here for a change of pace?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Mitsuru and I are trying to study, but we're not really getting anywhere...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3074 0 0]Hey, you should join us. We might make some progress, all three of us together, don't you think?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Sure.[e]
[uf 0 5 65278][uf 2 1]I'll pass.[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3115 0 0]Good, then it's settled. Go get your things and meet us back here.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]I see, no worries. Let me know if you change your mind.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3009 0 0]Oh, you're back? Did you decide to join us?[n][uf 1 1][e]

[msg MSG_006_1_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]What do you say?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Let's study together.[e]
[uf 0 5 65278][uf 2 1]Nah.[e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3115 0 0]Good, then it's settled. Go get your things and meet us back here.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]All right, then. Well, we'll be here if you decide otherwise.[n][uf 1 1][e]

[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

