[msg PFM_MAGICIAN]
[uf 0 5 65278][uf 2 1]The Magician Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_PRIESTESS]
[uf 0 5 65278][uf 2 1]The High Priestess Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_EMPRESS]
[uf 0 5 65278][uf 2 1]The Empress Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_EMPEROR]
[uf 0 5 65278][uf 2 1]The Emperor Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_HIEROPHANT]
[uf 0 5 65278][uf 2 1]The Hierophant Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_LOVERS]
[uf 0 5 65278][uf 2 1]The Lovers Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_CHARIOT]
[uf 0 5 65278][uf 2 1]The Chariot Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_JUSTICE]
[uf 0 5 65278][uf 2 1]The Justice Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_HERMIT]
[uf 0 5 65278][uf 2 1]The Hermit Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_FORTUNE]
[uf 0 5 65278][uf 2 1]The Fortune Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_STRENGTH]
[uf 0 5 65278][uf 2 1]The Strength Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_HANGEDMAN]
[uf 0 5 65278][uf 2 1]The Hanged Man Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_MOON]
[uf 0 5 65278][uf 2 1]The Moon Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_JUDGEMENT]
[uf 0 5 65278][uf 2 1]The Judgement Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_DEVIL]
[uf 0 5 65278][uf 2 1]The Devil Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_TEMPERANCE]
[uf 0 5 65278][uf 2 1]The Temperance Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_TOWER]
[uf 0 5 65278][uf 2 1]The Tower Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_STAR]
[uf 0 5 65278][uf 2 1]The Star Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_SUN]
[uf 0 5 65278][uf 2 1]The Sun Major Arcana card[n]has been added to Shuffle Time.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP1]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Samech, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP2]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Ayin, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP3]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Pe, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP4]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Tsadi, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP5]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Qof, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP6]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Resh, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP7]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Shin, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

[msg PFM_GET_CARD_LIMIT_UP8]
[uf 0 5 65278][uf 2 1]By acquiring the Book of Tav, the number of Major Arcana cards obtainable from Shuffle Time has increased by one.[n][uf 1 1][e]

