[msg MSG_708_100 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 2 1 0 6]I think that's the Shadow's main body floating up there...[n][uf 1 1][e]

[msg MSG_708_110 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 5 65535 50 0 0][uf 3 1 1 0 2 2 0 6]If it's that high, your attacks won't have the range to reach it...[n][uf 1 1][e]

[msg MSG_708_120 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 1 0 2 3 0 6]Wait, but... I'm picking up similar readings from those statues down there.[n][uf 1 1][e]

[msg MSG_708_130 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 4 0 6]There's a connection with the floating target, I'm sure of it![n][uf 1 1][e]

[msg MSG_708_000 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Not even my arrows can reach that far...![n][uf 1 1][e]

[msg MSG_708_001 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Target is out of range.[n][uf 1 1][e]

[msg MSG_708_200 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 1 0 2 5 0 6]The main body is down! It looks like it loses the ability to fly when you take out those statues.[n][uf 1 1][e]

[msg MSG_708_210 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 6 0 6]This is your chance to attack! Give it everything you've got![n][uf 1 1][e]

[msg MSG_708_002 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]The Shadow is back in the air! You can't attack it anymore![n][uf 1 1][e]

[msg MSG_708_300 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 1 0 2 7 0 6]I'm getting an unusual energy reading from the main body...[n][uf 1 1][e]

[msg MSG_708_310 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 8 0 6]Ah! It's getting more aggressive! Watch out for stronger attacks![n][uf 1 1][e]

[msg MSG_708_400 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 1 0 2 9 0 6]I'm picking up a powerful reading from this statue...![n][uf 1 1][e]

[msg MSG_708_410 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 50 0 0][uf 3 1 1 0 2 10 0 6]This one's not like the others. Let's do what we can to take it down![n][uf 1 1][e]

[msg MSG_708_003 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]We're almost there. Don't let up![n][uf 1 1][e]

