[msg MSG_000_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 3 0 65535 12466 0 0][uf 5 13 18 5 115]All right, wanna race again today?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 4 65535 65535 0 0][uf 3 1 3 0 65535 12473 0 0]...Hey, no cheating![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Hayase grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]It's almost dark...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

