[msg SYS_000_0_0]
[uf 0 5 65278][uf 2 1]If you load the data you save here, you will start the game over, carrying over certain attributes from your clear data.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If you overwrite the original save, you will be unable to continue playing from that point in the game.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If you upload your clear data to the network, you will only be able to load it through the network. We recommend you save clear data to the console.[n][uf 1 1][e]

[msg SYS_001_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Save clear data?[n][uf 1 1][e]

[msg SYS_002_0_0]
[uf 0 5 65278][uf 2 1][uf 1 4 1]Clear data has not been saved to the console. Are you sure you want to return to the title screen?[n][uf 1 1][e]

