[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]The main character's [uf 4 30 2 1 1 0][n]and determination lit a fire in my soul...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]The cinematic shots filled with beauty and[n][uf 4 30 1 1 1 0] made me appreciate the arts...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Watching the characters use body language to[n]communicate honed my [uf 4 30 0 1 1 0]...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Watching how the kids faced their[n]fears gave me some [uf 4 30 2 1 1 0]...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]My heart was captivated by the[n][uf 4 30 1 1 1 0] in this epic love story...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Seeing someone earnestly pursue the[n]truth helped refine my [uf 4 30 0 1 1 0]...[n][uf 1 1][e]

