[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]I hear you're the one taking care of it, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 1 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 5 1 25 25]Looks like it's shaping up quite nicely. The chairman was right to put you in charge.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 8 0 0]I've been told it was left in your care, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]I know it sounds like a lot of work, but it might be nice to try growing a thing or two.[n][uf 1 1][e]

