[msg MSG_001_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 3 0 65535 13002 0 0]I've been waiting for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0]I've called you here so that I may offer you another form of assistance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0]Now that you've been nurturing your powers throughout your exploration, I shall reveal to you more secrets of fusion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0]I am certain that you will find this to be of great benefit.[n][uf 1 1][e]

[msg PFM_003_0_0]
[uf 0 5 65278][uf 2 1]New combinations have been added to Special Fusion.[n][uf 1 1][e]

[msg MSG_004_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 3 0 65535 13016 0 0]I shall continue to observe as you progress further along your journey.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0]That is all I'd like to say. Now, if you would, Elizabeth?[n][uf 1 1][e]

