[msg MSG_000_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 5]So this is Tartarus from the inside...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 5]This is only the second time anyone has come here without special equipment.[n][uf 1 1][e]

[msg MSG_001_0_0 [Downcast Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 6]......[n][uf 1 1][e]

[msg MSG_002_0_0 [Middle-Aged Researcher]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 3]Normal weaponry is useless against Shadows. Anything you brought provides little more than peace of mind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 3]Everyone here has had their potential developed in our labs. That alone should suffice for protection.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 3]Though should you get devoured, that would provide us with valuable data as well, heheheh...[n][uf 1 1][e]

[msg MSG_003_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 5]Ugh... Is there anyone left in the Ergo Division who isn't a psycho?[n][uf 1 1][e]

[msg MSG_004_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 5]In any case, sir...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 5]Are you all right with this? I mean... with bringing your daughter here.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 254 0 5 65535 0 0][uf 3 1 1 0 0 10 0 0]I don't mind at all. I myself requested to come along.[n][uf 1 1][e]

[msg MSG_006_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]...You heard her.[n][uf 1 1][e]

[msg MSG_007_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 5]...My apologies, sir. I overstepped.[n][uf 1 1][e]

[msg MSG_008_0_0 [Downcast Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 6]......[n][uf 1 1][e]

[msg MSG_009_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 5]Hey, what's wrong...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Downcast Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 6]Ngh... Agh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 6]Aaagh! Gaaaaaah![n][uf 1 1][e]

[msg MSG_011_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 5]Wh-What the...!?[n][uf 1 1][e]

[msg MSG_012_0_0 [Middle-Aged Researcher]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 3]Eugh...! It appears we need to conduct further research in artificially developing the potential.[n][uf 1 1][e]

[msg MSG_013_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 5]Both of you, stand back![n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 254 8 5 65535 0 0][uf 3 1 1 0 0 20 0 0]So that's... a Shadow.[n][uf 1 1][e]

[msg MSG_015_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 5]You little—![n][uf 1 1][e]

[msg MSG_016_0_0 [Stern-Faced Bodyguard]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 5]Sir! Miss![n][uf 1 1][e]

[msg MSG_017_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Gah...![n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 254 8 5 65535 0 0][uf 3 1 1 0 0 24 0 0]Father![n][uf 1 1][e]

[msg MSG_019_0_0 [Middle-Aged Researcher]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 3]Did you see that!? Incredible, absolutely incredible! Such power![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 3]It's a Persona! I was right! People can use them![n][uf 1 1][e]

[msg MSG_020_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Mitsuru![n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 254 10 5 65535 0 0][uf 3 1 1 0 0 28 0 0]Father... I'm glad... you're safe...[n][uf 1 1][e]

[msg MSG_022_0_0 [Middle-Aged Researcher]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 3]That was wonderful, Miss Mitsuru! Of course you would be the first one to awaken your potential naturally![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 3]With this, the future truly does seem bright![n][uf 1 1][e]

[msg MSG_023_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Why the hell are you celebrating!?[n][uf 1 1][e]

[msg MSG_024_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Now Mitsuru will be condemned to a life of atonement...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]She'll spend her prime years bound to our vile legacy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]...And you call that "bright."[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 254 10 5 65535 0 0][uf 3 1 1 0 0 35 0 0]Don't worry, Father... This is what I wanted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 254 10 5 65535 0 0][uf 3 1 1 0 0 36 0 0]I will... protect you...[n][uf 1 1][e]

[msg MSG_026_0_0 [Takeharu Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 224 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Mitsuru...[n][uf 1 1][e]

