[msg MND_LASTWORD_NIGHT]
[uf 0 5 65278][uf 2 1]...It's gotten late. I should[n]head back to my room...[n][uf 1 1][e]

[msg MND_LASTWORD_AFTERNOON]
[uf 0 5 65278][uf 2 1]...It's almost nighttime. I should[n]head back to my room...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Lessons in Etiquette"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A quiz with right-or-wrong questions on[n]manners popped up on the screen...[n][uf 1 1][e]

[msg MSG_007_0_0 [Lessons in Etiquette]]
[uf 0 5 65278][uf 2 1]Q: Should you arrive ten minutes early to important meetings?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A: No. You should arrive ten minutes early to all meetings, not just important ones.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]The tricky questions continue...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I finished answering a large[n]number of quiz questions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The manners I learned might make[n]me more attractive and respected...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Virtual Diet"...[n][uf 1 1][e]

[msg MSG_011_0_0 [Virtual Diet]]
[uf 0 5 65278][uf 2 1]Now, you too can have a slim body without having to suffer through exercise![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]First, train yourself to curb your appetite by looking at blue food![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Looking at all the blue food on-screen[n]is making me lose my appetite...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I finished watching all the videos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I have a slimmer,[n]more attractive body already...[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Pickup Line Master"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems to be a game where you[n]talk to 108 different characters.[n][uf 1 1][e]

[msg MSG_015_0_0 [Pickup Line Master]]
[uf 0 5 65278][uf 2 1]Love comes in all shapes and sizes! Let's get you hooked up with someone too![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I guess it's a love simulation game.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I should try to pick answers that will[n]make the other character happy...[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]...I ended up forming a relationship[n]with an aging, 15-year-old dog.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I can effectively convey my[n]charm to just about anyone now...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Digital Cram School"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems to be a set of practice questions[n]from a famous school in the mountains.[n][uf 1 1][e]

[msg MSG_019_0_0 [Digital Cram School]]
[uf 0 5 65278][uf 2 1]Whether you're brilliant or average, your journey here begins by answering questions all the same.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I should try some questions in the[n]areas I'm studying right now...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]I finished answering a challenging,[n]yet satisfying set of questions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I've gotten better[n]at thinking outside the box...[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Language Made Easy"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There are conversational dialogues paired[n]with pictures for overseas travelers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The protagonist wants to go to the airport,[n]but keeps getting distracted on the way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I watch as they speak with broken[n]grammar to get a discounted burger...[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Eventually, the protagonist overcame the[n]language barrier and reached the airport.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel more confident in[n]my speaking skills now...[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Sage Brain Training"...[n][uf 1 1][e]

[msg MSG_025_0_0 [Sage Brain Training]]
[uf 0 5 65278][uf 2 1]With the right training, you can have the mind of a sage! Use these puzzles to train your brain![n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Looks like puzzles involving shapes,[n]wordplay, and numbers...[n][uf 1 1][e]

[msg MSG_027_0_0 [Sage Brain Training]]
[uf 0 5 65278][uf 2 1]Your IQ level is... "Sage Next Door"![n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]...I don't know how to feel about the results.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But, if nothing else, I feel a little[n]smarter after training my brain.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Animal Othello"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This looks like a game where you play[n]Othello against cutely drawn animals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The elephant begins to bawl[n]after I beat it in Othello...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I keep playing, and the cute animals[n]continue to weep when they lose...[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]I managed to make all the[n]animals break into tears.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They seem to be staring through[n]the screen with big, pitiful puppy eyes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...I feel like this experience has[n]strengthened my mental fortitude.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"TypinGhoul"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like a game where you[n]take down zombies by typing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The zombies are explaining the[n]rules very kindly to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...I don't feel like they're the enemy.[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]I decimated the zombies that patiently[n]provided me with a helpful tutorial...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I obtained unwavering[n]mental strength from this.[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Sengoku Chronicles"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems I can experience the Sengoku[n]period through the eyes of a warlord.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A cuckoo bird chose for me. Guess I'll[n]be seeing the life of Tokugawa Ieyasu...[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]I finished experiencing the[n]eventful life of Ieyasu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel inspired by the man who unified[n]the country amidst an age of turmoil...[n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Part-Time Master"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Looks like it teaches skills in customer[n]service, accounting, and product stocking.[n][uf 1 1][e]

[msg MSG_042_0_0 [Part-Time Master]]
[uf 0 5 65278][uf 2 1]Improve your skill set! Start with a promotion, end up a billionaire![n][uf 1 1][e]

[msg MND_043_0_0]
[uf 0 5 65278][uf 2 1]A series of easy-to-understand[n]instructions begins to play...[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]I finished learning about a[n]number of workplace skills.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I can apply this knowledge[n]to my part-time work![n][uf 1 1][e]

[msg SYS_JOBMANEY_0_0]
[uf 0 5 65278][uf 2 1]The amount of money you can earn from part-time jobs has increased.[n][uf 1 1][e]

[msg MND_045_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Veggie Farmer Sim"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like a game that[n]simulates raising crops.[n][uf 1 1][e]

[msg MSG_046_0_0 [Veggie Farmer Sim]]
[uf 0 5 65278][uf 2 1]Plants don't need "love"—they need appropriate amounts of nutrients and water![n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]A knowledgeable-seeming dwarf[n]is giving a lecture on agriculture.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I should follow their instructions[n]and adjust the water and fertilizer...[n][uf 1 1][e]

[msg MND_048_0_0]
[uf 0 5 65278][uf 2 1]I was able to produce a bountiful harvest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I learned something tangible[n]about growing vegetables...[n][uf 1 1][e]

[msg SYS_VEGETABLE_0_0]
[uf 0 5 65278][uf 2 1]The amount of crops you can harvest from the rooftop planters has increased.[n][uf 1 1][e]

[msg MND_049_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Muscle Boot Camp"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems to be educational software[n]that teaches you about muscles.[n][uf 1 1][e]

[msg MSG_050_0_0 [Muscle Boot Camp]]
[uf 0 5 65278][uf 2 1]In this short session, you'll learn 600 ways to use your muscles![n][uf 1 1][e]

[msg MND_051_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]An immense amount of information[n]is being presented at a rapid pace...[n][uf 1 1][e]

[msg MSG_052_0_0 [Muscle Boot Camp]]
[uf 0 5 65278][uf 2 1]Congratulations! You are hereby promoted to Muscle Sergeant![n][uf 1 1][e]

[msg MND_053_0_0]
[uf 0 5 65278][uf 2 1]I sure learned a lot about[n]how to use my muscles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I have more stamina[n]now that I've watched this...[n][uf 1 1][e]

[msg PFM_HPUP7_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 34]Max HP[uf 0 1 27] increased by [uf 0 1 45]7[uf 0 1 27].[n][uf 1 1][e]

[msg MND_054_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Image Muscle Trainer"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like software that stimulates[n]muscles through image training.[n][uf 1 1][e]

[msg MSG_055_0_0 [Image Muscle Trainer]]
[uf 0 5 65278][uf 2 1]Now watch these strength training videos and imagine yourself participating...[n][uf 1 1][e]

[msg MND_056_0_0]
[uf 0 5 65278][uf 2 1]I watch the videos and picture[n]myself working out in my head...[n][uf 1 1][e]

[msg MND_057_0_0]
[uf 0 5 65278][uf 2 1]For some reason, I feel as exhausted[n]as if I actually did the training.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like the image training may have[n]actually strengthened my muscles...[n][uf 1 1][e]

[msg PFM_HPUP9_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 34]Max HP[uf 0 1 27] increased by [uf 0 1 45]9[uf 0 1 27].[n][uf 1 1][e]

[msg MND_058_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Mindful Boot Camp"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It appears to be software that[n]teaches mindfulness meditation.[n][uf 1 1][e]

[msg MSG_059_0_0 [Mindful Boot Camp]]
[uf 0 5 65278][uf 2 1]Even those who have a hard time concentrating will be able to focus their minds with this program.[n][uf 1 1][e]

[msg MND_060_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Lessons on proper breathing[n]and posture begin to play...[n][uf 1 1][e]

[msg MND_061_0_0]
[uf 0 5 65278][uf 2 1]My head feels clearer than before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like the meditation has[n]helped me train my mind...[n][uf 1 1][e]

[msg PFM_SPUP5_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 34]Max SP[uf 0 1 27] increased by [uf 0 1 45]5[uf 0 1 27].[n][uf 1 1][e]

[msg MND_062_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Mental Instructor"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems to teach breathing techniques[n]and stretches at varying difficulty levels.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I follow the on-screen instructions[n]and begin diaphragmatic breathing...[n][uf 1 1][e]

[msg MND_063_0_0]
[uf 0 5 65278][uf 2 1]I was able to reach the final level, where[n]I could hear my true inner thoughts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like this spiritual training[n]has helped me free my mind...[n][uf 1 1][e]

[msg PFM_SPUP7_0_0]
[uf 0 5 65278][uf 2 1][uf 0 1 34]Max SP[uf 0 1 27] increased by [uf 0 1 45]7[uf 0 1 27].[n][uf 1 1][e]

[msg MND_064_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]The Umiushi official website...[n][uf 1 1][e]

[msg MSG_065_0_0 [Umiushi Official Website]]
[uf 0 5 65278][uf 2 1]MEMBERS ONLY: Exclusive takeout perks![n][uf 1 1][e]

[msg MND_067_0_0]
[uf 0 5 65278][uf 2 1]It looks like if I register, I'll be able[n]to order takeout from Umiushi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I should enter the membership code[n]from the [uf 4 4 1 37 2 0]...[n][uf 1 1][e]

[msg MSG_068_0_0 [Umiushi Official Website]]
[uf 0 5 65278][uf 2 1]Thank you for registering! We hope you enjoy the Umiushi taste in the comfort of your own home![n][uf 1 1][e]

[msg MND_069_0_0]
[uf 0 5 65278][uf 2 1]Looks like I've successfully[n]become a registered member.[n][uf 1 1][e]

[msg SYS_UMIUSHIOPEN_0_0]
[uf 0 5 65278][uf 2 1]You are now able to order takeout from Umiushi at the Iwatodai strip mall.[n][uf 1 1][e]

[msg MND_070_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Iwatodai Forum"... Looks like[n]a message board for locals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The most recently updated topic is...[n][uf 1 1][e]

[msg MSG_071_0_0 [Iwatodai Forum]]
[uf 0 5 65278][uf 2 1][NEW?] Secret about the vending machine in front of the station[n][uf 1 1][e]

[msg MND_072_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I'll take a look at this thread...[n][uf 1 1][e]

[msg MSG_073_0_0 [Iwatodai Forum Replies]]
[uf 0 5 65278][uf 2 1]anonymous10: when r they gonna fix that vending machine lol[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]anonymous11: wait what's this secret???[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]anonymous14: @anonymous11 you can actually still buy drinks that are marked as sold out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]the machines broken so theres drinks marked sold out when its not.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]just press the button. i recommend the 4biotic pack.[n][uf 1 1][e]

[msg MND_074_0_0]
[uf 0 5 65278][uf 2 1]It looks like drinks that are marked[n]as sold out can still be bought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should try it out on the [uf 0 1 2]vending[uf 0 1 27][n][uf 0 1 2]machine in front of Iwatodai Station[uf 0 1 27].[n][uf 1 1][e]

[msg MND_075_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Moonlight Channel"... Looks like an[n]unofficial forum for Gekkoukan High.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Topics include things like, "3rd-years[n]only!" and, "Who do u think is hot?"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Seems like the newest topic is...[n][uf 1 1][e]

[msg MSG_076_0_0 [Moonlight Channel]]
[uf 0 5 65278][uf 2 1]Anyone try the taiyaki at the school store?[n][uf 1 1][e]

[msg MND_077_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I'll take a look at this...[n][uf 1 1][e]

[msg MSG_078_0_0 [Moonlight Channel Replies]]
[uf 0 5 65278][uf 2 1]aaaaaaaaa: never seen this on sale. why is there such a limited amount?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sardine: i saw someone complain to the vendor about this[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Beta: Good news! The taiyaki is gonna be a permanent item now![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I asked about it and apparently there were a lot of requests for it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It sounds like they'll have it in stock daily now![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]TennisLover: wait so we can srsly get it whenevs now???[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Oda Nobunaga: ima get one[n][uf 1 1][e]

[msg MND_079_0_0]
[uf 0 5 65278][uf 2 1]It seems like a special [uf 0 1 2]taiyaki[uf 0 1 27] will[n]be available at the school store.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should take a look[n]next time I'm there...[n][uf 1 1][e]

[msg MND_080_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"My Lovely Veggie Garden Blog"...[n]Looks like it's about home gardening.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The blogger seems to have expressed[n]their love by writing entirely in baby talk...[n][uf 1 1][e]

[msg MSG_081_0_0 [My Lovely Veggie Garden Blog]]
[uf 0 5 65278][uf 2 1]Hewwo~ Hab you eber seen a tomato this shoiny!? [uf 1 3 139][n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It's shooooo pwetty!!! [uf 1 3 146] And it's vewy rare. [uf 1 3 135][uf 1 3 135][n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Did you know [uf 0 1 2]Golden Tomato Sprouts[uf 0 1 27] are onwy avaiwable at certain fwower shops!? [uf 1 3 145][n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Yew can find some at Raffwesia Fwower Shop over at Port Iswand Station! Yaaay!! [uf 1 3 136][uf 1 3 146][n][uf 1 1][e]

[msg MND_082_0_0]
[uf 0 5 65278][uf 2 1]It looks like new vegetable seedlings[n]will be available for purchase.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should [uf 0 1 2]stop by Rafflesia next[uf 0 1 27][n][uf 0 1 2]time I'm at Port Island Station[uf 0 1 27]...[n][uf 1 1][e]

[msg MND_100_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The "revenge website"... This must[n]be the site from those rumors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There are all kinds of[n]requests posted here...[n][uf 1 1][e]

[msg MSG_101_0_0 [Revenge Website Post]]
[uf 0 5 65278][uf 2 1][REDACTED]: I know he's always talking about me behind my back.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I hate it. I want revenge.[n][uf 1 1][e]

[msg MND_102_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]

[msg MND_103_0_0]
[uf 0 5 65278][uf 2 1]The hate-filled posts pleading[n]for revenge go on and on...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Bearing witness to the ugly side of[n]humanity has strengthened my resolve...[n][uf 1 1][e]

[msg MND_104_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I can't access the site the[n]URL normally leads to...[n][uf 1 1][e]

[msg MND_105_0_0]
[uf 0 5 65278][uf 2 1]It seems the revenge website[n]has been shut down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should do something[n]else to pass the time...[n][uf 1 1][e]

[msg MND_106_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"The Book of Nyx"... It looks like[n]a site for those who worship Nyx.[n][uf 1 1][e]

[msg MSG_107_0_0 [The Book of Nyx]]
[uf 0 5 65278][uf 2 1]The end that frees us from suffering is nigh.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We are all but fools. We perpetuate our own fear and misery, and allow them to control us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But Nyx-sama will show us the way. Nyx-sama will save us all...[n][uf 1 1][e]

[msg MND_108_0_0]
[uf 0 5 65278][uf 2 1]It seems as though the blog hasn't[n]been updated in a little while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I need to be ready for the fight[n]that awaits us on January 31st...[n][uf 1 1][e]

[msg PFM_SPUP5_1_0]
[uf 0 5 65278][uf 2 1][uf 0 1 34]Max SP[uf 0 1 27] increased by [uf 0 1 45]5[uf 0 1 27].[n][uf 1 1][e]

[msg MND_194_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Effective Security Measures Online"...[n]This seems to be a website that helps[n]with training security team members...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There's a list of self-defense videos here,[n]each with a detailed text explanation...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I guess I'll start with the[n]most-watched video...[n][uf 1 1][e]

[msg MND_196_0_0]
[uf 0 5 65278][uf 2 1]I watched a how-to video on[n]subduing violent individuals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned the importance of having[n]the will to stand up to an enemy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I can use what I learned[n]in our fights in Tartarus...[n][uf 1 1][e]

[msg SYS_170_0_0]
[uf 0 5 65278][uf 2 1]You learned how to use [uf 0 1 2]Ambush[uf 0 1 27]![n][uf 1 1][e]

[msg MND_197_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"The Art of Human Demolition"... Looks[n]like it's about the body's weak points.[n][uf 1 1][e]

[msg MSG_198_0_0 [The Art of Human Demolition]]
[uf 0 5 65278][uf 2 1]Humans know their own weaknesses, and here, we'll explain how to take full advantage of them![n][uf 1 1][e]

[msg MND_199_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I glance at the smiling mascot character,[n]Demolii-tan, and continue to read...[n][uf 1 1][e]

[msg MND_200_0_0]
[uf 0 5 65278][uf 2 1]I winced a bit, but managed to learn[n]new approaches to hit where it hurts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I've learned how to examine[n]the enemy before making the first strike...[n][uf 1 1][e]

[msg SYS_175_0_0]
[uf 0 5 65278][uf 2 1]Ambush has been enhanced! When attacking an enemy from behind, you will now inflict Distress without fail.[n][uf 1 1][e]

[msg MND_201_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Histories of the World's Greatest"...[n]Looks like trivia on historical figures.[n][uf 1 1][e]

[msg MSG_202_0_0 [Histories of the World's Greatest]]
[uf 0 5 65278][uf 2 1][TODAY'S TOPIC] Leaders in Battle[n][uf 1 1][e]

[msg MND_203_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I think I'll read more about this...[n][uf 1 1][e]

[msg MND_204_0_0]
[uf 0 5 65278][uf 2 1]I read about the decisions historical[n]leaders made in pursuit of their goals.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I've learned how to maintain[n]morale in the face of adversity...[n][uf 1 1][e]

[msg SYS_182_0_0]
[uf 0 5 65278][uf 2 1]Ambush has been enhanced! After successfully attacking an enemy from behind, your Theurgy gauge will rise.[n][uf 1 1][e]

[msg MND_205_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me see what this URL leads to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Ninja Hideout"... It looks like a foreign[n]forum where people post about ninjas.[n][uf 1 1][e]

[msg MSG_206_0_0 [Ninja Hideout]]
[uf 0 5 65278][uf 2 1]Ninpo: Ninja Research Score, 222[n][uf 1 1][e]

[msg MND_207_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Looks like people are serious about[n]becoming real ninjas. I'll take a look...[n][uf 1 1][e]

[msg MSG_208_0_0 [Ninja Hideout Post]]
[uf 0 5 65278][uf 2 1]no_ninnin: Ninjas have unique breathing methods, such as "futae-ibuki," "okinaga," and more...[n][uf 1 1][e]

[msg MND_209_0_0]
[uf 0 5 65278][uf 2 1]I found interesting breathing techniques[n]that ninjas used for long-distance travel.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I can use this to run[n]swiftly like a ninja myself...[n][uf 1 1][e]

[msg SYS_186_0_0]
[uf 0 5 65278][uf 2 1]Ambush has been enhanced! The amount of time needed to dash before being able to Ambush has been decreased.[n][uf 1 1][e]

[msg MND_235_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]This site seems to require an "offering."[n]Luckily, the note came with a free pass...[n][uf 1 1][e]

[msg MSG_236_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]Thank you for the offering, and welcome to the Matchmaking Supershrine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Picture anyone you wish to intensify your relationship with and click the button below.[n][uf 1 1][e]

[msg MND_237_0_0]
[uf 0 5 65278][uf 2 1]Who should I think of...?[n][uf 1 1][e]

[msg MND_251_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I'll think about [uf 2 4 0][n]and click the button...[n][uf 1 1][e]

[msg MND_252_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I'll think about the monk[n]and click the button...[n][uf 1 1][e]

[msg MND_269_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I'll think about Bunkichi-san and[n]Mitsuko-san and click the button...[n][uf 1 1][e]

[msg MSG_240_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]Praying... Current progress: 3%[n]Continue focusing while you wait.[n][uf 1 1][e]

[msg MND_241_0_0]
[uf 0 5 65278][uf 2 1]The progress bar seems stuck at 3%...[n]I'll continue thinking of [uf 2 4 0].[n][uf 1 1][e]

[msg MND_254_0_0]
[uf 0 5 65278][uf 2 1]The progress bar seems stuck at 3%...[n]I'll continue thinking of the monk.[n][uf 1 1][e]

[msg MND_267_0_0]
[uf 0 5 65278][uf 2 1]The progress bar seems stuck at 3%...[n]I'll continue thinking of Bunkichi-san[n]and Mitsuko-san.[n][uf 1 1][e]

[msg MSG_244_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]Prayer complete. Your relationship has intensified.[n][uf 1 1][e]

[msg MND_243_0_0]
[uf 0 5 65278][uf 2 1]It seems the prayer is done...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Having meditated on our[n]relationship, [uf 2 4 0] feels[n]more important to me...[n][uf 1 1][e]

[msg MND_256_0_0]
[uf 0 5 65278][uf 2 1]It seems the prayer is done...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Having meditated on our relationship,[n]the monk feels more important to me...[n][uf 1 1][e]

[msg MND_264_0_0]
[uf 0 5 65278][uf 2 1]It seems the prayer is done...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Having meditated on our relationship,[n]Bunkichi-san and Mitsuko-san feel[n]more important to me...[n][uf 1 1][e]

[msg MSG_258_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]If you would like to ask for another prayer, please purchase another Offering Pass.[n][uf 1 1][e]

[msg MND_247_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]Let me try the prepaid Offering Pass[n]that came with the URL note again...[n][uf 1 1][e]

[msg MSG_248_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]Picture anyone you wish to intensify your relationship with and click the button below.[n][uf 1 1][e]

[msg MND_249_0_0]
[uf 0 5 65278][uf 2 1]Who should I think of...?[n][uf 1 1][e]

[msg MSG_259_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]Praying... Current progress: 3%[n]Continue focusing while you wait.[n][uf 1 1][e]

[msg MND_260_0_0]
[uf 0 5 65278][uf 2 1]The progress bar seems stuck at 3%...[n]I'll continue thinking of [uf 2 4 0].[n][uf 1 1][e]

[msg MND_255_0_0]
[uf 0 5 65278][uf 2 1]It seems the prayer is done...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Having meditated on our[n]relationship, [uf 2 4 0] feels[n]more important to me...[n][uf 1 1][e]

[msg MSG_023_0_0 [Matchmaking Supershrine]]
[uf 0 5 65278][uf 2 1]If you would like to ask for another prayer, please purchase another Offering Pass.[n][uf 1 1][e]

[msg MND_164_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Intro to Dynamic and Kinetic Visual Acuity"...[n][uf 1 1][e]

[msg MSG_165_0_0 [Screen]]
[uf 0 5 65278][uf 2 1]Dynamic and kinetic visual acuity is the ability to process moving visual input and react accordingly to it.[n][uf 1 1][e]

[msg MND_168_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]...I followed a series of balls and shapes[n]that moved across the screen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel I've become more sensitive[n]to motion in my peripheral vision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This might be useful when[n]exploring Tartarus...[n][uf 1 1][e]

[msg MND_166_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]I decided to first try the training mode.[n][uf 1 1][e]

[msg MND_173_0_0]
[uf 0 5 65278][uf 2 1]I've achieved a high score and[n]survived three lightyears.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel as if I learned the importance of[n]observing an enemy for weak points...[n][uf 1 1][e]

[msg MND_171_0_0]
[uf 0 5 65278][uf 2 1]"Simple Shooting Game"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]This looks like a game where I[n]shoot down enemies to survive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hitting the enemies' weak points[n]will destroy them faster.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I look closely, I can see a mark[n]where the enemy's weakness is...[n][uf 1 1][e]

[msg MND_176_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Training + Mind"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like I have to choose the most[n]positive-sounding phrase out of the group.[n][uf 1 1][e]

[msg MSG_177_0_0 [Screen]]
[uf 0 5 65278][uf 2 1]A) "Tastes bad," B) "A unique taste," C) "Not really my thing," D) "Some people might like it."[n][uf 1 1][e]

[msg MND_178_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 25 60]I tried selecting the most[n]positive-sounding one...[n][uf 1 1][e]

[msg MND_180_0_0]
[uf 0 5 65278][uf 2 1]After that, I solved puzzles and[n]got inordinate amounts of praise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like my self-confidence[n]has improved...[n][uf 1 1][e]

[msg MND_183_0_0]
[uf 0 5 65278][uf 2 1][uf 4 22 0 1 61 5 60]"Reaction Training"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"Watch with your eyes, decide with[n]your brain, and move with your body!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Seems to be a game of rapidly tapping[n]glowing orbs that fly onto the screen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I couldn't quite keep up, but I stuck[n]with it until I got the hang of it...[n][uf 1 1][e]

[msg MND_184_0_0]
[uf 0 5 65278][uf 2 1]I was able to get a high score by[n]diligently continuing to play.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel I've gained the ability to[n]react even quicker to things...[n][uf 1 1][e]

[msg MND_215_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can't think of anyone I want[n]a stronger relationship with...[n][uf 1 1][e]

[msg MND_217_0_0]
[uf 0 5 65278][uf 2 1]Fortune[n][uf 1 1][e]

[sel SEL_218_0_0 top]
[uf 0 5 65278][uf 2 1]Yukari Takeba[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Fuuka Yamagishi[uf 4 27 6 0][e]
[uf 0 5 65278][uf 2 1]Mitsuru Kirijo[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Aigis[uf 4 27 7 0][e]
[uf 0 5 65278][uf 2 1]Team Manager[uf 4 27 106 0][e]
[uf 0 5 65278][uf 2 1]Treasurer[uf 4 27 109 0][e]
[uf 0 5 65278][uf 2 1]Classmate[uf 4 27 101 0][e]
[uf 0 5 65278][uf 2 1]Student Council[uf 4 27 102 0][e]
[uf 0 5 65278][uf 2 1]Track Team[uf 4 27 105 0][e]
[uf 0 5 65278][uf 2 1]Art Club[uf 4 27 108 0][e]
[uf 0 5 65278][uf 2 1]Transfer Student[uf 4 27 112 0][e]
[uf 0 5 65278][uf 2 1]Old Couple[uf 4 27 103 0][e]
[uf 0 5 65278][uf 2 1]Rival Athlete[uf 4 27 115 0][e]
[uf 0 5 65278][uf 2 1]Girl at the Shrine[uf 4 27 110 0][e]
[uf 0 5 65278][uf 2 1]Dying Young Man[uf 4 27 117 0][e]
[uf 0 5 65278][uf 2 1]Gourmet King[uf 4 27 116 0][e]
[uf 0 5 65278][uf 2 1]Businessman[uf 4 27 113 0][e]
[uf 0 5 65278][uf 2 1]Unusual Monk[uf 4 27 114 0][e]
[uf 0 5 65278][uf 2 1]Online Game[uf 4 27 107 0][e]

[msg MND_220_0_0]
[uf 0 5 65278][uf 2 1]Who should I think of...?[n][uf 1 1][e]

[msg MND_222_0_0]
[uf 0 5 65278][uf 2 1]I don't think we could get any[n]closer than we already are...[n][uf 1 1][e]

[msg MND_233_0_0]
[uf 0 5 65278][uf 2 1]I feel like the bond I have with[n][uf 2 4 0] has grown stronger...[n][uf 1 1][e]

[msg MND_265_0_0]
[uf 0 5 65278][uf 2 1]I feel like the bond I have with[n]the monk has grown stronger...[n][uf 1 1][e]

[msg MND_262_0_0]
[uf 0 5 65278][uf 2 1]I feel like my bond with Bunkichi-san[n]and Mitsuko-san has grown stronger...[n][uf 1 1][e]

[msg MND_261_0_0]
[uf 0 5 65278][uf 2 1]I already used the Offering Pass, but[n]maybe I don't want to do this after all...[n][uf 1 1][e]

[sel SEL_262_0_0 top]
[uf 0 5 65278][uf 2 1]Actually, I'll think of someone.[e]
[uf 0 5 65278][uf 2 1]Yeah, I'll quit.[e]

[sel SEL_263_0_0 top]
[uf 0 5 65278][uf 2 1]Use the matchmaking site[e]
[uf 0 5 65278][uf 2 1]Don't[e]

