[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 1 0 0]I'm getting that reading again. And it's... in the form of a human?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 2 0 0]That's so strange... It feels just like a real person.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 3 0 0]But... How could there be anyone else here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 50 0 0][uf 3 1 1 0 0 4 0 0][uf 4 25 6]Huh...[n][uf 1 1][e]

