[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Koromaru seems pleased...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I brushed him as thoroughly as I could...[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 1 0 0]Arf![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Koromaru brought this [uf 4 4 1 37 0 0].[n]Is he thanking me for brushing him...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 2 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I played with Koromaru for a while[n]before heading back to my room.[n][uf 1 1][e]

