[msg MSG_000_0_0]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[sel SEL_YES_NO top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Just a moment.[e]

[msg MSG_UPSTAIR_MITU_BATTLE_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Some members are in battle. Do you want to proceed without them?[n][uf 1 1][e]

[msg MSG_UPSTAIR_MITU_MEMBER_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I see. Then we'll continue on and rendezvous with them later.[n][uf 1 1][e]

[msg MSG_UPSTAIR_FUKA_BATTLE_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Some of our team members are still fighting. Will you continue without them?[n][uf 1 1][e]

[msg MSG_UPSTAIR_FUKA_MEMBER_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]All right. Well then, let's keep going![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]We'll meet up with them later.[n][uf 1 1][e]

[msg MSG_UPSTAIR_MITU_NPC_INF [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4101 0 0]There seems to be a person on this floor. Will you leave without them?[n][uf 1 1][e]

[msg MSG_UPSTAIR_MITU_NPC_IGN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4093 0 0]All right, let's go.[n][uf 1 1][e]

[msg MSG_UPSTAIR_FUKA_NPC_INF [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5092 0 0]Someone is still on this floor! Are you sure you want to move on?[n][uf 1 1][e]

[msg MSG_UPSTAIR_FUKA_NPC_IGN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5028 0 0]Okay, we'll keep going.[n][uf 1 1][e]

[msg MSG_TUTO_Shift01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4060 0 0]Wait. There could be more powerful enemies waiting ahead.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Go ahead with the others. And be sure to keep at least one other person with you.[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy01_M [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 3 0 65535 4098 0 0]Something feels different about the next floor![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I sense something more powerful... Like a tangible force of will. Stay alert.[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy01_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 3 0 65535 5073 0 0]I sense something really strong directly below you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]You could be in for a fight as soon as you head down. Are you ready?[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy02_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]I'm picking up a strong reading directly below![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy03_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]It looks like the enemy is holed up below.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy04_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]The final dead end should be below you.[n][uf 1 1][e]

[msg SYS_TUTO_FLOOR152_INFO]
[uf 0 5 65278][uf 2 1]The story will develop significantly beyond this point. It is recommended to save your game first at the Desert of Doors.[n][uf 1 1][e]

[msg MSG_TUTO_StrongEnemy04_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_FLOOR08_NG_F [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 52 50 0 0][uf 3 1 3 0 65535 5073 0 0]Hold on![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]There's something about the door on that floor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0]Aigis, could I ask you to investigate that door?[n][uf 1 1][e]

