[msg MSG_STOP_GO_OUT_MITURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4024 0 0]We cannot allow you to go out after dark.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sorry, but rules are rules.[n][uf 1 1][e]

[msg MSG_STOP_GO_OUT_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1006 0 0]Hey, you should stay in bed![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I don't want you to overdo it... Why don't you call it a day?[n][uf 1 1][e]

[msg MND_STOP_INTO_MYROOM [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]I was told to go to the fourth floor...[n][uf 1 1][e]

[msg MSG_RoomHit_NG_GoOut [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1007 0 0]Hey, where are you going!? It's not safe outside![n][uf 1 1][e]

[msg MSG_RoomHit_NG2Fto1F_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1103 0 0]Wait, not that way! We need to go up![n][uf 1 1][e]

[msg MSG_RoomHit_NG3Fto2F_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1100 0 0]What are you doing!? We have to go up to get away![n][uf 1 1][e]

[msg MND_AreaChange_Common [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's not safe down below...[n][uf 1 1][e]

[msg MND_010_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's raining heavily outside...[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2102 0 0]Hey! Where're you goin'?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2037 0 0]You shouldn't go out there, man! You're gonna catch a cold or something...[n][uf 1 1][e]

