[msg MSG_000_0_0 [Club Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Well, Hiraga-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]One of the judges saw a lot of potential in you as an artist and had an offer for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]If you're interested, they'd be willing to help arrange for you to study abroad. How does that sound?[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Study abroad? Me? A-As an artist?[n][uf 1 1][e]

[msg MSG_001_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Wow, as in overseas? Hiraga-senpai's amazing![n][uf 1 1][e]

[msg MSG_001_5_0 [Panicky Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 150]Hey, are you guys from the art club!?[n][uf 1 1][e]

[msg MSG_001_6_0 [Panicky Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 150]Have you seen Hiraga!?[n][uf 1 1][e]

[msg MSG_001_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Um, he's in the faculty office now for—[n][uf 1 1][e]

[msg MSG_002_0_0 [Panicky Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 150]Hiraga! I've been looking everywhere for you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 150]Mikarin just fainted! Come quick![n][uf 1 1][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Huh? Oh! Okay, got it, I'll be right there![n][uf 1 1][e]

[msg MSG_003_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I'm very sorry, but I'll need some time to think about this.[n][uf 1 1][e]

[msg MSG_004_0_0 [Club Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 200]He says he doesn't want to be a doctor...[n][uf 1 1][e]

[msg MSG_004_5_0 [Club Advisor]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 200]But he just can't ignore people in need. That's how he is.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 200]A doctor's son with such an eye for art... I never thought I'd be so jealous of a student.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I don't think anyone's in the mood to celebrate now.[n][uf 1 1][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'll let everyone know what happened. You can head off now if you'd like.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I said goodbye to Fuuka and[n]went back to the dorm.[n][uf 1 1][e]

