[msg TRL_000_0_0 [Uploading Save Data to the Network]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]By saving your game in the NETWORK SLOT, you can upload save data online instead of saving it to the main console storage.[n][uf 1 1][e]

[msg TRL_001_0_0 [Uploading Save Data to the Network]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]You will need an account for PlayStation™Network to utilize the NETWORK SLOT.[n][uf 1 1][e]

[msg TRL_002_0_0 [Uploading Save Data to the Network]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Game data saved using this method can be transferred between PlayStation®4 and PlayStation®5 consoles.[n][uf 1 1][e]

[msg TRL_003_0_0 [Uploading Save Data to the Network]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]However, trophies earned during gameplay on one console [uf 0 1 2]will not transfer[uf 0 1 27] to another console that you transfer your save data to.[n][uf 1 1][e]

