[msg MSG_000_0_0 [Wannabe Follower Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 754]I don't like having a rank system and following orders, so I didn't think I'd like this cult, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 754]But when I joined, it wasn't like that at all. It's not a typical cult or some strict organization.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 754]It's just a guy sharing his beliefs, and people who decide to respect him out of their own accord.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 754]So this cult isn't as strict as I thought it would be. I like that kind of freedom.[n][uf 1 1][e]

