[msg MSG_000_0_0 [Fanatical Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]Deliverance is coming soon. Did you know that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]The Absolute Will is coming from the sky to save us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]You, too, should join us. Cleanse your impure mind and wait for the time to come.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fanatical Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]He's a great man...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]He understands my pain and has answers to all my questions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]Thanks to him, I have accepted the teachings of Nyx.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 700]If only I had the words to explain to you how wonderful it feels...[n][uf 1 1][e]

