[msg MSG_000_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]*gasp* *gasp* *huff*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Just give me a minute... so I can... calm down...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Take as long as you need.[e]
[uf 0 5 65278][uf 2 1]You can do this.[e]

[msg MSG_002_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 5 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 20 5 117]The pain comes and goes... But I'll be fine once it passes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 117 1 25 25]...It's getting better. Thanks.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Right... Thank you, I'm... fine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]The pain comes and goes... But I'll be all right once it passes.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I... stopped taking my medicine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 117 3 25 25]It's not going to cure me anyway, right? It just eases my pain and suffering...[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]That's dangerous.[e]
[uf 0 5 65278][uf 2 1]Why did you stop?[e]

[msg MSG_006_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I know... It's only cutting down what time I have left...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]But, my medicine makes me drowsy, and if my hands go numb and shake, then I can't write...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]I have to finish my story...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 5 13 20 5 117]My medicine makes me drowsy, and if my hands go numb, then I can't write...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I have to finish my story...[n][uf 1 1][e]

[msg MSG_008_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]The reason I haven't finished my story... is because I haven't found the meaning of my life yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I'll get absorbed in my writing... erase it... and then lose sight of how to reach the end.[n][uf 1 1][e]

[msg MSG_008_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]...When I'm with you, I can almost see it... It's because you've been here for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]It seems like you might have given me a reason to finish...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I'm probably writing this book to find my own meaning in life...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]And, if I do find it... If I do finish the story...[n][uf 1 1][e]

[msg MSG_010_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...I hope we have a little more time together, after that.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Kamiki smiled weakly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger now...[n][uf 1 1][e]

[msg MSG_012_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]...The sun... is setting...[n][uf 1 1][e]

[msg MSG_012_5_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]That's it for today, but I hope to see you again.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]I parted ways with Kamiki,[n]then headed back to the dorm.[n][uf 1 1][e]

