[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 1 0 0]Wow, look at all the decorations...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 2 0 0]And they're so elaborate too.[n][uf 1 1][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 3 0 0]...Oh, over there! Those trees are made entirely of lights.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 4 0 0]They're so beautiful...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]They sure are.[e]
[uf 0 5 65278][uf 2 1]So, what's next?[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 5 0 0]Brrr. It's a bit chilly, but I'm really glad we came.[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 6 0 0]Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 6 1 25 25]It's just... such a wonderful night, isn't it?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 8 0 0]Um, I'm not sure...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 40 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 6 3 25 25]Sorry. I didn't really think about what to do after we got here...[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 10 0 0]I, um... I'm happy just being with you.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 11 0 0]Should we go inside? It's getting a little cold out here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 12 0 0]I don't want you to catch a cold.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I talked with Fuuka for a long time.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 13 0 0]I'm having such a good time today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 14 0 0]It's like a dream. I've come through here so many times before, but today it feels special.[n][uf 1 1][e]

[msg MSG_006_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 15 0 0]Oh, that's right, um...[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 16 0 0]These are for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 6 0 25 25]I was thinking of you when I made them.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]DEV: (Item name) received.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 18 0 0]I was originally planning to bake a cake in the spirit of Christmas, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 19 0 0]I'm not that good at baking yet, and I didn't want it to taste bad.[n][uf 1 1][e]

[msg MSG_009_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 20 0 0]But, I think you'll really like these...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 40 0 0][uf 3 1 1 0 0 21 0 0]So, um...[n][uf 1 1][e]

[msg MSG_010_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 40 0 0][uf 3 1 1 0 0 22 0 0]New Year's Eve is just around the corner.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 40 0 0][uf 3 1 1 0 0 23 0 0]If I were still my old self, I wouldn't have wanted to think about that... Especially on a day like this.[n][uf 1 1][e]

[msg MSG_010_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 24 0 0]But I'm a lot different now.[n][uf 1 1][e]

[msg MSG_010_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 25 0 0]Now, I know that time is precious, and I don't want to give up on the future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 40 0 0][uf 3 1 1 0 0 26 0 0]Meeting you was the best thing that ever happened to me...[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 27 0 0]Thank you for today.[n][uf 1 1][e]

[msg MSG_011_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 1 0 0 28 0 0]Having you with me on this special day... I couldn't be happier.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 40 0 0][uf 3 1 0 0 0 29 0 0]......[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]I shared a tender moment with Fuuka...[n][uf 1 1][e]

