[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]I've returned, everyone. Sorry to have worried you all.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 2 0 0]Man, it's good to see you! It's been a whole month, y'know. I was gettin' nervous.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Me too. I was afraid I wouldn't see you again...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]I'm just a machine. I can always be rebuilt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Even if I'm completely destroyed, my programming data would still exist.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 6 0 0]C'mon, don't talk about yourself like that.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0]I was told she'd need another week for a complete recovery, but I had the work expedited.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Tomorrow is New Year's Eve.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 9 0 0]I'm sorry for all the trouble I've caused.[n][uf 1 1][e]

[msg MSG_006_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]Mitsuru-san visited me while I was at the lab.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 7 3 25 25]I heard what happened... You've all been through so much.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 2]-san, have you been well?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 7 3 25 25]Well, given the circumstances, I'd assume not.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Not really...[e]
[uf 0 5 65278][uf 2 1]I've been okay.[e]
[uf 0 5 65278][uf 2 1]I was worried about you.[e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Really? That's a relief to hear.[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 15 0 0]I'm sorry. I could've done so much more.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 16 0 0]Ten years ago, I... What I did to you was...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 0 0 0 17 0 0]......[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]You did what you had to.[e]
[uf 0 5 65278][uf 2 1]You had no choice.[e]
[uf 0 5 65278][uf 2 1]You did the right thing.[e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 18 0 0]But...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 19 0 0]If I hadn't done what I did to you, you wouldn't be suffering like this.[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]As for what Ryoji-kun said...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]Have you... already made your decision?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, I have.[e]
[uf 0 5 65278][uf 2 1]No, not yet.[e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]I have a favor to ask.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Tomorrow, when Ryoji-kun comes back...[n][uf 1 1][e]

[msg MSG_016_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Please, kill him![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 25 0 0]I can't bear to see you all suffer like this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 26 0 0]If you're in this much pain, I beg you, choose to surrender your memories![n][uf 1 1][e]

[msg MSG_016_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Even if...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Even if it means forgetting everything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 29 0 0]...And everyone.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 6 65535 0 0][uf 3 1 1 0 0 30 0 0]A-Aigis, what're you talking about!?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 6 65535 0 0][uf 3 1 1 0 0 31 0 0]Yeah, seriously! This is not like you.[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 0 0 0 32 0 0]......[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 33 0 0]What is it, Aigis?[n][uf 1 1][e]

[msg MSG_022_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Why...? Why did I come back here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 35 0 0]My duty is to protect people from Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 36 0 0]But now, it's clear that I can't defeat them.[n][uf 1 1][e]

[msg MSG_022_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 37 0 0]What am I even doing here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 38 0 0]No matter how hard I try, I can't even shed a tear for you...[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 39 0 0]Aigis...[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 40 0 0]Why do you try to fight when you know it's hopeless?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 41 0 0]Why risk everything when it will only lead to suffering!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 6 65535 0 0][uf 3 1 1 0 0 42 0 0]You're all just throwing away your lives! I don't understand![n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 43 0 0]We're not throwing away our lives.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 6 65535 0 0][uf 3 1 1 0 0 44 0 0]In fact, our eyes are set on the future. Isn't that right?[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 45 0 0]Right.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 46 0 0]I don't understand. Perhaps it's because I lack a life of my own.[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 47 0 0]Haha, it's got nothin' to do with havin' a life.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 48 0 0]I'm a machine created to protect humans from Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 7 3 25 25]But I can't carry out that duty with the power I have.[n][uf 1 1][e]

[msg MSG_029_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 50 0 0]So what is my purpose now? I just... don't know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 51 0 0]And no one can give me an answer...[n][uf 1 1][e]

[msg MSG_030_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 52 0 0]Well yeah, we don't have the answers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 53 0 0]The meaning of life or death isn't somethin' someone else can just teach you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 54 0 0]Makin' your own decisions is hard, no matter who you are. No choice is perfect, y'know?[n][uf 1 1][e]

[msg MSG_030_3_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 55 0 0]But as long as we're alive, we gotta do something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 6 65535 0 0][uf 3 1 1 0 0 56 0 0]When you see someone goin' through the same thing you're goin' through, you just wanna help 'em.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 3 1 25 25]That's how we plan on gettin' through this.[n][uf 1 1][e]

[msg MSG_030_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 58 0 0]Haha, maybe that wasn't the best explanation, but that's the idea.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 59 0 0]That's... the idea?[n][uf 1 1][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 6 65535 0 0][uf 3 1 1 0 0 60 0 0]When I saw you collapse, I realized something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 6 65535 0 0][uf 3 1 1 0 0 61 0 0][uf 4 23 0 6 0 25 25]I want to protect you, Aigis. I don't want to forget about you.[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 62 0 0]Fuuka-san...[n][uf 1 1][e]

[msg MSG_034_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 63 0 0]There are times when you'll lose sight of your purpose, and you'll have to search for it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 64 0 0]But if you can't find it again, then what you need is to seek out a new purpose.[n][uf 1 1][e]

[msg MSG_034_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 65 0 0]I'm not really one to talk, but I feel like I've learned something important this year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 66 0 0]To truly live is to be willing to change. And we have to make those choices for ourselves.[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 6 65535 0 0][uf 3 1 1 0 0 67 0 0]Do you think... I'll be able to change, too?[n][uf 1 1][e]

[msg MSG_036_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 68 0 0]You have changed. So much. Haven't you noticed?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 69 0 0]You've even started speaking like a real human.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 70 0 0]I understand what my purpose is now.[n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 71 0 0]I'm a machine with the directive to "live."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 72 0 0]And the one issuing this new command... is me.[n][uf 1 1][e]

[sel SEL_039_0_0 top]
[uf 0 5 65278][uf 2 1]As it should be.[e]
[uf 0 5 65278][uf 2 1]So that's your decision.[e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 73 0 0]I'll stare fear in the face and choose to live. This is the promise I've made to myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 74 0 0][uf 4 23 0 7 1 25 25]I'm not sure how I'll do it, but perhaps that's a part of living, too.[n][uf 1 1][e]

[msg MSG_041_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 6 65535 0 0][uf 3 1 1 0 0 75 0 0]Yeah, it sure is.[n][uf 1 1][e]

[msg MSG_042_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 76 0 0]Woof![n][uf 1 1][e]

[msg MND_043_0_0]
[uf 0 5 65278][uf 2 1]The resolution in Aigis's heart has awakened a new Persona...[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]Aigis's Persona, [uf 0 1 35]Palladion[uf 0 1 27], has given rise to [uf 0 1 35]Athena[uf 0 1 27]![n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 77 0 0]Will you allow me to join you in this fight?[n][uf 1 1][e]

[msg MSG_046_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 6 65535 0 0][uf 3 1 1 0 0 78 0 0]You kiddin'? Of course, you've always been one of us![n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 79 0 0]Thank you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 80 0 0]From now on, I stand with all of you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 81 0 0]No matter what happens![n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 82 0 0]Yeah![n][uf 1 1][e]

