[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 2 25 25]We're finally at the last episode... I wonder how it's going to end.[n][uf 1 1][e]

[msg MSG_000_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]Y'know, about this series...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]I mentioned before how it caught my attention, but I was afraid it might be too scary for me...[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 11 25 25]But I'm glad I watched it! Guess it's important to break out of your comfort zone sometimes.[n][uf 1 1][e]

[msg MSG_000_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]Do you ever try watching things from genres you don't normally get into?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Bring it on.[e]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]If I'm with someone.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 1 25 25]Oh, wow. I could learn a thing or two from you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 1 25 25]Trying out all kinds of shows seems like a good way to find hidden gems.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Haha, I'm like that too. Like, what if you try it and it turns out to be horrible?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]But as we've seen, you never know when it might pay off to break out of your comfort zone.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]I'm the same way. Isn't it easier to try something new when you have someone with you for the ride?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 1 25 25]It's also nice to be able to comment on it and see the other person's reaction.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]Watching this together made me realize how much I appreciated the main character.[n][uf 1 1][e]

[msg MSG_005_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]Like how she can't turn a blind eye to people in need, and extends her hand to almost anyone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]And of course, the way she kept pressing forward, no matter what happened. It was so inspiring.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Come to think of it, isn't she just like you...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Hehe! That might be a stretch.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]Remember how I told you about that girl I was close to who started ignoring me one day?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 3 25 25]It's not like I did anything to make her hate me.[n][uf 1 1][e]

[msg MSG_007_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 3 25 25]We'd been friends for a long time. But one day, out of the blue, she just said...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 3 25 25]"My mother told me I can't play with you anymore."[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 3 25 25]It's because there were rumors floating around about my parents.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 3 25 25]I kind of get it now, looking back, but... at the time, I was just... sad.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Uh, what I'm trying to say is...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 1 25 25]This show made me realize I'd like to be a little more like the main character.[n][uf 1 1][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]I want to be the kind of person who'd help anyone, at any time. Someone who's kind and strong.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]It might be silly to say I look up to a fictional character, but there's no harm in following her example. At least that's what I think.[n][uf 1 1][e]

[msg MND_009_7_0]
[uf 0 5 65278][uf 2 1]Yukari has been inspired by the protagonist[n]of the show we watched on DVD...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 4 25 25]Oh! The last episode's starting![n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 11 25 25][uf 5 13 7 1 2]That ending was so good! I hope they'll make a sequel...[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]By observing the main character, I've begun to[n]understand the [uf 4 30 1 1 1 0] of an adult...[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 1 25 25]I'll bring more DVDs I'm curious about next time![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 1 25 25]It's about time we head back to our rooms. Have a good night, okay?[n][uf 1 1][e]

