[msg MSG_000_0_0 [Camera Footage]]
[uf 0 5 65278][uf 2 1]...＞ ...＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]06/14/2009 16:17:49[n]Starting playback...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It looks like Junpei's room...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 1 0 0]This way, Officer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 2 0 0]By the time I noticed the door was halfway open, his room was already like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 3 0 0]I've left the place untouched, as you requested.[n][uf 1 1][e]

[msg MSG_003_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 0 0 0 4 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 1 0 0 5 0 0][uf 5 21 0 2]Whose room is this?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 6 0 0]Junpei Iori. A second-year student.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 7 0 0]I've been trying to reach him on his cell phone, but he hasn't responded in the last half hour.[n][uf 1 1][e]

[msg MSG_005_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 9 0 0]It was careless of me to let my guard down. This dorm was attacked once in the past.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 10 0 0]Perhaps Iori himself is at fault here, however, if harm has fallen upon him, as head of SEES I am accountable...[n][uf 1 1][e]

[msg MSG_007_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]I hate to say it, Kirijo-san, but he most likely—[n][uf 1 1][e]

[msg MSG_008_0_0 [Voice from Outside]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]Huh? Kirijo-senpai?[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 13 0 0]Wh-What the hell!? Kurosawa-san? What's going on here!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 5 10 0 0][uf 3 1 1 0 0 14 0 0]Iori!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 5 10 0 0][uf 3 1 1 0 0 15 0 0]Where were you? I've been trying get a hold of you![n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 16 0 0]Huh? Oh, uh... It was hot and the AC was busted, so I went to the manga café, but I fell asleep.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 17 0 0]Well, I'm just glad you're safe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 18 0 0]So if it wasn't an attack, then it must have been theft. Why would the burglar target this room?[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 19 0 0]Burglar!?[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 10 0 0][uf 3 1 1 0 0 20 0 0]What else could it be? Someone clearly ransacked the place looking for something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 5 10 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 2 25 25]Vandalizing a school dorm... When I find out who did this, I'll see to it that they face a swift execution.[n][uf 1 1][e]

[msg MSG_015_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 1 0 0 22 0 0][uf 5 21 0 2]Well, son, sounds like you've got a death sentence.[n][uf 1 1][e]

[msg MSG_016_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 1 0 0 23 0 0][uf 5 21 0 2]How about it, Iori? Was this room really vandalized?[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 10 0 0][uf 3 1 1 0 0 24 0 0]Ah, uhhh, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 10 0 0][uf 3 1 1 0 0 25 0 0]This is... how my room always looks?[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 5 10 0 0][uf 3 1 1 0 0 26 0 0]Wh-What!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 3 25 25]But, I mean...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 28 0 0]You can't possibly live like this, can you!?[n][uf 1 1][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 29 0 0]Wh-What about the door? It was open.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 10 0 0][uf 3 1 1 0 0 30 0 0]Oh, that? I was just airin' the place out while I was gone. No one we don't know ever comes around, so...[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 0 0 0 31 0 0]......[n][uf 1 1][e]

[msg MSG_022_0_0 [Officer Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 10 0 0][uf 3 1 1 0 0 32 0 0][uf 5 21 0 2]I think this case is closed. May I get back to my duties now, young lady?[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 33 0 0]Oh, y-yes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 5 10 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 6 25 25]I'm... sorry you had to witness something so disgraceful.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 0 0 0 35 0 0]...![n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 36 0 0]I apologize for all this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 5 10 0 0][uf 3 1 1 0 0 37 0 0]It seems I grew up more sheltered than I realized.[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 38 0 0]You're not even gonna yell at me!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 39 0 0]And what's the deal with callin' the cops over a messy room, anyway!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 10 0 0][uf 3 1 1 0 0 40 0 0]The hell did I do to deserve this!?[n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 10 0 0][uf 3 1 1 0 0 41 0 0]Hey, wait...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 10 0 0][uf 3 1 1 0 0 42 0 0]I drew that "Worst Luck" fortune on the way back...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]The recording ends here...[n][uf 1 1][e]

