[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3125 0 0]Slacking off on training can impact both boxing and actual battles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]It's too bad I've fallen out of practice. I'll have to work harder to get back to where I was before.[n][uf 1 1][e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3099 0 0]First, the dorm's connected to some kind of labyrinth, and now we're traveling to the past...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0]What exactly is going on here, dammit!?[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3112 0 0]I thought I'd been doing all right, making sure my stamina doesn't get any worse, but guess I thought wrong.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]Actual combat can't compare to working out at the gym, but... That's just an excuse.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 3 0 65535 3082 0 0]Losing a parent is hard... in more than one way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]It was hard for me, too—and I was too young to even remember my parents' faces.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]I don't think any of us can blame Amada for the decisions he made back then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3053 0 0]Sorry, didn't mean to make the mood so glum. Was just thinking about things.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3012 0 0]Shinji joined the team right after I did.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]His potential wasn't that high, though. Nobody was sure if he could even control his Persona.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]I told him to give up, but... He just pushed his way into the dorm, wouldn't take no for an answer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 3 0 65535 3122 0 0]I guess he did all that for me... Seriously, that guy...[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3024 0 0]Koromaru wasn't the only one he met that day. I ran into him as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]If I hadn't been out patrolling that night, maybe he wouldn't be here, fighting with us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]A chance encounter indeed.[n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 3 0 65535 3004 0 0]Makes you wonder what it's like to be born into a prestigious family. To think she was fighting Shadows at that young an age...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]Shinji and I don't even remember our parents' faces. It was painful, but... in a way, that made things easier for us as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]Especially considering the burden Mitsuru must have had to shoulder.[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3073 0 0]Metis said that we're the reason the Abyss of Time exists, right...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0]And the place is infested with Shadows... Dammit, what the hell does it all mean!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 52 65535 0 0]At the risk of sounding like Junpei... I have no idea what's going on.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0][uf 3 1 3 0 65535 3116 0 0]Looked like that figure was trying to lure us in... Heh. We could just take the bait.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 52 65535 0 0]We'll find out who exactly this mystery person is soon enough.[n][uf 1 1][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3080 0 0]I understand why someone would want to change the past, how desperate they must be for the chance to do so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]But would we be meddling with the past for him? Or for our own sake?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]Because he wasn't the victim of some random accident. He chose this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3082 0 0]That's why... I won't change the past. I'll never agree to it.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3049 0 0]Why he lost his life, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]I thought I had already accepted his death, but... Maybe, in the end, I didn't want to face it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]I'll see it through this time, though. For closure's sake.[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0][uf 3 1 3 0 65535 3055 0 0]Before we fought, I said you had nothing to fight for, didn't I? Sorry about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 52 65535 0 0]You put your life on the line to arrive at your answer... Guess there's still a lot I have to learn.[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3002 0 0]Hey, good timing. You free right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]Was hoping we could talk about that book we found in the Abyss. You know, [uf 4 4 0 37 1 16778]?[n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time with Sanada-san...?[n][uf 1 1][e]

[sel SEL_046_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not right now, no.[e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 3 0 65535 3041 0 0]Thanks. Amada's been reading it, and he's got some questions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Figured it'd be a good idea for him to get some pointers from people with different fighting styles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]Let's head over.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3049 0 0]All right. Well, just let me know when you've got the time.[n][uf 1 1][e]

[msg MSG_050_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3011 0 0]Oh, hey. Listen, I've got some time on my hands right now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0]So I was thinking about reading that book we found in the Abyss. You interested?[n][uf 1 1][e]

[msg MSG_051_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3115 0 0]All right, let's go, then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0]"[uf 4 4 0 37 1 16779]," huh... Interesting title. Kinda got me curious.[n][uf 1 1][e]

[msg MSG_052_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3061 0 0]All good. Not like reading it together changes the content or anything.[n][uf 1 1][e]

[msg MSG_053_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 3 0 65535 3005 0 0]What's up? That book pique your interest?[n][uf 1 1][e]

