[msg MSG_009_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30001 0 0]Um, did you need me to explain anything?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Tell me about the Abyss of Time.[e]
[uf 0 5 65278][uf 2 1]Tell me about your abilities.[e]
[uf 0 5 65278][uf 2 1]Not at this time, no.[e]

[msg MSG_011_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30062 0 0]I believe the Abyss has spread beneath us, like the roots of a tree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Basically, it branches out in various directions, going deeper and deeper down.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]And the area right below us is the Desert of Doors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Each door there seems to lead to a different place. We should be able to use them to traverse to other areas.[n][uf 1 1][e]

[msg MSG_012_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30071 0 0]The weapon I wield is different from yours. It's a heavy melee weapon with some range.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]My Persona's name is [uf 0 1 35]Psyche[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Unlike you, I can only summon one Persona, but I don't lack for sheer strength and determination![n][uf 1 1][e]

[msg MSG_013_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30111 0 0]No need to worry! I'll be at your side every step of the way![n][uf 1 1][e]

[msg MSG_114_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30018 0 0]So that shady-looking person... Kurosawa, you said? He's a shopkeeper?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]What kind of store does he run, exactly...?[n][uf 1 1][e]

[msg MSG_014_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30090 0 0]Truth be told... I think I'm actually starting to enjoy this exploring stuff![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Isn't this rather fun, Sister?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, it is.[e]
[uf 0 5 65278][uf 2 1]You should ask the others, too.[e]

[msg MSG_016_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30057 0 0]I know we need to hurry and get through the Abyss for your sake, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]It'd be kind of sad for all this to come to an end... if you get what I'm saying.[n][uf 1 1][e]

[msg MSG_017_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30054 0 0]Oh... I'm sorry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I just... don't know the others all that well, so it's hard for me to figure out what to say to them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]

[msg MSG_017_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30112 0 0]I'll do whatever I can to help make this expedition easier for you, Sister.[n][uf 1 1][e]

[msg MSG_018_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30065 0 0]The date's different every time we go to that mall, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]The store lineup is always changing, and even though everything looks the same, it doesn't feel like it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Perhaps this aspect of the mall is also being influenced by everyone's thoughts.[n][uf 1 1][e]

[msg MSG_024_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30028 0 0]School, huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Oh, right... Everyone here has made memories with you outside of combat and exploring... Everyone but me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30113 0 0]Well, no point dwelling on that! I'll just give this expedition 110%![n][uf 1 1][e]

[msg MSG_025_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30048 0 0]Koromaru-san always seems to be worried about everyone... No, more like he's always watching over everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]It's like he thinks himself the alpha here even though you're our leader, Sister.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]I am, but only for now.[e]
[uf 0 5 65278][uf 2 1]No, I'm not really.[e]

[msg MSG_027_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30045 0 0]That's strange...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Whenever I tell Koromaru-san that you're the leader, he wears the same expression as you do now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30086 0 0]Well, I guess it's not my place to talk. Not like I know much about this kind of thing...[n][uf 1 1][e]

[msg MSG_028_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 4 52 65535 0 0][uf 3 1 3 0 65535 30095 0 0]Don't say that! It'll go to Koromaru-san's head![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]But... When I accused him of acting like the leader, he said the same thing as you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30086 0 0]Well, I guess it's not my place to talk. Not like I know much about this kind of thing...[n][uf 1 1][e]

[msg MSG_028_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30047 0 0]Both you and Koromaru-san are acting weird... Because you're the true leader, Sister.[n][uf 1 1][e]

[msg MSG_029_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]We've explored over half of the doors by now... Enough to start to see how those memories are all connected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]There's still much we don't know about that mysterious figure, but let's keep pressing on! Just a little further now![n][uf 1 1][e]

[msg MSG_030_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30056 0 0]I think Fuuka-san might know something about that figure we keep seeing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]But... It doesn't look like she wants to talk about it. Maybe she's waiting until we get more solid intel?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]She should just tell us what she knows anyway, so we can all share our thoughts.[n][uf 1 1][e]

[msg MSG_031_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30034 0 0]I am not a kid...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I've been helping. I kept my promise and haven't hurt anyone. So why am I always left out and treated like some child...?[n][uf 1 1][e]

[msg MSG_032_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30001 0 0]I just don't understand what's going through everyone's heads... Please don't let them get to you, though, Sister.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]I'll protect you in their place. No matter what.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Once we leave... We're all going to be split up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]You won't be able to see your friends after this. Are you ready?[n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Just one minute...[e]

[msg MSG_034_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30006 0 0]Okay... Follow me, then.[n][uf 1 1][e]

[msg MSG_035_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30044 0 0]Did you need some time to restock our supplies and prep for the battle ahead?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Because dwelling on this matter any longer... won't change anything.[n][uf 1 1][e]

[msg MSG_036_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30072 0 0]Sister... Please don't forget—this key is connected to your life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I won't be holding back against your friends, and... I want you to do the same.[n][uf 1 1][e]

[msg MSG_038_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30006 0 0]I won't stop.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Even if you hate me for this... No matter how painful it may be...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 52 65535 0 0][uf 4 25 11]......[n][uf 1 1][e]

[msg MSG_039_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30019 0 0]Sister... I...[n][uf 1 1][e]

[sel SEL_040_0_0 top]
[uf 0 5 65278][uf 2 1]Don't let it bother you.[e]
[uf 0 5 65278][uf 2 1]I'm so sorry.[e]

[msg MSG_041_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30089 0 0]But... it does.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Back then, when I intended to eliminate everyone... I didn't even think twice about hurting them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 52 65535 0 0]I didn't know that losing someone important to you... could make you feel like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 64 52 65535 0 0][uf 3 1 3 0 65535 30129 0 0]I... I'm sorry... I'm so sorry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 64 52 65535 0 0]But to me... you come first...[n][uf 1 1][e]

[msg MSG_042_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 2 52 65535 0 0][uf 3 1 3 0 65535 30121 0 0]No! It's not your fault, Sister![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I just... I wasn't prepared for this. I didn't know. That's why I could say such cruel things...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 64 52 65535 0 0][uf 3 1 3 0 65535 30129 0 0]I... I'm sorry... I'm so sorry...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 64 52 65535 0 0]But to me... you come first...[n][uf 1 1][e]

[msg MSG_042_5_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 52 65535 0 0][uf 3 1 3 0 65535 30019 0 0]I'm so sorry, Sister...[n][uf 1 1][e]

[msg MSG_043_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30060 0 0]Oh, Sister, I... I'm starting to understand things a little better now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Or at least, I think I am...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]Things like, why I don't know anything about myself... Why you're so important to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 10 52 65535 0 0][uf 3 1 3 0 65535 30028 0 0]And who... who I really am...[n][uf 1 1][e]

[msg MSG_094_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30020 0 0]Sister, do you have some time right now? There's something I want to show you...[n][uf 1 1][e]

[msg MND_095_0_0 [Metis]]
[uf 0 5 65278][uf 2 1]Should I spend time with Metis...?[n][uf 1 1][e]

[sel SEL_096_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not right now, no.[e]

[msg MSG_099_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30092 0 0]Yay! Remember that thing we found in the Abyss? That strange, cup-like object with a hole?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]Amada-san actually taught me how to use it. Come, I'll show you![n][uf 1 1][e]

[msg MSG_100_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30088 0 0]Oh, okay...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I won't force you if you're too busy.[n][uf 1 1][e]

[msg MSG_105_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30081 0 0]Sister, do you remember that book we found in the Abyss?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]Apparently, this [uf 4 4 0 37 1 16789] is an item used by close friends and family.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]So... If you have the time, maybe we could fill it out together?[n][uf 1 1][e]

[msg MSG_107_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0][uf 3 1 3 0 65535 30091 0 0]Hooray! Let's do an exchange, then![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]So basically, we each have to answer the questions, then trade pages to show each other what we wrote![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 1 52 65535 0 0]I've been wanting to do this with you, Sister. I'm so, so happy right now.[n][uf 1 1][e]

[msg MSG_108_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0][uf 3 1 3 0 65535 30068 0 0]Oh, okay...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 3 52 65535 0 0]I won't force you if you're too busy.[n][uf 1 1][e]

[msg MSG_106_0_0 [Metis]]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0][uf 3 1 3 0 65535 30017 0 0]Oh, Sister! Do you have some time right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 11 0 52 65535 0 0]I was thinking we could fill out that book we found in the Abyss together...[n][uf 1 1][e]

