[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]Aigis, there's something that I wanted to ask you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Is it possible that you can no longer activate Orgia Mode?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Yes, you're correct.[e]
[uf 0 5 65278][uf 2 1]Would you happen to know why?[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5049 0 0]Just as I thought. Something felt off when I was backing you up in combat...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]But it didn't look like you were malfunctioning. What could be the reason?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5061 0 0]I thought something was off when I was backing you up in combat. As for what's causing it, well...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0]It doesn't look like you're malfunctioning, but... How should I put it...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It's almost as if you forgot how to activate it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]Sorry, that sounds a bit silly...[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5028 0 0]It looks like Metis is able to activate Orgia Mode.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 3 0 65535 0 0 0]But I don't think you're malfunctioning. Honestly, it's almost as if...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It's as if... you forgot how to activate it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]Sorry, that sounds a bit silly...[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5009 0 0]Is something bothering you?[n][uf 1 1][e]

[sel SEL_086_0_0 top]
[uf 0 5 65278][uf 2 1]About the members not here...[e]
[uf 0 5 65278][uf 2 1]Orgia Mode...[e]
[uf 0 5 65278][uf 2 1]It's nothing.[e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]About the members not here...[e]
[uf 0 5 65278][uf 2 1]Orgia Mode...[e]
[uf 0 5 65278][uf 2 1]What was that reading you picked up?[e]
[uf 0 5 65278][uf 2 1]It's nothing.[e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Kirijo-senpai is looking for anything that could give us a clue about what's going on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0]This is just a theory, but... I think the area below the lounge was originally storage space.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]However, because the Abyss of Time appeared, whatever was stored down there got all jumbled up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Junpei-kun and Koro-chan are looking for any exits that we could use to get supplies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Since they're not planning to go too far, they'll be all right.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5065 0 0]Hm, I honestly have no idea...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]It just appeared out of nowhere and then disappeared. I couldn't tell what it was.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]It does bother me a little, but for now we should concentrate on exploring the area. We have too little intel at the moment...[n][uf 1 1][e]

[msg MSG_085_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5076 0 0]Looks like this place really isn't connected to anywhere outside...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]It's just like the dorms. Whenever we try to leave, some invisible force just pushes us back.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5025 0 0]It looks like it'll take Kirijo-senpai a little more time to search for intel.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I'm currently going through all the documents she's found so far, but it shouldn't take too long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]There's a lot we have now, so I'm sure we'll find something.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]The feeling I had when we all saw Amada-kun's memory is similar to the one I have when I'm backing you up in fights.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It's right in front of you, but you have no physical body. All you can do is... watch.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]I never expected I'd be able to share that feeling with all of you.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I'm slowly going through all the documents that Kirijo-senpai found. However...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]A number of them are almost... religious in nature. They're a bit hard to sift through for useful information.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]Sorry, but could you wait just a little longer on this?[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5004 0 0]We used to use the bulletin board a lot, didn't we?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Feels a little weird we're not using it at all now even though we're exploring again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I don't think any of us ever thought we'd have to continually explore like we are now.[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5077 0 0]I never really thought too much about it, but I wonder if everyone outside the dorm is okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I just... thought about my family a little.[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0][uf 3 1 3 0 65535 5062 0 0]I wonder if that figure we keep seeing has some kind of motive. And if so, what could it be?[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Do you remember what Metis first said about this place?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]She said that the Abyss of Time was originally a small, self-contained space...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5070 0 0]That actually might be true. It matches up with the information on the notes we've found.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I guess she was telling the truth this whole time...[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5001 0 0]I really don't think Metis is lying to us.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I think... she just really wants to protect you.[n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5028 0 0]We've all been saying that Metis acts pretty childish...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]But maybe she really is a child at heart. If that's the case, maybe we're the ones who should be reaching out to her.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5056 0 0]Sorry for saying weird things while we've been exploring. We really don't know a thing about that figure...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]Sorry, I'll try to figure it out.[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5084 0 0]I count on you for a lot of things, Aigis, and... I understand that it's hard to make a decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]But if I side with you on this, then the others...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0]I just don't know what to do.[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]I just can't decide... I'm sorry, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0]What should I do?[n][uf 1 1][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Aigis, are you okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]No... Of course you're not okay.[n][uf 1 1][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5083 0 0]I think... you made the right choice, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It's like what Yukari-chan said. I've thought about it and... my mind is made up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I'll support you, and I'll be your navigator... until the end.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]If it wasn't for you, I probably would've been swept up in all of this and wouldn't have been able to make my own decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Even though it was such an important one to make. So... thank you, Aigis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Once we're done with this final battle, we can use the true key and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Um... You know how to use the true key, right?[n][uf 1 1][e]

[sel SEL_028_0_0 top]
[uf 0 5 65278][uf 2 1]I do.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5029 0 0]R-Right. Sorry, I got a little nervous there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]But we'll be okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5053 0 0]I'm sorry... You're probably more scared about this than I am, Aigis. And I just...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0]It's hard for me to put it into words, but... This kind of reminds me of January 31st.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 52 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]

[msg MSG_030_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5076 0 0]Once we're done with this final battle, we can use the true key and...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]I'm scared, but being scared isn't going to help.[n][uf 1 1][e]

[msg MSG_086_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5002 0 0]Oh, Aigis. Would you like to study together?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]We found that [uf 4 4 0 37 1 16782] in the Abyss of Time, didn't we?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]I just figured that in times like these, it's nice to have something familiar to fall back on.[n][uf 1 1][e]

[msg MND_200_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time with Fuuka-san?[n][uf 1 1][e]

[sel SEL_087_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5039 0 0]Thanks. I actually invited Metis, too. She said she was interested in what high schoolers study.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Shall we go, then?[n][uf 1 1][e]

[msg MSG_089_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 3 0 65535 5094 0 0]Right, I guess you're busy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0]Well, if you decide you want to, feel free to join. I'll see you later, Aigis.[n][uf 1 1][e]

[msg MSG_092_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5002 0 0]Are you still busy, Aigis? If not, we could study together... If you feel like it.[n][uf 1 1][e]

[msg MSG_094_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5004 0 0]Oh, Aigis. Do you have some time right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Um, I'd like to watch that [uf 4 4 0 37 1 16783] with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]It looks like it's simple enough, but I wanted to get your opinion on it as well.[n][uf 1 1][e]

[msg MSG_095_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0][uf 3 1 3 0 65535 5043 0 0]Thanks! I wasn't sure if I'd understand all of it on my own, so I'm glad you'll watch it with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 52 65535 0 0]Shall we go, then?[n][uf 1 1][e]

[msg MSG_098_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5094 0 0]Oh, that's too bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0]Well, maybe we can when you're less busy? I'll see you later, then.[n][uf 1 1][e]

[msg MSG_099_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Are you still busy? I was wondering if we could watch that DVD together...[n][uf 1 1][e]

