[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7004 0 0]I feel like it's not just my Persona abilities that were affected. I can't handle my weapon as well as I used to, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]I guess battling is kind of like studying. You have to keep at it if you want to maintain a certain level of aptitude...[n][uf 1 1][e]

[msg MSG_074_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0][uf 3 1 3 0 65535 7062 0 0]We actually went back to the past...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]In a way, this feels far more dangerous than the Dark Hour. Don't you think so, too?[n][uf 1 1][e]

[msg MSG_011_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7138 0 0]The view outside the window looks normal, but I can't shake this weird feeling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]I can't exactly put my finger on it... For all I know, it could just be my imagination.[n][uf 1 1][e]

[msg MSG_012_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7077 0 0]Oh, are you worried about how I'm taking all of that? I'm honestly okay... That was so long ago now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]But, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7040 0 0]Thank you... Aigis-san.[n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7077 0 0]I think I figured out why I get this weird feeling whenever I look outside the window...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 52 65535 0 0]Everything happens at the exact same time as the last, right on the dot. The same person passing by, the same car...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]And that's pretty scary when you start thinking about it...[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7048 0 0]That figure... It doesn't seem like it wants a direct confrontation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]But what exactly does it want from us...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7001 0 0]You know, Junpei-san never really admits just how sad or hurt he is until it comes to a head.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]It kind of hit me how mature he can be... Especially considering how he's helped me through some stuff, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7132 0 0]I still think he ought to take things more seriously at times, though.[n][uf 1 1][e]

[msg MSG_018_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7078 0 0]I thought I understood how serious of a problem the Shadows are, but maybe it's even worse than I imagined...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]People getting caught up in accidents, having their minds consumed...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]What even are the Shadows?[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]I also wonder about that.[e]
[uf 0 5 65278][uf 2 1]They're the enemy.[e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7048 0 0]And it's so weird that only Persona-users stand a chance against them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Do you think Personas and Shadows may be related somehow...?[n][uf 1 1][e]

[msg MSG_021_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7065 0 0]Well, yeah, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Right now, all we're doing is taking them out little by little. Maybe we need to stop and figure out what they really are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]That's just a thought, though... It's kind of hard to put it into words.[n][uf 1 1][e]

[msg MSG_022_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7117 0 0]Let's keep going. If there's really an answer to all this, then no doubt it'll be at the very end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]That's what I think, at least, so I'll keep pressing forward![n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Maybe... Maybe there really is some kind of secret behind these Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Just a little further until we make it to the end... I wonder what we'll find there.[n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Maybe... Maybe there really is some kind of secret behind these Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]Same goes for that figure that keeps showing up. Why does Fuuka-san start acting weird whenever we see it...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]There's so much we don't know...[n][uf 1 1][e]

[msg MSG_025_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 52 65535 0 0][uf 3 1 3 0 65535 7085 0 0]To be honest... I miss him a lot, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 52 65535 0 0]It's not like I don't want him to come back...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]But he made his choice, and... I want to try to understand his decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7082 0 0]That's why I'll be siding with Sanada-san on this. He feels the same way as I do.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7096 0 0]I'm relieved we're all here, together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]I know I chose to split apart and fight for my side, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]The fact that we're in this as a team again puts me at ease.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7041 0 0]Thank you... Aigis-san.[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0]I'm still a little mad you didn't say anything about the key possibly being linked to your life, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 52 65535 0 0]No wonder Metis was so determined to win.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]She'll do anything for the person she cares about the most, even if it means harming others in the process...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 10 52 65535 0 0][uf 3 1 3 0 65535 7085 0 0]And I... I kind of relate to that.[n][uf 1 1][e]

[msg MSG_053_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7010 0 0]Oh, Aigis-san. Do you have some time right now?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Fuuka-san and I have been using the [uf 4 4 0 37 1 16784] we found to keep track of our supplies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]And I was wondering if you could lend us a hand? If you're okay with it, of course.[n][uf 1 1][e]

[msg MND_054_0_0]
[uf 0 5 65278][uf 2 1]Should I spend time[n]with Amada-san...?[n][uf 1 1][e]

[sel SEL_055_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Not right now, no.[e]

[msg MSG_058_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7045 0 0]Thank you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]I was actually asked to buy some more supplies, but I don't think I'll be able to carry all of it by myself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0]So I'm glad you agreed to help.[n][uf 1 1][e]

[msg MSG_059_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7095 0 0]Oh, okay...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Then, um... If you find the time, could you come see me?[n][uf 1 1][e]

[msg MSG_064_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7002 0 0]Aigis-san, do you have a moment?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]It's about the [uf 4 4 0 37 1 16785] we found. Something's been bugging me...[n][uf 1 1][e]

[msg MSG_063_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 52 65535 0 0][uf 3 1 3 0 65535 7041 0 0]Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Do you remember how it was in tatters? I think it was just an ordinary mystery book, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]I was thinking about fixing it up. I'm pretty confident I can do it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0]...At least, I think I can.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 52 65535 0 0][uf 3 1 3 0 65535 7095 0 0]Oh, okay. Well, in that case...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Let's work on it together whenever you have time. Just let me know if you're free.[n][uf 1 1][e]

[msg MSG_066_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0][uf 3 1 3 0 65535 7010 0 0]Oh, Aigis-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 52 65535 0 0]Remember that book we found while exploring? Could I talk about it with you?[n][uf 1 1][e]

