[msg MSG_000_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 3 0 65535 15213 0 0]Yes, [uf 4 1]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Did you have a question about my lecture— Hm? Yes? What are you staring at?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Is it my helm...? Could that be it?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 3 0 65535 15208 0 0]Is this really happening? Boy, oh boy. That's one discerning eye you've got there, kid![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Isn't this helm great? It is, isn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]It's a historic masterpiece Masamune had since he was young...[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Mr. Ono keeps going on[n]and on with his story...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]*sniffle* So Masamune gave this helm to his vassal before he departed...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Such generosity! It's as if he foresaw his fate...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]*sob* *sob*[n][uf 1 1][e]

[msg MSG_005_0_0 [Mr. Ono]]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0][uf 3 1 3 0 65535 15216 0 0]...And that's why I couldn't possibly part with it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]I could give you something else from my personal collection, though—one with no connections to Masamune.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]If you still want one... Well, you do, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1083 0 65535 65535 0 0]Come see me again, and I'll let you have it.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]I enjoyed the tales of Masamune.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I have a deeper understanding of history...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]If I come back to speak with Mr. Ono[n]at the faculty office another day,[n]I might get my very own helm...[n][uf 1 1][e]

