[msg Item_000]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_001]
[uf 0 5 65278][uf 2 1]A key that unlocks the door to the Velvet Room.[n][e]

[msg Item_002]
[uf 0 5 65278][uf 2 1]A fallen leaf from a young tree.[n][e]

[msg Item_003]
[uf 0 5 65278][uf 2 1]A blood-red fountain pen.[n][e]

[msg Item_004]
[uf 0 5 65278][uf 2 1]Proof of having defeated Elizabeth.[n][e]

[msg Item_005]
[uf 0 5 65278][uf 2 1]A massively multiplayer PC game called Innocent Sin Online.[n][e]

[msg Item_006]
[uf 0 5 65278][uf 2 1]An envelope from Mitsuru to be discretely given to Aragaki.[n][e]

[msg Item_007]
[uf 0 5 65278][uf 2 1]An envelope from Aragaki. It seems he won't return to school.[n][e]

[msg Item_008]
[uf 0 5 65278][uf 2 1]A key that opens the door to the gym.[n][e]

[msg Item_009]
[uf 0 5 65278][uf 2 1]"At the end of a great trial, the answer illuminates my path."[n][e]

[msg Item_00A]
[uf 0 5 65278][uf 2 1]A strip of paper from Takaya, seemingly part of some research material.[n][e]

[msg Item_00B]
[uf 0 5 65278][uf 2 1]A choker Tomochika made. Enables fusion of Futsunushi.[n][e]

[msg Item_00C]
[uf 0 5 65278][uf 2 1]The headphones Fuuka made. Enables fusion of Scathach.[n][e]

[msg Item_00D]
[uf 0 5 65278][uf 2 1]The key to Mitsuru's motorcycle. Enables fusion of Alilat.[n][e]

[msg Item_00E]
[uf 0 5 65278][uf 2 1]Proof of Odagiri's trust. Enables fusion of Odin.[n][e]

[msg Item_00F]
[uf 0 5 65278][uf 2 1]Fruit from Bunkichi's son's tree. Enables fusion of Kohryu.[n][e]

[msg Item_010]
[uf 0 5 65278][uf 2 1]Yukari's treasured cell phone strap. Enables fusion of Cybele.[n][e]

[msg Item_011]
[uf 0 5 65278][uf 2 1]A roll of sports tape from Miyamoto. Enables fusion of Thor.[n][e]

[msg Item_012]
[uf 0 5 65278][uf 2 1]A manga by Chihiro's favorite artist. Enables fusion of Melchizedek.[n][e]

[msg Item_013]
[uf 0 5 65278][uf 2 1]The message Maya left in the MMORPG. Enables fusion of Arahabaki.[n][e]

[msg Item_014]
[uf 0 5 65278][uf 2 1]Notification of Hiraga's prize. Enables fusion of Lakshmi.[n][e]

[msg Item_015]
[uf 0 5 65278][uf 2 1]A letter from the kids Yuko trained. Enables fusion of Atavaka.[n][e]

[msg Item_016]
[uf 0 5 65278][uf 2 1]The ring Maiko made. Enables fusion of Attis.[n][e]

[msg Item_017]
[uf 0 5 65278][uf 2 1]The pouch Bebe made. Enables fusion of Yurlungur.[n][e]

[msg Item_018]
[uf 0 5 65278][uf 2 1]The letter President Tanaka received. Enables fusion of Beelzebub.[n][e]

[msg Item_019]
[uf 0 5 65278][uf 2 1]Mutatsu's bottle tag. Enables fusion of Chi You.[n][e]

[msg Item_01A]
[uf 0 5 65278][uf 2 1]A car key received from Hayase. Enables fusion of Helel.[n][e]

[msg Item_01B]
[uf 0 5 65278][uf 2 1]A license received from Suemitsu. Enables fusion of Sandalphon.[n][e]

[msg Item_01C]
[uf 0 5 65278][uf 2 1]A notebook containing Kamiki's story. Enables fusion of Asura.[n][e]

[msg Item_01D]
[uf 0 5 65278][uf 2 1]A broken component from Aigis's body. Enables fusion of Metatron.[n][e]

[msg Item_01E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_01F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_020]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_021]
[uf 0 5 65278][uf 2 1]Enables fusion of the Hermit Persona, Mothman.[n][e]

[msg Item_022]
[uf 0 5 65278][uf 2 1]Enables fusion of the Emperor Persona, King Frost.[n][e]

[msg Item_023]
[uf 0 5 65278][uf 2 1]Enables fusion of the Fool Persona, Decarabia.[n][e]

[msg Item_024]
[uf 0 5 65278][uf 2 1]Enables fusion of the Hermit Persona, Nebiros.[n][e]

[msg Item_025]
[uf 0 5 65278][uf 2 1]Enables fusion of the Devil Persona, Lilith.[n][e]

[msg Item_026]
[uf 0 5 65278][uf 2 1]Enables fusion of the Tower Persona, Masakado.[n][e]

[msg Item_027]
[uf 0 5 65278][uf 2 1]Enables fusion of the Magician Persona, Hua Po.[n][e]

[msg Item_028]
[uf 0 5 65278][uf 2 1]Enables fusion of the Hierophant Persona, Thoth.[n][e]

[msg Item_029]
[uf 0 5 65278][uf 2 1]Enables fusion of the Judgement Persona, Lucifer.[n][e]

[msg Item_02A]
[uf 0 5 65278][uf 2 1]Enables fusion of the Sun Persona, Houou.[n][e]

[msg Item_02B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_02C]
[uf 0 5 65278][uf 2 1]Enables fusion of the Fool Persona, Orpheus Telos.[n][e]

[msg Item_02D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_02E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_02F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_030]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_031]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_032]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_033]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_034]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_035]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_036]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_037]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_038]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_039]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_03A]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_03B]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_03C]
[uf 0 5 65278][uf 2 1]A classified document from ten years ago, found in Tartarus.[n][e]

[msg Item_03D]
[uf 0 5 65278][uf 2 1]A research document found in Tartarus.[n][e]

[msg Item_03E]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_03F]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_040]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_041]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_042]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_043]
[uf 0 5 65278][uf 2 1]A memoir written by a researcher, found in Monad.[n][e]

[msg Item_044]
[uf 0 5 65278][uf 2 1]Hand powder used in archery. Looks like roasted soybean powder.[n][e]

[msg Item_045]
[uf 0 5 65278][uf 2 1]A slender sword with a triangular cross section that is hard to bend.[n][e]

[msg Item_046]
[uf 0 5 65278][uf 2 1]Has traces of having wiped a variety of things other than glasses.[n][e]

[msg Item_047]
[uf 0 5 65278][uf 2 1]A plant with red leaves. Sometimes called a "Christmas star."[n][e]

[msg Item_048]
[uf 0 5 65278][uf 2 1]Has a game called Odin Cube inserted in it.[n][e]

[msg Item_049]
[uf 0 5 65278][uf 2 1]It's quite used, but meticulously maintained.[n][e]

[msg Item_04A]
[uf 0 5 65278][uf 2 1]A figure of a popular hero with 40 individually moveable joints.[n][e]

[msg Item_04B]
[uf 0 5 65278][uf 2 1]Perfect for use by amateur athletes.[n][e]

[msg Item_04C]
[uf 0 5 65278][uf 2 1]Expensive dog food. Can also be used to feed wolves and tigers.[n][e]

[msg Item_04D]
[uf 0 5 65278][uf 2 1]Primarily used for firearms maintenance.[n][e]

[msg Item_04E]
[uf 0 5 65278][uf 2 1]Filled with miniscule oden ingredients.[n][e]

[msg Item_04F]
[uf 0 5 65278][uf 2 1]A discarded human anatomic model. It's eerily realistic.[n][e]

[msg Item_050]
[uf 0 5 65278][uf 2 1]Non-alcoholic, but provides a small taste of being adult.[n][e]

[msg Item_051]
[uf 0 5 65278][uf 2 1]A mahjong tile from the mahjong parlor. It has a drawing of a bird on it.[n][e]

[msg Item_052]
[uf 0 5 65278][uf 2 1]Inari sushi received from an old woman.[n][e]

[msg Item_053]
[uf 0 5 65278][uf 2 1]Replica of a Sengoku-era helm. It has the symbol for "love" on it.[n][e]

[msg Item_054]
[uf 0 5 65278][uf 2 1]A CD recording of Gekkoukan Boogie. Comes with a lyrics card.[n][e]

[msg Item_055]
[uf 0 5 65278][uf 2 1]A business card signed by the president of Tanaka's Amazing Commodities.[n][e]

[msg Item_056]
[uf 0 5 65278][uf 2 1]An old 500-yen bill. Seems to still be useable.[n][e]

[msg Item_057]
[uf 0 5 65278][uf 2 1]A seashell found in Yakushima. Emits the sounds of distant waves.[n][e]

[msg Item_058]
[uf 0 5 65278][uf 2 1]Seaweed picked up in Yakushima. It smells intensely of the sea.[n][e]

[msg Item_059]
[uf 0 5 65278][uf 2 1]Driftwood from Yakushima. Has a unique shape, due to erosion.[n][e]

[msg Item_05A]
[uf 0 5 65278][uf 2 1]A crab found in Yakushima. Moves quickly in dark places.[n][e]

[msg Item_05B]
[uf 0 5 65278][uf 2 1]A cloth used for treating injuries. There may be someone who needs this.[n][e]

[msg Item_05C]
[uf 0 5 65278][uf 2 1]A Gekkoukan student handbook. Should be returned to its owner.[n][e]

[msg Item_05D]
[uf 0 5 65278][uf 2 1]One touch and they can't resist! For those wishing to befriend cats.[n][e]

[msg Item_05E]
[uf 0 5 65278][uf 2 1]A thank-you letter regarding the rescue of a missing person.[n][e]

[msg Item_05F]
[uf 0 5 65278][uf 2 1]A Christmas present from a self-proclaimed Santa. Wrapped neatly.[n][e]

[msg Item_060]
[uf 0 5 65278][uf 2 1]The Aohige Pharmacy owner's prized aojiru. Bitter yet sweet.[n][e]

[msg Item_061]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_062]
[uf 0 5 65278][uf 2 1]A baseball glove gifted from Junpei. Enables fusion of Surt.[n][e]

[msg Item_063]
[uf 0 5 65278][uf 2 1]Proof of recognition by Sanada. Enables fusion of Horus.[n][e]

[msg Item_064]
[uf 0 5 65278][uf 2 1]A collar attached with a protective charm. Enables fusion of Byakko.[n][e]

[msg Item_065]
[uf 0 5 65278][uf 2 1]Amada's commemoratory key. Enables fusion of Michael.[n][e]

[msg Item_066]
[uf 0 5 65278][uf 2 1]Proof Aragaki thought about his future. Enables fusion of Hell Biker.[n][e]

[msg Item_067]
[uf 0 5 65278][uf 2 1]A music box that Ryoji left behind. Enables fusion of Saturnus.[n][e]

[msg Item_068]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_069]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06E]
[uf 0 5 65278][uf 2 1]The Fool card will appear during Shuffle Time.[n][e]

[msg Item_06F]
[uf 0 5 65278][uf 2 1]The Magician card will appear during Shuffle Time.[n][e]

[msg Item_070]
[uf 0 5 65278][uf 2 1]The High Priestess card will appear during Shuffle Time.[n][e]

[msg Item_071]
[uf 0 5 65278][uf 2 1]The Empress card will appear during Shuffle Time.[n][e]

[msg Item_072]
[uf 0 5 65278][uf 2 1]The Emperor card will appear during Shuffle Time.[n][e]

[msg Item_073]
[uf 0 5 65278][uf 2 1]The Hierophant card will appear during Shuffle Time.[n][e]

[msg Item_074]
[uf 0 5 65278][uf 2 1]The Lovers card will appear during Shuffle Time.[n][e]

[msg Item_075]
[uf 0 5 65278][uf 2 1]The Chariot card will appear during Shuffle Time.[n][e]

[msg Item_076]
[uf 0 5 65278][uf 2 1]The Justice card will appear during Shuffle Time.[n][e]

[msg Item_077]
[uf 0 5 65278][uf 2 1]The Hermit card will appear during Shuffle Time.[n][e]

[msg Item_078]
[uf 0 5 65278][uf 2 1]The Fortune card will appear during Shuffle Time.[n][e]

[msg Item_079]
[uf 0 5 65278][uf 2 1]The Strength card will appear during Shuffle Time.[n][e]

[msg Item_07A]
[uf 0 5 65278][uf 2 1]The Hanged Man card will appear during Shuffle Time.[n][e]

[msg Item_07B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_07C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_07D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_07E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_07F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_080]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_081]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_082]
[uf 0 5 65278][uf 2 1]The Temperance card will appear during Shuffle Time.[n][e]

[msg Item_083]
[uf 0 5 65278][uf 2 1]The Devil card will appear during Shuffle Time.[n][e]

[msg Item_084]
[uf 0 5 65278][uf 2 1]The Tower card will appear during Shuffle Time.[n][e]

[msg Item_085]
[uf 0 5 65278][uf 2 1]The Star card will appear during Shuffle Time.[n][e]

[msg Item_086]
[uf 0 5 65278][uf 2 1]The Moon card will appear during Shuffle Time.[n][e]

[msg Item_087]
[uf 0 5 65278][uf 2 1]The Sun card will appear during Shuffle Time.[n][e]

[msg Item_088]
[uf 0 5 65278][uf 2 1]The Judgement card will appear during Shuffle Time.[n][e]

[msg Item_089]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08C]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_08D]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_08E]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_08F]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_090]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_091]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_092]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_093]
[uf 0 5 65278][uf 2 1]The number of Major Arcana cards attainable in 1 day increases by 1.[n][e]

[msg Item_094]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_095]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_096]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_097]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_098]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_099]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_09F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A0]
[uf 0 5 65278][uf 2 1]Brand-name, black-[n]rimmed glasses that give off an air of intelligence.[n][e]

[msg Item_0A1]
[uf 0 5 65278][uf 2 1]A headband with cat ears that can make anybody cute.[n][e]

[msg Item_0A2]
[uf 0 5 65278][uf 2 1]Silly glasses with a fake nose attached that are sure to get a laugh.[n][e]

[msg Item_0A3]
[uf 0 5 65278][uf 2 1]A pointed, red hat that feels like Christmas. For Santas in training.[n][e]

[msg Item_0A4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0BF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0CF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0D9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0E9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0ED]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0EF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0FF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

