[msg MSG_000_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]You dipshits better watch yourselves. If we see your face around here too often, someone's gonna get hurt.[n][uf 1 1][e]

[msg MSG_001_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]When you have that apathy thing, it's like you're too lazy to do anything, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]So what's the matter with them that they can't see a doctor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I mean, I ain't never been to med school, but it's gotta be worth a try.[n][uf 1 1][e]

[msg MSG_002_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I guess it's all right to come here in your uniform if it's, like, after school or durin' the day.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But at night? You've gotta be shittin' me![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Dude's gonna get knocked flat for dressing like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Y'might say it's in violation of our whaddayacallit, dress code. You better look out, too.[n][uf 1 1][e]

[msg MSG_003_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I heard people sayin' that dude is stronger than he looks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]He's a loner. His clothes are kinda old, but he's cool.[n][uf 1 1][e]

[msg MSG_004_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But man... Why would some Gekkou candy asses come here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Students should stay at home and do their homework or whatever.[n][uf 1 1][e]

[msg MSG_005_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I couldn't give a crap about 'em.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Long as they don't start any shit, they're cool with me.[n][uf 1 1][e]

[msg MSG_006_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]The whole reason I hang out here is to shoot the shit with my buds.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Those three weirdos are the only ones who come here to try to learn stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]They need to get a life...[n][uf 1 1][e]

[msg MSG_007_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I thought that guy was a total loner... But he knows those weirdos?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Eh, like it matters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I don't give two shits 'bout who's friends with who.[n][uf 1 1][e]

[msg MSG_008_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Those assholes are just using us to gather info.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]They think we're some handy-dandy tool that'll give 'em the scoop any time they ask.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]There's somethin' wrong with those guys.[n][uf 1 1][e]

[msg MSG_009_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I can't even imagine what they do with themselves all day. Can you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Especially that long-haired freak. I think he, like, doesn't need anything but air to survive.[n][uf 1 1][e]

[msg MSG_010_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Even though there's just two of 'em now, they're still nuts.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Especially that long-haired freak! Guy pisses me the hell off.[n][uf 1 1][e]

[msg MSG_011_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I ain't crazy about goin' under the needle, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But you know how it is... I gotta have one, or else I'm chicken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]So what I did was I got this sticker that looks just like a tat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]You tell anyone and I'll beat your ass, got it?[n][uf 1 1][e]

[msg MSG_012_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Yo, this had NOTHIN' to do with us. Got it? We weren't even here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I know how it looks to guys like you on the outside...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But I don't give a shit about people if they just stay out of our faces.[n][uf 1 1][e]

[msg MSG_013_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Huh... I wonder what's in that case of his.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]He looks like the calmest dude out of the three of 'em. Don't ya think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Maybe he's more normal than I'm givin' him credit for.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Yeah... There probably ain't anything to worry about in his case.[n][uf 1 1][e]

[msg MSG_014_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]What was up with those guys?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]They come in, act like a buncha weirdos, and disappear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I don't get it.[n][uf 1 1][e]

[msg MSG_015_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Yeah, dude, it's all about self-confidence.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But we don't gotta worry about them anymore. They're long gone, dude.[n][uf 1 1][e]

[msg MSG_016_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Yeah, I know what he means... You can't go anywhere these days without seeing those weird flyers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]What's up with that shit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]It doesn't look like any rival gang sign I know, but...[n][uf 1 1][e]

[msg MSG_017_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Some guys like to plan this stuff in advance... I don't even own a calendar, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]When we wanna do something, we do it. That's our holiday.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]You gotta be free, dude.[n][uf 1 1][e]

[msg MSG_018_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]It's fine if they wanna say, "Those who believe will be saved." Whatever.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]It bugs me, but at least I get what they're sayin'.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But that weird sign they leave all over the damn place is different. It doesn't make any sense.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Creeps me out... Shit...[n][uf 1 1][e]

[msg MSG_019_0_0 [Languid Delinquent]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]I saw that dude so often, I just thought of him as "that freak"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]But he's some kinda savior?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]And he's got a whole cult behind him!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 426]Shit, dude... What the hell is everyone's problem?[n][uf 1 1][e]

