[msg MSG_000_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you swirl seafood ramen around six times clockwise and six times the other way without spilling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you do that with Hagakure's ramen, I heard you'll end up with the person you like![n][uf 1 1][e]

[msg MSG_001_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you drink a whole bowl of Hagakure's soup, you can see the word "WIN" at the bottom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you trace those letters with your chopsticks, I hear it makes you stronger in fights![n][uf 1 1][e]

[msg MSG_002_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]At Hagakure, try ordering cold ramen by saying "cobra men" to the waiter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If he understands what you said, I heard you won't get heatstroke.[n][uf 1 1][e]

[msg MSG_003_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Order ice cream at the sweets shop and eat it without stopping, even if you get a brain freeze.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you do that three times in a row... you'll get a stomachache. I mean, duh...[n][uf 1 1][e]

[msg MSG_004_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]When you order a pork cutlet set and there's cabbage on top...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Write a dollar sign on top of it, and I hear your allowance will increase![n][uf 1 1][e]

[msg MSG_005_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]When you order a medium beef bowl, order a raw egg with it and drop it onto the beef bowl.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you can get the egg in the middle of the bowl, I heard you'll become more popular in school.[n][uf 1 1][e]

[msg MSG_006_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Order the large fries at Wilduck Burger and make a "W" out of four of them, or an "M" if you're a girl.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Think of the one you love and eat the fries. Then you can't fail![n][uf 1 1][e]

[msg MSG_007_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Those people who just stare at you frighten me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]But it's okay! I'll order the chili garlic fries and make a cross! It drives them away... or so I hear.[n][uf 1 1][e]

[msg MSG_008_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]I heard when you buy takoyaki from Octopia and share it with your loved one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You'll break up. So, how's your relationship going?[n][uf 1 1][e]

[msg MSG_009_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]If you do something bad to the sweets shop's mascot, Azuki-chan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You'll lose control of your bladder! She might be cute, but don't think you can deface her![n][uf 1 1][e]

[msg MSG_010_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You only get the special miso soup if you order the fried shrimp set.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]I hear that sometimes, you'll find a real pearl in that soup![n][uf 1 1][e]

[msg MSG_011_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]I heard if you eat a bowl of ramen without setting it on the table...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]You'll be a master thing-holder. But it must be tough, since it's so heavy and hot...[n][uf 1 1][e]

[msg MSG_012_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]My mom is saying all this weird stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Something about the End, or the Salvation, or something...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]I don't understand adults.[n][uf 1 1][e]

[msg MSG_013_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]Now my dad says all that weird stuff, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]He's right there with my mom, saying the end is coming...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]I don't wanna go home...[n][uf 1 1][e]

[msg MSG_014_0_0 [Rumor-Loving Girl]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]My mom and dad keep saying this weird phrase...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]"Believe in Nyx-sama and be saved!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 411]But... who's Nyx-sama?[n][uf 1 1][e]

