[msg MSG_000_0_0 [Frowning Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]There's a bar by the gang spot with the best cocktails around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]But now they're looking into making non-alcoholic cocktails.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]It used to be a bar where adults could drink in peace... Now it'll be swarming with kids.[n][uf 1 1][e]

[msg MSG_001_0_0 [Frowning Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]There's a mahjong parlor by the gang spot, and one of the guys there is a mahjong demon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]He said, "Let me test my luck," and challenged me to a game.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]I came pretty close, man...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 423]If I'd gotten the Peacock, I could've beat him...[n][uf 1 1][e]

