[msg MSG_000_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]...Hey, you there. This may seem sudden, but do you want to be Santa?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Santa?[e]
[uf 0 5 65278][uf 2 1]What do you mean?[e]

[msg MSG_002_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Well, just between you and me... I'm THE Santa who makes kids' wishes come true on Christmas![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]...Well, you can't really tell when I'm dressed like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]I'm actually looking for someone to help me with my merry duties right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]It's a special job, but we're always short on staff... What do you say? Want to give it a try?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'll do it.[e]
[uf 0 5 65278][uf 2 1]No thanks.[e]

[msg MSG_004_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Great! Let's get on with it. ...But first, one question for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Can you show me proof that you've done something good for the world?[n][uf 1 1][e]

[msg MSG_005_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]I see... If you ever change your mind, you know where to find me.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Something good I've done for the world...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If I rescue someone from[n]somewhere dangerous, maybe[n]he'll acknowledge my deed...[n][uf 1 1][e]

[msg MSG_007_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Well then, I'll be waiting.[n][uf 1 1][e]

[msg MSG_008_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]I'm actually looking for someone to help me with my merry duties right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]It's a special job, but we're always short on staff... What do you say? Want to give it a try?[n][uf 1 1][e]

[msg MSG_009_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Can you show me proof that you've done something good for the world?[n][uf 1 1][e]

[msg MSG_010_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Hm? Is there something you want to show me?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I showed the person claiming[n]to be Santa a thank-you letter.[n][uf 1 1][e]

[msg MSG_012_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]I see... So you rescued a missing person...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Putting yourself on the line to help others is not something everyone can do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Fantastic... You pass the test! Here, take this.[n][uf 1 1][e]

[msg MSG_013_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Congratulations, you're now a certified Santa! Apprentices only get the hat, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]So, right off the bat, here's your first task: deliver this to someone who needs it.[n][uf 1 1][e]

[msg MSG_014_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]This year's work is pretty much taken care of already. You can start working hard for next year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 436]Well, I'll see you when the time comes. Merry Christmas![n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Come to think of it, I received a thank-you[n]letter from a missing person I rescued...[n][uf 1 1][e]

[msg MSG_016_0_0 [Eccentric Man]]
[uf 0 5 65278][uf 2 1]Hm? Is there something you want to show me?[n][uf 1 1][e]

