[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10863 0 0]This is the only place I could think of where I wouldn't have to use the stairs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]But maybe I shouldn't have come here in my track suit, heheh...[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]Ever since everyone found out about my knee, they've been giving me a hand with things. It's nice and all, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]I've been getting less and less practice in. These days, I can barely even walk...[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Can I ask you something? And just give it to me straight...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10872 0 0]With everything that's happening to me right now... do you really think I can still win the regionals next year?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]It's all mental strength.[e]
[uf 0 5 65278][uf 2 1]It's all up to you.[e]
[uf 0 5 65278][uf 2 1]Sounds impossible.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10828 0 0]Stop joking around. I'm being serious here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 4 23 0 105 3 25 25]I thought I told you to give it to me straight... C'mon, man.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto has gone silent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10822 0 0][uf 5 13 8 15 105]Yeah... You're right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 4 23 0 105 3 25 25]I know I talked big on toughin' it out... But it ain't that simple this time.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto is deep in thought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 3 0 65535 10822 0 0][uf 5 13 8 30 105]...Yeah, figures. That's the logical answer. Becoming the national champion's no walk in the park.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 4 23 0 105 1 25 25]Thanks for being honest though. I'm glad we had this talk.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto looks grateful.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]I'm gonna rest here for a little while so I don't strain my knee. You can head out without me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10831 0 0][uf 4 23 0 105 1 25 25]I'll cover the check. Thanks for today, [uf 4 1].[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I parted with Miyamoto and[n]headed back to the dorm.[n][uf 1 1][e]

