[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh man, this is awesome! We're like a super elite task force![n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 0][uf 3 1 1 0 0 2 0 0]C'mon, could you at least wear it like you're supposed to?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 2 0 25 25]Oh, but it does look like everyone's outfits are a bit different.[n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 4 0 0]Each one is made to complement our physiques and fighting styles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 4 1 25 25]They were testing the prototype out on me, but it feels even better than it did before.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 6 0 0]It's very light and sturdy. I wonder if it's the same materials they use in the military, or maybe even the ones for spacesuits.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 7 0 0]Seems like this armband isn't just for decoration either.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 8 0 0]According to the manual, there are a bunch of different features built into it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 9 0 0]For example, it can give you a readout of your vitals. What else...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 52 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 6 4 25 25]There's also a function that notifies you when you can use your Theurgy...?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]How do you use it?[e]
[uf 0 5 65278][uf 2 1]What does that do?[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 11 0 0]Sorry, it doesn't look like there's much information about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 52 65535 0 0][uf 3 1 1 0 0 12 0 0]All I can tell is that you load the cartridge into your Evoker to use it.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 13 0 0]Then let's make that our objective for today. Make sure to stay alert, everyone.[n][uf 1 1][e]

[msg MSG_008_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 14 0 0]All right, Yamagishi, you're going to be our backup, just like I mentioned before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 5 0 25 25]This time, I'll be joining the rest of you in battle.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 52 65535 0 0][uf 3 1 1 0 0 16 0 0]I'm going too. I gotta make sure my skills are still sharp.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 17 0 0]M-Me too![n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 18 0 0]All right, then including [uf 4 1], that will be our team.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 19 0 0]Wait, I wanna go too![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 20 0 0]I was so ready for this! You can't just put me on standby![n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 21 0 0]We can't go without [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 22 0 0]You stay here and support Yamagishi.[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Only you can do it, Junpei.[e]
[uf 0 5 65278][uf 2 1]You're our last line of defense.[e]
[uf 0 5 65278][uf 2 1]Gotta keep our ace in reserve.[e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 23 0 0]Oh, really?[n][uf 1 1][e]

[msg MSG_015_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 52 65535 0 0][uf 3 1 1 0 0 24 0 0]When you put it that way, how can I refuse? Don't worry, Fuuka. Nothing's getting past me![n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 52 65535 0 0][uf 3 1 1 0 0 25 0 0]Uh, okay...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 52 65535 0 1][uf 3 1 1 0 0 26 0 0]There he goes again.[n][uf 1 1][e]

[msg MSG_017_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 52 65535 0 0][uf 3 1 1 0 0 27 0 0]Fuuka, if it gets too dangerous, just leave him behind. And don't be afraid to smack him if he tries anything funny.[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 28 0 0]Okay, got it.[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 52 65535 0 0][uf 3 1 1 0 0 29 0 0]Huh? You get it!?[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 52 65535 0 0][uf 3 1 1 0 0 30 0 0]Yamagishi, could you scout the area and find a good floor for us to start on?[n][uf 1 1][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 65535 0 0][uf 3 1 1 0 0 31 0 0]Okay.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 50 0 0][uf 3 1 0 0 0 32 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 31 52 50 0 0][uf 3 1 1 0 0 33 0 0]It seems... different in here from before?[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 52 65535 0 0][uf 3 1 1 0 0 34 0 0]Well, that's nothing new, right?[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 35 0 0]No, not like that. It seems distorted... It's probably just temporary.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 52 50 0 0][uf 3 1 1 0 0 36 0 0]I'll try and find a stable floor for us to start on.[n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 52 65535 0 0][uf 3 1 1 0 0 37 0 0]You can tell that much already? Wow, Fuuka![n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 38 0 0]It could be because we didn't enter the usual way last time, or because of those huge Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 52 65535 0 0][uf 3 1 1 0 0 39 0 0]We have no idea what's gonna happen in here. Not that I'm complaining though.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 52 65535 0 0][uf 3 1 1 0 0 40 0 0]All right, let's go.[n][uf 1 1][e]

